### ISSUE TITLE
Implement rich media embeds for WYSIWYG

### ISSUE THREAD

**Issue by adamdelaney** [uiowa/uiowa#101]
### URL Embed
I've have tested out the url_embed module. This works well for quickly embedding rich media into the WYSIWYG. It creates an embed button that can be implemented via your text_format. This module does not create file/media entities and does not look like it will work within an entity browser, see: https://www.drupal.org/project/url_embed/issues/2956125. 

### Media embeds
The other option is to add additional projects to support remote assets such as video and audio. I found a core issue that relates to  video/oembed and core media handling, see: https://www.drupal.org/project/drupal/issues/2831944, which looks like they are working on adding a remote video plugin for core 8.6 release. Also see: https://www.drupal.org/project/media_entity for a list of media providers. Here looks like some useful ones:

- https://www.drupal.org/project/video_embed_field
- https://www.drupal.org/project/media_entity_twitter
- https://www.drupal.org/project/media_entity_instagram
- https://www.drupal.org/project/media_entity_soundcloud
- https://www.drupal.org/project/media_entity_facebook
- https://www.drupal.org/project/media_entity_flickr

**Comment by joewhitsitt** [comment]
Extending the remote video implementation, I suggest we move forward with the media entity approach which is also how Lightning has handled this.

**Comment by joewhitsitt** [comment]
Remote Video has been implemented. Kalutra is going to be a high-priority soon #254 

I suggest everything else be implemented the media_entity method.

**Comment by richardbporter** [comment]
D7 SiteNow has the ability to use oEmbed for certain providers. It also has custom Facebook and Twitter content panes.

**Comment by joewhitsitt** [comment]
We need to test the following contrib modules in terms of feature parity to see if their integration with media core is working.

These two note that the 2.x version is supposed to work with Media core:
https://www.drupal.org/project/media_entity_twitter
https://www.drupal.org/project/media_entity_instagram

There is a 2.x stable, but no note on the project page about media core support.
https://www.drupal.org/project/media_entity_soundcloud

**Comment by joewhitsitt** [comment]
Closing in favor of #393
