### ISSUE TITLE
Should we use focal point scale and crop for our custom image styles used in our media entity embed button?

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#103]
Currently we have focal point enabled when embedding images but none of our image styles that are being rendered through our custom view modes use the focal point scale and crop.

**Comment by briand44** [comment]
I think this issue should remain open. @adamdelaney is basically saying the exact same thing I stated in my first comment and actually strengthens my argument that there is an issue. "Focal point does not make sense to use", but we are currently using it. I will try explaining this issue better.

When uploading images through the WYSIWYG, users currently have the ability to set a focal point but none of the view modes available render image styles that use a focal point scale and crop. I believe this is confusing and a usability issue. I am recommending:

- Create new or update existing image styles to use focal point scale and crop
- Remove the ability to set a focal point when uploading through the WYSIWYG
- Leave this how it is for now, assuming once more functionality is built out there will be additional view modes that are available that will render image styles that are using focal point scale and crop.

**Comment by joewhitsitt** [comment]
For now focal point is what has been implemented for section, card, featured news image. We can revisit cropping another time.
