### ISSUE TITLE
Consider devel_a11y for local split

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#1060]
I finally dipped my toe in the aria live announce functionality built in to core and it is pretty awesome. To make testing easier they recommend enabling devel_a11y which will mimic JAWS for announcements and visually indicate tab accessible elements

https://www.drupal.org/project/devel_a11y

I haven't tried it yet, so I don't know if it is "always on" or if it is ready and waiting for you to activate for a certain node.

**Comment by richardbporter** [comment]
If we can use SI locally (#1791), do you think we still need this?

**Comment by joewhitsitt** [comment]
SI is a huge improvement since we are able to use the browser extension to test the same metric locally on a page by page basis. The SI module problem extends that.

I haven't tried devel_a11y but I am wondering how it could aid developers further as it relates to JAWS announcements, etc.

I would like to take the time to enable the module to see what it is about before closing this issue.

**Comment by joewhitsitt** [comment]
Closing this. I've added it to see announcements easier when developing some ajax callbacks. I don't think it needs to be part of our default local toolkit every time we sync.
