### ISSUE TITLE
Some scss files are not getting built in dev

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#1061]
Example: https://uiowa.dev.drupal.uiowa.edu/themes/custom/uids_base/assets/css/components/global/menus/off-canvas/off-canvas.css

I ran `blt artifact:deploy --dry-run` locally to see if it was showing up in the deployment package and the file gets built locally.

However, when @bspeare was testing #1043, we noticed the same problem on his local machine even after running `blt frontend` and `yarn workspace uids_base build`.

The .scss file that generates the file listed above exists in the develop branch: https://github.com/uiowa/uiowa/blob/develop/docroot/themes/custom/uids_base/scss/components/global/menus/off-canvas/off-canvas.scss. I also confirmed that the .scss file exists in the correct location in dev on uiowa01.

**Comment by pyrello** [comment]
@richardbporter I double-checked the top-level .gitignore file and didn't see anything that would be causing this to happen. Also the fact that it works for me locally is weird. Maybe you could try pulling that feature branch and see if the asset builds locally for you?

@bspeare Can you check to see if that css file exists in your local instance?

**Comment by bspeare** [comment]
@pyrello I commented out line 3 of scss/components/global/menus/mega-menus.scss and `blt frontend` worked fine and the site looks a lot better now.   That file doesn't exist yet in uids.

**Comment by richardbporter** [comment]
For some reason, Gulp does not return a non-zero exit code when tasks fail. If it did, Travis would fail and we'd catch these issues.

**Comment by richardbporter** [comment]
What is the fix for this? Just comment it out?

**Comment by pyrello** [comment]
Yeah, just comment it out.
