### ISSUE TITLE
Browser issues/errors on Chrome 65 with WYSIWYG

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#107]
BrowserStack, Mac OS Sierra Chrome 65
- If I embed a file into the content area I can't type or advance the cursor from the file focus.  Tabbing or arrow keys will not help either.   If I paste some text into the editor it pastes over the embedded file link.

BrowserStack, Mac OS El Capitan Chrome 65
- Same issue with text focus.  Sometimes if I try to reopen the file entity link the "Embed" button will not close the window and I will get the console errors in the attached screenshot. 

Probably not a blocker, but it seems pretty buggy on some browsers. 

![screen shot 2018-04-30 at 10 01 07 am](https://user-images.githubusercontent.com/1036433/39434387-14d3c658-4c5e-11e8-8945-8fd32ea869be.png)

The JavaScript error is similar to https://www.drupal.org/project/entity_embed/issues/2544020, https://www.drupal.org/project/entity_embed/issues/2534092

**Comment by richardbporter** [comment]
I don't _think_ this is a bug anymore since links to files are handled through LinkIt. I'm not able to replicate this. Closing for now but feel free to reopen if I'm mistaken.
