### ISSUE TITLE
Update Manager shut off by default in collegiate profile

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#1086]
Configure the collegiate profile to not install update manager by default.

**Comment by pyrello** [comment]
@richardbporter I'm not sure if you know anything about this, but I don't see that update manager is one of the modules we are enabling with collegiate, so I'm not sure how it ends up enabled after a site install.

**Comment by joewhitsitt** [comment]
Is this still an issue @briand44, @pyrello?

**Comment by pyrello** [comment]
Good question. I would think not, since the collegiate profile is no more and the collegiate split that replaced it doesn't have any impact on the underlying update manager settings.

**Comment by briand44** [comment]
I haven't been seeing the emails coming through any more so as far as I am concerned this could be closed.
