### ISSUE TITLE
Instructions for managing configuration for uiowa.edu

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#1092]
# I want to change config
* You will be making the changes on your local instance: https://uiowa.local.drupal.uiowa.edu
* If you haven't yet, make sure your master branch is up-to-date and create a feature branch
  ```
  git checkout master
  git pull
  git checkout -b feature_my_feature_branch
  ```
* Make sure that `uiowa.edu` is included in your local.blt.yml multisites list.
* Run `blt dsa` or `blt ds --site=uiowa.edu`. This will make sure that your site is up-to-date with changes in the remote site.
* Make any changes via the admin UI or drush.
* Run `drush @home.local cst` to see a list of config changes. This is a sanity check that allows you to investigate any config changes that may be showing up that you didn't expect.
* If you are happy with the changes, run `drush @home.local cex'.
* Commit the changes to your feature branch. If you are done working on your feature branch, push it to Github and open a PR so that it can be reviewed by another developer.

## Pre-launch
* Check out the `develop` branch and `git pull` to make sure it is up-to-date.
* Merge your feature branch into `develop`: `git merge --no-ff feature_my_feature_branch`
* Travis CI will build and deploy `develop` (assuming there are no build errors) to the dev environment on Acquia Cloud.

### Until we get automated config inports for uiowa.edu working
* Double check your work: `drush @home.dev cst`.
* Import config changes in dev: `drush @home.dev cim`.

## Post-launch
* Your PR gets merged, a release is created, and eventually deployed to production.
* I'm assuming by this point, automated config imports for uiowa.edu will be working.

**Comment by pyrello** [comment]
@bspeare I'm not sure where to put this, but in the meantime, you can reference it here.

**Comment by richardbporter** [comment]
I moved this to the wiki: https://wiki.uiowa.edu/display/drupaldev/Example+Config+Workflow. I'm going to close for now but it is still available for reference by searching closed issues. Another good reference is the config README files: https://github.com/uiowa/uiowa/blob/main/config/README.md and https://github.com/uiowa/uiowa/blob/main/config/features/README.md
