### ISSUE TITLE
Implement revision clean-up with custom or contrib module

### ISSUE THREAD

**Issue by genjohnson** [uiowa/uiowa#110]
There are issues in D7 with nodes that have "too many" revisions, and so we've been using node_revision_delete to clean-up old revisions automatically. We anticipate that there will be similar issues with D8 sites which have "too many" revisions for an entity.

We should investigate possible solutions for cleaning up revisions in D8, either by number of revisions or by time since the revision was created.

**Comment by adamdelaney** [comment]
## Projects
- [Node revisions autoclean](https://www.drupal.org/project/node_revisions_autoclean)
- [Node Revision Delete](https://www.drupal.org/project/node_revision_delete)

**Comment by joewhitsitt** [comment]
Waiting on core/contrib.

**Comment by joewhitsitt** [comment]
Related: https://www.drupal.org/project/drupal/issues/3043321 (generic revisions api)

Also, I _think_ I saw something in the config page while testing 8.8 that there is a delete orphaned revisions that has paragraphs.

**Comment by joewhitsitt** [comment]
Here it is. I am seeing this on 8.7. Looks extremely dangerous. There is no confirmation step and no additional details about what gets purged, only how many.

<img width="995" alt="Screen Shot 2019-11-14 at 11 31 52 AM" src="https://user-images.githubusercontent.com/4663676/68881536-e4d0a800-06d2-11ea-8c76-99c988d988e7.png">

**Comment by richardbporter** [comment]
https://www.drupal.org/project/node_revision_delete/releases/8.x-1.0-beta3

**Comment by joewhitsitt** [comment]
https://www.drupal.org/project/node_revision_delete/issues/3094354
