### ISSUE TITLE
Transition path for collegiate profile and sites

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#1148]
Just starting to put down some notes for when it comes time to figure this out.

This seems to be a code snippet for changing an existing site's profile:
https://www.drupal.org/node/2538996#comment-12658458

Idea for implementing an automated workflow for creating additional sites in the vein of uiowa.edu:
1. Add project.config_splits key to site's blt.yml, which is an array of config split's that should be applied to the site upon site install.
2. After running automated site-install, check for presence of this key.
3. Loop through splits and run partial import command to register the split in the environment the site is being installed in.
    `drush @site.env config:import --source ../config/feature_split --partial`

**Comment by richardbporter** [comment]
I believe all collegiate sites have been transitioned.
