### ISSUE TITLE
Add page number to default page title metatag.

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#115]
This is a good practice so Google doesn't count multiple pages as duplicate content. Currently this token has not been ported to D8. https://www.drupal.org/project/metatag/issues/2926852

**Comment by joewhitsitt** [comment]
Removing blocked. We should at least chime in on the issue or investigate whether or not the latest comment meets our MVP needs.

**Comment by richardbporter** [comment]
We can minimize the SEO issue by utilizing AJAX pagers whenever possible. In fact, the only use case we have for this right now is with articles and that view is already configured to use AJAX. It does not seem to be working, however.
