### ISSUE TITLE
Allow for classes to be added to the filtered and full HTML formats

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#1159]
# The Problem

- Editors building the new home page design need access to add classes to html elements such as p, h2, h3, h4, h5, h5, ul, ol, table, etc. 
- There are currently workarounds in place to use a `<div>` or a `<span>` on an element, but that doesn't work for a list-item like https://uiowa.github.io/uids/components/detail/lists.html or if you want to preserve the HTML document outline by adding classes to heading tags. 

# Proposed Solution

Allow classes to be added to HTML tags in the filtered HTML format.

**Comment by bspeare** [comment]
It looks like even the full HTML format strips out classes or doesn't allow for multiple classes.   Try adding multiple classes to the "How to apply" text on https://uiowa.stage.drupal.uiowa.edu/admissions/undergraduate-admissions.

**Comment by joewhitsitt** [comment]
SiteNow's full_html doesn't limit. There might be something else going on.

In the example, I see `bold-header` and `uids-component--circle-list` in the markup. I don't see styles related to `bold-header` appear in the inspector though.

filtered_html allows classes currently on the following:
```
<a> <blockquote> <h2> <h3> <h4> <h5> <h6> <p class="text-align-*"> <div> <span> <table> <tbody> <thead> <tfoot> <th> <td> <tr>
```

So adding `<ul> <ol>` and expanding `<p>` would cover the use-cases?

**Comment by bspeare** [comment]
I think that should cover the use cases.    You are right that something else is going on.  Something is blocking the text area from being updated after initially being created.  I will make a separate issue for that.
