### ISSUE TITLE
Use Entity Embed for inline links to files

### ISSUE THREAD

**Issue by genjohnson** [uiowa/uiowa#116]
As a follow up to issue #49, it may be nice to use Entity Embed to insert inline links to files in the WYSIWYG, as this would be consistent with our currently D7 implementation with all media handled through the same WYSIWYG button.

However, this will not be possible until Entity Embed supports inline elements (https://www.drupal.org/project/entity_embed/issues/2640398).

**Comment by joewhitsitt** [comment]
Based on the progress of this issue and the plan to adopt media library core #865, closing.
