### ISSUE TITLE
Create internal (secondary) navigation component/block

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#1160]
Apply uids styles for internal navigation to the menu block for displaying secondary navigation while providing different options for menu display:
- https://uiowa.github.io/uids/components/detail/main-menu--main-menu-secondary-horizontal.html
- https://uiowa.github.io/uids/components/detail/main-menu--main-menu-secondary-vertical.html

What makes this different than other components that we are building as blocks is that this is an existing block and we need to allow additional options to determine which way it will display.

Should the setting about whether to display the block as horizontal or vertical be set at the block level? In this scenario, it would be incumbent upon the developer to add the same block with the same configuration to every page that shared the navigation. Or should it be a theme-level setting? In which case any secondary (internal) navigation would use the same style.

I'd welcome any feedback that folks have about how this should work.

**Comment by pyrello** [comment]
After giving this some consideration, I think I'm leaning towards the idea of making this a theme-level setting that applies to all menus placed within layout builder.

**Comment by bspeare** [comment]
What makes you lean towards the theme level?   Once scenario worth considering is if an academic site with a sidebar navigation wants to create a landing page for a conference with a horizontal navigation.

**Comment by pyrello** [comment]
@bspeare That is an important consideration and I do ultimately think that the system should be flexible enough to accommodate these types of situations. I was leaning towards the theme-level setting because the process of reproducing the menu settings across many internal pages would seem to invite a greater possibility of the menu being inconsistently implemented when that was not the intention.

Maybe this needs to kind of like the page container? There is a theme-level setting that sets the default behavior, but then it can still be set at the block level if a different design is needed?

Alternately, a developer could create an override for a landing page menu using a sub-theme and custom CSS.

**Comment by bspeare** [comment]
The theme-level setting that sets the default behavior but could be overridden at the block level sounds ideal.  I guess It depends on how much work it will take.

**Comment by pyrello** [comment]
So, I'll build it out using a style setting added to the block in layout builder. If there is time, or eventually, it can also use a theme-level setting to help with consistency.

**Comment by pyrello** [comment]
@bspeare, @joewhitsitt, @mark-bennett-uiowa, @richardbporter 

In talking about the implementation of this with Ben, I am wondering what all of your thoughts are about the idea of adding a secondary navigation block underneath the page title and breadcrumbs in the default page LB template? This would allow us to set the default settings for the menu block to function in a consistent way without a lot of a per-page configuration necessary by the developer.

Here is the default setting that I am imagining: It shows peer-level pages to the current page, if the current page is second-level deep in the navigation structure. It only shows a depth of one.

Thoughts?

**Comment by richardbporter** [comment]
If I'm understanding correctly, I'm fine with this approach. It seems similar to what we already do in sitenow but in a sidebar: https://github.com/uiowa/uiowa/blob/master/docroot/profiles/custom/sitenow/config/sync/block.block.sidebar_mainnavigation.yml

Is #967 related to this?

**Comment by joewhitsitt** [comment]
So in layout this can be dragged around and placed elsewhere and that underneath title and breadcrumbs it is just the default?

SiteNow side bar menu only shows active children, not peers/siblings and currently displays at the top on mobile... which I have been wanting to change to bottom via flex/grid order to keep long menus vertical menus from increasing the scroll to get to the content.

**Comment by pyrello** [comment]
@richardbporter This was specifically about #967, but it would potentially be a standard way of handling secondary menus in a standard way.

@joewhitsitt Currently, there is no mechanism to prevent people who have access to edit the layout of the page - which would include content editors - from moving these elements around. We have talked about introducing some kind of lock mechanism for a certain section, or for certain elements that are set in a template.

I think that my ideal for an internal section menu is that it behaves similarly to the main navigation. If it is normally side-by-side links in a desktop view, those collapse into a stack with a toggle to expand or hide them.

I guess I had also considered a similar component for on-page navigation (to anchor links), so I think there would need to be some way to differentiate those.

I was working on building an example of using a custom block type as a sort-of wrapper around the navigation component, which would be placed on the block via its own LB template. That would allow us to embed all the settings of the navigation block into config. The downside is that LB doesn't show nested items, so it doesn't even have a "Placeholder for {field}..." label on it and just looks like a blank space.

This approach is meant as an alternative to adding this element as a default to the page layout template or the overly burdensome process of having to place and configure the menu block itself on every page that needs it. I might be able to programmatically add a "Placeholder for..." preview for that block type. If not, then I'm not sure that this approach is a good way to handle it, since having the blank space is confusing and likely to lead to human errors.
