### ISSUE TITLE
Regression: Admin toolbar overlapping tab logo when displayed veritically

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#1178]
<img width="1667" alt="Screen Shot 2020-03-12 at 11 47 32 AM" src="https://user-images.githubusercontent.com/709009/76545266-7836a180-6457-11ea-9e78-0c4b80a9dfe6.png">

This is new behavior, since we had the header working with the toolbar menu previously.

**Comment by bspeare** [comment]
I'll just add `header {padding-left: 15rem;}` to admin.scss when I work on #1158.
