### ISSUE TITLE
Add Colorbox to frontend build process

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#1200]
## Problem
As raised in https://github.com/uiowa/uiowa/pull/1177, the colorbox implementation could be cleaned up.

Since the current implementation is a patched, library overridden version, style/js hybrid of Colorbox, I am not sure to what extent this can be done.

**Comment by richardbporter** [comment]
Probably the same as the easysvg package - fork and require.

**Comment by joewhitsitt** [comment]
This refactor would apply to both since they have the assets local.

**Comment by joewhitsitt** [comment]
So, I started to do this in https://github.com/uiowa/uiowa/pull/2521 and have created a fork with patch of the repo https://github.com/joewhitsitt/colorbox, but I am getting a composer error when I try to use it/update the lock file.

`No valid composer.json was found in any branch or tag of git@github.com:joewhitsitt/colorbox, could not load a package from it.`

I revisited because I didn't want to start leaflet off on the wrong foot.

**Comment by joewhitsitt** [comment]
@richardbporter since you helped with my easysvg fork, I was wondering if you knew how to get around this one?

**Comment by richardbporter** [comment]
Yea - I'm curious what exactly was patched with it though as there may be another option. Was it only jackmoore#753 and jackmoore#765?

**Comment by joewhitsitt** [comment]
This is the pull that has everything I think: https://github.com/jackmoore/colorbox/pull/832

**Comment by richardbporter** [comment]
I gave this a shot in https://github.com/uiowa/uiowa/pull/2521/commits/8d26e81d90ab0caf2fbc90525d36d8f935bc1d65. This approach would not require you to fork the repo. That was goofy anyway as this package is not available on Packagist. 

Can you verify this works as expected? Any other thoughts?

Also, it would seem we may want to start thinking about a better supported lightbox solution for the future.

**Comment by joewhitsitt** [comment]
I will give this a shot in a bit. Consumed by another bug on that branch.

**Comment by joewhitsitt** [comment]
I think it worked, unfortunately, I don't think the a11y fixes in that branch are doing everything I want them to now that I am revisiting it...
