### ISSUE TITLE
Update file directory for previously migrated files

### ISSUE THREAD

**Issue by cory-skeers** [uiowa/uiowa#1208]
ap-purchasing.fo.uiowa.edu and horn.studio.uiowa.edu had file migrations prior to the file directory fix (all files placed in ...files/images/ directory). This effects the file URL, particularly a problem with PDFs.

Need to move files in the directory, as well as update the URI in the file_managed database table to maintain integrity of previously attached links to files.

- [x] ap-purchasing.fo.uiowa.edu
- [x] horn.studio.uiowa.edu

**Comment by joewhitsitt** [comment]
Might want to get @richardbporter 's thoughts on this, but instead of establishing a site specific module to run an update hook or pasting/running stuff in SequelPro, I think this could be an update hook within the SiteNow install file that only runs on these two sites.

**Comment by richardbporter** [comment]
That could possibly work. You could check the URI using the RequestStack service. 

https://github.com/uiowa/uiowa/blob/2f46813d7aa66dc4402bab0236eb5553e0edbc87/docroot/profiles/custom/sitenow/src/ConfigOverride/SimpleSitemapOverride.php#L39-L40.

**Comment by cory-skeers** [comment]
My initial thought had been to manually move the files in the directory, followed by `drush sqlc` and `UPDATE file_managed SET uri = REPLACE(uri, 'images/', 'new_path/')`, and sync back up, but was worried about passing over any hooks. Should be able to use the proper Drupal wrappers for a similar approach if it's in an update hook. Thanks!
