### ISSUE TITLE
Webform - Documentation

### ISSUE THREAD

**Issue by genjohnson** [uiowa/uiowa#121]
Document how to manage webforms, including best practices on the types of information (protected data) which should not be collected.

**Comment by joewhitsitt** [comment]
Related to #132

**Comment by joewhitsitt** [comment]
@ethanstjohn took a good step on this. Ethan and another pair of eyes should go over this once more, clean it up for "production" and close this. https://docs.sitenow.uiowa.edu/webforms/

**Comment by joewhitsitt** [comment]
We should also base this docs on any changes made by #355 and the other MVP Webform issues.

**Comment by ethanstjohn** [comment]
I like how the documentation is worded. I believe it is good enough to close the issue. Does anyone else want to take a look at it?

**Comment by joewhitsitt** [comment]
Still just skimming at this point, but I noticed a few things:

- Files should not be .html and should not have spaces.
- I think the Webform doc landing page should have the best practices content followed by an index listing of the interior pages.
- How to create a webform (bottom of page) the "please refer..." is part of the bulleted list. It should have a line return and a link to the advanced docs.
- Advanced should touch on the confirmation settings as with the future #346, this will be used a lot in deciding what to do after submission.

**Comment by ethanstjohn** [comment]
Thank you for reviewing this, Joe! I am going through your ideas and making changes.

**Comment by ethanstjohn** [comment]
Did you think all of the content on https://github.com/uiowa/uiowa/blob/gh-pages/webforms/webform-management/webform-management.md should go on the landing page?

**Comment by ethanstjohn** [comment]
I don't know where the .html files are either. I checked in the uiowa/webforms directory.

**Comment by joewhitsitt** [comment]
Fun fact, github turns nested directory md files into html files...

Just linked a couple things and fixed some markdown formatting.

Great work @ethanstjohn ! I love the conditional example.
