### ISSUE TITLE
Check A-Z List with ScreamingFrog

### ISSUE THREAD

**Issue by mjoneill** [uiowa/uiowa#1218]
@mjoneill

**Comment by mjoneill** [comment]
@ABoston88 apparently I can't upload .csv files to github, so Im going to get you the a-z list scans in slack.

**Comment by joewhitsitt** [comment]
@mjoneill can this be closed?

**Comment by mjoneill** [comment]
This is in Alex's court right now.  @ABoston88, did you get what you needed & can we close?

**Comment by ABoston88** [comment]
Yup. Can close.
