### ISSUE TITLE
[META] UI People

### ISSUE THREAD

**Issue by genjohnson** [uiowa/uiowa#123]
- [ ] Elicit & document requirements for UI People 
- [ ] Implement UI People
- [ ] Provide documentation for content contributors

**Comment by genjohnson** [comment]
@mark-bennett-uiowa has started work on a Person feature which gets information from APR. Should these be the same solution? Should the APR integration be provided in a sub-module or maybe even a completely separate module? 

Just putting the questions here for now...hopefully continued discussion and documentation of requirements will bring clarity to the direction we should go.

**Comment by joewhitsitt** [comment]
we have created and merged in an initial MVP sitenow_person module to relate people (authors) to articles and only consists of first name, last name, email, website.
