### ISSUE TITLE
Integrate UIDS form styles into uids_base

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#1239]
# Problem

The uids_base forms do not pick up uids form styles. 

# Proposed solution

Add `uids-content` class to uids_base form wrappers through `hook_form_alter` or ` theme_preprocess_form`?

**Comment by pyrello** [comment]
Currently, it looks like the class is actually `hds-content`. Do you want me to add it as `uids-content` with the expectation that it will be updated in uiowa/uids before launch?
