### ISSUE TITLE
Add "_blank" target option to external links in menus

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#1245]
Currently, there is no way to have external links open in a new browser tab/window in SiteNow. I think this would be the desired behavior for all the external links on uiowa.edu.

**Comment by joewhitsitt** [comment]
https://www.drupal.org/project/menu_link_attributes

**Comment by pyrello** [comment]
When we discussed this a while back, I think that @mjoneill was indicating that having all external links open in a new page is no longer considered best practice.

**Comment by joewhitsitt** [comment]
This module provides attributes on a case-by-case basis. If that is no longer desired as well, I think this issue can be closed.

**Comment by cory-skeers** [comment]
For reference: https://www.w3.org/WAI/WCAG21/Techniques/general/G200

Generally, they recommend against it unless there is a context and/or security reason for doing so, and to ensure there are indicators prior to the link to being clicked. Looks like the menu_link_attributes would work fine for this, if there are enough use-cases to match the above guidelines.

**Comment by pyrello** [comment]
I'm going to close this for now. If we get requests for this functionality, we revisit this issue.
