### ISSUE TITLE
Move sitenow configuration to default directory

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#1247]
It would be nice if we could move sitenow config to the default directory as outlined in the BLT docs: https://docs.acquia.com/blt/developer/config-split/#default-configuration

Multiple profiles running disparate config syncs works but isn't really supported by BLT. Advantages of this approach:

- Refer to platform configuration as default and not any one profile, i.e. sitenow
- Potentially setup profile splits, although more granular feature splits might be preferable
- Config lives outside docroot
- Potentially use hook_install() in profile(s)
- One less site/database as the default could be used for a demo site.

**Comment by richardbporter** [comment]
Related #1248

**Comment by pyrello** [comment]
@richardbporter I am for this approach, both philosophically and from a code organization standpoint. Its not clear to me yet what the ramifications might be in terms of maintenance, but I don't immediately see anything that would be much different in terms of how we work.
