### ISSUE TITLE
[Story] As a site visitor I can be redirected from old paths to where the content exists now.

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#1249]
- [x] Get current uiowa.edu redirects/match redirects and communicate freeze/double post of redirects going forward
- [x] See if match redirects work in D8
- [x] Use similar HR redirect update hook to import

**Comment by richardbporter** [comment]
Does redirecting via htaccess make this any easier?

**Comment by mark-bennett-uiowa** [comment]
This is a concern we have also moving forward. Our solution is to put htaccess redirects in for individual subdirectory sites to their new subdomain replacement, but not for individual pages. Architecture will change dramatically for our sites, as sites will be redesigned according to a more consistent structure. The sheer number of redirects that would be needed makes this undesired, especially to put these into an htaccess file. If push comes to shove, the Redirect module if we have to add these.

**Comment by joewhitsitt** [comment]
What made this difficult was distractions and some data massaging. This should be good now though it relies on an uncommitted patch. I'll watch the issue and the current homepage for new redirects and match redirects until go-live. I hope there isn't a lot of edits to existing redirects.
