### ISSUE TITLE
Instructions for uploading photos on uiowa.stage.drupal.uiowa.edu

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#1256]
# Preparing the images for upload

1. Resize the width of the image to 2592 pixels (the maximum width of all images on the site is 2592 pixels).
2. Run the image through an image compressor like https://compressor.io/. 
3. Upload the image to https://uiowa.stage.drupal.uiowa.edu/ following the steps listed below. 

# Uploading an image into the square grid format

This image uses a 1:1 aspect ratio. 

1. On the Layout edit screen, click "Configure" on the image block.

<img width="485" alt="Screen Shot 2020-03-25 at 10 30 57 AM" src="https://user-images.githubusercontent.com/1036433/77556190-28f46600-6e86-11ea-820a-4f3877a61ffc.png">

2. In the text editor, click on "Source" and delete the visible source code.  Toggle the "source" button back to the regular editing view and click on the image button in the WYSIWYG.

<img width="290" alt="Screen Shot 2020-03-25 at 10 31 05 AM" src="https://user-images.githubusercontent.com/1036433/77556273-488b8e80-6e86-11ea-8aa9-0e9a777a4725.png">

3. Upload the photo from your computer by clicking on the "Choose file" button.

<img width="1548" alt="Screen Shot 2020-03-25 at 10 51 17 AM" src="https://user-images.githubusercontent.com/1036433/77556761-e8491c80-6e86-11ea-9c7a-768a7aec5587.png">

4. Add Alternative Text to the image (https://webaim.org/techniques/alttext/). 

<img width="1124" alt="Screen Shot 2020-03-25 at 10 52 29 AM" src="https://user-images.githubusercontent.com/1036433/77556841-fdbe4680-6e86-11ea-93a4-e105f507d681.png">

5. Click on the "Save and Select" button. 
6. Then click on the "Insert Selected" button. 

<img width="1602" alt="Screen Shot 2020-03-25 at 10 52 38 AM" src="https://user-images.githubusercontent.com/1036433/77556902-13337080-6e87-11ea-88c5-f43264052f12.png">

7. Next click on the "Edit Media" button above the image in the text editor.  Select "Large Square" and set alignment to "none" and click "Save". 

<img width="1302" alt="Screen Shot 2020-03-25 at 10 52 56 AM" src="https://user-images.githubusercontent.com/1036433/77556981-2cd4b800-6e87-11ea-8a71-bd42a7fa3c6c.png">

8. Click on the "Update" button at the bottom of the text editor block.

<img width="1737" alt="Screen Shot 2020-03-25 at 10 53 11 AM" src="https://user-images.githubusercontent.com/1036433/77557060-4d9d0d80-6e87-11ea-9b9d-53bb97a958e5.png">

9. Then scroll back to the top of the page and click the "Save Layout" button. 

<img width="833" alt="Screen Shot 2020-03-25 at 10 53 18 AM" src="https://user-images.githubusercontent.com/1036433/77557302-9c4aa780-6e87-11ea-88ad-d11de37ad83d.png">

# Uploading an image into a card 

This image field uses a 16:9 aspect ratio. 

1. On the Layout edit screen, click "Configure" on the card block.

<img width="768" alt="Screen Shot 2020-03-25 at 10 57 30 AM" src="https://user-images.githubusercontent.com/1036433/77557374-b1273b00-6e87-11ea-98fd-ba7f03638432.png">

2. Remove the placeholder image. 

<img width="273" alt="Screen Shot 2020-03-25 at 10 57 42 AM" src="https://user-images.githubusercontent.com/1036433/77557402-b8e6df80-6e87-11ea-842f-c1a55690f98c.png">

3. Upload a new image.

<img width="294" alt="Screen Shot 2020-03-25 at 10 57 49 AM" src="https://user-images.githubusercontent.com/1036433/77557433-c0a68400-6e87-11ea-9302-414061afea61.png">

4. Select the new image. 

<img width="294" alt="Screen Shot 2020-03-25 at 10 57 49 AM" src="https://user-images.githubusercontent.com/1036433/77557484-ce5c0980-6e87-11ea-8762-a1c1271c42cf.png">

5. Repeat steps 3-6 from the above instructions. 
6. Save the block by clicking on the "Update" button at the bottom of the block. 
7. Then scroll back to the top of the page and click the "Save Layout" button. 

# Banner Image

This image uses a 21:9 aspect ratio 

1. Follow the similar steps outlined above for the Card image. 

<img width="921" alt="Screen Shot 2020-03-25 at 11 12 39 AM" src="https://user-images.githubusercontent.com/1036433/77559160-d026cc80-6e89-11ea-9014-2cabe488258a.png">

# Page Title Hero Image

This image uses a 21:9 aspect ratio 

1. Follow the similar steps outlined above for the Card image. 

# Event Thumbnail Image

This image uses a 1:1 aspect ratio. 

1. Follow the similar steps outlined above for the Card image. 

# Home page Aerial Photo

This image uses a 16:9 aspect ratio (this image must be updated by a site admin). 

# Updating the Looping video on the home page. 

1.  Edit the existing block on the home page. 

<img width="1783" alt="Screen Shot 2020-03-25 at 11 20 58 AM" src="https://user-images.githubusercontent.com/1036433/77560154-10d31580-6e8b-11ea-8af1-7241a00cc912.png">

2. Remove all of the placeholder files by clicking on the "Remove" buttons for each field. 
3. Upload a placeholder image in the Image field.  This image should be sized and cropped before uploading to 2592 x 1458 pixels (16:9 ratio). 
4. Upload a new mp4 video loop in the video field (size is limited to 32mb). 
5. Save the block by clicking on the "Update" button and scroll to the top and click on the "Save Layout" button. 

# Updating the Vertical Video on the home page

1. Edit the existing block on the page.

<img width="448" alt="Screen Shot 2020-03-25 at 11 16 56 AM" src="https://user-images.githubusercontent.com/1036433/77559502-44fa0680-6e8a-11ea-99ec-deb9ff0695a9.png">

2. Remove all of the placeholder files by clicking on the "Remove" buttons for each field. 

<img width="311" alt="Screen Shot 2020-03-25 at 11 17 13 AM" src="https://user-images.githubusercontent.com/1036433/77559617-622ed500-6e8a-11ea-9b21-e2a6bf26fac5.png">

3. Add a new video mp4 file (size is limited to 32mb). 

<img width="1361" alt="Screen Shot 2020-03-25 at 11 17 33 AM" src="https://user-images.githubusercontent.com/1036433/77559664-6fe45a80-6e8a-11ea-95dc-66a9aa123785.png">

4. Upload a .vtt track file.
5. Upload a placeholder image.  This image must be uploaded cropped as 1200 x 2100 pixels.  
6. Save the block by clicking on the "Update" button and scroll to the top and click on the "Save Layout" button. 

# Adding a YouTube video

1.  Add a text area to a section.

<img width="1326" alt="Screen Shot 2020-03-25 at 11 26 32 AM" src="https://user-images.githubusercontent.com/1036433/77560733-d61dad00-6e8b-11ea-80d4-c47ece0ad0ce.png">

2. Click on the media/image button in the WYSIWYG and click on the "Remote Video" option. 

<img width="277" alt="Screen Shot 2020-03-25 at 11 26 44 AM" src="https://user-images.githubusercontent.com/1036433/77560807-e6ce2300-6e8b-11ea-9f08-5c475938726a.png">

3. Paste video url into the field. 

<img width="737" alt="Screen Shot 2020-03-25 at 11 27 19 AM" src="https://user-images.githubusercontent.com/1036433/77560909-049b8800-6e8c-11ea-827d-2c6c01d23516.png">

4. Click on "Edit media" button in WYSIWYG if you want to change video aspect ratio.  
5. Save the block by clicking on the "Update" button and scroll to the top and click on the "Save Layout" button.

# Adding an icon image for a horizontal card

The horizontal cards at the bottom of https://uiowa.stage.drupal.uiowa.edu/admissions will need icons.  

1.  The icon will need to be manually placed/centered within the 16:9 image ratio that the Card block uses.  Use the image below as an example. 

![IOWA-DRAFT-Icon-Set-Color (1)_art-1](https://user-images.githubusercontent.com/1036433/77564662-15023180-6e91-11ea-9b03-a9f7dfebe0c3.png)

**Comment by bspeare** [comment]
@joewhitsitt Is there a better place to put this?  Maybe I can make an archive of this locally and move it somewhere if it is needed if the v3 documentation doesn't cover some of this.

**Comment by joewhitsitt** [comment]
Does @ABoston88 still reference this? I didn't see it as an actionable issue, and it is more specific than our documentation usually goes into.

I am okay with closing if it isn't being used internally anymore
