### ISSUE TITLE
uiowa.edu - Windows Firefox ESR Style Issues

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#1257]
Overall, I used Windows Firefox 60.2 ESR and didn't notice any major issues that weren't already defined.

- Brain Card Grid - Though it doesn't break functionally, content overflows the "grid square"
![Screen Shot 2020-03-25 at 1 39 30 PM](https://user-images.githubusercontent.com/4663676/77573272-695fde00-6e9e-11ea-9a3e-d6c27227bfe0.png)

**Comment by bspeare** [comment]
@joewhitsitt did the vertical video play buttons work in ESR?

**Comment by joewhitsitt** [comment]
@bspeare i was able to play/pause
