### ISSUE TITLE
Allow <span> tags in the Minimal HTML format

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#1266]
# Problem

The new alerts system is set to the Minimal HTML format.   Ideally, a site webmaster would be able to add an icon to their alert in the HTML `<span class="fa-exclamation-circle fas"></span>`. 

# Proposed solution

Add `<span>` to the list of allowed tags?

**Comment by joewhitsitt** [comment]
Short term i think this is fine, but I would rather there be a severity dropdown with regards to the alert config that handles icon, color, and aria info and doesn't rely on power users to implement.

**Comment by bspeare** [comment]
I agree.  We definitely don't want to open it up to any icon available. But in the short term it would help with the uiowa.edu launch.

**Comment by joewhitsitt** [comment]
so minimal already has div but restricts the classes allowed to alert and lead from bootstrap. are you okay with doing something similar for span like `<span class="fa*">`? That should cover icons and their type (e.g. fas, fab, etc.)

**Comment by bspeare** [comment]
That would be perfect!
