### ISSUE TITLE
Config ignore does not support drush config exports

### ISSUE THREAD

**Issue by adamdelaney** [uiowa/uiowa#127]
See: https://www.drupal.org/project/config_ignore/issues/2857247. The issue is when new config_ignore items are added and an export is performed, ignored items are getting exported as well. The work around is:
1) Add the config object name to config_ignore settings `admin/config/development/configuration/ignore`.
2) Export the config to the default sync dir `drush cex`.
3) Add only `config_ignore.settings` file.
4) Reset the the branch `git checkout .`.
5) Import config to other sites.

**Comment by richardbporter** [comment]
Patched.
