### ISSUE TITLE
uiowa_alerts MVP re-factoring

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#1271]
<img width="1538" alt="Screen Shot 2020-03-26 at 3 43 17 PM" src="https://user-images.githubusercontent.com/709009/77694726-8c5ec080-6f78-11ea-8e3f-269eb66f98e8.png">

Currently the uiowa_alerts module is designed so that the block it creates is *always* rendered as it is just a container for a javascript that runs to pull in the alerts. That means the region is always rendered and is always visible (as the image shows above) regardless of whether there is any content or not.

How do we resolve this?

**Comment by richardbporter** [comment]
Thinking about the configuration more: the D7 version was never built to allow non-admins/developers to configure the source or the message. If that is intended for D8, it probably doesn't make sense to allow webmaster to change the source of the feed. That seems more like a developer task to test them out locally in a settings.local.php override.

**Comment by pyrello** [comment]
So, to clarify what you are saying here, @richardbporter, the uiowa_alert.settings.source config would still be set but would not be represented in the admin UI?

**Comment by richardbporter** [comment]
Yes because I don't think those test alerts ever drop out of the feed with how the current system is built. So they'll always show which seems excessive.

I'm a bit confused on all the other issues related to this. I can assign myself and try to take it across the finish line.

**Comment by richardbporter** [comment]
I think I'll close this in favor of #1279.
