### ISSUE TITLE
Create module to collect additional site information

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#1273]
Adds the following fields:
- [x] Has a parent organization - checkbox which shows the next 2 fields
- [x] Organization name - textfield
- [x] Organization link - URL

**Comment by joewhitsitt** [comment]
i know the out of the box bucket is "slogan" but what I heard yesterday was that it was going to be more organizational hierarchy (college, department, program, etc.). Since we are thinking about a custom way of handling this, should we move away from the slogan use something else?

**Comment by pyrello** [comment]
@joewhitsitt I'm open to the idea of using a different field entirely. My idea was more about presenting the fields with different labels to the end user, then storing what they enter under the correct field.
