### ISSUE TITLE
As a site owner, I can turn on hawk alerts and/or specify a custom hawk alert message.

### ISSUE THREAD

**Issue by mjoneill** [uiowa/uiowa#1275]
- [x] #1277 Ability to select message options: Feed/Feed + Custom Message/Custom Only
- [x] #1278 Color selection? for alert levels
- [x] #1280 Meaningful a11y experience

**Comment by richardbporter** [comment]
Do we want active Hawk Alerts to display while logged in? I would think, yes?

**Comment by mjoneill** [comment]
I vote yes..  that feels like the right answer, provided it doesn't expose a whole dimension of pain to make it do that. 

^^^ also, not incredibly passionate about this.  So I'd defer to someone with a strong opinion, even if it's in the opposite direction.
