### ISSUE TITLE
Error when selecting multiple images from entity browser in WYSIWYG

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#128]
Steps to reproduce:

- Have at least two images in media library.
- /node/add/page and open the WYSIWYG's media browser.
- click on two or more images (places a green check mark over them) and then click "Select Entities"

`1 error has been found: Select this item`

**Comment by richardbporter** [comment]
Are you sure that issue is related? Patch did not resolve it for me.

**Comment by richardbporter** [comment]
Neither did updating to latest 2.x-dev.
