### ISSUE TITLE
Adminimal - Drag handles are cutoff

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#1286]
![Screen Shot 2020-03-27 at 10 27 18 AM](https://user-images.githubusercontent.com/4663676/77773732-05f9bb80-7018-11ea-928c-9f18b999dad5.png)

Currently affecting paragraphs implementations

**Comment by GaryRidgway** [comment]
will this be a problem after all sites are using Claro? If not, maybe we don't need to worry about it?

**Comment by joewhitsitt** [comment]
SiteNow v1 is not getting claro. so this is still a problem on D7 sites with adminimal and paragraphs

**Comment by GaryRidgway** [comment]
This should be completed and ready for approval

**Comment by joewhitsitt** [comment]
I reviewed this on the current brand site where the problem was reported. It looks like it resolves the issue. Thanks.
👍
