### ISSUE TITLE
Locally-hosted assets are not restricted to under the cacheable limit

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#1297]
Problem: any locally-hosted asset like file, image, video can be up to 50mb in size. This is above the 10mb recommendation https://docs.acquia.com/acquia-cloud/performance/varnish/files/#varnish-10mb. This has two negative consequences: disk space is eaten up faster (currently a 83% usage) and requests for these files bypass Varnish. 

Solution: limit all locally-hosted assets to a max of 10mb. Obviously, this is not a large amount. Some sites have legitimate use cases for larger assets. We should allow for better integration for embedding remote assets from third-party sources.

- [x] Images #1298
- [x] Video #1298
- [ ] Audio
- [ ] Document

**Comment by richardbporter** [comment]
Looks like this cannot be done per-field since we're using an entity reference to a media type. The limit needs to exist on the media type. Do you think that is a problem @joewhitsitt? What about other media types? Audio, background image, video, etc. It seems like a reasonable limitation since we are not a streaming service.

**Comment by joewhitsitt** [comment]
i don't think it is a problem for images. i'd like to get rid of https://github.com/uiowa/uiowa/issues/596 but that can wait for another day.

video is currently only being used by uiowa.edu that i know of

audio could have large files (lecture recordings)

**Comment by richardbporter** [comment]
This is probably less of issue with fields that leverage image styles but the WYSIWYG lets users embed the original image. This may be more of a question of disk space.

**Comment by joewhitsitt** [comment]
we need the original image for animated gif support so reduce the upload size

**Comment by joewhitsitt** [comment]
Closing this for now until:

> We should allow for better integration for embedding remote assets from third-party sources.
https://github.com/uiowa/uiowa/issues/1938
