### ISSUE TITLE
Github agile implementation thoughts

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#1303]
* Stories are created as issues in the relevant repo and tagged with `story` label as well as any other labels that are appropriate.
* Stories are added to the board in the the column that best represents the current state of the work (e.g. if any of its tasks are in progress, the whole story moves to in progress).
* Stories are written as a checklist of sub-tasks. As issues are created to represent the tasks, they are linked by adding `#123: ` at the beginning (where 123 is replaced with the issue number).
* Issues that are contained in a story are not added to the board as they are already represented on the story and just create additional noise.
* Issues that are not part of a story that represent support items can be added directly to the board.
* Support items that are not relevant to a particular repo (e.g. add user to role on x website) are added as notes and prefixed with **[Support]**.
* PRs are added to the board because they represent a support task that must be performed in terms of review/testing. When they are reviewed/tested they can be moved to Done.

**Comment by joewhitsitt** [comment]
To reiterate on what I said in standup, I think we are naturally moving this way for now. Long term (post launch), I feel like stories will be represented less in Github. As Rick mentioned, stories aren't common in the github space. I think stories are less technical and could be tracked elsewhere (still linking technical issues) as the the project/team transitions to a post-live development process. I agree more attention should be given towards the work done to review/approve/merge/deploy PRs, but the additional work of adding and tracking PRs independently of the stories they represent seems like a lot.

**Comment by pyrello** [comment]
I guess I was thinking that the role of the PR on the board is solely for being aware of what work needs to be done in terms of reviewing and testing. They wouldn't be placed on the board until they were at that point. I don't think that PR's need to have a relation to the stories of the tasks that spawned them outside of the issue linking which allows them to automatically close an issue. On the board, they are more of a support task than anything else. Especially because they are usually reviewed/tested by someone other than the person who worked on the task(s) they represent.

I guess I don't share the antipathy towards stories on the issue queue that others seem to feel. To me they just seem like containers or meta issues for tracking the progress of a set of other issues, which is a fairly common practice on Github. That they are written in the style of an agile story doesn't seem to diminish their usefulness.

Ultimately, it feels like the tide of opinion is against settling into this system for the long term, so I don't know how much it is worth trying to improve it in the short run.

**Comment by pyrello** [comment]
As a follow-up to the idea of using a PR on the board to represent reviewing/testing work, I think that if you are the one reviewing a PR, you should assign it to yourself? Then it will show up on the board with your avatar in the lower right corner.
