### ISSUE TITLE
Audit and create "diff" issues between SiteNow Paragraph Bundles and UIDS Components

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#1304]
## Problem

Currently SiteNow Paragraph bundles and UIDS components are not one to one (e.g. SiteNow blockquote [implements the cite attribute](https://github.com/uiowa/uiowa/blob/master/docroot/themes/custom/uiowa_bootstrap/templates/paragraphs/paragraph--blockquote--default.html.twig#L51))

To plan for and adopt the UIDS, we need to audit where the two systems differ and account for those differences in one or both systems.

## Proposed Solution

For each SiteNow paragraph bundle audit the structured fields, style options and template markup and compare it with the existing custom block types, options and uids templates.

It is recommended that both the uiowa.edu and demo.sitenow sites are brought down locally to compare and content in both systems is created to compare. Additionally, the uids_base theme can be turned on for a SiteNow site to see what breaks and what doesn't. If a SiteNow bundle is not currently represented in the UIDS or custom block types library (e.g. Accordion), create a separate issue indicating a need for the component and the list of fields/options that are available.

Issues related to this should be created in https://github.com/uiowa/uids/issues and tagged with SiteNow

**Comment by dnkemper** [comment]
# PARAGRAPH DISCREPANCIES
| *UIOWA BLOCKS NOT IN SITENOW*  | *SITENOW PARAGRAPHS NOT IN UIOWA*  |
|  -------------  |    -------------    |
|  Banner  |    Carousel (& Carousel Image)  |
|  CTA  |    Blockquote   |
|  Hero |    Accordion (& Accordion Item)  |
| Page Title Hero  |  Featured Content (Article, Page, Person) |
| Spacer/Separator  |  - |
|  Statistic  |    -   |
|  Vertical Video  |    -    |


## SITENOW SECTION CONTENT BLOCKS
Text, Accordion, Card, Blockquote, Events, Articles, Featured Content (Article, Page, Person), Carousel, Webform, Image Gallery

## UIOWA SECTION CONTENT BLOCKS  
Banner, Card, CTA, Event, Hero, Image Gallery, Page Title Hero, Spacer/Separator, Statistic, Text Area, Vertical Video - can also add Custom Blocks, Chaos Tools, Content Fields, Tabs (Core), Alert (Custom), Articles (Lists (View)), Menus, University of Iowa Alerts - Alert Block and Webforms 
 

# Card Component

**UIDS Card Block** block_content.type.uiowa_card

    - MODULES USED: heading

**SiteNow Card Paragraph** paragraphs.paragraphs_type.card 

    - MODULES USED: field_group and text

| SiteNow | SiteNow Base | UIDS | UIDS Base | 
| ---- | ------- | --------- | --- |
| Image | field_card_image | image | field_uiowa_card_image |
| Title | field_card_title | title | field_uiowa_card_title |
| Subtitle | field_card_subtitle | *subtitle (add)* || ? |
| ? | ? | author | field_uiowa_card_author |
| Text | field_card_body | content |field_uiowa_card_excerpt | 
| Link URL | field_card_link | link | field_uiowa_card_link | 
| Styles | field_uip_classes | - | - |
| Column Width | field_uip_colwidth | - | - |
| Unique ID | field_uip_id | - | - |


# Text Component

**UIOWA TEXT BLOCK** block_content.type.uiowa_text_area

    - MODULES: text

**SITENOW TEXT PARAGRAPH** paragraphs.paragraphs_type.text

    - MODULES: text

| SiteNow | SiteNow Base | UIDS | UIDS Base |
| ---- | ---- | ---- | ---- |
| Text Body | paragraphs.paragraphs_type.text  | Text Area | block_content.type.uiowa_text_area |
| Styles | field_uip_classes | - | - |
| Column Width | field_uip_colwidth | - | - |
| Unique ID | field_uip_id | - | - |


# Image Gallery Component


**UIDS Image Gallery Block** block_content.type.uiowa_image_gallery

    - MODULES: media_library

**SiteNow Image Gallery Paragraph** paragraphs.paragraphs_type.image_gallery

    - MODULES: media_library & field_group  


| SiteNow | SiteNow Base | UIDS | UIDS Base |
| ---- | ---- | ---- | ---- |
| Images | field_uiowa_gallery_image | Images | field_image |
| Title | field.field.paragraph.image_gallery.field_uip_title | Title | - |
| Display Title | field.field.paragraph.image_gallery.field_uip_display_title | - | - |
| Styles | field_uip_classes | - | - |
| Column Width | field_uip_colwidth | - | - |
| Unique ID | field_uip_id | - | - |

# Events Component

**SiteNow Events:** paragraphs.paragraphs_type.events

    - MODULES: link and field_group (uip groups = field_uip_colwidth, field_uip_classes, field_uip_id)

**UIDS Events:** block_content.type.uiowa_event

    - MODULES: heading, media_library, datetime, link

| SiteNow | SiteNow Base | UIDS | UIDS Base |
| ---- | ---- | ---- | ---- |
| Audiences | field_events_audiences | - | - |
| Department | field_events_department | - | - |
| Display More Link | field_events_more | - | - |
| Event Types | field_events_event_types | - | - |
| General Interests | field_events_gen_interests | - | - |
| Keywords | field_events_keywords | - | - |
| Number of Results | field_events_results | - | - |
| Styles | field_uip_classes | - | - |
| Column Width | field_uip_colwidth | - | - |
| Unique ID | field_uip_id | - | - |
| Title | field_uip_title | Title | field_uiowa_event_title |
| Path | field_events_more_path | Link | field_uiowa_event_link |
| - | - | Location | field_uiowa_event_location |
| - | - | Image | field_uiowa_event_image |
| - | - | Date | field_uiowa_event_date |

# SITENOW PARAGRAPHS NOT IN UIOWA

## SECTION

    - paragraphs.paragraphs_type.section

**Content Vertical Alignment** *field.field.paragraph.section.field_section_alignitems*      
**Content Width** *field.field.paragraph.sectionfield_section_container*   
**Content Blocks**  *field.field.paragraph.section.field_section_content_block*     
**Background Image**  *field.field.paragraph.section.field_section_image*    
**Content Horizontal Alignment** *field.field.paragraph.section.field_section_justifycontent*       
**Administrative Title**  *field.field.paragraph.section.field_section_title*     
**Unique ID** *field_uip_id*      
**Styles**  *field_uip_classes*     

#### SITENOW SECTION - MODULES
field_group, media_library, paragraphs    

## SITENOW BLOCKQUOTE

    - paragraphs.paragraphs_type.blockquote

**Cite** *field.field.paragraph.blockquote.field_blockquote_cite*    
**Content** *field.field.paragraph.blockquote.field_blockquote_content*    
**Footer** *field.field.paragraph.blockquote.field_blockquote_footer*    
**Blockquote Settings - Style:** *field.field.paragraph.blockquote.field_uip_classes*         
**Blockquote Column Width** *field.field.paragraph.blockquote.field_uip_colwidth*     
**Blockquote Unique ID** *field.field.paragraph.blockquote.field_uip_id*  

## SITENOW CAROUSEL IMAGE PARAGRAPH

    - paragraphs.paragraphs_type.carousel_image

**Caption** *field_carousel_image_caption*    
**Image** *field_carousel_image_image*    
**Styles** *field_uip_classes*    
**Unique ID** *field_uip_id*    

## SITENOW CAROUSEL PARAGRAPH

    - paragraphs.paragraphs_type.carousel

**Carousel Item** *field_carousel_item*    
**Column Width** *field_uip_colwidth*    
**Display Title** *field_uip_display_title*    
**Styles** *field_uip_classes*    
**Title** *field_uip_title*    
**Unique ID** *field_uip_id*    

## SITENOW FEATURED CONTENT PARAGRAPH

    - paragraphs.paragraphs_type.featured_content

**Featured Content** *field_featured_content*   
**Column Width** *field_uip_colwidth*   
**Display Title** *field_uip_display_title*   
**Styles** *field_uip_classes*   
**Title** *field_uip_title*   
**Unique ID** *field_uip_id*   


## SITENOW ACCORDION PARAGRAPH

    - paragraphs.paragraphs_type.accordion

**Accordion Items** *field_accordion_item*  
**Column Width** *field_uip_colwidth*  
**Display Title** *field_uip_display_title*  
**Styles** *field_uip_classes*   
**Title** *field_uip_title*   
**Unique ID** *field_uip_id*    

## SITENOW ACCORDION ITEMS PARAGRAPH

    - paragraphs.paragraphs_type.accordion_item

**Body** *field_accordion_item_body*   
**Title** *field_accordion_item_title*   
**Unique ID** *field_uip_id*   


## SITENOW ARTICLE PARAGRAPH

    - paragraphs.paragraphs_type.articles

**Column Width** *field_uip_colwidth*  
**Display More Link** *field_articles_more*  
**Display Title** *field_uip_display_title*  
**Filter Articles by Tag** *field_reference*  
**Items to Display** *field_uip_items*  
**Path** *field_articles_more_path*  
**Show Pager** *field_uip_pager*  
**Styles** *field_uip_classes*  
**Title** *field_uip_title*  
**Unique ID** *field_uip_id* 


# UIOWA PARAGRAPHS NOT IN SITENOW

## UIOWA STATISTIC

    - block_content.type.uiowa_statistic

**Excerpt**   *field_uiowa_statistic_excerpt*       
**Image**   *field_uiowa_statistic_image*     
**Title**  *field_uiowa_statistic_title*          
**UIowa Statistic Title Prefix** *field_uiowa_statistic_title_pre*       
**UIowa Statistic Title Suffix** *field_uiowa_statistic_title_suf*      
  

## UIOWA CTA

    - block_content.type.uiowa_cta

**Link** *field_uiowa_cta_link*       
**Summary** *field_uiowa_cta_summary*     
**Title** *field_uiowa_cta_title*     

## UIOWA HERO

    - block_content.type.uiowa_hero

**Excerpt**   *field_uiowa_hero_excerpt*        
**Image**    *field_uiowa_hero_image*       
**Title**    *field_uiowa_hero_title*        
**Video**   *field_uiowa_hero_video*      

## UIOWA PAGE TITLE HERO

    - uiowa_page_title_hero

**Image**    *field_uiowa_page_title_hero_img*       


## UIOWA SPACER SEPARATOR
    - uiowa_spacer_separator

**Spacer/Separator Text**   *field_uiowa_spacer_separator_txt*

## UIOWA VERTICAL VIDEO

    - block_content.type.uiowa_vertical_video

**Video**      *field_uiowa_vertical_video*    
**Captions**     *field_uiowa_vertical_video_cap*    
**Preview Image**     *field_uiowa_vertical_video_image*    
**Subheading**      *field_uiowa_vertical_video_sub*    
**Title**      *field_uiowa_vertical_video_title*

**Comment by pyrello** [comment]
Wow! Nice work so far, @dnkemper!

**Comment by pyrello** [comment]
Here is my own stab at making a comparison, with just the card component: https://gist.github.com/pyrello/c42d50b20d83c9840970af6950a87534

My comparison in intentionally stripped down with regard to the level of detail so that it can be focused on what choices need to be made about UIDS.

**Comment by pyrello** [comment]
@joewhitsitt I would like to suggest that we narrow the scope of this a little bit, as I think what has been produced as a result of it is a little overwhelming and that makes it hard to take away actionable tasks.

As a starting point, I think that the uiowa_blocks and sitenow paragraphs should be compared just in terms of which fields they have and what changes UIDS will need to make to accommodate both variants. From that we can create issues in UIDS to capture those changes.

After we get through that, then I think we can circle back around to take a look at how the section and paragraph style options that are selected can be accounted for, unless there are cases where you think those need to be factored into how the UIDS component is set up.

**Comment by dnkemper** [comment]
@pyrello @joewhitsitt I can set that up real quick and remove the extra details!

**Comment by joewhitsitt** [comment]
Sorry, I have not been paying attention to this and have become lost across all of the related issues. I suggest @GaryRidgway and @dnkemper come to standup parking lot tomorrow morning so we can all get on the same page.

**Comment by dnkemper** [comment]
I'll focus on this for the rest of today... My boss has had me working on SiteNow. So I haven't had time. Sorry everyone!
