### ISSUE TITLE
InvalidArgumentException: The timestamp must be numeric. 

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#1310]
https://diversity.uiowa.edu/news/feed/media-advisory-columbus-junction-students-visit-ui-explore-health-science-careers-april-10/all 

InvalidArgumentException: The timestamp must be numeric. in Drupal\Component\Datetime\DateTimePlus::createFromTimestamp() (line 198 of .../docroot/core/lib/Drupal/Component/Datetime/DateTimePlus.php)

**Comment by richardbporter** [comment]
Noticed this in while log streaming in prod. Haven't fully investigated yet.

**Comment by richardbporter** [comment]
Seeing this again while investigating #3039. We should fix it.

**Comment by richardbporter** [comment]
Ex. URL from logs: https://baran.lab.uiowa.edu/news/feed/2020/all

**Comment by joewhitsitt** [comment]
Related? https://github.com/uiowa/uiowa/issues/2031

**Comment by richardbporter** [comment]
The example links I provided are no longer throwing an error. Maybe this was fixed with #2983 ?
