### ISSUE TITLE
[Task] Implement Google Search Schema on new uiowa.edu home page

### ISSUE THREAD

**Issue by mjoneill** [uiowa/uiowa#1326]
Add Google Search schema to uiowa.edu.

- [x] @mjoneill to capture specification/code for search schema
- [ ] Developer add it to site

Parent: #1290

**Comment by mjoneill** [comment]
FYI: This is what this about...  

https://developers.google.com/search/docs/data-types/sitelinks-searchbox

Will furnish schema shortly...

**Comment by mjoneill** [comment]
[uiowa-search-action-json.txt](https://github.com/uiowa/uiowa/files/4440428/uiowa-search-action-json.txt)

json in the attached file needs to be expressed in the <head> section of the front page (only) of the new uiowa.edu.

Preferably right before (or after) the CollegeorUniversity schema (#1291). 

@joewhitsitt

**Comment by joewhitsitt** [comment]
To match this, we will need to try a patch for output that is to Google's liking: https://www.drupal.org/project/schema_metatag/issues/3055278

**Comment by mjoneill** [comment]
@joewhitsitt This looks pretty solid.  I had a bit of confusion based on a change to how Google's testing tool/linter shows the results...but the source looks to be spot on.

I'd consider this accepted.  

Only needs to be expressed on front page of the site.
