### ISSUE TITLE
Responsive images are not applied when trying to update image media style in WSYIWYG

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#1335]
# Problem

If you try to update the responsive image media style of an image in the WYSIWYG editor on uiowa.edu, the format will not save.

<img width="1252" alt="Screen Shot 2020-04-06 at 9 40 54 AM" src="https://user-images.githubusercontent.com/1036433/78570693-ebc79680-77ea-11ea-87ae-a35325f2ee80.png">

<img width="1329" alt="Screen Shot 2020-04-06 at 9 41 17 AM" src="https://user-images.githubusercontent.com/1036433/78570712-f08c4a80-77ea-11ea-9997-1ab8df6b3eb9.png">

**Comment by joewhitsitt** [comment]
https://www.drupal.org/project/drupal/issues/3102249
