### ISSUE TITLE
Change Text (plain, long) in uiowa_blocks to Text (formatted, long)

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#1340]
# Problem 

A few of the fields used in the uiowa_blocks are set to Text (plain, long) when they need to be Text (formatted, long). 

**Card**
https://github.com/uiowa/uiowa/blob/master/docroot/profiles/custom/sitenow/config/sync/field.field.block_content.uiowa_card.field_uiowa_card_excerpt.yml 

**Banner**
https://github.com/uiowa/uiowa/blob/master/docroot/profiles/custom/sitenow/config/sync/field.storage.block_content.field_uiowa_banner_excerpt.yml

# Proposed Solution

- Create new fields that are Text (formatted, long)
- Create an update hook to migrate data from old Text (plain, long)

**Comment by joewhitsitt** [comment]
This might be a way to change the type without a new field:
https://www.drupal.org/project/drupal/issues/2843108#comment-12069958

**Comment by dnkemper** [comment]
Started but computer had to be nuked/lost work.
