### ISSUE TITLE
Better menu management

### ISSUE THREAD

**Issue by adamdelaney** [uiowa/uiowa#135]
In d7 we used a collection on contrib to allow users to place nodes into the menu system more intuitively. It would be nice to improve this for d8

## Projects
- https://www.drupal.org/project/bigmenu
- https://www.drupal.org/project/collapsible_dnd
- [Menu Link Weight](https://www.drupal.org/project/menu_link_weight) has a D8 alpha version that relies on several other modules (beta, alpha versions).

**Comment by cory-skeers** [comment]
In the current menu system, unpublished pages (such as in draft workflow) aren't visible in menu selections by Webmaster or Editor. They can be placed from the structure/menus UI.
Mainly an issue if a new section of the website is being created in draft form.

Draft pages also cannot be added to non-main menu pages using the autocomplete entity field, but can using node/#
