### ISSUE TITLE
Allow webmaster role to choose unpublished node as parent menu item

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#1355]
What the webmaster sees:
<img width="469" alt="Screen Shot 2020-04-08 at 11 08 49 AM" src="https://user-images.githubusercontent.com/709009/78807217-5e6e7880-7989-11ea-91fc-2d9a73c343b5.png">

What the administrator sees:
<img width="466" alt="Screen Shot 2020-04-08 at 11 07 11 AM" src="https://user-images.githubusercontent.com/709009/78807248-66c6b380-7989-11ea-8a24-4512524a9d4a.png">

The administrator role is able to do this by virtue of the fact that it has the "Bypass content access control" permission: 
https://git.drupalcode.org/project/drupal/-/blob/8.8.x/core/lib/Drupal/Core/Menu/DefaultMenuLinkTreeManipulators.php#L141-148

But it is not clear to me by what mechanism access is being disallowed to the Webmaster role. The webmaster role has the following permissions, which would seem to allow access:
* Basic page: Create new content
* Basic page: Edit any content
* Basic page: View revisions
* View published content
* View own unpublished content
* View any unpublished content
* View the latest version

The "Administer content" role does not accomplish the desired outcome. The only thing that I've found so far that works is adding the "Bypass content access control" permission to the webmaster role.

Are there concerns about allowing this permission for the webmaster role? Is there another way to allow this access to webmasters?

**Comment by joewhitsitt** [comment]
Concerns beyond the help text associated with that particular permissions? No. It does make me think about the future #748 issue and how it applies to the webmaster role. If this is a need now though, we can deal with issues related to that later.

**Comment by pyrello** [comment]
Yes, understanding there are potential security implications of giving that permission to any role, let's also consider the additional help text: *"View, edit and delete all content regardless of permission restrictions."* Are there use cases where we don't want webmasters to be able to have that level of access to all content on the site?

**Comment by joewhitsitt** [comment]
I can think of a couple webmasters out there, but I think moving forward with this is fine.

**Comment by pyrello** [comment]
@richardbporter @bspeare @briand44 Any concerns about this change?

The proposed change is adding the "Bypass content access control" to the webmaster role.

**Comment by bspeare** [comment]
No concerns here.

**Comment by richardbporter** [comment]
I'm not planning on creating content that I don't want a webmaster to have access to.

**Comment by briand44** [comment]
To be honest, I don't love the idea of granting this permission. I can't think of any issues it would cause right now though but possibly in the future. I know in D7 we had content that was imported or something that we didn't allow webmasters to edit because it could break things.

**Comment by joewhitsitt** [comment]
In D7, we had use-cases where we would establish a piece of content (basic page as the front page) where we didn't want people to accidentally delete because of assumptions made on the node id. My understanding is that this would allow them to bypass that specific restriction.

In D8 Sitenow, we are preventing front page deletion until they assign a new page.
https://github.com/uiowa/uiowa/blob/master/docroot/profiles/custom/sitenow/sitenow.profile#L201

**Comment by pyrello** [comment]
If there is not consensus around implementing this at the SiteNow level, I can also add it to the Collegiate split or I can also implement a grad-specific split. I'm going to need this functionality on every site I build and at the moment I don't have time to chase down the reasons why this permission is the only way to make this functionality work.

@briand44 We can also implement this now as a sitenow-wide update and later move it to a split if it becomes apparent that it is causing trouble.

**Comment by joewhitsitt** [comment]
I just confirmed that this permission does **not** let webmasters get around the front page deletion code in sitenow.profile

**Comment by briand44** [comment]
Since we are not aware of any issues this currently causes with SiteNow, it can be added there and moved later if it ever becomes an issue.

**Comment by joewhitsitt** [comment]
There is a patch for this now that I am going to try in #5659 

https://www.drupal.org/project/drupal/issues/2807629
