### ISSUE TITLE
As a site editor, I should be able to utilize any webform component available to me, and have it styled with the uids_base theme

### ISSUE THREAD

**Issue by GaryRidgway** [uiowa/uiowa#1356]
- [x] 1. Identify the necessary components that need styling for webforms
- [x] 2. Discuss aesthetic with team, decide on look and feel.
- [x] 3. Style components based on discussions had with team, keeping in mind they will be ported eventually to the UIDS.
- [x] 4. Request peer review of these components
- [x] 5. Repeat styling until satisfactory.
- [x] 6. Back-port and refactor component styles in to UIDS

### Identified components

- [x] All fields have Description, Help text, and more text. #1357
- [x] Components that allow users to create more of themselves. #1358 
- [x] email confirm fields
- [x] scale
- [x] alerts
    - [x] success
    - [x] error
    - [x] warning
    - [x] info
- [x] checkboxes
- [x] radios
- [x] file upload

###When this is ultimately done, review and merge
- [x] https://github.com/uiowa/uids/pull/195

**Comment by pyrello** [comment]
Follow-up issue: #1747
