### ISSUE TITLE
Webform UIDS Update - User addable components

### ISSUE THREAD

**Issue by GaryRidgway** [uiowa/uiowa#1358]
Many components Allow the user to add more of them. This can be limited, or unlimited based on the configuration given to the user. when this option is given to the user, the following things are displayed and need to be styled:

- [x] a set of draggable handles is presented to reorder their responses 
- [ ] role weights are allowed as a secondary ordering system
- [x] +/- symbols are added to allow the user to add or remove more rows
- [ ] a bulk row add is presented at the bottom, which allows a user defined number of items to be added all at once

**Comment by joewhitsitt** [comment]
From the looks of #1356 this is done.
