### ISSUE TITLE
Configure meta tags for open graph

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#1361]
I was just sending a link to the new uiowa.edu site and noticed that it doesn't have a preview image when sent over Apple messages:
<img width="211" alt="Screen Shot 2020-04-08 at 4 40 51 PM" src="https://user-images.githubusercontent.com/709009/78836706-42360000-79b8-11ea-9f62-fcd062d34ffb.png">

I also checked FB and its a similar situation:
<img width="502" alt="Screen Shot 2020-04-08 at 4 42 08 PM" src="https://user-images.githubusercontent.com/709009/78836747-5679fd00-79b8-11ea-85d9-53307860acdd.png">

My guess is that we would want to these meta tags in place and configured correctly prior to launch.

- [ ] Preview Image
- [ ] Additional Missed metatag schema items :doh!:

**Comment by joewhitsitt** [comment]
A lot was left un-done with https://github.com/uiowa/uiowa/issues/351. Picking up from there.
