### ISSUE TITLE
[Story] As a reviewer, I can follow a link from any page on the stage site and submit feedback

### ISSUE THREAD

**Issue by mjoneill** [uiowa/uiowa#1364]
- [x] Convert current mailto link to webform.

Can't happen until we are live and/or we go to production.

**Comment by joewhitsitt** [comment]
@mjoneill This is now available for review in STAGE. Link to the form is in the footer, and the feedback form consists of a intro paragraph and fields to capture name, email and a feedback textarea. I created a custom confirmation message and setup an email handler to deliver a notification to the site email address with the submission details.

**Comment by mjoneill** [comment]
@joewhitsitt Fantastic.  Added a file collector field.  Also, I seem to be getting an error on submit.  Related? 

<img width="1474" alt="image" src="https://user-images.githubusercontent.com/7144234/79898844-87ebc300-83d1-11ea-986a-f64a9d70dca6.png">

**Comment by joewhitsitt** [comment]
@mjoneill This is because the site is in stage and we want to prevent site emails going out to site owners and such when testing/working in those environments. We can temporarily disable this functionality for uiowa.stage for a test, but it will get enabled again at the next deployment.

Looks like the importance of #1356 goes up with the file upload field.

I would suggest lowering the max file size and the allowed file types if you are going to keep the field.

**Comment by mjoneill** [comment]
@joewhitsitt Thanks for the explanation...

Hmmm...  My concern with the error message is that I suspect it will lead people who submit feedback to think there's an error/problem.  I'd like to avoid that if possible. 

Alternative: turn the feedback link into a mailto: link to me? 

Thoughts?

**Comment by joewhitsitt** [comment]
Ah, I thought this form was for after go-live and so the STAGE behavior wouldn't be a problem. I could delete the email handler and you could just periodically login and check for submissions? I believe this is also an issue with the contact form.

We _could_ split uiowa.edu with regard to this functionality and turn off the email prevention until after go-live.

If you want to abandon the webform for now and turn the feedback link into a mailto that is fine too. Just let me know

**Comment by mjoneill** [comment]
@joewhitsitt OK.  I'd rather not ask for a split...it's just going to increase overhead and I'd rather not add that to anyone right now.  I'll take a look again later today and see if I'd rather tell people to ignore the error message for now or switch the link to mailto until launch (at which point, we can replace email with the form (sans error).

**Comment by mjoneill** [comment]
@joewhitsitt I swapped the form link out for a mailto: link this morning.  I'd like to circle back to this after launch and make the form active, etc... 

Let me know if you have any reservations or ideas!

**Comment by joewhitsitt** [comment]
Okay. I have "closed" the form and added the same mailto link to the message to visitors.
