### ISSUE TITLE
Improve Layout Builder drag handle

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#1366]
Layout builder has a hidden drag handle:
<img width="442" alt="Screen Shot 2020-04-09 at 4 21 02 PM" src="https://user-images.githubusercontent.com/709009/78942001-5f350680-7a7e-11ea-805b-6250ba080e6a.png">

It can be a very useful tool when it works right, but sometimes, when using it, the settings tray develops a gap on the right hand side that gets larger each subsequent time it gets moved.
<img width="452" alt="Screen Shot 2020-04-09 at 3 57 19 PM" src="https://user-images.githubusercontent.com/709009/78942484-71fc0b00-7a7f-11ea-977a-b5fe87040c7c.png">
<img width="597" alt="Screen Shot 2020-04-09 at 4 30 13 PM" src="https://user-images.githubusercontent.com/709009/78942487-732d3800-7a7f-11ea-9d6b-e53ce4c19438.png">

It would be nice to fix this so that we could let site owners and content editors make use of it.

**Comment by bspeare** [comment]
https://www.drupal.org/project/lb_ux also has a drag handle to make it more obvious:

<img width="353" alt="Screen Shot 2020-07-14 at 4 46 54 PM" src="https://user-images.githubusercontent.com/1036433/87479817-bf919200-c5f1-11ea-9dc2-1c162463790f.png">

**Comment by pyrello** [comment]
@bspeare I think that it has the same problem in terms of the way that the padding on the right side gets bigger if you adjust the tray multiple times.

Just to be clear, I think we looked at lb_ux a while back and decided to incorporate some of their ideas into our theme, but not install the module. Is that your memory as well?

**Comment by bspeare** [comment]
Yes, I just wanted to point out the drag handle that they have.   It might be useful to have since it's not clear to users how to drag the window open.  I don't want to use the module.
