### ISSUE TITLE
Investigate adding critical_css module 

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#1368]
# Problem

We have a 2s page rendering block on uiowa.edu that slows down the page load on mobile. 

# Proposed solution

Add https://github.com/addyosmani/critical to our gulp process so that we have the `critical.css` file ready to use with https://www.drupal.org/project/critical_css when the time comes.

**Comment by richardbporter** [comment]
I'm a bit confused on this. It looks like the libraries require specifying a URL to determine what is critical. Seems like that could change quite a bit from page to page. Are we only concerned with the front page?

**Comment by richardbporter** [comment]
Doing it manually is an option as well: https://www.advomatic.com/insights/eliminating-render-blocking-javascript-and-css-in-above-the-fold-content-in-drupal-sites

**Comment by bspeare** [comment]
Maybe start with a basic page like https://uiowa.stage.drupal.uiowa.edu/contact?  Hopefully, all we need are the header and menu styles.

**Comment by richardbporter** [comment]
We could probably do that without the library by compiling bar, header, menu styles into one critical.css file. I'm guessing that will break the conditional loading of those components though.

**Comment by richardbporter** [comment]
Or result in duplicate styles - some inline and some in corresponding component files.

**Comment by bspeare** [comment]
I think there will be duplication no matter what.  I thought that having the library target the site would also grab the module styles from Superfish that the site depends on as well.

**Comment by richardbporter** [comment]
@bspeare This is on dev now as part of #1563 if you want to take a look: https://uiowa.dev.drupal.uiowa.edu/.

**Comment by bspeare** [comment]
@richardbporter The dev site loads weird for me. In particular how everything under the header loads initially.  I imagine that it's because we are messing with the css.   Looking at the lighthouse score it looks like we gain 2-3 points.

**Comment by richardbporter** [comment]
Not sure I'm following on the weird loading - can you be more specific?

I see a 10 pt gain on mobile with 1.4s reduction in first contentful paint. Desktop is only 4 points and .7s gain.

Stage
![image](https://user-images.githubusercontent.com/1068523/81597074-b8989a00-938a-11ea-8775-6403b9ec7450.png)

Dev
![image](https://user-images.githubusercontent.com/1068523/81597083-bdf5e480-938a-11ea-9349-ba1fdc16c0b9.png)

**Comment by richardbporter** [comment]
I see it now on a hard refresh. Below the fold elements suffer from FOUC since they're not styled initially. Not sure how to handle that. There is an include option for selectors to add or we could expand the viewport height to include more of the page. Otherwise, I think this is how it works.

**Comment by richardbporter** [comment]
I feel like lazy loading makes the FOUC more obvious. I'll play around with a few options.

**Comment by bspeare** [comment]
If I pull the branch down, how can I test the selectors to add?  Is there anything special to get this to run?

**Comment by richardbporter** [comment]
I added more details in #1563 and also pushed a change to dev. I can't seem to get rid of that uiowa-bar jank with the margins.

**Comment by bspeare** [comment]
It does seem to load better now - thanks!  Maybe all we need to figure out is a way to get rid of the uiowa-bar jank.

**Comment by bspeare** [comment]
I'll test this locally further today to see if there are any solutions for the jank.
