### ISSUE TITLE
Build generalized/abstract templates in uids_base for all UIDS components

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#1373]
# Elements
- [x] Button
- [x] Link
- [x] Image
- [ ] List

# Items
- [x] Accordion item
- [x] Banner
- [x] Blockquote
- [x] Card
- [x] Slider item
- [ ] CTA
- [ ] Event
- [x] Hero
- [ ] Image
- [ ] Stat

# Collections
- [x] Slider
- [ ] Image gallery
- [ ] Event listing

**Comment by pyrello** [comment]
This is related to uiowa/uids#309

**Comment by bspeare** [comment]
@pyrello can we close this?

**Comment by pyrello** [comment]
Closing.
