### ISSUE TITLE
People Paragraph Bundle

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#1392]
## Problem
We didn't quite reach feature parity with SiteNow v1 when it comes to people. Site owners are requesting a way to create dynamic lists of filtered people on their sites. The current option is to either use the full people listing or to manually curate people via featured content.

## Proposed Solution
Similar to the Articles paragraph bundle, create one that handles people. Start with a generic person view and through paragraph bundle settings allow the list to be filtered by tag and allow the sort order to switch between sticky/last/first or sticky/first/last. Similar styles can be extended from featured content where images and fields can be hidden along with the list/grid/masonry style options.

Depending on the timeline of this feature, styles should be done building off the patterns defined in UIDS. Work is currently be done to handle SiteNow articles in UIDS and this shouldn't be too much different.

## References:
https://github.com/uiowa/uiowa/blob/master/docroot/modules/custom/sitenow_articles/sitenow_articles.module#L275

**Comment by dnkemper** [comment]
Updated issue removing styles. Blocked for now
