### ISSUE TITLE
Update uids_base.settings config through update hook

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#1398]
Since `uids_base.settings` are ignored by config, the changes that happened in #1330 were not able to be propagated to all sites via the managed config process. There is a workaround to prevent issues with calling the correct header template in the `uids_base.theme`, but it would be nice to get the theme settings that are stored on all sites up-to-date with recent changes so that the workaround can be removed.

**Comment by richardbporter** [comment]
I noticed what looked like duplicate config the other day when accessing the settings via Drush. Do the config items nested under the addtional uids_base key just need to be deleted? 

https://github.com/uiowa/uiowa/pull/1330/files#diff-ee577aca5605039ffb0fe9e8cbb06372

**Comment by pyrello** [comment]
I believe that is outdated, so yes.

**Comment by joewhitsitt** [comment]
Is this still an issue now that https://github.com/uiowa/uiowa/pull/2538 made an additional pass?

**Comment by pyrello** [comment]
I believe this can be closed.
