### ISSUE TITLE
Local video text transcript has wrong mime type

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#1399]
Console error: `Resource interpreted as TextTrack but transferred with MIME type text/plain`

Can be seen in the console on the front page: https://uiowa.stage.drupal.uiowa.edu/

```
Resource interpreted as TextTrack but transferred with MIME type text/plain: "https://uiowa.stage.drupal.uiowa.edu/sites/uiowa.edu/files/2020-04/20200407%20ArtsVerticalInvestigate%201080.vtt".
```

**Comment by richardbporter** [comment]
@joewhitsitt Also interested in your take on this as well.

**Comment by joewhitsitt** [comment]
This appears to be the solution: https://stackoverflow.com/questions/59828734/resource-interpreted-as-texttrack-but-transferred-with-mime-type-text-plain#answer-59828735

**Comment by richardbporter** [comment]
I thought there was a way to set the mime type for media types. Where is this file uploaded?

**Comment by joewhitsitt** [comment]
I am not sure where to set that in D8. D7 it was file_entity that had that UI.

**Comment by joewhitsitt** [comment]
This is hardcoded now in D8 and I guess it is failing to properly identify...
https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21File%21MimeType%21ExtensionMimeTypeGuesser.php/property/ExtensionMimeTypeGuesser%3A%3AdefaultMapping/8.8.x

Contrib enters the room:
https://www.drupal.org/project/filemime

**BUT...**

It might be better to just wait for Core to handle captions and transcripts.. https://www.drupal.org/project/drupal/issues/3002770

**Comment by richardbporter** [comment]
We now have this module as a result of the Imagemagick update: https://www.drupal.org/project/sophron

I haven't looked into it much but it includes a more robust "mime-type guesser" submodule than core provides.

**Comment by richardbporter** [comment]
sophron_guesser does not solve this.

**Comment by richardbporter** [comment]
I can't reproduce this on uiowa.edu.
