### ISSUE TITLE
Table of Contents Block

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#140]
In D7, our link functionality included a fairly easy way to create and use anchors. That doesn't exist in our D8 implementation with LinkIt.

Our paragraph items each provide a unique id input which can be helpful, but editors still have to create manual links using `#intro` type links within LinkIt's URL field. Otherwise, editors have to view source and add ids themselves.

Table of Contents have come up a few times with my D7 clients and I see a use case in D8. My thought was an automatic table of contents block that would scan for headers in the main content using JS. I would just do it, but our content output isn't always predictable so it could use some more thought.

**Comment by joewhitsitt** [comment]
To improve accessibility, our current bundles were updated to use proper header nesting. The logic needed for this functionality has become simpler

**Comment by joewhitsitt** [comment]
Modified to capture idea for a possible block implementation

**Comment by bspeare** [comment]
I've had a few recent requests for this amazing feature:
- https://epicsupport.sites.uiowa.edu/
- Demand jump pages https://github.com/uiowa/uiowa/issues/6328

**Comment by bspeare** [comment]
Closing in favor of https://github.com/uiowa/uiowa/issues/8290.
