### ISSUE TITLE
Console warning about lazy loaded image with no dimensions

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#1406]
`[Intervention] An <img> element was lazyloaded with loading=lazy, but had no dimensions specified. Specifying dimensions improves performance.`

https://uiowa.stage.drupal.uiowa.edu/academics

**Comment by richardbporter** [comment]
@joewhitsitt Did you encounter this during your lazy load work?

**Comment by joewhitsitt** [comment]
Not that I recall. Could it be a webp addition that caused this? We can determine which image by pulling down and doing some elimination guess and check

**Comment by bspeare** [comment]
Maybe it’s just referring to the new practice of adding dimensions to images for performance ? https://twitter.com/jensimmons/status/1173293500563165186

**Comment by bspeare** [comment]
I wonder if something like this would help https://www.drupal.org/project/drupal/issues/3095126.  It would also help remove the Image Jank: https://developer.mozilla.org/en-US/docs/Web/Media/images/aspect_ratio_mapping.

**Comment by joewhitsitt** [comment]
I don't know if https://github.com/uiowa/uiowa/pull/1433 will solve the "image jank" unless the <img> which I believe is the fallback image is the same resolution as final loaded version AND the loaded version is reduced at all by the current device size and before the breakpoint.

**Comment by bspeare** [comment]
@joewhitsitt Are you still getting "image jank" with the patch?

**Comment by joewhitsitt** [comment]
yeah, i'll upload a mov to slack
