### ISSUE TITLE
administerusersbyrole update - Users only see people that they can manage

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#141]
Updating from 8.x-3.0-alpha2 to beta1 changes how users are listed on the overview page. Users will only see people that they can manage. This is nice for filtering out admins and our alter could be removed but it is is suboptimal for editors because they see nobody.

This is the commit that introduced the change: https://cgit.drupalcode.org/administerusersbyrole/commit/?h=8.x-3.x&id=40b6bec130359708a32787004d8e57b81a88ebbc

Our alter: https://github.com/uiowa/sitenow/blob/master/sitenow.profile#L57

**Comment by richardbporter** [comment]
Nothing is broken _yet_ so I'm removing label.

**Comment by joewhitsitt** [comment]
Updated title since it isn't a bug/broken. What is the plan then for this issue? Close/label "for reference", implement a fix in SiteNow to display all users or wait/contribute to an issue on D.o?

**Comment by joewhitsitt** [comment]
@richardbporter can i get your thoughts on https://github.com/uiowa/uiowa/issues/141#issuecomment-514778331 ?

**Comment by richardbporter** [comment]
I think we should take action because we will need to update at some point. I don't think we should close it or mark as for reference. I'd have to investigate further on what specific action needs to taken.
