### ISSUE TITLE
Hide on lists option for article authors is currently broken in uids_base

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#1413]
# Problem

The "Hide on Lists" option within the article content type and the article paragaraph view is currently broken within the article list template. 

<img width="1077" alt="Screen Shot 2020-04-17 at 10 29 28 AM" src="https://user-images.githubusercontent.com/1036433/79586347-99159680-8096-11ea-9420-167814a7e11d.png">

**Comment by joewhitsitt** [comment]
>You can select ‘Hide on lists’ if you don’t wish to display the particular person on the /people page.
https://sitenow.uiowa.edu/documentation/person-content-type

This doesn't extend to articles, just the /people view page right now. In the future it will also pertain to #1392.

Unless I don't understand, I think this is a non-issue

**Comment by bspeare** [comment]
@joewhitsitt Good! One less issue for now - thanks.
