### ISSUE TITLE
remove pad.org.uiowa.edu

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#1416]
This is on uiowa01. This was a subdirectory site that was going to transition and then it was decided it could go away.

**Comment by briand44** [comment]
When this is completed we should update the notes on the site request submission and lock it as well.

**Comment by briand44** [comment]
oh and we should notify hostmaster that they can reclaim pad.org.uiowa.edu.

**Comment by dnkemper** [comment]
Completed all steps and opened PR
