### ISSUE TITLE
Establish article page design in uids_base

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#1421]
# Problem

The `uids_base` page design for the article content type is quite different than https://sitenowdemo.dev.drupal.uiowa.edu/news/2020/04/lkjlkjlkj.     

# Proposed Solution

Work on integrating the features that exist within the `uiowa_bootstrap` article page design into `uids_base`.

**Comment by joewhitsitt** [comment]
I am not sure where this is, but I am open to a different design for articles. This is what we started with for HR (now forked): https://hr.uiowa.edu/development/learning-and-development/working-learning-and-leading-remotely/working-remotely-blog/mindfulness

We went big featured image in anticipation of the stories site... https://mnh.prod.drupal.uiowa.edu/news/2019/01/frank-russel-expedition

**Comment by bspeare** [comment]
No further work has been done on this yet so I appreciate you commenting and providing the examples!

**Comment by pyrello** [comment]
Noting the link to #1530 and #1536

**Comment by joewhitsitt** [comment]
> Noting the link to #1530 and #1536

Regarding https://github.com/uiowa/uiowa/pull/1530, I trying to reduce scope for "part 1" in an effort to get something ready by the end of the sprint. Article/Page full featured image, Section Images and Carousel image use a responsive image styles already. Not opposed to switching it to one of the other ones later.

**Comment by pyrello** [comment]
No worries! Just wanted to establish the connection in case it was helpful in the future :)

**Comment by bspeare** [comment]
Do you think we can close this one for now as a result of https://github.com/uiowa/uiowa/pull/1539?

**Comment by joewhitsitt** [comment]
Was this also the placeholder issue for converting the article content type to layouts? Is that still a thing or has it been captured elsewhere?

**Comment by bspeare** [comment]
Good point!   @pyrello What are your thoughts?  Create a new issue dedicated to creating a layout builder template?

**Comment by pyrello** [comment]
Created a new issue.
