### ISSUE TITLE
Uncaught SyntaxError on brand.prod.drupal.uiowa.edu

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#1429]
# Problem

There is a console error on brand.prod.drupal.uiowa.edu regarding the tag manager js in uiowa_core. 

<img width="895" alt="Screen Shot 2020-04-20 at 10 25 14 AM" src="https://user-images.githubusercontent.com/1036433/79769447-bb572080-82f1-11ea-89c0-cefc2466d1dd.png">

<img width="1274" alt="Screen Shot 2020-04-20 at 10 27 08 AM" src="https://user-images.githubusercontent.com/1036433/79769462-bf833e00-82f1-11ea-8232-8af91a7542fc.png">

# Proposed Solution

Is there a syntax error or is this another issue?

**Comment by pyrello** [comment]
Not sure how, but this js file is actually an HTML file: https://github.com/uiowa/uiowa/blob/master/docroot/modules/custom/uiowa_core/js/tag-manager.js

@joewhitsitt ?
