### ISSUE TITLE
Remove alert styling from layout builder message on edit page

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#1443]
# Problem

A giant alert message on each layout builder edit page announces a reminder about single page vs template page editing. 

<img width="1443" alt="Screen Shot 2020-04-21 at 12 33 48 PM" src="https://user-images.githubusercontent.com/1036433/79895640-d0ed4880-83cc-11ea-8a68-8126bd8c54ac.png">

# Proposed Solution

In an effort to de-clutter the layout builder edit page screen, the message will be reduced to a minimal line of text that is still visible to users. 

<img width="1448" alt="Screen Shot 2020-04-21 at 12 34 10 PM" src="https://user-images.githubusercontent.com/1036433/79895646-d2b70c00-83cc-11ea-9cb3-5a6d4d6adea1.png">

**Comment by joewhitsitt** [comment]
This happens for all system messages (e.g. webform submission confirmation, etc.)

**Comment by bspeare** [comment]
I am mostly hoping to de-clutter the layout builder edit screen for now since this type of alert seems over-the-top for the message that it is conveying.  What do you think?

**Comment by bspeare** [comment]
I think this also brings up the need to possibly adjust the alert styles that was discussed here: https://iowaweb.slack.com/archives/GDK8S2VFE/p1587061139291100.

**Comment by joewhitsitt** [comment]
Gotcha. Disregard then. I think the styles are fine as-is. I do like the idea of conforming to industry norms with regard to status messages but that is based on assumptions that people have been trained to expect that (similar to the hambuger menu = navigation). With all the padding in Claro I think it matches.
