### ISSUE TITLE
Add/move colorbox control image files from uiowa_bootstrap to uids_base

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#1458]
# Problem

https://brand.prod.drupal.uiowa.edu/creative-strategy

<img width="1646" alt="Screen Shot 2020-04-22 at 4 23 43 PM" src="https://user-images.githubusercontent.com/1036433/80035534-d07cac80-84b5-11ea-99af-733eb5515d80.png">

**Comment by joewhitsitt** [comment]
Is now the time to refactor how these are pulled in? https://github.com/uiowa/uiowa/issues/1200

**Comment by bspeare** [comment]
@joewhitsitt Did you still want to factor how these are pulled in?

**Comment by joewhitsitt** [comment]
Looks like you fixed this similar to uiowa_bootstrap, so #1200 can stay open and I will note that we should resolve it for both themes.

**Comment by bspeare** [comment]
Closed via https://github.com/uiowa/uiowa/pull/1472.
