### ISSUE TITLE
As a brand site user, I can use a lockup generator that looks like the rest of the site

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#1459]
# Problem 
- [x] Add `margin-bottom: 15px;` for lockup page h1

<img width="1001" alt="Screen Shot 2020-04-30 at 12 21 32 PM" src="https://user-images.githubusercontent.com/1036433/80740090-2ae0c300-8add-11ea-9bff-43abb3fe0370.png">

- [x] Add `margin-bottom: 5px;` to step details
<img width="373" alt="Screen Shot 2020-04-30 at 12 13 53 PM" src="https://user-images.githubusercontent.com/1036433/80739471-249e1700-8adc-11ea-91cc-545eb6c46c32.png">

- [x] Add `width: 100%;` to submit button

<img width="451" alt="Screen Shot 2020-04-30 at 12 13 13 PM" src="https://user-images.githubusercontent.com/1036433/80739514-37185080-8adc-11ea-986e-b2ee6961667e.png">

- [x] line breaks seem off for lockup name and category on preview page
- [x] download button butts against footer (This might be a setting padding we want to add to all non-paragraph page types).
- [x] Remove italic styling from help text (Adjust in https://github.com/uiowa/uiowa/blob/master/docroot/themes/custom/uids_base/scss/components/elements/forms/forms.scss)

<img width="359" alt="Screen Shot 2020-04-29 at 1 06 49 PM" src="https://user-images.githubusercontent.com/1036433/80630737-5058c880-8a1a-11ea-8983-baa9f5bdd269.png">

- [x] left align save as drop down menu and label (Adjust in https://github.com/uiowa/uiowa/blob/master/docroot/themes/custom/uids_base/scss/components/elements/forms/forms.scss)

<img width="383" alt="Screen Shot 2020-04-29 at 1 08 35 PM" src="https://user-images.githubusercontent.com/1036433/80630908-8d24bf80-8a1a-11ea-9e62-1838542967c6.png">

- [x] add arrow to submit button (Skip for now)

<img width="367" alt="Screen Shot 2020-04-29 at 1 08 14 PM" src="https://user-images.githubusercontent.com/1036433/80630874-8138fd80-8a1a-11ea-907d-23819b8d0d35.png">

- [x] can we reduce line height on "follow the steps below..." to 1.5rem. Is this text required? I could see just killing it completely. If it's better to keep it, let's revise text to read: Follow the steps below to create your unit lockup.

<img width="347" alt="Screen Shot 2020-04-29 at 1 07 58 PM" src="https://user-images.githubusercontent.com/1036433/80630847-77af9580-8a1a-11ea-9a67-61c65c091a96.png">

- [x] On https://brand.prod.drupal.uiowa.edu/lockup-system remove gold stroke on button style used on "apply" button, search approved lockups page. change button style to black. (Adjust in https://github.com/uiowa/uiowa/blob/master/docroot/themes/custom/uids_base/scss/components/elements/forms/forms.scss ?)

<img width="1351" alt="Screen Shot 2020-04-29 at 1 03 37 PM" src="https://user-images.githubusercontent.com/1036433/80630443-dcb6bb80-8a19-11ea-9fca-24542f2b9949.png">

- [x] The `views-exposed-form` on https://brand.prod.drupal.uiowa.edu/lockup-system should also be adjusted so all elements match the height of Apply button.  (Adjust in https://github.com/uiowa/uiowa/blob/master/docroot/themes/custom/uids_base/scss/components/elements/forms/forms.scss ?)

<img width="1351" alt="Screen Shot 2020-04-29 at 1 03 37 PM" src="https://user-images.githubusercontent.com/1036433/80630443-dcb6bb80-8a19-11ea-9fca-24542f2b9949.png">

- [x] Lockup Feature Branch https://github.com/uiowa/uiowa/pull/1452

**Comment by joewhitsitt** [comment]
@bspeare did you say you had screenshots and/or additional info about these items?

**Comment by joewhitsitt** [comment]
Ah, download on the node full page:
<img width="439" alt="Screen Shot 2020-04-29 at 12 56 08 PM" src="https://user-images.githubusercontent.com/4663676/80629724-dc69f080-8a18-11ea-8836-b4e815389146.png">

**Comment by bspeare** [comment]
@joewhitsitt I just updated with additional/new screenshots and notes for all of the check boxes.

**Comment by bspeare** [comment]
It looks like we are also missing the field labels on the full node page due to `uids_base`

`uiowa_bootstrap`

<img width="1127" alt="Screen Shot 2020-04-29 at 1 15 44 PM" src="https://user-images.githubusercontent.com/1036433/80631694-c447a080-8a1b-11ea-9527-cef52c202eee.png">

`uids_base`

<img width="1131" alt="Screen Shot 2020-04-29 at 1 15 15 PM" src="https://user-images.githubusercontent.com/1036433/80631699-c4e03700-8a1b-11ea-9839-0c1d8de014cc.png">

**Comment by bspeare** [comment]
The label was missing from the field template.  I can add that back in.

**Comment by bspeare** [comment]
It looks like https://github.com/uiowa/uiowa/issues/1484 will need to be done as well with this field template adjustment.

**Comment by joewhitsitt** [comment]
Do you want these fixes to be done as part of https://github.com/uiowa/uiowa/pull/1472 or start a new one?

**Comment by bspeare** [comment]
I'd be fine with putting them in #1472 unless you'd like to start a new one.

**Comment by joewhitsitt** [comment]
>I could see just killing it completely. If it's better to keep it, let's revise text to read: Follow the steps below to create your unit lockup.

This was requested by the customer originally, so I have updated the text for now

**Comment by bspeare** [comment]
Those updated words are by the customer too, so we can go either way.  I think it would look better to remove the text.

**Comment by joewhitsitt** [comment]
it would be one less thing that is custom... I will remove it

**Comment by joewhitsitt** [comment]
>add arrow to submit button

Since this is an drupal core input button with the value property serving as the button text, I don't know off-hand how best to approach this. as far as I can tell pseudo before doesn't work on input submit, and it seems like a lot to try and get it in properly with JS.

`.views-exposed-form` inputs would be covered if uids form styles weren't scoped under `.uids-content`. Could we turn these UIDS form styles into something reusable?

https://github.com/uiowa/uids/blob/master/components/01%20-%20elements/forms/_forms.scss#L3

**Comment by bspeare** [comment]
@joewhitsitt  What's the best way to move forward with making the UIDS form styles into something more reusable for this use case? It looks like if we added the `.uids-content` class to that form it would get us closer to what we want but that might not be the best practice.

**Comment by joewhitsitt** [comment]
i guess I am wondering why form styles are scoped under that. is it to prevent those form styles from being used in the header/footer/other areas?

if we went with the "add class to views-exposed-form" route, we should probably do it everywhere by either bring the template local and overriding or processing views on the fly.
`template_preprocess_views_exposed_form()`

**Comment by bspeare** [comment]
Yeah, it was to avoid the header and footer areas.  I'm open to changing it if you think it would help streamline things.

**Comment by joewhitsitt** [comment]
Looks like this is already implemented but restricted to certain views. Should we open this up to all views and have views opt-out instead?

https://github.com/uiowa/uiowa/blob/master/docroot/themes/custom/uids_base/uids_base.theme#L300

**Comment by bspeare** [comment]
Maybe we can use `template_preprocess_views_exposed_form()` for now and find a better solution for moving forward?

**Comment by bspeare** [comment]
We should probably open it up to all views for now.

**Comment by joewhitsitt** [comment]
Now that the guidelines are gone I am seeing some squeeze here:
<img width="362" alt="Screen Shot 2020-04-30 at 12 07 32 PM" src="https://user-images.githubusercontent.com/4663676/80738898-41861a80-8adb-11ea-8ee8-2ddb014d6e9a.png">

**Comment by bspeare** [comment]
@joewhitsitt I just added a few more checkboxes at the top of this page to address this issue.
