### ISSUE TITLE
Possible regression where toggle navigation shows instead of horizontal navigation

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#1462]
<img width="1336" alt="Screen Shot 2020-04-23 at 10 46 44 AM" src="https://user-images.githubusercontent.com/709009/80120282-606f3480-8550-11ea-9e0b-d81f7aa19559.png">

**Comment by mark-bennett-uiowa** [comment]
I was just trying to fix this in my config_split. By switching to Toggle Navigation and then back to Horizontal navigation in the UI, the cst showed it updated these two files:
```
block.block.main_navigation__superfish__horizontal   Different  
block.block.main_navigation__superfish__toggle       Different
```
Not sure if something in one of these files is causing it, but the navigation works when these are updated.

**Comment by pyrello** [comment]
That makes me think that it is a config default value which is not being properly set. I haven't checked yet, but I'm pretty sure what changes in those block config files is the UUID.

**Comment by pyrello** [comment]
@mark-bennett-uiowa Do you recall if you have encountered this again? I'm wondering if we fixed this?

**Comment by mark-bennett-uiowa** [comment]
@pyrello Im pretty sure this can be removed. It hasnt happened since April, so I think its been fixed. Closing issue.
