### ISSUE TITLE
As a visitor I can view events with UIDS styling

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#1465]

**Comment by bspeare** [comment]
I did some initial work on https://github.com/uiowa/uiowa/blob/master/docroot/themes/custom/uids_base/templates/misc/sitenow-events-teaser.html.twig to follow the format of the events component, but that can easily be changed to follow the example of the article teaser using the card template: https://github.com/uiowa/uiowa/blob/master/docroot/themes/custom/uids_base/templates/content/node--article--teaser.html.twig.
