### ISSUE TITLE
Lazy/WebP loaded images not respecting responsive rules when not containerized

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#1476]
Here is an example page with this issue: https://uiowa.stage.drupal.uiowa.edu/test-page-2

The image that loads at the top of the page has the "Medium - no crop" view mode selected and once the image loads, it is not respecting that.

**Comment by pyrello** [comment]
FYI, this issue is preventing me from completing https://gradcogscilang-temp.prod.drupal.uiowa.edu, which is part of the process of removing all the Collegiate sites.

**Comment by pyrello** [comment]
A couple notes from my initial investigation of this issue:
* The lazy module includes a CKEditor filter to lazy load images, which is not currently turned on in our setup. Turning this on for the appropriate text format did not resolve the issue. It may be that this filter is only for non-media images.
* There was a patch added in #1433 that adds `height` and `width` attributes to images and these appear to be showing up empty in my test image. Removing the patch also did not resolve the issue.

**Comment by joewhitsitt** [comment]
I am not positive, but I wonder if this has to do with an unknown height, without some extra js on the fly, maybe we will have to disable lazy load for no-crop view modes.

>The problem is that before the images are loaded, their height on the page is unknown. The browser has to download the image & observe its aspect ratio, and calculate a height for it.

**Comment by bspeare** [comment]
@pyrello Have you tried uninstalling the `webp` module?  I just did and the small no-crop setting worked.

**Comment by joewhitsitt** [comment]
i turned of webp and noticed the same, even with a new image upload. unfortunately webp looks to be a global thing...

**Comment by pyrello** [comment]
Since webp seems to introduce this bug, it seems like we should roll it back for now. I can try to figure out a summary of the issue and post it to the issue queue for the module.

**Comment by pyrello** [comment]
More precisely, this seems to be an issue of combining the webp + lazy modules together. When I uninstalled the lazy module and left webp installed, the image worked as expected.

<img width="1336" alt="Screen Shot 2020-04-29 at 12 04 57 PM" src="https://user-images.githubusercontent.com/709009/80624776-c60c6680-8a11-11ea-8050-7e84592ebcd3.png">

<img width="983" alt="Screen Shot 2020-04-29 at 12 05 38 PM" src="https://user-images.githubusercontent.com/709009/80624793-cc9ade00-8a11-11ea-99da-798930488eac.png">

**Comment by bspeare** [comment]
I vote that we keep the lazy module for performance gains.

**Comment by joewhitsitt** [comment]
WebP is @richardbporter 's baby. Any input?

**Comment by pyrello** [comment]
This is as far as I got in trying to summarize this issue in the most generic way possible:

>There seems to be an issue at the intersection of webp + lazy + responsive image styles + using the "Scale" image style operation. I have a website where lazy and webp are both installed, responsive image sets (which map to an media image view mode) and we have a "no crop" image option that inserts a responsive set of image scaled to a set of widths.

Not sure whether this needs to be filed in the lazy or webp issue queues.

**Comment by richardbporter** [comment]
Is this limited to the WYSIWYG? If so, we could preprocess responsive image styles, much like webp is doing, and unset the webp src.

Filing an issue and further debugging to determine the cause would great.

**Comment by richardbporter** [comment]
I'm not sure I understand the problem and expected behavior here. Uninstalling webp locally doesn't change anything for me.

**Comment by pyrello** [comment]
@richardbporter Compare these two pages:
* https://cogscilang.grad.uiowa.edu/
* https://gradcogscilang-temp.prod.drupal.uiowa.edu/

They are both displaying the exact same image using the same settings via WYSIWYG. In the second case, the image is not respecting the responsive image settings.

**Comment by richardbporter** [comment]
I can't figure it out. I guess just uninstall it.

**Comment by pyrello** [comment]
#sadface

**Comment by pyrello** [comment]
Another possibility is that we could still turn on WebP for the homepage, since we hadn't noticed any ill effects there. Ideally, I think we would like to get this turned back on for all sites eventually.

**Comment by joewhitsitt** [comment]
i vote for turning it off until we can fix it. it is a next gen format that has caused other issues (errors generating derivatives) that folks won't really notice when it is turned off/turned back on.

**Comment by richardbporter** [comment]
Actually, checking prefer native lazy loading fixes this in Chrome so its probably an issue with the library or some other config we need to adjust. 

![image](https://user-images.githubusercontent.com/1068523/80821711-e0277f80-8b9e-11ea-88f2-f385690aeef6.png)

**Comment by richardbporter** [comment]
I didn't get any further. :( I'm not sure what other configuration to change. The library says this about responsive images:
>Responsive image support (picture and/or srcset)
Lazysizes is built upon the Responsive image standard and extends it with additional functionality. For full cross browser responsive image support you must use either a full polyfill like picturefill or use the extreme lightweight partial respimg polyfill plugin or the responsive image on demand plugin.

Turning on webp renders responsive images with the `picture` tag and that seems to mess with lazysizes somehow. We didn't notice it before because the homepage has mostly containerized images but the wrong size is loading still. 

Uninstalling webp isn't really "fixing" the issue but we can still proceed with that if others think is best. This might crop again if responsive images start using `picture` tags for other reasons.

**Comment by pyrello** [comment]
I guess I thought that responsive images always used the `<picture>` tag.

**Comment by pyrello** [comment]
@richardbporter I guess I'm not sure what you mean when you say that uninstalling webp doesn't "fix" the issue.
