### ISSUE TITLE
Post Collegiate clean-up

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#1477]
- [x] Remove `docroot/profiles/custom/collegiate`.
- [x] Remove `docroot/themes/custom/collegiate_theme`.
- [x] Remove `collegiate_theme` entry from package.json workspaces.
- [x] Remove `Uiowa\Blt\Plugin\Commands\ReplaceCommand::replaceSetup` (https://github.com/uiowa/uiowa/blob/fc7fe6af7c60024677380f0da72e9b74257c6fac/blt/src/Blt/Plugin/Commands/ReplaceCommands.php#L74) to remove looping through profiles.
- [x] Compare collegiate.info.yml with composer.json to see if any dependencies can be removed.
- [ ] Archive https://github.com/uiowa/hds
- [x] Remove profile argument from `uiowa:multisite:create`.
- [x] Remove uiowa.profiles custom configuration from blt.yml. Move requester config up for new and existing sites.
- [x] Set cm.core.install_from_config to true in blt.yml.
- [x] Remove default profile configuration from site creation process.
- [x] Update all existing site blt.yml files to remove profile specific config.
- [x] Move sitenow.settings.php to global.settings.php and remove profile specific include chain.
- [x] #1248 
- [x] #1247

**Comment by richardbporter** [comment]
I added some additional cleanup steps. This would greatly reduce the complexity of our setup. If sites need to use a different profile or export all configuration, that would still be possible.
