### ISSUE TITLE
Replace views_tree module with something that is currently support and available via composer

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#1479]
The views_tree module was embedded with the project because it is a dependency of the uiowa_book module and is not built in a way that supports inclusion by composer. It currently has deprecated code errors, so I think it is time to start looking for a new module to handle this functionality.

**Comment by pyrello** [comment]
@mark-bennett-uiowa If you could help detail what the views_tree module is being used for, I would be happy to help look for an alternative solution.

**Comment by mark-bennett-uiowa** [comment]
The Views Tree module is only used for the Table of Contents view page and block.

The block was to be used in side-menu navigation to top level headings (basically depth=2 where depth=1 is the book itself). Moving forward, the side-menu block will most likely not be used as breadcrumbs is working to satisfy movement within the site.

The page is essential and the main "view" into the book itself (see [https://policy.clas.uiowa.edu/table-of-contents](https://policy.clas.uiowa.edu/table-of-contents)). During development it appeared as the recommended (and only) solution for the book module. I believe the UI Ops Manual site may be using the same thing, but I havent looked at that site in months.

Other options I have looked at (some tested) are:
Taxonomy Menu [https://www.drupal.org/project/taxonomy_menu](https://www.drupal.org/project/taxonomy_menu): appears to only work with voacbularies.
Book Tree Menu [https://www.drupal.org/project/book_tree_menu](https://www.drupal.org/project/book_tree_menu): seems to solve the block issue, not the page.
TOC filter [https://www.drupal.org/project/toc_filter](https://www.drupal.org/project/toc_filter): seems to create ToCs by parsing the node itself.

**Comment by mark-bennett-uiowa** [comment]
Switching the block to use a list format (HTML or unformatted) will still allow the block to work (if needed eventually). However, the page and its nested list feature doesn't work unless the Views_Tree module is used.

**Comment by pyrello** [comment]
Noting this issue in the views_tree issue queue where adding a composer.json file is rejected: https://www.drupal.org/project/views_tree/issues/2772135#comment-13579021

**Comment by mark-bennett-uiowa** [comment]
Should this module be moved to a site-specific module for the policy.clas.uiowa.edu site? Would that lessen the impact on composer? Should the code issues be remedied in a patch we create?
