### ISSUE TITLE
Update to 8.7

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#148]
now that it is available?

**Comment by joewhitsitt** [comment]
Blocked by `acquia/blt-require-dev  10.0.0-beta1`. Needs to be updated to require the 8.7 release of `webflo/drupal-core-require-dev`

**Comment by joewhitsitt** [comment]
Related: https://github.com/webflo/drupal-core-require-dev/issues/3

**Comment by joewhitsitt** [comment]
#100 has to be done at the same time.

**Comment by richardbporter** [comment]
I wonder if we still need this patch: https://github.com/uiowa/uiowa/blob/master/composer.json#L130 now that we are installing from existing config.

**Comment by joewhitsitt** [comment]
https://github.com/uiowa/uiowa/pull/198/commits/3997de0e6d3bb0cfb3e8516d1841b24d4ad4d248 to resolve #100
