### ISSUE TITLE
Error when trying to view revisions with uids_base

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#1480]
# Problem

Clicking on a revision link creates an error:

<img width="1307" alt="Screen Shot 2020-04-29 at 10 10 45 AM" src="https://user-images.githubusercontent.com/1036433/80612792-1380d780-8a02-11ea-810c-8548663aa2cc.png">

This is the message:

<img width="986" alt="Screen Shot 2020-04-29 at 10 10 30 AM" src="https://user-images.githubusercontent.com/1036433/80612840-1e3b6c80-8a02-11ea-83b7-eec1a9756c7c.png">

**Comment by joewhitsitt** [comment]
We have encountered something similar before. I will look into this.
