### ISSUE TITLE
Investigate adding style options for uids_base accordion

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#1482]
The brand.uiowa.edu team has requested gray, gold, and black variations of the accordion in UIDS.  Is it possible to add a styles field to the accordion paragraph settings?

<img width="1230" alt="Screen Shot 2020-04-29 at 12 18 45 PM" src="https://user-images.githubusercontent.com/1036433/80626330-e63d2500-8a13-11ea-8e51-eb7459810576.png">

**Comment by joewhitsitt** [comment]
The styles field already exists for each of the paragraph bundles, but we didn't have any 'dynamic' classes for accordion. If there are classes are ready in uids for this, we can use `uip_classes_allowed_values()`

https://github.com/uiowa/uiowa/blob/master/docroot/modules/custom/sitenow_paragraphs/sitenow_paragraphs.module#L237

and create a `hook_uip_classes_alter()` similar to

https://github.com/uiowa/uiowa/blob/master/docroot/modules/custom/sitenow_articles/sitenow_articles.module#L246

in 

https://github.com/uiowa/uiowa/blob/master/docroot/modules/custom/sitenow_paragraphs/modules/sitenow_accordion/sitenow_accordion.module (for everyone)

or

https://github.com/uiowa/uiowa/blob/master/docroot/sites/brand.uiowa.edu/modules/brand_core/brand_core.module (brand only until the theme switches for all)

**Comment by bspeare** [comment]
I'm going to close this for now.  We can always reopen if necessary.   For now, we need to prioritize https://github.com/uiowa/uids/issues/665 for accordions.
