### ISSUE TITLE
IE11 alignment issue with featured content block

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#1483]
https://university-shared-services.fo.uiowa.edu/uss-contacts-strategic-communications

They are displaying people in the featured content block and there is an alignment issue in IE.

**Comment by joewhitsitt** [comment]
Screenshot or it didn't happen...

**Comment by briand44** [comment]
![Screen Shot 2020-04-29 at 2 12 47 PM](https://user-images.githubusercontent.com/1017022/80636855-b5fd8280-8a23-11ea-8164-039568cc0ba0.png)

**Comment by briand44** [comment]
There is an email in its-web asking about the progress of this bug. When we have a fix in place we should communicate it out to them. Thanks
