### ISSUE TITLE
Change custom block type labels to hidden for uiowa_blocks 

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#1484]
# Problem

The labels for the custom block type fields used on uiowa.edu have not be set to  `-Hidden-` yet. 

<img width="1934" alt="Screen Shot 2020-04-29 at 1 31 56 PM" src="https://user-images.githubusercontent.com/1036433/80633416-5cdf2000-8a1e-11ea-9183-f461fe79084b.png">

# Proposed Solution

Set all custom block labels to `-Hidden-`.

**Comment by pyrello** [comment]
Do we want to set all the labels to 'Hidden' or 'Visually hidden'?

**Comment by bspeare** [comment]
SiteNow has their labels set to 'Hidden' I believe.

**Comment by pyrello** [comment]
From an a11y perspective, do we want the labels to be there but be visually hidden? @joewhitsitt or @inspector508

**Comment by joewhitsitt** [comment]
Since you are asking me, IMO, it depends on the field. A lot of fields are named with the content editor in mind instead of the the site visitor. (put your content into this bucket).
