### ISSUE TITLE
Convert image format for sitenow card to use responsive large widescreen view mode

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#1499]
# Problem

SiteNow card image needs to be updated to use `Large - Widescreen` view mode for the brand site.

**Comment by joewhitsitt** [comment]
Ugh. I just realized that this is not such an easy issue. We are programmatically rendering images instead of using view modes for these. I will try to think about a path forward.

**Comment by joewhitsitt** [comment]
Realized I used Full - Widescreen instead of Large - Widescreen...
