### ISSUE TITLE
Iowa Superfund - Publication/citation entity type

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#1503]
# Motivation
For the Iowa Superfund Research Program website, we need to create a Publication entity type (content or fragment).

Current example (not using structured data): https://iowasuperfund.uiowa.edu/publications

# Questions
- How can we account for different citations styles? (MLA, APA, etc)
- Can we specify certain fields or does it just need to be a generic text area?

**Comment by joewhitsitt** [comment]
Are you planning on guiding folks through a citation style? MLA, APA, etc? We have used https://www.drupal.org/project/biblio on D7 and regretted it.

What seems to work best for folks is an open text area with minimal formatting options and then using css to properly indent, etc.

I definitely see the use-case for this on campus with some kind of footnotes capability, but we haven't had the time to move forward with it.

**Comment by pyrello** [comment]
Its been long enough since I had to use a citation that I don't remember whether those style difference would result in different fields being present? Possibly try to create something that collects all the necessary info for all those styles and then let the user choose?

I guess I'm trying to resolve the fact that many of the citations on the page linked above do not seem to follow a consistent format.

**Comment by joewhitsitt** [comment]
oh yeah, if you ever have used biblio, not only it is the citation style at which everything is ordered, formatted, displayed or omitted, but the type of source you start off with (article, webpage, video, journal, etc.).

people have definitely requested a reusable, reference from other content, link out to, bucket to put these in if they want to take the time to enter and maintain them.

other drupal examples:
https://education.uiowa.edu/centers/center-research-undergraduate-education/crue-publications
https://teach.its.uiowa.edu/blogs/building-sense-belonging-stem-class

**Comment by pyrello** [comment]
@joewhitsitt Thanks for those examples. This looks like something that could benefit a variety of websites.

Is Citation the right thing to call it? Publication doesn't seem quite right to me.

**Comment by pyrello** [comment]
I'm looking back at some work I started on a publication/citation content fragment. In that version, I added an author field, which is a multi-value plain text field.

However, since one of the intended use cases is referencing a publication from a person, I'm wondering how best to handle this? Should the authors field have any connection to people, or should it be static?

**Comment by joewhitsitt** [comment]
Are you breaking up all the components of a citation into separate fields? Sounds like a slippery slope unless we adopt https://www.drupal.org/project/bibcite.

My suggestion is to create a long text minimal format (or even more minimal format (bold, italic, underline, link, indent, sub/super, bullet/order list, special character, clear formatting)) where the entire citation lives. allows easy copy paste entry and then have meta information like person entity reference (optional), tags taxonomy reference (optional), administrative label (aka title required) for searching.

**Comment by pyrello** [comment]
@joewhitsitt I guess my concern with one long text field is that it would invite inconsistencies and limit search-ability. In the link I posted at the beginning, you can see that there is a lot of inconsistency in how the publications are posted, since the user is not sticking to the same format. Also, we wouldn't be able to build any sort of views filters around different fields.

Maybe there is an aspect to this that I am not understanding? Is it that I put the term 'citation' in the title? Would you feel the same way about it if it was just called publication?

**Comment by joewhitsitt** [comment]
Can you post your current field list for this. That might help me understand

**Comment by pyrello** [comment]
* Title of article - plain text field
* Author(s) - unlimited plain text field
* Publication link - link field
* Publication details (title, volume, issue) - plain text field
* Publication date - date field

Fields that I would also be adding to Iowa Superfund:
* DOI - plain text field
* DOI link - link field
* Additional information - text area field
* PMC number - plain text field

I'm not sure what all of these fields are, but these are all ones that might be needed.

**Comment by joewhitsitt** [comment]
Okay, I worry that though this might work for the short term, to handle this for the 80% we are going to need something like bibcite in the future. From my experience, "publication" could be any number of mediums which all have different fields that need to be captured. I wonder how other institutions are handling this?

<img width="215" alt="Screen Shot 2020-11-09 at 10 10 11 AM" src="https://user-images.githubusercontent.com/4663676/98566151-0cba0380-2274-11eb-9073-dec14f0c4cc8.png">

**Comment by mjoneill** [comment]
I think there's a similar need from Education we might want to understand.

On their old site, they had this page: https://education.prod.drupal.uiowa.edu/centers/center-research-undergraduate-education/crue-publications that displayed a list of publication content types and provides organization and filter options.  Some publications may appear in multiple lists.

Since launching their new site, their workflow is to go to their old prod site, make the updates in the back end, then copy and paste the output into the relevant sections of the new site: https://education.uiowa.edu/research/research-centers-and-initiatives/center-research-undergraduate-education/crue-publications

Tagging @briand44 for visibility. It is unlikely education will get rid of their prod site if they are still using it to manage/format content.

**Comment by mjoneill** [comment]
And I see that @joewhitsitt already referenced (further up) the education links I just added (again).  :P

**Comment by joewhitsitt** [comment]
I thought education was starting to keep publication information in directory profiles?

**Comment by mjoneill** [comment]
> I thought education was starting to keep publication information in directory profiles?

I did too. The individual I was discussing with was not aware of any planning around that, but said they need to connect to the rest of the comms team on this.  

I couldn't recall what the latest was from the Directory Profiles group...so there's opportunity for me to connect there as well.

**Comment by pyrello** [comment]
Great time for this conversation to be starting up again since the Iowa Superfund site is going to be back on our radar in the near term.

**Comment by joewhitsitt** [comment]
Bumping this issue https://github.com/uiowa/uiowa/issues/3666 (inline footnotes) as possibly related.

**Comment by pyrello** [comment]
This is bubbling up again because it is going to be the only custom functionality on the Iowa Superfund site. We have most of the rest of the content migrated for it, so this is now the main blocker for being able to launch the new version of the site.

I'm hoping we can try to solve this as a platform feature, or at least a feature split, but I guess if that doesn't happen, I may just need to add some version of this to a site split.

**Comment by briand44** [comment]
See if Esploro is an option.

**Comment by briand44** [comment]
Added blocked label until it is determined if Esploro is an option https://iro.uiowa.edu/esploro/research-units.

**Comment by pyrello** [comment]
Sent a message about using Esploro to contacts at the library.

**Comment by pyrello** [comment]
ISRP is going with the Esploro option, so no more work is needed here.
