### ISSUE TITLE
Investigate better display options for media list in LB settings tray

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#1509]
Related to uiowa/uiowa#960.

See if there are options for choosing a different form display mode for a list of images in LB settings tray.

**Comment by pyrello** [comment]
This Lullabot module may provide some insights into how this can be altered: https://github.com/Lullabot/entity_browser_block_layout

**Comment by joewhitsitt** [comment]
Can we close this issue? I think it was created before v3 and have sorted out several issues related to the media reference fields within layout builder.
