### ISSUE TITLE
Investigate Fragments module

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#1511]
# Problem
There are use cases where we may want to have fragments of content that are not created using custom block types. The de facto standard for this type of thing is currently Paragraphs, but Paragraphs has some limitations and drawbacks. Notably, paragraphs cannot be created outside the context of a parent node.

# Proposed Solution
Investigate the Fragments module to see whether it is a better fit for the use cases where we need this type of content fragments.
https://www.drupal.org/project/fragments

**Comment by joewhitsitt** [comment]
I took a look at this module briefly last week and I don't see a whole lot of a difference between using this and creating our own custom content entity that allows different bundles.

The one thing I see beneficial is that they figured out what to call it. Alternatively, I thought "Bits" works.

I am starting to see a lot of use-cases for something like this and will mention them over on https://github.com/uiowa/uiowa/issues/2096

**Comment by pyrello** [comment]
The main value of this module is that it has already done the work of putting all the admin UI in place for creating stuff like this, if we roll our own, we'll have to create and maintain that.

**Comment by pyrello** [comment]
I think the work of this issue is done and follow-up can be continued at #2096

**Comment by joewhitsitt** [comment]
With only two sites using the Fragments module, we would probably end up maintaining it anyway. Views makes admin ui's pretty easy in D8/9 and allows us to build it how we want:

> Weirdly, the description field is required for a fragment type, which is annoying

`drush generate` does most of the initial creation work.

**Comment by pyrello** [comment]
I look forward to your demo on this subject, since I know not of what you speak! :)

**Comment by joewhitsitt** [comment]
<img width="434" alt="Screen Shot 2020-11-23 at 2 59 34 PM" src="https://user-images.githubusercontent.com/4663676/100014802-8f76ae80-2d9c-11eb-9cc6-e33bbe9da31b.png">

😜

**Comment by pyrello** [comment]
Demos speak louder than pictures :)
