### ISSUE TITLE
How dates/time should work

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#1515]
Related issues: uiowa/uiowa#1514, uiowa/uiowa#1513, uiowa/uiowa01#283, uiowa/uiowa01#304

After doing a deep dive into the current state of the date/time field ecosystem in D8, there is a lot to parse out, both in terms of where things are at, but also with regard to where things seem likely to go. I thought I would start by trying to articulate how I think the experience of entering dates (and optionally times) should work.

* (Start) Date is required
* (Start) Date defaults to the current date
* (Start) Time is optional
* Either: 
  * (Start) Time field is left blank by default
  * (Start) Time field is hidden by default and can be shown with a link that says "Add time" and can be removed again with a link that says "Remove time"
    <img width="434" alt="Screen Shot 2019-12-31 at 12 08 00 PM" src="https://user-images.githubusercontent.com/709009/71630181-4e474000-2bc7-11ea-8916-14c32a0f060d.png">
    <img width="548" alt="Screen Shot 2019-12-31 at 12 14 52 PM" src="https://user-images.githubusercontent.com/709009/71630189-569f7b00-2bc7-11ea-8db3-f0f4daf7b267.png">
* End date is optional (if applicable)
* End date field is hidden by default and can be shown with a link that says "Add end date" and can be removed again with a link that says "Remove end date"
  <img width="851" alt="Screen Shot 2019-12-31 at 12 24 40 PM" src="https://user-images.githubusercontent.com/709009/71630457-b8acb000-2bc8-11ea-9b99-591c9c85b050.png">
  <img width="845" alt="Screen Shot 2019-12-31 at 12 25 00 PM" src="https://user-images.githubusercontent.com/709009/71630465-be09fa80-2bc8-11ea-9b30-57678976bfad.png">
* End time is optional
* End time uses the same UI convention as (start) time
* Seconds should not ever be shown to the user in forms or rendered output unless it is a purely administrative field

**Comment by joewhitsitt** [comment]
Now that we have move forward with smart_date and are considering https://github.com/uiowa/uiowa/issues/4320, is this issue still needed?

**Comment by pyrello** [comment]
Nah
