### ISSUE TITLE
Lock header in LB for non-admin users

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#1523]
Possibly using this module: https://www.drupal.org/project/layout_builder_lock

**Comment by richardbporter** [comment]
This module works and allows admins to override things since they have the only permission. I'm seeing some wonkiness with lb_direct_add buttons in the locked section though.

**Comment by richardbporter** [comment]
What lock settings do we want? Here is what I set initially.

- [x] Do not allow updating default blocks
- [x] Do not allow deleting default blocks
- [x] Do not allow moving default blocks
- [x] Do not allow adding new blocks
- [ ] Do not allow configuring the section
- [x] Do not allow adding a new section before this section
- [ ] Do not allow adding a new section after this section
- [x] Do not allow moving blocks into this section
