### ISSUE TITLE
Tour and UIDS Header Z-Index Conflict

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#1532]
## Problem
The uids header has a z-index of 400, while frontend tours have a z-index of 101.

<img width="708" alt="Screen Shot 2020-05-05 at 9 44 26 AM" src="https://user-images.githubusercontent.com/4663676/81079479-37866200-8eb5-11ea-8a03-854222f65669.png">

## Replicate:
/?tour=1 on any frontend page

## Proposed Solution
Check with @bspeare to see if there is a reason for such a high z-index for the header. If so, bump the tours to 401 or higher.

**Comment by joewhitsitt** [comment]
Looks like @bspeare was addressing this here as well:
https://github.com/uiowa/uiowa/pull/1539

**Comment by bspeare** [comment]
As @joewhitsitt noted in https://github.com/uiowa/uiowa/pull/1539#pullrequestreview-408545282 it looks like the z-index for `.joyride-tip-guide` will need to be 502 to get past the admin bar and the superfish module css.

**Comment by joewhitsitt** [comment]
This fix got merged in: https://github.com/uiowa/uiowa/pull/1539/commits/fb15aa54deb4eb2212399fbe7bc693f8ee7c8b5b
