### ISSUE TITLE
Google Custom Search Result Styles in UIDS_Base

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#1549]

**Comment by bspeare** [comment]
@joewhitsitt Here are some thoughts on the styling:

- Remove all of the padding and make results line up with Page title
- Remove borders, lines
- Change colors
- Add more spacing between each result
- Increase font size to something like 30px/25px/18px
- Change font to Roboto
- You could use the card mixins as a starting place: https://uiowa.github.io/uids/components/detail/card--no_image.html

<img width="1867" alt="Screen Shot 2020-05-11 at 1 48 04 PM" src="https://user-images.githubusercontent.com/1036433/81599924-8721cd80-938e-11ea-9ab3-7aee995e30e5.png">

**Comment by bspeare** [comment]
- Black and gold search button (is possible).
- Increase line-height for results.

**Comment by bspeare** [comment]
- Increase search input and search button to match something closer to https://uiowa.github.io/uids/components/detail/search.html
