### ISSUE TITLE
Change environment indicator colors to match brand

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#1556]
These are hex values set in settings: https://github.com/uiowa/uiowa/blob/2557c1dfc2f289465e6363cf6c6951dd6560dab6/docroot/sites/settings/sitenow.settings.php#L15-L30

Multiple people have complained about them. We should change them to colors set in UIDS.

**Comment by richardbporter** [comment]
@bspeare have any colors in mind?

**Comment by bspeare** [comment]
I'll take a look today.

**Comment by bspeare** [comment]
If we are using the brand manual colors, I would probably use these as replacements.   What do you think?   What are the major complaints that you hear from people?

- local - Green -  #00664F
- dev - Blue - #00558C
- test - Gray - #63666A
- prod - Orange/red - #BD472A
