### ISSUE TITLE
Evaluate alternative local development stack

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#157]
Drupal VM is recommended by BLT.

**Comment by joewhitsitt** [comment]
I still like Lando but the inconsistency across computers has been a real headache. I think a combination of homebrew/drush run server and port mapping is a pretty good alternative as long as Acquia DevDesktop (Drupal 7) stays out of the way

**Comment by joewhitsitt** [comment]
i have switched from lando to drush run server mainly because i was tired of typing my ssh passphrase and i was having troubles with getting my old mbp laptop setup.

**Comment by richardbporter** [comment]
Rolling with RS for now with Lando on hold for various reasons.
