### ISSUE TITLE
Allow post deployment to proceed after failing config status check

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#1575]
Should post deploy fail on the "config is different" check? This shows as an error both locally and in production, but is really a warning that config needs to be fixed. The only way to resolve it is to merge another PR and in the meantime, no sites that come after will get database updates or config updates as part  that release. It seems like this could potentially be just a notification instead that allows the post deploy to move on to the next site.

**Comment by pyrello** [comment]
Is it possible that we could use this module to notify us in the event that deployment results in config that is out of sync? @richardbporter

**Comment by richardbporter** [comment]
We may be able to catch any exceptions thrown when we invoke the `drupal:update` process and then exit with the appropriate code at the end of multisite loop. That would mark the job as a failure but continue on through each site. Hopefully.

https://github.com/uiowa/uiowa/blob/de654ddf1c8dffe8f6e7b35b703e1012701aa015/blt/src/Blt/Plugin/Commands/ReplaceCommands.php#L36
