### ISSUE TITLE
Add a "black background" option in uids_base in addition to of dark gray brand option

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#1591]
# Problem

The brand team has requested to add a black background option. 

<img width="2225" alt="Screen Shot 2020-05-12 at 4 35 06 PM" src="https://user-images.githubusercontent.com/1036433/81748120-e951ff80-946e-11ea-8f66-308d3373390e.png">

# Proposed Solution

- Add a `Black Background` option to use `$secondary` background color.
- Switch `Dark Background` to use PMS Cool Gray 10 `#63666A`. 

<img width="1405" alt="Screen Shot 2020-05-12 at 4 35 33 PM" src="https://user-images.githubusercontent.com/1036433/81748130-ee16b380-946e-11ea-97f4-789d9ecfc902.png">

<img width="2235" alt="Screen Shot 2020-05-12 at 4 36 46 PM" src="https://user-images.githubusercontent.com/1036433/81748146-f1aa3a80-946e-11ea-841f-45cf4b55abcc.png">

**Comment by joewhitsitt** [comment]
Is there not supposed to be support for a dark gray anymore (PMS Cool Gray 10)? I would be more in favor of adjusting that and adding a black option.

https://brand.prod.drupal.uiowa.edu/color

**Comment by bspeare** [comment]
That is a good option too!

**Comment by bspeare** [comment]
@joewhitsitt I updated the issue to reflect your comment.
