### ISSUE TITLE
Convert HR's Article Featured Image to Responsive View Mode

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#1606]
## Problem

HR's article featured image stuff is split and is still using the sitenow 16:9 image

## Proposed Solution
Switch the article full to use the same image settings as default sitenow.

If sitenow 16:9 gets deprecated then this will be mandatory.

**Comment by joewhitsitt** [comment]
Need to check whether this is an current issue with the changes being done in https://github.com/uiowa/uiowa/pull/1622

**Comment by richardbporter** [comment]
I'm assuming this would be necessary for v3 conversion?

**Comment by joewhitsitt** [comment]
This will be needed for uids_base adoption regardless of v2/v3
