### ISSUE TITLE
Add all-day functionality to event date field on event block

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#1607]
# Problem

There is no "all-day" option for the event date field on uiowa.edu

# Proposed solution

Add "all-day" module?

**Comment by bspeare** [comment]
@mark-bennett-uiowa Do you recall how to set an "All-day" option on the core date field?

**Comment by mark-bennett-uiowa** [comment]
@bspeare It required an additional module, and I believe there were a couple to choose from: [https://www.drupal.org/project/smart_date](https://www.drupal.org/project/smart_date) and [https://www.drupal.org/project/date_all_day](https://www.drupal.org/project/date_all_day), but the date_all_day hasnt been updated in awhile.

**Comment by briand44** [comment]
Closing in favor of https://github.com/uiowa/uiowa/issues/3334
