### ISSUE TITLE
Align background image section text to the bottom on mobile instead of center

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#1610]
# Problem

Image captions obscure the image by centering on mobile as set in the section settings. 

<img width="486" alt="screen_shot_2020-04-16_at_4 55 23_pm" src="https://user-images.githubusercontent.com/1036433/81962994-225ab300-95da-11ea-9cb6-10cabb84e73c.png">

<img width="526" alt="Screen Shot 2020-05-14 at 11 56 54 AM" src="https://user-images.githubusercontent.com/1036433/81963157-57ff9c00-95da-11ea-97e8-f095f036cde0.png">

# Proposed Solution

Is there an additional setting to add to set mobile alignment top or bottom?

**Comment by joewhitsitt** [comment]
I'd like to get more thoughts on this but I am resistant to adding "mobile" settings to things. I assume that the majority of our users aren't designers or knowledgable about responsive design (e.g. what a mobile breakpoint is) and I also don't want to overwhelm editors with options. We were originally worried about putting in all of those existing flex/alignment options. So far with customers, "section height" (min-height for thin banners to large viewport height type effects) seems to be the next big request.

Additionally, section content could be anything... I have seen a full page of content with a section background image. Not pretty, but the whole alignment of that content becomes moot.

**Comment by joewhitsitt** [comment]
If this is scoped only to brand.uiowa.edu as a custom site customer, I could see a section style option for this without adding an additional field that forks the paragraph bundle.

**Comment by bspeare** [comment]
@joewhitsitt No problem.  I just wanted to create an issue surrounding the question posted in Slack a few weeks ago to see what was possible.  I agree, it's hard to know how the other components would respond to this setting.

**Comment by bspeare** [comment]
@joewhitsitt can we mark this as closed, won't fix?

**Comment by joewhitsitt** [comment]
Yes!
