### ISSUE TITLE
Alert close button is not working in uids_base

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#1620]
# Problem 

You cannot close an alert in uids_base. 

<img width="1544" alt="Screen Shot 2020-05-15 at 12 15 42 PM" src="https://user-images.githubusercontent.com/1036433/82078001-002e6700-96a6-11ea-82b2-3503ffbb9033.png">

# Proposed Solution

Investigate fixing the JS so that alerts can be dismissed.

**Comment by richardbporter** [comment]
The green X? I FWIW, I didn't think that was clickable. Thought it was just an icon. I must be used to close icons in the top right.

**Comment by bspeare** [comment]
@richardbporter It looks like a remnant from `uiowa_bootstrap` where you had bootstrap `alert-dismissible` JS.  Anyone want to attach some JavaScript to the `<button>` for closing the alert? https://github.com/uiowa/uiowa/blob/551f4c4f7d27740522f3d9e7d2ab8c81e571429b/docroot/themes/custom/uids_base/templates/misc/status-messages.html.twig#L40

**Comment by richardbporter** [comment]
I can. I think we should still be using jQuery until/if we rip it out. AFAIK, it is still a hard dependency of Big Pipe.

**Comment by richardbporter** [comment]
Thoughts on if this should be a library specific for status-messages or something abstract in uids_base.js to make 'alert-dismissible' reusable?

**Comment by bspeare** [comment]
Abstract sounds preferable.   What do you prefer?

**Comment by richardbporter** [comment]
Lets cross that bridge when we get there.
