### ISSUE TITLE
Color full section background containing a fixed-width container in uids_base

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#1623]
On the frontpage of [https://icsa-temp.prod.drupal.uiowa.edu/](https://icsa-temp.prod.drupal.uiowa.edu/) you will see the yellow background section with the link to NRCFCP. I want that to have an edge to edge yellow background, but condense the text and button link to a fixed-width container rather than having it expand to the full section width. If I set the style on that section to edge-to-edge it doesnt color the full width section background.

**Comment by pyrello** [comment]
I'm not completely sure, but I feel like this is now the default behavior. Any section background will span the entire width of the page, regardless of how wide the container is.

@mark-bennett-uiowa @bspeare Does this seem right?

**Comment by bspeare** [comment]
This should be fixed now.

**Comment by bspeare** [comment]
Closing this for now.
