### ISSUE TITLE
Revisit split permissions configuration

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#1626]
## Problem

We have entered into the growing-pains phase of split permissions. One little piece of config or functionality could trigger a split of permissions. As the number of roles increases and the number of sites splitting config we either need to figure out a better way of dealing with permission splits. Gone are the days where I was knowledgable about all of the custom sites on the service (hr, brand)

Permissions is the first major example of this, but other things will become more visible over time like basic page fields.

<img width="694" alt="Screen Shot 2020-05-18 at 11 31 25 AM" src="https://user-images.githubusercontent.com/4663676/82237620-914a4b80-98fb-11ea-8ba3-6fcb4955d652.png">

_this list is only going to grow_

A number of questions come up as I try to enable a new module for the service and set permissions accordingly.

- Should this split config get the new permission?
- Since it isn't required functionality, do they want it?
- What other things do I need to know about this site before making this change?
- If I make this change, how do I know the right person reviewing the PR will sign off on it?
- Should it just be a changelog type thing and notify folks to change things on their own time?
- Should I just make separate issues, tag the sites affected and leave it to the developer to decide?

I thought maybe once a site splits, their permissions should just be ignored and stay active config, but if we wanted to send out an updated permission to all, this would be an update hook and we would still run into the same issue of what sites should get it.

Should there be some kind of flag configuration in uiowa_core that states the "kind" of site it is like "Accepts all new base config unless it conflicts." But then if it conflicts, what then?

**Comment by joewhitsitt** [comment]
Another thought I just had, was to double down on the number of roles and create webmaster_base, editor_base, etc. Make those pretty stock and then let most splits (unique content type permissions, etc.) be site specific roles with site specific permissions. Two initial problems I see is the number of roles (max_input_vars) and making sure the weights don't affect the base role configuration so those can stay synced.

**Comment by pyrello** [comment]
Just dropping this here to review later: https://www.drupal.org/project/config_role_split

**Comment by pyrello** [comment]
@joewhitsitt Do you think this is effectively handled by #4137?

**Comment by joewhitsitt** [comment]
@pyrello from what I have seen, yes. Additionally, the work done to remove empty config directories also provides more visibility into what sites are not default.
