### ISSUE TITLE
Footer menu confusion between Primary/Secondary Footer Links and Footer primary/secondary/tertiary?

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#1628]
In the Basic site information screen, there is a section that links to these footer menus:
<img width="904" alt="Screen Shot 2020-05-18 at 2 22 12 PM" src="https://user-images.githubusercontent.com/3067017/82251617-23aa1980-9913-11ea-9368-645d500fe729.png">

Should these be changed to point to Footer primary, Footer secondary, and Footer tertiary menus instead?

**Comment by joewhitsitt** [comment]
We are kind of in a middle ground here. I don't know if this is a bug. SiteNow still uses the old menus and uids_base theme sites use a different set, I will add this to the https://github.com/uiowa/uiowa/issues/1611 issue

**Comment by richardbporter** [comment]
Sounds like this can be closed in favor of #1611, which might be happening soon-ish.
