### ISSUE TITLE
Adjust placement of search and top links in uids_base if not using toggle navigation

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#1633]
# Problem 

The top links and search bar does not adjust to display back within the container if the Toggle Navigation is not used. 

<img width="1854" alt="Screen Shot 2020-05-18 at 4 23 05 PM" src="https://user-images.githubusercontent.com/1036433/82261608-f4040d00-9924-11ea-84b9-b2af4f8cce6f.png">

# Proposed Solution

Adjust Search button and top links to appear within the page container when the Toggle Navigation is not in use. 

<img width="1712" alt="Screen Shot 2020-05-18 at 4 25 32 PM" src="https://user-images.githubusercontent.com/1036433/82261878-755b9f80-9925-11ea-86ba-3de102b90ace.png">

**Comment by mark-bennett-uiowa** [comment]
Yes, please! Thanks bud.
