### ISSUE TITLE
Adjust spacing on alert icon in uids_base

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#1634]
# Problem

The alert icon is too close to the alert heading. 

<img width="1359" alt="Screen Shot 2020-05-18 at 4 56 06 PM" src="https://user-images.githubusercontent.com/1036433/82263529-b903d880-9928-11ea-8eab-83a807342eb3.png">

# Proposed solution

Update spacing in uids_base or alerts module.

**Comment by richardbporter** [comment]
Spacing seems ok to me on stage/local.

![image](https://user-images.githubusercontent.com/1068523/82480421-64339f80-9a99-11ea-8b2b-ab257906e32e.png)

Where was this? What heading level?

**Comment by richardbporter** [comment]
Tested Chrome, Safari and FF on OSX.

**Comment by richardbporter** [comment]
Not able to reproduce this at the moment.
