### ISSUE TITLE
Update blt command to remove 'sitenow' when generating site provision command

### ISSUE THREAD

**Issue by dnkemper** [uiowa/uiowa#1637]
Update blt command to remove 'sitenow' when generating site provision command

**Comment by richardbporter** [comment]
Are you referring to what the request form prints out? If so, that can be changed in the webform UI on prod. Webform config is no longer tracked in the sitenow.uiowa.edu split.

**Comment by dnkemper** [comment]
@richardbporter Yes. I noticed that and changed it on prod but didn't want to close issue until I double checked. Thank you very much!

**Comment by richardbporter** [comment]
Cool, thanks!
