### ISSUE TITLE
Social media embed overflow and sizing

### ISSUE THREAD

**Issue by cory-skeers** [uiowa/uiowa#1656]
Social media post embeds overflow their parent containers. The "Display as" sizing doesn't appear to be applying, either--sizing constant for full, large, medium, and small.

![image](https://user-images.githubusercontent.com/49074566/82565395-fb533280-9b3f-11ea-812d-d79ef3adff1c.png)

Possibly related to discussions around #478

**Comment by joewhitsitt** [comment]
the embeds i found have specific min-widths (all different) which we can't control very well. we see about an overflow hidden on the drupal-entity/drupal-media wrapper or something similar.

**Comment by cory-skeers** [comment]
There's an (old) open issue with media_entity_twitter for supporting Twitter API parameters: https://www.drupal.org/project/media_entity_twitter/issues/2939863. 

If no width parameter is passed, defaults to 500px. Adding a width parameter helps some of the overlap range, and adds some responsiveness (394px to 500px), but it still stops above the min-width (220px).

FB has fewer available options.

**Comment by cory-skeers** [comment]
Culprit seems to be the <article> tag between the embed widget and the parent container added by media_entity with a width: 100%--with or without the width parameter in the embed API, if the embeds are added directly (not using media_entity_*), sizing is responsive and works appropriately. Direct embedding requires allowing <source> or work to attach the proper js, which is normally handled through the media_embed_twitter module.

Removing myself for now--working on alternatives for client.

**Comment by joewhitsitt** [comment]
Does this also affect uids_base @cory-skeers?

**Comment by cory-skeers** [comment]
~Updated the label--it does affect uids_base as well.~

Spoke to soon! The width is static, which is maybe not the prettiest/ideal solution, but it doesn't overflow in uids_base, so not a bug.

**Comment by joewhitsitt** [comment]
closing as this only relates to uiowa_bootstrap which is no longer
