### ISSUE TITLE
UIDS_Base WYSIWYG Styles

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#1662]
## Problem
WYSIWYG text areas are currently unstyled and don't offer a "preview" of uids_base rendering.

## Proposed Solution
Load the theme styles similarly to how uiowa_bootstrap did.

**Comment by cory-skeers** [comment]
@joewhitsitt Is this just getting the current SiteNow styles (alerts and Lead) rendered in the editor, or also updating paragraphs styles to include uids styles (bold and light intro, etc.)?

**Comment by joewhitsitt** [comment]
At a basic level, we need theme css like we did in uiowa_bootstrap

docroot/themes/custom/uiowa_bootstrap/uiowa_bootstrap.info.yml:
```
ckeditor_stylesheets:
  - assets/css/uiowa_bootstrap.css
```

The question is, is there one aggregated css file to use? uids_base uses on-demand css.

**Comment by cory-skeers** [comment]
Got a PR (#1712) open for current SiteNow styles.

Adding the additional uids styles would need new styles added to the text editor config list and additional css loads, with possibly a more robust method of adding them if we're anticipating more styles to be added to the uids.
