### ISSUE TITLE
Confirm Webform Settings regarding file uploads

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#1664]
We are seeing some odd default extensions and file size defaults.

I thought we addressed this in https://github.com/uiowa/uiowa/issues/353

Wonder if there was a configuration regression when we update webform.

**Comment by joewhitsitt** [comment]
Added to the +1 of the homepage project, but if someone is able, work on this can happen sooner rather than later.

**Comment by richardbporter** [comment]
The other issue says no action was needed. I think we set a default max upload size of 50 mb and remove a few extensions like dmg, jar and rar.

Another option would be to match exactly our media types but I don't think these file upload will be uploaded to the public file system and/or rendered for frontend users.
