### ISSUE TITLE
Bouncy Top Bar on Mobile and Desktop Safari

### ISSUE THREAD

**Issue by quamsta** [uiowa/uiowa#1665]
Hi all, I was playing around with the new homepage on some of my devices and I noticed that the sticky header that hides itself upon scrolling up gets a little "bouncy" if you use any kind of inertial scrolling on Safari and scroll quickly from the middle of the page to the top. It sort of slides down twice and sometimes a third time.

I'm attaching a video of this in action on desktop Safari, but it seems to happen on mobile Safari on iPads as well. This does not seem to occur at all on Chrome.

![ezgif-2-db590e69f1eb](https://user-images.githubusercontent.com/472923/82606194-4db24480-9b7c-11ea-8dba-ea17f07387e9.gif)

**Comment by bspeare** [comment]
Thanks @quamsta!

**Comment by bspeare** [comment]
@quamsta We deployed a change to the header on https://uiowa.edu/ that sets the scroll to start once the height of the header has been scrolled through.   Can you take a look at this on your iPad?

**Comment by quamsta** [comment]
@bspeare Oops, I did test this, but forgot to reply. It seems to be fixed on all of my devices I was seeing it occur on. Thanks for looking at this, Ben!

**Comment by bspeare** [comment]
@quamsta Thanks for verifying!
