### ISSUE TITLE
Policy - custom theme development

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#1671]
Need something for this

Could be an add-on to https://sitenow.uiowa.edu/policies#custom-engagements

**Comment by joewhitsitt** [comment]
@briand44 mentioned he has already sent emails with text that could be used for this

**Comment by richardbporter** [comment]
I feel like that kinda covers it in a nutshell. All of those policies probably need to be revisited.

**Comment by pyrello** [comment]
Just to clarify, is a custom engagement an instance where a customer hires an outside vendor to do work on the platform? Or is it indicating that the customer can pay OSC to do stuff, which seem incorrect? @mjoneill you might want to take a look.

**Comment by bspeare** [comment]
I think this is handled by https://brand.uiowa.edu/applying-brand/web and future planned updates to that page, so I am going to close this issue.
