### ISSUE TITLE
A11y adjustments for autoplay video loop

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#1680]
# Proposed Solution

- [x]  Set `prefers-reduced-motion` in JavaScript. 
- [x]  Set a cookie to remember whether pause was pressed? https://github.com/uiowa/uiowa/pull/1719
- [x]  Add aria label to play/pause button https://github.com/uiowa/uids/pull/228
- [x]  Move play/pause button top the bottom left of the video so that it can be paused https://github.com/uiowa/uids/pull/225

prefers-reduced-motion (https://web.dev/prefers-reduced-motion/)

https://developers.google.com/web/updates/2017/09/autoplay-policy-changes#audiovideo_elements

https://support.mozilla.org/en-US/kb/block-autoplay

**Comment by bspeare** [comment]
# Proposed Solution

1.  Set `prefers-reduced-motion` in JavaScript. 
2.  Set a cookie to remember whether pause was pressed?
3.  Anything else?

**Comment by pyrello** [comment]
To test this, there is an option in Google Chrome console to emulate this setting: https://developers.google.com/web/updates/2019/10/devtools#userpreferences
