### ISSUE TITLE
Anchor links possible with the current WYSIWYG?

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#1682]
Outside of updating each and every spite split for CLAS sites, are anchor links possible inside WYSIWYG editors? If not, could we consider adding them?

**Comment by joewhitsitt** [comment]
We have started an issue over here: https://github.com/uiowa/uiowa/issues/1412.

There is no button solution yet if that is what you are asking. LinkIt allows #anchor-name additions to the autocomplete field.

**Comment by joewhitsitt** [comment]
Closing in favor of #1412
