### ISSUE TITLE
Brand Lockup generator - Removing line break deletes text.

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#1686]
## Problem
If there are multiple lines and the editor tries to remove the line break, it deletes all of the text from the following line.

![out](https://user-images.githubusercontent.com/4663676/82952519-b9c2ed00-9f6e-11ea-9454-3b7fedb854b4.gif)

Not sure if this can be fixed given all of the validation and line length calculations.

**Comment by GaryRidgway** [comment]
[This](https://github.com/uiowa/uiowa/tree/brand-validation-update) should solve this for forward deletes and backward deletes, but it creates another issue that appears here:

![out](https://i.gyazo.com/1cab89ddd1654fb9236a2cf5cc24fb1a.gif)

where the lines text will get truncated if it is longer than the maximum length allowed by the line. This leads me to believe there may be a need for an undo functionality within the validation, but i am not sure that is worth it.

**Comment by joewhitsitt** [comment]
Sondra:
>I don't think you need to do the work of an "undo" functionality. People seem to be understanding there is a line limit in play and I think will realize why that is happening.

**Comment by GaryRidgway** [comment]
PR #1743 closed this
