### ISSUE TITLE
Embed Google Calendar

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#1689]
Heidi Schmitt with the Honors Program (https://honors.uiowa.edu) requested this functionality. I am not sure if they would be willing to fund this but making note of it here in case we get other requests for this functionality.

Added discussion needed label as we will want to discuss if this is something we should support or if we are only supporting events that are added to the University Events Calendar.

**Comment by richardbporter** [comment]
These would not be on-brand. 👎🏻

**Comment by joewhitsitt** [comment]
With recent discussions, isn't our stance on these, "no?"

>Google products are not supported by ITS. They are off-brand. We also have other event functionality (content.uiowa.edu/events.uiowa.edu and a local event content type that can be turned on for a v3 website). Ideally work should be done to further support integration with ITS supported Outlook and displayed in an accessible way.

https://wiki.uiowa.edu/display/drupaldev/Embedded+Content+Decision+Tree

**Comment by briand44** [comment]
Closing this as it currently isn't something we plan to support at this time. If we need to revisit this at a later date we can open it back up.
