### ISSUE TITLE
tour button colors aren't accessible with hawkeye scss partials

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#169]
The yellow button needs darker text color.
<img width="351" alt="Screen Shot 2019-05-13 at 8 52 53 AM" src="https://user-images.githubusercontent.com/4663676/57626922-8593ae80-755c-11e9-8b9c-131c9862c856.png">

**Comment by richardbporter** [comment]
Is it odd that we have different styles for UX components on the front vs. back end?
