### ISSUE TITLE
Revise moderation documentation

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#1694]
https://sitenow.uiowa.edu/documentation/content-moderation-and-workflow

Folks are getting confused that creating a new draft off existing published content does not "unpublish" the content.

A better wording of the following is needed:

Draft off existing published = A copy to work with while published version remains.
Create/Draft new content = An unpublished version.
Archived = Unpublished/Archive state. Not visible to anyone. New drafts can be created off archived content.

**Comment by cory-skeers** [comment]
Review revision is available; edits and comments welcome.

Also updated hierarchy to include an h2 for moderation states section and h3s for the various states.

**Comment by joewhitsitt** [comment]
Thanks for taking this on. Captures it. 👍 

Bonus: remove all caps now that these are headers

Publish/close

**Comment by cory-skeers** [comment]
Edits published! Closing out.
