### ISSUE TITLE
section background color is causing the wrong card body text color

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#170]
i forget the magical combination, but we should run through all the combinations again to ensure text color for content blocks is accessible on the various section background colors with or without the semi-transparent option.

**Comment by joewhitsitt** [comment]
https://github.com/uiowa/uiowa/pull/188/commits/b4db0e64a606f42913af66a3defd1b9dddc14f09

**Comment by cory-skeers** [comment]
Cards on a Dark Gray background appear with white text on a white background; not a problem with Light Gray or Yellow backgrounds.

**Comment by joewhitsitt** [comment]
this should now be fixed in DEV
