### ISSUE TITLE
Pathauto not creating proper nested path

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#1701]
Assume we are placing all nodes under the Main Menu, and there exists the following structure:
Main Menu
 -- About (/about)
 -- People (/people)
 -- Undergraduate Programs (/undergraduate)
 -- Graduate Programs (/graduate)
 ---- Admissions (1)
 -- Resources

Note that the Undergraduate and Graduate Program pages have been given custom URL aliases . When a new node is added underneath one of them, and the "Generate automatic URL alias" checkbox is checked within the URL alias tab for this child node, the automatic path created does not carry over the custom URL from the parent.

The path for Admission (1 above) should be /undergraduate/admissions, however the automatic path created is /undergraduate-programs/admissions. The alias pattern is currently set to:
`[node:menu-link:parents:join-path]/[node:title]`
Is this the proper pattern? [https://www.drupal.org/project/token/issues/2769299](https://www.drupal.org/project/token/issues/2769299) lists an issue but it was from 4 years ago, and they say it was fixed.

**Comment by mark-bennett-uiowa** [comment]
@pyrello @bspeare @joewhitsitt @richardbporter Should this be set to [node:menu-link:parent:url:path]/[node:title] instead? The token as it is now is not taking into account pathauto generated paths for parents. Therefore, for any nodes under a custom path, I need to continue to create custom paths, even if I dont need to.

Say we have this structure:
Undergraduate Programs (/undergraduate)
 -- Majors, Minors, and Certificates (_no link_, just a parent group in menu)
 ---- Bachelor of Arts in American Studies (/undergraduate/ba-american-studies)
 ------ Test Page (???) <------ trying to get this path correct, based off of parent paths.
 ---- Bachelor of Science in American Studies (/undergraduate/bs-american-studies)

[node:menu-link:parents:join-path]/[node:title] as it is now would give: http://americanstudies.local.drupal.uiowa.edu/undergraduate-programs/majors-minors-and-certificates/bachelor-arts-american-studies/test-page ❌

[node:menu-link:parent:url]/[node:title] gives the following:
http://americanstudies.local.drupal.uiowa.edu/http%3A/americanstudies.local.drupal.uiowa.edu/undergraduate/ba-american-studies/test-page ❌

[node:menu-link:parent:url:path]/[node:title] gives the following:
http://americanstudies.local.drupal.uiowa.edu/undergraduate/ba-american-studies/test-page ✅

So I tested this out even further with the following structure:
Undergraduate Programs (/undergraduate)
 -- Majors, Minors, and Certificates (no link, just a parent group in menu)
 ---- Bachelor of Arts in American Studies (/undergraduate/ba-american-studies)
 ------ Test Page (???)
 -------- New Test Page with Custom path
 ---------- Back to path auto

and it gives me the proper path, even after going back in to give the "New Test Page with Custom path" a new URL path:
http://americanstudies.local.drupal.uiowa.edu/undergraduate/ba-american-studies/test-page/custom/back-path-auto
<img width="1111" alt="Screen Shot 2020-11-12 at 5 57 11 PM" src="https://user-images.githubusercontent.com/3067017/99011094-ec5aa500-2510-11eb-84ef-525933f49e22.png">

**Comment by joewhitsitt** [comment]
@mark-bennett-uiowa thanks for providing these examples. I will have to jog my memory on this, but if I recall, I wasn't super happy with this pattern when I originally set this and ~~I feel like the the tokens were limited when Pathauto first reached a stable release~~ (just saw the drupal issue you linked to... 🤦 ). We also weren't accounting for <nolink> menu items when we hit v2 MVP.

I think if this is the ideal pattern and we want to make this change, we need to make sure redirects are created for existing paths and possibly a send out an email to the SiteNow list communicating the change. Are you able to pull this work yourself and put up a PR?

**Comment by pyrello** [comment]
Should we create redirects for existing pages as part of this update or just put the pattern in place for any pages that are created going forward? In any cases where people used custom URLs instead of the auto-generated ones for this reason, then those are going to have to be updated manually since I don't think we can put together a system for trying to guess which ones were intended to be custom vs. not.

Just updating the pattern might be enough for now.

**Comment by mark-bennett-uiowa** [comment]
@joewhitsitt I should be able to whip up something if I get a chance in the next few days. I agree with @pyrello though that it may just need the pattern update. I wouldn't want to assume what users are expecting for paths, so I prefer avoiding any scripts to change existing custom paths. We could build in a script to update the url alias of all page content (avoid media items and articles/people), or we could just let webmasters do this on their own for the pages they want.

**Comment by joewhitsitt** [comment]
I am pretty sure, redirects will happen on next save. I am just wanting to make sure (test) before we push this to live.
