### ISSUE TITLE
Articles paragraph read more link option

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#171]
Similar to events. If articles view enabled in site-wide settings use that path as default. Otherwise provide an other link option.

**Comment by joewhitsitt** [comment]
The logic was pushed but the field configuration was not... Reopening.

**Comment by dnkemper** [comment]
# Testing

- Style is same as events 'more' link
- Links to 'news' correctly
- If change link within paragraph, it goes to that link correctly

Looks good!
