### ISSUE TITLE
UIDS_Base WYSIWYG Styles Aggregated CSS File

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#1714]
Blocks #1662 
Relates to #1660 

- [x] Styles related to allowed html
- [x] Styles related to style dropdown
- [x] Button styles (bootstrap for now)
- [x] Styles related to other wywisyg buttons (e.g. table, drupal-media, drupal-entity)

When we have a list of individual scss partials that cover this, the uids_base can generate a aggregated css file to use for #1662.

As more, styles apply to the WYSIWYG, we can cover them in the uids_base task and not have to update the info file.

**Comment by cory-skeers** [comment]
Got a base updated in the `i1662-wysiwyg-styles` branch, with the few partials previously identified and the single aggregate css linked in the info.yml.

## Style Dropdown
 - Lead: sitenow/sitenow.scss
 - Alerts (various): alrerts/alerts.scss (paragraphs styling adjustment, and imports _alerts.scss theming from uids)

## Button styles
 - sitenow/sitenow.scss*

## WYSIWYG editor buttons

Strikethroughs indicate no additional styling needed.

- ~~Bold, Italic, Strikethrough~~
- ~~Left, center, right align~~
- ~~Superscript, subscript~~
- ~~Remove format~~
- ~~Insert symbol~~
- Unordered list: uids/components/01 - elements/lists/_lists.scss
  - Allows for additional styling, like uids-component--circle-list class
- Ordered list: uids/components/01 - elements/lists/_lists.scss*
- ~~Un/Indent~~
- ~~Link/remove link~~
- Blockquote: uids/components/01 - elements/blockquote/_blockquote.scss
- Insert table: scss/components/elements/tables/tables.scss (imports _tables.scss, as well as additional paragraphs fix)
- Media entity embed
- Style dropdown
- Format dropdown (paragraphs, h2 - h6): See Additional theming elements
- ~~Source~~
- ~~Show blocks~~
- ~~Undo/redo~~
- ~~hr~~
- ~~Maximize~~

## Additional theming elements

Not strictly required, but can include for a more consistent look and feel in the WYSIWYG (and adds additional classes, such as the uids-component--bold-intro and uids-component--light-intro).
- Paragraph font styling: uids/components/01 - elements/paragraph/_paragraph.scss

**Comment by cory-skeers** [comment]
Current allowable HTML tags are covered by the stylesheets imported for the style dropdown and wysiwyg editor buttons.
