### ISSUE TITLE
Patch to fix media library modal integration with Focal Point

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#1721]
https://www.drupal.org/files/issues/2020-05-26/3094478-39.patch

**Comment by joewhitsitt** [comment]
Don't suppose this is in 8.8.7 that was released today?

**Comment by pyrello** [comment]
This is a patch to the focal_point module: https://www.drupal.org/project/focal_point/issues/3094478

**Comment by joewhitsitt** [comment]
🤦 sorry. tired. signing off for the day

**Comment by pyrello** [comment]
Lol. No worries!

**Comment by joewhitsitt** [comment]
This patch was committed/fixed and we are using 1.5 https://www.drupal.org/project/focal_point/releases/8.x-1.5
