### ISSUE TITLE
Set default favicons in metatag config

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#173]
https://github.com/ITS-UofIowa/uiowa_favicon

see if campus is interested in the module or rename it sitenow_favicon

would be nice to extend to include some SEO image defaults (opengraph, etc.)

**Comment by richardbporter** [comment]
Check if we do this with theme settings.

**Comment by joewhitsitt** [comment]
For now, HR will be launch with a single .ico file of the uiowa dome. This can be a go-live task until we come out with a better solution.

**Comment by richardbporter** [comment]
Metatag module can do this for Apple/Android. Windows mobile is dead. Closing in favor of re-scoped PR #440.
