### ISSUE TITLE
Delete icsa-temp.uiowa.edu site.

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#1735]
I'm not sure if this is still needed but its failing on uiowa01 dev deployments.

**Comment by mark-bennett-uiowa** [comment]
Yes, it can be deleted. Would you like me to take care of this quick?

**Comment by richardbporter** [comment]
Sure.

**Comment by mark-bennett-uiowa** [comment]
Should be fixed with commit #1738
