### ISSUE TITLE
Problems with background color for section or blocks.

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#1739]
NOTE: This came from creating a temporary solution for a program block. Once program blocks are created, I will no longer be using this solution. Thought it would be helpful to catch these issues for the future though.
I hope this screenshot gives enough information as to the issues. The blue text represents a notice of behavior rather than an issue.
1: Section Padding: Top needs to be added to the section to add a colored spacing above first widget in section. I would assume this is intended and doesnt need to be fixed.
2: Uncolored background between two consecutive sections with background color.
3: Background color of card blocks is set to white, which does not show during layout building. Only appears upon save of layout.

To see this live: [https://africanamericanstudies.prod.drupal.uiowa.edu/undergraduate](https://africanamericanstudies.prod.drupal.uiowa.edu/undergraduate)

![Screen Shot 2020-06-04 at 9 32 41 AM](https://user-images.githubusercontent.com/3067017/83773577-4db94680-a64a-11ea-87bb-d80e334b138f.jpg)

**Comment by bspeare** [comment]
A few notes on how this could be addressed:

- If a section has a background color applied, top and bottom padding should automatically be applied.  
- Each section has default bottom margins applied to it.   If there are two consecutive sections with background colors these margins should be stripped out. 
- Card currently has a white a default background color.   The card background should adjust based on the containers background color?

**Comment by mark-bennett-uiowa** [comment]
@bspeare That all sounds great to me, but do we want/need to have a bunch of conditional logic on the styles? I dont want to cause problems with this if I'm just building something out incorrectly.

**Comment by bspeare** [comment]
I think we want those in place so that it is easy for someone to design a section.   @pyrello do you have any thoughts on this?

**Comment by pyrello** [comment]
I think ideally, we have sane default that make it easy to build this out without having to set a lot of overrides. If something outside of those defaults is desired, then that were the overrides come in.

Not sure if this helps clarify.

**Comment by mark-bennett-uiowa** [comment]
This appears fixed (for the gray background) in #2076.
