### ISSUE TITLE
Custom blocks created through block interface do not use inline block templates

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#1740]
# Problem 

Custom blocks created through block interface do not use inline block templates

For example, add a custom CTA block to the pre-footer block region in `uids_base`.

# Proposed Solution

Investigate way to map custom blocks placed through the block interface to use the inline block templates: https://www.drupal.org/forum/support/theme-development/2016-05-12/theming-custom-block-types.

**Comment by pyrello** [comment]
This seems related, at least tangentially, to https://github.com/uiowa/uiowa/pull/1529#issuecomment-624097007

**Comment by bspeare** [comment]
@pyrello I just tested out https://github.com/swentel/block_content_template and it works well.  Did you get to test it yet?  I could set up a demo PR if you want to see how the templates work.   What are your thoughts on using this module?

**Comment by pyrello** [comment]
I'm willing to give it a shot. I just hadn't gotten around to testing it yet because I wasn't immediately a fan of creating a new template namespace.

**Comment by bspeare** [comment]
@pyrello I added a example pr here if you want to check it out: https://github.com/uiowa/uiowa/pull/1764.   I'm sure there are better ways to reduce the duplication of code since the only thing that changes is that the fields use `elements` instead of `content`.
