### ISSUE TITLE
Adjust hero block component to disable video autoplay by default

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#1742]
- [ ] Change markup in hero block template to disable autoplay by default and dynamically change based on block level override. 
- [ ] Add override checkbox/field to hero block in layout builder tray to enable autoplay.
- [ ] If autoplay is enabled, add sufficient warning text about vestibular triggers

**Comment by mjoneill** [comment]
Story Points: 3

**Comment by mjoneill** [comment]
Can we have a conversation about any larger stories this may be a part of?  Waiting until @bspeare returns. Not urgent.

**Comment by pyrello** [comment]
Closing in favor of #2403
