### ISSUE TITLE
Move Drupal-specific form styles to uids_base from uids

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#1747]
Related to #1356 and uiowa/uids#195.

When the above tasks were undertaken, a lot of style rules were placed in UIDS that is Drupal-specific. Unless we are planning on adopting `webform-*` class names as our standard for forms in UIDS, anything that is not generic enough to stand on its own in UIDS should be moved to uids_base.

**Comment by bspeare** [comment]
I think this was done a while ago.  We have https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/scss/components/form/forms.scss.  Can we close this issue?

**Comment by pyrello** [comment]
Yeah, looks like this can be closed.
