### ISSUE TITLE
UIDS_Base coverage for IGHN.International

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#1749]
Relates to #1660 

## Problem

ighn.international has some css overrides to account for their custom person content type and view. This needs to be revisited before adoption of uids_base.

## Proposed Solution

The current css overrides should only be loaded if the active theme is uiowa_bootstrap.

Create a yarn workspace for ighn to utilize UIDS components and extend/override to cover the custom functionality in IGHN.

Follow the same designs being done with the person full and teaser in uids_base. Remove the map header bg as it is "off-brand"

This should rollout in conjunction with the uids_base switch.

- [x] Set parent organization stuff in site settings/theme settings

**Comment by joewhitsitt** [comment]
Started https://github.com/uiowa/uiowa/pull/1781 to play with the workspace idea. A lot of work to do. I think something might be wrong with the field groups used on the view modes.

`blt frontend` compiles the workspaces. probably want to ignore the assets going forward.

Not sure how to incorporate the old collapse behavior with the biography. https://uids.brand.uiowa.edu/components/detail/accordion--default.html comes to mind as an accessible solution, but might be overkill otherwise.

Might want to wait for https://github.com/uiowa/uiowa/pull/1468 to merge in where person work is currently being styled.

**Comment by joewhitsitt** [comment]
@pyrello and @bspeare, looking to get your thoughts on this issue. Including a link https://internationalighn.prod.drupal.uiowa.edu/ to demonstrate the current biography collapse functionality. I think the original idea was that we would not send visitors to the full node to read biography information and instead send clicks to the available website/cv. This paired with the max-height, somewhat deals with potential over-sharing in the bio field.

Anyway, given the template differences between uiowa_bootstrap and uids_base, we are wondering how we can extend the card to handle this extra content.

**Comment by pyrello** [comment]
@joewhitsitt If you want to add these fields to one of the existing extendable twig blocks, you would be looking at one of these: https://github.com/uiowa/uiowa/blob/1e44c8be06e9b855a6134f4995d12559218e2cea/docroot/themes/custom/uids_base/templates/uids/card.html.twig#L67-L83

Here is an example of two of those blocks being overridden in the article teaser template: https://github.com/uiowa/uiowa/blob/1e44c8be06e9b855a6134f4995d12559218e2cea/docroot/themes/custom/uids_base/templates/content/node--article--teaser.html.twig#L118-L126

**Comment by joewhitsitt** [comment]
This was added to #1806
