### ISSUE TITLE
Bug - Moderation button cutoff on nodeview

### ISSUE THREAD

**Issue by ethanstjohn** [uiowa/uiowa#179]
![Screen Shot 2019-05-13 at 5 01 40 PM](https://user-images.githubusercontent.com/42824212/57657326-a4b42f80-75a0-11e9-8527-7467ef116d60.png)

**Comment by cory-skeers** [comment]
Appears correctly in Chrome for me, but not Firefox or Safari (both have the same cutoff as Ethan's screen grab).
