### ISSUE TITLE
SiteImprove Error Locally

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#1791]
## Problem

I get the following each time I save a page locally:

>Warning: Invalid argument supplied for foreach() in Drupal\siteimprove\SiteimproveUtils->setSessionUrl() (line 154 of modules/contrib/siteimprove/src/SiteimproveUtils.php).

## Proposed solution

Turn off siteimprove locally via env split

**Comment by pyrello** [comment]
@joewhitsitt I think that makes sense, since it isn't really meant as a development tool. If we needed to test it locally, we could turn it on manually, or test it in dev or stage.

**Comment by joewhitsitt** [comment]
I haven't looked into the error much, but I wonder if this could be solved by covering the local domains and leaving it on. Michael just told me that that the number of domains is not an issue. This would also developers to deal with a11y issues before deploying!

**Comment by richardbporter** [comment]
This is driving me nuts!

**Comment by joewhitsitt** [comment]
can we turn off siteimprove locally via env splits?

**Comment by richardbporter** [comment]
Yes, if we don't want to use it locally.

**Comment by richardbporter** [comment]
Or if it can't be used locally.
