### ISSUE TITLE
Fix extra space between content and footer when uids_base is viewed in IE11

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#1793]
# Problem 

A giant space is between the footer and the content area when `uids_base` sites are viewed in IE11. 

# Proposed Solution 

Add targeted css to resolve this extra space.

**Comment by bspeare** [comment]
@joewhitsitt maybe we can close this issue once the new criteria is developed?

**Comment by joewhitsitt** [comment]
Relates to https://github.com/uiowa/uiowa/issues/2238

Sure. I don't recall this issue.
