### ISSUE TITLE
Add SiteImprove module to default config, remove from collegiate

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#1800]
Blocked for now while SSO is investigated

- [x] Enable for all sites
- [x] Setup default config/permissions
- [x] Remove from collegiate split

**Comment by mjoneill** [comment]
I'd like to revisit the conversation about adding the Siteimprove plugin to D7 Sitenow sites.  Seems like we might have clients on D7 longer than we knew a few weeks ago, and I'd like to see what we learn from D8 integration that could inform our conversation about D7 integration.

**Comment by joewhitsitt** [comment]
Here is the D7 (v1) task.
https://github.com/uiowa/uiowa/issues/2120

**Comment by pyrello** [comment]
This is done.
