### ISSUE TITLE
Option for automated content move from Paragraphs to Layout Builder

### ISSUE THREAD

**Issue by cory-skeers** [uiowa/uiowa#1803]
## Problem
Depending on timelines and methodology, possibility of an automated update to move content from paragraphs to layout builder could ease the transition.

### Update
Migration option is being built out in a custom module (sitenow_p2lb). Current functionality works (with some bugs) with text and card content blocks.

### Content types to account for from paragraphs
- [x] Text
- [x] Card
- [x] Accordion/accordion item
- [x] Blockquote
- [x] Image gallery
- [x] Webform
- [x] Featured content
- [ ] Articles/Events/People
  - [ ] Need updating, specifically People
- [x] Carousel/carousel image

### Other to-dos
- [x] Revisioning bug leading to migration of previously deleted content blocks
- [x] Section overrun bug (some cases lead to 5 or more column sections, which are invalid)
- [x] Section background images
- [x] Optional inclusion of section/content styling choices like background colors
- [ ] Improved options
  - [ ] Review of moved content?
  - [ ] Auto-removal of old paragraphs after migrate/review?
  - [ ] Rollback or revision option?
  - [ ] On-page conversion option rather than/in addition to separate menu?
  - [x] Bulk node updates?
  - [ ] Update perms split?
  - [ ] Revisions?
    - [ ] Remove previous node revisions to avoid rolling back pre-update? (low cost)
    - [ ] Create block revisions based on paragraph revisions, and update node revisions? (questionable...high cost)
  - [ ] Content moderation? Check that we have published and possible drafts updated.
- [ ] Lots of testing...
- [ ] Documentation and/or decision on methodology of rollout--user-run, dev-run, automated in an update hook, etc.?
- [ ] Remove sitenow_v2 flags in sites' blt.yml file
- [ ] Other things
- [ ] Handle cards with videos somehow
- [ ] Prevent deleting the rollback revision: https://github.com/uiowa/uiowa/issues/1803#issuecomment-876835327

### Migrate modules
Some work may be repurposed from SiteNow Migrate for the paragraphs end--SiteNow Migrate may also need to be updated if any automated D7->D8 migrations into layout builder would take place.

### Update hook
As multiple databases won't need to be handled as in a typical site migration, it's possible to include the entirety of the update in an update hook.

**Comment by cory-skeers** [comment]
Note: As long as paragraphs module is enabled, paragraph tables remain in database, and field_page_content_block remains on the page, revisions work to revert back to paragraphs setup post-migration to layout builder. 

Probably not worth the effort to make a specific 'rollback' option then, unless it's a simple revert to last revision (or maybe last revision which uses paragraphs). Wouldn't clear out LB content that was created, so may lead to some bloat, but in general there shouldn't be a lot of migrate, rollback, migrate, rollback...type scenarios.

**Comment by joewhitsitt** [comment]
Are permissions accounted for in this? Split perms will need to be updated so editors can use blocks, etc.?

**Comment by cory-skeers** [comment]
> Are permissions accounted for in this? Split perms will need to be updated so editors can use blocks, etc.?

Added it as another bullet in the "improved options." Think we have a general idea of the path for updating perms like when we updated coronavirus, but we do need to make sure it doesn't get overlooked, whether that's a manual split change or scripted.

**Comment by pyrello** [comment]
This is blocked by #3568

**Comment by joewhitsitt** [comment]
Without splitting, the goal for sprint 70 is to move forward with this issue by getting image gallery working and to groom this issue to be up-to-date with what is left to be done.

**Comment by pyrello** [comment]
Realizing I should have put this comment here: https://github.com/uiowa/uiowa/pull/1976#issuecomment-875031998

Here are some updates that I have made to #1976:
- Added a text field to the page content type (scoped to SiteNow V2) for storing the revision ID of the last revision prior to conversion.
- Built a Views-based conversion UI (copied initially from the Moderated Content view) that uses two displays and a filter checking whether the above field has been set or not. If empty, then content shows up on the "To be converted" page. If not empty, then content shows up on the "Converted" page.
- The "To be converted" page implements the action for converting a page from the V2 to the V3 format.
- When the action is triggered against one or more items, in addition to running through the conversion process, it also stores the revision ID for the last revision prior to the page being converted on the "Conversion revision ID" field.
- The new revision containing the changes from conversion is set to "draft" state for review and publishing.

I think this gets us to the providing the following options as part of this process:
- Owners can trigger the process for converting one or many nodes as they choose.
- Owners can review the changes without the page being published.
- Owners can make additional changes to the page before deciding to publish it.

# Screenshots

## To be converted page
![Screen Shot 2021-07-07 at 1 22 07 PM](https://user-images.githubusercontent.com/709009/124812665-84d2e900-df29-11eb-8f5f-f9249b2d8bf1.png)

## Converted page
![Screen Shot 2021-07-07 at 1 22 37 PM](https://user-images.githubusercontent.com/709009/124812706-93210500-df29-11eb-85a3-1b79c026502e.png)

**Comment by pyrello** [comment]
Making a note here to remember that we need to handle the case where the content revision id points to a revision that has aged out.

**Comment by pyrello** [comment]
More thoughts on how to prevent deletion of the fallback revision ID:
- The query for getting node revisions to delete in the `node_revision_delete` module uses the `addTag()` method to allow altering of the query: https://git.drupalcode.org/project/node_revision_delete/-/blob/8.x-1.x/src/NodeRevisionDelete.php#L486-488
- `hook_query_TAG_NAME_alter()` allows for altering the query in question: https://www.drupal.org/docs/7/api/database-api/dynamic-queries/query-alteration-tagging#s-hook-query-alter
- Combining those two things, it seems that we could pull a list of revision IDs from the `field_v3_conversion_revision_id` field and use the query alter to add a `WHERE NOT IN` clause.

**Comment by e-marie-w** [comment]
Closing this as due to #3792 the remaining work is now organized in #3878 and #3880.
