### ISSUE TITLE
Theming of <div> text

### ISSUE THREAD

**Issue by cory-skeers** [uiowa/uiowa#1810]
Relates to #1660 

## Problem
In uiowa_bootstrap, there is some theming at the body{} level which carries forward to text in `<div>` tags.
![image](https://user-images.githubusercontent.com/49074566/85146836-a32d5000-b213-11ea-81ac-16fa6024b56d.png)

In uids_base, the `<div>` tags don't get the full theming, and the spacing is tight.
![image](https://user-images.githubusercontent.com/49074566/85146998-d66fdf00-b213-11ea-8d71-bb495c09d540.png)

**Comment by cory-skeers** [comment]
The `line-height: 1.15` is explicitly added in the uids `_base.scss`. Might not be anything to "fix" then, and simply a style difference.

**Comment by bspeare** [comment]
@cory-skeers What items usually appear in the `<div>` within the wysiwyg?

**Comment by cory-skeers** [comment]
https://cnm.uiowa.edu/concert-season-54/concert-3b-102719 was the example page from above. SiteNow service webmaster who regularly goes into the `source` to edit and arrange content.

Not sure that any items use `<div>` within the wysiwyg outside of someone putting them in directly. Content in tables use the `line-height: 1.15` as well, but that also gets a `font-size: 1.2rem`, so the spacing isn't as noticeable.
