### ISSUE TITLE
Include 'Additional Information' from SiteNow footers in uids_base

### ISSUE THREAD

**Issue by cory-skeers** [uiowa/uiowa#1820]
Relates to #1660 

## Problem
'Additional Information' in basic site settings (admin/config/system/site-information) for SiteNow sites includes Title and textarea Details fields that can be included in the footer. This has been used for various content: contact details, site slogans, acknowledgement/attribution info.

### New home for existing content
Content already in place needs to be handled. Currently, after transitioning to uids_base, content in these fields are no longer displayed on the site.

### ~~Update basic site settings~~
~~The 'Additional Information' section is available in basic site settings with uids_base theme, but is not used in the site.~~
uiowa_footer module will likely be deprecated, which would remove this from the site settings.

## Proposed solution
Create a pre-footer region block to hold content currently in place in SiteNow.
~~Remove Additional Information section from basic site settings.~~

**Comment by cory-skeers** [comment]
Followup from parking lot discussion:
Contact info region in footer may be a better spot for it--move content into a block which can be placed here. Some cleanup may be necessary depending on the site, but this is likely a good catchall spot.

**Comment by joewhitsitt** [comment]
Doesn't the footer content (uiowa_footer) just need to be migrated into block/1 (Footer Contact Info) and just delete the default content in that block (generic address and phone number)?

**Comment by cory-skeers** [comment]
@joewhitsitt -- We can certainly do that. I was under the impression that the generic info was part of the universal branding, but that could have been my misunderstanding.

**Comment by joewhitsitt** [comment]
@pyrello correct me if I am wrong but isn't the content in the contact info block just to serve as "default content"

**Comment by pyrello** [comment]
The content in the contact info block is just placeholder content by default. It is meant to be customized per site. As part of the update that introduced that block a while back, there was an update hook to populate the block on every site, so it should exist, even if it's not visible.

**Comment by cory-skeers** [comment]
Ahhh... Okay. Parking lot suggestions from 6/23 make a lot more sense now. Thanks @joewhitsitt and @pyrello!
