### ISSUE TITLE
Remove Additional Info, Brand Lockup, and Slogan options from Site Settings

### ISSUE THREAD

**Issue by cory-skeers** [uiowa/uiowa#1824]
Site slogan, brand lockup, and additional info options are available in basic site settings of SiteNow sites. In uids_base, content from these fields is not used, and needs to be removed.

## Proposed solution

-  ~~Move content in Slogan to a suitable spot within uids_base (if necessary)~~
- [x] Remove Site Slogan from site settings options for uids_base theme, or add notice that it is deprecated/won't show
- [x] Move brand lockup image to media system (#1829)
- [x] Move Additional Info to uids_base footer (#1820)
- [x] Remove brand lockup and additional info options from site settings in uids_base theme (both can be removed by removing the uiowa/uiowa_footer module)
  - [x] ~~Move uiowa_footer.settings config, and update references~~ Remove uiowa_footer.settings
  - [ ] Replace login link addition outside of uiowa_footer _This should be resolved in uids_base_
- [x] Update tour info
- [ ] Update documentation

**Comment by cory-skeers** [comment]
Followup from parking lot discussion:
Brand lockup--remove the option in site settings, but maintain the file itself, possibly by moving it into the general managed files.

Site slogan--potentially hide on sites using uids_base theme where it isn't rendered, but leave in place overall for sites that may potentially use it still. However it gets handled has a potential for "where'd my slogan go?" type questions, so might be good to hold off and wait.

**Comment by pyrello** [comment]
Lockup forms for the footer are provided by uiowa_footer module, I believe. As we are replacing all the functionality from that module, I think we can consider deprecating the module and removing it from the project.

**Comment by cory-skeers** [comment]
Blocked by #1829

**Comment by cory-skeers** [comment]
Lockup forms for the footer as well as additional info, both of which will be deprecated in uids_base, are provided by the uiowa_footer module. Parts of the update from uiowa_bootstrap to uids_base will move content from Additional Info into the Footer Contact Info block, and create a media entity for any existing brand lockup image, so the file is still accessible by users.

Following those updates, deprecating uiowa_footer module would take care of removing these fields from site settings, leaving only Site Slogan.
