### ISSUE TITLE
Change "master" branch to "main" or something else.

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#1838]
This sums it up nicely: https://tools.ietf.org/id/draft-knodel-terminology-00.html#master-slave

Here is a guide on how to make it happen: https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx

**Comment by richardbporter** [comment]
I can tackle this after merging most of our open PRs. Mostly concerned with the dependabot ones.

**Comment by pyrello** [comment]
Thanks, @richardbporter!
