### ISSUE TITLE
Files aren't being deleted

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#1867]
## Problem

Media deletes a file, but it doesn't actually get removed from the server. All files are currently being marked as permanent and this doesn't change even if the file usage is 0. A change in 8.4 made this behavior the default to prevent unwanted data loss. 

`make_unused_managed_files_temporary`

Additionally, revisions are also keeping the file_usage count up.

https://www.drupal.org/node/2891902

The result is that files are still available on a server and there is nothing a site owner can do to remove the file. This can be problematic if the file contains outdated/sensitive information.

Our current configuration is set to delete temporary files after 6 hours next cron, but because of the variable, that is not happening.

This also affects our hosting storage.

## Proposed Solution

- [x] Switch the variable introduced in 8.4 to TRUE. "This will work for files going forward."
- [x] Adopt media replace functionality which overwrites files reducing the amount of orphaned files, duplicates. #883 
- [x] Run an update hook to mark existing files with 0 usage (file_usage) and flag them for deletion (file_managed status = 0). https://www.drupal.org/node/2891902#comment-13350023
- [x] Lower time till expire

**Comment by richardbporter** [comment]
> There is still a use-case where a client can't wait for the cron garbage collection and the file needs to be cleaned up right away. Replace is a workaround, but otherwise, the timestamp needs to be updated manually in the on the file in the db to clear ahead of the grace period. A admin ui/confirmation would be cool to clean these up on a case-by-case basis.

If we lower the temporary_maximum_age then this is less of an issue. Folks can delete the file through the UI and it should be deleted within 6 hours. Unless there is a contrib project that does this?
