### ISSUE TITLE
Set heading style for footer links in uids_base

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#1878]
# Problem 

Footer link headings appear unstyled and in a flex column next to the footer links.

<img width="670" alt="Screen Shot 2020-07-01 at 9 54 14 AM" src="https://user-images.githubusercontent.com/1036433/86259601-d3fd7580-bb81-11ea-8757-7d581583fa06.png">

# Proposed Solution

Add a style to `footer.scss` component to set this style.

**Comment by joewhitsitt** [comment]
@bspeare not sure if you have additional plans for this beyond color contrast which was fixed in #1947

**Comment by bspeare** [comment]
@joewhitsitt, yes I need to set some sizing styles and flexbox adjustments for the headings.   Thanks for the reminder.

**Comment by joewhitsitt** [comment]
Sorry, I mis-understood what this issue was about..

**Comment by bspeare** [comment]
@joewhitsitt my description could have spelled it out better!
