### ISSUE TITLE
Update footer contact info text area in uids_base footer to be minimal html format

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#1879]
# Problem

The Additional Information area for SiteNow sites in the `uids_base` footer is currently set to allow filtered html.    

# Proposed Solution

Change text format to minimal html and allow `<span>` tags for font icons.

**Comment by joewhitsitt** [comment]
Footer Contact Info is a text area block. Do we want to restrict the text area block to just minimal? Otherwise just restricting block/1 to minimal is a bit more complicated.

**Comment by pyrello** [comment]
We do not want to restrict text area block to minimal, since it is our catch-all block type that allows us to cover cases we can't cover with other components yet.

This would require an update hook instead of changing config.

**Comment by joewhitsitt** [comment]
We added span/class functionality to minimal and decided it wasn't worth the squeeze in trying to regulate the textarea format for a single block.

Should we close this one for now and wait to see what kind of policy comes from brand regarding footers?

**Comment by pyrello** [comment]
I concur.
