### ISSUE TITLE
Investigate limiting available options in layout builder editing tray

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#1889]
# Problem

The layout builder tray offers too many options when adding a new block when you select the "More..." option. 

<img width="1663" alt="Screen Shot 2020-07-02 at 9 12 15 AM" src="https://user-images.githubusercontent.com/1036433/86369751-7d0ca480-bc44-11ea-9fa1-075054407b66.png">
<img width="323" alt="Screen Shot 2020-07-02 at 9 12 01 AM" src="https://user-images.githubusercontent.com/1036433/86369762-80079500-bc44-11ea-9a65-323af205cdfd.png">

# Proposed Solution

Investigate methods to limit available fields and blocks available in the tray.

**Comment by pyrello** [comment]
You can set this in the content type manage display page by implementing block restrictions.

**Comment by bspeare** [comment]
To set it on uiowa.edu, you would go to https://uiowa.edu/admin/structure/types/manage/page/display#edit-layout-layout-builder-restrictions-allowed-blocks.
