### ISSUE TITLE
Investigate Asana github integration

### ISSUE THREAD

**Issue by mjoneill** [uiowa/uiowa#1892]
Investigate Asana github integration

[@mjoneill]

**Comment by mjoneill** [comment]
Moved this in to Parking Lot as we ran out of time in planning.

**Comment by mjoneill** [comment]
So, I poked around a bit and found a few possible routes to integrate.  The most feature rich right now seems to be the Unito product (not free): https://guide.unito.io/en/articles/3478406-asana-github-integration

@richardbporter I have a vague recollection that you once looked at integration options.  Do you recall if there was a native connector or something else you looked at?

**Comment by richardbporter** [comment]
I do not. I have not used Asana that much. I know other team members are not huge fans of it.

**Comment by pyrello** [comment]
It seems that the impetus for this issue has faded over time. I suggest that we close it and, should it bubble up again, we can re-open it.

**Comment by bspeare** [comment]
I agree with @pyrello, let's close this and re-open if needed.
