### ISSUE TITLE
Hawk Alerts need a landmark

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#1898]
## Problem
When rendered (see uiowa.edu stage site) there are two rendering of hawk alerts. One in the header and one in the drupal announce, both of which do not have an appropriate landmark. We should wait for a core solution for the Drupal Announce area (https://www.drupal.org/project/drupal/issues/3098857) but try and address the block version.

## Proposed solution

- [x] Update the JS block version with role="region" and aria-label it.

**Comment by richardbporter** [comment]
> Update the JS block version with role="region" and aria-label it.

Hawk Alerts are rendered via JS, the custom alert is rendered via a block: https://github.com/uiowa/uiowa/blob/af9f9f5a117fc7b309fc424f951d7c855918efb6/docroot/modules/custom/uiowa_alerts/src/Plugin/Block/AlertsBlock.php#L60 So updating the block render to include a region will partially solve this, is that correct?

**Comment by richardbporter** [comment]
Custom alerts already have the `role=region` attribute and `aria-label`: 

![image](https://user-images.githubusercontent.com/1068523/118554757-7802f780-b727-11eb-81a3-cfa51e79514d.png)

Do they also need `aria-labelledby`?

**Comment by joewhitsitt** [comment]
not the custom alert message, the hawk alert?
