### ISSUE TITLE
Remove `uiowa_footer` from dependencies

### ISSUE THREAD

**Issue by cory-skeers** [uiowa/uiowa#1907]
Blocked by #1824

**Comment by richardbporter** [comment]
Is this also blocked by HR still using uiowa_boostrap?

**Comment by cory-skeers** [comment]
@richardbporter I think without putting in workarounds or updating the split as well, HR using uiowa_bootstrap blocks #1824 too. Idea was to remove the uiowa_footer.settings and disable the module in that one, and remove it in this one. It's a little more tied up in things getting moved around/updated than I'd intended, though.

**Comment by joewhitsitt** [comment]
Uh, yes. HR is using all the things still. Nice catch.

**Comment by joewhitsitt** [comment]
To be clear, this is blocked now because it can't just be removed without accounting for HR because this is still used as part of their uiowa_bootstrap dependency. HR would have to split this module off, update permissions across splits.

**Comment by pyrello** [comment]
This is blocked until #3709 is wrapped up because we can't remove this module until after it is uninstalled by the updates to the HR config split.
