### ISSUE TITLE
Fix page title / featured image preview within layout builder edit screen

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#1908]
# Problem

There are a few issues that need to be addressed:

- The layout builder edit screen for pages contains a page title / hero section that is vertically condensed due to the `vh` property set on the hero container. 
- There are also multiple "Add Banner" options within the page title hero section - do we need to remove the ability to add blocks within this section?
- There is also no page title/breadcrumbs preview set if the page doesn't use a featured image. 

Screenshots:

<img width="1826" alt="Screen Shot 2020-07-07 at 10 59 30 AM" src="https://user-images.githubusercontent.com/1036433/86814049-82a02b00-c046-11ea-9550-08540f58d549.png">
<img width="1827" alt="Screen Shot 2020-07-07 at 10 58 55 AM" src="https://user-images.githubusercontent.com/1036433/86814078-8b90fc80-c046-11ea-84e7-f8e0522d5af4.png">

# Proposed Solution(s)

1. Adjust styles for hero component within `admin.scss` in uids_base 
2. Investigate method to show page title block by default and only show page title/hero component if a feature image is set. 
3. Remove option to add custom blocks within the Header Layout with Background Media

**Comment by richardbporter** [comment]
Should the featured image be showing in the layout builder edit screen when that field is set on the node? I'm not seeing it for some reason.

**Comment by richardbporter** [comment]
> Should the featured image be showing in the layout builder edit screen when that field is set on the node? I'm not seeing it for some reason.

I think this is working. Might be a local issue with lazy loading and/or stage file proxy.

**Comment by richardbporter** [comment]
> There is also no page title/breadcrumbs preview set if the page doesn't use a featured image.

I'm not seeing that. Seems to appear regardless. The only time it doesn't show is on the frontpage but thats by design.
