### ISSUE TITLE
WSOD on newly created site

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#1915]
`Error: Call to a member function label() on null in template_preprocess_uiowa_footer() (line 274 of modules/uiowa/uiowa_footer/uiowa_footer.module).`

### Steps to reproduce locally on the default site (simulating site creation):
- `drush sql:drop`
- `blt drupal:install`
- Visit the front page.

I'm not sure if this belongs here or in the uiowa_footer repo. First reaction is we might be missing default config.

**Comment by cory-skeers** [comment]
Meant to test this, but forgot to get off the branch for #1903. On the plus side, that worked without a WSOD (works to unhook uiowa_footer, in prep for removing it competely.)
