### ISSUE TITLE
Further investigation of inline block/LB permissions

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#1920]
As a follow-up to #1890, we should see what options exist in the contrib space to allow for greater control over LB or inline blocks.

**Comment by joewhitsitt** [comment]
- [x] Restrict vertical video to homepage.
- [ ] Restrict hero to collegiate. _being consolidated to banner_
- [x] Restrict separator to homepage only.
- [x] Remove Who's Online?
- [x] Remove Recently Updated?
- [x] Remove views until we are ready to let users place them.

**Comment by richardbporter** [comment]
>Remove Who's Online?
 Remove Recently Updated?

I don't see these. Checked.
