### ISSUE TITLE
Hide Site Improve widget when editing a layout builder page.

### ISSUE THREAD

**Issue by GaryRidgway** [uiowa/uiowa#1922]
When editing a Layout builder page and pulling in blocks from a side menu, the Site improve widget is by default open and blocks some of your view. This should be collapsed by default when editing a layout page.

**Comment by richardbporter** [comment]
It looks like if you collapse the widget, it is collapsed by default and saved in a cookie or local storage. I'm not sure how much of an issue this is or if it warrants the code in #1927 (which is cool BTW). :)
