### ISSUE TITLE
Layout Builder default content

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#1925]
# Problem
To be able to fully switch over to Layout Builder, we need to be able to replace the default homepage provided in SiteNow with something built in Layout Builder.

The Default Content module currently doesn't provide this functionality, as it depends on the built-in REST API and that doesn't support exporting layouts or layout blocks yet.

# Proposed solution
There is an issue to add support for Layout Builder-related content via REST and JSON: https://www.drupal.org/project/drupal/issues/2942975

1. Apply the latest patch to see if it works: https://www.drupal.org/files/issues/2020-07-07/2942975-116.patch
2. Using the SiteNow demo site (default), re-create the content using Layout Builder
3. Establish menu links for view pages (news, people) from #1081 ?
4. Contact form from #1415 ?
5. Re-export the content
6. ???
7. Profit!

**Comment by joewhitsitt** [comment]
OCD Joe: Don't delete node/1 and node/2. It would make me happy if we retained media/1 using #883 or something else.

It might be easier to remove default content completely, fresh install, new default content with node/1 as front.

**Comment by pyrello** [comment]
I started working on this. My plan was to replace the existing default content pages with versions built in Layout Builder, but keeping the same ID and UUID.

As an intermediate step, in #1932, I have just removed the content from the homepage.

**Comment by pyrello** [comment]
Might be good to check in with @ABoston88 about this too, since it could ultimately support the university's path towards a more standard IA strategy.

**Comment by pyrello** [comment]
This is blocked by #1555, as the current default content contains accordions, which are not available yet.

**Comment by pyrello** [comment]
Whenever #2028 is merged, this is unblocked.

**Comment by pyrello** [comment]
FYI, I started a branch for this: https://github.com/uiowa/uiowa/tree/feature_lb_default_content

**Comment by pyrello** [comment]
This is now blocked until #2032 is merged.
