### ISSUE TITLE
Should we keep the body field for basic pages?

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#1926]
In the context of #1779, one question that needs to be sorted out is whether the body field should be brought over from the Collegiate split.

My argument would be that yes, you should allow a body field for basic pages that don't need all the trappings of Layout Builder. This would be in addition to other updates that would make it more obvious that creating a more advanced layout requires going to a different page than the edit page.

**Comment by joewhitsitt** [comment]
>you should allow a body field for basic pages that don't need all the trappings of Layout Builder

Agreed.

More important I think is what is the future/purpose of the body summary field when field_teaser exists.
