### ISSUE TITLE
Refactor hero component to have hero and banner styles

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#1928]
# Problem

The Hero and Banner component share styles that can be refactored to offer one inline block component that will reduce the number of custom block options available. 

# Proposed Solution

Once https://github.com/uiowa/uids/pull/268 is completed, the Banner inline block component and the Hero component will need to be adjusted to offer more variation while being a little more prescriptive. 

- Text area becomes `minimal_html` instead of `filtered_html`. 
- Link field will need to be added

The Hero components featured on the home page will need to be set as custom styles and will not be featured as options within the Hero component.

**Comment by bspeare** [comment]
Related issue https://github.com/uiowa/uiowa/issues/1908.

**Comment by bspeare** [comment]
Possible options for renaming this block:

- Superhero
- Voltron
- Heroic Banner
- Media Object
- Image/Text Panel
- Feature

**Comment by joewhitsitt** [comment]
Missed the conversation about why renaming the block is necessary but for D7 before "hero" became a thing, we were using "showcase" a lot. Bootstrap uses "jumbotron." Billboard is another idea.

**Comment by bspeare** [comment]
@joewhitsitt Thinking about going with "Banner" since banner seems like it makes more sense to use within both larger and smaller spaces than "Hero" and it already exists within the system.
