### ISSUE TITLE
Let's have an image block

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#1931]
Currently we do not have a custom block that is just used for inserting an image. If someone needs to insert an image, they are just supposed to use the text area and insert it via the WYSIWYG. This is a decision that was made a while back, but it occurs to me that we should revisit it now that Layout Builder is going to be the shared solution.

**Comment by bspeare** [comment]
I think it would be nice to have.   Would it just be an image field where you could select the image style and crop?

**Comment by bspeare** [comment]
And could we also upload `<svg>` icons through this block too?  A brand icon library would come in handy too.

**Comment by pyrello** [comment]
Yeah, just a media image button and image style selection.

I'm wondering if an icon library would require a separate block type? Because in the case of an image, you'd be selecting from other images or uploading, but with an icon, you'd always be choosing from an existing set of options.

**Comment by cory-skeers** [comment]
There's at least some anecdotal need for this--I've seen SiteNow webmasters using both cards and plain text areas with nothing but an image, in trying to arrange the image separately.

Re: icons: Healthcare has an icon library on uihc.org that is controlled through a taxonomy, that I think has worked well for them, and could see something like that being put to good use on this side of the river. I think you could handle it either in the same blocktype or separate, with the first option needing to have extra settings on the block (select icons from a separate media library, selecting image or icon, etc), or the second option leading to more options in the block selection list. Might just depend on where you want to add the extra complexity/options for the user.

**Comment by joewhitsitt** [comment]
Bringing my grooming comment here:

I definitely get the developer benefit of being able to style around a basic bare image without the bloat around wysiwyg markup. Though an editor will quickly identify "Image" block over Banner, Text Area and such to place an image, I think they would wonder what is different about this block versus just adding an image to the wysiwyg which is a fairly common pattern now on campus.

I am curious what kind of features come with the image block (image effects?) that separate it from picking a responsive image style in the wysiwyg. Can I add a caption, will it pull in the global caption?

**Comment by pyrello** [comment]
After our recent discussion, I'm wondering if just having a "Media" block might make sense to allow for few options in the list. I would assume that we would allow them to still pick the image style they wanted to use.

People might wonder what the difference was, but if it was easier to do than placing an image via the WYSIWYG in text area, I don't think it would matter because they would just stop doing it the other way.

**Comment by bspeare** [comment]
An image block with access to an icon library could also be helpful if we want to use this a a replacement for a Blockquote block so the user could have access to upload images or utilize an icon in their blockquotes.

**Comment by bspeare** [comment]
Possible fields:

- Image/Icon 
  - Use similar strategy with new banner block: have a select list to use either an image or icon. 
- Text Area

**Comment by bspeare** [comment]
If you look at https://admissions.prod.drupal.uiowa.edu/how-apply/transfer-admissions you will see that the site editor is using the image gallery block to insert singular images into the page layout.   I think that having an image block would really provide clarity for users so that we can avoid placing singular lightbox images into page layouts. 

<img width="1609" alt="Screen Shot 2020-10-09 at 2 18 58 PM" src="https://user-images.githubusercontent.com/1036433/95623156-698a8a00-0a3a-11eb-9351-f4ed8ad5398c.png">

<img width="1602" alt="Screen Shot 2020-10-09 at 2 19 03 PM" src="https://user-images.githubusercontent.com/1036433/95623159-6b544d80-0a3a-11eb-9b0f-436988f14e36.png">

**Comment by bspeare** [comment]
Would we want to adjust the "Image Gallery" block to be an "Image" block?   We could set it so that single images are not treated as colorbox galleries and add the ability to adjust the image style?

**Comment by cory-skeers** [comment]
Capturing extra notes:

- There were (and may still be) examples of this in use on Admissions
- Previously this has been discussed in relation to adding a blockquote block as well, which has since been added. Similar use case and setup, different content

**Comment by briand44** [comment]
Scope to just image at least for now.

**Comment by briand44** [comment]
Headline?

**Comment by quamsta** [comment]
as a sidenote: despite my opinions on keeping the two blocks (Image and Image Gallery) separate, I think it may be worthwhile to adjust the way Image Gallery is rendered if there's only a single image in its gallery in order to accommodate people who may have used it in the past.

**Comment by pyrello** [comment]
In SNv2, I believe there is the possibility of creating a card that is just an image. So, this task will be relevant in #1976 because we were previously going to be moving the cards that met those conditions into text areas.

**Comment by joewhitsitt** [comment]
Personally, I think if this is going to be addressed, that a separate block would be best for single image/icon content instead of trying to utilize the image gallery block. I could get behind an image-only card but that is a lot more complexity to an already complicated block.

**Comment by bspeare** [comment]
A separate block with image/icon capability sounds good.   Would we offer the ability for image sizes/circle styles to be set?  @joewhitsitt what would an image-only card look like?

**Comment by briand44** [comment]
Block that allows adding a single image, choosing image style, optional link which requires a title if linked.

Caption, media block, icons, social media all things that could be considered down the road.

**Comment by joewhitsitt** [comment]
it hasn't been specified what image sizes/view modes should be available for this block

**Comment by makurj** [comment]
Any ideas on what styles to apply to this? Also, not getting the form display option for the block. Could someone test that out so I can figure out if it's my local environment? https://github.com/uiowa/uiowa/pull/5126

**Comment by joewhitsitt** [comment]
@makurj i would start with getting the layout builder styles setup so the editor can select these. then move on to the code image viewmode switching

reference the card image size stuff

**Comment by pyrello** [comment]
Updates from a Zoom session with @makurj:
* We added a fall-through case for `uiowa_image` to the code where we are handling view mode switching for `uiowa_card`. This worked without any other modifications.
* The image block needs to use different view modes behind the scenes because the images can potentially fill much bigger spaces. The `large__*` view modes are not big enough. We decided to use the `full__*` view modes instead.
* We refactored the logic to account for setting a different mapping of media classes to view modes and then processing the result. This worked as expected.
* However, upon viewing the rendering we noticed that `height` and `width` are added to the image and this seemed to constrain the size of the image. The `height` and `width` used were not for the largest available size.
* We tried removing those attributes from the `<img>` tag using the inspector and the browser selected a different image variant to use, but still did not select the largest one that would have filled the space. As far as I can tell from reviewing the HTML markup for the image, it seems like everything is rendering as expected. I'm not sure why the browser isn't picking up the largest possible image. The block `<div>` container is not constraining the potential size of the image.

We need to look into how `height` and `width` are getting set and see what options we change those values or remove them. Also, we need to figure out why the browser is picking an image that is quite a bit smaller than the available space.

**Comment by joewhitsitt** [comment]
Do the width/height match the fallback responsive image style set for full?

Full content - widescreen
<img width="864" alt="Screen Shot 2022-04-15 at 2 43 19 PM" src="https://user-images.githubusercontent.com/4663676/163625082-e584bf1a-3a92-4dfd-96f5-507b50fff0aa.png">

**Comment by makurj** [comment]
Yep. 

![image](https://user-images.githubusercontent.com/52135878/163625717-466fb1ae-d922-40e0-95da-22a5bb1e9da0.png)

**Comment by makurj** [comment]
Yep. 

![image](https://user-images.githubusercontent.com/52135878/163625773-260b3e1d-7c21-4652-b272-658894b6cc8e.png)

**Comment by joewhitsitt** [comment]
So that makes me think that the responsive image functionality is not working correctly for this implementation and is falling back. At a glance this might also be happening for cards https://sandbox.prod.drupal.uiowa.edu/cards (square or widescreen they get the 768px fallback version regardless of mobile or desktop)

See One-Column Card Image Test on https://sandbox.prod.drupal.uiowa.edu/cards

**Comment by makurj** [comment]
That seems to be working fine. 
![image](https://user-images.githubusercontent.com/52135878/163627215-8970cb82-1113-4c7c-85d4-eb4428b942b3.png)
![image](https://user-images.githubusercontent.com/52135878/163627243-255aa2fd-3ab7-44f2-8784-c1303a2a4cbe.png)

**Comment by joewhitsitt** [comment]
Oh. Weird. Must have been a cache issue on my end. Disregard.

**Comment by joewhitsitt** [comment]
No wait. The width and height are set to the fallback. 
<img width="403" alt="Screen Shot 2022-04-15 at 3 11 52 PM" src="https://user-images.githubusercontent.com/4663676/163627544-862d6481-0d04-49a3-ae69-12c725532913.png">

**Comment by makurj** [comment]
Where can I see the fallback sizes? View modes?

**Comment by joewhitsitt** [comment]
/admin/config/media/responsive-image-style

**Comment by makurj** [comment]
Merci beaucoup!

**Comment by joewhitsitt** [comment]
I looked at this a bit more on Friday. Responsive image styles set the width/height of the img element to the fallback image size (supposed to be the smallest possible) but the image that is loaded is bigger than those dimensions based on caching and device size. The difference between the image block and the card seem to be that card is implementing a `width:100%;`

## Card
<img width="774" alt="Screen Shot 2022-04-18 at 8 46 08 AM" src="https://user-images.githubusercontent.com/4663676/163818077-33050bdb-5c3f-4182-82e6-ff72c1e3f3e4.png">

## Image (inline style width 100%)
<img width="1135" alt="Screen Shot 2022-04-18 at 8 46 50 AM" src="https://user-images.githubusercontent.com/4663676/163818087-bc40421a-e996-41aa-8a61-6b9b333ce4d3.png">

**Comment by pyrello** [comment]
Nice find, @joewhitsitt! I was really baffled by why the browser wasn't just choosing the biggest image to fit the space.

**Comment by makurj** [comment]
With the width being set up and working correctly, does this mean the [PR](https://github.com/uiowa/uiowa/pull/5126) is ready to be reviewed?

**Comment by makurj** [comment]
Next steps:
1. Add some help text for how the link is being used.
2. Add some hover effects on the image instead of just cursor change?
3. Add some focus styles.

**Comment by bspeare** [comment]
The image gallery block has an opacity change on the image.  We might want to do something like that to be consistent:
```
a.photoswipe:hover img {
  opacity: .6;
}
```

**Comment by bspeare** [comment]
I added some focus and hover styles to the block.
