### ISSUE TITLE
EXIF data iPhone orientation

### ISSUE THREAD

**Issue by cory-skeers** [uiowa/uiowa#194]
Photos taken from an iPhone with orientation data get rotated incorrectly, and need to be stripped of their orientation EXIF data prior to being uploaded to Drupal.

**Comment by joewhitsitt** [comment]
Core issue:
https://www.drupal.org/project/drupal/issues/2664632

Adopted workaround by certain distros:
https://www.drupal.org/project/file_mdm by way of https://www.drupal.org/project/image_effects

**Comment by richardbporter** [comment]
I couldn't replicate this. An image to test with would be great.

**Comment by joewhitsitt** [comment]
@cory-skeers ran into one the other day when working on a site. still have it?

**Comment by cory-skeers** [comment]
![Bandsaw](https://user-images.githubusercontent.com/49074566/58499406-b6233d00-8145-11e9-882e-d3e1e1db59f1.JPG)

Here's one of the original example images (and GitHub doesn't handle the exif data either, I've just learned). Currently working around by saving copies, and then uploading the copied images.

**Comment by joewhitsitt** [comment]
you might have to air drop this photo to rick as anything else will probably lightly process the photo and remove exif data. was this oriented correctly when you received it?

**Comment by richardbporter** [comment]
FWIW, I gave image_effects a try locally but did not see any additional effects available on image styles. 🤷‍♂
