### ISSUE TITLE
Anyone know why I can't add a redirect for /athletics?

### ISSUE THREAD

**Issue by mjoneill** [uiowa/uiowa#1941]
This is the experience I get (see attached):

[@mjoneill]

**Comment by mjoneill** [comment]
![athletics-redirect (1)](https://user-images.githubusercontent.com/7144234/87226305-85599380-c358-11ea-91a4-d9c92c0284fb.gif)

**Comment by mjoneill** [comment]
PS: Tried adding other redirects, get the same experience.

**Comment by joewhitsitt** [comment]
This is the search interface. Click the add redirect button to go to the add form.

**Comment by mjoneill** [comment]
D'oh!
