### ISSUE TITLE
A11y question on theme header

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#1942]
@inspector508 emailed this out on Friday:

Running through some additional heuristic checkpoints, I noted that all pages use a generic and non-visible `<h1>` that reads “Home”. Ideally, that top-level heading would be assigned to the name of the site, at least in SiteNow. I’m thinking the `<a>` object with the class “branding_name” would be best for this purpose. The link could still point to the home page; it’d just be a matter of wrapping an `<h1>` around the branding_name link?

![Unknown](https://user-images.githubusercontent.com/1036433/87320099-1d3db580-c4f0-11ea-9e8b-cbd72a8cc29a.png)

An arrow with the tag `<h1>` points at the text of a SiteNow banner with site name circled. 
 
I don’t know how this slipped past me earlier but I hope we can address it on some level. Any thoughts?

# Proposed Solution

@joewhitsitt Is this an issue with the `uids_base` theme

**Comment by joewhitsitt** [comment]
@bspeare 

The non-visible home is the page-title block and the default node/1 is called "Home." Folks can change this to be visible (if not completely removed from layout builder) and change the text to whatever they want.

Not sure this is an issue unless we want to high jack the label on the front page if not visibly displayed. This is the same for both uiowa_bootstrap and uids_base

https://sitenow.uiowa.edu/documentation/basic-page-content-type See "visually hide title"

<img width="846" alt="Screen Shot 2020-07-13 at 11 03 23 AM" src="https://user-images.githubusercontent.com/4663676/87326560-845f6800-c4f8-11ea-9767-97ad177d0b5c.png">

**Comment by bspeare** [comment]
@joewhitsitt Can we close this one?

**Comment by joewhitsitt** [comment]
IMO, yes
