### ISSUE TITLE
Update website identifiers

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#1946]
## Problem
The help desk uses the console log to identify SiteNow sites. So if we are splitting v2 into v3, then we need to update the logic to differentiate.

<img width="534" alt="Screen Shot 2020-07-17 at 2 43 26 PM" src="https://user-images.githubusercontent.com/4663676/87825016-f5c25200-c83b-11ea-8d08-2b6bd6eb3f31.png">

## Proposed solution

Update console.log identifier to differentiate between v2/v3 and possibly update "SiteNow Help" toolbar link label to be version specific.

<img width="300" alt="Screen Shot 2020-07-17 at 2 44 32 PM" src="https://user-images.githubusercontent.com/4663676/87825074-1094c680-c83c-11ea-81fd-ef530b17937f.png">

Blocked until https://github.com/uiowa/uiowa/issues/1807

**Comment by richardbporter** [comment]
Somewhat related: I happened to notice a console error when a site is in maintenance mode and the formatting being off in IE11.

**Comment by richardbporter** [comment]
Although the console message styling is cool, we may want to drop it as it has no support in IE11 and spotty support in certain versions of other browsers. 

### IE11
![image](https://user-images.githubusercontent.com/1068523/92653487-0b8c4a80-f2b4-11ea-984c-bdf093ddfa51.png)


### Latest Safari
![image](https://user-images.githubusercontent.com/1068523/92653218-a59fc300-f2b3-11ea-8cda-8e1fc18e69a0.png)
