### ISSUE TITLE
Footer addresses have disappeared from existing sites after latest release

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#1949]
if you look at the footer on the [https://americanstudies.prod.drupal.uiowa.edu/](https://americanstudies.prod.drupal.uiowa.edu/) site, youll see that the footer address is now missing. I did not remove this, but I also havent updated the site to use a new solution if the footer address block was removed.

**Comment by joewhitsitt** [comment]
Can you be more specific? Just this site?

<img width="544" alt="Screen Shot 2020-07-15 at 3 22 30 PM" src="https://user-images.githubusercontent.com/4663676/87592205-1a3cf380-c6af-11ea-9ce1-7401a4ee77f4.png">

**Comment by mark-bennett-uiowa** [comment]
I just added them back in to all of my department sites. You can look at [icsa.uiowa.edu](https://icsa.uiowa.edu) and [policy.clas.uiowa.edu](https://policy.clas.uiowa.edu) to see that the addresses are still missing. Its like the entire block was deleted and re-added as empty.

**Comment by cory-skeers** [comment]
@mark-bennett-uiowa Have you made any changes to the content since the release, in general or when adding these back in? 

Looking into the issue that caused it now, and one option might be to roll the block back to a previous revision. If it's a blanket rollout, this would undo any changes made since then.

**Comment by mark-bennett-uiowa** [comment]
@cory-skeers I re-added the content back into these blocks for the three existing department sites, as well as the six new department sites. Looking at one of the previously existing sites, I can see how there is the Revision Information tab with the Create new revision checkbox checked, but no previous revisions to revert to.
<img width="651" alt="Screen Shot 2020-07-17 at 10 43 29 AM" src="https://user-images.githubusercontent.com/3067017/87805070-6789a400-c81a-11ea-8c0a-f13517515a3a.png">
