### ISSUE TITLE
Stat component regressions

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#1957]
# Problem

- UIDS 3.0 refactor removed contextual links from Stat component on layout builder edit screen https://github.com/uiowa/uiowa/commit/d88064d4c8c3ff8e9586220c4cb7384f2fb1ca75
- Extra padding is being added to stat preview which is a remnant from HDS component in `admin.scss`

## Missing contextual links:
<img width="407" alt="Screen Shot 2020-07-17 at 3 42 44 PM" src="https://user-images.githubusercontent.com/1036433/87829992-bac51c00-c845-11ea-8640-f68acaba348f.png">

## Extra padding from `admin.scss`:
<img width="318" alt="Screen Shot 2020-07-17 at 3 50 47 PM" src="https://user-images.githubusercontent.com/1036433/87829990-ba2c8580-c845-11ea-9eef-44c5ea6f47f1.png">

# Proposed Solution

- Add `{{ title_prefix }}` back into stat component template
- Adjust `admin.scss` to remove legacy stat styles.

**Comment by cory-skeers** [comment]
This was closed via #1967
