### ISSUE TITLE
Instructions for Layout Builder Blocks on uiowa.stage.drupal.uiowa.edu

### ISSUE THREAD

**Issue by dnkemper** [uiowa/uiowa#1961]
Go over different section options and blocks

# More... Options Block
`**wanted to bring this to top of page**`

## Content fields
- [x] **Authored by**
     - Render by entity ID necessary?
     - Rendered entity - View Modes:  User account, Token, Compact or Default..four view modes but all display the same
- [x] Body
- [ ] **Title**
     - Formatter: Instagram embed, twitter embed, Imagecache External Image (text field - shouldn't have these options)
     - Responsive image styles error w/ Imagecache external image option
- [ ] **Moderation Control** 
     - Do we want this?
- [x] Authored on
- [ ] **Tags**
     - Formatter options: RSS category, Rendered entity (Default, Taxonomy Term page, and Teaser View modes), Entity ID, Label, Full hierarchy, Hierarchy grouped by root and Flexible hierarchy -> What formats should I document?
- [x] **Content Description**
     - Formatter:  Instagram embed, twitter embed, Imagecache External Image - Responsive image styles 
- [x] Changed
- [ ] **Links**
     - This doesn't seem to do anything at all?
- [ ] **Featured Image**- rendered entity only display that works
     - Rendered entity w/ a billion view modes
     - Entity ID & Label:  Why use these for an image? Will they be utilized?
     - Thumbnail: EVERY image style in the world to select from
     - Does enabling lazy loading do anything?

##  List View options
- [x] **Articles block view** - Can’t edit items per page - defaults at 9; 
     - If you add the block and make no customization, no title displays above the block
     - If you want to override the title, you have to select  'Override Title' AND 'Display Title' 
     - When you don't override the title and select 'Display Title' a generic title doesn't appear for the block
     - If an article is added the website after the block is added to the page, the block doesn't display the updated content
- [x] **Articles monthly archive view** - When you override a title, it doesn't display unless you select 'Display Title' AND override title
- [x] **People block Sticky/First/Last** - Can’t edit items per page - defaults at 9; 
     - if you select 'Override Title' there's 'None' placeholder text?
     - you need to override the title AND select select 'Display Title' for the title text to appear
     - if you select 'Display Title' and don't select to 'Override [the] Title', the 'None' placeholder text is the blocks title
- [x] **People block Sticky/Last/First**  - Can’t edit items per page - defaults at 9; 
     - if you select 'Override Title' there's 'None' placeholder text?
     - you need to override the title AND select select 'Display Title' for the title text to appear
     - **if you select 'Display Title' and don't select to 'Override [the] Title', the 'None' placeholder text is the blocks title**
- [x] **Recent content**
     - If you add the block and make no customizations, no title will above the block
     - you need to override the title AND select select 'Display Title' for the title text to appear
     - Any new content added to website will not be rendered by this block. It only displays the most custom content of that moment. 
- [x] **Who’s online**
     - Only visible for admins

## University of Iowa Alerts
- [x] Alerts block

## User fields
- [x] Changed -> This is already being utilized in the 'Content Fields'?
- [x] Created -> This is already being utilized in the 'Content Fields'?

## System 
- [x] Breadcrumbs
- [ ] Main Page content -> errors out for me?

## Webforms
- [x] Webforms

# Blocks
- [x] Section
     - [x] Administrative label
    - [x] available styles
    - [x] how to edit existing sections styles
    - [x] How to add/remove a section
    - [x] layout options
    - [x] Explain banner block
    - [x] available blocks
    - [x] How to edit/move/remove builder blocks
    - [x] Block restrictions based on layout
- [x] Card
- [x] CTA
- [x] Event -> can we limit FA fields? Easy to error out
- [x] Hero (Banner will be merged iwith Hero so removed that doc option)
- [x] Image Gallery
- [x] Spacer/Separator -> Should I add this back?
- [x] Statistic
- [x] Slider
- [x] Text Area - link wysiwyg
- [ ] More... options

**Comment by joewhitsitt** [comment]
I am going to close this and #1929, #1992 and split remaining items into separate tasks:

Events: https://github.com/uiowa/uiowa/issues/2162
More Blocks: https://github.com/uiowa/uiowa/issues/2174
Banner (refactored): https://github.com/uiowa/uiowa/issues/2175
