### ISSUE TITLE
How to return to header+feature image after using section+page title hero blocks?

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#1978]
Before the feature image for basic pages change was added a few days ago, the basic pages with a page title hero were created in a new section above the header, and the page title hero block was added to this section and styled in LB. The header had the title and breadcrumbs removed so that they would only appear in the new section with the page title hero block.
When these pages were switched over to use the new feature image part of the header section, the previously created section + page title hero blocks were removed and the title and breadcrumb were returned to the header. The issue now is that even if I try to change the existing header to match the new settings, Section (Margin: Edge-to-edge) and Featured image (Label: -Visually hidden-, Formatter: Rendered entity, View mode: Full - Ultrawide), the image does not span the entire width of the section.
If I revert to default, this fixes the issue, but I lose all additional changes I may have made in layout builder. Do I need to recreate make additional sections in layout builder because of this change? Any suggestions?

**Comment by pyrello** [comment]
What site are you have this trouble with?

**Comment by mark-bennett-uiowa** [comment]
Closing this issue. Went through and manually returned these pages to the new default layout.
