### ISSUE TITLE
Adjust site header to check for a character limit on site name to determine header type

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#1980]
After today's design meeting it sounds like the next steps are:

- Determine character count for https://uids.brand.uiowa.edu/components/detail/iowa-bar--full.html
- Adjust mobile/tablet site name font size in `uids` for that new count. 
- Change sites that meet the character count requirements to use https://uids.brand.uiowa.edu/components/detail/iowa-bar--full.html
- Possibly limit some sites to only use https://uids.brand.uiowa.edu/components/detail/iowa-bar--site_name_below.html.

**Comment by bspeare** [comment]
- In theme settings lock down "Header Type" completely now that it is determined by character count?
- Remove configuration for "Parent Site" that is determining header type and set help text explaining the parent site settings instead?
- Allow admins to override?

**Comment by joewhitsitt** [comment]
Additional thoughts from grooming:

Sites are provisioned with the site's domain which can be long by default. I would suggest that v3 default to the site name below option to reduce validation requirements on provision.

Help text could be added to explain that parent organization/quick links only show with certain options. https://github.com/uiowa/uiowa/issues/2151

Validation needs to happen both on the basic site settings side and the theme settings side to prevent editors from setting a short site title temporarily and enabling the site name inline option or vice versa.

Communication would need to happen before we switch headers on existing sites found to not be using the correct one.
