### ISSUE TITLE
In base profile, allow content editors to set URL alias

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#1985]
# Problem
For the new Grad College site, I have a bunch of users that have the 'Content editor' role that are migrating content. As part of that process, I need for them to copy over the existing URL alias. Currently that role does not have access to that field.

# Proposed solution
Enable the 'Create and edit URL aliases' permission for the 'Content editor' role.

**Comment by joewhitsitt** [comment]
I would be more in favor of adding this to the publisher role than the editor role. I understand that a lot of students and such will be migrating content, but I don't want to lose the base restrictions of the editor role for the long term.

**Comment by pyrello** [comment]
Adding to the publisher role would work for me, although it doesn't really seem like a permission assignment that makes sense. The editor role seems like the appropriate place for this permission. This is basic stuff that everyone can do in Wordpress.

**Comment by joewhitsitt** [comment]
Whoa, pulling the wordpress card on me... unfair ;)

Most sites will want some kind of hierarchy of permissions. editor/publisher/webmaster was our attempt to offer that especially with moderation. Aliases was one of the things. Changes to aliases can affect other content, automatically creates redirects. Both of which affect SEO.

A user can have multiple roles to stack permissions and can be demoted to editor after initial migration. Thinking ahead, I don't want to create another role between editor and viewer, so I stand by my opinion for the default/service.
