### ISSUE TITLE
Allow card component to display in onecol layout as horizontal variant only

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#1987]
# Problem

The regular card component is not meant to render within a onecol layout.  However, the horizontal variant does render well within the onecol layout: https://uids.brand.uiowa.edu/components/detail/card--horizontal.html. 

# Proposed Solution

Force the `horizontal` style variant if card is placed within a onecol layout.

**Comment by bspeare** [comment]
# Possible solutions

- Change "Add Card" name within onecol interface to "Add Card (Horizontal)" and style card to reflect horizontal variant. 
- Create new "media" component that creates more flexibility for image position/size: https://philipwalton.github.io/solved-by-flexbox/demos/media-object/

**Comment by bspeare** [comment]
@pyrello any thoughts on how we should move forward with this?

- Change "Add Card" name within onecol interface to "Add Card (Horizontal)" and style card to reflect horizontal variant.
- Remove "override styles" option from card block in one column.   
- Add some custom styles to https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/scss/layouts/onecol.scss to enforce the horizontal variant?  Or programmatically add `card--horizontal` to block within card in onecol.

As an alternative to this work, we could create a new block that creates flexibility within each layout like https://philipwalton.github.io/solved-by-flexbox/demos/media-object/.

**Comment by bspeare** [comment]
The media object could also be used as an alternative to https://github.com/uiowa/uiowa/issues/1931.

**Comment by pyrello** [comment]
With the merging of #1979, it will be necessary to update the block restrictions to allow for creating a card in the one column layout again.

**Comment by richardbporter** [comment]
So we don't want to allow this:
![Screen Shot 2020-08-07 at 12 31 25 PM](https://user-images.githubusercontent.com/1068523/89672355-24b36d00-d8aa-11ea-99e3-31bf602edd93.png)

We want to force this:
![Screen Shot 2020-08-07 at 12 32 09 PM](https://user-images.githubusercontent.com/1068523/89672333-1bc29b80-d8aa-11ea-8fd3-e3567a422326.png)


Is this correct?

**Comment by richardbporter** [comment]
> With the merging of #1979, it will be necessary to update the block restrictions to allow for creating a card in the one column layout again.

I don't understand this because it seems like I'm able to create a card in a one-column layout.

**Comment by bspeare** [comment]
@richardbporter Yes, we want to force the horizontal variant.

**Comment by richardbporter** [comment]
We need some indication on the form to inform users of this. I'm not sure how to tell if the layout that the block is placed in is one column. I'm looking in the layout_builder_custom form alter right now.

**Comment by bspeare** [comment]
Is it possible to adjust the label for the Card within the one column layout?

<img width="1364" alt="Screen Shot 2020-08-07 at 2 29 25 PM" src="https://user-images.githubusercontent.com/1036433/89681382-76fc8a00-d8ba-11ea-876d-5c98dae06b4b.png">

**Comment by richardbporter** [comment]
Not sure yet. I think I'm on to something with the form. Do we want to allow the Card: Border style be applied to cards in a one column layout?

**Comment by bspeare** [comment]
@richardbporter That would be nice to have that option to add the border.

**Comment by richardbporter** [comment]
Here is what I came up with to start with: https://github.com/uiowa/uiowa/pull/2034.

It might be possible to allow the border style but all I can think of is adding a custom form validation handler and returning an error if horizontal is removed. That might work. Doing it in JS would be cleaner. I'm not seeing any option with Chosen to make that happen. Also Chosen is deprecated. :(

**Comment by bspeare** [comment]
@richardbporter How soon do we have to remove Chosen?
