### ISSUE TITLE
SiteNow v3 Basic Page Documentation

### ISSUE THREAD

**Issue by dnkemper** [uiowa/uiowa#1992]
Already unintentionally started on this but wanted to break up documentation a little bit for clarity 

- [x] Update the new block documentation
- [x] Collection block documentation
- [x] Add anchor notes 
- [x] Update the More... block
- [x] Add People Layout Builder block docs
- [x] Add Article Layout Builder block docs
- [x] Basic Page setup 
- mainly want this documentation to let users know they need to save the page before they have access to the layout builder blocks (not just include it in the content block documentation)
- [x] Highlight different layout of a page? 
- Where the save button is
- [x] Talk about menu of basic page (edit/view/layout) and what they do
- How to access Layout Builder

Need to add documentation for:
 - Change Banner/Hero blocks to match new version
- Event block documentation for dynamic events?

**Comment by joewhitsitt** [comment]
Decided to create separate issues for remaining docs and introduce them to parking lot as they are created

**Comment by joewhitsitt** [comment]
Actually, going to reopen this because it looks like a lot of the new documentation in the context of this issue is still unpublished. Let's work on getting those published.

**Comment by joewhitsitt** [comment]
Published several of these. Nice work @dnkemper 

Added a separate issue for the events block https://github.com/uiowa/uiowa/issues/2162

The remaining drafts are:
- more (i feel like this can be simplified a bit)
- spacer (not available in default)
- hero (going away)
- banner (refactoring https://github.com/uiowa/uiowa/pull/2075)
- page title hero (not available in default)

I am okay with closing this issue an create separate tasks for more and banner (blocked). Thoughts?

**Comment by joewhitsitt** [comment]
I am going to close this and #1961, #1929 and split remaining items into separate tasks:

Events: https://github.com/uiowa/uiowa/issues/2162
More Blocks: https://github.com/uiowa/uiowa/issues/2174
Banner (refactored): https://github.com/uiowa/uiowa/issues/2175
