### ISSUE TITLE
color combo issue: bg-dark and referenced content detail links

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#1997]
Relates to IR2298379

https://law.prod.drupal.uiowa.edu/
https://printmail.fo.uiowa.edu/contact-us

<img width="1373" alt="Screen Shot 2020-07-28 at 12 00 08 PM" src="https://user-images.githubusercontent.com/4663676/88697286-f673a780-d0c9-11ea-96f7-c67a5681d929.png">

**Comment by richardbporter** [comment]
I started looking at this before and throwing a `color: #000` here seemed to work: https://github.com/uiowa/uiowa/blob/808bc633012a712f4b064229a20e760e4591116e/docroot/themes/custom/uids_base/scss/paragraphs/_uiowa_paragraphs_background_overrides.scss#L376

**Comment by cory-skeers** [comment]
@richardbporter When I started looking at it, it looked like it was an issue with all card bodies, and not just ones used in featured-content. Checking now, though, that doesn't look like the case. Think I made it a bit more involved than it needed to be in #2036
