### ISSUE TITLE
LB's More.. block 'Featured Image' content field errors

### ISSUE THREAD

**Issue by dnkemper** [uiowa/uiowa#1999]
## Error 1
In Layout Builder, when adding a 'Featured Image' Content Field (selected from the ‘More..’ block), if I choose a ‘Label', ‘Entity ID’ or 'Thumbnail' format, it errors out the page. I didn’t notice it until I actually uploaded a ‘Featured Image’ after adding the block to the page.

Granted, I don’t think anyone would want to display a featured image as a ‘Label’ or ‘Entity ID’… but just wanted to put this out there.

The following error is what displays:

`The website encountered an unexpected error. Please try again later.
Error: Call to a member function count() on null in uids_base_preprocess_field() (line 211 of themes/custom/uids_base/uids_base.theme).
uids_base_preprocess_field(Array, 'field', Array) (Line: 287)
Drupal\Core\Theme\ThemeManager->render('field', Array) (Line: 431)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 200)
Drupal\Core\Render\Renderer->render(Array) (Line: 501)
Drupal\Core\Template\TwigExtension->escapeFilter(Object, Array, 'html', NULL, 1) (Line: 95)
__TwigTemplate_b56723691e9e628e7bea9937885dcd246f969f771b95cf8734ae3720616327c9->block_content(Array, Array) (Line: 214)
Twig\Template->displayBlock('content', Array, Array) (Line: 84)
__TwigTemplate_b56723691e9e628e7bea9937885dcd246f969f771b95cf8734ae3720616327c9->doDisplay(Array, Array) (Line: 453)
Twig\Template->displayWithErrorHandling(Array, Array) (Line: 420)
Twig\Template->display(Array) (Line: 432)
Twig\Template->render(Array) (Line: 64)
twig_render_template('themes/custom/uids_base/templates/block/block.html.twig', Array) (Line: 384)
Drupal\Core\Theme\ThemeManager->render('block', Array) (Line: 431)
Drupal\Core\Render\Renderer->doRender(Array) (Line: 444)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 200)
Drupal\Core\Render\Renderer->render(Array) (Line: 501)
Drupal\Core\Template\TwigExtension->escapeFilter(Object, Array, 'html', NULL, 1) (Line: 83)
__TwigTemplate_123117ff367d264abf23f7496b887c0273fe10de58a6f144b3cb11b149fbb41c->doDisplay(Array, Array) (Line: 453)
Twig\Template->displayWithErrorHandling(Array, Array) (Line: 420)
Twig\Template->display(Array) (Line: 432)
Twig\Template->render(Array) (Line: 64)
twig_render_template('themes/custom/uids_base/templates/layouts/onecol/layout--onecol.html.twig', Array) (Line: 384)
Drupal\Core\Theme\ThemeManager->render('layout__onecol', Array) (Line: 431)
Drupal\Core\Render\Renderer->doRender(Array) (Line: 444)
Drupal\Core\Render\Renderer->doRender(Array) (Line: 444)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 200)
Drupal\Core\Render\Renderer->render(Array) (Line: 501)
Drupal\Core\Template\TwigExtension->escapeFilter(Object, Array, 'html', NULL, 1) (Line: 131)
__TwigTemplate_a7a50700488f4c82bdf3ed0ef1bc1714883cf230a262c54f3dbea173c31299a5->doDisplay(Array, Array) (Line: 453)
Twig\Template->displayWithErrorHandling(Array, Array) (Line: 420)
Twig\Template->display(Array) (Line: 432)
Twig\Template->render(Array) (Line: 64)
twig_render_template('themes/custom/uids_base/templates/content/node--page--full.html.twig', Array) (Line: 384)
Drupal\Core\Theme\ThemeManager->render('node', Array) (Line: 431)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 200)
Drupal\Core\Render\Renderer->render(Array, ) (Line: 226)
Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}() (Line: 573)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 227)
Drupal\Core\Render\MainContent\HtmlRenderer->prepare(Array, Object, Object) (Line: 117)
Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object, Object) (Line: 90)
Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object, 'kernel.view', Object)
call_user_func(Array, Object, 'kernel.view', Object) (Line: 111)
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('kernel.view', Object) (Line: 156)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 68)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 57)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 52)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 708)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)`

## Error 2
When you add the 'Featured Image' to a Basic Page first, you're unable to add the 'Featured Image' content field block at all? When clicking save, in any format, nothing happens

**Comment by richardbporter** [comment]
I think "Featured image" should not be available for placement via Layout Builder. Thats one too many ways for working with it. Its confusing enough that it has to be added on the Edit form.

**Comment by dnkemper** [comment]
@richardbporter I agree with you 100%

**Comment by richardbporter** [comment]
@pyrello or @joewhitsitt thoughts on this? Somewhat related to https://github.com/uiowa/uiowa/pull/1979.

**Comment by joewhitsitt** [comment]
More related to https://github.com/uiowa/uiowa/issues/1920 I think since it isn't region specific.

I am all for locking down all of More... for v3 except for body until we can figure out how to restrict view modes for featured image, etc. and determine sound use cases. Keep in mind v3 is the default standard MVP, not the bells and whistles version.

**Comment by dnkemper** [comment]
Hahahaha NOOOOOOOOOOO!!!
