### ISSUE TITLE
Consistent heading variables

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#2001]
## Problem

We are running up differences in naming conventions for certain variables. One in particular is the heading variable passed to components to use the correct heading size/level based on where the content is placed.

https://github.com/uiowa/uiowa/pull/1991/files#diff-40b912448b3d2fbe4db1b58449acf9fbR369
https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/sitenow_articles/sitenow_articles.module#L191
https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/templates/content/node--article--teaser.html.twig#L90

Joe: maybe it should be heading_level to work with the component. idk
Sean:  I do think that content_heading doesn’t clearly convey what the variable is to me
Sean:  If I was choosing it from scratch, I think I would go with heading_size or heading_level

## Proposed Solution

Update articles, people, sliders, accordions and anything else that might have these.

**Comment by cory-skeers** [comment]
Closed by #2152
