### ISSUE TITLE
Review Webform Implementation

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#201]
So, we blindly merged in the webform work even though it had only been tested by @briand44. I have pulled his PR comments from https://github.com/uiowa/sitenow/pull/259 so we can revisit this and make sure it is in a stable spot for now.

Since this stuff is already out there (potentially being used), this is probably a high-priority.

>There is still quite a bit of work that needs to be done with this. This basically enables webform, webform ui and honeypot. Configures honeypot to be enabled on all webforms (hidden field functionality only at this point). It removes some elements that I didn't think we needed to allow at this time or are inaccessible (i.e. signature). Sets file uploads to use private files system. Creates default contact form.

```
Few things off the top of my head:
 - Any other webform submodules we should include (webform bootstrap, webform node)?
 - Should we allow wrapper, element and label attributes? If so, do we use default classes or our own?
 - Theming
 - Dialog support?
 - Should we disable client side validation for accessibility?
 - I think there is an issue with file uploads where form builders could add additional allowed file types.
 - Do we need to store libraries locally?
 - Should we be restricting access to other fields or config?
 - Configure testing data?
 - Still need to test viewing and downloading submissions.
```

**Comment by joewhitsitt** [comment]
Here are some initial thoughts while reviewing:

- Holy Toledo Batman! This module is a monster. I thought views was complex...
- webform bootstrap - i don't see a plug and play bootstrap 4 module out there and none of the bootstrap 4 themes out there seem to have webform specific styles yet. The sub-module appears to require the bootstrap base theme. Adam had made a first-pass which helps!
- webform node - i don't think so. the webform field seems to be all we need to make a paragraph type "Form" to allow editors to place the form pretty much wherever with default values (YAML based...). may need to review defaults like multi-page, confirmation URL, scheduling.
- for many of these "should we allow/support x" questions, i say no for now. if anything I see us turning off a few options since these are already live and we haven't had much time to test/review them.

**Comment by GaryRidgway** [comment]
I have reviewed this here if anyone would like to take a look:
https://wiki.uiowa.edu/display/sitenow/Alan%27s+Review+of+the+Webform+Implementation+in+Drupal+8

**Comment by joewhitsitt** [comment]
Looks like there might be more button color work to be done based on Alan's wiki notes: https://github.com/uiowa/uiowa/issues/203

**Comment by joewhitsitt** [comment]
We might want to finish this task using the latest RC: https://www.drupal.org/project/webform/issues/3059429

form multiple with tableDrag seems to just be in a bad spot for Drupal 8 right now, but is starting to get more attention from an accessibility stand point at least.

Claro could be inspiration/reference for form input look/feel

**Comment by richardbporter** [comment]
- [ ] Grant webmasters permission to manage webforms when this is complete.

**Comment by joewhitsitt** [comment]
Closing this issue in favor of separate issues. The functionality is live, webmasters have access. This was a high-priority that got neglected because the steps to success were poorly defined.
