### ISSUE TITLE
URL Redirects work from node/[nid] but not alias

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#202]
Currently only viewable on page.

**Comment by briand44** [comment]
@joewhitsitt can you explain? From what I can tell redirects are viewable on any content while editing.

**Comment by briand44** [comment]
But they don't seem to work for me.

**Comment by briand44** [comment]
I was able to get it to work redirecting from /node/[nid] but not from an alias.

**Comment by joewhitsitt** [comment]
@briand44 not sure if I understand correctly, but I can't reproduce your issues. Please provide more details.

This warns me about creating a redirect off an existing alias but allows me anyway:
<img width="795" alt="Screen Shot 2019-05-30 at 9 19 34 AM" src="https://user-images.githubusercontent.com/4663676/58639225-294ebf80-82bc-11e9-9ea0-59110709a068.png">

I was even able to stack a redirect /asdf -> /about -> <front>:
<img width="353" alt="Screen Shot 2019-05-30 at 9 20 10 AM" src="https://user-images.githubusercontent.com/4663676/58639226-294ebf80-82bc-11e9-9b5c-e31ab1685fe4.png">

Because redirect was added to Basic page, if the alias changes, a redirect is automatically created:
http://hr-d8.stage.drupal.uiowa.edu/family-services

As for the original language defaulting to "none specified", from my digging, I think this is only involved if we have the Core language module turned on and something other than English involved, otherwise redirect works with whatever the browser can detect.
https://git.drupalcode.org/project/redirect/blob/8.x-1.x/src/Form/RedirectForm.php#L70

So for what appears to be a relatively stable module, this issue entails enabling the automatic redirect functionality on the other content types (article, person) similar to basic page.

**Comment by briand44** [comment]
Here is the issue related to this. https://www.drupal.org/project/redirect/issues/2821158

**Comment by joewhitsitt** [comment]
Closing this issue in favor of #233
