### ISSUE TITLE
New site provisions not receiving default paragraphs content

### ISSUE THREAD

**Issue by cory-skeers** [uiowa/uiowa#2023]
Following the SiteNow v2 split, new site provisions are not receiving their default paragraphs content. Pages, media, etc. are there--just the sections/paragraphs for the Home and About Us pages need to be reimplemented.

**Comment by pyrello** [comment]
FYI, I started the process of creating a process for still provisioning the default content for V2 sites, but I forgot to add and enable it for the sitenow_v2 split: https://github.com/uiowa/uiowa/tree/main/docroot/modules/custom/sitenow_v2_default_content

**Comment by richardbporter** [comment]
Closing in favor of https://github.com/uiowa/uiowa/issues/1925.
