### ISSUE TITLE
Padding group drop-down auto-focus when configuring section

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2026]
As reported in https://github.com/uiowa/uiowa/pull/2000#pullrequestreview-461806700, when configuring a section in Layout Builder, the padding (first) drop-down group has focus on it, so it displays as open. This doesn't prevent the form from working correctly, but is not ideal.

![Screen Shot 2020-08-06 at 11 43 30 AM](https://user-images.githubusercontent.com/709009/89558703-29a8eb80-d7da-11ea-91d3-5f63653af65c.png)

**Comment by richardbporter** [comment]
I spent some time digging into what core JS auto-focuses the first element in the off canvas dialog to no avail. Anyone know what does that and if its possible to disable/override?
