### ISSUE TITLE
Refine Layout Builder "Preview"

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2029]
Per some of the feedback from the retro we had after our research spike into Layout Builder, we should refine the way the preview looks when people are actually using the Layout Builder UI.

Some suggested steps:
- [x] Reduce or completely remove the padding inside regions and sections.
- [x] Remove or reduce the margin in between sections.
- [x] Make 'Add section' button and 'Add block' buttons look more similar, possibly add a background color.
- [x] Make 'Edge-to-edge' sections display that way in preview.
- [x] Remove dotted/dashed lines from around sections, regions, and blocks except when they are hovered over.

**Comment by pyrello** [comment]
Here is partially what that could look like using the homepage homepage as an example:
![Screen Shot 2020-08-06 at 3 06 36 PM](https://user-images.githubusercontent.com/709009/89577585-86b29a80-d7f6-11ea-81a3-3488375b881c.png)
![Screen Shot 2020-08-06 at 3 06 53 PM](https://user-images.githubusercontent.com/709009/89577588-874b3100-d7f6-11ea-9332-61728a6da72e.png)
![Screen Shot 2020-08-06 at 3 07 05 PM](https://user-images.githubusercontent.com/709009/89577591-87e3c780-d7f6-11ea-9840-d9b4d02845a7.png)

**Comment by richardbporter** [comment]
IMO it would be nice to show only one add block link per section. The first shows up in the middle of content and really clutters the interface.
![image](https://user-images.githubusercontent.com/1068523/90268648-f8a16a00-de1c-11ea-89d4-e9982b20f3c2.png)

**Comment by richardbporter** [comment]
It might also be nice to tone down the styling of the add block/ section links as they catch the eye and take up a lot of real estate.

**Comment by bspeare** [comment]
@richardbporter what are you thinking for the styling on that?  Less padding?

**Comment by bspeare** [comment]
> IMO it would be nice to show only one add block link per section. The first shows up in the middle of content and really clutters the interface.
> ![image](https://user-images.githubusercontent.com/1068523/90268648-f8a16a00-de1c-11ea-89d4-e9982b20f3c2.png)

@richardbporter Where are you seeing the duplicate "Add Banner" blocks?

**Comment by richardbporter** [comment]
> @richardbporter what are you thinking for the styling on that? Less padding?

I'm not sure. I think that could probably wait until later as an additional enhancement. It'd be cool if it sort-of stayed out of the way but that might be hard for people to see. 

Maybe something like:
![image](https://user-images.githubusercontent.com/1068523/90416563-4239c100-e078-11ea-9331-858f8b919045.png)

Like I said, doesn't have to happen now.

**Comment by richardbporter** [comment]
> IMO it would be nice to show only one add block link per section. The first shows up in the middle of content and really clutters the interface.
> ![image](https://user-images.githubusercontent.com/1068523/90268648-f8a16a00-de1c-11ea-89d4-e9982b20f3c2.png)

Sorry, there are no duplicate buttons. It just looked that way because the sidebar is not styled - its stacked on top of the other region which gives the appearance of a duplicate button.

**Comment by bspeare** [comment]
@pyrello Do we want the "Add Section" and "Add Block" options to look the same?  I think it is kind of confusing to style them the same.  Perhaps something like this would be better?

<img width="1312" alt="Screen Shot 2020-08-18 at 1 18 18 PM" src="https://user-images.githubusercontent.com/1036433/90550376-7df68880-e155-11ea-86ee-f67ccaae56db.png">
