### ISSUE TITLE
Remove monthly RSS feed on SiteNow Articles

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#2031]
## Problem
Based on the month of articles the user views, the RSS link changes to only show the current month's articles. Not particularly valuable.

## Proposed Solution
Change it so that is always the main RSS feed (link and text) or remove it completely from the monthly contextual display while maintaing the main feed. Beware: The path is dynamic based on site owner configuration.

**Comment by richardbporter** [comment]
Should we also remove the icon from the "year displays" as well? Or just month?

**Comment by joewhitsitt** [comment]
probably. there should really only be the one feed...

**Comment by richardbporter** [comment]
I would say at that point the arguments could just be removed from the view but people may be using these. I could see a use case for creating aggregator blocks for "2020 Articles" and so maybe we just leave it for now.

**Comment by joewhitsitt** [comment]
i wouldn't worry too much about that. the whole point of the feed is supposed to be new/updated, not an peek into an archive. i say we just make a note that these were never supported, unintentional and are now gone.
