### ISSUE TITLE
Entity Types and sub modules cannot be enabled properly

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#2040]
After uninstalling the Sitenow Articles and Sitenow People modules, and trying to enable the Entity Types, Entity Types Articles and Entity Types People modules (for testing purposes), I get the following error:
<img width="907" alt="Screen Shot 2020-08-13 at 12 46 50 PM" src="https://user-images.githubusercontent.com/3067017/90168938-7b65ee80-dd63-11ea-96d6-2aba9455941a.png">

**Comment by joewhitsitt** [comment]
Is this issue still needed @mark-bennett-uiowa ?

**Comment by richardbporter** [comment]
I don't think this module is in the codebase anymore.
