### ISSUE TITLE
Address utility classes in uids base

### ISSUE THREAD

**Issue by ethanstjohn** [uiowa/uiowa#2047]
## Problem

After removal of the "ALLOWED CLASSES" paragraph https://sitenow.uiowa.edu/documentation/wysiwyg we now need updated docs on utility classes in UIDS Base.

The paragraph was as follows for reference:

ALLOWED CLASSES
To extend formatting of content within the WYSIWYG, certain HTML classes are allowed on the following elements: a, blockquote, p (text-align-* only), div, table, thead, tbody, tfoot, th, tr and td.

Some of those allowed classes are:
    - w-25, w-50, w-75, w-100: Element widths of 25%, 50%, 75% and 100%.
    - align-baseline, align-top, align-middle, align-bottom: Vertical alignment of inline and table cell elements.

## Proposed Solution

On https://sitenow.uiowa.edu/documentation/wysiwyg at the bottom write a new section for utility classes that can't be applied via the styles dropdown.

**Comment by joewhitsitt** [comment]
So this will be a bit more trick than last time as we aren't straight loading the whole bootstrap framework and all of the utility classes that come with it.

To update this documentation we need to split it off into minimal and filtered html sections as there are now two different editors available to users depending on the content they are trying to work with.

For each of those, you need to capture which elements we are allowing and which of those elements allow classes or other attributes. https://default.local.drupal.uiowa.edu/admin/config/content/formats

After that, we need to figure out what utility classes we are actually supporting and which ones are available for use. On-glance, I can't remember how those stylesheets are being loaded. @cory-skeers might remember what styles are being loaded into the wysiwyg so you can reference those.

**Comment by joewhitsitt** [comment]
Had a customer (power user) today ask about whether certain uids classes were available to use in v2. I said it was the same theme, but those classes might not be available on the paragraph bundle you are trying to use them. Without sacrificing our stylesheets on demand method, it would be nice to provide some guidance about which classes are available to use and where.

**Comment by bspeare** [comment]
Do we still want to do this?

**Comment by bspeare** [comment]
Checking on this again.  We do have some documentation on table classes at https://sitenow.uiowa.edu/documentation/wysiwyg and we can always reopen a dedicated issue to more classes as they surface.
