### ISSUE TITLE
Parent title field on certain block types

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#2048]
## Problem

To provide accessible DOM order to all parts of a page, we should provide a consistent option across certain block types to allow a parent title to be added.

## Proposed Solution

Look into extending the headline field or creating our own combination field.

- slider, collections, articles, people, image gallery
- possibly text area block in the future?

Instead of using a textfield, a long text field would allow future enhancements like word highlighting.

- optional
- long text field with a length limit (255?), 1 row display.
- heading size if not extending the existing headline field.
- visually hidden title (boolean)
- font selection (select)
- other style options?

If set, the parent title would set the children items appropriately making sure the DOM follows proper heading order. If not set, the children headings field would display and be configurable to set the children items.

**Comment by cory-skeers** [comment]
The start of a custom compound field is available in the block-headline-field branch. Basic schema/formatter/widget setup to build off of when it's time to work out the specifics.

**Comment by joewhitsitt** [comment]
Did you try extending off the existing headline field? Just curious. Not sure if it is wise to build so much off a contrib module.

**Comment by cory-skeers** [comment]
Nope--so far it's built on core fields, with a title text field, select list for size (so those two recreating the headline field, I think?) and a checkbox to visually hide the title.

Did it that way just so we'd have a good base for adding any sorts of field types, but I think I'd lean toward not building off a contrib module, if we're already in the position of needing to make a compound field.

I also have a tendency to prefer spaghetti-code routes, though...

**Comment by joewhitsitt** [comment]
Might be a good issue to tackle in tandem: https://github.com/uiowa/uiowa/issues/2001
