### ISSUE TITLE
Add default padding to text area block if it is used with a background color

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#2054]
# Problem

If you add a background color to the text area block, it will appear without default padding. 

<img width="1496" alt="Screen Shot 2020-08-20 at 1 19 38 PM" src="https://user-images.githubusercontent.com/1036433/90809989-e5dcd880-e2e7-11ea-87cf-61cee63c8968.png">

# Proposed solution

Add default padding to text area block if it is used with a background color. 

<img width="1598" alt="Screen Shot 2020-08-20 at 1 19 58 PM" src="https://user-images.githubusercontent.com/1036433/90810058-0311a700-e2e8-11ea-82b8-f9dbf837151d.png">

**Comment by mark-bennett-uiowa** [comment]
This appears fixed with #2076.
