### ISSUE TITLE
Develop alternative layout/style options for articles/people

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#2058]
## Problem
https://github.com/uiowa/uiowa/issues/1789 only went as far as getting the articles/people block functionality into layout builder as a list.

## Proposed solution

Decide how to provide other layout options within layout builder for this type of content.

- css class based styles?
- view mode switching?
- https://www.drupal.org/project/views_layout looked the most promising in a way to manipulate the view with the layout builder api.

**Comment by bspeare** [comment]
@joewhitsitt can we close in favor of https://github.com/uiowa/uiowa/issues/4453?  Seems like we have a lot of issues about the article layout.

**Comment by joewhitsitt** [comment]
I think this was related to providing different style/layout options for the v3 views blocks as it came from https://github.com/uiowa/uiowa/issues/1789 and then got later confused with the article/person node full view mode stuff.

this is done more or less.
