### ISSUE TITLE
Allow minimal_html and filtered_html to have an <hr> with a class

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#2060]
# Problem 

With the removal of the spacer/separator block, we need the ability to add a spacing and clear option within the markup: https://github.com/uiowa/uids/issues/289

# Proposed solution 

Allow `minimal_html` and `filtered_html` to use the `element--spacer-separator` class on `<hr>` tags.   Ideally, we could open up the `<hr>` class for future classes since I could see us developing different line styles.

**Comment by mark-bennett-uiowa** [comment]
Will this layout still be possible with the removal of the Spacer/Separator? Or am I understanding this incorrectly?
<img width="1356" alt="Screen Shot 2020-08-20 at 4 04 11 PM" src="https://user-images.githubusercontent.com/3067017/90825748-f9e00480-e2fe-11ea-8717-eba5d45a5ca0.png">

**Comment by joewhitsitt** [comment]
Aka modify `<hr>` to `<hr class>` for both formats and export the changes. admin/config/content/formats

Could also document the html elements allowed in documentation as part of https://github.com/uiowa/uiowa/issues/2047
