### ISSUE TITLE
Increase margin for basic pages after feature image

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#2063]
Before the feature image for basic pages change was added a few days ago, the distance between the bottom of the section/page title hero block and the top of the main content was 3rem. Basic pages with a page title hero were created in a new section above the header, and the page title hero block was added to this section and styled in LB. The header had the title and breadcrumbs removed so that they would only appear in the new section with the page title hero block. It appears that this distance was due to the 3rem margin-bottom of the "empty" header section:
<img width="1403" alt="Screen Shot 2020-07-22 at 1 09 53 PM" src="https://user-images.githubusercontent.com/3067017/88212711-4d3a3680-cc1d-11ea-8100-05ed03689ca9.png">
When these pages were switched over to use the new feature image part of the header section, and the previously created section + page title hero blocks were removed, the title and breadcrumb were returned to the header, but the distance is now 1.25rem and due to the margin-top of the class="block block-layout-builder block-field-blocknodepagebody" div.
<img width="1508" alt="Screen Shot 2020-07-22 at 1 07 53 PM" src="https://user-images.githubusercontent.com/3067017/88213304-29c3bb80-cc1e-11ea-9906-24c61b0d6c49.png">
Could this distance be increased if the feature image is used on a page?

**Comment by bspeare** [comment]
# Proposed Solution 

This needs to be adjusted https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/scss/layouts/onecol.scss#L15 and https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/scss/layouts/page--left-sidebar.scss#L85 to `$desktop-width-gutter`.
