### ISSUE TITLE
Create custom events block for use in Layout Builder

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#2071]
There are quite a few different options here. Considering there is already an event block built out, it could be confusing to have a separate events block for content hub integration if we plan on making the static event block generally available. Additionally, there has been talk of sites needing an event content type which further complicates things.

# Potential options
1. Create a separate event list block that pulls events from content hub.
  a. Keep the static event block in a split.
  b. Make the static event block generally available.
2. Integrate the event list block into the static block and allow the user to choose.
  a. This could also include a single event reference from content hub which would make for three choices.
3. An event content type could present a fourth option if integrated into this all-encompassing event block.

MVP, and probably the path of least resistance, is probably option 1 while keeping the static block in a spilt. However, I think the static event option is nice to have and offers more flexibility - we will eventually have requests for one-off events that are not on content hub for some reason. Thats why I prefer option 2 but have concerns of future integration of option 3, mainly over how intuitive and usable the interface would be. It could be done though with the states API and is at least accurately representing the myriad ways of creating/referencing events on campus.

**Comment by bspeare** [comment]
I like option 2 if that scenario is possible.

**Comment by joewhitsitt** [comment]
Again, I wasn't at the discussion for this, so I don't know if some of these points have been expressed or are not relevant.

So the current block is a single instance in which you need to place multiple instances together to achieve the homepage look. To me then I see this as two blocks then. Though it presents multiple options in Layout Builder, it will be clearer what the editor will get out of each one.

Event - option for page specific, single reference to content.uiowa.edu or local event content item.
Events - Pull upcoming from content.uiowa.edu based on filters or a view of local event content items. Listing display to start similar to articles/people. Less control over layout. Potential to merge external and local event content together.

The problem with a single reference to content.uiowa.edu is that it will be static and become a past, stale content if it is not maintained. I don't think events/content.uiowa.edu really supports past events.

IMO, I see the events content type as a feature split and not v3 default until there is a clear picture about the future of events on campus. The feature split can contain a modified version of the block that merges in local events. Local events (though desired by some groups) seems to further take us away from the previously stated content hub visions for campus that includes news and events (and maybe people).

**Comment by richardbporter** [comment]
I like that approach @joewhitsitt, thanks.

> The problem with a single reference to content.uiowa.edu is that it will be static and become a past, stale content if it is not maintained.

The same can be said for a static event so I don't really see that as a problem necessarily.

**Comment by joewhitsitt** [comment]
As for the single event reference, if autocomplete by title, I think you will want to make sure other identifying information is included (event id, start date) because I know there are several events with the same name (e.g. ICON Training Session). The downside to event id is that content.uiowa.edu and events.uiowa.edu don't have the same id... which could be confusing to an editor on which one they provide.

**Comment by richardbporter** [comment]
I'm wondering if we can shelve the other features here until we have the MVP of an events listing - basically what we can currently do in paragraphs. Or does it all need to be done up front? I'm guessing no but it would require an update hook later.

Also, looking for help on a couple things in #2086.
