### ISSUE TITLE
Adjust placement / use of moderation control

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#2078]
# Problem

The "Main content" area is often empty if no Body content has been created.     Having this Main content area rendered within the page layout creates extra spacing due to the default spacing that we are adding to Sections. 

<img width="1752" alt="Screen Shot 2020-08-24 at 3 07 52 PM" src="https://user-images.githubusercontent.com/1036433/91091269-fb217200-e61b-11ea-95a7-3501613b049e.png">

# Proposed Solution

- Remove "Main content" area from rendering if there is no Body content.
- Remove "Links" field.
- Or if the section is empty, render the "Main content" section last so that the Moderation control options will appear at the bottom of the page instead of in the middle. 

<img width="1288" alt="Screen Shot 2020-08-24 at 3 13 40 PM" src="https://user-images.githubusercontent.com/1036433/91091593-6bc88e80-e61c-11ea-8b16-44af5e0feeca.png">

**Comment by pyrello** [comment]
This is how this looks now:
![Screen Shot 2020-08-26 at 7 16 06 PM](https://user-images.githubusercontent.com/709009/91369155-a70bbe80-e7d0-11ea-9be8-1600c7614a04.png)

I'm cool with removing the "Links" because it doesn't seem like it ever gets used, at least so far.

I'm not sure about the rest of it. FWIW, this is the Coronavirus site, which splits `core.entity_view_display.node.page.default`, so it has its own template. This is also a different template than what is used in SiteNow V3.

**Comment by cory-skeers** [comment]
I worked on this some, but had mostly focused on changing how it appears on the editor side, and didn't get to a good resolution.

The main part that needs addressing is on the page, rendering the field w/out content leads to extra spacing. I've added sections above to draw attention to it:
![image](https://user-images.githubusercontent.com/49074566/91449115-5764db80-e840-11ea-9c99-5c5b4fbd7fe4.png)

![image](https://user-images.githubusercontent.com/49074566/91449571-e2de6c80-e840-11ea-9b48-bc7c30b9ee78.png)

**Comment by mark-bennett-uiowa** [comment]
I was curious about some of this also, as to (1) were fields like Links needed, etc., (2) is it possible to "hide visually" a section/block in LB, etc., and (3) to ensure that I could recreate the Main content section's default layout (Moderation control, Body, Links) if I moved to a different solution for certain pages and had to revert back.

I vote for removing the Links if we arent using it. Also, should I be adding the Moderation control block into a new section if I remove this default Main content section?

**Comment by pyrello** [comment]
Here is some clarification I would like to achieve for this issue:
* What changes are recommended for SN3? The main content section is part of the template that enforces the default layout preference for using a sidebar.
* What changes are recommended for the Customization Split? The main content section is part of a template that adds the body by default to accommodate the scenario where someone just wants to create a "basic" page (e.g. just use the body field).
* Is the Coronavirus split going to follow the Customization Split? Or do we want a different template entirely?
* How do we want to handle other site splits that make adjustments to page display, like uiowa.edu?

Additionally, the moderation control is a functional block that is provided to mimic the functionality that is available when not using LB for display. My recommendation is to place moderation control in its own section at the very beginning and lock it down completely.

**Comment by mark-bennett-uiowa** [comment]
> Additionally, the moderation control is a functional block that is provided to mimic the functionality that is available when not using LB for display. My recommendation is to place moderation control in its own section at the very beginning and lock it down completely.

@pyrello I fully support this. I was adding this Moderation control block back in to a custom section as to not lose the block, but would prefer it be placed directly below the Header section and locked down.

**Comment by pyrello** [comment]
The reason that I would place it before the header section is because the header section can be really tall (if there is a featured image) and I think the block is less useful if it isn't at the top of the page because people might assume that its not there.

**Comment by bspeare** [comment]
It could also be interesting to play around with how the block displays.  What if it was fixed to the bottom and only appear on hover and focus?  I've posted an example screenshot below that I imagine we could reduce the height on further. 

<img width="1685" alt="Screen Shot 2020-08-28 at 11 25 34 AM" src="https://user-images.githubusercontent.com/1036433/91590666-535cba80-e921-11ea-8f0e-1013dc0b2d49.png">

**Comment by mark-bennett-uiowa** [comment]
@bspeare I vote for THIS!!!! Beautiful, and exactly what I think I am looking for.

**Comment by cory-skeers** [comment]
Started a PR (#2102) for config changes removing the links field and moving the moderation control into a separate section. Right now it's placed above the header image, but we can use that as a sandbox to try out an approach like @bspeare

**Comment by cory-skeers** [comment]
And the extra margin that gets added if an empty body content field gets rendered still needs to get addressed 😬

**Comment by bspeare** [comment]
There is now even more space surrounding this with the latest style updates:

<img width="1516" alt="Screen Shot 2020-09-24 at 4 00 59 PM" src="https://user-images.githubusercontent.com/1036433/94200395-f866a680-fe7f-11ea-9175-a0c387f65696.png">

**Comment by pyrello** [comment]
lol... /sigh

**Comment by pyrello** [comment]
I think this is done.
