### ISSUE TITLE
Collection accordion styling issues

### ISSUE THREAD

**Issue by dnkemper** [uiowa/uiowa#2080]
Looks like the collection body for the accordion view mode and the headline and collection body for the detailed list view mode need a different background color to not clash with section background

<img width="1343" alt="Screen Shot 2020-08-24 at 4 39 08 PM" src="https://user-images.githubusercontent.com/16872949/91099901-c61c1c00-e629-11ea-9418-54aa3764e7ce.png">
<img width="977" alt="Screen Shot 2020-08-24 at 4 47 00 PM" src="https://user-images.githubusercontent.com/16872949/91099907-c7e5df80-e629-11ea-96cf-cec0a03d87d2.png">

**Comment by joewhitsitt** [comment]
I am addressing this in https://github.com/uiowa/uiowa/pull/2069

**Comment by dnkemper** [comment]
@joewhitsitt for the win!
