### ISSUE TITLE
WSOD when editing layout on page after attempting to add Main content block in LB

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#2088]
@pyrello @richardbporter Any thoughts on how to fix this?

Apparently Im not the only one having this issue: [https://www.drupal.org/project/layout_library/issues/3099195](https://www.drupal.org/project/layout_library/issues/3099195).

What I tried to do was create a new section (2 column, 75/25) in which I could put the Main page content block in the left (75%) column, and then stack two Statistic blocks in the right (25%) column. I didnt want to lock down the left hand main content block to admin-only editing, as I wanted to allow editors to edit the content in that part of the section. Basically I want to create a section like the opening section on [https://uiowa.edu/academics/leading-programs](https://uiowa.edu/academics/leading-programs), but allow content editors to edit the page rather than get into LB and change a text area in that left-hand column.

To reproduce error: Add a new section, set to any # of columns (doesnt matter % widths). In the new column, click on dropdown arrow and select More > System > Main page content. It does NOT add the new column (it appears as if it cant select the option). After this point, if you exit out without Discarding Changes, it will lock the page in a WSOD with the error: Temporarily Unavailable. The website that you're trying to reach is having technical difficulties and is currently unavailable...

I tried a cache rebuild on the prod site, but it did not fix the problem. Is there a remote command I can use to discard the changes or to avoid this WSOD?

**Comment by mark-bennett-uiowa** [comment]
I solved the WSOD by adding /discard-changes to the end of the URL: https://americanstudies.prod.drupal.uiowa.edu/node/123/layout/discard-changes. This got me out of the WSOD but the issue with adding the Main page content block still remains. A little research seems to suggest that 8.9.0 may have fixed this issue, but there are conflicting reports.

**Comment by mark-bennett-uiowa** [comment]
UPDATE: By adding the Body field it allows me to show the content that I need in that column, so my need has been taken care of. **In order to solve the WSOD issue, should be simply block the Main page content block from the available blocks?**

**Comment by joewhitsitt** [comment]
>simply block the Main page content block from the available blocks?

Funny you should say this. I am doing just that in https://github.com/uiowa/uiowa/pull/2089 because I don't think we have solved all the issues with most of these system blocks to have them available for use by any editor. I can extend this to the collegiate split with enough buy-in from existing sites.

**Comment by mark-bennett-uiowa** [comment]
@joewhitsitt thanks so much Joe. Yes, I would buy into this for sure on the collegiate split (unless we are moving ourselves over to the SiteNow standard anyways).

**Comment by mark-bennett-uiowa** [comment]
Thanks @joewhitsitt !

**Comment by joewhitsitt** [comment]
Actually, based on discussions @mark-bennett-uiowa, I was going to remove these restrictions for collegiate in the #2089. I suggest you talk to Sean or Ben about how to deal with this issue from happening again.

**Comment by pyrello** [comment]
@mark-bennett-uiowa I think there are some things getting conflated here. There is a template section for the page content type called "Main content". That section contains Moderation control, Body, and Links. Separately, there also appears to be a "Main page content" block that allows for adding... I'm not sure what.

So, to restore the "Main content" section, you just need to create a section and add the moderation control, body, and links blocks into that section.

**Comment by mark-bennett-uiowa** [comment]
@pyrello Yes Sean, thank you. I did get this figured out and fixed already, and was able to get around the WSOD lock by the steps I mentioned above. I was leaving this in here, so that if we were restricting blocks to add, I was suggesting removing the Main page content block since it created that WSOD lock (the community seems to have this issue also - see link above).

**Comment by mark-bennett-uiowa** [comment]
If we are removing the "Main page content" block from the available options in #2089 , then we can close this issue.

**Comment by pyrello** [comment]
FYI, the link posted above is in the Layout Builder Library module issue queue, which is a module we are not using yet.

**Comment by mark-bennett-uiowa** [comment]
Yes, but it is still an issue that exists with that block in our system, even without the additional module. It was just the best reference to the issue I could find quickly.

**Comment by mark-bennett-uiowa** [comment]
Closing this issue. Not fixed. The issue still exists, and the System > Main page content block is still available under the More... option in the LB list. Not sure if this will be fixed at any point, but it can be used as a warning to avoid this option.
