### ISSUE TITLE
File uploads are not limited

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#209]
256M seems excessive. We should limit it to like 50M.

**Comment by joewhitsitt** [comment]
The .ini file is where this is set ultimately for the server, so i don't know if we want to change that globally, but https://github.com/uiowa/uiowa/commit/0ba05cc4e64c894346582c7078997c01da008790 sets it for the media fields. section, card, article, wysiwyg images all "reference" one of these.
