### ISSUE TITLE
Enable search_api module for default platform to prevent need to re-export policy.clas.uiowa.edu config

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2091]
Currently, when new entities are added to the system or when existing entities are changed in the system, this sometimes results in needing to re-export the config for policy.clas.uiowa.edu. If we were to enable the search_api module platform wide, the entry that gets added to entity_view_display for each entity would be present for the whole platform and not need to be split for the policy site. While this may add a small amount of unnecessary overhead to each site, it would reduce on ongoing maintenance burden.

**Comment by mark-bennett-uiowa** [comment]
I fully support this. Are there are concerns with doing this for the whole system?

**Comment by joewhitsitt** [comment]
The possible performance hit to all sites for one site is my only concern. Not sure if it is an issue. I'd be okay with trying it and seeing. There is separate site specific configuration that has to be set to actually scan and store right?

**Comment by pyrello** [comment]
I don't imagine there will be much in the way of performance hit, other than that there is with enabling any module. To actually use the Search API module, you have to enable another module, such as Search API DB to have something it can index from. I don't think there is any additional processing when viewing a node, or if there is that it would be effectively negated by caching.
