### ISSUE TITLE
LB Collection enhancements

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2104]
# Problem
After the recent update to require at least one collection item, the collection now shows the add collection item form for the first item by default. This is a little confusing because it seems like the fields are related to the whole collection rather than the first item.
![Screen Shot 2020-08-28 at 12 57 57 PM](https://user-images.githubusercontent.com/709009/91601991-2fed3c00-e930-11ea-85b4-5c2145e8ec08.png)

# Proposed solution
Add some kind of label, outline, or other indicator to let the user know that the form items are for a nested item. This could be similar to how the collection items display after they are created:
![Screen Shot 2020-08-28 at 1 12 08 PM](https://user-images.githubusercontent.com/709009/91601984-2b288800-e930-11ea-99e4-55ce9055e8ab.png)

Additionally, I think a little bit of tweaking might be in order for the post-save view of the collection items.

**Comment by pyrello** [comment]
# To do
- [x] Add label and outline around collection item form.
- [x] Remove 'Collection' from 'Collection body' label for that field.
- [x] Rename 'Collection Items' to 'Items'.

**Comment by cory-skeers** [comment]
Another option could be to remove required from the config, and add a validation to check that at least one item has been added. Would keep it from auto-expanding an item field, but still serve to prevent an empty collections block from being created.

**Comment by pyrello** [comment]
I'm not opposed to having the form be expanded by default, as it is less clicks to get started.
