### ISSUE TITLE
Add a condensed-width section style to oppose the extended-width section style?

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#2105]
Since we have the fixed-width section style, and the extended width section style, what are people's opinions on a condensed-width section style since the Left and Right padding styles are being removed in #2076. Here is a screenshot of an example that is used on the program blocks I currently have:
<img width="1647" alt="Screen Shot 2020-08-28 at 1 40 39 PM" src="https://user-images.githubusercontent.com/3067017/91604355-1e0d9800-e934-11ea-8526-4dffca184899.png">

Notice the left and right padding added in the description under the heading. This was to keep the width of that block from reaching the full fixed-width style. Thoughts? Tagging @bspeare since we talked about this earlier.

**Comment by pyrello** [comment]
I was calling this a "narrow" container.

**Comment by mark-bennett-uiowa** [comment]
@pyrello do we have any defined fields/blocks/etc currently that use a similar nomenclature? Im good with either, I just thought condensed sounded more professional; but it isnt apparently the antonym of extended, narrow is.

**Comment by pyrello** [comment]
I'm not sure off the top of my head. Narrow makes more sense to me as describing width. Condensed to me reads as shorter.

**Comment by mark-bennett-uiowa** [comment]
good call. if others are good with it too, Im good with it.

**Comment by pyrello** [comment]
This was completed with #2076

**Comment by mark-bennett-uiowa** [comment]
I see this is still in planned, so I am linking an issue I just added this morning concerning additional, unneeded padding being added to the narrow container: #2248 .

**Comment by pyrello** [comment]
This issue was moved to done yesterday. I added your new issue to Parking Lot, so you can introduce it in standup on Monday.
