### ISSUE TITLE
Change all headers to the serif option by default?

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#2107]
Personally, having h1's (page titles) as serif and then h2-h6 as the sans-serif option is causing some issues. Personally on the CLAS sites, I have been changing all h2-h6 to serif using the class="bold-headline bold-headline-serif" styling. It looks like there seems to be a push for this on the uiowa.edu site as well, between the "uids-component--bold-intro" class for paragraph intros and the changing of the headers on various pages. Here are some screenshots:
![Screen Shot 2020-08-28 at 1 52 38 PM](https://user-images.githubusercontent.com/3067017/91605817-af7e0980-e936-11ea-9167-1db6c8d2f795.png)
Here is what the existing header looks like:
<img width="1625" alt="Screen Shot 2020-08-28 at 1 53 17 PM" src="https://user-images.githubusercontent.com/3067017/91605836-b9077180-e936-11ea-9774-dad4c06e9ab8.png">
Tagging @bspeare as we have just talked about this.

**Comment by mark-bennett-uiowa** [comment]
Let's see a hierarchy with h1, h2, maybe h3 in slab serif font, others in sans-serif?

**Comment by mark-bennett-uiowa** [comment]
Discussed this with the design team. No final decision was made, but there was some discussion about possibly making h2 serif by default. I still vote for at least h1 through h3. We could leave h4 through h6. Could possibly deal with this if we had a solution from #2532 but that still doesn't mean content editors are going to want the same thing or remember to do so.

**Comment by bspeare** [comment]
@mark-bennett-uiowa can we close this one in favor of https://github.com/uiowa/uiowa/issues/2532#issuecomment-1040864388?

**Comment by bspeare** [comment]
It is now possible to adjust header styles within the WYSIWYG so I am going to close this issue.
