### ISSUE TITLE
Add SiteImprove Module to Sitenow v1 Standard and Custom websites

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#2120]
## Problem

v1 customers can't use the benefits of the Drupal module unless they have a developer implement it one-off.

## Proposed Solution

Add it to sites/all for both standard and custom and set configuration and permissions for all (taking note of sites that have non-webmaster type roles)

**Comment by richardbporter** [comment]
I don't think this is worth doing.

**Comment by joewhitsitt** [comment]
With EOL approaching, closing.
