### ISSUE TITLE
Moderation control block showing in various places

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#2134]
I didnt see this behavior during testing, but on the various CLAS department sites, the Moderation control block is showing in one of three places:

- In its own section at the top of the page (as #2102 was handling).
- Directly underneath the title block in the Header section (see screenshot below):<img width="1555" alt="Screen Shot 2020-09-03 at 2 18 34 PM" src="https://user-images.githubusercontent.com/3067017/92158232-3167aa00-edf1-11ea-949d-3608409e92e0.png">
- At the top of the Main Content section about the content block:<img width="1551" alt="Screen Shot 2020-09-03 at 2 11 07 PM" src="https://user-images.githubusercontent.com/3067017/92158220-2dd42300-edf1-11ea-95f9-1a6e73f5bcc5.png">

Do I need to rebuild cache? Is this an issue with the PR? Is this a side effect of the PR? Just curious if anyone else has noticed this.

**Comment by cory-skeers** [comment]
Are the ones that aren't the first case existing pages, and if you create a new page on that site, is it in the top spot?

I believe it's only applying to new pages or pages which haven't had their template adjusted at all.

**Comment by mark-bennett-uiowa** [comment]
It's weird @cory-skeers as two similar existing pages on two different sites can have it in different regions, and then there are existing pages with it in the correct spot based on your PR. New pages appear as though they are correct from what I have seen,; I have been creating pages on the International Studies site all morning and it has so far.

**Comment by cory-skeers** [comment]
Note: This should only have affected existing sites, and not any new provisioned v3 sites.

**Comment by pyrello** [comment]
@mark-bennett-uiowa Can you post some example links? It seems like this would only be the case with pages where you modified the layout. Depending on when the page was created and the modification made, it would show up wherever the moderation control in the default template when the layout of the page was modified.

To "fix" it, we would need to either manually update those pages to create a section and place the moderation control similar to how it is in the current default template, or to write an update hook to do the same thing.

**Comment by mark-bennett-uiowa** [comment]
@pyrello Here is some examples:
[https://internationalstudies.prod.drupal.uiowa.edu/research](https://internationalstudies.prod.drupal.uiowa.edu/research),
[https://internationalstudies.prod.drupal.uiowa.edu/undergraduate](https://internationalstudies.prod.drupal.uiowa.edu/undergraduate), and
[https://internationalstudies.prod.drupal.uiowa.edu/undergraduate/tracks](https://internationalstudies.prod.drupal.uiowa.edu/undergraduate/tracks).
The first one was created prior to the update to this field in LB. The second one was created prior to the update also, but I manually moved the field into a new section because I had previously adjusted the layout. The third one was created after the update, and is working as intended.

I am fine with the solution you mentioned (manually update the pages), I was more curious now if there was an automatic way of moving this field without resetting the layout. I created numerous pages (namely the top level pages; About, UG Programs, Grad Programs, Research, etc) prior to this update, in which I adjusted the layout for either the behind-title-image or for program blocks. Some of these pages I should be able to Reset the layout and solve the issue. The UG and Grad pages I wont be able to without rebuilding them (not preferred). In these cases, I can just manually move the field. We can close this issue if that works for everyone.

**Comment by pyrello** [comment]
@mark-bennett-uiowa Ideally there would be some way of having individual sections being reset to default, but that doesn't exist yet. 

Created a feature request on drupal.org: https://www.drupal.org/project/drupal/issues/3171452. To be clear though, this is likely a far future thing and probably your best option is to manually reset this block on any pages affected.

**Comment by mark-bennett-uiowa** [comment]
@pyrello No worries Sean, and thank you for posting the request at d.org. I figured it would take some manual intervention, and in the end, is not really that big of a deal. I will make the manual updates to the pages I can find, and revert the others that dont really have true LB layout changes. We can close this now if that works for everyone.

**Comment by pyrello** [comment]
Just adding a note that I closed the drupal.org issue I opened. I had a chance to think through how complicated it would be to create that functionality and decided that the juice just wasn't worth the squeeze.
