### ISSUE TITLE
Section styles not visible when background image uploaded

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#214]
Its confusing that the section styles are not visible when a background image is set. We should maybe disable those if an image is set or output some sort of message, help text, etc.

**Comment by joewhitsitt** [comment]
These allowed style classes and all the combinations would be hard to throw validation logic at. I think better help text, docs, training is the way to go based on the current functionality.

**Comment by richardbporter** [comment]
Could not get a custom constraint to work for the section field: https://www.drupal.org/docs/8/api/entity-api/entity-validation-api/providing-a-custom-validation-constraint

Just improved docs for now.
