### ISSUE TITLE
Fix twitter embed preview in ckeditor

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#2147]
## Problem

Currently shows up as a small yellow dot (blockquote with no height/width). Other oEmbed objects either show blockquote content (facebook) or a preview placeholder (instagram).

<img width="1012" alt="Screen Shot 2021-10-05 at 4 22 25 PM" src="https://user-images.githubusercontent.com/4663676/136104881-9d0584e7-72b1-4106-8eb9-9396e2f0e285.png">

**Comment by richardbporter** [comment]
Potentially look at SNv1 as an example of a placeholder image.

**Comment by dnkemper** [comment]
NOTE: in D7, look at sitenow_media.module file on line 60 (wish could link directly to it haha)

Looks like we're rendering a default image on our D7 platform. Not sure if we want to do that for D8/9 ?

`$path = drupal_get_path('module', 'sitenow_media') . '/assets/thumbnails/twitter_thumbnail.png';`

**Comment by joewhitsitt** [comment]
Found this issue today: https://www.drupal.org/project/drupal/issues/3072317 via https://www.drupal.org/project/media_entity_twitter/issues/3081244

**Comment by joewhitsitt** [comment]
More twitter instances (not necessarily usage) than I thought (12/15/2023):

site	count
cbig.iibi.uiowa.edu	3
cheatum.lab.uiowa.edu	1
communicationstudies.uiowa.edu	1
debate.uiowa.edu	5
diversity.uiowa.edu	65
education.uiowa.edu	7
engineering.uiowa.edu	2
fictionawards.writersworkshop.uiowa.edu	1
fys.uiowa.edu	1
glefevre.iihr.uiowa.edu	1
gpsg.uiowa.edu	2
hawkeyemarchingband.uiowa.edu	1
holoreality.lab.uiowa.edu	3
intranet.writersworkshop.uiowa.edu	2
jabbari.lab.uiowa.edu	8
jtucker.lab.uiowa.edu	2
lamp-mission.sites.uiowa.edu	1
law.uiowa.edu	2
lhpdc.law.uiowa.edu	3
mailloux.lab.uiowa.edu	4
michaelson.lab.uiowa.edu	6
mu.lab.uiowa.edu	1
our.research.uiowa.edu	1
physics.uiowa.edu	10
sandbox.uiowa.edu	3
sander.lab.uiowa.edu	2
scope.uiowa.edu	1
shawgroup.lab.uiowa.edu	1
sitenow.uiowa.edu	2
tabel.lab.uiowa.edu	12
toxicology.grad.uiowa.edu	1
uiventures.uiowa.edu	1
veterans.uiowa.edu	2
vote.uiowa.edu	10
writinguniversity.org	2

**Comment by joewhitsitt** [comment]
This was fixed in https://github.com/uiowa/uiowa/pull/7132 (https://github.com/uiowa/uiowa/issues/5667#issuecomment-1861588815)
