### ISSUE TITLE
Accordion items use different button styles

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#215]
The AJAX spinner loads on top of them and there is no margin around it.

![image](https://user-images.githubusercontent.com/1068523/58341163-362e6780-7e13-11e9-80b0-b34219da40a0.png)

**Comment by richardbporter** [comment]
I find this widget difficult to work with in general, especially with many accordion items. Not sure if we can improve usability somehow.

**Comment by joewhitsitt** [comment]
accordions now use the same modern widget/config. see https://github.com/uiowa/uiowa/pull/206

will this be sufficient for now @richardbporter ?
