### ISSUE TITLE
Record v3 training screencast

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#2150]
## Problem

This has been a todo for a long time.

## Proposed Solution

- [ ] Once v3 reaches general availability, record a screencast of common editing situations.
- [ ] Make available on sitenow.uiowa.edu/documentation

**Comment by joewhitsitt** [comment]
Wondering if @ABoston88 is planning on doing this?

**Comment by richardbporter** [comment]
I wonder if the workshops make this unnecessary?

**Comment by joewhitsitt** [comment]
This was done: https://uicapture.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=5b75705e-9527-4ef4-be39-ade3015a3a3b&start=0

https://webcommunity.sites.uiowa.edu/training/using-layout-builder
