### ISSUE TITLE
Limit access to Top Links menu when 'inline' header option is selected

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#2151]
## Problem

A site with the gold bar site name option (Display inline with IOWA bar), doesn't display the top links.

## Proposed solution

When the 'inline' header option is selected, provide feedback to the user letting them know that the "Top Links" menu cannot be used.

**Comment by joewhitsitt** [comment]
This is working as originally designed. There are technical hurdles with this and discussion with the brand team needs to happen before any changes are made.

**Comment by joewhitsitt** [comment]
If no changes are made, the help text on the top links menu page should be updated to explain this to the webmaster.

**Comment by pyrello** [comment]
Updated OP to clarify the scope of the task.

**Comment by joewhitsitt** [comment]
Resolved by https://github.com/uiowa/uiowa/pull/2538
