### ISSUE TITLE
Can 'flex__wrapper' be removed from layout--onecol.html.twig

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2156]
For at least 6 months, there has been a typo in the `layout--onecol.html.twig` template where `flex__wrapper` was accidentally changed to `flex__wra`. This is a commonly used template and it seems to have not caused any issues that I am aware of, so to me it stands to reason that the logic in the code that adds the `flex_wra` class (and containing div) is no longer needed.

@bspeare When you have time, can you speak to whether or not this can be removed?

**Comment by bspeare** [comment]
Yes, please remove it!

**Comment by pyrello** [comment]
Does that mean it can be removed from all the layouts?

**Comment by bspeare** [comment]
It should be able to be removed from the `twocol` layout.   I can test it to be sure next week.
