### ISSUE TITLE
Publishing options title is misleading

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#216]
Makes it sound like more of a workflow/status fieldset but it has visual/design fields.

![image](https://user-images.githubusercontent.com/1068523/58341440-d2586e80-7e13-11e9-844d-bfb7c57e293f.png)

**Comment by joewhitsitt** [comment]
I don't care, but Publishing Options is what users found these "custom publishing options" under in Drupal 7.

Also, they are currently just visual/design fields, but could be much more later and is generic enough that it could keep a site from going custom with a basic page fork.

**Comment by joewhitsitt** [comment]
what is the action then for this issue? do you have a suggestion on what it should be?

**Comment by richardbporter** [comment]
I would suggest calling it Page Options.

**Comment by ethanstjohn** [comment]
What about "Layout Options"? The two options currently in there are hide title and remove side bar regions.

**Comment by joewhitsitt** [comment]
I am okay with Page Options since it is a faux field group. Leaves it open for non-style/layout options later. Docs will also have to be updated to reflect this change.

**Comment by richardbporter** [comment]
We typically leave issues open until the PR is merged. GitHub can close issues automatically with certain keywords: https://help.github.com/en/articles/closing-issues-using-keywords

**Comment by richardbporter** [comment]
I added the keyword to this PR description.

**Comment by ethanstjohn** [comment]
My apologies, thanks for explaining.
