### ISSUE TITLE
Events Block Documentation

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#2162]
## Problem

The events block is unaccounted for in the sitenow documentation.

## Proposed Solution

Draw from style/structure of https://sitenow.uiowa.edu/node/371 and UI Events/Field info of https://sitenow.uiowa.edu/node/171 to create events documentation to place under the [Layout Builder section](https://sitenow.uiowa.edu/node/266)

Point to the single event block type https://sitenow.uiowa.edu/node/311 and vice versa depending on use-case.

**Comment by ethanstjohn** [comment]
Documentation has been written here https://sitenow.uiowa.edu/documentation/layout-builder-sitenow-v3-only/events-block. It is in review state at the moment, I believe it is ready for others to review.

**Comment by joewhitsitt** [comment]
Made some edits. Published
