### ISSUE TITLE
Featured image in IE11 is not using the correct CSS in uids_base

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#2167]
# Problem 

IE issue with https://iowaresearch.lab.uiowa.edu/. Email in its-web.

- Looks like this style isn't being applied for IE:

***
.paragraph--type--section > picture > img {
    height: 100%;
    width: 100%;
    object-fit: cover;
    object-position: center;
}
***

# Proposed Solution

Investigate why IE is not using the Child combinator CSS: https://developer.mozilla.org/en-US/docs/Web/CSS/Child_combinator.

**Comment by pyrello** [comment]
Was this fixed by #2197 ?

**Comment by GaryRidgway** [comment]
yes, my apologies for not closing
