### ISSUE TITLE
Support Twitter Card Metatag

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#2169]
## Problem

Despite all of the metatags we output, we are missing out on twitter card...

## Proposed Solution

Enable sub module, configure defaults for page/person/article

## Test

https://cards-dev.twitter.com/validator

There was a browser extension that validated the current page (locally) that was nice, but I forget what it was called. Also tested Facebook open graph as well.

**Comment by joewhitsitt** [comment]
Blocked until we hear back from Law to see if they have resolved their twitter card issue using options already available.

@mjoneill ^^

**Comment by mjoneill** [comment]
Yep, I've investigated and reached out, but they have been radio silent. I would consider this a feature add and unblocked, as twitter card markup is really the only reliable way to do what they want.  

@briand44 @joewhitsitt can we scope adding this module (is it a module)? I've seen twitter card functionality available before.

**Comment by joewhitsitt** [comment]
If the current options work (which I thought they did via open graph), then I worry about adding more SEO fields for people to configure to get the same result. Can you check to see if uiowa.edu, coronavirus or brand are successful with twitter cards before we take this on?

Yes, this would be turning on a module and configuring it (permissions, content types) and then confirming that is solves the issue (if any).

**Comment by mjoneill** [comment]
> Absolutely! All the time. It’s a problem.
>  
> From: O'Neill, Michael J <michael-oneill@uiowa.edu>
> Date: Thursday, February 25, 2021 at 9:00 AM
> To: Benning, Michael J <michael-benning@uiowa.edu>
> Subject: Issues with sharing articles on Twitter?
> 
> Hi Michael,
>  
> Do you run into issues with the featured image shared in Twitter links for page or news content in our ecosystem?
>  
> Seems like articles in the Law news well don’t pull the image. I’m curious if you run into the same thing elsewhere…
>  
> Article example: https://law.uiowa.edu/news/2021/02/iowa-laws-federal-criminal-defense-clinic-fights-compassionate-release

**Comment by mjoneill** [comment]
BTW: Laura K of Law is making this visible to us. We'll want to close the loop with her when finishing this, etc.  She'd be a great partner if we need to test and/or get feedback, etc...

**Comment by mjoneill** [comment]
Unblocking as we've heard back from law and validated that it's not working with existing features.

**Comment by joewhitsitt** [comment]
yeah, this isn't so simple...
