### ISSUE TITLE
No padding in admin theme text areas

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#217]
We should add some to increase readability.
![image](https://user-images.githubusercontent.com/1068523/58341686-67f3fe00-7e14-11e9-88c1-f11776d5f8a2.png)

**Comment by joewhitsitt** [comment]
Here is an example of some padding (note yellow dotted line):
<img width="421" alt="Screen Shot 2019-05-28 at 3 20 36 PM" src="https://user-images.githubusercontent.com/4663676/58509479-40769b80-815c-11e9-90e2-1bc9f8cdc59e.png">

**Comment by richardbporter** [comment]
This can probably utilize the stylesheet created in #227.
