### ISSUE TITLE
Pull large version of event image from content.uiowa.edu

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#2170]
## Problem

We are currently pulling the medium image size offered by the API which is 220px on the longest side. We are then scaling and cropping to a square 1:1 with the 385px image style. This is causing "pixelization" all of the time even if the source is a 1:1 aspect ratio.

## Proposed Solution

Regardless of what we plan to do with the event style in https://github.com/uiowa/uids/issues/309, we should be pulling a larger version so that event images aren't scaled up. This way, if an event admin uploads a large 1:1 image, it will display correctly on our v2/v3 events listings pages.

Might need to purge image caches as part of this.

**Comment by mark-bennett-uiowa** [comment]
@joewhitsitt Definitely support this solution to the image issue. To take a step further, do we need to include such a large image (385px) in the event list even after this update? Could we cut this down to something like 250 or 275px?
### **Current:**
<img width="1380" alt="Screen Shot 2020-09-14 at 5 58 59 PM" src="https://user-images.githubusercontent.com/3067017/93146306-082e0000-f6b4-11ea-8afc-101912129cab.png">

### **Suggested:**
<img width="1395" alt="Screen Shot 2020-09-14 at 5 52 52 PM" src="https://user-images.githubusercontent.com/3067017/93146247-e6347d80-f6b3-11ea-81a4-752b6969c7b9.png">

**Comment by richardbporter** [comment]
I don't see an image style for 250 or 275px. We should probably match what articles/people are using. What are they using?

**Comment by richardbporter** [comment]
Never mind, got it!
