### ISSUE TITLE
Pharmacy people functionality

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#2171]
> At this time, I do not anticipate needing any type of automatic updating of people on pages, like the ones on our department/division listings. I think that can maintaining these pages manually, similar to how they are maintained on committees or administrative units.
 
>We will still need a Person Directory, similar to https://pharmacy.uiowa.edu/directory.  In addition, it would be ideal if the individual URLs for Profile pages remained the same format.

**Comment by joewhitsitt** [comment]
@briand44 is this different than what we just delivered?

**Comment by briand44** [comment]
No, this can be closed. Thanks for digging it up.
