### ISSUE TITLE
node--unpublished pink is covering up section background images in uids_base/v2

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#2173]
## Problem
The pink bg color is covering the background images.

## Proposed Solution

Consider the same "fix" that was done in uiowa_bootstrap: docroot/themes/custom/uiowa_bootstrap/scss/partials/02_elements/_node.scss 
```
.node--unpublished {
  background-color: inherit;
}
```
since we are already displaying a moderation message that the content is not published.

**Comment by richardbporter** [comment]
Once published, the image is visible.

**Comment by joewhitsitt** [comment]
Team decided that priority should instead go to getting sites to v3.
