### ISSUE TITLE
Banner (refactored) Documentation

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#2175]
## Problem

We need banner documentation. Blocked

## Proposed Solution

Revisit https://sitenow.uiowa.edu/node/356/edit once https://github.com/uiowa/uiowa/pull/2075 has been merged in and finalized

**Comment by ethanstjohn** [comment]
Update: The documentation here is ready to be reviewed and is in a reviewed state.
https://sitenow.uiowa.edu/documentation/layout-builder-sitenow-v3-only/banner-block

**Comment by joewhitsitt** [comment]
Thanks. Published
