### ISSUE TITLE
Uninstall seven theme

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#218]
We're not using it.

**Comment by ethanstjohn** [comment]
Would I just go into acquia/uiowa701/docroot/themes/ and delete seven? It has to be more complicated than that.

**Comment by richardbporter** [comment]
No - you would need to uninstall it through the UI locally and then export that configuration.

**Comment by richardbporter** [comment]
Here is BLT's documentation on config management: https://docs.acquia.com/blt/developer/configuration-management/

TLDR;
Uninstall, `drush config:export`, commit.

**Comment by ethanstjohn** [comment]
Thank you. I am confused on how to do this locally. I looked into how to do this. Once I find it locally and cd into that folder would I do, "composer remove "themes/seven"?

**Comment by richardbporter** [comment]
Its a core theme so it cannot be removed with Composer. You just need to uninstall via the UI and then export that configuration change. See: https://drupalize.me/tutorial/install-and-uninstall-themes under the 'Uninstall a theme' section.

You'll need to be logged in. Check out the README for instructions on running a site locally: https://github.com/uiowa/uiowa#setup-local-environment

**Comment by ethanstjohn** [comment]
Thanks for the help. I'm on the GIS site locally and I was under admin/appearance and the Seven theme does not have an uninstall option. I made sure I was an administrator.

**Comment by richardbporter** [comment]
My mistake, adminimal depends on it.
