### ISSUE TITLE
Drupal 7 Core Update

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#2185]
- [x] icgov
- [x] signage
- [x] healthcaresignage
- [x] uiowa701
- [x] uiowa702
- [x] uiowa703
- [x] dentistry
- [ ] ~~nursing~~
- [x] gradcollege
- [x] clas

**Comment by mark-bennett-uiowa** [comment]
uiclas was updated to drupal core 7.73 on Wednesday afternoon. Crossing that off the list above.
