### ISSUE TITLE
Provision CLAS sites

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#2198]
Provision the following CLAS sites:
hr.clas.uiowa.edu
finance.clas.uiowa.edu
cinematicarts.uiowa.edu
classics.uiowa.edu

**Comment by joewhitsitt** [comment]
https://github.com/uiowa/uiowa/pull/2199

**Comment by mark-bennett-uiowa** [comment]
Closed. Sites have been provisioned.
