### ISSUE TITLE
Featured Content Paragraph Bundle

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#220]
Related to #219 and the need/want to pull in entity content from elsewhere in the site (people, etc.)

I suggest a multi reference field that uses an entity browser to select one or more items based on content filtering. Filtering based on tag or other taxonomy (unit, person type?) could make things difficult or force multiple entity browser tabs.

entity browser does not have a select all based on filter option though it is on entity browser enhanced's roadmap: https://www.drupal.org/project/entity_browser_enhanced/issues/2972699

Display should have options like articles, events with an additional listgroup option.

**Comment by joewhitsitt** [comment]
This is being worked on again here https://github.com/uiowa/uiowa/pull/337

**Comment by dnkemper** [comment]
- [ ] - Make entity references backend display more table like (entity browser) (done)
- [ ] - Select all results
- [x] - Remove tags from entity browser view
- [x] - Remove ‘read more’ link from person teaser
- [x] - field_teaser (short bio) needs to be displayed in the person teaser if not empty

**Comment by dnkemper** [comment]
**Testing Instructions**

1. Go to content -> add content -> person
2. Add Info (first & last name, credentials, title, email, phone, bio, *on right sidebar* add short bio and person photo **make sure to add a short and long bio*
3. Save as ‘Published’
4. Please add a second person too
5. Go to content -> add content -> and edit an existing page
6. On the right hand menu, ‘Tags’ should not exist
7. Add a featured content paragraph to the existing section 
8. Click on ‘Select Content’
9. In the popup window, check the two people you created*
10. Should be grouped by CT (not required just thought it helped visually)
11. The two people should be displayed vertically, **NOT** horizontally
**FACT**: entity reference backend display is not feasible at the moment (See #[414](https://github.com/uiowa/uiowa/issues/414))
12. When you save the page, you should see the person’s short bio
13. There should NOT be a ‘Read More’ option on the ‘Person’ teaser
14. When you click on the person, you should see the full view/bio

**Comment by joewhitsitt** [comment]
This was merged in.
