### ISSUE TITLE
Person Content Type Additions/Updates

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#2205]
- [x] Make title/position field allow multiples (Professor of ..., chair of ...)
- [x] Add a multi valued link field with required title for person to list websites (link to cv, google scholar, pubmed, etc)
- [x] Add multi valued field for Education
- [x] Add multi valued field for Research Interests
- [ ] Styling updates

Here is a link to a profile page of a person to give an idea of what type of content will lieve in the Education and Research Interest fields.

**Comment by joewhitsitt** [comment]
>Here is a link to a profile page...

Can we get that link @briand44 ?

**Comment by briand44** [comment]
Sorry, here is a link to the profile that was used as an example https://stat.uiowa.edu/people/joseph-lang. I think there is still a brand component of this that needs to happen in regards to layout and design but this should give an idea of the data for those new fields.

**Comment by mark-bennett-uiowa** [comment]
Here is a link to the uiowa_person D8 module I wrote over a year ago: [https://github.com/uiowa/uiowa_person](https://github.com/uiowa/uiowa_person). It includes some fields. Also, should we consider:

- Additional address and contact info (some have more than two or three addresses on campus; lab, office, admin office)
- Appointments (read from feed)
- Education background (read from feed)
- Areas of Research Interest (read from feed)
- Awards and Honors
- Publications/Presentations/Performances/Creative Work
- etc

In regards to the Statistics link @briand44 linked above, here is some more information. Here is a screenshot of the fields in the content type for that APR D7 solution used by Statistics above:
<img width="1255" alt="Screen Shot 2020-09-29 at 12 11 32 PM" src="https://user-images.githubusercontent.com/3067017/94591027-1f8cf180-024d-11eb-9a9a-6c8fe5a610cc.png">
<img width="1262" alt="Screen Shot 2020-09-29 at 12 14 18 PM" src="https://user-images.githubusercontent.com/3067017/94591219-64b12380-024d-11eb-8632-24b9a58ace64.png">
The Publications/Presentations/Performances/Creative Work are all read from feed and not stored.

**Comment by briand44** [comment]
Thanks @mark-bennett-uiowa. We are trying to figure out the additional address and contact information and I do think that will be added soon in another issue. Appts, Education and Research Interests should all be handled with this issue. From my understanding the other items you mentioned (awards, performances/publications) are being considered but haven't been approved by ADF's and Provost Office yet.

**Comment by mark-bennett-uiowa** [comment]
Sounds awesome @briand44, thanks for the update! I did get a chance to talk to @mjoneill about this too, and would love to stay in the loop and help contribute in anyway possible.
