### ISSUE TITLE
Content migration conversation. How do we migrate existing areas of study content?

### ISSUE THREAD

**Issue by mjoneill** [uiowa/uiowa#2210]
* What are the content types we want to migrate, and what are our migration options?
* https://admissions.uiowa.edu/academics/undergraduate-areas-of-study

**Comment by mjoneill** [comment]
@cory-skeers @briand44 (and others): Do you think there's an automated path forward (that is worth investing in), or do we need a gaggle of student workers?

**Comment by cory-skeers** [comment]
It looks like this is very structured content, which would lend itself great to an automated path. We also have a lot of the initial structure built out in our sitenow_migrate module, which helps (it's outdated, but there are some gotchas like connecting between Dev Desktop and DrupalVM that have been solved already with it).

The interlinking pages concern me a little bit. I'd done some work on this issue in migration too, so it's not starting from scratch, but it's dependent on migrating all content in a site, and wouldn't work as is for only migrating areas of study--links going to other content like colleges wouldn't get updated with out-of-the-box functionality. Any other content that gets linked to would either need to be migrated in the same automated move, or prior (and an id->id mapping of how the page node ids are updated).

The good thing about putting in work here, at least, is that some of it would also translate to updating the sitenow_migrate option for general automated migration paths for D7 -> D8.

**Comment by briand44** [comment]
Closing this in favor of #2501
