### ISSUE TITLE
[Admissions Redesign - Core] International Landing Page

### ISSUE THREAD

**Issue by mjoneill** [uiowa/uiowa#2211]
* Front door to international content

**Comment by mjoneill** [comment]
Better page for international to use. 

This might no longer be needed as a separate feature/story.  Layout builder might solve for this.

**Comment by mjoneill** [comment]
https://international.admissions.uiowa.edu

**Comment by briand44** [comment]
Closing this issue since it seems there isn't any development needed for this.
