### ISSUE TITLE
[Admissions Redesign - Core] Why Iowa - Visually similar to new viewbook site?  - storytelling

### ISSUE THREAD

**Issue by mjoneill** [uiowa/uiowa#2213]
Why Iowa - Visually similar to new viewbook site?  - storytelling

**Comment by mjoneill** [comment]
Senior communications plan leans heavily on the theme of "Why Iowa".  List of things that make UI unique, combined together no other schools can offer these, etc...  

A piece of Why Iowa is baked into the site...  not sure if there's a second brochure site necessary, etc...  

Not sure if this is a technical ask, or something we can solve as content / site building exercise using existing tools.

**Comment by briand44** [comment]
Closing as Scott said this is no longer needed.
