### ISSUE TITLE
Admissions 2plus2 plan

### ISSUE THREAD

**Issue by mjoneill** [uiowa/uiowa#2217]
# Story

As an admissions site owner, I would like to display information about the 2plus2 plan on the existing Admissions website, so that students interested in this plan can get the information they need in one place without having to visit an outdated website.

# Additional Information

Admissions would like users to be able to browse from a list of all participating community colleges and then drill down into each available area of study to find relevant 2plus2 information specific to that community college and major.

https://2plus2.admissions.uiowa.edu/majors/colleges-new.htm

Admissions would also like users to be able to browse by area of study and see participating community colleges for that area of study and then drill down to find relevant 2plus2 informations specific to that major and community college.

https://2plus2.admissions.uiowa.edu/majors/index.html

# Proposed Solution
- [x] #4976
- [x] #5003
- [x] #5132
- [x] #5157
- [x] #5228
- [x] #5253
- [x] #5291
- [x] touch base with Jess to make sure print and web 2plus2 design aligns.

**Comment by joewhitsitt** [comment]
Scott said that one-to-one redirects (/something.html to /something) will not be part of this work.

**Comment by briand44** [comment]
There aren't a lot of details in this IS so it would be nice if we could add questions we have in comments here for us to discuss during a future Admissions weekly meeting.

**Comment by bspeare** [comment]
Could we use the area of study content type to display the majors (https://admissions.uiowa.edu/node/add/area_of_study) and the colleges taxonomy (https://admissions.uiowa.edu/admin/structure/taxonomy/manage/colleges/overview) to display community colleges?  If they used the area of study content type, perhaps we could include a "Hide on Lists" checkbox so that the 2plus2 areas of study would not display on https://admissions.uiowa.edu/areas-of-study.

**Comment by joewhitsitt** [comment]
Dumping my notes from the meeting:

- There will be a 2plus2 landing page on the Admissions website that lists 2plus2 majors and community colleges.
- Each AoS will have a link off from the Transfer Tips section that links to the corresponding 2plus2 major if said content exists.
- Each 2plus2 major landing has a links to community colleges, each with specific set of information related that major.
- Each community college has a list of related 2plus2 majors
- The 2plus2 community college major page consists of some lightly structured information (intro, student responsibilities, community college checkpoint (includes the college's name), and the university of iowa checkpoint)

**Comment by briand44** [comment]
Scope first slice to creating the Community Colleges taxonomy and view block.

**Comment by briand44** [comment]
Scope next slice to creating the 2+2 majors listing and creating a landing page in dev to demonstrate how all this fits together.

**Comment by bspeare** [comment]
I think we can move this to done after https://github.com/uiowa/uiowa/pull/5306.
