### ISSUE TITLE
[Admissions Redesign - Core] - Type-ahead search/autocomplete for Areas of Study

### ISSUE THREAD

**Issue by mjoneill** [uiowa/uiowa#2219]
Areas of Study type-ahead search (search box specific to majors, with access to show by college/group/type, etc)

MyMajors?

* https://admissions.wvu.edu
* https://und.edu/programs/index.html?search=&locations=on-campus,offcampus,online 
* https://admissions.wvu.edu/

**Comment by bspeare** [comment]
**Additional notes:**

- Core functionality for exposed filters like on https://admissions.uiowa.edu/academics/undergraduate-areas-of-study. 
- Autocomplete search block for majors
- Faceted search using Acquia Solr?

**Additional fields for Undergraduate Areas of Study content type:**
- Sort by Academic Groups? 
- Sort by Careers and Outcomes?

**Comment by mark-bennett-uiowa** [comment]
@bspeare search_api_autocomplete module is being used on policy.clas.uiowa.edu frontpage for this autocomplete feature. May want to see if this module will fill the needs here.

**Comment by bspeare** [comment]
- Walk through the areas of study content type and get a list of all the places that it is feeding. 
- Can this content type be shared across Colleges?

**Comment by briand44** [comment]
Closing in favor of https://github.com/uiowa/uiowa/issues/2715
