### ISSUE TITLE
[Admissions Redesign - Core] - Blog and Video Feed from existing WordPress Site

### ISSUE THREAD

**Issue by mjoneill** [uiowa/uiowa#2220]
Blogger/Video new posts (pulls from feeds, shows student images and media)

**Comment by mjoneill** [comment]
* http://blog.admissions.uiowa.edu/natalie/2020/09/masks-necessary-and-fun/ this is the source of the content
* Client does NOT need the content to live on admissions.uiowa.edu. It is fine for it to live on the blog site for now.  So first pass is that the content index view (three pieces of content that live elsewhere) are shown on this site.

**Comment by bspeare** [comment]
**Additional notes:**

- Blog feed listed here is a view of "Blog teasers" created from Feeds Importer: https://admissions.uiowa.edu/#block-views-student-blogs-blogs
- Additional feeds listed are listed at https://admissions.uiowa.edu/admin/config/services/aggregator
- XML feed example: http://blog.admissions.uiowa.edu/adam/feed/
- D7 site uses core Aggregator module and D8 still has this module. 
- Investigate whether these feeds can be placed via Layout Builder.  I just tried adding an Aggregator block and had Ajax errors. 
- Is it worth adjusting these feeds to JSON or will XML work if we want to use decoupled Vue.js blocks to display this content?

**Comment by bspeare** [comment]
List of current feeds:

- http://blog.admissions.uiowa.edu/andre/feed/
- http://blog.admissions.uiowa.edu/cori/feed/
- http://blog.admissions.uiowa.edu/ethan/feed/
- http://blog.admissions.uiowa.edu/faith/feed/
- http://blog.admissions.uiowa.edu/grace/feed/
- http://blog.admissions.uiowa.edu/kelsey/feed/
- http://blog.admissions.uiowa.edu/natalie/feed/
- http://blog.admissions.uiowa.edu/riya/feed/
- http://blog.admissions.uiowa.edu/counselors/feed/

**Comment by briand44** [comment]
Fields that need displayed:

- Author Image - This currently is not in the feed. It is a content type on the admissions site. If we don't import these as entities we would need some way of grabbing an image from a specified file path.
- Title of blog
- Teaser - This is being truncated to a 100 characters.
- Author - only using first name, could be an issue in future.

**Comment by bspeare** [comment]
Research spike:

- Investigate feed options
- Investigate ability to attach author via javascript
- Investigate front end / back end integration with Drupal
- Set config split for admissions.uiowa.edu

**Comment by richardbporter** [comment]
> Investigate whether these feeds can be placed via Layout Builder. I just tried adding an Aggregator block and had Ajax errors.

I was able to place a feed without issue. I wonder if we could expose aggregator settings and blocks for webmasters. The block lets you select a feed that you added to be displayed on a page.
<img width="1051" alt="Screen Shot 2020-10-01 at 4 58 29 PM" src="https://user-images.githubusercontent.com/1068523/94867706-5a3a8980-0407-11eb-903c-beb872a5e1d7.png">
