### ISSUE TITLE
Disable access to global theme settings

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2222]
In looking into #1935, it seems that the theme_permission module alone will not be enough to lock down theme settings enough. We will also need some custom code to accomplish the following:

1. Disable access to the Global settings tab:
  ![Screen Shot 2020-09-23 at 10 23 17 AM](https://user-images.githubusercontent.com/709009/94034143-4a77d100-fd87-11ea-827d-e453c8d97e84.png)
2. And we need to disable access to global settings on the UIDS base tab:
  ![Screen Shot 2020-09-23 at 10 24 15 AM](https://user-images.githubusercontent.com/709009/94034193-5b284700-fd87-11ea-99bd-b50d11f53261.png)

**Comment by joewhitsitt** [comment]
Easy peasy: https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/uiowa_core/src/Routing/UiowaCoreRouteSubscriber.php#L25
