### ISSUE TITLE
Update layout builder docs to reflect new style names

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#2226]
## Problem

Label name changes/options done in https://github.com/uiowa/uiowa/pull/2076 need to be accounted for on https://sitenow.uiowa.edu/documentation/layout-builder

**Comment by ethanstjohn** [comment]
Additions:
Narrow to Margin docs

Updates:
Bottom, Edge-to-Edge, Wide, Normal, Full width (has side margins), Remove default vertical spacing, and Top to Margin docs
Add extra bottom spacing, Bottom, Remove bottom spacing, Remove top spacing, Remove default column spacing, Restore default spacing, Add extra top spacing to Padding docs
