### ISSUE TITLE
Fix padding around images for card lists in uids_base

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#2227]
# Problem 

#2076 may have created some padding regressions with card lists where media images are right up against the border on v3. 

<img width="1429" alt="94057836-cbde5c00-fda5-11ea-8c5b-2a30053bb228" src="https://user-images.githubusercontent.com/1036433/94059530-2c6e9880-fda8-11ea-8395-262d38baf1e3.png">

# Proposed Solution

Adjust card list padding to create space for media images.

**Comment by richardbporter** [comment]
Would adding right margin to `card-media-horizontal-right` in UIDS work? Or should each block implementing card lists (events, articles, people) adjust `card__media`?

**Comment by richardbporter** [comment]
Gave it a shot in #2279. Feel free to comment there.
