### ISSUE TITLE
Featured image altered in LB IPE before save after layout edit, works as intended after save

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#2228]
After the latest 3.0.6 release, I started noticing this:
**Immediately after entering Edit Layout LB IPE:**
<img width="1596" alt="Screen Shot 2020-09-23 at 3 52 11 PM" src="https://user-images.githubusercontent.com/3067017/94068553-f552b400-fdb4-11ea-991a-5a83a3dd3baf.png">

**After editing anything on the page in layout builder, prior to save:**
<img width="1599" alt="Screen Shot 2020-09-23 at 3 52 35 PM" src="https://user-images.githubusercontent.com/3067017/94068563-f8e63b00-fdb4-11ea-94c9-7866b8126915.png">

**After save, page still appears normal:**
<img width="1595" alt="Screen Shot 2020-09-23 at 3 51 33 PM" src="https://user-images.githubusercontent.com/3067017/94068542-f1269680-fdb4-11ea-8fca-eba1b37bf913.png">

**Comment by joewhitsitt** [comment]
I am seeing something similar and just noticed recently:

> so when i add a new section and change the background color, the header background changes…

> looks like it doesn’t save that way or reloads layout builder that way, but it happens while making section edits

> i added a featured image and it stayed full width but the page title and such lost the white text

**Comment by joewhitsitt** [comment]
also, don’t know if is related but changing the first block on https://sandbox.prod.drupal.uiowa.edu/events-listing causes a messed up render of it in the header.

https://github.com/uiowa/uiowa/pull/2730#issuecomment-754277362

**Comment by pyrello** [comment]
I did not specifically test https://github.com/uiowa/uiowa/issues/2228#issuecomment-754780865 in #2794. If it is still present after that PR is merged, then I think another issue should be opened.
