### ISSUE TITLE
Documentation 1.0.7

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#223]
- [x] Remove docs/tour content related to "related content"
- [x] Update related publishing options docs to whatever it becomes #216 

More to come...

**Comment by ethanstjohn** [comment]
What is docs/tour content?

**Comment by ethanstjohn** [comment]
I found a few pages where the documentation refers to related content, I'm not sure what to delete.

**Comment by richardbporter** [comment]
Is this done? I'd like to close out the milestone.

**Comment by joewhitsitt** [comment]
Yeah.
