### ISSUE TITLE
Remove v2 flag from sitenow provision blt command

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#2237]
## Problem

v3 is default, you should have to add v2 flag for a v2 site.

## Proposed solution

update command for new submissions. this is an admin "field" on the form tracked through the sitenow site config split. make the change locally, export the config change.

**Comment by joewhitsitt** [comment]
I think @ethanstjohn was going to work on this, but hasn't assigned it

**Comment by ethanstjohn** [comment]
Yeah, I forgot to assign it to me. I got busy with another task on my Mac.

**Comment by ethanstjohn** [comment]
This is done on prod now.

**Comment by joewhitsitt** [comment]
Turns out this is no longer tracked in config. Updates to the form happen directly in PROD now.
