### ISSUE TITLE
Establish criteria for addressing IE issues

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#2238]
- internal doc listing out common IE issues we encounter and whether or not we should spend time fixing them. If we are fixing them, how "good" do we need to make it?

**Comment by bspeare** [comment]
Also, how should it be tested?
- BrowserStack
- `dev` branch
- Local machine

**Comment by joewhitsitt** [comment]
Took a first stab at this. Trying to get local env testing to work.

https://wiki.uiowa.edu/x/_ah6E
