### ISSUE TITLE
Move current version of demo site to v2demo.sitenow.uiowa.edu

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2241]
As we make the transition to rolling out SiteNow V3, we will likewise want to transition to using a V3 site as our default site. I think it would be a good idea to keep the v2 sitenow demo site around until we are able to migrate all the V2 sites to V3, as it is good for testing and being able to update config in the sitenow_v2 split.

**Comment by richardbporter** [comment]
We talked about this today and were wondering if it was still needed. Another potential option is to pick an existing v2 site without a site split and treat that as the "default" v2 site. For example, https://hawkeyemarchingband.uiowa.edu/ has been used extensively to test v2 changes and content. We could all agree to use that and then close this.

If that won't work or isn't a good idea, we may need this still if we have to export/compare/test v2 config in the future.

**Comment by pyrello** [comment]
I'm not sure this is actually needed anymore. A real life site is probably fine.
