### ISSUE TITLE
Improve field labels for LB blocks

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2246]
# Problem
Field help text is not always as helpful as it could be.

**Comment by pyrello** [comment]
@ABoston88 This would be a good place to document feedback about how we could improve the block forms for Layout Builder blocks.

**Comment by ABoston88** [comment]
https://iowa-my.sharepoint.com/:w:/g/personal/bosto_uiowa_edu/EdT6rVJcC1RMvehPTciCd1cBuhQMZcxFWszt-2IPfkCqnA?e=f3HXA7

Here's some "What is this" text for each form field and that could help with this as a supplement to Danielle's tour content and the documentation. Added some for the component types, as well. Feel free to edit if anything is incorrect. 

I'm currently going through and highlighting fields that have caused some confusion (and suggesting possible alternatives), as well.

**Comment by ethanstjohn** [comment]
![Screen Shot 2020-11-10 at 1 03 14 PM](https://user-images.githubusercontent.com/42824212/98719267-27b07480-2355-11eb-9d8c-16770ca3bdf1.png)
I was wondering, on this document of suggested help text given above, there are many more help text options than listed in the settings on the right for all of the given blocks. Should I just write documentation for the ones already created on the right? If not, how do I create new fields on the right?

**Comment by joewhitsitt** [comment]
If I understand correctly, title and size pertain to the field_uiowa_cta_title field, URL and link text pertain to field_uiowa_cta_link. Not sure if help text can be added to the layout builder style options without custom code.

I would combine for now where you can and make notes about what you are able to do through the UI.

**Comment by ethanstjohn** [comment]
Thank you.

**Comment by ethanstjohn** [comment]
So a possible further look is required to add in help text for every field on every LB block. I'll post the notes on which fields were not in the UI after I finish up adding the help text for what is there.

**Comment by ethanstjohn** [comment]
![Screen Shot 2020-11-11 at 10 37 48 AM](https://user-images.githubusercontent.com/42824212/98838541-08275380-240a-11eb-8a5a-1bb8eb632ac8.png)
