### ISSUE TITLE
V3 version of V2's featured content

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#2259]
## Problem

Several v2 websites are using Featured Content to reference existing content in a manually curated way and currently extends beyond article and person to include basic page as well. This type of functionality doesn't exist in v3.

This is commonly used to highlight a featured article, a manual sort of people, basic page content quick/related links.

Something to port over to will be necessary for v2 migration. https://github.com/uiowa/uiowa/issues/1779, https://github.com/uiowa/uiowa/issues/1803

## Proposed Solution

Recreate the featured content block in layout builder working around the current issue with the v2 version: https://github.com/uiowa/uiowa/issues/414

- [x] block type
- [x] headline/children
- [x] Permissions splits
- [x] entity view display splits, admissions entity print issue
- [x] styles

**Comment by pyrello** [comment]
Are we okay with not considering this a blocker to V3 GA?

**Comment by joewhitsitt** [comment]
Not a blocker.

**Comment by pyrello** [comment]
As a first slice through this, we are going to create:
* A new custom block type
* with a multi-value entity reference field that can reference articles and people
* that relies on existing teaser displays for styling children
* with a Headline field
* that affects the h size of the children in the collection
* with permissions for Editors and Webmasters
* and allowed to be placed in Layout Builder

**Comment by joewhitsitt** [comment]
Thought about providing a more link similar to the other "collection" blocks, but not necessarily as part of the current MMF

**Comment by richardbporter** [comment]
Headline/children field is set up but we don't know of a way to get at the relationship between the block and node.

**Comment by joewhitsitt** [comment]
Before this issue is closed, a follow-up task for page support should be created

**Comment by pyrello** [comment]
I'm not sure we should close this issue without articulating all the things that we didn't do for the first pass at this feature.

**Comment by richardbporter** [comment]
In honor of a11y day, I gave the headline issue a shot in #3552.

**Comment by pyrello** [comment]
Follow up issue: #3567
