### ISSUE TITLE
Not enough contrast in adminimal toolbar

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#226]
![image](https://user-images.githubusercontent.com/1068523/58572830-0eb81000-8202-11e9-8899-9c986ee4825a.png)

We should override the text color to be white to increase the contrast ratio. We'll need to double check how it looks in each environment by overriding the `$env` variable in `global.settings.php` temporarily.

See: https://github.com/uiowa/uiowa/blob/master/docroot/sites/settings/global.settings.php#L35

**Comment by briand44** [comment]
we will probably want to wait until #227 gets merged in. That should make this easier to implement.

**Comment by ethanstjohn** [comment]
![Screen Shot 2019-05-31 at 9 11 41 AM](https://user-images.githubusercontent.com/42824212/58711444-2e774180-8384-11e9-927f-c8fac2743662.png)
![Screen Shot 2019-05-31 at 9 11 52 AM](https://user-images.githubusercontent.com/42824212/58711449-31723200-8384-11e9-93f1-f8ed1d2ab62d.png)

This is what it looks like with the changes
