### ISSUE TITLE
Hitting update while in source editor doesn't save changes done in HTML.

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#2274]
# Problem 

Changes to markup are lost if you hit "update" to a text area block in source view.

<img width="795" alt="Screen Shot 2020-10-01 at 9 38 49 AM" src="https://user-images.githubusercontent.com/1036433/94823930-09f10680-03ca-11eb-9500-96ba87d1b9e5.png">

# Proposed Solution

?

**Comment by joewhitsitt** [comment]
Are we sure it is just the collegiate split or does it also apply to v3 default?

**Comment by bspeare** [comment]
Upon further testing, it looks like it applies to both.

**Comment by cory-skeers** [comment]
Related issue: https://www.drupal.org/project/drupal/issues/3095304

>Steps to reproduce: Add block to section
Create custom block
Edit text in body field
Save block
Edit block
Switch body field to ckeditor source mode
Edit text
Save
Changes are NOT saved!
Once I changed back to non-source mode before saving the changes are saved properly.
