### ISSUE TITLE
Anchor links in linked cards/banners go to the card/banner link instead of anchor

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#2277]
## Problem

While testing the banner refactor https://github.com/uiowa/uiowa/pull/2075, I noticed that an anchor link in one of these linked clickable component ultimately send the user to the card/banner link, not the anchor.

## Proposed Solution

Adjust `card.js` to allow anchor links in Excerpt area.

**Comment by bspeare** [comment]
Can you post a screenshot of what this looks like?

**Comment by joewhitsitt** [comment]
<img width="463" alt="Screen Shot 2020-10-01 at 11 54 29 AM" src="https://user-images.githubusercontent.com/4663676/94839704-f9965700-03dc-11eb-84bb-82aa854cbaa2.png">
<img width="401" alt="Screen Shot 2020-10-01 at 11 54 56 AM" src="https://user-images.githubusercontent.com/4663676/94839709-fb601a80-03dc-11eb-956e-a8cda3ad74e3.png">

So in this case, clicking "anchor link" scrolls me down the page where the anchor id is, but then sends me off to yahoo.

**Comment by bspeare** [comment]
@joewhitsitt is this the js that you are referring to?

https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/sitenow_paragraphs/modules/sitenow_card/js/card-link.behavior.js

**Comment by joewhitsitt** [comment]
yes

**Comment by bspeare** [comment]
Related issue https://github.com/uiowa/uiowa/issues/2292.
