### ISSUE TITLE
Re-install international.uiowa.edu as SiteNow v3.

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#2283]
Looks like its on uiowa.prod: https://international.prod.drupal.uiowa.edu/

Just needs an sql:drop and a re-install via BLT.

**Comment by joewhitsitt** [comment]
files deleted, database dropped, v3 install, varnish cleared, added Katie, sent modified site created email via sitenow.uiowa.edu. ssl cert was already covered on uiowa.
