### ISSUE TITLE
Tippie - Troubleshoot uiowa_events implementation

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#2286]
## Problem

>  I was able to add the pane to a page, however, even though “Events” show up, nothing is displayed under it. And also there’s a message at the top of the page about an undeclared variable in the tpl.php file “Notice: Undefined variable: content in include() (line 15 of /Users/mjain/acquia/uiowa703-dev/docroot/profiles/sitenow/modules/custom/uiowa_events/uiowa_events_pane/theme/uiowa-events-pane.tpl.php).” Any thoughts? I tried changing the variable based on the other files in that module but nothing helped.

**Comment by joewhitsitt** [comment]
Check with @makurj before taking this on to make sure it is still an issue.

**Comment by briand44** [comment]
@makurj is this still an issue?

**Comment by joewhitsitt** [comment]
>I think that can be closed for now.

@makurj
