### ISSUE TITLE
IRRC - New People Grouping View Display

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#2287]
## Problem

https://iowareadingresearch.org/people - request for new grouping display

>We need to add a new heading on our staff page (https://iowareadingresearch.org/people). I already went ahead and made the term under Affiliations, “Temporary Staff Member.” We just need it to appear on the staff page as “Temporary Staff,” between “Part-Time Staff” and “Graduate Student Staff.”

**Comment by joewhitsitt** [comment]
Thanks for picking this up @dnkemper. I will forward the original email to you.

**Comment by dnkemper** [comment]
@joewhitsitt thank you so much!
