### ISSUE TITLE
Convert person content type to use Layout Builder for content type template

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2293]
# Problem
We use Layout Builder for other content type templates, but not the person type. 

# Proposed solution
Enable Layout Builder to manage the layout for the Person content type and re-export configuration. This will need to be done for any split instances of `core.entity_view_display.node.person.default` that exists in config.

**Comment by joewhitsitt** [comment]
Admissions now has a layout based person full node which can serve as inspiration or "merge to default"

**Comment by joewhitsitt** [comment]
This is done for default now right @pyrello ?

**Comment by pyrello** [comment]
Yes.
