### ISSUE TITLE
Person contact information

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#2297]
We need to be able to store and display contact information for a person. This includes the ability to list multiple office addresses.

![Screen Shot 2020-10-05 at 4 40 46 PM](https://user-images.githubusercontent.com/1017022/95135663-633e9a00-072a-11eb-8a5e-09fd6dd339cb.png)

**Comment by briand44** [comment]
This is how the contact info is structured in APR database tables:

UPDATED_TS: TIMESTAMP(6) NOT NULL
UPDATED_BY: VARCHAR2(128) NOT NULL
PROFILE_ID: NUMBER(22) NULL
CONTACT_TYPE: VARCHAR2(1024) NULL
BUILDING: VARCHAR2(4000) NULL
ROOM: VARCHAR2(4000) NULL
PHONE_NUMBER: VARCHAR2(50) NULL
ADDRESS: VARCHAR2(1000) NULL
CITY: VARCHAR2(250) NULL
STATE: VARCHAR2(100) NULL
ZIP: VARCHAR2(25) NULL
STAFF_CONTACT: VARCHAR2(128) NULL

Here are the contact types they use:

PRIMARY_OFFICE("Primary Office", true, 10),
OFFICE("Office", true, 20),
LAB("Lab", true, 30),
CLINIC("Clinic", true, 40),
SCHEDULING("Scheduling", true, 50),
STAFF_CONTACT("Staff Contact", true, 60),
DEPARTMENT("Department", true, 70),
FAX("Fax", true, 80),
CELL("Cell", false, 90),
HOME("Home", false, 100),

**Comment by briand44** [comment]
And here is what has been reviewed and approved by ADFs:

![Screen Shot 2020-10-05 at 4 54 58 PM](https://user-images.githubusercontent.com/1017022/95228352-d4cb2680-07c4-11eb-95cf-94aeff61f737.png)

**Comment by pyrello** [comment]
The first question I see here is whether we want the label for each contact information section to be selected from a list of pre-determined options, set as a text field, or using a combination select/or text solution? My preference would be for the third option because it allows for commonly used options without the hassles of taxonomy tagging, but still allows for edge cases where people need to label a contact information section something non-standard.

**Comment by joewhitsitt** [comment]
So if I understand this correctly, the "other" option would have all of the contact fields available either as a "show all and leave them empty as optional" or the al a carte/pick and choose you described previously with paragraphs? The predetermined set would either have less fields and/or just act as a consistent label across the site.

I worry the predefined set would not get used unless it was an editor following a content migration plan written by a superior. As a webmaster, I would pick "other" 99% of the time so I can label it like I want and get the fields I want. That way I am not restricted in making my content. Still wearing my non-developer hat, I have no idea at the time of making my content how picking one option or another will affect things in the future when it comes to migration, etc.

**Comment by briand44** [comment]
My thoughts on this are if there is a way to keep this simple by just using https://www.drupal.org/project/address then I would be for that. Not sure if there is a text field component here that we could use as our Address Type?

Maybe:
Family Name = Address Type (Primary Office, Lab, etc) - Just a text field for a user to enter anything
Organization = Location Name (200A Eckstein Medical Research Building) - Just a text field for a user to enter anything

**Comment by pyrello** [comment]
@joewhitsitt I think you may be getting ahead of my question. I was only asking about the label for a contact section and was not saying anything about how that would affect the rest of how it would be built. To me, how the label gets built is a little bit of a sticking point, whereas the rest of it could easily be a common set of fields that get filled out or not depending on whether they were needed.

@briand44 It sounds like you are promoting the option of just using a text field - in this case via the address module. In that case, we are not even giving people suggestions about what the field text should be (unless we alter the help text). I guess that seems a bit too wide open to me.

Next question: In the schema output above, there are room and building fields. Is it important to capture these separately?

**Comment by joewhitsitt** [comment]
Sorry if I am jumping ahead. If the label is entirely separate and has no downstream functionality, I would lean towards the "pre-defined select or other" option. If there are downstream effects (e.g. availability/required), then yes, I would like to think ahead.

**Comment by pyrello** [comment]
I'm leaning towards a field collection (paragraph) that contains the label field and either a.) an address field, or b.) a set of comparable fields that can be used or not depending on the relevancy. These fields could be exposed through a further entity reference (e.g. Add an address, Add a phone number) or just be contained directly on the child paragraph entity. Either way, I wasn't imagining that the label would control what was shown or available.

**Comment by joewhitsitt** [comment]
Field collection works for me, but I think it should be something like Contact Information > Contact Item (contact label and contact info fields where all the fields are there but optional). I am imagining a student migrating content over and they just want to start pasting values in instead more clicks to pick fields and arrange them consistently. I don't know if I understand the separate entity approach if the content isn't used elsewhere.

I have not tried address field in D8, but for basic postal info, I think it is worth checking out. If it creates too much separation between the other fields it doesn't capture, we can pivot. On the frontend, we can always explode the address field values and arrange it anyway we want.

**Comment by mark-bennett-uiowa** [comment]
I believe I used the address module for the D8 version of people I wrote in the entity_types modules. Seemed to work pretty good, but that was months ago and Im not sure where current development or issues have gone with that. I liked the way it worked, but thought there were unnecessary fields included even in that module.
