### ISSUE TITLE
Investigate Calendar feature for events/seminars?

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#2298]
Investigate Calendar feature options for events/seminars.

**Comment by joewhitsitt** [comment]
I'd throw a vote towards https://www.drupal.org/project/fullcalendar with the clarification I haven't tested the D8/9 version

**Comment by mark-bennett-uiowa** [comment]
Nice! Ill check this out. Thanks @joewhitsitt

**Comment by pyrello** [comment]
Possibly related to #2396

**Comment by joewhitsitt** [comment]
We have fullcalendar in the codebase (grad thesis defense calendar) and should probably be used for most use-cases. Care if I close this?

**Comment by briand44** [comment]
Admissions has this, we need to understand if there is a larger need for this for folks who would be using the local event solution.

**Comment by joewhitsitt** [comment]
We have been using fullcalendar_views for a while on many sites.
