### ISSUE TITLE
Investigate Jobs listing feature pulled from jobs.uiowa.edu?

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#2299]
Investigate Jobs listing feature options pulled from jobs.uiowa.edu.

**Comment by richardbporter** [comment]
To my knowledge, there is no API for this data.

**Comment by briand44** [comment]
https://github.com/uiowa/uiowa/issues/5219#issuecomment-1121299875

**Comment by joewhitsitt** [comment]
@briand44 can this be closed based on #6631 and #7177?
