### ISSUE TITLE
Implement card option updates from UIDS

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2306]
In UIDS, events are just going to be one more thing that can be created with a card component. This means that cards will now support the variations that are currently limited to events. To support this change, we need to make the following changes
* Add LB style options for:
  - Image styles: rectangular (default) or round
  - Image size (when a card is in horizontal orientation): small, medium (default), or large
  - Image position (when a card is in horizontal orientation): left (default), or right, or above.
* Solve for programmatically setting the card image style to be square instead of widescreen when the round option is selected above.
* Show/hide the image size and position options as appropriate when the horizontal variant is selected.
* Add ability to add more background colors to card like `light` `dark` and `gray`.

**Comment by bspeare** [comment]
Display options for events like https://github.com/uiowa/uiowa/pull/2296#issuecomment-705612534 will also need to be considered in this refactor.
