### ISSUE TITLE
Create display options for lists, views and feeds in uids_base

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#2309]
# Problem

All of the v3 views and feed displays currently default to a list view within layout builder.    There is currently not a way to switch a display to a grid listing. 

# Proposed Solution

Create a "Display options" layout builder style that offers the ability to switch a view or feed to display as:

- Grid centered
- Grid left-aligned
- Grid 3-col
- Grid 2-col
- Grid 30-40-30?
- List style centered
- List style left-aligned

Initially added some thoughts on this here https://github.com/uiowa/uiowa/pull/2296#issuecomment-705612534.

**Comment by pyrello** [comment]
Bringing my comment over from the thread this started on: https://github.com/uiowa/uiowa/pull/2296#issuecomment-705640786

I would consolidate this down to the following:

**Display list as**
* List (default)
* Grid

**Content orientation**
* Left-aligned (default)
* Centered

**Grid columns** (only shown if *Grid* is selected above)
* 3 columns 33-34-33 (default?)
* 3 columns 30-40-30?
* 2 columns

**Comment by joewhitsitt** [comment]
Could Accordion be another display option? Might relate to https://github.com/uiowa/uiowa/issues/2486

**Comment by joewhitsitt** [comment]
With the card styles I was doing in #2644, I am wondering if the content orientation is needed here? Could this just be adding the grid options? Also, do these grid styles already exist in UIDS or is that separate work that needs to be captured/figured out

**Comment by bspeare** [comment]
@joewhitsitt Yes, I think that part is no longer needed.
