### ISSUE TITLE
People Manual Sort doesn't work in v3

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#2313]
## Issue

The recent addition of responsive tables is causing a conflict with the draggableviews table that is implemented via the SiteNow People manual sort option. As a result, the drag/drop doesn't work and there are table markup being displayed that shouldn't be.

V3: Non-functioning drag handles, non-hidden table markup.
<img width="612" alt="Screen Shot 2020-10-08 at 11 11 19 AM" src="https://user-images.githubusercontent.com/4663676/95485248-14c21300-0957-11eb-9a0e-0f3a4d5d5a75.png">

## Proposed Solution

- Provide another "turn-off" option to avoid providing any table styles or functionality to this particular table
OR
- Hardcoded scope to not apply functionality on top of the SiteNow People manual sort table.

**Comment by joewhitsitt** [comment]
Removing the responsive tables library solves the v3 issue. Since header content (wysiwyg) can be place above this table view, I think we need some more disable functionality beyond the table--static class

**Comment by joewhitsitt** [comment]
Added a known issue: https://sitenow.uiowa.edu/known-issues#uiowa-issues-2313

**Comment by joewhitsitt** [comment]
This issue has also come up with the PHP Live Chat (text version) that we tried to implement for advisingcenter. The JS for that pulls into the website some table markup (layout purposes, not data). We can't control this markup to apply any opt-out classes.

I think we need to revisit the scoping of the responsive table functionality.

**Comment by richardbporter** [comment]
Is this done?
