### ISSUE TITLE
Demo site for testing all the things

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2315]
# Problem
Currently we use existing sites, including the demo site to test things. This is useful insofar as that we are able to see if existing content or functionality is broken, but doesn't help us for testing hypothetical scenarios or edge cases in a consistent way. We have repeatedly needed to create "kitchen sink" pages for testing various combinations of background treatments, block types, and other elements. 

**Updated:**
# Proposed solution
Provision a site to be used for building testing content.

**Original:**
# Proposed solution
We should be a testing sites for both V2 and V3 that encapsulate this common testing scenarios in content and that these sites will actually become a production sites and that the content will exist continuously. That way we could have as many kitchen sink pages as needed and we need. New updates could be tested against a robust set of existing tools that are consistent from update to update.

**Comment by pyrello** [comment]
`test.prod.drupal.uiowa.edu`?
`testing.prod.drupal.uiowa.edu`?
`webdevtest.prod.drupal.uiowa.edu`?

To note, since we will only be using the internal prod domain, the drush alias file will need to be updated to point at the internal prod domain instead of what would be the production domain (e.g. `test.uiowa.edu`).

**Comment by joewhitsitt** [comment]
sandbox

**Comment by richardbporter** [comment]
I would vote to avoid `test` or `testing` - `sandbox` works for me.

**Comment by mark-bennett-uiowa** [comment]
Also vote sandbox.

**Comment by dnkemper** [comment]
sandbox it is. Provisioned and merged into master!
