### ISSUE TITLE
Document that article summary is used for RSS feed description

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#2316]
https://coronavirus.uiowa.edu/news

**Comment by joewhitsitt** [comment]
This is a non-issue. Working as designed. The recent articles don't have summaries which is what is used for teasers/RSS.

<img width="492" alt="Screen Shot 2020-10-09 at 8 33 54 AM" src="https://user-images.githubusercontent.com/4663676/95589358-434cf600-0a0a-11eb-96a0-10e677936662.png">

**Comment by richardbporter** [comment]
Isn't there a way to use the summary if set, otherwise fall back to a trimmed description?

**Comment by richardbporter** [comment]
That seems like a better experience for people. I thought we did that a lot in D7.

**Comment by joewhitsitt** [comment]
We've talked about bringing back the body/summary combo which is what was used commonly in D7 but early on we started with field_teaser (Article Summary) instead of body for all of this. Separate fields and will require noodle code to achieve this.

Psst! I wanted to keep the body field originally...

**Comment by richardbporter** [comment]
For the RSS view specifically, this could be a simple field rewrite no?

**Comment by joewhitsitt** [comment]
why wouldn't we do this across the board for teasers and meta descriptions as well? i know rss is this week's hot trend, but facebook/twitter/teaser display meta is more visible/used

**Comment by richardbporter** [comment]
Because the view is using fields, not a view mode.

**Comment by richardbporter** [comment]
I agree the concept is shared and would be very useful across the board but the implementation is not (I don't think).

**Comment by joewhitsitt** [comment]
not following the fields/view mode point. meta description is a field taking in token value from another field (field_teaser).

**Comment by richardbporter** [comment]
Team consensus was "works as designed" - I wonder if we can just update the field description to inform users that this is used for RSS feed descriptions?
