### ISSUE TITLE
Person layout/design changes

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#2320]
# Story

As a brand team design member or person content type stakeholder, I have seen and given approval for all the changes being made to the default person content type layout/design changes.

# Proposed Solution

As we develop how the _default_ person profile look going forward for SiteNow v3 and accounted for all the new fields we plan to add to the content type. We should seek guidance/approval from the Brand team and other stakeholders.

Relates to: 
https://github.com/uiowa/uiowa/issues/2205
https://github.com/uiowa/uiowa/issues/2293
https://github.com/uiowa/uiowa/issues/2297
https://github.com/uiowa/uiowa/issues/2291
https://github.com/uiowa/uiowa/issues/2234
https://github.com/uiowa/uiowa/issues/2498

**Comment by joewhitsitt** [comment]
Thoughts from the design meeting. Let me know if I forgot some stuff, I am sure I did.

Good examples: [Tippie](https://tippie.uiowa.edu/people), [Harvard Library](https://library.harvard.edu/staff)

- Image placement, see Harvard, if no image, doesn't disrupt the flow of the rest of the content.
- Title below image.
- Consider if no sidebar content, the region collapses making the main full-width.
- Consider splitting sidebar into mobile top (positions/titles) and mobile bottom content (external websites), flowing above and below the main content. The idea comes from CSS Grid, but could be accomplished by a layout that has a sidebar primary and sidebar secondary together in desktop but separate in mobile.

**Comment by pyrello** [comment]
It sounds to me like we may want to create a custom layout to handle this, which would allow us to accomplish the 3rd and 4th points above.

> * Title below image.

In this case, by title, are we talking about the person's name?

**Comment by joewhitsitt** [comment]
Admissions now has a layout based person full node which can serve as inspiration or "merge to default"

**Comment by joewhitsitt** [comment]
via Slack:
>https://github.com/orgs/uiowa/projects/1#card-46994730 has a list of related issues which are all closed now and so maybe it can be closed and moved to Done?

#2293 hasn’t been done for the default yet, just Admissions. I never really filled in this issue, but I think I originally thought this would be the design review/finalization task about look and placement of all our person fields for the default display. If that has already happened, I think this can be closed.
