### ISSUE TITLE
Provision Sitenow v3 site for dentistry.

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#2322]
There is currently a SiteNow v2 site already living at https://dentistry.prod.drupal.uiowa.edu on the uiowa application. They are fine with blowing this away and making it a v3 site. I don't think there is a site request for this and we won't be able to submit one since there is already a site. We will want to give Chuck McBrearty (mcbrearty) webmaster access and notify him when the site is available.

**Comment by briand44** [comment]
*.dentistry.uiowa.edu is covered on uiowa but there is not an entry for dentistry.uiowa.edu.

**Comment by richardbporter** [comment]
I ran the install in prod but encountered errors. The default content is not exactly what it should be but its a v3 site!

**Comment by richardbporter** [comment]
Added chuck. Recreated SSL cert. Contacted chuck.
