### ISSUE TITLE
Regressions from layout builder styles vertical spacing updates

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#2324]
# Problem

The LB Styles refactor (https://github.com/uiowa/uiowa/pull/2076) has produced a few spacing regressions.

**Admissions site with hidden page title:**

<img width="1791" alt="Screen Shot 2020-10-09 at 1 04 26 PM" src="https://user-images.githubusercontent.com/1036433/95618430-a8b4dd00-0a32-11eb-85fa-91d9e00117ae.png">

**Diversity site two column sidebar layout:**

<img width="1760" alt="Screen Shot 2020-10-09 at 1 04 54 PM" src="https://user-images.githubusercontent.com/1036433/95618450-b10d1800-0a32-11eb-945c-33786c69c58d.png">

# Proposed Solution

Do another round of cleanup and testing targeting v2 and v3 sites like in the examples listed above.

**Comment by bspeare** [comment]
The issue with admissions is being caused by https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/scss/global.scss#L72.   
```
  &.layout--title--hidden + &:not([class*="bg-"]) {
    padding-top: $desktop-width-gutter;
  }
```
We added this so that we could have some default padding set for nodes that hide their page titles like:

<img width="1516" alt="Screen Shot 2020-10-12 at 3 10 59 PM" src="https://user-images.githubusercontent.com/1036433/95786459-37c52d80-0c9d-11eb-8db3-1764d884860b.png">

Maybe we should remove this line and rely on content editors to add in their own spacing?

<img width="483" alt="Screen Shot 2020-10-12 at 3 15 23 PM" src="https://user-images.githubusercontent.com/1036433/95786749-d487cb00-0c9d-11eb-8448-ef070c52f8bc.png">

**Comment by pyrello** [comment]
I think the first example, in the OP of the admissions site with the extra spacing is correct. I'm assuming that the item displaying below the header is a banner. In the case of a banner being a first item, you would not want any space before it. However, if you were starting the page with a block of text, then you would. I think the second case should be the presumed default and that people should strip the top spacing in the case of a banner or slider.
