### ISSUE TITLE
Add global rule for text area links to break

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2325]
Add a CSS rule to uids_base for links contained in text areas:
```css
word-break: break-word;
```

This might be able to be applied more broadly, but we would have to think through potential ways this could break existing links.

**Comment by bspeare** [comment]
Adding the documentation here of the bug:

# Problem
<img width="713" alt="Screen Shot 2021-08-19 at 8 28 37 AM" src="https://user-images.githubusercontent.com/1036433/130077027-64ecf453-835c-4c69-9773-624d2873d991.png">

# Proposed solution
<img width="657" alt="Screen Shot 2021-08-19 at 8 27 18 AM" src="https://user-images.githubusercontent.com/1036433/130077061-a6f86614-a1ad-4e1d-979b-6b01ee7d22a8.png">

**Comment by joewhitsitt** [comment]
Reopening due to education bug https://iowaweb.slack.com/archives/C01LA6Y2XGV/p1634148982063800

**Comment by joewhitsitt** [comment]
<img width="1096" alt="Screen Shot 2021-10-13 at 1 33 52 PM" src="https://user-images.githubusercontent.com/4663676/137192731-279557d8-6918-46af-b879-2ccfffe20bab.png">
