### ISSUE TITLE
Advising Center - Add Live Chat Feature - 

### ISSUE THREAD

**Issue by mjoneill** [uiowa/uiowa#2328]
- [x] Create new GTM container and add it to the prod site
- [x] Give the snippet to the client to place in their own container and update the site.
- [x] Provide on-brand image for use in all PHP Live Chat snippets. - Split to https://github.com/uiowa/uids/issues/423
- [ ] Figure out where chat service back end should be hosted (optional)

**Comment by joewhitsitt** [comment]
I "enabled" the Google Tag container functionality on the v2 site (advisingcenter.prod).

**Comment by joewhitsitt** [comment]
Google tag manager method works (custom html tag, trigger all pages), but the element is un-styled and not-clickable as 0x0px.

<img width="834" alt="Screen Shot 2020-10-20 at 12 37 09 PM" src="https://user-images.githubusercontent.com/4663676/96623451-0669e480-12d1-11eb-8bf6-714b2f8d8c22.png">

So I guess the next step would be to have them setup a Google Tag account for this and for us to design a chat element that floats on top of the page similar to a back to top button.

Then we can work to get our stylized version added to their container.

In the meantime, I am going to remove the container from the site and delete the container from the webservices account.

**Comment by joewhitsitt** [comment]
This is barebones how I would alter this chat element to work. Ideally the before could be replaced with a fontawesome icon. Ultimately, I think it is not very accessible. It creates a clone element in the DOM as well. Anything between the `<span>` is stripped so I don't know how text can be added to this beyond pseudo elements. Also elements like UIDS' badge won't work without content within the span.

<img width="109" alt="Screen Shot 2020-10-20 at 3 10 00 PM" src="https://user-images.githubusercontent.com/4663676/96638926-85b5e300-12e6-11eb-957f-1e6592db0894.png">


```html
<span style="color: #000; line-height: 0px !important; cursor: pointer; position: fixed; bottom: 10px; right: 20px; z-index: 20000000;" id="phplive_btn_1602255331"></span>
<style type="text/css">
#phplive_btn_1602255331 {
	text-align:center;
	box-shadow: 2px 2px 3px #999;
  padding: 1rem;
  width:20px;
  height:20px;
  border-radius:25px;
  background-color: #ffcd00;
}
#phplive_btn_1602255331:before {
  content: 'chat';
  font-size: 10px;
  line-height: 20px;
}
</style>
```

**Comment by bspeare** [comment]
**Notes from design meeting**

- What are the technical implementations of styling the chat button?
- Place on top of the content and disrupt or have it sit on the side with extra space?
- Style like a UIDS button to include text and icon?
- Current admissions chat button has animated gif to grab attention.

**Comment by joewhitsitt** [comment]
**Responses to design meeting notes**
 
> * What are the technical implementations of styling the chat button?

More than normal. Anything between the <span> is stripped so I don't know how text can be added to this beyond pseudo elements.

> * Place on top of the content and disrupt or have it sit on the side with extra space?

Not sure where the extra space would come from. This won't belong on every site and uids_base wasn't built to pad out for things like this.

> * Style like a UIDS button to include text and icon?

It would have to be done via pseudo elements for the text. Would it still float? This is definitely an MVP solution though.

<img width="1046" alt="Screen Shot 2020-10-21 at 5 16 41 PM" src="https://user-images.githubusercontent.com/4663676/96793116-53c57f00-13c1-11eb-91d8-a9cbd3b102a5.png">


> * Current admissions chat button has animated gif to grab attention.

Yes it does. Although, I am having troubles seeing it all of a sudden.

**Comment by joewhitsitt** [comment]
Fun fact, the button supplied by php live works via Google Tag manager works as-is. I dropped Admission's snippet into gtag and pulled into advisingcenter.local and the button displays. I suspect that the button shows/hides based on chat availability and that nobody is at the other end of AdvisingCenter's yet.
<img width="201" alt="Screen Shot 2020-10-22 at 8 46 14 AM" src="https://user-images.githubusercontent.com/4663676/96880684-11dd1d00-1443-11eb-8cfe-3d273dd9b30a.png">

**Comment by joewhitsitt** [comment]
I have added the advising center snippet to a new container within the uiowa gtag and added the container to the advising center's new site. The code is there, but the button doesn't show. Waiting for confirmation from Scott about whether or not this shows/hide based on staff availability.

**Comment by joewhitsitt** [comment]
Waiting for client to establish their own GTAG container.

**Comment by joewhitsitt** [comment]
Created a separate issue for a UIDS chat icon/button - https://github.com/uiowa/uids/issues/423
