### ISSUE TITLE
URL Redirects work from node/[nid] but not alias

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#233]
Carry-over issue from #202.

@briand44 said:
> I was able to get [redirect] to work redirecting from /node/[nid] but not from an alias.

Here is the issue related to this. https://www.drupal.org/project/redirect/issues/2821158

**Comment by joewhitsitt** [comment]
At first, I agree with Bedir which said:
>The thing is, I don't understand why you would even have both an alias and a redirect for the same path? Aliases are for existing things, redirects are to go from a not-actually existing thing to an existing thing. Why would you have an alias for something that doesn't exist? So maybe instead of trying to do something automatically, we should actually validate and prevent such redirects, possibly with an easy way to drop the alias?

But then mfernea brought up a use case that rings true with our idea of "archived" pages:
>My use case is: I have an unpublished node. If a visitor loads the page he gets a 403. So, I want to add a redirect for it.

In that case, the node/[nid] workaround works, but is not "easy"

**Comment by briand44** [comment]
This is another issue that may be getting more attention.
https://www.drupal.org/project/redirect/issues/2879648

**Comment by cory-skeers** [comment]
Similar issue, likely to be resolved in the same update: https://www.drupal.org/project/redirect/issues/2702889

### Problem
1. /current-redirect is in place and functioning
2. Create a new page, the auto alias of which matches the previous /current-redirect
3. /current-redirect is still listed as a URL redirect, but the alias takes precedence

### Expectation
Validation should prevent auto alias from choosing a current redirect URL

### Proposed solution
Validation for auto alias on new node creation and on redirect creation--check for existing redirects/aliases.
