### ISSUE TITLE
Default content - Import homepage as nid 1

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2330]
# Problem
When default content is created, we don't seem to have any control over which piece of content get nid 1. The is problematic because the homepage has logic attached to it that doesn't allow the user to delete it unless it is set to a different piece of content. Currently, the homepage is being imported as nid 2 during local development and nid 6 when installed in production. This means that the logic related to the homepage will either be broken locally or in production depending on what we set the default homepage nid to.

# Proposed solution
Figure out how to have the homepage be imported as nid 1, so it will be the same locally and in production and won't break related functionality.

**Comment by pyrello** [comment]
This might be a way of resolving this: https://www.drupal.org/project/default_content/issues/3175870

**Comment by richardbporter** [comment]
There is warning during install I just noticed. No clue if it is related.

`[info] Undefined offset: 1 ContentEntityNormalizer.php:262`

**Comment by richardbporter** [comment]
Also https://github.com/uiowa/uiowa/issues/1914

**Comment by richardbporter** [comment]
The comments above are meant for #2331. Sorry.
