### ISSUE TITLE
Remove links in University of Iowa Branding Bar configuration

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#2336]
Related:
https://github.com/uiowa/uiowa/issues/2151
https://github.com/uiowa/uiowa/issues/1980

I noticed there is a top links menu. Should customers be using this instead. Lots of confusion here.

**Comment by briand44** [comment]
I think it was discussed that this should be removed in favor of the top links menu.

**Comment by joewhitsitt** [comment]
hr.uiowa.edu needs to be accounted when doing this. splitting off the uiowa_bar functionality to the hr split.

related: https://github.com/uiowa/uiowa/issues/1907

**Comment by pyrello** [comment]
I created a new issue to resolve the branding bar interface causing confusing: #2381. I'm not sure whether that means this issue can be closed in favor of that, or whether there is other work here that needs to be done.
