### ISSUE TITLE
New height style of hero images distorts images at wide resolutions

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#2349]
Something I was unaware of that was added to the hero image block was the height (small, medium, and large) styling. If you inspect an internal page with a Featured image, the featured image will show the pre-PR state (a large image that I was uploading 3000x1286px images into). This was working for responsiveness, even on large, widescreen displays. Now, the hero images are being cropped and once the browser window reaches a certain width, it starts stretching images. This is hard to see in action on a Macbook screen, but is apparent on a large display.

With the restrictions of small, medium, and large, it makes it much harder to find images that will work for this ratio. Would it be possible to include a 4th option (i.e. extra-large or tall) that reverts this height restriction and gives us an option of what it was before the latest PR?

**Comment by bspeare** [comment]
We would probably need to add a fourth option to let image size determine the height.  The current implementation uses the image as background image to fill the container height at the three current sizes.  This fourth version would need to rewrite the implementation to place the text absolutely on the image.  This type of implementation is less responsive, but maintains the image size.

**Comment by mark-bennett-uiowa** [comment]
@bspeare sounds good, and thanks for the details about the height/text implementation!

**Comment by pyrello** [comment]
@mark-bennett-uiowa Just as some context, we changed the way that the container is being sized so that we could set a `min-height` to allow for people putting too much content into a banner, which was previously causing it to break. In the implementation you tested, the 'large' option essentially worked in the way that @bspeare is describing above, but that actually made it inconsistent with the implementation of the 'medium' and 'small' versions.

**Comment by mark-bennett-uiowa** [comment]
@bspeare @pyrello So interior pages will remain the larger height? Pages such as:
[https://uiowa.edu/academics/areas-study](https://uiowa.edu/academics/areas-study)
[https://uiowa.edu/academics/leading-programs](https://uiowa.edu/academics/leading-programs)
[https://anthropology.prod.drupal.uiowa.edu/graduate](https://anthropology.prod.drupal.uiowa.edu/graduate)
On the frontpage of the uiowa.edu site, the video is remaining the large height. Is this something that is available? Setup in a custom split? Sorry, I just want to understand this.

**Comment by bspeare** [comment]
@mark-bennett-uiowa those are still using the "Hero" styles.   I imagine that moving forward we want to replace those with the new banner styles and put any future work into the banner component.

**Comment by bspeare** [comment]
@mark-bennett-uiowa Are you still interested in pursuing an option to preserve the banner image aspect ratio beyond the fixed heights?

**Comment by mark-bennett-uiowa** [comment]
@bspeare I would like to see/know if its possible. Some images look badly distorted as we stretch the width, or cut off important parts of the images.

**Comment by bspeare** [comment]
@mark-bennett-uiowa can you check your sites and see if we can close this with the latest updates that we implemented?

**Comment by mark-bennett-uiowa** [comment]
Yes, sorry, this seems to definitely be working now. I should have commented and closed this long ago. Thanks for the work on this all!
