### ISSUE TITLE
Transition Coronavirus site to V3

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2358]
# Problem
The Coronavirus site remains in a weird state where it is still a V2 site, but has Layout Builder enabled. This makes it a bit of a wildcard for some updates. Since the site is mostly (or completely?) transitioned to Layout Builder, it would be nice to finish that process and make that site a standard V3 site.

# Proposed solution
- [x] Confirm with client that it is okay to remove any revisions of content not currently in use. - _available window Feb 9th_
- [x] Migrate remaining live paragraph content to its LB equivalent.
- [x] Delete pages/revisions that are no longer needed. - https://coronavirus.uiowa.edu/admin/content?title=&type=page&status=All&langcode=All https://github.com/uiowa/uiowa/files/5767302/Coronavirus.pages.using.V2.paragraphs.pdf
- [x] Delete any orphaned paragraph content.
- [x] Disable sitenow_v2 split via update hook
- [x] Disable coronavirus_uiowa_edu split via update hook
- [x] Query for every textarea field and convert `<drupal-entity>` instances to `<drupal-media>` and their respective view mode attributes.
- [x] Schedule content freeze
- [x] Make sure no new pages have paragraph items created by default. Gut. Save. Clear revisions.
- [x] Make sure none of the layouts for pages have the v2 content block field placed. Remove. Save. Clear revisions.
- [x] Run Cron, delete orphans (twice).
- [ ] Merge/deploy https://github.com/uiowa/uiowa/pull/3048

**Comment by joewhitsitt** [comment]
https://github.com/uiowa/uiowa/issues/2742 - met with site owner. they will work on transitioning content to v3 layout builder blocks as they have time.

**Comment by pyrello** [comment]
Site owner has requested that we notify them before taking the next step, which is removing all the old revisions from each piece of content. They have also requested that this work only happen on Tuesdays and Thursdays.

**Comment by joewhitsitt** [comment]
Reached out to Hayley about starting revision remove tomorrow (Feb 9th) with Brian, Michael and Danielle cc'd. Hayley gave approval and told us to reach out if we needed anything

**Comment by joewhitsitt** [comment]
So, I went through all the pages and removed empty paragraph items and the items from the archived pages. Then I cleaned up revisions again. Syncing down though however, I am still seeing paragraph items. Going to look into where they are coming from.

**Comment by joewhitsitt** [comment]
So, there was a corrupted section paragraph item that was preventing the cleanup of itself and 4 others. I manually corrected the corrupted rows. When the current deployment is done, cron and delete orphans needs to run twice.

Update: Done in Prod

**Comment by joewhitsitt** [comment]
So without an update hook, I think the go-live process is:

Content freeze. We don't want new paragraphs created when visiting/saving node/add/page.
Disable v2 split in prod. Switches everything to active db config.
Make sure no new pages have paragraph items created by default. Gut. Save. Clear revisions.
Make sure none of the layouts for pages have the v2 content block field placed. Remove. Save. Clear revisions.
Run Cron, delete orphans (twice).
Deploy PR that removes the split items from the coronavirus but keeps the split itself.

**Comment by pyrello** [comment]
> Disable v2 split in prod. Switches everything to active db config.

Do be clear, are you just planning on turning off the v2 split, but not running `drush @coronavirus.prod cim`?

> Deploy PR that removes the split items from the coronavirus but keeps the split itself.

Is there a reason that you want to keep the Coronavirus site split?

**Comment by joewhitsitt** [comment]
Correct. The plan is to let the deployment do the import.

>Remove coronavirus_uiowa_edu split - Must be done as a separate step from the previous one.

I figured this was one of those follow-up in the next deployment situations.

**Comment by joewhitsitt** [comment]
Based on https://github.com/uiowa/uiowa/pull/3044#issuecomment-776812029, I think for our next available window we need to remove the v2 content blocks from the layouts of each existing page or this needs to be done programmatically with an update hook.

**Comment by pyrello** [comment]
@joewhitsitt I'm not sure if it needs to be removed in a follow-up step. I don't remember why I wrote it out that way.

**Comment by pyrello** [comment]
Just did a test:
* @joewhitsitt synced prod > stage
* On stage, disabled SiteNow V2 split and Coronavirus site split.
* Ran `drush @coronavirus.test cim`

That all worked successfully. However, I just realized there is another piece to this that I didn't consider. The V2 WYSIWYG uses the `<drupal-entity>` inline embed syntax, while in V3 it uses `<drupal-media>`. I think that means that, to finish this, we are going to need our PR to use an update hook to do the following:
* Turn off sitenow_v2 and coronavirus splits
* Query for every textarea field and convert `<drupal-entity>` instances to `<drupal-media>`.
* Run code equivalent to `drush cim`.

**Comment by joewhitsitt** [comment]
And deal with the left over layout builder placements of the field_page_content_block within existing pages. Just saving this page, causes a white screen: https://coronavirus.stage.drupal.uiowa.edu/node/556/edit

>Query for every textarea field and convert <drupal-entity> instances to <drupal-media>

Should we polish off https://github.com/uiowa/uiowa/issues/865 for v2 as a part of this?

**Comment by joewhitsitt** [comment]
Got approval for 2/10:
>to remove the 'Placeholder for the "Sections" field" block within the layout edit screen for each of the existing pages. As part of the process, we will save a new revision and again remove the older revision once we confirm the page renders as before.

**Comment by joewhitsitt** [comment]
Looks like the attributes that matter aren't one-to-one: drupal-media has `data-view-mode="large__no_crop"` while drupal-entity has `data-entity-embed-display="view_mode:media.image_large"`

I think I have familiarized myself with the new way of doing a sql update in case we decide to go that route. https://gist.github.com/joewhitsitt/f14d1ec6218cf2c4b4e6facf33755998

**Comment by pyrello** [comment]
#3048 has the code I was working on for this. I had already started it in a separate PR, so I just left it there, since we'll eventually need this for #865. We can adapt that to this issue as needed.

**Comment by joewhitsitt** [comment]
@dnkemper went through the PROD site this morning to resolve https://github.com/uiowa/uiowa/issues/2358#issuecomment-777033961

We will want to check for any new pages before go live but the bulk has been dealt with.

**Comment by joewhitsitt** [comment]
Got approval for 2/15 to freeze content (they will check with us if they need to change something).

**Comment by joewhitsitt** [comment]
I went through the recently updated and didn't see evidence of new paragraphs or continued placement of the field_page_content_block on layout builder. Going to sync db to dev and try https://github.com/uiowa/uiowa/pull/3048 there
