### ISSUE TITLE
Update layout-onecol--background template to use updated banner.html.twig template

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#2369]
# Problem 

The one column background template is still using the `hero.html.twig` template: https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/templates/layouts/onecol--background/layout--onecol--background.html.twig#L27. 

# Proposed Solution

Update the template to use the `banner.html.twig` template and styles.

**Comment by dnkemper** [comment]
Started a draft PR for this.. have to remove my assignment since my computer crashes every time I try to add a featured image :(
