### ISSUE TITLE
New banner style "gradient" overlay appears over entire image below 1350px wide

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#2376]
On the frontpage image on [https://anthropology.prod.drupal.uiowa.edu/](https://anthropology.prod.drupal.uiowa.edu/) the banner image appears to have an overlay with no gradient (covers entire image uniformly) when under 1350px wide. You can see this more clearly when changing the overlay color to light, rather than dark:
<img width="1304" alt="Screen Shot 2020-10-20 at 9 47 08 AM" src="https://user-images.githubusercontent.com/3067017/96603238-75d3da00-12b9-11eb-92f3-87c0c0af0030.png">
Here is 1563px wide with light gradient:
<img width="1546" alt="Screen Shot 2020-10-20 at 9 53 49 AM" src="https://user-images.githubusercontent.com/3067017/96604124-5be6c700-12ba-11eb-9c80-0359bbf670ae.png">
Here is 1281px wide with light gradient:
<img width="1265" alt="Screen Shot 2020-10-20 at 9 54 25 AM" src="https://user-images.githubusercontent.com/3067017/96604197-70c35a80-12ba-11eb-897a-4c065aaebb95.png">

Looking at an interior page that is still using the hero block, this does not appear to be an issue.

**Comment by bspeare** [comment]
Closing this in favor of https://github.com/uiowa/uiowa/issues/2857.
