### ISSUE TITLE
Investigate integration with MAUI for Areas of Study

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2379]

**Comment by richardbporter** [comment]
There is not much information in MAUI besides basic info like name, department, etc. The current admissions site areas of study is much more than that. Leveraging MAUI would either be:

- a one time import
- continuous import
- something dynamic with augmented local data

A desired starting point for the new site is the current site and _not_ MAUI.  Leveraging MAUI might be useful for automating active/inactive status but that is not desired by customer as information for new programs won't exist immediately. We could still build a basic listing of academic programs in the yet-to-be-ported MAUI module but I'm not seeing an overlap with the admissions site requirements.
