### ISSUE TITLE
Investigate shared use case for Areas of Study

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2380]
# Motivation
As part of #2365, there is going to be a content type created for the Admissions website for an Area of Study. This task would be to investigate whether we can use some of these fields for a shared use content type of the same name.

**Comment by richardbporter** [comment]
I don't have a lot of experience building areas of study for D7 sites so I'd like to hear from others but a shared use case for this seems difficult for a few reasons:

- Highly specific, custom requirements.
- Customer preference for migrating content from existing site.
- Time/budget (?).

Also, building specifically for admissions does not preclude us from sharing later on. 

I mentioned in #2379 that we could still build a dynamic, basic listing of majors, minors, etc. Maybe we could link those list items somewhere for more info (general catalog?, admissions even?). Would that suffice as a shared feature for people? Obviously, it would be much more bare-bones with the idea of centralizing details somewhere else. If not, and the desire is to allow any site to customize areas of study then I don't see a whole lot of value in sharing.

**Comment by richardbporter** [comment]
Another option would be to build this out for admissions and then leverage JSON API to "feed" the content out to other websites that want to display it. Maybe even with department filters and such. That way, we don't have to worry about the the complexities of CM but we're still able to "share" the functionality.

**Comment by pyrello** [comment]
@richardbporter Thanks for your thoughts on this.

To clarify, I wanted to see how much overlap there was between what we would build for admissions (which is highly specific to their use case) and for other sites that might want to display this type of information, but probably only need a handful of fields. I'm not sure, but I think that @mark-bennett-uiowa had expressed that this would be useful for some of his sites. If there is a smaller footprint base case version of an Area of Study content type that could be built, that could be part of a shared feature split, while the functionality that is more specific to Admissions could live in their split, similar to what has been built for the scholarship content type and related jump menu functionality.

**Comment by pyrello** [comment]
Here are a few examples I could find:
* https://clas.uiowa.edu/departments-and-divisions/majors-minors
* https://uiowa.edu/academics/areas-study
* https://grad.admissions.uiowa.edu/graduate-areas-of-study

**Comment by mark-bennett-uiowa** [comment]
@pyrello nailed this for the main use case for CLAS. I could also see this being used in a Person type for tying people to areas of research or creative work, but that opens up a slightly different use case. In D7, we created a separate content type called Research, and entity referenced it from a field in the person content type. That way we could display the areas of research under a Person, as well as maintain a list of people under the Area of Research. For instance: [https://biology.uiowa.edu/research/genetics](https://biology.uiowa.edu/research/genetics)

I am envisioning the first case (a list of areas of study) with this issue, and assuming we are planning on something for the people as a separate issue.

**Comment by mark-bennett-uiowa** [comment]
@pyrello @richardbporter Im envisioning something simple to start, such as:

- **Area of Study** (Name)
- **Degree(s) Offered** (the same list Sean has on the Grad Admissions site, just include the Undergraduate degrees; BA, BS, BSc, etc)
- **Description**
- **Category** (this comes into play with groups (see [https://uiowa.edu/academics/areas-study](https://uiowa.edu/academics/areas-study) and [https://clas.uiowa.edu/departments-and-divisions/majors-minors](https://clas.uiowa.edu/departments-and-divisions/majors-minors) above)
- **References to similar or adjacent degrees** in other colleges or departments (see the Business MBA in the grad link above)
- **Image**

If we want to start adding the additional information like on [https://grad.admissions.uiowa.edu/academics/accounting-mac](https://grad.admissions.uiowa.edu/academics/accounting-mac), that would be above and beyond to start.

**Comment by richardbporter** [comment]
> * **Degree(s) Offered** (the same list Sean has on the Grad Admissions site, just include the Undergraduate degrees; BA, BS, BSc, etc)

So just a list field of these options? Where are those?

**Comment by richardbporter** [comment]
All of the areas of study on https://clas.uiowa.edu/departments-and-divisions/majors-minors link to the general catalog (which kinda goes back to my previous comments). It looks like we'll need a link field as well.

**Comment by mark-bennett-uiowa** [comment]
@richardbporter A link field, absolutely. However, are you envisioning a link field for each degree? All the CLAS degrees are separate pages. For instance, the area of study is Anthropology. The degree options are PhD in Anthro, MA in Anthro, BA in Anthro, BS in Anthro, Minor in Anthro, Museum Studies Certificate. Each have their own link.
