### ISSUE TITLE
Add additional background color options for banner block

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#2387]
# Problem

There is not an option to set `Light` or `Gray` background options for the banner block. 

# Proposed Solution

Add `Light` and `Gray` background options for the banner block. 

<img width="1180" alt="Screen Shot 2020-10-21 at 2 10 17 PM" src="https://user-images.githubusercontent.com/1036433/96772707-25d44080-13a9-11eb-81d1-24de6a3730ec.png">

**Comment by bspeare** [comment]
Map the `Light` option to `bg--light` and the `Gray` option should already be a defined style.

**Comment by bspeare** [comment]
@ethanstjohn, a small correction on this.    The `Light` option should be `White` and map to the class `bg--white`.

**Comment by ethanstjohn** [comment]
Good to know! thank you

**Comment by ethanstjohn** [comment]
I have been working on this and I believe I got the gray part to work, however, the white part seems to show as transparent when I look at my default site. I may need some backup.
