### ISSUE TITLE
Add a redirect on node edit forms

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#239]
Missing functionality from D7.

Waiting on:
https://www.drupal.org/project/redirect/issues/2958635 (RTBC)

**Comment by joewhitsitt** [comment]
This is now in -dev. Need to evaluate the dev version to see if we can move forward with this in production.

**Comment by cory-skeers** [comment]
Tried out -dev locally, and the option to add a redirect from node edit forms mostly works well.

Only issues I ran into seem to be related to: https://www.drupal.org/project/redirect/issues/3057250

Having the same validation issues in the official release:
- Add a destination before a source (choosing to add a redirect from the edit node page fills in the destination automatically)
- Add the source
- Without clicking away from the source, click directly on submit

The source path field gets deleted and validation fails. After this, re-filling in the path skips validation completely and allows invalid redirect source paths.

**Comment by cory-skeers** [comment]
This is now in production for Redirect 8.x-1.4
https://www.drupal.org/project/redirect

Haven't checked if the validation bug noted above is present in the update, but it wasn't listed in the included bug fixes.

**Comment by joewhitsitt** [comment]
There are several issues still with redirect (#233 for example). If the recent release resolves the current issue without introducing more (minus the validation hiccup), I say we go ahead and update to the stable release as a step in the right direction.
