### ISSUE TITLE
Promote Training Sessions in Site Create Email Templates

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#2390]
Add to the site created emails in sitenow.uiowa.edu request-site webform (linked text).

Attend a SiteNow v3 Tutorial/Workshop Session (https://hpproject.sites.uiowa.edu/forms/sitenow-v3-session-signup)

**Comment by joewhitsitt** [comment]
Closing. This is done. Thanks @dnkemper

**Comment by dnkemper** [comment]
CRUD. SORRY AND THANK YOU @joewhitsitt
