### ISSUE TITLE
Aggregator Documentation

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#2391]
New functionality: https://github.com/uiowa/uiowa/pull/2296

**Comment by richardbporter** [comment]
Drafted: https://sitenow.uiowa.edu/documentation/layout-builder-sitenow-v3-only/rss-feeds Please make changes there if anyone thinks of something. Otherwise, I'll probably publish and close this later today.

**Comment by richardbporter** [comment]
Actually, it references the parent title docs so we'll need those first. https://github.com/uiowa/uiowa/issues/2392

**Comment by dnkemper** [comment]
@richardbporter since the parent title docs are finished, this can be published!

**Comment by richardbporter** [comment]
Thanks. For some reason, I'm having trouble finding them. Could you point me to them?

**Comment by richardbporter** [comment]
Oh it looks like it was added to each block documentation. I was thinking we would split that out and link to it so we don't duplicate docs. Maybe we can do that at a later point. Thanks!

**Comment by dnkemper** [comment]
@richardbporter oops sorry! I figured this way it would focus on the specific block they're needing help with instead of being redirected to a new page? Since the documentation is currently set up that way?
