### ISSUE TITLE
Add background video loop functionality to banner block

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#2403]
# Problem 

The current banner block does not allow for a video loop to be uploaded into the block. 

# Proposed Solution

Create a "Video" option within the "Background" options of the banner block where users can upload local video files. 

## Next steps

- [ ] Integrate UIDS work from uids#394

## Accessibility fixes

- [ ] Change markup in hero block template to disable autoplay by default and dynamically change based on block level override. 
- [ ] Add override checkbox/field to hero block in layout builder tray to enable autoplay.
- [ ] If autoplay is enabled, add sufficient warning text about vestibular triggers

**Comment by joewhitsitt** [comment]
If placeholder image still exists, I suggest using the existing image field for that and creating a separate video field. This will ease any logic about the media type

**Comment by pyrello** [comment]
@joewhitsitt I was actually thinking that this would be easier if we adapted the existing field to allow for image or video, then added a thumbnail (placeholder) image field to the video media entity.

Can you clarify why you think a separate field would ease logic about the media type?

**Comment by joewhitsitt** [comment]
Template or preprocessing logic, i imagine to do different things based on the media type, is easier when you can just look to see if video field has value instead digging further in to a share field to see what kind of media type it is. The placeholder image should do similar things as a regular banner image if only temporarily during load or error.

Just a suggestion. I defer those actually implementing

**Comment by pyrello** [comment]
I guess that my assumption is that if we end up implementing a video with placeholder in multiple entities eventually, then it would be better to figure out how to do it at the media entity level, so we wouldn't have to add the same set of fields to multiple blocks. I have, however, not tested this out as a possible solution, so I'm not sure what sort of gotchas we might run into.

Thanks for the clarification.

**Comment by pyrello** [comment]
Adding some notes based on discussion in standup to clarify what is being proposed:
- Adding a placeholder/thumbnail image field to the local video media entity
- Implementing a module like https://www.drupal.org/project/media_thumbnails_video to handle auto-generation of still image from the video.
- Adding an autoplay video checkbox (defaulted to off) to the local video media entity
- Adding local video as an option for the banner image field
- Using the media entity templates to handle the specific styling for each type of media, hopefully meaning that not much change would be needed in the banner block template.
