### ISSUE TITLE
Change banner link field settings to allow for 3 links to be added for button rows

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#2404]
# Problem

The current banner block only allows for one banner link button to be placed within the block. 

# Proposed Solution

Change the banner link field to allow up to 3 links to be placed within a banner block. 

## Next steps

- Change banner_link field to allow multiple links
- Adjust banner template in `uids_base`
- If necessary, adjust UIDS component to allow for a button row: https://uids.brand.uiowa.edu/components/detail/banner--default.html
- If necessary, adjust UIDS js https://github.com/uiowa/uids/blob/main/src/components/banner/banner.js to change accessible link strategy.

**Comment by bspeare** [comment]
How do we want to handle the setting for the link field?  Set to 3 or set it Unlimited and limit it to 3 programmatically?

**Limited to 3:**

<img width="677" alt="Screen Shot 2020-11-19 at 10 51 34 AM" src="https://user-images.githubusercontent.com/1036433/99697705-94aec300-2a55-11eb-9695-968e7f0eaf51.png">

**Unlimited:**

<img width="665" alt="Screen Shot 2020-11-19 at 10 52 13 AM" src="https://user-images.githubusercontent.com/1036433/99697719-9a0c0d80-2a55-11eb-8eee-9ca75bfc693a.png">

**Comment by cory-skeers** [comment]
> How do we want to handle the setting for the link field?

I'd personally lean toward the unlimited and limit programmatically. Keeps it a little cleaner on edit, but also I think the Limit to 3 option adds pressure on the user to come up with links, rather than opting in if they already have a plan for more than 1.

**Comment by dnkemper** [comment]
Whoops didn't read through comments. @bspeare are you working on this right now?

**Comment by bspeare** [comment]
@dnkemper Nope! Check in with @GaryRidgway on his work in https://github.com/uiowa/uids/pull/412.

**Comment by richardbporter** [comment]
Seems like nobody is assigned to this. I think @GaryRidgway is doing the UIDS part of it. I can start on the Drupal side of things.

**Comment by richardbporter** [comment]
I started on this in #2609 and initially I I agreed with @cory-skeers about limiting to 3 via validation but it now feels like bad usability to present the user with an option to add more than three only to return a form error saying they can't.

**Comment by cory-skeers** [comment]
@richardbporter That's a good point. I wonder if there's a way to limit it to 3 on the form itself, by hiding the "Add another item" button if 3 links are already present? Not sure how that button gets added, if it's readily accessible to add a `#states` attribute and hide with AJAX. If something like that's not readily accessible, though, maybe it's better to set it to 3.

**Comment by bspeare** [comment]
@richardbporter  I see what you mean on the validation.  It doesn't look like you can remove the fourth link if it has been added - is that correct?  Setting it to 3 seems like a good MVP for now and perhaps we can do future work to enhance the show/hide of these 3 link fields?

<img width="1199" alt="Screen Shot 2020-12-01 at 1 44 40 PM" src="https://user-images.githubusercontent.com/1036433/100789125-aa1fd780-33db-11eb-90b5-8f080f6eb0ad.png">

**Comment by richardbporter** [comment]
Yea, that too. :)

I gave @cory-skeers suggestion a shot but had trouble with the logic. Seems like the simplest solution for right now is just to use Drupal's field limit out of the box so everything is handled for us.

**Comment by cory-skeers** [comment]
I believe I have it working to show one with an "add more" button, but limit to only 3 being added.

If you can get into a situation where more than three links are added, there's no catch or validation to limit it, but I'm fairly sure using the `#max_delta` and unsetting the "add more" button is restrictive enough that you couldn't get into that situation unless links were added programmatically.

**Comment by cory-skeers** [comment]
Thanks @bspeare for catching a way that you could still add unlimited links! (Editing a banner block with 3 links already existing creates a blank fourth link by default...and then a fifth if you save four, and sixth if you save five.......)

Another update in place that removes the fourth auto-added link field when `#max_delta` reaches the limit. _Now_ I think, between no auto-added link field and now "Add more" button, there shouldn't be a way to add more than 3 links through the UI.
