### ISSUE TITLE
Change featured image field to allow users to set different heights

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#2405]
# Problem

Users have requested the ability to set different heights on their featured images in order to reduce page scrolling. 

<img width="1842" alt="Screen Shot 2020-10-26 at 2 41 32 PM" src="https://user-images.githubusercontent.com/1036433/97220427-77aa0b80-1799-11eb-92b2-45d952a3f600.png">

# Proposed Solution

Utilize the banner block refactor sizes to allow for users to set a small, medium, or large size on their featured image blocks. 

<img width="1839" alt="Screen Shot 2020-10-26 at 2 43 28 PM" src="https://user-images.githubusercontent.com/1036433/97220544-a0ca9c00-1799-11eb-80f7-076d80877df9.png">

## Next steps

- Determine a method to set the height for the featured image 
  - Through the node edit screen?
  - Or through a new custom block that can be edited within layout builder?

**Comment by GaryRidgway** [comment]
I think this should be implemented on the edit screen just under the featured image so that it is not confusing to find all of the functionality for the featured image. Keeping it in the same place that the featured image is selected drives home the functionality and purpose of the option, and makes sure users know exactly what it relates to.

**Comment by bspeare** [comment]
Backlog grooming conversation:
- Add select list to featured image area on node edit screen with `small`, `medium`, `large` options using values used in layout builder banner styles such as this example: https://github.com/uiowa/uiowa/blob/main/config/default/layout_builder_styles.style.banner_large.yml
- Pass those values to the banner attributes listed in https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/templates/layouts/onecol--background/layout--onecol--background.html.twig
- Future work to add a global height option that would override the individual node options (#2633)
