### ISSUE TITLE
As a prospective student, I can view detailed profiles of current students on the admissions website

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#2409]
# Request
Admissions would like to have a page for teasers of student profiles (https://admissions.uiowa.edu/student-profiles). These teasers consist of a first name, photo, major and a quote and links to the students full profile. The full profile consists of a photo, first name only (they don't show last name of students), quote, major, hometown, bio and a videos if they exist.

They need the ability to display a set number of random profiles in a block. They currently have a block that displays 12 random thumbnails. Each thumbnail is a link to that specific student profile. This does not need to be 12, it can be a different number that works within the design. Also, when hovering the first name of the student is displayed. They are open to different ideas for displaying this as well. Currently these are displayed on all pages unless the block is specifically excluded from a page. They would at a minimum need a way to add this content to multiple pages of their choosing.  Currently displays on all student profiles as well as many other pages. (https://admissions.uiowa.edu/profiles/yiqian)

Additionally, on occasion Admissions will have a campaign around student profiles based on some student attributes or location attributes (e.g. transfer students, students from a specific country or state) so they need some flexibility in order to display student profiles in various ways, possibly within a block that can be placed with layout builder (https://admissions.uiowa.edu/international-ambassadors).

# Proposed solution
One potential solution discussed for the block was the ability to configure a block display of student profiles based on some structured data stored as part of the profile and place that block using layout builder. Examples of options would be to display a specified number of random student profiles, display student profiles based on state, country, or other student attributes.
- Build a content type that allows for the display of all the information and design/theme profile entities.
- Build and design/theme teaser page.
- Build and theme a block to display random profiles as well as profiles based on state, country, and other attributes. This needs to be flexible in design (allow display of different number of items) as well.

# User Stories 

- [ ] As a prospective student, I can view a student profile page on the admissions dev website. https://github.com/uiowa/uiowa/issues/2457
- [ ] As a prospective student, I can view teasers of the student profiles on an overview page https://github.com/uiowa/uiowa/issues/2458

**Comment by joewhitsitt** [comment]
Per @briand44, Content Type might not be needed for this. Instead an alias pattern would used instead.

**Comment by bspeare** [comment]
Updated the issue with a user story section.
