### ISSUE TITLE
Tippie - ImageAPI Optimize configuration

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#2411]
## Issue

Tippie is trying to implement the ImageAPI Optimize module with http://resmush.it/ but is having issues with the default setup that allows uploading to the private file system.

## Proposed Solution

Checkout the feature branch and test the functionality. If the private option can be removed safely, form alter and remove access/disable to allow the form to be successfully submitted. The process of getting the functionality production ready and deployed is out of scope.

**Comment by joewhitsitt** [comment]
@makurj is this still an issue?

**Comment by makurj** [comment]
@joewhitsitt not sure yet. I'll update this once I know one way or the other.

**Comment by makurj** [comment]
@joewhitsitt The uploading issue has been resolved. I do need 10-15 minutes to talk over a couple other things regarding this module.

**Comment by joewhitsitt** [comment]
@makurj based on today's discussion is this issue still needed or should I leave it open for now?

sounded like some compression was occurring in addition to drupal's gd2 default.

**Comment by makurj** [comment]
@joewhitsitt There is definitely compression happening. After testing with rsync, if images are still missing from dev, I may choose not to proceed with this module. Also, I have to take into consideration PNGs not getting compressed. I wouldn't mind leaving this open a little while longer, just in case.

**Comment by joewhitsitt** [comment]
If you are still poking around, I would also suggest looking at ImageMagick which is available in sites/all to just enable and use instead of GD2. You might be able to lower the quality to 75 with that.

**Comment by makurj** [comment]
Yep, I'm planning to. Thanks for all the ideas!
