### ISSUE TITLE
Implement and test card template refactor for event, events, aggregator, articles, people

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#2425]
# Issue

Now that the card option updates from UIDS have been implemented in https://github.com/uiowa/uiowa/issues/2306, additional work is necessary to implement and test these updates with the `v2` and `v3` custom blocks, paragraphs, feeds, and content types that use the card template for their displays. 

## Template updates

- [x] Update event template to implement updated card template.
- [x] Update events template to implement updated card template.
- [x] Update aggregator template to implement updated card template.
- [x] Update people teaser template 
- [x] Update paragraphs card template
- [x] Update articles teaser template

**Comment by joewhitsitt** [comment]
Is there a consumable diff somewhere that illustrates the types of changes needed here? Also, is this blocked by anything?

**Comment by bspeare** [comment]
I think we updated the templates that I checked off above in the previous PR and this is not blocked by anything.

**Comment by GaryRidgway** [comment]
I've got a branch started for this, give me a moment and I will push it up so we can all work on it together
https://github.com/uiowa/uiowa/pull/2461 is the PR,
`i2425-card-template-rafactor` is the branch name

**Comment by joewhitsitt** [comment]
event -> card, one thing i have noticed is that the event was transparent. (e.g. uiowa.edu event items are white on gold after making the change). each of these block types don't have the style selection options currently and I am not sure if that is in scope for this issue.

**Comment by bspeare** [comment]
@joewhitsitt https://github.com/uiowa/uiowa/pull/2462 is bringing in the background color updates.   We might need to move this work over to that pr once you and Alan have the templates finished for complete `a11y` tests.
