### ISSUE TITLE
Implement headline refactor from UIDS into uids_base

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#2427]
# UIDS Headline refactor 

A headline refactor and background component was added in https://github.com/uiowa/uids/pull/392 and these changes will need to be implemented into `uids_base`. 

- [x] Update references to LBS background color names in component `scss` files.
- [x] Update class names to remove legacy classes like `bold-headline`.
- [x] Update Headline template to reflect class name refactor: https://github.com/uiowa/uids/blob/i309-event-card-variant/src/components/headline/headline.twig

**Comment by joewhitsitt** [comment]
broken link in description. https://github.com/uiowa/uids/blob/main/src/components/headline/headline.twig

**Comment by bspeare** [comment]
Looks like we still need to work on this at some point: https://github.com/uiowa/uiowa/search?q=bold-headline.
