### ISSUE TITLE
Allow feed items beyond the 6 month/25 max limit

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#2428]
## Issue

Some feeds contain an archive of content that extends beyond the 6 month limit. This would help avoid importing this type of content.

Example Newsletter Archive
https://apps.its.uiowa.edu/dispatch/archives/past/--iowa-law---september-25-lxj144j

https://careers.prod.drupal.uiowa.edu/gaining-experience

## Proposed Solution

Special consideration should be given to database sizes and query performance.

- [x] Remove max number of items limit
- [x] Add a mini pager for feeds with more than X.
- [x] ~~Option to disable default 6 month limit on a per feed basis~~

**Comment by richardbporter** [comment]
I didn't really think about this at first but maybe unlimited feed items is a custom engagement? The aggregator config could be split for a site and changed. It is fairly simple config. This might be a short-term fix and we could look to increase the standard limit later on.

> Option to disable default 6 month limit on a per feed basis

Unfortunately, the config sets all feeds import and clear durations. Maybe we could override this somehow if desired.

> Add a mini pager for feeds with more than X.

~~We would also need a way to allow an unlimited number of results placed in the RSS Feeds block as it is currently limited to 25~~. Another option would be to allow access to the Aggregator pages which display all items paged by default, _I think_. The URL/breadcrumbs aren't great for those though.

**Comment by joewhitsitt** [comment]
Honestly, not sure if the unlimited listing is required if the source can still be linked to (more link). Going to mark this as postponed for now. Law requested this, but doesn't have a v3 website yet.

**Comment by richardbporter** [comment]
The admissions site which I know uses aggregator has the following database table sizes related to aggregator: 
```
 aggregator_feed                                    0.09 MB   
 aggregator_item                                    0.09 MB   
 block_content__field_uiowa_aggregator_feeds        0.06 MB   
 block_content__field_uiowa_aggregator_text         0.06 MB   
 aggregator_feed__field_aggregator_feed_image       0.06 MB   
 block_content__field_uiowa_aggregator_count        0.05 MB  
```

I'd be ok with expanding this but maybe not right now with our storage issue.
