### ISSUE TITLE
Adjust CSS for top entry on news block

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#2433]
As can be seen on this page: [https://americanstudies.prod.drupal.uiowa.edu/news](https://americanstudies.prod.drupal.uiowa.edu/news), the top border still appears on the first news entry for the listing block.
<img width="1333" alt="Screen Shot 2020-10-30 at 9 57 51 AM" src="https://user-images.githubusercontent.com/3067017/97720878-c9eb7500-1a96-11eb-8f29-cf3e0ef34e95.png">

Setting the following should fix this:
```
.view-articles .view-content:first-child .views-row:first-child, .view-id-articles .view-content:first-child .views-row:first-child, .view-display-id-page_articles .view-content:first-child .views-row:first-child {
  border-top: none;
  .node--type-article .card__body {
    padding-top: 0;
  }
}
```

There is already a fix for the people view similar to this: `.view-id-people .view-content:first-child .views-row:first-child {...}`, I just included additional classes for the articles view.

**Comment by joewhitsitt** [comment]
Can this be closed? I don't see a top border anymore
<img width="1181" alt="Screen Shot 2021-05-05 at 3 13 05 PM" src="https://user-images.githubusercontent.com/4663676/117203278-72ff8900-adb4-11eb-9d4d-14e937009d07.png">

https://americanstudies.uiowa.edu/news
