### ISSUE TITLE
As a prospective student, I can search and filter a page listing Areas of Study on the Admissions site

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2444]
# Motivation

As part of #2365, we need to build a search page for Areas of Study that allows filtering by terms that are associated with the Area of Study content type.

# Proposed solution

- [ ] Build a view of Areas of Study content type
- [ ] Build exposed filter that allows searching and filtering by associated terms
- [ ] Implement autocomplete on exposed search field

Additional tasks may need to be defined here as a result of #2445.

**Comment by bspeare** [comment]
Is this considered done with https://admissions.prod.drupal.uiowa.edu/areas-of-study in place or does it still need more work?

**Comment by bspeare** [comment]
Closing this in favor of https://github.com/uiowa/uiowa/issues/3203.
