### ISSUE TITLE
As Admissions staff, I can access a printable version of an Area of Study page

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2446]
# Motivation

Admissions staff currently have the ability to access a printable PDF version of Areas of Study pages that is generated directly from the content on their website. These PDFs are formatted differently than their associated page. The generation is handled in Drupal 7 via the print module.

# Proposed solution

Expose a printable PDF version of Areas of Study page.

## Example
[Accounting.pdf](https://github.com/uiowa/uiowa/files/5469293/Accounting.pdf)

**Comment by briand44** [comment]
Closing this in favor of #2500.
