### ISSUE TITLE
As a prospective student, I can view a student profile page on the admissions dev website

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#2457]
Story split from epic: https://github.com/uiowa/uiowa/issues/2409

**Investigate and create content type:**
  - Can we use the profile content type as a base for the content type/design or is this a completely new content type?
  - What part (if any) can be used in the default profile vs what goes in a split?
  - If this is new, can it be used for other colleges?
    - The fields look like standard student profile fields.
     - Are there any fields missing that we want to add?

*Acceptance Criteria:*  a content type with all of the fields displayed mapped to the profile content type twig template and library styles.

## Field notes
Title
First Name
Last Name - Not displayed publicly
Content Type - used for url alias pattern - These currently all live at profiles/firstname
Gender - used internally only
Student attributes - list of attributes used internally and may be used to build block displays for campaigns
Major - text
Home Town - text
Home State - list of states - I just noticed this list currently included China and India I'm not sure why
Home Country - list of countries
Anticipated graduation date - this is used internally to determine when they should manually remove the profile. Currently a date field but doesn't need to be. Could be session (Fall 2021)
Short profile blurb - used as the quote on teasers and profiles
Body - WYSIWYG
Activities - they thing this can go away and just be part of the body field
image - they currently have two but think 1 is fine as long as cropped and scaled appropriately for display
video - ability to potentially have multiple youTube videos
photo gallery - not needed anymore

**Comment by joewhitsitt** [comment]
Blocked by #2291

**Comment by bspeare** [comment]
- Can we use person content type and the layout builder template used for counselors as the MVP?  
  - Once we have a patch for (https://www.drupal.org/project/layout_library/issues/3082434) can we move forward with the layout library module to adjust the layout to use a different template based on the student profile selection?
    - https://www.drupal.org/project/layout_library
    - https://www.drupal.org/project/template_entities_lbl

**Comment by bspeare** [comment]
Some thoughts on handling the student profile after today’s design meeting:

- Create a separate content type called “Profile” or “Student profile”
- Reuse field storage definitions from “Person” content type where you can
- Set the content type up to use a layout builder template to use the featured image banner header
- We can add UIDS component classes to individual field templates to style them for the rest of the layout

**Comment by dnkemper** [comment]
- Display hometown + (if US, display state) + if (international, display country)
- Next/Previous button at bottom of full student nodes
- Square images for grid - zoom in on image or image style? Might need to add two separate images
- Make grid of images = 9
- Make blockquote (student profile blurb) bigger

**Comment by bspeare** [comment]
Here are my notes:
- Apply now button in sidebar?
- Remove center alignment on view header in sidebar
- Change major field to be a reference to areas of study
- Add location icon and hometown info to teaser view
- Find a better style treatment for the quote within the teaser view

**Comment by dnkemper** [comment]
- [x] Apply now button in sidebar?
- [x] Remove center alignment on view header in sidebar
- [x] Change major field to be a reference to areas of study
- [x] Add location icon and hometown info to teaser view
- [x] Find a better style treatment for the quote within the teaser view
- [ ] Display hometown + (if US, display state) + if (international, display country)
- [ ] Next/Previous button at bottom of full student nodes
- [ ] Square images for grid - zoom in on image or image style? Might need to add two separate images
- [x] Make grid of images = 9
- [x] Make blockquote (student profile blurb) bigger
