### ISSUE TITLE
Port Drupal 7 APR module to Drupal 8

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#2463]
Remaining issues:

- [x] Get directory introduction to show up
- [x] Add form validation for config page routes and paths
  - Otherwise the returned HTML does not output correctly if routes are bad, conflicting, etc.
- [x] Fix double slashes in sitemap controller output
- [x] Theme everything

**Comment by richardbporter** [comment]
If we want to own this module then we'll probably want to move it alongside our other repos if not just part of uiowa/uiowa.

https://git.uiowa.edu/java/uiowa-apr-d7/
https://git.uiowa.edu/java/uiowa-apr-d7/-/issues/15

**Comment by richardbporter** [comment]
If anyone cannot access the above links, please contact me.

**Comment by richardbporter** [comment]
I've implemented the introduction exactly like the D7 module but its not showing. I must have overlooked something.

**Comment by richardbporter** [comment]
> 've implemented the introduction exactly like the D7 module but its not showing. I must have overlooked something.

This is fixed now.

**Comment by richardbporter** [comment]
@bspeare Just checking with what is left to do with theming. Looks like the grid images and responsive tables. I reached out to AIS re: grid images and the table striping class. I can dig into responsive tables again but was really stuck before break.

**Comment by bspeare** [comment]
@richardbporter we could implement a CSS-based responsive solution for the tables that doesn't have all the bells and whistles of the JS solution.  That would probably get this closer to an MVP.

**Comment by richardbporter** [comment]
I might be on to something re: tables.

**Comment by joewhitsitt** [comment]
Sorry, not sure if this is the issue but saw the notifications come through.

Responsive tables are opt-in here: docroot/themes/custom/uids_base/assets/js/tables.js because we were running into tables that _should not_ be responsive more often than not.

Otherwise there is a table-static option to opt-out: https://uids.brand.uiowa.edu/components/detail/tables.html if it _is_ being applied and not wanted.

**Comment by richardbporter** [comment]
Unfortunately not that simple in this case b/c of how the data is loaded. I'm almost there but for some reason the `table:not(.table--static)'` addition to the selector returns null when it should be getting the element.

**Comment by richardbporter** [comment]
Nevermind. I think it would be best to implement some quick-and-dirty responsive tables CSS. Layering JS on top of JS is messing with the Vue app here. For example, since our tables.js replaces the table element with a div, it breaks the pager functionality.

**Comment by richardbporter** [comment]
I've removed access to the list/grid switcher since the grid display is not in use on D7. AIS said getting the images the same size was going to take some time. Since APR is going away, I think its best to skip that functionality for now.

**Comment by bspeare** [comment]
@richardbporter maybe something simple like https://adrianroselli.com/2020/11/under-engineered-responsive-tables.html would be useful here?

**Comment by richardbporter** [comment]
I gave that a shot but I'm still getting overflow:

<img width="764" alt="Screen Shot 2021-01-05 at 8 47 27 AM" src="https://user-images.githubusercontent.com/1068523/103660308-1047cf00-4f33-11eb-8078-51aab30d1463.png">

**Comment by richardbporter** [comment]
I think I got that working now. Had to move the overflow up to the container.

**Comment by richardbporter** [comment]
@bspeare I'm having trouble with that table scroll box shadow mentioned in the article. Not sure if we need that or not. Also noticed the pager looks odd on mobile:

<img width="466" alt="Screen Shot 2021-01-05 at 10 28 29 AM" src="https://user-images.githubusercontent.com/1068523/103673639-73416200-4f43-11eb-8e6c-b451083f5332.png">

**Comment by bspeare** [comment]
@richardbporter that is weird about the pager.   It must not be getting all the styles from the extending of the `.pager` class.   I can take a look at that if you'd like.

**Comment by richardbporter** [comment]
Yea go for it. I'm tied up in meetings.
