### ISSUE TITLE
Review transportation.uiowa.edu and let them know what may need to be custom development

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#2464]
cost calculator
facilities and mapping
translations

Dagong Wang is the person asking for this. April Wells, Erin Shane and Chik-Lun Woo (Janet) were also in the meeting where this was requested.

**Comment by joewhitsitt** [comment]
cost calculator looks fairly d8/d9 port friendly

**Comment by mjoneill** [comment]
Client reached out yesterday wondering what we've learned.  I told them that this work is likely to be pulled next sprint.

**Comment by joewhitsitt** [comment]
# Transportation Audit

## General Summary

The current transporation.uiowa.edu website makes heavy use of Drupal taxonomy reference system to create relationships between content and to provide alternative paths of navigation. So far in SiteNow v3, theses in-depth relationships functionality is limited and the taxonomies/categorization available by default (tags, research areas, person types) are not meant to work as content/navigation.

## Taxonomies

Though several of the taxonomies on the transportation.uiowa.edu website are used for their term name only in categoriziing content, there are a few taxonmies (e.g. audience, departments, modes of transporation, etc.) that act as content with additional fields. These would most likely be unstrucutred basic pages or custom structured content types in SiteNow v3.

## Content

### Advertisement

Can be replaced by call to actions in v3 or other block types, however, they are currently one-offs and can't be reused through the site.

### Alert

There is a global alerts feature that pairs with hawk alerts, but for page specific alerts, this must be done with alert styling in WYSIWYG or a reference to a particular tag of Articles to recreate what is currently available on transportation. Scheduling/dates is not currently available.

### Committee/Committee Meeting

This can sort of be recreated by using basic page with articles listings and people categorized by tag. transporation.uiowa.edu has committee member types that are not available in the default person types offering.

### Facility

This would have to be done with basic pages currently. General multi-point mapping functionality is on our roadmap, but so far is not scoped to allow data/polygon data to be pulled from an external source like ArcGIS data from facilities.uiowa.edu. Additionally, custom development would be required to recreate the facilities content type to still provide the api feeds of data. Not sure those are being used outside of the site, but you should reach out to stakeholders to confirm before removing these.

`/api/v1/%/facilities.xml`
`/api/v1/%/facilities.json`

### Featured Slider

Though there is not a direct replacement in SiteNow v3, Banner or Slider might work as a replacement.

### Frequently Asked Questions

SiteNow v3 offers one-off Accordions but there is currently no way to reuse existing, tag/filter or display an overall listing like /faq. Reusable bits of content like this is on our roadmap.

There is no search or filtering capabilities for site visitors beyond Google Custom Search.

### News

SiteNow v3 offers the article content type, SiteNow articles configurable listing page, and a block to filter/display news. There is only a Tags taxonomy for filtering. News is generally compatible for automated migration, but some site specific adjustments might need to be made.

### Person

SiteNow v3 offers and is expanding a person content type, SiteNow people configurable listing page and a block to filter/display people. Tags and Person Type exist but the "Administration" person type on transporation.uiowa.edu is not in the default offering of person types. CVs must either be linked to or added to the Biography field.

### Permit

Beyond a basic page or a page-specific block, this functionality does not exist in SiteNow v3. There is also no way to reference basic pages elsewhere on the website but this is on the roadmap.

### Policy

Beyond a basic page or a page-specific block, this functionality does not exist in SiteNow v3. There is also no way to reference basic pages elsewhere on the website but this is on the roadmap. /policy

There is no search or filtering capabilities for site visitors beyond Google Custom Search.

### Rate

Beyond a basic page or a page-specific block, this functionality does not exist in SiteNow v3. There is also no way to reference basic pages elsewhere on the website but this is on the roadmap.

### Webform

SiteNow v3 offers webform functionality, however, there is no migration path possible for these. They would have to be recreated and configured individually.

### Upload File Archive

This functionality does not currently exist in SiteNow v3, but an initial file migration can be done of managed Drupal 7 files.

### Mode of Transportation Calculator

This is custom functionality that would have to be ported to work with SiteNow v3. It doesn't appear to use much Drupal 7 legacy functionality so it shouldn't require too much reworking for Drupal 8/9 if it is still desired.

### Google Translate

SiteNow v3 does not currently offer this out of the box. Site Owners are able to add Google Tag Manager containers which may offer a way to add this same snippet of functionality at no cost.

**Comment by joewhitsitt** [comment]
Can @briand44 or @mjoneill review and pass on to the customer?

**Comment by briand44** [comment]
Shared this feedback with the customer.
