### ISSUE TITLE
IRRC - New People Grouping Display

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#2467]
## Issue

https://iowareadingresearch.org/people - request for new grouping display

The new category we need is: Postdoctoral Research Staff
ALSO change view display of all people views for their page

## Proposed Solution

Same but different: #2287

**Comment by joewhitsitt** [comment]
IRRC requested in addition that all the images related to this view be sized down. Not sure if there is a smaller square image style to choose from in the display settings or additional work would need to be done in the theme (i think it is based off radix which is thankfully node/npm based). Also, with the bootstrap grid, I suspect these images fill the width of the column.

**Comment by dnkemper** [comment]
@joewhitsitt i was going to create a new issue since I already started working on it. Sorry about that! I can just reopen this one though.

**Comment by dnkemper** [comment]
P.S. they do fill the width of the column. The css style I saw that affected the images was the max-width

**Comment by dnkemper** [comment]
@joewhitsitt to not interfere with the archived done column from the last sprint, I'm going to create a new issue and link it to this one so can point it. Hope that's okay!
