### ISSUE TITLE
As an end user, I can view a styled 404 page if my desired page is not found.

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#2478]
# Story

As an end user, I can view a styled 404 page if my desired page is not found.

Do we have any more thoughts on 404 pages? I know at one point this was discussed, but not sure where this left off.

# Proposed solution

As a temporary solution, I have been creating a new page "404" (see [https://americanstudies.prod.drupal.uiowa.edu/404](https://americanstudies.prod.drupal.uiowa.edu/404)). The page has a single section just below the Moderation control section containing a banner block with simple text and a button back to the frontpage of the site. The page title has been hidden by the page setting, and the section containing the body field block has been removed.

Lastly, you can set this new page as the default 404 page under Administration > Configuration > System > Basic site settings under Error Pages.

Do we want to expand on this? There is a lot of discussion about the right way vs wrong way to create and utilize 404 pages out there on the web. Thoughts?

**Comment by joewhitsitt** [comment]
A question I have is what would the behavior be if the default 404 is deleted? Do we need to account for it the same way we did the front page. If the page is deleted, the reference on Basic site settings might confuse webmasters when the value there no longer exists.

Also, is the default 404 not doing what it is supposed to do? All of the links/menu are still available on the page providing multiple paths away from the 404.

**Comment by mark-bennett-uiowa** [comment]
I would guess that the 404 would need to be protected in the same way as the frontpage (as well as any other non-removable pages).

The default 404 page is "working" but its awfully boring:
<img width="1629" alt="Screen Shot 2020-11-05 at 11 59 05 AM" src="https://user-images.githubusercontent.com/3067017/98278669-8beec500-1f5e-11eb-8672-2037d5b415cd.png">

**Comment by richardbporter** [comment]
I'm ok with boring because that equals lightweight and we get a lot of 404s!

**Comment by mark-bennett-uiowa** [comment]
Closing this issue until we decide to do this university wide.
