### ISSUE TITLE
SSL for *.law.uiowa.edu on uiowa

### ISSUE THREAD

**Issue by dnkemper** [uiowa/uiowa#2496]

**Comment by joewhitsitt** [comment]
law.uiowa.edu is on uiowa. this wildcard should probably be on the same application

**Comment by dnkemper** [comment]
@joewhitsitt dang. The blt command told me there wasn't any ssl coverage on any app

**Comment by joewhitsitt** [comment]
there technically isn't, it isn't smart enough to catch relationships like this.

**Comment by dnkemper** [comment]
@joewhitsitt hahaha relatable 🥇

**Comment by joewhitsitt** [comment]
This cert still needs to be created, but instead on uiowa.

**Comment by joewhitsitt** [comment]
this is done.
