### ISSUE TITLE
Areas of Study PDFs

### ISSUE THREAD

**Issue by cory-skeers** [uiowa/uiowa#2500]
# Motivation
As part of #2365, "The area of study pages also have carefully designed PDFs that are generated and used internally by Admissions to provide print copies of this information. (https://admissions.uiowa.edu/at-iowa-print)."

# Story

As an authenticated user on the Admissions site,
I want access to a carefully designed PDF version of Areas of Study
so that I can print well-structured, on-brand copies of information from the website to give to prospective students.

# Example
[Accounting.pdf](https://github.com/uiowa/uiowa/files/5850453/Accounting.pdf)

# Proposed solution

- Explore options for generated PDFs in Drupal 8.
  - https://www.drupal.org/project/pdf_generator
  - https://mpdf.github.io/
  - https://www.drupal.org/project/printable
- Implement the best option as part of the Admissions split.
- Build an access-restricted page or similar option to generate PDFs and/or access pre-generated PDFs
   - If pre-generated prior to access:
     - Is it okay if the files are technically accessible publicly, but hidden behind an access page, or do they need to be locked down?
     - How/when are they re-generated? Content post-save hook, cron, etc.?

**Comment by richardbporter** [comment]
I'd be happy to keep working on PDFs since I'm so deep into it. It would also help validate my decision in #2797 to go further.

I'm confused on the difference between this issue and #2563. Are they duplicates?

**Comment by cory-skeers** [comment]
I think the idea is that by the end of this issue, counselors would be able to get _a_ printed version of the page, and #2563 would be the followup to work with them on customizing it (changing the layout, possibly hiding fields, or adding design elements to make it nicer as a printout). Depending on how flexible things are in getting the PDF working, that layout/customization work could go in here. 

Think this was an example of their current printables (https://github.com/uiowa/uiowa/files/5469293/Accounting.pdf), which looks fairly straightforward, but I'm not sure if there was further customizations wanted beyond that.
