### ISSUE TITLE
Remove collegiate split

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2517]
# Story

As a developer I want to remove the collegiate split to reduce complexity in managing the codebase and considerations for testing.

# Proposed solution

- [x] Investigate how removing Collegiate split from a site like uiowa.edu affects the ability to manage existing pages.
- [x] If necessary based on previous investigation, audit usage of blocks that are available in collegiate split and not in default profile.
- [x] Handle adding limits to main menu block not based on collegiate split: https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/layout_builder_custom/layout_builder_custom.module#L200
- [x] Turn off collegiate split in existing sites
- [x] Remove the `collegiate` directory from `/config/features`

**Comment by pyrello** [comment]
@joewhitsitt Looking at item 3 above, do you think it would work to wrap this in an access check instead of checking for the collegiate profile? We could see if the user had the Administrator role, and if not, restrict the options on the block? I don't think this has any practical effect on existing implementations because it doesn't affect how the data is stored. It would only affect the person ability to make changes.

**Comment by joewhitsitt** [comment]
Admin role access works for me. I know times have changed, but this split check is in place because you wanted it for the collegiate split. https://github.com/uiowa/uiowa/pull/2089#issuecomment-682168172

**Comment by pyrello** [comment]
More than I wanted it, I wasn't ready to fully understand all the implications of what we would be removing. Now what I want is one less place to have to maintain duplicate config updates :)
