### ISSUE TITLE
DCV iowastem.org

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#2522]
BEFORE 11/25

Involves UNI communication. More complicated than a normal DCV process.

**Comment by richardbporter** [comment]
They never replied.

**Comment by joewhitsitt** [comment]
Contacted se.iowastem.org about who to contact for this since our contacts for iowastem.org have not responded.

Contact. 😛

**Comment by joewhitsitt** [comment]
Reached out the the original contacts at UNI based on the information that iowastem office provided.

**Comment by joewhitsitt** [comment]
Calling this done.
<img width="875" alt="Screen Shot 2021-01-11 at 3 00 37 PM" src="https://user-images.githubusercontent.com/4663676/104238171-ca9d7180-541e-11eb-8cac-452a8403f9e2.png">
