### ISSUE TITLE
re-provision electronicmusic.studio.uiowa.edu as a SiteNow v3 site

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#2525]
The customer wants a student to manually migrate content from http://theremin.music.uiowa.edu/ to https://electronicmusic.studio.uiowa.edu. The new site is currently v2 so we will first want to provision this as a v3 site before starting to manually migrate content.

**Comment by dnkemper** [comment]
@briand44 I re-provisioned the site but can you please tell me who the customer is so I can add them as a webmaster?

**Comment by briand44** [comment]
scohenelias is the customer. We will be migrating content so no need to communicate anything.

**Comment by dnkemper** [comment]
@briand44 okay! Thank you for your help!
