### ISSUE TITLE
Image issues with Articles news aggregator block and individual article content

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#2530]
# Problem
The best way to describe this issue is to show it. These are examples from the [https://americanstudies.prod.drupal.uiowa.edu](https://americanstudies.prod.drupal.uiowa.edu) site. The first image is the Articles block news aggregator on the frontpage:
<img width="1361" alt="Screen Shot 2020-11-12 at 3 45 08 PM" src="https://user-images.githubusercontent.com/3067017/99000300-a85ea480-24fe-11eb-8ff2-f8a3d2b686d3.png">
(1) The images are too large (which I heard was being fixed in another PR) and work as if they are feature images.
(2) The entire block is linked, rather than just the title. If a user clicks on the description, they are redirected to the individual article. This is an issue with people, news and events at this point. Not sure if this is intended behavior or not.
(3) The only way to add an image to the article outside of the body field, is to use the feature image field/tab. This results in the following behavior on the individual article page:
<img width="1469" alt="Screen Shot 2020-11-12 at 3 45 58 PM" src="https://user-images.githubusercontent.com/3067017/99000584-202ccf00-24ff-11eb-9dc2-13235a4d0c9d.png">
(4) On the Articles view page, the image shows in the same manner as the front page issue above, rather than the events list does:
<img width="1217" alt="Screen Shot 2020-11-12 at 3 55 01 PM" src="https://user-images.githubusercontent.com/3067017/99000906-99c4bd00-24ff-11eb-86fc-fa03253e7e81.png">
<img width="826" alt="Screen Shot 2020-11-12 at 3 56 37 PM" src="https://user-images.githubusercontent.com/3067017/99000948-ab0dc980-24ff-11eb-9e42-ba3b6826b4ad.png">

# Steps to reproduce
Add a few news articles and add images to these entries under the Feature image field/tab. Events are pulled, so nothing to do here.
Add an Articles aggregator block on a page and display all options.

# Proposed solution
Can we switch this to a smaller, more-square, image with or without that circular border (like events)?
Can we hide the article image on the default display, but keep it in the edit page under an Article image tab rather than feature image tab?

**Comment by joewhitsitt** [comment]
I think this needs to be broken up in to separate tasks.

In terms of "Aggregator" aka RSS Feed, card image options already exist and we are going to be working to extend this to other list blocks shortly: https://github.com/uiowa/uiowa/issues/2351

The card.js whole card link issue has similar issues: https://github.com/uiowa/uiowa/issues/2277 and will probably need to be revisited.

I have heard the use-case for teaser/SEO images for articles but that don't want the large feature on full node. #2711 might be able to help here.

I'd like to update SiteNow People/Articles view pages to allow the same card options as #2351, but that is outside where layout builder styles typically play and the same configuration is used on v2 sites where these card options don't exist. I don't think an issue has been created for that.

**Comment by joewhitsitt** [comment]
1. Image size options for the articles block will be added with #3501
2. The click functionality with the card template has been revisited https://github.com/uiowa/uiowa/issues/2277, https://github.com/uiowa/uids/issues/553
3. Full node featured image display control was added with https://github.com/uiowa/uiowa/pull/2711
4. SiteNow Articles views page has not yet addressed but is working as designed.

I am going to remove the bug label from this and remove from the bug smash milestone. I suggest re-grooming this issue to change the image view mode on SiteNow Articles view page (enhancement). 

>I'd like to update SiteNow People/Articles view pages to allow the same card options as #2351, but that is outside where layout builder styles typically play and the same configuration is used on v2 sites where these card options don't exist. I don't think an issue has been created for that.

Adding card style options to SiteNow Articles view page would be another route but would be a bigger lift based on how it works now.

**Comment by bspeare** [comment]
@mark-bennett-uiowa can this be closed?  It looks like we have fixed this issues based on the ones listed in @joewhitsitt comment above: https://github.com/uiowa/uiowa/issues/2530#issuecomment-934856820.
