### ISSUE TITLE
As a member of the Presidential Search team, I can review updated on-site content per most recent notes

### ISSUE THREAD

**Issue by mjoneill** [uiowa/uiowa#2533]
- [x] About the Position page hidden for launch
- [x] Links to Shared Governance groups from About Iowa
- [x] BoR/Search committee role explanation added to Search Process page
- [x] Link to presidential search "Best practices" doc from Search Process page
- [x] Consent to being contacted checkbox or disclaimer on Feedback form
- [x] Making fields in feedback form optional
- [x] Form comments limited to 500 words
- [x] Populate articles from Iowa Now to avoid the missing content experience for news?
- [x] Add the search committee names
- [x] Link to our search partner in box
- [x] Image in search partner box
- [x] Copy review in search partner box
- [x] Circle thumbnails in This is Iowa box on front page. (All are currently the same)
- [x] Images in news well articles.  
- [x] Balance length of text in Board of Regents vs. Search committee boxes
- [x] Layout Search Process page
- [x] Link to Process Overview is dead on this page: https://presidentialsearch.prod.drupal.uiowa.edu/search-process
- [x] Fix images in news well (again).  I added another article and broke our alternation strategy
- [x] Add GTM and GA
- [ ] Figure out points of contact inside OSC for editorial changes, etc.  "Who should the search committee contact when they need a site change?
- [x] Share copy of unpublished search page with Search Committee
- [x] Head shots of search committee
- [x] QA Site
- [ ] Add redirect for this page once the new search site launches: https://provost.uiowa.edu/ui-presidential-search

**Comment by ABoston88** [comment]
Everything should be addressed aside from:
-Images in articles (I can do this)
-linking to best practices document @mjoneill Were we sent a copy of that? Having trouble tracking it down, now. 

@bspeare If you have time to do one last styling look at About Iowa and Search Process, that'd be great. If not, no big deal.

**Comment by mjoneill** [comment]
@aboston88 yes, we were emailed a link to the best practices doc

**Comment by mjoneill** [comment]
@ABoston88 forwarded the email referenced above ^^^

**Comment by mjoneill** [comment]
<img width="1350" alt="image" src="https://user-images.githubusercontent.com/7144234/99454100-8ba1e280-28eb-11eb-9b48-2d5f040c74d7.png">

@ABoston88 these links on home page don't seem done.  Submit a Resume has to be nuked for now.

**Comment by mjoneill** [comment]
About the position link in the home page banner goes to an unpublished page. 

<img width="672" alt="image" src="https://user-images.githubusercontent.com/7144234/99454272-d02d7e00-28eb-11eb-91f9-239be6873e53.png">

@ABoston88

**Comment by mjoneill** [comment]
How to participate block on home page: 

All links need updating.
* Forums
* Nominations
* Feedback

@ABoston88

**Comment by mjoneill** [comment]
There seem to be some sitenow default pages that are still published.  Can we unpublish/remove those? 

Example: https://presidentialsearch.prod.drupal.uiowa.edu/about

@ABoston88

**Comment by mjoneill** [comment]
It looks like there are no meta descriptions on any pages. 

@ABoston88

**Comment by joewhitsitt** [comment]
@mjoneill can this issue be closed since it was moved to "Done?"

**Comment by mjoneill** [comment]
Yes.
