### ISSUE TITLE
Site Provisions 11/12-11/19

### ISSUE THREAD

**Issue by dnkemper** [uiowa/uiowa#2535]
## Site Provisions 11/12-11/19
* reno.sites.uiowa.edu [PR](https://github.com/uiowa/uiowa/pull/2534)
* afpcc.org.uiowa.edu - **IR2393717** [PR](https://github.com/uiowa/uiowa/pull/2534)

## Re-provisions
* electronicmusic.studio.uiowa.edu #2525 
* centerforconferenceshrandbusiness.prod.drupal.uiowa.edu #2570

**Comment by joewhitsitt** [comment]
old news. closing
