### ISSUE TITLE
IRRC requested to make people view images smaller

### ISSUE THREAD

**Issue by dnkemper** [uiowa/uiowa#2536]
IRRC requested in addition that all the images related to this view be sized down. Not sure if there is a smaller square image style to choose from in the display settings or additional work would need to be done in the theme (i think it is based off radix which is thankfully node/npm based). Also, with the bootstrap grid, I suspect these images fill the width of the column.

_Originally posted by @joewhitsitt in https://github.com/uiowa/uiowa/issues/2467#issuecomment-726811711_

**Comment by joewhitsitt** [comment]
<img width="908" alt="Screen Shot 2020-11-16 at 10 51 59 AM" src="https://user-images.githubusercontent.com/4663676/99282804-cb889d00-27f9-11eb-8421-3b706b527b29.png">

Can you just update the views bootstrap grid settings to be 4 column instead of three?

**Comment by dnkemper** [comment]
Good idea! I'll try that out! Thank you so much!
