### ISSUE TITLE
Create workbench access feature split

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2549]
# Story

As a custom site owner I want the ability to limit editorial access to content based on association with a term or group.

# Proposed solution

Building on the work started in #748, build a feature split to allow for sites to turn on workbench access.

**Comment by joewhitsitt** [comment]
Going to see if I can get this started

**Comment by joewhitsitt** [comment]
@pyrello should this access be on all the content types or specific ones on grad.uiowa.edu?

Depending on the need, this might warrant that next level role or effective management will really be restricted to publisher/editor. If the idea is that webmasters control access, webmasters would have access to assign themselves and other webmasters to any editorial groups.

**Comment by pyrello** [comment]
It looks like this is mainly used for the page content type, although it is present on a few other content types as well on the current GC site.

**Comment by joewhitsitt** [comment]
with https://github.com/uiowa/uiowa/pull/2607 closed @pyrello, can you decide what you want to do with this issue? #748 still exists for dentistry's sake.

**Comment by pyrello** [comment]
I'm fine with closing this, unless we think we might still develop this for other sites. In which case, we could toss it back into the backlog.

**Comment by joewhitsitt** [comment]
#748 has more information and backlinks to the same grad PR so until we decide to actually create the feature split, I am in favor of going back to that investigation issue and marking it for reference.
