### ISSUE TITLE
gis.sites.uiowa.edu - go live

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#255]
- [x] Document the Drupal 8 go-live process along the way ([here](https://wiki.uiowa.edu/display/sitenow/SiteNow+Drupal+8)) which should still be based on our Drupal 7 [pre-golive](https://wiki.uiowa.edu/display/sitenow/Custom+Sites+Pre-Production+Checklist) and [post-golive](https://wiki.uiowa.edu/display/sitenow/Custom+Sites+Production+Go+Live+Checklist).
- [x] sitesgis.prod is ready to go so, create the production domain.
- [x] deprovision standard site uiowa.edu/gis and set up redirect pointing to gis.sites
- [x] ensure https://github.com/uiowa/uiowa/commit/60018203b958de00e6535741e549c32348f0892a is in PROD
- [x] clean up spreadsheet and update to start tracking the status of sites.
- [x] update its.uiowa.edu/esri content to point to new site.
- [x] request cname from hostmaster pointing to acquia dlb.
- [x] setup ssl coverage on uiowa.
- [x] generate sitemap (this might actually be done automatically...)
- [x] fix content accessibility issues: incorrect headings on technical advisory committee page

**Comment by ethanstjohn** [comment]
Need SSL on uiowa.

**Comment by ethanstjohn** [comment]
I don't see what is wrong with the accessibility/ incorrect headings on the technical advisory page.

**Comment by ethanstjohn** [comment]
I'm not sure where the spreadsheet is to clean up either.

**Comment by joewhitsitt** [comment]
They are currently h3 headers after an h1 page title. should be h2s to follow the proper order.

The sub-directory spreadsheet that you have been working on.

**Comment by ethanstjohn** [comment]
Thank you, Joe. I have completed both of those tasks. The excel spreadsheet is located as before on the Microsoft teams folder.
