### ISSUE TITLE
Stacked cards need a bottom margin

### ISSUE THREAD

**Issue by dnkemper** [uiowa/uiowa#2554]
# Problem

When you stack two cards in a column, there isn't a clear separation between the two separate cards
<img width="416" alt="Screen Shot 2020-11-17 at 10 52 03 AM" src="https://user-images.githubusercontent.com/16872949/99420588-01458880-28c3-11eb-8cff-46c3c482a001.png">

# Steps to reproduce

Add a card to a column and then add another card below it - boom

# Proposed solution

Going to add a bottom margin to create some space between them

**Comment by bspeare** [comment]
This is a good idea.   I wonder if we should add a container setting to add/remove margins between blocks?  We could add a default margin for all stacked components within a layout and then create a setting on the container to `remove default component spacing` or something like that.

**Comment by dnkemper** [comment]
@bspeare you are a styling wizard! Thank you!

**Comment by bspeare** [comment]
Closing this in favor of https://github.com/uiowa/uiowa/issues/2554 which is already pointed.
