### ISSUE TITLE
Setup Dispatch for our Drupal 8 service

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#256]
I think we want to have webmasters added to the list, but with the ability to opt-out of dispatch messages, how would be ensure this stays up to date?

**Comment by ethanstjohn** [comment]
We need webmasters on a mailing list. At the bottom of the dispatch message we could insert a link which makes a premade email they can send to us saying they would like to be taken off the list. Then we remove their name from the list and tick a box or equivalent on a spreadsheet so we keep track of their preference.

**Comment by richardbporter** [comment]
D7 SiteNow at least has a ListServ.

**Comment by GaryRidgway** [comment]
I have started work on this and it seems like authentication could be a problem. So far the only real options are basic auth and unauthenticated with OAUTH apparently in the works but not necessarily close to being done. I guess I don't see TOO much of a problem with just passing Hawkid's to data.its but I am hoping to get other opinions before I move forward with anything.

**Comment by GaryRidgway** [comment]
made a branch for this at https://github.com/uiowa/uiowa/tree/i256. You can add it to any site to then access the webmaster api at /api/webmasters/v1?_format=json. There is one problem in that I am unsure of how to set up anonymous viewing for emails as it works when authenticated but not when unauthenticated. 

I hope this makes sense, and I'm sorry it isn't complete, but i wanted to push it before i left for the next week.
