### ISSUE TITLE
Style print/PDF version of Area of Study page.

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2563]
# Story

As an Admissions staff member I want to be able to print (or download a PDF of) a styled version of Areas of Study pages so that they look beautiful when they are sent to a prospective student.

# Proposed solution

Based on the results of #2500, implement some way of outputting specific fields in a specific format for an Area of Study page when viewed as a printable page or PDF.

Todo:

- [x] Remove 'View PDF' link shown for authenticated users at the bottom of AOS pages.
- [x] Get TTF fonts working in PDF.
- ~~Create specific role for access AOS PDFs and listing view.~~
  - Authenticated role has permission. Webmasters can add users with viewer role for most-restrictive access.
- [x] Recreate view of AOS print links without print instructions: https://admissions.uiowa.edu/at-iowa-print
- [x] Set downloaded filename to mail item code field.
- [x] Refactor imported UIDS partials as PDF-local versions to avoid generation failure.
- [x] Create on-brand PDF with an existing template in mind: https://brand.uiowa.edu/template-library

**Comment by cory-skeers** [comment]
Depending on the level of formatting needed, probably would be more involved than is necessary to get it working, but could be worth checking out https://www.latex-project.org/. Predominantly used for formatting academic papers, or print-ready materials that need special formatting like mathematical equations, but it is very useful when formatting PDFs in general.

https://www.drupal.org/project/latex, https://www.drupal.org/project/drutex are two possible modules at least as reference for implementation (very underused), and maybe get an idea of it's worth looking into or a non-starter.

**Comment by richardbporter** [comment]
> Depending on the level of formatting needed, probably would be more involved than is necessary to get it working, but could be worth checking out https://www.latex-project.org/. Predominantly used for formatting academic papers, or print-ready materials that need special formatting like mathematical equations, but it is very useful when formatting PDFs in general.
> 
> https://www.drupal.org/project/latex, https://www.drupal.org/project/drutex are two possible modules at least as reference for implementation (very underused), and maybe get an idea of it's worth looking into or a non-starter.

Thanks but I think we're too deep into dompdf at this point. I also don't know of LateX would run on AC depending on the requirements.
