### ISSUE TITLE
Block arrows don't display with the brain pattern black section background color 

### ISSUE THREAD

**Issue by dnkemper** [uiowa/uiowa#2565]
# Problem

Block arrows don't display with the brain pattern black section background color. 
<img width="1315" alt="Screen Shot 2020-11-18 at 10 33 45 AM" src="https://user-images.githubusercontent.com/16872949/99560022-04a44700-298b-11eb-9afb-78894214aac9.png">

# Steps to reproduce

1. Add a section with the brain pattern black background
2. View the magic

**Comment by bspeare** [comment]
# Proposed Solution

- Add a rule to https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/scss/admin.scss#L931 for `bg--black`, `bg--black--pattern--brain`, and `bg-pattern--brain-black` for `color: $secondary;`. 
- Also need to set:
```
.dropbutton-multiple.open .dropbutton-arrow {
    border-top-color: inherit;
}
```
