### ISSUE TITLE
Card link button isn't visible w/ '- None -' background on a section with a 'brain pattern reverse' background

### ISSUE THREAD

**Issue by dnkemper** [uiowa/uiowa#2566]
# Problem

Card link button isn't visible w/ '- None -' background on a section with a 'brain pattern reverse' background
<img width="916" alt="Screen Shot 2020-11-18 at 10 48 41 AM" src="https://user-images.githubusercontent.com/16872949/99561709-dfb0d380-298c-11eb-86ba-cd562a7aaee3.png">

# Steps to reproduce

1. Add section with a 'brain pattern reverse' background
2. Add a card block with a  '- None' background

# Proposed solution

Button outline is gold -> adapt what the card does when background is '- None - ' and section background is gold

**Comment by bspeare** [comment]
You can also see it here: https://sandbox.prod.drupal.uiowa.edu/cards.

**Comment by bspeare** [comment]
- Add `bg-pattern--brain-reversed` and `bg--gold--pattern--brain` to https://github.com/uiowa/uids/blob/main/src/components/button/button.scss#L108-L118.

**Comment by bspeare** [comment]
I think this was resolved in https://github.com/uiowa/uids/pull/416.  Please reopen if that is not the case!
