### ISSUE TITLE
Section styling fails on main navigation block on non-white/gray background

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#2572]
# Problem
The styles we have been using on cards et al, does not appear to be set on sections where the Main navigation block is used. This only appears to be an issue on non-white/gray backgrounds. For reference, see [https://classics.prod.drupal.uiowa.edu/syllecta](https://classics.prod.drupal.uiowa.edu/syllecta). See screenshots below:
<img width="1590" alt="Screen Shot 2020-11-18 at 2 56 57 PM" src="https://user-images.githubusercontent.com/3067017/99588427-2a901280-29b0-11eb-98f2-4aef3c8cf4a1.png">
<img width="1598" alt="Screen Shot 2020-11-18 at 2 57 39 PM" src="https://user-images.githubusercontent.com/3067017/99588445-3085f380-29b0-11eb-9aac-cda1296d9704.png">
<img width="1591" alt="Screen Shot 2020-11-18 at 2 58 08 PM" src="https://user-images.githubusercontent.com/3067017/99588453-32e84d80-29b0-11eb-8cdf-50e0b134fdda.png">
<img width="1583" alt="Screen Shot 2020-11-18 at 2 59 00 PM" src="https://user-images.githubusercontent.com/3067017/99588468-38459800-29b0-11eb-9606-080162bc3a07.png">

# Steps to reproduce
Create a new section with any width, but give it a colored or patterned background other than white or gray.

# Proposed solution
Carry over accessible and contrasting styles from other widgets to the main navigation block.

**Comment by joewhitsitt** [comment]
https://github.com/uiowa/uids/issues/305

**Comment by joewhitsitt** [comment]
I think this was covered by https://github.com/uiowa/uids/issues/480

Can you confirm @mark-bennett-uiowa

**Comment by mark-bennett-uiowa** [comment]
Tested this using all 16 available background options using the SSW site's [https://socialwork.uiowa.edu/resources/national-nursing-home-social-work-network](https://socialwork.uiowa.edu/resources/national-nursing-home-social-work-network) page. This is now fixed. Closing. Thanks all.
