### ISSUE TITLE
How to display members on City of Iowa City page

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#2574]
They are wanting a list of members to appear at the top of the right sidebar on this page https://www.icgov.org/city-government/boards-commissions-and-committees/ad-hoc-truth-and-reconciliation-commission. An example of this can be seen https://www.icgov.org/city-government/boards/airport-commission.

Customer is Shannon-McMahon@iowa-city.org

**Comment by joewhitsitt** [comment]
I think there is a boards taxonomy that needs to be created of the same name?

**Comment by joewhitsitt** [comment]
@briand44 

The are wanting this on a page which doesn't have this functionality. There is a boards taxonomy (e.g. https://www.icgov.org/city-government/boards/airport-commission) that has this functionality.

They should recreate this page as a board. https://www.icgov.org/admin/structure/taxonomy/boards

<img width="1026" alt="Screen Shot 2020-11-19 at 9 40 18 AM" src="https://user-images.githubusercontent.com/4663676/99688315-4399d180-2a4b-11eb-9671-51afd51eb675.png">

**Comment by briand44** [comment]
@joewhitsitt I shared your feedback and it seems like they are happy with that response. I think we can close this.
