### ISSUE TITLE
Provision a SiteNow v3 site for https://prairierestoration.course.uiowa.edu

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#2578]
https://prairierestoration.course.uiowa.edu is a SiteNow v2 site currently live in production and they would like to begin transitioning to SiteNow v3. So, we will need to provision them a new site to start this manually transition. I believe this is currently on uiowa01. Not sure the process here. Do we provision a new site on uiowa02 or use a different environment?

**Comment by joewhitsitt** [comment]
I thought that we could wipe clean/reinstall in stage and then go live like how a round of custom development would go.

**Comment by briand44** [comment]
Customer is Mike Fallon (michael-fallon@uiowa.edu)

**Comment by joewhitsitt** [comment]
installed (thanks Rick), internal https://courseprairierestoration.stage.drupal.uiowa.edu/ domain created. customer contacted via its-web
