### ISSUE TITLE
Add page/view option per person type (e.g. Faculty, Students pages)

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2587]
# Story

As a site owner I want to display separate pages for different types of people (e.g. a Students page for students) so that visitors can find Faculty and Students more easily.

# Proposed solution

Building upon the existing people view to allow for a contextual filter. Expand the SiteNow People settings to allow for selecting one or more person types to have a separate view/page. Add the ability to set an alias for each.

**Comment by mjoneill** [comment]
Saw this comment in zoom chat.  Adding it here to capture it...

> I’d vote for person type filter on the people view block and an option to display exposed filters on SiteNow People view page (name, person type) As first steps.

**Comment by pyrello** [comment]
Having a separate page is a very common use case, FYI: https://www.google.com/search?q=uiowa+faculty

**Comment by joewhitsitt** [comment]
Relates to https://github.com/uiowa/uiowa/issues/3418 and https://github.com/uiowa/uiowa/issues/3417

**Comment by pyrello** [comment]
I think this can be closed in favor of #2524
