### ISSUE TITLE
Layout containers on layout builder edit screen are not showing appropriate container spacing

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#2591]
# Problem

Since the form container was updated in https://github.com/uiowa/uiowa/pull/2528/commits/bb90f5a051b1038d80a6f81136530a3a991d1e84, it appears that the containers in the layout builder edit screen are not showing the correct spacing. 

<img width="1984" alt="Screen Shot 2020-11-20 at 11 04 30 AM" src="https://user-images.githubusercontent.com/1036433/99828549-b163fd00-2b20-11eb-8431-9cdac8d831fe.png">

# Steps to reproduce

Edit the layout of https://admissions.prod.drupal.uiowa.edu/ and notice the spacing in the screenshot above and the spacing after the page is saved. 

# Proposed solution

Adjust https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/scss/admin.scss#L374-L407.

**Comment by richardbporter** [comment]
I don't understand how bb90f5a caused this. It looks like we need to target `.layout__spacing_container` instead but I don't understand what is adding that class. I started this in #2688.

**Comment by richardbporter** [comment]
I _think_ this should have been renamed as part of https://github.com/uiowa/uiowa/pull/2076 looking at https://github.com/uiowa/uiowa/pull/2076/files#diff-f80656a154856437798ba3ce695b96bfe44275a2a1473c731bfebc04d29945c1R356-R389.
