### ISSUE TITLE
Update Sessionless BigPipe to 2.0.0

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2592]
# Motivation

In preparation for moving to Drupal 9, updating to a compatible version of Sessionless BigPipe is necessary.

# Proposed solution

- [x] `composer require 'drupal/big_pipe_sessionless:^2.0'`
- [x] Testing on dev

**Comment by richardbporter** [comment]
Yes, I'll take a look at this when I can.

**Comment by pyrello** [comment]
Originally implemented in #1296. Can potentially refer to for testing ideas.

**Comment by pyrello** [comment]
It sounds like, from the original PR, that testing this on dev may be of limited use because of the different hardware there vs. prod.

**Comment by joewhitsitt** [comment]
>Configuration tracked in the repository will need to be exported before deployment. To ensure configuration is exported correctly, manually sync a site from production using Drush. Then run database updates and export any configuration changes. Add and commit the config changes and then run another blt dsa to check for any further config discrepancies.

https://github.com/uiowa/uiowa#updating-dependencies

**Comment by pyrello** [comment]
I think that may be a little out of date now that we are using `drupal/core-recommended`.

**Comment by richardbporter** [comment]
Testing criteria:

> So, when using Varnish: the first request will be streamed by BigPipe, and not cached in Varnish. The second request will be a Page Cache hit, not a Varnish hit. The third request and all later requests will be Varnish hits.

**Comment by richardbporter** [comment]
I think this will need to be done simultaneously with D9 as 2.0.0 seems to require Drupal 9: 

```
vagrant@local:/var/www/uiowa$ composer require drupal/big_pipe_sessionless:^2
...
  Problem 1
   ...
    - drupal/big_pipe_sessionless[dev-2.x, 2.0.0] require drupal/core ^9 -> found drupal/core[9.0.0-alpha1, ..., 9.2.x-dev] but it conflicts with your root composer.json require (^8.9.13).
...
```

**Comment by pyrello** [comment]
Thanks for looking into this!

**Comment by richardbporter** [comment]
Regarding testing:

I think we'll want to do the update (along with D9) on a feature branch and then merge into develop. Once deployed, we'll need to inspect response headers such that it meets the criteria I quoted above.

**Comment by richardbporter** [comment]
Should we rename this issue to be more of "Update to Drupal 9" with subtasks, one of which could be bigpipe 2?

**Comment by pyrello** [comment]
Maybe create a new issue and make this a sub-task?

**Comment by pyrello** [comment]
Also this: https://support.acquia.com/hc/en-us/articles/360045796154-Upgrading-from-BLT-11-to-BLT-12

**Comment by richardbporter** [comment]
This seems to work fine on dev. 👍🏻
