### ISSUE TITLE
Update Component Libraries to 8.x-2.0-beta3

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2593]
# Motivation

In preparation for moving to Drupal 9, updating to a compatible version of Component Libraries is necessary.

# Proposed solution

- [x] `composer require 'drupal/components:^2.0@beta'`
- [x] Test that there are no errors when UIDS component libraries are referenced.

**Comment by joewhitsitt** [comment]
>Configuration tracked in the repository will need to be exported before deployment. To ensure configuration is exported correctly, manually sync a site from production using Drush. Then run database updates and export any configuration changes. Add and commit the config changes and then run another blt dsa to check for any further config discrepancies.

https://github.com/uiowa/uiowa#updating-dependencies

**Comment by pyrello** [comment]
FYI, @ethanstjohn When you are working on an issue like this, it should be placed into the "In progress" column during standup. You can place it in "Parking lot" to queue that up. The "PRs awaiting" category is only meant for PRs that are ready to be tested :)

**Comment by ethanstjohn** [comment]
I understand now, thank you.

**Comment by richardbporter** [comment]
Any reason not to use  2.1.0 of drupal/components?

**Comment by pyrello** [comment]
Nope... this requirement came from #2474, which is probably out-of-date.
