### ISSUE TITLE
Update Imagecache External to 3.0.0

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2595]
# Motivation

In preparation for moving to Drupal 9, updating to a compatible version of Imagecache External is necessary.

# Proposed solution

- [x] `composer require 'drupal/imagecache_external:^3.0'`
- [x] Test that there are no errors when referencing images from an external source.

**Comment by joewhitsitt** [comment]
>Configuration tracked in the repository will need to be exported before deployment. To ensure configuration is exported correctly, manually sync a site from production using Drush. Then run database updates and export any configuration changes. Add and commit the config changes and then run another blt dsa to check for any further config discrepancies.

https://github.com/uiowa/uiowa#updating-dependencies
