### ISSUE TITLE
Update Webform to 6.0.0

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2596]
# Motivation

In preparation for moving to Drupal 9, updating to a compatible version of Webform is necessary.

# Proposed solution

- [x] `composer require 'drupal/webform:^6.0'`
- [x] Test that there are no errors with existing webforms.
- [x] Test webform creation.

**Comment by joewhitsitt** [comment]
>Configuration tracked in the repository will need to be exported before deployment. To ensure configuration is exported correctly, manually sync a site from production using Drush. Then run database updates and export any configuration changes. Add and commit the config changes and then run another blt dsa to check for any further config discrepancies.

https://github.com/uiowa/uiowa#updating-dependencies

**Comment by joewhitsitt** [comment]
@ethanstjohn, historically we have had to save all of the webform configuration pages to get updated configuration. not saying this will be the case this time, but good to check.

**Comment by ethanstjohn** [comment]
Thanks for letting me know

**Comment by joewhitsitt** [comment]
@ethanstjohn target the 6.0.0 release instead of the alpha. https://www.drupal.org/project/webform/releases/6.0.0

**Comment by ethanstjohn** [comment]
Will do

**Comment by joewhitsitt** [comment]
I'd also be curious if https://github.com/uiowa/uiowa/issues/2579 is fixed by this release. 🤞

**Comment by ethanstjohn** [comment]
Currently blocked for me, since I can't blt dsa. Looking/trying solutions to fix.
