### ISSUE TITLE
As a site owner, I want to designate a time zone for my event block in layout builder

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#2597]
# Story

As a site owner, I want to designate a time zone for my event so that users can see a time zone listed next to the event date. 

# Proposed solution

- ?

**Comment by bspeare** [comment]
Related to https://github.com/uiowa/uiowa/issues/2396

**Comment by joewhitsitt** [comment]
This is available via #2396. Renamed to relate to lb event block

**Comment by bspeare** [comment]
Since this is available in the event content type and the plan is to transition the event block to https://github.com/uiowa/uiowa/issues/4765, I think we can close this.
