### ISSUE TITLE
Google Analytics 4 Release

### ISSUE THREAD

**Issue by dnkemper** [uiowa/uiowa#2614]
# Problem

Google Analytics released a new version which now uses a new property ID, beginning with a "G" instead of "UA-". We need to find a way to incorporate change since affecting D8 analytics currently

# Proposed solution

Apply patch that allows updated GA v4 prefix:
https://www.drupal.org/project/google_analytics/issues/3178179

**Comment by joewhitsitt** [comment]
SiteNow Known Issue - https://sitenow.uiowa.edu/known-issues#uiowa-issues-2614

**Comment by mjoneill** [comment]
Wonder if we can work around by recommending clients who want GA4 to remove the GA tag from the D8 admin tool and add a GTM container through which they can deploy GA4.

**Comment by dnkemper** [comment]
Wanted to figure out how to do this... first time for everything? :)

**Comment by dnkemper** [comment]
P.S. Know not part of sprint yet... just wanted to see how to apply patch/if worked etc
