### ISSUE TITLE
Field group is not compatible with person types show/hide field logic

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2619]
# Problem
The code logic that sets person content fields to only display for certain person types doesn't work with Field Groups.

# Steps to reproduce
Add field group to the person content type and add a field that is only shown for one person type to it. View the add content page for the person type and observe that, when the person type in question is not selected, the field group still shows.

# Proposed solution
Create a way to associate the field group with a person type.

**Comment by joewhitsitt** [comment]
Duplicate of https://github.com/uiowa/uiowa/issues/2523?

**Comment by pyrello** [comment]
D'oh.
