### ISSUE TITLE
Add a program config entity

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2622]
# Motivation

There seems to be a use case for a reusable program list similar to what is being created in #2562. This is currently handled in the `person_extended` split via a vocabulary and term reference field. But this approach depends on users entering the departments manually, which introduces the potential for discrepancies between sites.

# Proposed solution

Create a custom config entity called Program and populate entries for it for all the established programs and subprograms.

**Comment by joewhitsitt** [comment]
See if MAUI has a list for these

**Comment by pyrello** [comment]
I updated the title and content to reflect my recent learning about the fact that department isn't the really the correct terminology anymore.

**Comment by pyrello** [comment]
Closing this because I'm not sure it is actually important.
