### ISSUE TITLE
BLT Multithreading

### ISSUE THREAD

**Issue by GaryRidgway** [uiowa/uiowa#263]
It would be nice to have the ability to multithread our own type of 'blt dsa' that essentially would create a thread for each site and sync it down.

**Comment by richardbporter** [comment]
This sounds cool but I really don't want to deviate from what Acquia/BLT recommends. We've been down the "wrapper script" path before and it just ends up biting us later. 

Sites you need to work on can be synced individually with `blt sync --site mysite.iuowa.edu` and `blt dsa` doesn't need to be run all the time. It probably _shouldn't_ be run all the time. We may just need more docs on how/when to use it.
