### ISSUE TITLE
General Field Styles in uids_base

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#2648]
# Story

As a developer I want extend content types with additional fields have have them look okay "out of the box" when rendered in uids_base.

# Proposed solution

- Provide basic styles for core field types when they are placed on article, person content types (e.g. number, telephone, entity reference label, etc.)
- Person phone number looks like it got missed last round.
<img width="320" alt="Screen Shot 2020-12-02 at 4 05 20 PM" src="https://user-images.githubusercontent.com/4663676/100937263-5e8f2b80-34b8-11eb-8af3-6cf595ae098e.png">

**Comment by bspeare** [comment]
@joewhitsitt do you have an sites or content types that you recommend testing this on?

**Comment by joewhitsitt** [comment]
Noticed it while reviewing the Grad Scholar PR. If I was testing it, the idea behind the issue would be to add core field types and their different formatters just to make sure they look okay out of the box. That way when a site does add custom fields to a content type they have the same kind of styling similar to other existing fields in terms of field labels, margins, etc. and won't have to have a separate workspace build just for an additional field.

**Comment by bspeare** [comment]
@joewhitsitt Do you think we should build a kitchen sink page on the sandbox site to test all variations?

**Comment by joewhitsitt** [comment]
Why do you have to ask the tough questions? 😉

I brought this up because I thought the phone field was missed. Looking at another site, I see that it looks fine. I didn't inspect the difference before.

<img width="411" alt="Screen Shot 2020-12-08 at 10 30 55 AM" src="https://user-images.githubusercontent.com/4663676/101512372-8bbc5d80-3940-11eb-847b-60c152ae93d6.png">

By adding every and any field under the sun (sandbox fields) we are saying we support those field types even if they aren't part of the default.

I guess I am more curious why we are so scoped with some of these styles? Can we just rescope a bit to provide basic coverage and then extend on top when the use-case hits?

Sorry, I didn't think this was going to be worked on right away. I thought it would be a clean up thing later on.

**Comment by bspeare** [comment]
@joewhitsitt   I think https://github.com/uiowa/uiowa/pull/2677 just adds a few needed defaults that were missing.  We don't have to go overboard on it.
