### ISSUE TITLE
Changes to Counselors Listing/Map

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#2649]
# Issue

The admissions team came back with a few changes to the counselors map/listing functionality.

# Proposed Solution

- [x] Change views exposed filter - Any - to - All - in territory filter. This probably has to be done programmatically.
- [x] Remove territories except for states, dc, international recruitment from the select list field, export changes. This may result in data loss but the customer is aware.
  - [x] Move international recruitment to the top of the list.
- [x] Remove puerto rico from the map (e.g statesdata geojson)

**Comment by GaryRidgway** [comment]
So I have done some investigation for removing the six necessary territories for checkbox two. After speaking with @joewhitsitt we have determined this issue to be a bit more complex than initially pointed, and so are going to merge checkboxes 1 and 3 with https://github.com/uiowa/uiowa/pull/2700 in and repoint this issue for the second checkbox.

**Comment by joewhitsitt** [comment]
was there any work on this yesterday?

**Comment by cory-skeers** [comment]
Finished up by #2717
