### ISSUE TITLE
Google Analytics 4 support for SiteNow v1 websites

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#2653]
# Issue

My understanding is that new GA properties are forced into GA4 which uses a different ID format. These can't be added using the existing module.

UA will stop receiving data in July 2023

# Proposed Solution

- [x] Update D7 sites to use 7.x-2.7 version of Google Analytics

- ~701~
- ~702~
- ~703~
- ~Clas~
- ~Grad~
- ~Dentistry~
- Signage - not needed?
- Healthcare Signage - not needed?
- Icgov - not needed?

**Comment by pyrello** [comment]
From project board card: Community is currently recommending switching to google_tag module for D7 to indirectly support G- analytic IDs since the google_analytics module is struggling to support it.

**Comment by joewhitsitt** [comment]
Looks like they are working on a 7.x-2.7 version to support it https://www.drupal.org/project/google_analytics/issues/3174214

**Comment by joewhitsitt** [comment]
A new release for this is available! https://www.drupal.org/project/google_analytics/releases/7.x-2.7

We have been getting more requests about this lately based on the recent SiteImprove webinar

**Comment by briand44** [comment]
Closing this as I believe all of the applications that should get this update have been updated.

**Comment by joewhitsitt** [comment]
Woot! Just to understand better, this is still probably a support type issue as most if not all folks don't have GA access on v1 standard/custom correct?

I know that @bewoldt was waiting to do this for a website. We should probably announce this update in demo.

**Comment by briand44** [comment]
I'll check but I would assume most have access.

**Comment by mjoneill** [comment]
> most if not all folks don't have GA access on v1 standard/custom

I'd like to understand this as well.  It seems like I've worked with many v1 partners with GA.

Tangentially related (awareness): This month (this week?) Google will automatically create GA4 accounts for existing UA properties.  This is supposed to happen without user intervention and without having to deploy new tags.

**Comment by briand44** [comment]
So it seems like v1 standard webmasters should have privileges to configure Google Analytics. Custom sites are unlikely to have granted these permissions though since we set GA up for those sites.
