### ISSUE TITLE
As a developer, I can create a new content type without having to add a field template file for the page title

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#2674]
# Story

As a developer, I can create a new content type without having to add a field template file for the page title.

# Proposed solution

- Create one page title template: `docroot/themes/custom/uids_base/templates/field/field--node--title.html.twig`

- Remove these templates:
```
docroot/themes/custom/uids_base/templates/field/field--node--title--area-of-study--default.html.twig
docroot/themes/custom/uids_base/templates/field/field--node--title--page--default.html.twig
docroot/themes/custom/uids_base/templates/field/field--node--title--person--default.html.twig
docroot/themes/custom/uids_base/templates/field/field--node--title--student-profile--default.html.twig
docroot/themes/custom/uids_base/templates/field/paragraphs/field--node--title--article--default.html.twig
```
- Remove `<h1>` from https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/templates/content/page-title.html.twig#L17
- Run a search for other templates used outside of `uids_base`

**Comment by joewhitsitt** [comment]
Other node types
 config/default/node.type.page.yml
 config/default/node.type.person.yml
 config/default/node.type.article.yml
 config/hr.uiowa.edu/node.type.faq.yml
 config/grad.uiowa.edu/node.type.book.yml
 config/brand.uiowa.edu/node.type.lockup.yml
 config/icsa.uiowa.edu/node.type.project.yml
 config/policy.clas.uiowa.edu/node.type.book.yml
 config/features/scholarship/node.type.scholarship.yml
 config/iowasuperfund.uiowa.edu/node.type.publication.yml
 config/iowasuperfund.uiowa.edu/node.type.project_core.yml
 config/iowasuperfund.uiowa.edu/node.type.support_core.yml
 config/features/areas_of_study/node.type.area_of_study.yml
 config/ighn.international.uiowa.edu/node.type.ighn_person.yml
 config/iowasuperfund.uiowa.edu/node.type.research_project.yml
