### ISSUE TITLE
https://intranet.oneit.uiowa.edu/events/calendar not working.

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#2678]

**Comment by joewhitsitt** [comment]
I suspect this just needs otter to be jquery 1.7 (easy peasy), but the question that then comes up is what is needing 1.9 (current)?

What other kind of javascript is custom on this site?

**Comment by joewhitsitt** [comment]
Updated fullcalendar to 1.6.4 on 701-3:

701: 5ef5e6ea226f2d7956505a4c661fe7dd8e04e842
702: c3506859c8fbe7aec33721dabcbb11a3ba9dbc8b
703: df3eeed61e15d4f59b1f17e4e63bec45450cc681

Waiting for deploy. Will check PROD before closing.

**Comment by joewhitsitt** [comment]
<img width="766" alt="Screen Shot 2020-12-21 at 12 13 38 PM" src="https://user-images.githubusercontent.com/4663676/102808467-fa100f80-4385-11eb-82d7-489a40a6d190.png">
