### ISSUE TITLE
Issue with zero duration smart date range field

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2691]
# Problem
Tracking an issue that was filed at https://www.drupal.org/project/smart_date/issues/3187574

# Steps to reproduce
* Add a Smart Date Range field to a content type
* Set "Allowed durations increments" to just one row with the value of 0.
* Set "Default duration" to 0.
* Save the field settings
* Create a piece of content using the content type

# Proposed solution
Wait for update at the linked issue.

**Comment by joewhitsitt** [comment]
Is this still an issue then @pyrello as it relates to https://github.com/uiowa/uiowa/pull/5014?

**Comment by pyrello** [comment]
I don't think it is framed correctly, but it is tracking an issue that is still open and is actually still an issue. Should we ever decide to adopt smart date for other things, we may need to fix it. Currently it only seems to affect Grad College.

**Comment by joewhitsitt** [comment]
Resolved by https://github.com/uiowa/uiowa/pull/7078
