### ISSUE TITLE
Regression? Webmasters are able to configure the Header section within a layout

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#2694]
# Problem

While we have locked out editors/webmasters from adding blocks to the "Header" section, they are able to edit the section and add background colors and container updates. 

<img width="1711" alt="Screen Shot 2020-12-10 at 12 10 03 PM" src="https://user-images.githubusercontent.com/1036433/101812184-a6c5d380-3ae0-11eb-8495-3b4639c469b0.png">

<img width="1731" alt="Screen Shot 2020-12-10 at 11 59 03 AM" src="https://user-images.githubusercontent.com/1036433/101811975-5ea6b100-3ae0-11eb-9621-e26acbe20e6e.png">

# Steps to reproduce
Masquerade as a webmaster and edit a page with a featured image in layout builder and try to edit the "Header" section. 

# Proposed solution
Update section permissions

**Comment by richardbporter** [comment]
Haven't dug deep into this but it all seems vaguely familiar. I think this is related: https://github.com/uiowa/uiowa/pull/2068#issuecomment-701656125

**Comment by richardbporter** [comment]
I guess I'm confused whether webmasters should be allowed to configure the header or not. The conversations in #2068 seemed to indicate yes they should.

If not, #2699 seems to work for newly created pages but not the default content on the default site. I don't know if that means all existing pages will not respect this setting or not.

**Comment by richardbporter** [comment]
Why do these display options exist for headers if they are not supposed to be changed?

**Comment by bspeare** [comment]
@richardbporter I think they exist by default on all one-column sections and this just happens to be the one section that we aren't prepared to allow those style variations.

**Comment by richardbporter** [comment]
I'm going to continue on #2463 until I get to a better stopping point.
