### ISSUE TITLE
Allow <br> and <small> tag in minimal_html format

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#2701]
# Problem
The banner using the `minimal_html` format has brought visibility to the need for adding single line break within the banner text.  

<img width="902" alt="Screen Shot 2020-12-11 at 4 25 03 PM" src="https://user-images.githubusercontent.com/1036433/101960635-7871f200-3bcd-11eb-9570-56ccfc67f6bf.png">

Also, allowing `<small>` tags in `minimal_html` will address https://github.com/uiowa/uids/issues/275. 

# Steps to reproduce
Try adding a `<br>` or `<small>` tag in the `minimal_html` format. 

# Proposed solution
Allow `<br>` and `<small>` tags in the `minimal_html` format.

**Comment by joewhitsitt** [comment]
any reason why we shouldn't match this change to v2?

**Comment by bspeare** [comment]
I don't think so.  Are there extra steps we need to take for that?

**Comment by joewhitsitt** [comment]
export the same config change on a "default" v2 site like hawkeyemarchingband

see https://github.com/uiowa/uiowa/pull/2675/files as an example
