### ISSUE TITLE
Allow Call to action block to use minimal html as an option

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#2710]
# Problem
A few site owners (CLAS, Admissions) have requested the ability to add links or minimal text formatting to the Call to action block. 

# Proposed solution
- [x] Create update hook to update field to (formatted, long) in place of (plain, long) and keep existing data.
  - [x] Update existing data to format as `plain_text` as part of this.
- [x] Allow `minimal_html` and `plain_text` formats. 
- [x] Ensure `plain_text` is the default format for newly created CTAs (with `minimal_html` as a secondary option).
- [x] Update component css (https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/scss/components/cta.scss) and add `.cta__content p { margin: 0;}`

**Comment by cory-skeers** [comment]
Reference to an old update hook from a similar text field change: https://github.com/uiowa/uiowa/blob/6eff817684082a7a101f1a48955c3f26c653a41a/docroot/profiles/custom/sitenow/sitenow.install#L344-L482

**Comment by cory-skeers** [comment]
@bspeare Circling back with another clarifying question on this one--

The goal is to default to `plain_text` in creating a CTA, but to have the option to select `minimal_html` (as opposed to defaulting to `minimal_html` when a user adds a new CTA)?

**Comment by bspeare** [comment]
@cory-skeers Yes, that would be ideal to have the option to switch to `minimal_html` as a secondary option.

**Comment by cory-skeers** [comment]
Perfect, that was what I was thinking. Thanks @bspeare!
