### ISSUE TITLE
Create base MAUI integration with upcoming dates by session display

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2714]
# Story

As a site owner I want to be able to show a version of the Academic Calendar, possibly filtered by event category, so that I can display upcoming events to my visitors.

Example: https://registrar.uiowa.edu/dates-by-session

# Proposed solution

Adapt whatever solution is being used to display the above page to create a similar feature for Drupal 8. Add the ability for the site to set an event category to limit the events displayed to just that category.

**Comment by richardbporter** [comment]
I'll start looking at this.

**Comment by richardbporter** [comment]
I'm wondering if we can treat this issue as a subtask/split from #2184 since I think only the upcoming dates by session view is needed. That might allow us to get it done faster and revisit the rest of the MAUI functionality later.

**Comment by pyrello** [comment]
Sounds good to me.

**Comment by richardbporter** [comment]
I had envisioned using custom blocks for this, maybe similarly to the aggregator block. Is that ok or were you thinking of a "page display" like SiteNow People or something?

**Comment by pyrello** [comment]
I had just imagined a page like SiteNow People, but I'm open to having it be a block.

**Comment by richardbporter** [comment]
The D7 panel panes allow for additional content to be placed before/after the dynamic displays. That was a common request and was why I initially was thinking of using custom block types in D8. If we use custom block types, we'll probably want to use the shared headline field which means we can't provide the block via the module (https://github.com/uiowa/uiowa/pull/2152#issuecomment-708500240). That means we probably have a lot of config to split out into a feature. It may be easier to just turn this on for everyone since there is no harm in doing so. We'd probably want to move the block placement in LB to the "More..." section off-canvas though as there will be quite a few blocks eventually.

The uiowa_maui.module and api/ functions _could_ be ported as-is with D8 replacements for deprecated code although I was thinking a custom service might be more appropriate. Then this issue would just need the dates_by_session pane from uiowa_maui_pane submodule ported to a block.

**Comment by bspeare** [comment]
Would this be a good issue to implement the event list design suggestions from https://github.com/uiowa/uiowa/issues/2727?

**Comment by richardbporter** [comment]
> Would this be a good issue to implement the event list design suggestions from #2727?

Maybe? Is that because they don't have an image and location like other events?

I didn't even think about using events for this but I guess that makes sense.

**Comment by bspeare** [comment]
@richardbporter  It seems like we could implement some of the design suggestions from there to get things started.  Do we have any control over how the dates are rendered?  For instance can we alter the markup of `<div class="uiowa-maui-date">January 15, 2021 - January 27, 2021</div>` ?

**Comment by richardbporter** [comment]
Yea - I'm just getting to that in #2833. We can construct it however we see fit. They (registrar) did want to group "academic dates" happening on the same day and you can see some of that at https://registrar.uiowa.edu/dates-by-session. I don't know if thats problematic or not.

**Comment by richardbporter** [comment]
I think to do the grouping, we'd just need to combine the data into one "event" before theming it up. Should be possible.

**Comment by pyrello** [comment]
FYI, that grouping by date was something that was specifically mentioned for GC stakeholders as something that was important.

**Comment by richardbporter** [comment]
I think I've got a basic theme implementation of the dates working in #2833. @bspeare or anyone If you have time, could you look at that PR and maybe how to approach overriding it in uids_base? I'm going to switch to TD and some other things and get back to this later.

**Comment by bspeare** [comment]
@richardbporter I can take a look.

**Comment by bspeare** [comment]
@richardbporter I updated the template to use the card and badge styles.   Let me know if think that will work for this feature.

**Comment by richardbporter** [comment]
That looks great, thanks. I was thinking we would leave the basic template in the module and then put this uids version in the theme but this works too.

**Comment by richardbporter** [comment]
FYI - I seem to have lost the badge styling locally. Not sure if that was intentional or not. I think it looked good.

**Comment by bspeare** [comment]
@richardbporter It should still be there, I just updated it to use a different card variable.

**Comment by richardbporter** [comment]
Thats weird. I see them while logged in but not while logged out. Do you?

**Comment by bspeare** [comment]
I see that.  I'll look into why the badge library isn't loading.

**Comment by richardbporter** [comment]
That did it. Thought I was going crazy.
