### ISSUE TITLE
LB contextual links don't work after dragging block

### ISSUE THREAD

**Issue by cory-skeers** [uiowa/uiowa#2716]
# Problem
After dragging a block within the layout builder editor, contextual links no longer work until the layout changes have been saved.

# Steps to reproduce
Edit a page layout.
Drag a block into a new section or a new region within the section.
Attempt to edit/move/remove the block using the contextual link.

# Proposed solution
Unsure, but my guess is the contextual link is attempting to load a block based on the section/region in which the block is appearing in the layout preview, but as the layout has not yet been saved, the block does not exist by that reference. Some way that reference chain needs to be retained and/or updated upon dragging. Can maybe look into how the contextual move option works, as that appears to work correctly.

**Comment by richardbporter** [comment]
We should confirm that this is a problem in a standard D9 install to make sure it isn't caused by something else on our platform. If it is, we should open an issue on d.o.

**Comment by joewhitsitt** [comment]
https://simplytest.me/ would be an easy way to test.

**Comment by dnkemper** [comment]
Can't duplicate this bug. Feel like a despicable human being for being bummed, but hey... at least I wasn't crazy? Like Cory said in meeting, must have been fixed... it has been a year!

**Comment by bspeare** [comment]
I think https://www.drupal.org/project/drupal/issues/3160785 partially describes our issue.

**Comment by dnkemper** [comment]
Slightly worried that after talking, I still can't replicate it. I'll do my best 😅

**Comment by bspeare** [comment]
I was able to replicate this on https://simplytest.me/ after creating a layout on a page with:

- Custom text area
- System Breadcrumbs

After adding those to the page, try moving and editing each block.  This could be related to this recent comment: https://www.drupal.org/project/drupal/issues/3160785#comment-14272498.

**Comment by dnkemper** [comment]
Looks like there's a potential patch. FINGERS CROSSED. https://www.drupal.org/project/drupal/issues/3160785#comment-14328285
