### ISSUE TITLE
YouTube oEmbed videos with `www` links will not embed correctly.

### ISSUE THREAD

**Issue by GaryRidgway** [uiowa/uiowa#2720]
# Problem
Recently youtube changed some things that made `www` links for OEmbed not embed correctly. This has the potential for breaking all videos that are currently embedded with `www` links. 

# Steps to reproduce
Try to embed any youtube video with the www link in the URL and it will not work, saying that it `Could not retrieve the oEmbed resource.`

# Proposed solution
Possibly run an update hook on all video assets to replace all  instances of `https://www.youtube.com/watch?v=` with `https://youtu.be/`

**Comment by joewhitsitt** [comment]
D8/9 issue: https://www.drupal.org/project/drupal/issues/3188842
D7 issue: ?
YouTube changelog documenting these recent changes: ?
https://issuetracker.google.com/issues?q=componentid:186600%20status:open

**Comment by joewhitsitt** [comment]
Might be related: https://issuetracker.google.com/issues/176032254

**Comment by briand44** [comment]
icgov.org has experienced conflicting results related to this. Originally they were not able to use the www link from the browser as mentioned above. After changing the endpoint to https and telling them to use the share link format, things worked as expected. A few days later they experienced the issue where the `https://youyu.be/` format would not embed but I was able to get it to embed using the www url format (`https://www.youtube.com/watch?v=CAKVc8BX80U`).

**Comment by joewhitsitt** [comment]
I think as long as they can be successful with one of the many URL patterns, this is a sit-and-wait upstream type issue. Nothing has been changing on our end.

This support article lists the youtube patterns that they can try for D7: https://its.uiowa.edu/support/article/110816
