### ISSUE TITLE
As a site owner, I can place an embedded remote video into the card component

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#2724]
# Story

As a site owner, I can place an embedded remote video into the card component so that the card format can showcase YouTube videos.

<img width="1064" alt="Screen Shot 2020-12-17 at 3 58 12 PM" src="https://user-images.githubusercontent.com/1036433/102548719-aef1b600-4080-11eb-9947-f0e7bd10e1c9.png">

<img width="1369" alt="Screen Shot 2020-12-17 at 3 56 51 PM" src="https://user-images.githubusercontent.com/1036433/102548598-82d63500-4080-11eb-8665-89a439c92125.png">

# Proposed solution

Like the banner block has a "Background" select option, we would create a "Media" option on the card block that would allow users to select an image or video.  

<img width="525" alt="Screen Shot 2021-10-08 at 4 17 37 PM" src="https://user-images.githubusercontent.com/1036433/136625779-d12bc04c-e43d-4624-9e69-1b2e10d6298c.png">

Once the video has been selected, we would hide some of the card formatting options like:

- Remove card image size options and set to large by default. 
- Set image as the default media option (will this need an update hook?)
- Use the banner image issue as reference for what needs to be done: https://github.com/uiowa/uiowa/pull/2545. 

<img width="464" alt="Screen Shot 2020-12-17 at 4 06 11 PM" src="https://user-images.githubusercontent.com/1036433/102549604-02183880-4082-11eb-843c-4a6d99a68273.png">

**Comment by bspeare** [comment]
Closing this for now.  We can reopen if this is requested in the future.

**Comment by joewhitsitt** [comment]
Any idea if card.js will have to be adjusted to handle clicks on this object?

**Comment by bspeare** [comment]
@joewhitsitt I don't think so, tried it out locally and clicks are working fine.

**Comment by briand44** [comment]
This would need the update hook or possibly check if config is set?

**Comment by pyrello** [comment]
I would like to pair on this.

**Comment by briand44** [comment]
Scope this to remote video only, which means it differs a bit from how the banner works.

**Comment by makurj** [comment]
I would like to pair on this.

**Comment by pyrello** [comment]
When media element is present and the type of media is video, then "Image format" should be set to widescreen and be hidden.

**Comment by makurj** [comment]
Adding a video for the first time: If the video is not already added and you click into the block form and then you add the video, it doesn't hide the image format option.

**Comment by makurj** [comment]
Update: It's working as expected. The "image format" option is being hidden when adding a remote video to a card for the first time. It's being displayed as soon as the video is removed. It's visible again when the video is re-added.


https://user-images.githubusercontent.com/52135878/139691450-2fc2aa56-20cc-4d1d-82d5-5f5e11abcc84.mp4


https://user-images.githubusercontent.com/52135878/139691488-2699d2ce-078d-4e2e-a9be-1dc83d3dbec1.mp4

**Comment by makurj** [comment]
Intended behavior for image: if image position is stacked, and circle is image format, image size shows up. Image size doesn’t show up for square and widescreen. If left is selected for position. With left for image position, no matter the image format, image size is always visible. Same with right image position.

Intended behavior for remote video: Image size and image format should not be visible irrespective of image position options.
