### ISSUE TITLE
Replace DevDesktop with another development environment for D7

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#2735]
DD is EOL June 2021

### Initial Probe
- Experiment with Cloud IDE and report back. https://docs.acquia.com/ide/start/

### Proposed additional probe
- Experiment with DrupalVM on D7 knowing that we will need an M1 workaround (but already need one for D9).

**Comment by joewhitsitt** [comment]
:drupal_cry:

**Comment by richardbporter** [comment]
Just noticed that DD does not have PHP 7.4 and 7.3 is EOL later this year.

**Comment by joewhitsitt** [comment]
>Just noticed that DD does not have PHP 7.4 and 7.3 is EOL later this year.

:drupal_cry:

**Comment by richardbporter** [comment]
Cloud IDE thoughts:

- 2 across both orgs does not seem like enough. Unless healthcare isn't planning on using any. Since D7 is maintenance only, 2 for us might work with the support rotation using them. They are app-specific though and can't be shared.
- There is a decent amount of setup time per IDE. Switching apps, setting up keys, etc. Ran into some timeouts here but things seemed to work.
- Not as feature rich as PHPStorm but for D7 that is probably ok.
- Requires code changes to get the site working which probably should not be committed.
  - Requires changing the multisite site settings.php to include a differently named DB inc file - the same as the app: `uiowa701-settings.inc`.
  - Requires changing the sites.php file to route the IDE name to the appropriate multisite.
- Terminal is slow.
- PHP 7.4 is the default and needs to be switched. 

I used an IDE to update both FAQ modules on uiowa701/3. 👍🏻 

Unrelated: PHP 7.4 with D7/Drush was spitting out a lot of errors/warnings.  😬

**Comment by joewhitsitt** [comment]
Based on this and our conversation this morning, I'd vote for D7 DrupalVM using what we know and keeping this in our back pocket for now for M1 computers going forward.

**Comment by richardbporter** [comment]
Why don't we have another person try out a Cloud IDE instead of experimenting with more intensive things like DDev or Lando. I took those off the issue description. I agree that setting up DrupalVM for D7 might be easiest but probing that could give us more info.

Another limitation of Cloud IDE, as far as I know, is that you can really only work with one multisite at a time because there is only one IDE URL: https://docs.acquia.com/ide/faq/#can-i-run-a-multisite-application-on-cloud-ide

Here is some additional information on getting started with Cloud IDEs.
- ACLI is required right now to create an IDE. 
  - https://docs.acquia.com/acquia-cli/install/
- Once installed, you should be able to run through the Cloud IDE docs on getting started.
  - https://docs.acquia.com/ide/
  - One key thing there is switching the PHP version to 7.3 before doing any work: https://docs.acquia.com/ide/#working-with-php
- Once the IDE is up and running, you'll need to set up the multisite of your choice.
  - Changing the multisite settings.php file to include the application-specific database include. This is the same as the app machine name, for example uiowa701-settings.inc. You find this on the IDE with `ls /var/ww/site-php/`. Its an inc file within a directory there named the same as the application.
  - Also add a line to sites.php file such that the temporary IDE URL points to the multisite you are working with. For example, `$sites['lkasjdflasdfl.acquia.whatever'] = 'mysite.uiowa.edu';
  - Don't commit either of these changes, i.e. avoid `git add -A`. If the database change gets committed, bad things will happen.

**Comment by makurj** [comment]
Correction for the last bullet point: It's www in ` ls /var/www/site-php/`

**Comment by richardbporter** [comment]
Lets plan on using Cloud IDE in the short term. We can try something else if it doesn't work.

**Comment by joewhitsitt** [comment]
Cloud IDE no. 2 should be available now per Brian
