### ISSUE TITLE
Sitelinks searchbox not working

### ISSUE THREAD

**Issue by mjoneill** [uiowa/uiowa#2736]
It seems like Google finally implemented the sitelinks search box in Google Search.  Yay! 

The bad news is that the schema doesn't represent the actual URL anymore and needs to change.  

This line in the searchAction:
> "https://uiowa.edu/google-search?search={search_term_string}",

Needs to be 
> "https://uiowa.edu/search?search={search_term_string}",

[Bug]

**Comment by joewhitsitt** [comment]
config/uiowa.edu/metatag.metatag_defaults.front.yml

**Comment by richardbporter** [comment]
it'd be nice to change the duplicate search in the URL querystring parameter to something like terms: https://uiowa.edu/search?terms=foo

**Comment by mjoneill** [comment]
> it'd be nice to change the duplicate search in the URL querystring parameter to something like terms: https://uiowa.edu/search?terms=foo

Not part of my ask, but I like the idea and it appeases my OCD.  If it's easy to do, I'm game.  I'll need to make a change to Google Analytics if we do change the query string so that it continues to capture search terms correctly.
