### ISSUE TITLE
Accessibility Fixes

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#274]
### Problem
A scan returned from FAE identified a couple issues that pertain to the programmatic output of the page.
- [x] [landmark role "region" must be uniquely identifiable.](https://fae.illinois.edu/summary/16b6bc9565d9cd2f/rc/landmarks/rule/landmark17/page/3/)
- [x] [Remove the role attribute on the a[href] element, change the attribute role="region" to an allowed role, or use a different element that represents the semantics of the content. (Skip link, menu links)](https://fae.illinois.edu/summary/16b6bc9565d9cd2f/rc/links/rule/role12/page/1/)

### Proposed Solution
- I believe .layout-sidebar-first and .skip-link-region divs with role="region" need an aria-label. Look on the web for a good label for a sidebar where the content could be different per page.
- I think a.skip-link needs a role change to "link" from "region."

### Test
- Run spot check scans using WAVE and AInspector browser extensions on sites.
- Run a Google Lighthouse audit for accessibility issues.
- FAE is limited to public facing sites, so this issue must be merged and deployed to DEV at least to test. Have someone with access run an FAE scan again to see if the issue is resolved.

**Comment by joewhitsitt** [comment]
https://fae.illinois.edu/summary/16b6bc9565d9cd2f/rc/landmarks/rule/landmark17/page/3/

https://fae.illinois.edu/summary/16b6bc9565d9cd2f/rc/links/rule/role12/page/1/

**Comment by ethanstjohn** [comment]
I am unable to start up a site locally
