### ISSUE TITLE
provision shl.uiowa.edu as a SiteNow v3 site. 

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#2740]
The provision process was started for this quite awhile back but got put on hold waiting some domain clarification. I'm assuming that was SiteNow v2.

This domain is probably covered already on one of our applications.

**Comment by dnkemper** [comment]
Looked in uiowa, uiowa01 and uiowa02 prod and stage environments and can't find an existing database or domain for this site. Messaged Brian, and he will take a look later to verify or correct me.

**Comment by briand44** [comment]
It is very likely I misinterpreted the notes on this. There was already a site request submitted but it may not have been started. Also, there is a *.shl.uiowa.edu covered on uiowa01 but we still need to cover shl.uiowa.edu.

**Comment by dnkemper** [comment]
Thank you for helping clarify that for me! [Provisioned](https://github.com/uiowa/uiowa/pull/2745) on uiowa01. [Created SSL cert ](#2744 ).

**Comment by briand44** [comment]
Site has been provisioned and delivered.
