### ISSUE TITLE
As a site owner, I can create an Area of Study page that has all of the defined fields

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#2741]
# Story

As a site owner, I can create an Area of Study page that has all of the defined fields

# Proposed solution

- [x] Subtitle - Text (formatted, long, with summary)
- [x] Intro - Text (formatted, long, with summary)
- [x] Why Iowa - Text (formatted, long, with summary)
- [x] Admission Requirements - Text (formatted, long, with summary)
- [x] Create Admission Requirements content type (Title Field and Body - Text (formatted, long, with summary))
- [x] Admission Requirements - reference field to "Admissions Requirements" content type (limit to 3)
- [x] Careers and Outcomes - Text (formatted, long, with summary)
- [x] Student Opportunities - Text (formatted, long, with summary)
- [x] Stories - Multi-value paragraph field with an image field that also accepts remote video: https://github.com/uiowa/uiowa/issues/2724
  - Use same fields and formats as card block 
- [x] Related Links - multi-value link field?
- [x] Program types

**Comment by joewhitsitt** [comment]
> Multi-value paragraph field with an image field that also accepts remote video: #2724
Use same fields and formats as card block

I see the referenced issue, but it seems to relate to the lb block, not this proposed paragraph bundle. I missed the discussion on this piece and I am hoping to get more clarity as to what is expected here.

**Comment by bspeare** [comment]
@joewhitsitt I don't think https://github.com/uiowa/uiowa/issues/2724 needs to happen before this.  The card styles will work with an embedded video if you want to move forward with building a paragraph bundle with a field that also accepts images/remove video.

**Comment by joewhitsitt** [comment]
@pyrello or @bspeare There is an existing body field (Description) on the area of study content type. Does Admissions need a separate “Intro” field or should I use the body field?

**Comment by pyrello** [comment]
In the D7 content type, the Intro is the body field.
