### ISSUE TITLE
Identify Coronavirus site pages still using V2 Paragraphs

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2742]
# Motivation

As a first step to preparing the Coronavirus site for an update to move it to a standard V3 site, we need to identify all pages that are currently using V2 Paragraph elements.

# Proposed solution

Visit all page content on the site and see whether it uses Paragraphs and add it to a list of all these pages.

**Comment by ethanstjohn** [comment]
Here are the pages and sections using v2 paragraphs.

[Coronavirus pages using V2 paragraphs.pdf](https://github.com/uiowa/uiowa/files/5767302/Coronavirus.pages.using.V2.paragraphs.pdf)

**Comment by joewhitsitt** [comment]
@ethanstjohn thanks for this list. @mjoneill who should this document go to now?

**Comment by mjoneill** [comment]
Next steps: discuss how to proceed, schedule convo with clients, review work completed.

**Comment by joewhitsitt** [comment]
Going to spot check this.

**Update** without visiting every page, this looks pretty accurate and it appears when new pages are created, they aren't creating new paragraphs content.

**Comment by joewhitsitt** [comment]
Keeping open until we have our meeting with the Coronavirus website manager.

**Comment by joewhitsitt** [comment]
Met with Haley from the Coronavirus website and passed along the list. They will work on this list as they have time and they will reach out if they have questions about v3 equivalent blocks to use, etc.. No timeline has been set.

**Comment by mjoneill** [comment]
I will check in with Hayley in a week to see how it's going, with the hope that she builds some amount of comfort working with the new ~~components~~blocks.

I have a calendar reminder.

Let me know if the pace/timeline is not tenable or causes pain.
