### ISSUE TITLE
What to do with sitemap documentation

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#275]
https://docs.sitenow.uiowa.edu/seo/

Currently the sitemap section is pretty sparse. We should suggest that folks take their sitemap and create a Google search console property with it like we used to do with Drupal 7 sites.

**Comment by ethanstjohn** [comment]
I added some documentation, I'm not happy with it. I'll look further into how this works.

**Comment by ethanstjohn** [comment]
I'm not sure what else could be added to this. I referenced what you suggested.

**Comment by joewhitsitt** [comment]
i made it better.
