### ISSUE TITLE
As an Admissions content editor, I can embed things in the WYSIWYG without them being stripped out.

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#2750]
# Story

As an Admissions content editor, I can embed things in the WYSIWYG without them being stripped out.

[OnceHub](https://www.oncehub.com/) was one example that was given but the overall request was to be able to use full html because there are other instances of html being stripped out of the WYSIWYG and it is expected that the list will continue to grow. Admissions content folks currently can do this on their existing site and would like to be able to continue doing this and want to avoid long delays each time a new request comes in.

# Proposed solution

**Comment by joewhitsitt** [comment]
Admissions shared a doc with the following embed providers:

Update: Top 3 are higher priority than video stuff.

- ScheduleOnce (oncehub)
- Net price calculator - https://admissions.prod.drupal.uiowa.edu/finances/net-price-calculator - admissions.uiowa.edu/npc
- Google Maps
- UI Capture
- Video option that isn't blocked in China (YouTube and UI Capture are blocked) - Kaltura/Mediaspace?

**Comment by briand44** [comment]
https://iowa-my.sharepoint.com/:w:/g/personal/katmills_uiowa_edu/Ea2Pp75OZIVDh5PVo4pt0W0BCClNhh87XVFDSN_lBeZkLA?e=4P5mNb

**Comment by briand44** [comment]
I embedded the map on https://admissions.prod.drupal.uiowa.edu/visit-campus/parking-guide and have embedded the net price calculator on https://admissions.prod.drupal.uiowa.edu/finances/net-price-calculator

**Comment by briand44** [comment]
To Do: 
Create pages and embed html video player on the new site from existing pages outlined in https://iowa-my.sharepoint.com/:w:/g/personal/katmills_uiowa_edu/Ea2Pp75OZIVDh5PVo4pt0W0BCClNhh87XVFDSN_lBeZkLA?e=4P5mNb. Looks like there are about six pages.

Embed Once Hub scripts. Some scripts are outlined in the file linked above as well but it is not clear at this point which pages on the new site need this.

**Comment by cory-skeers** [comment]
From Slack:

 > I see the OnceHub embed on the following five pages of the admissions site.  Are there more?

```
https://admissions.uiowa.edu/apply/international-application-process
https://admissions.uiowa.edu/future-students/international-students
https://admissions.uiowa.edu/visit-campus/meet-admission-counselors-and-academic-departments
https://admissions.uiowa.edu/international/international-first-year-student-admission
https://admissions.uiowa.edu/future-students/international-transfer-student-admission
```

> That probably covers it, but where they go on the new site might be different than where they are currently.
> This one will be a stand-alone (new page on new site):
```
https://admissions.uiowa.edu/visit-campus/meet-admission-counselors-and-academic-departments
```
> The others are for international-specific pages. They are in a sidebar, so replicating them might be different on the new site because that page may not exist, or may be structured in a different way that doesn't allow for a sidebar/OnceHub button.

> Gotcha.  We’ll need to know what pages we need the OnceHub embed on so we can place them. Is that something you [Scott Fiddelke] or Katelyn Mills-Erickson can provide in the upcoming days?

> For now the page listed above is the most important (https://admissions.uiowa.edu/visit-campus/meet-admission-counselors-and-academic-departments). It has 2 embed (first year and transfer). I think we can probably figure out a way to do the international ones with a button/link in the interim, but this does show the flexibility we want/need with these embeds. (Just rebuild that same page with the embed at the same path on the new site.)

**Comment by cory-skeers** [comment]
Video embed updates:
https://admissions.uiowa.edu/future-students/international-students/about-iowa/international-experience -> https://admissions.prod.drupal.uiowa.edu/node/3961/latest

https://admissions.uiowa.edu/international-students/about-iowa/you-are-welcome-here -> https://admissions.prod.drupal.uiowa.edu/you-are-welcome-here

https://admissions.uiowa.edu/connecting-iowa-world -> https://admissions.prod.drupal.uiowa.edu/connecting-iowa-world

https://admissions.uiowa.edu/international-students/about-iowa/campus-tour -> https://admissions.prod.drupal.uiowa.edu/university-iowa-campus-tour

https://admissions.prod.drupal.uiowa.edu/next-step-iowa-international-presentations -> https://admissions.prod.drupal.uiowa.edu/next-step-iowa-international-presentations

https://admissions.uiowa.edu/international-students/about-iowa/international-io -> https://admissions.prod.drupal.uiowa.edu/international-iowa-overview

**Comment by cory-skeers** [comment]
OnceHub scheduling embeds:
https://admissions.uiowa.edu/visit-campus/meet-admission-counselors-and-academic-departments -> (existing) https://admissions.prod.drupal.uiowa.edu/visit-campus/meet-admission-counselors-and-academic-departments

**Comment by cory-skeers** [comment]
There may be additional updates needed, or further OnceHub embeds, but at this time all the listed embeds have been created on the prod site.
