### ISSUE TITLE
Scholarship displaying all content while collapsed.

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#2754]
# Problem
The Collegiate and Departmental Scholarships scholarship is displaying all of the content in the accordion while collapsed.

# Steps to reproduce
https://admissions.prod.drupal.uiowa.edu/first-year-resident-scholarships

![Screen Shot 2020-12-23 at 1 45 12 PM](https://user-images.githubusercontent.com/1017022/103032205-1e562280-4525-11eb-9ac4-274f64b017c0.png)

# Proposed solution

**Comment by joewhitsitt** [comment]
This is technically working as they requested. Did they change their minds? Scott said they don't usually put much into this field and is supposed to act as a teaser to reduce clicks.

**Comment by briand44** [comment]
Would using the additional information for the bulleted items be a work around in this case?

**Comment by joewhitsitt** [comment]
Yes, only the contents of Description are used in the "teaser"

**Comment by briand44** [comment]
I updated the content and moved the bulleted items to the additional information field.
