### ISSUE TITLE
Add back to top link button functionality

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2755]
# Story

As a site visitor I want be able to have an easy way to get back to the top of the page on long pages so that I don't have to manually scroll back up on long pages.

This feature is being requested in the context of building the Grad College Manual of Rules and Regulations section, which will have some very long pages and a set of anchor links at the start. Having a back to top button will be important for people being able to find their way around.

# Proposed solution

Add a javascript to detect when the user has scrolled down the page a certain distance and will trigger an otherwise hidden element to be shown that, when clicked, move user back to the top of the page.

**Comment by joewhitsitt** [comment]
Maybe https://github.com/uiowa/uiowa/issues/587 can close and be replaced by this if it is to be in uids_base and not just for grad

**Comment by joewhitsitt** [comment]
Here is the old stuff: https://github.com/uiowa/uiowa/pull/640

**Comment by joewhitsitt** [comment]
Comment from standup:
>Without looking at it, page options sounds like a good place for page-by-page control. Not sure how this scales for other content types (article, person) as well as site-specific content types

Does this bring into question whether we want content by content override or should we stick with a global setting and just display the button after certain amount of scrolling?

**Comment by bspeare** [comment]
Do we need new `JS` for this or can we just use the `scroll-down` body class provided by the Iowa Bar (https://github.com/uiowa/uids/blob/main/src/components/branding/iowa-bar/iowa-bar.js) to hide/show the arrow and use https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior for the smooth scroll behavior?

**Comment by bspeare** [comment]
For the styling, we have a back to top link on https://viewbook.admissions.uiowa.edu/ that would be appropriate for this:

<img width="1745" alt="Screen Shot 2021-01-14 at 10 07 38 AM" src="https://user-images.githubusercontent.com/1036433/104616872-6d890200-5650-11eb-8fda-d0622daee039.png">

The css is at https://github.com/uiowa/uids/blob/main/src/components/menus/vertical-dots/vertical-dots.scss. 

Not sure if we need the animated "Back to top" text.

**Comment by dnkemper** [comment]
Thank you so so much, @bspeare! I'll redo some things and apply your recommendations!

**Comment by briand44** [comment]
off by default, only show after scrolling down page

**Comment by cory-skeers** [comment]
Was curious about this, and pulled up https://www.nngroup.com/articles/back-to-top/. Haven't gone through it all myself, so not sure how useful, but may be a good resource to check out.

**Comment by dnkemper** [comment]
awesome! Thank you, @cory-skeers! Will definitely check that out!
