### ISSUE TITLE
Move US States Allowed Values Function to be shared

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#2764]
# Story

As a developer, I can make use of a shared list of US States with the ability to alter it to add/remove options without recreating the wheel each time.

# Proposed solution

Move admissions_core_state_options function in [admissions_core](https://github.com/uiowa/uiowa/blob/9472ebe354cc7b50f9158a90eb11e15025cacc3a/docroot/sites/admissions.uiowa.edu/modules/admissions_core/admissions_core.module#L1074-L1132) to uiowa_core module, rename it to something like uiowa_core_state_options, and add an alter similar to [sitenow paragraphs](https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/sitenow_paragraphs/sitenow_paragraphs.module#L336) that allows [modification](https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/sitenow_articles/sitenow_articles.module#L268). Update the fields that currently use admissions_core_state_options to instead pull from uiowa_core (name change in config files).

IISC recently added a similar Iowa counties options function to uiowa_core.

An update hook in uiowa_core or sitenow to flush caches might be needed for a clean deployment. There are examples of these types of updates already in those .install files.

**Comment by makurj** [comment]
I'd like to work/pair on this.

**Comment by briand44** [comment]
may need cache rebuild update hook on deployment?

**Comment by makurj** [comment]
Not clear on the "modification" (https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/sitenow_articles/sitenow_articles.module#L268) requested.

**Comment by joewhitsitt** [comment]
Looks like the line numbers changed. https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/sitenow_articles/sitenow_articles.module#L345
