### ISSUE TITLE
Set consistent page title size for featured images

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#2775]
# Problem
With https://github.com/uiowa/uiowa/pull/2711 the ability to adjust the banner size of the featured image also adjusts the size of the page title based on the selection.

# Steps to reproduce

Large example:

<img width="1614" alt="Screen Shot 2021-01-04 at 6 37 35 AM" src="https://user-images.githubusercontent.com/1036433/103536225-baeabf80-4e57-11eb-99a1-12555cac3c6e.png">

Medium example:

<img width="1596" alt="Screen Shot 2021-01-04 at 6 37 15 AM" src="https://user-images.githubusercontent.com/1036433/103536242-c4742780-4e57-11eb-8d6a-de7773772096.png">

# Proposed solution
Adjust https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/scss/components/banner.scss#L139-L146 to be scoped to the `layout--title` in addition to the current rule.

**Comment by joewhitsitt** [comment]
This is done right @bspeare?

**Comment by bspeare** [comment]
@joewhitsitt yes, thanks!
