### ISSUE TITLE
Article featured image display setting text appears if set to anything other than the default

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#2780]
# Problem
The Article content type featured image is displaying banner image size display setting field text on the page. 

# Steps to reproduce
Add a new article with a custom large or medium featured image and verify that there is display text below the page title.

<img width="1735" alt="Screen Shot 2021-01-04 at 9 54 09 AM" src="https://user-images.githubusercontent.com/1036433/103553450-14141c80-4e73-11eb-92f8-2529d36c22aa.png">

<img width="610" alt="Screen Shot 2021-01-04 at 9 55 02 AM" src="https://user-images.githubusercontent.com/1036433/103553472-1b3b2a80-4e73-11eb-8c10-c5dd6da9d092.png">

# Proposed solution
Adjust layout builder template for article to remove this field. 

<img width="1720" alt="Screen Shot 2021-01-04 at 9 53 45 AM" src="https://user-images.githubusercontent.com/1036433/103553482-1eceb180-4e73-11eb-9f93-1c75fd28e421.png">

**Comment by joewhitsitt** [comment]
Do you think this needs to be a hotfix or can it wait for a later release?

**Comment by bspeare** [comment]
@joewhitsitt I can put up a fix now.
