### ISSUE TITLE
Update housing.uiowa.edu table styles to match dining.uiowa.edu housing styles.

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#2789]
> How can I get the tables on this page https://housing.uiowa.edu/refunds to look like the tables on this page https://dining.uiowa.edu/refunds?

Contact: Jake and Megan

**Comment by joewhitsitt** [comment]
I suspect this theme is using node 7.5 if a nvmrc file is not available.

**Comment by dnkemper** [comment]
And I suspect this is an error I made since I worked on the dining table styles previously. I'll clean up my mess :) 

**by mess I mean I'll apply what I did in dining to housing and hope it compiles correctly haha
