### ISSUE TITLE
Update or pin dev modules to commit hashes to prevent unexpected updates

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2793]
In trying to add a new patch to `drupal/core` in a PR, I kept running into an issue where several modules, including Metatag, were also taking the opportunity to update themselves. Essentially, if we have `-dev` modules, anytime we run `composer update --lock`, this can potentially happen. In the case of Metatag, this was the diff between the two versions: https://git.drupalcode.org/project/metatag/-/compare/c32d6f8...e46ef6b

- [x] "drupal/layout_builder_shortcuts": "1.0.x-dev"
- [x] "drupal/lb_direct_add": "1.x-dev"
- [x] "drupal/media_entity_facebook": "2.x-dev@dev"
- [x] "drupal/media_entity_file_replace": "1.x-dev"
- [x] "drupal/media_entity_instagram": "3.x-dev"
- [x] "drupal/menu_block": "1.x-dev#fbfb8fe"
- [x] "drupal/metatag": "1.x-dev"
- [x] "drupal/redirect": "1.x-dev"
- [x] "kartsims/easysvg": "dev-master"
- [x] "uiowa/block_content_template": "dev-master"

**Comment by joewhitsitt** [comment]
I felt like we did this to speed up initial development (way back when) with the idea that we would pin things once we "launched." I am on-board with this.

**Comment by pyrello** [comment]
FWIW, we should probably add a file with notes about why we are pinned to certain versions, especially if it's a commit hash. I have no idea why we are using dev versions for some of those modules, so not sure if we could move to stable versions now or not.

**Comment by richardbporter** [comment]
Yea probably. Unless we can move to a stable release like you mentioned.

**Comment by richardbporter** [comment]
Here is a quick list as I keep running into this:
```
"drupal/layout_builder_shortcuts": "1.0.x-dev",
"drupal/lb_direct_add": "1.x-dev",
"drupal/media_entity_facebook": "2.x-dev@dev",
"drupal/media_entity_file_replace": "1.x-dev",
"drupal/media_entity_instagram": "3.x-dev",
"drupal/menu_block": "1.x-dev#fbfb8fe",
"drupal/metatag": "1.x-dev",
"drupal/redirect": "1.x-dev",
"kartsims/easysvg": "dev-master",
"uiowa/block_content_template": "dev-master",
```

I left out dev deps. Not as concerned with those.

**Comment by richardbporter** [comment]
menu_block is actually pinned but I think its worth a quick look to see if a stable release is an option.

**Comment by richardbporter** [comment]
Seems like this becoming a common issue and maybe we should jump on it.

**Comment by pyrello** [comment]
I think that `metatag` is taken care of in #2771

**Comment by richardbporter** [comment]
### Proposed solution
Evaluate each dev dependency to see if updating to stable release is viable. If so, update. If not, lock at current SHA. Document why we locked at a specific SHA somewhere.
