### ISSUE TITLE
As a webmaster, I can easily navigate the admin page to successfully configure my site.

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#2795]
# Story

As a webmaster, I can easily navigate the admin page to successfully configure my site.

# Motivation
Our custom modules that have configuration pages are named differently in the admin section. Some are prefixed with SiteNow, UIowa, University of Iowa, etc. They are also all located in the System menu section which seems wrong for things like SiteNow Articles which should probably be under Content Authoring.

<img width="966" alt="Screen Shot 2021-01-06 at 8 52 06 AM" src="https://user-images.githubusercontent.com/1068523/103782252-d5aa6900-4ffc-11eb-91a9-d91d9e733c46.png">

IMO, the average person doesn't need to see a prefix at all and Articles Configuration would be better than SiteNow/UI/Uiowa Articles.

# Proposed solution

Decide on a naming convention and change existing admin menu links for custom modules. Also place custom module menu links in the appropriate menu parent.

This issue does **not** include changing module machine names.

**Comment by joewhitsitt** [comment]
Glad you brought this up. Noticed this yesterday when testing the APR module.

**Comment by richardbporter** [comment]
Example menu parent for SiteNow Articles: https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/sitenow_articles/sitenow_articles.links.menu.yml#L3

**Comment by richardbporter** [comment]
> Example menu parent for SiteNow Articles: https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/sitenow_articles/sitenow_articles.links.menu.yml#L3

Further clarification on this example: I would change the title to just `Articles`, the `description` to `Configuration for article content.` and the `parent` to `system.admin_config_content` so that it appears under `Content authoring` as opposed to `System`.

[
<img width="1222" alt="Screen Shot 2021-09-09 at 1 53 09 PM" src="https://user-images.githubusercontent.com/1068523/132745893-ff9a4af7-5cb6-4885-85f4-a9c0e9b2a50f.png">
](url)

**Comment by richardbporter** [comment]
Also, I think this is a good dev sprint candidate. :)

**Comment by e-marie-w** [comment]
- Some of the custom modules don't have a .links.menu.yml file, I assume that means they aren't a part of the menu?
- Is there a specific site that'd be good to test this on locally, or would any do?
- I was going to follow the example and use 'Configuration for module_name' as the basis for descriptions, unless someone had a better idea. I know some are set up as 'Configure module_name', if we wanted it shorter for some reason.

**Comment by richardbporter** [comment]
> * Some of the custom modules don't have a .links.menu.yml file, I assume that means they aren't a part of the menu?

Yea, those can probably be ignored.

> * Is there a specific site that'd be good to test this on locally, or would any do?

I would use default and then enable feature splits to see if those custom modules have a config page.

> * I was going to follow the example and use 'Configuration for module_name' as the basis for descriptions, unless someone had a better idea. I know some are set up as 'Configure module_name', if we wanted it shorter for some reason.

I was thinking we would omit the module name from the admin pages entirely. From a webmaster perspective, I don't think the module names are valuable and maybe add more confusion in terms of uiowa_ vs. sitenow_. 

I think it'd be nice if the descriptions gave some indication of what the config page is for. For example, SiteNow Articles could say "Customize the display of articles on the site." or something like that.

**Comment by e-marie-w** [comment]
Should I still be general if the module only has one or two settings, or should I then be specific? For example, instead of 'Customize the display settings for pages' should the description be 'Set the default image display size for pages', since that's currently the only option upon clicking (SiteNow) Pages in the admin config menu.

**Comment by joewhitsitt** [comment]
I'd vote more general than not. We may add additional settings to these in the future.

I haven't tested the PR yet, but something to check is if the URL paths changes with these moves. I know we have documentation and reference the relative URL for these pages.

**Comment by e-marie-w** [comment]
Okay awesome, I'll use general descriptions and check those URL paths.

**Comment by e-marie-w** [comment]
I moved `Articles`, `Events`, `Pages`, and `People` into the `Content Authoring` section and left `DCV`, `Dispatch`, `Migrate`, `Alerts`, `APR Integration`, `Core Settings`, `Entities`, `Profiles Directory`, and `Search` in `Settings` for now.

`Alerts` lets you create custom alerts so I'm wondering if it should be moved to `Content Authoring` or stay in `System`. I'll probably have the same question for APR and Directory Profiles, but I haven't enabled those yet so I'm not sure of the options.

The admin config menu on a site does have other section options like `Development`, `User Interface`, `Search and metadata`, etc. Do we want to use any of those and if so where would I find the names to use to set them as the `parent`? I'm thinking we could put the `Search` module in the `Search and metadata` section at the very least. `Migrate` might fit under `Development`, I'm not sure (haven't enabled that module yet either).

Oh, also, regarding the URLs: as far as I can tell this only changes the title of the module on that admin config page. I can click on the re-named `Events` option under `Content Authoring` on the menu page and then the settings page it takes me to is still called SiteNow Events with the same .../system/sitenow-events URL. 

...Do we want more than just the names on the menu page changed right now?

**Comment by richardbporter** [comment]
The `system.links.menu.yml` file defines those admin sections. You can open that file locally and see each one - `system.admin_config_search` is the search and metadata one.

>I'm thinking we could put the Search module in the Search and metadata section at the very least. Migrate might fit under Development, I'm not sure (haven't enabled that module yet either).

Yes and yes.

**Comment by e-marie-w** [comment]
Thanks for the file name, that helped a ton! Also Sean went over how to do feature splits with me so I've successfully turned on the Migrate one and checked that it is in fact under Development now. I also turned on APR Integration and the Profiles Directory, which didn't need title or description changes but I'm wondering if we should move from System to Content Authoring or Development?

I'm still a little confused on if these minor changes affect the feature splits so I'm going to talk to Sean again before I push anything. In the meantime now that I know how to turn stuff on I can double-check if those modules without a `/.links.menu.yml` are showing up in the menu or not.

**Comment by bspeare** [comment]
@richardbporter Thanks for pointing out this issue.   I know you've put a lot of work into this already but I guess I would rather see these items move to a separate "SiteNow" category so users don't have to scan each category looking for the feature they want to configure.  There is a simplicity to just having the "SiteNow Articles", etc listed in one scannable chunk.  For instance, does a webmaster know that the "Web Services" category is where feeds are configured?  Wouldn't that be easier to find in a SiteNow category list under the name "SiteNow Feeds"?  :) 

If there was a SiteNow category section, could we also potentially list features that aren't turned on?  Like "SiteNow Collections" so that current and future features are discoverable as they are added in?

**Comment by e-marie-w** [comment]
Okay I lied I did push since I had already pushed changes to those modules yesterday so if I need to make changes I need to make changes regardless of anything done today.

There were 3 modules without a menu link file that I could turn on and check weren't appearing in the admin config menu. That leaves 9 other custom modules without a menu link or ability to turn on and check, I'm going to assume they work like the previous 3 and can just be ignored.

I can go back to the SIteNow names if that's what we want. Pretty sure I can add a new category heading too!

**Comment by richardbporter** [comment]
> @richardbporter Thanks for pointing out this issue. I know you've put a lot of work into this already but I guess I would rather see these items move to a separate "SiteNow" category so users don't have to scan each category looking for the feature they want to configure. There is a simplicity to just having the "SiteNow Articles", etc listed in one scannable chunk. For instance, does a webmaster know that the "Web Services" category is where feeds are configured? Wouldn't that be easier to find in a SiteNow category list under the name "SiteNow Feeds"? :)

Good point. No, they won't know that, at least not initially. But by extension, why have categories at all then? 

> If there was a SiteNow category section, could we also potentially list features that aren't turned on? Like "SiteNow Collections" so that current and future features are discoverable as they are added in?

Not based on how the the menu links YAML files work. They live in each module and aren't active until the module is enabled. IDK if there some other way of doing it though.

**Comment by richardbporter** [comment]
> For instance, does a webmaster know that the "Web Services" category is where feeds are configured? Wouldn't that be easier to find in a SiteNow category list under the name "SiteNow Feeds"? :)

Oh that one is provided by core which is why its under Web Services. We could have altered but its not really a SiteNow/UIowa thing.

Maybe step one is decide on naming things SiteNow vs. UIowa because I don't see how two naming conventions helps people.

**Comment by joewhitsitt** [comment]
Based on what a webmaster can see, I don't think that scanning the established "content authoring" and "system" categories is all that bad. It also helps distribute the page evenly.

Of all people, I could get behind a "SiteNow" or "University of Iowa" category but our module names are pretty mixed and it would be one long column after more things are turned on.

**Comment by e-marie-w** [comment]
I'm fine with either option, I just agree we shouldn't keep both SiteNow and UIowa because it is really confusing. 

Also I'm out from 1-2, so if you have a huddle/zoom and come to a decision during that time just let me know somewhere.

**Comment by bspeare** [comment]
A "SiteNow" or "University of Iowa" category could be useful.  Removing categories might help too.   At least if it is very long list, users would know to scroll through it vs if "Search" is under Search and Metadata it might appear as a category buried at the bottom of the page.   Perhaps we could also add a class to "SiteNow" or "UIowa" modules to add a icon or gold background or something to highlight them more.    

And maybe a link to "View all SiteNow features" that takes the user to a list on the docs site?

**Comment by bspeare** [comment]
> Oh that one is provided by core which is why its under Web Services. We could have altered but its not really a SiteNow/UIowa thing.
> 
That makes sense, but it might be useful to rename this one if we want it to be more accessible to the average user if we are taking the time to make some optimizations for admin UX.

**Comment by bspeare** [comment]
Or we could focus on switching admin themes that have a slightly better design like https://miro.medium.com/max/4800/1*_E7ROXHkuZqZImPnoGmtLQ.png

**Comment by e-marie-w** [comment]
So what I'm getting is that we want to keep SiteNow (or UIowa) in front of the module names, but we still need to decide if we want them to be their own category or mixed in existing categories or drop categories all together. 

I'll get started on adding SiteNow back in front of the SiteNow and UIowa modules. Unsure if the category thing is something we want to discuss as an entire team or if we can just hash it out here.

**Comment by bspeare** [comment]
@e-marie-w I don't think that has been decided yet, it might be a useful thing to discuss as a group.

**Comment by bspeare** [comment]
Just took a look at the latest update and the new category looks great!

- Is it possible to move the SiteNow category so that it appears first?
- Can we move "Basic site settings" to the SiteNow category? I know this core but it is a pretty key part of a SiteNow website. 
- Are we able to move "Aggregator" to the SiteNow category?

<img width="1685" alt="Screen Shot 2021-09-16 at 3 41 44 PM" src="https://user-images.githubusercontent.com/1036433/133682892-53472126-799b-4efb-938d-5735afe040cd.png">

**Comment by joewhitsitt** [comment]
I think this is where I differ. I don't think we should be moving links of other modules. We would be talking about route subscribers to alter these.

Is that the webmaster view above? Is Layout Builder Direct Add supposed to be showing to webmasters?

**Comment by bspeare** [comment]
@joewhitsitt That's the webmaster view.

**Comment by bspeare** [comment]
Changing from dropbutton to popover is not a huge deal if a webmaster prefers that.

**Comment by bspeare** [comment]
> I think this is where I differ. I don't think we should be moving links of other modules. 

That's understandable, I do wish we had a better way to make people aware that they need to change their site name through the "Basic site settings".   Maybe we could redirect users to that setting when they login the first time :). 

Edit: or change the Site Name into a QuickEdit field.

**Comment by e-marie-w** [comment]
Some good news, I got the SiteNow category appearing first in the list! (turns out weights work the opposite way of what I thought).

**Comment by joewhitsitt** [comment]
I agree that the site name seems to be an issue for many. I wonder if we could collect that on the site request form. I think there used to be a limitation before, but now that we are creating initial user with permission, that might be possible.

**Comment by bspeare** [comment]
@joewhitsitt the request form would be a great idea!

**Comment by e-marie-w** [comment]
Since this issue was just for changing how module names appear in the menu, not the actual module names themselves, I'm good to request review on the PR, correct? And we can create another issue if we want to fix the module names in other places like individual pages.
