### ISSUE TITLE
Investigate PDF generation options for D8

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2797]
# Motivation

Admissions and the Grad College website both need some version of having PDFs be automatically generated for a page or set of pages. The ground has shifted in this area of functionality between D7 and D8 and there are a number of potential contrib solutions. Our needs in this area might be better described as programmatic generation of some pages or sets of pages vs having a plug and play solution that turns on PDFs for all pages or certain content types.

# Proposed solution

Investigate contrib module options including:
* https://www.drupal.org/project/entity_print
* https://www.drupal.org/project/printable - Successor to the "print" module
* ~~https://www.drupal.org/project/pdf_tools~~
* https://www.drupal.org/project/pdf_using_mpdf
* https://www.drupal.org/project/entity_pdf

**Comment by richardbporter** [comment]
I crossed out `entity_print` because it requires a CLI utility that is not supported on Acquia Cloud. https://support.acquia.com/hc/en-us/articles/360020517573-Acquia-Cloud-and-wkhtmltopdf

**Comment by richardbporter** [comment]
I think `pdf_tools` requires that utility as well and is not covered by the security advisory policy.

**Comment by richardbporter** [comment]
The `entity_pdf` page says:

> The module provides a htmlpdf.html.twig file so you can control the entire HTML structure that gets converted to PDF. No CSS and/or JS from Drupal will get added so you need to add everything by hand in the twig file.

while the pdf_using_mpdf page says:

> Add custom Style Sheet to PDF

**Comment by pyrello** [comment]
@richardbporter I forgot to add some details to this about what we need for the Grad College website (eventually). We need to create a PDF from a page and every child page underneath it in the menu.

**Comment by richardbporter** [comment]
Thanks!

**Comment by richardbporter** [comment]
Additional notes:

- The `printable` and `pdf_using_mpdf` modules have much more usage than `entity_pdf`.
- `entity_pdf` might need a core patch.
- The `print` module for D7 had the ability to print an entire Book from the top-level page. I don't think this functionality exists for D8. @pyrello were you planning on using book? Either way, that might require something custom.

**Comment by richardbporter** [comment]
More notes:

Printable
- Adds print links to every node by default. 
- Does not have separate permissions for accessing print pages vs PDFs.
- Not many docs. Not seeing much in terms of API and template overrides.
- PDFs include usual print-module stuff: logos, breadcrumbs, links
- Requires pdf_api which has not been touched in 5 years.

pdf_using_mpdf
- Seeing an error after PDF generation. Coming from mpdf dependency.
- Separate permissions but access is granted via "Generate PDF" local menu task. :(
- Has some docs. I see references to an API, CSS and template overrides.

entity_pdf
- Limited configuration
- Odd PDF URLs with no link
- Downloads PDF instead of viewing in browser
- Not much docs.

**Comment by richardbporter** [comment]
entity_pdf is very bare-bones and its doing something weird with a tmp directory in the docroot.

I was wrong about entity_print: only the D7 version requires wkhtmltopdf. The D8 version supports other engines. That would be my vote based on usage and what appears to be the best documentation.

**Comment by richardbporter** [comment]
Wow nevermind. I cannot for the life of me get that module working.

**Comment by richardbporter** [comment]
Finally got it working - it was an issue with a specific version of the dompdf depedency. The module allows for other PDF generation engines if that one gives us trouble with updating.

I'm gonna say entity_print is still the way to go. It has the best docs, usage and seems to be actively maintained. It should work for AOS based on the CSS and template options I saw. It includes a bulk operation for printing multiple pages into one PDF from the content overview page so we should be able to copy and repurpose that for the grad requirement.

I'll close this for now unless anyone else has reasons to use another module.

**Comment by pyrello** [comment]
> @pyrello were you planning on using book?

We are not using book. I'm assuming that it would need be custom functionality. This is the section of this site: https://grad.prod.drupal.uiowa.edu/academics/manual
