### ISSUE TITLE
Create template application for building Vuejs-based pamphlet sites

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2808]
# Motivation

As part of #2751, we need to create the base application that will be used to build the eventual Next Steps site.

# Proposed solution

* Make a copy of the existing viewbook site.
* Identify elements that are not currently components, but are going to be reused in the new site and create components for them.
* Strip out content that is specific to the Viewbook site.
* Create a template app Github repo and save this snapshot of the codebase there. To do this, you'll need to remove the `./.git` folder.

**Comment by bspeare** [comment]
I think this is done.
