### ISSUE TITLE
Create empty Github repo for Next Steps Vuejs site

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2810]
# Motivation

As part of #2751, we'll need a new Github repo for the Next Steps application that is being created.

# Proposed solution

Create a new Github repo called `admissions-next-steps`.

**Comment by GaryRidgway** [comment]
created

https://github.com/uiowa/admissions-next-steps

**Comment by pyrello** [comment]
@GaryRidgway Can you add me as an admin?
