### ISSUE TITLE
As a site owner, I can adjust the layout/placement of a featured image in the article content type

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#2813]
# Story

As a site owner, I can adjust the placement of a featured image in the article content type so that there is an alternative to the widescreen image format at the top of the page. 

# Proposed solution

Create a "Featured image display option" in the "Featured image" edit panel on the node edit screen:

<img width="531" alt="Screen Shot 2021-01-07 at 1 41 40 PM" src="https://user-images.githubusercontent.com/1036433/103937290-2cdc3680-50ee-11eb-92e1-a3c351fd1e33.png">

This select option would control the layout for the article.  
- The `Default` option could be the standard widescreen
- An additional `Sidebar` option could display the article in a two column layout

## First sidebar layout mockup:

- Displays featured image inline with the body text 
- Displays sidebar with date, author, share links

<img width="1878" alt="Screen Shot 2021-01-07 at 12 45 11 PM" src="https://user-images.githubusercontent.com/1036433/103937559-847aa200-50ee-11eb-874a-ecc574794f2d.png">

**Comment by bspeare** [comment]
Possible solution related to https://github.com/uiowa/uiowa/issues/2784 and https://github.com/uiowa/uiowa/issues/2530.

**Comment by bspeare** [comment]
Questions/observations from planning discussion:

**Default layout: Editorial Design**
- Narrow centered column width would make sense for widescreen featured image like https://stories.uiowa.edu/iowa-helps-turn-tide-in-pandemic but only if featured image is displayed. 
- Add banner headline styles for highlight text treatment
- Keep container left aligned?

**Sidebar layout: Press Release Design**
- How to handle different featured image sizes inline?
- Use WYSIWYG instead to upload an image after hiding the featured image?
- Two column layout format with meta information in the sidebar would be useful for the Event content type layout.
- Options for meta information placement and column width?

**Comment by bspeare** [comment]
After further consideration, maybe we should just update the layout to add an option use a sidebar column for metadata to solve the line-length issue?

## Sidebar column option with featured image:

<img width="1738" alt="Screen Shot 2021-01-25 at 2 50 50 PM" src="https://user-images.githubusercontent.com/1036433/105765113-841b3d00-5f1d-11eb-9826-9a935e6df750.png">

## Sidebar column option with featured image hidden:

<img width="1878" alt="sidebar" src="https://user-images.githubusercontent.com/1036433/105765483-1facad80-5f1e-11eb-912a-bc963cbc069c.png">

**Comment by pyrello** [comment]
Wanted to also drop a couple things here. Lauren had wondered about being able to add blocks to an article sidebar for related news and/or recent articles.

**Comment by bspeare** [comment]
Do we still want to consider providing the ability to change the placement of the featured image or should we close this in favor of #4453.

**Comment by pyrello** [comment]
> Do we still want to consider providing the ability to change the placement of the featured image or should we close this in favor of #4453.

It seems like this is a pretty difficult thing to do well, so I'd be cool with closing it. If its important to someone, it'll bubble up again.

**Comment by bspeare** [comment]
Close it.
