### ISSUE TITLE
As an admissions site owner, I can place a featured image into my Area of Study page and see it styled like the mockup

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#2816]
# Story

As a site owner, I can place a featured image into my Area of Study page and see it styled like the mockup

<img width="1685" alt="Screen Shot 2021-01-26 at 2 44 45 PM" src="https://user-images.githubusercontent.com/1036433/105903072-11759480-5fe5-11eb-8a3b-28a1e944c9af.png">

# Proposed solution
- [x] Implement Header section in layout builder like https://github.com/uiowa/uiowa/blob/main/config/admissions.uiowa.edu/core.entity_view_display.node.student_profile.default.yml#L39-L82 so that it will use https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/templates/layouts/onecol--background/layout--onecol--background.html.twig
- [x] Add separate field template for page title to apply `headline--uppercase headline--highlight` style like https://github.com/uiowa/uiowa/blob/main/docroot/sites/admissions.uiowa.edu/modules/admissions_core/templates/field--node--title--student-profile--default.html.twig. 
- [x] Add preprocess function in `admissions_core` (https://github.com/uiowa/uiowa/blob/main/docroot/sites/admissions.uiowa.edu/modules/admissions_core/admissions_core.module#L115-L131) to alter banner attributes (https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/templates/layouts/onecol--background/layout--onecol--background.html.twig#L18-L25) for small size and vertically and horizontally centered alignment: `banner--horizontal-center banner--vertical-center banner--transparent`

**Comment by joewhitsitt** [comment]
Can't seem to get this right. Hoping @bspeare can fix it

**Comment by bspeare** [comment]
I'll check it out.

**Comment by bspeare** [comment]
@joewhitsitt The image is now appearing.  Was that the issue you were having?

**Comment by joewhitsitt** [comment]
Yes! Thanks. Added the span for the yellow highlight. Not related to this issue per say, but the container issue for the whole node is still hard left with space on the right.
