### ISSUE TITLE
Domain Name for next steps app and working with hostmaster.

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#2818]
- [x] Get domain from Admissions team. - _nextsteps.admissions.uiowa.edu_
- [x] Request CNAME pointed at Github Pages DNS
- [x] Make CNAME config file in the correct branch so it is written to the served directory.

**Comment by joewhitsitt** [comment]
Blocked by https://github.com/uiowa/uiowa/issues/2810

**Comment by bspeare** [comment]
This is done as well.
