### ISSUE TITLE
Potential text area bug (Google Chrome only)

### ISSUE THREAD

**Issue by ABoston88** [uiowa/uiowa#2824]
Came from Pharmacy. The screenshot below is what Barb Kelley sees when she interacts with the text area editor. She was able to replicate it while on Zoom

![Chrome Issue in Layout](https://user-images.githubusercontent.com/58865958/104028970-fb677780-518e-11eb-822d-8d58dc8860a1.png)

**Comment by richardbporter** [comment]
FWIW I tested Chrome 87 on Windows 10 and text areas seem to work fine.

**Comment by ABoston88** [comment]
Going to leave this up until my weekly check-in with Pharmacy...but sounds like it might be an issue on their end, not ours.

**Comment by richardbporter** [comment]
Sounds good. We can test specific versions of Chrome and operating systems if you can relay those.
