### ISSUE TITLE
rsync drupal 8 site provision issue

### ISSUE THREAD

**Issue by ethanstjohn** [uiowa/uiowa#283]
Here is your friendly reminder of the rsync issue from Thursday. The command that ended up working was drush -l veterans.uiowa.edu rsync @self:%files @veterans.dev:%files.

**Comment by richardbporter** [comment]
I can't remember what the actual issue was. I tested with local and remote-to-remote aliases and it seemed to work fine. The site needs to bootstrap to get the files path correctly.
