### ISSUE TITLE
Update SROP mentors and scholars to use their own content types

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2830]
# Motivation

Previously SROP mentors and scholar pages lived in the context of the SROP pages in terms of the path alias. As this point, the D8 implementation using the Person content type will result in them being created with an auto-generated URL of `people/person-name`. The implementation in D7 was imperfect (you'll notice that the path alias pattern doesn't quite match the parent pages), but that was the intention, at least.

https://www.grad.uiowa.edu/ogi/srop/scholars/malik-afrifa

First, is this a problem? Maybe it doesn't matter to have those individual pages not exist in the same path pattern as the parent pages. @mjoneill if you had any thoughts, I would appreciate it.

If it is a problem, then #2753 potentially creates a path forward for continuing to use the person content type and then setting up a path alias that can be based on the primary person type.

-OR-

Maybe this need for a separate URL structure - similar to the need for a separate display output - is an indicator that the need would be better served by a separate content type, even though it would be similar.

Thoughts and feedback appreciated!

**Comment by mjoneill** [comment]
I might have thoughts on this, but probably need a bit more context. Can we reserve a couple minutes to discuss this afternoon?

**Comment by pyrello** [comment]
After discussing this some more, I think that I am convinced of the need to move to a different content type each for the Scholar and Mentor person types. I'm going to update the OP to layout to the steps to achieve this.

**Comment by pyrello** [comment]
This was closed by #2834
