### ISSUE TITLE
Create upcoming Thesis Defense listing view

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2837]
# Story

As a Grad College site owner I want display a list of upcoming Thesis Defenses so that interested parties can easily find out about them.

Existing page: https://www.grad.uiowa.edu/academics/thesis-and-dissertation/list

# Proposed solution

Build a view that displays a list of Thesis Defense teasers that have not occurred yet using the horizontal card style.

**Comment by joewhitsitt** [comment]
Almost think that this will be blocked until view config changes are mostly done on https://github.com/uiowa/uiowa/issues/2836. Trying to export the same config file doing different things will cause merge issues.

**Comment by joewhitsitt** [comment]
going to try and register a basic view so that https://github.com/uiowa/uiowa/issues/2836 can addon

**Comment by joewhitsitt** [comment]
Trying to create demo content for this and I think I am running into https://github.com/uiowa/uiowa/issues/2691
<img width="546" alt="Screen Shot 2021-01-15 at 10 37 19 AM" src="https://user-images.githubusercontent.com/4663676/104753888-33863180-571e-11eb-8356-548995461bdd.png">

**Comment by pyrello** [comment]
I thought that I had added code to work around this:
https://github.com/uiowa/uiowa/blob/a2d6035428fc6ea9c243aab3e46943ab24f7636f/docroot/modules/custom/grad_custom/grad_custom.module#L55-L65

Maybe something is broken now?

**Comment by joewhitsitt** [comment]
@pyrello Worked around it temporarily to create demo content and to finish this issue. Looking at the date issue now though, field validation happens before submit so i wonder if this was ever triggering. locally I changed it to a validation function which fires first and confirmed that form_state start/end had the same date object, but it still seems to trip the widget validation.

docroot/modules/contrib/smart_date/src/Plugin/Field/FieldWidget/SmartDateWidgetBase.php

**Comment by pyrello** [comment]
This is weird because I definitely tested this against both adding and editing thesis defense content before. The whole reason I added this is based on a conversation with the module maintainer and the fact that when I just set the end date field to be `'#access' => FALSE`, it would trigger this type of error.
