### ISSUE TITLE
Person_card view block does not display if person content type is initially created as in "draft" state

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#2845]
# Problem
The profile image, email, degree, or other contact information in the `person_card` view does not display if a Person is created and set to the "Draft" state. 

<img width="383" alt="Screen Shot 2021-01-12 at 8 18 39 AM" src="https://user-images.githubusercontent.com/1036433/104326896-d9803480-54af-11eb-8b90-4e4e61e7c25e.png">

# Steps to reproduce
Create a new Person with an image and set it to the "Draft" state. 

# Proposed solution
- I suspect this view just needs the published status filter criteria removed, saved, exported. admin/structure/views/view/person_card

OR

- Investigate permissions or caching that is blocking the `person_card` view from displaying.

**Comment by joewhitsitt** [comment]
I suspect this view just needs the published status filter criteria removed, saved, exported. admin/structure/views/view/person_card
