### ISSUE TITLE
Create a person teaser display with bio summary for Graduate College

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#2851]
# Story

As a site owner, I can create a teaser display of Person types that contain the bio in the summary for a page like https://www.grad.uiowa.edu/advisory-board. 

# Proposed solution

- Update current person teaser implementation to allow to show/hide bio
- Add to the existing view and then can be removed via block setting

**Comment by pyrello** [comment]
I think this has been resolved.
