### ISSUE TITLE
Create process for sending email in response to the creation of a Job (GA positions)

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2864]
# Motivation

Currently when a user creates a GA position on the current website, an email is sent to a moderator, so that they can review the posting and publish it.

# Proposed solution

TBD

**Comment by joewhitsitt** [comment]
fyi, Brand is using workbench_email to do this.

**Comment by pyrello** [comment]
Grad is going to use Handshake to handle job listings.
