### ISSUE TITLE
IWP - Create Writer Bio content type

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2865]
# Story

As an IWP visitor I can view a writer's bio so that I can learn more information about the author of a piece of writing.

The current IWP website defines both a person and writer's bio content type. The writer bio content type includes locational information for regions of the planet and then the specific country the writer is from. These fields power a map.

# Proposed solution

- [ ] Determine whether it makes the most sense to modify the person content type (split for this site) to add the additional fields, or whether it is better to have a semi-duplicate content type for displaying this information.
- [ ] Either: A.) Build a new content type or B.) Modify person content type and add/update site split for IWP to account for differences.

**Comment by briand44** [comment]
Closed in favor of #7549
