### ISSUE TITLE
Event card styles inconsistent based on parent layout

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#2867]
# Problem
Certain events blocks depending on their parent layout do not transition styles properly.

# Steps to reproduce
Events within a two-column layout doesn't switch from circle to square.

<img width="1424" alt="Screen Shot 2021-01-14 at 10 52 19 AM" src="https://user-images.githubusercontent.com/4663676/104622216-9c09db80-5656-11eb-9844-750be805a755.png">

# Proposed solution
Review events styles to make sure there isn't an override causing this.

**Comment by bspeare** [comment]
@joewhitsitt Can you provide a screenshot?

**Comment by joewhitsitt** [comment]
absolutely! updated with screenshot

**Comment by bspeare** [comment]
Looks like https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/scss/components/event.scss#L59 is the issue.

**Comment by joewhitsitt** [comment]
@bspeare Should I move that out specifically for uiowa-card-event and uiowa-events?

Or is this working as designed? I see the four-column as well.

**Comment by bspeare** [comment]
I think we added those before the card option updates.  I would remove both.

**Comment by joewhitsitt** [comment]
https://github.com/uiowa/uiowa/pull/2868
