### ISSUE TITLE
Allow webmasters to toggle display of certain theme settings

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#287]
This is currently possible on the D7 SiteNow service.

**Comment by joewhitsitt** [comment]
Need to audit current options we provide and whether or not we should continue do so.

**Comment by richardbporter** [comment]
They should at least be able to toggle slogan. Need to hide/remove:

-  BS JS/CSS
- Favicon b/c metadata overrides

Audit other D7 options.

**Comment by joewhitsitt** [comment]
This is what webmasters currently see on the standard service:

<img width="975" alt="Screen Shot 2019-08-20 at 1 21 39 PM" src="https://user-images.githubusercontent.com/4663676/63373413-830bd680-c34d-11e9-8fc9-7d3e9136a5d4.png">

**Comment by richardbporter** [comment]
There is no slogan theme setting. Nothing else makes sense for a webmaster to change. Closing.
