### ISSUE TITLE
Need consistency of article and event titles, dates, fonts on pages and LB blocks

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#2871]
# Problem
The titles (including padding), dates, links, images, etc are not consistent between articles and events. See screenshots below and use [https://internationalstudies.prod.drupal.uiowa.edu/](https://internationalstudies.prod.drupal.uiowa.edu/) as an example:
![news_events](https://user-images.githubusercontent.com/3067017/104649279-1ef05d80-567a-11eb-9891-b56f6585d661.png)
THIS IS SHOWING THAT PADDING EXISTS WITHIN LB, but not outside of LB:
<img width="1409" alt="Screen Shot 2021-01-14 at 3 12 51 PM" src="https://user-images.githubusercontent.com/3067017/104649991-2b28ea80-567b-11eb-934a-8f598f63246c.png">
<img width="994" alt="Screen Shot 2021-01-14 at 3 08 11 PM" src="https://user-images.githubusercontent.com/3067017/104649451-5e1eae80-567a-11eb-9609-bd1111eecd91.png">
<img width="1102" alt="Screen Shot 2021-01-14 at 3 02 47 PM" src="https://user-images.githubusercontent.com/3067017/104649365-3a5b6880-567a-11eb-8194-80766c99f684.png">

# Steps to reproduce
The news and events pages are as default, no steps needed to reproduce.
For the frontpage blocks, see the link above and perform the following:
Create a two- or three-column section.
In one column, add the Articles block, limiting to displaying 1 or 2.
In another column, add the Events block, and limit this to a small handful (2-4). Remove images and descriptions from the events block styles.

# Proposed solution
Decide which fonts, styles, etc are to be used where. I like the serif individual article/event titles, but it seems like too much if the main section title is serif. I like the serif and slightly greyed dates. Thoughts?

How is this going to be dependent on the main People page?

**Comment by bspeare** [comment]
@mark-bennett-uiowa Articles are still on an older style.  The work in https://github.com/uiowa/uiowa/pull/2730 will bring them to be similar.   We should definitely get you to review that pull request when it is ready.

**Comment by mark-bennett-uiowa** [comment]
@bspeare Just took a look at recent developments in regards to this issue, as well as #2730 completion. The below are things I noticed on the new [https://globalhealthstudies.uiowa.edu/](https://globalhealthstudies.uiowa.edu/) site on the frontpage.

![Screen Shot 2021-06-01 at 1 12 16 PM](https://user-images.githubusercontent.com/3067017/120371142-01dfc280-c2db-11eb-8d6d-1872cc565c86.png)

### Structure Differences:
Articles are wrapped in the following structure:
```
class="inner--list grid--threecol--33-34-33 block block-layout-builder block-inline-blockuiowa-articles"
    class="view view-articles-block view-id-articles_block view-display-id-block_articles"
        class="view-content list-container"
            class="views-row"
                role="article" class="card--media-right node node--type-article node--view-mode-teaser card--list card click-container"
```

Events are wrapper in the following structure:
```
class="inner--list grid--threecol--33-34-33 block block-layout-builder block-inline-blockuiowa-events"
    class="uiowa-events-wrapper list-container"
        class="event-item bg--white card--media-left card--centered-left card--alignment-left inner--list grid--threecol--33-34-33 list-item card click-container"
            class="card__body"
```

### Headlines:
**Articles class="card__title headline"**
font-family: Zilla Slab, serif
font-size: 1.5rem (ends up 24px)
line-height: 1.2 (ends up 28.8px)
margin-bottom: .325rem (ends up 5.2px)

**Events class="card__title headline"**
font-family: Zilla Slab, serif
font-size: 1.4rem (ends up 22.4px)
line-height: 1.2 (ends up 26.88px)
margin-bottom: .325rem (ends up 5.2px)

### Container:
**Articles div class="article-meta"** 
_none_

**Events div class="card__details"**
margin: 0 0 .625rem;

### Date and Location:
**Articles div class="article-meta" > span class="article-created-date"**
font-family: Zilla Slab, serif
font-size: 1.3rem (ends up 20.8px)
line-height: 1.3 (ends up 27.04px)
opacity: .7

**Events div class="card__details" > div class="card__date"**
font-family: Roboto, sans-serif
font-size: 1.1rem (ends up 17.6px)
line-height: 1.4 (ends up 24.64px)

**Events div class="card__details" > div class="card__label"**
font-family: Zilla Slab, serif
font-size: 1.2rem (ends up 19.2px)
line-height: 1.3 (ends up 24.96px)
margin-top: .325rem (ends up 5.2px)
padding-left: 20px (for icon)

### Description:
**Articles div class="field field--name-field-teaser field--type-string-long field--label-hidden field__item"**
font-family: Roboto, sans-serif
font-size: 1rem (ends up 16px)
line-height: 1.7 (ends up 27.2px)
margin-top: .5rem (ends up 8px)

**Events div class="card__description"**
font-family: Roboto, sans-serif
font-size: 1rem (ends up 16px)
line-height: 1.7 (ends up 27.2px) from card__body

**Comment by mark-bennett-uiowa** [comment]
This can be seen on [https://physics.prod.drupal.uiowa.edu/](https://physics.prod.drupal.uiowa.edu/):

![Screen Shot 2021-06-01 at 1 59 42 PM](https://user-images.githubusercontent.com/3067017/120379268-2476d900-c2e5-11eb-8ebb-72826fab9a44.png)


Can also get this floating button issue:
![Screen Shot 2021-06-01 at 2 57 21 PM](https://user-images.githubusercontent.com/3067017/120382922-d9ab9000-c2e9-11eb-897b-727d5d8ba702.png)


### Empty results block:
**Articles div class="view-empty"**
font-family: Roboto, sans-serif
font-size: 1rem (ends up 16px) inherited from body
line-height: 1.15 (ends up 18.4px) inherited from body

Button a href class="bttn bttn--primary bttn--caps" wrapped inside div class="more-link"

**Events div class="events-empty"**
font-family: Roboto, sans-serif
font-size: 1.2rem (ends up 19.2px) inherited from p
line-height: 1.7 (ends up 32.64px) inherited from p
margin-top: 0 inherited from p
margin-bottom: 1.05rem (ends up 16.8px) inherited from p

Button a href class="more-link bttn bttn--primary bttn--caps" NOT wrapped inside div

**Comment by mark-bennett-uiowa** [comment]
This can be seen on https://physics.prod.drupal.uiowa.edu/ as well, but have to remove the news to get the empty results to show [https://physics.prod.drupal.uiowa.edu/](https://physics.prod.drupal.uiowa.edu/):

![Screen Shot 2021-06-01 at 2 18 02 PM](https://user-images.githubusercontent.com/3067017/120379312-322c5e80-c2e5-11eb-9c3d-c22c4c1564d5.png)

### Grid Layout:
These seem to be the exact same settings as the non-grid blocks above.

**Comment by mark-bennett-uiowa** [comment]
This looks like its working properly now with #3638. Tested font sizes, font families, and consistency on blocks as well as pages. Outside of the small date difference (already been mentioned, new issue coming soon) and the extra padding at the top of the articles list page (aware of the issue, currently fixing), we can close this issue. Thanks so much Ben!!
![Screen Shot 2021-06-11 at 3 27 26 PM](https://user-images.githubusercontent.com/3067017/121745817-7fb98000-caca-11eb-8d67-5eae63cbf9ec.png)
![Screen Shot 2021-06-11 at 3 29 03 PM](https://user-images.githubusercontent.com/3067017/121745822-82b47080-caca-11eb-8c4f-2cf87baa96be.png)
![Screen Shot 2021-06-11 at 3 28 53 PM](https://user-images.githubusercontent.com/3067017/121745827-83e59d80-caca-11eb-943d-2651cf223a03.png)

**Comment by mark-bennett-uiowa** [comment]
Extra padding at top of Articles list page has been fixed now too. Can close this issue. Thanks Ben!
