### ISSUE TITLE
Should default moderation state be "Draft?"

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2880]
Currently all content starts in a "Draft" state, which means that it has to be changed every single time. Are we clear that most site owners want their content to default to this option? When I'm using it, I often accidentally create something as a draft, then have to immediately edit it to set it to published.

Alternately, should we have separate workflows for different content types? There isn't an easier way to duplicate an existing workflow via the UI, but it seems like copying and pasting one to create a new one should be fairly straightforward. Splitting out workflows per content type would also allow for more targeted overrides in site and feature splits.

**Comment by cory-skeers** [comment]
This might be a good question to bring up in demo--otherwise, @ABoston88 do you have some input on this from your own work and people you've worked with in training?

I've always worked off of a default to Draft unless otherwise chosen, and that's the functionality I expect. Might be a chicken or the egg situation though, that I only expect that because I've gotten used to the systems in which I've worked.

**Comment by joewhitsitt** [comment]
I agree with the demo conversation idea. I can understand how this is coming up with mass content creation that you are currently experiencing, but typically, I see draft as a default and a "are you sure you want this published" type check.

**Comment by bspeare** [comment]
I agree that it is confusing.   If we plan on moving forward with this as the standard, we should make the "Draft" page design indicator something more dramatic indicating the draft state besides the pink background color.

**Comment by ABoston88** [comment]
I'm working mostly with editors that don't have live sites, yet - so they're working in the published state on every page. They haven't mentioned any issues moving things over to published. Having one last opportunity to look things over with everything saved and the Layout tool closed is useful, so I'd be in favor of keeping draft as the default. 

We can probably use Ben's suggestion to both indicate the draft state and point people to the place where they change it to published. Maybe just a text box above the drop-down with "This content is currently in a "draft" state and will not be visible by visitors to the site. Select "Published" in the menu below to make this content public." or something like that.

**Comment by joewhitsitt** [comment]
We have had a tough time with the unpublished-pink:  https://github.com/uiowa/uiowa/issues/2173, https://github.com/uiowa/uiowa/issues/1137, https://github.com/uiowa/uiowa/issues/178

I am all for revisiting if that is the underlying issue here.

**Comment by pyrello** [comment]
> I am all for revisiting if that is the underlying issue here.

That is not the underlying issue, but I am supportive of finding different visual cues to indicate draft status to the user.

It sounds like I may be in the minority about what the default state should be and I would defer to the group. I do like the idea of raising it at demo in the next few weeks to gather some additional feedback.

Thanks for the conversation!

**Comment by joewhitsitt** [comment]
It sounded like that most content writers assume draft is the default for creating new content. Do we need to gather more feedback about this or do we want to explore a toggle "fast-editing" mode for those use-cases where a lot of content is created at once and the experience is less ideal? If so, I think after node creation save, another fast-editing feature would be to direct the editor to a new node/add form of the same type. 👀

**Comment by pyrello** [comment]
I like the idea of a toggle to allow the state to be set to "Published" by default for the purpose of manual content migration. I created a follow-up issue: #2921.
