### ISSUE TITLE
Add Quote block type

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2881]
# Story

As a content editor I want to be able to embed structured block quotes in my page so that I can display quotes and associate them with a person.

# Motivation

It looks like there is a V2 blockquote paragraph type and we maybe decided at some point to just translate that into text areas formatted as `<blockquote>` when we migrate the content.

However, in trying to construct a nice looking block quote like what is currently on the Grad College homepage, it is very hard to do it.

<details>

Grad College homepage example:
![Screen Shot 2021-01-17 at 10 18 48 AM](https://user-images.githubusercontent.com/709009/104849061-6ca0dc00-58ad-11eb-8a0d-4ed65ddfd463.png)

My attempt at recreating this:
![Screen Shot 2021-01-17 at 10 19 23 AM](https://user-images.githubusercontent.com/709009/104849086-89d5aa80-58ad-11eb-9475-d3a9418df5f9.png)

My recreation doesn't look terrible, although it could look much nicer. It is however, not intuitive at all. I ended up creating a text area to create the actual quote above, then a card with the additional information below it. It would be nice to be able to create a structure like this without having to go to so much trouble.

</details>

# Proposed solution
- [x] Set permissions for this block
- [x] Check site split permissions?
- [ ] Use existing prototype code listed at https://github.com/uiowa/uiowa/issues/2881#issuecomment-952281022
- [x] Create a Blockquote block with:
  - Content field
  - Footer field
  - Citation field with url and link text 
  - Image fields
  - Blockquote style settings:
    - Left (default)
    - Right 
    - Center
  - Image position: 
    - Within `<footer>`
    - Above content  

**Examples of how this would look:**

https://uids.brand.uiowa.edu/branches/feature_blockquote_prototyping/components/detail/blockquote--default.html

## Future slice

- [ ] Add a reference field that would reference the profile content type without manually adding image, content, citation, etc.

**Comment by joewhitsitt** [comment]
Duplicate of https://github.com/uiowa/uiowa/issues/943? Can we move the info from one or the other and close one?

**Comment by bspeare** [comment]
@pyrello's comment from duplicate closed issue:

"Our current iteration of P2LB (#1976) converts pull quotes into text areas. If we truly want to pursue this as an option, we may want to consider doing it prior to launching the conversion tool, otherwise, we will likely lose the ability to know that something was intended to be a pull quote vs intended to be a text area."

**Comment by joewhitsitt** [comment]
Should this start in UIDS to account for images?

**Comment by bspeare** [comment]
I think we can backport the solution to UIDS based on what the final product looks like with this block.

**Comment by makurj** [comment]
Blockquote example on Tippie D7: https://tippie.uiowa.edu/stories/phaedra-strohmaier-mba

![image](https://user-images.githubusercontent.com/52135878/138939284-c323d1ae-75bd-458c-8053-a376b0c75754.png)

**Comment by mjoneill** [comment]
An example from the stories site of _a_ story with a blockquote : https://stories.uiowa.edu/improving-outcomes-children-hearing-loss

There may be other/additional types of block quotes in play on that site.

**Comment by makurj** [comment]
I would like to work/pair on this.

**Comment by bspeare** [comment]
I've updated the proposed solution to suggest using the UIDS code from https://github.com/uiowa/uids/pull/603.
