### ISSUE TITLE
Update pear/archive_tar package

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2883]
Getting this on builds in Travis currently:
```
Symfony Security Check Report
=============================
1 packages have known vulnerabilities.
pear/archive_tar (1.4.11)
-------------------------
```

**Comment by richardbporter** [comment]
drupal/core-recommended has this locked at 1.4.11 so we can't update. We could disable security checks temporarily in the blt.yml config file. Still investigating.

**Comment by richardbporter** [comment]
I think this is done.
