### ISSUE TITLE
Intermittent issue with multiple MAUI session date blocks under certain conditions.

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2889]
# Problem

Following up on issue reported in #2833.
 
When adding multiple blocks MAUI Dates by Session blocks to a page, when one of the blocks has a category set, but the session is exposed, changing the session resets the block to showing all results. This doesn't happen when there is only one block on the page.

# Steps to reproduce
1. Add a  Dates by Session block to a page via LB. In the block configuration, leave both filter exposed.
2. Add a second Dates by Session block to the same page. In the block configuration, set the category to "Graduate Students" and leave the session filter exposed.
3. Save the layout.
4. Change the session in the second block and observe whether it is sticking to the correct category.

# Proposed solution

TBD

**Comment by joewhitsitt** [comment]
I was able to reproduce using the no classes category (dates I am familiar with). when i changed the session, I was definitely getting dates like "UCR flag and off-cycle date reports."
