### ISSUE TITLE
Migrate articles from engineering.uiowa.edu to engineering.prod.drupal.uiowa.edu

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#2893]
https://github.com/uiowa/uiowa/issues/2652

# Proposed solution

- [x] Add engineering migration module/split
- [x] Write engineering article migration YAML
- [x] Write engineering article migration source plugin
- [x] Map author field--prepend to Organization
- [x] Map primary department, department feed, and audience fields--include as prefixed tags

**Comment by cory-skeers** [comment]
Including some of the correspondence on the migration here--quotes are questions asked of Bill, and following texts are his responses.

> "Legacy" fields, such as Legacy NID, Temp Department, etc.: Do these need to be kept, or can they be ignored? (It sounded like these might not need to be moved, but I don't think there was a 100% decision yet.)

I'm pretty sure these can be ignored. I think some were just part of the last migration from the 2016 redesign.

> Author field: These are inline entities in V3, and could be created as part of the migration with some extra time. There also might be some issues with naming inconsistencies if initials are used in some places and not others, titles, etc. 

> The quicker option would be to put the author into the "Source Organization" field without the "Source Link" -- It would look essentially the same to the end user, but not take advantage of linking various articles to the same author. There could always be manual cleanup later, or possibly an update hook if it's decided that it's needed later.

Yes, whatever you recommend on these is fine. A generic author is totally fine.

> Extra fields, such as Department or Audience: We've talked about including those using the V3 tags. I was thinking they'd be prefixed by each category, so they could still be clearly distinguished between each other and other tags (e.g. audience-faculty, or similar).

Yes, the department and audience would probably work best as taxonomy tags now. I believe my original request to Brian/Michael had an excel file that listed all the tags used in the old site and what I had set up in the new site, including node IDs. If you need those files, I can send them to you. It might help. I think there are about 25-30 tags being used. If those can be kept, it would help a lot (but translated to how the new site manages that. The exact method does not have to be kept.)

> Files: Is there a need to migrate files as well? Previously migrations have been set to first migrate all files, and then node migrations use this migration mapping to attach the new media entities in field images and inline references. Working on an option to conditionally migrate files only as they're found in migrated nodes, rather than migrating ALL files beforehand. Once this conditional option has been done generally, either getting it in place or just migrating all files take about the same amount of time. It just comes down to: do you only want to migrate files that are used in articles, or do you want all files, regardless of whether they're used?

Just files that are used would be best. We are horribly behind on file maintenance/management and don't see it ever getting better. So we might as well use this as a time to update that, if even a little.
