### ISSUE TITLE
Admissions student profiles

### ISSUE THREAD

**Issue by dnkemper** [uiowa/uiowa#2894]
# Problem

If the area of study field isn't filled out in the student profile content type, the image is only field that displays in teaser
https://admissions.prod.drupal.uiowa.edu/student-profiles
# Steps to reproduce

https://admissions.prod.drupal.uiowa.edu/student-profiles
# Proposed solution

Absolutely no idea haha

**Comment by briand44** [comment]
Looks like we duplicated this issue. Closing in favor of #2895 since it is already on the project board and prioritized.
