### ISSUE TITLE
Graduate College Thesis Defense Date Save Error

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#2899]
# Problem

Grad thesis defense content cannot be save with fields restricted by #access or #disabled.
https://github.com/uiowa/uiowa/blob/main/docroot/sites/grad.uiowa.edu/modules/grad_core/grad_core.module#L44

Relates to https://github.com/uiowa/uiowa/issues/2691 and https://github.com/uiowa/uiowa/issues/2837#issuecomment-761050356

# Proposed solution

- [ ] Try switching to the inline smart date widget, paired with smart_date 3.5.1 and https://www.drupal.org/project/smart_date/issues/3269460 or 3.5.2
- [ ] Remove https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/grad_custom/grad_thesis_defense/css/admin.css

**Comment by joewhitsitt** [comment]
I think the most lightweight way to address this and future "duration 0" fields is to work with the #states api.

If duration field is 0, set end date and duration to invisible. Unfortunately there isn't a good way to target the h4 field label for the end date so a form_alter/admin css override might not be avoidable.

<img width="426" alt="Screen Shot 2021-01-20 at 3 52 18 PM" src="https://user-images.githubusercontent.com/4663676/105245493-910fe900-5b37-11eb-9f2a-1a99d9f36eec.png">

**Comment by joewhitsitt** [comment]
Looks like smart_date 3.2.0 cleans up the end date label now with https://www.drupal.org/project/smart_date/issues/3208136

<img width="567" alt="Screen Shot 2021-05-07 at 4 17 00 PM" src="https://user-images.githubusercontent.com/4663676/117509432-da9e0b80-af4f-11eb-8168-810878fe1006.png">

**Comment by joewhitsitt** [comment]
This has cropped again with updating smart_date. They refactored the JS and this is no longer being hidden. https://github.com/uiowa/uiowa/pull/4902#issuecomment-1061103499

**Comment by joewhitsitt** [comment]
Adding a bit of css to deal with this for now: https://github.com/uiowa/uiowa/pull/4902/commits/5ef6b2ec50f112015169e4625343479fc992c2a5

There is a core issue to change the datetime element (https://www.drupal.org/project/drupal/issues/3078334) which might make working with it easier than targeting with `nth` stuff

**Comment by joewhitsitt** [comment]
For visibility, I am communicating/testing upstream

**Comment by joewhitsitt** [comment]
It is recommended from the maintainer that we try the other widget for this functionality. I don't recall the particulars about this content type/field so I think this should wait for @pyrello to chime in on. https://www.drupal.org/project/smart_date/issues/3261072#comment-14446977

**Comment by pyrello** [comment]
I'm fine with switching to a different widget. The way it was set up at the time is just the best way I could figure out to do it at that point. There is never an end date with these.
