### ISSUE TITLE
Finish renaming modules

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#291]
Some are sitenow, some are uiowa. 🤷‍♂

**Comment by joewhitsitt** [comment]
So assuming we are sticking with sitenow_* for docroot/modules/custom modules (not /uiowa) the following would need to be renamed (directory, file names, functions, comments, info file information, documentation).

We might also want to double check that these (or elements of (uiowa_events_load)) won't be shared as repos with other entities on campus.

What stinks are all of those _uip_ fields related to uiowa_paragraphs, but I believe that is out of scope for now.

- uiowa_events
  - sub modules (combined into parent module?)
- uiowa_forms
- uiowa_media_wysiwyg
- uiowa_paragraphs
  - sub modules (combined into parent module?)
- uiowa_seo

**Comment by joewhitsitt** [comment]
A PR has been started for this #300 and the conversation has moved there.

**Comment by richardbporter** [comment]
Next steps:

- [x] Merge rename PR
- [x] Deploy to each env
- [x] Push uninstall config changes for deprecated modules to each env
- [x] Remove deprecated modules
