### ISSUE TITLE
Grad SROP scholar view page not showing up

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2922]
# Problem
This page is showing as "Page not found": https://grad.prod.drupal.uiowa.edu/dei/srop/past-scholars

It looks like it should be working: https://github.com/uiowa/uiowa/blob/94707e419e2843010cab47182c6805bad2c1eb68/config/grad.uiowa.edu/views.view.srop_scholars.yml#L335

There is now SROP scholar content, so these pages should be populating.

# Steps to reproduce
Visit the above page and see that it is not showing the view that should be showing up.

# Proposed solution
Troubleshoot and TBD

**Comment by bspeare** [comment]
Taking a look now.

**Comment by bspeare** [comment]
@pyrello Looks like the view is not `enabled`.

**Comment by pyrello** [comment]
Well, at least that seems like an easy problem to solve!
