### ISSUE TITLE
SSL Cert - basbls.uc.uiowa.edu on uiowa01

### ISSUE THREAD

**Issue by cory-skeers** [uiowa/uiowa#2928]

**Comment by mark-bennett-uiowa** [comment]
@cory-skeers @briand44 I just created a new SSL cert for uiowa01, so make sure that whoever handles this uses the newest cert. It should be the active one. I left the old one Brian made in place until I was certain the new one was working, but it can be removed (labeled 12-28).

**Comment by mark-bennett-uiowa** [comment]
@cory-skeers This has been added to a new SSL certificate for uiowa01. Closing.
