### ISSUE TITLE
As a site owner, I can create Admissions Requirements with a separate content type and reference them in the Areas of Study content type and see them styled like the mockup

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#2934]
# Story

As a site owner, I can create Admissions Requirements with a separate content type (https://github.com/uiowa/uiowa/blob/main/config/admissions.uiowa.edu/core.entity_view_display.node.admissions_requirement.default.yml) and reference them in the Areas of Study content type and see them styled like the mockup

https://admissions.prod.drupal.uiowa.edu/academics/accounting
https://admissions.prod.drupal.uiowa.edu/academics/education

# Proposed solution

- [x] Place in layout using a wide one-column
- [x] Styled through using card template

<img width="1787" alt="Screen Shot 2021-01-26 at 8 48 52 AM" src="https://user-images.githubusercontent.com/1036433/105860588-5a145a00-5fb3-11eb-85b3-42444597df89.png">

**Comment by bspeare** [comment]
Examples of admissions requirements content:

First Year: https://admissions.uiowa.edu/undergraduate-programs/first-year-admission-college-liberal-arts-and-sciences
Transfer students: https://admissions.uiowa.edu/future-students/transfer-admission-liberal-arts-sciences
International: https://admissions.uiowa.edu/apply/international-application-process
