### ISSUE TITLE
Create Alumni role and allow non-SSO login

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2938]
# Story

As a site owner I want to provide resources that are only available to Alumni because that is part of the value proposition that we are offering with completion of our program.

# Motivation

Both the SLIS and SPPA websites provide web portals where their alumni can log in to view resources that are not available to the public or to current students.

# Proposed solution

TBD

**Comment by richardbporter** [comment]
I'm really not in favor of allowing non-SSO logins on our platform. I'd be curious to know if alumni HawkIDs stay active after graduation, this seems to indicate yes: https://its.uiowa.edu/support/article/101541 If not, would guest accounts work for this? https://its.uiowa.edu/support/article/114826

If you have a HawkID of an alumni, I may be able to inspect it for details. Send it on Slack.

**Comment by pyrello** [comment]
> I'm really not in favor of allowing non-SSO logins on our platform.

Could you unpack this a bit? It is not immediately obvious what the problem with doing this is.

> If not, would guest accounts work for this? https://its.uiowa.edu/support/article/114826

Currently, a person can request an alumni account, which then gets approved by a site admin. I'm not sure how we could create a workflow incorporating the link above in a way that wouldn't make the process much more onerous for the person doing the account approval and provisioning. I'm open to suggestions about how this might work.

**Comment by pyrello** [comment]
Based on additional conversations on this topic, I think this can be closed. To work around this limitation, we are going to create webforms to allow Alumni to request access to protected resources and the site owner will request guest HawkIDs for them.
