### ISSUE TITLE
Fix SROP mentor display

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2939]
# Problem
The images on this page don't look quite right:
![Screen Shot 2021-01-26 at 12 57 07 PM](https://user-images.githubusercontent.com/709009/105891319-1d0d8f00-5fd6-11eb-80ef-6836b8cecd46.png)

# Steps to reproduce
After the next build completes, this should be viewable at https://grad.prod.drupal.uiowa.edu/dei/srop/mentors

# Proposed solution
TBD

**Comment by bspeare** [comment]
The template is fine, you just need to set an image style on the view to use a `1:1` aspect ratio.

**Comment by bspeare** [comment]
It is using the node teaser template, so the image style needs to be set on the teaser: 

<img width="1569" alt="Screen Shot 2021-01-26 at 3 46 14 PM" src="https://user-images.githubusercontent.com/1036433/105909923-c4e28700-5fed-11eb-96e7-f7250bbd5974.png">

**Comment by bspeare** [comment]
Also this view could be updated to use the existing card fields like the thesis defense list: https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/grad_custom/templates/node--thesis-defense--teaser.html.twig#L89-L107 (https://grad.prod.drupal.uiowa.edu/academics/thesis-defenses/list).
