### ISSUE TITLE
Create develop branch

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#294]
To alleviate workflow issues (pushing hotfixes, security updates, site provisions, etc.) where you don't want to push custom development up, we need a separate branch.

**Comment by GaryRidgway** [comment]
I thought I was being helpful so I created a develop branch but then joe said it was much more dev-ops-y than that. Oh well, its sitting there now for when it matters.

**Comment by richardbporter** [comment]
I deleted that one. We should wait until HR goes live to do this.
