### ISSUE TITLE
Admissions - Add entity reference fields for admissions requirements and application process

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#2942]
# Proposed solution

* [x] Confirm with Scott how he wants to handle entering "Application Process" content.  Do they want to enter as pages similar to "Admission Requirements?"
* [ ] ~~If using a dedicated content type for "Application Process," add the content type. The fields/layout/etc. can be added in a follow-up task. If that is necessary, please create a the follow-up issue.~~
* [x] Remove the Admission Requirements content type.
* [x] Create paragraphs bundle to house the fields
  * Title/label
  * Intro
  * Requirement label
  * Requirement entity reference (page)
  * Process label
  * Process entity reference (page)
* [x] Create three separate paragraphs fields on AoS that allow one item from the bundle above.
* [x] Bring the local admissions requirements field into the same gray section to connect the "four" together.
* [x] Output in card template for follow up work in https://github.com/uiowa/uiowa/issues/2934

<details>
<summary>Original details</summary>
```
- [ ] Add 3 entity reference fields that link to pages, with the following names:
  - Requirements: First year
  - Requirements: Transfer
  - Requirements: International
- [ ] Add 3 entity reference fields that link to whatever content type is determined to be used for "Application Process" content based on previous conversation, with the following names:
  - Application process: First year
  - Application process: Transfer
  - Application process: International
```
</details>

**Comment by pyrello** [comment]
After discussing this content type with Scott earlier, I'm realizing that I must have gotten the wrong idea about how this would work more broadly. Instead of creating Requirements pages with the admissions requirement content type that was created in #2905, they have already created these pages using the page content type. So, likely we will need to replace this entity reference field with an entity reference field targeting a page. However, I want to look into this a little bit more to understand it a little better before moving ahead with it.

**Comment by pyrello** [comment]
D7 Admission Requirements page example: https://admissions.uiowa.edu/academics/first-year-admission-business

D8 Admission Requirements pages: https://admissions.prod.drupal.uiowa.edu/admin/content?title=admission&type=All&status=All&langcode=All

D7 Application Process page example: https://admissions.uiowa.edu/apply/first-year-student-application-process

D8 Application Process pages: https://admissions.prod.drupal.uiowa.edu/admin/content?title=application&type=All&status=All&langcode=All

It looks like the Application Process pages mostly haven't been moved over.

**Comment by joewhitsitt** [comment]
@pyrello how is this going? can i help with this at all?

**Comment by pyrello** [comment]
@joewhitsitt If you want to touch base with Scott about the first point, that would be great.

**Comment by joewhitsitt** [comment]
From Scott:

_I guess it comes down to how they will be displayed in that new combined section (Process + Requirements) per student. We can likely work with just a title and link for both of them, but I don’t if you’re still going in the direction of having those as buttons like in the current design mock-up, or if buttons will even work for every scenario (longer text possibilities)._

_I think we can start with the following for this section, but there are design considerations to this content._

**First Year**

- Intro text
- Requirements title
- Requirements link
- Process title
- Process link

**Transfer**

- Intro text
- Requirements title
- Requirements link
- Process title
- Process link
- Transfer tips (I know this is somewhat an external thing, but it would be mixed in with the above content for transfer)

**International**

- Intro text
- Requirements title
- Requirements link
- Process title
- Process link_
