### ISSUE TITLE
uiowa702 site removals

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#2953]
The following sites can be removed from uiowa702 after Feb. 1st at 8:00am. I've added the blocked label until then.

Deleting a multisite documentation - https://wiki.uiowa.edu/pages/viewpage.action?pageId=259624476

- [x] https://120thcelebration.centerforconferences.uiowa.edu/
- [x] https://aasog2019.centerforconferences.uiowa.edu/
- [x] https://b1gchiefsanddirectors.centerforconferences.uiowa.edu/
- [x] https://hcccretreat.centerforconferences.uiowa.edu/
- [x] https://iipc.centerforconferences.uiowa.edu/
- [x] https://ips2017.centerforconferences.uiowa.edu/
- [x] https://isv2019.centerforconferences.uiowa.edu/
- [x] https://midwestregionburn.centerforconferences.uiowa.edu/
- [x] https://nasscfl2020.centerforconferences.uiowa.edu/
- [x] https://psychpostgrad.centerforconferences.uiowa.edu/
- [x] https://tme2018.centerforconferences.uiowa.edu/
- [x] https://automated.uiowa.edu

**Comment by joewhitsitt** [comment]
yay
