### ISSUE TITLE
As a site owner, I can use the remaining headline styles in the text area headline field

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#2960]
# Story

As a site owner, I can use the remaining headline styles in the text area headline field so that I don't have to copy and paste classes from https://uids.brand.uiowa.edu/components/detail/headlines.html.

# Proposed solution

- [ ] Add remaining headline styles to the text area headline field: https://uids.brand.uiowa.edu/components/detail/headlines.html. 
- [x] Also fix incorrect naming of "Bold serif, highlighted"
- [x] Adjust headline sizes/margins so that they appear same size as `Roboto`: https://github.com/uiowa/uids/issues/437.  
- [x] Remove fix headline size so that size will change based on selected heading level: https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/scss/components/typography/headings.scss#L24-L28
<img width="777" alt="Screen Shot 2021-01-28 at 8 36 50 AM" src="https://user-images.githubusercontent.com/1036433/106154113-e1dd9e00-6144-11eb-8b46-286acf3134c2.png">

**Comment by joewhitsitt** [comment]
I could use this on https://github.com/uiowa/uiowa/issues/3232... How many points do you think this would be @bspeare ?

**Comment by bspeare** [comment]
`5`?  Might be worth pulling in if this would help.

**Comment by joewhitsitt** [comment]
I've gone down a rabbit hole and can get by with some scss includes for now. If this turns out to be the only problem I can bring it up in parking lot.

**Comment by joewhitsitt** [comment]
FYI, element--light-intro/element--bold-intro was added as a WYSIWYG style dropdown item recently. Not sure if that changes the scope of this issue.

**Comment by bspeare** [comment]
@joewhitsitt good point. I updated the solution.

**Comment by bspeare** [comment]
I think the work on this is complete for Admissions.  At this point I don't think we want to add the remaining headline styles to the headline field, but we can reopen this if that becomes a priority in the future.
