### ISSUE TITLE
As a site owner, I can expect to see Apply Now and Request Info buttons at the top of every Area of Study page

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#2968]
# Story

As a site owner, I can expect to see Apply Now and Request Info buttons at the top of every Area of Study page.

https://admissions.prod.drupal.uiowa.edu/academics/accounting
https://admissions.prod.drupal.uiowa.edu/academics/education

# Proposed solution

- [x] Both links are placed in sidebar at top of the page
- [ ] **Request Info** link:  Dynamically place major name into link text? Or will "Request Info for this Major" be sufficient? This link will be replaced by link to form on page in the future.
- [x] Apply now: https://apply.admissions.uiowa.edu/admissions/login.page
- [x] Request Info: https://www.maui.uiowa.edu/maui/pub/admissions/webinquiry/undergraduate.page

**Comment by joewhitsitt** [comment]
Where should the links point to for MVP? Is this a custom block that will be placed in Layout?

**Comment by bspeare** [comment]
I added the links to the proposed solution.  @pyrello any thoughts on how we should add these button links to the sidebar layout?

**Comment by pyrello** [comment]
Not sure if we have done this before, but I was just thinking it could be a text area added to the layout template. Alternately, we could create a block plugin class, which just displays those link buttons and place that via the LB template.

**Comment by bspeare** [comment]
Adding text area blocks to the layout template creates this error if you try to export the config and install and edit the layout page template: `Error: Call to a member function getEntityTypeId() on null in Drupal\layout_builder\Plugin\Block\InlineBlock->build()`.   Which sounds similar to this issue: https://www.drupal.org/project/drupal/issues/3049332#comment-13848037.   

Is it worth creating link fields within the content type to use for these buttons instead?

**Comment by joewhitsitt** [comment]
If these are always the same links and might have dynamic labels, can we just make a custom block for admissions to do this?

**Comment by bspeare** [comment]
@joewhitsitt I'm not clear how we do that and add it to the config if you have thoughts on that part.

**Comment by joewhitsitt** [comment]
Create a block like https://github.com/uiowa/uiowa/blob/main/docroot/profiles/custom/sitenow/src/Plugin/Block/SiteNowBlock.php in admissions_core. It should be available to place via layout builder via the "Site custom" block category. Put it in another block category that isn't allowed in layout builder if you don't want them placing it on pages.

Export config once placed.
