### ISSUE TITLE
Webform Basic HTML field cannot use text formats, so uids styling is broken

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#2971]
# Problem
The only option for an HTML markup field in webforms is the Basic HTML field. This field does not use a text format and does not allow p tags, which is causing styling issues (see below). Is this something worth fixing? The following screenshot can be found at [https://socialwork.prod.drupal.uiowa.edu/undergraduate/ba-social-work/information-sessions/iowa-city](https://socialwork.prod.drupal.uiowa.edu/undergraduate/ba-social-work/information-sessions/iowa-city).

<img width="1350" alt="Screen Shot 2021-01-28 at 4 46 37 PM" src="https://user-images.githubusercontent.com/3067017/106210512-86cf9980-618c-11eb-827f-2625b99f99da.png">

# Steps to reproduce

- Create a new webform from Structure > Webforms.
- Add a Basic HTML field and enter basic text, list items, etc.
- Give the form its own dedicated URL under Settings > General > URL path settings.
- Save form and view results.

# Proposed solution
This could be "fixed" by attaching the webform to another node or block, but these Information Session forms get updated regularly with new dates and times. Rather than editing both the node/block and then the field values of the form, we could simply edit both from the webform settings. This may need to be done if this issue isn't high priority.

If we allow the webform markup field to utilize the Filtered HTML and/or Minimal HTML hopefully our uids styling would carry over. I dont see an option to change this in the admin settings or form settings. This may need to be fixed in uids.

There was something about this at [https://drupal.org/project/webform/issues/2952809](https://drupal.org/project/webform/issues/2952809) and [https://drupal.org/project/webform/issues/2888626](https://drupal.org/project/webform/issues/2888626).

**Comment by joewhitsitt** [comment]
Is this still an issue @mark-bennett-uiowa? Did this https://github.com/uiowa/uiowa/pull/3178 solve this?

**Comment by mark-bennett-uiowa** [comment]
@joewhitsitt Yes, #3178 did solve this. Thank you! Closing issue.
