### ISSUE TITLE
Long URL in events block breaks container

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2972]
# Problem
An event with a very long embedded URL will visually break the container it is in:
![Screen Shot 2021-01-29 at 8 39 51 AM](https://user-images.githubusercontent.com/709009/106288602-e02bdd00-620d-11eb-974e-7eea871418ae.png)

# Steps to reproduce
Viewable here: https://grad.uiowa.edu/

# Proposed solution
Apply an overall word-wrap rule on the card.

**Comment by joewhitsitt** [comment]
Can we think of an instance where we don't want a link to wrap if it is too long? https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uiowa_bootstrap/scss/partials/03_components/regions/_body.scss#L6

**Comment by bspeare** [comment]
Is this still an issue?  It looks like we have `word-wrap: anywhere` on the `card-description` that might take care of this:

<img width="1451" alt="Screen Shot 2021-08-03 at 1 55 59 PM" src="https://user-images.githubusercontent.com/1036433/128070604-ae5cfbcf-ecce-4613-8910-3110be33b0e6.png">

**Comment by pyrello** [comment]
I'm cool with closing this.
