### ISSUE TITLE
og:image meta tag is not being populated for Grad homepage

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2978]
# Problem
The `og:image` metatag is not being populated for https://grad.uiowa.edu/. 

# Steps to reproduce
View source and confirm or use the FB scraping debug tool: https://developers.facebook.com/tools/debug/?q=grad.uiowa.edu

# Proposed solution
TBD

**Comment by joewhitsitt** [comment]
Working on https://github.com/uiowa/uiowa/issues/2169 I noticed this doesn't seem to be the issue anymore.

<img width="913" alt="Screen Shot 2021-03-22 at 3 19 02 PM" src="https://user-images.githubusercontent.com/4663676/112053242-19a00b00-8b22-11eb-9e3f-cd1eed156968.png">
