### ISSUE TITLE
linking to files from cards

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#2986]
# Story

As a SiteNow v3 user, I want to be able to link to files from the card component using autocomplete functionality similar to linking to nodes so that when my site goes live I don't have links with "stage.drupal" or "prod.drupal" in the url.

# Proposed solution

**Comment by joewhitsitt** [comment]
This should also be considered when working on https://github.com/uiowa/uiowa/issues/2873

**Comment by joewhitsitt** [comment]
Closing in favor of https://github.com/uiowa/uiowa/issues/4235
