### ISSUE TITLE
Pharmacy news migration

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#2987]
# Story

As a College of Pharmacy website owner, I would like news articles migrated from our existing website (https://pharmacy.uiowa.edu") to our new website (https://pharmacy.prod.drupal.uiowa.edu), so that site visitors can see past Pharmacy related news without the College of Pharmacy having to manually create hundreds of old news articles manually.

# Additional Info

>We would like to migrate all historical news articles from our current website to our new website, while also preserving backlinks. We have articles dating back to 2012.  See: https://pharmacy.uiowa.edu/news/archive

We need to create redirects from old paths to new as part of this migration.
 
>Ideally, we would also like hyperlinks removed from articles from 2016 and earlier. That is, links that appear within the articles themselves.

They are fine with just removing the links as part of the migration process, no need to provide a list of node id's that we removed links from.

# Proposed solution

**Comment by richardbporter** [comment]
I think this is blocked by #3205. I've almost got that to a point where it can be merged.

**Comment by richardbporter** [comment]
Sorry - poor planning on my part. There is a decent refactor of sitenow_migrate going on there.

**Comment by richardbporter** [comment]
Here are the fields on their D7 article content type:

- Title
- Body
- Image	
- Migrated	
- Custom Person Directory	
- Department	
- Audience	
- Category	
- Person	
- Title for Gallery	
- Gallery	

Only image, title and body have a direct destination. The term reference could maybe migrate to tags. I'm not sure about the others. Migrating images is a little tricky since we're not importing all images.

Any idea what fields they want?

> They are fine with just removing the links as part of the migration process, no need to provide a list of node id's that we removed links from.

Just delete the anchor element? Or unlink it but leave the text?

**Comment by briand44** [comment]
I will get clarification. My assumptions are we can ignore the following fields:

- Migrated
- Custom Person Directory
- Title for Gallery
- Gallery

I will ask about the reference fields:

- Department
- Audience
- Category
- Person

My understanding was unlink it but leave the text.

**Comment by richardbporter** [comment]
Some additional tasks to be done in #3190 

- [x] Debug ~~and fix~~ obscure errors on import.
- [x] Double check sticky setting is migrating correctly. First article listed on /news is old.
- [x] Set an image style on body images - too big.
- [x] Fix teaser markup characters still being printed on some articles.
- [x] Report internal links

**Comment by cory-skeers** [comment]
Only one article (original node 10636) was marked sticky, and was an old one. I just removed `sticky` from the mapping, assuming we should default all nodes to `0` for sticky if this one shouldn't appear first.

**Comment by richardbporter** [comment]
I fixed the link replacement functionality for links before 2016 which was not working and am now logging out internal links. I reverted the file_get_contents error suppression commit for now as well but hope to get back to it because the file paths seem wrong.

**Comment by richardbporter** [comment]
I'm now going to look at setting an image style for those inline images.

**Comment by pyrello** [comment]
@cory-skeers and @richardbporter Can I be of any assistance on this issue?

**Comment by richardbporter** [comment]
I think the `Unkown format` errors can be safely ignored as they do not seem to be memory related. It happens when the the file entity is saved only with certain images. I'm not sure what causes it, maybe imagemagick or something, but the file seems to be saved correctly and displays fine.

I think all thats left is the image styles for inline images. I'm working on that now and I'm looking to create a responsive image - if we have an example of that you could point me to, that would be great.

**Comment by pyrello** [comment]
I think the approach for setting the image style in this comment is still the right way to go: https://github.com/uiowa/uiowa/pull/3190#issuecomment-812667642

There may be something wrong about the implementation, but that is roughly what needs to be done just by looking at the output of how the image is represented in one of our D9 sites.

By selecting a view mode that maps to a responsive style is how you make the image responsive. The generation of the responsive image markup happens in the background and is not relevant to what gets embedded in the text field.

**Comment by richardbporter** [comment]
I don't think I'm using that `replaceInlineImages` method though. I'm using the regex with `entityReplace` since there are files, docs, etc.

**Comment by pyrello** [comment]
That's going to require adding a similar `data-view-mode` attribute to the `constructInlineEntity` function:

https://github.com/uiowa/uiowa/blob/c05630523a8d365227edb66a78d40195da167a2e/docroot/modules/custom/sitenow_migrate/src/Plugin/migrate/source/ProcessMediaTrait.php#L108-L118

**Comment by richardbporter** [comment]
Think I finally figured that out. Thanks.

**Comment by richardbporter** [comment]
@cory-skeers I have an example of the alignment not working in `processMediaTrait::entityReplace`. I was hoping you could take a look to see if finding the alignment is working correctly in general and this is maybe just an outlier.

The source node 10916 (https://pharmacy.uiowa.edu/article/distinguished-alumni-award-recipients-announced-0) has an image aligned left but the regex isn't finding it. I'm looking at the first image. Here is the match it is searching: 
```
[[{"fid":"24541","view_mode":"teaser","fields":{"alt":"Chrischilles","title":"Elizabeth Chrischilles","class":"media-element file-teaser media-wysiwyg-align-right","data-delta":"1","format":"teaser","alignment":"left","field_file_image_alt_text[und][0][value]":"Chrischilles","field_file_image_title_text[und][0][value]":"Elizabeth Chrischilles"},"type":"media","field_deltas":{"1":{"alt":"Chrischilles","title":"Elizabeth Chrischilles","class":"media-element file-teaser media-wysiwyg-align-right","data-delta":"1","format":"teaser","alignment":"left","field_file_image_alt_text[und][0][value]":"Chrischilles","field_file_image_title_text[und][0][value]":"Elizabeth Chrischilles"}},"attributes":{"alt":"Chrischilles","title":"Elizabeth Chrischilles","class":"media-element file-teaser media-wysiwyg-align-left","data-delta":"1"}}]]
```

Should it be regex'ing for `alignment`?

**Comment by richardbporter** [comment]
Actually, that looks like JSON. I don't know if it always is but maybe we could try to decode it into an array and check to see if a key/property is set?

**Comment by cory-skeers** [comment]
> Actually, that looks like JSON. I don't know if it always is but maybe we could try to decode it into an array and check to see if a key/property is set?

I think that should always be the case. Pretty sure the initial pass at looking for alignment was a quick fix for standard v1 sites. Decoding into an array should work--might have to check for a few different patterns, but that would be a lot easier to do with an array than a convoluted (but fun?) regex.

**Comment by cory-skeers** [comment]
Took a stab at it, and at least for the example provided (source node 10916) alignments seem to work. Need to check if we can always pull alignment from there, or if we need to check different spots.

It also depends on the (I believe correct...) assumption that the format is always `[[{JSON}]]`, but that should be what the original regex is looking for, so if that's false...I think we have bigger issues.

**Comment by cory-skeers** [comment]
https://pharmacy.uiowa.edu/node/13161 picked up an image as a plain, left-aligned inline image where the source has it inside a right-aligned block quote.

@richardbporter any expectations on dealing with quotes, captions, or the like, or is bringing it in as a simple image adequate?

**Comment by richardbporter** [comment]
> @richardbporter any expectations on dealing with quotes, captions, or the like, or is bringing it in as a simple image adequate?

No, just the image. Thanks for doing that! I'll check it out with my last change (hopefully).
