### ISSUE TITLE
As a visitor to arts.uiowa.edu, I can see past events so I can find virtual dates and times.

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#2998]
# Story

As a visitor to arts.uiowa.edu, I can see past events so I can find virtual dates and times.

# Proposed solution

- Change arts_events cron job to keep events for a longer period of time.
- Allow backwards navigation in the date picker
- Add past events views to the category pages
- Investigate options for long-running events with irregular date repeat rules on content.uiowa.edu and advise customers.

**Comment by joewhitsitt** [comment]
Started a feature branch on 703 `arts_past`

> Change arts_events cron job to keep events for a longer period of time.

arts_core handles this currently. deletes everything not in the year feed. past events are present until their last instance is past. now this is checking whether the end date has past today by 365 days and deletes. I'd like to monitor locally for a few days to see if it is really working by adjusting the expiration to -1 day.

> Allow backwards navigation in the date picker

done

> Add past events views to the category pages

added a new argument/button and performing a result reversal on the view for the end range being older than today.

> Investigate options for long-running events with irregular date repeat rules on content.uiowa.edu and advise customers.

🤷

**Comment by joewhitsitt** [comment]
@richardbporter can I get you to review this?

## To Test

- on uiowa703 locally, checkout `arts-past`
- sync arts.uiowa.edu and do all of that crazy d7 setup stuff (rr, /tmp, hloc)
- date pickers can now go into the past to select a date (max 1 year)
- there is a past button that takes you to a reverse sorted display of past events
- if you replace `$noexist` on line 88 of docroot/sites/arts.uiowa.edu/modules/custom/arts_core/arts_core.module with `$destination_list` and change `-365` to `-1` on line 95 you can run the importer to see that past events are cleaned up. This mimics a difference that the event no longer appears in the content.uiowa.edu year feed. nodes are looped through and those events older than a day are removed from the site.

## Customer Review

Does this need to go to DEV for customer review or can it just be pushed and communicated?

**Comment by richardbporter** [comment]
Yea I'll check this out today.

**Comment by richardbporter** [comment]
I was thinking only the "past" button would be 100% width. Otherwise it adds some extra spacing under the featured image:

![image](https://user-images.githubusercontent.com/1068523/114038761-c202de80-9847-11eb-81b6-ad1fc1ebc6d8.png)

> Does this need to go to DEV for customer review or can it just be pushed and communicated?

Probably. I'm curious about their thoughts on a few things like the reverse order of past events. 

> if you replace $noexist on line 88 of docroot/sites/arts.uiowa.edu/modules/custom/arts_core/arts_core.module with $destination_list and change -365 to -1 on line 95 you can run the importer to see that past events are cleaned up. This mimics a difference that the event no longer appears in the content.uiowa.edu year feed. nodes are looped through and those events older than a day are removed from the site.

Not sure I understand this change. Maybe we could talk in person.

**Comment by joewhitsitt** [comment]
The buttons weren't flexed before and I didn't want to try to get the theme to compile. I took a short cut and made a one line change in three places... are you sure the spacing is from the buttons or the long featured title overflowing?

I can walk you through the expiration testing via call. It was a pain to test otherwise

**Comment by joewhitsitt** [comment]
Customer approved. Deployed with `tags/2021-04-16`

**Comment by richardbporter** [comment]
Sorry but I overlooked how important deleted events are to this site. The context for the feed importer is `/result/events/item/event/event_instances/item/event_instance` so it relies on deleting events from the source to "update" events when times change because each event_instance maps to different node. When times change, an event instance is removed and a new one added so its not possible to keep that mapping. 

They could manually delete these but would need training/permissions and a code change. I'm trying to think if there is a way to alter the after_import code to make this work but I'm not sure its possible. Rolling back might be easiest for now.

**Comment by richardbporter** [comment]
Rolled back for now.

**Comment by richardbporter** [comment]
I think the structure of the site would have to change. We'd probably need to adapt whatever structure other D7 sites with feed importers are using. I'm guessing that is moving away from the separate node-per-instance model into one event with a multi-value date field. The representative node views would need to be rebuilt. I'm sure there is other work that I can't think of right now.

**Comment by bspeare** [comment]
At our meeting this week for performingarts.uiowa.edu, they mentioned that they are hoping that their new site will replace this site.  Since they don't plan on any future development work can we close this issue @briand44?

**Comment by briand44** [comment]
Yes
