### ISSUE TITLE
As a visitor to pharmacy.uiowa.edu, I can get redirected from old directory person pages to new directory person pages.

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#2999]
# Story

As a visitor to pharmacy.uiowa.edu, I can get redirected from old directory person pages to new directory person pages.

# Problem
The current pharmacy directory nests person pages under /directory/person/{slug} while the new APR directory only nests them under whatever is configured as the the directory path. Webmasters could create redirects for each person but that would tedious. We could create the redirect in the htaccess file but if the destination ever changes, the redirects will break.

# Proposed solution

Investigate ways for webmasters to bulk import lots of redirects or create wildcard redirects that forward the path along to the destination. If thats not feasible, create the redirect in htaccess with the caveat that the APR directory config cannot change without notifying us.

**Comment by richardbporter** [comment]
Update: htaccess and be done with it.

**Comment by richardbporter** [comment]
I was able to write a migration for this in #3190 which was pretty easy. It imported 1700+ redirects. Anyone have thoughts on if that approach is ok?

**Comment by joewhitsitt** [comment]
my only concern if it is able to find and reduce duplicates. if duplicates, does it cause problems

**Comment by richardbporter** [comment]
Cut it in half by filtering people to published at the source. I wouldn't expect duplicates as the path alias would be -0 or something.
