### ISSUE TITLE
Drawer menu getting cut off on shorter screen height

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#3010]
# Problem
This issue was reported on the Graduate College site:

<img width="959" alt="Drop Down Menu" src="https://user-images.githubusercontent.com/709009/106757079-92401c00-65f5-11eb-978f-c59cc631d763.png">

As can be seen in the image, the links at the bottom are cut off and inaccessible despite being scrolled all the way down.

# Steps to reproduce
Visit https://grad.uiowa.edu and resize window to similar dimensions as shown in the image above. Click the menu button to open the drawer menu. Click the "Info for" link. Attempt to scroll to and click on "Alumni & Friends."

# Proposed solution
TBD

**Comment by dnkemper** [comment]
Note: Chrome looks/works as should. Can reproduce in Firefox.

**Comment by dnkemper** [comment]
Update: Chrome looks/works as should locally. Can produce bug in prod if have browser window full width, open menu and expand one of the menu sections, then scale window down to a smaller size. (shoutout to Sean for the step order)

**Comment by bspeare** [comment]
@dnkemper playing around with the dev tools, this seems to help:

```
// Firefox only
@-moz-document url-prefix() { 
  #superfish-main-accordion {
    padding-bottom: 300px !important;
      @include breakpoint(sm) {
         padding-bottom: 100px !important;
      }
   }
}

// Extra padding to help other browsers
.o-canvas--open .o-canvas__drawer {
    padding-bottom: 300px;
   @include breakpoint(sm) {
         padding-bottom: 100px;
      }
}
```

**Comment by dnkemper** [comment]
@bspeare YOU. ROCK. THANK YOU THANK YOU THANK YOU!
