### ISSUE TITLE
Create Transfer Tips content type for Admissions website

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#3011]
# Story

As an Admissions Site owner I want to be able to create Transfer Tips so that that information is available to prospective Transfer students.

An example of this can be seen by visiting this page: https://admissions.uiowa.edu/academics/accounting; scroll down to the Admissions Requirements section, then click on the Transfer Students tab.

# Proposed solution

- [x] Separate content type (title/body/path pattern)
- [x] Entity reference on AoS that then displays on the transfer admissions requirements card
- [x] Must be in the correct form order https://github.com/uiowa/uiowa/issues/3108
- [x] See below

## Updated path to success

- [x] Add a required reference field to transfer tips that references a single AoS. 
- [x] This reference should display as a back link to the AoS on the full/teaser view modes.
- [x] Remove the transfer tip field on AoS
- [x] Remove the current logic in admissions_core that looks for the field to pass path data to the template. Leave the template as-is.
- [x] Pattern should be /academics/[area-of-study-title]/transfer-tips for now
- [x] A transfer tips presave function should update the title to be "[Area of Study] Transfer Tips", hide the title field on the form. This way it is distinguishable content on both the node and the content overview.
- [x] Update the admissions split to reflect the field changes on AoS and Transfer Tips
- [x] Setup basic SEO settings for the transfer tips content type (Ahem probably need to revisit a couple other content types later on :cough: scholarships, etc.). No need to go full field_teaser with this. Yet. Meta description and the related SEO description fields should have a default "Transfer tips for [Area of Study Reference Label Token] at Iowa" that can be overridden by webmasters at least. Identify this new configuration and admissions split it.
- [x] "Transfer Tips List" views block (admissions core category) needs to be created with a list of linked titles that should be available in LB assuming the category is correct. A webmaster should be able to see and place this views block. For reference their current list: /transfer-plan but no accordion is needed and this will be placed on a basic page so header text can be supplied.
  - [x] The title for each row should just be the AoS label but link to the transfer tip.
- [x] Rework the transfer requirement card preprocess to query transfer tips that have the AoS as the reference. Since multiple references _could_ exist, just grab the first result and link to that.

**Comment by joewhitsitt** [comment]
>my original thought on that issue was to preprocess the transfer requirement paragraph, look for the node field data (transfer tips) if it existed pull it into the transfer paragraph based on the mockup

**Comment by joewhitsitt** [comment]
Based on the Admissions meeting, we might need to move the reference to the transfer tip and reference the AoS to get all of this other stuff wired up (title, back link, meta, view listing). This will of course change how we find/get the transfer tip on the Transfer Admissions Requirement Card

**Comment by joewhitsitt** [comment]
Updated issue summary. This should be re-pointed for accuracy of the work left to do.

**Comment by dnkemper** [comment]
Thank you so so much for all of your help, @joewhitsitt
