### ISSUE TITLE
Error for Webform: Memcache API and Integration 2.2

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#3030]
# Problem
As @makurj reported, sites are showing this error on the status report page:

`Memcache API and Integration 2.2 is causing unexpected regressions for the Webform module. Please consider downgrading to Memcache API and Integration 2.1 and following Issue #3176519: Uploaded files not linking correctly in emails sent through Webform module after upgrading to memcache 2.2.`

# Steps to reproduce
Go to https://admissions.prod.drupal.uiowa.edu/admin/reports/status or https://italymba.tippie.uiowa.edu/admin/reports/status. 

# Proposed solution
Upgrade to https://www.drupal.org/project/webform/releases/6.0.1 which has the fix from 3175525

**Comment by joewhitsitt** [comment]
Related:
https://iowaweb.slack.com/archives/C8SM82ZFZ/p1611247118003800
https://www.drupal.org/project/memcache/issues/3176519
https://www.drupal.org/project/webform/issues/3175525

I think the solution is to upgrade to https://www.drupal.org/project/webform/releases/6.0.1 which has the fix from 3175525

**Comment by joewhitsitt** [comment]
Webform settings are split across a couple sites

**Comment by joewhitsitt** [comment]
This should roll into to and be tested with https://github.com/uiowa/uiowa/pull/2983

**Comment by joewhitsitt** [comment]
I believe updating the module resolves the issue. It at least removes the error message from the status report.

**Comment by richardbporter** [comment]
A customer reported that although the error message is gone, the regression with the file links in emails remains. Others are reporting this on https://www.drupal.org/node/3175525.

**Comment by richardbporter** [comment]
I can reproduce this on dev but not locally.

**Comment by richardbporter** [comment]
I'm not sure downgrading memcache is an option looking at the diff. I can reproduce this locally now.

**Comment by joewhitsitt** [comment]
sry 😞

**Comment by richardbporter** [comment]
Email file link regression might be fixed by https://www.drupal.org/project/memcache/releases/8.x-2.3. I can test it out locally as time allows.
