### ISSUE TITLE
Manually move sitenow.uiowa.edu to v3

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#3033]
# Story

As an owner of sitenow.uiowa.edu, I want to be on SiteNow v3 because it is amazing and so that we can provide better examples of v3 components in our v3 documentation.

# Some Thoughts
I believe there is some custom functionality as part of our webforms that we will need to account for.

Not sure if these are in scope but eventually we would like to provide a portfolio of v3 sites for potential and existing v3 customers to view as examples. It may be nice to have different categories of examples (lab, org, college, dept, etc).

We may also want to provide examples of style options for each component in our v3 docs.

# Proposed solution

- [x] Provision a v3 site in stage environment
- [x] Manually recreate content on v3 site
  - Use headings instead of bold/uppercase text. Better for a11y and allows anchor ids to be added.
  - Since we aren't in a content freeze during this. Pay attention to the recently updated content overview page for changes since this task was started.
- [x] Account for custom developed functionality in our webforms.
- [x] Launch
- [x] Backup/import site request submission data - https://www.drupal.org/node/3040513
- [x] Remove v2 site

https://wiki.uiowa.edu/display/drupaldev/Writing+best+practices+for+sitenow.uiowa.edu

**Comment by ethanstjohn** [comment]
This website is ready to be reviewed.
https://sitenow.stage.drupal.uiowa.edu/

**Comment by joewhitsitt** [comment]
@ethanstjohn thanks for working on this. I haven't done a full review, but a few things:

- There has been new content/edits that haven't been captured on the new site. I would look at the content overview of the current site to find these. Updates from March (new), Known Issues ([edit](https://sitenow.uiowa.edu/node/196/revisions)). We didn't know if we were in a content freeze period.
- The newsletter signup on the homepage needs to be placed in a full_html text area or it will get stripped.
- We used anchor ids a lot on the site and have linked to them. (e.g. https://sitenow.uiowa.edu/known-issues#uiowa-issue-3167, https://sitenow.uiowa.edu/policies#domains-vanity). I know there isn't a unique id field on v3, but you can add these as id attributes on headings.
- Can you change the articles to have the same date as the original https://sitenow.stage.drupal.uiowa.edu/news?
- `Account for custom developed functionality in our webforms` - Did you want to try and take on porting this over?

**Comment by e-marie-w** [comment]
Finished going over the site, these are the pages with differences/things to update that I noticed:
  - Home - add newsletter sign-up form
  - News - add March, April, May (once published) Update articles, also update dates on articles to match original publish date
  - Known Issues - some styling differences
  - FAQs - update text and a few links 
  - Policies - some styling differences
  - WYSIWYG - update content order
  - Basic Page Content Type - text box color different
  - Articles Block - articles path link needs to be updated 
  - Events Block - add display past events paragraph
  - Banner Block- fix image specifications anchor link 
  - Card Block- fix image specifications anchor link 
  - Collection Block - remove excess text from title
  - Event Block - update content 
  - Featured Content Block - needs to be added
  - Image Gallery Block- fix image specifications anchor link 
  - People Block - add additional content & update order of existing content 
  - Statistic Block - add Block Restrictions paragraph 
  - Text Area Block- fix image specifications anchor link 
  - More..Blocks - update Webform Documentation link, tokens link needs to be fixed as well 
  - Cards - fix image specifications anchor link 
  - Carousel - fix image specifications anchor link 
  - Events - update content 
  - Image Gallery - fix image specifications anchor link 
  - People - 'people that have been previously tagged' links to article content type, I assume should be person content type instead?
  - Article Content Type - fix link to image specifications
  - Person Content Type - fix link to image specifications
  - Social Media Embed - update layout format
  - How to Create a Webform - update link to Advanced webform configuration
  - Search Engine Optimization - extra box
  - Request a Site - banner different 
  - Contact Us - update form, add Training link to side column 

I'll start with content changes and the anchor links.

**Comment by dnkemper** [comment]
@e-marie-w NICE 👏 👏 👏

**Comment by e-marie-w** [comment]
Just want to check I understand what to change regarding headings. For pages like https://sitenow.uiowa.edu/documentation/basic-page-content-type I would turn the bold/all caps text into a non-bolded, title case heading 3 (since heading 2 already in use). So, it ends up looking like this https://sitenow.stage.drupal.uiowa.edu/documentation/basic-page-content-type. 
Also, anchor ids - do I only add one if there's an existing link to that section, or should I pre-emptively set them for all the headings?

**Comment by joewhitsitt** [comment]
Thanks for working on this @e-marie-w 

Using headings allow screen readers to tab through content easier and are easier to target if styles change. It also allows us to use bold within a paragraph and have it stand out from the other text. So yes, I think that is a change we want to make if possible.

I would only make sure existing ids are captured as we have linked to those. If you think there is a section worth setting an id for, I don't think anyone will stop you.

**Comment by e-marie-w** [comment]
Thanks @joewhitsitt! I think I get it now. So something like the [Card Block page](https://sitenow.uiowa.edu/documentation/layout-builder/card-block) would keep the bolded choices under Display Options as-is, since they're part of paragraphs with normal text. It's only when the bolded text is on its own line that it should become a heading.

**Comment by joewhitsitt** [comment]
technically, those could become headings as well, but I don't think it is necessary to go that granular when it comes across as an unordered list of information.

**Comment by e-marie-w** [comment]
Broken Links (v2 site linked here, do we want to update them for just the v3 site or here as well?):

- [Policies ](https://sitenow.uiowa.edu/policies)page links to https://www.flickr.com/photos/uinews/. Assuming there's no replacement flickr account I'll just remove it from the resource list.
- [Policies ](https://sitenow.uiowa.edu/policies)also links to https://itaccessibility.uiowa.edu/web. Do we want to change it to just https://itaccessibility.uiowa.edu/ or something like https://itaccessibility.uiowa.edu/web-standards? 
- Both the [Articles Block ](https://sitenow.uiowa.edu/documentation/layout-builder/articles-block) and the [People Block ](https://sitenow.uiowa.edu/documentation/layout-builder/people-block) link to pages on https://default.local.drupal.uiowa.edu/ when talking about using SiteNow paths. I assume they should link to [SiteNow Articles](https://sitenow.uiowa.edu/documentation/sitenow-articles) and [SiteNow People](https://sitenow.uiowa.edu/documentation/person-content-type/sitenow-people) instead.
- [More...Blocks](https://sitenow.uiowa.edu/documentation/layout-builder/more-blocks) also links to https://default.local.drupal.uiowa.edu/ when talking about tokens and I'm not sure what the replacement link should be. 

Besides the tokens thing I feel confident about the rest but wanted to run it past someone before I changed anything.

**Comment by joewhitsitt** [comment]
To replace flickr, https://brand.uiowa.edu/imagery could be a useful resource but I think Photoshelter is the only pool of photos now.

I'd vote https://itaccessibility.uiowa.edu/web-standards

Correct about the articles and people blocks.

For the tokens, i'd unlink and say: "You may use tokens. See _Browse Available Tokens_ below for more information"

**Comment by e-marie-w** [comment]
On pages like https://sitenow.uiowa.edu/documentation/basic-page-content-type, should some of the extra whitespace be preserved? Visually it might look better but will it cause issues with screen readers or anything? Changing the caps/bold to h3 and h4 helps but keeping the extra blank line before a new h2 section still looks nice: https://sitenow.stage.drupal.uiowa.edu/documentation/basic-page-content-type. I just want to be sure it doesn't cause any issues.

**Comment by joewhitsitt** [comment]
Screen readers will navigate over blank markup but ideally typography spacing between headlines and paragraphs should be handled in the design system for all sites. If you have specific spacing suggestions, you could create an issue in https://github.com/uiowa/uids. I wouldn't add blank paragraphs _just_ to create separation.

**Comment by e-marie-w** [comment]
Thanks Joe, that answers my questions perfectly!  I'll take out the blank paragraphs on that page and any others. The current spacing system looks fine to me, seeing the repeated blank lines just made me wonder if it was on purpose/wanted.

**Comment by e-marie-w** [comment]
I've removed the excess whitespace from all the pages, but on the [WYSWYG page](https://sitenow.stage.drupal.uiowa.edu/documentation/wysiwyg) the images do cause some of the headings to be indented without an extra blank line, is that okay?  

Other things:
- Old [Contact Us](https://sitenow.uiowa.edu/contact-us) page vs. new [Contact Us](https://sitenow.stage.drupal.uiowa.edu/contact-us) - I just removed the heading as otherwise there was a gap between the text area block and the webform block. 
- [v2 Training page](https://sitenow.uiowa.edu/training) -  since event is past and we're focusing on v3 now, is page/webform needed on new site? 
- [Future Enhancements](https://sitenow.uiowa.edu/future-enhancements) - this page is in draft, should it be kept in draft on new site or changed? 
- ~[Request a Site](https://sitenow.uiowa.edu/request-site) - if not logged in, this page displays a message about needing to log-in. This message is outside of the webform and above the page title, so I'm not sure where to create it and set the conditions. Note: the webform is already hidden if not logged in, it's just the message that is missing on the new site.~ Rick helped me with this, turns out it's a user log-in block, should be on v3 site now.
- [Home page](https://sitenow.uiowa.edu/) - still needs the newsletter sign-up section. It was mentioned this had to be done in full html which isn't an option for me from layout builder. There was also a mention in stand-up of testing some method out on this, let me know which option to pursue/how to pursue it.

**Comment by joewhitsitt** [comment]
Thanks for your continued work on this.

Contact - Sounds good.
Training - The form is closed which is good. https://webcommunity.sites.uiowa.edu/training is now the home for training so we should point to and highlight that.
Future - You can delete that. https://webcommunity.sites.uiowa.edu/web-team/backlog is what we reference now.
Home - An admin can place the script whenever. The other method is farther off I think: https://github.com/uiowa/uiowa/issues/3302

WYSIWYG page. That page is in need of editing. Additional spaces where those image are could help in the short term. Sorry for the flip-flop.

**Comment by briand44** [comment]
>Home - An admin can place the script whenever. The other method is farther off I think: #3302

It isn't that far off. We will likely discuss in grooming tomorrow.

**Comment by e-marie-w** [comment]
I deleted the Future page and removed the v2 training form from the v3 site. The training website is linked on the Contact Us and FAQ pages I know. I also added spacing back into the WYSIWYG page and updated the Known Issues page as that was updated last week.

**Comment by e-marie-w** [comment]
Checked out [webform migration page](https://www.drupal.org/node/3040513) from meeting. Process seems simple enough, issue is I don't have option to upload data to webforms. Comment on video mentioned needing to enable Webform Submission Export/Import under Extend. Not sure where that setting is or if it's something I can update. The upload option could be an admin only thing too, I'm not sure.

**Comment by e-marie-w** [comment]
Webform migration works (thanks Joe for activating it!). Data for Request a Site webform all moved, having some trouble with Contact Us webform. The 495 most recent submissions move fine, but there's 159 earlier ones that are not showing up despite also being in the uploaded CSV. 

Update: Nevermind got them all migrated over. Apparently 495 was the upload limit? I reversed the order of the records and the last 159 were added just fine. All 654 records are showing, Contact Us form data migration now done.

**Comment by joewhitsitt** [comment]
Added the newsletter widget for now. I need to add the login stuff to the request site form.

**Comment by joewhitsitt** [comment]
k. got the site split enabled and things seem to be firing.

**Comment by e-marie-w** [comment]
Right now request site webform is not showing for me even after logging in, but that might just be a permissions thing. The alert to log-in and the link to do so work fine.

**Comment by joewhitsitt** [comment]
Launched - https://sitenow.uiowa.edu/
