### ISSUE TITLE
Investigate reported downtime.

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#3039]
# Story

As a member of the web team, I would like to understand what caused the reported downtime, so we can avoid future downtime.

# Additional Info
https://insight.acquia.com/support/tickets/1128014

# Proposed solution

- [x] dig into New Relic a bit more to see if we can isolate these external calls.

**Comment by richardbporter** [comment]
The external calls to content.uiowa.edu were a red flag to me initially but digging deeper thats only because the response time was slow not the amount of calls made.

**Comment by richardbporter** [comment]
I contacted ISPO for helping parsing Splunk. 

Looking through the logs myself, it seems like a perfect storm of bots, siteimprove linkcheck, cron, autodiscover and another MS-related active-sync entry.

**Comment by richardbporter** [comment]
I'm going to close this so we don't spend too much time on it, especially considering it was ephemeral and did not trigger any Acquia monitoring.

I think #1310 and #3059 are more concrete issues that we can follow this up with.
