### ISSUE TITLE
Blog entry migration followup

### ISSUE THREAD

**Issue by cory-skeers** [uiowa/uiowa#3052]
Followup to #2792 -- pull in categories, allow `<pre>` tags and update content.

# Proposed solution

Categories didn't get pulled in, but we have a mapping of all old nids to new nids. Create a followup migration to create tags and add them to the proper nodes.
Allow `<pre>` in `filtered_html`, then update nodes that used it previously.

**Comment by cory-skeers** [comment]
Looks like only 12 nodes used `<pre>` on the old site, so likely easiest to manually update once that tag is allowed.

Edit: And it looks like the tags are preserved, so once they're allowed those 12 nodes will be up-to-date.

**Comment by pyrello** [comment]
@cory-skeers Is this issue closed by #3055 and #3058?

**Comment by cory-skeers** [comment]
@pyrello I need to run the migration and sync it up to prod yet before it'll be fully ready to close.

**Comment by cory-skeers** [comment]
Migration (categories followup) completed 🚀
