### ISSUE TITLE
Implement UIDS styles on APR profile pages

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#3056]
# Problem
APR font sizing seems to be off. I think this is because heading elements are used. However, I don't think we can change that.

# Steps to reproduce
https://pharmacy.prod.drupal.uiowa.edu/people/aliasger-k-salem
https://pharmacy.prod.drupal.uiowa.edu/people/jay-d-currie

# Proposed solution
Would it be possible to match the heading font sizes a little more closely with the sizes used for Tippie? 
 
Tippie
https://tippie.uiowa.edu/people/pamela-g-bourjaily

**Comment by bspeare** [comment]
Maybe this isn't a bug?  I think we just need to plan time to invest in making the profile to use some styles and headings from UIDS.

**Comment by bspeare** [comment]
Denny is working on updating the page styles to look like UIDS.   Maybe we don't need this issue and we should just wait for that update?

**Comment by richardbporter** [comment]
This is still a thing that we will need to do.
