### ISSUE TITLE
[Grad College] Mentor pages are showing credentials twice

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#3061]
# Problem
On mentor pages, the person's credentials are showing twice. I changed the way mentor page titles are generated to use the mentor's credentials, which is different than how other person type content types are handled.

# Steps to reproduce
https://grad.uiowa.edu/dei/srop/mentors/gordon-buchanan-md-phd

# Proposed solution
TBD

**Comment by richardbporter** [comment]
It looks like this is being done in multiple places:

- https://github.com/uiowa/uiowa/blob/1c254b98137cd3cf835ad36bb374fe96188f3ae8/docroot/modules/custom/layout_builder_custom/src/EventSubscriber/SectionComponentSubscriber.php#L60
- https://github.com/uiowa/uiowa/blob/39f7dc098efa125fb459ca69a48e2a58fe1ee661/docroot/sites/grad.uiowa.edu/modules/grad_core/grad_core.module#L15-L26

Let me know which one is preferred and I can move forward. I would probably also move the field template to grad_core from uids_base.

**Comment by pyrello** [comment]
In the first case, I think we are changing the output prior to display. In the second, we are changing the value of the title of the node prior to saving.

I think the first method is the better method of handling it. But changing the logic in the second one require an update hook to re-save all the mentor nodes.

If anyone else has any thoughts on whether it is preferable to store the credentials as part of the title of the node, I would be curious to hear it.

**Comment by briand44** [comment]
I would avoid storing the credentials with the title, I would be in favor of just displaying them together on output.

**Comment by joewhitsitt** [comment]
so the first applies only to layout builder. what about teasers? I think displaying them together in a preprocess (node/layout/etc) or in template markup makes it more flexible based on the condition.

**Comment by richardbporter** [comment]
Another thing to note is here I spent quite a bit of time debugging this and did not realize there was code in layout_builder_custom affecting it. Putting all kinds of code in there makes it a little harder to debug things especially for site-specific issues.

Removing the LBC code "fixes" this pretty quickly... :)

**Comment by joewhitsitt** [comment]
>Removing the LBC code "fixes" this pretty quickly... :)

FYI, we are using this for the main person content type, etc.

**Comment by pyrello** [comment]
Thanks for the feedback. I think based on that, I would go with the route of removing the addition of credentials to the title prior to saving the node in `grad_core.module`. And the update hook 😐

**Comment by richardbporter** [comment]
> > Removing the LBC code "fixes" this pretty quickly... :)
> 
> FYI, we are using this for the main person content type, etc.

Can you point me to that?

**Comment by pyrello** [comment]
@richardbporter In the first snippet you provided above, that is affecting the person content type. Any content type with credentials field, actually.
