### ISSUE TITLE
Remove temporary claro node form CSS

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#3066]
# Motivation

#3065 introduced a temporary CSS override to "fix" an issue that was introduced in 9.1 with the node form in Claro. There are open issues to address this issue:
* https://www.drupal.org/project/drupal/issues/3184667
* https://www.drupal.org/project/drupal/issues/3181964
* https://www.drupal.org/project/drupal/issues/3076820

# Proposed solution

Whenever a workable fix drops via the above issues and we update to that code, we can remove the changes introduced in #3065.

**Comment by richardbporter** [comment]
I know this is temporary but I forgot when reviewing this that the sitenow profile also includes admin CSS styles. Just making a note of that here.

https://github.com/uiowa/uiowa/blob/main/docroot/profiles/custom/sitenow/css/admin-overrides.css

**Comment by pyrello** [comment]
Good call. We might want to consider moving these to `uiowa_core`.

**Comment by joewhitsitt** [comment]
This was removed in #7098 but re-introduced in #7044 https://github.com/uiowa/uiowa/pull/7044#issuecomment-1838827587 because there isn't another non-layout builder custom css file that gets loaded for node add/edit forms.
