### ISSUE TITLE
Button style not appearing in v3 text area block

### ISSUE THREAD

**Issue by ethanstjohn** [uiowa/uiowa#3078]
# Problem
Buttons don't appear to work in SiteNow v3 text area blocks. I found this bug when moving the SiteNow website from v2 to v3.

# Steps to reproduce
Go to a text area block on a SiteNow v3 website and style in a button.

# Proposed solution

- [ ] Update the Linkit modal overrides in docroot/modules/custom/sitenow_media_wysiwyg/js/button_style.js to be UIDS specific.
- [ ] Programmatically update v2/v3 websites similar to the media markup update https://github.com/uiowa/uiowa/pull/3048

**Comment by joewhitsitt** [comment]
Either we can update the modal to use uids syntax and use what have learned with https://github.com/uiowa/uiowa/pull/3048 to update all existing or we need to add the same btn* coverage to v3 text areas.

**Comment by bspeare** [comment]
Here's a live site with the `btn` not working: https://coronavirus.uiowa.edu/returning-work/signage-flyers-and-communication-guides.   Perhaps we should move the `btn` styles to https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/scss/components/button.scss?

**Comment by bspeare** [comment]
The kitchen sink page: https://sandbox.prod.drupal.uiowa.edu/kitchen-sink will be good for testing this.  We could add all of the `btn` variations to each section for testing.   Do we know what class variations we need to use?

**Comment by bspeare** [comment]
Most of the button background color overrides are in https://github.com/uiowa/uids/blob/main/src/components/button/button.scss.

**Comment by joewhitsitt** [comment]
This was noticed during the coronavirus conversion to v3. Now that those sitenow v2 styles aren't loaded there are a lot of broken buttons. They plan to workaround them for now so I don't know if changes priority.

<img width="1150" alt="Screen Shot 2021-02-16 at 5 09 17 PM" src="https://user-images.githubusercontent.com/4663676/108133205-ceee2780-7079-11eb-8a7f-7f0c3a2beec4.png">

**Comment by joewhitsitt** [comment]
> Programmatically update v2/v3 websites similar to the media markup update #3048

I worry about this method as we found return characters in content afterwards. We didn't pin it on #3048 but we didn't rule it out. I wonder if a db update would be faster/easier

**Comment by joewhitsitt** [comment]
I tried to get rid of the linkit button presets stuff and just use the ckeditor style dropdown, but it doesn't seem to like:
```
a.bttn.bttn--primary.bttn--caps|Button Primary
a.bttn.bttn--secondary.bttn--caps|Button Secondary
```
Instead it works if it is:
```
a.bttn.bttn--primary|Button Primary
a.bttn.bttn--secondary|Button Secondary
```

So, I think it has to do with how the style is represented in the CSS file.

**Comment by joewhitsitt** [comment]
https://github.com/uiowa/uiowa/issues/3078#issuecomment-821572405

Update: classes needed to be in alphabetical order... 🤷

**Comment by joewhitsitt** [comment]
Moving forward with the styles dropdown in CKEditor instead of relying on the LinkIt workaround. Need to split for HR and provide the same but for bootstrap.
