### ISSUE TITLE
IE 11 - Content/Footer overlap

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#308]
Sent by an IE 11 user. This would most likely need to be tested on the Window machine in the office with Microsoft Edge, emulating IE 11. Inspect the markup/styles and see what is causing this.

Can't confirm whether the user was in IE Compatibility mode or not.

![thumbnail_image001](https://user-images.githubusercontent.com/4663676/60730025-c3cc9f00-9f09-11e9-8082-24e21642cd79.png)

Example URL:
https://hr.prod.drupal.uiowa.edu/development/staff-language-and-culture-services

**Comment by ethanstjohn** [comment]
This seems to be a bigger issue than first glance. The whole hr.prod.drupal.uiowa.edu website is off.

**Comment by joewhitsitt** [comment]
just in IE 11 though right? i can't reproduce with my mac browsers. i would start poking around the flexbox related styles/classes in the global regions like main-content, footer. we might be implementing something for the sticky footer that doesn't jive with IE 11.

**Comment by ethanstjohn** [comment]
There are issues in all verisons of IE. Some versions had very different placements.

**Comment by ethanstjohn** [comment]
By unchecking some css styling parts of it a sort of fixed, but I'm still looking for what is specifically causing the problem.

**Comment by joewhitsitt** [comment]
IE 11 has partial support of flex box. https://caniuse.com/#search=flex

We are implementing a sticky footer via flex-direction: column that IE can't calculate very well.

By attaching `flex: auto 1 0;` to `.dialog-off-canvas-main-canvas` div element (not a very good item to target) this seems to fix the issue. Looks like the flex-shrink was applied to the wrong element: https://github.com/uiowa/uiowa_bootstrap/commit/11a97a7fa16e15678587a1d6f1a4880f903f3d60#diff-bfb68f5ce10ce32ed994c6fd28c01106

We should look into establishing this wrapping div correctly closer to classy's default
