### ISSUE TITLE
College link on Areas of Study should link to a page with other areas of study for that college.

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#3081]
The existing admissions website has a taxonomy for Colleges that contains additional information about the college including title, text, photo, link to college website and areas of study for that college. They would like something similar on their new site. The link to the College page can be output as the first item of the related links section.

https://admissions.uiowa.edu/colleges/college-liberal-arts-sciences

# Proposed solution
- [ ] Add an entity reference field labeled college to the Area of Study content type
- [ ] Must be in the correct form order https://github.com/uiowa/uiowa/issues/3108
- [ ] Create a view with the following constraints:
  - [ ] Filtered to just nodes of type Area of Study
  - [ ] Contextual reference limiting to just Area of Study items that reference a particular page node
  - [ ] Set contextual reference to get the node ID from the current page
  - [ ] Create a block display

**Comment by briand44** [comment]
Added blocked label for investigation issue #3095

**Comment by pyrello** [comment]
It occurred me that the the plan that was articulated above isn't fully fleshed out. We have to figure out how to get a link on the Areas of Study page that links to the corresponding College page that will be created. This can't be done by just adding the college field to the AoS content type, as there will be no connection between the college page that is created and the college field that is set on the AoS node. So we need to figure that out to proceed with this.

**Comment by pyrello** [comment]
I updated the plan for this. Basically, we are just going to skip using the Colleges field that we developed in favor of just creating and referencing pages.
