### ISSUE TITLE
sitenow.uiowa.edu - Update resend emails to use site email for replyto

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#3088]
Replyto is now a required field in core's mail which webform uses. we have "default" set for replyto which is supposed to pull from the "from" field which we have the site email token set for. this isn't working.

## Proposed solution

update the resend email templates (active db) to use the site email dropdown option. If that doesn't work try a custom value with the same site email token used for "from"

**Comment by richardbporter** [comment]
Its set to default and the form says it should use the from address then. Doesn't seem like that is working...

**Comment by joewhitsitt** [comment]
This is done.
