### ISSUE TITLE
Card template incorrectly printing card description.

### ISSUE THREAD

**Issue by GaryRidgway** [uiowa/uiowa#3090]
# Problem
[As shown here](https://github.com/uiowa/uiowa/blob/a1b887d0cd14bbd4c2492d747155de1aaa11e25b/docroot/themes/custom/uids_base/templates/uids/card.html.twig#L99), Cards assume card text to be able to be placed in a `<p>` tag. As the card description field is a WYSIWYG field, it has wrapping html tags. `<p>` tags, by design, can only contain inline elements, and none with wrapping tags. Because of this, any WYSIWYG data is reprinted once it hits the HTML parsing of the page, and is printed as a sibling to the `<p class="card__description"></p>` tag, example shown here:

![Screen Shot 2021-02-16 at 12 18 45 PM](https://user-images.githubusercontent.com/23122142/108104761-4e1b3580-7051-11eb-959f-edabfb2b96b8.png)

# Steps to reproduce
Add a description in the WYSIWYG to a card and observe whether it is printed in the `<p class="card__description"></p>` tag.

# Proposed solution
change the `<p class="card__description"></p>` tag to `<div class="card__description"></div>`

**Comment by GaryRidgway** [comment]
Look at the uids implementation and map this to how that template is printing

**Comment by bspeare** [comment]
I don't think we are using that class anymore.    The class is not used on https://github.com/uiowa/uids/blob/main/src/components/card/card.scss or https://github.com/uiowa/uids/blob/main/src/components/card/_card-mixins.scss.

It is in use here in `uids_base` which might be something that we didn't remove at the time:

- https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/scss/components/card.scss#L93
