### ISSUE TITLE
As a site owner, I can add content to an area of study page and expect only the sections containing content to display

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#3092]
# Story

As a site owner, I can add content to an area of study page on admissions and have sections render only if there is content entered in each field. 

Currently, the view block and the "Admission Process" section display if there is not content in each section.

<img width="1739" alt="Screen Shot 2021-02-16 at 12 47 05 PM" src="https://user-images.githubusercontent.com/1036433/108107829-5ffed780-7055-11eb-944b-ade9dd2f24b9.png">

# Proposed solution

- Update view block settings to not render if empty
- Find a solution for not rendering the "Admission Process" section if there is not content in the fields

**Comment by joewhitsitt** [comment]
This is part of the problem with the AoS information view block: https://www.drupal.org/project/drupal/issues/953034

Also, thinking ahead, if transfer tips are supposed to render in the transfer card then this adds a bit more complexity to the visibility of the admissions requirement region.
