### ISSUE TITLE
Investigate College Config Entity Listing pages for referencing entities

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#3095]
Investigate options for handling college config entity lists related to request from Admissions for taxonomy like pages listing references to it.

Examples of these pages on the current Admissions site:
* https://admissions.uiowa.edu/colleges/tippie-college-business
* https://admissions.uiowa.edu/colleges/college-liberal-arts-sciences

**Comment by pyrello** [comment]
One idea for how to handle this on Admissions specifically is to create a custom view block that filters by the selected college and lists the Areas of Study related to it. Then create static pages for each one and place the block with the correct argument on it. This could potentially build on the work in #2702.

**Comment by joewhitsitt** [comment]
I think given the circumstances, this would be the easiest path forward while retaining what we have built for all sites to use. Are there additional fields of content that would be placed on these pages or would this all be covered with the views block on a page?
