### ISSUE TITLE
Migrate D7 SiteNow MNH site

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#310]
https://mnh.prod.drupal.uiowa.edu/

Be sure to block all users on that site before starting the migration to avoid content loss. That can be done with `drush herky-toggle-users`.

**Comment by richardbporter** [comment]
1. Provision new D8 MNH site
2. Sync D7 standard site to stage or dev to use as content source
3. Remove mnh.prod.drupal.uiowa.edu domain from D7 app
4. Add mnh.prod.drupal.uiowa.edu domain to D8 app
5. Recreate content in D8 site

**Comment by ethanstjohn** [comment]
I have started work on this issue.

**Comment by ethanstjohn** [comment]
https://github.com/uiowa/uiowa/compare/master...initialize-mnh.uiowa.edu

It looks like this has been started but a PR hasn't been created for it.

**Comment by joewhitsitt** [comment]
Blocked by #330

**Comment by joewhitsitt** [comment]
#330 is still open, but i adjusted the composer file to get the pipeline moving again until we can figure out a longer term solution.

Step 1, provision is done and the site can now be migrated to mnh.prod.

**Comment by richardbporter** [comment]
I've contacted the customer.
