### ISSUE TITLE
Remove OneIT@Iowa logo and replace with text

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#3101]
>I need to remove the OneIT@Iowa logo from the OneIT site so that it meets the new brand standards put in place by OSC. We need to remove the logo and replace with "OneIT" text.

Jalessa Hohensee

﻿https://oneit.uiowa.edu/

**Comment by joewhitsitt** [comment]
- [x] Toggle logo in theme settings
- [x] Remove element invisible or whatever on site-name in styles
<img width="865" alt="Screen Shot 2021-03-25 at 4 03 39 PM" src="https://user-images.githubusercontent.com/4663676/112543406-b31a2780-8d83-11eb-84af-92de8d4ababe.png">

**Comment by bspeare** [comment]
@joewhitsitt are the theme settings set in config?

**Comment by joewhitsitt** [comment]
i don't think so. you would deploy the style change and manually change prod

**Comment by bspeare** [comment]
Removed the logo and live text is now displaying on https://oneit.uiowa.edu/.

**Comment by briand44** [comment]
This should say OneIT (all one word, no space between One and IT) and remove the “at Iowa”.

**Comment by briand44** [comment]
I've made the update.
