### ISSUE TITLE
WYSIWYG Styles dropdown is anchored to page, not the WYSIWYG itself.

### ISSUE THREAD

**Issue by GaryRidgway** [uiowa/uiowa#3104]
# Problem
Shown here, there is a problem with the anchoring of the Styles dropdown of the WYSIWYG:
![353c26638d9ba9e390b974d66343dfd7](https://user-images.githubusercontent.com/23122142/108235905-f261b280-710b-11eb-86fa-0ee195205d83.gif)
<img width="1031" alt="Screen Shot 2022-01-31 at 10 18 41 AM" src="https://user-images.githubusercontent.com/16872949/151845553-5a749233-21d2-4896-b86c-cfb380ecd4eb.png">

# Steps to reproduce
Open a WYSIWYG and then open the styles dropdown. scroll either the page to the left of the editor tray or the Styles dropdown to the bottom and then continue scrolling. This should produce the above effect.

# Proposed solution
Find a way to absolutely position the dropdown in relation to the WYSIWYG instead of the page itself.

**Comment by joewhitsitt** [comment]
I think this should be reported to the Drupal project issue queue. These are both in core and should work together.

**Comment by bspeare** [comment]
Just tested on simplytest.me and this is easy to reproduce.    Perhaps we just need to find the drupal.org issue where this has already been reported?

Steps to reproduce:

1. Install Drupal 9 site on simplytest.me
2. Turn on layout builder at /admin/modules
3. Adjust basic page to use layout builder /admin/structure/types/manage/page/display
4. Create a new basic page and add a "custom block" to the layout
5. Select "Normal" menu and scroll down slightly
6. You should see the select menu detached like the screenshot below:


<img width="1318" alt="Screen Shot 2021-12-14 at 3 25 20 PM" src="https://user-images.githubusercontent.com/1036433/146081717-720a7efa-5598-4f36-b431-2e88a9d0e316.png">

**Comment by briand44** [comment]
Search issue queues and create issue if one doesn't already exist. If determined we don't have a path forward, add the upstream label.

**Comment by dnkemper** [comment]
Issue created on drupal.org: https://www.drupal.org/project/drupal/issues/3261594#comment-14392776

**Comment by pyrello** [comment]
The drop-down that opens is located in a div at the very end of the document:
![Screen Shot 2022-01-31 at 9 44 10 AM](https://user-images.githubusercontent.com/709009/151825338-0b593ac7-4e0c-4ed0-87a4-b523d8f00290.png)

You can cause it to show/hide by selecting it in the inspector and then toggling the `display: none` property.

**Comment by briand44** [comment]
Removing this from project board and unassigning Dani since she completed the work that was planned for this sprint. Will leave it in our bug milestone at a lesser priority.

**Comment by bspeare** [comment]
I'm no longer seeing this as an issue.  Can anyone else confirm? I checked our local instance and simplytest.me.  If so, we might want to close https://www.drupal.org/project/drupal/issues/3261594#comment-14392776.

**Comment by pyrello** [comment]
> I'm no longer seeing this as an issue. Can anyone else confirm? I checked our local instance and simplytest.me. If so, we might want to close https://www.drupal.org/project/drupal/issues/3261594#comment-14392776.

I closed it.
