### ISSUE TITLE
Academic Groups for areas of study

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#3110]
# Story

As an admissions site owner, I want to have academic groups so that users can optionally navigate areas of study by first choosing the academic group they are interested in.

# Additional Info
* Taxonomy or similar functionality to create list of academic groups.
* Each academic group should be able to have a title, photo, description and video.
* Ability to reference multiple groups from an individual area of study.
* Full academic group page should have all the above mentioned fields as well as teasers for each area of study that has referenced the specific group, with link to those areas of study (https://admissions.uiowa.edu/academics/biz-econ-mgmt).
* Have ability to filter by these groups on future Areas of study search page (https://admissions.prod.drupal.uiowa.edu/academics/undergraduate-areas-of-study)
* These referenced group(s) do not need to be output on an area of study entity.
* Must be in the correct form order: https://github.com/uiowa/uiowa/issues/3108

# Proposed solution

**Comment by bspeare** [comment]
We pointed this but I don't see a proposed solution.   Is there anything to add there?

**Comment by pyrello** [comment]
I think this is the best way to handle this:
* Build a new content type called Academic Groups with the following fields: Name, Description, Featured image, Video, and an entity reference field to the Areas of Study content type. 
* There is also a Profile field, but the example I am looking at doesn't have a value for it, so maybe it's not used? Probably check that with Scott.
* Style the reference field as a set of cards.

**Comment by pyrello** [comment]
Alternately, this could just be done by adding a taxonomy for Academic groups and an entity reference field to the Area of Study content type that references it.

@bspeare raised the concern about whether the first approach I laid out would allow for us to use Academic groups as a filter on the Areas of Study search page. I think that it is possible, but would require adding a relationship with a reference from the Academic group to the Area of Study in the view. I'm pretty sure it is possible to do something like this, but ultimately, I'll leave the decision up to the person who takes over this task.
