### ISSUE TITLE
IOWA bar header disappears when editing blocks in LB

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#3119]
# Problem
After clicking any button that causes the settings tray to show (e.g. "Configure" for a block), the IOWA bar disappears.

![Screen Shot 2021-02-22 at 8 12 09 AM](https://user-images.githubusercontent.com/709009/108720447-6faf6d80-74e6-11eb-9aab-ba5505dedebc.png)

# Steps to reproduce
Visit https://grad.uiowa.edu/ and login. Visit the homepage and click the "Layout" tab. Click an action link inside LB.

# Proposed solution
TBD

**Comment by bspeare** [comment]
@pyrello this was intentional functionality since the Iowa bar doesn't play well with the tray and all the media queries set up for the elements in the header.   I'd probably change this to a story about getting all header variants to work with the tray.

**Comment by pyrello** [comment]
I was not aware that we had introduced this.
