### ISSUE TITLE
D9 Webform datepicker not working in Safari and IE

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#3126]
# Problem 

Datepicker does not appear on IE and Safari and manual date entry does not work either on: https://designcenter.uiowa.edu/form/submit-job-request.     

# Proposed Solution
- https://www.drupal.org/project/webform/issues/3027747#comment-14002223
- Remove datepicker?

**Comment by richardbporter** [comment]
Wow. I was going to suggest manually entering the date or switching to the date list element, however, getting the format right is a pain. When you consider webmasters can't see what format the date should be in to add help text, I would vote for a non-jQuery polyfill if one exists.

**Comment by richardbporter** [comment]
I'm actually not seeing many. Sounds like Safari will support this in the next release and IE is IE 👎🏻 . 

I kinda like this idea of setting a placeholder equal to the format which would only show for browsers that don't support the HTML `date` element: https://stackoverflow.com/a/56577624 I think we could do that in code.

**Comment by richardbporter** [comment]
I would say this is a browser issue. Removing bug label.
