### ISSUE TITLE
Move commencement.uiowa.edu from 702 to 703

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#3136]
# Story

As an ITS/OSC web team member,  I want to move commencement.uiowa.edu from uiowa702 to uiowa703 so that we can start to free up another application for Drupal 9.

# Additional Info

We want to document all steps involved in this process for future reference and to help determine if/how much of this we could automate.

Once this gets planned, we will need to reach out to Josh to schedule a time during the sprint week when they don't need to make any content edits.

We need to remember to cover SSL on the destination application as well.

# Proposed solution

Initialization
- [x] Copy site directory to uiowa703. Update DB include in settings.php. Delete DD include in settings.php. Delete any .gitingore in the site directory before committing.
- [x] Add dev/test/prod site entries to uiowa703 sites.php.
- [x] Copy two versions of the Drush alias to uiowa703. Rename the first to site-uiowa702 and leave as is. Leave the second named as is but replace all instances of uiowa702 with uiowa703 in it.
- [x] Create site database in uiowa703 named exactly like uiowa702 site database.
- [x] Create a release of the changes above and deploy to uiowa703 dev/test/prod.
  - This just ensures aliases and site directories exist everywhere.
- [x] Ensure the domain(s) exist in the uiowa703 SSL certificate.
  - There is a combined cert of all uiowa702 and uiow703 SANs in the works.
- [x] Set up the site locally in DD by editing datamodel.xml.

Launch
- [x] Block users on uiowa702 site via `drush herky-toggle-users`.
- [x] Add internal prod domain to uiowa703.
- [x] Sync files and DB from uiowa702 to uiowa703.*
- [x] Inspect site at internal prod domain. 
- [x] If ok, move prod domain and remove internal prod domain.
- [x] Unblock users on uiowa703 sites via ` drush herky-toggle-users`.
- [x] Clear caches.

Cleanup
- [x] Delete old site from uiowa702 as per usual process.

Syncing files and database may require a temporary Drush alias pointing to the uiowa702 site. Ideally, we could use the application alias with the `--uri` option but I'm not sure if that will cut it.

**Comment by joewhitsitt** [comment]
One thing I just thought about. Don't we have a hard limit of 100 SANs per application? 703 has 96 by my count.

**Comment by briand44** [comment]
I am not sure if we know if that is a hard limit or not? We have never ran into it. @richardbporter thoughts? Also, I am assuming there are some entries that could be removed. We probably haven't done a great job of cleaning those up as sites move.

**Comment by briand44** [comment]
@joewhitsitt it is a good point to bring up though because I think a lot of 702 sites are non uiowa domains.

**Comment by joewhitsitt** [comment]
I will push this forward to establish some steps in the IS but additional input is strongly encouraged.

**Comment by joewhitsitt** [comment]
I will do an audit on the SANs to see what the actual numbers are like.

update: looks like 5, maybe 6 of the 96 can be removed from 703 before commencement is added

- diversity.uiowa.edu
- hr.uiowa.edu
- *.sports.uiowa.edu?
- pathforward.uiowa.edu
- transfer.uiowa.edu
- uiventures.uiowa.edu

2 can be removed from the 37 that 701 has. lynda, sitenow however there is still 300+ dbs on that application.

**Comment by richardbporter** [comment]
>ssh in and create public and private file directories?

I think Acquia handles that.

> change tmp and private filesystem paths

The private path is relative from the docroot so I don't think that needs to be changed.

>disable caching

I wouldn't think this would be necessary.

>magically sync files and db from 702 to 703 OR sync locally, move and sync up.

If we also create a temporary "old" alias then syncing remote-to-remote should work. Syncing locally outside Linux could cause case-insensitive file loss.

**Comment by richardbporter** [comment]
Based on the SSL audit, it sounds like this and other sites should probably be moved uiowa701. 

However, I was able to generate a cert with all the SANs from 702 and 703 so it doesn't appear to be a hard limit. Whether or not the browser is able to load the certificate is another question. The site badssl.com has a 1000 SAN cert that seems to load: https://1000-sans.badssl.com/ I'm not saying 1000 should be our limit because apparently SANs come at a performance cost, at least if this is still relevant: https://discuss.httparchive.org/t/san-certificates-how-many-alt-names-are-too-many/1867

It seems like size is a more important factor with SANs. The current uiowa703 certificate is 5.5kb. The combined uiowa702/3 certificate is about 7kb (I think). So it is an increase for sure but not astronomical. There are many other assets and requests larger than that on say, its.uiowa.edu.

Maybe we could touch base on this in person.

**Comment by briand44** [comment]
>Based on the SSL audit, it sounds like this and other sites should probably be moved uiowa701.

If there isn't a hard limit than I am not sure 701 is a better option.

>Maybe we could touch base on this in person.

I do think it would be worth a conversation. Maybe we should not move them anywhere. Buy more applications? Clear up another app?

**Comment by richardbporter** [comment]
I'm leaning towards just moving them to 703 as it doesn't seem like that much of an increase. It seems like ~100 sites per app/cert is still a good target.

**Comment by richardbporter** [comment]
I updated the issue summary.

**Comment by richardbporter** [comment]
Ran into an issue where the old site .gitignore prevented the site settings.php file from being committed.

**Comment by richardbporter** [comment]
I can't seem to get the site to show up in DD. I'm not sure if that is a requirement or not. I added it to the checklist because it seems like it to me.

**Comment by richardbporter** [comment]
We might need to create the site in DD first, then copy in assets like themes, modules, etc.

**Comment by richardbporter** [comment]
Had to hack the datamodel to get in DD. Also had to copy a uiowa702 version of the Drush alias to sync.

**Comment by richardbporter** [comment]
The rsync is a little awkward but works: `drush @commencement.dev rsync @commencement-uiowa702.prod:%files @self:%files`

**Comment by richardbporter** [comment]
>Update the file_temporary_path variable.

This was already updated after syncing.

**Comment by richardbporter** [comment]
I had to run cc all, rr, cron a few times to get rid of Missing Feeds plugin FeedsExJsonPath error.

**Comment by joewhitsitt** [comment]
Easy peasy? open the floodgates to more moves?
