### ISSUE TITLE
Fix Admissions Student Profiles block

### ISSUE THREAD

**Issue by dnkemper** [uiowa/uiowa#3138]
# Problem

https://iowaweb.slack.com/archives/C0164FNN1PV/p1614281335067900
The student profile block still displays even if there is no content to fill it.

The student profile block also doesn't display profiles at random. 

# Steps to reproduce

https://admissions.prod.drupal.uiowa.edu/student-profiles/aasthika-das
# Proposed solution

Could potentially follow Joe's fix?!
 - if no data, don't display student profile view block
 - Don't show student profile image of the full profile node you're currently viewing
https://github.com/uiowa/uiowa/blob/main/docroot/sites/admissions.uiowa.edu/module[…]--views-block--areas-of-study-block-block-information.html.twig 
- Display student profiles at random. If viewing a full node student profile, that profile shouldn't be displayed in the block. It should be random and display other student profiles.

**Comment by mjoneill** [comment]
Question: How do we add a block of student profiles to an existing page. 

"We need the ability to put a block of student profiles on any page, and have it filtered by (taxonomy)?  Ex: Show me a collection of student profiles for international students..."

Scott has some recollection of evaluating comps/designs of how this would appear. Thinks it was Photo|Student Name?

@dnkemper any recollection of this?

**Comment by dnkemper** [comment]
@mjoneill I don't believe we created the view filters to do that yet. At least it wasn't part of the issues we've worked on so far. We created the full node/teaser node displays of the student profiles that have a block built into the content type, but not an individual block that can be placed on a page. That part (adding the view block to the page) will be easy as pie, we will just need to work on the filtering part of that request. This sounds fun to me!

**Comment by joewhitsitt** [comment]
@mjoneill are you suggesting we increase the scope of this issue beyond the block visibility bug or should a separate issue be created?

**Comment by mjoneill** [comment]
Please don't let me scope creep. I was following up on a comment Scott mentioned where he indicated he saw and approved comps for this at some point, but never saw it built.  

I'll let you and @briand44 determine whether we have a means to meet the client need, and handling that in an appropriate story.

**Comment by briand44** [comment]
Sorry, I already have another issue created https://github.com/uiowa/uiowa/issues/3232. I just got requirements from Scott so I will be working on grooming that issue prior to planning. Sorry, if I wasn't clear on this before or if I didn't make it visible.

**Comment by briand44** [comment]
But that issue may affect how we address this.

**Comment by dnkemper** [comment]
@briand44 I will fix the description of this. This is for the 'student profile' block that displays on a student profile full node. It has nothing to do with the individual student block that Scott wants to be able to place on a page! This is implemented in the layout builder display.

**Comment by joewhitsitt** [comment]
Getting a lay of the land with #3232, I am wondering if the same block can be used for both. If someone picks this up before me, check in with me.

**Comment by bspeare** [comment]
@joewhitsitt that's probably a great idea.

**Comment by briand44** [comment]
@joewhitsitt the same block could be used for both. I first discussed that with Scott but then thought it might be better to go with two separate so they aren't required to manually add the block to every student profile.

**Comment by joewhitsitt** [comment]
The work with #3232 is causing me to work on this as well.
