### ISSUE TITLE
Malformed HTML causes WSOD

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#3167]
*I keep getting this error on one particular page when trying to save the Layout:
"Temporarily Unavailable
The website that you're trying to reach is having technical difficulties and is currently unavailable.
We are aware of the issue and are working hard to fix it. Thank you for your patience."*

*This is the page:
https://writinguniversity.org/node/116/layout*

*I am able to save the page through Edit without that error but every time I try to save the Layout I get this error. It started happening yesterday around 11am? I've tried on several browsers too.*

Error: 
```
Uncaught PHP Exception Drupal\Core\Entity\EntityStorageException: "The "" entity type does not exist." at /mnt/www/html/uiowa01/docroot/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php line 810
```

Seems to be caused by the following actions:

- Removing URL from a link
- Attempting to link an image using WYSIWYG toolbar

**Comment by richardbporter** [comment]
This is being caused by some malformed HTML in the Juan Felipe Herrera text area block:
```
<a data-entity-substitution="" data-entity-type="" data-entity-uuid="" href="http://litcity.lib.uiowa.edu/person/juan-felipe-herrera/" id="" rel="" target="" title="">
<drupal-media data-align="center" data-entity-type="media" data-entity-uuid="182d8e24-dd2f-4f28-a29f-282deb264b3b" data-view-mode="full__no_crop"></drupal-media>
</a>

<h3 class="bold-headline--serif text-align-center">Juan Felipe Herrera</h3>

<p class="text-align-center"><br />
<em><sup>Fiction, Iowa Writers' Workshop, Faculty, Alumni</sup></em></p>
```

The anchor has some data- attributes that it shouldn't. Removing those data-entity-* attributes seems to allow saving the layout.

I don't know how this happened or if we need to investigate. I'm guessing some dragging and dropping in the WYSIWYG?

**Comment by richardbporter** [comment]
@pyrello Do you want me to do any more digging or just relay this to the customer and move on?

**Comment by richardbporter** [comment]
I think this is the issue we're having: https://www.drupal.org/project/linkit/issues/3201405 I can replicate it at least.

**Comment by richardbporter** [comment]
I guess a short-term fix would be to use the unlink button to remove the link and then relink it.

**Comment by richardbporter** [comment]
The weird thing is the href is set on that link so the referenced issue may not be exactly what happened here.

**Comment by laurenhaldeman** [comment]
Could this have happened because I tried to make the image a link? I highlighted the image and clicked the link symbol in the WYSIWYG.

**Comment by joewhitsitt** [comment]
Possibly. I think the only way to link an image right now is to follow these steps: https://sitenow.uiowa.edu/documentation/media/images-and-files#link-image

**Comment by laurenhaldeman** [comment]
Update: I removed the data- attributes from the anchor, as well as the id, rel and title, and the page layout saved. Thanks all!
From:
`<a data-entity-substitution="" data-entity-type="" data-entity-uuid="" href="http://litcity.lib.uiowa.edu/person/juan-felipe-herrera/" id="" rel="" target="" title="">`
to
`<a href="http://litcity.lib.uiowa.edu/person/juan-felipe-herrera/">`

**Comment by joewhitsitt** [comment]
This is happening on csomaycenter with link wrapped images.

Update: resolved the same way.

**Comment by joewhitsitt** [comment]
Added a known issue: https://sitenow.uiowa.edu/known-issues#uiowa-issue-3167

**Comment by pyrello** [comment]
It seems like we don't actually have a path forward on this right now? I forget what work we pointed this 5 points for. Is it just the investigation that Rick already did?

**Comment by richardbporter** [comment]
Probably but maybe we should remove the point label and move this to the backlog until we know more about a proposed solution?

**Comment by pyrello** [comment]
Sounds good to me.
