### ISSUE TITLE
As a developer I can hide specific menu items without disabling them

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#3188]
# Story

As a developer I can hide specific menu items without disabling them. I need to hide one menu item from the main navigation, but still show its children in a side menu.

This all stems from a specific need I have for the Social Work site, specifically for the Field Education section. This Field Education section contains information for both undergraduate and graduate students. On their existing site, they have actually duplicated the content underneath both areas, which is leading to inconsistent content. On their new site, I have combined all of this information into one section (Field Education) and created a custom link to this section underneath both the UG and Grad menus:

![Screen Shot 2021-03-05 at 12 30 39 PM](https://user-images.githubusercontent.com/3067017/110161643-411d7680-7db3-11eb-92fd-0fb2de84d464.png)

The problem with this is the Field Education section of the menu needs to be hidden so as to not show in the Main Navigation display. This could easily be solved by "disabling" the menu item from the main menu (if that was the only item), but this item has children of its own. And it gets worse: If I disable the parent Field Education item, then all of its children under up floating to the Alumni section, where it definitely doesn't belong.

![Screen Shot 2021-03-05 at 1 09 29 PM](https://user-images.githubusercontent.com/3067017/110162235-1384fd00-7db4-11eb-95f6-cc648304cb18.png)

Furthermore, the Field Education section's children need to stay visible in their side menu:

![Screen Shot 2021-03-05 at 1 06 18 PM](https://user-images.githubusercontent.com/3067017/110161888-98bbe200-7db3-11eb-9e3b-80156f0e480a.png)

So, Im looking for a way to "hide" the parent menu item (Field Education) from being displayed in the Main Navigation (and in turn its children), while still allowing the side menu for these sections to remain intact.

# Proposed solution

Menu Item Role Access may be a solution: [https://www.drupal.org/project/menu_item_role_access](https://www.drupal.org/project/menu_item_role_access)

Menu Per Role may be a solution: [https://www.drupal.org/project/menu_per_role](https://www.drupal.org/project/menu_per_role)

Menu Item Visibility does not look to be a solution, as it looks to be a dead project: [https://www.drupal.org/project/menu_item_visibility](https://www.drupal.org/project/menu_item_visibility)

**Comment by joewhitsitt** [comment]
Worse case solution idea: an additional "unlisted" menu in default that folks can create navigational hierarchies/breadcrumbs for the menu system items that don't fit in the main menu structure.

- Resources referenced by separate pages across the main menu system
- Audience based navigation

**Comment by pyrello** [comment]
I haven't had a chance to fully look this over yet, but it seemed potentially relevant: https://www.drupal.org/project/menu_position

**Comment by joewhitsitt** [comment]
We used menu_position on its.uiowa.edu to deal with breadcrumbs for news articles and info centers (non-menu content types). https://its.uiowa.edu/news/top-10-linkedin-learning-videos

**Comment by mark-bennett-uiowa** [comment]
### Information Gathering
I first tried the drupal/menu_per_role module. Simple installation, no additional requirements, no errors during setup, admin, or while in place. Can only "show" or "hide" menu under Edit menu for Main Navigation, not at the node level under Menu settings.

### Screenshots
![Screen Shot 2021-03-10 at 10 52 10 PM](https://user-images.githubusercontent.com/3067017/110738124-5a2f8880-81f4-11eb-9353-3c28c6a565dd.png)

Menu still appears while logged in, even when authenticated user is checked under "Roles not able see the menu link".

![Screen Shot 2021-03-10 at 10 49 54 PM](https://user-images.githubusercontent.com/3067017/110738145-63205a00-81f4-11eb-889e-f173deb16833.png)

When logged out of the site, the menu does "hide" as intended.

![Screen Shot 2021-03-10 at 10 49 05 PM](https://user-images.githubusercontent.com/3067017/110738309-a7abf580-81f4-11eb-8b25-f62fc3e187fd.png)

Child menus still appear properly in side-menu of page content.

![Screen Shot 2021-03-10 at 10 56 43 PM](https://user-images.githubusercontent.com/3067017/110738327-b1355d80-81f4-11eb-8faa-e443d361ea8e.png)

### Results
Seems to work for this need, could be used for other purposes (as stated on module page):

- You are dealing with external links (these are considered public and have full access rights by default.)
- Menus that you do not want to show to certain users although the destination pages are still freely accessible.
- You could have a site with a menu for registered users and a menu used to appeal to new users so they create an account.

Can only "show" or "hide" menu under Edit menu for Main Navigation, not at the node level under Menu settings.
Only configuration changes involve updating composer and core.extension.

**Comment by mark-bennett-uiowa** [comment]
### Information Gathering
I next tried the drupal/menu_item_role_access module. Simple installation, no additional requirements, no errors during setup, admin. Can only "allow" menu under Edit menu for Main Navigation, not at the node level under Menu settings.

### Screenshots
Only gives checkboxes for allowing access to the menu, not selectively hiding like menu_per_role does.

![Screen Shot 2021-03-10 at 11 38 44 PM](https://user-images.githubusercontent.com/3067017/110741765-d6c56580-81fa-11eb-9f13-a2eab388e4ae.png)

### Results
Even when selecting Authenticated user for the Field Education menu item, the menu still appeared while logged out of the site. I assumed that I needed to allow this at a parent item and then "disallow" a child menu item, but this also did not work. Module does not seem to work, or I am using it incorrectly.

**Comment by pyrello** [comment]
Is it possible that clearing the varnish cache is necessary to see the change after logging out?

**Comment by mark-bennett-uiowa** [comment]
I didn't check that, but I did use two separate branches to test this rather than just one, because I didn't want one module affecting the other. I could try this again, but if a varnish clear was necessary to get one module to work properly, Id rather go with the working module that doesn't require an additional varnish clear every time something is changed in the menu visibility.

**Comment by bspeare** [comment]
I tested out `menu_per_role` module and as @mark-bennett-uiowa said, it allows you to hide a section from being listed in the dropdown, yet preserve the page navigation and breadcrumbs.  The screenshot below shows the horizontal page navigation showing up but the page not appearing the "Resources" dropdown. 

<img width="1582" alt="Screen Shot 2021-03-24 at 4 10 03 PM" src="https://user-images.githubusercontent.com/1036433/112383721-7daa0700-8cbb-11eb-82d5-849bb552d9d0.png">

You can't hide individual pages within a dropdown and have them still appear in the vertical or horizontal page navigation.  For instance, hiding "Webinars" in this example makes it disappear from the dropdown and vertical or horizontal page navigation. 

<img width="1568" alt="Screen Shot 2021-03-24 at 4 13 42 PM" src="https://user-images.githubusercontent.com/1036433/112384121-06c13e00-8cbc-11eb-9884-b4b793874891.png">

Also, superfish is confused when hiding all the child pages of a parent using this module and still displays a toggle icon. 

<img width="228" alt="Screen Shot 2021-03-24 at 3 46 12 PM" src="https://user-images.githubusercontent.com/1036433/112385352-84d21480-8cbd-11eb-860f-b623450fce3e.png">

If you want to limit the top dropdown menu to only display the parent page but not the children while having the "children of active menu item" appear in the vertical or horizontal page navigation, then you would need to hide the parent page in the menu using this module and create a duplicate link with a hard-coded url to the page.  The downside to that is you would always need to have to create a page/node to function as the parent item container. 

<img width="970" alt="Screen Shot 2021-03-24 at 4 18 22 PM" src="https://user-images.githubusercontent.com/1036433/112384782-cf9f5c80-8cbc-11eb-90e7-1ec0a506cc65.png">
<img width="1591" alt="Screen Shot 2021-03-24 at 4 19 28 PM" src="https://user-images.githubusercontent.com/1036433/112384803-d6c66a80-8cbc-11eb-8c01-1a457166444f.png">

Scott has mentioned that he would be interested in both of the scenarios listed above.
