### ISSUE TITLE
Wipe/Re-Install bme.engineering.uiowa.edu as v3 on uiowa

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#3189]
Never went live. They want all department sites on v3.

**Comment by joewhitsitt** [comment]
Ran into an install error related to cshs.

`Error: Unsupported operand types in cshs_config_schema_info_alter() (line 63 of /mnt/www/html/uiowa/docroot/modules/contrib/cshs/cshs.module`

Going to look into updating this module.

**Comment by richardbporter** [comment]
I'm not getting that error - you got this after running `blt drupal:install --site bme.engineering.uiowa.edu`?

**Comment by joewhitsitt** [comment]
`./vendor/bin/blt drupal:install --site=bme.engineering.uiowa.edu` on PROD. not local.

**Comment by richardbporter** [comment]
I didn't get it on dev either. Not sure what the difference would be...

**Comment by richardbporter** [comment]
cr after drop?

**Comment by joewhitsitt** [comment]
This worked after deleting the database from Acquia Cloud and recreating. Then installing using the general `blt uiowa:multisite:install` command
