### ISSUE TITLE
Allow webmasters the ability to assign the publisher role

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#319]
Masquerading as a webmaster, only editor and webmaster or role options when editing another user.

**Comment by ethanstjohn** [comment]
I would love to work on this. I'm looking through the uiowa folder looking for some sort of permissions  or roles folder. Do you have an idea where it might be if I don't find it right away?

**Comment by joewhitsitt** [comment]
Normally, this would be added as another permission through the UI, but it appears the permission applies to all roles and that the publisher role is simply not showing up as an option on the user node. VBO options exist for webmasters to add/remove the publisher role, so we must be doing something funky that is hiding the option. More investigation is needed.

**Comment by joewhitsitt** [comment]
oops. straight to master...
