### ISSUE TITLE
As an prospective student, I can use a set of filters to sort through the Areas of Study and see detailed results

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#3203]
# Story

As an Admissions website user, I can use a set of filters to sort through the Areas of Study and see Majors and Subprograms listed in the results. 

# Additional Info
https://iowa-my.sharepoint.com/:w:/g/personal/sfiddelk_uiowa_edu/EUCW5mYgGHVHklicgfev3e8BGLGl34GtPMN2-U6xfsWeAA?e=UPhayh

A core patch is needed if entity reference (node) filtering is used: https://www.drupal.org/project/drupal/issues/2429699

# Proposed solution

Using https://admissions.uiowa.edu/academics/undergraduate-areas-of-study as a model, update the search filter on http://admissions.local.drupal.uiowa.edu/areas-of-study and http://admissions.local.drupal.uiowa.edu/ to include the ability to sort by:

- Academic Group
- College
- Program Type (Major, Minor, Certificate, Preprofessional Program, Online/Offcampus Program)

<img width="1276" alt="Screen Shot 2021-03-08 at 11 48 18 AM" src="https://user-images.githubusercontent.com/1036433/110360333-360d5500-8004-11eb-90a7-d830547d9499.png">

Update the listing on http://admissions.local.drupal.uiowa.edu/areas-of-study to include Majors and Subprograms like it is listed on https://admissions.uiowa.edu/academics/undergraduate-areas-of-study. 
- Include Majors
- Include Subprograms

<img width="1226" alt="Screen Shot 2021-03-08 at 11 47 57 AM" src="https://user-images.githubusercontent.com/1036433/110360278-255cdf00-8004-11eb-8021-b1e7bb3aa042.png">

**Comment by bspeare** [comment]
Inspirational links from: https://github.com/uiowa/uiowa/issues/2218.  

- https://und.edu/programs/index.html?search=&locations=on-campus,offcampus,online
- https://admissions.wvu.edu/

**Comment by bspeare** [comment]
The D7 site had a "Program Type" field with help text "Select each type of program affiliated with this area of study and this record. This is used for sorting/filtering results in the A-Z list."

**Comment by joewhitsitt** [comment]
I think this issue is going to have the same reference filtering issue as https://github.com/uiowa/uiowa/issues/3043 there are possible solutions in the comments.

**Comment by dnkemper** [comment]
Thank you so so much, @joewhitsitt

**Comment by joewhitsitt** [comment]
I think this is only blocked until we decide how to move forward with https://github.com/uiowa/uiowa/issues/3223

Did @pyrello a possible conflict with the search box placed elsewhere on the website? I don't see that information in the IS.

**Comment by pyrello** [comment]
This may be blocked from being completed, but someone could certainly start working on it prior to completion of #3223.

The search block on the home page is implemented via a custom block plugin which pulls in the `area_of_study` view and renders the exposed form:

https://github.com/uiowa/uiowa/blob/2d8c0765fae784d4e6239d7e968dbc6a45f56aee/docroot/modules/custom/uiowa_area_of_study/src/Plugin/Block/AreasOfStudySearchBlock.php#L72-L97

I think it is fine to make whatever changes are necessary to the `areas_of_study` view exposed filters to meet the needs of this request and then just suppress the display of those additional exposed filters in the above class.

**Comment by joewhitsitt** [comment]
Looked at the current website and see that the program type is based on the actual types, not the content of those types (aka the field values of how it was built on the new site)

<img width="531" alt="Screen Shot 2021-03-16 at 4 03 51 PM" src="https://user-images.githubusercontent.com/4663676/111380551-7eff8200-8672-11eb-830b-188e47b33c68.png">

**Comment by pyrello** [comment]
I think we may want to write a views filter plugin to make this work: https://api.drupal.org/api/drupal/core%21modules%21views%21src%21Plugin%21views%21filter%21FilterPluginBase.php/group/views_filter_handlers/9.1.x

**Comment by joewhitsitt** [comment]
Scott is okay with adding an additional field of checkboxes that when checked make the related field visible for input. This field could then be targeted in the view filter.

**Comment by joewhitsitt** [comment]
Waiting on https://github.com/uiowa/uiowa/pull/3253 to move this forward.

**Comment by joewhitsitt** [comment]
I am thinking a view mode would help with pulling together a single table column of all this data:

title linked, preprocess or extra field that combines the values (what i assume are program type values, etc.) into a comma-separated list that has different styles.

<img width="361" alt="Screen Shot 2021-03-17 at 1 45 21 PM" src="https://user-images.githubusercontent.com/4663676/111521388-17efd500-8727-11eb-8ec0-c625326ba165.png">

**Comment by joewhitsitt** [comment]
Never mind on the view mode. Going a different route closer to views and with less configuration.

**Comment by joewhitsitt** [comment]
Not sure I have the correct information here. Stringing together unique degree abbreviations and printing the text values of minors, certs, preprofessional, online/off-campus. Previously was alternative description text. Anyone more familiar with the content, please chime in.

<img width="1055" alt="Screen Shot 2021-03-17 at 4 02 03 PM" src="https://user-images.githubusercontent.com/4663676/111538023-2d222f00-873a-11eb-9e46-9154b1298961.png">

**Comment by briand44** [comment]
Does this help? https://iowa-my.sharepoint.com/:w:/g/personal/sfiddelk_uiowa_edu/EUCW5mYgGHVHklicgfev3e8BGLGl34GtPMN2-U6xfsWeAA?e=UPhayh

**Comment by joewhitsitt** [comment]
I think I need to talk this out because that confuses me more. Subprograms is in the IS above, but not in the file. College is in the file but not in the IS.

>Listings
>Name Degree/type College
>Name Degree/type College

**Comment by joewhitsitt** [comment]
Comma separated list of what is available:

>an example of one that has everything: BA, BS, Minor, Certificate, Online Option
