### ISSUE TITLE
Signage - 4K image support

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#3209]
## Issue

>Are we able to increase the 2000x2000 image pixel restriction and down-sampling to allow for at least 4k images (3840 x 2160, 8.5MP, or higher)?

## Proposed Solution

Increase the maximum resolution (3840 x 3840) and up file size limits to 10 MB for all image fields on signage. There are both horizontal and vertical displays

**Comment by richardbporter** [comment]
After talking with folks, only the image slide field was updated to 4k on signage and healthcare signage. I think that should be enough.
