### ISSUE TITLE
Image Specs Documentation

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#321]
Image Specs:
Section Background Image - Largest is 2000x2000px scaled and cropped. We recommend a center focal point or no focus as the image is scaled down and position differently based on device size and content.
Card/Teaser Image - 1200×600px scaled and cropped. Focal Point supported.
Article Image - 1110×740 scaled and cropped. Articles use the Card/Teaser Image style for other displays. Focal Point supported.
Square - 768×768 Used for person currently. Focal Point supported.
Large, Medium, Small - 480px, 220px, 100px (WYSIWYG areas) - Maintains original aspect ratio and scales the largest side (horizontal, vertical) to the pixel length.
Original (WYSIWYG areas) - Displays the image as uploaded to the site but will have a max width of the container element it resides in. This is also the only way to display animated .gif files.

**Comment by ethanstjohn** [comment]
Should I add this to a section in the gh-pages branch?

**Comment by joewhitsitt** [comment]
I think it can be an sub header of https://docs.sitenow.uiowa.edu/media/

**Comment by ethanstjohn** [comment]
Awesome, that's where I'm currently writing it.

**Comment by ethanstjohn** [comment]
https://docs.sitenow.uiowa.edu/media/ I have added it here.
