### ISSUE TITLE
Add SEO settings for the Scholarship CT

### ISSUE THREAD

**Issue by dnkemper** [uiowa/uiowa#3217]
Setup basic SEO settings for the scholarship content type. Meta description and the related SEO description fields should have a default "[Scholarship Reference Label Token] at Iowa" that can be overridden by webmasters at least. Identify this new configuration and admissions split it.

**Comment by joewhitsitt** [comment]
For this one, I think this should be in the scholarships feature split and not be admissions specific

- [ ] Using the default site, turn on the scholarships split.
- [ ] Make changes and export to feature split.
- [ ] Sync admissions and make sure it imports correctly and doesn't export changes.
