### ISSUE TITLE
Admissions - AoS College Reference Field limited to just Colleges, not all basic pages

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#3223]
# Story

As an editor when filling out the AoS I only want want to see auto results for Colleges, not all basic pages on the website.

# Proposed solution

- [x] Refactor as a taxonomy vocabulary "Colleges"
- [x] Add fields to vocabulary that allows Admissions to use the taxonomy as a replacement
- [x] Use a layout builder template for term rendering
- [x] Update the AoS content type to reference the taxonomy
- [ ] Update the render as necessary

**Comment by joewhitsitt** [comment]
This might not need to happen for MVP if the migration populates this field correctly.

**Comment by bspeare** [comment]
Should we just change the field to be a taxonomy field instead? That would probably help with https://github.com/uiowa/uiowa/issues/3203.  I know that we decided against taxonomy initially for a faster solution but there will be a lot of extra work with this and getting it to work with search.

**Comment by joewhitsitt** [comment]
Didn't think about #3203 but just changing it to a taxonomy doesn't solve it all right? Didn't they want layout builder for this content? Or is it just that they already stubbed this content out. 

Changing it would also mess up the migration work.

For the view, we have altered these filters before and there is https://www.drupal.org/project/selective_better_exposed_filters to only show filter items that exist in the view results.

**Comment by bspeare** [comment]
Taxonomy could solve a good portion of it.   I just wanted to throw that out as a possibility since the Academic Groups were set up as taxonomy.  I think we can create a decent layout with layout builder in taxonomy.

**Comment by joewhitsitt** [comment]
Summary from Slack:

Joe Whitsitt Today at 3:04 PM
So, the “limit the colleges field” on AoS is bringing up some good questions about how all this is working together. Ben suggested this be changed to a taxonomy and these pages are turned into terms/designed. Additionally, the same filtering challenges of the people view page are probably going to play out for the AoS study search issue regardless because we are using entity reference which still doesn’t play nicely with views. Thoughts?
Ben Speare  12 minutes ago
I wasn’t aware of the entity reference issue so I’m fine with moving forward with https://github.com/uiowa/uiowa/issues/3223 if that solves the issue.
Joe Whitsitt  11 minutes ago
a core patch solves the views filtering issue for node entity reference items
Joe Whitsitt  10 minutes ago
it would still need to be filtered both on the field and the view dropdown/autocomplete to not include every page in the system
bdickey  9 minutes ago
I think if it is going to make our lives easier with the filters and such I am fine with changing to Taxonomy. If we can handle the filters without much extra effort, than I think we can take the approach in https://github.com/uiowa/uiowa/issues/3223 and I think that it is a nice to have
Joe Whitsitt  7 minutes ago
well the filtering would be tied to a tag or hardcoded nids so not exactly fool proof compared to a taxonomy
Joe Whitsitt  3 minutes ago
looks like the core patch is just jumping through administrative hoops at this point. “tests” have been checked off.

**Comment by joewhitsitt** [comment]
Updated the IS to reflect refactoring as a taxonomy.
