### ISSUE TITLE
Articles and events list block edit form does not display selected layout builder styles after saving page

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#3224]
# Problem
Articles and events list blocks do not display selected layout builder styles after saving page.

# Steps to reproduce
Edit the first articles block on http://sandbox.local.drupal.uiowa.edu/articles.    Hide the images and description and save the page.   Edit the page again and try to adjust the same styles and it should appear empty:

<img width="691" alt="Screen Shot 2021-03-10 at 3 31 47 PM" src="https://user-images.githubusercontent.com/1036433/110700618-c76ff900-81b5-11eb-92f4-d6a715a0bae3.png">

# Proposed solution
- Logs show:`Notice: Undefined index: #description in Drupal\uiowa_core\HeadlineHelper::getElement() (line 67 of /var/www/uiowa/docroot/modules/custom/uiowa_core/src/HeadlineHelper.php)` that could be causing the issue.

**Comment by joewhitsitt** [comment]
Is this just articles and events? I saw this on events when I was preparing for demo and forgot to turn it into an issue.

**Comment by bspeare** [comment]
Those are just the two that I found immediately.   More testing could reveal further impact.

**Comment by cory-skeers** [comment]
#3237 fixes the logs notice and an underlying missing headline description issue, but is unrelated here.

It looks like the problem is with saving multiple layout builder style values, and those multiple values not getting loaded back into the form. The same issue appears when adding a section (Spacing and Styles both allow multiple values.

Haven't tracked anything down that I can tell would be interfering with this, and wondering if it might either be an issue with lbs or config of our styles, and if it's expecting single values only when loading `#default_value`.

**Comment by joewhitsitt** [comment]
Have you tried disabling chosen temporarily to see if that is affecting things?

**Comment by cory-skeers** [comment]
> Have you tried disabling chosen temporarily to see if that is affecting things?

I've not...will try and check that out today!

**Comment by bspeare** [comment]
Maybe we lost the functionality when we updated the `layout_builder_styles` patch? https://github.com/uiowa/uiowa/pull/2983/files#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34R255.   I removed the patch and I was able to apply multiple styles without them disappearing after saving the page.   The Chosen functionality still worked as well.

**Comment by bspeare** [comment]
I tested this out on https://simplytest.me/ and I can confirm **8.x-1.0-beta4** with latest patch https://www.drupal.org/files/issues/2021-01-20/style_groups_for_layout_builder_styles-3075502--beta4.patch has the same problem with multiple styles being applied while **8.x-1.0-beta2** with https://www.drupal.org/files/issues/2020-06-22/style_groups_for_layout_builder_styles-3075502--beta2.patch worked fine.   

Can we roll back to **8.x-1.0-beta2**?

**Comment by bspeare** [comment]
Also, removing lines 207-215 from the module after https://www.drupal.org/files/issues/2021-01-20/style_groups_for_layout_builder_styles-3075502--beta4.patch has been applied also fixed the issue.

```
    if ($config && $config->get('multiselect' === 'single')) {
      if(count($elementSelectedStyles) === 1) {
        $elementSelectedStyles = array_shift($elementSelectedStyles);
      }
      else {
        $elementSelectedStyles = null;
      }
      $form[$element_name]['#default_value'] = $elementSelectedStyles;
    }
```

**Comment by bspeare** [comment]
@cory-skeers, any thoughts on how we should proceed with fixing this problem?  @pyrello suggested that we could add our own patch to https://www.drupal.org/project/layout_builder_styles/issues/3075502 to use.

**Comment by pyrello** [comment]
Dropping this here for future reference: https://git.drupalcode.org/project/layout_builder_styles/-/commit/370ade3ae5329862ac982777c61360a784c86f7a

This is the commit that added the functionality that @bspeare [pointed out](https://github.com/uiowa/uiowa/issues/3224#issuecomment-799681211) seems to be problematic.

**Comment by cory-skeers** [comment]
Ahhhhh....

`    if ($config && $config->get('multiselect' === 'single')) {`
^- This should always be equivalent to true even when it's a multiselect, which then leads to the case where it sets the default value to `null` as a way to unset it, thinking that there are multiple values in a single-select form field.

Moving an end parenthesis should fix it.

Probably good to submit a patch. Not familiar with the process, but now might be a great time to learn!

**Comment by pyrello** [comment]
> `$config->get('multiselect' === 'single')`

This seems like it should evaluate to `$config->get(FALSE)`, since  would think that the `'multiselect' === 'single'` section should be evaluated first. Its an equivalent comparison between two strings which are different. Or am I reading this wrong?

**Comment by pyrello** [comment]
Nevermind my last comment. I'm just now getting what you were saying:

> Moving an end parenthesis should fix it.

**Comment by cory-skeers** [comment]
Have a new issue with a patch in it: https://www.drupal.org/project/layout_builder_styles/issues/3203931

Unfortunately, patching as a new issue conflicts with the patch we're using from https://www.drupal.org/project/layout_builder_styles/issues/3075502, so we need to either wait for one, the other, or both to be completed, or add the change to that issue in addition to the separate, new issue.

**Comment by pyrello** [comment]
I added [a patch](https://www.drupal.org/project/layout_builder_styles/issues/3075502#comment-14032178) that combines the two patches we are using that are incompatible. The patch applies and seems to resolve the issue.
