### ISSUE TITLE
Admissions Student Profiles Block with Filters

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#3232]
# Story

As an Admissions content editor, I want the ability to place a filtered student profile block on any page.

# Additional Info

Need the ability to filter by the following fields:
- Gender
- Student Attributes
- State
- Country if Not US

They would also like the ability to determine how many items are displayed.

They would also like the ability to control the title. It can default to Student profiles with a link to the student profiles page but they should be able to override the text. The link should always remain the same.

The design of this should be similar to the random student profiles block.

# Proposed solution

**Comment by joewhitsitt** [comment]
On a separate issue somewhere I saw something about a mockup of this. @briand44 or @bspeare do you know what that refers to.

**Comment by bspeare** [comment]
@joewhitsitt where did you see that somewhere?

**Comment by joewhitsitt** [comment]
@bspeare https://github.com/uiowa/uiowa/issues/3138#issuecomment-794401995

I see this:

>The design of this should be similar to the random student profiles block.

But just wanted to make sure I didn't miss anything.

**Comment by bspeare** [comment]
I don't recall any mockups.  Maybe we need clarity on whether this block is a block like https://admissions.prod.drupal.uiowa.edu/student-profiles or a sidebar block like https://admissions.prod.drupal.uiowa.edu/student-profiles/aasthika-das?

**Comment by briand44** [comment]
similar to sidebar block. Scott mentioned he thought he saw a mockup. Not sure if I ever did or where that would be.

**Comment by joewhitsitt** [comment]
This got complicated because views block filtering isn't there yet.

@pyrello is going to hook me up the working bits of https://github.com/uiowa/uiowa/pull/2702 to provide filtering on the views block.
