### ISSUE TITLE
Facebook domain validation context...

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#3233]
# Story

As a site owner displaying adds on Facebook, I want to be able to validate my domain with Facebook so that my ads continue to display once Facebook makes this a requirement.

# Additional Comments from Michael

Plan for next sprint if we can. I got into our FB Business Manager account and the ads are still running. We have a window to get the domain validation stuff up.

# Proposed solution

It looks like we have updated to the 8.x-1.15 version where this functionality was introduced.

- [ ] Update permissions on uiowa.edu to allow webmasters to add the facebook validation meta on frontpage config.
- [ ] Deploy to PROD and let Michael test it.

**Comment by bspeare** [comment]
It looks like the site verification field can either be added to the metatag defaults for the SEO section on the edit form for pages in (https://github.com/uiowa/uiowa/blob/main/config/default/metatag.settings.yml) or in code for (https://github.com/uiowa/uiowa/blob/main/config/uiowa.edu/metatag.metatag_defaults.front.yml).  It looks like the only way a webmaster can access those settings is if `site_verification: site_verification` is set on `page` in https://github.com/uiowa/uiowa/blob/main/config/default/metatag.settings.yml.   Does anyone have a suggestion on how we should proceed? Split `metatag.settings.yml` for uiowa.edu only or push up the verification ID via `https://github.com/uiowa/uiowa/blob/main/config/uiowa.edu/metatag.metatag_defaults.front.yml`?

**Comment by joewhitsitt** [comment]
okay, if i understand correctly, i think it is safe to enable site verification in the default and get the id from Michael to update uiowa.edu's front config. In this case the permission is not needed?

**Comment by bspeare** [comment]
@joewhitsitt Thanks!

**Comment by joewhitsitt** [comment]
Sorry for sending you down the permission path initially. I forgot I was the one making changes to frontpage for Michael.
