### ISSUE TITLE
Add config split guidelines to config README

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#3238]
# Motivation

I think we are all doing config splits a little differently. I would like to attempt to get us all on the same page about how they should be structured.

# Proposed solution

I will write up some guidelines and add them to the config README file to lay out how I think they should be handled as a way to start a discussion, if one needs to be had, about how this should be handled in the future.

**Comment by richardbporter** [comment]
Hm. Did #3256 resolve this?

**Comment by pyrello** [comment]
Yes
