### ISSUE TITLE
"Add Articles" dropdown-like button is unclear

### ISSUE THREAD

**Issue by quamsta** [uiowa/uiowa#3244]
As I've worked with layout builder recently, I've found myself (and some others I've talked to) getting lost when I'm adding blocks into sections when I see a button simply labeled "Add Articles." I often overlook the arrow that provides more options. 

<img width="567" alt="Screen Shot 2021-03-12 at 12 00 42 PM" src="https://user-images.githubusercontent.com/472923/110982575-4e47e180-832e-11eb-8409-4ca1304c0d02.png">

Is there a way to clarify (visually or otherwise) that there are more options for blocks besides articles if you click the arrow? The user experience is a bit confusing because it's not really presented as a dropdown list of options of things to add, but instead looks more like a simple action button that will only "Add Articles," with an arrow being the only indicator of... something else when you click it, but it doesn't necessarily imply adding additional things. It appears to be a sort of hybrid between a dropdown and a button, where changing a dropdown value will change the action button

I've researched layout builder a bit and I'm wondering if there's a reason (besides maybe fewer clicks needed) we aren't simply saying "Add block" here as a clear, direct action, as screenshotted here from Ohio State's documentation:

<img width="1135" alt="Screen Shot 2021-03-12 at 12 35 11 PM" src="https://user-images.githubusercontent.com/472923/110983462-65d39a00-832f-11eb-880f-9343d4d362c3.png">

**Comment by bspeare** [comment]
@quamsta It looks like there is some work being done that might help this here: https://www.drupal.org/project/lb_direct_add/issues/3157440.

**Comment by pyrello** [comment]
@quamsta To add a little more clarification here, this is a feature of a contrib module that I built that we utilize in the `uiowa/uiowa` project. The idea behind it is that the drop-button is fewer clicks than clicking "Add block" and waiting for the whole settings tray to come up.

It looks like the patch @bspeare linked to has been tested by someone else, so I'll try to get it tested and merged in to the module.

**Comment by quamsta** [comment]
Just recently saw this was updated. Thanks all!
