### ISSUE TITLE
Rename Yellow Background to Gold Background

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#325]
This is what OSC suggests based on their brand guidelines.

Postponed for now. Ideally we will want to update the class/variable names as well which will require an update hook.

**Comment by joewhitsitt** [comment]
This could happen alongside #260

**Comment by richardbporter** [comment]
Would this still be necessary if v2 goes away?

**Comment by joewhitsitt** [comment]
nope
