### ISSUE TITLE
Add defaults to Areas of Study fields

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#3251]
# Motivation

Per conversation with Admissions, they would like to add some default values to Areas of Study fields.

# Proposed solution

Add the following default content to fields:

**Student Opportunities** 
In addition to having nearly 500 Student Organizations, Iowa students choose from multiple Living-Learning Communities, Study Abroad Programs, and Undergraduate Research Opportunities.

 
**Careers and Outcomes**
Iowa graduates have job placement rates ranging from 86-100 percent, depending on their area of study, and our Pomerantz Career Center offers multiple resources to help students find internships and jobs.
 
**Scholarships**
The University of Iowa provides a variety of scholarships to eligible undergraduate students through the Iowa Scholarship Portal. Scholarships are available to first-year, transfer, and currently enrolled students. For additional details on scholarships for your program of study, check directly with the department or college.
 
The Office of Admissions and the Office of Student Financial Aid are great resources for students seeking scholarships.

**Comment by dnkemper** [comment]
this looks like a nice brain break after the support week I had. I'll start this/assign myself after planning

**Comment by richardbporter** [comment]
Not sure where the text came from in the proposed resolution but it was mentioned today in the meeting that there should be links within those blurbs.

Here is a raw copy/paste from the D7 site that can be compared/cleaned up:

Student Opportunities
```
<p>In addition to having nearly 500 <a href="http://uiowa.orgsync.com/">Student Organizations</a>, Iowa students choose from multiple <a href="http://fye.uiowa.edu/admitted-now-what/living-learning-communities">Living-Learning Communities</a>, <a href="http://international.uiowa.edu/study-abroad">Study Abroad Programs</a>, and <a href="http://www.uiowa.edu/%7Eicru/index.shtml">Undergraduate Research Opportunities</a>.</p>
```

Careers and Outcomes
```
<p>Iowa graduates have job placement rates ranging from 86-100 percent, depending on their area of study, and our <a href="http://www.careers.uiowa.edu/">Pomerantz Career Center</a> offers multiple resources to help students find internships and jobs.</p>
```

Scholarships
```
<p>The <a href="/node/79">Office of Admissions</a> and the <a href="http://www.uiowa.edu/financial-aid/aidtypes/scholarships/index.shtml">Office of Student Financial Aid</a> are great resources for students seeking scholarships.</p>
```

**Comment by dnkemper** [comment]
Okay! Thank you!

**Comment by richardbporter** [comment]
Maybe there is updated text provided by them in a O365 doc or something?

**Comment by dnkemper** [comment]
So should I not move forward with this? Because might have kinda sorta started haha. Should I move forward with what you put above then ask in Friday's meeting?

**Comment by richardbporter** [comment]
I think that will work but any internal links need to be updated for the new site. I think only scholarship text has one.

**Comment by dnkemper** [comment]
Ah, okay! Looks like that node doesn't exist. I'll create one in a draft state in the prod site then sync down and fix that. Thank you so much!

**Comment by richardbporter** [comment]
node/79 on the D7 site is https://admissions.uiowa.edu/finances/scholarships. I'm assuming that is https://admissions.prod.drupal.uiowa.edu/finances/scholarships on the new site.

**Comment by dnkemper** [comment]
Haha I was just checking that out, thank you so much!
