### ISSUE TITLE
Design/Style College taxonomy term page for Admissions

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#3255]
# Story

As an admissions website owner, I would like to see a more visually appealing College taxonomy term page.

# Additional Info

Here is a link to a current example of a college term in the dev environment https://admissions.dev.drupal.uiowa.edu/colleges/college-liberal-arts-sciences-0

The customer is fine with us making our best judgment on how to design these term pages.

# Proposed solution

**Comment by pyrello** [comment]
Some ideas for style updates:
* Add the serif highlight headline style to the "Areas of Study" title. Will probably have to be done via template. The title is created by adding the content type as a hidden field on the view and then adding a grouping based on that field.
* Alphabetize the Areas of Study list.
* Have the list of items display without so much space.
