### ISSUE TITLE
Admissions - AoS Listing/Search Improvements

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#3258]
## Issue

https://github.com/uiowa/uiowa/pull/3249 made things functional, but improvements can be made.

## Proposed Improvements
- [x] I think we are going to need to work on the design a bit. When I added a college, the "Search" button was pushed to a new line, making the whole box very big.
- [x] I think we should consider adding a reset button. The form is somewhat hard to use without it.
- [x] Probably need something other than '-Any-' as a placeholder for those last two boxes. The colleges field takes up a lot of space.
- [x] Can we break the filters into two lines and have it auto-submit to remove the search?
- [x] Is it possible to have auto-submit functionality like D7 site: https://admissions.uiowa.edu/academics/undergraduate-areas-of-study?
- [x] Can we use something like https://www.drupal.org/project/better_exposed_filters to make the filter more dynamic?
- [x] Could we have one search bar across the top of the page with Program Type, Academic Group, and College filters as selects/checkboxes in a sidebar for further filtering? https://www.arizona.edu/degree-search/majors and https://admissions.umich.edu/academics-majors/majors-degrees are examples with sidebar filter.
- [x] It was also requested that we only have two columns for the results (Name and College) and having the other column of information display under the name similar to how it is on their existing site.

**Comment by joewhitsitt** [comment]
Last time I used BEF it didn't announce the autosubmit so there is an a11y concern with going this route and removing the search button.

**Comment by bspeare** [comment]
It looks like the home page search block is inheriting the same filters as noted in https://github.com/uiowa/uiowa/issues/3203#issuecomment-796778508

<img width="1289" alt="screen_shot_2021-03-19_at_9 56 40_am" src="https://user-images.githubusercontent.com/1036433/111801047-8ef9aa80-889a-11eb-820b-797f6c7849da.png">

@pyrello do you have any suggested fixes before you leave?

**Comment by joewhitsitt** [comment]
I will work with the suggestion here: https://github.com/uiowa/uiowa/issues/3203#issuecomment-796778508

**Comment by pyrello** [comment]
Regarding the issue first mentioned [here](https://github.com/uiowa/uiowa/issues/3203#issuecomment-796778508) and illustrated by the above image, here are some ideas for workarounds:
* New display which creates an exposed filter that is limited to the combined search field introduced in #3249. This would require some updates to the logic in the custom block plugin.
* New view which essentially does the same as the above.
* Bespoke search field in the custom block plugin type that directs to the filtering page.

**Comment by bspeare** [comment]
We discussed the filters at today's meeting:

- Is it possible to have auto-submit functionality like D7 site: https://admissions.uiowa.edu/academics/undergraduate-areas-of-study?
- Could we have one search bar across the top of the page with Program Type, Academic Group, and College filters as selects/checkboxes in a sidebar for further filtering?  https://www.arizona.edu/degree-search/majors and https://admissions.umich.edu/academics-majors/majors-degrees are examples with sidebar filter.

**Comment by briand44** [comment]
It was also requested that we only have two columns for the results (Name and College) and having the other column of information display under the name similar to how it is on their existing site.

**Comment by joewhitsitt** [comment]
Not working on this yet, but I will push a branch with the tweaks I made for Thursday's demo as a step forward

**Comment by joewhitsitt** [comment]
So, heads up. The Issue description is a collection of similar/conflicting items. Based on the discussion last Wednesday Sidebar filters and autosubmit seem to be the main deliverables and will be reviewed.

**Comment by dnkemper** [comment]
@joewhitsitt thank you so much, Joe!

**Comment by joewhitsitt** [comment]
Also, SiteNow Articles view page is an example of a single view doing sidebar type layout. I think that uses bootstrap classes though so you might need to find the uids_base equivalents.
