### ISSUE TITLE
Remove entire card link on Areas of Study Admission Process

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#3262]
It was brought up during the Admissions design meeting that they don't like how the entire card is a link on the Areas of Study Admissions Process cards since there are multiple links.

An example was on an Area of Study page (https://admissions.prod.drupal.uiowa.edu/academics/biology).

![Screen Shot 2021-03-19 at 3 08 22 PM](https://user-images.githubusercontent.com/1017022/111837012-3c81b380-88c5-11eb-895b-cfc9d7345359.png)

They also mentioned  it may be nice to have a hover effect or something to make the non button link stand out more.

# Proposed solution

- Once https://github.com/uiowa/uids/issues/531 is completed, update Areas of Study admission process card template (https://github.com/uiowa/uiowa/blob/main/docroot/sites/admissions.uiowa.edu/modules/admissions_core/templates/paragraph--admissions-requirement--default.html.twig) with modifier class to remove card link.

**Comment by joewhitsitt** [comment]
My thought is to create an opt-out class for the card link functionality within UIDS. Then preprocess add the class if multiple links exist.

The requested hover effect is documented here: https://github.com/uiowa/uids/issues/460

**Comment by bspeare** [comment]
@joewhitsitt should we just add the opt-out class to all of the areas of study admission process cards? It seems weird that some cards might retain the linked behavior and some not.

**Comment by joewhitsitt** [comment]
looking back on my comment, I am not exactly sure what I was thinking. opt-out class on all aos admissions process cards sounds like the immediate path forward.

**Comment by bspeare** [comment]
@joewhitsitt thanks for taking a look!
