### ISSUE TITLE
Migrate articles for Parking and Transportation

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#3264]
# Story

As a Parking and Transportation site owner, I would like articles migrated from the Parking and Transportation Drupal 7 site (https://transportation.uiowa.edu) to https://transportation.prod.drupal.uiowa.edu so that users will be able to view all of the past news articles.

# Additional Info
They would like us to map tags according to the following screenshot.

![Screen Shot 2021-03-19 at 3 49 46 PM](https://user-images.githubusercontent.com/1017022/111840646-c3855a80-88ca-11eb-8455-98921748f818.png)

They would like us to programmatically create redirects from old urls.

We should migrate all existing news articles from old site.

They may manually create policy information as news articles.

# Proposed solution

**Comment by mjoneill** [comment]
Comments from Janet on April 2:

> Hi Team,
>  
> Thank you for arranging our meeting in March about migrating Parking website’s news articles. That was very helpful.  May we move forward:
>  
> 1 We will follow the original plan to ask for your help to migrate all news article. (There are a little more than 100 news articles in current site).  Please find the tag mappings at attachment – 1st sheet “Article to Article”.
>  
> 2 Could you also help us migrate some of the Alerts from current site to the new site as Article with another set of tags?
>  We need to migrate these Alerts:
> ·       Mode of Transportation = CAMBUS or Parking; and
> ·       Alert Type = "COVID-19 Service Change" or "UI Hospitals & Clinics service change"; and
> ·       publish date on or after 3/1/2020.
> The tag mapping for the Alert migration can be found at attachment – 2nd sheet “Alert to Article”.
> There are approx. 20 alerts from CAMBUS, and approx. 8 alerts from Parking which have one of the mentioned alert types.
>  
> 3 As mentioned in the meeting, you will kindly help us update some common internal URLs used in articles while migrating them,, so they will point to the new URLs in the new site. We identified 2 commonly used URLs and listed them along with their new URLs (attachment – 3rd sheet “Common URLs”) The new URLs contain the string “.prod.drupal.”. I’m not sure if I should remove that section, because when the site goes live, that section should disappear.
> If you can help us migrate the alerts described at #2, we know that the 2 common URLs are also included in some of those alerts. It would be great if they can be updated to the new URLs as well.
>  
> All tags mentioned in the attachment have been created in the new site. 
>  
> Please let us know if the above plan works for your team. Really appreciate your help!
>  
> Thanks,
> - Janet

[Articles - Mode of Transport - Tag Mapping.xlsx](https://github.com/uiowa/uiowa/files/6258326/Articles.-.Mode.of.Transport.-.Tag.Mapping.xlsx)

**Comment by briand44** [comment]
They said they will manually migrate the alerts mentioned in item 2 above, so we can ignore that.
