### ISSUE TITLE
As a site editor, I can hide the date on the articles teaser list

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#3272]
# Story

As a site editor, I can hide the date on an articles teaser list so that older dates at the top of the teaser list are not visible. 

# Proposed solution

- Replace articles list with exposed filters available in https://github.com/uiowa/uiowa/pull/2702?

**Comment by bspeare** [comment]
@joewhitsitt is this blocked until https://github.com/uiowa/uiowa/issues/3501 is implemented?

**Comment by joewhitsitt** [comment]
From what I have seen from the people listblock view, instead of a teaser view mode fields are used and so this would be an option in #3501

**Comment by bspeare** [comment]
Added the admissions label after we discussed this feature in today's meeting.
