### ISSUE TITLE
Add option on Mega Menu to show 3rd level items

### ISSUE THREAD

**Issue by bewoldt** [uiowa/uiowa#3273]
As I understand it, the Mega Menu navigation option only shows the 2nd level menu items and displays them horizontally across the full width dropdown. I'd like a way to show 3rd level navigation items so that they are stacked in columns underneath their parent.

# Proposed solution

![Screen-Shot-2021-03-25](https://user-images.githubusercontent.com/731952/112510626-9835bc00-8d5f-11eb-9426-74c597f28595.jpg)

**Comment by bspeare** [comment]
@bewoldt What's the expected appearance if your example items under Art are not expanded?  Does the design of the second level change to all caps or would these be only if all caps and bold if `<nolink>` is used as a parent item category?

**Comment by bewoldt** [comment]
@bspeare Here is an rough example codepen. https://codepen.io/bewoldt/pen/QWvWMay

**Comment by bspeare** [comment]
@bewoldt thanks for adding that!
