### ISSUE TITLE
Fix config mismatches after 3.15.5

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#3293]
New token display mismatches and others:

hr.uiowa.edu:
```
core.entity_view_display.node.article.token                                             
core.entity_view_display.node.page.token 
```  

grad.uiowa.edu:
```
migrate_plus.migration.d7_grad_srop_scholar   Only in sync dir
```

grad.uiowa.edu, immuno.grad.uiowa.edu, amcs.uiowa.edu:
```
core.entity_view_display.node.person.token
```

**Comment by joewhitsitt** [comment]
@pyrello do you know what this one is about?

`grad.uiowa.edu - migrate_plus.migration.d7_grad_srop_scholar   Only in sync dir`

**Comment by pyrello** [comment]
Under what conditions are you seeing that?

**Comment by pyrello** [comment]
@richardbporter It looks like the migrate modules are all turned on in prod now... including the Grad-specific ones. Any idea why this would be the case?

**Comment by richardbporter** [comment]
Were they ever turned off?

**Comment by pyrello** [comment]
They were never turned on in prod, but I don't think I turned them off locally after running the imports because it didn't seem to matter.

It seems like I should be able to shut them off now. That is probably a precursor to solving the issue above.

**Comment by joewhitsitt** [comment]
@pyrello can i move forward with #3295 or should something related to [this](https://github.com/uiowa/uiowa/issues/3293#issuecomment-810571826) be tacked on to the PR?

**Comment by pyrello** [comment]
I just disabled the migrate modules on grad.uiowa.edu. I don't think there is any additional work to do there. You should be able to move ahead.
