### ISSUE TITLE
Multisite Provision Process is not working

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#330]
Following the steps to a T, we have bee unable to provision new sites

We are either getting (after local CR and sync):
`Configuration in the database does not match configuration on disk.`

OR

`The module devel does not exist.` after a dev CR

**Comment by joewhitsitt** [comment]
After a chat with Adam last week, the issue appears to be related to devel and possibly stage_file_proxy as require-dev in the composer file. During deployment since these aren't downloaded it errors because it can't find them and needs them to update the site active config (uninstall the module).

Ideally, it would be nice to find a way that these "dev" dependencies are download to all environments, but as long as they aren't installed maybe it isn't an issue.

Would love to get @richardbporter thoughts on this when he gets back.

**Comment by joewhitsitt** [comment]
I don't recall the deploy process failing during the tag deploy to test/prod before. It was successful after I cleared mnh.test and mnh.prod cache and redeploy. We might want to hold off on further site provisions. The mnh site (#310) can now be worked on.

**Comment by richardbporter** [comment]
The config discrepancy is related to the environment splits. I updated the provisioning steps to get around it but this is really annoying.
