### ISSUE TITLE
Signup for Dispatch Communications

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#3302]
# Story

As a SiteNow site owner, I would like the ability to have users sign up to dispatch communications from my website so that users can receive newsletters and other dispatch communications.

# Additional Info

Charlie Taylor would like this functionality on diversity.uiowa.edu.

Our SiteNow site is probably a good test site to use while working on this.

~`Michael Alberhasky has some initial work on the Dispatch side of this and will follow up in a couple weeks.~ This work had been done... https://apps.its.uiowa.edu/dispatch/api-ref#/SubscriptionLists

# Proposed solution

Create a uiowa_dispatch module which has two things initially:

- A configuration page for webmaster to add at least their client API key. More configuration may be needed.
- A Signup Form custom block that takes configuration for a communication/population. Use the API key to query new API endpoint and return embedded signup form.

Because the form can change arbitrarily on Dispatch side, this was preferred method rather than constructing ourselves. AIS agreed to style after UIDS and can add/remove classes as needed.

This module could hold more Dispatch integrations in the future.

**Comment by mjoneill** [comment]
@imuben BTW: looping you in to an issue we had discussed previously. we'll keep you posted as opportunities surface for future conversations.

**Comment by richardbporter** [comment]
https://apps.its.uiowa.edu/dispatch/help/api

**Comment by richardbporter** [comment]
The idea for this was based on the Dispatch integration done for www.facilities.uiowa.edu on uiowa702. The admin form is here: https://www.facilities.uiowa.edu/admin/config/services/facilities-alerts-emails I don't think we need all the other fields right now, just the API key. There are more code examples in the facilities_alerts module of that site.

**Comment by richardbporter** [comment]
We're not sure what endpoint to use to get this signup form.

**Comment by GaryRidgway** [comment]
So I looked in to styling iframes and it looks like it might be a security issue to style iframes. should we create a stylesheet for Michael to serve with a custom version of the form?

**Comment by bspeare** [comment]
Maybe we can just set up the form as the first slice and work on the styling as a follow-up issue?

**Comment by richardbporter** [comment]
I think thats why I did not style the form on https://sitenow.uiowa.edu/. I remember some wonkiness embedding that as well. If I understand this correctly, I think we'd have the same issue if there was an API endpoint that returned markup - we'd still have to embed it.

I would vote for constructing the form ourselves. The first slice could be just the email field, maybe first/last name as well. Custom fields would be difficult but doable assuming they are available in the API. Those could come later.

**Comment by GaryRidgway** [comment]
the base of this module should not be ready, there is still some stuff up in the air on  what we will display and how it is displayed, but a good first stab should be ready.

**Comment by richardbporter** [comment]
Another consideration is that an embedded signup form includes a title. We'd need them to hide it if we wanted to allow people to set a title in LB.
