### ISSUE TITLE
As a site owner, I can control whether my superfish menu items appear as expanded in the main navigation

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#3308]
# Story

As a site owner, I can control whether my superfish menu items appear as expanded. 

Superfish sets all menu items to be expanded by default so that the "show as expanded" option provided by Drupal is overridden.   

<img width="1069" alt="Screen Shot 2021-03-31 at 3 57 39 PM" src="https://user-images.githubusercontent.com/1036433/113210588-01bf3a00-923a-11eb-8a3d-dac97d691f4d.png">

# Proposed solution

- [ ] Change the menu block settings for the Toggle, Horizontal, and Mega menu blocks
  - Update config for these menus https://github.com/uiowa/uiowa/blob/main/config/default/block.block.main_navigation__superfish__toggle.yml, https://github.com/uiowa/uiowa/blob/main/config/default/block.block.main_navigation__superfish__mega.yml, https://github.com/uiowa/uiowa/blob/main/config/default/block.block.main_navigation__superfish__horizontal.yml
- [ ] Create update hook to set all existing menu items as expanded. 
  - Turn on show as expanded options
  - Manually import the appropriate menu type block config per site. 
- [ ] Check against all sites and HR

**Comment by joewhitsitt** [comment]
Should we disable or remove access to the menu item option if it is overridden anyway?

**Comment by bspeare** [comment]
@joewhitsitt What part would we remove access to? This part?

<img width="1112" alt="Screen Shot 2021-04-01 at 9 07 18 AM" src="https://user-images.githubusercontent.com/1036433/113306498-c66c4c00-92c9-11eb-8da5-a1287737df17.png">

**Comment by joewhitsitt** [comment]
>Superfish sets all menu items to be expanded by default so that the "show as expanded" option provided by Drupal is overridden.

Yes, since this will have no effect why show it to users.

**Comment by bspeare** [comment]
Ah, once the changes in this issue are made then it will work.    Currently, it doesn't have any effect if checked.

**Comment by joewhitsitt** [comment]
If touching all menu links, I would batch and then do a menu rebuild after.
Batch update example: https://github.com/uiowa/uiowa/blob/main/docroot/profiles/custom/sitenow/sitenow.install#L181

**Comment by joewhitsitt** [comment]
Test to make sure it doesn't break HR

**Comment by pyrello** [comment]
@joewhitsitt Just took a look at HR. Since it is using a different menu block in a different theme, should we just skip that site? We could run this same migration on that site whenever they move to UIDS Base.

**Comment by pyrello** [comment]
Alternately, we could let the update hook run on HR, since I don't think it will change the behavior on the current menu block because it is using the same setting that we are changing in UIDS base.

**Comment by joewhitsitt** [comment]
If HR tests well with the update hook, I'd let it. One less thing to do later.
