### ISSUE TITLE
As a content editor, I can create a person list filtered by Person Type(s) instead of just Relationships (Tags).

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#3309]
# Story

As a content editor, I can create a person list filtered by Person Type(s) as another option other than Relationships (Tags). That way I can create separate Faculty, Staff, Student, etc pages without having to add Relationships (tags) that duplicate the Person Types.

For instance, lets say I want to create the following structure within all CLAS sites:
<img width="464" alt="Screen Shot 2021-03-31 at 4 39 22 PM" src="https://user-images.githubusercontent.com/3067017/113214859-adb75400-923f-11eb-979c-9d9739c2dfd2.png">

I could create a site split specific to the site, and add additional person types for Professional Advisory Board, Hall of Fame, etc. Then I could create individual pages, edit the layout of the page, and create a filtered block of People based on these Person Types.

As of right now, we enter a Person, and then check the checkbox based on their type. However, if we want to create a filtered list of Faculty, I also have to add a 'Faculty' relationship to each person. I see Relationships as additional filtering beyond Person Types. For instance, Biology has iBio Graduate Students and Genomics Graduate Students. Both types could be checked as Students, but then iBio Graduate Students could have an 'iBio' relationship and Genomics Graduate Students could have a 'Genomics' relationship. Then I could create a list of all Students, a list of iBio students, and a list of Genomics students.

# Proposed solution

Add the Person Types as an available filter in the People list block, in addition to the Filter by tag option:
<img width="681" alt="Screen Shot 2021-03-31 at 4 53 28 PM" src="https://user-images.githubusercontent.com/3067017/113216270-b0b34400-9241-11eb-8773-19e43ffc38b7.png">

**Comment by joewhitsitt** [comment]
Thank you for creating this issue. This has been on my mind for a while.

**Comment by joewhitsitt** [comment]
Ah. @briand44 was right, this issue already exists. https://github.com/uiowa/uiowa/issues/2524 Can we close and consolidate?

**Comment by mark-bennett-uiowa** [comment]
@joewhitsitt Absolutely. Closing this issue in favor of #2524. Adding my text above as a comment there.
