### ISSUE TITLE
Add additional types as default options in Person Types

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#3310]
I anticipate that we will all have one-off examples of person types that we may run across around campus. However, Alumni seems to be an option that would be campus-wide, whether it is used or not for a particular site.

UPDATE: Adding the following as additional types:
Alumni
Adjunct Faculty
Visiting Faculty (may be combined with Adjunct Faculty)
Postdoc (or Postdoctoral Researcher)

Would this be an acceptable option to add to the default configuration as a standard option?

**Comment by joewhitsitt** [comment]
Wondering how this intersects with https://github.com/uiowa/uiowa/issues/2582 if at all. We originally based our person types off what the provost/apr was doing. I am open to this option if we can figure out the bigger picture.

**Comment by mark-bennett-uiowa** [comment]
Reopening this conversation. We are discovering the need for multiple additions to this Person Types list, on a multitude of sites. Would it be possible to add the following to the default, system-wide list of Person Types, available to all sites:

Alumni (it looks like Alumni as a type is needed here: #3305)
Adjunct Faculty
Visiting Faculty (this may or may not fall under Adjunct, depending on political decision)
Postdoc (or Postdoctoral Researcher)

At this point, any additional one-off, individual Person Types could be managed via site split.
