### ISSUE TITLE
Admissions menu structure

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#3312]
Create menu structure for Apply, Admitted Students and Visit Campus in the Admissions Prod environment.

Visit Campus - page that redirects to node/296. No visible children displayed in main menu. When click visit campus the secondary navigation should display first year visit options (active page) and transfer visit options.

Apply - page that redirects to node/21. Visible children displayed in main menu should be Apply Now, How to apply (same as parent menu link), Admitted Students. When click apply link secondary navigation should display first year admissions (active page), transfer admissions, international admissions and additional admission options.

Admitted Students - redirect to node/291? No visible children in main nav. When click on Admitted Students secondary nav will display first-year admitted (active), transfer admitted (node/251) and admitted international (node/1176).

**Comment by briand44** [comment]
Blocked by #3308

**Comment by briand44** [comment]
The Visit Campus menu is complete.

Still need to address Admitted Students page.

Still need to address Transfer Admissions, International Admissions and Additional Admission Options. The Secondary Menu doesn't exist on those pages.

**Comment by pyrello** [comment]
@briand44 Can you take a look at the Admitted section now and help me to understand what, if anything, still needs to be done?

**Comment by briand44** [comment]
@pyrello it looks like the correct items are appearing when clicking on admitted students but when you click on "admitted transfer students" or "admitted international students" the menu does not show on those pages. It looks like this similar issue was fixed on the apply page.

**Comment by pyrello** [comment]
I think this is done now. Please re-open if I missed anything.

**Comment by briand44** [comment]
Admitted Students looks good.

When clicking the following links on the apply page, "Transfer Admissions", "International Admissions" and "Additional Admissions Options", the menu does not show. I thought this was just working but I may have been looking at the dev site.

**Comment by pyrello** [comment]
I fixed those pages as well.
