### ISSUE TITLE
As a site owner, I can build a timeline layout with layout builder

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#3314]
# Story

As a site owner, I can build a timeline layout with layout builder

# Proposed solution

- Create a separate timeline block with paragraph items for each timeline entry
  - Technical details
    - Block will need to be created programmatically in order to place in the "More" block section
    - Media field that allows image or video
    - Font awesome Icon picker field
    - Title
    - Date (date range?) 
      - Date field will be used to group by year in future slice?
    - Description
    - Link w/title
  - Styling
    - Use https://ultimateelementor.com/widgets/timeline/ as design inspiration using card template
    - Alternate position left and right
    - Card alignment and styles options from card block

## Future Slices
- Vertical dot navigation for year based navigation like on https://viewbook.admissions.uiowa.edu/. 
- Waypoints and animate.css scroll animations for each timeline item

**Comment by mark-bennett-uiowa** [comment]
@bspeare I would love this, especially to solve the issues of embedding a JS timeline like these two sites: [https://cs.uiowa.edu/alumni/timeline](https://cs.uiowa.edu/alumni/timeline) and Journalism's (which you cant see anymore).

**Comment by joewhitsitt** [comment]
#655

**Comment by mark-bennett-uiowa** [comment]
As a mentioned above, I now have several sites that would be replacing custom JS timelines with this and they love the idea and the look. I would definitely like to be part of the discussion into this and see this take some priority if possible.

Thoughts:
(1) Is this going to have its own, new, custom Content Type for entry?
(2) Is this going to have us tag News items with a new custom field in Sitenow Articles?
(3) Is this going to allow us a LB interface like Collections, where we can add unlimited Timeline entries?
(4) Will this alternate sides based on Timeline Date automatically?

**Comment by makurj** [comment]
I would like to pair on this.

**Comment by briand44** [comment]
Hancher is interested in this functionality for a timeline of their 50 year history. Some notes from them:

- Needs to be visually rich and inviting to interact with
- Ability to see the whole timeline at once
     - Maybe this could be done by creating one graphic for the whole thing, one graphic for each decade, one graphic for each year, and one graphic for each entry
- Ability to zoom in on select dates and date ranges
- Ability to "drill down" into select dates to see additional images and text
- Ability to edit and add nodes after publication
- Needs to work on mobile

**Comment by makurj** [comment]
I would like to pair on this.

**Comment by briand44** [comment]
Title, image, date, description, ability to link

**Comment by briand44** [comment]
icon picker

**Comment by briand44** [comment]
possible date range to showcase overlap in timeline

**Comment by mjoneill** [comment]
Some "timelines" in the wild on campus:
* https://stories.uiowa.edu/timeline-student-journalism-iowa
* https://www.iihr.uiowa.edu/history/
* https://medicine.uiowa.edu/anesthesia/timeline
* https://chem.uiowa.edu/graduate/for-prospective-phd-students/typical-timelines-for-phd-completion
* https://studentsuccess.uiowa.edu/timeline-initiatives
* http://webeye.ophth.uiowa.edu/ILEB/index.html

**Comment by bspeare** [comment]
Here are a few page builder timeline demos:

https://getwid.getmotopress.com/blocks/content-timeline-block/
https://ultimateelementor.com/widgets/timeline/

**Comment by bspeare** [comment]
It seems like setting up a timeline similar to https://ultimateelementor.com/widgets/timeline/ using the card template makes the most sense for what we need. 

- Image
- Icon picker
- Title
- Date 
- Description
- Link
- Timeline position - left or right
- Card alignment and styles options from card block

If we could group these cards by year, it would be pretty cool to use @GaryRidgway's viewbook dot navigation (https://viewbook.admissions.uiowa.edu/) to move between years.

**Comment by richardbporter** [comment]
>Timeline position - left or right

Can we just alternate left/right and skip this?

**Comment by briand44** [comment]
>Can we just alternate left/right and skip this?

I am fine with that as part of this first slice.

**Comment by bspeare** [comment]
I updated the proposed solution based on our conversation this morning.  Please take a look and add comments or edits if I missed anything!

**Comment by bspeare** [comment]
It looks like @pyrello has an issue out there (https://www.drupal.org/project/lb_direct_add/issues/3098555) allowing `lb_direct_add` to exclude blocks from the initial menu, so maybe we don't need to build this block programmatically?
