### ISSUE TITLE
File replace caching

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#3327]
## Issue

Varnish for the file is not purged when replaced.

>Most likely, static files (.txt, .pdf, etc) served from your website will be cached by external caches for a long time, which means if you replace the contents of a file on your web server, users may not see the update content. External caches include things like a Varnish, a CDN, and a browser. You can control the behavior of external caches by emitting certain HTTP headers for static file responses. This cannot be configured in Drupal, because Drupal is not involved in serving static file assets. Your web server is.

-- https://www.drupal.org/project/media_entity_file_replace

## Proposed Solution

Any or some of these would make an improvement

- If you can, configure your web server to emit an ETag cache header for static file assets instead of a max-age header.
- Set a short max-age header for static file assets. Drupal's default .htaccess file (which provides configuration for Apache) sets a max-age header to 2 weeks for static files. You can lower this to something like 5-10 minutes. You may need to inform your content editors that all users may not see the updated file contents for some time.
- Button to update metadata - https://www.drupal.org/project/drupal/issues/2983456
- Image purging - https://www.drupal.org/project/purge/issues/2920332
- Varnish purge - https://www.drupal.org/project/varnish_purge

**Comment by richardbporter** [comment]
I assume you already found https://www.drupal.org/project/media_entity_file_replace/issues/3115477 but just adding it here in case.

**Comment by joewhitsitt** [comment]
I hadn't seen the recent comments on that but yes. We could do something similar to what we are doing for brand lockup files: docroot/sites/brand.uiowa.edu/modules/brand_core/brand_core.module

**Comment by pyrello** [comment]
My comment from Slack:
> Can we write some custom code to hook in to the entity save event for the file and check if the file name is the same but that the file has changed? And then clear the cache?

**Comment by richardbporter** [comment]
> My comment from Slack:
> 
> > Can we write some custom code to hook in to the entity save event for the file and check if the file name is the same but that the file has changed? And then clear the cache?

Seconded. Look for core/contrib patch/option that does this first then custom code.

**Comment by richardbporter** [comment]
Brand lockup example: https://github.com/uiowa/uiowa/blob/14f7d298b109e1642774285477b274e2f4e9c830/docroot/sites/brand.uiowa.edu/modules/brand_core/brand_core.module#L391-L424

**Comment by dnkemper** [comment]
THANK YOU, @richardbporter 🥳

**Comment by richardbporter** [comment]
sitenow_media_wysiwyg might be a good place for this.

**Comment by richardbporter** [comment]
#4322 is working great for files. Are we concerned about other media types - audio, image, social media post, etc.? Have those been reported as problematic? I've only heard about files. Other types could be trickier, for example images would need to include derivative regeneration and purging.

**Comment by dnkemper** [comment]
^^tested and same. Could I checkout https://www.drupal.org/project/purge/issues/2920332 or are you wanting a custom solution for this too? Also, what about that patch that updated the thumbnail image?

**Comment by richardbporter** [comment]
I'd vote to keep this limited in scope to files specifically since that seems to be most common and not worry about images, video, etc. for now.

**Comment by dnkemper** [comment]
@richardbporter AWESOME! Sold!

**Comment by joewhitsitt** [comment]
>I'd vote to keep this limited in scope to files specifically since that seems to be most common and not worry about images, video, etc. for now.

I was referencing the "file" entity when writing this issue which is what media_entity_file_replace covers. Is it a big lift to also handle file entities like images, audio, local video?

**Comment by richardbporter** [comment]
For whatever reason, browsers don't seem to hold on to documents (txt, pdf, etc) as long as audio and images. #4322 definitely works well for documents and there is an obvious use case for people sending out links to documents in emails and other communications.

I see less of a use case for audio and images. Not replacing audio and especially images, actually works better for caching. New image styles are generated, references are updated and browsers don't have the new file name in cache so the change is seen as immediate.

I wonder if we should alter the media update form to do one or more of the following:

- advise users not to replace images and/or audio due to browser caching
- uncheck replace by default for images and/or audio
- remove file replace functionality from images and/or audio

**Comment by joewhitsitt** [comment]
I am okay with:
- unchecking `Overwrite original file` for images/audio. i could also be persuaded to remove editor access to the checkbox for these two media types.
- i think a message on all replace media types would be helpful "there are potential caching issues with file replacement"

I don't think removal of the functionality all together is a good idea. the big benefit is to upload a replacement and have it be updated (eventually) where ever it is used.

Did you find out if the old file is deleted if the file is replaced and not overwritten?

**Comment by richardbporter** [comment]
I guess I assumed old files were deleted based on https://github.com/uiowa/uiowa/pull/2165. I can double check though by lowering temp file time to like 60 seconds.

**Comment by joewhitsitt** [comment]
>If "Overwrite original file" is unchecked, the original functionality of the main file/image widget is maintained. A new file entity is created, and the media entity is updated to reference it. The old file entity is referenced, and may be marked as temporary (for deletion) if nothing else on the site is referencing it. - https://www.drupal.org/project/media_entity_file_replace

Though grouped together in #2165 they had two different goals at the time. Offer replace functionality and delete files marked for deletion (including backlog files pre-8.4). I don't recall thinking a whole lot about the relationship between the two.

**Comment by richardbporter** [comment]
> > If "Overwrite original file" is unchecked, the original functionality of the main file/image widget is maintained. A new file entity is created, and the media entity is updated to reference it. The old file entity is referenced, and may be marked as temporary (for deletion) if nothing else on the site is referencing it. - https://www.drupal.org/project/media_entity_file_replace
> 
> Though grouped together in #2165 they had two different goals at the time. Offer replace functionality and delete files marked for deletion (including backlog files pre-8.4). I don't recall thinking a whole lot about the relationship between the two.

I'm not seeing file_usage changes or the status of the old file set to 0 in file_managed. :(

**Comment by richardbporter** [comment]
> I'm not seeing file_usage changes or the status of the old file set to 0 in file_managed. :(

I think this is due to media revisions which apparently are a thing without a UI. I enabled https://www.drupal.org/project/media_revisions_ui, deleted all past revisions for one media entity and saw one old file removed. A couple others persisted for some odd reason. Looking in the database, I see 3 revisions for the media I'm working with and none in the UI. That must be why.

**Comment by richardbporter** [comment]
> unchecking Overwrite original file for images/audio. i could also be persuaded to remove editor access to the checkbox for these two media types.

I was leaning this way. I'm ok with leaving access to editors in case someone does have a use case for sending out links to images/audio.

**Comment by richardbporter** [comment]
Talked with @joewhitsitt. Maybe to avoid risking creating orphaned files, we should merge #4322 as-is and dig deeper into media revisions in a follow-up. We are purging all we can in #4322.
