### ISSUE TITLE
Vimeo embed error

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#3329]
The issue was first reported on iwp.prod.drupal.uiowa.edu, but I was able to reproduce on sandbox.prod.drupal.uiowa.edu. The issue does not appear to affect existing Vimeo embeds: https://media.journalism.uiowa.edu/alumni-stories

# Steps to reproduce
1. Visit https://sandbox.prod.drupal.uiowa.edu/node/1/layout
2. Add a text area block and add a media library element to it.
3. Select Remote video, paste in https://vimeo.com/225310021/db626debd8 and hit Add.

# Proposed solution
* Investigate whether other videos can be embedded.
* TBD

**Comment by joewhitsitt** [comment]
I think it is something with this or other videos of this account. I tried this version of the video as well: https://vimeo.com/225310021

Historically it has something to do with a Vimeo privacy setting on the video.

I was able to add one of the videos (first one, from different account) from https://media.journalism.uiowa.edu/alumni-stories and previously that one from yesterday. I also have no problem with the definitely public ones here https://vimeo.com/watch

<img width="1046" alt="Screen Shot 2021-04-02 at 1 10 38 PM" src="https://user-images.githubusercontent.com/4663676/113442008-ddd43380-93b4-11eb-9b25-a3c6c69940ea.png">

**Comment by joewhitsitt** [comment]
I would recommend the customer look into the privacy settings for these videos: https://vimeo.com/blog/post/video-privacy-explained/

Vimeo has a special "nowhere" and "anywhere" settings that makes video shareable externally.

**Comment by pyrello** [comment]
I sent en email to the customer to see if they are still encountering this error.

**Comment by briand44** [comment]
Closing this since customer hasn't let us know if this is still an issue. We can re-open if we hear it is still a problem.
