### ISSUE TITLE
Implement UIDS table changes, strip table classes from text areas, update table JS

### ISSUE THREAD

**Issue by GaryRidgway** [uiowa/uiowa#3330]
Part of the [507 Responsive Tables](https://github.com/uiowa/uids/issues/507) epic.

As a tables user, after https://github.com/uiowa/uids/issues/509 and https://github.com/uiowa/uids/issues/510 are completed the `table--static` and `table--is-striped` classes will no longer be relevant.

# Proposed solution
- [ ] Implement UIDS table default styles and responsive solution updates.
- [ ] Iterate through all text areas and remove the `table--static` and `table--is-striped` classes from them in an update hook.
- [ ] Update UIDS tables JS implementation to match UIDS.

**Comment by joewhitsitt** [comment]
It would be nice to coordinate this with https://github.com/uiowa/uiowa/issues/3078 so we are only passing through sites once.

**Comment by GaryRidgway** [comment]
After talking with @pyrello we should probably wrap all tables with a scroller div in this hook as well, as described in uiowa/uids#510.
