### ISSUE TITLE
Communicate to users that responsive behavior is changing

### ISSUE THREAD

**Issue by GaryRidgway** [uiowa/uiowa#3333]
Part of the [507 Responsive Tables](https://github.com/uiowa/uids/issues/507) epic.

Users need to be told that the default tables and responsive tables behavior is changing. This should be communicated to them.

# Proposed solution

1. Talk with team about what should be conveyed.
2. Possibly email all webmasters that the behavior is changing and make an announcement on all Demo material including the demo presentation, articles, and emails?

**Comment by pyrello** [comment]
I think that we handled this with the April update email and dispatch communication.
