### ISSUE TITLE
SPPA: Build article migration

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#3343]
# Proposed solution

- [x] Create SPPA migration module.
- [x] Add article migration.
  - [x] First delta of `field_image_attach` can become the featured image. Any other deltas can be ignored.
- [x] Add article redirect migration.

The following fields can be ignored:
* `field_d8_migration_status`
* `field_multi_public_file`
* `field_newsstory_caption`

**Comment by joewhitsitt** [comment]
Sorry but which site in the grad d7 application does this align with? I don't see the same acronym.

**Comment by pyrello** [comment]
`urban`
