### ISSUE TITLE
Adjust APR styles

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#3348]
> Increase the font size of the Rank/Title displayed under the photo
> List each website on a separate line. They currently run together in some cases. (https://pharmacy.prod.drupal.uiowa.edu/people/guohua-an)
> List the office phone number below the Primary Office and with a heading of “Phone”. In some cases the phone number is listed with the address. (https://pharmacy.prod.drupal.uiowa.edu/people/vern-k-duba)
>  
> Also, I noticed on the main directory page https://pharmacy.prod.drupal.uiowa.edu/people, the rank/title isn’t always listed below the name.  Is there a way to ensure it gets listed below the name?

**Comment by pyrello** [comment]
Probably should have chimed in on this before it it got pointed, but should we adjust the design of the APR pages to be more in line with the way the person page looks? I think that the new People Directory is going to be more modeled after that, so it seems like we should probably have this be consistent.

**Comment by joewhitsitt** [comment]
Isn't this solution just a stop gap solution until the new thing which will be different markup, etc.? If so, I would do the quick solution for now.

**Comment by pyrello** [comment]
How long are we going to have it as a stop gap?

**Comment by joewhitsitt** [comment]
🤷 good question

**Comment by richardbporter** [comment]
Yea I don't know either. I do know they are not going to make any changes to the markup because this new solution is coming at some point. So any attempts to match it up to our person pages would have to all be done in CSS.

**Comment by bspeare** [comment]
Should we remove the "Back" link on profile pages too?  That link only works if you navigate to the page from the directory.

**Comment by GaryRidgway** [comment]
@bspeare I think we should. If it is not functioning correctly then it should be removed.

Also, in order to fix the 'Phone' issue without adding HTML, I've added a Pseudo element that adds a similar title to how the other titles are listed, as such. 

![Screen Shot 2021-04-19 at 1 32 21 PM](https://user-images.githubusercontent.com/23122142/115285658-bd75da00-a113-11eb-8dc9-a9d51029b9dc.png)


Hope that works for everyone else.
