### ISSUE TITLE
Long text in sidenav breaks layout

### ISSUE THREAD

**Issue by bewoldt** [uiowa/uiowa#3352]
# Problem
If you have a long page name with no breaking spaces in it the side navigation will grow to a point where it breaks the layout and the main content area wraps underneath the sidenav.

# Steps to reproduce
You can see it in action here. https://stanleymuseum.prod.drupal.uiowa.edu/about. The page title of "Employment/Opportunities" is breaking the layout.

# Proposed solution
You could force a break on the text with `word-break: break-all;` on the anchor.
or 
add and ellipsis to the end of the text

**Comment by bspeare** [comment]
@bewoldt Can you provide a screenshot?

**Comment by bewoldt** [comment]
<img width="1186" alt="Screen Shot 2021-04-08 at 1 55 08 PM" src="https://user-images.githubusercontent.com/731952/114081400-2175e400-9872-11eb-9087-8d41e5d4868a.png">
