### ISSUE TITLE
Post-migrate areas of study content issues

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#3354]
Multiple issues were found after running the AOS migration.

- Almost every AOS contains a broken link to http://uiowa.orgsync.com/ in the student opportunities field. It should point to https://uiowa.campuslabs.com/engage. A redirect is not possible.
- This broken link also exists in the default value for the student opportunities field.
- The degree abbreviations seem to contain an extra space in the parentheses.
![image](https://user-images.githubusercontent.com/1068523/114190182-a44d7c00-9910-11eb-8175-9cfd89f6e8fb.png)

### Proposed solution
Update the default value for student opportunities. Write an update hook to update that orgsync link in every AOS, if it exists. Write an update hook to remove the extra space in the degree abbreviations.

**Comment by bspeare** [comment]
I just checked the extra space on the parentheses and it doesn't appear to be `CSS` related.

**Comment by richardbporter** [comment]
> I just checked the extra space on the parentheses and it doesn't appear to be `CSS` related.

I thought it was maybe migrated with that extra space but this is an options field and those values don't seem to have whitespace before/after. I'm not sure where its coming from...

**Comment by bspeare** [comment]
OK, maybe it is `CSS` then.  I'll take another look.
