### ISSUE TITLE
Update education.uiowa.edu to use brand gold

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#3355]
# Proposed solution

Update radix theme variable to use brand gold primary hex color on https://uids.brand.uiowa.edu/components/detail/colors.html.

**Comment by joewhitsitt** [comment]
Branch `education-brand-gold` on 703

**Comment by joewhitsitt** [comment]
<img width="628" alt="Screen Shot 2021-04-15 at 9 06 48 AM" src="https://user-images.githubusercontent.com/4663676/114882813-f50a1c80-9dc9-11eb-951b-11880257bfc0.png">

Done
