### ISSUE TITLE
Build Computer Science news migration

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#3357]
# Background

Computer Science news entries (News and Announcements, machine name 'article') have the following fields:

- Title (machine name: title)
- Section (will not be used, workbench access is no longer needed)
- Date (machine name: field_event_date)
- Body (machine name: body)
- Image (machine name: field_image)
- Image Gallery (machine name: field_image_gallery)
- External Link (machine name: field_news_external_link; URL and Optional Title)

# Proposed solution

This may be a relatively straight-forward migration of the following (OLD --> NEW):

Title --> Title
Section --> Relationships (will add these tags in preparation of migration, can ignore x,x, and x)
Date --> Authored on date
Body --> Body (can we take a 150-200 character substring and copy to Article Summary??)
Image --> Featured Image
Image Gallery --> ignored???
External Link title --> ignored
External Link URL --> Source Link

**Comment by cory-skeers** [comment]
Notes from discussion re: image gallery.

Think we're good with appending these in the body at the end of the article. Likely use the `fetchMultiField` to grab the images, create media entities, and append these to the body using either the `replaceInlineFiles` or DOM method.
