### ISSUE TITLE
Taxonomy Term Styling

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#3358]
## Issue

Taxonomy term pages (e.g. tags) include teasers that are un-styled and publicly viewable.

## Proposed Solution

Extend the card styling for the default content type teasers. It is the responsibility of the developer to extend similar styles to each custom content type that can reference a publicly viewable taxonomy.

- [ ] https://github.com/uiowa/uiowa/issues/1955 Page Teasers

**Comment by mark-bennett-uiowa** [comment]
@joewhitsitt Here are some links to the Table of Contents styling I mentioned in planning:

[https://uiowa.edu/a-z](https://uiowa.edu/a-z)
[https://policy.clas.uiowa.edu/table-of-contents](https://policy.clas.uiowa.edu/table-of-contents)
[https://policy.clas.uiowa.edu/a-z](https://policy.clas.uiowa.edu/a-z)

**Comment by joewhitsitt** [comment]
i like the clean look of titles only, but Rick mentioned folks are using the RSS feeds with these vocabs as well so having teasers display as well would help fill out those feeds.
