### ISSUE TITLE
Re-provision dei.sports.uiowa.edu as dei.athletics.uiowa.edu

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#3367]
I heard back from Athletics and they would prefer going with dei.athletics.uiowa.edu. 

Remove dei.sports.uiowa.edu
Request domain/reclaim dei.sports
Provision dei.athletics.uiowa.edu

Remove *.sports.uiowa.edu
Cover *.athletics.uiowa.edu

We should communicate with Wendy and Eddie Etsey once provisioned.

**Comment by joewhitsitt** [comment]
Site created emails went out. @briand44 is more communication beyond that needed?

**Comment by briand44** [comment]
Was Eddie included on those or just Wendy?

**Comment by briand44** [comment]
Nevermind, looks like just Wendy, I'll let Eddie know as well. Thanks!

**Comment by briand44** [comment]
Can this be closed?
