### ISSUE TITLE
Build Physics and Astronomy news migration

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#3369]
# Background

Physics and Astronomy news entries (News, machine name 'clas_news') have the following fields:

- Title (machine name: title)
- News Tags (machine name: field_clas_news_tags; a taxonomy-ish term reference field to tag entries as Space Physics, Plasma Physics, etc news)
- News Date (machine name: field_clas_news_date)
- News Description (machine name: field_clas_news_description)
- News Link (machine name: field_clas_news_link; URL and Optional Title)

I need to get feedback on how often the News Tags are used, which I will update here.

# Proposed solution

This may be a relatively straight-forward migration of the following (OLD --> NEW):

Title --> Title
News Tags --> ignored for now, Relationships (will add these tags in preparation of migration, can ignore x,x, and x)
News Date --> Authored on date
News Description --> Body (can we take summary and copy to Article Summary??)
News Link title --> ignored
News Link URL --> Source Link

**Comment by mark-bennett-uiowa** [comment]
This should be available to test if you get a chance @cory-skeers . I can explain what I was trying to do with the tags next week.

**Comment by pyrello** [comment]
@mark-bennett-uiowa If this is going to be closed by a PR, then our standard practice is to put it into the Blocked column until the PR merges.

**Comment by mark-bennett-uiowa** [comment]
@pyrello Sorry, I thought that the PR had already been merged and we were waiting for closer to launch to actually run the migration. Ill move this back to Blocked/Waiting.
