### ISSUE TITLE
Search and replace strings of text

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#3373]
# Story

As a site webmaster, I would like the ability to search for a string and replace all instances of it so that I don't have to make the change in every instance it is used.

# Additional Information

We have a custom module "Find Text" in use on SiteNow v1 sites.

https://www.drupal.org/project/scanner was also mentioned as a module that has been used for this type of functionality.

Probably some conversations needed here to understand what types of fields this could work on and what wouldn't be possible as well as if this would be safe for webmasters to use or if it should be limited to administrators.

# Proposed solution

**Comment by cory-skeers** [comment]
Also interested in potentially using this to search for instances of *.prod/stage/dev/local links that have been hardcoded as a pre-launch check. This would potentially increase the scope, where link fields would need to be checked as well, but might be needed anyway (could see the use case of looking for any links to a particular site, 3rd party source, etc).

Think would want to use the Drupal API to dynamically pull relevant fields to query against, but particular implementation needs to be worked out.

**Comment by cory-skeers** [comment]
Parking a few comments here.

- First slice, find text, with potential followup slices of replace text functionality
- There are two sides of this: The content editor looking to find specific text content on their site (links, mentions of content, etc), and developer looking for specific text content (links, inline classes, entity embeds, etc). For the latter, can see the desire for cli, on-site tools, and/or an API to be able to use this functionality in other modules.

**Comment by cory-skeers** [comment]
Right off the bat, trying drupal/scanner led to a WSOD (specifically on a line that was attempt to add the message "There were some errors.")

Likely still a good reference, but looks like it'd need some patching to get working at minimum, as well as a custom plugin to work with layout builder. Currently works for direct node content fields and paragraphs.

**Comment by bspeare** [comment]
Based on previous site launches, it seems like the majority of the hard-coded `.prod` links are used in link fields on cards and ctas.   Are we looking for this module to find these or we planning on using another solution?

**Comment by cory-skeers** [comment]
> Based on previous site launches, it seems like the majority of the hard-coded `.prod` links are used in link fields on cards and ctas. Are we looking for this module to find these or we planning on using another solution?

This module is intended to check those as well, and already has code in place to handle link fields separately from how plain string fields are handled. If it's not currently catching those, then there's a bug(s) to be worked out 😬

**Comment by bspeare** [comment]
Thanks for the clarification @cory-skeers !
