### ISSUE TITLE
Migrate news articles for International Programs

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#3375]
# Story

As an International Programs site owner, I would like articles migrated from the International Programs Drupal 7 site (https://international.uiowa.edu) to https://international.prod.drupal.uiowa.edu so that users will be able to view all of the past news articles.

# Additional Info

Need  to get additional info in regards to:
- when they hope to launch - end of August(ish)
- migrating tags - yes
- migrate author labels (multiple) to organization field
- creating programmatic redirects
- if we are migrating all articles or articles going back to a specified date - migrate all articles beginning January 2015
- how handling broken links

# Proposed solution

**Comment by briand44** [comment]
Pharmacy would be a good site to look at.

**Comment by cory-skeers** [comment]
As part of the migration, run a report of potential non-article broken links (looking for /node references; Parking and Transportation and/or Admissions may have examples of this). Can provide the list of these to the client to decide whether they need to be mapped for the migration, remove the links, etc.

Article links can be updated as part of the migration using existing tools.

**Comment by joewhitsitt** [comment]
Should the author (field_news_author, term reference) be migrated over as an organization string? These values won't match up to person content on the site. (e.g. IP Staff)

**Comment by joewhitsitt** [comment]
We hit a bit of a bump with the migration of over 3k nodes… Memory issue.

**Comment by joewhitsitt** [comment]
Reached out to customer about https://github.com/uiowa/uiowa/issues/3375#issuecomment-868756795

**Comment by joewhitsitt** [comment]
Updated issue-summary to include migrating author labels (multiple) to the organization field.

**Comment by cory-skeers** [comment]
Thanks @joewhitsitt!
