### ISSUE TITLE
Embed UICapture/Panopto videos

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#3392]
# Story

As a SiteNow content editor, I would like the ability to embed UICapture/Panopto videos on my website similar to YouTube and Vimeo.

Panopto does not provide an oEmbed option.

# Proposed solution

- From what we learned with https://github.com/uiowa/uiowa/issues/3450, create a generic iframe or Panopto media type where an editor provides a share URL and the url is parsed into a rendered embed. Panopto provides an embed api instead of us maintaining an iframe object ourselves.

# Nice to have

- Embed Panopto Playlists
- Embed a Panopto Department

The second point is that I think we should explore is the ability to embed playlists. It uses the same "Embed.aspx" player, but the "id=" changes to "pid=" so maybe this could be a checkbox when users are entering their information. I didn't think of that initially, but I think it would be good to at least explore. Here is an example of the embed player loaded with a playlist: https://uicapture.hosted.panopto.com/Panopto/Pages/Embed.aspx?pid=f5642cc1-3863-4171-8fa0-acbd0102df02

The last thing that I had was something to support users who might want to share using the full player without needing to support embedding that player directly. If one embeds a folder, users that select content and click-through will be directed to the full player. That will also allow people to embed a Panopto "Department" within their existing sitenow sites. Below is an example of a department in an iFrame:
`<iframe src="https://uicapture.hosted.panopto.com/Panopto/Pages/EmbeddedList.aspx?folderID=cbca7443-6b29-4931-83be-acbd010219f2&embedded=1" height="405" width="720" style="border: 0;" ></iframe>`
Folders diverge from the format of videos and playlists, but I think this would be a better route than trying to embed the "Viewer.aspx" player. Much like the playlists, I don't think this is a "need" but I could see it being useful so it might be good to dig into some.

# Resources
- https://uicapture.hosted.panopto.com/Panopto/Pages/Sessions/List.aspx# (click a video and see/click share icon for URL to parse)
- https://www.codimth.com/blog/web/drupal/create-ckeditor-custom-plugin-drupal-8
- https://support.panopto.com/s/article/Learn-About-Panopto-Embed-API
- https://www.drupal.org/docs/8/core/modules/media/creating-and-configuring-media-types
- https://www.drupal.org/docs/8/core/modules/media/creating-a-custom-mediasource-plugin-for-external-assets
- https://git.drupalcode.org/project/media_entity_remote_image/-/tree/8.x-1.x
- Michael Espey (ITS)

**Comment by dnkemper** [comment]
if I don't get to this issue, would love to pair/ be a fly on the wall with the person that works on this because last/only time I've ever created a media type was for audio files over a year ago/before the homepage project 🙏

**Comment by joewhitsitt** [comment]
This will be more involved that the audio media type which ships with core and will require us lifting a mediasource plugin from another module or creating our own.

If I was to take this up (maybe later), I would see about using the javascript api panopto provides (resources above) instead of constructing the iframe. 

media_entity_panopto exists but i don't think it works or is being maintained.
media_entity_remote_image might be something to work off of as it takes in a url and validates.

sitenow_media_wysiwyg would be where I would create this initially.

**Comment by joewhitsitt** [comment]
I think for MVP and a replacement to Kaltura, we should just take in the regular video format and validate against it to prevent saving other types. The playlist/department options, while easy to look for/switch have different display considerations (e.g. aspect ratio) as well as additional a11y navigation concerns..

**Comment by richardbporter** [comment]
It seems like creating the iFrame markup ourselves would have been easier than using the Javascript embed API.

**Comment by richardbporter** [comment]
I'm not seeing any attributes available in the link, for example the title and thumbnail image. The media_entity_panopto module was querying the API for that data using the ID in the URL. The ID is the only thing available in the URL.

**Comment by richardbporter** [comment]
Hm. On the UICapture site, I'm seeing thumbnails created by a redirect URL. For example, on https://uicapture.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=a4bfc444-ad63-42f2-bef3-7ad4905ab649 the #splashScreen div has a background pointing at `/Panopto/Services/FrameGrabber.svc/FrameRedirect?objectId=a4bfc444-ad63-42f2-bef3-7ad4905ab649&mode=Delivery&random=0.304899272650899&usePng=False`. That gets redirected to this image: https://d2y36twrtb17ty.cloudfront.net/sessions/2e38a9e9-36a6-45c7-9e32-7c9c0c15d4f0/1a19dc83-54a6-425a-935a-d319d8c7c8a7_et/thumbs/slide1.jpg

I can investigate wiring up the thumbnails using that.
