### ISSUE TITLE
As a user of search, I can get directed to search.uiowa.edu if it provides value, i.e. additional results.

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#3409]
# Story

As a user of search, I can get directed to search.uiowa.edu if it provides value, i.e. additional results.

Unfortunately, it does not in every context. It is displayed all the time and provides no value if a site is configured to use the default CSE and not limit to the current domain. 

# Proposed solution

~~Hide the link if a site is using the default CSE ID and not limiting the scope to the current domain.~~

**Comment by richardbporter** [comment]
Hiding it automatically seems to cover all the use-cases except if down the road there is a site that:

- has a university brand exception (regents tri-funded)
- has their own cse id
- wants to limit search to their site

Maybe it should be a config option. I think that would be the easiest long term instead of dealing with politics down the road. On by default, turned off for the homepage. Let webmasters decide.

**Comment by richardbporter** [comment]
Whoops.

**Comment by joewhitsitt** [comment]
This is now a configurable option. It has been turned off for the homepage. The link has been updated to point to uiowa.edu/search. [search.uiowa.edu is slated for retirement](https://github.com/uiowa/uiowa/issues/7464).
