### ISSUE TITLE
Admissions - Report of Long Text Full_HTML fields

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#3419]
## Issue

We suspect that during migration, fields with full_html on the old site were migrated over to the new site the same way where editors don't have access. Additionally, fields have been marked full_html intentionally by developers to provide embeds.

## Proposed Solution

- [x] Query the admissions site for long text and long text summary fields with the full_html format. Provide the entity id associated with one.
  - There are a couple of examples of queries that could be run locally that output messages that could be turned into something to hand over to admissions.
  - https://github.com/uiowa/uiowa/blob/ea2052f6822e02b5c34ceaaca1c73e03c82ac29c/docroot/profiles/custom/sitenow/sitenow.install#L2449
- [ ] Ask Admissions which fields can be turned back to filtered_html and either run an update hook or manually correct.

https://iowaweb.slack.com/archives/C019B2C8K8U/p1619115149056800

**Comment by joewhitsitt** [comment]
Forgot to bring this up for grooming/planning.

**Comment by pyrello** [comment]
This is going to be slightly more difficult than I was originally thinking because of text areas in blocks in Layout Builder. The entity ID in the field table is for the block and so we can't provide it to the client like we can with a node ID.

**Comment by joewhitsitt** [comment]
Changed the IS to show an earlier version of the MEGA update hook where it went through each db table instead where the entity id is available

**Comment by pyrello** [comment]
The entity ID is the block content ID, which isn't helpful unless you know which node ID they correspond to.

**Comment by joewhitsitt** [comment]
ah

**Comment by cory-skeers** [comment]
> The entity ID is the block content ID, which isn't helpful unless you know which node ID they correspond to.

Get the list of full html block IDs, then check the `layout_builder__layout` field for instances of any of the block IDs in the blob text?

**Comment by briand44** [comment]
Update: Scott mentioned in today's meeting that he expects all of the Areas of Study fields currently using full html, don't need to be (no embeds or anything currently in these). Likely all items listed in report will need fixed.

**Comment by pyrello** [comment]
Does this mean he is requesting that we update the field format in addition to identifying it?

If so, we can maybe put some basic parameters around it (such as limiting it to Areas of Study content items), but beyond that, it is pretty much going to be all or nothing. That means if they did happen to have any content that is not compatible with the limited HTML format, it will get wiped out the next time the content item is saved.

**Comment by briand44** [comment]
asking in the admissions slack channel to clarify. Depending on Scott's response could we possibly update all areas of study fields to use the appropriate text format but just provide the list for non areas of study?

**Comment by pyrello** [comment]
I think so.

**Comment by pyrello** [comment]
@bspeare brought up during our update hook session that we can probably exclude block content from the report since we didn't migrate any content into the page content type. So, the existing `full_html` fields related to block content should be all intentional. Does that seem right? @richardbporter and/or @cory-skeers?

**Comment by cory-skeers** [comment]
That...is a very good point, and I think a fair assumption. The full_html blocks should only be the embeds we've added on various pages then. And if we can update all AoS fields, then that simplifies things quite a bit, doesn't it?

**Comment by richardbporter** [comment]
Yea I think that makes sense. We only migrated AOS data.

**Comment by pyrello** [comment]
Preliminary runs seem to suggest that we are going to update some items that are AoS's and Transfer Tips (because they were created from the original AoS) and we will have one other page, which I'm assuming is an embed we did for them.
