### ISSUE TITLE
Hide {sitename}.prod...edu from search engines

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#343]
### Problem:
A site being staged in the prod environment is starting to see search results for their site even though they have yet to launch.

Since our workflow for converting existing D7 sites to D8 involves using the .prod domains these sites are already out there and exposed.

I don't know if we ended up implementing for DEV/STAGE yet, but we should consider those at the same time.

In D7 robots.txt module was being used. I remember an early discussion that we may not want to go that route this time around.

**Comment by richardbporter** [comment]
I don't think we can easily distinguish between live/stage sites in prod at an application level. People probably should be staging content in stage. 

However, after #516 is merged, sites being staged in prod can split the config if needed. I don't think that should be set on site initialization.
