### ISSUE TITLE
Deprovision gsab.org.uiowa.edu 

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#3433]
The customer has requested that their site be moved from gsab.org.uiowa.edu to cgsa.org.uiowa.edu.

**Comment by GaryRidgway** [comment]
Is this a possible opportunity to have them move to v3 as well?

**Comment by pyrello** [comment]
It seems like an opportunity for that. I guess it would be up to the customer whether they have the capacity to go through that effort at the moment.

**Comment by richardbporter** [comment]
Unfortunately, this requires a new provision, deployment and file/db sync. We've talked about actually supporting renaming in the past but haven't got there yet.

**Comment by richardbporter** [comment]
The rename process would at least involve:

- Removing the filesystem test that checks each site.
- Renaming the site directory.
- Updating the sites.php file.
- Updating the site's blt.yml file.
- Deploying a release.
- Renaming the site's files directory.

Creating new sites, syncing them and deleting the old ones might actually be the cleaner option.

**Comment by GaryRidgway** [comment]
Talked to Lucas today and he seems generally on board with migrating to V3. I explained to him the process once he response I will comment with an update. This might turn out to be as easy as a site provision. **Fingers crossed**

**Comment by GaryRidgway** [comment]
They have agreed to migrate to v3. This is now to deprovision after migrated.
