### ISSUE TITLE
Layout builder columns do not correctly render if adjacent columns are empty

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#3445]
# Problem
Layout builder columns do not correctly render if adjacent columns are empty

# Steps to reproduce
As reported by @bewoldt, you can view the issue at https://stanleymuseum.prod.drupal.uiowa.edu/giving.

<details>
<img width="1471" alt="Screen Shot 2021-05-03 at 3 58 59 PM" src="https://user-images.githubusercontent.com/1036433/116932938-854cbc00-ac28-11eb-9e19-72be53259695.png">
<img width="1613" alt="Screen Shot 2021-05-03 at 4 01 55 PM" src="https://user-images.githubusercontent.com/1036433/116933275-f42a1500-ac28-11eb-87f0-dd31abdf08b3.png">
<img width="1635" alt="Screen Shot 2021-05-03 at 4 02 12 PM" src="https://user-images.githubusercontent.com/1036433/116933294-f8563280-ac28-11eb-8e09-711198f9857b.png">
</details>

# Proposed solution
- Work with the initial work started in https://github.com/uiowa/uiowa/compare/feature_layout_gaps.
- Test on different browsers
- Test on IE

**Comment by makurj** [comment]
I would like to pair on this.
