### ISSUE TITLE
Create media collections

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#3453]
# Motivation
IWP wants to create a page listing 150 videos (and counting) posted on Vimeo as part of a series. Additionally they want to curate pages with smaller collections based on topic. I discouraged them from using the article for this and am wondering how we would propose someone handle something like this?

# Proposed solution
* Implement #137.
* Create a view block for media collections with filtering by tag.

**Comment by joewhitsitt** [comment]
Original use-case is now being focused on over here: https://github.com/uiowa/uiowa/issues/7794
