### ISSUE TITLE
superfish 3rd level menus show offscreen

### ISSUE THREAD

**Issue by bewoldt** [uiowa/uiowa#3454]
# Problem
The Horizontal navigation style will sometimes show 3rd level menu items off-screen when the text is too long.

<img width="934" alt="Screen Shot 2021-05-05 at 9 58 23 AM" src="https://user-images.githubusercontent.com/731952/117164001-d1634200-ad89-11eb-93dd-2c2a18424f79.png">

<img width="922" alt="Screen Shot 2021-05-05 at 9 58 08 AM" src="https://user-images.githubusercontent.com/731952/117164044-dfb15e00-ad89-11eb-860d-db006a04e7bf.png">

# Steps to reproduce
Examples for reference are https://africanamericanstudies.uiowa.edu/. Under Graduate Programs > Degrees and Certificates.

https://cinematicarts.uiowa.edu
Under Graduate Programs > Degrees and Certificates

**Comment by bspeare** [comment]
This appears to be an issue with the superfish library or module and not `uids_base`.  I tested this with `bartik` and observed the same issue.

**Comment by bspeare** [comment]
If we aren't able to fix this, we could prioritize https://github.com/uiowa/uiowa/issues/3273 as an alternative solution for sites that want to display 3rd level menus.

**Comment by briand44** [comment]
may be some superfish config that could potentially help?

**Comment by bspeare** [comment]
@joewhitsitt was right, you can adjust the width of the supersubs and it would probably fix this issue:

<img width="1351" alt="Screen Shot 2021-10-05 at 2 09 17 PM" src="https://user-images.githubusercontent.com/1036433/136087445-5b56a693-d341-4007-8c82-9a2224ffcf1b.png">

**Comment by dnkemper** [comment]
Note: Gonna make a quick fix to this as well while I'm in here
![image](https://user-images.githubusercontent.com/16872949/136399408-022a4bf1-c504-4f02-98c8-a7829fb3f983.png)

**Comment by joewhitsitt** [comment]
Hope @bspeare or @pyrello could answer this: is it necessary to main the separate config for these menus in uids_base optional?

**Comment by dnkemper** [comment]
> Hope @bspeare or @pyrello could answer this: is it necessary to main the separate config for these menus in uids_base optional?

Yeah. Went towards being more on the consistent side of things and felt like I'd rather be safe than sorry but 🤷🏼‍♀️

**Comment by joewhitsitt** [comment]
I did the same thing way back when. Not sure if it is needed.

**Comment by pyrello** [comment]
I don't believe so. To check for sure, we could try removing them and then install a new site locally.
