### ISSUE TITLE
Component headings not consistent

### ISSUE THREAD

**Issue by bewoldt** [uiowa/uiowa#3459]
# Problem
When adding multiple components horizontally across a section, the headings don't align to the top. It looks like the events component has an extra margin applied to it whereas the People and Articles components do not have this.

`.block-inline-blockuiowa-events {
    margin-top: 1.25rem;
}`

<img width="1034" alt="Screen Shot 2021-05-05 at 1 09 32 PM" src="https://user-images.githubusercontent.com/731952/117188994-47c06e00-ada3-11eb-8ab8-577e07821c2e.png">

<img width="1035" alt="Screen Shot 2021-05-05 at 1 10 12 PM" src="https://user-images.githubusercontent.com/731952/117188974-41ca8d00-ada3-11eb-9728-84a5c8fe9412.png">

# Steps to reproduce
Add the Events, Articles, and People components to a section.

# Proposed solution
Either add margin to all component headings or none.

**Comment by joewhitsitt** [comment]
Can we close this issue in favor of https://github.com/uiowa/uiowa/issues/2871 which addresses the headings among other things?
