### ISSUE TITLE
Article Featured Image caption breaking page layout

### ISSUE THREAD

**Issue by bewoldt** [uiowa/uiowa#3461]
# Problem
When you add a caption to the Featured Image in an article, the caption wrapper is visibly hidden but has a width of 100% and is breaking the page.

<img width="1082" alt="Screen Shot 2021-05-05 at 1 29 30 PM" src="https://user-images.githubusercontent.com/731952/117192235-1649a180-ada7-11eb-95cc-ea56353a8aa7.png">

<img width="1088" alt="Screen Shot 2021-05-05 at 1 27 09 PM" src="https://user-images.githubusercontent.com/731952/117192249-1a75bf00-ada7-11eb-857c-fb396cb83870.png">

# Steps to reproduce
Create an article and add a featured image, then add a caption to the image. Add the Articles component to a page.

Examples:
https://stanleymuseum.prod.drupal.uiowa.edu/
https://stanleymuseum.prod.drupal.uiowa.edu/news

# Proposed solution
I'm not sure what the intended use of the image caption is for an article. As far as I can tell, it is not visible anywhere on the site.

**Comment by joewhitsitt** [comment]
so the caption is supposed to be shown on the full node if the image is set to display, so I think we can scope this a bit better.

**Comment by joewhitsitt** [comment]
...which appears to no longer be working.

update: going to see if i can get this working again and remove it from the teaser.
