### ISSUE TITLE
Can't remove collections items

### ISSUE THREAD

**Issue by cory-skeers** [uiowa/uiowa#3462]
Looks like the "extra actions" dropdown has fallen off, making it impossible to remove individual collection items.

# How to recreate

Add a Collections block with a few items.
Try to remove an item.

# Proposed solution

~Check that the delete option is available in the dropdown~ Checked this, and it is. The dropdown toggle button is just inaccessible.
Adjust CSS so that the dropdown options are available.

**Comment by joewhitsitt** [comment]
Relates to #3401

**Comment by bspeare** [comment]
A hotfix for this would be to update https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/scss/admin.scss#L891-L894:
```
.paragraphs-tabs-wrapper .paragraphs-dropdown-toggle {
    width: 26px !important;
    background: url(/modules/contrib/paragraphs/icons/icon-actions.svg) no-repeat 50% !important;
    height: 26px !important;
    border: none !important;
}
```
