### ISSUE TITLE
Images need to be resampled before being rendered to templates

### ISSUE THREAD

**Issue by quamsta** [uiowa/uiowa#3472]
# Story

As a developer and user of the CMS I want to be able to upload images to components in such a way so that they can be resampled or limited to a maximum resolution automatically by SiteNow so that loading times are reduced, bandwidth is reduced, and that images don't have to be resized manually.

Users of the SiteNow platform will likely have uploaded extremely large images (think: 10MB straight-from-the-camera images) to the platform and shouldn't be expected to load them into a separate tool to reduce their size.

We have hundreds of images and dozens of sites and manually resizing each of them for every case/component is incredibly time and energy consuming when we used to be able to limit resolution by resampling images automatically in our previous platform.

# Proposed solution

I found that there's a Drupal image resampling plugin that could be used, but I'm not sure if it's maintained or works with layout builder.

https://www.unleashed-technologies.com/blog/drupal-8-responsive-image-module

**Comment by joewhitsitt** [comment]
We are currently using responsive image, lazy loading for almost every image. Additionally everything should be cached pretty heavily to reduce load times. We had webp turned on but there was a conflict and we [had to turn it off](https://github.com/uiowa/uiowa/issues/1476). Can you be more specific with where you think there could be improvement?

**Comment by pyrello** [comment]
It sounds like this is a request to initially resize the image when it is uploaded so that the source image is not enormous. Can you confirm @quamsta?

**Comment by quamsta** [comment]
@pyrello @joewhitsitt 

I might have been confused by a discussion we had during a web community meeting about resampling images. There was some talk of manually resizing images via external services like https://compressor.io so I was under the impression that images were always being served at their original size. That freaked me out a bit.

Good to know about the responsive images thing, thank you for clarifying, @joewhitsitt !

Is there a maximum for image dimensions for the largest screen size that the responsive images module "tops out" at? That'd be my only concern, but it sounds like this is something y'all are on top of :)

**Comment by joewhitsitt** [comment]
Not sure if this is up-to-date but the link below shows what are the "max" dimensions that would be loaded if the display called it. In most cases it never pulls those though. The biggest is person photo for some reason (2592×2592). We use ImageMagick but it is still set at 95% quality so it doesn't compress as much as compressor.io, etc.

https://sitenow.uiowa.edu/documentation/media/images-and-files#image-specifications

If you have thoughts what we can add to this to improve this, let us know. With placement of images being so flexible in v3, we have to generalize a bit to make sure we cover those big situations.

**Comment by quamsta** [comment]
I'm going to close this since it arose from a misunderstanding of Layout Builder and how pages are built and rendered that I had early on.
