### ISSUE TITLE
"Sibling" or other pages in a section are not shown in the side navigation

### ISSUE THREAD

**Issue by quamsta** [uiowa/uiowa#3474]
# Story

As a user of SiteNow, I'd expect to see what current "section" of the site I'm in via the side navigation, but currently the side navigation only shows "children" or pages under the current site:

Example:

On the page "Jean Jew Award," we see that page's menu children, which is correct: 

<img width="514" alt="Screen Shot 2021-05-06 at 8 29 15 AM" src="https://user-images.githubusercontent.com/472923/117306620-6ecf7c00-ae45-11eb-8b35-64d1ae5684d1.png">

However, once you click into "About Jean Jew," you lose any sense of where you're at in the site's menu, since the side navigation disappears:

<img width="650" alt="Screen Shot 2021-05-06 at 8 29 20 AM" src="https://user-images.githubusercontent.com/472923/117306773-99213980-ae45-11eb-8eba-39a515c55daf.png">

# Proposed solution

As in our current system, you should be able to see "sibling" elements in the menu the deeper you go, with indicators for where you're at in the menu. For example, if you were on "About Jean Jew," you would see this:

<img width="590" alt="Screen Shot 2021-05-06 at 8 29 36 AM" src="https://user-images.githubusercontent.com/472923/117306947-c1109d00-ae45-11eb-9a6d-150cc337b6e9.png">

**Comment by joewhitsitt** [comment]
I wouldn't call this a bug. It is working as we designed it. We also have issues already that work to make this an enhancement.

https://github.com/uiowa/uids/issues/453
https://github.com/uiowa/uiowa/issues/3200

**Comment by pyrello** [comment]
@quamsta One layer of complexity in this is that we are currently using the same menu blocks to provide horizontal and vertical menus, so any solution like this is going to need to account for both form factors.

**Comment by bspeare** [comment]
@quamsta can we close this in favor of https://github.com/uiowa/uiowa/issues/3200?

**Comment by quamsta** [comment]
@bspeare yeah! That looks to be the same sorta thing.
