### ISSUE TITLE
Deprovision lungimaging.sites.uiowa.edu on uiowa701

### ISSUE THREAD

**Issue by dnkemper** [uiowa/uiowa#3475]
Deprovision lungimaging.sites.uiowa.edu on uiowa701

**Comment by joewhitsitt** [comment]
@dnkemper Re: parking lot -  is this blocked for any reason? Brian wondered.

**Comment by dnkemper** [comment]
@joewhitsitt @briand44 nope. Wasn't on support last week.

**Comment by briand44** [comment]
@joewhitsitt I believe this issue was the one I was concerned about https://github.com/uiowa/uiowa/issues/3433. Doesn't look like it has the deprovision label though.

**Comment by dnkemper** [comment]
lol didn't even know we had a deprovision label
