### ISSUE TITLE
As an "internal" user, I can see non-public node(s) without having editing access to the site

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#3484]
# Story

An issue what brought up today about giving Dean's Office staff (without editing access to the site) access to view certain "internal" nodes that are not visible to the public.  

I could easily see adding this small handful of people as "Viewers" for the site, but I was curious if we had a solution for how to "hide" the node from public view without archiving or unpublishing the node.

**Comment by joewhitsitt** [comment]
If using the view role/unpublished content is not a solution for you @mark-bennett-uiowa, can we close this in favor of this existing issue? https://github.com/uiowa/uiowa/issues/2305

**Comment by mark-bennett-uiowa** [comment]
Closing in favor of #2305.
