### ISSUE TITLE
Webform fields don't respect field width settings

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#3486]
# Story

As SiteNow webform creator, I would like my form fields to respect the width I set, so that we don't have very large fields when the input only accepts a small number of characters.

# Additional Info
An example of this https://admissions.prod.drupal.uiowa.edu/biomedical-sciences-supplemental-application. The ACT and SAT fields have a size of 15 defined but are showing as 100% width.

# Proposed solution

**Comment by bspeare** [comment]
We could override [this](https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/scss/components/form/forms.scss#L125-L158) for `.webform` in `webform.scss` doing something like:

```
input[size]:not([size='60']) {
   width: inherit;
}
```

We would need to make sure that everything within `.webform-flex--container` still displays with a 100% width for webform layouts.
