### ISSUE TITLE
Add LB style options to people list block

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#3489]
# Story

As a site owner I use card styles with the people list block created in #2702 to take advantage of all the card options that have been developed.

# Proposed solution

- [x] Enable the Person block list view.
- [x] Provide layout builder style options related to card (background, image position, image format, content alignment, image size, card border)
- [x] Default styles for new instances should be `white, left align, images are left align small circle`
- [x] Update layout_builder_custom to have the same show/hide options functionality as aggregator.
- [x] Style adjustments and update templates to receive block style configuration.
- [x] Disable people list view to prevent premature deployment of the whole feature.

## Relates to

https://github.com/uiowa/uiowa/issues/3501
https://github.com/uiowa/uiowa/issues/2351

**Comment by joewhitsitt** [comment]
Could we add a "styles" checkbox to this? I think there are some div changes (e.g. headline in relation to the views rows) that might need to be adjusted.
