### ISSUE TITLE
As a brand owner, I can see the 175th year logo update in footer on October 6, 2021

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#3497]
# Story 
As a brand owner, I can see the 175th year logo update in footer

# Proposed Solution
- [x] Swap out footer block logo with special 175th year logo starting on _October 6_, 2021
  - Will probably need to either create a new include template for 175 logo template or just include the logo svg code into the footer https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/templates/layout/footer.html.twig#L15-L21.
- [x] Grab new logo from https://brand.uiowa.edu/anniversary-logo and make it look like the screenshot below:
<img width="619" alt="175-WebFooter-Mockup" src="https://user-images.githubusercontent.com/1036433/119142830-85accb80-ba0c-11eb-8e1a-7d4662c64a9d.png">

**Comment by mjoneill** [comment]
@bspeare This is likely needed to go live in July.  Jess is our visionholder/stakeholder/partner and can add clarity.

**Comment by bspeare** [comment]
<img width="619" alt="175-WebFooter-Mockup" src="https://user-images.githubusercontent.com/1036433/119142830-85accb80-ba0c-11eb-8e1a-7d4662c64a9d.png">

**Comment by bspeare** [comment]
Adding the blocked label as the go live date might be delayed.

**Comment by bspeare** [comment]
I've updated this issue with instructions for replacing the footer logo.

**Comment by bspeare** [comment]
Closed via https://github.com/uiowa/uiowa/pull/4263.
