### ISSUE TITLE
Replace article custom block with views-based alternative

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#3501]
# Story

As a site owner I want to use a views block with new functionality from #2702 to build my article lists so that I can make use of the enhanced functionality.

# Reference

https://github.com/uiowa/uiowa/pull/2702 and related follow-up PRs (hotfixes, orphans)
https://github.com/uiowa/uiowa/issues/4267

# Proposed solution

- [x] Create the Article list view block similar to the People list view block and export config.
- [x] Provide layout builder style options related to card (background, image position, image format, content alignment, image size, card border, grid options)
- [x] Default styles for new instances should be `white, left align, images are right align wide small`
- [x] Add `sitenow_articles.path` token
- [x] Update layout_builder_custom to have the same show/hide options functionality as aggregator.
- [x] Style adjustments and update templates to receive block style configuration.
- [x] Update hook to replace existing article blocks with the views-based alternative.
- [x] Replace preprocess_block logic in SiteNow Articles related to article block.
- [x] Check and remove orphans?
- [x] Remove Article block content type.
- [x] Remove fields that are unique to Article block content type.

## Relates to
https://github.com/uiowa/uiowa/issues/2351
https://github.com/uiowa/uiowa/issues/3489
https://github.com/uiowa/uiowa/issues/3272

**Comment by richardbporter** [comment]
Just got a report of #3558 and child heading sizes changing after paging via AJAX. This issue might be the best solution to both as I'm not 100% sure #3558 is happening with new views people list.

**Comment by makurj** [comment]
I would like to be able to enter my own custom text for the "display more link" button so that if I'm using it for articles tagged with Student Stories, the button link can say "View More Student Stories" instead of the the default "View More News". This functionality should be available per Articles block. Example:

![image](https://user-images.githubusercontent.com/52135878/124635143-b6c24d80-de4c-11eb-85fd-4de444595124.png)

**Comment by briand44** [comment]
Could potentially split this by doing everything above the update hook in the first slice but avoid delivering it until we are able to finish. We can revisit during planning to see if we have capacity to tackle it all in one sprint.

**Comment by pyrello** [comment]
To add the token, here are relevant pieces of code from when we did this for people:

https://github.com/uiowa/uiowa/blob/bed3a121ad35801f33991805e25bcaa74f957b5a/docroot/modules/custom/sitenow_people/sitenow_people.module#L140-L145

https://github.com/uiowa/uiowa/blob/bed3a121ad35801f33991805e25bcaa74f957b5a/docroot/modules/custom/sitenow_people/sitenow_people.module#L370-L371

https://github.com/uiowa/uiowa/blob/bed3a121ad35801f33991805e25bcaa74f957b5a/docroot/modules/custom/sitenow_people/sitenow_people.module#L789-L806

https://github.com/uiowa/uiowa/blob/bed3a121ad35801f33991805e25bcaa74f957b5a/docroot/modules/custom/sitenow_people/sitenow_people.module#L808-L831

**Comment by joewhitsitt** [comment]
Should https://github.com/uiowa/uiowa/issues/3501#issuecomment-874905664 (custom more link label) be part of the scope or a separate issue?

**Comment by briand44** [comment]
>Should #3501 (comment) (custom more link label) be part of the scope or a separate issue?

I think this is a feature others will ask for. We could default it to "View More News" but allow it to be changed.

I don't know how much this increases scope. I would say if it could delay this or other planned work from getting done, we should create a follow up issue.

**Comment by pyrello** [comment]
This is not really relevant to this particular work. It is going to be additional work to modify our ListBlock class to add this option to the view and the block configuration.

**Comment by joewhitsitt** [comment]
Created a separate issue to address the request. https://github.com/uiowa/uiowa/issues/4305

**Comment by joewhitsitt** [comment]
re: limit views block hide fields

I think @pyrello brought this possibility up originally, but I am leaning towards moving some of the source/org/direct logic to each field within a `preprocess_field`. Direct link to source will still replace the card link but, the mash up of source link and org can happen in the org field preprocess (help text on the field would still be correct). on the views block, the user can hide/show source link and org as they choose.

downsides:
- don't know off the top of my head how hiding a field affects the logic to link the "card"
- possibility of redundant links if all shown and the card is linked to source link.

there is still a use-case where we don't want to allow certain fields from toggled ([content id](https://github.com/uiowa/uiowa/issues/4234)).

**Comment by pyrello** [comment]
If we need to display the actual source link URL and allow it to be hidden, then I suggest that doesn't change whether or not the card is linked. By setting a source link and checking the link to directly to source box, users have indicated that the source link should override the link in all cases where the teaser for the article is displayed. This means that if those conditions are met, the card should link should be the source link. Whether it is selected in the hide fields section of the block settings should only control whether it actually displays as a URL on the article teaser.

**Comment by joewhitsitt** [comment]
agreed. just wasn't sure if hiding the field disrupted any of the in-place logic to link up the card.

**Comment by pyrello** [comment]
I think we can access the value of the field via `getFieldValue` regardless of whether it is showing or not. But we might want to validate that idea.

**Comment by e-marie-w** [comment]
Differences between article block default content so far: author styled differently, difference in view more button ('View More' vs. 'View More Articles')
