### ISSUE TITLE
Differentiate actions (especially destructive actions) in the Drupal editor menu by icon or color

### ISSUE THREAD

**Issue by quamsta** [uiowa/uiowa#3508]
<img width="653" alt="Screen Shot 2021-05-10 at 8 21 23 AM" src="https://user-images.githubusercontent.com/472923/117665688-b79a7400-b168-11eb-8081-f47aebe2a7df.png">

# Story

As a content editor, I find myself accidentally clicking "Delete" too often when I really want to click "Edit" or "Layout" Does the "Delete" button need to be nestled in between "Edit" and "Layout" in the top navigation in Drupal? 

# Proposed solution
Destructive actions should probably be made a bit more obvious/less "easy" to do. There is a confirmation after clicking "Delete" thankfully, but I still feel this sort of action shouldn't be as easy as it currently
 is to initiate.

Either rearrange the delete button to be at the end of the editor's top navigation, or remove it entirely and only allow a user to delete a page while in "Edit" mode or while batch editing pages.

Or differentiate all icons by color or icon like:

<img width="1085" alt="Screen Shot 2021-05-10 at 8 32 56 AM" src="https://user-images.githubusercontent.com/472923/117667255-55db0980-b16a-11eb-9ce6-276eb5a67a47.png">

**Comment by quamsta** [comment]
I'm using this as a test case just to learn how Drupal hooks work, if anyone has feedback on this as an item, let me know!

**Comment by bspeare** [comment]
@quamsta One thing that I wonder about this is if all the icons on each local task create more visual clutter to an already busy interface.   What if we reserved the icons for a few important actions?  I've added a screenshot below as an example. 

<img width="1494" alt="Screen Shot 2021-05-14 at 11 35 17 AM" src="https://user-images.githubusercontent.com/1036433/118301568-d8d0cc80-b4a8-11eb-9a10-ec649d06d447.png">

**Comment by pyrello** [comment]
Usage doesn't seem appropriate to have as a button, IMO. I'm wondering if, after the conversation regarding people's concerns about deleting content whether it might not be better to just remove the "Delete" tab altogether?

**Comment by quamsta** [comment]
@pyrello , yeah I could see us totally removing "Delete" from that spot all together, I think that would be good

@bspeare 

I like this idea! I still want to push for some iconography or some way to visually distinguish the three actions, "View," "Edit," "Layout." Here's my reasoning:

### Reason 1:
 In my opinion, those three actions are the "big three" actions that users do when managing and editing existing content in SiteNow and like a lot of toolbars, important actions are given visual prominence or nice icons to help the user differentiate them. 

For example. Drupal itself provides icons at the top of the page for actions "Content," "Structure," Appearance," "Extend," "Configuration," etc, and those actions may not even be used as much as View/Edit/Layout.

<img width="494" alt="Screen Shot 2021-05-17 at 8 52 41 AM" src="https://user-images.githubusercontent.com/472923/118500235-3ead9600-b6ed-11eb-92f2-8dd5bb06b27f.png">


Giving the View/Edit/Layout menu items icons gives them prominence and makes it clear that they're important actions when editing the site, and not just "tabs" in a website navigation bar.

### Reason 2: 

Ignoring "View" for  a sec, I feel "Edit" and "Layout" need to be more clearly differentiated or their meaning needs to be expressed more clearly. 

I've been editing and managing content for a few sites now and it's initially unclear what "Edit" means. Does it mean that you're going to "Edit" the page's components/layout when you click it? 

No. But if we're encouraging users to use Layout Builder, then technically "Edit" could take you to a place where you are going to "Edit" the layout and content in the components in Layout Builder. The distinction between them quickly becomes a bit blurry.

<img width="368" alt="Screen Shot 2021-05-17 at 8 57 00 AM" src="https://user-images.githubusercontent.com/472923/118500941-d8754300-b6ed-11eb-8439-c73592989f24.png">

- The pencil-and-paper icon representing "**Edit**" clarifies that when you click "Edit," you're going to be filling out/writing in content fields, and making adjustments with a form.
- The four-squares icon for "**Layout**" says "Hey, you're going to be moving around columns and sections and things" and expresses that more clearly.
- And for "**View,**" seeing a globe icon represents the fact that you're going to be previewing the page's layout and content from an outside perspective, and might also be helpful.

Is there some way we can distinguish "Layout" and "Edit" without cluttering up the user interface?

**Comment by cory-skeers** [comment]
> Ignoring "View" for a sec, I feel "Edit" and "Layout" need to be more clearly differentiated or their meaning needs to be expressed more clearly...Is there some way we can distinguish "Layout" and "Edit" without cluttering up the user interface?

Another request that had been made had been to either change the Save button on the Edit screen or add an additional button for "Save and Edit Layout." Similar request due to the confusion between Edit and Layout, and this might be a good time to consider as part of a "let's make this less confusing" effort.

**Comment by pyrello** [comment]
There is a PR open (#3370) to test drive Gin, which is a newer Admin theme. I'd be interested to see what, if anything, we can learn from that theme.

**Comment by bspeare** [comment]
Gin adds this toolbar at the top of the layout edit screen:

<img width="1626" alt="Screen Shot 2021-05-19 at 3 02 21 PM" src="https://user-images.githubusercontent.com/1036433/118877041-939b0900-b8b3-11eb-8386-ac8003831dd6.png">


Maybe we could move the edit tools into this top bar?

<img width="1633" alt="Screen Shot 2021-05-19 at 3 00 04 PM" src="https://user-images.githubusercontent.com/1036433/118877173-ba593f80-b8b3-11eb-97e1-86330e0ca71a.png">

**Comment by mark-bennett-uiowa** [comment]
@bspeare I like the idea of a edit toolbar like your second screenshot. Very nice!

Does the Discard Changes button and Revert to Default buttons get removed from LB?

**Comment by bspeare** [comment]
@mark-bennett-uiowa those actions are under the gear toggle in that header but there's a pop-up that tells you there's unsaved changes.

**Comment by quamsta** [comment]
@bspeare 
That Gin Admin theme is sweet, really slick looking 👍. I dig it.

I wonder how we're going to roll it out since a new admin theme like that is going to completely change the way the editors work in the sites. I worry it might be a big shift that we'd have to make for training, etc.

Is it possible to do this in phases where we introduce the icons and then provide a custom admin theme (that's a lot less cluttered) a bit further down the line?

**Comment by bspeare** [comment]
Here are some screenshots of the latest version in the pr.

<img width="1602" alt="Screen Shot 2021-06-03 at 9 25 47 AM" src="https://user-images.githubusercontent.com/1036433/120695875-7c424b00-c471-11eb-9978-38016e36315a.png">

<img width="1561" alt="Screen Shot 2021-06-03 at 1 41 20 PM" src="https://user-images.githubusercontent.com/1036433/120695918-882e0d00-c471-11eb-9202-30d6c71b0002.png">
