### ISSUE TITLE
Finalize SEO Configuration

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#351]
### Problem
We have thrown some modules at the content types hoping to check off SEO expectations, but I don't think we are there.

### Proposed Solution
Revisit what global and content specific options are available to the webmaster role. Run a page, article, person and the articles view page through SEO audit tools like Google lighthouse, Twitter cards, open graph to see where we need to improve.

Is it proper to have both schema article options available on the basic page content type?

- [x] View pages (articles, people) need meta description.

Establish SEO defaults for things like twitter cards (image, organization, etc.).

### Test
Above tools and maybe consult with Michael from Tippie to get a MVP thumbs up.

**Comment by richardbporter** [comment]
![image](https://user-images.githubusercontent.com/1068523/63035021-0033d900-be80-11e9-8599-7c36d41d0861.png)

Missing meta description since that field needs to be filled out manually. Not every user will do this but that does ding the score.

**Comment by richardbporter** [comment]
>Is it proper to have both schema article options available on the basic page content type?

I think so.
