### ISSUE TITLE
People page filter wrapping to two lines in some browsers

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#3512]
# Problem
The People page filter wrapping to two lines in some browsers due to the very long character count of some Research Areas. 

# Steps to reproduce

View https://anthropology.uiowa.edu/people in chrome, safari, and firefox. 
<img width="1371" alt="Screen Shot 2021-05-10 at 1 33 47 PM" src="https://user-images.githubusercontent.com/1036433/117707872-b97a2c80-b194-11eb-9b7e-53243ca5d659.png">
<img width="1405" alt="Screen Shot 2021-05-10 at 1 33 57 PM" src="https://user-images.githubusercontent.com/1036433/117707877-bb43f000-b194-11eb-89ee-4db5c5e64228.png">

# Proposed solution
- Update views.scss to remove `flex-wrap: wrap` starting at the `sm` breakpoint in the filter styles to work across browsers
```
.views-exposed-form .form--inline {
display: flex;
justify-content: flex-start;
align-items: flex-end;
/* flex-wrap: wrap; */
}
```

**Comment by mark-bennett-uiowa** [comment]
Im guessing this has to do with the length of some of the Research Areas, if not the sheer volume they have. This was due to get cleaned-up post launch, but thank you for noticing this issue @bspeare!

**Comment by bspeare** [comment]
@mark-bennett-uiowa Yes, your Research Area length has helped expose this!
