### ISSUE TITLE
Webform - Test Viewing and Downloading Submissions

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#352]
Follow-up from #201 

### Problem
This functionality was released without testing whether or not it works...

### Test
Create a crazy from of allowed components, create a few submissions as anonymous, authenticated users. Login as a webmaster and view submissions, try download options to see if they work. ProTip: D7 Excel format was always buggy.

Additionally, try configuring emails upon submission. One to an email address component (e.g. submitter gets a confirmation email) and another one that sends all the submission data (e.g. webmaster that needs submission data without logging to the site)

**Comment by ethanstjohn** [comment]
I have created a crazy from of many components and completed all of the suggested tests. I have not found any problems or issues with this. I have received all of the information through the emails I sent to myself and can download excel versions without issue.
