### ISSUE TITLE
Secondary menu on tuition and estimated costs page

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#3521]
# Story

As an admissions site owner, I would like to be able to have a secondary menu on the tuition and estimated costs page so that it is easier for international students and part time students to find their relevant costs.

# Additional Info

The following link is the page where the secondary menu is desired.
https://admissions.prod.drupal.uiowa.edu/finances/estimated-costs-attendance

> On this page: https://admissions.prod.drupal.uiowa.edu/finances/estimated-costs-attendance
We need 2 submenus
Estimated Costs (the default for this page https://admissions.prod.drupal.uiowa.edu/finances/estimated-costs-attendance)
International Estimated Costs – points to this page: https://admissions.prod.drupal.uiowa.edu/finances/estimated-costs-international-students

# Proposed solution

**Comment by bspeare** [comment]
Closed an approved by the client: https://admissions.prod.drupal.uiowa.edu/finances/estimated-costs-attendance.
