### ISSUE TITLE
Troubleshoot and fix formatting issues on for areas of study and test PDFs

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#3523]
# Problem

## Areas of Study
Some Areas of study PDFs are breaking to the second page immediately after the "Course Work" heading:
- https://admissions.prod.drupal.uiowa.edu/print/pdf/node/3406
- https://admissions.prod.drupal.uiowa.edu/print/pdf/node/3381

## Tests
There are some styles that might not be covered in the test print styles:

**A few examples:**

- https://admissions.prod.drupal.uiowa.edu/academics/ap All caps styles
- Music theory row on https://admissions.prod.drupal.uiowa.edu/academics/ap
- Table `caption`: https://admissions.prod.drupal.uiowa.edu/print/pdf/node/451

# Proposed solution
- Test out the Areas of study PDFs and see if any WYSIWYG line breaks or character count reduction for the fields above and below "Course Work" would help 
- Compare the test pages against the PDFs and determine which items are style and content issues. 
  - Adjust styles at https://github.com/uiowa/uiowa/blob/main/docroot/sites/admissions.uiowa.edu/modules/admissions_core/sass/pdf.scss
  - Make a list for Scott of content adjustments that would help make the PDFs look better
 - Debug page: https://admissions.prod.drupal.uiowa.edu/print/pdf/node/446/debug, PDF page: https://admissions.prod.drupal.uiowa.edu/print/pdf/node/446/

**Comment by joewhitsitt** [comment]
Caption doesn't seem to apply any styles we give it (even `!important`). Debug works. We suggest for this particular instance that the caption be shortened. CLAS instead of the full college name for example

**Comment by richardbporter** [comment]
Similar to caption, multiple rowspan issues exist in dompdf: https://github.com/dompdf/dompdf/issues?q=is%3Aissue+is%3Aopen+rowspan+

We may not be able to fix the display issues caused by rowspans occuring at page breaks. The only solution may be to not use rowspans and duplicate the rows where that is ocurring.

**Comment by joewhitsitt** [comment]
This one seems the most current with a circular path linking back to it: https://github.com/dompdf/dompdf/issues/1388

**Comment by joewhitsitt** [comment]
Though the solution may not be ideal, I believe we have remedied all of the reported issues with fixes and workarounds in #3529
