### ISSUE TITLE
SiteNow email receipt could have the requested site URL or something indicating which site was requested

### ISSUE THREAD

**Issue by quamsta** [uiowa/uiowa#3534]
# Story

As a requester of a SiteNow site, it'd be nice to see in the email receipt which domain was requested. I thought I requested six sites, but I have five receipts. Not sure if this is because the receipt emails didn't make it to my inbox (see: https://github.com/uiowa/uiowa/issues/3498) or if I missed one. And if I missed one, I can't tell which one I didn't submit. 

Attached is the current email receipt text:

> Thank you for requesting a SiteNow site.
> A member of the Web Services team will review your request and follow up with you as soon as possible.
> 
> Regards,
> ITS - Custom Solutions & Integrations - Web Services

# Proposed Solution

Change the text to something like:

> Thank you for requesting a SiteNow site (domain.uiowa.edu).
> A member of the Web Services team will review your request and follow up with you as soon as possible.
> 
> Regards,
> ITS - Custom Solutions & Integrations - Web Services

**Comment by joewhitsitt** [comment]
This should be done now for new requests. Maybe we should consider limiting how many sites a user can request in a span of time. 😉

**Comment by quamsta** [comment]
Haha thanks for this @joewhitsitt . Just tested this with a new request and it worked great :)
