### ISSUE TITLE
Docs - Featured Content Block Type

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#3546]
https://sitenow.uiowa.edu/documentation/layout-builder

Proposed Solution

- Document the block type similar to the other block types. IMO, this should document which content types are available for selection.

**Comment by pyrello** [comment]
https://sitenow.uiowa.edu/documentation/layout-builder/featured-content-block

**Comment by pyrello** [comment]
I feel like this is good enough for now.
