### ISSUE TITLE
Make Article Featured Image Caption Render Again

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#3561]
With https://github.com/uiowa/uiowa/pull/3550 we are sweeping a regression under the rug until we can reimagine how a caption on an article should render for all devices or decide to deprecate and remove the caption functionality.

Before we decide to remove/deprecate the caption functionality, keep in mind there is a global caption field and that there have been requests to provide better attribution for media sources.

Known issue:  https://sitenow.uiowa.edu/known-issues#uiowa-issue-3561

# Proposed solution
- Make sure styles are scoped for only featured image caption for the article page. 
- Banner mobile stacked featured image will need to be tested/taken into account. 
- Try https://github.com/uiowa/uiowa/issues/3561#issuecomment-1331166227 first, and then https://github.com/uiowa/uiowa/issues/3561#issuecomment-1331106535
- Search for `core.entity_view_display.node.article.default.yml` on https://github.com/uiowa/uiowa/find/main

**Comment by joewhitsitt** [comment]
Marking this as a bug because there is a field that can be populated that is not rendering and it is confusing editors.

**Comment by bspeare** [comment]
Here's how the banner handled the caption previously.  We revealed the caption on hover due to the markup of the banner.  There are some existing styles in https://github.com/uiowa/uiowa/blob/09ed2ad1c947325ccd3184dcf1a4565a1296baa7/docroot/themes/custom/uids_base/scss/components/caption.scss that you can uncomment to look like the screen capture below. 

https://user-images.githubusercontent.com/1036433/182714858-79073c4c-3121-4b4e-be92-18f1b746f238.mov

**Comment by briand44** [comment]
Investigate where we should be rendering this within the markup. Take into account the mobile stacked view.

**Comment by joewhitsitt** [comment]
Do we want to rule out tooltip/popup/modal solutions for this?

**Comment by bspeare** [comment]
Looking at this again, perhaps we just render it under the page title?

<img width="1467" alt="Screen Shot 2022-11-29 at 12 23 42 PM" src="https://user-images.githubusercontent.com/1036433/204615108-56fcc910-c4fc-4780-b7fd-a96bd65442e6.png">


We would just need to adjust placement in layout builder:

<img width="280" alt="Screen Shot 2022-11-29 at 12 20 39 PM" src="https://user-images.githubusercontent.com/1036433/204614562-7da3ae27-f6f5-4638-9596-e07538c022b9.png">

**Comment by cory-skeers** [comment]
> Looking at this again, perhaps we just render it under the page title?

I like this option!

**Comment by briand44** [comment]
Explore possibly using tool tip (https://codepen.io/heydon/pen/Vzwdpy), if not we can go with rendering under title. We may need to check some splits.

**Comment by e-marie-w** [comment]
We updated the styling, here's how it looks with a left arrow icon and the info icon. Also, now it's only visible when you hover over the banner.
![left_arrow](https://user-images.githubusercontent.com/68179015/205984006-214b9ec1-4609-4fac-9105-49d7ee50f4dd.png)
![info_icon](https://user-images.githubusercontent.com/68179015/205984020-fcdbff65-5649-422c-aaca-3f51d8c6308e.png)

**Comment by cory-skeers** [comment]
Update on the current functionality:
https://user-images.githubusercontent.com/49074566/206019048-fa14161b-d2bf-4ecf-8964-495e997ac23f.mov
