### ISSUE TITLE
Next steps for p2lb

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#3568]
Determine next steps to get #1803 moving again.

Proposed next steps: https://github.com/uiowa/uiowa/issues/3568#issuecomment-857177504

**Comment by richardbporter** [comment]
A confirmation before the Magic button proceeds might be nice. :)

**Comment by cory-skeers** [comment]
> A confirmation before the Magic button proceeds might be nice. :)

I don't know...maybe, as long as it's still magical.

"Are you ready to be amazed? Yes or No."

**Comment by richardbporter** [comment]
> "Are you ready to be amazed? Yes or No."

I go with "Yes" or "Ok".

**Comment by richardbporter** [comment]
Looks like there is an issue processing carousel image captions. I'm working on that now.

**Comment by cory-skeers** [comment]
Ran into an execution max runtime error when magicking cnm.uiowa.edu (463 pages to process, some of them quite large), but it technically _worked_. Hitting the button a second time finished things up.

**Comment by richardbporter** [comment]
Seeing errors related to processing empty sections. Working on it.

**Comment by richardbporter** [comment]
If you process one node from the select list, should it be removed from the select list when complete? I'm thinking no and this relates to:

>Auto-removal of old paragraphs after migrate/review?

from the original issue. I would vote for that.

Also, a confirmation message or  some sort of output would be nice after processing.

**Comment by richardbporter** [comment]
I guess if the update hook is being considered some of my comments are not applicable. Still trying to familiarize myself with this. :)

**Comment by cory-skeers** [comment]
Can discuss more, but wonder if one option for this could be to run it for all V2 sites on dev (adds complexity of not all sites having dev domains), but would give an option to give all V2 users a chance to review and either make updates or give the go ahead to switch to V3. (Could also do a form of this in waves, or a per-site basis).

**Comment by joewhitsitt** [comment]
investigate how big the db grows if we keep both (paragraphs/blocks) for a bit.

**Comment by joewhitsitt** [comment]
advanced notice for certain clients to plan for (hr, brand, law)

**Comment by pyrello** [comment]
General game plan:
- Finish functionality to allow for a site owner to convert one or many pages into a new draft revision of the page. This would allow them to make additional changes before the page goes live.
- We allow for a period of time where people can go through the process of converting their pages like this by themselves, possibly 2-3 months.
- At the end of that time, we introduce an update hook that converts any remaining pages and publishes a new version. At this point in time, we won't actually remove the old data, we will just hide it so that it is not rendered to the page. This will allow for us to do follow-up update hooks if we need to correct mistakes or do any sort of additional processing.
- After 2 additional weeks or whenever we feel confident that the transition was successful and doesn't need additional mitigation, we can remove all the V2-specific data, configuration, and code.

Considerations:
- We need to investigate how much larger the databases might get in V2 sites will they are going through the conversion process.
- We would like to investigate the possibility of a temporary upsize to our database server resources to account for the increased size from the time that we introduce the functionality to when we finally remove the V2 data.
- We would like to solicit feedback from high profile V2 sites about how much time they think they'll need to review any potential changes to their pages and when we could schedule this for.

**Comment by richardbporter** [comment]
I think https://github.com/uiowa/uiowa/issues/3568#issuecomment-857177504 summarizes this perfectly. I feel like this issue is probably done pending team and PO discussion.

**Comment by mjoneill** [comment]
I like the thinking behind this and think it has the potential to be a great step forward.  I'm curious, what would make a good next step?  Do we need to identify 1 or 2 sites to help through this process before we turn it over to partners to do on their own? 

Off the top of my head, brand.uiowa.edu is a v2 site (I think) and we have good working relationships with the owners.  Law has expressed a desire to get on v3...but would require a different level of attentiveness from us if we are operating on their live site, etc...

**Comment by mjoneill** [comment]
> We would like to investigate the possibility of a temporary upsize to our database server resources to account for the increased size from the time that we introduce the functionality to when we finally remove the V2 data.

This is very much an option.  But I think we need some sizing metrics first.  Can we take a site (or two), "clone it" and run it through this process to see how much more space it consumes during this process?  We might then be able to understand the expected impact.

@briand44 what do we need to explore this option with Alex?

**Comment by pyrello** [comment]
Created a new issue to capture the output from this: #3752
