### ISSUE TITLE
Investigate Digital Signage integration with Mazevo

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#3579]
# Story

As an IMU Digital Signage user I would like a widget similar to the EMS Event Listing widget that integrates with Mazevo so that we can display meeting information on signs in the IMU.

# Additional Info

This may need to be sliced into a smaller probe.

API Documentation     [Using the Mazévo API](https://www.gomazevo.com/help/using-the-mazevo-api)
API URL: https://api-east.mymazevo.com/api/.

There are also API keys available, that can be shared.

# Proposed solution

**Comment by richardbporter** [comment]
If this is not replacing EMS, I would propose that we copy the EMS widget and refactor to work with the Mazevo system. Seems like it would be ok to replicate styles, JS, etc.

**Comment by richardbporter** [comment]
Investigation: can we leverage the Mazevo API to replicate the EMS custom content pane? Is it the right data structure?

**Comment by richardbporter** [comment]
Perhaps not all of the team has access to the uisignage application on AC.

**Comment by richardbporter** [comment]
Seems like this should work fine based on the current EMS filtering of building, rooms, status and types. All of those API calls are documented. I tested out one and got data back. 

I don't see another issue for implementing this. I think the next step would be just to dive a little deeper and start building out the custom content pane.

**Comment by briand44** [comment]
Awesome... Any ideas on an estimate of time? If we do this soon we will likely cost recover as we don't have a budget for new features.

**Comment by richardbporter** [comment]
Pushed to prod.
