### ISSUE TITLE
People View/Configuration Pages

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#358]
### Problem
Though we are planning to provide a way for editors to display an abitrary list of people (featured content #247) it has also been requested that there be a default alphabetical listing of people that works similar to the SiteNow Articles view page.

### Proposed solution
- [x] Create a view page that default sorts people alphabetically by last name that lives at /people.
- [x] Create a configuration page similar to SiteNow Articles that allows webmasters the ability to enable/disable the page, change the path/title, provide header content, reorder the global weight of people (similar to Standard service's configuration using draggableviews).
- [x] Teaser listing for MVP, possibly card grid and table later on.

Draggableviews is a mess... Ideally, this module would fix some things (all of these have issues i believe but development is stalled):

- Show weight values
- Add people to bottom of the list
- Allow separate views contextual filtering sorts

_Considerations should be made with regard to future APR integrations._

### Test
On site install, the /people page should render if person content has been created with a default sort by last name. Webmasters should be able to access a configuration screen that allows them to configure the options listed above, include the ability to change the order globally for people.

**Comment by joewhitsitt** [comment]
I tried out entityqueue in combination with auto_entityqueue. Didn't love it for the use-case of a global management of people order. Going to look at draggable views again with the idea of adding a "reset to alphabetical" button or something.

After attempting to change sort order/change sort options on one view page display I am not thinking there there will be three people page displays (sticky/last/first order, sticky/first/last order and the arbitrary sort option based on draggable views or whatever) that will enable/disable from the configuration form.

**Comment by dnkemper** [comment]
1. After creating people, the page automatically rendered
2. All three people page displays work
      i. Can drag and drop people manually when using customized sorting
3. Can change path/header of people page
4. Can enable/disable people listing
5. Customized order, sticky/first/last, and sticky/last/first displays all look similar
6. Looks good in large mobile, tablet, and laptop views
      i. **ONLY ISSUE** small mobile view: 
![Screen Shot 2019-08-15 at 12 53 21 PM](https://user-images.githubusercontent.com/16872949/63114931-b8827f80-bf5b-11e9-984f-02e6d8a9a67f.png)
      ii. medium mobile view works:
![Screen Shot 2019-08-15 at 12 54 08 PM](https://user-images.githubusercontent.com/16872949/63114975-d18b3080-bf5b-11e9-9065-17a44c9ab1af.png)

**Comment by GaryRidgway** [comment]
reviewed this recently and it looked fine, added in a word wrap to make it so that there was less issue with pushing people pictures off of small screen sizes with long emails. this does not solve the issue but it will help the symptom. I will try and make better image styles in #462

**Comment by joewhitsitt** [comment]
this was merged #405
