### ISSUE TITLE
Person - Hide from listing

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#359]
### Problem
There might be people added to the site that should not for whatever reason be listed in the /people listing (#358). Blocked until 358 is farther along so you can modify the view.

### Proposed Solution
Create a boolean field or "Person Options (e.g. Page Options)" that is off by default that toggled on will filter that person from the people listing view page. The view page will have to be modified to include this filter.

### Test
Create a person that initially shows up in the people listing. Then check the new boolean to hide person on people page and see if that worked. Uncheck the boolean to revert. Check again.

**Comment by joewhitsitt** [comment]
Now that the view is a bit further along on #358, i've started work on this as well.

**Comment by joewhitsitt** [comment]
This is more or less done, but tied up as part of #358.

**Comment by dnkemper** [comment]
This works correctly! Can hide/display people as you please.

**Comment by joewhitsitt** [comment]
this was merged in #405
