### ISSUE TITLE
Purge - Setup purge rules for view pages

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#360]
### Problem
If an article or person gets updated, the view page cache for SiteNow Articles and (#358 SiteNow People) won't get purge.

### Proposed Solution
See about setting a purge rule for article and person that targets the respective view machine name and not the path as the path can change based on configuration.

Blocked until 358 is farther along. Investigation into purging a view machine/display name not the current view URL path can be done ahead of this issue.

### Test
Purge/Varnish and all that can only be tested in Acquia environments. This code will have to be merged in to properly test. Add/edit/delete article/person content to see if the respective views get cleared regardless of what path they reside (e.g. /news, /articles, /people, /staff).

**Comment by joewhitsitt** [comment]
After talking with @richardbporter, this might be a non-issue in D8 due to cache tags. Needs testing.

**Comment by richardbporter** [comment]
Yep. Non-issue. Just tested.
