### ISSUE TITLE
SiteNow Updates News Article - June

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#3608]
## Issue/Solution

Provide a "release notes" type article of finished/done features/updates and publish to website, then send out dispatch email.

- [x] Create draft and update the parking lot card with an edit link (https://sitenow.uiowa.edu/node/396/edit)
- [x] Add "release notes" covering the month of v2/v3 default profile enhancements and webmaster/edit visible bug fixes.
  - See https://sitenow.uiowa.edu/news/2021/02/updates-january as an example.
  - Bullet points from demo stories slide per week.
  - Check recent "done" and "archive" items and finished docs tasks.
  - Take notes during sprint demo presentation.
- [x] Get at least one team member to look over the draft before publishing.
- [x] Since the draft was started earlier, adjust the publish date/time, publish, get the link to the article.
- [x] Dispatch email with link to article. (To get access, send an email to dispatch-support@uiowa.edu to have the account provisioned. Provide your hawkid and mention the CSI:drupal group)
  - Modify SiteNow Announcements Template (tweak opening line, update the article link, any other editorial adjustments)
  - Create new communication off SiteNow Announcements campaign
    - Use SiteNow Announcements population, template, suppression list, bypass approval.
    - When scheduling, check the "archive" option so that there is an RSS instance we can use in the future. I don't think this can be done after the fact.
- [x] Create the next months's issue and copy all this bullet list into it, removing the checked boxes if any. - _https://github.com/uiowa/uiowa/issues/3766_

**Comment by joewhitsitt** [comment]
Do we want to hold and do this with our launched v3 site? https://github.com/uiowa/uiowa/issues/3033

**Comment by joewhitsitt** [comment]
https://sitenow.uiowa.edu/node/396/edit

**Comment by mjoneill** [comment]
@joewhitsitt I reviewed the news article and made one minor change (added a hyperlink in the top para).

I feel less like I can speak to the list of enhancements for this newsletter. I don't have a solid read on what might be missing, so I'll leave it with a copy proof there (looked good to me).

**Comment by pyrello** [comment]
I made one small adjustment to one of the bullet points. Otherwise, it looks good to me!

**Comment by joewhitsitt** [comment]
Published: https://sitenow.uiowa.edu/news/2021/07/updates-june
Dispatch scheduled for 7/7 2:30p
https://github.com/uiowa/uiowa/issues/3766 created
