### ISSUE TITLE
Add chat feature to admissions site

### ISSUE THREAD

**Issue by mjoneill** [uiowa/uiowa#3609]
As an admissions site visitor, I can use the embedded live chat feature on the new website so that I can connect with and talk with a real human who can answer questions.

**Comment by mjoneill** [comment]
Partner is unable to add the code to template himself. Pulling this to try (first) via GTM.  If that's not going to work, we need to discover quickly so that we can pivot in time for their site launch.

Embed code should be on all pages.  Partner added the code snippet to slack channel.

**Comment by joewhitsitt** [comment]
advisingcenter.uiowa.edu has implemented this chat feature similarly. it can be tough to test because they are setup to only be visible when someone is on the other end to respond.

here is the old issue where i tried to style an off hours widget... https://github.com/uiowa/uiowa/issues/2328

**Comment by dnkemper** [comment]
Thank you so much, @joewhitsitt 🥳

**Comment by joewhitsitt** [comment]
"custom html tag, trigger all pages"
