### ISSUE TITLE
Ability to bulk unpublish/publish

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#3610]
Admissions said they can't unpublish scholarships. 

I believe the bulk operation for unpublishing may not work on any sites based on perms. 

The below screenshot is from default.prod.drupal.uiowa.edu

![Screen Shot 2021-06-03 at 10 30 24 AM](https://user-images.githubusercontent.com/1017022/120671244-cff36b00-c456-11eb-885a-9bc18422cd48.png)

**Comment by joewhitsitt** [comment]
VBO aside, they can archive a published scholarship which is the moderation equivalent. Scholarship is using the same moderation transitions as the default content types 

<img width="410" alt="Screen Shot 2021-06-03 at 12 55 43 PM" src="https://user-images.githubusercontent.com/4663676/120690741-36828400-c46b-11eb-974e-7df23e6a5c31.png">

**Comment by GaryRidgway** [comment]
Should this perm be going to webmasters, publishers, and editors? or just webmasters and publishers? or something in between?

**Comment by joewhitsitt** [comment]
i'd say webmasters/publishers for now. bulk operations doesn't seem very editor-like
