### ISSUE TITLE
Provide content/design recommendations to Parking and Transportation

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#3611]
- [x] Check for content containers using edge-to-edge containers and provide recommendation to use "normal" or "wide" for accessibility line-length.  
- [x] Check for stat component being used for text areas instead of numbers.  
- [x] Check for CTAs using "edge to edge" and recommend using the "normal" option for users on larger screens.
- [x] Check for extra whitespace at top of page or bottom, and recommend they update the section containers to "remove top spacing" or "remove bottom spacing"
- [x] Check for buttons being created using the CTA and recommend they use the WYSIWYG button option in the text area. 
- [x] Check for text in containers using background colors without padding.  Offer recommendations to add padding. 
- [x] Check for use of all lowercase in headings.

**Comment by joewhitsitt** [comment]
who is the contact for delivering these recommendations.

captured these for future use: https://wiki.uiowa.edu/display/drupaldev/Content+Design+Best+Practices

**Comment by briand44** [comment]
We had discussed communicating these recommendations with April Wells.

**Comment by bspeare** [comment]
Sent these on to April yesterday.
