### ISSUE TITLE
Image editing functionality in CKEditor fix

### ISSUE THREAD

**Issue by bewoldt** [uiowa/uiowa#3614]
# Problem
When you edit an image in the wysiwyg editor you get a certain amount of options in the Display dropdown. It's not clear to the user what these options mean. When I pick small, I get a 100px wide image. When I pick Small - Square I would expect to get a 100px wide square image but instead I could (based on screen width) get a 2592x2592px image with a width="768" set on it.

The "Small - Square" and "Large - Square" images options end up being the same size.

I created some demo pages with examples of images.
https://studentlife.prod.drupal.uiowa.edu/image-test-small
https://studentlife.prod.drupal.uiowa.edu/image-test-medium
https://studentlife.prod.drupal.uiowa.edu/image-test-large

# Steps to reproduce
<img width="261" alt="Screen Shot 2021-06-03 at 4 53 44 PM" src="https://user-images.githubusercontent.com/731952/120717246-d4d31180-c48c-11eb-97e7-c522c1d0ba32.png">

# Proposed solution
Ideally there should be a way for the content editor to select a customize width/height for the image but I assume this would require a different plugin. In the mean time, I'd like to see the Square, Widescreen, and Ultrawide options be consistent. So, if Medium is 220px than Medium - Square should be 220px but cropped square.

**Comment by briand44** [comment]
small, medium, large came from v2 and were kept for video.

**Comment by briand44** [comment]
investigate to see if a bug was introduced here.

**Comment by joewhitsitt** [comment]
Might be a bad config regression here related to the small/medium/large options being available to images. Unfortunately, I think to fix (remove) those options for images (admin/structure/media/manage/image/display) textarea markup will have to be updated to switch to a replacement similar to the v2 merge.

**Comment by joewhitsitt** [comment]
>Might be a bad config regression here related to the small/medium/large options being available to images.

Looked into this. When we switched v2 over to media library, small/medium/large core image styles (not responsive) came with it.

We originally re-mapped them but the difference between small and small-no-crop was big as mentioned on this issue. So we just continued to support them and all we did was update entity-browser-isms to media-library-isms. https://github.com/uiowa/uiowa/pull/3048#issuecomment-778449186

What we didn't do was prevent new images from being set with these options using some kind of alter. That could still be a solution going forward if we want everything to be responsive. Removing them won't work because a cache rebuild will switch the image to original.

**Comment by pyrello** [comment]
We could run an update hook to convert image styles that weren't intended for V3 but snuck in based on the above change that @joewhitsitt discussed. As indicated, this would be similar to what we will need to do when we finally convert the remaining V2 sites to V3. It could be a trial run and probably the code could be reused.

**Comment by joewhitsitt** [comment]
I am not sure we have a proposed solution here yet. I think the ideal would be to stop allowing the non-responsive core image styles here, but we don't have a suitable substitute for existing without a big communication plan.

>We originally re-mapped them but the difference between small and small-no-crop was big

So are we developing responsive replacements?

Small = Thumbnail - No Crop
Medium = Tiny - No Crop
Large = Extra Small - No Crop

I think the other issue is that folks don't really know what they are going to get in the end so help text with a link to more information or adding min-max dimensions to the labels might be helpful with editor UX.

**Comment by mjoneill** [comment]
Next step: Hold until we can participate in a discussion with both @pyrello and @bewoldt .  Reluctant to propose a next step without their perspective represented.

**Comment by bewoldt** [comment]
What's the difference between Full and Original?

**Comment by joewhitsitt** [comment]
From the discussion, this is what I heard/thought:

- The original options were based on the available functionality at the time and might not be the best for what our platform has become or how it is being used.
- Survey our users to see what they use?
- Ask our collegiate group about how they approach wysiwyg images.
- Keep existing content markup in mind if we are retiring or repurposing options.
- See how ckeditor5/media is going to work related to images. Maybe there will be a compatible plugin to allow better in-editor manipulation.
- See about eliminating small/medium/large options for new images (grandfather existing)
- Confirm that our images are rendering in the expected aspect ratios (reports of square not looking square)
- With other components in v3, do providing all of these make sense? Should a separate set be used for WYSIWYG?
- Change our strategy from responsive/lazy to next gen/lazy? https://medium.com/@julienetienne/responsive-images-in-2020-vision-10caa8e9b993
- Investigate changing cropping strategy from focal point to see if we can better separate shape from size in the wysiwyg options.
- Add additional help text for whatever strategy we adopt going forward.

**Comment by joewhitsitt** [comment]
> What's the difference between Full and Original?

Full scales down to 2592w and is still processed/responsive. That is less important now that our upload has a max allowed that scales down as well.

Original was need for animated gif support (no processing) for images uploaded under the max.
