### ISSUE TITLE
Migrate Obermann files to v3

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#3615]
https://obermann.uiowa.edu -> https://obermann.prod.drupal.uiowa.edu/

**Comment by cory-skeers** [comment]
Wki page with instructions for `sitenow_migrate`: https://wiki.uiowa.edu/display/drupaldev/Using+SiteNow+Migrate

Doesn't need any custom code--general process is to enable the sitenow migrate config split, complete the Sitenow Migrate config page, and run the `d7_file` migration.

Previous process involved running the migration locally, disabling the split, and syncing files/db up to prod. Updated process allows running directly to prod.

**Comment by bspeare** [comment]
I'm hitting the "I'm interested" button on this one.

**Comment by bspeare** [comment]
File migration is complete and I have emailed the customer.
