### ISSUE TITLE
LB Styles renames

### ISSUE THREAD

**Issue by cory-skeers** [uiowa/uiowa#3617]
"Normal (Default)" section container setting was mentioned as possibly confusing, and difficult to describe what "normal" means. Has been some discussion, with both "Default" and "Standard" two preferred options.

"I’ve had trouble explaining the different options because a “normal” width is hard to describe. Standard would be my preference." <- Alex

May want to look through other styles, and have a discussion about additional possible changes.

**Comment by bspeare** [comment]
Another thing we could rename is the `Vertical align: start` style on sections to a more user-friendly label like `Remove equal height spacing`.

**Comment by makurj** [comment]
For my dev sprint.
