### ISSUE TITLE
Pharmacy map of Palliative Care Graduates

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#3624]
# Story

As a Pharmacy website owner, I would like the ability for site users to be able to view a map of palliative care graduates in the US to showcase that program and help with recruitment.

# Additional Info

They like https://admissions.prod.drupal.uiowa.edu/counselors but would want some way to designate that there is a graduate in a state vs states with no graduate. Discussed a different color on the map or possibly dots for each location.

They are fine with results below the map but would be open to other options.

Could technically have multiple graduates in one location.

They data that would be available is:

- Name
- Job Title
- Area of Practice
- Location
- Photo - not required

The Palliative Care Certificate is a Registrar sanctioned certificate that has been around for 3ish years and averages 15-20 graduates per year so maybe around 50 records at most initially.

The College of Pharmacy is not currently using the person content type.

Also shared https://international.uiowa.edu/global-network and https://uihc.org/our-current-resident-class as examples but liked Admissions more.

# Proposed solution

- [x] Site split
- [x] ~~Add Palliative Care Graduate tag (in PROD) to target as MVP instead of a split person type.~~ _person type done instead_
- [x] Location field (state/territory dropdown)?
- [x] Copy and adjust guts of Admissions' counselors map
- [x] Copy and adjust guts of Admissions' counselors view
- [x] Make sure it doesn't split the basic page layout builder config
- [ ] Area of Practice field? https://github.com/uiowa/uiowa/issues/3624#issuecomment-892857891
- [x] Enable split/module in PROD
- [ ] Place blocks on layout builder page

**Comment by joewhitsitt** [comment]
>They like https://admissions.prod.drupal.uiowa.edu/counselors but would want some way to designate that there is a graduate in a state vs states with no graduate. Discussed a different color on the map or possibly dots for each location.

This is setup this way, Admissions just has counselor coverage for all polygons. Some counselors cover an entire region.

https://international.uiowa.edu/global-network used to be a non-powerbi map but didn't have a UI to update content.

I think we can easily establish base functionality for these types of maps, but each one will need custom tweaks based on the content.

I have big ideas about maps for the 80% but there will always be 20% custom use-cases: https://github.com/uiowa/uiowa/issues/725

**Comment by dnkemper** [comment]
I'm so down to trying to figure out how to implement this 😅  Might need @joewhitsitt's assistance when he gets back - but want to give it a shot

**Comment by joewhitsitt** [comment]
@briand44 is `Area of Practice` a separate field or would that be covered by education, research areas or bio?

**Comment by dnkemper** [comment]
@briand44 @joewhitsitt do you have an idea what page they were wanting to implement this on? Not sure what communication may have taken place and for some reason thought it was listed in issue

**Comment by joewhitsitt** [comment]
Ah, I forgot that Brian said something about the contact being on leave. I would just make sure the the blocks are available for webmasters to place for right now unless Brian knows the answers these questions:

- Can Area of Practice be captured in another field or does it need a separate field?
- Where should the map/listing be placed?

**Comment by briand44** [comment]
I don't have those answers and yes, the contact is out. Yeah, just make sure the blocks are available for webmasters to place. I will reach out to customer with the remaining questions and follow up once I hear back.

**Comment by dnkemper** [comment]
Thank you so so much, @briand44

**Comment by joewhitsitt** [comment]
_The team built this functionality into the existing person content type and we were wondering if one of the existing fields (Education, Research Areas, Bios) would work to capture the Area of Practice data or if we need to create a separate field for that?_

> I’m a visual person and don’t know how to answer this.  Could you show me what you mean?

_Also, do you know where this should be placed on your website?_

> At first glance I would say here: https://pharmacy.uiowa.edu/pharmd/dual_cert/palliative
But this page is pretty full already, so when absolutely ready, I would probably make a link off of this page, make a new page (“where are they now?”) and place it on that page.  I could do that later next week.

**Comment by dnkemper** [comment]
Thank you, @joewhitsitt! I'm thinking about creating a draft "where are they now?" page and adding the map there then taking screen snapshots of how to add a person and the fields where we are suggesting the possible "Area of Practice" field. Please let me know if you have a better idea of how to go about this!

**Comment by joewhitsitt** [comment]
instead of touching content on the site, can we just fill out https://sandbox.prod.drupal.uiowa.edu/node/11/edit and send that for a visual?

sounds like Barbara is able to create a page for the content when able.

**Comment by dnkemper** [comment]
Okay! Thank you so much!

**Comment by dnkemper** [comment]
Wait.. how will I be able to show them their new person type and how to implement the map if we're going the sandbox route?

**Comment by dnkemper** [comment]
Emailed Barb an example of the fields that could possibly be used for 'Area of Practice'. Waiting to hear back. Also let know that when have page URL and needs help adding map to reach out

**Comment by joewhitsitt** [comment]
I think with the change in https://github.com/uiowa/uiowa/pull/4142, this can be closed correct @briand44 and @dnkemper ?

**Comment by joewhitsitt** [comment]
Barbara has the permissions and the recent demonstration to place the blocks

**Comment by dnkemper** [comment]
Agreed! Can wait for @briand44's input though

**Comment by briand44** [comment]
Agree! Nice work!
