### ISSUE TITLE
Pilot inactive site deprovision process on uiowa702

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#3625]
The uiowa702 app only has a few inactive sites. We can use that as a probe to try out a deprovision process and adjust for other applications.

Process
- Create an ad-hoc Dispatch communication templated with a placeholder for site URL.
- For each site, get all non-admin user emails and send the communication to them, replacing the site URL.
- Ask them to respond within two weeks indicating whether or not the site is needed.
- After two weeks, send the communication again asking them to respond within one week but this time mention that the site will be removed if there is no response.
- After that, remove the site domain.
- After a period of time without response, remove site code and database.

Removed sites can be restored from daily database backups and reverting commits if necessary.

**Comment by briand44** [comment]
Just adding that if we do remove site code and database we should probably create a backup as part of that process. We won't have daily backups once the database is removed and we only have around 3 days of backups available so that could be an issue if they don't notice right away and want their site back, correct?

**Comment by richardbporter** [comment]
Removing a database does not remove its daily backups. The last 3 should still be available.

**Comment by briand44** [comment]
So, it keeps the last three db backups around forever? Good to know if that is the case. I assumed they would be gone after 3 days.

**Comment by richardbporter** [comment]
Yes, as far as I know. Not so great for storage quotas. :)

**Comment by bspeare** [comment]
Updated this issue to make this a smaller slice and removed the Drush script slice and moved it to https://github.com/uiowa/uiowa/issues/3684.

**Comment by bspeare** [comment]
Email template: https://apps.its.uiowa.edu/dispatch/templates/932493356
Email population: https://apps.its.uiowa.edu/dispatch/populations/932491408/members
Email campaign: https://apps.its.uiowa.edu/dispatch/campaigns/932490456
Email communication: https://apps.its.uiowa.edu/dispatch/communications/932479972

Scheduled to go out June 21, 2021 9:00 AM.

**Comment by bspeare** [comment]
**Removed:**

- oldcapitoltennis.com
- lapd2019.centerforconferences.uiowa.edu

**Kept:**

- https://hawkeyecaucus.com

**Not responded by July 1st, 2021:**

- https://iexplorestem.org

If https://iexplorestem.org doesn't respond by the end of the day, do we move forward with removing https://iexplorestem.org?

**Comment by briand44** [comment]
We should double check if we tried communicating with gina-schatteman@uiowa.edu. When I looked at this before I was out I thought we hadn't reached out to that user and that was who I last communicated with in regards to iexplorestem.org. If we haven't communicated with that user we should resend the original communication (with date changed) to that user.

**Comment by bspeare** [comment]
@briand44 I will send out that communication this morning.

**Comment by bspeare** [comment]
Dispatch says the email sent was delivered and opened: https://apps.its.uiowa.edu/dispatch/analytics/communication/932479972.

**Comment by briand44** [comment]
We don't have a dispatch template for the follow up email communication if we don't hear back in two weeks. I just emailed Gina from my personal email and sent this message:
>Hi Gina,
We sent an email a couple weeks ago letting you know we are reviewing the SiteNow service for inactive sites and we asked if the https://iexplorestem.org website is needed? Can you please respond to us by the end of the week (July 30th) and let us know if you still need that website or if we can remove it? Please let us know if you are not the correct contact for this site. If we don’t get a response by July 30th, we will deactivate the https://iexplorestem.org website.

**Comment by briand44** [comment]
I got a response and the site is still needed. Updated the spreadsheet. Marking this complete as all inactive sites on 702 have been communicated with. The 2nd email template can be created as part of the process for 703.
