### ISSUE TITLE
Link to full url in Admissions PDF's

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#3627]
Is there a way in the PDF's to point to the full path for a URL vs the relative path? You can see in the engineering example (https://admissions.prod.drupal.uiowa.edu/print/pdf/node/2716) the bulleted majors at the top point to /node/xxx or the relative path /academics/xxx. Since these will only be seen in print these need to be the full URL.

**Comment by joewhitsitt** [comment]
on the surface, i think it prints whatever the wysiwyg has. internal links with linkit show the relative path. so there is a content solution to this at the risk of creating broken links down the road.

**Comment by GaryRidgway** [comment]
It may be possible to use a css selector using an [attribute begins with selector](https://www.w3schools.com/css/css_attribute_selectors.asp#:~:text=The%20%5Battribute%5E%3D%22value,to%20be%20a%20whole%20word!). this would allow us to determine if it is an internal link (Starts with a `/`) or an external link (Starts with an `h` or a `w`). With this, we could prepend `admissions.uiowa.edu` to the front of the `pseudo` element?
