### ISSUE TITLE
Remove default left/right banner padding if specific background and section colors are selected

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#3630]
# Problem

Selecting a banner background color adds extra padding that is unnecessary when banner is sitting within a section container with the same background color.  

# Steps to reproduce

Go to https://sandbox.prod.drupal.uiowa.edu/banner-examples-0. 

<img width="1510" alt="Screen Shot 2021-06-09 at 12 43 24 PM" src="https://user-images.githubusercontent.com/1036433/121403676-c23f5900-c920-11eb-9748-b19e4cd9c44c.png">
   

# Proposed solution

- Add a rule in `banners.scss` that will remove default padding if the selected background color is the same as the container background color. 
```

.layout:not([class*="bg-"]),
.layout[class*="bg--white"], {
  .banner[class*="bg--white"] {
    .banner__content {
      padding: 1.5rem 0;
    }
  }
}

.layout[class*="bg--black"], {
  .banner[class*="bg--black"] {
    .banner__content {
      padding: 1.5rem 0;
    }
  }
}

.layout[class*="bg--gray"], {
  .banner[class*="bg--gray"] {
    .banner__content {
      padding: 1.5rem 0;
    }
  }
}

.layout[class*="bg--gold"], {
  .banner[class*="bg--gold"] {
    .banner__content {
      padding: 1.5rem 0;
    }
  }
}
```

**Comment by makurj** [comment]
I'd like to pair with whoever picks this up.
