### ISSUE TITLE
Import OneIT Intranet projects more frequently

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#3646]
The OneIT Intranet imports projects from data.its to display on the Intranet. Data.its if getting these projects from Workflow. The request is to have this import happen more frequently. My understanding is that data.its is getting these from Workflow once a day.

**Comment by joewhitsitt** [comment]
How much more often? half day? six hours? hourly?

https://git.uiowa.edu/its-web/data.its.uiowa.edu/-/blob/main/app/Http/Controllers/WorkflowController.php#L112

**Comment by richardbporter** [comment]
Sine the feed is configured to import hourly and there is a scheduled cron job to support that, I would propose reducing the data.its cache time to make that import actually useful. Maybe like 15 minutes or so.

**Comment by richardbporter** [comment]
The `Cache::put` calls would need to be updated as well to match the response header.

**Comment by briand44** [comment]
If it is currently once every 24 hours, I think moving to once every 6 hours would be great if possible.

**Comment by richardbporter** [comment]
I changed the data.its cache to 6 hours for all workflow endpoints, deployed to prod and cleared the cache items. I also changed the intranet feed importer to run every 6 hours. This left the feeds feature in an overridden state but I'm unable to export it locally due to a fatal error.

**Comment by richardbporter** [comment]
I'll double check the feed importer runs later today. This could probably be closed now.

**Comment by richardbporter** [comment]
Log says it timed out. Increased timeout setting x2.

**Comment by richardbporter** [comment]
Imported fine this morning. Still unable to export the feature locally though. Don't fra in prod.
