### ISSUE TITLE
IRRC - Ability to link to Google Scholar and ResearchGate with supporting icons

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#3648]
# Story

As an owner of iowareadingresearch.org, I would like to have the ability to add links to Google Scholar and ResearchGate with supporting icons for people teasers and profiles.

# Additional Info

Icons to appear on  https://iowareadingresearch.org/people similar to http://readerbench.com/people but displaying below names on teaser display.

# Proposed solution

There is an existing links field, not sure if it makes sense to use that field and figure out a way to display icons or create new fields.

**Comment by bspeare** [comment]
The changes have been deployed to prod.  Closing this unless there are further changes to implement.
