### ISSUE TITLE
Add "[Closed]" text to the body of closed alert emails for ITS alerts

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#3649]
>[Closed] is in the subject line of the email notification but we would like to add it to the body of the message, too.

![Screen Shot 2021-06-18 at 8 54 26 AM](https://user-images.githubusercontent.com/1017022/122576214-103a1800-d017-11eb-8242-7b4bef343aad.png)

@joewhitsitt thought we may run into some accessibility issues with the red font and it may be difficult to align the "[closed]" text with the "Update" header.

@adriennecoon said the text can be black and it should be fine if the "[closed]" text appears above the "Update" header.

This is in `_email_alert()` in its_content_types/its_content_types.helper.inc

**Comment by joewhitsitt** [comment]
Locally, be wary of emails. Reroute email and its email debug admin/config/system/its

**Comment by richardbporter** [comment]
Putting it in front of the `UPDATE:` label will only print if there are updates to the alert. I'm assuming that is always the case.

**Comment by joewhitsitt** [comment]
>it should be fine if the "[closed]" text appears above the "Update" header.

Can this be adjusted to not rely on the update being there?

**Comment by richardbporter** [comment]
This is done but not deployed.
