### ISSUE TITLE
Article - Source/Organization Label, Source Link

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#365]
### Problem
Not all articles are written by individuals, some are written by an group/org/etc. Additionally, not all articles originate from the site, some are lifted from other sites like IowaNow. There needs to be a way to capture and display this.

### Proposed Solution
Create two fields, text field and a link field (link only), as both fields are optional and can be used with or without each other. Display the text field with no label. If a source link is provided, wire it to the text field.

Conditional states should display the source link if the source/organization field is filled out.

This should be incorporated into the byline area that already exists.

The help text should also encourage that if this is an external source that the metatag canonical URL should be specified.

### Test
An editor should be able to populate the organization and source URL and have it render appropriately on the node teaser and full node.

**Comment by richardbporter** [comment]
Can we just render the metatag fields instead of creating new ones?

**Comment by joewhitsitt** [comment]
Which meta fields would we use? How would we determine to render them?

Canonical URL
Original source (url)

Also, might be related, should we fill out defaults for schema article author?

**Comment by cory-skeers** [comment]
@joewhitsitt @richardbporter Started a branch on this (going with the original suggestion of two new fields) but wanted to get another set of eyes before going further.

Right now all the display logic is located in the .twig files, but it's a little excessive to where I think it would be better handled in a preprocess--both in keeping logic separate and to give more flexibility in extending it into possibly programmatically meta tag fields. 

I'd originally started with a preprocess in sitenow_article, but in making adjustments to add/not add linking, more and more shifted to the .twig template until...

**Comment by joewhitsitt** [comment]
going to take a look at this

**Comment by joewhitsitt** [comment]
I talked to @briand44 about this and we got some scope creep. For some D7 custom sites if a source link was provided, it would change the teaser path to link to the source instead of the node. I think we are going to add a boolean option to give editors the ability to do this.

Ultimately, I think this array of options is going to require re-structuring of the render logic.

**Comment by joewhitsitt** [comment]
This needs to account for HR specific templates and styles.
