### ISSUE TITLE
Unused page with left sidebar layout builder sections render with empty space on pages

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#3652]
# Problem
Unused "Page with left sidebar" layout builder section render with empty space on pages.

# Steps to reproduce
https://sandbox.prod.drupal.uiowa.edu/empty-sections-page

# Proposed solution
- [ ] Update template to use simplified include method: https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/templates/layouts/twocol/layout--twocol.html.twig#L19-L21.  Keep lines https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/templates/layouts/page--left-sidebar/layout--page--left-sidebar.html.twig#L16-L27. 
- [ ] Update SCSS to use `--content` class instead of `--main` in https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/scss/layouts/page--left-sidebar.scss
- [ ] Test heavily on v2.  This template is used by the majority of v2 pages.  HMB is a good site that uses a mix of layouts. Also test on Brand site.  Test with these page options in v2:
<img width="701" alt="Screen Shot 2021-06-17 at 3 44 37 PM" src="https://user-images.githubusercontent.com/1036433/122469890-0e267980-cf83-11eb-8f3a-343bf0c60734.png">

**Comment by makurj** [comment]
I'd like to pair with whoever picks this up.
