### ISSUE TITLE
URL styling not showing in custom People lists

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#3673]
# Problem
It looks like the blue colored font of URL links in the main SiteNow People page is not working on the custom filtered People list blocks elsewhere in the site. You can see this in [https://cs.prod.drupal.uiowa.edu/people](https://cs.prod.drupal.uiowa.edu/people) vs. [https://cs.prod.drupal.uiowa.edu/people/adjunct-faculty](https://cs.prod.drupal.uiowa.edu/people/adjunct-faculty).

![Screen Shot 2021-06-17 at 1 40 37 PM](https://user-images.githubusercontent.com/3067017/122455524-1aeea180-cf72-11eb-9d89-9eeb83a31b73.png)
![Screen Shot 2021-06-17 at 1 40 27 PM](https://user-images.githubusercontent.com/3067017/122455532-1e822880-cf72-11eb-8206-7808e046d0a0.png)

# Steps to reproduce
Should be there by default.

# Proposed solution
Add additional classes to the CSS to cover custom blocks.

**Comment by bspeare** [comment]
@mark-bennett-uiowa You can set your people block background to `-none-` if you want the blue links.

**Comment by mark-bennett-uiowa** [comment]
Ahh, thank you @bspeare !
