### ISSUE TITLE
Upgrade all applications to PHP 7.4

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#3675]
https://support.acquia.com/hc/en-us/articles/360061578973-PHP-7-3-Retirement-FAQ
https://support.acquia.com/hc/en-us/articles/1500005697422-Upgrading-from-PHP-7-3-to-7-4

- [x] #3965
- [x] #3966
- [x] #3967
- [x] #3968
- [x] #3969
- [x] #3970
- [x] #3971
- [x] #3972
- [x] #3973
- [x] #3974
- [x] #3975

**Comment by richardbporter** [comment]
We should figure out a path forward with SiteNow Migrate as part of this. If connecting to a Cloud IDE environment works, that would be ideal.

**Comment by richardbporter** [comment]
I would probably start with our single site applications first before tackling the larger multisite applications. It might be good to run PHPCS compat checks on the codebase before "testing" so we can narrow issues down. Acquia recommends upgrading dev environments first and debugging from there which seems like a good start.

**Comment by richardbporter** [comment]
It might be possible to install PHP 7.4 in DD: https://evolvingweb.ca/blog/install-specific-version-php-or-drush-acquia-dev-desktop

**Comment by briand44** [comment]
Do we need to split this into separate tasks for dev/stage environments and another for prod environments?

**Comment by joewhitsitt** [comment]
![look at us](https://media.giphy.com/media/iHyVaHfEYXZos8qPX2/giphy.gif?cid=ecf05e47k0ejdq5bzl0lyl2cn77m63lvtkcctzng65ojbwx4&rid=giphy.gif&ct=g)
