### ISSUE TITLE
As a v2 site editor/publisher/webmaster, I can embed Panopto videos.

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#3676]
# Story

As a v2 site editor/publisher/webmaster, I can embed Panopto videos.

Follow up from #3621 

# Proposed solution

Update v2 permissions to allow for this. Double check it works properly. Probably requires some responsive style updates.

**Comment by joewhitsitt** [comment]
Could be done in conjunction with https://github.com/uiowa/uiowa/issues/3691

**Comment by dnkemper** [comment]
@joewhitsitt I'll do this and #3691 together!
