### ISSUE TITLE
Multiple titles in people lists run together w/o separator

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#3677]
# Problem
Multiple titles show up as a concatenated string without separation in the People lists.

Here is one with two titles:
![Screen Shot 2021-06-17 at 3 42 05 PM](https://user-images.githubusercontent.com/3067017/122469521-aa9c4c00-cf82-11eb-9c59-a1aaf0c27577.png)

Here is one with three titles:
![Screen Shot 2021-06-17 at 3 42 33 PM](https://user-images.githubusercontent.com/3067017/122469531-ad973c80-cf82-11eb-9f61-5a906ee17fef.png)

# Steps to reproduce
This is visible on any sites with people who have multiple titles. Above examples are on [https://cs.prod.drupal.uiowa.edu/people](https://cs.prod.drupal.uiowa.edu/people).

# Proposed solution

- Break to new lines for each title like in the individual person view
- Update SiteNow People block using...
- Update people view blocks using...

![Screen Shot 2021-06-17 at 3 44 42 PM](https://user-images.githubusercontent.com/3067017/122469812-f949e600-cf82-11eb-9106-98ccb1fbdbee.png)

**Comment by bspeare** [comment]
To clarify, this is only an issue with the SiteNow People page `/admin/config/system/sitenow-people` and not an issue with the People List block.    Titles are separated with a comma in the People List block.

**Comment by bspeare** [comment]
We could add or scope this to the people list only `.field--label-visually_hidden.field--type-string` to https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/scss/fields/fields.scss#L90 to add commas or we could do it through the module.   Does anyone have a preference for solving this bug?

```
.field--label-visually_hidden.field--type-string {
  .field__item  + .field__item {
    &:before {
      content: ",";
      padding-right: $xsm;
      margin-left: -3px;
    }
  }
}
```

**Comment by joewhitsitt** [comment]
Override css rule for this field to just not be inline?

<img width="883" alt="Screen Shot 2021-06-22 at 1 11 14 PM" src="https://user-images.githubusercontent.com/4663676/122977769-67175880-d35b-11eb-91b1-b9801ea3a506.png">

**Comment by mark-bennett-uiowa** [comment]
Looks like the consensus was to break to separate lines for each title. @joewhitsitt your approach seems like a simple solution to this by simply removing the inline style. That seems to work on SIteNow People on initial testing.

In People view blocks however, the title is a concatenated string and wrapped in a single div:
![Screen Shot 2021-06-22 at 1 15 07 PM](https://user-images.githubusercontent.com/3067017/122978227-e4db6400-d35b-11eb-8a7d-849ebf7b7344.png)
