### ISSUE TITLE
Updates to sidebar items on ITS Service Alerts

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#3680]
Make menu system on IT Service Alerts page editable to @adriennecoon (I only have access to the section under IT Service Alerts in the menu, not the legend or blue box). If not, we’d like to make some modifications to items in the blue box and move the legend. There is a support article explaining how to subscribe to the Listserv via command prompt that we’d like to add to the blue box section.

**Comment by briand44** [comment]
@joewhitsitt suggested we would likely just make these changes. @adriennecoon can you let us know the modifications to the items in the blue box and where you want the legend?

**Comment by adriennecoon** [comment]
Here are the changes to the blue box: 
Get Service Alerts (header)
[Subscribe to email alerts via listserv](https://list.uiowa.edu/scripts/wa.exe?SUBED1=HELPDESK-ALERTS)
[Subscribe to email alerts listserv via email command](mailto:listserv@list.uiowa.edu?body=subscribe%20HELPDESK-ALERTS)
[Subscribe to the ITS alerts RSS feed](https://its.uiowa.edu/alerts/feed)
[Find out more about RSS on the ITS website](https://its.uiowa.edu/support/article/104758)
[How to post an IT service alert](https://its.uiowa.edu/support/article/107561)

And please put the legend below the blue box.

**Comment by joewhitsitt** [comment]
Closed as not planned
