### ISSUE TITLE
Add text to ITS alerts status history page

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#3681]
>We got some feedback that some faculty are using this page to view history of service status and thinking this is it: https://its.uiowa.edu/alerts/status-history Add a text box for a paragraph at the top that says it only goes back 5 days and to use the calendar view to see previous alerts or click on the individual service and use the alerts tab to see history for specific service. Link to the full calendar.

@adriennecoon can you provide the text you want and we will get it added.

**Comment by adriennecoon** [comment]
Here's the text we would like to display at the top of the page: 
"The purpose of this page is to show the operational status over the last five days of most technology services on campus. To see beyond five days, please review the [Alerts Calendar](https://its.uiowa.edu/alerts/calendar).”

**Comment by joewhitsitt** [comment]
Closed as not planned
