### ISSUE TITLE
Improve mobile view of ITS alerts calendar

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#3682]
>Mobile calendar view of alerts looks bad. Single character view (Safari on iPhone).

https://its.uiowa.edu/alerts/calendar

We discussed possibly using the full calendar list option here. Is that something that could be set based on screen size?

**Comment by briand44** [comment]
tagging @adriennecoon for visibility

**Comment by joewhitsitt** [comment]
Closed as not planned
