### ISSUE TITLE
Consistent usage of am/pm on ITS alerts

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#3683]
>AM/PM inconsistencies in calendar view, email view, alert on website, etc. We prefer AP Style (lowercase with period: a.m. and p.m.).

@joewhitsitt mentioned we may not have much control over the calendar view.

@adriennecoon prefers AP Style mentioned above but it is more important to have consistency.

Let's see what we can do with the calendar first and decide how to move forward based on that.

Most of the alerts stuff is in:
its.uiowa.edu/modules/custom/its_content_types
its.uiowa.edu/modules/custom/its_core
admin/structure/types/manage/alert/auto_label

**Comment by briand44** [comment]
would nice to have links to specific instances. Can remove grooming label once add links

**Comment by briand44** [comment]
https://its.uiowa.edu/alerts
http://its.uiowa.edu/alerts/calendar

![Screen Shot 2021-08-06 at 10 50 05 AM](https://user-images.githubusercontent.com/1017022/128537465-98d4e7a7-13d0-4a27-8dbe-20648b25b258.png)

@adriennecoon any other specific links to places where am/pm is being output inconsistently?

**Comment by richardbporter** [comment]
PHP doesn't do `a.m.` or `p.m.` with a date format so we can't just change the calendar view field date format. We'd have to manipulate the string somewhere in the theme. Still looking for where we might do that...

**Comment by richardbporter** [comment]
I think the best option is to change the Drupal "Alerts Digest" date format to use lowercase am/pm. Everywhere else seems to use lowercase so that would make it consistent. 

The spacing before `am/pm` is inconsistent though. We could remove or add a space in other locations depending on their preference.

**Comment by richardbporter** [comment]
Just changed the "Alerts Digest" format in prod to use lowercase am/pm as that does not seem to be featurized.

**Comment by richardbporter** [comment]
This is done but not deployed.
