### ISSUE TITLE
Add dates on info center IT Service Alerts tab

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#3685]
>On info centers, under the IT Service Alerts Tab, under Alert History, display date for Outages and Degradation of Services similar to Maintenance. Display date the outage/degradation started. Here’s an example: https://its.uiowa.edu/pressbooks#!it-service-alerts

In addition to adding dates for outages and degradation of services we also want to output the year for all of these.

## Proposed Solution

- [x] Update logic admin/structure/types/manage/alert/auto_label to not be type specific.
- [x] Add year

**Comment by briand44** [comment]
tagging @adriennecoon for visibility

**Comment by joewhitsitt** [comment]
auto entity label: admin/structure/types/manage/alert/auto_label

**Comment by makurj** [comment]
Feature branch: `its-alert-date`
In this file, sites/its.uiowa.edu/modules/custom/its_views/its_views.module, remove the switch case for "maintenance" and add the date formatter code to all alert types.
Also, added a comma after the year.

Big thanks goes to @GaryRidgway for pairing on this.
