### ISSUE TITLE
Admissions status report error:

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#3689]
The following error shows up on the status report for admisisons.uiowa.edu.

Mismatched entity and/or field definitions
The following changes were detected in the entity type and field definitions.
Content
The node.field_area_of_study_college field needs to be updated.

**Comment by bspeare** [comment]
Running the code outlined here (https://www.drupal.org/node/3034742#comment-13999920) made the error disappear:

```
function sitenow_update_9013() {
    $entity_type_manager = \Drupal::entityTypeManager();
    $entity_type_manager->clearCachedDefinitions();

    $entity_type_ids = [];
    $change_summary = \Drupal::service('entity.definition_update_manager')->getChangeSummary();
    foreach ($change_summary as $entity_type_id => $change_list) {
      $entity_type = $entity_type_manager->getDefinition($entity_type_id);
      \Drupal::entityDefinitionUpdateManager()->installEntityType($entity_type);
      $entity_type_ids[] = $entity_type_id;
    }
    drupal_flush_all_caches();

    return t("Installed/Updated the entity type(s): @entity_type_ids", [
      '@entity_type_ids' => implode(', ', $entity_type_ids),
    ]);
  }
```

Does anyone have a better method to fix this issue?

It looks like `drush entup` would have taken care of this back in the Drupal 8 days.

**Comment by bspeare** [comment]
`drush entup` gives the message  `Drupal removed its automatic entity-updates API in 8.7. See https://www.drupal.  
  org/node/3034742`.    The page referenced in the Drush message there is where I found the proposed update hook solution posted above.

**Comment by joewhitsitt** [comment]
Can we just run this update in admissions_core.install and specific to the field?

**Comment by bspeare** [comment]
@joewhitsitt do you have a suggestion on how to update https://github.com/uiowa/uiowa/pull/3698/files to be specific to the field?

**Comment by joewhitsitt** [comment]
Sorry, I didn't look that closely at the code before and I don't know what exactly is being returned with `$change_summary.` If this is just scoped to Admissions, I don't care too much if this solves the issue.
