### ISSUE TITLE
informatics.uiowa.edu site changes. Backup, deprovision, create redirect to new CS portal page.

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#3694]
# Story

The existing Iowa Informatics Initiative (UI3) site is now defunct: [https://informatics.uiowa.edu/](https://informatics.uiowa.edu/). The initiative has ended and it needs to be taken down. The existing site needs to be backed up (not critical, but just in case), and the existing URL will end up redirecting to https://cs.uiowa.edu/informatics as an undergraduate/graduate portal page. Computer Science is the administrative home for the undergraduate Informatics program and the graduate program in Informatics is jointly administered by the Graduate College and the CS Department.

This new https://cs.uiowa.edu/informatics page will be a portal page with a link to the Undergraduate degree options from CS and the Graduate degree options in [https://informatics.grad.uiowa.edu/](https://informatics.grad.uiowa.edu/). IGPI site will then be updated with a new faculty list and trimmed so that duplication of content is not being created on this site or the CS site.

# Proposed solution

- [x] #3801
- [x] #3802
- [ ] Ensure that the informatics.uiowa.edu domain points to acquia-dlb.its.uiowa.edu.
- [x] #3803
- [x] Update new portal page at https://cs.uiowa.edu/informatics.

**Comment by mark-bennett-uiowa** [comment]
Based on discussion today, it sounds like we will wait until CS launch to deprovision the informatics site and setup the redirect (@briand44 will assist here).

**Comment by mjoneill** [comment]
Our understanding is that work for the team in this sprint is the vulture redirect.

**Comment by mjoneill** [comment]
Update: Discussed this in planning. Team can commit to the slice of this that falls on us when @mark-bennett-uiowa is ready to pull this story into work.
