### ISSUE TITLE
HTML tags in global captions show on hover over image gallery images

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#3695]
# Problem
This can be seen on [https://vanallen.physics.uiowa.edu/photo-gallery](https://vanallen.physics.uiowa.edu/photo-gallery) among others.

# Steps to reproduce
Mouse over an image in the masonry image gallery and you can see HTML tags on hover.

# Proposed solution
- Move forward with https://github.com/uiowa/uiowa/pull/4708

**Comment by bspeare** [comment]
@mark-bennett-uiowa Can you provide a screenshot?

**Comment by mark-bennett-uiowa** [comment]
![Screen Shot 2021-06-21 at 3 13 46 PM (2)](https://user-images.githubusercontent.com/3067017/122822386-9a96ac00-d2a3-11eb-87ca-edb7b8abc398.png)
@bspeare whoops, sorry. Had to grab it before it disappears.

**Comment by joewhitsitt** [comment]
Based on the limitations of colorbox I think the only way to solve this would be to change the captions to be plain text as colorbox. Either that or we should revisit the library we use for this.
