### ISSUE TITLE
Adjust/remove the frontend "Person Types:" label

### ISSUE THREAD

**Issue by quamsta** [uiowa/uiowa#3696]
I was migrating some staff/person pages from our older sites and I noticed that this label "Person Types:" seemed a bit odd:

![image](https://user-images.githubusercontent.com/472923/122949207-1561d480-d341-11eb-8929-f0b073f13bfe.png)

Could we rethink the wording of "Person Types:" on the frontend or possibly prevent this label/field from being rendered? I know both possibilities were discussed at the web community meeting.

**Comment by quamsta** [comment]
@pyrello

**Comment by pyrello** [comment]
Thanks for putting this together, @quamsta!
