### ISSUE TITLE
Mazevo signage integration issue.

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#3699]
I set up a test sign called IMU-Schedule, but there is an issue. When I go into Configure Mazevo Event Listing to edit my selections, it seems to lose which Building and Room(s) I selected previously for display and defaults back to building University Club with no rooms selected.

It does seem to remember which Statuses and Types I selected previously, though.

**Comment by richardbporter** [comment]
There weren't any events for the next few weeks when this was built initially so to test locally you have to modify "today's date" in the code to be out a ways.

**Comment by richardbporter** [comment]
I think I got this figured out. Deployed.
