### ISSUE TITLE
Brand - Lockup Generator

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#370]
Work has been started https://github.com/uiowa/uiowa/tree/brand-lockup-feature to recreate the lockup generator currently on brand.uiowa.edu in D8 on the new brand site with updated lockup design. Additional improvements to workflow have been requested.

Steps related to this work is being tracked in OSC's Asana.

**Comment by GaryRidgway** [comment]
Completed dividing bars, color correction, and improved show/hide functionality 
https://github.com/uiowa/uiowa/commit/0dd79847f4b3be525f43817881e96af41121898c, https://github.com/uiowa/uiowa/commit/796b22268aecf61e1c0f6427e07fa1c11dcf0715, https://github.com/uiowa/uiowa/commit/c63a055f534776770500aa9dcb1cacc60715932d, https://github.com/uiowa/uiowa/commit/0a1e7fcb8c4b12385d7dd89183ff049814c46502

**Comment by joewhitsitt** [comment]
I am going to push brand-lockup-feature with what we have so far so that OSC can see the progress and start a new branch.

**Comment by joewhitsitt** [comment]
The lockup functionality is currently being reviewed by OSC. Separate tasks have been split off and will be created based on upcoming feedback. Closing.
