### ISSUE TITLE
As a content editor, I can have a default anonymous image for Person nodes

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#3701]
# Story

As a content editor, I can have a default anonymous image for Person nodes if one is not added.

# Proposed solution

Can we include a default, anonymous, non-identifying, image to use for Person nodes if an editor does not upload one for the node?

I added one temporarily for Computer Science and Physics faculty members, but would prefer to have an automatic default if one is not uploaded and attached to the Person node:

![Screen Shot 2021-06-22 at 1 27 37 PM](https://user-images.githubusercontent.com/3067017/122979961-c1b1b400-d35d-11eb-9648-ff67aa127198.png)
![anonymous_silhouette](https://user-images.githubusercontent.com/3067017/122980045-d7bf7480-d35d-11eb-9c4c-5d8c6b1b22d4.jpeg)

**Comment by bspeare** [comment]
Denny has set a default for the new directory: https://profiles-test.uiowa.edu/people/bruce-ayati.    Maybe upload that and reuse it for each site?

**Comment by mark-bennett-uiowa** [comment]
@bspeare That may work, but *shakes head* its awfully boring. What is the possibility of having this be a automatic default image that doesnt require attaching to each person?

**Comment by bspeare** [comment]
Adding a default image to the people lists would be great since it is now a standard being set by the new profiles directory.

**Comment by makurj** [comment]
How about a more generic placeholder image? Like this, perhaps? 
![image](https://user-images.githubusercontent.com/52135878/123816247-c544be00-d8bc-11eb-986b-5485c479c2e4.png)

**Comment by bspeare** [comment]
MARCOM has requested to update the person profile to use the brand icon, so here's what the current implementation in https://github.com/uiowa/uiowa/pull/3727 looks like:


<img width="1394" alt="Screen Shot 2021-06-30 at 3 51 26 PM" src="https://user-images.githubusercontent.com/1036433/124030537-e4764500-d9bb-11eb-9c0b-9f40418b56d1.png">
<img width="1399" alt="Screen Shot 2021-06-30 at 3 53 04 PM" src="https://user-images.githubusercontent.com/1036433/124030557-eb9d5300-d9bb-11eb-9b36-31c752ace78c.png">
<img width="1395" alt="Screen Shot 2021-06-30 at 3 56 05 PM" src="https://user-images.githubusercontent.com/1036433/124030568-ecce8000-d9bb-11eb-8dda-764f576e9579.png">
<img width="1393" alt="Screen Shot 2021-06-30 at 3 51 16 PM" src="https://user-images.githubusercontent.com/1036433/124030577-ee984380-d9bb-11eb-821e-f4f51e397a4c.png">
<img width="858" alt="Screen Shot 2021-06-30 at 3 51 08 PM" src="https://user-images.githubusercontent.com/1036433/124030599-f7891500-d9bb-11eb-9399-a4b03df2d079.png">

**Comment by bspeare** [comment]
Here's what the latest icon looks like and new positioning based on @joewhitsitt suggestion. 

<img width="642" alt="Screen Shot 2021-07-07 at 2 34 36 PM" src="https://user-images.githubusercontent.com/1036433/124818478-b4392400-df30-11eb-9105-75b8bb6b38c1.png">

<img width="1404" alt="Screen Shot 2021-07-07 at 2 35 10 PM" src="https://user-images.githubusercontent.com/1036433/124818495-b7ccab00-df30-11eb-9831-358d88e70491.png">

**Comment by joewhitsitt** [comment]
i am a fan. just more consistent look when you have a mix of actual headshots and placeholder images.
