### ISSUE TITLE
SPPA - Build opportunity resource listing page

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#3706]
# Story

As an SPPA student, I can view opportunities (jobs, fellowships, etc.) in a list on the site.

# Proposed solution

* Build a view to list content created via the result of #3211.
* Provide filters for name, location, type of opportunity.
* May involve minimal styling based on timely feedback from the client.

**Comment by joewhitsitt** [comment]
Should this be a block or a view page?

**Comment by pyrello** [comment]
View page.

**Comment by joewhitsitt** [comment]
Should the path be /opportunities or something else?

**Comment by pyrello** [comment]
Yeah, let's go with that for now
