### ISSUE TITLE
As a developer, I can use visual regression testing as part of my code review workflow

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#3713]
# Story

As a developer, I can use visual regression testing as part of my code review workflow so that fewer visual regressions happen after code deployment. 

- https://css-tricks.com/testing-for-visual-regressions-with-percy/#unlocking-the-true-power-of-percy

# Proposed solution

Use Percy's free solution (https://percy.io/pricing) and see if it helps us find visual regressions that might be missed in code reviews.

**Comment by bspeare** [comment]
It might be a good idea to pair this issue with the work in https://github.com/uiowa/uiowa/issues/3678.

**Comment by richardbporter** [comment]
We'll have to snapshot what is available in CI which is the default site. I think we have two options there:

- default content
- content created via Behat

The first would be easier to start with but might not be as useful, unless we update the default content. The latter would provide functional test coverage to ensure blocks but would take longer to set up. We'd also have to ensure Percy ran after behat tests.

**Comment by richardbporter** [comment]
> It might be a good idea to pair this issue with the work in #3678.

I did not work on that since it was marked as postponed.
