### ISSUE TITLE
Adjust breakpoint on `layout__container` for padding consistency

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#3720]
# Problem
The layout container padding that is added or removed through the "Spacing" options on layout builder sections is not consistent for 

# Steps to reproduce
Add `Add extra top spacing` to a layout section and observe how the spacing gets smaller if you drop below the `container` breakpoint. 

# Proposed solution
- Change the spacing to be increased at a lower breakpoint so that there is not an unexpected spacing shift if the browser width drops below the `container` breakpoint. 
- Update https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/scss/global.scss#L38 to `sm` intead of `container`.

**Comment by makurj** [comment]
I would like to pair on this.
