### ISSUE TITLE
Engineering Go-Live Aug 16th on uiowa

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#3724]
Review Engineering.prod.drupal.uiowa.edu in preparation for launch in the next couple weeks.

## Soon
- [x] screaming frog
- [x] design review
- [x] copy review

---

## Launch Tasks
- [x] create domains for www and engineering.uiowa.edu on uiowa application
- [x] point engineering.prod.drupal.uiowa.edu to old site on 70x application
- [x] add reminder to follow up in one month after launch to see if they still need old site (likely will)
- [x] turn off news article feeds importers for departmental sites (BME, CBE, CEE, ECE, ISE, ME)
- [x] guide customers with go-live (seo, etc.)

**Launch Day Support**
 On launch day assist our partner with:
- [x] Identifying broken links with Screaming Frog
- [x] identifying links to prod/stage/dev with Screaming Frog
- [x] identifying missing meta descriptions with Screaming Frog 
- [x] identifying typos and spelling errors with Screaming Frog
- [x] submitting sitemap via Google Search Console
- [x] verifying 404/403s are visible in Google Analytics (and showing partner how to see those)
- [x] verify content/pages are not blocked by robots.txt
- [x] schedule recrawl with Siteimprove

**Comment by joewhitsitt** [comment]
@GaryRidgway caught this: https://engineering.prod.drupal.uiowa.edu/future-students/first-year-students/student-ambassadors

**Comment by mjoneill** [comment]
I completed the screamingfrog review for engineering and posted results in #redesign-engineering slack channel.

**Comment by briand44** [comment]
Engineering will update links to people pages and create redirects on Departmental sites to point to appropriate places on the new engineering site after launch.

**Comment by briand44** [comment]
@mjoneill @joewhitsitt I've made a few updates to this based on our conversation today. Please add any additional action items that I may have missed. Should we outline the specific SEO/launch related items we need to assist/guide them on?

**Comment by briand44** [comment]
@joewhitsitt I was editing at same time and overwrote some of your changes

**Comment by briand44** [comment]
I think SSL is done already

**Comment by mjoneill** [comment]
<removed comment as content was added to issue description>

**Comment by briand44** [comment]
@mjoneill I added those items to the description

**Comment by joewhitsitt** [comment]
i will plan to start around 8 am on 8/16

**Comment by joewhitsitt** [comment]
This hit a snag and I have switched the domains back. Waiting for information from Engineering CTO and Acquia.

**Comment by joewhitsitt** [comment]
site is live

**Comment by mjoneill** [comment]
Sitemap submitted (can't click the checkbox due to permissions). I'll enumerate here as I get things complete

**Comment by mjoneill** [comment]
Since we dropped www, I went ahead and asked siteimprove to change the URL it was using and kick off a new scan.  We can call this ("schedule recrawl with Siteimprove")  Done, but the results are not immediate...

**Comment by mjoneill** [comment]
This is done: "verifying 404/403s are visible in Google Analytics (and showing partner how to see those)"

**Comment by mjoneill** [comment]
The following are done: 

- Identifying broken links with Screaming Frog
- identifying links to prod/stage/dev with Screaming Frog
- identifying missing meta descriptions with Screaming Frog
- identifying typos and spelling errors with Screaming Frog
- verifying 404/403s are visible in Google Analytics (and showing partner how to see those)
- verify content/pages are not blocked by robots.txt

**Comment by joewhitsitt** [comment]
Did any additional work crop up or is this considered done?

**Comment by mjoneill** [comment]
> Did any additional work crop up or is this considered done?

I think we can consider it done. I shared all the reports in the #redesign-engineering slack channel.

They have an absolute flood of prod.drupal links on their site. I think we're going to have to figure out a more reliable way to get visibility into this prior to launch.  

^^^ I'll add a card to backlog.
