### ISSUE TITLE
Add support for *.biology.uiowa.edu to uiowa01 SSL certificate

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#3733]
Adding support for *.biology.uiowa.edu to uiowa01 SSL certificate in order to cover the iba.biology.uiowa.edu site.

**Comment by joewhitsitt** [comment]
@mark-bennett-uiowa this is done finally after figuring out those troublesome dcv domains!

**Comment by mark-bennett-uiowa** [comment]
Thanks @joewhitsitt
