### ISSUE TITLE
Section Background affects lb_direct_add text color

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#3734]
## Story

As an editor, I can create a new section, use any background color I choose and when adding a block to the section, see the the available options in an accessible way.

## Steps to Reproduce:

Section with black background particle

<img width="1453" alt="Screen Shot 2021-07-01 at 1 46 00 PM" src="https://user-images.githubusercontent.com/4663676/124175365-22827000-da73-11eb-9b94-04658fe149a6.png">

## Proposed Solution

- [ ] Replace these lines (https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/templates/form/container.html.twig#L28-L42) with the solution below or another solution of your choice. 
```
{% set style_classes = [] %}
{% for style in attributes.class %}
  {# Remove bg classes from being printed on layout-builder__section div  #}
  {% if style starts with 'bg--' %}
    {% set style_classes = style_classes|merge([style]) %}
  {% endif %}
{% endfor %}
```

**Comment by makurj** [comment]
I would like to pair on this.

**Comment by GaryRidgway** [comment]
So far during testing I am unable to reproduce. possibly seems like cache clearing may have fixed this? @makurj suggests cache clearing worked for the Tippie site.

![Screen Shot 2021-07-09 at 2 21 22 PM](https://user-images.githubusercontent.com/23122142/125126613-f8f3c500-e0c0-11eb-93a5-4cda680373b6.png)

**Comment by bspeare** [comment]
@GaryRidgway Have you tried it with the black background particle style?  That’s the only one causing the bug.
