### ISSUE TITLE
Recserv - Highlight "join us" menu link

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#3751]
# Story

As a visitor to the recserv.uiowa.edu website, I can see a different styled menu link for the join us link, that brings more attention to it than the other menu items.

>We would like to be able to highlight our “Join us! Become a member” link on the top in a different color or with a different background.  Is this possible?  See [Florida](https://recsports.ufl.edu/) for example.

<img width="450" alt="Screen Shot 2021-07-01 at 4 06 33 PM" src="https://user-images.githubusercontent.com/4663676/124189473-6337b480-da86-11eb-9071-57271d4ab637.png">

## Proposed Solution

- [x] Target the last leaf menu link class in this menu to provide a theme-branded highlighted menu link. something like `.top-nav .block--menu-rec-top-nav-links .nav > li.last > a`
<img width="437" alt="Screen Shot 2021-07-01 at 4 14 42 PM" src="https://user-images.githubusercontent.com/4663676/124190518-063cfe00-da88-11eb-8e7e-aa9d5e44fa57.png">

- [x] Since the default hover is yellow, a custom hover for this item would be ideal.
- [ ] If you can't get the theme to compile, a local css style file can be added.

**Comment by makurj** [comment]
I would like to help with this.

**Comment by joewhitsitt** [comment]
Reached out to customer for review

**Comment by makurj** [comment]
Completed.
