### ISSUE TITLE
Recserv - Update footer information

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#3753]
# Story

As a site owner I can see the updates I provide for the footer in production since I can not make the changes myself.

# Proposed solution

Update the following links in the footer (docroot/sites/recserv.uiowa.edu/modules/custom/rec_footer_block/rec_footer_block.module)
- [ ] ~~Join our Newsletter – Waiting to hear back from marketing about this.~~
- [x] Donate Now Link -  Change to https://donate.givetoiowa.org/s/1773/giving/19/interior.aspx?sid=1773&gid=2&pgid=509&cid=1288&bledit=1&dids=608.28.606.579&sort=1&appealcode=2021GFWA

**Comment by joewhitsitt** [comment]
Regarding the newsletter link update:
>it will be quite some time before that switch happens so we can hold off on that change but move forward with the others.

IS update and unblocking

**Comment by makurj** [comment]
Completed.

**Comment by joewhitsitt** [comment]
Thanks @makurj!
