### ISSUE TITLE
Superfish - Touch is not working correctly on iPads

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#3757]
# Problem
>Anyone else notice that if you’re using a tablet in horizontal mode, the main navigation dropdown menus are impossible to use? Any tap interaction just takes you to the main links page before the dropdown shows up.

# Steps to reproduce
With an iPad, attempt navigate to a dropdown menu item on https://coronavirus.uiowa.edu. Though long press works for emulators, iPads have a long-press behavior that opens a modal window.

https://user-images.githubusercontent.com/4663676/124304971-0ee61080-db2a-11eb-8586-21cda401c917.MP4

This might be able to be reproduced in BrowserStack.

# Proposed solution
- [ ] Try updating the superfish module to the latest stable version and place the feature branch in DEV for review by those that have iPads to test with.
or
- [ ] Look through the superfish module and library issue queues for in progress solutions that we may be able to leverage.
or
- [ ] See if the touch plugin settings can be adjusted to allow touch dropdown on the arrows and adjust styles.
or
- [ ] Create an override with additional JS.
or
- [ ] invoking mobile menu for ipads all the time?
or
- [ ] Consider moving away from Superfish. Specifically, Drupal Superfish... Could lift nav from Olivero.

**Comment by joewhitsitt** [comment]
Curious if the same iPad behavior is experienced here: http://lb.cm/olivero.

They have a separate button for the dropdown items
<img width="721" alt="Screen Shot 2021-07-06 at 8 56 26 AM" src="https://user-images.githubusercontent.com/4663676/124612639-1e21d280-de38-11eb-96f6-ecc9fbebcde3.png">

**Comment by mjoneill** [comment]
> Curious if the same iPad behavior is experienced here: http://lb.cm/olivero.

This defaults to hamburger menu on horizontal/iPad (11in, iPad Pro)

@joewhitsitt

**Comment by joewhitsitt** [comment]
sf-Touchscreen is currently disabled. It can be invoked by window width or by user-agent info. This might be the easiest short term solution.

>sf-Touchscreen provides touchscreen compatibility. (The first click on a parent hyperlink shows its children...)

Then the following behaviors:

- Opening the parent menu item link on the second tap.
- Hiding the sub-menu on the second tap.
- Hiding the sub-menu on the second tap, adding cloned parent links to the top of sub-menus as well. (Default)

We are using the _Hiding the sub-menu on the second tap, adding cloned parent links to the top of sub-menus as well. (Default)_ behavior for off-canvas menu.

I am not sure if there was a reason behind this originally or if it was just configuration that wasn't set.

**Comment by bspeare** [comment]
Just tested this locally with browserstack and updating the `sf-Touchscreen` setting seems to have fixed the issue:


<img width="1156" alt="Screen Shot 2021-07-07 at 9 20 49 AM" src="https://user-images.githubusercontent.com/1036433/124776004-b71e1f80-df04-11eb-840d-a1a315fd144f.png">

**Comment by joewhitsitt** [comment]
@bspeare was this just testing or are you suggesting a path forward would be to enable sf-Touchscreen for horizontal and mega regardless of window width or user agent? Do you prefer this over trying to get the dropdown buttons working and styled?

**Comment by bspeare** [comment]
I would prefer this solution for now and eye the additional work for the future.

**Comment by pyrello** [comment]
I think this is supposed to be closed via #3768

**Comment by joewhitsitt** [comment]
Will someone volunteer to create that follow-up issue?
