### ISSUE TITLE
SSL Cert - *.iowastem.org on uiowa02

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#3761]
https://org-iowastemse.prod.drupal.uiowa.edu

**Comment by briand44** [comment]
iowastem.org has been validated.

**Comment by joewhitsitt** [comment]
should we wait on this a bit more so it doesn't become a problem again? their site still has default content on it.

**Comment by joewhitsitt** [comment]
Updated the issue summary. This issue can proceed through our normal workflow.
