### ISSUE TITLE
As a webmaster, I can access the Site Verification tab in SEO Settings on Page content type

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#3764]
As a webmaster, I can access the Site Verifcation tab in SEO Settings on Page content type so that I can verify my site with a number of services. 

# Proposed Solution

- Update SEO Settings permissions to allow webmasters access to Site Verification tab. 

# Possible Concerns

- If this is allowed on every page and not just the home page, does this create verification issues for site owners if they add the verification code on pages other than the home page?

**Comment by makurj** [comment]
I would like to pair on this.
