### ISSUE TITLE
Banner URL button does not have hover effect

### ISSUE THREAD

**Issue by makurj** [uiowa/uiowa#3767]
# Problem
If you have a yellow brain pattern banner and add a link to it, the button has no hover "underline" effect. It also looks like the ids coming in the CSS are different. See screenshot below:

![image](https://user-images.githubusercontent.com/52135878/124820012-940a6480-df32-11eb-90dc-cd74e8ccf2a0.png)

# Steps to reproduce
https://tippie.prod.drupal.uiowa.edu/banners

**Comment by makurj** [comment]
I would like to work on this with some guidance.

**Comment by bspeare** [comment]
I think if you add this to https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/scss/components/banner.scss#L187 it should fix the issue. 

```
[class*="bg--gold"] .bttn--primary::after {
  background-color: #fff;
}
```
