### ISSUE TITLE
Superfish - submit pull request for Superfish library

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#3772]
# Story

As a developer I can submit a patch to the Superfish module to share the changes we made for user agent detection back tot the Drupal community. 

# Proposed solution: submit a pull request for the Superfish library

- [ ] Create pull request on https://github.com/mehrpadin/Superfish-for-Drupal/pulls based on change in https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/assets/js/sftouchscreen.js.

**Comment by pyrello** [comment]
Thanks for putting this together! I don't think that the second bullet point is actually necessary. If the change is accepted and a new release is created in the 2.x series for the Superfish-for-Drupal, then the module shouldn't need any changes for that to get updated.

**Comment by pyrello** [comment]
I think it should be @GaryRidgway who does this task. It was his fix and he deserves the credit.

**Comment by GaryRidgway** [comment]
[This has been submitted here](https://github.com/mehrpadin/Superfish-for-Drupal/pull/31), thanks all for pushing me to contribute back, it is a nice feeling :)
