### ISSUE TITLE
CKEditor strips empty <span> tags (FontAwesome issue)

### ISSUE THREAD

**Issue by cory-skeers** [uiowa/uiowa#378]
### Problem
Related to #367. CKEditor strips any html tags from WYSIWYG fields which do not surround text. This interferes with the ability to use FontAwesome icons within content, as it won't allow empty `<span class>` tags.

### To Reproduce
Open a WYSIWYG editor source, add an example icon
`<span class="fa fa-facebook-square fab"></span>`
Close the source.

### Proposed Solution
Either allow all empty tags in WYSIWYG fields (not recommended) or implement a check in CKEditor to look for and allow FontAwesome-related tags.

### Test
Successfully insert an empty `<span class></span>` tag into a WYSIWYG field.

**Comment by joewhitsitt** [comment]
This appears to be one way to handle it:
https://drupal.stackexchange.com/questions/183036/allow-empty-tags

**Comment by richardbporter** [comment]
#382
