### ISSUE TITLE
SPPA - Export job content items from D7 site

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#3781]
# Motivation
There are about 18,000 job content items that  are not being migrated to the new SPPA site. We need to figure out the best way to export them into a CSV file or some other format.

# Proposed solution
- Use views to generate a SQL query that can be used to create an export in Sequel Pro.
- Use Sequel Pro to generate a CSV export with the query.

**Comment by briand44** [comment]
May be able to use views data export. There are a lot of records. I've had to do multiple exports in the past when a large number of records. If times out, try exporting half records in one and then run the other half.

**Comment by pyrello** [comment]
On other sites we have had very mixed success with views data export. It is basically unusable for large record sets. I think anything over 2-3k records is going to bomb out. Because of those issues, I don't really trust the tool and it actually seems like more work to get it done and to verify that it worked.

**Comment by joewhitsitt** [comment]
Did you try sequel pro last time? I thought I had recommended that for an issue with larger data

**Comment by briand44** [comment]
>I think anything over 2-3k records is going to bomb out.

This is good to know. I wasn't sure how many records before it would start choking.

**Comment by pyrello** [comment]
> Did you try sequel pro last time? I thought I had recommended that for an issue with larger data

Nope. That is what this issue is about.

**Comment by briand44** [comment]
database name is "urban"

**Comment by pyrello** [comment]
Here is the SQL query:

```sql
SELECT 
node.nid AS nid, 
node.created AS node_created, 
node.title AS node_title, 
listing_type.field_listing_type_value, 
listing_link.field_listing_link_url, 
organization.field_listing_organization_value, 
city.field_listing_city_value, 
state.field_listing_state_value, 
requirements.field_listing_requirements_value, 
salary.field_listing_salary_value, 
opentil.field_listing_opentil_value, 
closedate.field_listing_closedate_value, 
interndates.field_listing_interndates_value
FROM 
node
LEFT JOIN field_data_field_listing_type AS listing_type ON (listing_type.entity_id = node.nid)
LEFT JOIN field_data_field_listing_link AS listing_link ON (listing_link.entity_id = node.nid)
LEFT JOIN field_data_field_listing_organization AS organization ON (organization.entity_id = node.nid)
LEFT JOIN field_data_field_listing_city AS city ON (city.entity_id = node.nid)
LEFT JOIN field_data_field_listing_state AS state ON (state.entity_id = node.nid)
LEFT JOIN field_data_field_listing_requirements AS requirements ON (requirements.entity_id = node.nid)
LEFT JOIN field_data_field_listing_salary AS salary ON (salary.entity_id = node.nid)
LEFT JOIN field_data_field_listing_opentil AS opentil ON (opentil.entity_id = node.nid)
LEFT JOIN field_data_field_listing_closedate AS closedate ON (closedate.entity_id = node.nid)
LEFT JOIN field_data_field_listing_interndates AS interndates ON (interndates.entity_id = node.nid)
WHERE (( (node.type IN  ('job_listing')) ))
ORDER BY node_created ASC
```

**Comment by pyrello** [comment]
I think this is done, although I am waiting for confirmation from the customer. I ended up using TablePlus to export this because it seemed to do a better job of creating non-broken CSV exports. I had to change the UTF encoding to prevent smart quotes from being rendered as weird symbols.

Here is the SQL query I used for the most recent version of the export:
```sql
SELECT 
node.nid AS "ID", 
DATE_FORMAT(FROM_UNIXTIME(node.created), '%m/%d/%Y %H:%i') AS "Created", 
node.title AS "Title", 
listing_type.field_listing_type_value AS "Type", 
listing_link.field_listing_link_url AS "Web link", 
organization.field_listing_organization_value AS "Organization", 
city.field_listing_city_value AS "City", 
state.field_listing_state_value AS "State", 
requirements.field_listing_requirements_value AS "Degree requirements", 
salary.field_listing_salary_value AS "Salary", 
opentil.field_listing_opentil_value AS "Open until filled", 
DATE_FORMAT(closedate.field_listing_closedate_value, '%m/%d/%Y') AS "Close date", 
interndates.field_listing_interndates_value AS "Internship dates"
FROM 
node
LEFT JOIN field_data_field_listing_type AS listing_type ON (listing_type.entity_id = node.nid)
LEFT JOIN field_data_field_listing_link AS listing_link ON (listing_link.entity_id = node.nid)
LEFT JOIN field_data_field_listing_organization AS organization ON (organization.entity_id = node.nid)
LEFT JOIN field_data_field_listing_city AS city ON (city.entity_id = node.nid)
LEFT JOIN field_data_field_listing_state AS state ON (state.entity_id = node.nid)
LEFT JOIN field_data_field_listing_requirements AS requirements ON (requirements.entity_id = node.nid)
LEFT JOIN field_data_field_listing_salary AS salary ON (salary.entity_id = node.nid)
LEFT JOIN field_data_field_listing_opentil AS opentil ON (opentil.entity_id = node.nid)
LEFT JOIN field_data_field_listing_closedate AS closedate ON (closedate.entity_id = node.nid)
LEFT JOIN field_data_field_listing_interndates AS interndates ON (interndates.entity_id = node.nid)
WHERE (( (node.type IN  ('job_listing')) ))
ORDER BY node.created ASC
```

**Comment by pyrello** [comment]
Ugh. Getting this to output correctly was a character encoding nightmare! The export looked fine when directly viewing the file contents in a program like VS Code. It also looked fine in Numbers. But when opened in Excel (both the online and desktop versions) it was replacing smart quotes with various symbols. I ended up having to export from Numbers into an Excel spreadsheet format, then open in Excel (which triggered a "repair"), then re-save the file to get it to display correctly.

Customer has confirmed that the file looks good now.
