### ISSUE TITLE
Grad - Investigate json export feed solution

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#3784]
# Motivation

To finally retire the D7 Grad site, we need to come up with a replacement for the following json export, which is currently in use on several Qualtrics forms: https://grad.prod.drupal.uiowa.edu/json/GradFellowProgramsV2.json

# Proposed solution

Add json extension to document media type.

**Comment by briand44** [comment]
Can you provide a little context about where this data is coming from, how often this data is updated, how it is updated, etc. I would like to help come up with some options for this, just don't recall enough information about it.

**Comment by pyrello** [comment]
I believe that this is a list that we have curated, transformed into JSON and uploaded to our D7 Grad site via a custom module. It is updated maybe 1-2 times per year, if that. When it is updated, it would involve uploading a new file.

**Comment by briand44** [comment]
Curious on if this could just be hosted on data.its? The issue there would be that it would involve developer interaction when it needs updated. Is that a deal breaker?

**Comment by pyrello** [comment]
Not necessarily. I'd need more details about how it would work to say for sure.

**Comment by briand44** [comment]
Lets try adding json to the doc file type and see if this renders correctly and meets the need.
