### ISSUE TITLE
SPPA - Export bio content items from D7 site

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#3785]
# Motivation
We are not building a replacement solution for SPPA to display this information, but they would like it in some format.

# Proposed solution
Similar to #3781 - note the discoveries made in the comments that views_data_export might not work for this content and the alternative

**Comment by briand44** [comment]
Views data export may be a good path forward.

**Comment by briand44** [comment]
database name is "urban"

**Comment by pyrello** [comment]
Blocker for #6119

**Comment by briand44** [comment]
This is no longer relevant. D7 site no longer exists.
