### ISSUE TITLE
Genetics - Adapt Thesis Defense content type from grad.uiowa.edu split

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#3786]
Story: As a site owner, I want to publish information about upcoming student thesis defenses.

# Proposed solution
* Move configuration related to the Thesis Defense content type, Views calendar and list displays, as well as anything else related to these from the Grad College split to a feature split.
* Write an update hook for Grad College to turn the split on.

**Comment by joewhitsitt** [comment]
i wonder if it would be easier and less human error if we pushed out an empty feature split. turned it on in grad and then moved things into it so the normal deployment just runs
