### ISSUE TITLE
Update Outreach Map

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#3793]
The data associated with https://outreach.uiowa.edu/map/county needs to be updated.

There is information about the developer process here once the update CSV files are provided:
modules/custom/outreach_county_data/README.md

Point of contact: Nick Benson

**Comment by joewhitsitt** [comment]
Reached out to Nick for the latest .csv files. Previous updates/examples are in the outreach_county_data module.

**Comment by joewhitsitt** [comment]
Updated data was provided. Assuming it is in the correct format, work can proceed on this.

**Comment by bspeare** [comment]
@joewhitsitt where is the updated data?

**Comment by joewhitsitt** [comment]
Sorry, didn't realize we were moving through the sprint work so quickly!

[MyCountyData_Spring2021_Alumni.csv](https://github.com/uiowa/uiowa/files/7197376/MyCountyData_Spring2021_Alumni.csv)
[MyCountyData_Spring2021_EnrolledStudents.csv](https://github.com/uiowa/uiowa/files/7197377/MyCountyData_Spring2021_EnrolledStudents.csv)
[MyCountyData_Spring2021.xlsx](https://github.com/uiowa/uiowa/files/7197378/MyCountyData_Spring2021.xlsx)

**Comment by joewhitsitt** [comment]
@makurj good news is that those errors you reported are a local only issue. relates to drupal_http_request() so I checked out the branch in 703 dev.

I don't think the numbers are lining up. For PROD the stat is `36,215 University of Iowa alumni live in Johnson County` whereas in DEV the stat is `4,631 University of Iowa alumni live in Johnson County` also, `154 Registered Advanced Nurse Practitioners` in PROD compared to `964,037 Registered Advanced Nurse Practitioners` in DEV.

Comparing to the 2017-18 files the columns don't quite line up. I would delete the inc/ js files, groom the data a bit and try again.

Good work on getting the generator to run so far!

**Comment by makurj** [comment]
Thanks, Joe. It looks like there are many more columns in the 2017-18.csv than there are in 2020-21.csv so I'll bring those over without the numbers and see if that works.

**Comment by makurj** [comment]
Here you go, Joe. [2020-21.csv](https://github.com/uiowa/uiowa/files/7203895/2020-21.csv)
[2020-21students.csv](https://github.com/uiowa/uiowa/files/7203896/2020-21students.csv)

**Comment by makurj** [comment]
[2020-21.csv](https://github.com/uiowa/uiowa/files/7204126/2020-21.csv)

**Comment by makurj** [comment]
Thanks so much @joewhitsitt! Completed. Joe will contact the user.

**Comment by joewhitsitt** [comment]
Customer contacted
