### ISSUE TITLE
dropdown menus in wysiwyg editor move with screen change

### ISSUE THREAD

**Issue by bewoldt** [uiowa/uiowa#3796]
# Problem
Dropdown menus in the ckeditor move up/down with the screen when scrolling or resizing browser window.

# Steps to reproduce

https://user-images.githubusercontent.com/731952/125661621-1c810aad-b0c8-4dbd-b73e-c49aec98b34a.mov

**Comment by joewhitsitt** [comment]
This is a duplicate of https://github.com/uiowa/uiowa/issues/3104. Added the studentlife tag to that. Can we close this?

**Comment by bewoldt** [comment]
yeah. I remember this issue was brought up in a demo one time and thought it was fixed.
