### ISSUE TITLE
Videos within cards in V2 are overflowing the card

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#3800]
# Problem
Videos within cards in V2 are overflowing the card

<img width="1405" alt="Screen Shot 2021-07-14 at 3 26 18 PM" src="https://user-images.githubusercontent.com/1036433/125690571-7d833066-2269-4c46-9025-255afced8b97.png">

# Steps to reproduce
Try adding a Panopto or Youtube video to the card text area on a V2 site. 

# Proposed solution
Since we don't allow media embeds in cards in V3 this isn't an issue there.

**Comment by joewhitsitt** [comment]
yikes! did not see that in HR. Was this introduced in https://github.com/uiowa/uiowa/pull/3711 or does it currently exist?

**Comment by bspeare** [comment]
@joewhitsitt Currently existed, not Panopto specific.

**Comment by joewhitsitt** [comment]
Workaround is to move video to text area "block" instead. We have an issue to account for filtered_html cards in v2 to v3. https://github.com/uiowa/uiowa/issues/3878
