### ISSUE TITLE
Backup DB and file system for Iowa Informatics Initiative (UI3) site.

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#3801]
Backup database and file system for Iowa Informatics Initiative (UI3) site.

[https://informatics.uiowa.edu/](https://informatics.uiowa.edu/)

**Comment by joewhitsitt** [comment]
create a site folder https://iowa.sharepoint.com/sites/CSI-Drupal2/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2Fsites%2FCSI%2DDrupal2%2FShared%20Documents%2FGeneral%2Fsite%2Dbackups&FolderCTID=0x0120002F9851D81A9B1E4DB63DA70E38793599

**Comment by richardbporter** [comment]
done
