### ISSUE TITLE
Add Vulture redirect from informatics.uiowa.edu to https://cs.uiowa.edu/informatics.

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#3803]
Add Vulture redirect from https://informatics.uiowa.edu to https://cs.uiowa.edu/informatics. (Contact Jack Moeller)

**Comment by mark-bennett-uiowa** [comment]
With @briand44 's help this was put into place by Jack Moeller last Friday. Can be turned on today when CS site goes live.

**Comment by briand44** [comment]
DNS has been updated. Not sure if it has propagated everywhere but the redirect worked from my phone.
