### ISSUE TITLE
As a site owner displaying events on my site, I can list more than 50 events.

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#3809]
# Story

As a site owner displaying events on my site, I can see more than 50.

The current maximum is 50 and there is no way to display more. It is entirely feasible someone may want to display more than that instead of directing people away from their site using the More link. 

# Proposed solution

Details TBD but essentially leverage the content hub API to retrieve the total number of results and page the output accordingly.

**Comment by joewhitsitt** [comment]
Somewhat relates to https://github.com/uiowa/uiowa/issues/2739 (+50 past events)

**Comment by richardbporter** [comment]
Requested by education.

**Comment by briand44** [comment]
Closing in favor of https://github.com/uiowa/uiowa/issues/2739

**Comment by briand44** [comment]
Work to be done as part of https://github.com/uiowa/uiowa/issues/5189
