### ISSUE TITLE
Hamburger Menu appearing in mobile view even when there are no child items

### ISSUE THREAD

**Issue by mjoneill** [uiowa/uiowa#3828]
On bam.sites.uiowa.edu I noticed that the hamburger menu was appearing in mobile sizes even though there are no menu items to display. 

![needless-hamberber](https://user-images.githubusercontent.com/7144234/126013684-fafae56a-b227-4a0d-97c0-37f960920be7.jpg)

**Comment by joewhitsitt** [comment]
https://www.drupal.org/project/superfish/issues/3059268

**Comment by bspeare** [comment]
This is also an issue for the "Toggle Navigation" on desktop.  Perhaps we could just run a check for menu items in the template before rendering the `{{ content }}`?

**Comment by joewhitsitt** [comment]
Is the template flexible enough if this doesn't exist?

**Comment by bspeare** [comment]
Yes, it will still look ok if the block doesn't render.

**Comment by richardbporter** [comment]
Seems like the site now has menu items but they are all drafts so anonymous users don't have access to them. Not sure if that was the case initially or not.

**Comment by mjoneill** [comment]
> Seems like the site now has menu items but they are all drafts so anonymous users don't have access to them. Not sure if that was the case initially or not.

Yes, they unpublished almost all their pages prior to the first CNN episode.  They are continuing to work on them in an unpublished state, and will likely publish as they are ready, etc...
