### ISSUE TITLE
FontAwesome icons don't display in Editor

### ISSUE THREAD

**Issue by cory-skeers** [uiowa/uiowa#383]
***Problem
FontAwesome icons used in WYSIWYG fields don't display in the editor. 

They render, appear on edit pages when the field editor hasn't been opened, and in the Source view for the field.

***Note
Might be an issue with how the iframe is rendered.

**Comment by joewhitsitt** [comment]
Is this because the fontawesome library (css/js) isn't being loaded in the admin theme?

**Comment by cory-skeers** [comment]
fontawesome-span branch partially solves this.
Currently:
Icons correctly appear in the editor if you
- save the page while the text field is open, either as editor or source
- Source is in focus while collapsing the paragraph
But, if the regular text field is in focus when you collapse a text field, the icon will disappear. The <span> tags get commented out (and can be uncommented to make the icon appear again). 

I think there's a conflict with how Paragraphs handles its "Collapse" feature alongside CKEditor's content filtering, and plugin.es6.js::svgToTags isn't getting called, after tagsToSvg was called for the text field display.

**Comment by richardbporter** [comment]
#382
