### ISSUE TITLE
SSL - studentlegal.uiowa.edu on uiowa02

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#3831]

**Comment by richardbporter** [comment]
Related #3824. Not sure if that SAN exists in a cert but if so, it can be removed.

**Comment by joewhitsitt** [comment]
I think there is a wildcard for *.studentlife.uiowa.edu. @quamsta do you know of other sites that will be at *.studentlife.uiowa.edu in the near future?

**Comment by quamsta** [comment]
@joewhitsitt we have three more sites at *.studentlife.uiowa.edu that we may move over in the near(ish) future, but they're a bit further down our migration list:

slc.studentlife.uiowa.edu
awards.studentlife.uiowa.edu
sds.studentlife.uiowa.edu 

And one (a big intranet project website) that I'm not sure when we'll migrate:
connect.studentlife.uiowa.edu



although it may be a while before we get to those sites, they're not quite at the top of our list.

**Comment by joewhitsitt** [comment]
Okay. I think for now we should leave the wildcard cert for studentlife in there.

**Comment by joewhitsitt** [comment]
SSL is done.
