### ISSUE TITLE
Admissions print kiosk

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#3841]
Admissions would like a print kiosk so people who come in can choose to print the pdf's for whatever Areas of Study they are interested in rather than Admissions pre-printing lots of these.

# Additional Info
Some Intro text
List of Areas of Study with checkboxes to select one or more
Big print button
when click print, it just prints - no additional dialogues, can print multiple at once
not indexed
~possibly authenticate & go directly to page to select what to print~
Scott shared https://printjs.crabbly.com/ as a possibility to look at.

Hardware - will use CLAS kiosks - Microsoft Surface
Printer hardwired

Isaac P in ClAS is contact related to hardware

**Comment by bspeare** [comment]
These seem like possibly useful links/issues: 

**Bulk operations:**

Create a duplicate view of /areas-of-study/print-links and add node operations bulk field: https://www.drupal.org/docs/contributed-modules/entity-print/usage#s-create-your-own-view

**Issues with this method:**
- https://www.drupal.org/project/entity_print/issues/3168977
- https://www.drupal.org/project/entity_print/issues/3220313

**Comment by dnkemper** [comment]
@bspeare FOR THE WIN!

**Comment by dnkemper** [comment]
* Contacted Isaac about silent printing `--kiosk --kiosk-printing` in chrome. He said he will look into it further. Might need to test on one of their devices. There's an email in ITS-Web w/ more info
* There's an issue with pdf's running into each other when downloading multiple at a time
* Patch for [Render multiple entities separately and on separate pages](https://www.drupal.org/project/entity_print/issues/3168977) doesn't seem to be working :( - might have to manipulate multiple page issue w/ css

**Comment by dnkemper** [comment]
Question: Has anyone looked into the entity print views module? It adds a 'print' action

**Comment by bspeare** [comment]
@dnkemper Probably worth turning on and trying out, but the description doesn't sound like what we need: "With the Entity Print Views module enabled, a "Print" Global option can be added to the View's header or footer."

**Comment by dnkemper** [comment]
True. It also added a 'print' action to the bulk node operations bulk form? Need to resync site but might check it out after grooming?

**Comment by bspeare** [comment]
A few other considerations:

- Remove theme CSS so the page will not be impacted by theme changes (suggested by @pyrello)?
- Should we remove the header, nav, and footer so that this is just a table and print button?

**Comment by dnkemper** [comment]
I did remove the footer. By header do you mean the title? Or am I misunderstanding

**Comment by bspeare** [comment]
Sorry, I meant header and footer of the website, not the view :)

**Comment by dnkemper** [comment]
@bspeare so DEFINITELY misunderstood haha. Thank you for clarifying 🙈

**Comment by pyrello** [comment]
Just to be clear, I didn't meant that we should remove all theme CSS necessarily, but that we should consider removing anything that isn't strictly necessary to limit the chances that we unintentionally break the kiosk page with unrelated theme work.
