### ISSUE TITLE
Investigate: Publishing content in multiple languages

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#3867]
# Motivation
The WhitmanWeb (IWP) site contains a body of work by Walt Whitman which has been translated into multiple languages. The funding for this project requires that each translated version of each piece of content be accessible at a different URL. The funding has also paid for the content translation, so we do not need to rely on automated translation solutions for this.

Some investigation work was already done in #3506, but the conclusions from that issue will not work for what we need on WhitmanWeb.

## Examples
English: https://iwp.uiowa.edu/whitmanweb/en/writings/civil-war/week-1/the-million-dead
Arabic: https://iwp.uiowa.edu/whitmanweb/ar/writings/civil-war/week-1/the-million-dead

# Stories

* As a content editor for WhitmanWeb, I can publish pages with separate URLs for each translated version of a piece of content.
* As a visitor to WhitmanWeb, I can choose which language I want to view the site in.
* As a visitor to WhitmanWeb, I can navigate through a multiple page piece of content and stay in the same language the whole time.

# Proposed solution

Investigate how to meet the above story requirements. This may involve the following steps:
* Talk to @dnkemper regarding her work on #3506 to learn anything important there that applies here.
* Enable Language and Content translation modules for the WhitmanWeb to see if they work for this use case.
* Investigate options for language switching.
* Determine whether to use Symmetric or Asymmetric language translation with Layout Builder and bring a recommendation back to the team for discussion.
* Document process for adding/editing translated content.

**Comment by dnkemper** [comment]
Since they're wanting to handle multiple instances of the same content in different languages, the translation modules available in core should be able to do the trick for this issue. Especially since they're okay with publishing them at different URLs. Solid!

**Comment by dnkemper** [comment]
Asking @pyrello if I can take a stab at this. 😇

**Comment by pyrello** [comment]
@dnkemper Sounds good to me. I added an account for you on https://iwp.uiowa.edu/whitmanweb, case that is helpful. I'm available for any questions that come up. I have hopefully done a better job than some previous issues of writing this one up :)

**Comment by dnkemper** [comment]
@pyrello Haha hey now... I've learned a lot and am thankful for that 🤗 This seems greatly detailed and will work on keeping you posted. Thank you so much 🥳

**Comment by dnkemper** [comment]
@makurj and I are going to add screenshots to ask our questions. 

1. Do we want the menu to be translatable?
2. Does the user interface for editing need to be translatable?
3. Will there be other languages added later?
4. How are they planning on editing both versions once the paid translators are gone?
5. How they want the selector to be displayed?

Here is what the current page translation looks like when we select 'Arabic'

<img width="1400" alt="Screen Shot 2021-08-30 at 1 37 25 PM" src="https://user-images.githubusercontent.com/16872949/131388156-c7bea325-654b-44e4-b824-05d881093c45.png">

6. Do we leave Views alone? There are extra settings for "Rendering language" now:

![image](https://user-images.githubusercontent.com/52135878/131388929-38a0d120-79bf-4194-9830-ea9298618970.png)

7. Arabic = right to left. Messes up block Iowa (logo and site name)

<img width="650" alt="Screen Shot 2021-08-30 at 2 00 36 PM" src="https://user-images.githubusercontent.com/16872949/131390910-afc4c015-134f-4b49-8428-c4291e9410f4.png">

**Comment by pyrello** [comment]
1. Yes, the menu needs to be translatable.
2. The editing UI does not need to be translatable.
3. Yes. Currently a language is being added and another one is planned sometime in the next year.
4. I'm not sure I understand this question. The translators will only be providing translations. The content editors for the site will be responsible for actually entering and maintaining content over time.
5. I'm not sure I understand this question. Are you talking about a language selector? They are not determining how it needs to be displayed. Instead, we need to figure out the best option(s) and if there are multiple ways we can do it, then we can present those as options if we are not sure how to proceed based on our own best judgment.
6. I'm not sure how views would be relevant to the WhitmanWeb site. If you have a specific example in mind, please elaborate.
7. I'm pretty sure that we only want translated content on the site to display RTL. That would include the menu and actual content areas. I'd invite @bspeare to weigh in on this as well.

As a side note, this is the future site where this work will be happening: https://whitmanweb.iwp.uiowa.edu/

**Comment by makurj** [comment]
Findings from today:
1. Any new language that's added to the Languages module will need to be added to the config split.
2. A new language's URL will need to be set.
3. Settings for Content translation module...
[Content language _ WhitmanWeb.pdf](https://github.com/uiowa/uiowa/files/7094051/Content.language._.WhitmanWeb.pdf)
[Languages - Detection and selection _ WhitmanWeb.pdf](https://github.com/uiowa/uiowa/files/7093992/Languages.-.Detection.and.selection._.WhitmanWeb.pdf)
4. Sitename style needs to be fixed when in Arabic. It's getting hidden behind IOWA.
5. **_NEED HELP_**: Which LB content blocks should be enabled with translation, if any? Will Paragraphs' editing interface suffice?
6. Layout option is not available on Arabic pages. Cards added in LB on the English page are visible on Arabic but continue to be in English. So no matter, which language we select on the card block on the English page, it doesn't make a difference.
7. Menus are now translating: this has to be done manually per menu item (https://www.drupal.org/docs/multilingual-guide/menu-translation-in-drupal-8) See example: 
<img width="1365" alt="Screen Shot 2021-09-01 at 3 27 32 PM" src="https://user-images.githubusercontent.com/52135878/131740718-c36a61e0-a099-4c5c-82c0-fcc9b8cc5b52.png">

**Comment by makurj** [comment]
8. **_NEED HELP_**: 
There are way too many files listed for config changes when trying to export, even for content blocks we've chosen not to translate in the module settings. View display of media is being changed, entity form display, etc. 
[Synchronize _ WhitmanWeb.pdf](https://github.com/uiowa/uiowa/files/7094380/Synchronize._.WhitmanWeb.pdf)
Here are the config settings:
[Edit Whitman IWP _ WhitmanWeb.pdf](https://github.com/uiowa/uiowa/files/7094382/Edit.Whitman.IWP._.WhitmanWeb.pdf)

**Comment by joewhitsitt** [comment]
>NEED HELP

If this functionality is changing for whitman web and it isn't supposed to be in the default config, then you need to add all of these to the site split and export.

**Comment by dnkemper** [comment]
> > NEED HELP
> 
> If this functionality is changing for whitman web and it isn't supposed to be in the default config, then you need to add all of these to the site split and export.

woof. 157 files 😅. Thank you, @joewhitsitt

**Comment by pyrello** [comment]
Not necessarily. If there are common patterns for config files that get added en masse, then those can be done with wildcards.

However, we were planning on having a discussion to figure out to what degree we might want to bake this into the platform. Are there any other sites where we need translations? If so, then this should become a feature split. Based on how many files are involved, I definitely think we should split it as few times as possible. Let's wait until after the discussion to decide where to put all this.

**Comment by joewhitsitt** [comment]
>Not necessarily. If there are common patterns for config files that get added en masse, then those can be done with wildcards.

Sorry, yes, I assumed the config split documentation would be followed. https://github.com/uiowa/uiowa/blob/main/config/README.md

**Comment by dnkemper** [comment]
We just assumed it was weird that things we didn't want to touch were still getting changed 🤷🏼‍♀️

**Comment by makurj** [comment]
Considering closed for now.
