### ISSUE TITLE
WhitmanWeb - Add writing content type with translation enabled

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#3868]
# Motivation

As a follow-up to #3867, we need to actually implement the recommendations that come out of that investigation.

# Stories

* As a content editor for WhitmanWeb, I can publish pages with separate URLs for each translated version of a piece of content.
* As a content editor, I can group pieces of writing together in a collection and control the order in which they display.
* As a visitor to WhitmanWeb, I can choose which language I want to view the site in.

# Proposed solution
* [x] Add site split.
* [x] Enable content translation and language switching modules for the site and add to the site split.
* [x] Place language switching UI and add block changes to site split.
* [x] Add Writing content type (see definition below)
* [x] Document process for adding/editing translated content.
* [ ] Add writing collection either using taxonomy or a separate content type.
* [ ] Figure out how to handle translating field labels.
* [ ] Add translations for all field labels.

## Writing content type definition
- [x] Title - built-in
- [x] Featured Image - use existing field
- [x] Featured Audio - multi-value media field restricted to audio media type
- [x] Foreword - text area (minimal)
- [x] Content - multi-value text area (minimal)
- [x] Afterword - text area (minimal)
- [x] Question - text area (minimal)

Note: for now we are not adding fields for Section Number and Category, or the Previous and Next buttons, as the menu should cover it. They may need to be added down the road if the menu isn't sufficient.

**Comment by e-marie-w** [comment]
### Most recent list above under Content Type Definition ###
Components needed for new content type that combines the Stanza and Writings content type:
- Title - text field
- Language selection  - was drop-down previously
- Section Number (replaces Stanza Number & Week Number) - was drop-down previously
- Image - file upload
- Foreword - text area
- Body - multi-value text area
- Afterword - text area
- Question - text area

Questions about other previously-used fields that may or may not be needed:
-  Category - do we need a way mark which module the content belongs to, with a way to add more categories should they develop more modules?

**Comment by pyrello** [comment]
I think we are going to need to have a way to group together the different parts of a piece of writing that does not depend on the menu system. My initial thought is that each piece of writing could be created as a taxonomy term in a vocabulary called Writing.

**Comment by pyrello** [comment]
I just updated the IS to include a story that had become part of the work in #4643 but was not reflected here: _As a content editor, I can group pieces of writing together in a collection and control the order in which they display._

When I originally put this together, taxonomy seemed like the obvious option to use as a collection for pieces of writing. The taxonomy entity is field-able, so extra things can be added to it to store information about the collection. It provides a list of content that is tagged with the term out of the box.

However, the one piece I had not really worked on before is ordering the content. Thinking about a book as a collection of writing, you would potentially have it sectioned by chapter. Without the ability to put the chapters in the correct order, the collection is missing something important. I've been trying to think about how to do this with taxonomy, but the best I'm coming up with is adding a weight field to the writing content type and then creating a specialized view to allow setting the weight of the items within the taxonomy term with that.

Another way to handle this would be with another content type. A collection content type could have a multi-value reference field to add pieces of writing which would allow order them. A content entity can effectively be made to function similarly to a taxonomy. However, the workflow here would suffer. It makes the most sense to define the collection in the context of the piece of writing: You add a piece of writing and set a connection to existing collection or create one on the fly as you do that. Creating the writing, then adding it to a collection is a bit clunky. I'm not sure if there would be a way to reference the collection node when generating the URL from a piece of writing.

If we reverse the direction of the entity reference, to go from Writing => Collection, then we run into the same issue as with taxonomy. We have to come up with some way of ordering the content.

Open to ideas on how to get this done.

**Comment by joewhitsitt** [comment]
Before reading your comment, it sounded like weight module (Admissions already has it). The multi-value method does sound painful for more than a couple items. As I read on, it started to sound like, dare I say it, the Book module (policy.clas already has it).

**Comment by quamsta** [comment]
@pyrello 

Couple of approaches we've considered and actually used for this sort of collection/publication containing multiple pieces:

1. Is using Drupal's menu system an option for ordering pieces of writing "under" a collection page hierarchically? In our old SilverStripe system, for publications we'd just put pages under other pages in the order we'd like to see them. Screenshot below: 
<img width="294" alt="Screen Shot 2022-07-07 at 8 51 36 AM" src="https://user-images.githubusercontent.com/472923/177790186-b6fed644-6d4d-45a3-933f-2b82d37b3e30.png">

Drupal's equivalent is manipulating the menu system, but I'm not sure how flexible this is/how well it lends to creating paths to the next/previous chapters from a piece of writing.

2. For the Journal of Corporation Law, we took a more "flat" approach and just made a table of contents in Layout Builder and linked to each article in their proper order by adding cards:

https://jcl.law.uiowa.edu/

In the case of something like a book where you'd need to move to the next chapter from a piece of writing, manual links to the next chapter would have to be placed.

This is a bit laborious, but lends well to just using the tools at hand

**Comment by pyrello** [comment]
> Before reading your comment, it sounded like weight module (Admissions already has it). The multi-value method does sound painful for more than a couple items. As I read on, it started to sound like, dare I say it, the Book module (policy.clas already has it).

_tl;dr: The book module is showing its age and makes for a clunky UI for managing the relationship I'm trying to create._

@joewhitsitt Your comment piqued my curiosity. At first I was thinking that the book module would probably be getting moved to contrib soon (like what's happening with the [aggregator](https://www.drupal.org/project/aggregator) and [forum](https://www.drupal.org/project/forum) modules), but I couldn't find any evidence of that being the case. Indeed there does seem to be movement on book module issues in core for current and future versions: https://www.drupal.org/project/issues/drupal?component=book.module. I'll need to peruse these a bit more carefully, as what patches are available may inform my thinking about it.

I enabled the module on my local version of WhitmanWeb to try out the setup. Here are my observations:
- The included "Book page" content type is not something that I am interested in. In the past, the naming of this content type has proved very confusing to site editors who didn't know what the difference between the page and the book page was and therefore created both.
- Fortunately, it is possible to add book features to your own content type.
- Where things get a little weird and this possibly stops making as much sense is that I would like to have 2 types of content that interact to create a collection. The collection itself, and the piece of writing that makes up the collection. The settings don't really have a way to set up this connection:
  ![Screen Shot 2022-07-07 at 1 44 16 PM](https://user-images.githubusercontent.com/709009/177846507-f6ddb594-e730-45af-8870-b68fc4eaf8e9.png)
- Speaking of the settings, wouldn't you think that the settings above should prevent me from doing this? They don't.
  ![Screen Shot 2022-07-07 at 1 46 15 PM](https://user-images.githubusercontent.com/709009/177847625-b7564e2f-fa3e-4c5e-8fb8-fe2ac7f695fd.png)
- That outline tab is not horrible, but a little bit clunky in terms of setting up the outline content order.
- The book module also allows for setting up multiple levels of nesting, which isn't what we want here. We could instruct the user how to use it, but it introduces the very easy possibility of accidentally selecting the wrong parent item.
- The book module does not seem to have caught up to the Layout Builder era at all: The book navigation block help text is geared towards using the original block system and the "Back", "up", and "Forward" links are actually appended not using a block after all the content.

**Comment by joewhitsitt** [comment]
Here is the book -> contrib issue: https://www.drupal.org/project/ideas/issues/3265493

In D7, I recall doing some adjustments and applying a patch to get it to work better. I can try to dig that up to see how it relates to your comments

Update: We were doing all kinds of modifications for teach.its

- https://www.drupal.org/node/502430 - Allow the book outline functionality on non-book-enabled node types to be hidden from users with the "Administer book outlines" permission
- Forced a particular content type as an automatic book
- Changed path if it wasn't a top-level page

**Comment by pyrello** [comment]
> Is using Drupal's menu system an option for ordering pieces of writing "under" a collection page hierarchically?

@quamsta This definitely seems like a possibility, although I need to play with it a bit to see how it would work. 

> Drupal's equivalent is manipulating the menu system, but I'm not sure how flexible this is/how well it lends to creating paths to the next/previous chapters from a piece of writing.

We could potentially grab the menu entity and use the ordering that is built into it to get previous and next items, so that is potentially workable.

> For the Journal of Corporation Law, we took a more "flat" approach and just made a table of contents in Layout Builder and linked to each article in their proper order by adding cards

The site is question is one that I hope for the owners of it to be able to update on their own, so this type of approach would probably not work well, since it requires a high degree of understanding how to use Layout Builder and an eye for being consistent that are probably not going to be in the cards with this particular customer.

**Comment by pyrello** [comment]
@joewhitsitt Thanks for adding your comments about this. It seems like, if there was a way to disable the nesting functionality for a book tree, that this might be workable.

Adding this here to look at later: https://www.drupal.org/project/entity_hierarchy

**Comment by pyrello** [comment]
I was trying to figure out how to resolve a different issue that was raised as part of the review of this: Translating field labels. It looks like this is handled by turning on the `config_translation` module. When I attempted to do this, I ran into uiowa/uiowa_auth#1

**Comment by pyrello** [comment]
On Friday, I started looking into the Entity Hierarchy module. The base module by itself just provides the mechanism for linking the parent and child items. What I immediately like about this over the book module is the ability to associate two different content types as parent and child. With the book module, every element is a book page. My preference for these writing collections is to have a parent content type (Writing Collection) and separate individual child items (Writing).

Here is a screenshot of the "Children" tab that gets added to the parent content type:
![Screen Shot 2022-08-22 at 8 59 25 AM](https://user-images.githubusercontent.com/709009/185941092-200fc594-b933-4b24-8ac3-5f4a2130242f.png)

There are two submodules that enhance the functionality of the base module:
- EH Breadcrumb - Makes these work as would be expected.
- EH Microsites - I believe this allows creating a "section" for the site that has its own menu that gets generated. Overall this seems to work pretty well, but is a little clunky because you have to create the "microsite" separately than the "homepage" for it. This provides a block which can be placed on the content type via LB template.

This is a quick example of what an article in the collection might look like (using 91st Meridian as an example):
![Screen Shot 2022-08-22 at 9 26 55 AM](https://user-images.githubusercontent.com/709009/185946044-09c027b6-ddf4-4ba4-8daa-3da2c9d7c5ef.png)

**Comment by bspeare** [comment]
Closing as WhitmanWeb is launching without custom development.
