### ISSUE TITLE
Engineering media metadata

### ISSUE THREAD

**Issue by cory-skeers** [uiowa/uiowa#3870]
# Story

As a content editor for engineering.uiowa.edu, I would like my previously migrated media content to have its D7 metadata and/or other unique metadata so that I can easily find my content, and have accessible alt text readily available for site visitors.

# Proposed solution

Check that affected media is easily findable in the D8 database by either null values in title/alt or default values ("title" and "alt"). Find a way to update these entries using the D7 database (likely by matching filenames), or at least update the titles to something reasonable like filename minus extension.

**Comment by richardbporter** [comment]
Looks like sitenow_migrate was already turned off in prod. Turning it back on locally does not get `drush ms` working.

**Comment by richardbporter** [comment]
Scratch that: it does work but all migrations are marked as unprocessed which is unfortunate. I thought rolling back might be the best approach.
