### ISSUE TITLE
Cache clear required after SiteNow Migrate config form save

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#3871]
# Problem
In running the CS custom migration script with @pyrello and @cory-skeers, I had originally put in the incorrect database name into that field:
![screen_shot_cs](https://user-images.githubusercontent.com/3067017/127183803-08c418a4-faa9-4654-b91e-4165e7686c64.jpg)
When I made the correction, saved the form, and ran another `drush @cs.prod ms`, the database name was still the previous incorrect name:
![Screen Shot 2021-07-27 at 10 33 57 AM](https://user-images.githubusercontent.com/3067017/127184266-c983c5f2-3e04-4e56-bf80-c6c819614dd8.png)

# Steps to reproduce
Pull a site with a custom migration setup (CS, Physics, etc).
Enter an incorrect field value in one of the SiteNow Migration config setting fields.
Save the form.
Run `drush @cs.local ms`. This should fail.
Enter the correct field value in the config settings field above.
Rerun `drush @cs.local ms`. This should fail as well, and show that the field value was still cached.
Run `drush @cs.local cr`. This will fix the problem on next drush ms.

# Proposed solution
Add an automatic cache clear upon form save to SiteNow Migrate form.

**Comment by pyrello** [comment]
I wouldn't consider this a bug, but rather a feature request.
