### ISSUE TITLE
SSL Cert - www.dentistry.uiowa.edu on uiowa

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#3873]
launching Aug. 17th

**Comment by richardbporter** [comment]
The uiowa cert already has both *.dentistry.uiowa.edu and dentistry.uiowa.edu SANs so this should be good to go.

**Comment by briand44** [comment]
Thanks for verifying that. So why would we ever add a www domain to our SAN?

**Comment by richardbporter** [comment]
I'm not sure, I'd have to look into that. Its probably safer to only cover www and not all subdomains if that isn't required.
