### ISSUE TITLE
Launch tutor site

### ISSUE THREAD

**Issue by mjoneill** [uiowa/uiowa#3885]
Partner is hoping to launch tutor.prod.drupal.uiowa.edu on Friday (07/6/2021) morning (or move launch date to the following Monday.

The following has to happen.

**Pre-launch Support**
- [x] Help establish if the partner currently has Google Analytics on tutor.uiowa.edu.  I see this ID on some of the pages: UA-426753-42
- [x] Help partner access their existing Google Analytics for tutor.uiowa.edu
- [x] Add Google Analytics to their new site (should be the same GA that's currently in use)
- [x] Introduce Stephanie to Alex
- [x] Brief Alex on this launch
- [x] Run a screaming frog crawl and get Stephanie a list of all known pages on the currently live site (tutor.uiowa.edu) so she can plan redirect strategy prior to going live
- [x] Identifying broken links with Screaming Frog
- [x] identifying links to prod/stage/dev with Screaming Frog
- [x] identifying links to test application (tutor-resources-test.its.uiowa.edu) with Screaming Frog
- [x] identifying missing meta descriptions with Screaming Frog 
- [x] identifying typos and spelling errors with Screaming Frog

**Launch Day Support**
 On launch day assist our partner with:
- [x] Identifying broken links with Screaming Frog
- [x] identifying links to prod/stage/dev with Screaming Frog
- [x] identifying links to test application (tutor-resources-test.its.uiowa.edu) with Screaming Frog
- [x] identifying missing meta descriptions with Screaming Frog 
- [x] identifying typos and spelling errors with Screaming Frog
- [x] submitting sitemap via Google Search Console
- [x] verifying 404/403s are visible in Google Analytics (and showing partner how to see those)
- [x] verify content/pages are not blocked by robots.txt

**Technical Launch tasks**
- [x] Lower TTL
- [x] move site from stage to prod environment
- [x] create tutor.uiowa.edu in Acquia Cloud on uiowa02
- [x] Cover in SSL 
- [x] Have Hostmaster update DNS
- [x] Remove internal prod domain
- [ ] Have Student Life Comm (Dustin) deactivate and archive old site (may want to wait a day or two)
- [x] Tell Hostmaster to return TTL to default (may want to wait a day or two)

**Comment by mjoneill** [comment]
tagging @briand44 and @ABoston88 on this

**Comment by briand44** [comment]
Thanks Michael, I have added the technical launch tasks as well.

**Comment by mjoneill** [comment]
Tutor group has forwarded their GA account info to me.  This should clear impediments to getting them set up.

**Comment by mjoneill** [comment]
Can someone turn on Google Tag Manager capability for tutor.prod.drupal.uiowa.edu?

**Comment by mjoneill** [comment]
@briand44 do you have any examples of links to the dev side of the actual tutor application?

**Comment by cory-skeers** [comment]
@mjoneill I got GTM turned on.

**Comment by mjoneill** [comment]
I was able to wire up GA and GTM to the tutor.prod.drupal.uiowa.edu site & verify that analytics were streaming through. I have NOT created goals or set up event tracking for specific link clicks on the site (yet).

**Comment by mjoneill** [comment]
> @briand44 do you have any examples of links to the dev side of the actual tutor application?

Brian, got it by being a better reader above: tutor-resources-test.its.uiowa.edu

**Comment by mjoneill** [comment]
I only found one link to tutor-resources-test.its.uiowa.edu. It's on the Search for Help button of the front page.

I've sent a note to the partner.   

<img width="1180" alt="image" src="https://user-images.githubusercontent.com/7144234/127931500-0edc1409-c653-4309-b308-51a2d56f5ba5.png">

Also attaching the report results (showing one entry).  A little suspicious that there's only 1 link found...

[custom_search_tutor_test_application_links_(contains).csv](https://github.com/uiowa/uiowa/files/6919923/custom_search_tutor_test_application_links_.contains.csv)

**Comment by mjoneill** [comment]
Attaching a SF report for pages containing "drupal.prod".  @ABoston88 or @cory-skeers, can you take a look at this and see if it's noise or useful?  Share what's necessary with our partner if there are things that she should fix proactively.

[custom_search_prod_drupal_(contains).csv](https://github.com/uiowa/uiowa/files/6919931/custom_search_prod_drupal_.contains.csv)

**Comment by mjoneill** [comment]
I sent the following broken links report to partner.  Capturing here in case there are questions...

[client_error_(4xx)_inlinks.csv](https://github.com/uiowa/uiowa/files/6919948/client_error_.4xx._inlinks.csv)
[no_response_inlinks.csv](https://github.com/uiowa/uiowa/files/6919949/no_response_inlinks.csv)

**Comment by mjoneill** [comment]
I sent the attached spelling error report to our partner.

[spelling_and_grammar_errors.csv](https://github.com/uiowa/uiowa/files/6919959/spelling_and_grammar_errors.csv)

**Comment by mjoneill** [comment]
Screaming Frog identified no missing meta descriptions.  Did not evaluate existing Metas for quality, etc...

serp_summary_metadescriptions

**Comment by mjoneill** [comment]
Checked robots.txt.  Seems to have not been updated. Reading:

> User-agent: *
> Disallow: /

Will make visible in parking lot
