### ISSUE TITLE
People page table is not full-width when used as a simple list

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#3898]
# Problem
People page table is not full-width when used as a simple list with name, title, and image. 

# Steps to reproduce
https://pharmacyuip.prod.drupal.uiowa.edu/leadership-team

# Proposed solution
- Remove https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/scss/views/view-display-id-people.scss#L38,

**Comment by bspeare** [comment]
This is now less of an issue now that the image alignment has shifted to the left as the default: https://uip.pharmacy.uiowa.edu/leadership-team.

**Comment by briand44** [comment]
Closing based on Ben's comment.
