### ISSUE TITLE
Migrate news articles for College of Education

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#3899]
Will get more details when we get closer to tackling this.

## Proposed solution

- Migrate all existing articles.
- Maintain published/unpublished status
- Tags, Affiliations are migrated to Tags. (Might have a list of consolidation for us to map)
- Source Title -> Organization
- Source Link -> Source Link
- Image -> Featured Image (site-wide default)
- Caption -> stripped and truncated to caption
- Body summary -> field_teaser
- Byline -> Prepend to body
- Short Description -> Prepend to body (uids-component--light-intro)
- body -> body (convert btn-primary to bttn bttn--caps bttn--primary, pull-quote to blockquote)
- Create redirects from old articles.
- Provide initial list of potential broken links.

### No action
- Image Gallery
- Header type
- Header image/video

**Comment by briand44** [comment]
Sounds like they likely will want us to run the migration in production for the new site once they have a chance to review and sign off. They don't want to wait until close to launch because they want the extra time to make any updates needed and they don't have a lot of new articles being created.

**Comment by briand44** [comment]
We will also want to double check title/alt and any other new changes to the migration scripts as part of this.

**Comment by richardbporter** [comment]
We will try to convert the body classes to their UIDS equivalent.
