### ISSUE TITLE
People in listings with multiple titles don't show titles on separate lines or with commas

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#3908]
# Problem
People in listings with multiple titles don't show titles one separate lines or with commas.

# Steps to reproduce
See https://law.uiowa.edu/faculty-and-scholarship/meet-our-faculty

# Proposed solution
Adjust people card template to display multiple titles using new lines. Notify laura-kivlighan@uiowa.edu when this is fixed.

**Comment by joewhitsitt** [comment]
Reopening. https://github.com/uiowa/uiowa/pull/4286 caused a regression related to this. College of Law reports that they are comma separated again.
