### ISSUE TITLE
Add `click-target` to admissions counselors and student profiles views

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#3923]
# Problem
After the work in https://github.com/uiowa/uids/pull/552, the admissions and counselor views are not entirely clickable because they don't have the `click-target` class on the `<a>`. 

# Steps to reproduce
Try clicking on an image at https://admissions.uiowa.edu/counselors. 

# Proposed solution
- Update view title `<a>` to have the the `click-target` class.
- Review other views on grad college and check if there are any views that need updating.

**Comment by makurj** [comment]
For my dev sprint.
