### ISSUE TITLE
SiteNow Updates News Article - August and September

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#3929]
## Issue/Solution

Provide a "release notes" type article of finished/done features/updates and publish to website, then send out dispatch email.

- [x] Create draft and update the parking lot card with an edit link
- [x] Add "release notes" covering the month of v2/v3 default profile enhancements and webmaster/edit visible bug fixes.
  - See the previous month's article as an example.
  - Bullet points from demo stories slide per week: https://drive.google.com/drive/folders/1EehKUjxCbakaB9FchrGhAbaxuRbqyDGW?usp=sharing..
  - Check recent "done" and "archive" items and finished docs tasks.
  - Take notes during sprint demo presentation.
- [x] Get at least one team member to look over the draft before publishing.
- [x] Since the draft was started earlier, adjust the publish date/time, publish, get the link to the article.
- [x] Dispatch email with link to article. (To get access, send an email to dispatch-support@uiowa.edu to have the account provisioned. Provide your hawkid and mention the CSI:drupal group)
  - Modify SiteNow Announcements Template (tweak opening line, update the article link, any other editorial adjustments)
  - Create new communication off SiteNow Announcements campaign
    - Use SiteNow Announcements population, template, suppression list, bypass approval.
    - When scheduling, check the "archive" option so that there is an RSS instance we can use in the future. I don't think this can be done after the fact.
- [x] Create the next months's issue and copy all this bullet list into it, removing the checked boxes if any.

**Comment by bspeare** [comment]
https://sitenow.uiowa.edu/news/2021/08/updates-august

**Comment by richardbporter** [comment]
Our monthly articles would be easier if we had: As a SIteNow v3 user creating an article, I can choose to send a corresponding Dispatch communication.

**Comment by richardbporter** [comment]
https://github.com/uiowa/uiowa/issues/4084

**Comment by bspeare** [comment]
Some Dispatch analytics for the past 3 articles:

<img width="1308" alt="Screen Shot 2021-09-14 at 1 27 39 PM" src="https://user-images.githubusercontent.com/1036433/133313793-ccec2135-6ca6-489f-b182-31f2b09cffd7.png">
<img width="1338" alt="Screen Shot 2021-09-14 at 1 28 04 PM" src="https://user-images.githubusercontent.com/1036433/133313795-3d6e1120-4062-49e3-9193-b6181a602cb2.png">
<img width="1329" alt="Screen Shot 2021-09-14 at 1 28 44 PM" src="https://user-images.githubusercontent.com/1036433/133313798-71b66e4f-c2d1-41da-9200-243aab59f902.png">

**Comment by briand44** [comment]
Combine August and September news article. Try and provide more text explanation on slide deck to easier translate to news article.

**Comment by briand44** [comment]
Continue monthly going forward

**Comment by e-marie-w** [comment]
Since we only include enhancements/bug fixes for the default site profile, I'm skipping stuff like migrations and site-specific features, like the pharmacy map, admissions event series, or the concept3d map stuff. I'm also skipping any investigations like the snowplow analytics stuff and the privacy acknowledgment pop-up. (Let me know if any of that should actually be included.)

I'm a little confused about some of the new features that aren't site-specific but also not turned on by default, like Areas of Study or the Topic Collection content type from Student Life. Should these be mentioned or not? Also, are the timeline and graph blocks turned on by default, or is it like AoS where it has to be requested?

**Comment by joewhitsitt** [comment]
We have included "feature splits" in the past articles. So I think AoS, Topic, Graph can be included. Timeline is turned on for all.

**Comment by e-marie-w** [comment]
Oh awesome, that is a lot of cool work that is nice to make visible. Thank you @joewhitsitt!

**Comment by e-marie-w** [comment]
Draft ready for review/suggestions!

**Comment by joewhitsitt** [comment]
Update the article created date to today and it has my approval 👍 to publish and move on.

**Comment by e-marie-w** [comment]
Awesome, thanks @joewhitsitt! Published it and emailed Dispatch about getting access.

**Comment by e-marie-w** [comment]
Emails sent!
