### ISSUE TITLE
Implement remaining oEmbed providers

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#393]
### Problem
As a continuation of https://github.com/uiowa/uiowa/issues/101 and to reach feature parity, we need to provide the ability to place additional oEmbed objects in the WYSIWYG. We are currently using the remote video plugin to provide YouTube and Vimeo and there is a separate issue to extend it to offer Kalutra support (#254).

The remaining feature parity oEmbed endpoints are:

- [x] Facebook
- [x] Twitter
- [x] Instagram
- ~Soundcloud~

### Proposed Solution
We need to test the following contrib modules in terms of feature parity to see if their integration with media core is working. If so, we need to enable these and configure Media/Entity Browser to allow editors to place oEmbed objects from these sources in the WYSIWYG.

These three note that the 2.x version is supposed to work with Media core:
https://www.drupal.org/project/media_entity_twitter
https://www.drupal.org/project/media_entity_instagram
https://www.drupal.org/project/media_entity_facebook

There is a 2.x stable, but no note on the project page about media core support.
https://www.drupal.org/project/media_entity_soundcloud

### Test
A user armed with oEmbed compatible URLs from these sources should be able to paste in the link to embed the object into the WYSIWYG. There should be some visual indicator for the object in the WYSIWYG if a working version is not possible. On save/render the object should load and allow the user to interact (play, scroll, view) whatever content is provided.

As these objects are saved as media entity, a user should be able to add an existing object from the media library as well.

Further testing should be done to make sure that this does not break other embeds/content in the same WYSIWYG area (both in the editor and on render).

**Comment by joewhitsitt** [comment]
I thought I would get this started, but if anyone else wants to pick it up from here I won't stop them.

Some notes, it appears the Twitter implementation can only do single tweets, so to meet feature parity, we may need to provide a twitter widget.

I also don't love how each provider is a separate tab in the entity browser, but unless we write our own mashup like remote video using `hook_media_source_info_alter()` i think this is the way it is. Thunder makes each provider a separate paragraph type which would be another approach.

**Comment by joewhitsitt** [comment]
I did a query of SoundCloud use on our D7 sites. One one site has used it in production for a total of two embeds. Offline, we are currently exploring offering audio file uploads in D8, I suggest moving forward with that and dropping support for SoundCloud (one less tab in entity browser).

**Comment by joewhitsitt** [comment]
added facebook support a6974f84b96075ab3149aebc1acb01ec45a63e98

**Comment by joewhitsitt** [comment]
Folks are okay dropping support for SoundCloud and moving forward with core's audio media type #413 .

**Comment by dnkemper** [comment]
**Testing**

**Comment by GaryRidgway** [comment]
Me and @dnkemper have talked about this a bit and we have nailed down how to do it and some documentation and ideas that we want to get done. I will make this list but I have some other things to work on so I will just state them and then Danielle will be taking action on them.

-icon is missing for media embed.
-there is no help text.
-the way to embed things is confusing and needs documentation.
-posts are mostly very thin so it would be useful to convey to users how to align the posts around text. I am currently unaware of how to do this and it should be documented.

**Comment by dnkemper** [comment]
Facebook

1. Make sure post is public
2. If you’re on your timeline, find the post you would like to embed

3. **THERE ARE THREE DIFFERENT WAYS TO DO STEP 3** 
    1. In the top left hand corner of the post, right click the date (or # of days/minutes) of the post you would like to embed and select ‘Copy Link Address’
    2. If post has an image, click on the image of the post to see the full view and copy the URL 
    3. If post does not have an image, click the three little dots in right hand corner of the post
       1. Select ‘Show in tab’
       2. In the popup window, click the settings icon in the top right corner and select ‘See full post’
       3. Copy URL of the full post
4. In Drupal, on the WYSIWYG, click the media icon in the toolbar
5. In the header of the popup window, select ‘Facebook’ 
6. Paste the URL you copied from Facebook in the Facebook* text box
7. Save
8. Note: while in the editing view of your node, you will only see ‘Posted by: Name on Date’

Twitter

**Make sure account is **NOT** private
1. Click on the tweet you wish to embed for the full view
2. Copy URL of the single tweet
    1. Ex: https://twitter.com/temiAlchemy/status/1150835103163133953
3. In Drupal, on the WYSIWYG, click the media icon in the toolbar
4. In the header of the popup window, select ‘Twitter’ 
5. Paste the URL you copied from Twitter in the Twitter URL* text box
6. Save

Instagram

**Make sure account is NOT private**
1. Click on the post you wish to embed
2. Click on the three dots in the upper right corner
3. Select ‘Copy Link’
    1. Ex:https://www.instagram.com/p/B0CI72fHXnd/
4. In Drupal, on the WYSIWYG, click the media icon in the toolbar
5. In the header of the popup window, select ‘Instagram’ 
6. Paste the URL you copied from Instagram in the Instagram* text box
7. Save

**Comment by dnkemper** [comment]
Some side notes: 

**Twitter Testing**
1. Tweet w/ no media = good
2. Tweet + picture = good
3. Tweet + video = good and plays on page without taking you to twitter
4. RT = good
5. RT + image = good
6. RT + video = good
7. When you RT + comment a tweet that contains a video [here](https://twitter.com/ayyeechristian/status/1151551656854581248?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1151551656854581248&ref_url=http%3A%2F%2Flocalhost%3A8888%2F), it takes you to twitter when you try to watch the video **BUT** if you embed the direct tweet that contains a video [here](https://twitter.com/temiAlchemy/status/1150835103163133953), without the RT + comment, it plays on your webpage & doesn’t redirect you to Twitter 

**Instagram Testing**
1. Post + image = good
2. Post + video = good **BUT** can't control video (can't go backwards in time or forwards) **AND** if you want to replay it, have to refresh page or go to Instagrams website ex: [here](https://www.instagram.com/p/By8ZKAQHNTM/?utm_source=ig_web_copy_link)
3. Post with multiple images = good
4. Post with multiple videos = good
5. Post with images + videos = good
Side note: If post deleted, Instagram still shows up with a "link to this photo or video may be broken, or the post may have been removed'

**Facebook testing**
1. Post w/ no media= good
2. Post w/ image = good
3. Post w/ video = good (can replay without it taking you to Facebook) BUT styling doesn't change size ex: [here](https://www.facebook.com/thesociallect/videos/400324737021243/)
4. Post w/ multiple images = not great. You get a collage of them instead of arrows to see the images one by one
         *when click on collage, it doesn't take you to fb post
         * ex: [here](https://www.facebook.com/DrupalCon/posts/2480684531998293?__xts__%5B0%5D=68.ARA9IwKKtwI4Xu8k357ONuha4lIlvWcBr8cGwuLExl1nBrEgpdJDLw6Q-X_h7fPEiP6nwyh_ECwADhnJEIMgwhSDzRz3kidKv_STZc-8l6i3qet7yl1KmYBJD87BXQv3e65Y4fbsUHf24O2KOjD-StgMkeqTCu4fD_orgAwoF8MnibdSvcd_WtGw5jYX9wmS0QuUfqnfIQrfjEfNv-LRKDEch7HDJ1wETuF4BIgpMcshGSkQiSIU9-k9spAIjN6X-cc7-kAtiQv1DGuIFVS6ouwlu8t-rHAoSgh1eUM3asjvxsCYUDMyez2u01lRZzHyFB9cQX43OcnSE8B33QluqFHbrA&__tn__=-R)
5. Post w/ images + videos = not great. You get a collage and can't play videos
        *When click on collage, it doesn't take you to fb post
        *ex: [here](https://www.facebook.com/danielle.kemper.1/posts/3767910674338)

**Comment by joewhitsitt** [comment]
> -icon is missing for media embed.
-there is no help text.
-the way to embed things is confusing and needs documentation.
-posts are mostly very thin so it would be useful to convey to users how to align the posts around text. I am currently unaware of how to do this and it should be documented.

- embed icon is a local issue related to rsync and default_content
- we didn't provide help text in the standard site because providers could easily change their oembed support.
- we should definitely follow up with documentation similar to https://its.uiowa.edu/support/article/110816 (without screenshots)
  - i think the recommendation should be to use the media align center and the paragraph column width setting to wrangle embeds.
  - twitter only allows tweets, facebook allows post/video, instagram is a post.
- i believe i have fixed/consolidated the styles as best we can (facebook does some weird calculating, and they all have different max-widths which can change and affect things)
- We can't control what elements of an embed are interactive/click out etc.
