### ISSUE TITLE
Remove/Disable EMS widget from Signage

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#3934]
We were told that the EMS service isn't being used anymore so we can remove that widget from Signage.

If we are going to remove, we should check to see if it is placed on any signs.

**Comment by joewhitsitt** [comment]
I can easily disable as part of this work: https://github.com/uiowa/uiowa/issues/3933

**Comment by joewhitsitt** [comment]
This is on the signage application `signage-outlook` for review. It doesn't impact existing widgets, just prevents new ones from being added.

**Comment by joewhitsitt** [comment]
This was done a while ago and then re-done by @richardbporter later on.
