### ISSUE TITLE
Move Careers staging site to prod environment

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#3936]
The Career Center has a v2 site at https://careers.prod.drupal.uiowa.edu that they are no longer using.

Let's move their v3 site https://careers.stage.drupal.uiowa.edu to the prod environment using the internal prod domain (https://careers.prod.drupal.uiowa.edu) so the launch process will be simpler.

We need to communicate with them on the timing of this so they are not working on content while we are in the process of syncing. Dana Dominguez and Drake Wilbur are contacts.

**Comment by bspeare** [comment]
I emailed Dana and Drake on Friday and I am waiting to hear back from them.

**Comment by joewhitsitt** [comment]
This is done. https://careers.prod.drupal.uiowa.edu/

Also, removed stage domain to reduce confusion.
