### ISSUE TITLE
enable uiowa profiles for Dentistry

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#3937]
Enable Uiowa Profiles module for Dentistry so that they can display people from directory profiles prior to launch.

**Comment by richardbporter** [comment]
To do this, the config split needs to be enabled and then config needs to be imported. That's it.

**Comment by richardbporter** [comment]
Profiles split is missing perms. Updating...

**Comment by richardbporter** [comment]
Done https://dentistry.prod.drupal.uiowa.edu/admin/config/system/uiowa-profiles
