### ISSUE TITLE
Add privacy notice popup on uiowa.edu

### ISSUE THREAD

**Issue by mjoneill** [uiowa/uiowa#3943]
Because I expect a reputable brand to be upfront about how they respect my privacy as a web visitor, I expect a notice on first visit to any page on the uiowa.edu website

### Examples
The notice appears on first visit, requires acknowledgement to clear, & sets a cookie, and does not appear again unless: 
- the Privacy page content changes
- 1 year has passed? 

### Future
In the future, will likely extend this first to admissions, then to other primary colleges, etc...
This may preface future options that include specific cookie enumeration and consent, etc...
We may consider vended solutions like OneTrust, etc...

**Comment by dnkemper** [comment]
SQUATTING. DIBS. ME. MOI. PLEASE.

**Comment by makurj** [comment]
I would love to pair on this. Tippie D7 has something similar.

**Comment by joewhitsitt** [comment]
quite a few contrib projects for this that might be worth looking at before creating a homegrown solution. there have been discussions in edudu and highedweb slack about what folks are doing for this.

**Comment by dnkemper** [comment]
https://www.drupal.org/project/eu_cookie_compliance

**Comment by bspeare** [comment]
It would be great to showcase and get feedback on the design of https://github.com/uiowa/uiowa/pull/4107 at the next design meeting on 10/6 with the brand team.

**Comment by dnkemper** [comment]
@bspeare That makes me happy and hesitantly optimistic. Sounds like a plan to me 🥳

**Comment by joewhitsitt** [comment]
Does this and #4107 close too based on https://github.com/uiowa/uiowa/issues/5446#issuecomment-1505539415

**Comment by joewhitsitt** [comment]
Closing in favor of https://github.com/uiowa/uiowa/issues/6490
