### ISSUE TITLE
Grant awards story intake form

### ISSUE THREAD

**Issue by cory-skeers** [uiowa/uiowa#3944]
As an Iowa Now content curator, I want a custom webform to help make it easier to maintain more frequent grant award stories in order to support internal faculty pride (and help support faculty recruitment efforts).

Grant award stories end up here: https://now.uiowa.edu/achievements
Some stories are more detailed (https://now.uiowa.edu/2021/07/physicist-wins-award-space-based-technology) than others, but all follow a basic format. As such, even a simple webform soliciting specific information upfront may greatly lessen the time required to get these up.

# Proposed solution
Custom webform for grant awards that faculty may fill and submit.
First pass, info from this form should go to Richard Lewis in order to review and create the story.
Next pass, possibly format some of the info into a story format as much as possible.
Next pass, create a draft page with the information in place, which may then be reviewed, edited, and published.
Next passes, more cool stuff.

Here are some proposed fields for a grant award template:

• Grantee name(s)
• Affiliation (or title)
• Funding agency or entity
• Award amount
• Award duration
• Brief description of award (limit XXX characters)
• Web site/URL for grant award
• Quote to use in news item about winning the award (limit XXX characters)

# Additional info

There is currently a form in workflow that has some of this in place, but it's less readily available to all staff/faculty.
![image](https://user-images.githubusercontent.com/49074566/129041402-c73c8c69-e8de-4211-a377-efcb1c9327ec.png)
![image](https://user-images.githubusercontent.com/49074566/129041435-47d2bce3-c4e7-4d68-bded-5018d715ea2b.png)

**Comment by briand44** [comment]
Just planning on scoping this to what has been identified as the first pass. Webform that captures the info and emails it to the correct person.

Sounds like webform is not enabled yet on this site.

**Comment by briand44** [comment]
hidden captcha likely needed for this form as well.

**Comment by makurj** [comment]
Should any of these form components be required? For example, name, affiliation, description, website/URL?

![image](https://user-images.githubusercontent.com/52135878/136418543-7a8cc6ac-3976-4692-b106-7ae81c49014e.png)

**Comment by makurj** [comment]
Also, I tried to use textarea for description and quote but it doesn't allow for a character limit. Only textfield does. Is that okay?

What is the character limit they want? Right now, I have it set to 500.

**Comment by makurj** [comment]
For standup tomorrow (I'm out):

Locally:
- Enabled webform, CAPTCHA, hidden CAPTCHA modules
- Created webform (have some questions about the fields)
- Enabled hidden CAPTCHA on the form

I can create this on prod upon my return.

**Comment by makurj** [comment]
First pass webform on prod done: https://now.uiowa.edu/grant-awards-intake-form. Should I reach out to Richard?

**Comment by makurj** [comment]
The font size was too small so added some styling to make it more readable.

**Comment by makurj** [comment]
Met with Chris and Richard. Here are the new requests:

- [x] Make all fields except the quote required.
- [x] Add an email field.
- [x] Don't show previous submission information.
- [x] Remove $ as default value for Award amount.
- [x] Add "500 character limit" to description and quote labels
- [x] Replace Richard's email with osc-researchrequest@uiowa.edu for submissions.

**Comment by makurj** [comment]
Set up https://www.drupal.org/project/webform_validation and changed description and quote fields to textareas with 500 character limit.

**Comment by makurj** [comment]
First pass complete.

**Comment by briand44** [comment]
I think we could probably close this issue now that the first pass is complete. We can let the customers begin using this form and get feedback on if it is working well for them and how urgent any future enhancements would be. Ideally, the future enhancements could be part of the larger redesign and move to SiteNow v3. We can re-open if there is any more urgent feedback.
