### ISSUE TITLE
Set migrated Obermann article summaries to 400 characters.

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#3949]
### Problem
#3948 

### Proposed Solution
Write an update hook to iterate all the migrated obermann articles, probably using the migrate map, and set all the summaries correctly to 400 characters as requested.

If we use the same trim functionality in BaseNodeSource then this is blocked by #3948 otherwise something else could be used.

**Comment by richardbporter** [comment]
With an ellipsis if over 400 characters!

**Comment by richardbporter** [comment]
>you could go ahead and set summaries for all of the articles on the new site, overwriting whatever is already there.

**Comment by cory-skeers** [comment]
@richardbporter So, I think this is set to go, if we're setting the article summary values themselves. The processing in `BaseNodeSource` could be updated to use this as well--there are quite a few extra bells and whistles over the current processing.
