### ISSUE TITLE
Inactive site communications 703

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#3953]
We need to send out communications to inactive 703 sites.

**Comment by briand44** [comment]
https://github.com/uiowa/uiowa/issues/3684

**Comment by richardbporter** [comment]
The Dispatch template should be updated to ask at least one person to log in to the site. This indicates the site is still needed and prevents it from being flagged as inactive the next time we run the script.

https://apps.its.uiowa.edu/dispatch/templates/932493356

The same template/communication is used for both the first and all subsequent emails so it needs to be changed to account for that. For example, we might want to add a final warning message before sending the second communication.

**Comment by richardbporter** [comment]
I've added a contact line to the template. We talked about adding 1 week to the second email to ensure we use the same relative date for both communications. Example:

1. `drush @sites php-script drush/inactive.php --send-email '6 months ago'`
2. `drush @sites php-script drush/inactive.php --send-email '6 months 1 week ago'`

'6 months 1 week ago' appears to be valid based on https://www.php.net/manual/en/datetime.formats.relative.php.

Additionally, the template should be updated for the second communication to reflect the fact that it is the second and final notice.

**Comment by briand44** [comment]
Added blocked label until at least a week has passed since initial communication.

**Comment by richardbporter** [comment]
Updated template. Sent 2nd round to remaining sites. Set campaign back to test mode.

**Comment by richardbporter** [comment]
The next run of `drush @sites php-script drush/inactive.php --send-email '6 months 2 weeks ago'` can happen on 10-4-2021.

**Comment by joewhitsitt** [comment]
```
.mnt.www.html.uiowa703.docroot#careers.uiowa.edu                     >> 
.mnt.www.html.uiowa703.docroot#careers.uiowa.edu                     >> 
.mnt.www.html.uiowa703.docroot#distance.uiowa.edu                    >> Domain distance.uiowa.edu does not   [error]
point to uiowa703 application.
.mnt.www.html.uiowa703.docroot#law.uiowa.edu                         >> Domain law.uiowa.edu does not point  [error]
to uiowa703 application.
.mnt.www.html.uiowa703.docroot#maps.uiowa.edu                        >> No active webmasters found for site  [error]
maps.uiowa.edu. Cannot send email.
.mnt.www.html.uiowa703.docroot#obermann.uiowa.edu                    >> Domain obermann.uiowa.edu does not   [error]
point to uiowa703 application.
.mnt.www.html.uiowa703.docroot#president.uiowa.edu                   >> Domain president.uiowa.edu does not  [error]
point to uiowa703 application.
.mnt.www.html.uiowa703.docroot#www.engineering.uiowa.edu             >> Domain www.engineering.uiowa.edu does[error]
not point to uiowa703 application
```

**Comment by joewhitsitt** [comment]
Going off the previous list of site identified, only theme.uiowa.edu returned back. @GaryRidgway logged into all of the previous sites to see that no one had logged in. Not sure why the script returned the way it did. Not sure how to move forward. Instructions unclear.

**Comment by joewhitsitt** [comment]
@briand44 knowing that folks haven't logged in, should we remove the domains for these sites?

**Comment by briand44** [comment]
@joewhitsitt what sites other than theme.uiowa.edu?

**Comment by joewhitsitt** [comment]
The original list was:

```
- aging.uiowa.edu  - removed                   
- fa.fo.uiowa.edu   - logged in                  
- inspire.uiowa.edu   - logged in                
- magazine.education.uiowa.edu - removed       
- theme.uiowa.edu
```

**Comment by briand44** [comment]
Not inspire, someone logged in. I'll create a card about that one because Michael made it sound like we may be able to remove now that it has been archived by the libraries.

**Comment by joewhitsitt** [comment]
we double-checked inspire and fa.fo. both had logins. we can proceed with removing the domain for theme.uiowa.edu

**Comment by joewhitsitt** [comment]
theme.uiowa.edu domain was removed from 703 PROD.
