### ISSUE TITLE
SiteNow Request Form - Conditional Logic Not Working Correctly

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#3960]
## Problem

When the site moved over the conditional logic for the site-request form got messed up so a pre-approved domain asks for a full site URL.

https://sitenow.uiowa.edu/admin/structure/webform/manage/request_a_site/submission/12346

<img width="741" alt="Screen Shot 2021-08-12 at 12 44 57 PM" src="https://user-images.githubusercontent.com/4663676/129247104-ad066642-6564-41d3-8103-9bf98e3dc107.png">

## Proposed Solution

- Refer to a backup of the site or recreate conditional logic for the request form

**Comment by richardbporter** [comment]
I'm not sure I understand the problem here. I think a full URL is required for each request type.

**Comment by joewhitsitt** [comment]
the submission has been changed since creating this issue, but the request came over as https://startalkchinese.sites.edu Is the expectation that the requester takes the pre-approved pattern and formulates the correct URL on their own? I thought we captured it separately and strung it together to prevent input errors.

**Comment by richardbporter** [comment]
Ah I see. Since that is a URL field, I think that is the expectation. I don't believe we strung it together because that would fail the webform URL base validation. 

I think this indicates our custom validation isn't working.

**Comment by richardbporter** [comment]
This should be fixed now in prod. The issue was the request type and URL pattern option keys were not set to what we are expecting in code. I updated the option keys.
