### ISSUE TITLE
Upgrade Signage application to PHP 7.4

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#3965]

**Comment by richardbporter** [comment]
I've updated Composer dependencies to work with Composer 2 and PHP 7.4.

**Comment by joewhitsitt** [comment]
```
Deprecated: Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in /.../docroot/profiles/signage/modules/contrib/entityreference_prepopulate/entityreference_prepopulate.module on line 336
```

Otherwise, locally, I am able to work with the sign (have not tested all of the widgets).

**Comment by richardbporter** [comment]
Switched dev.



> I've updated Composer dependencies to work with Composer 2 and PHP 7.4.

Needs to be deployed when prod is switched.

**Comment by richardbporter** [comment]
Just noting that adding an existing slide doesn't seem to work currently and is unrelated to upgrade.

<img width="919" alt="Screen Shot 2021-08-31 at 3 51 55 PM" src="https://user-images.githubusercontent.com/1068523/131574151-2ebb58ce-dac1-491c-a11e-ab921c989871.png">

**Comment by richardbporter** [comment]
Noting that Specialty -> ED Waitimes pane display seems off currently and unrelated to upgrade.

Also noting that Specialty -> USGS Earthquake map does not currently work.
