### ISSUE TITLE
Upgrade Dentistry application to PHP 7.4

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#3968]

**Comment by richardbporter** [comment]
I've updated Composer dependencies to work with Composer 2 and PHP 7.4.

**Comment by briand44** [comment]
Viki mentioned some concerns around this to me because they have lots of modules that aren't well maintained. Viki and Chuck would like to be notified when we have upgraded dev environment so they can help with testing and approving for prod.

**Comment by richardbporter** [comment]
Just switched dev over to 7.4.

**Comment by briand44** [comment]
>Just switched dev over to 7.4.

Did you communicate with Viki and Chuck or would you like me to let them know?

**Comment by richardbporter** [comment]
I did not b/c it takes a while for the servers to switch over. Go ahead though, it should be good now.

**Comment by briand44** [comment]
Can we sync the database and files so the dev site will more closely reflect prod before notifying them? It looks like it has been over two years since we have done that.

**Comment by richardbporter** [comment]
> I've updated Composer dependencies to work with Composer 2 and PHP 7.4.

This needs to be deployed before switching prod.

**Comment by richardbporter** [comment]
I synced the database and files from prod. The files should absolutely be deleted after they are done testing. We may want to clear out stage as well if they were ever synced there in the past.

**Comment by briand44** [comment]
I let Chuck and Viki know dev has been updated.

**Comment by richardbporter** [comment]
Done in dev, stage and prod. Waiting to hear back on deleting files in dev.

**Comment by richardbporter** [comment]
Files removed from dev.
