### ISSUE TITLE
Upgrade CLAS application to PHP 7.4

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#3969]

**Comment by mark-bennett-uiowa** [comment]
Updated local environment and tested on several sites of various sizes. Cleared varnish, cleared caches, checked forms, views, status report, etc to verify successful update.

Updated dev environment and performed similar tests on a variety on sites.

Updated stage environment and performed similar tests on a variety of sites.

Updated prod environment and performed similar tests. Sites seem to be working properly. At this point, waiting to see if anything pops up.

Done. Closing issue.

**Comment by briand44** [comment]
Closing this based on comment above.
