### ISSUE TITLE
Redirects don't work with trailing slash in source path

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#3979]
Looks like there is a patch out there if we want to fix this: https://www.drupal.org/project/redirect/issues/2932615

## Issue
If you go to the redirect configuration (ex https://africanamericanstudies.local.drupal.uiowa.edu/admin/config/search/redirect/add), and add a link with a trailing slash (`/asdf/`) to the `path* field`, and then add where you'd like the redirect to point to (`/about`), if you go to /asdf/ or /asdf, it should take you to the '/about' URL

**Comment by joewhitsitt** [comment]
i'd try no.22 first. no.29 seems to increase scope

**Comment by dnkemper** [comment]
had a few minutes to spare. Haven't added patch in a hundred years. Sawwy. BTW @joewhitsitt's suggestion of using no.22 worked swell. Nice job, guys!
