### ISSUE TITLE
Linkcheck .prod.drupal links

### ISSUE THREAD

**Issue by mjoneill** [uiowa/uiowa#3996]
As a site builder, I have visibility into how many links I have to .prod.drupal, .stage.drupal, .dev.drupal, and .local.drupal because I need to fix these prior to launching (or as soon after as possible).

Previous probe - https://github.com/uiowa/uiowa/pull/373 - jw

**Comment by mjoneill** [comment]
@cory-skeers et al, it seems like you had additional thinking on this.  Also, @joewhitsitt added a related probe...

**Comment by richardbporter** [comment]
Another component of this could be adding validation to try and prevent internal links being used in the first place. Attaching a filter to the Filtered HTML text format would ensure that validation is run in many different places - blocks, content types, etc. That same validation could be added to link fields as well.

**Comment by cory-skeers** [comment]
Previous probe has an interesting article as part of a go-live checklist: https://kevinquillen.com/mass-updating-drupal-fields-mysql-stored-procedure-pt-2

One thing that struck me about it is that the .prod/dev/stage links post-launch is the biggest and most visible issue, but absolute links are always a sticking point for content editors, and can lead to suboptimal situations where links either break in the future, or rely on redirects where `node/#` or `media/#` links would not.

My initial thoughts went in two directions:

- A tool where editors can run a "scan" of their site, which would check text fields, menu links, etc., for any absolute links to the site (or prod/dev/stage) and give them a report of which node, where the link is, etc.
- A validator of some sort to check on save and either give a notice, fix it (if possible) and give a message, or some other sort of intervention.

I'd lean toward the second. One issue with the first is the high number of areas a user can enter a link, and it can quickly become outdated (eg a new layout builder block type gets added, and it's not added to the query). It also requires an extra step on the user to get the report and then go to fix.

The second option is more proactive, in a similar way to how https://www.drupal.org/project/editoria11y (#3396) tries to make a11y easier and more in-your-face for the editor. It wouldn't help in-progress sites as much, but any new sites (and new edits) would benefit.

**Comment by richardbporter** [comment]
It looks like it is possible to search SiteImprove inventory for specific URLs: https://my2.siteimprove.com/QualityAssurance/991404/Inventory/Links/1?Query=prod.drupal

However, I don't see the Inventory tab on other sites. Not sure why that is. Also, SiteImprove respects robots.txt so we'd have to open up internal domains for scanning before launch. Just throwing this out there.

**Comment by richardbporter** [comment]
> Another component of this could be adding validation to try and prevent internal links being used in the first place. Attaching a filter to the Filtered HTML text format would ensure that validation is run in many different places - blocks, content types, etc. That same validation could be added to link fields as well.

Rethinking this a bit, I wonder if it makes more sense to just use pathologic instead of rolling our own version of that.

**Comment by richardbporter** [comment]
For awhile I've wondered if we could automate some go-live tasks, perhaps in a Drush command part of uiowa_core. That command could maybe use that stored procedure to fix those links if we'd prefer not to use Pathologic which only works on text formats.

**Comment by quamsta** [comment]
This may be a usability issue with the "anything goes" autocomplete link field that comes with Drupal. We had some rare issues with this sort of thing before, but a showing a specific "link to a page on this site" option first in our SilverStripe tinyMCE editor might have done a lot to mitigate this. No idea if there's anything like that for CKeditor/Drupal

<img width="547" alt="screen_shot_2021-08-30_at_10 05 23_am" src="https://user-images.githubusercontent.com/472923/131362032-2165f44d-20f9-4643-b249-6a6e1a8df8c4.png">

**Comment by briand44** [comment]
This may be related https://github.com/uiowa/uiowa/issues/3373

**Comment by briand44** [comment]
Let's learn some more about pathologic, find text and possible drush command to find and replace and we can weigh advantages and disadvantages.
