### ISSUE TITLE
Write tests for default content type stories

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#4000]
# Motivation

When we make changes to permissions (as in #3986), there is the possibility of introducing regressions related to the basic functionality around our 3 standard content types. We could automate testing this to prevent the need to write testing instructions and manually test them.

# Proposed solution

Write tests (@richardbporter suggested Behat) that include testing/execution of these stories:

- As an editor, I can create an article
- As an editor, I can create a page
- As an editor, I can create a person
- As an editor, I can edit an article
- As an editor, I can edit a page
- As an editor, I can edit a person
- As a publisher, I can create an article
- As a publisher, I can create a page
- As a publisher, I can create a person
- As a publisher, I can edit an article
- As a publisher, I can edit a page
- As a publisher, I can edit a person
- As a publisher, I can publish an article
- As a publisher, I can publish a page
- As a publisher, I can publish a person
- As a webmaster, I can create an article
- As a webmaster, I can create a page
- As a webmaster, I can create a person
- As a webmaster, I can edit an article
- As a webmaster, I can edit a page
- As a webmaster, I can edit a person
- As a webmaster, I can publish an article
- As a webmaster, I can publish a page
- As a webmaster, I can publish a person

Please double-check my work on the above list.

**Comment by briand44** [comment]
scope to a single role (editor) and test stories that a role should NOT be able to do.

**Comment by joewhitsitt** [comment]
I see from the IS that Rick suggested behat. Does anyone recall why we got rid of our behat tests? https://github.com/uiowa/uiowa/blob/4fd2134d40da7c51ea1066108af5c2bea84f2035/tests/behat/features/Search.feature

**Comment by pyrello** [comment]
> Does anyone recall why we got rid of our behat tests?

Not totally sure about this, but it seems like behat tests were a bit difficult to work with, since they use a completely different structure and syntax than everything else we are doing. Not opposed to revisiting these if they turn out to be easier to write or take less time to run.

**Comment by e-marie-w** [comment]
I _think_ I found an existing example in our code base: https://github.com/uiowa/uiowa/blob/main/docroot/profiles/custom/sitenow/tests/Kernel/PermissionsTest.php. We want to test different permissions and put the test somewhere other than the `docroot/profiles/`, but the hard part seems to already be figured out. The test passes normally, and when I added and removed permissions from `user.role.editor.yml` the test would fail as expected.

**Comment by joewhitsitt** [comment]
My expression that Michael mentioned in standup was because editor has the ability to add/edit and `override publish option` on the default content types, but they don't have the ability to move to the "publish" moderation state. This moderation functionality overrides that `override publish option` permission for the default content types

This may complicate the test if you want to test against moderation publish permissions

**Comment by joewhitsitt** [comment]
I think adding `assertArrayHasKey` for `use editorial transition publish` for publisher and webmaster and the reverse for editors would be a valuable addition to this test as this is what most site owners are concerned about based on what roles they give folks.
