### ISSUE TITLE
Change new pre-approved website deliver process

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#4001]
# Problem
Production domains are being indexed by Google before they are ready to launch.

# Proposed Solution
Deny robots until sites are ready to launch.

- Update provision instructions on https://wiki.uiowa.edu/display/drupaldev/Website+requests+via+sitenow.uiowa.edu
  - All new sites should be provisioned using internal `prod` domain so that they are hidden from robots.
- Update site created email
  - Possibly update the email that is sent to customers similar to the "existing site" template

**Comment by briand44** [comment]
Use existing domain provision process. May need to make some tweaks

**Comment by briand44** [comment]
review/update communications

**Comment by briand44** [comment]
Potential future follow up to build in ability to override robotstxt per site

**Comment by bspeare** [comment]
Since this is close to the top of the backlog, can someone chime in on what we are updating in the proposed solution?

- Update provision instructions for "New Sites"?  
  - Where are we denying robots for each new site?
- Update site created email.  
  - Are we asking customers to contact us when they are ready to launch their site so we can remove the deny robots rule?

**Comment by briand44** [comment]
My understanding of the plan is just to use the internal prod domains for "new" sites rather than provisioning "new" sites using the final production url. So we need to update the internal docs accordingly and potentially updating the email that is sent to customers similar to the "existing site" template.

**Comment by bspeare** [comment]
@briand44 thanks!  Are robots blocked from all `*.prod.drupal.uiowa.edu` sites now?

**Comment by briand44** [comment]
That is my understanding, yes.

**Comment by dnkemper** [comment]
Updated all docs to point to internal domain. Also changed emails so there's now a `Site Created Email - URL internal production` email and a `Site Launched Email`.

**Comment by joewhitsitt** [comment]
i will take a look

**Comment by joewhitsitt** [comment]
sorry, i went wild. additional feedback is welcome otherwise i think this can be closed.
