### ISSUE TITLE
Add `word-break: break-word` for text area `<a>` tags

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#4002]
# Problem
<img width="713" alt="Screen Shot 2021-08-19 at 8 28 37 AM" src="https://user-images.githubusercontent.com/1036433/130077027-64ecf453-835c-4c69-9773-624d2873d991.png">

# Proposed solution
<img width="657" alt="Screen Shot 2021-08-19 at 8 27 18 AM" src="https://user-images.githubusercontent.com/1036433/130077061-a6f86614-a1ad-4e1d-979b-6b01ee7d22a8.png">

**Comment by joewhitsitt** [comment]
I feel like this has come up before for another component in uids_base. Is there a situation where we don't want this to happen? uiowa_bootstrap has this as a base style for `<a>`

**Comment by bspeare** [comment]
Yes, we should look into adding this globally.  We just need to test how it changes the behavior of other components.

**Comment by bspeare** [comment]
Closing this because https://github.com/uiowa/uiowa/issues/2325 already exists.
