### ISSUE TITLE
Link field with MyUI urls containing `.` are converted to `_`

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#4003]
# Problem
MyUI urls used within link fields have `.` converted to `_`. 

# Steps to reproduce
View the difference between the text area link and the card link field on: https://sandbox.prod.drupal.uiowa.edu/link-test

# Proposed solution
?

**Comment by cory-skeers** [comment]
Poked around at this a little, and wondering if https://www.drupal.org/project/redirect/issues/3153360 is related. Either `Url::fromUri()` in Core, or the more general `parse_str` method seems to be a common culprit. Haven't dug in to see where the difference in URL handling is that may include this.

**Comment by bspeare** [comment]
Nice find @cory-skeers !

**Comment by cory-skeers** [comment]
The patches being worked on in https://www.drupal.org/project/drupal/issues/2984272 have the potential to be farther reaching, but there is also a limited-scope workaround.

Curious that the original issue doesn't appear to crop up when using the Source link and Link Directly to Source options for articles, and then viewing the article teaser. There may be a difference in filter settings or preprocesses that are effecting it which may be a better approach than the workaround which basically undoes core link field preprocessing.
