### ISSUE TITLE
SPPA private permissions didn't stick

### ISSUE THREAD

**Issue by GaryRidgway** [uiowa/uiowa#4008]
# Story
As a user, i want the SPPA private page stuff to work as described in https://github.com/uiowa/uiowa/pull/3986

# Proposed Solution

- [x] Confirm marking a page as private now in PROD ([post permission rebuild](https://github.com/uiowa/uiowa/issues/4008#issuecomment-902280689)) now has the expected visibility for anonymous users.
- [ ] Update the display settings to [not show the private field](https://github.com/uiowa/uiowa/issues/4008#issuecomment-902255285) above the page title.

**Comment by joewhitsitt** [comment]
Increase in scope. This displays:
<img width="402" alt="Screen Shot 2021-08-19 at 4 18 47 PM" src="https://user-images.githubusercontent.com/4663676/130145637-87275f29-23af-46db-b63f-c526c8fae5b0.png">

each page that is being saved now has a public or private status above the title.

https://sppa.uiowa.edu/current-students/jobs-and-internships
https://sppa.uiowa.edu/about-us/welcome-director
https://sppa.uiowa.edu/future-students/alumni-success

**Comment by joewhitsitt** [comment]
I ran a permissions rebuild for sppa which I think fixes this (admin/reports/status/rebuild or https://github.com/uiowa/uiowa/pull/3807/files).

**Comment by joewhitsitt** [comment]
Maybe @e-marie-w can confirm the permissions rebuild worked by marking a piece of content as private.

**Comment by e-marie-w** [comment]
It's working for me, pages marked private give me 'access denied' if not logged in while pages with the public status are still visible.

**Comment by GaryRidgway** [comment]
this is a yee-haw moment.
