### ISSUE TITLE
provision faculty-senate.uiowa.edu

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#401]
Currently a subdirectory site moving to D8. Let me know when this is resolved and I will follow up with the customer.

**Comment by ethanstjohn** [comment]
When "drush sql:sync @faculty-senate.local @faculty-senate.dev" is ran it does not find the correct dev database. It shows the default dev database.

**Comment by richardbporter** [comment]
https://faculty-senate.prod.drupal.uiowa.edu/

Needs webmaster.

**Comment by briand44** [comment]
Created webmaster account.
