### ISSUE TITLE
Extend event content type feature to provide Series Link and Directly link to Series functionality

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#4010]
# Story

As an editor, I can provide a Series Link for event content that displays as a button on the event node but also provides and option to link directly to it from teasers and view titles.

# For reference

Look at sitenow_articles for functionality similar to this.

# Proposed Solution

- [x] Extend event content feature to provide a "Series Link" link field.
  - [x] Output the title/link as a button so visitors to the event instance can navigate to the Event Series
- [x] Extend event content feature to provide a "Directly link to Series" boolean field.
  - [x] Teasers and views row titles link to Event Series if direct link is checked.

**Comment by bspeare** [comment]
@joewhitsitt Do we want the Series Link field to be a link for internal pages only or allow external as well?

**Comment by joewhitsitt** [comment]
I think it should allow both.
