### ISSUE TITLE
Review topic landing page pr and provide feedback

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#4011]
Review https://github.com/uiowa/uiowa/pull/4009 and provide feedback to @quamsta

**Comment by quamsta** [comment]
Thanks @bspeare, thought about setting up an issue but sorta forgot while I was hunched over scribing my pull request. Appreciate it!

**Comment by bspeare** [comment]
There's currently a draft converting this to layout builder: https://github.com/uiowa/uiowa/pull/4060.   During the next sprint (starting 9/2) I think we will need another working session with @quamsta to get that pr ready for review.

**Comment by bspeare** [comment]
Closed via https://github.com/uiowa/uiowa/pull/4060.
