### ISSUE TITLE
Create "Event series" content type

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#4018]
# Story 

As an editor, I can create an Event series page that pulls in published upcoming event content dates referencing it and is sorted chronologically.

# Proposed Solution

- Create "Event series" content type
  - [ ] Layout template that is similar to Hawkeye Visit Days content
  - [ ] I doubt we can reliably output the general time summary of all event instances, so providing a "Series schedule summary" long text that captures this would be suitable.
  - [ ] Block that pulls in published upcoming event content dates referencing it (contextual filter on content id) and is sorted chronologically. If linked, this is the one instance where it should link to the event instance.
  - [ ] ~~[EventSeries](https://schema.org/EventSeries) information captured and mapped to the related SEO settings by way of https://www.drupal.org/project/eva or entityQuery collecting details for the subEvent and pulling in event instances meta info. Use hook_metatags_alter() to set. Consider keeping these Schema Event defaults from being overridden by webmasters but still allowing other meta information to be editable.~~ Based on https://github.com/uiowa/uiowa/issues/4018#issuecomment-904720492

**Comment by bspeare** [comment]
@joewhitsitt If https://admissions.uiowa.edu/hawkeye-visit-days is our model for this do we need the fields listed below?

- Featured Image
- Intro text (Or just have them set this in the Body?)
- Body

Event details sidebar featuring:
  - Series schedule summary field
  - Link field for the "Register" button

**Comment by joewhitsitt** [comment]
Good question. I figured this content type would be a set layout capturing most of what they have here, but I have not confirmed if this is the look they want versus the solution they came up with based on the LB options available to them.

**Comment by joewhitsitt** [comment]
Bit of a road bump. schema_metatag doesn't have an EventSeries type. The module recommends using metatags_alter to do altering but it fires before the json is created. This means we either need to repurpose existing event schema inputs or we might need to create an EventSeries sub module

Also should be noted that part of the reason EventSeries is not an available type is because it is still a pending thing.

Update: I think this part of the issue be postponed until [EventSeries](https://schema.org/EventSeries) is more of a thing.

**Comment by joewhitsitt** [comment]
Capturing query work before I ran into the bump. This would be an alternative to the EVA module.
```php
/**
 * Implements hook_metatags_alter().
 */
function admissions_core_metatags_alter(array &$metatags, array &$context) {
  if (isset($context["entity"])) {
    $admin_context = \Drupal::service('router.admin_context');
    if (!$admin_context->isAdminRoute()) {
      $node = \Drupal::routeMatch()->getParameter('node');
      $node = ($node ?? \Drupal::routeMatch()->getParameter('node_preview'));
      if ($node instanceof NodeInterface) {
        // Find event content that references this event series.
        if ($node->bundle() == 'event_series') {
          $nid = $node->id();
          $query = \Drupal::entityQuery('node')
            ->condition('status', 1)
            ->condition('type', 'event')
            ->condition('field_event_series_link.uri', 'entity:node/' . $nid, '=');
          $nids = $query->execute();
        }
      }
    }
  }
}
```
