### ISSUE TITLE
Areas of Study: Create a clear split from admissions

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#4034]
Continue within https://github.com/uiowa/uiowa/pull/3926
Move everything that Admissions needs over and eventually disable the feature split on Admissions

## Notes

The #3926 PR is currently adding the new stuff to Admissions but not placing the field on the content type nor providing permissions for the taxonomy vocabularies.

**Comment by cory-skeers** [comment]
Still more to do in #3926, but I think this part of it is done.

**Comment by bspeare** [comment]
Seeing this on `admissions.local`:

<img width="1275" alt="Screen Shot 2021-08-30 at 12 56 12 PM" src="https://user-images.githubusercontent.com/1036433/131383301-d76c7591-0f0a-4ccf-a834-e0e6066aaeb0.png">

Should this be a part of this issue or https://github.com/uiowa/uiowa/issues/4041?
