### ISSUE TITLE
As a site visitor using IE11, I can use a functional SNv2/3 website.

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#4036]
# Problem
We currently have some JS errors in IE 11:
<img width="449" alt="Screen Shot 2021-08-27 at 8 47 59 AM" src="https://user-images.githubusercontent.com/1068523/131137515-bce2dc8c-5115-408a-b4c4-4f57eedde17c.png">

If IE11 needs to be functional, some of the errors might indicate otherwise.

# Steps to reproduce
Spin up IE11 on BrowserStack and inspect all default and custom JS.

# Proposed solution
Audit all existing JS for unsupported features and either refactor or transpile with Babel.

**Comment by richardbporter** [comment]
As noted in https://github.com/uiowa/uiowa/pull/5141, profiles do not work at all in IE11.

https://dentistry.uiowa.edu/directory?cohort=456874&appointment=&category=&query=&page=1&size=25 in IE11:

<img width="1321" alt="Screen Shot 2022-05-17 at 9 29 47 AM" src="https://user-images.githubusercontent.com/1036433/168836163-ceaeda84-ce1d-4a80-9d10-4e78dabfc700.png">

**Comment by mjoneill** [comment]
I think we have clear runway. No longer supported by MS. Continued decrease in volume of site visitors using it.  Let's nuke it and throw a party.
