### ISSUE TITLE
Genetics - allow advisor field to contain multiple advisors

### ISSUE THREAD

**Issue by e-marie-w** [uiowa/uiowa#4037]
# Motivation:
Some students on genetics.grad.uiowa.edu have multiple PhD advisors. Currently, the person content type only allows users to save one advisor in the advisor field. 

## Story
As an editor/webmaster on a site with the `grad_person_extended`, I can set multiple advisors for a person of the student person type.

# Proposed solution
* `blt ds`
* `drush @default.local uli admin/config/development/configuration/config-split`
* Enable `grad_person_extended` split.
* `drush @default.local cim`
* Visit https://default.local.drupal.uiowa.edu/admin/structure/types/manage/person/fields and edit the Advisor field.
* Change the field settings for the Advisor field to allow unlimited entries.
* Change the form settings for this field to use "Autocomplete" option (not "Autocomplete (tags)").
* `drush @default.local csex grad_person_extended`

**Comment by GaryRidgway** [comment]
I'm going to try and tackle this. I was told that this is a good place to make these changes, so i will use this branch and pr: (https://github.com/uiowa/uiowa/pull/4026)

**Comment by GaryRidgway** [comment]
this should be done!

**Comment by pyrello** [comment]
Re-opening. We'll let the PR close this issue :)
