### ISSUE TITLE
Area of study: "Search" filter block similar to admissions.uiowa.edu that sends queries to URL specified in block config

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#4041]
Create search block similar to the one displayed on the home page of admissions.uiowa.edu that sends queries to URL specified in block config:

<img width="1269" alt="Screen Shot 2021-08-30 at 12 52 27 PM" src="https://user-images.githubusercontent.com/1036433/131382823-c746c670-33a5-45ea-a6c1-f3ed858f8f19.png">

<details>
-  Moved functions related to `admissions_core` out of `uiowa_area_of_study` and back into `admissions_core` so that the admissions.local site doesn't WSOD when editing or viewing an area of study https://github.com/uiowa/uiowa/pull/3926/commits/2ac9348145725a758c4b943c6217fc302db4ccc4
-  Set `admissions_core` up with a replacement search block so that it doesn't use the `uiowa_area_of_study` block https://github.com/uiowa/uiowa/pull/3926/commits/25013b4148edb51ab8af1d43146bccb7c045d348
-  Set up `uiowa_area_of_study` with search styles for the `uiowa_area_of_study` block https://github.com/uiowa/uiowa/pull/3926/commits/6a1e33cbabea2384bc54747c68c663394a391cf0
</details>

**Comment by joewhitsitt** [comment]
The team thinks this is a good opportunity to create a generic search block that through block config captures the endpoint and a query parameter. Each block should allow unique config.

Admissions should continue to have their AoS search block and view page for now. Could the module be enabled but not the feature split? Bigger slice for another time.
