### ISSUE TITLE
Tags added within Relationship text input are hidden from view

### ISSUE THREAD

**Issue by bewoldt** [uiowa/uiowa#4042]
# Problem
When you have multiple tags added within a Relationship they end up being hidden if they are longer then the width of the text input field. It is hard to even add a new tag because you have to scroll all the way over to the right which is then covered up by the search icon.

<img width="480" alt="Screen Shot 2021-08-30 at 12 52 27 PM" src="https://user-images.githubusercontent.com/731952/131383553-de2ac7dd-e5c3-4ab7-9d8d-885b32621f4a.png">

# Proposed solution
Use a textarea where tags wrap to a new line if it is too long.

**Comment by joewhitsitt** [comment]
I think long term it would be better to switch to the default field widget for this (single tag per input, drag handles to reorder, add another button)

<img width="669" alt="Screen Shot 2021-08-30 at 1 17 19 PM" src="https://user-images.githubusercontent.com/4663676/131385625-c265b2eb-8474-4482-aa74-0c0932602770.png">

**Comment by benlewzz** [comment]
As a team with multiple sites and hundreds of pages that will be using this, I hope we can keep this to a large, comma-separated text field for ease of pasting and editing.

**Comment by benlewzz** [comment]
Edited a few more pages, realizing that either of these would work great.

**Comment by joewhitsitt** [comment]
>I hope we can keep this to a large, comma-separated text field

I think converting this to a textarea with wrapping is not possible (more than one row). Looks like there was an issue long ago to add this, but it was shut down and I don't think there is a contributed project that does this. 

https://www.drupal.org/node/90329

**Comment by briand44** [comment]
Move forward with https://github.com/uiowa/uiowa/issues/4042#issuecomment-908575764

**Comment by briand44** [comment]
articles, people and pages
