### ISSUE TITLE
Admission viewbook updates

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#4044]
>I have a few text updates for the viewbook site to pass along. No structural changes are necessary, just the text changes below (and in red on the attached screenshot). Our counselor travel and virtual fairs won’t start for a couple weeks, so that’s probably out best deadline for this.

-------------

24 International Fulbright Scholars in 2020-21

21 NCAA Division I Teams

1316+ students studied abroad (remove “last year”)

Tuition table:
Iowa residents - $ 9,942
Nonresidents - $31,905*
Standard housing and meal plans - $11,780**

ACT and SAT Test Scores
The Iowa Board of Regents has waived the requirement for students needing to submit either an ACT or SAT in order to be admitted for the Fall 2022 term. Students who wish to be considered for admission without a test score may leave the test score section blank on the application. An individual review process will be used to make an admission decision for students who do not self-report a test score as part of their application. Students admitted to the University of Iowa without test scores may also be considered for direct admission to University of Iowa academic programs and some merit scholarships awarded by the Office of Admissions.

Apply for housing and dining.
**update the date to May 2, 2022**

**Comment by briand44** [comment]
![viewbook-site](https://user-images.githubusercontent.com/1017022/131400244-5b8064d4-39bd-4bab-941c-500fb46f22b5.png)

**Comment by makurj** [comment]
More copy updates requested:

  We just got a few stats update in (the past couple of days) that need to change. Once that’s done we should be good to go.
  We work together: #33 BEST PUBLIC UNIVERSITY BY U.S. NEWS & WORLD REPORT
  Student Outcomes: 93% OVERALL JOB/GRADUATE SCHOOL PLACEMENT RATE
  College of Education
  94%
  College of Engineering
  92%
  College of Liberal Arts & Sciences
  93%
  College of Nursing
  98%
  College of Public Health
  98%
  Tippie College of Business
  94%
  *keep the list in the same order, just update the percentage/rate*

![image](https://user-images.githubusercontent.com/52135878/132908462-d7f21c46-2f2c-4baf-88e8-50081dc16004.png)

**Comment by makurj** [comment]
Completed. Live.
