### ISSUE TITLE
Export all events on obermann.prod.drupal.uiowa.edu

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#4048]
# Story

As an Obermann Center site owner, I would like a csv export of all events (past and future) so that we can refer to them as needed once our new site goes live.

# Additional Info

Fields in csv:
Title
Date - start and end
Description
Location
Type
Related Links

# Proposed solution

I believe we have used views data export for this type of thing in the past.

**Comment by dnkemper** [comment]
Emailed Jenna and waiting to hear back on csv export formatting. For now, here's the location of the view changes that were made to export the events content: https://iowa.sharepoint.com/:f:/r/sites/CSI-Drupal2/Shared%20Documents/General/obermann%20csv?csf=1&web=1&e=oEOnv3
