### ISSUE TITLE
Signage - Flexslider prevents full-width display of event widgets

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#4050]
# Problem

There is a resolution issue with the following image and the devices in question are being adjusted, but the widgets are limited in how wide the tables grow.

<img width="640" alt="thumbnail_image001" src="https://user-images.githubusercontent.com/4663676/131579926-c53deac1-695a-4dbf-af4b-d8d996c610e3.png">

# Proposed solution

- [ ] Figure out a way to wrangle flexslider or consider this a wontfix

**Comment by bewoldt** [comment]
Use display:table instead of display: block on the table inline styles. Or you could take off the display: block on the tables too.

**Comment by joewhitsitt** [comment]
Thanks for the suggestion @bewoldt. I will sneak this in with other in-progress Signage work.

**Comment by joewhitsitt** [comment]
Added to `signage-outlook` for UI Signage. See #3933.  Pushed to master for UI Healthcare Signage. Waiting for deployment.
