### ISSUE TITLE
Evaluate/Update latest paragraphs release

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#406]
### Problem
Paragraphs is about to release a new version and Bedir sent out a tweet to test it ahead of time:
https://twitter.com/berdir/status/1158625467185975296

Since this is such a core piece of our service, we should make sure this update doesn't break our stuff.

### Test
Evaluate the latest dev within our environment and see if it affects anything (editor experience, output).

**Comment by joewhitsitt** [comment]
This has been released https://www.drupal.org/project/paragraphs/releases/8.x-1.9

**Comment by ethanstjohn** [comment]
I have tested the paragraphs release on my local site. All of the paragraph content types seem to work and look as they did before.

**Comment by joewhitsitt** [comment]
Let's repurpose this task then and go ahead and update paragraphs to 1.9. @ethanstjohn you want to try this?

`composer update drupal/paragraphs` should result in a modified composer.lock file. That is what we should create a PR of.

**Comment by ethanstjohn** [comment]
https://github.com/uiowa/uiowa/pull/670 Done :)
