### ISSUE TITLE
Law Viewbook updates

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#4064]
Update Law Viewbook according to email. Michael, Ben, Alan, Makur and myself have this email and can forward it to whoever needs it.

**Comment by makurj** [comment]
EDITS TO SITE:

1. See Word Document for copy edits to content blocks.
-   These are highlighted in the document with notes for clarification.
-   Note a new section that needs to be added at the bottom. For reference, see the last spread of the [printed viewbook here](https://issuu.com/uiowa-osc/docs/law-jdviewbook-2021-final-forissuu).
![image](https://user-images.githubusercontent.com/52135878/131917894-a5cb491e-438a-454a-861c-48e1df803a8e.png)

-   New photos attached.

2. Update APPLY link: https://law.uiowa.edu/apply
3. Update VISIT link: https://law.uiowa.edu/admissions/admissions-events 
4. Lighten overlay on the main photo – Law feels it is too dark, as is. They actually suggested we find a different photo, but I think a simple adjustment will help.

![2019_10_08-Iowa-River-Drone-Shoot-II-jatorner--0307-Pano](https://user-images.githubusercontent.com/52135878/131914782-065c7e50-e593-484b-b15e-3bd494933b95.jpg)
![2021_08_04-Boyd-Law-Building-Spaces-III,-August-2021-jatorner--0688](https://user-images.githubusercontent.com/52135878/131914796-c8ad5d49-6647-4f10-be57-af0b976ea199.jpg)
[Why Iowa Digital-R4Edits.docx](https://github.com/uiowa/uiowa/files/7101709/Why.Iowa.Digital-R4Edits.docx)

**Comment by makurj** [comment]
Checked with Laura and she said no need to add a new section at the bottom and we moved the stats above the "FIRST IOWA THEN ANYWHERE" section to avoid black background stats on black background footer.

**Comment by bspeare** [comment]
Let's also make sure to update this gold card text to grey so that it is accessible:

<img width="683" alt="Screen Shot 2021-09-03 at 10 21 07 AM" src="https://user-images.githubusercontent.com/1036433/132029294-375d1df4-d42b-4f4d-8974-4db9ef4f293a.png">

**Comment by bspeare** [comment]
For the overlay, you can use the gradient style that is used on the banners in `uids_base` if you want:

`.banner--gradient-bottom::after {
    background: linear-gradient(180deg,transparent 0,rgba(0,0,0,.65) 70%);
}`

**Comment by makurj** [comment]
Live. Closing this issue for now.
