### ISSUE TITLE
Approve pending dev/stage wildcard certificates and install in every application dev/stage environment on the uiowa subscription except icgov. 

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#4067]
Current dev/stage certs expire 9-9-2021. 

These are different types of certs but the usual process should hold. They were auto-renewed which I think is not something we are supposed to check going forward. Once installed everywhere and activated, the old certs should be revoked in CM and removed from AC.

**Comment by makurj** [comment]
Completed.
