### ISSUE TITLE
Recreate existing view page as a view block that can be placed on any layout builder page.

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#4069]
Epic: https://github.com/uiowa/uiowa/issues/3837
# Story

As an editor, I want to be able to place a view block of area of studies within a layout builder page.

# Proposed Solution

- [x] Recreate the existing areas of study view as a block display and package up in AoS feature split
- [x] Disable or remove the view page from the feature split.
- [x] Make sure the styles are scoped correctly
- [x] Make sure the exposed filters still work

**Comment by joewhitsitt** [comment]
This could be added to https://github.com/uiowa/uiowa/pull/3926

**Comment by dnkemper** [comment]
Crap. Okay!
________________________________
From: Joe Whitsitt ***@***.***>
Sent: Friday, September 3, 2021 9:49:37 AM
To: uiowa/uiowa ***@***.***>
Cc: Kemper, Danielle N ***@***.***>; Assign ***@***.***>
Subject: [External] Re: [uiowa/uiowa] Recreate existing view page as a view block that can be placed on any layout builder page. (#4069)


This could be added to #3926<https://github.com/uiowa/uiowa/pull/3926>
