### ISSUE TITLE
Docs - Policies - WWW -> non-WWW

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#407]
### Problem

As a follow up to #356, we need to write a policy about how we won't be supporting WWW sites on D8 and that all WWW requests will redirect to the non-WWW address.

**Comment by ethanstjohn** [comment]
https://github.com/uiowa/uiowa/blob/gh-pages/policies/index.md

**Comment by ethanstjohn** [comment]
Written under 'Domain Changes"
