### ISSUE TITLE
Finalize Concept3D CSV Import

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#4076]
Epic: https://github.com/uiowa/uiowa/issues/3957
Blocked by https://github.com/uiowa/uiowa/issues/4025

# Story

As the integration manager for Concept3D, I have received a finalized .csv document from the University of Iowa for initial import into the Concept3D CMS.

# Proposed solution

- [x] With the .csv data dump that Facilities provides, fill in the Bulk Upload spreadsheet that Concept3D provides.
- [x] Combine lat and long into a comma separate format for location.
- [x] See about getting initial data for building images added
- [x] See about getting initial gender inclusive restrooms and lactation rooms data added
- [x] Capture manually curated information like descriptions, links, keywords, pano URL, CMS categories.
- [x] Decide visibility of each building (visible/private)

**Comment by briand44** [comment]
removed blocked label since #4025 is closed

**Comment by joewhitsitt** [comment]
i'd like to at least help guide this work. others have expressed interest. i am willing to huddle and lay it out.

**Comment by joewhitsitt** [comment]
Ben, Marie and I pulled together a google spreadsheet (shared in email/slack). We will need help from @ABoston88  and @mjoneill to finalize the sheet before we send it to Concept3D.

**Comment by joewhitsitt** [comment]
I was able to pull a list of lactation and gender inclusive restrooms but the data doesn't quite align with what we got going. I am going to see about cleaning it up for the initial import. This and similar data might be a periodic manual pull/groom process

**Comment by ABoston88** [comment]
Making progress on category section...have a few buildings highlighted that are pretty far off-site (Okoboji, MacBride). Curious if those should be included in the import. Does Concept3D range that far?

**Comment by joewhitsitt** [comment]
>Curious if those should be included in the import. Does Concept3D range that far?

@ABoston88 I don't think Concept3D extends renders to those from what I am seeing. I think we could still import but leave them as not visible/private. Ultimately this is an "active" building according to Facilities and would show up again on a later import/sync unless we find another db property to filter buildings by (e.g. combination of main campus, etc.)

I notice some of your categories do not align with the MVP categories as discussed (https://github.com/uiowa/uiowa/issues/4024). I think we will need to create these additional categories if ahead of import if we want them to be properly assigned.

**Comment by ABoston88** [comment]
Right, my bad. I was going back-and-forth on whether we should take this chance to be more specific. I'll work with what we have and we can revisit that later.

**Comment by joewhitsitt** [comment]
I got lactation rooms into the spreadsheet. I combined "lactation room, lactation and family lactation" together from the db and kept "staff lactation room" separate but included.

**Comment by ABoston88** [comment]
Looking at this list, I think we will probably need two additional categories. I don't know how to categorize research centers/facilities with what we have now...or utility/service stuff. My fault for not remembering that these were part of the old map...but didn't need tagging in the old structure. Would those be difficult to add, at this point?

**Comment by ABoston88** [comment]
For smaller potential categories like cultural centers, it might be best to just import and adjust manually, no? Assuming we'll have rights to make changes after the imports take place.

**Comment by joewhitsitt** [comment]
So these are what are currently in there. I don't think creating new categories is much trouble at all, just that it needs to be done before input.

<img width="211" alt="Screen Shot 2021-09-21 at 4 12 09 PM" src="https://user-images.githubusercontent.com/4663676/134248468-dc7e43e0-a950-473c-be90-e5e3bc5b07db.png">

Don't forget we can also do sub-categories. Also, categories can be changed for a point after import as well.

**Comment by joewhitsitt** [comment]
I got gender-inclusive restrooms added to the sheet as well. Limited the db query to just `RESTROOM - NEUTRAL SINGLE USER` which seemed aligned with a lot of the existing information on the maps.uiowa.edu however there are a few notable locations that no longer have one by that classification... This data varies in classification quite a bit and I am not sure which ones meet the definition for this.

**Comment by joewhitsitt** [comment]
Made an assumption that any building with a photo should be visible/not private in the CMS and marked those as such.

**Comment by joewhitsitt** [comment]
I brought over the only two quality descriptions from the maps.uiowa.edu site. (OC and UCC)

The one other one seem to duplicate lactation/restroom information (CB)

**Comment by ABoston88** [comment]
Categories are filled out. The addition of four categories would be really helpful for the import:

Research
Services
Residence
Academic Building

Any other adjustments are pretty small and can be made in Concept3D. Taking a look at private/visible now. Agree with assumption that anything with a photo can be marked as visible.

**Comment by ABoston88** [comment]
Sorry, 4. Academic Building, as well. Added to list above.

**Comment by ABoston88** [comment]
Visibility column is filled out. 

There are a few duplicate columns highlighted in the spreadsheet. Can I delete the spare?

**Comment by joewhitsitt** [comment]
>There are a few duplicate columns highlighted in the spreadsheet. Can I delete the spare?

Yes! Good catch.

**Comment by joewhitsitt** [comment]
@mjoneill is going to reach out to Concept3D about the next step for this

**Comment by joewhitsitt** [comment]
The recent email from Concept3D is a bit disappointing. The additional fields (address, lactation rooms, gender-inclusive) are not neatly available in a feed. We might have to expand our existing data.its feed to massage this data into something Concept3D can consume.

Additionally, I think this confirms that the building common name is the unique identifier to align any data we want to sync. This historically been a weak link when buildings are renamed due to donations, etc.

**Comment by joewhitsitt** [comment]
In a bit, I will remove the additional columns (preserve it elsewhere) so that we can move forward with the initial import.

I guess though I have one question. Would it be worth combining this information and appending it to the description field for MVP until we can figure out the sync later on? The cost of doing this would be removing the addition from each building later on when synced info is provided. Thoughts @mjoneill and @ABoston88 ?

**Comment by joewhitsitt** [comment]
I made a copy of the spreadsheet in its-web's Drive and removed the additional columns from the spreadsheet we have been sharing around.

**Comment by mjoneill** [comment]
> I guess though I have one question. Would it be worth combining this information and appending it to the description field for MVP until we can figure out the sync later on? The cost of doing this would be removing the addition from each building later on when synced info is provided. Thoughts @mjoneill and @ABoston88 ?

I'm OK with this.

**Comment by joewhitsitt** [comment]
I have updated the spreadsheet to combine our "custom fields" into using the description field.

Examples:

```
The Old Capitol’s history began as the seat of the territorial government of Iowa. It became the University’s first permanent building in 1857 when the state legislature moved to Des Moines. In addition to being the administrative center of the University, at various times it was also the home of the law school, the library, a museum, a dormitory, and even a gymnasium. Today, it is the home of the Old Capitol Museum and serves as the centerpiece of campus.

Address: 1 North Clinton Street, Iowa City, IA 52242
Year built: 1840
Building abbreviation: OC
```

```
Address: 141 East Park Road, Iowa City, IA 52242
Year built: 2016
Building abbreviation: HA
Lactation room information: 1029A (Lactation Room)
Gender-inclusive restroom information: 1023, 1321, 1326, 2007, L006, L347
```

If this is okay, I think this sheet is ready to go.

**Comment by joewhitsitt** [comment]
Emailed Patrick (Concept3D) with the link to the spreadsheet

**Comment by joewhitsitt** [comment]
This is done, but manual follow-up work will be needed. I will add additional notes/findings from today's meeting to the epic.

<img width="494" alt="Screen Shot 2021-10-01 at 10 34 16 AM" src="https://user-images.githubusercontent.com/4663676/135648513-4b207c93-4b4b-4ed1-b072-2cbc37fe7010.png">
