### ISSUE TITLE
7 Day COVID Rolling Averages Chart

### ISSUE THREAD

**Issue by mjoneill** [uiowa/uiowa#4078]
As a visitor to the Covid By The Numbers page, I see a chart reflecting the Johnson County 7 day rolling average COVID-19 positivity rate vs. UI 7 day rolling average.

* Manual updates/screen capture is possible
* ~Is data in the BI data repository (could we automate this)?~ No.
* Can we get an informed mockup of how we would create the page on a dev site?

**Comment by mjoneill** [comment]
Turned this into an issue. Getting pulled in as unplanned, etc... 

@bspeare @briand44 @inspector508

**Comment by mjoneill** [comment]
I think a first slice is a mockup on dev on what this could look like so we can understand the accessibility issues and have a conversation with partners on what it would take to maintain this on an ongoing basis.

**Comment by GaryRidgway** [comment]
thought I'd take a look at some JS plotting ideas and this popped up as an option?

https://plotly.com/javascript/line-charts/

**Comment by joewhitsitt** [comment]
An accessibility workaround for most charts would be to just provide a properly formatted numeric table replicating the chart data, however PowerBI has previously not been able to provide us that kind of raw data.

**Comment by mjoneill** [comment]
This data is not coming in from PowerBI. 

This is manually curated spreadsheet.  Maintainer of the spreadsheet has volunteered to get us an image of the chart every publication day (if that's part of the solution space).

**Comment by mjoneill** [comment]
> An accessibility workaround for most charts would be to just provide a properly formatted numeric table replicating the chart data, however PowerBI has previously not been able to provide us that kind of raw data.

Indeed.  Discussed with client, and they are particularly eager to see a visual representation of the data, even if it means an image (which we then have to describe, contextualize, etc...)

**Comment by joewhitsitt** [comment]
Beyond the daily image and with powerbi out of the way, we could host the file somewhere or pull from somewhere and do a js render like Alan mentioned or we could add the data to the site and use https://www.drupal.org/project/charts which has Google Charts or Highcharts compatibility out of the box.

**Comment by mjoneill** [comment]
Bug?

<img width="821" alt="image" src="https://user-images.githubusercontent.com/7144234/134514935-84fc9b59-7363-4068-bcfb-35a58495e0b8.png">
