### ISSUE TITLE
Broken links message on Iowa Now

### ISSUE THREAD

**Issue by mjoneill** [uiowa/uiowa#4079]
As an editor of Iowa Now, I have a way to toggle a message at the top or at the bottom of old news articles.  Message says something like, "Links in this article are preserved for historical purposes, but the destination sources may have changed."

Iowa Now: a way to check if a link in a news article is broken and direct to an explainer page (the link you followed was correct when written and preserved for historical purposes..."

## Proposed Solution

- [ ] Add boolean to content type to toggle this message.
- [ ] Provide a configuration page to allow webmaster to customize the message.
- [ ] Create a custom block placed under main content that shows if boolean is true
- [ ] Use markup similar to drupal messages and drop the icon from display

## For Reference

https://inrc.law.uiowa.edu/admin/config/user-interface/inrc-config has a custom footer block that the editor can configure.

**Comment by mjoneill** [comment]
Joe Sherlock is our partner on this issue.

**Comment by briand44** [comment]
Ability to manually enable this message on individual articles

**Comment by briand44** [comment]
Is there an easy way to manually add this message with proper styles?

**Comment by joewhitsitt** [comment]
I think it is import to capture that this is an omega theme (bootstrap alerts styles would an extra lift, getting the theme to compile is an even bigger lift)

**Comment by briand44** [comment]
Message should be configurable for the site.

**Comment by briand44** [comment]
Potentially use Drupal_set_message().

**Comment by joewhitsitt** [comment]
If using drupal set message, this would be the warning version of it.
<img width="1035" alt="Screen Shot 2021-09-28 at 1 52 56 PM" src="https://user-images.githubusercontent.com/4663676/135148308-15df589c-3529-47bc-acf6-5baecae4aff0.png">

**Comment by mjoneill** [comment]
> If using drupal set message, this would be the warning version of it.
> <img alt="Screen Shot 2021-09-28 at 1 52 56 PM" width="1035" src="https://user-images.githubusercontent.com/4663676/135148308-15df589c-3529-47bc-acf6-5baecae4aff0.png">

Would it be possible to show that at the bottom of the article?

**Comment by joewhitsitt** [comment]
Uh, yeah it would be possible but it (`drupal_set_message()`) would no longer be the easy solution.

If it must be bottom, I would probably approach it differently with a custom block below main content. We could see if we could mimic the markup to achieve the same styling if that is okay, otherwise we will probably have to create a local css file because of the theme situation.

**Comment by mjoneill** [comment]
> would no longer be the easy solution

Gotcha. I worry that this feels to much like an error, so I'd push for below the article and a little toned down. Maybe the same thing without the exclam would feel better?  

I recognize that I'm pulling us out of a solution that seems within easy reach, and I don't want to take that step lightly.  @bspeare thoughts?  

If I'm the lone stick in the mud on this, we can loop in Joe and Tricia and get their thoughts.

**Comment by bspeare** [comment]
I think a custom block below the content makes more sense.   We could probably lose the icon and use the rest of the styles in Joe's screenshot.

**Comment by e-marie-w** [comment]
Could I start working on this, or am I better off waiting to pair with someone on it?

**Comment by briand44** [comment]
@e-marie-w if you feel like you understand how to move forward, I would say go for it.

**Comment by e-marie-w** [comment]
SHOOT did not realize it was v1. (It didn't look like normal v3 but it had the right icon in the browser tab I feel betrayed). Sorry for the false excitement, I still don't have d7 stuff set up so I guess I can't.

**Comment by bspeare** [comment]
This has been deployed to the live site:

You can edit the custom link message here: https://now.uiowa.edu/admin/structure/block/manage/block/6/configure

On each "News Feature" there is a custom checkbox at the bottom of the page that will control the visibility of the expired links message:

<img width="1534" alt="Screen Shot 2021-10-05 at 12 47 36 PM" src="https://user-images.githubusercontent.com/1036433/136076247-7613547e-3d97-4dd8-9e94-c903667ea83e.png">


Once checked, the message will appear at the bottom of the page:

<img width="1524" alt="Screen Shot 2021-10-05 at 12 48 27 PM" src="https://user-images.githubusercontent.com/1036433/136076270-c3c8c155-e13d-4958-ac96-7314c06e6432.png">

**Comment by bspeare** [comment]
Met with Tricia and Joe this morning to demo the feature.  I added this field to the "Achievement" and "News Feature" and it is now live on now.uiowa.edu.  Closing this issue for now.
