### ISSUE TITLE
Docs - Policies - General Caching

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#408]
### Problem

As a follow up to #356, we need to write a policy about general caching on our Drupal 8 service. By default we cache pages up to six hours. Explain the various triggers that clear the site/page cache and the potential issues related to files and browser cache.

**Comment by joewhitsitt** [comment]
After talking with Rick, we should probably block this until we have a better understanding of the cache layers in D8, test uiowa events and possibly provide site owners with the acquia purge button.

**Comment by richardbporter** [comment]
Cache tags should invalidate purged assets more intelligently than D7. Custom integrations that don't implement cache tags or are time-based can't really be documented generally. Another reason to use JS.
