### ISSUE TITLE
Narrow container option doesn't work after removing sidenav

### ISSUE THREAD

**Issue by bewoldt** [uiowa/uiowa#4080]
# Problem
If you have a page that has sub-pages and you check the option to Remove sidebar regions to hide the side-nav, when you change the layout of the content container to use the Narrow option the css styles get overridden.

Example page:
https://mentalhealth.uiowa.edu/recovery
This page has sub-pages, is set to use the Narrow content container width, and has the side-nav turned off.

**Comment by bspeare** [comment]
# Proposed Solution

Update https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/scss/global.scss#L205 with `sidebar-invisible` class:

```
  .page__container--narrow,
  .page__container--narrow.sidebar-invisible {
```

**Comment by bewoldt** [comment]
@bspeare Is the the expected result if you have a narrow container that has a sidebar region? If so, this will need a fix too.


<img width="1251" alt="Screen Shot 2021-09-22 at 11 35 48 AM" src="https://user-images.githubusercontent.com/731952/134387292-60c581aa-7b85-49fa-b6a2-f7c6e399f477.png">
