### ISSUE TITLE
Replace AoS Search Block on Admissions with uiowa_core SearchBlock

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#4082]
## Issue

We made a search block in uiowa_core that does what the aos search block does on admissions. admissions is the only site using the AoS search block. Let's reduce that to one.

## Proposed solution

- [x]  Update content type description to stop referencing view page and instead mention the "Areas of Study" block.
- [x]   Now that the uiowa_core search block is available. remove the current block from admissions homepage (prod), add the uiowa_core block and configure to point to the same /areas-of-study destination.
- [x]  Find usage on the site. I think there is one tucked away somewhere. We have past update hook code that can look for instances.
- [x]  Delete area_of_study_search block content type from split
- [x]  Update permissions to not include areas_of_study_category? Taxonomy vocabulary doesn't exist?
- [ ]  Sync changes (db) to stage/dev so we don't have missing block errors.
- [x]  Remove block from areas of study module

**Comment by joewhitsitt** [comment]
This can actually cause an error if placed on a non-admissions site as the hardcoded view page used to send the search does not exist in the feature split.

<img width="283" alt="AoS-heads-up" src="https://user-images.githubusercontent.com/4663676/133153645-6956f4e7-a1ec-4ebe-bd98-ae269dd59b37.png">

**Comment by briand44** [comment]
This block should remain on Admissions

**Comment by bspeare** [comment]
@joewhitsitt for "Sync changes (db) to stage/dev so we don't have missing block errors." before I do this, is there anything on the stage/dev that needs to be saved before they are overridden?

**Comment by bspeare** [comment]
We added an update hook in https://github.com/uiowa/uiowa/pull/4139 that just removes the block from the page revisions on admissions.uiowa.edu so the block would not be available if they wanted to revert the home page to a previous revision.  We need to check with the client to see if this would be OK.

**Comment by bspeare** [comment]
Client is OK with losing the block from page revisions in the update hook, so I will move forward with getting the pr reviewed.
