### ISSUE TITLE
Events content overflowing in Safari

### ISSUE THREAD

**Issue by makurj** [uiowa/uiowa#4085]
# Problem
Events info is overflowing into the next event in the next event doesn't have an image in Safari (Version 14.1.2). It's fine in Chrome.

https://tippie.prod.drupal.uiowa.edu/events

Safari:
![image](https://user-images.githubusercontent.com/52135878/132568368-62d70575-ec64-4439-9e7a-9a6c8a53c358.png)
![image](https://user-images.githubusercontent.com/52135878/132568731-1cd3d54c-bc96-42d0-8c86-3682d048c380.png)

Chrome:
![image](https://user-images.githubusercontent.com/52135878/132568415-f1700345-392d-4e84-813f-19927b1e4944.png)

# Known Issue
https://sitenow.uiowa.edu/known-issues#uiowa-issue-4085

**Comment by joewhitsitt** [comment]
As a short term step, we could create a known issue https://sitenow.uiowa.edu/known-issues with the workaround, "use list for best browser compatibility"

**Comment by bspeare** [comment]
This is an issue with Safari (https://stackoverflow.com/questions/30169301/undocumented-word-break-break-word-css-property) not respecting the current `word-wrap` property.   Fixing this we would need to make a change like this:

```
.card__description {
word-wrap: anywhere;
overflow-wrap: anywhere;
word-wrap: break-word;
word-break: break-word;
}
```

**Comment by makurj** [comment]
So should we do the fix or create a known issue now?

OR

Create a known issue for right now? And apply the fix when the bug gets prioritized?

**Comment by bspeare** [comment]
It should be a known issue when a long text string like a zoom link is included in the event description for Safari.

**Comment by makurj** [comment]
Sounds good. I'll create a known issue for it for now.

**Comment by makurj** [comment]
Known issue created. https://sitenow.uiowa.edu/known-issues
