### ISSUE TITLE
Investigate large D7 databases and reduce size if possible.

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#4087]
There are quite a few large D7 databases as posted in Slack. 

- https://iowaweb.slack.com/archives/C8SM82ZFZ/p1631116101046400 (701)
  - no sites over 150 MB 
- https://iowaweb.slack.com/archives/C8SM82ZFZ/p1631114232039100 (702)
  - content.uiowa.edu >> 631.98 MB - _nrd was not configured. configured to 10 for all content types. scfc enabled and configured every hour. - jwhitsit_
  - iowalakesidelab.org >> 394.79 MB - _nrd was not configured for all types (news, person, webform (50)). configured to 10 for all content types. also purged over 10 candidate nodes' revisions. scfc enabled and configured every hour. - jwhitsit_
  - ~~jacobsoninstitute.org >> 3403.75 MB~~
  - www.iowajpec.org >> 112.34 MB - _nrd was not configured for one content type (news (10)). configured to 10 for all other content types. - jwhitsit_
- https://iowaweb.slack.com/archives/C8SM82ZFZ/p1631114822042600 (703)
  - dsp.research.uiowa.edu >> 659.09 MB - _nrd was not configured for one content type (news (10)). configured to 10 for all other content types. also purged over 100 candidate nodes' revisions. scfc enabled and configured every hour. - jwhitsit_
  - education.uiowa.edu >> 271.15 MB - _nrd was not configured for all types. configured to 10 for all content types. also purged over 45 candidate nodes' revisions - jwhitsit_
  - grantbulletin.research.uiowa.edu >> 369.39 MB _nrd was not configured. configured to 10 for all content types. no immediate candidate nodes. scfc enabled and configured every hour. - jwhitsit_
  - inrc.law.uiowa.edu >> 253.39 MB - _nrd was already configured, scfc already enabled/configured. - jwhitsit_
  - international.uiowa.edu >> 356.16 MB - _nrd was already configured. purged over 6 candidate nodes' revisions. scfc enabled and configured every hour. - jwhitsit_
  - its.uiowa.edu >> 301.44 MB - _nrd was already configureds. scfc enabled and configured every hour. - jwhitsit_
  - library.law.uiowa.edu >> 271.02 MB - _nrd was not configured for all types. configured to 10 for all content types. also purged over 63 candidate nodes' revisions - jwhitsit_
  - now.uiowa.edu >> 1628.07 MB - _nrd was already configured however, there are 2390 candidate nodes' revisions (as of 9:45 10/21). i have increased how many and how often are removed. not going to try to purge this in one go. scfc enabled and configured every hour. - jwhitsit_
  - pharmacy.uiowa.ed >> 176.74 MB - _site was removed_
  - recserv.uiowa.edu >> 182.30 MB - _nrd was already configured - jwhitsit_
  - tippie.uiowa.edu >> 469.70 MB -_nrd was not configured for all types. configured to 10 for all content types. scfc enabled and configured every hour. - jwhitsit_
  - www.engineering.uiowa.edu >> 293.15 MB - _nrd was already configured at 50 per content type. site going away soon. - jwhitsit_
- dentistry >> 240.99 MB 
- https://iowaweb.slack.com/archives/C8SM82ZFZ/p1631115539045600 (icgov)
  - default >> 249.50 MB 
- https://iowaweb.slack.com/archives/C8SM82ZFZ/p1631116053046100 (nursing)
  - default >> 164.72 MB 
- https://iowaweb.slack.com/archives/C8SM82ZFZ/p1631116970047500 (clas)
  - physics.uiowa.edu >> 270.72 MB
  - default >> 539.72 MB
  - english.uiowa.edu >> 184.40 MB
  - instructional-resources.physics.uiowa.edu >> 201.35 MB
  - psychology.uiowa.edu >> 240.20 MB
  - stat.uiowa.edu >> 192.23 MB
- https://iowaweb.slack.com/archives/C8SM82ZFZ/p1631117215047800 (grad)
  - admissions >> 546.81 MB
  - gc >> 332.10 MB
  - gss >> 151.79 MB
  - placement >> 540.75 MB
  - urban >> 864.05 MB

### Proposed resolution
1. Determine if the site/database can be deleted.
2. Investigate why the database is large using the docs linked below.
3. Take steps to reduce the size, if possible.

- https://support.acquia.com/hc/en-us/articles/360005251714-Keeping-the-cache-form-table-to-a-reasonable-size
- https://support.acquia.com/hc/en-us/articles/360059891074-Managing-your-Drupal-database-revision-table-

Running the SQL query in the second link would give us insight into whether its one or both of these issues. Configuring NRD in prod for all content types to keep 10 or so revisions and ensuring cron is running will reduce size over time.

**Comment by richardbporter** [comment]
I did the first option for jacobsoninstitute.org and reduce DB size quite a bit.

**Comment by richardbporter** [comment]
Moved previous console output to O365: https://iowa.sharepoint.com/:f:/r/sites/CSI-Drupal2/Shared%20Documents/Acquia%20Database%20Usage?csf=1&web=1&e=0phl0q

**Comment by briand44** [comment]
still need to identify a clear scope here. How many db's do we try and address?

**Comment by joewhitsitt** [comment]
>Moved previous console output to O365

Ugh.. didn't see this. See issue summary for 150 MB+ dbs

**Comment by briand44** [comment]
Start with largest and work through them. If we need to turn on Node Revision Delete, 10 is a good number of revisions to keep.

**Comment by briand44** [comment]
jacobsoninstitute and inrc.law are examples of where a cron job has been setup to clear the cache but that might not be needed for most.

**Comment by richardbporter** [comment]
There is a script in each application that can be run on one site or all sites with Drush to get database size info:
`drush -l mysite.uiowa.edu php-script ../drush/dbsize.php`
`drush @sites php-script ../drush/dbsize.php`

**Comment by joewhitsitt** [comment]
Going to start looking at a few. Folks are welcome to join

**Comment by joewhitsitt** [comment]
Took the opportunity to also purge orphans on some big v2 sites:

law: Paragraph: Deleted 122 orphan revisions
brand: Paragraph: Deleted 434 orphan revisions
hr: Paragraph: Deleted 127 orphan revisions

might be worth considering running this periodically on sites now that the drush command has been created and [released](https://www.drupal.org/project/entity_reference_revisions/releases/8.x-1.9). https://github.com/uiowa/uiowa/pull/4252

**Comment by joewhitsitt** [comment]
Configured node_revision_delete for most of the IS's websites. now.uiowa.edu has quite a few candidates. watching for a dip. If it doesn't dip, might need to manually batch run it off-hours.

Used the 300 MB+ as the base line for safe cache form clear to be enabled and configured.

Going to wait and see how these change db sizes and if there are new big offenders that need attention.

**Comment by joewhitsitt** [comment]
Manually cleared cache_form on:

inrc.law = 1518.64 to 118.51
dsp.research = 777.99 to 131.11
iowalakesidelab 383.55 to 31.39
engineering 456.33 to 250.25

hoping scfc can keep up now, but if inrc is any indication (running every minute), we will have to watch some of these and manually truncate.

**Comment by joewhitsitt** [comment]
manually running nrd on now.uiowa.edu via drush

**Comment by joewhitsitt** [comment]
now.uiowa.edu got bigger... 🤦 

1620.94 to 1819.68

for all of the revisions that nrd got rid of does it keep a record of greater size?

+600 MB in field_body_revision table alone

This site also has search api and is indexing a bunch of stuff. Not sure if that feature is needed.

**Comment by joewhitsitt** [comment]
Updated https://iowa.sharepoint.com/:f:/r/sites/CSI-Drupal2/Shared%20Documents/Acquia%20Database%20Usage?csf=1&web=1&e=0phl0q with refreshed db size info for 701-3.

I think we should periodically check some of these dbs just in case there is a runaway cache_form table, but closing this issue for now. For example, inrc.law jumped up again.
