### ISSUE TITLE
Docs -  Policies - Video

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#409]
### Problem

As a follow up to #356, we need to write a policy about how we don't allow video uploads to the site and that we provide oEmbed options instead (e.g. YouTube, Vimeo, Kaltura (TBD)). Videos are large files that our service is not equipped to handle.

Additionally, we should point out that to maintain accessibility, transcripts/captions should be included with those remote videos.

**Comment by ethanstjohn** [comment]
https://docs.sitenow.uiowa.edu/policies/ I have added suggested documentation.
