### ISSUE TITLE
Export Education people to CSV

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#4114]
Education would like to export people from their existing site into a csv to import into directory profiles. 

Fields to be included:
- First Name
- Last Name
- Working Title
- Rank - Should only be exporting staff, graduate students, temporary staff
- Image - ideally they would prefer the actual files named <hawkid.jpg> but if we only have url's that will work.
- Bio
- Areas of Expertise
- Email
- Office Number
- Building Location
- Phone
- Affiliations

There are some example csv's https://git.uiowa.edu/java/profiles/-/issues/279.

**Comment by joewhitsitt** [comment]
views data export should be able to do this

**Comment by briand44** [comment]
Got confirmation that we can just dump all this to one CSV with multi-valued fields just having a separator. We will want to share this with Suzanne Malo as soon as we have something so they can react to it.

**Comment by dnkemper** [comment]
If need to duplicate/do again, here is view file that resembles changes: [education_person_views.views_default.inc](https://iowa.sharepoint.com/:u:/r/sites/CSI-Drupal2/Shared%20Documents/General/education_person_views.views_default.inc?csf=1&web=1&e=UkS7xQ)
