### ISSUE TITLE
Docs - Policies - Updating the platform

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#412]
### Problem

As a follow up to #356, we need to write a policy about updating our platform whether it is releasing new features, theme changes, security updates or underlying tech updates (php, symphony, javascript libraries). Talk about possible down time, loss of functionality, customer review/test process.

**Comment by ethanstjohn** [comment]
https://github.com/uiowa/uiowa/blob/gh-pages/policies/index.md
