### ISSUE TITLE
SLIS - Export Alumni data from SLIS D7 site

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#4120]
# Motivation

SLIS is not carrying forward their alumni listing feature with the launch of their SN3 site. However, they would still like to retain the data to feed back into their existing data about alumni.

# Proposed solution

Build a view to export the data as a CSV file.

or

Write a SQL query to export the data as a CSV file.

**Comment by pyrello** [comment]
Blocker for #6119

**Comment by briand44** [comment]
No longer relevant. SLIS D7 no longer exists.
