### ISSUE TITLE
Local tasks underline renders on pages without edit tabs

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#4121]
# Problem 

Local tasks underline renders on pages without edit tabs

<img width="1467" alt="Screen Shot 2021-09-14 at 10 00 37 AM" src="https://user-images.githubusercontent.com/1036433/133282543-237117a7-d695-4a8f-889e-ee3e133f2077.png">

# Proposed Solution

Adjust border to just appear on `.tabs li` so that the edit tab underline will not appear on pages without edit tabs. 

**Before**

<img width="1406" alt="Screen Shot 2021-09-14 at 10 02 19 AM" src="https://user-images.githubusercontent.com/1036433/133282930-0bf9cc85-da31-4dc8-a78b-c0557d3082eb.png">

**After**

<img width="1412" alt="Screen Shot 2021-09-14 at 10 02 51 AM" src="https://user-images.githubusercontent.com/1036433/133282960-c645adfd-c883-4dfe-ad18-0373063c68f9.png">

**Comment by richardbporter** [comment]
ew
