### ISSUE TITLE
Admissions area of study teasers card display are a little broken

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#4123]
# Problem
It looks like the addition of the teaser template for the Areas of Study disrupted the cards on https://github.com/uiowa/uiowa/blob/84f376dffba781b1142635cbfb6cdd0f982ab7a1/docroot/modules/custom/uiowa_area_of_study/templates/node--area-of-study--teaser.html.twig. 

<img width="1640" alt="Screen Shot 2021-09-14 at 4 27 45 PM" src="https://user-images.githubusercontent.com/1036433/133336527-fd0b52ea-2e89-4d7b-99e9-c20632de1426.png">

# Steps to reproduce
Go to https://admissions.uiowa.edu/academics/biz-econ-mgmt and compare against https://web.archive.org/web/20210812002345/https://admissions.uiowa.edu/academics/biz-econ-mgmt

<img width="1545" alt="Screen Shot 2021-09-14 at 4 32 28 PM" src="https://user-images.githubusercontent.com/1036433/133336875-c8f3932f-31e3-400d-9dd4-8ef9acebc801.png">

# Proposed solution
Update admissions to use the correct card template and styles.

**Comment by joewhitsitt** [comment]
Yikes. This should could also be solved if we can turn the module off on admissions. I think this block was the last piece https://github.com/uiowa/uiowa/issues/4082

**Comment by bspeare** [comment]
https://github.com/uiowa/uiowa/issues/4082 Sounds like a good plan.  Let's just make sure to test this page in that pr.
