### ISSUE TITLE
AoS block only shows 10 items when view config is set to show all

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#4124]
# Problem
The AoS block is limiting results to 10 items but the view config is set to display all items with no pager.

# Steps to reproduce
```
blt sync --site desmoines.uiowa.edu &&
drush @desmoines.local uli
```

See that there are more than 10 results on https://desmoines.local.drupal.uiowa.edu/admin/structure/views/view/areas_of_study/edit/areas_of_study_block but that only 10 show up on https://desmoines.local.drupal.uiowa.edu/areas-study-program-finder.

# Proposed solution
TBD

**Comment by bspeare** [comment]
I think this needs to change to:

<img width="611" alt="Screen Shot 2021-09-15 at 9 29 38 AM" src="https://user-images.githubusercontent.com/1036433/133452767-1b06fae4-2815-4b99-97d5-33c404adf900.png">
