### ISSUE TITLE
Events list block

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#4126]
Blocked until https://github.com/uiowa/uiowa/issues/4305

# Story

As an admissions editor, I would like the ability to dynamically display local event content within a page.

# Proposed Solution

_Build off the default site with event feature enabled first!_

- [x] Establish new view block in events split.
- [x] Add to card-related LB styles
- [x] Use generalized card list template and preprocess unique fields into the correct place in the card
- [x] Extend to admissions split

# Follow-up

- Part of our strategy to consolidate event functionality https://github.com/orgs/uiowa/projects/1#card-63850273

**Comment by briand44** [comment]
Establish new view block in events split. Account for styling, etc.

**Comment by briand44** [comment]
possibly generalize template more?

**Comment by briand44** [comment]
Part of feature split for all as well as Admissions.

**Comment by makurj** [comment]
I'd like to work/pair on this.

**Comment by joewhitsitt** [comment]
Part of our strategy to consolidate event functionality https://github.com/orgs/uiowa/projects/1#card-63850273
