### ISSUE TITLE
Thank You Program

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#4127]
The College of Pharmacy would like to automate their thank you program similar to the existing OneIT thank you program.

Their existing manual process is:
User fills out webform to submit a thank you
Webform generates email to Pharmacy staff council
Pharmacy manually sends templated email (see below) to staff being thanked as well as to the staff members supervisor.

They would like the webform submission to continue to send email to Pharmacy staff council as well as trigger a lookup of the staff members supervisor based on staff members email, trigger an email to be sent from dispatch to the supervisor and staff member.

The email template in dispatch would include who it is being sent to, who it is from (person submitting webform), image, the message from the webform and some text saying that the staff members supervisor has also been notified. The email from would be College of Pharmacy Staff Council and the subject would be "[Name], You've been thanked!" 

We have existing functionality on the OneIT website (https://oneit.uiowa.edu) that does this same thing and we will likely need to account for this functionality on that site when it moves to V3.

My main concern here is if we have access to get Pharmacy Supervisor information from HR or if the current endpoint that is available to us is only for OneIT staff/supervisors.

**Comment by briand44** [comment]
![Screen Shot 2021-09-15 at 10 49 56 AM](https://user-images.githubusercontent.com/1017022/133468355-579b6055-5a93-47ba-85eb-7303a5abed0f.png)

**Comment by briand44** [comment]
Could we potentially combine the dispatch templates into one or use an existing branded template?

**Comment by briand44** [comment]
Would Workflow be a better option?

**Comment by briand44** [comment]
Marking this as blocked until we learn more about if Workflow is a better option.

**Comment by briand44** [comment]
Reached out to the OneIT website folks about why we didn't use Workflow previously.
>Hi, Brian,
We definitely did not want Workflow, and yes we talked about it a great deal back then.  Our reason: Workflow requires approvers.  We did not think it was something that needed anyone’s approval, and that it would just create more work for HR and supervisors, without real benefit.  We like how the thank you program we have is sent directly, it frees up time and labor by HR and supervisors.  We also didn’t like the aesthetic/look of the Workflow output.  Some supervisors and HR staff receive dozens of Workflow items a day, and it looked like just another work item, rather than standing out more in an email (as we do currently).

**Comment by briand44** [comment]
There is some additional info about the API contacts on the Wiki https://wiki.uiowa.edu/display/drupaldev/On-premise+server+ACL

**Comment by briand44** [comment]
Reilly Williams is the contact for Pharmacy who is asking for this.

**Comment by richardbporter** [comment]
I'm not sure how the original form works exactly but I'd be curious if the webform remote POST handler could work for this.

**Comment by briand44** [comment]
I reached out to HR to see if they would entertain a campus wide solution and if not if the API we use is open to more than just OneIT staff/supervisors.

**Comment by briand44** [comment]
>HR has encouraged Colleges and Administrative Orgs to establish and administer local rewards and recognition programs.

>the API endpoint should work across Orgs and isn’t just restricted to One IT

**Comment by cory-skeers** [comment]
Followup notes:

Plan is to have the thank you form be placeable as a block (similar to the transportation calculator), allowing for it to be added to an otherwise fully customizable page. This would allow for the option to place multiple blocks throughout a site, but all blocks will be tied to the same base configuration (ie user won't have the option to have one page with a thank you that goes to one group or is tied to one campaign, and a second page that goes to a different group).

**Comment by quamsta** [comment]
Few notes/ideas for a future slice based on some things we learned/needed while doing a similar project for the DSL Intranet:

- Ability for site editor to adjust the terminology of "Thank You," since other units may want to send things like "High Five," etc
- Ability to optionally publicly display a list of Thank Yous
- Option to not do the supervisor notification and send a Thank You directly, only notifying that person
- Customize the email being sent through Dispatch

A few screenshots of our work:

<img width="1379" alt="Screen Shot 2021-10-22 at 9 40 21 AM" src="https://user-images.githubusercontent.com/472923/138473796-8968718e-641d-43ca-a8cb-b81b4c5f9cd6.png">
<img width="1378" alt="Screen Shot 2021-10-22 at 9 42 51 AM" src="https://user-images.githubusercontent.com/472923/138474219-31e53313-54b9-4494-8a53-0e1be5e6cdeb.png">

**Comment by richardbporter** [comment]
The template.html file in the D7 oneit_thankyou module looks to be very similar to what is in the _OneIT Thank You Recipient_ email template on Dispatch. I'm guessing it was just versioned in the repo and copied/pasted. It is slightly different though, so I think we can ignore that file and just use what is in the Dispatch UI.

https://apps.its.uiowa.edu/dispatch/templates/586370992

**Comment by richardbporter** [comment]
> There is some additional info about the API contacts on the Wiki https://wiki.uiowa.edu/display/drupaldev/On-premise+server+ACL

Just noting that all applications in prod are on the same hardware so no modifications to the ACL should be needed.

**Comment by richardbporter** [comment]
> the API endpoint should work across Orgs and isn’t just restricted to One IT

I'm taking this to mean that any site that wants this feature would use the same HR API credentials. If that is true, I think we could store those credentials in [the secrets file](https://docs.acquia.com/resource/secrets/#secrets-settings-php-file) instead of settings form config.

**Comment by richardbporter** [comment]
> Could we potentially combine the dispatch templates into one or use an existing branded template?

I think so, yes. We could set up a new, generic campaign/template/etc. for D9 and we'd select that in the module config when setting this up on new sites. Using an on-brand template in Dispatch seems like a good idea. 

> Customize the email being sent through Dispatch

The current module config would allow for this just by selecting different campaign/templates/etc.

**Comment by cory-skeers** [comment]
> > Customize the email being sent through Dispatch
> 
> The current module config would allow for this just by selecting different campaign/templates/etc.

As long as the templates use the same `toName`, `toAddress`, and `message` variables, any campaign/template can be used. Looks like this would cover the use cases we've seen so far, but a future slice could open this up to more customizability with more/different inputs if needed.

**Comment by richardbporter** [comment]
Found the pharmacy form which has a couple extra fields but is essentially the same thing: https://pharmacy.uiowa.edu/form/thank-you-program

**Comment by richardbporter** [comment]
There is currently an issue with certain placeholders on the UI 1 row x 1 col - Version 2 template. Dispatch support is working to resolve.

**Comment by richardbporter** [comment]
I think we should use data its for a shim to make this easier to develop. The shim can store the HR credentials but require an access token to use.

**Comment by richardbporter** [comment]
Todo:

- [x] Determine and add [additional placeholders](https://apps.its.uiowa.edu/dispatch/help/curatedtemplate/UI%201%20row%20x%201%20col%20-%20Version%202) to settings form and update Dispatch template to use variable names.
- [x] Create data.its API shim to query HR data. 
- [x] Remove HR creds from settings form and replace with check for access token. Access token should be set in secrets files.
- [x] Remove Dispatch API key, campaign and communication from settings form and replace with check for secrets file config override.
- [x] Refactor module to use sitenow_dispatch wherever possible.

**Comment by richardbporter** [comment]
@cory-skeers Would you mind if we move this block and form into sitenow_dispatch actually?

**Comment by cory-skeers** [comment]
> @cory-skeers Would you mind if we move this block and form into sitenow_dispatch actually?

Not at all!

**Comment by cory-skeers** [comment]
Additional placeholder: Image header. Potentially add a file field to the settings form, and that can be used to pass the image url into the template.

**Comment by richardbporter** [comment]
> Determine and add additional placeholders to settings form and update Dispatch template to use variable names.

Talked in standup about pumping the brakes on this one until the Dispatch issue is resolved with placeholders in curated templates.

Additional things we can do before moving this to blocked/waiting:

- [x] Implement headline field on block (@richardbporter)
- [x] Make CC supervisors optional via config (@cory-skeers)
- [x] Make Dispatch service more similar to uiowa_maui/MauiApi (@richardbporter)
  - [x] Merge get/post into one request method
  - [x] Set API base and trim slashes
- [x] Catch supervisor 404 exception on form validate and output a different message. This indicates that no supervisors were found for the email entered. Seems like we should inform people of that. (@richardbporter)
- [x] Wire up spam prevention form field(s). (@richardbporter)
- [x] Check that the right styling is being added (Add webform classes? Right now it isn't adjusting appropriately to different section backgrounds.)
   - Partially complete, partially waiting on #4385 and #4387

**Comment by richardbporter** [comment]
Customer feedback:
- Stock image is ok for now but needs to be customizable in the future. This is blocked for now.
- [x] Adjust thank you email to note that a copy is being sent to supervisor if config is set.
- [x] Add config option to send copies to additional arbitrary email addresses.
- [ ] ~~Adjust thank you form to disclose to end user that a copy is being sent to supervisor and/or additional email addresses if config is set.~~

Last note I had was to highlight the employee's supervisor in the messages to additional emails. I wonder if just might be easier to build the logging and admin interface right now instead of doing that. I can see the email logic getting fairly complex and it sounds like they'd prefer the admin interface in the long run. Thoughts @cory-skeers ?

**Comment by cory-skeers** [comment]
> Last note I had was to highlight the employee's supervisor in the messages to additional emails. I wonder if just might be easier to build the logging and admin interface right now instead of doing that. I can see the email logic getting fairly complex and it sounds like they'd prefer the admin interface in the long run.

I think we could append a note listing the supervisor to the additional emails fairly easily, as long as it's always included in the additional emails (assuming the supervisor copy is being sent), and always with the same note (no option to configure, just if it's being sent to additional emails and a supervisor copy is used, the same message of "This was sent to XX@XX supervisor" appended. Anything more than that could get complex quickly though, especially if nested placeholders don't work.

The other bonus of starting with the logging/admin interface would be that it could have a true record of all thank yous sent. It didn't sound like it would be a major issue for them if they didn't have logs of thank yous sent prior to the admin interface, as long as they'd had the emails to keep track of, but I could also see that as being a data collection option you don't think you need until you do.

Even if the logging is put into place right away, the admin interface and CSV export pieces could continue to be improved and built out as future slices, I'd think.

**Comment by briand44** [comment]
Lets finish the items in the checkboxes and we can revisit the logging dashboard and exporting in a future slice.

**Comment by richardbporter** [comment]
>Add config option to send copies to additional arbitrary email addresses.

I've added a single value field for right now as Drupal does not yet support the `#multiple` attribute for `email` inputs. A single additional email might be enough though based on our meeting the other day.

**Comment by richardbporter** [comment]
>Adjust thank you form to disclose to end user that a copy is being sent to supervisor and/or additional email addresses if config is set.

Seems odd to disclose the additional email address to the public. I'm not going to do this one.

**Comment by richardbporter** [comment]
Running into an issue trying to set the footer statement placeholder only in the recipient message to note that a copy was sent to the supervisor(s). I can't seem to get the Dispatch syntax right for checking placeholder existence. Reached out to support.

**Comment by richardbporter** [comment]
We might just have to remove all optional placeholders for now until that is resolved. This will also require modifying the message instead of using another placeholder for the note re: CC to supervisor.

**Comment by richardbporter** [comment]
Followup issues: #4572 #4571
