### ISSUE TITLE
Enable/Configure Core Media Audio

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#413]
### Problem
We currently don't have a way to place audio on our sites. In D7 we provided SoundCloud oEmbed support, but it was rarely used (one site, two embeds). For this and other reasons we will not be adding SoundCloud support in D8. We have identified a use-case were uploaded audio would be beneficial and after talking with Acquia about performance concerns think we can move forward with enabling Audio files for all sites.

### Proposed Solution
Update permissions for editor, publish, webmaster to upload/manage core media audio files similar to files. Update the media_wysiwyg entity browser to allow audio uploads and picking from the media library. Update other media related views to make sure audio files are filterable/selectable.

Set maximum upload size to 50 MB (current server max?) for MVP.

Look into the current accessibility state of the core media audio type and document any shortcomings.

Consider adding an optional transcript field if not already present to the audio media type to provide an accessible fallback and display that transcript out of the way but accessible near the audio player on render.

### Test
Make sure that roles on the site can successfully upload, manage, place audio files and that anonymous users can play/interact with audio files. Test whether the player controls are mouse/keyboard accessible. Test whether the included transcript is accessible by clicking and keyboard. Evaluate the allowed file types and whether they can be successfully be listened to through the player on all the major browsers.

**Comment by dnkemper** [comment]
Testing: 

1. Structure -> Media types -> Make sure audio is listed as an option
2. Content -> Media -> Add media -> Audio -> add an audio file (Add name + add audio file) -> save
3. Make sure audio file shows up on Grid/Table views (where you're redirected after you save) 
4. Use the filters located in the 'Grid' section of the existing media, and select 'Audio' as the media type and make sure it filters correctly 
5. Now go to a page -> edit text w/ wysiwyg -> select media option in wysiwyg toolbar -> Add audio from the Media library -> Save page -> Make sure it displays
6. Edit page again -> edit text w/ wysiwyg -> select media option in wysiwyg toolbar -> Select 'Upload Audio' option -> upload new audio -> save page and make sure the new audio displays


P.S Might need to update your php.ini file in your local environment to increase MB size
P.S.S. You're welcome for the Taylor Swift song :) 
[Taylor Swift - You Need To Calm Down.mp3.zip](https://github.com/uiowa/uiowa/files/3506141/Taylor.Swift.-.You.Need.To.Calm.Down.mp3.zip)
[Afternoon Delight.mp3.zip](https://github.com/uiowa/uiowa/files/3506143/Afternoon.Delight.mp3.zip)

**Comment by joewhitsitt** [comment]
testing

**Comment by joewhitsitt** [comment]
Merged
