### ISSUE TITLE
As a SiteNow customer, I can enter my site name on the site request form 

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#4140]
# Story

As a SiteNow customer, I can enter my site name on the site request form so that I don't have to manually change it in the system settings. 

# Proposed solution

Add a required Site Name field on https://sitenow.uiowa.edu/request-site that will set the `site_name` value on install.

**Comment by joewhitsitt** [comment]
additional context: https://github.com/uiowa/uiowa/issues/2795#issuecomment-921265406

**Comment by joewhitsitt** [comment]
Related https://github.com/uiowa/uiowa/issues/2121

**Comment by richardbporter** [comment]
I think this could work similarly to the requester where it is an option set for the `blt uiowa:multisite:create` command, set in the site's blt.yml file and then parsed and set via Drush after the site is installed.

https://github.com/uiowa/uiowa/blob/ba6a026cf40f7683a7749f95337582eeb5b64115/blt/src/Blt/Plugin/Commands/MultisiteCommands.php#L400-L421

https://github.com/uiowa/uiowa/blob/ba6a026cf40f7683a7749f95337582eeb5b64115/blt/src/Blt/Plugin/Commands/MultisiteCommands.php#L601-L604

https://github.com/uiowa/uiowa/blob/ba6a026cf40f7683a7749f95337582eeb5b64115/blt/src/Blt/Plugin/Commands/MultisiteCommands.php#L982-L994

Then the request form could be updated to output the new command like `blt uiowa:multisite:create foo.com --requester bar --site-name baz` or something like that.

**Comment by joewhitsitt** [comment]
Started to capture this information on the form in PROD:

<img width="567" alt="Screen Shot 2022-03-25 at 4 17 45 PM" src="https://user-images.githubusercontent.com/4663676/160202090-188254a9-71cf-4e91-b2a0-ebecdda5ba43.png">
<img width="747" alt="Screen Shot 2022-03-25 at 4 18 22 PM" src="https://user-images.githubusercontent.com/4663676/160202092-33214996-fd49-4159-8a61-dd8550cee105.png">
<img width="397" alt="Screen Shot 2022-03-25 at 4 18 54 PM" src="https://user-images.githubusercontent.com/4663676/160202093-c3fa663e-96ff-4927-a22b-7092f726502f.png">
