### ISSUE TITLE
Timeline date positioning is off

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#4147]
# Problem
Timeline date positioning is off and needs some CSS adjustments. 

# Steps to reproduce
Go to https://175.prod.drupal.uiowa.edu/milestones-university-iowa-history. 

<img width="1431" alt="Screen Shot 2021-09-20 at 1 46 33 PM" src="https://user-images.githubusercontent.com/1036433/134057405-e621df66-dbb6-46b1-ba87-903e001298f8.png">

# Proposed solution
Test with https://175.prod.drupal.uiowa.edu/milestones-university-iowa-history and adjust CSS in https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/scss/components/timeline.scss

**Comment by mjoneill** [comment]
@bspeare, B.Hill just reached out with the following:

> random update, it looks like the timeline issue- with the date being concealed by the icon- was caused by my setting the section's container width to Narrow, and that reverting to Normal (default) remedies this.  fwiw

Do you think he's actually seeing the fix, or there's still an issue?

**Comment by bspeare** [comment]
@mjoneill that is good information!  I will revisit the bug fix to check.
