### ISSUE TITLE
Decrease technical debt of ListBlock class

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#4158]
# Motivation

The ListBlock class was created originally as a fork of the `ctools_views` [Block](https://git.drupalcode.org/project/ctools/-/blob/8.x-3.x/modules/ctools_views/src/Plugin/Display/Block.php) class. At the time this approach seemed the best because we could make it work exactly the way we wanted. The downside was always that we were duplicating a lot of code that is already maintained in the contrib space. However, as we have learned, these classes are pretty hard to maintain and so we would like to reduce our footprint in that regard by shifting to a model where we extend the Block class instead of recreating it.

Getting this to a more stable state will allow us to continue with converting other views blocks to using this paradigm.

# Proposed solution

As was started in #3829, switch the ListBlock class to just extend `Drupal\ctools_views\Plugin\Display\Block`. This will require a lot of code clean-up and removal in the ListBlock class. All that we need to do in the ListBlock class is to apply changes to the existing logic that we want to apply to all of our views block displays.

**Comment by pyrello** [comment]
Related to #3501

**Comment by makurj** [comment]
I would like to pair on this.

**Comment by joewhitsitt** [comment]
ditto

**Comment by joewhitsitt** [comment]
ListBlock zoom huddle summary. We started combing line by line through ListBlock.php to remove anything that ctools_views is already providing. @makurj is going to push this initial work.

**Comment by joewhitsitt** [comment]
i tried to move forward with https://github.com/uiowa/uiowa/pull/4198 but hope that @pyrello will have a chance periodically to check in on this.

noticing some UX setbacks but so far things are still rendering...

**Comment by pyrello** [comment]
> i tried to move forward with #4198 but hope that @pyrello will have a chance periodically to check in on this.
>
> noticing some UX setbacks but so far things are still rendering...

So far this looks good. If you are running into specific issues, I'm happy to step through them with you.

**Comment by joewhitsitt** [comment]
I feel like we haven't done that much gutting yet but switching from `Drupal\views\Plugin\views\display\Block` to `Drupal\ctools_views\Plugin\Display\Block` really changes things...

<img width="451" alt="Screen Shot 2021-09-24 at 4 41 05 PM" src="https://user-images.githubusercontent.com/4663676/134742747-65b28c96-d5aa-4463-8927-87a5df198ddf.png">

**Comment by pyrello** [comment]
It does. We were structuring things a bit differently. Part of this will be figuring out how to modify the existing structure to get it to look like we had it before.

**Comment by joewhitsitt** [comment]
Closing due to https://github.com/uiowa/uiowa/pull/4198

I imagine more work will be done to refine ListBlock but we are now using ctools_views.
