### ISSUE TITLE
Config Split MR - Improve config patch and merge for sequences

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#4159]
# Motivation

We would like to adopt Config Split 2.x in #4091, but first we need to get the outstanding MR for [this issue](https://www.drupal.org/project/config_split/issues/3232243) to a stable state.

# Proposed solution

Continue the work started in https://git.drupalcode.org/project/config_split/-/merge_requests/9 and work with the maintainer to get the code to a stable state where it is likely to get approved for merging. Follow the issue for more details.

**Comment by briand44** [comment]
Helpful to read entire D.O issue linked in issue summary.

**Comment by briand44** [comment]
postponing until we can move forward with writing a test to help with this.

**Comment by pyrello** [comment]
I believe at this point the solution is mostly in place. We just need to account for a sorting issue that is causing the test to fail.

**Comment by pyrello** [comment]
I think that we have what we need here to be able to move forward: https://www.drupal.org/pift-ci-job/2207527
