### ISSUE TITLE
Provision staff-council.uiowa.edu

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#418]

**Comment by ethanstjohn** [comment]
I have inputed the blt rmi command to provision the site. It created the staff-council folder in uiowa/docroot/sites/ however, the rest of the command fell through with errors. I can't move forward.

**Comment by richardbporter** [comment]
Should be good now to provision after pulling latest master. I think you'll need to start over though.

**Comment by ethanstjohn** [comment]
It is provisioned and has a prod domain of staff-council.prod.drupal.uiowa.edu
