### ISSUE TITLE
Create a process for moving sites between servers

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#4180]
Created from https://github.com/uiowa/uiowa/issues/4153#issuecomment-923452000.

Here is a theoretical idea for how this could work:
1. Release a code update to create a temporary drush alias file for the site at the new server using the `.prod.drupal`. This will be necessary for syncing the database and files later.
2. Set up the `.prod.drupal` domain on the new application.
3. Create the database(s) for the site on the new application.
4. Run the site install command on the new server.
5. Sync the database and files from the current site to the new site.
6. Move domain from the current application to the new application.
7. Release a code update which updates the site's permanent drush alias file to point to the new server.
8. _*Optional:_ If there is any reason why you need to continue to access the old version of the site, you may need to update the temporary drush alias file to point to the old server.
9. Whenever you are done, release a code update to remove the temp drush alias file.

**Comment by briand44** [comment]
Curious if this would just be to handle D9 sites or D7 sites as well? Assuming D9 but we've had conversations about having the ability to move sites between 701/2/3 as well to help free up an application. Interested in thoughts about D7.

**Comment by pyrello** [comment]
This was only intended for D9, but I'm guessing that the process would be similar. The constraint in D7 might be that the applications are different? I'm not as familiar with the 70x applications setup. But this definitely wouldn't work for moving a Grad site or a CLAS site.

Maybe @richardbporter can weigh in?

**Comment by briand44** [comment]
The 70x applications are identical. Just not sure how much different the process would be and if it is worth the value.

**Comment by pyrello** [comment]
I think the process would actually be pretty much the same. The steps above are not able to take advantage of our automated provisioning process because of the problem with domain name conflicts. The format of the drush alias files is different, I believe, but they would be created manually.

lt may be a little bit time consuming. It requires 2-4 code deployments depending on whether the existing site needs to be available for a period of time for any reason. We would gain the most efficiency by doing a bunch of sites in one batch.

**Comment by briand44** [comment]
Here is some info about moving sites on 70x applications https://github.com/uiowa/uiowa/issues/3136

**Comment by richardbporter** [comment]
>Run the site install command on the new server.

I don't think this would be required since we'd be sql:syncing over it.

**Comment by richardbporter** [comment]
Checking for SSL coverage on the destination would be another step.

**Comment by pyrello** [comment]
I think there could be an alternative set of steps for an automated process. Some assumptions:
* The site owner shouldn't need to check the site.
* The process probably needs to be broken up into a couple discrete steps.
* There are a few things that will still have to happen manually.

Here are the proposed process:
* (Manual) Add alt prod domain in the new server.
* (Manaul) Add database to new server.
* (Manual) Ensure SSL certificate at new server can handle the site being moved there. Add relevant entries if not.
* (Auto) Create temporary drush alias file using alt prod domain for site being moved using the server it would be moving to.
* (Auto) Sync database and files from old site to new site.
* (Auto) Remove temp drush alias file and update old drush file, creating a new branch, committing changes, and providing instructions for pushing and creating a PR.
* (Manual) Move the site.
* (Manual) Merge and deploy code updates. This is tricky because there is no way (without adding a step to deploy the temp drush file above) to have access to both sites simultaneous via drush. So, there will be a window where there is a mismatch between the available drush aliases and where the site actually is located.

**Comment by richardbporter** [comment]
I'll step through this and update as soon as I can.

**Comment by richardbporter** [comment]
Thanks for adding this @pyrello ! Just noting some thoughts before I forget.

>(Manual) Add alt prod domain in the new server.

I wouldn't think this would be necessary If the site owner or us do not need to visit the site in a browser. Drush can bootstrap the site without the domain actually existing on the application.

>(Manaul) Add database to new server.

This could be automated. We're doing a bit of this in `Multisite::create()` and `Multisite::delete()`.

>(Manual) Ensure SSL certificate at new server can handle the site being moved there. Add relevant entries if not.

Verification of destination SSL coverage could be automated and error out if not covered. SSL cert creation cannot obviously. We could extract SSL verification code in `Multisite::create()` and share between commands.

>(Auto) Sync database and files from old site to new site.

If we do remote-to-remote syncs, then the aliases have to exist on the servers which is not great b/c that requires a code deploy. So like `drush @mysite.prod sql:sync @self @mysite-temp.prod` wouldn't work. :(

However, what we did for the on-prem to Acquia migration was automate DB/file syncs locally first and then up to Acquia to avoid that problem. We could do this here which would save a very awkward step.

>(Manual) Move the site.

This could be automated. A local temp alias can bootstrap a remote site without the alias existing on the server. I tested this on dev.
 
>(Manual) Merge and deploy code updates. This is tricky because there is no way (without adding a step to deploy the temp drush file above) to have access to both sites simultaneous via drush. So, there will be a window where there is a mismatch between the available drush aliases and where the site actually is located.

Yea this is awkward. We could automate the commit of the new Drush alias but until it is merged there would be that gap. There could also be a step in-between here to delete the database and files from the source application environment but we might want to manually do that to start with.

I'd like to test a bit more in the dev environment and then finalize the steps.

**Comment by richardbporter** [comment]
We could initially sync sites to another environment like stage to begin working on this. Another thing to keep in mind is duplicating database/files will increase usage and we'll want to clean up after testing.

**Comment by richardbporter** [comment]
> Curious if this would just be to handle D9 sites or D7 sites as well? Assuming D9 but we've had conversations about having the ability to move sites between 701/2/3 as well to help free up an application. Interested in thoughts about D7.

I would scope this to D9 first.
