### ISSUE TITLE
Outreach County Map - Fix data for spaced counties

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#4205]
# Story

As a site owner, I expect to see student data for counties like Black Hawk, Buena Vista, Des Moines.

See https://github.com/uiowa/uiowa/issues/3793 for previous details.

# Proposed solution

- [x] Fix 2020-21students.csv file to have hyphens instead of spaces.
- [x] Re-run the generator.
- [x] Check those output files to make sure data aligns.

**Comment by joewhitsitt** [comment]
Let me know when this is pushed and I can contact the customer

**Comment by makurj** [comment]
Completed. User can be notified.

**Comment by joewhitsitt** [comment]
Thanks @makurj. Customer has checked it out and says that it is accurate (including Black Hawk).
