### ISSUE TITLE
https://lablimoli.prod.drupal.uiowa.edu - Help migrating content

### ISSUE THREAD

**Issue by makurj** [uiowa/uiowa#4206]
https://limoli.lab.uiowa.edu
https://lablimoli.prod.drupal.uiowa.edu

"I would like help moving the content from the current V1 site to V3. Thanks!" Dominique Limoli

**Comment by joewhitsitt** [comment]
Like they want us to programmatically run migrations for them? I doubt a lab site will get prioritization any time soon. I would suggest that they request a site and go forth manually migrating it.

**Comment by makurj** [comment]
Sounds good. I will provision this out later today and can edit the automated email to suggest the manual migration option.

**Comment by joewhitsitt** [comment]
Have them formally request a site so we can track the submission if they haven't already

**Comment by makurj** [comment]
Provisioned. Waiting for release to install.

**Comment by makurj** [comment]
Copy Sean on internal prod URL email so he can explain to the user about manually migrating content.

**Comment by makurj** [comment]
Provisioned. Email sent to user, Sean copied.
