### ISSUE TITLE
Deactivate a site temporarily - https://uigearup.uiowa.edu/

### ISSUE THREAD

**Issue by makurj** [uiowa/uiowa#4207]
Submitted on: Tuesday, September 28, 2021

What is the nature of your inquiry?
General

Customer
Existing Customer

Site URL
https://uigearup.uiowa.edu/

First Name
Angie

Last Name
Lamb

Email
angela-lamb@uiowa.edu

Question
Our GEAR UP grant has ended and we no longer need this website to be live. We may need it again in the future, but the soonest would be around 2026. Can I deactivate it for now?

**Comment by joewhitsitt** [comment]
Just remove the domain from Acquia cloud

**Comment by joewhitsitt** [comment]
Find a place to make a note about it though (site request submission?)

**Comment by briand44** [comment]
I wonder if we could put them in touch with the digital archivist at the library and get the site archived and then we could completely remove it? It is a v2 site and not sure we want to be supporting a v2 site in 2026. There isn't a lot of content if it were needed again in 5 years.

**Comment by makurj** [comment]
So should I hold off on removing the domain?

**Comment by briand44** [comment]
I would for now until we have a chance to discuss in PL. If it will be archived, we would still need the domain.

**Comment by joewhitsitt** [comment]
>I wonder if we could put them in touch with the digital archivist at the library and get the site archived and then we could completely remove it?

We should capture this process as part of our workflow.

**Comment by makurj** [comment]
Emailed user letting them know to work with the digital archivist and once that is complete, to inform us, so we can deprovision the site.

**Comment by makurj** [comment]
User emailed saying they're okay with us deleting the current site and will request a new one in 2026.

**Comment by makurj** [comment]
See #4216
