### ISSUE TITLE
As a webmaster, I would like to embed TikTok videos with a preview thumbnail

### ISSUE THREAD

**Issue by makurj** [uiowa/uiowa#4208]
"Is it possible to embed/post TikTok videos in our Drupal system? (With the preview thumbnail?)
I’m trying to do just that on this page and can’t quite get there: https://bam.sites.uiowa.edu/videos"

Robert R Cargill

**Comment by quamsta** [comment]
@mjoneill, here's my exploration on this in the PR:

https://github.com/uiowa/uiowa/pull/4784

**Comment by joewhitsitt** [comment]
marking as blocked, needs discussion on whether we pursue this further based on https://github.com/uiowa/uiowa/pull/4784#issuecomment-1054709426

**Comment by quamsta** [comment]
Example TikTok embed code that's provided by TikTok in case we need to investigate alternate routes/allowing iframes, script tags or other elements and attributes:

```
<blockquote class="tiktok-embed" cite="https://www.tiktok.com/@uiowa/video/7082749025522404650" data-video-id="7082749025522404650" style="max-width: 605px;min-width: 325px;" >
   <section> <a target="_blank" title="@uiowa" href="https://www.tiktok.com/@uiowa">@uiowa</a> Our favorite place. 💛🖤 <a title="uiowa" target="_blank" href="https://www.tiktok.com/tag/uiowa">#uiowa</a> <a title="iowa" target="_blank" href="https://www.tiktok.com/tag/iowa">#iowa</a> <a title="collegelife" target="_blank" href="https://www.tiktok.com/tag/collegelife">#collegelife</a> <a target="_blank" title="♬ original sound - UIowa" href="https://www.tiktok.com/music/original-sound-7082748952600234794">♬ original sound - UIowa</a> </section>
</blockquote>
<script async src="https://www.tiktok.com/embed.js"></script>
```

**Comment by joewhitsitt** [comment]
darn, is there just an iframe option without the additional JS?

**Comment by quamsta** [comment]
Not really. It's technically possible to get the generated iframe that's built via that embed.js script and place it back in CKEditor's view source mode, but that's a pretty big ask for the content editor.

**Comment by joewhitsitt** [comment]
Then the "allow this iframe domain" approach is not going to work for TikTok :(

**Comment by joewhitsitt** [comment]
Is this the nail in the coffin for this work? https://www.iowaregents.edu/news/board-news/statement-from-president-mike-richards-on-governor-reynolds-directive-to-ban-access-to-tiktok

**Comment by mjoneill** [comment]
> Is this the nail in the coffin for this work? https://www.iowaregents.edu/news/board-news/statement-from-president-mike-richards-on-governor-reynolds-directive-to-ban-access-to-tiktok

It is not something that we would ever prioritize/undertake unless there's a policy change. 

One thing that's missing from the guidance, however, is a directive to remove any tiktok feeds from university websites.  I would think a generous reading of "electronic devices" would include servers that host UI websites.

Stay tuned on that front.  In the meantime, anyone who has [directly embedded tiktok](https://developers.tiktok.com/doc/embed-videos/) or used an aggregator or third party service to embed tiktok on sites will need to consider this.

**Comment by joewhitsitt** [comment]
>Cease the creation, posting, and active management of content on all TikTok accounts owned or controlled by the institution.

Should we remove the icon/link from the social media links on the homepage?

**Comment by mjoneill** [comment]
> Should we remove the icon/link from the social media links on the homepage?

Let's pull this into planned below the line.

**Comment by joewhitsitt** [comment]
>It is not something that we would ever prioritize/undertake unless there's a policy change.

Closing this issue.
