### ISSUE TITLE
Delete files identified in #4086

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#4209]
For:
- [x] uiowa701
- [x] uiowa702
- [x] uiowa703
- [x] uiowa
- [x] uiowa01
- [x] uiowa02
- [x] dentistry

SSH into each application dev, test and prod instance and:

- `drush @app.env ssh`
- `cd /mnt/gfs/app.env/sites`
- `rm -vrf SITE-LIST`

Where SITE-LIST is the space-delimited list of directories corresponding to the application in https://iowa.sharepoint.com/sites/CSI-Drupal2/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=D1x6f7&cid=bbbfd7a7%2Da9b0%2D4992%2D84d0%2D4f29c0e15dad&RootFolder=%2Fsites%2FCSI%2DDrupal2%2FShared%20Documents%2FAcquia%20File%20Usage&FolderCTID=0x0120002F9851D81A9B1E4DB63DA70E38793599.

We should also document that removing the multisite files should be done when deleting a multisite. For example when deleting `foo.com`, also remove `/mnt/gfs/app.env/sites/foo.com` from each application environment.

-----

There are also some large .tmp files on dentistry. We should investigate what those are and remove them from test first and then prod. That could be done with:

- `drush @uidentistry.prod ssh`
- `cd /mnt/gfs/uidentistry.prod/`
- `rm -f tmp*.tmp`

**Comment by briand44** [comment]
https://iowa.sharepoint.com/sites/CSI-Drupal2/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=D1x6f7&cid=bbbfd7a7%2Da9b0%2D4992%2D84d0%2D4f29c0e15dad&RootFolder=%2Fsites%2FCSI%2DDrupal2%2FShared%20Documents%2FAcquia%20File%20Usage&FolderCTID=0x0120002F9851D81A9B1E4DB63DA70E38793599

**Comment by joewhitsitt** [comment]
Given the possibility of user error with this, I'd be interested in pairing with someone on this so that there is a second set of eyes.

**Comment by richardbporter** [comment]
Removed files on uiowa703.dev as a test case. 👍🏻

**Comment by richardbporter** [comment]
>We should also document that removing the multisite files should be done when deleting a multisite. For example when deleting foo.com, also remove /mnt/gfs/app.env/sites/foo.com from each application environment.

I've added something to the D9 docs and the process is about the same for D7. Feel free to edit.
