### ISSUE TITLE
Identify all maps.uiowa.edu integrations on SiteNow v1.

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#4212]
Epic: https://github.com/uiowa/uiowa/issues/3957

## Usage/Integrations (701, 702, 703) as of 10/01/2021
- uiowa_maui/uiowa_maui_pane/course_deadlines
  - update uiowa_maui/uiowa_maui_pane/plugins/content_types/course_deadlines.inc#L362 to not link building abbreviation - link to facilities if we have that building number.
- registrar.uiowa.edu - (example: https://registrar.uiowa.edu/contact) Taxonomy vocabulary has link field that takes a map link.
- ~~law.uiowa.edu (703) - hardcoded footer~~
- ~~stories.uiowa.edu - hardcoded header (not in use)~~
- ~~iowareadingresearch.org - hardcoded footer - developer needs to update~~ - https://github.com/uiowa/uiowa/issues/4591#issuecomment-1005234118
- Facilities maps on building pages (using mapbox directly so will continue to work but could get pricey).
- sitenow_maps - individual_building or pin pane (not available in the sitenow_standard_profile) - possible graceful fallback maintaining size and outputting text and link.
  - careers.uiowa.edu
  - classrooms.uiowa.edu
  - its.uiowa.edu
  - library.law.uiowa.edu
  - ~~president.uiowa.edu (703)~~
  - ~~www.engineering.uiowa.edu (703)~~
  - arts.uiowa.edu (pin)
  - mnh.uiowa.edu
  - oldcap.uiowa.edu
  - hawktools.uiowa.edu

**Note:** This does not include general links that could be captured on any site.

**Comment by briand44** [comment]
SiteNow maps pane, ITS website pulling building data, etc

**Comment by briand44** [comment]
Search codebase on 701/2/3 for `maps.uiowa.edu` and note usage in modules. Check for usage of those modules with `drush @sites pmi module_name` executed on prod env of uiowa701/2/3.

Also check whether sitenow_maps was enabled by default for standard and custom profiles.

**Comment by richardbporter** [comment]
Can we ignore links? For example, a site importing a feed from content.uiowa.edu with a venue_url set to https://maps.uiowa.edu/cpb. Will that just work after the switch?

**Comment by joewhitsitt** [comment]
>Will that just work after the switch?

As of now, there are not redirects setup and these pages don't existing in Concept3D.

>Can we ignore links?

I think so. Similar to a site launch we will probably consider redirects and communicate the change out to folks to update their sites.

"Redirects or replacement for building pages - See https://github.com/uiowa/uiowa/issues/3957#issuecomment-916253913"

**Comment by richardbporter** [comment]
There is a lot of code constructing links to maps.uiowa.edu/building that we'll need to fix then. The only API-related references to `maps.uiowa.edu/api` I'm seeing are in sitenow_maps. There is a reference to maps.uiowa.edu in aging.uiowa.edu/aging_maps we might want to investigate.

I'd recommend running `grep -R 'maps.uiowa.edu' .` or some variation of it above all your D7 docroots locally as a start.

**Comment by joewhitsitt** [comment]
Just looked at its.uiowa.edu. They are no longer pulling building data. HD Staff are manually maintaining now. They wanted to tailor building names for Alerts instead of using what was provided by BuildingCommonName.

**Comment by briand44** [comment]
Aging site has been removed so we don't need to worry about that.

**Comment by joewhitsitt** [comment]
Updated the IS with usage info. Less than I thought. I think we could make a change to maui, IRRC code and registrar help text then deprecate sitenow_map_pane and work with those sites to provide concept3d links or static maps.

For links that anyone could be using out there, it would be nice to put together a guide of replacement links for buildings and distribute as part of our communication plan.

**Comment by joewhitsitt** [comment]
Updated epic with next step. Closing. Marking as for reference.
