### ISSUE TITLE
audit footers of sites to see if we can move to minimal text format

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#4213]
- [x] Audit footers for media
  - [ ] Check for other things that is not allowed in minimal that may be allowed in filtered_html
- [x] Switch footer text format to minimal
- [x] Update default content to use minimal: https://github.com/uiowa/uiowa/blob/main/docroot/profiles/custom/sitenow/content/block_content/0c0c1f36-3804-48b0-b384-6284eed8c67e.yml#L23
- [x] Prevent editors from switching to Filtered HTML
- [ ] Send communication about the change

Also for reference: footer guidelines from brand located at https://brand.uiowa.edu/applying-brand/web

**Comment by briand44** [comment]
Identify if there are others with media in footer

**Comment by briand44** [comment]
Can we use minimal text format?

**Comment by joewhitsitt** [comment]
Minimal allows ```<span role class="fa*">```

**Comment by joewhitsitt** [comment]
Will default content need to be updated?

**Comment by bspeare** [comment]
What's the best method to audit footers for media usage?

**Comment by cory-skeers** [comment]
I feel like there's a better way, but generally, this should return the content in the footer.
```
SELECT 
  field_uiowa_text_area_value FROM block_content__field_uiowa_text_area
  WHERE revision_id IN (
    SELECT
      revision_id FROM block_content_field_data
      WHERE info="Footer Contact Info"
    );
```
The next step would be to look for content we don't want to allow. Media should be of the form `<drupal-media data-align="center" data-entity-type="media" data-entity-uuid="23cdfc8e-249b-4517-8f27-af890ab2bee5"></drupal-media>`
So...

```
SELECT 
  field_uiowa_text_area_value FROM block_content__field_uiowa_text_area
  WHERE revision_id IN (
    SELECT
      revision_id FROM block_content_field_data
      WHERE info="Footer Contact Info"
    )
  AND field_uiowa_text_area_value LIKE "%drupal-media%";
```
^^ query should either return a result if there is media embedded or an empty set, and if we can run that across sites and flag those that return results, I think we'd have a pretty good audit.

**Comment by joewhitsitt** [comment]
Diff of what is allowed in filtered_html (left) vs minimal (right)
<img width="1223" alt="Screen Shot 2021-10-04 at 11 57 02 AM" src="https://user-images.githubusercontent.com/4663676/135892781-678ca8b4-5975-4660-a82b-ba4cc210a6dd.png">

**Comment by makurj** [comment]
Need more discussion on what specifically is not allowed by brand policy. For example, these elements below are not specifically disallowed by brand policy, but if we make this minimal format, they would be stripped out.

1. Lists (li, ul, ol)
2. Description list (dd, dt, dl)
3. Superscript
4. Subscript
5. Preformatted text
6. Horizontal line
7. Table
8. Caption
9. Drupal media
10. Highlighted text (mark)
11. iframe

  https://brand.uiowa.edu/applying-brand/web
  Footer content should not include:
  
  - Unit lockups
  - Videos or images
  - Other logos
  - Taglines or blocks of text


Also, how do we run the queries above (https://github.com/uiowa/uiowa/issues/4213#issuecomment-931579067) for more than 1 site at a time?

**Comment by makurj** [comment]
Thanks @joewhitsitt! The screenshot was really helpful!

**Comment by joewhitsitt** [comment]
So, I think a handful of queries could be run to find the big offenders (e.g drupal-media). Maybe communicate/interact with these sites directly. There _shouldn't_ be many iframes in footers because it is very limited in what the iframe can contain at the moment and is stripped if not valid. These other html elements, the content will still render but won't be formatted as originally written.

I think this diff should be more of the communication plan. Let folks know that we are locking down the footer content and that these elements will no longer be supported.

To run a query for all sites on an application (ssh'd cd ../) it would be something like (assuming the original query was correct):
`./vendor/bin/blt ume "sqlq \"SELECT field_uiowa_text_area_value FROM block_content__field_uiowa_text_area WHERE revision_id IN (SELECT revision_id FROM block_content_field_data WHERE info='Footer Contact Info') AND field_uiowa_text_area_value LIKE '%drupal-media%'\""`

**Comment by makurj** [comment]
Results for each application for the query above:
[uiowa.txt](https://github.com/uiowa/uiowa/files/7286870/uiowa.txt)
[uiowa01.txt](https://github.com/uiowa/uiowa/files/7286871/uiowa01.txt)
[uiowa02.txt](https://github.com/uiowa/uiowa/files/7286872/uiowa02.txt)

**Comment by pyrello** [comment]
I was not aware that you could use `blt ume` with an argument like this.

**Comment by joewhitsitt** [comment]
planning to continue helping with this today

**Comment by bspeare** [comment]
I think it makes sense to move to minimal and remove the items listed in 1-12 in https://github.com/uiowa/uiowa/issues/4213#issuecomment-933821134

**Comment by briand44** [comment]
What is left to do here? I thought this was originally scoped to just an audit?

**Comment by joewhitsitt** [comment]
>What is left to do here? I thought this was originally scoped to just an audit?

Oops. Saw the checkboxes and @makurj and I kept moving forward. Draft PR which takes care of the non-audit checkboxes. Part of it was a working session with Makur to explain some things. Sorry.

We didn't see the value in checking each of the elements so we limited our queries to drupal-media. - https://github.com/uiowa/uiowa/issues/4213#issuecomment-934487734

The next step is to decide if we want to lock this down (PR does it) and if so, send out a communication about the change.

**Comment by briand44** [comment]
I agree we should do this as well, just wasn't sure if it was happening as part of this issue or a follow up.

**Comment by joewhitsitt** [comment]
I missed some of the design meeting discussion over this. sounds like there should be at least one more conversation. follow up issue would be fine with me.

**Comment by joewhitsitt** [comment]
Closing in favor of https://github.com/uiowa/uiowa/issues/4271. Thanks for taking this on @makurj

**Comment by makurj** [comment]
Thanks for getting it to done @joewhitsitt
