### ISSUE TITLE
Tippie: Profiles / Pivot Stories

### ISSUE THREAD

**Issue by makurj** [uiowa/uiowa#4226]
Profiles / Pivot Stories
We like the student profiles here, and the ability to look at more profiles once you’re reading one. It’d be nice if the grid of student pictures was actually more like a list of headlines with images. Or maybe a set of 3 cards at the bottom with stories that share the same tags as the stories currently being read. We’ll want to work with Nikki and Steph on this when we get a little farther into that design step.

We would also like this to display a random/different story on a page on each page reload.

https://admissions.uiowa.edu/student-profiles

**Comment by bspeare** [comment]
Added this information to https://github.com/uiowa/uiowa/issues/4817 and closing this one.
