### ISSUE TITLE
College of Pharmacy Intranet: Date on Individual News Articles

### ISSUE THREAD

**Issue by makurj** [uiowa/uiowa#4233]
# Story

Articles: https://intranet.pharmacy.uiowa.edu/articles
Individual News Article: https://intranet.pharmacy.uiowa.edu/articles/macgillivray-receives-american-chemical-society-midwest-award

From: Lauer, Holly J <holly-lauer@uiowa.edu> 
Sent: Monday, September 20, 2021 10:59 AM
To: Gleeson, Kristina E <kristina-gleeson@uiowa.edu>; Kelley, Barbara <barbara-kelley@uiowa.edu>
Subject: Intranet Request
 
Is there a way for there to be a date on the news articles that are posted on the Intranet?
 
You can see a date in the Daily Dose feed, but when you click on an individual news article, you can’t see a date.

**Comment by briand44** [comment]
Looks like we just need to add this to the article switch statement in node.inc
`case 'full':
          // Created date.
          $vars['title_prefix'][] = array(
            '#type' => 'html_tag',
            '#tag' => 'div',
            '#value' => format_date($vars['created'], 'custom', 'F j, Y'),
            '#attributes' => array(
              'class' => array(
                'small',
                'created-date',
              ),
            ),
          );
          break;`

And then copy the scss to _node-type-article.scss 
`.created-date {
    text-transform: uppercase;
    color: $accessible-grey;
    letter-spacing: normal;
  }`

I would just do this but having issues compiling the scss.

**Comment by joewhitsitt** [comment]
assuming it is a radix theme, you will follow the nvm/gulp steps: NVM, Node and NPM Oh My! - https://wiki.uiowa.edu/display/sitenow/Onboarding OR create a local css override.

**Comment by briand44** [comment]
follow up with customer once it is deployed.

**Comment by joewhitsitt** [comment]
no customer review is necessary before deployment. follow-up after

**Comment by dnkemper** [comment]
Updated full article to display date. Deployed code and sent an email. Waiting for approval before closing issue.
