### ISSUE TITLE
Nested accordions

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#4236]
# Problem
> ...[Accordion] items are inexplicably nesting within the items that precede them. See these two examples:

> https://hr.uiowa.edu/pay/pay-plans/merit-trainee-pay-plan
> https://hr.uiowa.edu/pay/workforce-operations/hr-transaction-system-guidelines/special-compensation-guidelines

> On the back end, everything looks normal. I haven’t been able to figure out what’s up.

# Steps to reproduce

- `<table>` within `<table>` within an accordion item seems to cause the issue.

# Proposed solution

- [x] Contact customer to have them remove the empty wrapping table from the markup.

**Comment by joewhitsitt** [comment]
Issue is related to a table within a table that is within an accordion item.

Mob programming has solved this issue. Credit to @bspeare @richardbporter @makurj @cory-skeers @e-marie-w 

Going to contact the customer.

**Comment by makurj** [comment]
Fastest solution to a problem in history! Nicely done @joewhitsitt

**Comment by GaryRidgway** [comment]
i didnt even get to come back to help after my reboot Q_Q

**Comment by joewhitsitt** [comment]
Customer is cleaning the markup. Closing
