### ISSUE TITLE
SiteNow Request Form - Should "Comment/Questions" be optional?

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#4238]
I just noticed when looking at the SiteNow request form that the final Comments/Questions field is required. It is not clear why it is that way. I'm guessing that it forces people into writing messages that cause confusion when the site is being provisioned. Either we should be more clear about what we want people to write here or we should make it optional.

**Comment by bspeare** [comment]
Looks like it is only required if "seek approval for alternate domain" is selected unless someone adjusted the settings in the last 15 hours.

**Comment by pyrello** [comment]
Ah... good to know. Still might be nice to provide some context there because it isn't clear why it is required.

**Comment by bspeare** [comment]
The help text on the text box changes to "Please provide details about the requested domain to help expedite the approval process." when that option is selected.

**Comment by pyrello** [comment]
Nevermind. I should have investigated this further before opening a ticket.
