### ISSUE TITLE
When all content is private, store all files in private files system

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#4242]
# Story

As an owner of a site where all content is private, I would like all my sites files to be private as well.

# Additional Info
Parent issue #4241 

# Proposed solution
- Most of the work for this has already been done.
- [ ] Write test to check for private scheme patch version of config for every default public scheme: https://github.com/uiowa/uiowa/issues/4242#issuecomment-1013324907

**Comment by richardbporter** [comment]
We discussed a potential solution of setting the `$config['system.file']['default_scheme'] = 'private';` in a site's `settings.php` file right after it is created. This would prevent anyone from switching back and forth, at least without modifying code and understanding the implications.

However, we also discussed that SiteNow was created for public-facing websites from day 1 and that retrofitting an "intranet" solution might be overlooking lots of baked-in functionality.

**Comment by pyrello** [comment]
A few notes from our grooming conversation about this:
* If a site were somehow able to switch back and forth between public and private, we would need some sort of (drush?) script to move all the files from one filesystem to another.
* Because of the above, it would be a lot easier to make it a policy that a site that is going to be private needs to be created that way from the start and will then always be private.
* Is it a possibility to set the filesystem type per media bundle? If so, we could potentially create a "private file" option for things that need to be protected in a mixed system.

**Comment by richardbporter** [comment]
Hm. Changing the `system.file.default_scheme` from public to private locally doesn't actually do anything - thats just the default scheme used when creating new file fields. All of our existing media type file fields would still use the public file system. That config would have to be changed, as well as anything else configured to use the public file system (custom code, etc.).

**Comment by pyrello** [comment]
> Hm. Changing the `system.file.default_scheme` from public to private locally doesn't actually do anything - thats just the default scheme used when creating new file fields. All of our existing media type file fields would still use the public file system. That config would have to be changed, as well as anything else configured to use the public file system (custom code, etc.).

That's good to know. So, we would probably need to set this up as a split and turn it on for sites prior to granting them access.

**Comment by pyrello** [comment]
This is not comprehensive, but provides a few points to think about: https://industrialagency.ca/blog/private-files-drupal-8

**Comment by richardbporter** [comment]
References to `uri_scheme`: https://github.com/uiowa/uiowa/search?q=uri_scheme

References to `public://`:
```
config/default/media.settings.yml:icon_base_uri: 'public://media-icons/generic'
config/default/media.type.instagram.yml:  thumbnails_directory: 'public://oembed_thumbnails'
config/default/media.type.remote_video.yml:  thumbnails_directory: 'public://oembed_thumbnails'
config/default/media_entity_instagram.settings.yml:local_images: 'public://instagram-thumbnails'
config/default/media_entity_twitter.settings.yml:local_images: 'public://twitter-thumbnails'
config/features/sitenow_v2/embed.button.media_entity_embed.yml:  uri: 'public://embed_buttons/uiowa_media_wysiwyg_icon.png'
docroot/modules/custom/grad_custom/grad_migrate/src/Plugin/migrate/source/ProcessGradMediaTrait.php:    return 'public://' . date('Y-m') . '/';
docroot/modules/custom/grad_custom/grad_migrate/src/Plugin/migrate/source/ProcessGradMediaTrait.php:      $filename_w_subdir = str_replace('public://', '', $uri);
docroot/modules/custom/sitenow_media_wysiwyg/src/Plugin/media/Source/Panopto.php:          $destination = 'public://panopto_thumbnails/';
docroot/modules/custom/sitenow_migrate/src/Form/MigrateSettingsForm.php:          'drupal_file_directory' => 'public://' . date('Y-m'),
docroot/modules/custom/sitenow_migrate/src/Plugin/migrate/source/ProcessMediaTrait.php:    return 'public://' . date('Y-m') . '/';
docroot/modules/custom/sitenow_migrate/src/Plugin/migrate/source/ProcessMediaTrait.php:        $filename_w_subdir = str_replace('public://', '', $uri);
docroot/modules/custom/sitenow_migrate/src/Plugin/migrate/source/ProcessMediaTrait.php:    $filename_w_subdir = str_replace('public://', '', $uri);
docroot/modules/custom/studentlife_migrate/config/split/migrate_plus.migration.studentlife_files_import_remote.yml:    file_dest_uri: 'public://imports'
docroot/modules/custom/studentlife_migrate/config/split/migrate_plus.migration.studentlife_images_import.yml:    file_dest_uri: 'public://featured_images'
docroot/profiles/custom/sitenow/content/file/008973ee-696b-4bc5-8555-84abfd06c036.yml:      value: 'public://2020-10/Herky-full color on black@2x_14.png'
docroot/profiles/custom/sitenow/content/file/3e58e867-3fa9-4c6a-8ed6-2e8ea8b11811.yml:      value: 'public://2019-02/2018_09_01-Iowa v N. Illinois-tschoon-978_14.jpg'
docroot/profiles/custom/sitenow/content/file/57d7231a-e7d4-4096-af1e-a537d2e39318.yml:      value: 'public://2020-09/2018_09_12-Drone Campus Images-0001-HDR_14.jpg'
docroot/profiles/custom/sitenow/content/file/690b7b98-5917-4afb-a028-0f57e9a22744.yml:      value: 'public://oembed_thumbnails/Ya1DyQvuSicHe3Onmusg9FE27qsi1WKCZmQDuu3R0Js_14.jpg'
docroot/profiles/custom/sitenow/content/file/8b2f15d4-2951-4168-9c76-20518868f790.yml:      value: 'public://2020-10/Block-IOWA-GOLD-ffcd00_14.png'
docroot/profiles/custom/sitenow/content/file/b0a786d0-cded-4375-bcfa-ceb332466beb.yml:      value: 'public://2020-09/2018_06_07-Summer Lifestyle Shoot-jatorner-0188-2_14.jpg'
docroot/profiles/custom/sitenow/content/file/c47953a6-e63b-4c3f-96b9-da4c83d864dd.yml:      value: 'public://embed_buttons/uiowa_media_wysiwyg_icon_14.png'
docroot/profiles/custom/sitenow/content/file/ee885f39-348c-4e94-9e61-9a077a30345e.yml:      value: 'public://2020-09/2018_08_16-Old Capitol with Flowers-tschoon-004_14.jpg'
docroot/sites/brand.uiowa.edu/modules/brand_core/brand_core.module:            $lockup_dir = 'public://lockups/';
docroot/sites/brand.uiowa.edu/modules/brand_core/src/Controller/LockupController.php:      $directories['lockups'] = 'public://lockups';
docroot/sites/brand.uiowa.edu/modules/brand_core/src/Controller/LockupController.php:      $file = 'public://lockups/' . $nid . '/' . $nid . '.zip';
```

**Comment by richardbporter** [comment]
> References to `uri_scheme`: https://github.com/uiowa/uiowa/search?q=uri_scheme
> 
> References to `public://`:
> 
> ```
> config/default/media.settings.yml:icon_base_uri: 'public://media-icons/generic'
> config/default/media.type.instagram.yml:  thumbnails_directory: 'public://oembed_thumbnails'
> config/default/media.type.remote_video.yml:  thumbnails_directory: 'public://oembed_thumbnails'
> config/default/media_entity_instagram.settings.yml:local_images: 'public://instagram-thumbnails'
> config/default/media_entity_twitter.settings.yml:local_images: 'public://twitter-thumbnails'
> config/features/sitenow_v2/embed.button.media_entity_embed.yml:  uri: 'public://embed_buttons/uiowa_media_wysiwyg_icon.png'
> docroot/modules/custom/grad_custom/grad_migrate/src/Plugin/migrate/source/ProcessGradMediaTrait.php:    return 'public://' . date('Y-m') . '/';
> docroot/modules/custom/grad_custom/grad_migrate/src/Plugin/migrate/source/ProcessGradMediaTrait.php:      $filename_w_subdir = str_replace('public://', '', $uri);
> docroot/modules/custom/sitenow_media_wysiwyg/src/Plugin/media/Source/Panopto.php:          $destination = 'public://panopto_thumbnails/';
> docroot/modules/custom/sitenow_migrate/src/Form/MigrateSettingsForm.php:          'drupal_file_directory' => 'public://' . date('Y-m'),
> docroot/modules/custom/sitenow_migrate/src/Plugin/migrate/source/ProcessMediaTrait.php:    return 'public://' . date('Y-m') . '/';
> docroot/modules/custom/sitenow_migrate/src/Plugin/migrate/source/ProcessMediaTrait.php:        $filename_w_subdir = str_replace('public://', '', $uri);
> docroot/modules/custom/sitenow_migrate/src/Plugin/migrate/source/ProcessMediaTrait.php:    $filename_w_subdir = str_replace('public://', '', $uri);
> docroot/modules/custom/studentlife_migrate/config/split/migrate_plus.migration.studentlife_files_import_remote.yml:    file_dest_uri: 'public://imports'
> docroot/modules/custom/studentlife_migrate/config/split/migrate_plus.migration.studentlife_images_import.yml:    file_dest_uri: 'public://featured_images'
> docroot/profiles/custom/sitenow/content/file/008973ee-696b-4bc5-8555-84abfd06c036.yml:      value: 'public://2020-10/Herky-full color on black@2x_14.png'
> docroot/profiles/custom/sitenow/content/file/3e58e867-3fa9-4c6a-8ed6-2e8ea8b11811.yml:      value: 'public://2019-02/2018_09_01-Iowa v N. Illinois-tschoon-978_14.jpg'
> docroot/profiles/custom/sitenow/content/file/57d7231a-e7d4-4096-af1e-a537d2e39318.yml:      value: 'public://2020-09/2018_09_12-Drone Campus Images-0001-HDR_14.jpg'
> docroot/profiles/custom/sitenow/content/file/690b7b98-5917-4afb-a028-0f57e9a22744.yml:      value: 'public://oembed_thumbnails/Ya1DyQvuSicHe3Onmusg9FE27qsi1WKCZmQDuu3R0Js_14.jpg'
> docroot/profiles/custom/sitenow/content/file/8b2f15d4-2951-4168-9c76-20518868f790.yml:      value: 'public://2020-10/Block-IOWA-GOLD-ffcd00_14.png'
> docroot/profiles/custom/sitenow/content/file/b0a786d0-cded-4375-bcfa-ceb332466beb.yml:      value: 'public://2020-09/2018_06_07-Summer Lifestyle Shoot-jatorner-0188-2_14.jpg'
> docroot/profiles/custom/sitenow/content/file/c47953a6-e63b-4c3f-96b9-da4c83d864dd.yml:      value: 'public://embed_buttons/uiowa_media_wysiwyg_icon_14.png'
> docroot/profiles/custom/sitenow/content/file/ee885f39-348c-4e94-9e61-9a077a30345e.yml:      value: 'public://2020-09/2018_08_16-Old Capitol with Flowers-tschoon-004_14.jpg'
> docroot/sites/brand.uiowa.edu/modules/brand_core/brand_core.module:            $lockup_dir = 'public://lockups/';
> docroot/sites/brand.uiowa.edu/modules/brand_core/src/Controller/LockupController.php:      $directories['lockups'] = 'public://lockups';
> docroot/sites/brand.uiowa.edu/modules/brand_core/src/Controller/LockupController.php:      $file = 'public://lockups/' . $nid . '/' . $nid . '.zip';
> ```

Won't CS2 make this much easier to split? This doesn't seem as broad as I initially thought since all of our file fields are on media entities, currently.

**Comment by joewhitsitt** [comment]
>Won't CS2 make this much easier to split?

That is what I thought. I feel like a lot of these won't even apply. What seems to be missing is the field_image, etc. How is that controlled?

**Comment by richardbporter** [comment]
> > Won't CS2 make this much easier to split?
> 
> That is what I thought. I feel like a lot of these won't even apply. What seems to be missing is the field_image, etc. How is that controlled?

field_image is an entity reference to a media type so I don't think that controls anything regarding file storage.

**Comment by joewhitsitt** [comment]
Yeah, so then where is media type image in this list then? This search should be expanded to include `uri_scheme: public` - config/default/field.storage.media.field_media_image.yml

**Comment by richardbporter** [comment]
Oh, that is in the GitHub search link I posted: https://github.com/uiowa/uiowa/search?q=uri_scheme. I used that because it works if the search query does not include special characters. I then manually searched for `public://` and copy/pasted that.

Maybe there are other things we should be searching for?

**Comment by joewhitsitt** [comment]
sorry. missed that. thanks

**Comment by richardbporter** [comment]
Give this a shot in #4626 in the uiowa_intranet split that was introduced there to see exactly what this would take.

**Comment by richardbporter** [comment]
First problem I'm seeing is that all the default content has files set to use the public directory. Not sure if default content can be split or not. If not, it has to be deleted after site install. That is pretty quick with `drush entity:delete`.

**Comment by joewhitsitt** [comment]
do we need to go through the trouble of deleting it. anyone worried if that default content is public? if they replace file overwrite existing after the private file switch does it create the same file name in the private directory?

**Comment by richardbporter** [comment]
>If they replace file overwrite existing after the private file switch does it create the same file name in the private directory?

You would think so but I'm not seeing that behavior. Might be worth someone else testing. I pushed up some changes in #4626.

**Comment by richardbporter** [comment]
Another problem I noticed is that the private files path is not set appropriately for multisites in the local environment.

**Comment by richardbporter** [comment]
Splitting the config in #4626 works but its awkward. We'll have to remember to split any default config and/or functionality in sitenow for uiowa_intranet going forward. I don't know if we can guarantee that always happens. If we only have to look for `field.storage.*` and check the settings, an automated test might be possible.

This seems like a good use case for a separate profile but we moved away from separate profiles long ago (https://github.com/uiowa/uiowa/issues/1247). I remember issues with that approach and BLT doesn't really support it. 

Another potential option is a complete split of config. We haven't really tried that: https://github.com/uiowa/uiowa#overriding-configuration

I think we could probably get a private content type with specific private file upload out the door quicker and get feedback on it (https://github.com/uiowa/uiowa/issues/4241). That combined with webform access might go a long ways.

**Comment by joewhitsitt** [comment]
>Another problem I noticed is that the private files path is not set appropriately for multisites in the local environment.

Can you explain this a bit more @richardbporter? I am not sure I understand. Do you mean how it is all dumped in `/var/www/html/files-private` and not by site?

>default content has files set to use the public directory

This is actually bothering me a bit because of the replace functionality. Theoretically, someone could replace these images and these will stay public if they overwrite existing. Rick mentions deleting them, but that will break references on the blocks. OCD in me would love to keep node 1 so maybe we can have a targeted attack to clean up and leave the site with a more plain starting point making sure to delete revisions properly so that garbage collection happens.

I think this could be done manually and is not a blocker, but if more than a couple sites are using this, it would be good to clean this up.

Default content has issues to delete imported content and I wonder if there is some kind of flag we could pass with the site install command to prevent default content from importing.

**Comment by pyrello** [comment]
> If we only have to look for `field.storage.*` and check the settings, an automated test might be possible.

Not totally clear how this would work. Would we be checking that all `field.storage.*` instances in the intranet split have the right scheme? If so, wouldn't that require us to run a separate site instance with that split turned on?

> default content has files set to use the public directory

One idea about default content is that we could move it into a module (instead of the profile). Then we could create an alternate version of the default content that has private file references and have a second module. We could potentially alter the provision process to indicate whether a site is private and that would trigger the private version of the default content module to be loaded.

**Comment by richardbporter** [comment]
>Can you explain this a bit more @richardbporter? I am not sure I understand. Do you mean how it is all dumped in /var/www/html/files-private and not by site?

Yes.

>Not totally clear how this would work. Would we be checking that all field.storage.* instances in the intranet split have the right scheme? If so, wouldn't that require us to run a separate site instance with that split turned on?

I was thinking we could add a filesystem test to parse all `field.storage.*` config files in `config/default` directory and if they have `settings.uri_scheme` then we assert a patch exists in the uiowa_intranet split of the same field name overriding that setting.

These filesystem tests aren't great but they have saved us a couple times in the past: https://github.com/uiowa/uiowa/blob/main/tests/phpunit/src/Unit/FilesystemTest.php

**Comment by joewhitsitt** [comment]
Interesting idea on the default content idea @pyrello. I think I recall there being some gotchas early on with default_content and our provision process but those might not an issue anymore. At the same time, the less default content we have to manage also appeals to me. I wonder if the default content still has the same value as it once did now that there are many sites out there that people can look at for inspiration. Student Life has an issue to create a no default content option or default content lite: https://github.com/uiowa/uiowa/issues/3473

Curious on thoughts here: I don’t think there are blockers preventing review of the #4626 unless we want increase scope and automate the default content situation or file scheme check as part of it.

**Comment by joewhitsitt** [comment]
Rick mentioned at standup that the default content portion doesn't seem like a blocker but that writing the test would be nice.

**Comment by joewhitsitt** [comment]
Moved the default content bit to https://github.com/uiowa/uiowa/issues/4640
