### ISSUE TITLE
When all content is private, ability to assign access/role based on AD group

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#4243]
# Story

As an owner of a site where all content is private, I would like the ability to grant site access based on AD group(s).

# Additional Info
Parent issue #4241 

One or more AD groups should be able to be configured so that if a user is part of the specified AD group(s), an account will be created for that user with the mapped role.

If a user should be removed from an AD group, the next time they attempt to login that role would be removed from their account and they would no longer have that level of access.

Website management role access (webmaster, publisher, editor, etc.) can continue to be managed as they currently are.

# Questions

What role should be used for access to these authenticated sites? Do we need a new role? Requestor role, viewer role? I don't think we will want to use the authenticated user role.

Do Webmasters have the ability to configure these AD groups or is that something an administrator would need to do?

In the past these AD groups have been required to be Universal and cannot be nested. Assuming this still applies?

# Proposed solution

**Comment by joewhitsitt** [comment]
This is currently set to authenticated. If you can authenticate (have a hawkid on the site) you have access.

**Comment by richardbporter** [comment]
AD role mapping should work the same for intranets. No changes there.

>Do Webmasters have the ability to configure these AD groups or is that something an administrator would need to do?

Admin only. Managed via config. Sites have previously split this when necessary. CS2 makes it easier to split.

**Comment by briand44** [comment]
>This is currently set to authenticated. If you can authenticate (have a hawkid on the site) you have access.

Is this what we want though? In the past when someone was removed from an AD group their role that was mapped to that AD group was removed. We cannot remove the authenticated user role unless we cancel their user account. Not sure how complicated that is?

**Comment by joewhitsitt** [comment]
It is currently a permission set for the feature default. It can be more specific if AD mapping is in play.

**Comment by richardbporter** [comment]
In the intranet split, could we remove the view content/media/etc perms from authenticated users and add them to viewer? Shift them over one? Otherwise, authenticated users can still log in and view content/media after a role mapping no longer applies or is removed.

There is also something goofy with authenticated users being logged in but not having access to anything:
![image](https://user-images.githubusercontent.com/1068523/151434819-8a50a0cf-ccb7-4bcb-8391-af9b4b0a7f5d.png)

**Comment by briand44** [comment]
Sounds like see if we can use viewer role for access to intranet and remove perms for authenticated user role.

**Comment by briand44** [comment]
Weird login problem? Rick maybe explain more.

**Comment by joewhitsitt** [comment]
Viewer has additional permissions to view content that is in a non-published moderation state. Would we leave that or adjust that as well?

**Comment by joewhitsitt** [comment]
Talked with Rick and Brian about this. The plan is to move forward with using the viewer role as the restrict_ip default and adjusting the other permissions to be less of a workflow role and instead serve as a generic viewer.

Also plan to take a look at adjusting the authenticated role and/or adjust messaging based on role: https://github.com/uiowa/uiowa/issues/4243#issuecomment-1023591767

**Comment by joewhitsitt** [comment]
@briand44 has sitenow_intranet be enabled yet for any sites? aka do we need an update hook to assign users (not blocked) to the viewer role?

**Comment by briand44** [comment]
It has not been enabled for anyone yet as far as I know. Shouldn't need an update hook.

**Comment by joewhitsitt** [comment]
Should we provide a logout link (footer?) for viewers since they can no longer see the toolbar?

**Comment by richardbporter** [comment]
> Should we provide a logout link (footer?) for viewers since they can no longer see the toolbar?

I would say grant only the toolbar permission which would then show their username only, hopefully, which will handle the logout link. 🤞🏻

**Comment by joewhitsitt** [comment]
> I would say grant only the toolbar permission which would then show their username only, hopefully...

yeah, i will give that a go here soon. d7 i recall didn't work that well.

**Comment by joewhitsitt** [comment]
I updated the PR with some todos

**Comment by pyrello** [comment]
Pulling to test.
