### ISSUE TITLE
When all content is private, ability for users to search private content

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#4244]
# Story

As an owner of a site where all content is private, I would like the ability for viewer roles and above to search private content.

# Additional Info

Parent Issue #4241 

# Proposed solution

**Comment by briand44** [comment]
Search API is turned on for the service. Database as backend. Scope to Intranet split. Could add a search link to a search page as part of first slice and have another slice to implement search box on all pages.

There is a generic search block that could potentially be wired up to this.

Ideally search block would exist in header for users with access to intranet.

Eventually look at SOLR.

**Comment by briand44** [comment]
May want to require at least 3 characters for searching to reduce db bloat

**Comment by pyrello** [comment]
It looks like our search block is not in a search-specific region: https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/uids_base.info.yml

One idea for how to handle swapping out search blocks is that this could just be a configuration override in the intranet split.

**Comment by bspeare** [comment]
I found a few relevant links for `search_api` and layout builder:

https://www.drupal.org/project/search_api/issues/3038591
https://www.drupal.org/project/layoutbuilder_search_api

It doesn't look like there is a quick and easy solution that we could add to https://github.com/uiowa/uiowa/pull/4770.
