### ISSUE TITLE
SiteNow Updates News Article - October

### ISSUE THREAD

**Issue by e-marie-w** [uiowa/uiowa#4256]
## Issue/Solution ##
Provide a "release notes" type article of finished/done features/updates and publish to website, then send out dispatch email.

- [x] Create draft and update the parking lot card with an edit link
- [x] Add "release notes" covering the month of v2/v3 default profile enhancements and webmaster/edit visible bug fixes.
  * See the previous month's article as an example.
  * Bullet points from demo stories slide per week: https://drive.google.com/drive/folders/1EehKUjxCbakaB9FchrGhAbaxuRbqyDGW?usp=sharing..
  * Check recent "done" and "archive" items and finished docs tasks.
  * Take notes during sprint demo presentation.
- [x] Get at least one team member to look over the draft before publishing.
- [x] Since the draft was started earlier, adjust the publish date/time, publish, get the link to the article.
- [x] Dispatch email with link to article. (To get access, send an email to dispatch-support@uiowa.edu to have the account provisioned. Provide your hawkid and mention the CSI:drupal group)
  * Modify SiteNow Announcements Template (tweak opening line, update the article link, any other editorial adjustments)
  * Create new communication off SiteNow Announcements campaign
    * Use SiteNow Announcements population, template, suppression list, bypass approval.
    * When scheduling, check the "archive" option so that there is an RSS instance we can use in the future. I don't think this can be done after the fact.
- [x] Create the next months's issue and copy all this bullet list into it, removing the checked boxes if any.

**Comment by e-marie-w** [comment]
https://sitenow.uiowa.edu/news/2021/10/updates-october I've kept it updated as the month went on so it should be pretty close to done already, for whoever pulls it in.

**Comment by joewhitsitt** [comment]
Shout out to @e-marie-w for putting this together during the month and not all at the end.

**Comment by e-marie-w** [comment]
Added a link to updated documentation, going to say this is ready for review. One question: are we including .org and .lab type sites in our Notable Launches list or should I remove that org one I added?

**Comment by cory-skeers** [comment]
Looked over the draft, and it looks great!

I was hesitant about the org, because it had launched with some incomplete content, but it looks like it's since been updated. I think generally .org and .lab sites are less "notable," but there's also nothing saying that they couldn't or shouldn't be included. Mostly, I think we'll drop them off if we get to too long a list.

So...I'd say it's good to publish as is.

**Comment by e-marie-w** [comment]
Thanks again for reviewing this @cory-skeers! Dispatch went out at 12:45, closing this.
