### ISSUE TITLE
Neuroscience - Create article migration

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#4260]
# Proposed solution
* Build migration for articles.
  * Add external link field.
* Build migration for creating redirects from old to new article paths.

These fields can be ignored:
* redirect
* xmlsitemap
* field_d8_migration_status

**Comment by pyrello** [comment]
Apparently there is an external link field that I missed before. I updated the solution to reflect this.

**Comment by richardbporter** [comment]
It doesn't appear that the D7 site links directly to external URLs if that field is set so I set it up to import without checking the "Link directly to source" boolean in #4371 . I see a few examples of text that says "Read more here..." if the external link field is set. However, we could process that boolean as TRUE if the external link field is set. Any preference?

D7
https://neuroscience.grad.uiowa.edu/news/congratulations-2021-kwak-ferguson-fellowship-winner-ryan-betters

D9
Teaser
![image](https://user-images.githubusercontent.com/1068523/140779744-350eef8f-6cf3-4b8d-b01a-dba8fabeb7ad.png)

Full node
![image](https://user-images.githubusercontent.com/1068523/140779782-0e26d20e-56c4-4ea6-8b7b-3f8d57f17a84.png)

**Comment by richardbporter** [comment]
Sorry, the screenshots are a bad example. That is actually set in the body. Looking into it a bit further.
