### ISSUE TITLE
Inactive Site Communications 701

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#4262]
Related issues: #3953, #3625, #3684, #3153 

The same template/communication is used for both the first and all subsequent emails so it needs to be changed to account for that. For example, we might want to add a final warning message before sending the second communication.

There is a higher chance of response earlier in the week, so avoid late in the week communciations.

Email template: https://apps.its.uiowa.edu/dispatch/templates/932493356
Email population: https://apps.its.uiowa.edu/dispatch/populations/932491408/members
Email campaign: https://apps.its.uiowa.edu/dispatch/campaigns/932490456
Email communication: https://apps.its.uiowa.edu/dispatch/communications/932479972

- [x] Run without email option first to see if any sites can be deleted without customer interaction (e.g. no database/domain doesn't point). `drush @sites php-script drush/inactive.php '6 months ago'`
- [x] Make note of any of these and remove. Update spreadsheet.
- [x] Update dispatch template (https://apps.its.uiowa.edu/dispatch/templates/932493356) - see below for example template.
- [x] Turn off campaign test mode.
- [x] Initial run `drush @sites php-script drush/inactive.php --send-email '6 months ago'` ssh'd in and from the application root
- [x] Turn on campaign test mode to prevent accidental emails.

_Wait a week (10/18)_

- [x] Make sure previous identified sites have been removed so that users are not sent emails again. https://github.com/uiowa/uiowa/issues/4262#issuecomment-940191196
- [x] Update dispatch template (https://apps.its.uiowa.edu/dispatch/templates/932493356) - see below for example template.
- [x] Turn off campaign test mode.
- [x] Secondary run `drush @sites php-script drush/inactive.php --send-email '6 months 1 week ago'` ssh'd in and from the application root
- [x] Turn on campaign test mode to prevent accidental emails.

_Wait a week (10/25)_

- [x] Final run (no emails) `drush @sites php-script drush/inactive.php '6 months 2 week ago'` ssh'd in and from the application root
- [x] Ping the product owner to review the list.
- [x] Any sites that return for the final run, remove the domain from Acquia Cloud, make a note in the sites spreadsheet in Microsoft teams

_Later_
- [x] Move these instructions to the wiki for future reference.
- [ ] Full site deprovision happens with customer approval, batch work, docroot retirement

<details>
<summary>Initial template</summary>

```html
<p>Hello ${toName},</p>

<p>This email is being sent to all active webmasters on the SiteNow v1 website <a href="https://${website}">${website}</a>. The active webmasters are: ${webmasters}.</p>

<p>In accordance with https://its.uiowa.edu/support/article/110821, we are reviewing the SiteNow v1 service for inactive websites and have detected that no users have logged into <a href="https://${website}">${website}</a> in over 6 months.</p>

<p>If <a href="https://${website}">${website}</a> is no longer needed, please <a href="mailto:its-web@uiowa.edu?subject=${website}&cc=${webmasters}">reply</a> to this email indicating so.</p> 

<p>If the site is still needed, please have at least one active webmaster <a href="https://${website}/user">log in</a> to it within one week.</p>

<p>We will scan for inactive sites again in one week.  Also, consider upgrading to <a href="https://sitenow.uiowa.edu/frequently-asked-questions">SiteNow v3</a>. Feel free to <a href="mailto:its-web@uiowa.edu?subject=${website}&cc=${webmasters}">contact us</a> if you have any questions or concerns.</p>

<p>Thank you,<br />
OSC  Web Services</p>
```

</details>

<details>
<summary>second/final template</summary>

```html
<p>Hello ${toName},</p>

<p>This is the second and final inactive site email for the SiteNow v1 website <a href="https://${website}">${website}</a>. It is being sent to all active webmasters. The active webmasters are: ${webmasters}.</p>

<p>In accordance with https://its.uiowa.edu/support/article/110821, we are reviewing the SiteNow v1 service for inactive websites and have detected that no users have logged into <a href="https://${website}">${website}</a> in over 6 months.</p>

<p>If <a href="https://${website}">${website}</a> is no longer needed, please <a href="mailto:its-web@uiowa.edu?subject=${website}&cc=${webmasters}">reply</a> to this email indicating so.</p> 

<p>If the site is still needed, please have at least one active webmaster <a href="https://${website}/user">log in</a> to it within one week.</p>

<p>We will scan for inactive sites again in one week. If this site is flagged again next week, it will be deactivated. Also, consider upgrading to <a href="https://sitenow.uiowa.edu/frequently-asked-questions">SiteNow v3</a>. Feel free to <a href="mailto:its-web@uiowa.edu?subject=${website}&cc=${webmasters}">contact us</a> if you have any questions or concerns.</p>

<p>Thank you,<br />
OSC  Web Services</p>
```

</details>

**Comment by briand44** [comment]
Decided during grooming it would be good to document these steps in one place for future reference.

**Comment by joewhitsitt** [comment]
is this the same, "wait till Monday" type task?

**Comment by briand44** [comment]
I don't think it needs to wait till Monday but I would prefer not sending out late afternoon on Friday.

**Comment by joewhitsitt** [comment]
Updated IS with consolidated instructions. Had Rick review them for accuracy.

**Comment by joewhitsitt** [comment]
No instances of domain or database issues in initial run.

**Comment by joewhitsitt** [comment]
Emails moved to "responses" folder its-web > inactive
Can be removed, authorized by:

- [x] edoncampus.org.uiowa.edu - bdlewis
- [x] fiedorowicz.lab.uiowa.edu - fwilliamson
- [x] slingala.lab.uiowa.edu - sajangoud-lingala@uiowa.edu
- [x] uienvironmentalcoalition.org.uiowa.edu - bdlewis
- [x] uiphotography.org.uiowa.edu - bdlewis
- [x] onefinance.uiowa.edu - deborah-zumbach@uiowa.edu, dagwang
- [x] qi.lab.uiowa.edu - dennis-dunnwald@uiowa.edu
- [x] mccrory.lab.uiowa.edu - gmccrory, mfullenk
- [x] cycling.org.uiowa.edu - amccubbin
- [x] trumpet.studio.uiowa.edu - anning
- [x] allen.lab.uiowa.edu - strommerl
- [x] au.lab.uiowa.edu - strommerl
- [x] mipl-roc.uiowa.edu - kevin-schartz@uiowa.edu
- [x] mcelroy.lab.uiowa.edu -  steven-mcelroy@uiowa.edu
- [x] imarc.org.uiowa.edu -  harley-waldstein@uiowa.edu
- [x] russian-folklore.cours.uiowa.edu -  irina-kostina@uiowa.edu
- [x] urocomp.lab.uiowa.edu - chris-ortman@uiowa.edu
- [x] blackart.org.uiowa.edu - reanna-lewis@uiowa.edu
- [x] mapps.org.uiowa.edu - wendy-moorehead@uiowa.edu, todd-weissenberger@uiowa.edu
- [x] mindfulatiowa.org.uiowa.edu - kenneth-heitritter@uiowa.edu
- [x] heaar.lab.uiowa.edu - julie-ostrem@uiowa.edu
- [x] roco.org.uiowa.edu - sanda-trestian@uiowa.edu
- [x] nguyenresearchgroup.lab.uiowa.edu - mark-bennett@uiowa.edu
- [x] inventionofwriting.course.uiowa.edu - sabine-golz@uiowa.edu
- [x] uiugf.sites.uiowa.edu - emily-d-hill@uiowa.edu
- [x] nsr.lab.uiowa.edu - dbfunk@engineering.uiowa.edu
- [x] yannickmeuricegroup.lab.uiowa.edu - yannick-meurice@uiowa.edu
- [x] outreach.lab.uiowa.edu - lori-adams@uiowa.edu
- [x] uisafe.clas.uiowa.edu - julie-ostrem@uiowa.edu

Request to update user(s) on site:
- [x] shared-governance.sites.uiowa.edu - remove adolphm
- [x] richerson.lab.uiowa.edu - remove najones, add george-richerson@uiowa.edu
- [x] tranel.lab.uiowa.edu - remove najones, add daniel-tranel@uiowa.edu
- [x] turkish.org.uiowa.edu - remove murat-kilinc@uiowa.edu, emrah-tiras@uiowa.edu
- [x] vandervelde.studio.uiowa.edu - Remove Nicole Mier, Kirk Corey, David Henson; Add Daniel Bermudez (dbermudez), Jamie Matthews (jlmatthe)
- [x] hornbuckle.lab.uiowa.edu - Remove william-easton@uiowa.edu and jacob-gleason@uiowa.edu
- [x] nsr.lab.uiowa.edu - Remove william-easton@uiowa.edu and jacob-gleason@uiowa.edu
- [x] pennathur.lab.uiowa.edu - Remove william-easton@uiowa.edu and jacob-gleason@uiowa.edu
- [x] wrl.lab.uiowa.edu - Remove william-easton@uiowa.edu and jacob-gleason@uiowa.edu

**Comment by joewhitsitt** [comment]
Not sure if it is related to the inactive, but a request came in for a v3 upgrade for https://roman.lab.uiowa.edu/ which has a v2 site already https://labroman.prod.drupal.uiowa.edu/. Created #4292

**Comment by joewhitsitt** [comment]
Captured the initial rush of responses. Not sure how to address the email from Tina at Pathology. I can assist with deprovisions but otherwise I am going to remove my assignment from this for now.

**Comment by joewhitsitt** [comment]
Secondary run done. Next up 10/25 run/domain removal

**Comment by joewhitsitt** [comment]
Ping Brian with list of sites before domain removal

**Comment by dnkemper** [comment]
701

- [x] UPDATE [ok] does not mean "okay"
- [x] 3ddesign.org.uiowa.edu 
- [x] acce.org.uiowa.edu 
- [x] actonhealth.lab.uiowa.edu
- [x] amy-lee.lab.uiowa.edu
- [x] arabstudentsassociation.org.uiowa.edu
- [x] bassukferguson.lab.uiowa.edu
- [x] cinema1968.lab.uiowa.edu
- [x] cognitive-brain.lab.uiowa.edu
- [x] deltachapterdst.org.uiowa.edu
- [x] ghs.org.uiowa.edu 
- [x] gilbertson-white.lab.uiowa.edu
- [x] glaucomagenetics.lab.uiowa.edu
- [x] grose.lab.uiowa.edu 
- [x] han.lab.uiowa.edu

 Do NOT deprovision: hawktools.uiowa.edu

- [x] herkycares.org.uiowa.edu
- [x] hpproject.sites.uiowa.edu
- [x] ifsae.org.uiowa.edu
- [x] internet.lab.uiowa.edu
- [x] ioword.lab.uiowa.edu
- [x] itmaturitymodels.lab.uiowa.edu
- [x] itsonus.org.uiowa.edu
- [x] kristensen.lab.uiowa.edu
- [x] lal.lab.uiowa.edu
- [x] lhand.lab.uiowa.edu 
- [x] mensvolleyball.org.uiowa.edu
- [x] mssui.org.uiowa.edu
- [x] musselman.lab.uiowa.edu
- [x] naacp-iowacity.org.uiowa.edu
- [x] nonnenmann.lab.uiowa.edu
- [x] oasis.uiowa.edu
- [x] ostem.org.uiowa.edu 
- [x] predict-hd.lab.uiowa.edu
- [x] productdesignstudio.org.uiowa.edu
- [x] pso.org.uiowa.edu
- [x] robertson.lab.uiowa.edu
- [x] salgadopabon.lab.uiowa.edu
- [x] sipe.org.uiowa.edu
- [x] spectrumui.org.uiowa.edu
- [x] talman.lab.uiowa.edu
- [x] taylor.lab.uiowa.edu
- [x] tkd.org.uiowa.edu 
- [x] translateiowa.org.uiowa.edu
- [x] uefauiowa.org.uiowa.edu
- [x] uibestbuddies.org.uiowa.edu
- [x] uimsa.org.uiowa.edu
- [x] uinasa.org.uiowa.edu
- [x] uiowagammas.org.uiowa.edu
- [x] uipaws.org.uiowa.edu
- [x] wassink.lab.uiowa.edu
- [x] williamsgroup.lab.uiowa.edu
- [x] willour.lab.uiowa.edu
- [x] witry.lab.uiowa.edu
- [x] wohlgenannt.lab.uiowa.edu
- [x] wulab.lab.uiowa.edu
- [x] zaheer.lab.uiowa.edu - dnkemper

702

- [ ] iexplorestem.org
- [ ] marce2020.com

703

- [ ] hts.research.uiowa.edu
- [x] theme.uiowa.edu
- [x] get rid of president.uiowa.edu ?
- [x] get rid of engineering.uiowa.edu ?
- [x] get rid of distance.uiowa.edu ?
- [ ] mentioned maps.uiowa.edu  having no active webmasters but pretty sure we don't want to get rid of this yet 😬

**Comment by briand44** [comment]
so my understanding is only 701 is in scope here. We should not deactivate Hawktools. Otherwise, I am fine with moving forward with this as planned. Not sure if @mjoneill wants to review or has any concerns.

**Comment by dnkemper** [comment]
Got excited I guess 🙈

**Comment by mjoneill** [comment]
No concerns providing there's still a possible undo if necessary. :P

**Comment by dnkemper** [comment]
701 site domains removed and documented in spreadsheet. Highlighted yellow.

**Comment by joewhitsitt** [comment]
Moved the issue summary to https://wiki.uiowa.edu/display/sitenow/Inactive+websites

**Comment by joewhitsitt** [comment]
Created https://github.com/uiowa/uiowa/issues/4363 so we can close this issue.
