### ISSUE TITLE
Duplicate views result with multiple arguments on people_list_block and article_list_block

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#4267]
# Problem
If content has more than one taxonomy term reference and those same terms are used in the people list block and article list block as multiple arguments, view results display duplicates.

# Steps to reproduce

- Create a person node, add two tags 
- Use those same two tags in a people_list_block
NOTE: do same with research areas - bug affects this filter as well

- Create an article node, add two tags.
- Use those same two tags in a article_list_block

https://sandbox.prod.drupal.uiowa.edu/node/551/edit

<img width="911" alt="Screen Shot 2021-10-05 at 3 46 38 PM" src="https://user-images.githubusercontent.com/4663676/136100184-33ffaa89-074c-4868-a952-c126f920d459.png">

# Proposed solution

- [ ] See if views distinct or aggregation can fix the issue without causing additional issues.
- [ ] See if setting "reduce duplicates" on the individual filters can fix the issue without causing additional issues.
- [ ] Make sure the way the arguments are passed in aren't related to https://github.com/uiowa/uiowa/issues/2109
- [ ] If the above don't work, last option could be to add a preprocess prior to render to manually skim the entity_ids and reduce duplicates. Increases noodle-code, but gives (almost) full control over timing and methodology of duplicate removal.

**Comment by pyrello** [comment]
I updated the OP to include an option to investigate using "reduce duplicates" on the individual filters that support that option.

**Comment by briand44** [comment]
Likely be an issue with articles once that rolls out as well.

**Comment by pyrello** [comment]
Is this an issue with article lists as well? @dnkemper Might be worth fixing in #4406 too if so.

**Comment by dnkemper** [comment]
GOOD question! Will look into it! Thank you so much, @pyrello

**Comment by dnkemper** [comment]
@pyrello glad you brought this up... same problem. YAY! I GET TO FIX TWO BUGS! Thank you for making my day :)

**Comment by dnkemper** [comment]
@pyrello is it bad that I'm bummed that both views just needed to reduce duplicates on the filters? Ready for review🙈

**Comment by pyrello** [comment]
@dnkemper Take the easy wins when they happen. I'm dealing with the other extreme where you can't quite ever seem to get a project to done because you keep finding issues that need to be resolved. That gets old.

**Comment by dnkemper** [comment]
@pyrello okay, that is an excellent point. Now I feel terrible and I'm sorry  🥺

**Comment by pyrello** [comment]
No need to feel terrible :)
