### ISSUE TITLE
Update footer text area to use minimal html text format

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#4271]
We will want to plan a communication around this as part of this issue as well.

Related to #4213

**Comment by briand44** [comment]
Blocked, waiting for #4296 so folks have a potential alternate solution when we restrict what they are currently doing.

**Comment by richardbporter** [comment]
Comms plan: send an email a week in advance advising people to move content to pre-footer if necessary.

**Comment by GaryRidgway** [comment]
Comms have been sent out and stated that this update will happen on Monday, Nov 21 2021. We should merge  and release then.
