### ISSUE TITLE
When <nolink> is used, nested superfish menu links w/ children overlap the dropdown arrow in tablet and smaller breakpoints

### ISSUE THREAD

**Issue by dnkemper** [uiowa/uiowa#4276]
# Problem

If a child of a menu link has children (grandchild of top level menu link?) the dropdown arrow overlaps the text in tablet and smaller breakpoints - only happens when `<nolink>` is used

# Steps to reproduce

Go to africanamericanstudies.uiowa.edu or cinematicarts.uiowa.edu and minimize window to tablet breakpoint and/or smaller
- In africanamericanstudies, expand Graduate Programs menu and view Degrees and Certificates link overlapping arrow 

Example: 
<img width="1435" alt="Screen Shot 2021-10-06 at 6 30 22 PM" src="https://user-images.githubusercontent.com/16872949/136416478-ece0a07b-c3ea-43fa-b79a-c9c858a36505.png">

# Proposed solution

**Comment by bspeare** [comment]
Looks like this issue was also filed by @bewoldt in UIDS.  Let's make sure to close https://github.com/uiowa/uids/issues/588 when we fix this issue.

**Comment by dnkemper** [comment]
@bspeare good catch! Sorry about that!
