### ISSUE TITLE
Accordion content is overflowing container

### ISSUE THREAD

**Issue by bewoldt** [uiowa/uiowa#4280]
# Problem
Content within an accordion dropdown is overflowing its container.

<img width="351" alt="Screen Shot 2021-09-30 at 4 25 40 PM" src="https://user-images.githubusercontent.com/731952/136450820-9d8ed667-ac8b-4f9d-8252-0635d8e9a0c7.png">

# Steps to reproduce
I saw this on the Nursing site which is using accordions.
https://nursing.uiowa.edu/academics/bsn

**Comment by bspeare** [comment]
This is caused by the site owner using inline styles using full HTML.   

# Proposed Solution

Reach out to site owner and either suggest:
- Removing inline CSS
- Suggest using existing grid classes for a better mobile experience
