### ISSUE TITLE
Update CKEditor Library and Acquia Connector for SiteNow v1

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#4284]
- Original issue awareness: https://www.drupal.org/sa-core-2021-005
  - Update CKEditor library for D7 XSS vulnerability (build-config.js) https://ckeditor.com/blog/ckeditor-4.16.2-with-browser-improvements-and-security-fixes. Probably mitigated for most sites. I think we should at least do it for uiowa701/2/3 to cover any public facing WYSIWYGs.
- Acquia Connector updates D7

- Tippie/Education may require extra testing for CKEditor

**Comment by joewhitsitt** [comment]
Created branches `update-dependencies-2021-10` for 701, 2, 3.

```
- update CKEditor library for sitenow_standard_profile to 4.16.2 via build-config.js
- update CKEditor library for sitenow to 4.16.2 via build-config.js
- update acquia_connector from 7.x-3.7 to 7.x-3.8
```

**Comment by joewhitsitt** [comment]
Going to checkout on 703 DEV and sync tippie, education, ITS for testing.

**Comment by joewhitsitt** [comment]
Need to test against tippie (need permission from @makurj) and education (dev is d9). Syncing ITS to DEV for now. Going to test education locally (media browser plus, styles dropdown).

**Comment by joewhitsitt** [comment]
`No database updates required`

**Comment by joewhitsitt** [comment]
I don't see any acquia_connector issues in DEV. Subscription badge is present and status report is clean. 🤷

**Comment by joewhitsitt** [comment]
No noticeable issues using media browser plus on education. The functionality is pretty separate from CKEditor actually.

**Comment by joewhitsitt** [comment]
Very _brief_ testing on tippie locally. it seems ckeditor module is picking up the updated library. i don't recall why tippie is using this setup instead of the standard sitenow_wysiwyg setup.

**Comment by joewhitsitt** [comment]
These updates have been deployed.

**Comment by makurj** [comment]
Tested Tippie prod WYSIWYG (filtered and full HTML), create new text area, edit an old one, save, create links, etc. It all seems to be working fine.
