### ISSUE TITLE
Build solution for designable pre-footer region

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#4296]
# Story

As a site owner, I would like to be able to add content to a pre-footer region that is persistent from page to page.

# Proposed solution

* Build a custom content entity type for region areas. Possibly with a bundle for region? Investigate whether we might want to use this module: https://www.drupal.org/project/storage or Fragments. Whichever entity type gets used, it won't have any fields, but will have Layout Builder enabled.
* Set the Layout Builder Restrictions for the new entity to only allow one, two, and three column layouts. Only allow text area and CTA blocks to be placed.
* Create a way to display an entity in a region, either via a custom block type, or using a Views block display.

# Question
* Do we want to allow different options for how the pre-footer area looks? If so, how do we provide those options?

<details>
 <summary>Original issue</summary>
Original title: Add Give to Iowa block to pre-footer region

<img width="1433" alt="Screen Shot 2020-07-08 at 5 14 22 PM" src="https://user-images.githubusercontent.com/3067017/86975810-c0807a80-c13e-11ea-820b-1eb7426e751d.png">
Looking to add a Give to [Iowa] block in the pre-footer region so that it is visible on all pages and is directly adjacent to the footer region (no padding or margin).

The above screenshot shows an idea for this block, similar to a CTA block, with minor tweaks:

- Much smaller padding/margin on top and bottom compared to CTA block. (changed from 1.875rem to 0.875rem in this example)
- Button link is on the left side of the text.
- Text size of excerpt is much smaller than standard text. (used font-size:smaller in this example)
- No longer 50/50 flex but more like a 33/66 layout, so that there is much less padding/margin around button link.
</details>

**Comment by bspeare** [comment]
@mark-bennett-uiowa What are your thoughts on just using the cta-left version: https://uids.brand.uiowa.edu/branches/feature_lb_feature_maturity/components/detail/cta--black-left.html.  I know that is the current format of the donate buttons on CLAS sites (https://clas.uiowa.edu/hhp/).  

<img width="1425" alt="Screen Shot 2020-08-21 at 5 02 54 PM" src="https://user-images.githubusercontent.com/1036433/90939067-43e4eb00-e3d0-11ea-927e-a80a5a5ab82a.png">

**Comment by joewhitsitt** [comment]
Just capturing my thoughts once @pyrello mentioned custom entity... INRC has these "global asides" where aside is the custom entity and these are assigned to pre-defined regions (e.g. pre-footer). Alternatively, an individual page can override the global set ones.

<img width="889" alt="Screen Shot 2021-10-12 at 1 32 27 PM" src="https://user-images.githubusercontent.com/4663676/137010403-fe5afee8-e7ed-411e-a1b1-90c1da342312.png">
<img width="972" alt="Screen Shot 2021-10-12 at 1 32 43 PM" src="https://user-images.githubusercontent.com/4663676/137010410-7e4efd56-ff65-4866-8305-920104edc658.png">
<img width="599" alt="Screen Shot 2021-10-12 at 1 36 36 PM" src="https://user-images.githubusercontent.com/4663676/137010691-e66c7c97-9bcd-4928-a403-ef73350bfe45.png">

This could also be extended to handle multiple entities per region to create randomized functionality.

**Comment by cory-skeers** [comment]
> This could also be extended to handle multiple entities per region to create randomized functionality.

I'm especially interested in randomized functionality and/or on-platform A/B testing. A/B testing would need plenty more discussion and planning, but this seems like a good base for enhancements like that.

**Comment by pyrello** [comment]
Updated issue summary based on most recent planning meeting discussion.

**Comment by GaryRidgway** [comment]
As an update for this, I thought I would put some progress here:
- I started with fragments, as they were already installed and easily usable
- There were some easy ways to manipulate the default layout builder options to make it so users could not add any more sections, and only got the one on the fragments
- I thought it was a good idea to be able to let users make multiple pre-footers and then select which one they wanted, for example seasonal pre-footers. So I wanted there to be an option for them to configure that
- I tried making this a view with publishing options to select which one was going to be used, but it seemed finicky, so I have started working on a settings page implementation, allowing users to configure which pre-footer they use on that page.
