### ISSUE TITLE
People directory pager styling

### ISSUE THREAD

**Issue by mjoneill** [uiowa/uiowa#4302]
Feels...different.

https://education.prod.drupal.uiowa.edu/directory

**Comment by mjoneill** [comment]
<img width="781" alt="image" src="https://user-images.githubusercontent.com/7144234/137166713-118a2f44-0232-42b9-a1b2-9b21a95610d6.png">

**Comment by mjoneill** [comment]
Just capturing this. Seems wonky. Might just be my cold meds...

**Comment by bspeare** [comment]
I added this as an issue in https://git.uiowa.edu/java/profiles/-/issues/395 and I'm going to close this issue since we do not control these styles.

**Comment by bspeare** [comment]
Related issue: https://github.com/uiowa/uids/issues/757.
