### ISSUE TITLE
Custom more link label via ListBlock

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#4305]
# Story

As a site editor I would like to add a more link to my people/articles/events (local) views block and choose to use a default label or provide a custom label.

# Background

https://github.com/uiowa/uiowa/issues/3501

https://github.com/uiowa/uiowa/issues/3501#issuecomment-874905664 was decided it should be a separate follow-up task.

# Proposed solution

- [x] Similar to the more link path provided via ListBlock, provide a more link label field.
- [x] For existing blocks out there, default to "View more" or whatever we have currently.
- [x] Update logic to use custom label if populated.

**Comment by makurj** [comment]
I would like to work/pair on this.
