### ISSUE TITLE
Make breadcrums/menu active trail consider url arguments

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#4312]
# Story
As a College of Education site editor, I would like to be able to link to filtered directory profile results from multiple places within the menu system and retain the breadcrumb structure and active menu trail so that users can easily get back to the page they came from.

# Problem
Drupal currently doesn't handle linking to the same page from multiple places in the menu system well. This would make Drupal think it is linking to a different page if the query parameters are different.

# Additional Info
We wouldn't want to limit this functionality to only Education. Others should be able to do this if desired as well.

Not sure if this would cause unwanted behavior for some folks or not?

Would we need to make this configurable?

Would this be useful for other filters besides Directory Profiles?

Here is an example:
https://education.dev.drupal.uiowa.edu/directory-profiles?cohort=2286071&appointment=&category=&query=&page=1&size=25
and
https://education.dev.drupal.uiowa.edu/directory-profiles?cohort=2286068&appointment=&category=&query=&page=1&size=25

Both the above links link to different filtered results of directory profiles. The first lives in the menu under Admissions -> Cost and Aid while the second lives under About -> Administration.

Both links display the breadcrumb and active menu as About -> Administration. Ideally, the first would display the breadcrumb and active trail as Admissions -> Cost and Aid.

https://www.previousnext.com.au/blog/making-drupal-8s-menu-active-trail-consider-query-arguments

**Comment by joewhitsitt** [comment]
Thank you for spelling this out a bit more.

**Comment by briand44** [comment]
blocked until we hear back on if the customer is open to this alternative route.

**Comment by briand44** [comment]
Going to close this issue for now as it sounds like a new feature on the Directory Profile side of things allowing intro text for each affiliation will solve Educations issue of not having a way to get back to program information once you land on the directory. If we hear more use cases for this we can re-open and prioritize accordingly.
