### ISSUE TITLE
As a developer deleting a D9 site, I can delete files through an automated process.

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#4314]
# Story

As a developer deleting a D9 site, I can delete files through an automated process. 

Right now, this is a manual and error prone process. 

# Proposed solution

Copy the automation added in #4283 and add to the `uiowa:multisite:delete` command for each application environment.

**Comment by briand44** [comment]
Would this just be scoped to D9 then?

**Comment by richardbporter** [comment]
Yes. Updated.

**Comment by richardbporter** [comment]
https://github.com/uiowa/uiowa/blob/028bb73cb09d68d666e5ffcb9db8013a232d271d/blt/src/Blt/Plugin/Commands/MultisiteCommands.php#L970-L979

**Comment by briand44** [comment]
Distance and iowacreates are D7 sites so they are not relevant to this issue, correct?

**Comment by richardbporter** [comment]
> Distance and iowacreates are D7 sites so they are not relevant to this issue, correct?

Correct, my mistake.

**Comment by briand44** [comment]
Copy code from transfer command. May need some adjustment? Use to remove referenced sites.

**Comment by briand44** [comment]
Update v2/v3 deprovision docs
