### ISSUE TITLE
Social Media - Post overflows layout builder in Safari

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#4324]
# Problem

Instagram/Twitter iframe embeds are overflowing in Safari.

https://iowaweb.slack.com/archives/C01LA6Y2XGV/p1634575047074400

<img width="1476" alt="Screen Shot 2021-10-18 at 11 33 55 AM" src="https://user-images.githubusercontent.com/4663676/137774525-ec0c22fb-e83f-4158-9414-fbefd97de8cc.png">

# Steps to reproduce

- Looks like education had a three column layout of text areas where the instagram post is centered.
- See diversity and vote as well.

# Proposed solution

- [ ] ???

# Additional Info

To test locally you need the api keys: https://wiki.uiowa.edu/pages/viewpage.action?pageId=276466961

**Comment by bspeare** [comment]
Also happening on https://diversity.uiowa.edu and https://vote.uiowa.edu

**Comment by dnkemper** [comment]
Happens with Twitter and most likely Facebook too

**Comment by bspeare** [comment]
Looks like all this needs is `.media--type-instagram {position: relative;}`.   Might want to increase the scope of that for all media types.

**Comment by dnkemper** [comment]
@bspeare NINJA
