### ISSUE TITLE
UI Press - Investigate using Person content type for creating Authors

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#4329]
# Motivation

UI Press needs a Person content type to handle authors, illustrators, etc that contribute to a book but aren't part of their staff. In D7 they used a separate Author content type. The different roles could be added to our existing Person Types, but since there's about a dozen it might be easier to keep them separate and create a custom Person type. 

Fields needed:
- First Name
- Last Name
- Roles/Person Types 
   - [x] Author
   - [x] Editor
   - [x] Illustrator
   - [x] Photographer
   - [x] Translator
   - [x] Preface Author
   - [x] Foreword Author
   - [x] Introduction Author
   - [x] Afterword Author
   - [x] Essay by
   - [x] Contributor 
- Biography 
- Website 
- Image 
  - Place to list photographer credit for author photo
- Social media links? - nice-to-have, existing link fields should fulfill this

Additionally, in d7 the page that displays for each person includes a view that lists & links any books they worked on and what their role was. (https://github.com/uiowa/uiowa/issues/4658)

# Proposed solution

Investigate how to set up person types (using custom person types or just tags) and what additional customizations would be necessary (if any) to use the Person content type for authors/etc. in the new UI Press site. We also need to investigate what are the potential problems with using the Person content type (e.g. the built-in person listing page needs to be turned off, what is involved in building out listing pages for authors, etc.)

**Comment by makurj** [comment]
I would love to pair/work on this.

**Comment by pyrello** [comment]
Results of the investigation: We think that the person content type can be used. Here is how we'll handle each field that isn't explicitly accounted for:
Role - After looking at the old site and what the role field is being used for, we have decided to use person types for it instead of tags or creating a dedicated vocabulary and term reference field. The roles are used to build multiple views that are displayed on the person page and so there is no need for the customer to be able to create new role options on the fly.
Photo credit for person photo - Can be placed on global caption with the associated media item.
Social media links - Website field can handle as many of these as they care to add.
