### ISSUE TITLE
Headline field showing up in "Footer Contact Info" block

### ISSUE THREAD

**Issue by quamsta** [uiowa/uiowa#4331]
# Problem
The headline field was made available to the text area block which serves as the base for the Footer Contact Info block. This is not desired.

<img width="460" alt="Screen Shot 2021-10-19 at 10 43 04 AM" src="https://user-images.githubusercontent.com/472923/137946592-240cc0ee-7e9c-4c04-8524-f7fffc896cfe.png">

# Steps to reproduce
Go to /block/16 and you can see the spurious field.

# Proposed solution

- [x] Update hook to get this particular block and set values to empty
- [x] Form alter to target this block specifically and find a way to remove it (try `#access = FALSE` first). 

See examples of an update hook and form alter where we are targeting this block specifically 
- https://github.com/uiowa/uiowa/pull/4269/files#diff-cce5595154c40be8aea65b9d6fc5d349fc78e0b27205507567745ad5da7a681a
- https://github.com/uiowa/uiowa/pull/4269/files#diff-fead566a578ea17efbda9b82e2a399962f8d578c39998fedf5bb87ceebd7d3f6

**Comment by joewhitsitt** [comment]
So this block uses the text area block which recently received the headline field. We have other code that targets this block directly. We can just form alter and remove access to this field.

This is unrelated to prefooter work.

`$uuid == '0c0c1f36-3804-48b0-b384-6284eed8c67e'`

**Comment by makurj** [comment]
I would like to pair on this.
