### ISSUE TITLE
Embed Group Fitness Schedule

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#4335]
# Story

As a Rec Services site owner, I would like to display our group fitness schedule from Fusion so that end users can know when and where these activities are taking place without us having to manually enter this content in multiple places.

# Additional Info

Link on current live site https://recserv.uiowa.edu/programs/fitness/group-fitness/group-fitness-schedule
Link to where this should exist on new site  https://recserv.prod.drupal.uiowa.edu/group-fitness

Raaj R. (CSI App Dev group) manages the endpoint.

Are we good with the branding?

# Proposed solution

- Embed the following iframe as full html and make any necessary adjustments?

`<iframe frameborder="0" height="900" scrolling="no" src="https://hours.iowa.uiowa.edu/recserv.fusioncalendar.groupfitness/groupFitnessCalendar.html" style="border-width: 0" width="100%"></iframe>`

**Comment by briand44** [comment]
Other option would be to allow iframes from this source?

**Comment by briand44** [comment]
Don't let the look/brand hold this up but would be good to understand how much control CSI has.

**Comment by bspeare** [comment]
I've added this to https://recserv.prod.drupal.uiowa.edu/groupfit. 

Edit: I have reached out to Raaj in CSI app dev and requested that they remove the `background-color: gold` from this table:

Before:

<img width="1197" alt="Screen Shot 2021-11-29 at 10 48 08 AM" src="https://user-images.githubusercontent.com/1036433/143908942-4da57eb7-04d7-431d-80b2-379bce4ed10f.png">

After:

<img width="1225" alt="Screen Shot 2021-11-29 at 10 47 59 AM" src="https://user-images.githubusercontent.com/1036433/143908954-1b633e9d-37fd-4e0b-8d10-2fc6d9812197.png">

**Comment by bspeare** [comment]
Raaj has updated the styles and this issue can be closed now.
