### ISSUE TITLE
Embed Intramural Sports Offerings

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#4336]
# Story

As a Rec Services site owner, I would like to display our intramural sports offerings from our 3rd party so that end users can find this information without us having to manually enter this content in multiple places.

# Additional Info

Link on current live site https://recserv.uiowa.edu/intramural-sports
Link to where this should exist on new site https://recserv.prod.drupal.uiowa.edu/intramural-sports

Are we good with the branding?

# Proposed solution

- Embed the following as full html and make any necessary adjustments?

`<script type="text/javascript" src="//www.imleagues.com/Integration/Widgets/WidgetLoader.ashx?SchID=8a848595603e47c7bad340e8f091d166&amp;width=100%&amp;height=658px&amp;type=Intramural&amp;scrolling=auto" async=""></script>`

**Comment by bspeare** [comment]
I added this to https://recserv.prod.drupal.uiowa.edu/intramural-sports.   The tag labels using green and orange for the background colors fail a11y checks.   Should we request that those be updated to accessible colors before embedding this content?

<img width="1356" alt="Screen Shot 2021-11-29 at 10 43 22 AM" src="https://user-images.githubusercontent.com/1036433/143908025-0c2bae04-5e75-4198-af89-8c18d70291cc.png">

**Comment by briand44** [comment]
I would just embed it, since it already exists on current site, then reach out and make them aware of the accessibility issues and see if they can work with their vendor to resolve. As part of that conversation, it would be good to find out how much design control is allowed in case it could be more UI branded.

**Comment by bspeare** [comment]
We have embedded the calendar and suggested new colors to fix the bootstrap badge colors.
