### ISSUE TITLE
Media Revisions and Orphaned Files

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#4338]
Follow-up from https://github.com/uiowa/uiowa/issues/3327

## Problem

Media revisions are turned on but don't have a UI and we aren't limiting them similar to node revision delete. As it relates to media_entity_file_replace, if a file is replaced (new file name), the old file continues to have usage due to revisions and is not cleaned up.

This is also affecting redirects. If the file still exists, apache will serve that first regardless of what the redirect in Drupal says.

https://www.drupal.org/project/drupal/issues/1239558

## Proposed Solution

- [x] Consider whether or not we need media revisions turned on? There is currently not a way to compare/revert revisions through the UI.
- [x] #4641
- [x] #4811
- [ ] Consider lowering the time to clean up variable

**Comment by richardbporter** [comment]
There is a contrib project to view/revert/delete media revisions that I briefly interacted with in #3327: https://www.drupal.org/project/media_revisions_ui.

**Comment by joewhitsitt** [comment]
I poked at this a bit as it relates to the old brand file as I wanted to better understand what is going on. https://iowaweb.slack.com/archives/C0164FNN1PV/p1635471287135600

Replacing a file more often than not creates a new revision (checked by default). The file_usage remains. When a media entity is deleted and there is no recorded usage for that latest revision, it gets marked as temporary and eventually deleted. The media revisions also get deleted, but the file_managed rows associated with those past revisions don't get the same "mark as temporary" treatment and don't get cleaned up. file_usage for those files still list the media entity (deleted).

For this particular brand file, to remove it properly, I deleted past revisions of nodes where it was used and then using media_revisions_ui, deleted all but the latest media revision. The next two cron runs, the file_managed entry is marked as temporarily and after 6 hours (or a modified changed timestamp) are cleaned up.

This potentially leaves previous file_usage out there for media entities that no longer exist. Because of the file_usage, the file_managed are never cleaned up.

**Comment by joewhitsitt** [comment]
To avoid using the module, Rick helped me construct this gem to be run using `drush php`:

`\Drupal::service('entity_type.manager')->getStorage('media')->deleteRevision(6556);` where "6556" is the revision `vid` in question. This will delete the media revision and kick off the necessary "mark as temporary" workflow and the file will eventually/safely get deleted from the server in six hours.

Finding the revision id is tricky and is linked to the file's created timestamp.

Find the file in `file_managed` by `uri`, get the `fid` and `created` timestamp. In `file_usage`, get the media `id` by filtering by the `fid`. Take the media `id` and the file `created` timestamp to `media_revision`, filter by `mid` and get the `vid` by comparing the `revision_created` timestamp to the file's `created` timestamp.

**Comment by joewhitsitt** [comment]
Based on https://www.drupal.org/project/drupal/issues/1239558, I think it would be in our best interest to move forward with "disabling" revisions for media and removing all revisions except for the latest version.

**Comment by richardbporter** [comment]
Should we consider lowering the 6 hours config as part of this?

**Comment by joewhitsitt** [comment]
We would have to setup our own to go lower:
<img width="391" alt="Screen Shot 2021-11-02 at 4 36 04 PM" src="https://user-images.githubusercontent.com/4663676/139955217-95193c1d-4bf9-4d87-8593-e30ef96bb745.png">

**Comment by joewhitsitt** [comment]
Moving to Parking lot as my support pick issue

**Comment by joewhitsitt** [comment]
FWIW, Drupal 11 has media revision ui support: https://www.drupal.org/node/3366630

**Comment by joewhitsitt** [comment]
I think this is done, unless we see enough value in overriding core to increase the frequency. So far it seems like folks notice something hasn't been deleted right away, but that they are okay with it clearing up within a day or so.
