### ISSUE TITLE
Governance plan document for uiowa.edu

### ISSUE THREAD

**Issue by mjoneill** [uiowa/uiowa#4343]
As a campus leader, I can look at a governance plan for uiowa.edu and understand when the site gets updated, on what cadence, and by who:

Examples of content types:
* Sparkle facts and claims
* Links
* Banner video(s)
* Events
* Vertical videos
* News articles
* Photos and imagery

**Comment by ABoston88** [comment]
Link to draft document for reference: https://iowa-my.sharepoint.com/:w:/g/personal/bosto_uiowa_edu/EbIu-RFeeZZIkj2GQ5OykWgBGcjuH1T3UZR5GfuAaaoeWA?e=HmdREA
