### ISSUE TITLE
As a SNv3 site owner leveraging Exchange to manage resource hours, I would like to be able to display those hours on my website.

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#4344]
# Story

As a SNv3 site owner leveraging https://hours.iowa.uiowa.edu to manage location hours, I would like to be able to display those hours on my website so that end users know when our locations are open/closed and this information can be maintained in one place.

# Proposed solution

Create a block that takes an location identifier (Exchange resource name, ex. RES-foo-200) as an input and passes that to an API and returns the hours for the specified location. The block should have the ability to display open/closed based on the current time compared to the hours of operation.

Related issue: #3933

**Comment by richardbporter** [comment]
I think this could be built in a such a way that it could work for Housing & Dining location hours or other sites that might have a use case. I will fill in details later.

**Comment by richardbporter** [comment]
One caveat to the block approach is it probably makes it more difficult to show all location hours on one page. RecServ does not need this anymore because they are using `<nolink>` to drive people to individual pages. UHD has a similar page: https://dining.uiowa.edu/locations with additional features like a map, filtering, etc. Perhaps that might not be needed for a v3 transition. If it is, we might need another approach. Maybe fragments or something? Unless UHD just wants a specific location content type again.

**Comment by briand44** [comment]
reach out to Dining to understand their future needs to help us determine best path forward here.

**Comment by richardbporter** [comment]
Thinking about this again, building it for RecServ in a way that works for Dining would be overly complicated. Dining also has a map on that page and many more fields on their locations. They will probably need something custom for that page or their own location content type.

**Comment by dnkemper** [comment]
Questions:

1. Feature split or site split (was working towards feature split if other sites might utilize hours.uiowa.edu info)
2. To make sure on right path, add a block with 1 field that will be used to gather the exchange resource name (ex. RES-foo-200) - make unlimited so can enter however many location hours want to display on site then display it like a card that shows if open or closed (display similar to people/articles?)

**Comment by richardbporter** [comment]
> Questions:
> 
> 1. Feature split or site split (was working towards feature split if other sites might utilize hours.uiowa.edu info)
> 2. To make sure on right path, add a block with 1 field that will be used to gather the exchange resource name (ex. RES-foo-200) - make unlimited so can enter however many location hours want to display on site then display it like a card that shows if open or closed (display similar to people/articles?)

1. Feature split, yes.
2. I think single value only. A toggle to choose to display a status indicator to show open/closed and another one to toggle Pickadate functionality like on https://recserv.uiowa.edu/facilities/campus-recreation-wellness-center.

**Comment by dnkemper** [comment]
@richardbporter THANK YOU SO MUCH! Also... ninja response skills
![PARKOUR](https://user-images.githubusercontent.com/16872949/144499031-df61eec2-7723-4b84-9ed1-1ef42a62d243.GIF)

**Comment by dnkemper** [comment]
Okay... I apologize in advance if I'm off base here...

1. Should I follow the facilities content type and add 'Major closure', 'Hours - Today', or 'Hours Timeline' extra fields to the block?
2. For the 'toggle to choose to display a status indicator to show open/closed and another one to toggle Pickadate functionality'...  Only physical/editable field in block form display= resource (where they enter exchange key), right? Getting confused while looking at D7 and all of the extra fields they added based on certain recserv content types 
2a. EX: looking at that [URL](https://recserv.uiowa.edu/node/1206/edit) and there are extra fields related to hours that can be added (major_closure and rainout -> will we need these in D8 too? If so, what content type should I follow? All have diff extra fields related to the hours module -  'Major closure', 'Hours - Today', or 'Hours Timeline' etc)
3. Should I just attempt to setup the display as similar as possible to: https://recserv.uiowa.edu/facilities/campus-recreation-wellness-center?

**Comment by joewhitsitt** [comment]
Outside looking in, but saw your comment about fullcalendar_view in Slack. When I think of a date picker and what is currently on recserv, I think of pickadate.js which now has a non-jQuery version: https://github.com/amsul/pickadate.js/releases/tag/v5.0.0-alpha.3. If the idea is to have a calendar display instead of a list again, then fullcalendar_view is IMO the best option currently.

I don't understand the issues related to block v content type

**Comment by joewhitsitt** [comment]
Also, we have jquery_ui_datepicker in our composer file to support webform. AFAIK, webform doesn't have a replacement for several jquery ui dependencies yet. https://www.drupal.org/project/webform/issues/3174099

**Comment by briand44** [comment]
For the hours search portion of this the customer is hoping we can autosubmit after choosing a date so users don't have to click submit.

**Comment by joewhitsitt** [comment]
Danielle DM'd me this morning with some details about the work in progress. I plan to take a look at this today.

**Comment by briand44** [comment]
We meet with Rec Services today at 4pm. If anyone is working on this and has questions for them let me know and I can extend the invite.
