### ISSUE TITLE
SiteNow Find Text UX improvements

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#4348]
# Motivation

The Find Text feature is a tool rather than a configuration setting, so placing it in the context of the SiteNow configuration menu doesn't make a lot of sense, since you are not changing configuration when you use it. Also, I think we are a little over the top in wanting to name things branded with "SiteNow" and that this tool could just be called "Find Text" instead of "SiteNow Find Text." I think this would potentially reduce confusion for people using the tool without other context because the "SiteNow" in the name is not meaningful in relation to how it works.

# Proposed solution

- Change the menu and page title of the tool to just "Find Text"
- Move the menu item to be a top-level Admin menu item (as a sibling to "Content" and "Structure")

**Comment by cory-skeers** [comment]
Maybe we can work these changes alongside #4268
