### ISSUE TITLE
Add generic ID's to component headlines

### ISSUE THREAD

**Issue by bewoldt** [uiowa/uiowa#4349]
# Problem
As a site editor I would like to link to a section within a page but I don't have an ID to hook to. Headline fields within components don't have ID's so I often resort to using the component's wysiwyg editor to add my headers or sometimes I have to make a whole new section with a text area. 

# Proposed solution
Give generic ID's to component headlines

**Comment by bewoldt** [comment]
Closing. This issue is covered in #3311

**Comment by joewhitsitt** [comment]
Oh sorry @bewoldt, I didn't mean to indicate that this issue should be closed, but as a potential slice of that larger issue. I added this to the "Consider implementing one or more of the following existing issues." We determined that https://github.com/uiowa/uiowa/issues/3567 should be the path forward for editor customized IDs along with better WYSIWYG support, but that we might still want to offer an auto-generated id like this at some point.
