### ISSUE TITLE
Update Canonical url for buildings

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#4350]
# Story

As an owner of the maps website, I would like to have the canonical url for each building point to the corresponding building page on the Facilities website, in preparation for redirecting those pages in the future.

# Additional Info

https://maps.uiowa.edu/sh - current canonical url shows `<link rel="canonical" href="https://maps.uiowa.edu/sh" />`

It should be `<link rel="canonical" href="https://www.facilities.uiowa.edu/building/0002" />`

# Proposed solution

**Comment by joewhitsitt** [comment]
The data.its endpoint that currently populates maps has building number available. Could get that data into a csv, do some spliting/curating into a source/destination list that we can add to the redirects table.

Might be nice to rabbit hole redirect in case authenticated still needed to get to the building page.

**Comment by briand44** [comment]
Potentially preprocess into meta tag since building id exists on maps site?

**Comment by joewhitsitt** [comment]
The full building number is available

```
<building>
<Building>0002 SH</Building>
<BuildingFormalName>Schaeffer Hall</BuildingFormalName>
<BuildingCommonName>Schaeffer Hall</BuildingCommonName>
<Address>20 East Washington Street</Address>
<CampusLocation>East Campus</CampusLocation>
<Site>Main Campus</Site>
<latitude>41.660705530000000</latitude>
<longitude>-91.535676159999900</longitude>
<BuildingStatus>ACTIVE</BuildingStatus>
<YearBuilt>1902</YearBuilt>
<District>East Campus</District>
<BuildingNumber>2</BuildingNumber>
<BuildingAbbreviation>SH</BuildingAbbreviation>
<City>Iowa City</City>
<State>IA</State>
<ZipCode>52242</ZipCode>
</building>
```

**Comment by richardbporter** [comment]
This is done. Pages will update as caches expire naturally.
