### ISSUE TITLE
Audit building information

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#4351]
# Story

As a maps site owner, I would like to understand what building information is currently available that would be lost if we redirect these building pages to Facilities, so that we can understand what if anything needs to be accounted for on Facilities, prior to redirecting.

# Additional Info

Things like "explore" and "things here".

Example of a maps building - https://maps.uiowa.edu/sh
Example of a Facilities building - https://www.facilities.uiowa.edu/building/0002

# Proposed solution

- [ ] Provide an export of all the explore and things here data with a reference to the building so that one can review and decided what data should be retained and accounted for elsewhere.

**Comment by joewhitsitt** [comment]
Extras = Explore

https://maps.uiowa.edu/admin/structure/taxonomy/extras

**Comment by joewhitsitt** [comment]
See the comments here: https://github.com/uiowa/uiowa/issues/4006

**Comment by mjoneill** [comment]
If automating the aggregation of the info in the Proposed Solution section is not possible, we can likely invest in a manual audit.

**Comment by e-marie-w** [comment]
Do we know yet if this needs to be manual or if it can be automated?

**Comment by joewhitsitt** [comment]
Should be able to construct something using views_data_export module

**Comment by e-marie-w** [comment]
I don't know how to use the views_data_export module so I'd like to pair with whoever takes this on.

**Comment by GaryRidgway** [comment]
Hey all, working with @e-marie-w on this, [does this meet the criteria for what we are looking for?](https://teams.microsoft.com/l/file/9512A873-121C-4FB5-A00A-3E50894D8C6A?tenantId=1bc44595-9aba-4fc3-b8ec-7b94a5586fdc&fileType=csv&objectUrl=https%3A%2F%2Fiowa.sharepoint.com%2Fsites%2FCSI-Drupal2%2FShared%20Documents%2FGeneral%2Fbuildings-data-export-maps-site.csv&baseUrl=https%3A%2F%2Fiowa.sharepoint.com%2Fsites%2FCSI-Drupal2&serviceName=teams&threadId=19:4faedfd92c2044a5aecd543efd14217b@thread.skype&groupId=1fd551d5-c98b-4118-a759-b2debe414198)

**Comment by briand44** [comment]
I am not seeing anything in the Explore column and I guess I assumed there would be. Am I missing something?

**Comment by GaryRidgway** [comment]
good catch, there were things there before but perhaps the export did not like them, I will investigate

**Comment by GaryRidgway** [comment]
[okay, tried this again, added in highlighting for things.](https://teams.microsoft.com/l/file/9BD0F56C-108D-486A-850A-53449D445B52?tenantId=1bc44595-9aba-4fc3-b8ec-7b94a5586fdc&fileType=xlsx&objectUrl=https%3A%2F%2Fiowa.sharepoint.com%2Fsites%2FCSI-Drupal2%2FShared%20Documents%2FGeneral%2Fbuildings-data-export-maps.xlsx&baseUrl=https%3A%2F%2Fiowa.sharepoint.com%2Fsites%2FCSI-Drupal2&serviceName=teams&threadId=19:4faedfd92c2044a5aecd543efd14217b@thread.skype&groupId=1fd551d5-c98b-4118-a759-b2debe414198)

Green: not actively shown on maps, but are available and not shown in facilities.
Orange: Shown on maps but not on facilities.

**Comment by joewhitsitt** [comment]
This seems to contain what needs to be considered when moving forward with content on Facilities and Concept3D

**Comment by briand44** [comment]
It may be useful to have the distinct list of https://maps.uiowa.edu/admin/structure/taxonomy/extras in a separate sheet of the excel file unless they are already handy somewhere to be shared with stakeholders?
