### ISSUE TITLE
Image Specification Docs for v3

### ISSUE THREAD

**Issue by dnkemper** [uiowa/uiowa#4352]
A user was asking about specific image specs regarding v3 blocks. I realized our documentation doesn't currently provide any helpful information regarding suggested image sizes based on block type. We should update this since the v3 block docs link users to it. 

https://sitenow.uiowa.edu/documentation/media/images-and-files

**Comment by joewhitsitt** [comment]
This kind of came up in demo today as it related to the WYSIWYG responsive image style options. These have been steady for a while and have more meaning now that we are potentially going to solve some long term issues with https://github.com/uiowa/uiowa/pull/7185

**Comment by bspeare** [comment]
As a part of https://github.com/uiowa/uiowa/issues/7184, I have updated this page with a comprehensive table that covers all of our image styles.
