### ISSUE TITLE
Unlabelled URLs alter size of person card

### ISSUE THREAD

**Issue by e-marie-w** [uiowa/uiowa#4357]
# Story #
User noticed unlabelled website links cause the person card to become bigger and not match person cards with labelled URLs. 

They were only labeling if there was more than one website link, so if this is expected behavior they suggested maybe changing the helper text.

Label:
![labelled link](https://user-images.githubusercontent.com/68179015/138764416-34f28a66-1d63-44e7-ba3e-85e1520be8a8.png)
![with title](https://user-images.githubusercontent.com/68179015/138764863-8b8804f1-3131-44d2-8551-2ad4174082a8.png)
No label/plain URL:
![unlabeled link](https://user-images.githubusercontent.com/68179015/138764431-8b9b27e5-6e60-4ba5-9390-bb1fb70f54f8.png)
![no title](https://user-images.githubusercontent.com/68179015/138764876-7ae17c9d-60fe-4558-8f5e-685ca939e8cb.png)

**Comment by bspeare** [comment]
This will be resolved when https://github.com/uiowa/uiowa/pull/4286 merges.
