### ISSUE TITLE
SSL for www.iowajpec.org and iowajpec.org on uiowa02

### ISSUE THREAD

**Issue by dnkemper** [uiowa/uiowa#4359]

**Comment by joewhitsitt** [comment]
The current site resolves to https://www.iowajpec.org. Should www be accounted for again?

**Comment by joewhitsitt** [comment]
@makurj do you know if iowajpec still needs www coverage? https://sitenow.uiowa.edu/policies#www

**Comment by makurj** [comment]
I'll check.

**Comment by makurj** [comment]
They would prefer www to be covered also.

**Comment by joewhitsitt** [comment]
Done
