### ISSUE TITLE
Docs - Update v3 Articles Block

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#4362]
https://github.com/uiowa/uiowa/pull/4286

**Comment by e-marie-w** [comment]
[Draft of update](https://sitenow.uiowa.edu/node/271/latest) vs [Original](https://sitenow.uiowa.edu/documentation/layout-builder/articles-block)

Sorry, I was between things and it seemed easier to do this while the changes were still fresh in memory. Then I mostly just used the People block page as a template anyways and just added or removed options and sections as needed.

**Comment by joewhitsitt** [comment]
I approve and published. Thanks @e-marie-w
