### ISSUE TITLE
Final removal of inactive sites

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#4363]
Follow-up from https://github.com/uiowa/uiowa/issues/4262

Related issues: #3953, #3625, #3684, #3153, #4262

If application retirement is not on the immediate horizon, this can be taken on.

I want to say there was a task to define the period of time and process more, so please enlighten this issue if you have knowledge of that work.

## Proposed Solution

- [x] backup db's, files, site directory?
- [x] Remove sites identified/deactivated in the inactive site tasks.
- [x] Update the spreadsheet

 **First Slice**

701
- [x] 3ddesign.org.uiowa.edu 
- [x] acce.org.uiowa.edu 
- [x] actonhealth.lab.uiowa.edu
- [x] amy-lee.lab.uiowa.edu
- [x] arabstudentsassociation.org.uiowa.edu
- [x] bassukferguson.lab.uiowa.edu
- [x] cinema1968.lab.uiowa.edu
- [x] cognitive-brain.lab.uiowa.edu
- [x] deltachapterdst.org.uiowa.edu
- [x] ghs.org.uiowa.edu 
- [x] gilbertson-white.lab.uiowa.edu
- [x] glaucomagenetics.lab.uiowa.edu
- [x] grose.lab.uiowa.edu 
- [x] han.lab.uiowa.edu
- [x] herkycares.org.uiowa.edu
- [x] ifsae.org.uiowa.edu
- [x] internet.lab.uiowa.edu
- [x] ioword.lab.uiowa.edu
- [x] itmaturitymodels.lab.uiowa.edu
- [x] itsonus.org.uiowa.edu
- [x] kristensen.lab.uiowa.edu
- [x] lal.lab.uiowa.edu
- [x] lhand.lab.uiowa.edu 
- [x] mensvolleyball.org.uiowa.edu
- [x] mssui.org.uiowa.edu
- [x] musselman.lab.uiowa.edu
- [x] naacp-iowacity.org.uiowa.edu

**Second Slice**

701
- [x] nonnenmann.lab.uiowa.edu
- [x] oasis.uiowa.edu
- [x] ostem.org.uiowa.edu 
- [x] predict-hd.lab.uiowa.edu
- [x] productdesignstudio.org.uiowa.edu
- [x] pso.org.uiowa.edu
- [x] robertson.lab.uiowa.edu
- [x] salgadopabon.lab.uiowa.edu
- [x] sipe.org.uiowa.edu
- [x] spectrumui.org.uiowa.edu
- [x] talman.lab.uiowa.edu
- [x] taylor.lab.uiowa.edu
- [x] tkd.org.uiowa.edu 
- [x] translateiowa.org.uiowa.edu
- [x] uefauiowa.org.uiowa.edu
- [x] uibestbuddies.org.uiowa.edu
- [x] uimsa.org.uiowa.edu
- [x] uinasa.org.uiowa.edu
- [x] uiowagammas.org.uiowa.edu
- [x] uipaws.org.uiowa.edu
- [x] wassink.lab.uiowa.edu
- [x] williamsgroup.lab.uiowa.edu
- [x] willour.lab.uiowa.edu
- [x] witry.lab.uiowa.edu
- [x] wohlgenannt.lab.uiowa.edu
- [x] wulab.lab.uiowa.edu
- [x] zaheer.lab.uiowa.edu - dnkemper - spreadsheet says domain was removed but I can still hit the site (bdickey)??

702

703
- [x] theme.uiowa.edu

**Comment by briand44** [comment]
Understand the drush archive option to backup.

**Comment by briand44** [comment]
Here are some docs for backing up sites but it looks like it is geared more towards D9 sites. https://wiki.uiowa.edu/display/drupaldev/Backing+up+a+site+before+deletion

**Comment by richardbporter** [comment]
https://wiki.uiowa.edu/display/sitenow/Backing+up+a+site+before+deletion

**Comment by briand44** [comment]
Created a new folder for the inactive site backups. https://iowa.sharepoint.com/sites/CSI-Drupal2/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=bUk1ZD&cid=0b4106e6%2De8f8%2D464f%2D8631%2D60e42fbb89a5&FolderCTID=0x0120002F9851D81A9B1E4DB63DA70E38793599&id=%2Fsites%2FCSI%2DDrupal2%2FShared%20Documents%2FGeneral%2Fsite%2Dbackups%2FInactive%20Site%20Backups&viewid=bf54b9d9%2D0975%2D4fbc%2D9f1b%2D6377bdc2307c

**Comment by briand44** [comment]
I've created backups for all the sites listed in the first slice of this. @richardbporter can you take a look and double check that I created the backups correctly before I start removing any sites?

**Comment by richardbporter** [comment]
I checked a few random ones and can see the site code, SQL dump and files after downloading the zip file. I think as long as you remembered to pull files from prod env, they should be good. 👍🏻

**Comment by briand44** [comment]
Thank you!!

**Comment by briand44** [comment]
First slice all done.

**Comment by briand44** [comment]
>zaheer.lab.uiowa.edu - dnkemper - spreadsheet says domain was removed but I can still hit the site (bdickey)??

It looks like the dev and stage domains were removed but the prod domain must have been missed. I went ahead and removed the prod domain since there still had not been any log in activity on that site. Will remove the site with the others as planned.
