### ISSUE TITLE
Launch https://itcommunities.stage.drupal.uiowa.edu/ 10/28/21

### ISSUE THREAD

**Issue by dnkemper** [uiowa/uiowa#4364]
Location: uiowa01

Webform request URL: https://sitenow.uiowa.edu/admin/structure/webform/manage/request_a_site/submission/10511/edit?destination=/admin/structure/webform/manage/request_a_site/results/submissions%3Fsearch%3Dcommunities

**Comment by richardbporter** [comment]
Is this done? :)

**Comment by dnkemper** [comment]
@richardbporter you're saving me today. Yes. Sorry about that!
