### ISSUE TITLE
As a webmaster, I can use the built-in webform flex layout and expect my form elements to be aligned

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#4370]
# Story

As a webmaster, I can use the built-in webform flex layout and expect my form elements to display 

This will come in handy if we want to allow forms in the prefooter region. 

# Proposed solution

Investigate if the webform "Layouts" will work for our forms.   If they do, make design adjustments as needed. 

<img width="1575" alt="Screen Shot 2021-10-28 at 3 09 13 PM" src="https://user-images.githubusercontent.com/1036433/139328086-6f286ac4-0272-43d6-971c-94deba03fb33.png">

Old idea:
<details>
We would need the utility class to do something like what's below, or maybe we want to use our grid layout classes in https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/scss/components/grid.scss.

```
.form-container--flex {
  display:flex;
}

.form-container--flex  * + * {
  margin: 0 10px;
  align-self: flex-end;
}

.form-container--flex  .form-actions.webform-actions {
  margin-bottom: 2rem;
}
```
</details>

**Comment by makurj** [comment]
I would like to pair on this.

**Comment by dnkemper** [comment]
Going to add #4388 fix to this too

**Comment by dnkemper** [comment]
Update: moved #4388 to its own PR - Ben made the excellent executive decision to keep them separate. Thank goodness for that too 🥳

**Comment by bspeare** [comment]
We changed the user story of this issue after doing some investigation into the default layouts that the webform module provides.  The work surrounding this issue was mostly to make some small tweaks to our form styles to make them look good using webform's layout options.
