### ISSUE TITLE
Walking 175th anniversary tour on Concept3d

### ISSUE THREAD

**Issue by mjoneill** [uiowa/uiowa#4374]
As a visitor interested in the 175th anniversary of Iowa, I can go to a maps.uiowa.edu/* url for a curated walking tour of historical locations on campus. 

Tour can be staged before go-live.

This tour is powered by Concept3d, and needs to be up and running by the end of February.

Similar to Penn State's walking tour.  The goal is not to have people walking around on campus in Feb, but clicking through a tour with stops at historical locations, links to pages or photos, etc...
https://map.psu.edu/?id=1134#!t/1953:1

**Comment by joewhitsitt** [comment]
Where is this content coming from, is it ready?

Update: 175th committee is working on it. Not ready

**Comment by joewhitsitt** [comment]
Training was recorded for this functionality to share with others

**Comment by briand44** [comment]
This is no longer needed. Going to close this. We can reopen if things change.
