### ISSUE TITLE
Change submit button scoping

### ISSUE THREAD

**Issue by cory-skeers** [uiowa/uiowa#4387]
# Story

As a developer I want form submit button styling to apply to any id, so that I don't need to rely on manually updating the button id to receive proper styling, as this have unintended consequences.

Example encountered while working on the Thank You forms:
![image](https://user-images.githubusercontent.com/49074566/139848675-19ea6b8d-7480-45d5-a6e6-df38a0dc931f.png)

# Proposed solution

Update the scoping in:
https://github.com/uiowa/uiowa/blob/a147127e2d867f017d1fd8a26d7370ba1cd0d808/docroot/themes/custom/uids_base/scss/components/form/forms.scss#L717-L754
to apply to all buttons, or all 'submit' buttons, without relying on too specific an id.

**Comment by richardbporter** [comment]
>so that I don't need to remember to update the button id to receive proper styling.

Just want to mention that changing a form input ID is not advised as that can break things like unique ID creation, AJAX, etc.
