### ISSUE TITLE
As a webmaster, I can include embedded forms in prefooter

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#4389]
Related issue: https://github.com/uiowa/uiowa/issues/4370

## Proposed Solution
- [x] Update related config to include webform
- [x] Account for any style issues different from normal page placement

**Comment by makurj** [comment]
I would like to work/pair on this.

**Comment by makurj** [comment]
Once this is set up, test and make sure remote post continues to work for Tippie webforms.

**Comment by makurj** [comment]
@bspeare Webforms and inline webforms are working. However, the submit button for the inline webform is not getting the right color. 
<details>
<summary>Screenshot here:</summary><img src="https://user-images.githubusercontent.com/52135878/141529721-a84391de-e2a0-463a-8e72-af0f66ee1447.png">
</details>

**Comment by cory-skeers** [comment]
> Webforms and inline webforms are working. However, the submit button for the inline webform is not getting the right color.
> 
> Screenshot here:

I think this is related to #4387. The CSS is scoped to the ID, but only the first webform will have that exact id.

**Comment by makurj** [comment]
Just tested again and it seems that it changes based on whether it's a customized button or not. For example, if you set the button's text as something other than "submit", which is the default, and save, then it appears correctly.

<details>
<summary>Screenshot here:</summary><img src="https://user-images.githubusercontent.com/52135878/141530346-c3543c37-32c1-448e-9c4a-d849ecf271af.png">
</details>

**Comment by GaryRidgway** [comment]
Upon further investigation, @cory-skeers is completely correct and we are adding `edit-submit` to the style rules and that should cover our issues.

**Comment by makurj** [comment]
Our newest commit should resolve #4387
