### ISSUE TITLE
Provide print.css for general browser printing

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#4393]
# Story

As a site visitor I want to be able to print a page on SiteNow v3 and have that output be fairly clean and readable.

Though entity print has been made available for certain content, a general print style can serve most other content.

# Proposed solution

- [ ] Establish print.css to be available on all pages.
- [ ] Style certain content to have a decent print style fallback. (header, footer, body fields, etc.)
- [ ] Hide other elements that might not be necessary for print (background images/colors, etc.)

**Comment by bspeare** [comment]
Can we close this?  I think https://github.com/uiowa/uiowa/pull/5753 forgot to add the resolve label.

**Comment by joewhitsitt** [comment]
yeah
