### ISSUE TITLE
As a site owner, I can align my block headline to the left or center

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#4402]
# Story

As a site owner, I can align my block headline to the left or center so that site owners don't have to create separate text areas to center their headings. 

Currently, I'm seeing a lot of site owners create separate text areas just to center a headline style.  Adding an alignment option to the Headline would help us reduce the technical debt of having custom text areas with custom headline classes when they could be using the built-in Headline field.  

# Proposed solution

- Add a "Headline alignment" select option to the Headline, these files are the main headline files to update:             
  - https://github.com/uiowa/uiowa/blob/75d37e08e6fd5de44f5dd3174db9d21286f7babe/docroot/modules/custom/uiowa_core/src/HeadlineHelper.php
  - https://github.com/uiowa/uiowa/blob/c05630523a8d365227edb66a78d40195da167a2e/docroot/modules/custom/uiowa_core/src/Element/Headline.php
  - Possibly https://github.com/uiowa/uiowa/blob/c05630523a8d365227edb66a78d40195da167a2e/docroot/modules/custom/layout_builder_custom/src/Plugin/Field/FieldType/UiowaHeadline.php
- Use `headline--center` as modifier class to center headline.   The left default option does not need a class. 
- Pass the headline alignment option to the template https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/templates/uids/headline.html.twig

<img width="653" alt="Screen Shot 2021-11-03 at 1 24 40 PM" src="https://user-images.githubusercontent.com/1036433/140417660-3a85df4f-1c76-4afc-933f-341fff710f48.png">

**Comment by cory-skeers** [comment]
This would be for the block itself, and not the section, right? So in the case of wanting a headline over a 3-col layout would still be some form of another block in a 1-col above the 3-col section?

**Comment by bspeare** [comment]
Yes, just the block but a section headline would come in handy for reducing all of the custom text areas used for that as well!

**Comment by e-marie-w** [comment]
Quick update on where this is at: Collection, Events, Text Area, and RSS Feeds blocks all working fine. Alignment options appear but do not work for Image Gallery, Slider, Timeline, Articles List, and People List blocks.

For Image Gallery, Slider, and Timeline selecting the center option adds the `headline--center` class fine, but it won't visually change. The list blocks don't work at all currently.
