### ISSUE TITLE
Carousel paragraph bundle image gallery view mode

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#441]
It would be nice to allow the carousel paragraph bundle to be displayed as thumbnails that open in a modal. The modal would be a carousel that navigates to the other slideshows.

A field or class that allows users to pick which view mode to render the carousel as.

Blocked by #357

**Comment by joewhitsitt** [comment]
If the idea that the carousel could contain other items besides just images (e.g. stat), I think this issue should be defined to just be an image gallery bundle with a multi media upload field separate from carousel.
