### ISSUE TITLE
Education launch

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#4416]
- [x] screaming frog
- [x] design review
- [x] copy review
- [x] Dev volunteer for go-live
- [x] Confirm certs (bare, www)
- [x] Assist with post-go-live (analytics, seo)

what time?

**Comment by richardbporter** [comment]
The www domain is not in the uiowa02 cert but I will update that later.

**Comment by richardbporter** [comment]
I will launch it tomorrow between 8-9am.

**Comment by richardbporter** [comment]
Updated cert.
