### ISSUE TITLE
Boring "Subscribe to News" link on SiteNow Articles page.

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#4435]
# Problem
The Subscribe to News link at the bottom of the SiteNow Articles page is an just a standard link. Compared to the View More Events button link or the View More button created on an Articles block, it could use some styling:
![Screen Shot 2021-11-12 at 12 08 39 PM](https://user-images.githubusercontent.com/3067017/141515227-e73e7e49-87bf-406c-8db4-696229d9cd0c.png)

# Steps to reproduce
Create a SiteNow Articles page and check Show RSS Feed icon in the SiteNow Articles settings page: /admin/config/sitenow/uiowa-articles. I dont even see the feed icon for my sites.

# Proposed solution
Style this link like the View More buttons from other blocks?

**Comment by joewhitsitt** [comment]
This could also extend to all taxonomy term subscribe links

**Comment by quamsta** [comment]
@mark-bennett-uiowa We're actually having the opposite problem here, where people are clicking on the "Subscribe to" link on a taxonomy term for subscribing to scholarships, for example:

https://sds.studentlife.uiowa.edu/tags/ui-scholarships-students-disabilities

<img width="568" alt="Screen Shot 2022-01-11 at 10 22 23 AM" src="https://user-images.githubusercontent.com/472923/148981143-5370fdcc-2eb3-4b16-85b8-188d032130a1.png">


...But they're just hitting an RSS/XML feed that they don't really understand or know how to use. Most browsers don't provide a path to subscribing to feeds anymore by default unfortunately.

I'm wondering if in some cases these feed links could go away entirely and those who want to subscribe to a feed can just use Feedly or whichever client and add the subscription manually by entering the url (like the one above) and the feed reader can find the RSS feed via a meta tag.

**Comment by quamsta** [comment]
Also, we could just remove the link on the taxonomy term but leave it in the articles view, since it might be more useful in articles than in something specific like a taxonomy term.

**Comment by quamsta** [comment]
Here are what all major browsers do when you click a feed link without any browser extensions or third party tools (1/11/22):

Chrome:
<img width="942" alt="Screen Shot 2022-01-11 at 10 28 15 AM" src="https://user-images.githubusercontent.com/472923/148982463-eed98e1f-5818-4845-9af1-d99d4fd259da.png">

Safari:
<img width="1120" alt="Screen Shot 2022-01-11 at 10 27 50 AM" src="https://user-images.githubusercontent.com/472923/148982299-18310769-d00f-4bfd-832d-cd3228341cf8.png">

Firefox:
<img width="486" alt="Screen Shot 2022-01-11 at 10 27 36 AM" src="https://user-images.githubusercontent.com/472923/148982264-520d6f1b-a9ae-4aea-9b4c-9ce6af772934.png">

**Comment by joewhitsitt** [comment]
RSS is making a comeback: https://blog.chromium.org/2021/05/an-experiment-in-helping-users-and-web.html

**Comment by joewhitsitt** [comment]
Can we just rename it to "Subscribe using RSS" or something to make it less like a mailing list link?

Another thing to consider is altering the link to do a "you are being directed to an RSS path that may or may not be supported or handled properly by your browser. read more about RSS feeds here (link). get me out of here (link)" type thing

**Comment by mark-bennett-uiowa** [comment]
@quamsta and @joewhitsitt I think you are both making excellent points. More than anything I just wanted to see the link styled like the events or news link buttons, if we were going to keep this RSS feed link. If the team decides to lose the link, I would be fine with that (although I do have department sites that feed parent division sites and would need this RSS feed link). If the team prefers to redesign the button to be more explanatory to users, I would be fine with that as well.

**Comment by quamsta** [comment]
@joewhitsitt Until Chrome or other browsers are handling RSS feed anchor tags in the body of the DOM in a decent way by default, I think it's important to just remove the link from the public view. 

I think it's relevant to mention that each page in SiteNow that has its RSS feed linked to in a metatag within `<head>` that Chrome or any other browser or a developer can use to detect a feed for features like the "Follow" button described in the Chromium blog you linked to, ex:

`<link rel="alternate" type="application/rss+xml" title="UI Scholarships for Students with Disabilities" href="https://sds.studentlife.uiowa.edu/taxonomy/term/16/feed"/>`

Shows up in the `<head>` of https://sds.studentlife.uiowa.edu/tags/ui-scholarships-students-disabilities

@mark-bennett-uiowa This means that the feed URL should be discoverable if you view a news page's or term page's source from a browser if you need to feed other websites with articles or other content.

I'm really in the mindset that until browsers are handling these links decently again (they used to! Safari used to have a little "RSS" button in the address bar that was sweet, but again, used the metatag and not a link in the body of the document), we probably shouldn't muddy the waters and try to explain what RSS is on each taxonomy term's page or each news page.

**Comment by joewhitsitt** [comment]
Like https://github.com/uiowa/uiowa/issues/4695#issuecomment-1026012515 should this issue be closed?

**Comment by mark-bennett-uiowa** [comment]
Yes, closing this issue due to updates in #4695 . Thanks!
