### ISSUE TITLE
Image size resets to large when editing a remote video on a card set to medium image size

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#4441]
# Problem
Image size resets to large when editing a remote video in a card set to medium image size

# Steps to reproduce

Try editing the block on https://sandbox.prod.drupal.uiowa.edu/node/616/layout and note that the current image size is "Medium" but the block will reset to "Large" when you edit the block. 

# Proposed solution
Revisit https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/layout_builder_custom/js/card-block-form.js

**Comment by makurj** [comment]
I would like to work/pair on this.
