### ISSUE TITLE
WhitmanWeb - Initial setup

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#4443]
# Story

As a WhitmanWeb site owner I can publish writings in multiple languages.

# Proposed solution

* Create site split.
* Turn on translation.
* Add a "Writing" content type. Don't worry about fields besides body for now.
* Add and export all config changes to site split.

**Comment by briand44** [comment]
Added blocked label to have conversation with customer before moving forward.

**Comment by briand44** [comment]
Closing as this work will happen as part of https://github.com/uiowa/uiowa/issues/3868
