### ISSUE TITLE
Accessibility Review

### ISSUE THREAD

**Issue by gdelliott** [uiowa/uiowa#445]
After D8 feature parity complete, have Todd perform accessibility review

**Comment by joewhitsitt** [comment]
Either we should wait for #509 or make sure Todd is aware of the upcoming release which fixes it.

**Comment by joewhitsitt** [comment]
Compliance sheriff was run on HR recently. The only errors seem to be content related.

**Comment by joewhitsitt** [comment]
This is an ongoing process which results in multiple issues. Closing for now.
