### ISSUE TITLE
Add Help Desk role and perms to Signage/HC Signage

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#4471]
# Story

As a ITS Help Desk staff member, I would like to be able to access the Signage services so we can be the first level of support for this service.

# Additional Information
The ITS Help Desk is going to begin being the first level of support for Signage. Once they have the ability to access Signage, the plan is to setup an auto reply from the ui-signage email letting folks know the support process has changed as well as auto create HD tickets from emails to UI-Signage (not our responsibility to handle the email auto-reply and ticket creation).

The Help Desk should be granted access to Signage and HC Signage with permissions to create users and grant access to signs, create signage groups and any other permissions that make sense.

Help desk AD group is ITS-HD-Staff

# Proposed solution

- Create Role for HD
- Assign HD role if member of ITS-HD-Staff
- Assign permissions to create users, grant access to signs, create signage groups, etc.
- Make sure the changes happen to both Signage and HC Signage
- Communicate with Jessica, Jamie Matthews and Jacob Ricke that access is available

**Comment by makurj** [comment]
Do these permissions for the HD role look good? 
![image](https://user-images.githubusercontent.com/52135878/144653108-7aa0b739-7fbb-4be7-addb-b5e009310c5e.png)

**Comment by makurj** [comment]
Also, can we create a duplicate issue for the Healthcare part of this which has to be done on campus?

**Comment by joewhitsitt** [comment]
Hard to visualize these permissions without comparing them to another role.

Are permissions featurized? If so, it is my understanding that this can be replicated and deployed for healthcare and that is is possibility running a feature revert while on campus.

**Comment by makurj** [comment]
I copied some from webmaster. I can do a screen recording of both side-by-side. 

None of the features looked overridden once I made these changes locally, and working tree was clean also. So I'm thinking this will need to be done directly on prod for both signage.uiowa and signage.healthcare.

**Comment by makurj** [comment]
https://user-images.githubusercontent.com/52135878/144655390-177fb409-443e-4c4e-a786-be0a5bd1aa64.mp4

**Comment by makurj** [comment]
"Assign HD role if member of ITS-HD-Staff" does this mean go through the AD group and assign the new HD role to all the folks in that group, or is this about setting up logic somewhere to check against the AD group automatically?

**Comment by joewhitsitt** [comment]
>Assign HD role if member of ITS-HD-Staff

There is functionality here: admin/config/people/simplesamlphp_auth/sync to auto map an AD group to a particular role id. The its.uiowa.edu website does this for the ITS-HD-Staff AD group and can be used as a reference. The role id will probably be different. Not sure if this is tracked in features or would have to be another live change. We would ultimately need someone from that AD group to try logging in to see if they auto get the role.

**Comment by joewhitsitt** [comment]
Thanks for the side-by-side diff of permissions. I don't know what all we expect this role to be able to do, but I did notice some gaps that a webmaster can do that hd staff can't do. It will be hard for them to support a webmaster if they can't equally do the same operations. Additionally, I am sure there are certain permissions they need to stand in for an administrator. If you can masquerade as a user with that role and perform the tasks listed in the IS and any other common support tasks that we handle as part of Signage support then I think it will be a good first step.

>Assign permissions to create users, grant access to signs, create signage groups, etc.

**Comment by makurj** [comment]
Made my account on https://signage-dev.uiowa.edu/ an HD role one and I can edit people, edit groups, add signs, add slides but I cannot masquerade. The option is not available, even with “masquerade as user” and “masquerade as any user” checked for the HD role. Anyone have any thoughts on how to make this work?

**Comment by makurj** [comment]
Allowing HD role to use the administration theme also allowed for masquerade to show up.

**Comment by e-marie-w** [comment]
Okay, I've tested:
- creating a user account (& changing status from pending to active)
- creating a signage group
- adding & removing user from a signage group
- adding/editing a sign
- adding & removing slide from a sign
- masquerading as a user

Am I forgetting something that should be tested? Otherwise I'll remove my added sign & signage group as a last check.

**Comment by makurj** [comment]
Thanks @e-marie-w! I think that should be it.

**Comment by e-marie-w** [comment]
One thing I noticed: helpdesk role can't specify what roles others have. When you add people they are given the editor role automatically. Is this enough or should helpdesk be able to add the webmaster role?

**Comment by makurj** [comment]
I'll let @briand44 weigh in on that.

**Comment by briand44** [comment]
It looks like there are only a handful of users that have the webmaster role and those users were all created in the last few months. I'm wondering if folks are even supposed to have the level of access? We may need to remove the webmaster role from those folks if that is the case.

**Comment by makurj** [comment]
Sounds good. I'll check with Jessica.

**Comment by makurj** [comment]
Confirmation from Jessica. It's all working well on signage.uiowa.edu. This can be done on Healthcare once someone is on campus. Set up the HD role and its permissions, which can be copied from https://signage.uiowa.edu/admin/people/permissions/6

Add the HD AD group here: https://signage-dev.uiowa.edu/admin/config/people/simplesamlphp_auth/sync
|8:urn:oid:2.5.4.31,=,"CN=ITS-HD-Staff,OU=Groups,OU=Helpdesk,OU=Services,OU=ITS,DC=iowa,DC=uiowa,DC=edu"

**Comment by makurj** [comment]
Done on healthcare signage and added the whole web team as admins.
