### ISSUE TITLE
Grad Admissions Areas of Study

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#4473]
Grad Admissions would like an Areas of Study content type that has similar fields to the existing Grad Admissions site (https://iowa.sharepoint.com/:w:/r/sites/CSI-Drupal2/_layouts/15/Doc.aspx?sourcedoc=%7B611D3AB0-35BC-4BB4-A703-71548F2D1778%7D&file=AoS_Fields.docx&action=default&mobileredirect=true).

Grad Admissions would like to display the Areas of Studies similarly to the main admissions site (https://admissions.uiowa.edu/areas-of-study). One catch here is that each Area of Study can have one or more degree options that may contain the same or different information.

# Additional Info
Will reference Estimated Costs, Colleges

# Proposed Solution
~Area of Study~ -added in #4523 

~Program Page Name~ -added in #4523  

~Subtitle~ -added in #4523 

**Degrees (choose)** -Display on full page or not?

~See also~ using AoS taxonomy description instead in #4568 

~Intro~ -added in #4523 

~Links (sidebar)~ -added in #4523 

~· Catalog~ 

~· Department~
^^both fields combined = related links -added in #4523 

~· College (choose)~ added in #4523 

~Estimated cost of attendance intro~ - Added in #4475 

~Estimated cost of attendance (choose)~ - Added in #4523 

~Admission requirements~ -added in #4523

~Application deadlines~ -added in #4523 

~Application Procedures~ -added in #4523

~Apply (sidebar)~ -added in #4523 

~Contact information (sidebar)~ - added in #4523

**Comment by dnkemper** [comment]
Added multiple fields to #4523 since was fresh in back of my mind after meeting. Hope that's okay and I'm sorry in advance.

**Comment by joewhitsitt** [comment]
So, from looking at #4523, most of this is in progress and/or already done and that the view page could probably just be split out from this. Moving to parking lot to discuss where this should actually be on the board.

**Comment by briand44** [comment]
Closing this as most of this work is complete. Will create follow up issues based on feedback from Admissions meeting
