### ISSUE TITLE
Grad Admissions Cost Estimate

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#4475]
- [x] Estimated costs for domestic and international students for Graduate Programs. Tied to an area of study. Similar fields to existing Grad Admissions site (year and cost estimate for US as well as year and cost estimate for international).
- [x] Multiple grad areas of study could reference a single cost estimate.
- [x] The cost estimates would be rendered as links on the grad area of study (not outputting all info on the grad area of study).
- [x] Admissions likes the tabbed interface to switch between domestic and international estimated costs but are open to other ideas that make sense.
- [x] There won't be a list of all cost estimates, users would need to navigate to the grad area of study to find the cost estimate specific to that degree option.
- [x] Add entity reference field and cost estimate info field to AOS
- [x] URL path: /costs/title

**Comment by joewhitsitt** [comment]
This should be added to https://github.com/uiowa/uiowa/pull/4523

**Comment by dnkemper** [comment]
Question. Could we utilize the 'tab' field groups in 'manage display'?

Here's how it looks after adding a tabs field group to entire content type, then adding two separate tab field groups to domestic and international
<img width="885" alt="Screen Shot 2021-12-10 at 3 41 19 PM" src="https://user-images.githubusercontent.com/16872949/145647586-85915951-249b-4f1e-be4c-ac73321553a9.png">

**Comment by dnkemper** [comment]
Second question: is there a desired URL path we need to setup?

**Comment by briand44** [comment]
>Second question: is there a desired URL path we need to setup?

I just asked Scott in the redesign-admissions slack channel.

**Comment by dnkemper** [comment]
thank you, @briand44!

**Comment by dnkemper** [comment]
Messaged Brian and Michael, but adding this here for visibility too. 

Discussed how to move forward with the estimated costs content type. The team thought it would be best to remove the custom content type all together and reference individual pages (filter by an “estimated cost” tag). Then provide a way to relate two pages to provide a tabbed like implementation like: https://admissions.uiowa.edu/finances/estimated-costs-attendance. In the future, if we provide a layout builder solution for tabs there are content concerns with the amount of content being placed in them - how we reached this decision.

Proposed solution
- inform Scott that there will be tab like feature but will be done similar to the main admissions site.
- remove estimate costs content type
- change AoS reference for estimated costs to basic page.
  -- consider tag based subset of pages for fewer results.
- manual migration of each estimated costs to two basic pages (maybe tagged)
- each page will be placed in the menu system and horizontal style menu will be configured for the pages.

**Comment by briand44** [comment]
Thanks. I am a little confused by this:
>Then provide a way to relate two pages to provide a tabbed like implementation

>each page will be placed in the menu system and horizontal style menu will be configured for the pages.

So will each domestic and international cost estimate page need to be added to the menu system or will this happen dynamically based on relating two pages?

**Comment by dnkemper** [comment]
Ah, yes. Provide a way to relate domestic and international estimated cost pages to produce the tab like menu. From my understanding, there’s a way to implement this without having to display them in the actual main navigation menu. Like make international page rely on domestic page? @pyrello please correct me if I'm butchering this.. slightly fried

**Comment by joewhitsitt** [comment]
The main admissions site has these tied to the main menu. I would assume the same for these unless they have a custom menu. Granted there are more of them and we would need to still pair them through a parent item (nolink) or something.

**Comment by briand44** [comment]
I think we want to run this by Scott to get feedback before we blow up what we have so far. Not sure if adding all these pages to the menu will get push back
