### ISSUE TITLE
As a site owner, I can display an events list with teaser text that allows `<a>` tags

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#4477]
# Story

As a site owner, I can display an events list from events.uiowa.edu with teaser text that allows `<a>` tags so that site visitors can click on register and zoom links without clicking through to the next page. 

# Proposed solution

- Update docroot/modules/custom/sitenow_events/includes/sitenow_events.teaser.inc to allow `<a>` tags by updating `Xss::filter` to include an allowed list or switch over to use `Xss::filterAdmin` which is what the full display uses for better or worse.  
- For reference https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Component%21Utility%21Xss.php/class/Xss/9.2.x

**Comment by joewhitsitt** [comment]
Do we have link wrapping ready for this?

**Comment by bspeare** [comment]
It's ready!

**Comment by bspeare** [comment]
This work will help us close this issue: https://github.com/uiowa/uiowa/issues/4085.

**Comment by joewhitsitt** [comment]
Updated IS with more specifics
