### ISSUE TITLE
Reduce space between ::before icon and Admin Login link in footer

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#4487]
Currently it is set to padding-right: 1.05rem. Could this be cut in half to more closely match the icon in a footer address?
<img width="333" alt="Screen Shot 2020-05-26 at 12 48 06 PM" src="https://user-images.githubusercontent.com/3067017/82940304-3d261380-9f5a-11ea-868e-d83adedbb576.png">

**Comment by bspeare** [comment]
I transferred this from `uids`.   This still seems like a good idea to adjust the login icon size and padding to match the icons in the footer address. 

Adjust spacing here: https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/scss/components/footer.scss#L30-L39.
