### ISSUE TITLE
.tippie.uiowa.edu SSL cert on uiowa02

### ISSUE THREAD

**Issue by dnkemper** [uiowa/uiowa#4488]

**Comment by bspeare** [comment]
Just found this in `uids`, is it still needed? :)

**Comment by richardbporter** [comment]
> Just found this in `uids`, is it still needed? :)

Ditto. I might create a cert soonish.

**Comment by richardbporter** [comment]
Update: if this was for *.tippie.uiowa.edu, then that is already covered on uiowa02.

If it was for another domain, sorry and feel free to reopen!
