### ISSUE TITLE
Question: "Why is only one 175-related event showing up on the 175 anniversary site?" (https://175.uiowa.edu)

### ISSUE THREAD

**Issue by makurj** [uiowa/uiowa#4493]
Can you tell me if there's a technical problem or a workflow problem (or possibly both)?

Here's an example of another event that should be there: https://events.uiowa.edu/56010

**Comment by makurj** [comment]
Found only this in Slack: 
https://iowaweb.slack.com/archives/C02GA7SEYFP/p1633449419027700
https://iowaweb.slack.com/archives/C02GA7SEYFP/p1633471504038600

**Comment by makurj** [comment]
Email chain in ITS-Web: 

From: ITS Web Technology Services <its-web@uiowa.edu>
Date: Friday, October 29, 2021 at 12:35 PM
To: "Remesh Ranjini, Raaj" <remeshranjini-raaj@uiowa.edu>, "Mills, Brandon T" <brandon-mills@uiowa.edu>, "Rinner, Andrew L" <andrew-rinner@uiowa.edu>
Subject: Re: events.uiowa.edu prolems

Raaj,

The original issue seemed to be that events tagged with this event type were not showing up on events.uiowa.edu but can be accessed through other integrations with content.uiowa.edu. Looks like there is currently one event that has been tagged with this event type:

https://175.uiowa.edu/

https://175.uiowa.edu/event/80911/0 links to https://events.uiowa.edu/event/drupal/80911

Not seeing this Friday, August 26 to Sunday, August 28, 2022 (all day) event here:

https://events.uiowa.edu/?d=20220826

The event type (175th Anniversary) still doesn't seem to show as a filter option on the events.uiowa.edu page: https://events.uiowa.edu/

Beyond these details, we don't know how events.uiowa.edu handles things.

Joe

OSC - Web Services
 
From: Remesh Ranjini, Raaj <remeshranjini-raaj@uiowa.edu>
Sent: Friday, October 29, 2021 12:19 PM
To: ITS Web Technology Services <its-web@uiowa.edu>; Mills, Brandon T <brandon-mills@uiowa.edu>; Rinner, Andrew L <andrew-rinner@uiowa.edu>
Subject: RE: events.uiowa.edu prolems 
 
It does look like the API is returning “175th Anniversary” as one of the event types. Could you please tell me what I need to do to reproduce the issue on my end?
 
Thanks,
 
Raaj
 
From: ITS Web Technology Services <its-web@uiowa.edu> 
Sent: Friday, October 29, 2021 11:44 AM
To: Remesh Ranjini, Raaj <remeshranjini-raaj@uiowa.edu>; Mills, Brandon T <brandon-mills@uiowa.edu>; Rinner, Andrew L <andrew-rinner@uiowa.edu>
Subject: Re: events.uiowa.edu prolems
 
Hi Raaj,
 
It is our understanding that https://content.uiowa.edu/api/v1/views/filters_api.json?display_id=filters is periodically fetched on the events.uiowa.edu side which contains the new event type (175th Anniversary).
 
Here is additional API information: https://content.uiowa.edu/events-api
 
The events themselves are posted to https://events.uiowa.edu/api/event/.
 
Hope this helps in tracking this down,
 
Joe
 
OSC - Web Services
 
From: Remesh Ranjini, Raaj <remeshranjini-raaj@uiowa.edu>
Sent: Friday, October 29, 2021 11:34 AM
To: ITS Web Technology Services <its-web@uiowa.edu>; Mills, Brandon T <brandon-mills@uiowa.edu>; Rinner, Andrew L <andrew-rinner@uiowa.edu>
Subject: RE: events.uiowa.edu prolems 
 
Hi Web team,
 
Could you please tell us what the data source for this calendar is?
 
Thanks,
 
Raaj
 
From: ITS Web Technology Services <its-web@uiowa.edu> 
Sent: Thursday, October 21, 2021 9:35 AM
To: Mills, Brandon T <brandon-mills@uiowa.edu>; Rinner, Andrew L <andrew-rinner@uiowa.edu>
Cc: Remesh Ranjini, Raaj <remeshranjini-raaj@uiowa.edu>
Subject: Re: events.uiowa.edu prolems
 
Hi Brandon, 
 
Checking in to see if you have any updates on this?
 
OSC - Web Services
 
From: ITS Web Technology Services <its-web@uiowa.edu>
Sent: Tuesday, October 12, 2021 10:03 AM
To: Mills, Brandon T <brandon-mills@uiowa.edu>; Rinner, Andrew L <andrew-rinner@uiowa.edu>
Cc: Remesh Ranjini, Raaj <remeshranjini-raaj@uiowa.edu>
Subject: Re: events.uiowa.edu prolems 
 
Hey Brandon, 
 
Any update on this?
 
-Alan
 
From: ITS Web Technology Services <its-web@uiowa.edu>
Date: Friday, October 8, 2021 at 1:38 PM
To: Mills, Brandon T <brandon-mills@uiowa.edu>, Rinner, Andrew L <andrew-rinner@uiowa.edu>
Cc: Remesh Ranjini, Raaj <remeshranjini-raaj@uiowa.edu>
Subject: Re: events.uiowa.edu prolems
https://sandbox.prod.drupal.uiowa.edu/example-events-175th-anniversary
 
No worries! If you click the link above and then choose either event, if you choose “View on event calendar” it will error.
 
Does that help?
-Alan
 
From: Mills, Brandon T <brandon-mills@uiowa.edu>
Date: Friday, October 8, 2021 at 12:12 PM
To: ITS Web Technology Services <its-web@uiowa.edu>, Rinner, Andrew L <andrew-rinner@uiowa.edu>
Cc: Remesh Ranjini, Raaj <remeshranjini-raaj@uiowa.edu>
Subject: RE: events.uiowa.edu prolems
…adding Raaj to the conversation as Andrew is heads down on a different issue.
 
Thanks Alan!
Can you tell me more specifically which link(s) aren’t working?  When I click through on the events links in the sandbox they appear to work for me.

Thanks!
 
From: ITS Web Technology Services <its-web@uiowa.edu> 
Sent: Friday, October 8, 2021 11:22 AM
To: Mills, Brandon T <brandon-mills@uiowa.edu>; Rinner, Andrew L <andrew-rinner@uiowa.edu>
Subject: events.uiowa.edu prolems
 
Hey there!
 
Alan here with the OSC web team on support rotation today. We received an email yesterday about two events that were entered on content.uiowa.edu recently that are not showing up on their respective dates on events.uiowa.edu. They were given a new “Event type” tag called “175th Anniversary”. 
 
Upon further investigation It seems that even when we place an events block on our sitenow sites and try and click through the links on these items, we are receiving 500 errors, as seen here below the getting started section (https://sandbox.prod.drupal.uiowa.edu/)
 
I am unsure how to fix this, what might my next steps be?
-Alan

**Comment by makurj** [comment]
Another one:

From: ITS Web Technology Services <its-web@uiowa.edu>
Date: Friday, October 29, 2021 at 9:50 AM
To: "Clair, Christopher W" <christopher-clair@uiowa.edu>
Cc: "Mills, Brandon T" <brandon-mills@uiowa.edu>
Subject: Re: Events approved but not showing up

Hi Chris,

I am not sure if someone responded to this email. We reached out to Brandon Mills and the team that handles the events.uiowa.edu side of things. They are short staffed at the moment and with Brian Finley gone (primary developer of events.uiowa.edu) they haven't had a chance to investigate this.

Joe

OSC - Web Services
 
From: Clair, Christopher W <christopher-clair@uiowa.edu>
Sent: Friday, October 15, 2021 8:43 AM
To: ITS Web Technology Services <its-web@uiowa.edu>
Subject: Re: Events approved but not showing up 
 
Alan, I think I found the problem. 
 
I recently added a new Event Type to the Content Hub taxonomy, that being 175th Anniversary. Ben’s entries both had that tag applied. I re-created the events to see if I could get them to go through. The funny thing is, I forgot to apply the 175th tag when I re-entered one of the events, and that one published as expected.
 
So I think it’s a matter of that new Event Type tag isn’t part of the events.uiowa.edu database—that side’s taxonomy needs to be refreshed or recognize the new tag?
 
For now, I’ve left off the 175th tag, and the events are on the Events Calendar. We do need that new Event Type tag to be part of the forward-facing system, though.
 
Hope this helps.
 
Chris
 
—
Christopher Clair (he/him/his)
Office: 319-384-0900 
uiowa.edu
 
 
 
From: ITS Web Technology Services <its-web@uiowa.edu>
Date: Thursday, October 14, 2021 at 1:03 PM
To: Christopher Clair <christopher-clair@uiowa.edu>
Subject: Re: Events approved but not showing up
 
Hey Chris, 
 
I contacted people about this but they have not gotten back to me yet. I have prodded a few times but received no response. I will prod the bear again!
 
-Alan
 
From: Clair, Christopher W <christopher-clair@uiowa.edu>
Date: Thursday, October 14, 2021 at 12:08 PM
To: ITS Web Technology Services <its-web@uiowa.edu>
Subject: FW: Events approved but not showing up
Following up on this—any ideas?
 
—
Christopher Clair (he/him/his)
Office: 319-384-0900 
uiowa.edu
 
 
 
From: Christopher Clair <christopher-clair@uiowa.edu>
Date: Thursday, October 7, 2021 at 5:19 PM
To: ITS Web Technology Services <its-web@uiowa.edu>
Subject: Events approved but not showing up
 
Ben H entered two events this afternoon, both of which I approved:
 
https://content.uiowa.edu/installation-barbara-j-wilson-university-iowas-22nd-president
https://content.uiowa.edu/2022-presidential-lecture-event
 
They are not appearing on their respective dates on events.uiowa.edu.
 
I added a new Event Type to the taxonomy (that being 175th Anniversary). I don’t know if that would be a factor.
 
Would someone troubleshoot?
 
—
Christopher Clair (he/him/his)
Office: 319-384-0900 
uiowa.edu

**Comment by joewhitsitt** [comment]
The event listed in the IS is not using the same tag used to filter events on 175.uiowa.edu

https://events.uiowa.edu/56010
https://content.uiowa.edu/installation-barbara-j-wilson-university-iowas-22nd-president-0

**Comment by briand44** [comment]
As far as the 175 anniversary events go, I am not seeing any issues. There is only one event in content hub tagged with that event type (https://content.uiowa.edu/event-types/175th-anniversary). There is one event showing on events.uiowa.edu (https://events.uiowa.edu/?f=12506). There is one event showing on 175.uiowa.edu (https://175.uiowa.edu/). The only thing that I can see that should possibly be changed is the View More Events link on https://175.uiowa.edu. It links to https://events.uiowa.edu when I would expect it to link to https://events.uiowa.edu/?f=12506.

**Comment by briand44** [comment]
All events tagged with 175th Anniversary event type are now appearing on events.uiowa.edu. They are not all appearing on the 175th website because of the Audience filter is set to "Everybody" but that is excluding events tagged with 175th Anniversary that have an audience that is not set to "Everybody". I let the site owner know this. Closing this.
