### ISSUE TITLE
Horizontal overflow on mobile

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#450]
Horizontal overflow on mobile.

![image](https://user-images.githubusercontent.com/1068523/62976869-34a58780-bde3-11e9-8b60-a87b9c2b4cc1.png)

 - OS: iOS 12.3.1
 - Browser: Safari
 - Device: iPhone SE
 - Session: anonymous

**Comment by joewhitsitt** [comment]
Looks to be caused by superfish (hidden accordion) and the footer lockup.

Side note: get a bigger phone Rick.

**Comment by joewhitsitt** [comment]
I think @dnkemper was working on this, so I am going to be bold and assign it to her and place it in the In Progress column.

**Comment by dnkemper** [comment]
I had to make changes in the uiowa repo and the uiowa_footer repo
