### ISSUE TITLE
Fix "PanoptoURL" plugin does not exist bug

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#4500]
# Problem
We are seeing instances of the following watchdog errors:
```https://teachonline.prod.drupal.uiowa.edu/media-library?_wrapper_format=drupal_ajax&ajax_form=1&hash=XXX&media_library_allowed_types%5B0%5D=image&media_library_allowed_types%5Baudio%5D=audio&media_library_allowed_types%5Bfacebook%5D=facebook&media_library_allowed_types%5Binstagram%5D=instagram&media_library_allowed_types%5Bpanopto%5D=panopto&media_library_allowed_types%5Bremote_video%5D=remote_video&media_library_allowed_types%5Btwitter%5D=twitter&media_library_content=1&media_library_opener_id=media_library.opener.editor&media_library_opener_parameters%5Bfilter_format_id%5D=filtered_html&media_library_remaining=1&media_library_selected_type=panopto|https://teachonline.prod.drupal.uiowa.edu/node/add/page|11||Drupal\Component\Plugin\Exception\PluginNotFoundException: The "PanoptoURL" plugin does not exist. Valid plugin IDs for Drupal\Core\Validation\ConstraintManager are: Callback, Blank, NotBlank, Email, AddressFormat, Country, FeedTitle, FeedUrl, ModerationState, CropTypeAspectRatioValidation, CropTypeMachineNameValidation, DateTimeFormat, FileUriUnique, FileValidation, LinkAccess, LinkExternalProtocols, LinkNotExistingInternal, LinkType, oembed_resource, FacebookEmbedCode, MenuSettings, PathAlias, RedirectSourceLinkType, TaxonomyHierarchy, ProtectedUserField, UserMailRequired, UserMailUnique, UserName, UserNameUnique, MenuTreeHierarchy, Bundle, EntityChanged, EntityHasField, EntityType, EntityUntranslatableFields, ReferenceAccess, ValidReference, UniquePathAlias, ValidPath, AllowedValues, ComplexData, Count, Null, Length, NotNull, PrimitiveType, Range, Regex, UniqueField, Uuid in Drupal\Core\Plugin\DefaultPluginManager->doGetDefinition() (line 53 of /docroot/core/lib/Drupal/Component/Plugin/Discovery/DiscoveryTrait.php).```

This seems like the one referenced in https://support.acquia.com/hc/en-us/articles/360054634014-How-to-set-a-unique-hash-salt-for-an-individual-site-in-Site-Factory but we should investigate further to make sure its not a different issue with our Panopto media plugin.

# Steps to reproduce
TBD

# Proposed solution
TBD

**Comment by richardbporter** [comment]
It would probably be a good idea to output some APCu stats in the administrative interface before and after making this change, if we do it, to compare. Reading through https://www.drupal.org/project/drupal/issues/2984232 would be wise as well. One comment asks whether per-multsite APCu caches is worth doing at all.

**Comment by joewhitsitt** [comment]
Site editor is experiencing this issue first-hand and unable to add a video. Temporarily unavailable message.

https://iowaweb.slack.com/archives/C02F85V53/p1638464241026200

**Comment by joewhitsitt** [comment]
Waiting to hear back from Acquia about the proposed solution in #4524

**Comment by joewhitsitt** [comment]
Didn't mean to close this, but the #4524 PR seems to have solved teachonline's immediate issue of adding panopto videos.
