### ISSUE TITLE
Metatag configuration not restricted for webmasters

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#451]
**Describe the bug**
There seems to be a lot more configuration available on the metatag admin pages.

**Expected behavior**
I would expect this extra configuration to be hidden for webmasters.

**Screenshots**
![image](https://user-images.githubusercontent.com/1068523/62978018-de861380-bde5-11e9-8d32-6534940059d7.png)
 
**Additional context**
I think we updated metatag recently and this could be new config that we need to hide.

**Comment by richardbporter** [comment]
We should remove the permission for webmasters to configure global metatags. We're only using for site verification and there is too much configuration and risk for them to have access. We should find another way to verify site ownership (https://support.google.com/webmasters/answer/9008080?hl=en).

**Comment by richardbporter** [comment]
Also, I only found one D7 SiteNow site with a verification which was Google. This was not a widely used feature.

**Comment by joewhitsitt** [comment]
For site verification, our docs suggest the Google Analytics approach.
