### ISSUE TITLE
Provision cbig.engineering.uiowa.edu

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#452]
Create webmaster accounts for laverman and jcb. Reassign to me for customer follow up.

**Comment by briand44** [comment]
they want www to redirect to non-www so we will need to remember to create the domain for www as well as make sure we cover it in a cert once they are ready to launch.

**Comment by joewhitsitt** [comment]
I think this is successfully in PROD now with laverman and jcb created as webmasters. Assigning back to Brian for www redirect and customer follow-up

**Comment by briand44** [comment]
Thank You!! I've notified the customers.
