### ISSUE TITLE
Try starting with the AoS feature split (leveraging the degree types taxonomy)

### ISSUE THREAD

**Issue by dnkemper** [uiowa/uiowa#4520]
Grad Admissions would like to display the Areas of Studies similarly to the main admissions site (https://admissions.uiowa.edu/areas-of-study). One catch here is that each Area of Study can have one or more degree options that may contain the same or different information. Could look at Admissions transfer tips for inspiration

**Comment by joewhitsitt** [comment]
I don't think this needs to be a separate slice. I added it as a note to the Epic's IS as something to probe. "Could look at Admissions transfer tips for inspiration" has to do with the estimated costs not the AoS content.

I will add this to https://github.com/uiowa/uiowa/pull/4523 where the AoS split is being turned on.

**Comment by joewhitsitt** [comment]
I think it makes sense to start with the AoS feature split. This IMO is done in #4523 but shouldn't be merged yet
