### ISSUE TITLE
UI Press - Book node design

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#4522]
# Motivation

In preparation for #4328, it would be useful to define how the book page is going to look so that when that work is being done, we can just follow the design.

# Proposed solution

Provide layout builder page on https://uipress.prod.drupal.uiowa.edu to guide development of the layout of the Book node type when it is created.

Existing page example: https://www.uipress.uiowa.edu/books/9781609387488/william-gibson-and-the-futures-of-contemporary-culture

The customer has expressed a desire for a page design that looks like Amazon's book page: https://www.amazon.com/Snow-Crash-Neal-Stephenson/dp/0553380958/ref=tmm_pap_swatch_0?_encoding=UTF8&qid=1638480567&sr=8-1

**Comment by bspeare** [comment]
Does the "Get Permissions" need to be an image button?

<img width="449" alt="Screen Shot 2021-12-07 at 9 18 24 AM" src="https://user-images.githubusercontent.com/1036433/145056146-8380998e-4805-4caa-9f8a-6ed8536aa9a5.png">

There are some better looking search forms listed on https://developers.google.com/books/branding.

**Comment by pyrello** [comment]
I don't think that "Get Permissions" needs to be an image button. I'm guessing that the link is what's important.

I'm open to whatever search box seems to fit the best :)

**Comment by bspeare** [comment]
Are these actions necessary since it doesn't really add anything to a cart?  Seems like one "Buy Now" button would make more sense and create less UX confusion.   The "View Cart" and "Checkout" options seems like they should reside on the shop website. 

<img width="425" alt="Screen Shot 2021-12-07 at 10 12 21 AM" src="https://user-images.githubusercontent.com/1036433/145065169-1bf5edd6-4884-4088-908f-3608ba4fd905.png">

Edit: Add to Cart | View Cart buttons should remain but let's remove the Checkout option because it doesn't really take you to a checkout process.

**Comment by bspeare** [comment]
It also looks like the "Search this book" code needs to be updated because it doesn't seem to work and asks you to try the new version.

**Comment by bspeare** [comment]
@pyrello Are there higher resolution sizes available of these book covers?  https://www.uipress.uiowa.edu/sites/uipress/files/styles/thumbnail/public/attached_images/9781609387488.jpg 150 x 225 is pretty small.

**Comment by bspeare** [comment]
Building out a mockup using layout builder using existing styles is probably the best way to start this design.

**Comment by bspeare** [comment]
I built a mockup locally to get this issue moving:

<img width="1577" alt="1" src="https://user-images.githubusercontent.com/1036433/145111995-b90d243e-2291-4579-a52d-294633782922.png">

**Comment by bspeare** [comment]
Attaching the most recent mockup below. 

![uipress uiowa ddev site_ecospatiality-place-based-approach-american-literature (3)](https://user-images.githubusercontent.com/1036433/150149892-3521af39-ba05-4bb6-abf3-735ed9e1640d.png)

**Comment by pyrello** [comment]
@bspeare Any thoughts about whether we need to get tabs working as a component prior to incorporating them here?

**Comment by bspeare** [comment]
@pyrello I think we would want to develop that in UIDS, but should we wait for Allison's approval?

**Comment by pyrello** [comment]
I'd like to figure out how to move forward without having to wait for approval. Maybe that means we strip out the tab section from this and complete it later?

**Comment by bspeare** [comment]
I think it's a good idea to strip out the tabs until we know.  We can just stack those sections on top of each other.
