### ISSUE TITLE
Remove banner gradient overlay if page title is hidden

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#4531]
# Problem
If the page title is set to "Visually hide title" on the featured image, the overlay gradient meant to provide accessible color contrast ratios still appears. 

<img width="876" alt="Screen Shot 2021-12-03 at 1 20 15 PM" src="https://user-images.githubusercontent.com/1036433/144660564-db360f0a-1cc7-4ee0-a474-28cf156a81a4.png">

# Steps to reproduce
Add a featured image to a Page and hide the page title. 

# Proposed solution
- Add a modifier class in `banner.scss` to remove the gradient: `.banner--gradient-bottom.layout--title--hidden::after`

**Comment by bspeare** [comment]
This is needed for a series of landing pages being built on admissions.uiowa.edu.

**Comment by richardbporter** [comment]
I'd be interested to see if we could write a test for this. It'd be nice if we could write a failing test first, then fix it.
