### ISSUE TITLE
Remove Kaltura support

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#4533]
after 12/28? - Confirm with OTLT

**Comment by joewhitsitt** [comment]
>embedded Kaltura content will no longer be able to playback.

We should remove the ability to add new Kaltura videos but continue to render the existing. Site owners will eventually replace them once they realize their videos will no longer play.

**Comment by pyrello** [comment]
Noting here that videos stopped rendering when the service ended.
