### ISSUE TITLE
Signage: Contrast on select and textarea

### ISSUE THREAD

**Issue by makurj** [uiowa/uiowa#4535]
# Problem
When I'm logged in as an HD role person or masquerade as someone with the helpdesk role, the color contrast on select options and textarea is not enough. It seems it's the color: inherit property for select and textarea.

![image](https://user-images.githubusercontent.com/52135878/144887811-bb7c62d5-16ed-4bfa-a18d-790878eedf77.png)

# Steps to reproduce
Masquerade as someone with the helpdesk role and add or edit a user.

# Proposed solution

**Comment by joewhitsitt** [comment]
I think if the user has permissions for administration and help pages, it will use the correct theme for this route.

**Comment by makurj** [comment]
Tried that. Didn't help.
![image](https://user-images.githubusercontent.com/52135878/144890523-b2acb3b6-7335-45af-9920-aa3907680a19.png)

**Comment by makurj** [comment]
Adding "View the administration them" helped.
