### ISSUE TITLE
Finalize/consolidate top-level categories and sub-categories and how they are navigated

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#4541]
## Problem

Currently concept3d has a mix of default categories and imported categories.

https://cms.concept3d.com/map/cms/?id=1890
https://map.concept3d.com/?id=1890#!

Marie has already made a great pass at this work with https://github.com/uiowa/uiowa/issues/4433

## Proposed Solution

- [x] Consolidate Parking categories, others.
- [x] Hide categories that don't have content.
- [x] Assign certain buildings to multiple categories or find a better home
- [x] Mark buildings that shouldn't be clickable to private
- [x] MRNA Sub-Category of Recreational Facility
- [x] Pat’s Too is missing
- [ ] Additional photo/content work (see Michael's doc ([link to card](https://github.com/orgs/uiowa/projects/1#card-75350831)))
  - ~~Add a photo if there isn't one currently. Suggested that facilities photo be used for now: https://www.facilities.uiowa.edu/buildings~~
  - Get photo team to put together images for the following:
    - Soccer Complex Facility
    - Pediatric Associates Building 2
    - UI Community Home Care
    - Iowa River Landing Parking
    - Any other buildings moving from private/all buildings to another category.
  - Michael plans to chat with Alex about additional content improvements
- [x] Switch all hotlinked images by downloading and re-uploading...
- [ ] Have Michael evaluate/approve from a site visitor perspective.

## For Reference

https://help.concept3d.com/hc/en-us/articles/360023798134-Creating-A-New-Category-

**Comment by joewhitsitt** [comment]
Going to work with Alex to assign points to additional categories, etc.

**Comment by joewhitsitt** [comment]
Alex is going to take a first pass through the buildings to re-assign, consolidate

**Comment by ABoston88** [comment]
I've deleted the Historic Buildings category and made the difference between Athletics and Recreational Facility clearer. Also moved some other items around and did some multi-tagging to make the categories more useful. 

How do we feel about making the "residence" layer private, as well? I'd be surprised if many users come to our maps for that information. It might confuse some users when they're trying to find student housing...and it's a pretty large list when folded out. Nesting it under Housing instead might make the distinction between residence halls and residences even less clear.

**Comment by joewhitsitt** [comment]
@ABoston88 since residence isn't on the current site, I think making it private at least for MVP makes sense.

**Comment by joewhitsitt** [comment]
I marked residence as private. changed athletics from blue skating to yellow soccer ball.

I wonder if more should be done to mark certain buildings as private (e.g. track storage, finkbine pump house 1 (older), volatile storage). I am rethinking the "all buildings" category and think that buildings should still be classified but be private to visitors. I have deleted the all buildings category and moved that finkbine restroom back to services as private.

**Comment by ABoston88** [comment]
How many were left in "All buildings"? 

If you know of any buildings that weren't listed before, we can make them private. Is there any way to surface what wasn't listed before? Probably something we can keep working at after launch, as well.

**Comment by joewhitsitt** [comment]
When i deleted the category, there was only that finkbine bathroom and i re-assigned it.

I was going to go building by building in concept3d and then check to see if the building is on the maps site

**Comment by ABoston88** [comment]
Sounds good. Let me know if I can help with that process, at all.

**Comment by joewhitsitt** [comment]
I can start up a huddle in a bit and will ping you.

**Comment by e-marie-w** [comment]
This is looking great and a lot easier to understand now!

For locations-within-a-building, such as all the dining places, should they display more info when the map pin is clicked, or are they fine as-is since they aren't actually buildings?

**Comment by joewhitsitt** [comment]
@e-marie-w yes, i think we should probably go through and add a link to those

update: if there is one

**Comment by joewhitsitt** [comment]
@mjoneill,

Alex, Marie and I went through most of the buildings and points to see if they should be hidden or supplemented with info. At your convenience, please review the map from a point/category perspective https://map.concept3d.com/?id=1890#

**Comment by joewhitsitt** [comment]
For MVP and since Alex is out:

match maps.uiowa.edu categories/order

All buildings
Point of interest
Housing
Dining
Recreational facilities
Libraries
Healthcare
Public parking
Construction project
360 Panoramas
Building labels

mark other categories as private and re-title to append (draft)
assign all buildings to "All buildings"
provide facilities link for each building

later lift:
check on facilities photos for additional buildings and see if we can get this feed working?

**Comment by joewhitsitt** [comment]
Capturing my process to provide facilities link for each building:

Pick an old category (all buildings is changing by the minute) and work your way down
copy the building name
pase in the search here https://www.facilities.uiowa.edu/buildings
copy the link and modify this markup in an open text file `<a href="https://www.facilities.uiowa.edu/building/0001" target="_blank">More building information</a>`
copy paste that markup in to the view source of description (there should be some `<br>` tags already for padding)

- [x] academic
- [x] athletics
- [x] events venue
- [x] research
- [x] residence
- [x] services
- [x] points of interest
- [x] housing
- [x] dining
- [x] recreation
- [x] libraries
- [x] healthcare
- [x] parking
- [x] construction

**Comment by e-marie-w** [comment]
Okay, all buildings should be in All Buildings now, I plan to do some double-checking. I didn't add any locations that weren't buildings, so here's a list of those grouped by category, in case we need them.

Libraries:
- Art Library 
- Law Library 
- Marvin A. Pomerantz Business Library 
- Lichtenberger Engineering Library
- Rita Benton Music Library

Healthcare:
- UI QuickCare
- IMU Nurse Care Clinic

Point of interest:
- University of Iowa Hospitals and Clinics
- Museum of Natural History
- Iowa House Hotel
- Office of Admissions
- Admissions Visitors Center

Recreational facilities:
- Fitness East Recreational Facility 

Dining: 
- Black's Gold Grill
- Burge Market Place
- Catlett Market Place
- Clinton Street Market
- EMRB Cafe
- Food for Thought Cafe
- Hillcrest Market Place
- Java House IMU
- Pat's Diner
- Power Cafe
- River Room Cafe
- Union Station

**Comment by e-marie-w** [comment]
Oh, also I identified some duplicate buildings, wanted to check if the second copy could be removed or needed to be changed to represent a different building. 

- Research - two of Shop North
- Residences - two of 1131 East Burlington Street
- Recreational facility - two of MRNA - Storage Shed B

**Comment by joewhitsitt** [comment]
I finished adding the facilities link to each building. I inspected the duplicates and confirmed they had the same reference id so I remove them. I also added the list of "extras" from https://github.com/uiowa/uiowa/issues/4541#issuecomment-999151526 to a separate private category in order to keep track of these.

All together, this satisfies the todos here: https://github.com/uiowa/uiowa/issues/4541#issuecomment-998925979

Waiting on the icon replacements here https://github.com/uiowa/uiowa/issues/4542

@mjoneill https://map.concept3d.com/?id=1890 is ready for review again

**Comment by mjoneill** [comment]
Looking pretty solid.  It appears that some buildings do not show addresses... Admissions Visitor Center (under point of interests), for example.  

When I see this, does it reflect a gap in the data import?

**Comment by mjoneill** [comment]
> Looking pretty solid. It appears that some buildings do not show addresses... Admissions Visitor Center (under point of interests), for example.
> 
> When I see this, does it reflect a gap in the data import?

This particular card is for a location that exists within a building. Reaching out to Scott to see what experience he'd like on the card for this one.  I suspect photo, address, etc...

**Comment by mjoneill** [comment]
Noticing something strange on cards for some buildings.  When I click on them, they provide an experience like this (see uploaded image).  

That experience persists on subsequent clicks for that card/location for <120 seconds or so.  After that time, revisiting the card for the location may reveal the actual and expected content experience.  

Anyone else noticing this type of behavior?  I'm on Safari...

<img width="465" alt="image" src="https://user-images.githubusercontent.com/7144234/147486976-99556ba8-40ca-4245-b438-cc96f9482863.png">

**Comment by joewhitsitt** [comment]
It takes a bit, but I get a loading gif and then (safari, brave)

<img width="551" alt="Screen Shot 2021-12-27 at 9 50 33 AM" src="https://user-images.githubusercontent.com/4663676/147487452-262cf766-27ee-424f-8786-98b5f4855e35.png">

**Comment by mjoneill** [comment]
> It takes a bit, but I get a loading gif and then (safari, brave)
> 
Thanks Joe.  When it happens to me, no image loading indicator until after that initial experience (seemed to be a couple minutes). 

If it continues to happen, I'll ask Patrick (our contact) about it...

**Comment by joewhitsitt** [comment]
As discussed, added Pat's Too and created the MNRA sub-category

<img width="737" alt="Screen Shot 2021-12-30 at 11 23 02 AM" src="https://user-images.githubusercontent.com/4663676/147774317-10ae9a24-d4b1-4274-b80b-cb46e5c759ef.png">

**Comment by joewhitsitt** [comment]
Updated IS with photo/content todo info

**Comment by e-marie-w** [comment]
I added photos to the buildings that I could, and on the doc highlighted locations still missing an image. Most are locations found inside an already listed building, like the dining places. A few, though, are buildings that just don't have an image on the facility site page.

Edit: should we just use the same image for now? Like, the Burge Hall image for the Burge Hall Marketplace? Then we'd only be missing 5 building images.

**Comment by richardbporter** [comment]
I was playing around with the data export feature yesterday in relation to #4591 and noticed some image references to maps.uiowa.edu. For example, the Slater Hall image is `https://cms.concept3d.com/map/lib/image-cache/i.php?mapId=1890&image=https://maps.uiowa.edu/sites/maps.uiowa.edu/files/s-100701-tj-15.jpg&w=260&h=200&r=1` which is kind-of odd. I don't know if that means its using an "external" image or something but if so, that won't work after DNS changes for maps.uiowa.edu.

**Comment by joewhitsitt** [comment]
That sounds like a question for Patrick and would be a huge bummer if they are essentially hotlinking...

**Comment by e-marie-w** [comment]
I don't know if this makes it better or worse, but it seems like only the bulk upload images include that maps.uiowa.edu? For images I grabbed from facilities and then uploaded, like Pearl Softball Field, the url looks like `https://cms.concept3d.com/map/lib/image-cache/i.php?mapId=1890&image=1890/1ec392fe2d35c99015f34ee793a58831.jpeg&w=260&h=200&r=1`.

**Comment by joewhitsitt** [comment]
Sent an email to Patrick

**Comment by joewhitsitt** [comment]
> I connected with our development team yesterday afternoon and they have come to the conclusion that indeed you are correct and those images will break. 

The workaround is to download them from the original import spreadsheet (ask me for a link) or from the concept3D cms and re-upload.

**Comment by joewhitsitt** [comment]
I found that the data export feature downloaded to my computer and open in Excel was a good way to filter/sort by the points affected.

**Comment by joewhitsitt** [comment]
We swarmed the heck out of the re-upload image stuff

**Comment by joewhitsitt** [comment]
This could use one more look through that buildings in categories besides all buildings have a photo. @e-marie-w was going to provide a list of buildings that didn't have a facilities photo in case the photo team needed to supply one. Additional content work is still being done by Alex?

**Comment by e-marie-w** [comment]
#### Buildings with no image on facilities: ####
Part of a published category:
- Soccer Complex Facility
- Pediatric Associates Building 2
- UI Community Home Care
- Iowa River Landing Parking
- ~~Stanley Museum of Art (construction)~~ _got rendering image from stanleymuseum website_

Only found in All Buildings/unpublished categories:
- University Hygienic Lab - Ankeny
- 109 East Market Street
- 1120 East Court Street
- Brown Motel 1 (Units 101-106)
- Brown Motel 2 (Units 107-115)
- Cabin 14
- Cabin 15
- Cabin 16
- Cabin 17
- Cottage 12 - 13
- Gerdin Athletic Learning Center
- Green Motel 3 (Units 210-217)
- James Street Laboratory 
- Jefferson Street Building
- LaMair Managers Residence
- Nagle Family Clubhouse
- Rierson House
- Stone Cottage 6
- Stone Cottage 7
- Tamisiea House
- UIHC 2nd Street Warehouse
- UIHC Centralized Emergency Power Generation Facility

#### Private buildings with no image on facilities: ####
- Dining Hall and Student Lounge
- Directors Residence
- Shop North
- Stone Cottage 10
- Stone Cottage 11
- Waitt Laboratory

#### Buildings marked private I haven't checked for facilities photos yet: ####
- 229 Melrose Court
- Butler Storage Court Street
- Finkbine Machine Shed
- Finkbine Pump House 1 (Older)
- Finkbine Restroom North
- Finkbine Restroom South
- Finkbine Storage Facility
- Laundry Building (Old)
- MERGE
- Oakdale 69kV Substation
- Oakdale Chilled Water Plant
- Oakdale Wel House
- Parklawn Warehouse
- UIHC Highland Court Storage
- Volatile Storage

**Comment by joewhitsitt** [comment]
going to do one more pass through

**Comment by joewhitsitt** [comment]
Added Stanley Museum of Art (construction) to Marie's list above for public, no photo

**Comment by ABoston88** [comment]
Found images for two of the public buildings (Soccer Complex, IRL parking). The other two are eluding me. We don't seem to have anything and there's nothing publicly available elsewhere.

Many of these private ones will also likely not have images (Okoboji locations, in particular). We can keep looking into those but given that they're private, I wouldn't hold on launch for it.
