### ISSUE TITLE
Work with brand team to create and upload category icons

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#4542]
## Issue

We are currently moving forward with icons from Concept3D's library, but would ultimately like to be "on brand" by adopting brand team approved icons.

## Proposed Solution

- [x] Coordinate with brand team to develop and update the category icons and their colors in Concept3D.
- [x] [See support doc](https://help.concept3d.com/hc/en-us/articles/360018974513-Icons)

![information_list_grey](https://user-images.githubusercontent.com/4663676/146461262-5cdb25f9-f247-40d0-bfd3-1fb640109ba0.png)
![information_marker_grey](https://user-images.githubusercontent.com/4663676/146461265-818b1073-1df3-4724-9478-0f85eb5bd9e9.png)

<img width="353" alt="Screen Shot 2021-12-21 at 10 29 38 AM" src="https://user-images.githubusercontent.com/4663676/146980572-a337feb1-b742-4c01-be22-98b77c3d0bad.png">
<img width="214" alt="Screen Shot 2021-12-21 at 12 30 45 PM" src="https://user-images.githubusercontent.com/4663676/146980621-bb978264-733c-4ee5-a656-ef47616f1155.png">
<img width="118" alt="Screen Shot 2021-12-21 at 12 31 54 PM" src="https://user-images.githubusercontent.com/4663676/146980725-24a1d315-7f7f-4070-9a39-cb79b7ceadd1.png">

**Comment by joewhitsitt** [comment]
Talked with Michael about this. Blocking until https://github.com/uiowa/uiowa/issues/4541 because categories might change. Michael plans to let the Brand team know that this work is still coming but not yet.

**Comment by joewhitsitt** [comment]
Updated the IS with a new picture of categories from work done in #4541. I think it is to a point where this can be unblocked.

**Comment by joewhitsitt** [comment]
All buildings
Point of interest
Housing
Dining
Recreational facilities
Libraries
Healthcare
Public parking
Construction project
360 Panoramas
Building labels

**Comment by joewhitsitt** [comment]
Jessica provide a set of icons today and I have uploaded them to the CMS. https://map.concept3d.com/?id=1890

In addition to the visible categories, a tigerhawk icon was provided for the current draft athletics category

**Comment by joewhitsitt** [comment]
UPDATED:

<img width="403" alt="Screen Shot 2021-12-30 at 10 09 58 AM" src="https://user-images.githubusercontent.com/4663676/147768737-a7ffe244-453e-446b-9f81-5607e699a908.png">

**Comment by briand44** [comment]
Need to get a new icon or approval on existing icon for academic buildings category

**Comment by joewhitsitt** [comment]
Emailed the brand team about the additional icon

**Comment by joewhitsitt** [comment]
Minutes later, a replacement icon has been provided and uploaded. Would you say this is done now @mjoneill
