### ISSUE TITLE
Featured image adjustments

### ISSUE THREAD

**Issue by makurj** [uiowa/uiowa#4543]
# Story

As a designer/webmaster, I would like to be able to do the following for the featured image:

1. Center text horizontally and vertically
2. Add secondary line of text
3. Ability to add CTA buttons

**Comment by pyrello** [comment]
This is how I thought we might accomplish this:
* Currently, we use a specialized layout for the featured image/title/breadcrumbs.
* We would add a custom Layout class
* This would allow us to add options to the layout form and storage that would control some of these settings.

**Comment by bspeare** [comment]
One of the issues with this is that the breadcrumbs visibility will be greatly reduced if this change is made.   If we move forward with this change we need to consider adding a transparency overlay to the entire image to ensure color contrast against the image or adjust the direction of the gradient based on the alignment selection. 

Left aligned option with our current gradient:

<img width="1909" alt="Screen Shot 2021-12-09 at 11 28 14 AM" src="https://user-images.githubusercontent.com/1036433/145447011-a5c89b48-4340-4ce8-a96c-54a267d553ad.png">

Centered option:

<img width="1921" alt="Screen Shot 2021-12-09 at 11 29 19 AM" src="https://user-images.githubusercontent.com/1036433/145447116-5d3fbbed-fc73-4688-8f51-01a444012e1b.png">

Centered with transparency overlay:

<img width="1924" alt="Screen Shot 2021-12-09 at 11 29 46 AM" src="https://user-images.githubusercontent.com/1036433/145447268-3b635e10-5497-45d7-8c01-9f55d1fffca1.png">

Left aligned with transparency overlay:

<img width="1910" alt="Screen Shot 2021-12-09 at 11 30 55 AM" src="https://user-images.githubusercontent.com/1036433/145447330-be9ab972-e806-4314-b82d-d23d579f7126.png">

Centered with gradient direction reversed:

<img width="1913" alt="Screen Shot 2021-12-09 at 11 32 51 AM" src="https://user-images.githubusercontent.com/1036433/145447416-5e2de7b6-9db5-4dd8-9a28-c5c46e64473b.png">

If we wanted to avoid this issue, we could:
- Remove breadcrumbs entirely from the featured image
- Place breadcrumbs elsewhere
- Remove breadcrumbs if additional text and button is added
- Add a region above the page title and allow users to place banners in that section

**Comment by bspeare** [comment]
It could be useful to just add a region above the page title and allow users to add banners to that region.  

<img width="1601" alt="Screen Shot 2021-12-09 at 9 03 29 AM" src="https://user-images.githubusercontent.com/1036433/145450804-013be8ab-bae2-4698-a8ff-15bafeff5d22.png">

**Comment by pyrello** [comment]
> It could be useful to just add a region above the page title and allow users to add banners to that region.

I like this last idea the best! Probably less work than what I was suggesting too.

**Comment by bspeare** [comment]
It sounds like Tippie would like to hide the page title and use an `<h1>` in the banner if we opened up the region above the page title.   So we would have the potential for multiple `<h1>` in the document outline.    

Should we go back to pursuing the Featured Image enhancements instead?

**Comment by joewhitsitt** [comment]
I feel like we are getting boxed in based on the list of requirements. Does it make sense to push back on any of these?

- Center text horizontally and vertically
- Add secondary line of text (hopefully max length)
- Ability to add CTA buttons
- Must be an h1 (why?)
- Breadcrumbs must display

At the same time we need to:
- Ensure contrast coverage
- Ensure a page title is provided
- Work with all featured image height options or be limited to large
- Ensure SEO and Teasers have featured image coverage if an image is designated.

Does any of this change if we break out breadcrumbs as a separate visibility option (currently grouped with hide title)?

**Comment by bspeare** [comment]
Now that we know that they plan on hiding the hiding the page title and breadcrumbs, it might make sense to not make any changes at this time.  They can add a banner to the top of their layouts and customize it as much as they would like and hide the page title and breadcrumbs in the page settings.

**Comment by bspeare** [comment]
After checking in with Tippie in the `#redesign-tippie` Slack channel, I think we can close this issue for now.  @makurj is that your impression as well?

**Comment by makurj** [comment]
I think so.

**Comment by bspeare** [comment]
Created a new issue for this https://github.com/uiowa/uiowa/issues/8697.
