### ISSUE TITLE
Upgrade to Drupal 9.3.x

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#4562]
# Motivation
Drupal 9.3.0 is out: https://www.drupal.org/project/drupal/releases/9.3.0

# Proposed solution

- [ ] Upgrade to Drupal 9.3.x
- [ ] Review the changes at the link above and figure out what is going to need to change and add it here
- [ ] Other stuff

**Comment by pyrello** [comment]
There is a known issue for 9.3.0 that may affect our platform: https://www.drupal.org/project/drupal/issues/3253568

Based on that, it might make sense to wait for 9.3.1 as it is likely to be released soon to fix that bug.

**Comment by richardbporter** [comment]
This seems like a duplicate of https://github.com/uiowa/uiowa/issues/4411.
