### ISSUE TITLE
Timeline indicator to scroll for content

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#4565]
As a visitor to a timeline on a webpage (https://175.uiowa.edu/milestones-university-iowa-history), I can see some sort of indication that I should scroll down so that I know there's content there.  Perhaps draw the first element by default?  something else?

**Comment by briand44** [comment]
Possibly remove line prior to first item and display first item by default.

**Comment by cory-skeers** [comment]
Made the first item opaque on load in #4599. Took a look at it in standup, and the consensus is that making the first item visible on load is likely enough.

Followup task may involve adjusting the gold line in relation to this--eg filling the line in up to the first item, or adjusting how far down the page it fills.
