### ISSUE TITLE
Review branding on Concept3D website

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#4566]
Take screenshots ahead of meeting for them to review before drive-through

- [ ] Look for contrast ratio issues
- [ ] Expected branding

**Comment by briand44** [comment]
schedule time with Jess and Sondra to get feedback on design.

**Comment by briand44** [comment]
If we have specifics, share screenshots, etc beforehand.

**Comment by GaryRidgway** [comment]
From my inspectionI think Joe [covered contrast issues here](https://github.com/uiowa/uiowa/issues/3957#issuecomment-964624811) and I don't think I am expecting a lot more from the branding standpoint. I think the branding looks sufficient right now. I think this is potentially ready for feedback from Jess and Sondra.

**Comment by bspeare** [comment]
@joewhitsitt can you provide details on the "expected branding" question?  Is this a general question or a series of specific questions about each interaction?

**Comment by joewhitsitt** [comment]
This originally was a note to get brand team feedback that got turned into an issue. I don't have specifics in mind, only that historically new things have been brought in front of the brand team for review. There are limitations within concept3D but are there noticeable/fixable issues where the solution is not brand-compliant? I mentioned to Alan that this work will closely relate to the icon work in https://github.com/uiowa/uiowa/issues/4542

**Comment by bspeare** [comment]
Thanks @joewhitsitt.   Do you have an example of a noticeable/fixable issue where the solution is not brand-compliant?

**Comment by bspeare** [comment]
Thanks for the clarification @joewhitsitt!

**Comment by joewhitsitt** [comment]
Blocked until tours tab is visible (waiting on Admissions walking tour and/or 175th), the [top-bar link](#4567 ) and [icons](#4542 ) are finalized. Once these are done, send another email to the brand team for final review.

**Comment by briand44** [comment]
This is no longer blocked as the tours tab has been made public.

**Comment by briand44** [comment]
Feedback from Jess:
>This looks good to me. The only thought I potentially had was to add some gold to the footer – Potentially putting “The University of Iowa” in gold.
 
>Additionally, the social media icons vary just slightly from those used in the homepage footer. I assume that is because they are built into the app, but wanted to note it in case there is opportunity for consistency.
 
>I’ll let Sondra weigh in on whether she sees anything additional worth noting with her brand eye.

**Comment by briand44** [comment]
Feedback from Sondra:

>The only thing that caught my eye was the logo appears to be rendering with wavy edges in Safari, screenshot attached with side-by-side comparison to Chrome.

<img width="685" alt="Screen Shot 2022-01-20 at 11 24 31 AM" src="https://user-images.githubusercontent.com/1017022/150390776-0c353030-48f9-47df-a023-5845fcdb6e97.png">

**Comment by joewhitsitt** [comment]
Changed the UofI text to brand yellow.

**Comment by joewhitsitt** [comment]
This is the site I used to create the icons for the footer. https://fa2png.app/ They are stored on sandbox.prod.drupal.uiowa.edu like all of our other non-drupal assets

**Comment by joewhitsitt** [comment]
I don't think we can fix the safari issue which seems to be cause by this image-rendering css:
<img width="983" alt="Screen Shot 2022-01-20 at 4 05 12 PM" src="https://user-images.githubusercontent.com/4663676/150429706-22649ef0-01c6-4da6-810a-5947b5671b72.png">

**Comment by joewhitsitt** [comment]
This is done:
<img width="354" alt="Screen Shot 2022-01-20 at 4 47 27 PM" src="https://user-images.githubusercontent.com/4663676/150434332-2f263bbe-525f-40c3-9fff-b1a20d595560.png">

uiowa.edu:
<img width="432" alt="Screen Shot 2022-01-20 at 4 47 59 PM" src="https://user-images.githubusercontent.com/4663676/150434418-b9ad3d67-171d-42c4-bd56-0f10dc6a9f95.png">

**Comment by joewhitsitt** [comment]
It was recommend to try a different image (perhaps using the recommended dimensions) to try and fix the Safari issue.

Update: recreated and uploaded the following png from an svg and it doesn't seem to fix the issue...
![iowa](https://user-images.githubusercontent.com/4663676/150591622-584d6772-603a-4599-bc1f-25477173c0ff.png)
