### ISSUE TITLE
Decide on top-bar links for Concept3D.

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#4567]

**Comment by briand44** [comment]
Michael to discuss with TM and Scott F. Possible request info link? Possible Accessibility related link?

**Comment by mjoneill** [comment]
Well, I added the Request Information topbar button. Anyone know how to style it? 

https://map.concept3d.com/?id=1890#!ct/51247

**Comment by mjoneill** [comment]
TM indicated a desire for an Accessibility button that would:
* Be near the beginning of the tab order
* lists custom key commands, tips for screen reader users, or where to find ALT content

He is restarting the conversation with Patrick.  Holding on this for now...in fact, this may be a story split.

**Comment by joewhitsitt** [comment]
Not sure if it is a primary or secondary button but if you had a button color combo in mind, we could add it. Looks like button black bg, white foreground is our default for yellow bgs.

<img width="347" alt="Screen Shot 2022-01-04 at 11 52 11 AM" src="https://user-images.githubusercontent.com/4663676/148102288-83b25d5c-e7bd-4e0f-9ed8-53eea16acd03.png">

**Comment by joewhitsitt** [comment]
>in fact, this may be a story split

I'd vote this. Originally I thought it would be another contact us type link (probably routed to our team) to aid users who are having issues with accessing the content in the primary form. I think if Concept3D had something like what was described above it would be great alternative.

**Comment by mjoneill** [comment]
> Not sure if it is a primary or secondary button but if you had a button color combo in mind, we could add it. Looks like button black bg, white foreground is our default for yellow bgs.
> 

Thanks @joewhitsitt .  I should have found this in the help...  

I'm going to go with hawkeye black for now and ask @bspeare to evaluate, etc...

**Comment by bspeare** [comment]
The black is a little strong, a white background might better if possible.  

<img width="1604" alt="Screen Shot 2022-01-05 at 9 18 15 AM" src="https://user-images.githubusercontent.com/1036433/148242050-2a6e4097-7dc6-45a2-b227-fb0fe021acc6.png">

**Comment by mjoneill** [comment]
> white button

I'll make the switch

**Comment by joewhitsitt** [comment]
Moved to done but wasn't closed.
