### ISSUE TITLE
Grad Admissions Areas of Study taxonomy

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#4568]
Areas of Study taxonomy (holds `see also` info and allows multiple pieces of content to show up as one row on the view display)

**Comment by briand44** [comment]
blocked until #4475

**Comment by dnkemper** [comment]
Never got to this. Didn't feel right to assign myself to it if someone had time to complete it before I get back

**Comment by joewhitsitt** [comment]
So, from looking at #4523, most of this is in progress and/or already done. We could leverage the taxonomy default "description" field for the see also. Moving to parking lot to discuss where this should actually be on the board.

**Comment by joewhitsitt** [comment]
Based on my discovery here: https://github.com/uiowa/uiowa/issues/3842#issuecomment-1002291548 the taxonomy might need some additional fields.

**Comment by joewhitsitt** [comment]
Take back what I said earlier, no additional taxonomy fields necessary.

**Comment by joewhitsitt** [comment]
This isn't blocked because it was already part of the PR
