### ISSUE TITLE
Start redirecting building pages to facilities website equivalent

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#4574]
Need to reach out to Facilities and see if they give us the green light to start redirecting.

## Proposed Solution

- [x] Redirect building content type nodes to facilities equivalent using the building number that is pulled into the node either through preprocess drupal_goto or via rabbit hole using tokens? (e.g https://www.facilities.uiowa.edu/building/0001)

**Edits to FM Building Information pages**:
- [x] Create draft page and copy hearing-loop-system information to it.  https://maps.uiowa.edu/extras/hearing-loop-system
- [x] Remove energy button (this tool will be rebuilt and added back in at a later time)
- [x] Remove link to “Utility Bill” and “Bids”
- [x] Add a link to “Lactation Room Locations” that links to this page  https://hr.uiowa.edu/well-being/family-services/lactation-facilities-and-resources/lactation-room-locations
- [x] Add a link to “Hearing Loop Systems Locations on Campus” see above
- [x] Add a link to “Gender Inclusive Restrooms” https://trans-resources.org.uiowa.edu/gender-inclusive-restroom-map-campus with a note in parenthesis (updated resource coming soon).

## Notes:
For the location of the lactation room, hearing loop, and gender inclusive website links, I suggest putting them underneath the contact information on the right-hand side under a new section called “Resources”

**Comment by briand44** [comment]
Preprocess node and redirect to canonical.

**Comment by joewhitsitt** [comment]
https://api.drupal.org/api/drupal/includes%21common.inc/function/drupal_goto/7.x

**Comment by briand44** [comment]
I emailed Facilities to get the green light. Added blocked label until we hear back.

**Comment by briand44** [comment]
**Edits to FM Building Information pages**:

- [x] Remove energy button (this tool will be rebuilt and added back in at a later time)
- [x] Remove link to “Utility Bill” and “Bids”
- [x] Add a link to “Lactation Room Locations” that links to this page  https://hr.uiowa.edu/well-being/family-services/lactation-facilities-and-resources/lactation-room-locations
- [x] Add a link to “Hearing Loop Systems Locations on Campus”  https://maps.uiowa.edu/extras/hearing-loop-system
- [x] Add a link to “Gender Inclusive Restrooms” https://trans-resources.org.uiowa.edu/gender-inclusive-restroom-map-campus with a note in parenthesis (updated resource coming soon).
- [x] For the location of the lactation room, hearing loop, and gender inclusive website links, I suggest putting them underneath the contact information on the right-hand side under a new section called “Resources”

**Comment by e-marie-w** [comment]
The edits can all be done on the live site, correct? No DevDesktop needed? If I'm understanding it right I'd be interested in working on this.

Edit: Nevermind. Remembered I could log in to see how the pages are set up and no they aren't editable.

**Comment by richardbporter** [comment]
The FM building pages are entirely dynamic and changes will need to be in code, probably using DD first.

**Comment by richardbporter** [comment]
Random thought: does Rabbit Hole have access to node field tokens? If so, that might work instead of coding the redirect on the maps site. Don't know if that is any better/easier/etc.

**Comment by joewhitsitt** [comment]
Updated IS

**Comment by richardbporter** [comment]
https://www.facilities.uiowa.edu/hearing-loop-system

**Comment by richardbporter** [comment]
>For the location of the lactation room, hearing loop, and gender inclusive website links, I suggest putting them underneath the contact information on the right-hand side under a new section called “Resources”

Any room to negotiate on this? We put them in the button group where the other links were:
![image](https://user-images.githubusercontent.com/1068523/146966695-01cb2486-8601-4e78-a7c6-a0062bbaf44d.png)

**Comment by richardbporter** [comment]
We looked into RH but it won't handle padding the building numbers to 4 digits. Going the drupal_goto route.

**Comment by briand44** [comment]
>Any room to negotiate on this? We put them in the button group where the other links were:

I emailed Wendy to ask if she would be ok with this. I attached the screenshot. Waiting to hear back.

**Comment by richardbporter** [comment]
Pushed both branches to AC (uiowa702, uiowa703) while we wait. Not checked out in dev yet but could be for review.

**Comment by richardbporter** [comment]
This is done now.
