### ISSUE TITLE
Update in-code references to maps.uiowa.edu and develop/release communication regarding link updates.

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#4591]
Includes sitenow_maps pane (SiteNow v1)

Related issue https://github.com/uiowa/uiowa/issues/4212

Static Maps or Embed iFrame?

See what happens if the endpoint goes dark? Graceful fallback. Link to main map?
 
Allow staticmap.concept3d.com/map/static-map iframe embeds for Static Map replacements? https://help.concept3d.com/hc/en-us/articles/360008043454-Static-Maps

**Comment by joewhitsitt** [comment]
In terms of a fallback link we could get the building abbreviation from the pane and construct a search link like this: https://map.concept3d.com/?id=1890#!s/OC?ct/51247 (Old Captiol) (obviously replacing with maps.uiowa.edu for the final URL)

**Comment by richardbporter** [comment]
Example static map URL for Art Building West: https://staticmap.concept3d.com/map/static-map/?map=1890&loc=579415&scale=2&zoom=17

**Comment by richardbporter** [comment]
Sounds like there is an API but it isn't free so I'm assuming we don't have access: https://help.concept3d.com/hc/en-us/articles/360016590393-Interactive-Map-API-FAQs

We might be able to construct a static list of abbr/number -> markerID using the CMS data export feature. I tried to do that for Art Building West though, and the marker IDs don't seem to match. The marker ID in the static map above is 579415 but the data export has a marker instance ID of 579415590640.

They do match for Engineering Building though: https://staticmap.concept3d.com/map/static-map/?map=1890&loc=545695&scale=2&zoom=17

**Comment by joewhitsitt** [comment]
Got the go-ahead from IowaReadingResearch to change their footer link to the facilities version.

Update: IRRC link has been updated. Pushed with the security release

**Comment by richardbporter** [comment]
Starting to probe this a little.

**Comment by richardbporter** [comment]
>uiowa_maui/uiowa_maui_pane/course_deadlines
update uiowa_maui/uiowa_maui_pane/plugins/content_types/course_deadlines.inc#L362 to not link building abbreviation - link to facilities if we have that building number.

We don't have the number. The data is coming from MAUI and the section API call data has the building abbreviation, not the building number. I started a branch on uiowa703 called update-maps-refs that changes this to a search link as @joewhitsitt documented above. We can stage other changes in that branch.

**Comment by richardbporter** [comment]
>registrar.uiowa.edu - (example: https://registrar.uiowa.edu/contact) Taxonomy vocabulary has link field that takes a map link

This is content that they have access to change. I updated the help text to more generic instead of referencing "a building on maps.uiowa.edu."

**Comment by richardbporter** [comment]
sitenow_maps pin seems unaffected by this change. The building pane builds its options list from https://maps.uiowa.edu/api/v1/buildings.xml and kinda breaks. I thought we could maybe copy/paste that to data.its but the lat/lon points for individual buildings are not included in that - those are retrieved from https://maps.uiowa.edu/api/v1/sh/detail.xml and similar.

**Comment by richardbporter** [comment]
I was able to get sitenow_maps individual_building pane working by using an existing data.its endpoint. I've pushed up this change to the feature branch on uiowa703.

**Comment by richardbporter** [comment]
I searched the other docroots again and didn't find any other code references. I did search feeds config for maps references and found its and vending have two feed endpoints pointing at maps.uiowa.edu. Not sure if they're in use still but if so, they'd need updating.

**Comment by briand44** [comment]
>Just looked at its.uiowa.edu. They are no longer pulling building data. HD Staff are manually maintaining now. They wanted to tailor building names for Alerts instead of using what was provided by BuildingCommonName.

Comment from Joe on related issue. Not sure if this was in regards to the map feed

**Comment by richardbporter** [comment]
> > Just looked at its.uiowa.edu. They are no longer pulling building data. HD Staff are manually maintaining now. They wanted to tailor building names for Alerts instead of using what was provided by BuildingCommonName.
> 
> Comment from Joe on related issue. Not sure if this was in regards to the map feed

Thanks. Vending seems to be in use still. I can look into it.

**Comment by richardbporter** [comment]
I think I have the vending feed working with the data its endpoint. Included in the 703 feature branch.

**Comment by richardbporter** [comment]
I think I've replaced everything I can find. The change to uiowa_maui requires DNS be updated for maps.uiowa.edu to point at Concept3D. Also, the feed endpoint for vending needs to be updated when the code is deployed. Marking as blocked.

I think @joewhitsitt thought about removing MapBox entirely as part of this. We could probably remove it from some sites but not facilities, however. Facilities building pages are built dynamically and there is no place to embed a map. Further, there is no way to build dynamic embeds with Concept3D without access to the API.

**Comment by richardbporter** [comment]
I've copied the sitenow_maps and uiowa_maui changes to uiowa701/2 on a feature branch of the same name.

**Comment by richardbporter** [comment]
Pulling this back into progress after @briand44 found something we may have missed.

**Comment by richardbporter** [comment]
It looks like content.uiowa.edu has a taxonomy called Places with a link field that is populated with lots of maps.uiowa.edu URLs for building pages. These Places are output in the API when referenced from an event which in turn gets displayed on lots of different websites. We will need to update these links to point to facilities.uiowa.edu instead. A quick count of Places looks to be around 250. An update hook should be possible but once again, we don't have the corresponding building number in this context. However, it should be possible to either query the existing data.its endpoint and match them up or build a static map of abbr -> number values.

**Comment by richardbporter** [comment]
Moved content hub work to separate issue: #4704 

Updated uiowa_maui module to use new number lookup data its endpoint and link to facilities site instead of concept3d search link.

Deployed all changes to prod. Reverted features where necessary. Updated vending feed URL.
