### ISSUE TITLE
Restore icfm2020.org in dev environment

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#4593]
# Story

As an owner of icfm2020.org, I would like this site to be made available somewhere so that I can get snapshots of pages to provide in a report to funding agency.

# Additional Information
DNS is not pointing to Acquia so it probably makes sense to restore this in a dev or stage environment.

DB, Files and code backups live https://iowa.sharepoint.com/sites/CSI-Drupal2/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FCSI%2DDrupal2%2FShared%20Documents%2FGeneral%2Fsite%2Dbackups%2Ficfm2020%2Eorg&viewid=bf54b9d9%2D0975%2D4fbc%2D9f1b%2D6377bdc2307c.

# Proposed solution

**Comment by briand44** [comment]
I let the customer know we will only be able to keep this around for about a month so they said they would work on it right away once we make the site available again. I can communicate with the customer once this is ready.

**Comment by richardbporter** [comment]
This is done: https://org-icfm2020.dev.drupal.uiowa.edu/
