### ISSUE TITLE
Update payment info for paid accounts

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#4601]
- [x] Mapbox
- [x] BrowserStack
- [x] JetBrains
- [x] Slack UI Web Community
- [x] Slack OSC - renews Jan 1
- [x] Travis (trans. declined)
- [x] Moz
- [x] Semrush

Others??

**Comment by joewhitsitt** [comment]
Ben is listed as owner of BrowserStack, I can see the plan but not update billing

**Comment by mjoneill** [comment]
I don't have permissions to tic the boxes, but OSC Slack, Semrush, and Moz are all Done!

TY!

**Comment by bspeare** [comment]
Browserstack is now updated.

**Comment by briand44** [comment]
Closing as all items we are aware of are completed.
