### ISSUE TITLE
Disable URL Aliases for media

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#4613]
## Story

As an editor, I won't be tempted to change a media entity alias and cause trouble by not being able to access the media entity edit screen.

## Problem

Changing the media url alias prevents webmaster/etc from accessing the media edit form.

I can't think of a use-case where the media alias should be changed.

## Proposed Solution

- [x] Prevent webmasters and below from modifying the alias. Allow admins to access it so they can fix media paths that have been modified.

**Comment by joewhitsitt** [comment]
This has come up a few times and could be causing issues for editors. I think we should stomp this out soon to reduce headaches later.

If folks want a friendlier path, they should use the redirect functionality (e.g. /admin/config/search/redirect) instead.

**Comment by joewhitsitt** [comment]
Labelling this as a bug since it can prevent editors from accessing the media edit form and require a developer to step in and fix.

**Comment by briand44** [comment]
Grooming conversation... Entity specific permissions, more broad permission, access check on form were some different options discussed. Joe suggested moving forward with just an access check on the specific form and keeping this scoped to media.

**Comment by briand44** [comment]
can possibly use existing is_admin check to allow access

**Comment by joewhitsitt** [comment]
```
/** @var Drupal\uiowa_core\Access\UiowaCoreAccess $check */
      $check = \Drupal::service('uiowa_core.access_checker');

      /** @var Drupal\Core\Access\AccessResultInterface $access */
      $access = $check->access(\Drupal::currentUser()->getAccount());

      if ($access->isForbidden()) {
        // Disable or access false to fieldset/field related to URL alias
      }

```

**Comment by cory-skeers** [comment]
This popped up again, where an editor tried to manually update the alias to keep old links working (filepath updated from .../2023-01/... to .../2024-01/... and they unchecked the auto alias to change it to the 2023 path). Led to quite a bit of confusion with access denied messages.
