### ISSUE TITLE
Provide a list of building link info to web community

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#4616]
Epic - https://github.com/uiowa/uiowa/issues/3957

## Issue

Though we are currently redirecting building pages to facilities, those redirects will no longer exist when we switch over to Concept3D. It would be nice to provide content editors the information they need to replace old links with the facilities equivalent.

## Proposed Solution

- [x] Views data export of building content from maps.uiowa.edu containing building name, building abbreviation, current url, facilities url (constructed off available building number)
- [x] Pass out to web community, campus communicators, sitenow community, app dev list

**Comment by briand44** [comment]
share via demo, web community list serv, web community meeting

**Comment by dnkemper** [comment]
Have everything setup, but unsure of last field to export. 

I’m looking at Old Capitol, and its 0001 on facilities.uiowa.edu and the building number is 1 on maps.uiowa.edu… is there a way to add the 0 prefix to make the building number 4 numbers for URL? Or is that something to do in excel?
If want to look at export: (still need to hide building number - but made it easier to compare buildings on maps vs facilities) https://maps.uiowa.edu/reports/building-info.xml

**Comment by dnkemper** [comment]
Could do a fixed number length on excel? Works fine..just not sure if this path is acceptable

**Comment by joewhitsitt** [comment]
So based on this discovery, it might make sense to just export the building number as-is then in excel apply a custom format or `RIGHT("0000" & cell, string_length)` to provide the leading zeros, then construct the URL in excel using concat or A1&&B1 type stuff.

Rick was handling this for the canonical link by using `str_pad()` in PHP. uiowa703-dev/docroot/sites/maps.uiowa.edu/modules/custom/campus_maps_core/campus_maps_core.module

**Comment by dnkemper** [comment]
Alright! Thank you, Joe! I just used excel to do it. Here's the link to review: https://iowa.sharepoint.com/:x:/s/CSI-Drupal2/EbwgBFsnDzpLtrQNahJ4pTABotaRlcx1YfobJBL2PLYpoA?e=q4mExr

**Comment by mjoneill** [comment]
[client_error_(4xx)_inlinks_maps_to_facilities.xlsx](https://github.com/uiowa/uiowa/files/7824862/client_error_.4xx._inlinks_maps_to_facilities.xlsx)

@dnkemper and @briand44 these are the facilities links that generated a 404. Does this help?

**Comment by dnkemper** [comment]
Alright, created a new doc that highlights the broken facility links. Let me know if it looks wonky or not, please! If good, I'll delete the old doc. S/O to @cory-skeers for leading me into the right direction 🥳 https://iowa.sharepoint.com/:x:/s/CSI-Drupal2/EQGyVsYaCBdMkMxlY8q7wewB6OKmOFN03Jbq73NnUgnmgg?e=7c6Wbf

**Comment by e-marie-w** [comment]
I think it looks fine! And I figured out the Voxman Music Building thing - it's actually listed twice. Once with the correct VOX abbreviation/redirect, and later with the incorrect broken VMB one.

**Comment by briand44** [comment]
I went through maybe a dozen of these and didn't notice anything that stood out or any issues with the export. I will share with Facilities folks. Thanks!

**Comment by briand44** [comment]
Email sent to Facilities.

**Comment by dnkemper** [comment]
@e-marie-w you are awesome and thank you, @briand44! SO glad you caught those! Thank you both!

**Comment by briand44** [comment]
I honestly think we just remove the records from the spreadsheet that are 404's and continue forward. I think the maps site has building nodes that aren't being removed ever so it is showing outdated info. I don't think it makes sense to put effort in to clean that up. It will be resolved when we launch Concept3D.

Might make sense to hear from Michael and the rest of the team in standup before just taking my advice though.

**Comment by mjoneill** [comment]
> Might make sense to hear from Michael and the rest of the team in standup

Lest I forget by Monday...  I think if Facilities doesn't see a problem and indicates these are old buildings that have churned out of our ecosystem, etc...  then I'm fine with just removing them from what we share with campus.


As far as comms plan, I was thinking that we should share the final list of URLs with the following communities (on the following channels): 
* Mail to web community listserv (anyone)
* Mail to sitenow community (anyone)
* Mail/share in web community meeting (@ABoston88)
* Mail to campus communicators (@mjoneill)

^^^ May have missed something!


Anything

**Comment by dnkemper** [comment]
Updated doc is here: https://iowa.sharepoint.com/:x:/s/CSI-Drupal2/EZDzSSVbf1FItyElXbgqpqEBDBsk5-YfUNPyQ_3BbTUhbA?e=6gnJb9

Removed the broken links and put them in a new tab

**Comment by richardbporter** [comment]
Maybe we should refer to those broken links using another word? Deprecated, retired or something? Just thinking we don't want to give the expectation that they can be fixed.

**Comment by joewhitsitt** [comment]
It was suggested that a draft email be put together for the upcoming announcement

**Comment by mjoneill** [comment]
> Maybe we should refer to those broken links using another word? Deprecated, retired or something? Just thinking we don't want to give the expectation that they can be fixed.

I like "retired"... may even be a better term someone is sitting on.  But essentially the messaging is something like, "these pages and corresponding URLs are retiring when we go live with the new maps site. Be proactive now and fix in advance if you know you link to some of these buildings... After going live, these will appear as broken links in your Siteimprove reporting..."  <--- idea, not mandate

**Comment by richardbporter** [comment]
First draft, please edit.

https://iowa.sharepoint.com/:w:/r/sites/CSI-Drupal2/Shared%20Documents/General/Building%20Links%20Communication.docx?d=w3305331f17c34835b3f35b68ef5ad381&csf=1&web=1&e=cwwFqo

**Comment by joewhitsitt** [comment]
Thanks for the first pass. Made a couple edits.

**Comment by dnkemper** [comment]
Updated doc with new terminology

https://iowa.sharepoint.com/:x:/s/CSI-Drupal2/EXZXa8Aao55LlCI3aafQccIB2Y33AX_woCwZTZ5m-S3T1A?e=h3Psr2

Annoying, but can't update in UI. Have to download and upload a new spreadsheet bc of query functionality used to manipulate things.

**Comment by mjoneill** [comment]
> First draft, please edit.
> 
> https://iowa.sharepoint.com/:w:/r/sites/CSI-Drupal2/Shared%20Documents/General/Building%20Links%20Communication.docx?d=w3305331f17c34835b3f35b68ef5ad381&csf=1&web=1&e=cwwFqo

Seems like a solid start. I'd like @ABoston88 to take a gander at it as well.  Also (all), what do you think about Jan 31 as proposed launch date?

**Comment by mjoneill** [comment]
Audiences: 

- Web community in meeting 
- Sitenow user’s lists 
- Campus Communicators (listserv) 
- Web community (listserv) 
- Sprint Demo visitors (listserv) 
- App dev group?  Do we need to discover/reach out to Maui folks or Hawktools folks to prep them for this?  Email to app dev group before the change?

**Comment by ABoston88** [comment]
Made some minor tweaks to wording, added a link to text search. I'm cool with the launch date.

**Comment by joewhitsitt** [comment]
i will send the sitenow announcements version today

**Comment by joewhitsitt** [comment]
Scheduled to send at 10:30 with contents of the earlier ui-web email: https://apps.its.uiowa.edu/dispatch/communications/1027865585

**Comment by briand44** [comment]
Sent to app dev list with minor modifications.

**Comment by mjoneill** [comment]
Sent to Campus Communicators listserv with slight modifications + inclusion of an animated gif that shows where to identify links to maps site in siteimprove.

**Comment by mjoneill** [comment]
![finding-maps-links-in-siteimprove](https://user-images.githubusercontent.com/7144234/150835435-8ada3bf3-aff1-4aef-bc8c-5d5092d0044a.gif)
