### ISSUE TITLE
Special characters are escaped in the News subscribe link

### ISSUE THREAD

**Issue by mjoneill** [uiowa/uiowa#4625]
I noticed today that special characters appear to be escaped in the News subscribe link.

Observed on the 175 site.  Hid the subscribe link for now. Not urgent that it is there.  

<img width="840" alt="image" src="https://user-images.githubusercontent.com/7144234/148280158-eb9c6516-3b2f-4203-a487-06e828568770.png">

**Comment by joewhitsitt** [comment]
Hmm. Not setup exactly as I assumed when mentioned in the slack. This is where the change would start. Make sure it gets passed in correctly: https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/sitenow_articles/src/Form/SettingsForm.php#L285

**Comment by joewhitsitt** [comment]
Created an example here: https://sandbox.prod.drupal.uiowa.edu/news

**Comment by bspeare** [comment]
I think we can close this due to the work that happened in https://github.com/uiowa/uiowa/pull/4714.   @joewhitsitt please reopen if I'm wrong about this.
