### ISSUE TITLE
Restrict access to Areas of study and Degree Types term pages

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#4628]
# Story

As a Grad Admissions site owner, I would like to hide the areas of study and degree type taxonomy term pages since they add no additional value and aren't being linked anywhere.

# Additional Information
We will want to make sure robots.txt is disallowing these paths and that they are not included in sitemaps as well as making these not accessible to anonymous users.

# Proposed solution

- [x] Enable rabbit hole and rabbit hole taxonomy for grad admissions, include it in the split
- [x] Configure and export for AoS and Degree types taxonomy access denied
- [x] Update permissions to allow authenticated to bypass for the taxonomy rabbit hole, export
- [x] Make sure taxonomy is not included as part of the sitemap

# Later on

- [ ] Create a term for Michael to review in PROD?
- [ ] See if additional robots.txt disallow is needed for these paths.

**Comment by joewhitsitt** [comment]
For reference, HR is using rh_taxonomy for their Unit taxonomy. Maybe we can inspect to see if out of the box any additional seo work is necessary? https://hr.uiowa.edu/units/administrative-services I don't see these in https://hr.uiowa.edu/sitemap.xml
