### ISSUE TITLE
Button color declared in sitenow.css is conflicting with button styles when used with background colors

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#4631]
# Problem
As noted by @bewoldt, the button color declared in sitenow.css is conflicting with button styles when used with background colors

# Steps to reproduce
Go to https://studenthealth.prod.drupal.uiowa.edu/news

<img width="1500" alt="Screen Shot 2022-01-06 at 8 54 13 AM" src="https://user-images.githubusercontent.com/1036433/148402299-6f3dcfbd-7cb9-4941-945e-9bbfde8aad21.png">

# Proposed solution
Remove the `!important` from the button color definition in `sitenow.scss` and test bttn styles for `v2` sites.

**Comment by richardbporter** [comment]
Here is the blame for that: https://github.com/uiowa/uiowa/blame/main/docroot/themes/custom/uids_base/scss/sitenow.scss#L473 The commit/PR might provide insight into the "why", maybe not. :)

**Comment by bspeare** [comment]
Looks like this was the commit https://github.com/uiowa/uiowa/pull/3379/commits/3b81c38ae0d37cf33bec00c6c5c7a01f4bfb7933.
