### ISSUE TITLE
Main menu disappears on uiowa.edu intermittently

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#4632]
# Problem
There have been multiple reports of the main menu disappearing on uiowa.edu.

<img width="1780" alt="Screen Shot 2021-12-01 at 9 10 17 AM" src="https://user-images.githubusercontent.com/1036433/148449930-e0bbf0bc-e1b4-408c-a643-9937a4c5f8a4.png">

# Steps to reproduce
TBD

# Proposed solution
TBD

**Comment by richardbporter** [comment]
We should check all logs next time this happens for any useful information before clearing the cache.

We may want to ask support to analyze our memcache config. We had previously asked them to do this for D7 when authenticated sessions were getting evicted frequently. I wonder if that could be happening here and/or with #3585.

**Comment by joewhitsitt** [comment]
Has this happened recently?

**Comment by richardbporter** [comment]
Not that I know of.

**Comment by joewhitsitt** [comment]
https://www.drupal.org/project/drupal/issues/2984232

This was brought up in Higher-Ed Drupal as possibly being related to our previous issues with missing [plugins](#4500 )/[layouts](https://github.com/uiowa/uiowa/issues/3585). This is the only one still open so I am posting it here.

**Comment by richardbporter** [comment]
Maybe we should close this?

**Comment by pyrello** [comment]
Re-open if it comes up again.

**Comment by joewhitsitt** [comment]
Closing based on comments above

**Comment by joewhitsitt** [comment]
While streaming logs when this happened on 10/07/2022 ~10:11ish, nothing stood out.

Clearing cache (not varnish) was enough for anonymous visitors to see it again. Authenticated users could see it.

**Comment by briand44** [comment]
Let's hold off on trying to dive into this since we are currently changing the menu for uiowa.edu

**Comment by briand44** [comment]
blocked until this happens again after we switch menu implementations.

**Comment by bspeare** [comment]
Now that we've switched the menu on uiowa.edu, what's the next step on this?  Close and reopen if we get a report of the menu missing?

**Comment by joewhitsitt** [comment]
I'd be okay with that. Did we do an audit earlier to see what other sites are using the off-canvas?

**Comment by bspeare** [comment]
Maybe the audit was the next step? I don't recall that we put work into finding a list of all the sites using off-canvas.

**Comment by briand44** [comment]
Let's close this and reopen if it happens again on uiowa.edu. If we get reports of off-canvas menu missing on other sites we can adjust this issue.
