### ISSUE TITLE
Migrate Grad Admissions AOS and related content

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#4638]
see also moves from content type to taxonomy. links within need to redirect

We'll want to remove any testing content prior to running migration(s).

- [x] Manually migrate Estimated Costs
  - [x] Set up redirects from the old cost estimate paths to the new
- [x] Programmatically migrate colleges taxonomy
- [x] Programmatically migrate Degree types taxonomy
- [x] Programmatically migrate Areas of Study taxonomy
- [x] Programmatically migrate Areas of Study content (sans "See also" and "Sub title" field)
- [x] Dry run with broken links report sent to customer for corrections map
- [x] Broken links map migration
- [x] Run in DEV for technical and customer review

## Broken Links Report
[gradadmissions-broken-links.txt](https://github.com/uiowa/uiowa/files/7945458/gradadmissions-broken-links.txt)

## Estimated Costs Map
<details>
<summary>

_php_
...

</summary>
<description>

```php
  $map = [
    // source_nid => target_nid,
    // MAc. mac-program-estimated-costs.
    121 => 211,
    // MD. md-program-estimated-costs.
    112 => 246,
    // JD. jd-program-estimated-costs.
    415 => 256,
    // SJD. sjd-program-estimated-costs.
    111 => 266,
    // LLM. llm-program-estimated-costs.
    421 => 276,
    // MSL. master-studies-law-msl-program-estimated-costs.
    583 => 286,
    // PharmD. pharmd-program-estimated-costs.
    116 => 296,
    // DNP. doctor-nursing-practice-dnp-program-estimated-costs.
    113 => 306,
    // DPT. dpt-program-estimated-costs.
    131 => 316,
    // MPH. master-public-health-program-estimated-costs.
    118 => 326,
    // Public health (not MPH). graduate-programs-public-health-estimated-costs.
    103 => 336,
    // Sustainable Water Development. sustainable-water-development-certificate-estimated-costs.
    931 => 346,
    // Oral Science Program. oral-science-program-estimated-costs.
    115 => 356,
    // Applied Math & Computational Sciences. applied-math-computational-sciences-estimated-costs.
    105 => 366,
    // LIS. library-information-science-estimated-costs.
    109 => 376,
    // Second Language Acquisition. second-language-acquisition-estimated-costs.
    119 => 386,
    // Grad Programs in Pharmacy. graduate-programs-pharmacy-estimated-costs.
    117 => 396,
    // Informatics. informatics-estimated-costs.
    412 => 406,
    // Dental Public Health. dental-public-health-estimated-costs.
    106 => 416,
    // Urban & Regional Planning. urban-regional-planning-estimated-costs.
    120 => 426,
    // Endodontics. certificate-program-endodontics-estimated-costs.
    132 => 436,
    // DDS. doctor-dental-surgery-dds-program-estimated-costs.
    107 => 446,
    // Speech Pathology & Audiology. speech-pathology-and-audiology-ma-or-aud-estimated-costs.
    417 => 456,
    // Health Administration. health-administration-program-estimated-costs.
    108 => 466,
    // Business (PhD). phd-programs-business-estimated-costs.
    96 => 476,
    // Education. education-estimated-costs.
    101 => 486,
    // Liberal Arts & Sciences. graduate-programs-liberal-arts-sciences-costs.
    99 => 496,
    // Engineering. engineering-estimated-costs.
    102 => 506,
    // Nursing (PhD). phd-program-nursing-estimated-costs.
    133 => 516,
    // Nursing (MSN). msn-cnl-program-estimated-costs.
    114 => 526,
    // Medicine (non-MD). ms-phd-mme-mca-and-mpa-programs-medicine-estimated-costs.
    100 => 536,
    // Business (MBA). full-time-mba-program-estimated-costs.
    110 => 546,
  ];
```

</description>
</details>

**Comment by joewhitsitt** [comment]
Report of broken links to give to Grad Admissions to provide corrections for

**Comment by joewhitsitt** [comment]
See also field is moving to AoS Taxonomy term so with a many-to-one situation, I don't think it should be automatically migrated and that they should add those manually once the AoS terms are added.

**Comment by joewhitsitt** [comment]
Initial notes:

- I assume the AoS content migration is partially blocked until there are estimated costs content to map and wire up.
- Colleges taxonomy on the grad.admissions d7 had a programs long text field. I assume that needs to migrate over as well. Could it just be appended to the description? If so, do we have a taxonomy source plugin to reference here?

**Comment by cory-skeers** [comment]
> Colleges taxonomy on the grad.admissions d7 had a programs long text field. I assume that needs to migrate over as well. Could it just be appended to the description? If so, do we have a taxonomy source plugin to reference here?

We don't have a specific taxonomy source plugin--most taxonomies we've done have had some extra caveat, like they were being renamed as well, or some taxonomy terms had been migrated manually but not others.

If it's a straight, pulling all taxonomy terms over and appending that extra field to the description, I think it could all be done with a YML migration definition file.

**Comment by joewhitsitt** [comment]
I think I want to pick your brain @cory-skeers if you have some capacity today. I see `concat` as an option but I don't know how to pair that with the callback I am already doing to fix the rich text.

**Comment by cory-skeers** [comment]
> I think I want to pick your brain @cory-skeers if you have some capacity today. I see `concat` as an option but I don't know how to pair that with the callback I am already doing to fix the rich text.

Absolutely! @pyrello could probably help out too. He was the main proponent to getting the URL Aliases into a YML-only migration. Maybe we can huddle on it later.

**Comment by joewhitsitt** [comment]
bugger. also tried `plugin: merge` from migrate plus. probably doing it wrong. switching to testing other PRs for the moment

**Comment by joewhitsitt** [comment]
Update: figured out how to append the long text programs field to the term description just using yaml:

```yaml
  temp_description:
    -
      plugin: callback
      callable: strip_tags
      source: description
    -
      plugin: callback
      callable: htmlspecialchars_decode
    -
      plugin: str_replace
      search: '&#39;'
      replace: ''''
    -
      plugin: str_replace
      search: '&rsquo;'
      replace: ''''
  description:
    plugin: concat
    source:
      - '@temp_description'
      - 'field_programs/0/value'
    delimiter: '<br /><br />'
```

Update to update: Never mind...

<img width="734" alt="Screen Shot 2022-01-13 at 4 32 32 PM" src="https://user-images.githubusercontent.com/4663676/149419539-314f72eb-d5c9-4e4c-8b05-7f66ccebaf1e.png">

**Comment by briand44** [comment]
Let's just commit to the estimated costs manual migration this sprint.

**Comment by cory-skeers** [comment]
> Update to update: Never mind...

If you go to edit the migrated term and re-save, does the issue persist? If so, might have to explicitly set the `description/value` (or `description/0/value`?) to `filtered_html`.

Something like this, I think:

```
  description/format:
    plugin: default_value
    default_value: filtered_html
```

**Comment by joewhitsitt** [comment]
Thanks @cory-skeers! It was a re-save format issue. Those didn't work for me (maybe a weird term description issue). The secret sauce turned out to be:

```yaml
  description/value:
    plugin: concat
    source:
      - '@temp_description'
      - 'field_programs/0/value'
    delimiter: '<br /><br />'
  description/format:
    -
      plugin: get
      source: format
```

**Comment by joewhitsitt** [comment]
Based on https://github.com/uiowa/uiowa/issues/4638#issuecomment-1012581247, going to un-assign for now and re-focus in the AM

**Comment by joewhitsitt** [comment]
Do I have these steps right @pyrello and @dnkemper for the Estimated Costs migration?

- Filter current grad.admissions website to show only Estimated Costs
- For each estimated cost:
  - Create a disabled link under Cost and Funding
  - Add an estimated cost (https://admissionsgrad.prod.drupal.uiowa.edu/node/add/costs_estimate) and click US Citizens & Permanent Residents", paste in the domestic title, body content (tidy html) and year, and Select ‘provide a menu link’ -> Select ‘Cost and Funding’ -> Select the disabled item created above. Change the menu title to "US Citizens & Permanent Residents." Save.
  - Make a note of the Domestic version `nid` and map as part of a list on this issue to the current grad.admissions `nid` for wiring up the estimated cost during the AoS content migration.
  - Add an estimated cost (https://admissionsgrad.prod.drupal.uiowa.edu/node/add/costs_estimate) and click "International", paste in the domestic title, body content (tidy html) and year, and Select ‘provide a menu link’ -> Select ‘Cost and Funding’ -> Select the disabled item created above. Change the menu title to "International." Save.

**Comment by bspeare** [comment]
Do we need to add the "Year" field to the instructions?

**Comment by joewhitsitt** [comment]
updated to include the year ~~(prepended to the body right?)~~

**Comment by bspeare** [comment]
There's a separate year field if that's what you mean. 

<img width="932" alt="Screen Shot 2022-01-14 at 1 57 18 PM" src="https://user-images.githubusercontent.com/1036433/149577211-1583fd4c-6c8a-4d62-bb5c-7a398386308c.png">

**Comment by pyrello** [comment]
@joewhitsitt Steps looks correct to me.

**Comment by cory-skeers** [comment]
The Estimated Costs have been migrated over, separated into their respective domestic/international components and placed in the menu structure following the instructions above and the previously moved example.

The mapping has also been updated in the issue summary, along with comment lines indicating which degrees they relate to for possible troubleshooting.

**Comment by dnkemper** [comment]
Not all heroes wear capes 🏆

**Comment by cory-skeers** [comment]
Redirects from the old cost estimate paths to the new (domestic) paths have been added, so I believe the estimated costs are officially done being migrated.

**Comment by joewhitsitt** [comment]
AoS subtitle is currently being migrated over I believe. We learned earlier this week that it is no longer necessary (to migrate and to be part of the content type)

**Comment by joewhitsitt** [comment]
Need to revisit the related links. Something isn't wired up correctly:

<img width="359" alt="Screen Shot 2022-01-26 at 11 24 21 AM" src="https://user-images.githubusercontent.com/4663676/151214564-65a728d5-cdf8-41f8-8846-64a4178891f2.png">
<img width="325" alt="Screen Shot 2022-01-26 at 11 24 26 AM" src="https://user-images.githubusercontent.com/4663676/151214566-43a3055e-bc24-44e2-b00d-62114ae68fcf.png">
https://admissionsgrad.uiowa.ddev.site/academics/accounting-mac

Update: catalog fixed, colleges is not a link field (actually a ref field multi) and needs work

**Comment by joewhitsitt** [comment]
Waiting for the broken links map back from Admissions

**Comment by joewhitsitt** [comment]
The Admissions team has provided an initial list of broken link mappings to start working with. Leaving as blocked though until the list is finalized.

https://iowaweb.slack.com/archives/C019B2C8K8U/p1643813586124759?thread_ts=1643730878.610609&cid=C019B2C8K8U

**Comment by joewhitsitt** [comment]
This is now in DEV for customer and technical review.

We can easily add additional broken link mappings to this if they are provided before the final run.

**Comment by briand44** [comment]
Removed blocked label as Admissions gave us approval to run this.

**Comment by joewhitsitt** [comment]
Done. Notified Scott in Slack and provided remaining broken links report.
