### ISSUE TITLE
Intranet - Additional considerations

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#4640]
Not sure if this will become an epic, but we wanted to capture some other aspects of running an Intranet split. Jotting those down here:

- ~~Update content types to not be included in the sitemap and/or look at disabling (but not uninstalling the sitemap functionality). Ultimately, Sitemap.xml should NOT disclose pages that are not accessible without authentication.~~ 
- ~Disable or redirect search result page~
- ~~Remove xml feeds (sitenow articles, taxonomy terms)?~~
- ~~Additional disallow entries to the robots.txt~~
- ~~Remove SEO Settings per content type and/or set meta noindex, nofollow tag set in the meta~~
^^ https://github.com/uiowa/uiowa/issues/4640#issuecomment-1050073341
- ~~See about a certain range of IPs to allow?~~ - https://github.com/uiowa/uiowa/issues/4640#issuecomment-1010431168
- ~~Consider removing header and footer as links and footer content will be public~~ https://github.com/uiowa/uiowa/issues/4640#issuecomment-1050074591
- [x] Custom handling/messages (redirect elsewhere?, Custom Intranet messaging other than Access Denied)
- ~~Update or split off default content to not use public files for this split~~
- ~~Set destination parameter for post-login redirect~~

Pulled bits from comment https://github.com/uiowa/uiowa/issues/4241#issuecomment-952239131, the "later on" todo of https://github.com/uiowa/uiowa/pull/4626 and discussion from our Intranet files meeting

Updated todo:

- [x] Ensure editor/publisher/webmaster do not have access to siteimprove.
- [x] Figure out why the footer login link test isn't failing - it should be. (@richardbporter)
- [x] Set the footer login link config on install of module. (@richardbporter)
- [x] Set config override priority of robotstxt to take precedence over other overrides.

**Comment by richardbporter** [comment]
>See about a certain range of IPs to allow?

Don't think this possible without encountering cache issues.

**Comment by richardbporter** [comment]
I wonder if the "Access Denied" page should actually return a 403? Currently returns 200.

**Comment by briand44** [comment]
Let's probe the items listed in the IS and determine what makes sense to address in additional slices.

**Comment by richardbporter** [comment]
The current login link in the footer sets the destination parameter to redirect back to the access denied page which is really odd UX.

**Comment by joewhitsitt** [comment]
>The current login link in the footer sets the destination parameter to redirect back to the access denied page

This is because it isn't showing the /about 403, it is redirecting to another path so when you click the login link, that is the destination.

I think we would need to alter restrict_ip's code to capture the page that is being accessed and then add that as a destination param for the login link. It might reveal real paths to unauthenticated users if they want to play the guessing game (e.g. /articles/org-welcomes-new-dean-john-doe-public-announce-tbd)

**Comment by richardbporter** [comment]
> > The current login link in the footer sets the destination parameter to redirect back to the access denied page
> 
> This is because it isn't showing the /about 403, it is redirecting to another path so when you click the login link, that is the destination.
> 
> I think we would need to alter restrict_ip's code to capture the page that is being accessed and then add that as a destination param for the login link. It might reveal real paths to unauthenticated users if they want to play the guessing game (e.g. /articles/org-welcomes-new-dean-john-doe-public-announce-tbd)

Yea maybe we could just remove the footer login link in the intranet split somehow? Or if we decide to just hide the footer entirely, its a non-issue.

**Comment by richardbporter** [comment]
>Consider removing header and footer as links and footer content will be public

These don't seem to be displaying on the access denied page for some reason, which is good but I haven't figured out why yet.

**Comment by richardbporter** [comment]
>Update content types to not be included in the sitemap and/or look at disabling (but not uninstalling the sitemap functionality). Ultimately, Sitemap.xml should NOT disclose pages that are not accessible without authentication.
Disable or redirect search result page
Remove xml feeds (sitenow articles, taxonomy terms)?
Additional disallow entries to the robots.txt
Remove SEO Settings per content type and/or set meta noindex, nofollow tag set in the meta

I remember discussing it might not be worth doing all this since none of it is accessible to anonymous users, i.e. SEO bots and we can't uninstall default modules (simple_sitemap, etc.). If it becomes accessible, it'd be for the same reason any content was accessible. It might be possible to add tests to cover these scenarios in #4854.

**Comment by richardbporter** [comment]
> > Consider removing header and footer as links and footer content will be public
> 
> These don't seem to be displaying on the access denied page for some reason, which is good but I haven't figured out why yet.

restrict_ip ships with a hook_block_access() implementation that is taking care of the footer and top links blocks. It is not necessary for us to unset.

**Comment by richardbporter** [comment]
I've been trying to remove the admin login link from the footer but not sure exactly how to do that. I don't think its necessary to show it there, especially since it is setting the destination parameter. The destination parameter for sitenow_intranet will always be the access denied page which already includes a login link.

**Comment by bspeare** [comment]
What methods have you tried?  Can you just unset https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/templates/layout/footer.html.twig#L47-L53 in a preprocess function or something?

**Comment by briand44** [comment]
Test - assert access denied for anonymous users

**Comment by richardbporter** [comment]
>Custom handling/messages (redirect elsewhere?, Custom Intranet messaging other than Access Denied)

This seems doable now with a webmaster-accessible admin form.

>Update or split off default content to not use public files for this split

This might be better left alone until issues like #4849 and #3473 are resolved. In the meantime, we can provision sites as per usual and then `drush entity:delete` everything afterwards.

>Set destination parameter for post-login redirect

I agree this could lead to information disclosure and we shouldn't do it. Another reason to unset the footer login link. The plan for that is to create a config setting that controls it because right now, its not easy to unset.

**Comment by richardbporter** [comment]
Thinking about robots.txt more, should this actually be accessible to bots but configured to disallow all? Is that better than an access denied?

**Comment by joewhitsitt** [comment]
>Thinking about robots.txt more, should this actually be accessible to bots but configured to disallow all? Is that better than an access denied?

Asked @mjoneill in stand up and it sounds like yes, we should do that if possible

**Comment by richardbporter** [comment]
Another thing I just thought of is SiteImprove - it doesn't work without access to the pages. I'm trying this on default dev now and the UI just shows an error. Not sure if there is a way to "disable" it for intranets but I only see it as an admin. Was that taken care of already?

**Comment by richardbporter** [comment]
> Another thing I just thought of is SiteImprove - it doesn't work without access to the pages. I'm trying this on default dev now and the UI just shows an error. Not sure if there is a way to "disable" it for intranets but I only see it as an admin. Was that taken care of already?

OIC. Permissions only exist in the prod split: https://github.com/uiowa/uiowa/search?q=siteimprove 

I think this is something we'd want to address.

**Comment by richardbporter** [comment]
> > Another thing I just thought of is SiteImprove - it doesn't work without access to the pages. I'm trying this on default dev now and the UI just shows an error. Not sure if there is a way to "disable" it for intranets but I only see it as an admin. Was that taken care of already?
> 
> OIC. Permissions only exist in the prod split: https://github.com/uiowa/uiowa/search?q=siteimprove
> 
> I think this is something we'd want to address.

Removing the perms via the intranet split didn't seem to work.
