### ISSUE TITLE
Unlimited slider blocks create unusable slider that doesn't slide

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#4645]
# Problem
It appears that the number of slider blocks you can add is unlimited and creates an unusable slider if there are more than 4 items. 

# Steps to reproduce
https://careers.prod.drupal.uiowa.edu/jobs

https://user-images.githubusercontent.com/1036433/149164741-d8855116-c8aa-464f-a855-4a22d34b995d.mov

# Proposed solution
Limit amount of slides to 4

**Comment by briand44** [comment]
No update hook to change existing content. Update help text

**Comment by joewhitsitt** [comment]
Based on https://github.com/uiowa/uiowa/pull/5159#issuecomment-1108762433

- Switch the field back to unlimited
- Keep the help text
- Similar to https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/layout_builder_custom/layout_builder_custom.module#L491-L497, register the slider block within this validate function, count the number of items and formseterror if it is greater than four.
