### ISSUE TITLE
UI Press - Finish styling and configuring the series vocabulary term pages

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#4659]
# Proposed solution
- [ ] Display books on the Series term page as a cover image, title, and author.
- [ ] Display books in a grid.

**Comment by bspeare** [comment]
Displaying books in a grid using card template with left or right aligned image would look pretty good.   Example of right aligned book cover from a book website below:

<img width="807" alt="Screen Shot 2022-01-25 at 2 28 37 PM" src="https://user-images.githubusercontent.com/1036433/151054471-955a51da-478e-4df7-8ad5-255b54afde22.png">

**Comment by bspeare** [comment]
Was this work completed in https://github.com/uiowa/uiowa/pull/4700? 

<img width="1567" alt="Screen Shot 2022-01-31 at 12 36 27 PM" src="https://user-images.githubusercontent.com/1036433/151852568-90500c38-f6a2-4efc-8451-de75689beb09.png">

**Comment by pyrello** [comment]
Kind of. There was a view added in that PR that is providing the above page in the screenshot, but it was not my desire to add a new view if we could help it. I had been intending to try to figure out how to just set the grid class and pager settings in a views-related hook.
