### ISSUE TITLE
Healthcare signage: Add Hawk IDs to Helpdesk role

### ISSUE THREAD

**Issue by makurj** [uiowa/uiowa#4665]
Please assign the following Hawk IDs to the HD role on https://signage.uihealthcare.org/ and add them signage.uiowa.edu. You will need to be on campus for the HC part.

- [x] On HC signage, add them as HD role and add ITS group to their accounts.
- [x] On signage, add them as HD role and add ITS HelpDesk group to their accounts.

![image](https://user-images.githubusercontent.com/52135878/149554285-b146d7a6-e48f-43e7-a9f0-72ca92219830.png)

Later, on signage.uiowa.edu, the SimpleSAML role mappings are not allowing people to authenticate, so this can be looked into later.
On HC signage, the SimpleSAML role mappings are incorrect.

**Comment by richardbporter** [comment]
Drush could work for this without being on campus.

**Comment by makurj** [comment]
Could you list the steps here?

**Comment by richardbporter** [comment]
Nevermind. The checkbox to allow SAML auth for a user is not checked by default when adding users with `drush user-create`.

**Comment by briand44** [comment]
jricke was added as a user with the Help Desk role and assigned to the ITS group on Healthcare Signage. Hoping he can create the rest of the HD users.

**Comment by makurj** [comment]
https://github.com/uiowa/uiowa/issues/4471#issuecomment-987041927

**Comment by briand44** [comment]
^^ We either will want to address that or update the role mappings and verify that once a user account is created and they log in they will automatically be assigned the Help Desk role.

**Comment by makurj** [comment]
To clarify, we only want any HD AD group or manually added HD Hawk IDs to get the HD role. We don't want other folks on campus who manage signs to get the HD role as it has elevated privileges. Most folks would be editors, etc.

**Comment by briand44** [comment]
Right, just saying if we update the role id's in the existing incorrect role mappings, it should work as you described.

**Comment by briand44** [comment]
The role mappings have been updated on Healthcare Signage. I think we could have Jacob test logging in from on campus and create another HD user and assign them to ITS group. That user could try logging in and verify they get assigned the Help Desk role and have perms to create users, create signs, etc.

**Comment by briand44** [comment]
Sounds like Jacob is not part of the HD anymore. Alan is planning to be on campus Wednesday. We will want to manually add all HD staff with the HD role and assign to ITS group.

**Comment by GaryRidgway** [comment]
I went in and added all these users. Then, i went to the helpdesk in person and asked one of them to sign in and it worked, showing that they all should be able to sign in using the method i used to create them. this should be done.
