### ISSUE TITLE
Image gallery block not functioning as expected

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#4669]
# Problem
If the global caption is set, the image gallery block is excluding images from displaying within the lightbox gallery. 

Sondra also reporting that the image gallery on https://brand.uiowa.edu/environmental-branding is not advancing past the 3rd image.  

# Steps to reproduce
Trying clicking on the first image on https://sandbox.prod.drupal.uiowa.edu/single-image-gallery. 

# Proposed solution
- Move forward with https://github.com/uiowa/uiowa/pull/4708

**Comment by quamsta** [comment]
Noticed this on our [MLK Poster Archive page](https://mlk.uiowa.edu/poster-archive) as well the other day

**Comment by joewhitsitt** [comment]
Maybe a solution will be easy for this once we dig into it, however, I wouldn't mind investigating colorbox alternatives now that we have two bugs now with this setup and it is one of our long term jQuery weak points. https://github.com/uiowa/uiowa/issues/3695

**Comment by briand44** [comment]
Get TM to review photoswipe once we have something we can put in dev.
