### ISSUE TITLE
Add additional domains to default Google CSE

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#4672]
"When I try to find details of an event, a person, a policy, or even a clinic at the hospital, the search results are usually years old, often irrelevant, and not helpful."

Should we have click paths from uiowa.edu search that can take you to UIHC, Advancement, events (for searching)?

Domains to add:
- writinguniversity.org
- foriowa.org
- uihc.org

**Comment by richardbporter** [comment]
@mjoneill Updated with the domains I think need to be added. Any others?

**Comment by mjoneill** [comment]
No, let's start here.  

Thanks for pulling this forward.

**Comment by richardbporter** [comment]
This is done.
