### ISSUE TITLE
Add .ical and .ics file types to file media type

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#4680]
# Story

As an editor, I would like to provide a calendar event file for visitors to download and add to their calendars as a reminder of my upcoming event.

This should not be limited to the event content split but generally available to place within a WYSIWYG.

# Proposed Solution

- [x] Update the file media type configuration to allow .ical and .ics files

**Comment by RishiKumarRay** [comment]
Do we have to edit file extensions?

**Comment by joewhitsitt** [comment]
If the event is on events.uiowa.edu there is an .ics file available. Not a named anchor, etc. but it exists:

<img width="1078" alt="Screen Shot 2022-02-01 at 12 53 06 PM" src="https://user-images.githubusercontent.com/4663676/152032620-b0d13498-79ca-4a62-9ded-e483d6cbb10b.png">
