### ISSUE TITLE
Review/Test International Programs News Migration

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#4685]
It's been awhile since we've done this work. Let's make sure all is still working before we schedule a date to run it in prod.

https://github.com/uiowa/uiowa/issues/3375

# Proposed Solution

Follow test steps on the PR https://github.com/uiowa/uiowa/pull/3716

**Comment by briand44** [comment]
Visual review of this code.

- Check that traits are being used where necessary (processMedia), and that any trait methods have been updated (using the correct variables, correct number of variables, etc)
- Check if there are custom functions added to the Source class that should be replaced with traits
- Check if there are any post-import processes that need to be moved out of an event subscriber and into the postImport function

**Comment by cory-skeers** [comment]
Code review everything looks good. Planning on doing a test run. It does need to be split into multiple runs to work properly.

**Comment by cory-skeers** [comment]
If the migration runs after upgrading to 9.3, we may be able to switch to https://api.drupal.org/api/drupal/core%21modules%21file%21src%21FileRepositoryInterface.php/function/FileRepositoryInterface%3A%3AwriteData/9.3.x in place of `file_save_data` in the ProcessMedia trait, which might help or solve the memory issues that require this to be run in multiple batches.
