### ISSUE TITLE
As an admissions site owner, I can customize the display of my student profiles block

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#4689]
# Story

As an admissions site owner, I can customize the display of my student profiles block for use outside of the student profile pages. 

The current grid display option is not very useful when the block is used on other pages with one or two profiles. 

Profile page grid: https://admissions.uiowa.edu/student-profiles/ashley-cimarolli

<img width="471" alt="Screen Shot 2022-01-20 at 8 40 22 AM" src="https://user-images.githubusercontent.com/1036433/150361281-8fa33987-73ad-4ee1-83e4-f4b870f108fe.png">

California Hawkeyes page: https://admissions.uiowa.edu/node/4896

<img width="969" alt="Screen Shot 2022-01-20 at 8 39 57 AM" src="https://user-images.githubusercontent.com/1036433/150361558-7db47e8e-1328-491f-83f5-d281445438b1.png">

# Proposed solution
- Remove person icon from the block title
- Update view to display name and year: https://github.com/uiowa/uiowa/blob/main/config/sites/admissions.uiowa.edu/views.view.student_card.yml
- Reuse the "List (default)" and "3 columns (default)" and "2 columns" layout builder styles.
- Possibly use the "Hide details" for the option to hide name and major fields and adjust CSS in https://github.com/uiowa/uiowa/blob/main/docroot/sites/admissions.uiowa.edu/modules/admissions_core/sass/student-profile.scss. 
- Move this (https://github.com/uiowa/uiowa/blob/main/docroot/sites/admissions.uiowa.edu/modules/admissions_core/templates/block--views-block--student-card-block-student-grid.html.twig) to use the card template and use `card--stacked` for grid and `card--media-left` for list 
- Could add a modifier class to https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/scss/components/grid.scss for grids to maintain grid style on mobile like on https://user-images.githubusercontent.com/1036433/150361281-8fa33987-73ad-4ee1-83e4-f4b870f108fe.png.

**Comment by joewhitsitt** [comment]
I am a bit confused on the proposed solution. Would it be to provide style options to hide icon and to display like /student-profiles?

**Comment by joewhitsitt** [comment]
Scott said "name and major" should be shown when most room is available.

**Comment by briand44** [comment]
List and Grid style option, list would display name and major. Need to get feedback on this from Admissions.

**Comment by briand44** [comment]
We are good to move forward with adding the list style option that would display name and major. Once we have something for Admissions to see, we should reach out for their feedback.

**Comment by bspeare** [comment]
I've updated the proposed solution with more details.

**Comment by joewhitsitt** [comment]
>Scott said "name and major"
>Update view to display name and year

@bspeare can you confirm that we are supposed to be displaying year instead of major?

**Comment by bspeare** [comment]
@joewhitsitt I think I just typed the wrong thing there.  Good catch!

**Comment by joewhitsitt** [comment]
darn. year would have been easier...

**Comment by joewhitsitt** [comment]
For the different classes per display type, we will have to leverage `hook_preprocess_views_view_unformatted()` similar to what is being done in layout_builder_custom making sure that the admissions module is not overtaken by the logic there.

**Comment by joewhitsitt** [comment]
Capturing some todo:

- [x] Move link from around image to around card
- [x] See about mobile grid modifier only if hide details is in play (admissions specific)
- [x] card--enclosed if grid and title/major are shown?
