### ISSUE TITLE
Hide or adjust feed links in taxonomy term views (but don't remove the feeds entirely)

### ISSUE THREAD

**Issue by quamsta** [uiowa/uiowa#4695]
# Story

Related to: https://github.com/uiowa/uiowa/issues/4435

**Background: This request originated from from Student Disability Services due to user confusion with the "Subscribe to" links on the taxonomy terms on pages like:  https://sds.studentlife.uiowa.edu/tags/ui-scholarships-students-disabilities**

We'd like to hide the "Subscribe to" feed links in taxonomy terms (at least) because of the lack of RSS feed support currently in web browsers. When clicking on a "Subscribe to" link on a taxonomy page like the one below:

<img width="568" alt="Screen Shot 2022-01-11 at 10 22 23 AM" src="https://user-images.githubusercontent.com/472923/148981143-5370fdcc-2eb3-4b16-85b8-188d032130a1.png">

Users are presented with the following dialogs or raw XML code depending on the browser:

Chrome:
<img width="942" alt="Screen Shot 2022-01-11 at 10 28 15 AM" src="https://user-images.githubusercontent.com/472923/148982463-eed98e1f-5818-4845-9af1-d99d4fd259da.png">

Safari does a weird variety of things including:

![](https://user-images.githubusercontent.com/4663676/151036401-d3d0c6e2-e551-4d51-a7b9-fa556551bd50.png)

<img width="1227" alt="Screen Shot 2022-01-25 at 3 44 01 PM" src="https://user-images.githubusercontent.com/472923/151072009-611d6edf-d8af-4974-a7ca-727244e32b3d.png">

<img width="1120" alt="Screen Shot 2022-01-11 at 10 27 50 AM" src="https://user-images.githubusercontent.com/472923/148982299-18310769-d00f-4bfd-832d-cd3228341cf8.png">

Firefox:
<img width="486" alt="Screen Shot 2022-01-11 at 10 27 36 AM" src="https://user-images.githubusercontent.com/472923/148982264-520d6f1b-a9ae-4aea-9b4c-9ce6af772934.png">

# Proposed solution

As @mark-bennett-uiowa stated in https://github.com/uiowa/uiowa/issues/4435, the feeds themselves are often crucial to some sites' functionality. And as @joewhitsitt said in the same issue, RSS feeds may see a comeback in the browser. 

However, the anchor/link in the body of the taxonomy term's page really only results in user confusion unless they have an RSS feed reader extension installed in their browser.

My proposed solution is that we simply hide the link on the taxonomy term with CSS for now. This leaves the feed attached to the taxonomy view and the RSS feed is still visible to feed readers in the DOM, or to anyone who actually needs to find the feed URL:

`<link rel="alternate" type="application/rss+xml" title="UI Scholarships for Students with Disabilities" href="https://sds.studentlife.uiowa.edu/taxonomy/term/16/feed"/>`

**Comment by quamsta** [comment]
A couple of notes from the grooming/mid-sprint demo:

- Users of the Aggregator module to feed sites need visible links to the RSS feeds for ease-of-access
- As @joewhitsitt mentioned, not every browser situation presents the feeds as broken.
> FWIW, this is my Safari experience which I don't think is broken either:
> ![](https://user-images.githubusercontent.com/4663676/151036401-d3d0c6e2-e551-4d51-a7b9-fa556551bd50.png)

I'm going to revisit this and see if the link can be presented in a friendly way that doesn't break current functionality.

**Comment by joewhitsitt** [comment]
I am probably in the boat of leave the link, add the orange icon (small) and maybe change the link to be explicit about what it is but I can be out voted and move on. Academic orgs are generally filled with folks (myself included) that love the availability of these "power-user" additions. With that said, I am not going to die defending RSS links on primary brochure type sites.

I just checked and we are already customizing views-view.html.twig in uids_base (from classy base) and commenting out the render of feed icons removes it from the render but keeps it in the head as an alternate. Now, SiteNow articles has a toggle for this that is currently enabling/disabling the entire view display. The toggle feature should probably be maintained but can be adjusted by either splitting the template for the news view page or changing what the toggle does (keep display enabled but change the template render (link not rendered by default)). We could implement the same toggle functionality could be done on each vocabulary where we ask similar questions of whether the term pages should even be viewable to visitors.

**Comment by quamsta** [comment]
Hi all, took a stab at this again this morning and wanted to show an option or two that may work:

## Idea 1: Show newly styled/worded feed buttons for all users
This idea has the FontAwesome RSS icon (in gold, just to stay on brand) in a tertiary button style with the text "RSS Feed" showing for all users (logged in or not) in the bottom right, which places it a bit out of the way and not in the same visual hierarchy as the list of pages above it.

<img width="859" alt="Screen Shot 2022-01-26 at 8 59 14 AM" src="https://user-images.githubusercontent.com/472923/151187478-9510a7ae-81bf-4f81-b7d1-dd748c202c50.png">

## Idea 2: Show feed links for logged in users

Same as above, except **only show the feed links to logged in users**. @pyrello mentioned that these feeds are often used and consumed by other webmasters or editors on campus. My thought here is that users who need to be able to consume feeds might be webmasters or editors on the sites that provide the feeds.

 I'm not sure if this is a common way that editors are using feeds. @pyrello are the users of these feeds typically editors on sites that provide them?

## Idea 3: Remove the feed_icons variable from the template

This is a variation on my original "just remove the darn link" proposal, where instead of hiding the link via CSS, the variable is removed from the `views-view.html.twig` template instead, which is a cleaner way to do this.

**Comment by richardbporter** [comment]
>Idea 1: Show newly styled/worded feed buttons for all users

I like this.

**Comment by richardbporter** [comment]
>I'm not sure if this is a common way that editors are using feeds. @pyrello are the users of these feeds typically editors on sites that provide them?

Maybe, maybe not. I think Idea 1 is the safer option.

**Comment by joewhitsitt** [comment]
I think "idea 1" is going to get the most support (based on the discussion earlier) until RSS is actually dead. It is a small slice and will close https://github.com/uiowa/uiowa/issues/4435 as well.

I know that it was mentioned that the rss blocks were a big consumer of these links these days, but I don't think it is safe to say that solely folks with access to the site are the ones grabbing these links.

I could get behind idea three if we make it an option for developers or site owners to toggle on per-vocab basis (with the stylings of idea 1). That way student life can get what they originally wanted. This is a bigger slice though.

**Comment by pyrello** [comment]
I also like idea 1 the best because it will allow us to get feedback from users that will help clarify the problem or let us know that we have resolved it. I'm not necessarily opposed to the idea of removing the feed link or changing the way it is delivered, but I think generally we want to be thoughtful and deliberate about removing features (even if they are not well-implemented).

**Comment by quamsta** [comment]
Opening up a PR for Idea 1. Thanks all!

**Comment by quamsta** [comment]
https://github.com/uiowa/uiowa/pull/4714

**Comment by bspeare** [comment]
@quamsta should we close this issue?

**Comment by mark-bennett-uiowa** [comment]
@quamsta @bspeare @joewhitsitt Yes, closing this issue due to latest updates. Thanks!

**Comment by mark-bennett-uiowa** [comment]
I closed my issue #4435 . Thanks!
