### ISSUE TITLE
Tippie - tasks to facilitate site development

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#4701]
# Motivation

As part of the work on #3200 and the subsequent conversation about it is that we may not be ready to move ahead with a platform-level solution to opening up the menu block options. However, this was a requirement for Tippie's website. Also, they are likely going with a horizontal menu on most pages, so facilitating that for them would be nice.

# Proposed solution

- [ ] Add a layout builder style called "Mega" and a machine-name/ID of `block_menu_mega` and group set to `menu_orientation`.
- [ ] Add `layout_builder_styles.style.block_menu_mega` config as completely split to the Tippie site split.
- [ ] Modify the page LB template to replace the "layout w/sidebar" layout with a one column layout with just the body field in it. Below the header section, add a new section and add the main menu block. Default settings are to be determined based on feedback from the customer.
- [ ] Add the `core.entity_view_display.node.page.default` config as completely split to the Tippie site split. 
- [ ] Re-export the Tippie site split.

**Comment by bspeare** [comment]
I think this issue is blocked until we get clarification from Tippie on what direction they want to pursue for the navigation.   We received some new requests this morning that we need to figure out before moving forward.

**Comment by bspeare** [comment]
Waiting to hear back from James about what direction they want to take with the horizontal menu so I've added the blocked label for now.   I will update this issue as soon as I get an answer.

**Comment by bspeare** [comment]
Tippie has decided to go with https://github.com/uiowa/uiowa/issues/4823, and we will need to update this issue with a new proposed solution once we have groomed #4823.

**Comment by bspeare** [comment]
We need to discuss the pros and cons of this with James and Nikki, @makurj and I have a meeting with them set for 3/3.  The question is whether they need the `core.entity_view_display.node.page.default` if they are designing templates that they plan on replicating for use throughout the site.

**Comment by bspeare** [comment]
Tippie is OK with using the replicate function so I don't think they need this work done.
