### ISSUE TITLE
Content hub maps.uiowa.edu building links

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#4704]
It looks like content.uiowa.edu has a taxonomy called Places with a link field that is populated with lots of maps.uiowa.edu URLs for building pages. These Places are output in the API when referenced from an event which in turn gets displayed on lots of different websites. These will need to be updated to point to facilities.uiowa.edu instead. A quick count of Places looks to be around 250. It was previously mentioned that content hub owners do not have capacity to do this. An update hook should be possible using https://data.its.uiowa.edu/maps/number-lookup

**Comment by richardbporter** [comment]
Proposed solution

Update hook to iterate all Places taxonomy terms, parse URL and check host matches maps.uiowa.edu, if so check path exists in data.its number lookup, if so resave field as facilities link using building number.

**Comment by joewhitsitt** [comment]
A little extra info to get started with: 

```php
$vid = taxonomy_vocabulary_machine_name_load('places')->vid;
$terms = taxonomy_get_tree((int) $vid);
foreach ($terms as $term) {
  // Parse and fix url value.
  // Save term edit.
  taxonomy_term_save($term);
}
// Clear caches.
drupal_flush_all_caches();
```

**Comment by cory-skeers** [comment]
Having some difficulties with local environment, but while working on it, grabbed a list of the terms that need to be updated as a way to check.

113 terms total that include "maps" (plus one extra false positive that's a google URL).

<details>

<summary>
Maps URLs
</summary>

entity_id | url
------ | --------------
357 | http://maps.uiowa.edu/chst
358 | http://maps.uiowa.edu/tnsw
359 | http://maps.uiowa.edu/mtp2
360 | http://maps.uiowa.edu/mtp1
361 | http://maps.uiowa.edu/mtp4
374 | http://maps.uiowa.edu/bhs
398 | http://maps.uiowa.edu/csm5
399 | http://maps.uiowa.edu/csm6
403 | http://maps.uiowa.edu/cc
406 | http://maps.uiowa.edu/cctr
444 | http://maps.uiowa.edu/hca
445 | http://maps.uiowa.edu/hda
449 | http://maps.uiowa.edu/hra
464 | http://maps.uiowa.edu/icl
466 | http://maps.uiowa.edu/ipa
471 | http://maps.uiowa.edu/gsb
477 | http://maps.uiowa.edu/jb
478 | http://maps.uiowa.edu/jh
481 | http://maps.uiowa.edu/khf
483 | http://maps.uiowa.edu/ks
484 | https://maps.uiowa.edu/krc
485 | http://maps.uiowa.edu/kh
486 | http://maps.uiowa.edu/lshs
487 | http://maps.uiowa.edu/lsc
488 | http://maps.uiowa.edu/lnac
489 | http://maps.uiowa.edu/l
490 | http://maps.uiowa.edu/lb
491 | http://maps.uiowa.edu/lab
492 | http://maps.uiowa.edu/lfr
493 | http://maps.uiowa.edu/lhpd
494 | http://maps.uiowa.edu/lgbt
495 | http://maps.uiowa.edu/lcua
496 | http://maps.uiowa.edu/ls
497 | http://maps.uiowa.edu/lc
498 | http://maps.uiowa.edu/lsp
499 | http://maps.uiowa.edu/mh
501 | http://maps.uiowa.edu/mlh
502 | http://maps.uiowa.edu/mssb
503 | http://maps.uiowa.edu/m
504 | http://maps.uiowa.edu/meb
505 | http://maps.uiowa.edu/merf
506 | http://maps.uiowa.edu/ml
507 | http://maps.uiowa.edu/mrc
508 | http://maps.uiowa.edu/mrf
509 | http://maps.uiowa.edu/mapf
510 | http://maps.uiowa.edu/mbsb
511 | http://maps.uiowa.edu/mtf
512 | http://maps.uiowa.edu/mw
513 | http://maps.uiowa.edu/nads
514 | http://maps.uiowa.edu/nrp
515 | http://maps.uiowa.edu/ncp
516 | http://maps.uiowa.edu/nh
518 | http://maps.uiowa.edu/cnb
519 | http://maps.uiowa.edu/orf
520 | http://maps.uiowa.edu/osba
521 | http://maps.uiowa.edu/stua
522 | http://maps.uiowa.edu/opp
526 | http://maps.uiowa.edu/pbb
527 | http://maps.uiowa.edu/jpp
528 | http://maps.uiowa.edu/park
530 | http://maps.uiowa.edu/ss
533 | https://maps.uiowa.edu/phar
534 | http://maps.uiowa.edu/ph
535 | http://maps.uiowa.edu/prl
536 | http://maps.uiowa.edu/pco
537 | http://maps.uiowa.edu/pc
538 | http://maps.uiowa.edu/pfp
539 | http://maps.uiowa.edu/pp
541 | http://maps.uiowa.edu/pr
542 | http://maps.uiowa.edu/pltf
544 | http://maps.uiowa.edu/q
545 | http://maps.uiowa.edu/bwcc
546 | http://maps.uiowa.edu/rb
547 | http://maps.uiowa.edu/rpls
548 | http://maps.uiowa.edu/r
550 | http://maps.uiowa.edu/rrh
551 | http://maps.uiowa.edu/rmcd
552 | http://maps.uiowa.edu/srsb
553 | http://maps.uiowa.edu/sh
554 | http://maps.uiowa.edu/sl
555 | http://maps.uiowa.edu/sc
556 | http://maps.uiowa.edu/ssh
557 | http://maps.uiowa.edu/shse
559 | http://maps.uiowa.edu/srf
560 | http://maps.uiowa.edu/s
561 | http://maps.uiowa.edu/scsb
562 | http://maps.uiowa.edu/sq
563 | http://maps.uiowa.edu/sw
564 | http://maps.uiowa.edu/nh
565 | http://maps.uiowa.edu/slp
566 | http://maps.uiowa.edu/osmr
567 | http://maps.uiowa.edu/stan
568 | http://maps.uiowa.edu/shl
569 | http://maps.uiowa.edu/shsb
570 | http://maps.uiowa.edu/hli
572 | http://maps.uiowa.edu/sa
573 | http://maps.uiowa.edu/sth
574 | http://maps.uiowa.edu/tic
578 | http://maps.uiowa.edu/tb
581 | http://maps.uiowa.edu/th
582 | http://maps.uiowa.edu/bvc
584 | http://maps.uiowa.edu/ucc
586 | http://maps.uiowa.edu/uac
592 | http://maps.uiowa.edu/upcc
593 | http://maps.uiowa.edu/usb
596 | http://maps.uiowa.edu/vs
598 | http://maps.uiowa.edu/wp
599 | http://maps.uiowa.edu/inrc
600 | http://maps.uiowa.edu/shc
601 | http://maps.uiowa.edu/wcsp
602 | http://maps.uiowa.edu/wctc
603 | http://maps.uiowa.edu/wl
604 | http://maps.uiowa.edu/wrac

</details>

**Comment by joewhitsitt** [comment]
Forgot to note that local development for this site needs a little love before work can be done: https://wiki.uiowa.edu/display/sitenow/content.uiowa.edu

**Comment by cory-skeers** [comment]
Started on this this morning, and the total of maps.uiowa.edu links is down to 29 from 113...looks like someone may be doing this already?

No revisions on the taxonomy terms, so not sure who's doing it, but looks like this might be a person over machine case after all.

**Comment by cory-skeers** [comment]
Updated list as of 2/2 (22 rows remaining).

Spot checking these, it looks like they may all be in our list of known retired buildings (no facilities link for the building number) or simply unavailable on the maps.uiowa.edu currently.

Still unsure of who exactly did the updates, but the number remaining (and especially if they are all retired buildings) has made pursuing an automated solution moot.

<details>
<summary>Maps urls</summary>

entity_id | url
---- | ----------------
358 | http://maps.uiowa.edu/tnsw
374 | http://maps.uiowa.edu/bhs
398 | http://maps.uiowa.edu/csm5
399 | http://maps.uiowa.edu/csm6
403 | http://maps.uiowa.edu/cc
406 | http://maps.uiowa.edu/cctr
444 | http://maps.uiowa.edu/hca
445 | http://maps.uiowa.edu/hda
449 | http://maps.uiowa.edu/hra
464 | http://maps.uiowa.edu/icl
471 | http://maps.uiowa.edu/gsb
491 | http://maps.uiowa.edu/lab
498 | http://maps.uiowa.edu/lsp
509 | http://maps.uiowa.edu/mapf
512 | http://maps.uiowa.edu/mw
542 | http://maps.uiowa.edu/pltf
550 | http://maps.uiowa.edu/rrh
556 | http://maps.uiowa.edu/ssh
561 | http://maps.uiowa.edu/scsb
574 | http://maps.uiowa.edu/tic
586 | http://maps.uiowa.edu/uac
592 | http://maps.uiowa.edu/upcc

</details>
