### ISSUE TITLE
Grad Admissions AoS Updates round 2

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#4706]
- [x] Remove button styles for cost estimate reference on Area of Study - should just use regular link styles
- [x] Allow control of text link for button on Apply box in sidebar
- [x] Change order of college field & related fields to match admissions
- [x] Reverse display of related links to show colleges first
~- [ ] Not sure if this issue is being worked on as part of the migration or if it should be handled here https://github.com/uiowa/uiowa/issues/4638#issuecomment-1022421795~

**Comment by bspeare** [comment]
It seems like we just need to reverse the display of the related links to show the colleges first.   @joewhitsitt aren't we using the same field setup that admissions is using for the related links?

<img width="453" alt="Screen Shot 2022-01-27 at 9 17 35 AM" src="https://user-images.githubusercontent.com/1036433/151388132-b6197d3b-0d37-49bf-b185-49c9b989898f.png">

**Comment by dnkemper** [comment]
@bspeare okay sure thing! I remember there was a reason why I did it this way... might have been following D7 site?

**Comment by joewhitsitt** [comment]
Not sure I know what the last bullet point means or what the ask was. The migration is moving content over, we aren't changing the layout. If it is changing order of field values, in code, for related links there is this:

>Add field_area_of_study_link to the end of field_area_of_study_college. - `grad_admissions_core_preprocess_field()`

**Comment by bspeare** [comment]
Sounds like we can remove that last box.  Thanks for the clarification @joewhitsitt!
