### ISSUE TITLE
As a site owner, I can use a newly added pre-title field as a part of the banner block that appears above the banner title

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#4713]
# Story

As a site owner, I can use a pre-header field in the banner block

![curriculum_testiowamba](https://user-images.githubusercontent.com/1036433/151570405-14a6c4ff-d763-4098-a03a-d813b6f6b2ed.png)

# Proposed solution

- [ ] Add a pre-header field to the banner block
- [ ] Add help text to the field "The pre-title will not appear on the page if the title field is empty."
- [ ] Update banner block template to not render pre-title if title field is empty
- [ ] Pre-title styles will either be Antonio caps or Zilla based on headline style

**Comment by bspeare** [comment]
Since Tippie wants this "pre-title" field to function as a breadcrumb path for each page, is it worth considering this instead as an adjustment to the featured image instead of the banner block?  

We would need to add this functionality to the featured image:

- Ability to center the page title on the featured image
- Ability to adjust headline styles of featured image
- Ability to set the "Active trail's parent title" as the breadcrumb instead of the full path

**Comment by joewhitsitt** [comment]
The more it is a part of the node, breadcrumb, the less it seems likely that banner will handle this. That said, placing all of this alongside the featured image doesn't sound right to me. Pre-title is starting to sound like a field that should work regardless of whether a featured image exists.

**Comment by bspeare** [comment]
Seems like the page title alignment is something the stories site could use if that helps inform our decision here at all:

- Centered: https://stories.uiowa.edu/grant-day-arm-injury-serving-country-and-county
- Right aligned: https://stories.uiowa.edu/andy-spurgin-pharmacy-grad-practicing-estherville
- Left aligned: https://stories.uiowa.edu/husband-wife-hearing-world-around-them-better
- Top right aligned: https://stories.uiowa.edu/maddie-mccarron-sports-media
- Top left aligned: https://stories.uiowa.edu/175-years-400k-degrees

**Comment by bspeare** [comment]
I also have concerns that the "pre-title" field would be used for large chunks of text like we have seen with the Prefix and Suffix fields in the Statistic block which is why turning the "pre-title" field into some sort of breadcrumb path is appealing.

**Comment by makurj** [comment]
I would like to pair on this.

**Comment by bspeare** [comment]
After grooming this we decided to add the pre-title field to the banner block and add help text below the field to say something like "The pre-title will not appear on the page if the title field is empty."
