### ISSUE TITLE
Need Vulture redirects for two domains to frg.physics.uiowa.edu

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#4720]
# Problem
Michael Flatte from Physics and Astronomy just approved his new Flatte Research Group lab website: [https://frg.physics.uiowa.edu](https://frg.physics.uiowa.edu). When I contacted the Physics IT group to make the DNS switch from the Physics web server to Acquia LB, there were two additional DNS entries for this site.

nano.physics.uiowa.edu is the A-record for the original site.
flatte.physics.uiowa.edu is a CNAME to nano.
frg.physics.uiowa.edu is a CNAME to nano.

The Physics and Astronomy IT group has ended up pointing all three at the Acquia LB now:

```
I made the DNS updates to nano and flatte this morning based on the email from last evening.  It looks like Mark Bennett may need to make an update to the Acquia site for those to start working.
frg             IN      CNAME                   acquia-dlb.its.uiowa.edu.
nano            IN      CNAME                   acquia-dlb.its.uiowa.edu.
flatte          IN      CNAME                   acquia-dlb.its.uiowa.edu.
```

I have added the two additional domains to uiowa01 (where frg.physics.uiowa.edu was created). I now need the .htaccess file updated with these two rules so that traffic to nano.physics or flatte.physics will go to frg.physics properly:

```
  # nano.physics.uiowa.edu
  RewriteCond %{HTTP_HOST} ^nano\.physics\.uiowa\.edu$ [NC]
  RewriteRule ^(.*)$ https://frg.physics.uiowa.edu/ [R=301,L]

  # flatte.physics.uiowa.edu
  RewriteCond %{HTTP_HOST} ^flatte\.physics\.uiowa\.edu$ [NC]
  RewriteRule ^(.*)$ https://frg.physics.uiowa.edu/ [R=301,L]
```

# Proposed solution
I just got DDEV working on my machine and havent performed a PR since. Also, if I remember correctly, there was an additional file that needed updating. Could use some assistance if possible, thanks!

**Comment by briand44** [comment]
We are attempting to get away from handling redirects in .htaccess. I will reach out to our sysadmin to see if he can create these on Vulture. Going to update the title to represent this.

**Comment by briand44** [comment]
I think the process will be:

- Create redirects on Vulture
- Update DNS to point to Vulture
- SSL certs created on Vulture

There will likely be 10-30 mins of downtime while SSL certs are being setup.
