### ISSUE TITLE
Tippie News Migration

### ISSUE THREAD

**Issue by makurj** [uiowa/uiowa#4725]
1. Look at other migration issues to get a sense of how to do this. Taxonomy terms, etc.
2. How much news is Tippie migrating? Look at analytics. WAITING ON ANSWER.
3. Review Tippie's current content type (fields, taxonomy terms, etc.)
4. How to handle redirects? Broken links?
5. What will be required by Tippie once the migration solution is ready?
6. Get a solution ready before mid-May.
7. Get this done by mid-May on prod.

# Proposed Solution/Checklist

- [x] Establish migration module for tippie
- [x] news from jan 2020 forward
- [x] Map tags referenced in https://github.com/uiowa/uiowa/issues/4725#issuecomment-1121417859
  - [x] check for replacements/cleanup
  - [x] if department gets "department_name" tag but check xls for replacements.
  - [x] Type - media mention gets "media mention" else tag with "news"
  - [x] Featured research gets 'faculty research' and confirm "research" tag is in the mix.
- [x] Ignore content blocks but provide a list of nodes that should be updated post-migration (38 articles)
- [x] url/title to source org/link
- [x] "news writer, link title" to organization
- [x] broken links report
- [x] redirects

**Comment by briand44** [comment]
What existing content type are you wanting to migrate over as articles? Currently I see Alumni News, Blog (no content), News Item, Story.

**Comment by makurj** [comment]
News item. Also pinging @JKurtzlebenUI

**Comment by briand44** [comment]
Making some notes in regards to existing fields on the news item content type that don't exist in v3.

- Type - (Press Release, Media Mention)
- Featured Research
- Date
- Content Block Types - (Image, multicolumn image, text area, video)
- News Writer - where should this map, article author (person) or organization?
- Source link title - Does this map to organization?
- Departments -

**Comment by briand44** [comment]
Migrate all news from Jan 2020 forward

**Comment by cory-skeers** [comment]
Couple extra notes from poking around:

805 total news items, with 386 since jan 1 2020 (~1577858400 timestamp)
News Body Archive? (looks like only 2 news items since Jan 2020 have anything in it: 71206 [empty spaces] and 77111 [one paragraph of text]). Can probably skip.

Content block—38 articles use these, 137 blocks total
limited number of paragraph types to account for, with some amount of style options as well.
For automated migration, we can try to map as close as possible into the body field, or dump all content with the idea that they’ll be manually cleaned up. Unsure of how big a lift recreating the content in the body would be without further investigation.

**Comment by cory-skeers** [comment]
Some notes from the 4/25 meeting:

- news from jan 2020 forward
- type: pr or media mention
  - Tag articles as "news" unless they are a media mention (media mention should get "media mention" tag)
- ignore featured research (but should pull over 'research' tag)
- there are some hierarchies in taxonomies, which may or may not need extra work--but generally pull over all tags. They may do some tag auditing and/or tag mapping work prior.
- date field: created
- Content blocks—ignore these for now, but give them a list of nodes that will need updated post-migration (38 articles)
- Source information:
  - news writer (generally blank for PR, media mention usually author’s name) - map to organization
  - url/title map to source org/link
  - what if there’s a news writer as well as url/title? - join writer and title with a comma separator
- ignore full text archive
- every news article not media mention gets news, if it has a department then also a department-news tag.

**Comment by briand44** [comment]
Thanks Cory! The only thing that I understood differently was that I didn't think we needed a plain department tag. Also, create redirects and broken links report.

**Comment by joewhitsitt** [comment]
Not sure how to achieve maintaining taxonomy hierarchy (usually a separate migration) while also doing random adding new tags on the fly. Thoughts/examples are welcome.

**Comment by JKurtzlebenUI** [comment]
Amanda and I mapped some key tags for migration.
 
The first tab in the spreadsheet addresses both the existing D7 article form tabs and checkboxes as well as streamlining a few of the existing tags to map from D7 tags, checkboxes and fields to D9.
 
The second tab has the go-forward tagging rules for creating new stories and includes some new tags. This probably isn’t directly useful in the scripting for migration. Maybe more to show the plan for tagging going forward after launch.
 
Let us know if you have questions or suggestions.
[News Tag Audit_Tippie.xlsx](https://github.com/uiowa/uiowa/files/8654138/News.Tag.Audit_Tippie.xlsx)

**Comment by joewhitsitt** [comment]
I think I misunderstood Cory's notes about hierarchy. I had a short huddle with @makurj to get clarification. I think I have what I need now.

**Comment by joewhitsitt** [comment]
@JKurtzlebenUI, for departments, your spreadsheet has them coming over as `UI Document Center (DC)`, `gmp`, `iowa jpec`, etc. but then we have a note to append `-news` to these. So like `UI Document Center (DC)-news`, `iowa jpec-news`

Is that correct?

<img width="415" alt="Screen Shot 2022-05-11 at 8 38 49 AM" src="https://user-images.githubusercontent.com/4663676/167863463-6e10c0bf-a0cf-4c5a-bd84-5eee8cdb89b6.png">

**Comment by JKurtzlebenUI** [comment]
Anything that doesn't have a tag 'media mention' should get a tag 'news'. On the second tab in the sheet for rules, we're going to count on their either being the tag 'news' or 'media mention' to determine if that article displays in a media mentions list or a news list. This would include the list of all past articles (back to Jan 2020 in this case) only consisting of articles tagged 'news.' Not sure if that use case helps some.

**Comment by joewhitsitt** [comment]
Yeah, that should already be wired up (media mention/news). So I don't need to separately append `-news` to all tags for this migration to make them news specific tags?

**Comment by JKurtzlebenUI** [comment]
yeah, as we worked through the tagging process, and reminded ourselves about any filters with multiple tags being an 'or' statement and understanding all the existing use cases, we decided we didn't need the compound tag.

**Comment by JKurtzlebenUI** [comment]
so as long as a non-media mention story about, say business analytics gets the tags "business analytics" and "news" should be ok if we're understanding properly :)

**Comment by JKurtzlebenUI** [comment]
The use cases for tags is on the second tab in the spreadsheet and  you'll see some exclusively use 'news' or 'media mention' but others only use the subject tags like 'business analytics' or 'msba' or both. :)

**Comment by joewhitsitt** [comment]
@JKurtzlebenUI and @makurj I believe the migration is to a reviewable state. Should I run this in DEV for your review?

**Comment by makurj** [comment]
Yes, please. Thank you!

**Comment by joewhitsitt** [comment]
@JKurtzlebenUI and @makurj ,

This is available in DEV for review. https://tippie.dev.drupal.uiowa.edu/news

Non-migration images were not synced down from tippie.prod.drupal.uiowa.edu

Cory noticed a summary encoding issue with https://tippie.dev.drupal.uiowa.edu/node/4146/edit that I am going to see if we can do anything about. Since this is formatted text migrating into plain text, I am not sure much can be done besides stripping html.

**Comment by JKurtzlebenUI** [comment]
Joe, this is looking really nice! Thanks to you and the team. I'd like to share this with our two comms folks at Tippie as they're closer to the content and have a better feel for looking things over. 

Would that be ok or is there a reason you'd like me to wait until sharing with them?

**Comment by joewhitsitt** [comment]
Yes, the more eyes the better

**Comment by makurj** [comment]
Looks so good!

**Comment by joewhitsitt** [comment]
## Possible broken links, content blocks report (DEV - 5/11):

- [notice] Content blocks found on old /node/70836. Consider revising For the love of numbers (& diamonds)
- [notice] Content blocks found on old /node/70846. Consider revising Diving in: 3M director sees company and his family through a year of change
- [notice] Content blocks found on old /node/70851. Consider revising 40/40/20
- [notice] Content blocks found on old /node/71021. Consider revising 3 people 3 questions
- [notice] Content blocks found on old /node/71201. Consider revising Tippie Gateway opens doors for participants 
- [notice] Content blocks found on old /node/71691. Consider revising Student enrollment numbers remain steady in the midst of the pandemic
- [notice] Content blocks found on old /node/72656. Consider revising Welcome to the family: meet our four new accounting faculty members
- [notice] Content blocks found on old /node/72671. Consider revising Goodbye Jetlag: Brad Downes is bringing supersonic travel to the masses
- [notice] Content blocks found on old /node/72681. Consider revising In memoriam: John Doyle Phillips Jr. 
- [notice] Content blocks found on old /node/72686. Consider revising Why is Grant Wynia in the middle of the jungle?
- [notice] Content blocks found on old /node/72691. Consider revising Accounting graduates CPA exam performance ranks first in Iowa; fourth in Big Ten
- [notice] Content blocks found on old /node/72761. Consider revising Fearless negotiations
- [notice] Content blocks found on old /node/72766. Consider revising Fearless Midwestern neighborliness
- [notice] Content blocks found on old /node/72781. Consider revising Fearless entrepreneur 
- [notice] Content blocks found on old /node/73421. Consider revising Virtual study abroad in Italy receives positive response and unexpected benefits
- [notice] Content blocks found on old /node/74361. Consider revising More than a game: How Nicole Schmidt found a home for herself in baseball
- [notice] Content blocks found on old /node/74366. Consider revising Outrunning a tidal wave: What it's like to be a hospital COO during COVID-19
- [notice] Content blocks found on old /node/74371. Consider revising Wait. Is that Chuck Norris?
- [notice] Content blocks found on old /node/74376. Consider revising Proof: Associate Professor Richard Peter has it
- [notice] Content blocks found on old /node/74381. Consider revising Gloves up: Jose Duran is a fighter by trade
- [notice] Content blocks found on old /node/74406. Consider revising 3 People / 3 Questions: Eden Simmer, Lisa Stange, & Lu Li
- [notice] Content blocks found on old /node/74701. Consider revising How Henry and Patricia Tippie Met
- [notice] Content blocks found on old /node/75991. Consider revising Before her time: A deep dive into the epic history of Mary E. Murphy (BSC27)
- [notice] Content blocks found on old /node/76131. Consider revising The power of the fourth estate
- [notice] Content blocks found on old /node/76136. Consider revising Working behind the scenes to get you Clorox wipes
- [notice] Content blocks found on old /node/76186. Consider revising Financial sleuth: Shawn Fox always finds the money
- [notice] Content blocks found on old /node/76191. Consider revising Hitting all the fairways
- [notice] Content blocks found on old /node/76216. Consider revising Black Diamonds: Q&A with Vail Resorts Accounting Manager Wynn Tan (BBA18) 
- [notice] Content blocks found on old /node/76451. Consider revising In Memoriam
- [notice] Content blocks found on old /node/76506. Consider revising 175 years: Black and gold history
- [notice] Content blocks found on old /node/76591. Consider revising The John Pappajohn Entrepreneurial Center Celebrates a Quarter Century of Innovation
- [notice] Content blocks found on old /node/76851. Consider revising “I’ll take S corps for 500, Alex”
- [notice] Content blocks found on old /node/77256. Consider revising Shining a light into a dark market
- [notice] Content blocks found on old /node/77356. Consider revising Thriving in Dubai
- [notice] Content blocks found on old /node/77361. Consider revising Saving a million lives
- [notice] Content blocks found on old /node/77371. Consider revising Forks in the road
- [notice] Content blocks found on old /node/77376. Consider revising 3 People 3 Questions
- [notice] Content blocks found on old /node/77406. Consider revising Learning to sell
- [notice] Possible broken links found in node 2966: Master of Science in Finance Program: node/9876
- [notice] Possible broken links found in node 3031: Master of Science in Finance: node/9876
- [notice] Possible broken links found in node 3091: Master of Science in Finance program: node/9876
- [notice] Possible broken links found in node 3121: Master of Science in Business Analytics (MSBA): node/2127,Business Analytics Part-Time Graduate Program: node/130
- [notice] Possible broken links found in node 3501: Iowa MBA: node/74591

**Comment by JKurtzlebenUI** [comment]
Thanks for the links report, Joe, and also thanks for your work on this migration!

**Comment by JKurtzlebenUI** [comment]
Hi Joe, can you tell if we're picking up articles at this level: https://tippie.uiowa.edu/news/alumni/matthew-j-smith-named-cfo

There's not a date associated with it, so i couldn't easily search. I wondered if it was something you could tell from what your script pulled.

**Comment by briand44** [comment]
We are not. That is part of the alumni news content type and we are migrating news item content. https://github.com/uiowa/uiowa/issues/4725#issuecomment-1101755187

**Comment by JKurtzlebenUI** [comment]
gotcha, i'd thought they were part of the news article type in D7. Is there anyway we could bring those too? We'd want to just tag them 'alumni updates' and not have a 'news' or 'media mentions' tag assigned.

**Comment by JKurtzlebenUI** [comment]
Let's go ahead and import the news that we have into Production. Amanda has given her go-ahead.

**Comment by joewhitsitt** [comment]
Got the go-ahead from @JKurtzlebenUI to run the migration in PROD as soon as possible. I will be looking to get the PR merged and deployed so it can be run.

**Comment by joewhitsitt** [comment]
This was run in PROD this AM

**Comment by JKurtzlebenUI** [comment]
Tippie Comms was trained yesterday afternoon and have the checklist from the import that Joe shared to start going through. We've configured several filtered news lists across the site and are pleased with how it's going so far 👍
