### ISSUE TITLE
Site installs - Missing required data for configuration?

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#4729]
# Problem

```
 [notice] Missing required data for configuration: purge.logger_channels
 [notice] Missing required data for configuration: purge.plugins
 [notice] Missing required data for configuration: sitenow_events.settings
```

# Steps to reproduce
This is showing during site installs after our usual block content and moderation messages.

# Proposed solution
?

**Comment by joewhitsitt** [comment]
Related? https://www.drupal.org/project/config_ignore/issues/3168888

**Comment by richardbporter** [comment]
Can we close this as a dupe of #1914 ?
