### ISSUE TITLE
Re-factor headline field to use core block label and third party settings

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#4734]
# Motivation

A long, long time ago someone ([me?](https://github.com/uiowa/uiowa/blob/3a6ed834490cb0150098c6c2c151cf06943f34b1/docroot/modules/custom/layout_builder_custom/layout_builder_custom.module#L33-L34)) decided that we were going to hide the block label field and we have mostly never looked back. Then we started adding the headline field to various blocks. If left unset the block label gets automatically set and stored, so it seems like storing the additional headline field is just extra database storage for no particular reason. Additionally, we may be losing out on built-in block functionality that we could start to take advantage of.

# Proposed solution

- Re-factor content and custom blocks to display the block label field and use that as headline storage.
- Use `thirdPartySettings` (pending [this issue](https://www.drupal.org/project/drupal/issues/3015152) being resolved) to store the settings related to headline besides the headline itself.
- Allow block label to be shown in the block form.
- Account for Views blocks.

**Comment by joewhitsitt** [comment]
We noticed an issue with our block label customizations when evaluating big pipe: https://github.com/uiowa/uiowa/issues/4651#issuecomment-1024659550

**Comment by pyrello** [comment]
Dropping this here in case it is relevant: https://www.drupal.org/node/3191609

**Comment by briand44** [comment]
initially scope to a particular block type (text area?) but can expand to additional block types time permitting or in future.

**Comment by pyrello** [comment]
An idea for how this could work: Use the Form API to change the field type of the block title to the custom `headline` field that we created. We would need to provide the additional properties on the field that the field type expects. If we do that, it might "just work"!

This will need an update hook for any block definitions that get changed.

**Comment by pyrello** [comment]
First issue that I am finding that I will need to work around: The core block label field is required and core handles whether to display it as a title or not by including a checkbox to hide it. The presumption is that you will always be setting a block label, but that you can still choose whether to display it our not. By contrast, our headline field operates under the assumption that it is either filled in or not. If it is filled in, then a headline will render. If it is not filled in, then it will not render.

Potential solution: Emulate the headline behavior by continuing to hide the checkbox and then programmatically set its value based on whether the block label is empty or not.

**Comment by pyrello** [comment]
Updates:
- I was able to use our `HeadlineHelper::getElement()` to wire up the block label field to have the `headline` render array necessary for it to display correctly.
- However, when I used xdebug to look at the `$formState` object in a form submit handler, I cannot find any of relevant values being passed through.
- I looked in a form validation handler and also could not find any of the data related to the headline there either.
- It appears that the headline form values may be getting stripped out by a block form validation handler which is running prior to our own validation handler.
- This begs the question of how we would go about saving the values from the form.
- Some searching related to modification of block titles in the block form didn't turn up much, so I'm not seeing any examples of how other people might be doing something similar.
- It is possible that we could do this by overriding a block class or possibly the controller class that is processing the updates. However, this gets us into territory that I'm not sure that we want to get into.
- We could also potentially continue to hide the block title, keep the headline field, and then set the block title based on the headline field.
- However, since this would not simplify our setup, its not clear what value it would be providing unless we want to take another pass at whatever @richardbporter was working on here: https://github.com/uiowa/uiowa/issues/4651#issuecomment-1024659550
- I'm inclined to close this issue unless we find that we are in a situation where we need the block label functionality for some reason.

**Comment by joewhitsitt** [comment]
Outside looking in, but this slack thread from Higher-Ed Drupal makes it sound like it would be possible with an event subscriber and a custom base block template. Originally I didn't chime in on this thread because we weren't using the block title.

https://edudu.slack.com/archives/C19HGHTJR/p1629740140010500

**Comment by pyrello** [comment]
Thanks for the tip, @joewhitsitt! I looked into that. There were a couple things of note:
- Princeton is adding custom form fields for title settings using a form alter and then an event subscriber (`LayoutBuilderEvents::SECTION_COMPONENT_BUILD_RENDER_ARRAY`) to actually process the settings for use in rendering the block.
  ![Screen Shot 2021-08-26 at 8 32 42 AM](https://user-images.githubusercontent.com/709009/173870829-12e382d2-d27d-4951-8513-ac194f61b645.png)
- The [block_link_title](https://git.drupalcode.org/project/block_title_link/-/blob/1.1.x/block_title_link.module) module adds form elements to the block form explicitly in `third_party_settings` which means their storage gets handled automatically.
- The [inline_block_title_automatic](https://git.drupalcode.org/project/inline_block_title_automatic/-/blob/8.x-1.x/src/FormAlter.php) is doing something very similar to what we are doing by hiding the `label` and `label_display` from the block form, although in a novel way (using a FormAlter class implemented in a hook_form_alter function).

The main thing here seems to be that, to add extra field elements like this, they need to be added separately from the actual `label` field, rather than added to it. This is based on the fact that when I alter the existing label to field to turn it into a `'#type' => 'headline'` field, all the values besides the label value itself are stripped out. Another consideration is that we want the whole headline field to act as a single unit. So, either we add our separate fields using `third_party_settings` to have the setting stored correctly and then do some Form API ninjitsu to get it to render as a single unit, or we essentially have to have a dummy "title" field in our headline and then programmatically pass the value over to the block label.

I'm not opposed to doing this, but it still raises the same questions for me as to the value we are getting for the effort, especially since this will, in fact add additional complexity to our code rather than simplifying it, which was one of the original goals of this issue. I think I'm still in favor of letting this go for now and potentially revisiting it when we get to a point where the block title functionality is blocking something else, like getting `big_pipe_sessionless` working.

**Comment by joewhitsitt** [comment]
>but it still raises the same questions for me as to the value we are getting for the effort, especially since this will, in fact add additional complexity to our code rather than simplifying it, which was one of the original goals of this issue. I think I'm still in favor of letting this go for now and potentially revisiting it when we get to a point where the block title functionality is blocking something else, like getting big_pipe_sessionless working.

Thanks for poking at it and documenting this. Based on your findings, I agree that the benefit might not exist yet. Feel free to close.
