### ISSUE TITLE
Update Featured Image for Grad Admissions AoS

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#4740]
Admissions requested we update the default featured image for Areas of Study. The request was to use the same image that the undergrad admissions site is using.

**Comment by briand44** [comment]
Here is an example of how we handled this as part of the migration for undergrad Admissions.

https://github.com/uiowa/uiowa/blob/f5dcf5dfcba082f1a1d34e7455e24643d5eb2329/docroot/sites/admissions.uiowa.edu/modules/admissions_migrate/config/split/migrate_plus.migration.d7_admissions_aos.yml#L48-L50

Thanks @cory-skeers 

#4650

**Comment by richardbporter** [comment]
This is included in #4650. The pentacrest drone shot will be used by default for migrated AoS. There is no default value for new AoS, just like the admissions site.

**Comment by briand44** [comment]
Evidently we used the wrong image here. I believe the image they want is the same that is being used on https://admissions.uiowa.edu/academics/human-rights

**Comment by richardbporter** [comment]
My bad. This will need to be an update hook now, iterating all AoS, checking if the featured image equals FID 16 and updating it to the new photo if so. The new photo must exist in prod as a media item if it does not already.

**Comment by joewhitsitt** [comment]
Can we just replace the media file using the overwrite replace functionality and clearing all of the caches?

**Comment by richardbporter** [comment]
Ah yes maybe. It could be in use in other places besides AoS though. If they're ok with that, it'd be much faster.

**Comment by briand44** [comment]
Should we reach out in the admissions slack channel to see if they'd be ok with that approach or are we looking at usage to see if it is used in other places?

**Comment by richardbporter** [comment]
> Can we just replace the media file using the overwrite replace functionality and clearing all of the caches?

This is done.
