### ISSUE TITLE
diversity.uiowa.edu blank menu dropdown for adding a page to the menu

### ISSUE THREAD

**Issue by makurj** [uiowa/uiowa#4747]
When adding a new page, and checking "provide a menu link", the parent items dropdowns are blank. Noticed this on multiple browsers and OSes, and sites (diversity, tippie). User's info is:

Google Chrome Version 98.0.4758.80
Mac OS Monterey version 12.1

![image](https://user-images.githubusercontent.com/52135878/152374206-da0ac3c9-4c7f-4004-a249-e677b03ded39.png)

Reaching out to user with temporary workaround of saving the page and going back in to view the menu dropdowns, or add the page via structure to the menu.

**Comment by joewhitsitt** [comment]
though i see grammarly in the toolbar, historical cause of editor mayhem, my guess it is this: https://www.drupal.org/project/cshs/issues/3258226

**Comment by joewhitsitt** [comment]
I am encountering this as well... Brave [Version 1.34.81 Chromium: 97.0.4692.99]
