### ISSUE TITLE
Empty profile image not displaying 

### ISSUE THREAD

**Issue by bewoldt** [uiowa/uiowa#4748]
# Problem
The empty profile image is not being shown when using certain settings with the People component.

Image format: Circle
Image position: Stacked
Image size: Small
Display List as: Grid or List

<img width="690" alt="Screen Shot 2022-02-03 at 11 12 56 AM" src="https://user-images.githubusercontent.com/731952/152394130-117404fa-e674-427f-bccb-38447780d987.png">

Test page:
https://sandbox.prod.drupal.uiowa.edu/people-image-test

Tested on chrome, safari, firefox

**Comment by bspeare** [comment]
To fix this, we will need to revisit this line in https://github.com/uiowa/uids/blob/main/src/components/card/card.scss#L291-L292.
