### ISSUE TITLE
As a site owner, I can choose to visually hide the banner title in the banner block

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#4750]
# Story

As a site owner, I can choose to visually hide the banner title in the banner block so that I can create content with a background image and text area only.   

<img width="794" alt="Screen Shot 2022-02-03 at 1 47 48 PM" src="https://user-images.githubusercontent.com/1036433/152417975-2f8e2e1e-e503-4754-a74c-da7c5a60c9b0.png">

# Proposed solution
- [x] Make the banner title field not required
- [x] Add validation logic to provide a form error if neither the title nor link text are included.
- [ ] Use `#states` to set the required property on the link text field (if possible)

**Comment by bspeare** [comment]
If we remove the requirement from the banner block for the title, this turns the banner block into a background image and text area.   Examples below. 

<img width="1835" alt="Screen Shot 2022-02-21 at 12 28 55 PM" src="https://user-images.githubusercontent.com/1036433/155009905-21a1be08-3b30-4c48-8b32-b925a8e9e9f8.png">

<img width="1876" alt="Screen Shot 2022-02-21 at 12 28 04 PM" src="https://user-images.githubusercontent.com/1036433/155009891-1f87f5d8-d784-4f15-97f9-d8e087e29aed.png">

Do we want to turn the banner block into our section background image container?  Or should we try to figure out how to add background images to layout builder sections?  For example, what if we offered a "one column layout w/ background image" that was restricted to using a few custom block components like blockquote and text area?

**Comment by bspeare** [comment]
Here's an example of how Tippie wants to use the banner block without the headline.  It looks pretty good just using the blockquote in this example:

<img width="2101" alt="Screen Shot 2022-03-09 at 3 08 43 PM" src="https://user-images.githubusercontent.com/1036433/157536435-91594e09-44b4-4bb1-99cb-fc3105fb8933.png">

**Comment by makurj** [comment]
I would like to pair on this.

**Comment by bspeare** [comment]
After grooming this we decided to remove the requirement from the title field.

**Comment by bspeare** [comment]
Based on @dnkemper comment on https://github.com/uiowa/uiowa/pull/4989#issuecomment-1072468290, I guess we would either need to do one of the following things:

- Add help text under link saying that link field won't work without link title if title is empty
- Refactor banner.js to include this scenario
- Pursue a different background image approach (https://www.drupal.org/project/layout_bg)

I think this issue is blocked until we can figure what to do about the link.

**Comment by dnkemper** [comment]
Thank you, @bspeare!

**Comment by bspeare** [comment]
Here are a few thoughts suggested in Slack and standup this morning:

- Require link text if title is empty
- Add circle button
- Possibly wrap banner with link
- Pursue https://www.drupal.org/project/layout_builder_backgrounds which would could be a better approach for our blockquote component
  - Would need a specialized one column layout with options to:
    - Add and require overlay or gradient
    - Control gradient direction
    - Control component alignment within the layout section

**Comment by joewhitsitt** [comment]
Team is planning on discussing this before moving forward

**Comment by pyrello** [comment]
After another discussion on the subject, here is where we have landed for now:
* We will require link text if the title is empty. We might be able to handle this on the form with `#states` as `required` is a property that can be controlled that way.
* We'll need to add some validation logic to provide a form error should they somehow make it past our browser validation.
* We may want to consider adding a circle button to the banner in cases where there is a title and a link but no link text, similar to when we add it for cards: https://github.com/uiowa/uiowa/issues/5086

**Comment by pyrello** [comment]
I made an attempt at getting the `#states` option to work, but I was not able to figure it out. Seems like it is probably good enough without that.
