### ISSUE TITLE
UI Press - Implement tabs on book page

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#4759]
Fields that will be individual tabs:

- Reviews/blurbs
- Contributors
- Table of contents
- Excerpt
- Awards

Fields are going to have to be placed in a view to allow placement as a single item in Layout Builder.

Tabs section will go before Related Reads in the book content layout. 

- Implement tabs css and js from: https://github.com/uiowa/uids/pull/637
- Create a tabs library in `uids_base` like: https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/uids_base.libraries.yml#L80-L84
- Create a tabs template and possibly use existing tab template: 
  - https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/templates/paragraphs/paragraph--uiowa-collection-item--tab.html.twig

**Comment by joewhitsitt** [comment]
My mention of using collections as a base in grooming might be old news and not the best practice anymore. We did this for a few accordion implementations. https://github.com/uiowa/uiowa/search?l=Twig&q=collection--accordion
