### ISSUE TITLE
Update applications to PHP 7.2

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#477]
Everybody pick a site and test it. Document any issues here with a comment if you find any.

- [x] Dev
  - [x] uiowa701
  - [x] uiowa702
  - [x] uiowa703
  - [x] ICGov
  - [x] Dentistry
  - [x] Signage
  - [x] HC Signage
- [x] Stage
  - [x] uiowa701
  - [x] uiowa702
  - [x] uiowa703
  - [x] ICGov
  - [x] Dentistry
  - [x] Signage
  - [x] HC Signage
- [x] Prod
  - [x] uiowa701
  - [x] uiowa702
  - [x] uiowa703
  - [x] ICGov
  - [x] Dentistry
  - [x] Signage
  - [x] HC Signage

**Comment by briand44** [comment]
I've updated dev and stage to php7.2 for the applications listed above.

**Comment by richardbporter** [comment]
https://github.com/ITS-UofIowa/sitenow_custom_profile/pull/293
https://github.com/ITS-UofIowa/sitenow_custom_profile/commit/277d48793c4614e8d21ad62cfb62c9f92b13a88c

**Comment by richardbporter** [comment]
- [x] Create new release of standard profile

**Comment by briand44** [comment]
I will be testing the Pharmacy site.

**Comment by makurj** [comment]
I will watch out for issues on Tippie stage and dev.

**Comment by richardbporter** [comment]
Tested arts, dining, housing, catering. Had a fatal error on catering related to rules that required an RR.

**Comment by briand44** [comment]
I did some testing on Pharmacy. The migrations seemed to work and I didn't notice any glaring issues.

**Comment by joewhitsitt** [comment]
ITS seems to work fairly well. There were warning and notices which I believe can be resolve with some contrib module updates.

I am going to try poking around on Engineering tomorrow.

**Comment by joewhitsitt** [comment]
Engineering looks fine to me. I did a few panel pane operations with no issue.

**Comment by richardbporter** [comment]
Dentisty just needs to tell us when to make the switch. Code is updated in prod.
