### ISSUE TITLE
Adding a link to an image global caption is broken

### ISSUE THREAD

**Issue by dnkemper** [uiowa/uiowa#4774]
Adding a link to image's global caption errors out. 

## Steps to reproduce
1. add image
2. go to add a global caption
3. try to add a link to the global caption
4. try to save after adding link

**Comment by dnkemper** [comment]
When working on https://github.com/uiowa/uiowa/pull/4708, I found this bug. Double checked on prod so know it's not a photoswipe issue. Also not a text area block/body field etc bug, just a global caption issue.

**Comment by joewhitsitt** [comment]
Related #1157

**Comment by dnkemper** [comment]
THANK YOU, JOE!
