### ISSUE TITLE
Social Media Timeline Embeds

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#478]
## Problem
Our SiteNow Standard service currently provides Facebook and Twitter timeline blocks that users can configure/place using contrib modules. Our oEmbed implementation has taken a step back in functionality and doesn't handle timeline URLs (Twitter tweets and Facebook posts), so there is currently not a way to place timelines within the site.

https://www.drupal.org/project/twitter_block
https://www.drupal.org/project/fb_likebox

## Proposed Solution
Wait an oembed solution that plays nicely with our existing media entity based solution.

OR

Develop a paragraph bundle that takes in the configuration needed for these blocks and render the block programmatically within the paragraph?

OR

Otherwise, it might just be easier to grab the latest embed markup for these and alter the markup ourselves based on paragraph configuration (account, height) and set the remaining defaults for MVP.
https://publish.twitter.com
https://developers.facebook.com/docs/plugins/page-plugin/

OR

Revisit https://www.drupal.org/project/url_embed which does not create file/media entities, but doesn't appear to have a maintainer or a way to restrict providers. This one is for @briand44. 😁

OR

Stay in the business of placing these widgets and countless others for customers in a new full_html wysiwyg area. The one nice thing is that it can stay locked to editors in an isolated paragraph item alongside other content that they can move around (even duplicate) instead of locking editors completely out of the page.

**Comment by joewhitsitt** [comment]
Based on a usability study I saw _:cough:_, users tended to look to see if the website had a social media presence that the user prefers and clicked the link to view the social media activity on the external site or app instead of scrolling and viewing the timeline on the website.

Personally, I also feel that these timelines are often blocked by "do not track" browser settings, extensions, increase load time, are typically inaccessible, don't blend well into the web design and take up a lot of real estate.

So even though I don't like moving forward with this, IF we did move forward with this, I like the oembed solution. Ideally, the backend UX for it would be so hidden only power users would really use it.

**Comment by joewhitsitt** [comment]
One more option I thought of, but don't love, is to stay in the business of placing these for folks by creating a full_html wysiwyg option again. It is a little more flexible than our D7 where we only had one body field or something to work with, but now could just be a paragraph text area among a sea of other content that they can control.

**Comment by joewhitsitt** [comment]
Indirectly working towards this with #776. Would need follow-up docs for developers to place (making sure a height is set), and site owners about how to request placement with refs to accessibility/security.

![localhost_8888_about](https://user-images.githubusercontent.com/4663676/69462482-bc822280-0d3e-11ea-84ca-bccd66873739.png)

**Comment by joewhitsitt** [comment]
I have been told we don't want to be in the business of placing embeds for folks. full_html will be there as an option but isn't a service we offer.

**Comment by joewhitsitt** [comment]
Discussed at the dev meeting. Sounds like people are coming around to full_html, possible embedly type service down the road, and a big giant FAQ telling people why we are currently not supporting it.

**Comment by joewhitsitt** [comment]
Added an FAQ for this.
