### ISSUE TITLE
Switch column order for Admissions events in mobile

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#4782]
# Story

As an Admissions site owner, I would like to see event registration information display higher in mobile order on events to help get more registrations.

# Proposed solution

- Create a layout builder style called something like "Reverse column order for mobile" which would which would apply class like `.section-order__reversed`.
- In `global.scss` create the class and style that will be applied in the layout builder style like:

```
.section-order__reversed {
  // two column
  &.layout--twocol {
    .layout__spacing_container {
      display: grid;
      @include breakpoint(sm) {
        display: inherit;
      }

      .layout__region--first {
        order: 2;
        @include breakpoint(sm) {
          order: inherit;
        }
      }

      .layout__region--second {
        order: 1;
        @include breakpoint(sm) {
          order: inherit;
        }
      }
    }
  }
}
```
- Apply layout builder style to the event content type config here https://github.com/uiowa/uiowa/blob/main/config/features/event/core.entity_view_display.node.event.default.yml#L81.

**Comment by bspeare** [comment]
Related issue: https://github.com/uiowa/uiowa/issues/2737.

**Comment by makurj** [comment]
I would like to pair on this.

**Comment by dnkemper** [comment]
Alright, to give ya a heads up on what I did so far with this:
1. Created lb style: 'Reverse column order for mobile'
2. Added style to events: https://github.com/uiowa/uiowa/pull/4867/files#:~:text=0%3A%20section_order_reversed
3. added scss Ben added to issue

**Comment by makurj** [comment]
Perfect timing! I was just about to ask you what all is left :) Test, export split?

**Comment by dnkemper** [comment]
Right before I abandoned it, it didn't seem like the expected styling was correctly applying/working
Like you can see the section order reversed style in the template but not the corresponding styles that were added?

**Comment by makurj** [comment]
Is there an example page I can use for testing? First time working on admissions, flying in the dark here :)

**Comment by bspeare** [comment]
This one? https://admissions.uiowa.edu/event/next-step-iowa-admitted-student-days-0

**Comment by makurj** [comment]
Thanks!

**Comment by makurj** [comment]
@dnkemper already got everything done. `blt frontend` for me made the registration section show up at the top for mobile. 
![image](https://user-images.githubusercontent.com/52135878/156215682-05e2fd3c-d268-47b8-979e-aed0ae33596f.png)

**Comment by joewhitsitt** [comment]
spacing looks tight between those. can that be padded a bit?

**Comment by makurj** [comment]
I was wondering about that too. Will add some and see how it looks.

**Comment by makurj** [comment]
![image](https://user-images.githubusercontent.com/52135878/156218350-6289f1ee-577b-4e4e-92a5-945a87ce8b89.png)
