### ISSUE TITLE
Create custom cache tag for sitenow_events block render

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#4786]
First slice of #4651. Should be investigated first to make sure it is doable. 

https://www.drupal.org/docs/drupal-apis/cache-api/cache-tags

### Proposed solution
Add `time:hours_3` cache tag in `sitenow_events_preprocess_block` to block render. Push to dev and test Varnish cache is cleared when tag is purged manually with `drush @mysite.dev pinv tag time:hours_3` for pages that the events view is placed on. Inspect response headers to verify cache clear. Bonus points for testing an update to an event is displayed after tag is purged.

**Comment by briand44** [comment]
Start with every 3 hours and we can lower if still an issue.

**Comment by briand44** [comment]
May be a blog post referenced in the epic that could be useful.

**Comment by briand44** [comment]
cache tag name ideas welcome

**Comment by dnkemper** [comment]
have free time on my hands, feel like everyone is busy doing their own thing. I learn how to do new things through google (excellent tool) and def can't decipher this without working on events before. My brain is trying to apply this to sitenow_events_load instead of sitenow_events_preprocess_block? Gonna take step back and focus on others things.

**Comment by joewhitsitt** [comment]
going to start looking at this. will start a huddle for those interested

**Comment by joewhitsitt** [comment]
Might see about creating some events for web community (e.g. demo), getting a block cached in dev, updating the event, triggering invalidation and seeing what happens.

**Comment by richardbporter** [comment]
> Might see about creating some events for web community (e.g. demo), getting a block cached in dev, updating the event, triggering invalidation and seeing what happens.

You could also override the sitenow_events.settings endpoint config to point at the dev or stage content hub site.

**Comment by joewhitsitt** [comment]
So I think something is missing from this. Created an event (thanks Digital Signage unit). Got it pulled into https://default.dev.drupal.uiowa.edu/ as cached. Change the title to just be `Web Team Sprint Demo` instead of prefixed with OSC. I ran `drush @default.dev pinv tag time:hours_3` and didn't see a change.

Originally, I thought the custom cache tag on the block would be more of flag to then query the page where these are placed on and invalidate one of their tags.

**Comment by richardbporter** [comment]
> So I think something is missing from this. Created an event (thanks Digital Signage unit). Got it pulled into https://default.dev.drupal.uiowa.edu/ as cached. Change the title to just be `Web Team Sprint Demo` instead of prefixed with OSC. I ran `drush @default.dev pinv tag time:hours_3` and didn't see a change.
> 
> Originally, I thought the custom cache tag on the block would be more of flag to then query the page where these are placed on and invalidate one of their tags.

Did you do all that in under 5 minutes? :) 
https://github.com/uiowa/uiowa/blob/de472bd53e4a95b3b4932ed58a99de61fd3c781c/docroot/modules/custom/sitenow_events/sitenow_events.module#L301-L305

**Comment by joewhitsitt** [comment]
>Did you do all that in under 5 minutes? :)

D'oh!

Update: changed the title again. Going to sit for a bit.

**Comment by joewhitsitt** [comment]
Welp. It gets varnish to miss but looks like drupal cache is still a hit with this.

<img width="904" alt="Screen Shot 2022-02-16 at 2 30 40 PM" src="https://user-images.githubusercontent.com/4663676/154353592-f8006cc1-08bf-49c1-bd08-82972f739730.png">
<img width="997" alt="Screen Shot 2022-02-16 at 2 31 26 PM" src="https://user-images.githubusercontent.com/4663676/154353604-a94afe58-c677-431a-9073-7a925bab5810.png">

**Comment by richardbporter** [comment]
Hm. Yea I can replicate this locally...

**Comment by joewhitsitt** [comment]
Between content.uiowa.edu (10 min) and the query cache (5 min), we are looking at about 15 minutes. Going to sit for a bit longer and test again.

**Comment by joewhitsitt** [comment]
Bummer. As-is, waiting longer didn't work. Something else is wrong with this block's caching. Trying some things locally since drupal cache seems to be in the way

**Comment by joewhitsitt** [comment]
i want to say that throwing a max-age 0 in there as well has solved our problems... but at what cost?

**Comment by joewhitsitt** [comment]
i wonder if single event (docroot/modules/custom/sitenow_events/src/Controller/EventsController.php) will need this too

**Comment by richardbporter** [comment]
So I'm seeing updates to events without the `max-age` change in #4818 - I commented out/removed those just for now. I'm wondering if someone can try this locally:

- Sync a site and change the sitenow_events endpoint to dev `drush @mysite.local cset sitenow_events.settings base_endpoint 'https://content.dev.drupal.uiowa.edu/api/v1/'`.
- Create a page with an Events block filtering by Digital Signage department. That should display the event https://content.dev.drupal.uiowa.edu/node/82386.
- Save that page and view it to make sure uievents cache is set.
- Change the title and/or other fields on https://content.dev.drupal.uiowa.edu/node/82386. 
- Wait ~2 minutes or so.
- Refresh the page and see the event displays the changes.

I reduced the dev content hub and uievents cache time to 1 minute to make testing a bit easier. I don't think the purge functionality is working correctly on content hub so waiting for the max-age to expire is required. Also, it seems like the APE alt cache time functionality does not work on content hub and/or D7 in general. I changed the default cache time to 1 minute on dev.

**Comment by joewhitsitt** [comment]
i can try this. thanks for continuing to poke at this. might as well assign yourself ;)

**Comment by joewhitsitt** [comment]
Locally that worked

**Comment by richardbporter** [comment]
> Locally that worked

Great, thanks for confirming. I'd be interested in seeing if that then works in combo with the cache tag purge in dev. Looks like that is on its way...

**Comment by richardbporter** [comment]
Saw the update very quickly while logged in. Did not see it after purging cache tag, URL or full domain via AC. I had to purge tag and cc render to get it to show. :(

**Comment by richardbporter** [comment]
Not working with max-age 60, at least not for me. I'm not sure why that wouldn't work and max-age 0 would. Maybe because there still is nothing to invalidate the render cache and max-age 0 prevents the render cache in the first place? I guess lets roll with max-age 0 if that worked and page cache is still set.

**Comment by joewhitsitt** [comment]
Did you re-save the block after pushing that up?

**Comment by richardbporter** [comment]
No

**Comment by richardbporter** [comment]
I have reduced the content hub prod page cache time to 5 minutes.
