### ISSUE TITLE
As a site editor, I can choose to hide the circle arrow button on the card block

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#4788]
# Story

As a site editor, I can choose to hide the arrow button on the card block if I don't want to have an arrow display below the card. 

Scott has mentioned that the arrows are useful, but it would be handy to turn them of in some situations.  Like on this "Contact Us" page: https://admissions.uiowa.edu/contact-us.

<img width="1502" alt="Screen Shot 2022-02-09 at 4 01 42 PM" src="https://user-images.githubusercontent.com/1036433/153297541-f396ca87-a532-4c4a-8354-6926d033d438.png">

# Proposed solution

- [x] - Introduce a separate settings page for layout builder block specific settings (code can live in layout_builder_custom for now).
- [x] - Similar to Featured Image settings, provide a global Show/Hide setting for card link visual indicators with help text explaining the functionality.
- [x] - We change the card field to be an options list: "Use site default", "Show", "Hide". We default this to "Use site default". Help text needs to be specific with the functionality here. Same #states logic would exist: If the card link field contains a url and the link title field is empty show a checkbox option to hide the circle button.
- [x] - Our update hook to update existing card blocks would set this field to the same default value "Use site default".

**Comment by makurj** [comment]
I would like to pair on this.

**Comment by makurj** [comment]
Would this be for just admissions or the platform?

**Comment by joewhitsitt** [comment]
I think we should shoot for platform-wide on this to start

**Comment by makurj** [comment]
Would the changes be made here: `docroot/themes/custom/uids_base/templates/uids/card.html.twig` or `docroot/themes/custom/uids_base/templates/block/block--inline-block--uiowa-card.html.twig?`

**Comment by joewhitsitt** [comment]
...templates/block.. remember the uids folder is not tracked it uiowa git but is imported from uids.

**Comment by makurj** [comment]
Perfect! The if statements in `docroot/themes/custom/uids_base/templates/uids/card.html.twig` were throwing me off. Thanks, Joe!

**Comment by pyrello** [comment]
I'm not sure I agree with the logic of the update hook to set the button to be active for all existing cards. The behavior before we introduced this feature is that no cards had the button. I don't think that we should assume that everyone wanted those cards to have the indicator link. I'm cool with setting new cards blocks to have this option by default, but I'm not sure that is the right move for existing blocks.

**Comment by joewhitsitt** [comment]
@pyrello the buttons are on by default currently: https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/templates/block/block--inline-block--uiowa-card.html.twig#L56

**Comment by pyrello** [comment]
> @pyrello the buttons are on by default currently: https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/templates/block/block--inline-block--uiowa-card.html.twig#L56

Understood. But that condition might be viewed as a mistake that we made in rolling it out without allowing folks to opt out. We can't clearly interpret people's intentions at this point, so my argument is that we should fall back to the original condition and let people opt out moving forward.

**Comment by joewhitsitt** [comment]
I think I figured out the update hook if we are staying the course. Allowing people to opt-out going forward is the main purpose of this issue. By not updating existing, it is a flip-flop and we are causing a visual regression (percy too) that forces users to go in and modify existing content.

**Comment by pyrello** [comment]
> By not updating existing, it is a flip-flop and we are causing a visual regression (percy too) that forces users to go in and modify existing content.

We created a visual regression when we released this feature in the first place, but there was no way for users to go in and change it. Why would we assume that everyone was just cool with the change and that it represents what they want?

**Comment by bspeare** [comment]
To recap, @joewhitsitt would like to keep the arrow set by default in the update hook and @pyrello is advocating for removing it?  I agree that setting it by default was a little heavy-handed and I like the idea of resetting that in the update hook.

**Comment by cory-skeers** [comment]
My main thoughts here are that while we did force the change on all cards previously, and it could have been viewed as a regression, we're in a similar spot now for anyone who may appreciate the additional arrow.

Defaulting to the arrow:

- Cards that didn't want the arrow were previously forced to have it, and will continue to have it but have the option to remove it
- At least some cards want the arrow, got it by default, and no change needed

Defaulting to no arrow

- Cards that didn't want the arrow forced to have it, and are fixed
- Cards that want the arrow are forced to have it removed, but have the option to re-add it

In my view defaulting to no arrow at this point is forcing another visual change that may not be desirable on at least some set of cards, whereas defaulting to arrow on keeps things visually consistent with the way things are now (albeit not with what may have been the original intent, which we don't have a reliable way to know).

BUT that being said, I don't have a solid read on whether users would like the arrow on a majority of their cards or not, and insight there could sway me. I'm looking at it from the case where either option is equally desired across all sites.

**Comment by joewhitsitt** [comment]
>like to keep

not sure i am saying that. my only concern is changing an established pattern that is now six-months in.

**Comment by makurj** [comment]
I agree with not removing it by default as users have gotten used to it and this would maintain visual consistency.

**Comment by GaryRidgway** [comment]
While I personally, If i had a website, would want to have current arrows default to off, I think this comes down to a matter of users already getting used to it. I think rolling it back to default-off becomes less and less reasonable the further away from the release of the original arrow we get, so ultimately i think we should keep the arrows on. As much as it makes me grumbly.

**Comment by pyrello** [comment]
It seems like we are split, with more people favoring continuing the existing pattern as a the default. If that is the will of the group, I continue to disagree that that is the right approach, but I concur with moving ahead that way.

It is possible that there is a way to resolve this in a more satisfactory way, although it would involve increasing the scope and delaying its deployment.

Here is the idea:
- We create a global setting for the default behavior for card block arrows. We initially set this to "Show" which is consistent with what people have gotten used to over the last 6+ months since the feature was launched.
- We change the card field to be an options list: "Use site default", "Show", "Hide". We default this to "Use site default".
- Our update hook to update existing card blocks would set this field to the same default value "Use site default".

This is similar to how we handled the rollout with different featured image options. By having the global default as the default on each card block, if someone was unhappy with the arrows showing up, they can turn them off en masse. If they enjoyed them, they don't need to do anything. We don't need to try to figure out what people wanted or didn't want, we just give them an easy option to "fix" it without having to potentially go through and edit hundreds of cards.

**Comment by bspeare** [comment]
@pyrello I like this idea.   How would this integrate with the card arrows we are offering for articles list?

<img width="916" alt="Screen Shot 2022-06-15 at 10 38 59 AM" src="https://user-images.githubusercontent.com/1036433/173868812-afeb9282-60d7-4ef0-b0b8-5433c07ee23d.png">

**Comment by pyrello** [comment]
>@pyrello I like this idea. How would this integrate with the card arrows we are offering for articles list?

I think it would be a separate setting. It seems reasonable that you could set different options for card blocks vs. article lists.

**Comment by joewhitsitt** [comment]
Yeah, since work was already done related to this for content card teasers, I can get behind this additional setting.

**Comment by makurj** [comment]
Is the additional setting something we're doing in this PR or another one?

**Comment by joewhitsitt** [comment]
This would change the existing PR. Almost replaces the entire thing because we would be moving from a boolean to a select list

**Comment by makurj** [comment]
Got it! I switched it to draft and will start on the select list.

**Comment by makurj** [comment]
Should I create a brand new module called sitenow_blocks with SettingsForm.php?

**Comment by pyrello** [comment]
I think we can put this in an existing module, possibly `layout_builder_custom`.

**Comment by joewhitsitt** [comment]
Captured the proposed solution from https://github.com/uiowa/uiowa/issues/4788#issuecomment-1156609064

**Comment by pyrello** [comment]
> Captured the proposed solution from https://github.com/uiowa/uiowa/issues/4788#issuecomment-1156609064

Thanks for taking care of this, @joewhitsitt!
