### ISSUE TITLE
Upgrade to Drush 11

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#4789]
Second slice of #4651 for events option 2.

### Proposed solution
Check release notes: https://github.com/drush-ops/drush/releases and issue queues for any gotchas. BLT issue queue as well.

Try requiring it in Composer and see what needs updating also. This probably needs updating: https://github.com/richardbporter/drush-users-commands Our custom commands might as well in https://github.com/uiowa/uiowa/blob/main/drush/Commands/UiowaCommands.php

After updating, test out custom Drush commands, BLT commands that make use of Drush, deploy to dev and test there, etc.

**Comment by richardbporter** [comment]
Blocked by https://github.com/acquia/blt/pull/4465

**Comment by richardbporter** [comment]
Actually, there is some other work to be done here.

**Comment by joewhitsitt** [comment]
>Actually, there is some other work to be done here.

Not sure what other issues were blocking this but it looks like some issues were resolved and a new release was created: https://github.com/acquia/blt/releases/tag/13.3.0

**Comment by pyrello** [comment]
We discussed this in grooming and would like to get @richardbporter's take on this issue before moving forward with it.
