### ISSUE TITLE
WSOD on https://education.uiowa.edu/beateacher

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#4792]
`Error: Call to a member function getFileUri() on null in docroot/modules/contrib/photoswipe/src/ImageDTO.php on line 11`

**Comment by dnkemper** [comment]
Note: Had to install colorbox to sync this down locally 🤔

**Comment by dnkemper** [comment]
Once I ran 'composer require drupal/colorbox' and synced the site, that page displays without errors.

**Comment by richardbporter** [comment]
> Once I ran 'composer require drupal/colorbox' and synced the site, that page displays without errors.

Tried that but no dice for me.

**Comment by dnkemper** [comment]
OOOHHH! I'm on lazy branch? https://github.com/uiowa/uiowa/pull/4781
1. git checkout photoswipe-lazy
2. composer require drupal/colorbox
3. add this to photoswipe patches for fun "sdfsd": "https://git.drupalcode.org/project/photoswipe/-/merge_requests/18.diff"
3a. Was issue you pointed to during planning
4. composer install
5. blt ds --site=education.uiowa.edu
