### ISSUE TITLE
Re-organize menu_block settings to make them easier to understand

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#4794]
# Proposed solution

Continue the work in https://github.com/uiowa/uiowa/pull/4667, and make these changes:

-  [x] Find a way to unset the "Fixed parent item" if "Make the initial visibility level follow the active menu item" is checked when the block is saved. 
-  [x] Find a way to reset the "Initial Visibility" level to `2` if "Make the initial visibility level follow the active menu item" is checked when the block is saved. 
- [x] Update and reorganize form display so the show/hide makes sense
- [x] Update the "main navigation" block under the "more.." option in layout builder to have the same settings that are provided through the block placed on the page. 
- [x] ~Test that everything is still working with our custom logic to hide "depth" setting and automatically set that value to `1` when "Horizontal" is selected.~ We decided to allow the depth setting to be used for both menu types in anticipation of #4823. 
- [x] Write test to assert that fields we have hidden in custom code are not showing up on the menu block form.

**Older partially completed and outdated solution:**
<details>
- [x]  Check the [`menu_block` issue queue](https://www.drupal.org/project/issues/menu_block?version=any_8.x-) to see if there is any upstream work going on to re-organize the form in a way that makes sense. If there is, these suggestions may need to be adjusted to reflect that work.
- [x] Validate that "Make the initial visibility level follow the active menu item." option essentially overrides anything that is set for "Initial visibility level" and "Fixed parent item" (See comments below).
- [ ] Move this section of the form into or before the Menu levels section:
  <img width="456" alt="Screen Shot 2022-02-09 at 11 01 36 AM" src="https://user-images.githubusercontent.com/709009/153251353-12dce299-534c-46db-9a3b-1dc6c90c9fef.png">
- [x] "Make the initial visibility level follow the active menu item." should be checked by default.
- [x] Decide which of the radio buttons should be the default and make it so: "Active menu item" or "Children of active menu item"
- [x] If "Make the initial visibility level..." is checked, hide "Initial visibility level" and "Fixed parent item" options.
- [X] ~Probably just get rid of the "Advanced options" details section because it doesn't really help the form to break the options up that way.~ Renamed this to "Visibility options" instead.
</details>

**Comment by cory-skeers** [comment]
> * Check the [`menu_block` issue queue](https://www.drupal.org/project/issues/menu_block?version=any_8.x-) to see if there is any upstream work going on to re-organize the form in a way that makes sense. If there is, these suggestions may need to be adjusted to reflect that work.

Checked out the issue queue, and didn't see any current issues re: organizing the form.

**Comment by joewhitsitt** [comment]
> Decide which of the radio buttons should be the default and make it so: "Active menu item" or "Children of active menu item"

I believe the reason we adopted menu_block in the first place was for it to follow the children and is the defaultConfiguration for the module https://git.drupalcode.org/project/menu_block/-/blob/8.x-1.x/src/Plugin/Block/MenuBlock.php#L369

**Comment by bspeare** [comment]
I'm currently looking into the second checkbox on this issue.

**Comment by bspeare** [comment]
> Validate that "Make the initial visibility level follow the active menu item." option essentially overrides anything that is set for "Initial visibility level" and "Fixed parent item".

After testing this on a few sites, I don't think "Make the initial visibility level follow the active menu item" overrides the other settings.  Adjusting the "Fixed parent item" seems to cause the most havoc which I have documented below in a `<details>`.    Based on the details below, I would recommend that we completely hide the "Fixed parent item" section.  I'll provide a follow-up comment on if we might want to use "Initial visibility level" with "Make the initial visibility level follow the active menu item."


<details>

## Pros of fixed parent item:
- Live layout builder preview that is correct
- Ability to set random menu on pages that have no relationship to active or children
## Cons of fixed parent item:
- Live layout preview is broken if used with "Initial visibility level will be" section
- Sometimes needs the initial visibility level for `1` in order to work properly
- Requires menu to be selected on each page

## Additional notes
- Using the fixed parent item instead of the "Initial visibility level will be" section does generate a live layout builder preview. 
- Using the fixed parent item and the "Initial visibility level will be" section generates an incorrect live layout builder preview unrelated to a visibility level of `1` as noted in the screenshots below. 
- The fixed parent item sometimes needs the initial visibility level for `1` in order to work properly.  If you are selecting a fixed parent items a few levels in, you need a visibility level of `1` set in order to see your choice (See screenshot below).
- The live layout builder preview provided by the fixed parent item settings is nice, but configuring that section requires extra work selecting specific menus for each page. 

### Example where  fixed parent item needs initial visibility level of `1`:

<img width="1565" alt="Screen Shot 2022-02-14 at 11 47 45 AM" src="https://user-images.githubusercontent.com/1036433/153918471-998356dd-dd6b-4f36-996c-4290342e2d3b.png">

### Here's a screenshot of a live preview generated using the "fixed parent item" on the education site:

<img width="1406" alt="Screen Shot 2022-02-14 at 11 23 07 AM" src="https://user-images.githubusercontent.com/1036433/153915857-eb46c558-deab-4b2f-b599-2a393ebdfd1b.png">

### And here's what it looks like saved:

<img width="1425" alt="Screen Shot 2022-02-14 at 11 23 22 AM" src="https://user-images.githubusercontent.com/1036433/153915886-7560d251-1e8b-4edc-a4d4-655e84a91143.png">



</details>

**Comment by bspeare** [comment]
The "make the initial visibility level follow the active menu item" does seem to override or do the same thing as the "Initial visibility level."  Because of this, I think we should hide the initial visibility level for all options, and set to `2` by default.   Setting initial visibility level is useful for the "Fixed parent item" but it appears that you can accomplish the same through using "Children of active menu item" checkbox.

Regarding @pyrello's suggestion to "Move this section of the form into or before the Menu levels section", I'm not sure if we need to move the sections around, I think hiding a few of the options and renaming the "Advanced options" toggle would provide better clarity.  Renaming the "Advanced options" to "Visibility options" and keeping it closed by default also helps keep the form free of clutter if someone just wants to switch between the `Horizontal` and `Vertical` options without changing the defaults. 

<details>
## Proposed `Vertical` options:

<img width="494" alt="Screen Shot 2022-02-14 at 12 41 22 PM" src="https://user-images.githubusercontent.com/1036433/153926316-0c27e4d2-72bd-4dd4-8433-56d5540beddd.png">

## Proposed `Horizontal` options:

<img width="496" alt="Screen Shot 2022-02-14 at 12 41 42 PM" src="https://user-images.githubusercontent.com/1036433/153926391-7b3e9ad6-c96c-40e8-9527-de1288b1caf7.png">
</details>

**Comment by bspeare** [comment]
> I believe the reason we adopted menu_block in the first place was for it to follow the children and is the defaultConfiguration for the module https://git.drupalcode.org/project/menu_block/-/blob/8.x-1.x/src/Plugin/Block/MenuBlock.php#L369

For some reason, the default radio is not being set.  This is an issue outside of the work happening in https://github.com/uiowa/uiowa/pull/4667.   You can test it out by adding a new page and then editing the navigation block through layout builder.

**Comment by joewhitsitt** [comment]
>For some reason, the default radio is not being set.

I wonder if the schema for it wasn't updated at the time we saved those blocks to config. https://www.drupal.org/project/menu_block/issues/3022011

I wonder what would happen if those blocks were resaved now that we are on 1.7 https://github.com/uiowa/uiowa/pull/4667/commits/8471e544d474f2711ff59c7722caf88d1afa11ce

**Comment by bspeare** [comment]
It looks like Nursing is using every option that we are looking to hide, does that mean we add an access check and continue to allow all admins access to these fields?

<details>
<img width="629" alt="Screen Shot 2022-02-15 at 9 57 35 AM" src="https://user-images.githubusercontent.com/1036433/154099433-46d67ca4-0fdd-401f-87bd-08440d0d614f.png">
</details>

**Comment by joewhitsitt** [comment]
I can start an email thread to understand the use-cases

**Comment by bspeare** [comment]
> I can start an email thread to understand the use-cases

Sounds good, I think they can accomplish they same thing through the settings we will be offering.   Do we need to offer to go in and adjust every page?

**Comment by bspeare** [comment]
We met with Sam today and it looks like they have a need for the "Fixed parent item" functionality.  So for now we are going to allow access to that for the admin role only.    In a `<details>` below, here's how the form will appear for webmaster and editors:

<details>
**Vertical** 

<img width="483" alt="Screen Shot 2022-02-15 at 4 36 20 PM" src="https://user-images.githubusercontent.com/1036433/154161460-5c004751-c59b-45f3-b299-f5c7d79aa6c7.png">

**Horizontal** 

<img width="481" alt="Screen Shot 2022-02-15 at 4 36 13 PM" src="https://user-images.githubusercontent.com/1036433/154161471-bd15dc30-5e40-48c9-aeef-ab75f83e3775.png">

</details>

**Comment by bspeare** [comment]
@joewhitsitt I forgot that will still need to figure out https://github.com/uiowa/uiowa/issues/4794#issuecomment-1039636009.   Do you have time to look at that today?

**Comment by joewhitsitt** [comment]
Yeah, I can pull it down and see if I can make it stick

**Comment by joewhitsitt** [comment]
@bspeare does that look correct to you or did I mess it up? https://github.com/uiowa/uiowa/pull/4667/files#diff-c9334b7b9603dd84a065e5bc14db7aed09f961a74b411c0c4a00d50c9dfe43ad

update: looks like i messed it up. working on fixing it

**Comment by bspeare** [comment]
@joewhitsitt It looks you fixed it, thanks!

**Comment by bspeare** [comment]
Added the blocked label until we hear back from Nursing on their custom menu implementation.

**Comment by bspeare** [comment]
After learning about the menu direction that Tippie would like to pursue, it seems like there are three types of menus that a webmaster might want to create with the menu settings.  I've documented the three types below in a `<details>` below for reference. 

<details>

**1. Persistent/fixed menu**
- This is the type of menu that Tippie would like for their site. 
- Every page in a section sets a fixed parent item and the exact same menu displays on all the pages within the section.
- Needs access to "Initial visibility level" to get persistent nav to show based on the depth of the menu. 
- This option will display a live preview in layout builder

In the movie below, the "Iowa MBA" section menu appears on all pages displaying the same menu on every page in the section using the settings above.

https://user-images.githubusercontent.com/1036433/154571177-6cfedc61-56a3-4d66-be2c-2d12e47098aa.mov

**2.  Make the initial visibility level follow the active menu item (Children of active menu item)**
- This is the SiteNow default (Children of active menu item) selected. 
- Only needs access to “make the initial visibility options” checkbox
- Initial visibility level `2` is a good fixed default. 
- Needs access to "Number of levels to display"
- The "Children of active menu item" will display child pages
- This option will not display a live preview in layout builder

In the movie below, the menu will only appear in the "Iowa MBA" section if the page has child pages:

https://user-images.githubusercontent.com/1036433/154571558-f9fd248c-7b4f-488c-970e-5887238d9773.mov

**3.  Make the initial visibility level follow the active menu item (Active menu item)**
- This will display sibling pages
- Only needs access to “make the initial visibility options” checkbox
- Initial visibility level `2` is a good fixed default. 
- Needs access to "Number of levels to display".
- This option will not display a live preview in layout builder.

In the movie below, the menu only appears in the "Iowa MBA" section if the page has sibling pages:

https://user-images.githubusercontent.com/1036433/154572530-cf59ea3e-00b7-4c66-88a4-5d6b321581f2.mov

</details>

**Comment by bspeare** [comment]
After grooming this today we discussed that:
- Move forward with the current configuration in https://github.com/uiowa/uiowa/pull/4667. 
- Find a way to unset the "Fixed parent item" if "Make the initial visibility level follow the active menu item" is checked when the block is saved. 
- Find a way to reset the "Initial Visibility" level to `2` if "Make the initial visibility level follow the active menu item" is checked when the block is saved.

**Comment by pyrello** [comment]
I'm interested in working on this if it gets pulled in before I get a chance to do it myself.

**Comment by pyrello** [comment]
Chatted with @bspeare a little bit about this yesterday. Here were a couple salient points:

> * Find a way to unset the "Fixed parent item" if "Make the initial visibility level follow the active menu item" is checked when the block is saved.
> * Find a way to reset the "Initial Visibility" level to 2 if "Make the initial visibility level follow the active menu item" is checked when the block is saved.

We don't need to do this in the form. We can just set the appropriate values in the form submit handler.

Ben also indicated that the default settings in a new menu block don't match our defaults when a new page is created. Defaults when a new page is created are what we want. These changes will be handled in our `layout_builder_custom_form_alter` section related to the menu block.

**Comment by pyrello** [comment]
My proposed list of test for menu block:
```
// @todo Test menu orientation field is showing only once.
// @todo Test parent field is hidden when follow is checked.
// @todo Test initial visibility field is hidden when follow is checked.
// @todo Test text 'Make sure that "Initial visibility level" is set to "1"
//   below.' is showing.
// @todo Test 'Visibility options' is showing and not 'Advanced'
// @todo Test label_type field is not rendered.
// @todo Test label_link field is not rendered.
// @todo Test follow description is not shown.
// @todo Test that depth options are 1-3.
// @todo Test that expand_all_items field is not rendered.
// @todo Test that style field is not rendered.
// @todo Test that follow is set to 1 if the add block form is being used.
```
I suggest that for this first implementation, we implement a test that checks that fields are not rendered where `'#access' => FALSE` has been set.
