### ISSUE TITLE
UI Press - Create "view cart" button to appear in the top nav or top links

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#4797]
# Story

As a UI Press customer, I can see a persistent "View cart" button in the top navigation. 

<img width="1473" alt="Screen Shot 2022-02-10 at 3 58 58 PM" src="https://user-images.githubusercontent.com/1036433/153503673-a8825ddd-7b3f-41e3-bc24-d8c232a90509.png">

# Proposed solution

- https://github.com/uiowa/uiowa/issues/2873?
- Create custom block for uipress_core?
- Add the ability to select font awesome icon and add a custom class to a link in the main navigation?

**Comment by joewhitsitt** [comment]
was top-link not an option?

**Comment by bspeare** [comment]
Top link could be a good location too.

**Comment by bspeare** [comment]
Asked the brand team their preference on this and they thought that it will be more visible if it is in the main navigation region.

**Comment by briand44** [comment]
Use menu item, scope it to UI Press only
