### ISSUE TITLE
Update url for mbhd2020.centerforconferences.uiowa.edu

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#4803]
This is a SiteNow v1 site. The conference is in May 2022 and the site will be able to be removed in June 2022. Wanting to update the url to represent 2022 rather than 2020.

Sounds like we don't have a v1 provision process anymore so we likely will just route the new url manually rather than provisioning a new site and syncing db and files.

**Comment by briand44** [comment]
This is blocked while we wait to hear back on some url questions.

**Comment by briand44** [comment]
This is no longer blocked. The customer would like to move forward with mbhd.conference.uiowa.edu.

Also, they want to send mass communication about this at the end of the week so they are hoping this can get done this week.

**Comment by briand44** [comment]
We should communicate with them before we begin this process.

**Comment by briand44** [comment]
CNAME has been requested.

**Comment by briand44** [comment]
CNAME has been created

**Comment by richardbporter** [comment]
The site is now available at https://mbhd.conference.uiowa.edu. The old URL https://mbhd2020.centerforconferences.uiowa.edu is now redirecting. The D7 metadata has been updated but might take a while to regenerate.

Reopen for any follow-up work.
