### ISSUE TITLE
Admissions - Migration caused some fields to be uneditable

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#4808]
# Problem

Migration caused some fields to receive the wrong format and editors don't have access to them.

- Estimated Cost of Attendance
- Application Deadlines

# Proposed solution

Loop through and re-save the fields with the correct filter format?

Some are marked as full_html (node__field_area_of_study_deadlines).

**Comment by briand44** [comment]
May be some example code in undergrad Admissions migration if needed.
