### ISSUE TITLE
Clean up media revisions

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#4811]
Epic #4338 

# Story

When a media entity is deleted from the website, as a site editor I expect the underlying file to be removed from the server so it no longer shows up in search results.

# Proposed Solution

Update hook to remove non-current media revisions and set the related files' status to 0 so that garbage collection can remove them.

- [x] query the media table for all `mid/vid`. Then in media_revision get all `mid/vid` that don't intersect and safely delete using `\Drupal::service('entity_type.manager')->getStorage('media')->deleteRevision({vid});` OR look into comparing `changed` values to identify older candidates.
- [x] Test to see if file_usage table counts are updated with this alone, otherwise look into other ways to trigger an update without the usual add/edit/delete operations.
- [ ] Confirm that existing "latest" media is not wiped out and that cron doesn't remove them in subsequent runs.
- [ ] Run off-hours

**Comment by briand44** [comment]
Don't delete "latest"

**Comment by joewhitsitt** [comment]
Untested but query the `media` table for all `mid`/`vid`. Then in `media_revision` get all `mid`/`vid` that don't intersect and safely delete using `\Drupal::service('entity_type.manager')->getStorage('media')->deleteRevision({vid});`?

**Comment by joewhitsitt** [comment]
not sure what to do to trigger entity usage to update their counts though (this is usually done with UI media operations)

**Comment by joewhitsitt** [comment]
Updated proposed solution

**Comment by joewhitsitt** [comment]
Not sure if we still need to manually re-trigger a recount but https://www.drupal.org/project/entity_usage/issues/3240349 is baked into the next version of entity_usage https://github.com/uiowa/uiowa/pull/4902
