### ISSUE TITLE
Add Heatmap code to icgov.org

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#4814]
We received a request to add some tag manager code to icgov.org for a heatmap. This is to assist them and their new development team as they transition off of our platform.

Tag Manager is currently not enabled, do we enable it or just add the code through the template?

I forwarded the email that contains the code to its-web for reference.

**Comment by briand44** [comment]
Sounds like adding the GTM module is the preferred path forward here. We will want to explain that it is added to all pages and they can limit on their end.

**Comment by briand44** [comment]
I got another email about this. Blocking until I can get some further clarification.

**Comment by briand44** [comment]
Ok, it now seems like we just need to add the Heatmap code (email in its-web) to the homepage for icgov.org. Tag Manager is no longer in scope.

**Comment by richardbporter** [comment]
I need to deploy a release for icgov so I can probably wrap this up into it.
