### ISSUE TITLE
Image gallery image style regression

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#4827]
# Problem
https://github.com/uiowa/uiowa/pull/4781 caused a regression where the image gallery view mode and the original image got swapped. the original image is now being loaded for the grid/masonry and the image gallery style (max of 768 or whatever) is loaded in the viewbox. Depending on the size of the monitor original image in the light box it should expand to fill the space and not be capped at a max height/width.

<img width="1017" alt="Screen Shot 2022-02-17 at 10 16 21 AM" src="https://user-images.githubusercontent.com/4663676/154523476-9e4f0e26-bce1-42b0-83c5-92d240aa93f9.png">

# Steps to reproduce

Inspect the gallery here: https://sandbox.prod.drupal.uiowa.edu/single-image-gallery

# Proposed solution

- Assign a responsive image style (small or medium no-crop) as the node option and original image for the lightbox/viewbox option. Lazy should still work with this.
- Run off-hours, clearing cache to regenerate image styles for these blocks.

**Comment by dnkemper** [comment]
actually this wasn't possible with photoswipe and had to be swapped to use a photoswipe 'responsive' image to be able to implement lazyload instead of just using the original photoswipe image (which was what was set originally). So at the moment it's going to be one or the other - lazy or this. OR will require a custom patch
<img width="1136" alt="Screen Shot 2022-02-17 at 11 58 05 AM" src="https://user-images.githubusercontent.com/16872949/154543446-db788d60-a3a7-4159-bded-4377f4263853.png">

**Comment by joewhitsitt** [comment]
Okay, yeah, image gallery isn't a responsive style. Instead we should use small or medium no crop then and sunset the image gallery image style.

**Comment by joewhitsitt** [comment]
changing this will probably have to be an off-hours release again to clear caches and get the gallery to re-trigger the image style generation

**Comment by makurj** [comment]
Where do I go to get to the page in Dani's screenshot? I've looked at multiple image gallery and image display pages, but no luck so far.

**Comment by joewhitsitt** [comment]
I think it is `Media Type Image > Display Settings > Image Gallery view mode`

**Comment by makurj** [comment]
/admin/structure/media/manage/image/display Choose one of these? 
![image](https://user-images.githubusercontent.com/52135878/156004824-25b5db09-a2b7-446a-bd52-8f488081a179.png)

**Comment by joewhitsitt** [comment]
Did you change the image formatter? It should stay responsive and you should select small or medium no crop for the image style and original for the viewbox.

**Comment by makurj** [comment]
I did not change anything. I pulled `default` down on Thursday and started a fresh branch off the latest `main`.

**Comment by joewhitsitt** [comment]
are you here: /admin/structure/media/manage/image/display/image_gallery ?

**Comment by makurj** [comment]
On that page but `default` was selected at the by default so I didn't change it and scrolled down to image. I see the options once `image gallery` has been clicked at the top.

**Comment by makurj** [comment]
Like so? 
![image](https://user-images.githubusercontent.com/52135878/156008283-70d27f3d-3d9d-4976-82a2-92056a9dfa57.png)
