### ISSUE TITLE
Education People Directory Google Search Issue

### ISSUE THREAD

**Issue by mjoneill** [uiowa/uiowa#4837]
CoE faculty member identified that his profile is no longer appearing in site search.  It is also not appearing in Google search (not surprising, since it's the same engine).

**Comment by mjoneill** [comment]
People directory sitemap is submitted, all the profiles are crawlable.  Google isn't having trouble finding the content.  It is, however, _choosing_ not to display it in serps.

**Comment by mjoneill** [comment]
I do notice that prior to this, their directory was set up at the following path: 

https://education.uiowa.edu/people/

Now it is https://education.uiowa.edu/directory/

Yet the root https://education.uiowa.edu/people/ page still exists and is accessible (with no content on it).  Seems weird, and makes me wonder if this is expected, or there might be more components of the old directory at play.

I am also curious about any redirect strategy that CoE might have used when they made this change.

**Comment by mjoneill** [comment]
Noticing something a bit weird. Screamingfrog is reporting that profile pages are not indexable because they are canonicalized, and that there's a canonical reference to the profile that exists on Directory Profiles main site for each profile on education.uiowa.edu.

Can someone more familiar with how the module is working and what is doing take a look for the canonical to profiles.uiowa.edu/people/*

[list_mode_export.xlsx](https://github.com/uiowa/uiowa/files/8101414/list_mode_export.xlsx)
[education_diagnostics.xlsx](https://github.com/uiowa/uiowa/files/8101395/education_diagnostics.xlsx)

**Comment by mjoneill** [comment]
Seeing similar behavior in search for dentistry and education.  @briand44 I suspect we're going to want to push a change out to the module for whatever canonical reference is pointing back at another website.  

I notice both these sites are also using /directory/ for the path. Seems like that's just coincidental to whatever is going on, but I am making note of it just in case that's meaningful.

Let's discuss options during/after parking lot on Monday.

Would also be interested in understanding if we have the ability to add a meta description to these profiles, perhaps based on [name] + [primary title] + [college/unit] | University of Iowa on our own, or we would need to collaborate with directory profiles group for something like that.

**Comment by joewhitsitt** [comment]
Going to look into this issue

**Comment by joewhitsitt** [comment]
Waiting on the directory profiles team to update allowed URLs to include our new DDEV local url pattern for local testing.

**Comment by joewhitsitt** [comment]
Without being able to step through this [for now](https://github.com/uiowa/uiowa/issues/4837#issuecomment-1054508983), it appears the JS is grabbing metadata from a profiles endpoint (https://profiles.uiowa.edu/api/people/{person name}/metadata?apiKey=...) and changing the canonical link (just in time?) based on whatever is returned back which my guess is set as `https://profiles.uiowa.edu/people/{person-name}`

Looks like we could grab other data (e.g. meta description) if it existed and was provided, but right now it just seems to spit out `profileId`, `name`,  `canonical_url`

I'd like to confirm once I can test locally to make sure it doesn't conflict some way, but site owners can disable the local person content type view display at /people. However, I don't think this is causing Google not to index the profiles. https://sitenow.uiowa.edu/documentation/person-content-type/sitenow-people

**Comment by joewhitsitt** [comment]
Do we have access to the profiles backend to see if canonical_url is something editors can set?

**Comment by mjoneill** [comment]
> Do we have access to the profiles backend to see if canonical_url is something editors can set?

I don't think anyone on this team does, but Denny should be able to tell you if that's possible.  He's been responsive on slack if you want to ask him.  I don't see him in GitHub

**Comment by joewhitsitt** [comment]
@mjoneill 

According to Rick, we were going to allow canonical path to be set on the website per api key (not per-profile), but that it was ripped out. I imagine because that canonical path should be set on a per person basis.

So either these individuals need to be updated to have https://education.uiowa.edu/directory/person-name as their canonical url. Not sure if this would solve the issue but, if the canonical url isn't education, my guess is that Google wouldn't index it there.

If profiles.uiowa.edu is supposed to be the fallback for any profile that doesn't declare a canonical replacement, the meta information on that site should be improved. I am seeing a lot of blank or empty metadata.

**Comment by joewhitsitt** [comment]
>Waiting on the directory profiles team to update allowed URLs to include our new DDEV local url pattern for local testing.

This is done. Denny also sent an education test key to use locally.

Locally, I have disabled the canonical url functionality we are doing on our end but that doesn't appear to be needed anymore as the canonical base has been set for Education from the Profiles side of things. This should resolve any issue with Education and the canonical url.

Google search results still seem incomplete though according to @mjoneill. Meta descriptions are not currently set by Profiles (could be) and we could update the JS to also set that. Alternatively, we could create our own based on the profile data received (i think).

**Comment by joewhitsitt** [comment]
Conversation is happening in the Java gitlab: https://git.uiowa.edu/java/profiles/-/issues/486/

**Comment by joewhitsitt** [comment]
Sounds like the Directory Profiles team is going to move forward with providing meta description information for us to consume and handle similarly to the canonical_url. I imagine this is blocked until we know what that new value looks like and what the recent canonical_url change upstream does for Google search results.

**Comment by richardbporter** [comment]
> Sounds like the Directory Profiles team is going to move forward with providing meta description information for us to consume and handle similarly to the canonical_url. I imagine this is blocked until we know what that new value looks like and what the recent canonical_url change upstream does for Google search results.

This functionality existed in APR but not Profiles so it was removed from our module port. I can probably find a commit...

**Comment by richardbporter** [comment]
> > Sounds like the Directory Profiles team is going to move forward with providing meta description information for us to consume and handle similarly to the canonical_url. I imagine this is blocked until we know what that new value looks like and what the recent canonical_url change upstream does for Google search results.
> 
> This functionality existed in APR but not Profiles so it was removed from our module port. I can probably find a commit...

Maybe not. Looks like APR had a title callback setting the page title and canonical. I'm guessing we'll do something different for profiles.

**Comment by briand44** [comment]
Closing this as the issue with canonicals has been resolved. Meta description work can happen in https://github.com/uiowa/uiowa/issues/4889
