### ISSUE TITLE
config_ignore did not properly update

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#484]
## Problem
New config was specified in config_ignore for metatag (favicons) but wasn't properly imported to the sites with the latest release.

As a result, all of our production sites are sporting the drupal logo for the favicon.

**Comment by richardbporter** [comment]
Looks like the culprit is bbbd8ab0e1a61e02dff186b8b0f703b54d6ada1f: https://github.com/uiowa/uiowa/commit/bbbd8ab0e1a61e02dff186b8b0f703b54d6ada1f#diff-07812ac16a2df79e886917c484760b80R3
