### ISSUE TITLE
Create hook_cron to invalidate and purge custom cache tag used in sitenow_events

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#4842]
Blocked by #4841.

### Proposed solution
Rename sitenow_events cache tag created in #4818 from `time:hours_3` to `time:hourly`. 

Implement `hook_cron()` in uiowa_core.module. Check for existence of of [State API](https://www.drupal.org/docs/8/api/state-api/overview) key called `uiowa_core_hourly_last` or similar. If set, subtract the value from the request time. If that is greater or equal to an hour (3600 seconds), then invalidate the tag `time:hourly` via `Cache::invalidateTags();` and queue a purge for the tag as documented in the [purge README](https://git.drupalcode.org/project/purge#queueing). Set the State API key `uiowa_core_hourly_last` to the current request time.

#### Testing
This can be tested similarly to #4818 but instead of running the commands, just wait for cron to run assuming it has been set up on dev in #4841.

##### Story
As an anonymous visitor to a SiteNow website, I can see updates to events after one hour.

**Comment by briand44** [comment]
save a last run time - compare against current time - if >= then purge

**Comment by briand44** [comment]
shared temp storage?

**Comment by briand44** [comment]
state API?

**Comment by briand44** [comment]
invalidate cache tag, purge request for cache tag. Rick to add drush commands here.

**Comment by richardbporter** [comment]
>Check for existence of of [State API](https://www.drupal.org/docs/8/api/state-api/overview) key called sitenow_events_hourly_last or similar.

If it isn't set, I assume the cache tag should be invalidated and a purge queued, then set the State key.

**Comment by joewhitsitt** [comment]
I missed the bit where we are scoping this just to sitenow_events. Wasn't the idea to go generic so that other things can be tied to this in the future if needed? `sitenow_cron:hourly` and put it in the profile?

**Comment by richardbporter** [comment]
> I missed the bit where we are scoping this just to sitenow_events. Wasn't the idea to go generic so that other things can be tied to this in the future if needed? `sitenow_cron:hourly` and put it in the profile?

Ah yea, thats a good idea. I was thinking we didn't want multiple hook_cron implementations running and doing the same thing. Good call.

**Comment by richardbporter** [comment]
> > I missed the bit where we are scoping this just to sitenow_events. Wasn't the idea to go generic so that other things can be tied to this in the future if needed? `sitenow_cron:hourly` and put it in the profile?
> 
> Ah yea, thats a good idea. I was thinking we didn't want multiple hook_cron implementations running and doing the same thing. Good call.

Updated issue description.
