### ISSUE TITLE
maps.uiowa.edu clear search button has invalid color contrast ratio

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#4848]
# Problem
Maps.uiowa.edu clear search button has invalid color contrast

<img width="457" alt="Screen Shot 2022-02-18 at 12 54 49 PM" src="https://user-images.githubusercontent.com/1036433/155196362-db6ab44f-c561-4240-b744-c556ccda6163.png">

**Hover:**

<img width="449" alt="Screen Shot 2022-02-18 at 12 54 54 PM" src="https://user-images.githubusercontent.com/1036433/155196379-cea4f79e-4d88-4203-8e20-d474af2c13a1.png">

# Steps to reproduce
Try searching for something on maps.uiowa.edu and hovering over the clear button. 

# Proposed solution
From Patrick at Concept3d:

"There is a way to change this in the CMS. It is under the tab of Front End Styles, and then under the category of Primary Buttons. The setting to change would be the hover color option for primary buttons. You can also adjust the hover state settings and background colors to make it accessible. "

**Comment by e-marie-w** [comment]
![Screen Shot 2022-11-11 at 1 25 18 PM](https://user-images.githubusercontent.com/68179015/201415790-c65b3fde-0b92-4bf8-923e-1c74066a1382.png)

It looks like the clear button has changed? Unsure if it was us or Concept3d. Also unsure if this is a win or if we want the button a different color.

**Comment by joewhitsitt** [comment]
wasn't me.

**Comment by bspeare** [comment]
I don't remember doing this either but glad to see that it has changed!

**Comment by joewhitsitt** [comment]
if it has changed and is good, let's just call this closed
