### ISSUE TITLE
As a site owner, I can use the default home page install as a starting point for my site design instead of a showcase of components

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#4849]
# Story

As a site owner, I can use the default home page install as a starting point for my site design instead of a showcase of components.

# Problem 
- The current installed home page (https://default.dev.drupal.uiowa.edu/) is a kitchen sink of component and text areas. 
- Customers cannot use the "Featured image" field since the template does not allow it. 

# Proposed solution
- [x] Initial slice: Design for new default home page on the Sandbox site.
- [x] Add two more default articles to the site install
- [x] Move current home page install to a new page so we can still track changes with Percy - call the page "Components Showcase"?
- [x] Convert https://sandbox.prod.drupal.uiowa.edu/homepage-example-4 into default content.

**Comment by joewhitsitt** [comment]
Semi-related to https://github.com/uiowa/uiowa/issues/3473 also by removing some media items, there are less public stored images that would interfere with an Intranet split.

**Comment by bspeare** [comment]
This screenshot is a good example of the confusion that the default home page install creates for users:

![Screenshot 2022-02-24 at 11-13-27 iowajpec org The University of Iowa](https://user-images.githubusercontent.com/1036433/155573808-975e83a8-13f9-415b-8dea-5cf01ca77152.png)

**Comment by pyrello** [comment]
Ideas for future iterations:
* Move the current showcase of blocks to a new demo content page.
* Redesign the about page to use the default content layout.

**Comment by bspeare** [comment]
Here is the current favorite if anyone has feedback on this version: https://sandbox.prod.drupal.uiowa.edu/homepage-example-4.

**Comment by joewhitsitt** [comment]
I like https://sandbox.prod.drupal.uiowa.edu/homepage-example-2 because it doesn't have video or icons. Change up some of the photos to be more "general university" so there is more potential for them being used for other content.

**Comment by bspeare** [comment]
@joewhitsitt good point.  Maybe we can blend the two a bit.

**Comment by bspeare** [comment]
We've created https://sandbox.prod.drupal.uiowa.edu/homepage-example-4-alt that removes the icons.  There's also no videos on this version either.

**Comment by GaryRidgway** [comment]
I really like the new alt! The only thing i can think of is possibly putting these cards in a grey section?
<img width="1435" alt="Screen Shot 2022-03-09 at 10 02 35 AM" src="https://user-images.githubusercontent.com/23122142/157480349-cd28d93a-55d2-4655-8cb1-2e7ed3a7d472.png">

My instinct comes from this:

As i was learning with Alex about content creation, he often suggested to me that breaking sections in to things that the eye can parse is really important. Therefore, adding muted background colors or changing the layout to spearate in to chunks makes it easier for a user to know what piece of content they need to consume to know they understand that section.

This to me feels like a "Separation" moment, but I understand if others feel differently. Sorry for the long ramble, just trying to use the knowledge given to me!

**Comment by bspeare** [comment]
Thanks for the feedback @GaryRidgway. I tend to want to see those in a background too, but I think Brandon is trying to create a cohesive content chunk/grouping by combining intro text area with cards.  The images and smaller font size in the cards help set some contrast/hierarchy against the text area above.   @ABoston88 what do you think?

**Comment by ABoston88** [comment]
The body copy and the cards definitely read as grouped together to me, which is kind of hard to picture a use-case for. That single paragraph has to introduce the unit, do a little messaging work, and provide a natural lead-in to what those links are. But maybe if you had some core services or pages that'd be a good way to immediately surface them? 

If we're aiming towards creating a usable starting front page the Collection/FAQ seems an odd fit. Typically FAQs are last resorts for unsuccessful info searches not first destinations. This might suggest to users that they go front-and-center, which I probably wouldn't recommend.

**Comment by bspeare** [comment]
@ABoston88 good point about the collection.   Maybe we can just put a text area there.

<img width="687" alt="Screen Shot 2022-03-09 at 3 38 14 PM" src="https://user-images.githubusercontent.com/1036433/157540626-a77bc141-e013-47e9-9256-762ceaae228f.png">

**Comment by ABoston88** [comment]
Do we want a demo prefooter to be part of the default content? Could be helpful...and they're pretty simple to alter or delete. Adding a CTA to every page is a good habit to encourage, too.

**Comment by bspeare** [comment]
@ABoston88 I think for this page design we want a CTA at the bottom.   I'm not sure if we can integrate that into the prefooter for the default install, but let's add a CTA at the bottom of this page design through layout builder for now.

**Comment by ABoston88** [comment]
Will do. The rest of the draft content is in place. Just need to make the CTA. 

Edit: CTA made. Open to any notes on copy.

**Comment by bspeare** [comment]
I think https://sandbox.prod.drupal.uiowa.edu/homepage-example-4 is ready for the team to review.  I'll add a card to prs ahoy to make that visible.

**Comment by joewhitsitt** [comment]
I like it. We will need to up the amount of default articles though with this change (showing 3 instead of our 1). Start generating those copy ideas!

**Comment by bspeare** [comment]
Good point about the articles @joewhitsitt! 

@ABoston88 can you think of some default articles that would be good to include in the default install?  Here's a look at the one article that installs with all sites: https://default.dev.drupal.uiowa.edu/news.

**Comment by bspeare** [comment]
Next steps on this:

- [ ] Possibly add two more default articles to the site install
- [ ] Move current home page install to a new page so we can still track changes with Percy - what do we want to call it?
- [ ] Convert https://sandbox.prod.drupal.uiowa.edu/homepage-example-4 into default content. 

Are there any other steps we should consider?

**Comment by joewhitsitt** [comment]
>what do we want to call it?

"Component showcase," "Everything but the kitchen sink," "Component examples," "Hall of Bill Murray," "Elements," "Rich content examples"

**Comment by ABoston88** [comment]
FWIW, I think "component showcase" captures the current (soon-to-be previous) default home page well.

On the articles, I could just throw together a "Welcome" article that has some key contacts and introductory info. Maybe the second could be a very quick "Getting started" guide that links to the Web Community Site and training stuff? I know we don't want to update this very frequently but that article could include more as we develop more resources. 

Open to other ideas, too. Otherwise, I'll write those up.

**Comment by bspeare** [comment]
@ABoston88 I think those articles sound like good ideas!

**Comment by pyrello** [comment]
> Hall of Bill Murray

🤣

**Comment by makurj** [comment]
Waiting for articles from @ABoston88 to proceed.

**Comment by ABoston88** [comment]
Articles drafted here:
https://sandbox.prod.drupal.uiowa.edu/news/2022/03/welcome-sitenow-v3 
https://sandbox.prod.drupal.uiowa.edu/news/2022/03/quick-start-guide-sitenow 

Would adding images pose any issues on a default install? The second article could do with some illustrations but could live without, if need be.

**Comment by bspeare** [comment]
@ABoston88 Images shouldn't be a problem.  I think we mostly just need featured images for each article.    Should we just add a couple of campus images?  Or we could also just reuse the block Iowa logo for each article.

**Comment by ABoston88** [comment]
Campus shots should work fine. I'll add some of those and a screenshot or two to the quick-start guide.

**Comment by makurj** [comment]
@ABoston88 Here is what I have so far. Could you review the images on the page, especially the Recreational Services ones? Are they a good representation of campus?
![image](https://user-images.githubusercontent.com/52135878/160435549-adc591fd-e955-4223-829f-7c126c47e537.png)

**Comment by ABoston88** [comment]
This looks good to me. We'll probably want to take a look at that third article in the news feed, renaming to something like "Demo article", which I've done on the sandbox site. That suits the purpose of these a bit more explicitly. Otherwise, I think we're good.
