### ISSUE TITLE
SSL for prc.public-health.uiowa.edu on uiowa03

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#4852]
I checked with Patrick and Christopher at Public Health and they said that setting up the cert to cover `*.public-health.uiowa.edu` makes sense to them as long as:

 "It doesn’t affect my ability to request a certificate for the same in the InCommon certificate manager.  Our SSL certificate used by our on-prem sites and WordPress sites in AWS also covers *.public-health.uiowa.edu."

**Comment by dnkemper** [comment]
Wrapped this with https://github.com/uiowa/uiowa/issues/4874
