### ISSUE TITLE
square image showing instead of widescreen on card block

### ISSUE THREAD

**Issue by bewoldt** [uiowa/uiowa#4856]
# Problem
A card block has the image format set as Widescreen but is displaying as Square after saving.

site: https://stanleymuseum.prod.drupal.uiowa.edu
<img width="657" alt="Screen Shot 2022-02-24 at 9 13 48 AM" src="https://user-images.githubusercontent.com/731952/155552079-88cab2ed-2393-4f31-bf5b-7d1181c0d492.png">

<img width="475" alt="Screen Shot 2022-02-24 at 9 14 10 AM" src="https://user-images.githubusercontent.com/731952/155552102-ed4b4f5d-ea84-4ae0-bf3d-08da238a595a.png">

**Comment by joewhitsitt** [comment]
I wonder if this is an issue with the image itself. We have file size and dimension restrictions because the server chokes on processing images past a certain point. Looks like this image is over our width restriction.

@bewoldt can you try swapping it with an under 10 MB, under 2000 px image?

@quamsta said that some images might have been migrated in on this site which would bypass those restrictions.

**Comment by joewhitsitt** [comment]
We noticed while working on the https://github.com/uiowa/uiowa/issues/4691#issuecomment-1018656724 that some images were too big

**Comment by bewoldt** [comment]
@joewhitsitt the image in question is only 5mb. https://stanleymuseum.prod.drupal.uiowa.edu/media/image/766

**Comment by bewoldt** [comment]
@joewhitsitt the image was uploaded by the client and not migrated.

**Comment by quamsta** [comment]
@joewhitsitt  Yeah, I also just did a dive into the file migration for Stanley that we did back in October and the maximum image size we migrated was 300kb, so we resampled the images before migration. This may just be a consequence of a user really enjoying uploading ~5mb and above images. 

We always try to ensure that we're not uploading giant images during our migrations to be mindful of space constraints.

**Comment by joewhitsitt** [comment]
You are right but the original image is over 5000px wide. Looks like we are restricting images to 10Mb or less but aren't restricting dimensions. We probably should as we run into problems in this area.

In the past we haven't recommended over 3840 x 3840px.

Can't hurt to try swapping out to see if it is related to the image.

**Comment by bewoldt** [comment]
The original image was 5568 x 3712px. I resized to to 2200px and uploaded a new image and that fixed the issue. If there are image dimension requirements they need to be clearly stated or maybe disallowed during upload.

**Comment by joewhitsitt** [comment]
I have created an issue to set restrictions and update documentation. https://github.com/uiowa/uiowa/issues/4863

Glad this wasn't an issue with our card logic especially after the 9.3.5 update.

**Comment by joewhitsitt** [comment]
>I resized to to 2200px and uploaded a new image and that fixed the issue.

Closing in favor of https://github.com/uiowa/uiowa/issues/4863
