### ISSUE TITLE
Site install fails on AC

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#488]
**Describe the bug**
Site installs fail on AC.

**To Reproduce**
1. `drush @demo.dev si sitenow`
2. See error

**Expected behavior**
Should work.

**Screenshots**
```
In EntityStorageBase.php line 482:
                                                           
  'date_format' entity with ID 'fallback' already exists.
```

**Comment by richardbporter** [comment]
CR

**Comment by shelane** [comment]
Which commit fixed this? We're seeing a similar message on our site in AC as well.

**Comment by richardbporter** [comment]
The site just needed a `drush cache:rebuild` and the `site:install` worked. 🤷‍♂

**Comment by shelane** [comment]
OK. That is odd considering a site install should drop the tables. We are seeing the same thing though. If we do a `drush cr` then do a `site:install` it works. Try another `site:install` without a `cr` and it gives the same failure. I'd like to report the issue, but why I only have this issue on AC, ¯\_(ツ)_/¯ A `si` works file locally and on our Jenkins server.

**Comment by damontgomery** [comment]
Thanks for the notes, this worked for us as well. I believe it might have to do with the fact the not all the cache tables are in the database on Acquia Cloud. It has some stored in APCu. See https://docs.acquia.com/acquia-cloud/manage/php/#apcu.

**Comment by marcelovani** [comment]
If you have memcached enabled, you better clear it before you reinstall a site

**Comment by kerasai** [comment]
Noticed this on a "standard" D8 site, using Redis as cache backend. Thanks for the clue!
