### ISSUE TITLE
The Topic Collection page itself shows up in the taxonomy view when filtering by a term

### ISSUE THREAD

**Issue by quamsta** [uiowa/uiowa#4882]
# Problem
We and our partners have noticed that when a user clicks on a tag from the Topic Collection, the Topic Collection page itself is either the first or last item in the list. For example, the Topic Collection "Find Resources" shows up in the filtered view after clicking on it from the Topic Collection itself:

<img width="648" alt="Screen Shot 2022-03-02 at 8 31 04 AM" src="https://user-images.githubusercontent.com/472923/156381534-3c902d63-5fcf-4f8c-a071-668971be8a22.png">

# Steps to reproduce
1. Enable "Topic Page" in `admin/config/development/configuration/config-split`
2. Tag some pieces of content on the site
3. Create an instance of the Topic Collection content type
4. Fill out the "Browse By" list of tags
5. Save and view the page
6. Click on a tag in the main tag area and you can see the topic collection itself

# Proposed solution
Exclude the Topic Collection content type from the taxonomy view in the "Topic Page" config split

**Comment by joewhitsitt** [comment]
So, we have a "hide on lists" boolean for node content (person content currently uses) that could be used for this and set by default (disabled to editors if you don't want them to change it)

**Comment by quamsta** [comment]
Nice!! That could be an easy solution for this

**Comment by quamsta** [comment]
@joewhitsitt 

Couple of questions:

1. If I go this route of adding the Hide on Lists field to this content type, do you think I should I reuse the one that's on the Person content type or create a new one specific to this content type?
2. Either way, how do I ensure that this checkbox field is in "Page Options" accordion in the edit node form. that seems to be eluding me at the moment

**Comment by joewhitsitt** [comment]
Ah darn. My mention of this has made things sticky. Sorry. I thought it was a global field like field_image or title_hidden that could be reused... I also realize that we aren't hiding people on taxonomy pages that have this checked...

At this point, if it were me, I would create a `hide_on_lists` type field in default that we could possibly migrate person functionality to later.

We could then create a follow up issue to update the person functionality to use this instead and by default taxonomy lists would then be covered.
