### ISSUE TITLE
Careers -BI embeds

### ISSUE THREAD

**Issue by dnkemper** [uiowa/uiowa#4883]
Investigate Powerbi embeds - console is spitting out a bunch of errors related to https://careers.uiowa.edu/about/hiring-data-annual-reports (default chrome browser, no extensions, blockers) `TypeError: Cannot read properties of undefined (reading 'options')` compared to https://dsp.research.uiowa.edu/contract-metrics. Comparing the load times of the first view provided by powerbi, careers has a longer delay, but dsp.research has a longer wait. In the end they finish within milliseconds of each other.

https://iowaweb.slack.com/archives/C0164FNN1PV/p1646151471441499

**Comment by joewhitsitt** [comment]
Possible solution from our end to offer up: display only one per page.

They referenced an example on v1 which is also having problems (multiple embeds): https://international.uiowa.edu/global-network

<img width="1072" alt="Screen Shot 2022-03-02 at 10 47 32 AM" src="https://user-images.githubusercontent.com/4663676/156408257-81de817f-b169-4bfc-8345-3656e2f3a47e.png">

**Comment by briand44** [comment]
I let them know they may want to just link out directly to the PowerBI reports temporarily until we can understand if there is an issue on our end.

**Comment by briand44** [comment]
Also, I was running into some issues just loaded the PowerBI link directly. https://iowaweb.slack.com/archives/C0164FNN1PV/p1646256239488099

**Comment by quamsta** [comment]
I was able to recreate this issue with the embeds, but it may be related to trackers not loading due to browser adblocking extensions or capabilities. I tried in a private browsing window with extensions disabled in Chrome and the embed appeared to work fine. Can you try testing with adblockers turned off?

**Comment by briand44** [comment]
I am still having issues directly loading the link to PowerBI in Chrome, Safari and Firefox using private browsing windows. Seeing console errors as well.

**Comment by joewhitsitt** [comment]
@pyrello responded via its-web today and referenced the codepen: https://codepen.io/joewhitsitt/pen/rNYQzOO

**Comment by joewhitsitt** [comment]
PowerBI team is opening a ticket with Microsoft. @briand44 moved this to done. Closing.

**Comment by briand44** [comment]
thanks!
