### ISSUE TITLE
Concept3D - Base layer edits

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#4894]
Keeping a list of additions/edits/removals to pass on to Concept3D periodically to handle in batches

- [x] Hancher Footbridge is mislabeled as "Hatcher Footbridge"
- [x] Removed 118 S Clinton St - lease expired.
- [x] Pappajohn Business Building is mislabeled as "Papajohn Business Building"
- [x] Change the name of the building “Old Museum of Art” to “Performing Arts Annex”
- [x] Building label for Plaza Centre One is missing
- [x] The concept3d errantly labels the "Hawkeye Recreation Fields" as the "Iowa Rugby Fields". Please edit.
- [x] Please re-name the old and out-dated "Front Street" to "Museum Drive"
- [x] Stanley Museum of Art building label?

**Comment by mkyoder** [comment]
Hi! Can we add Pappajohn Business Building to this list?

Pappajohn Business Building is mislabeled as "Papajohn Business Building"

<img width="260" alt="Screen Shot 2022-09-26 at 9 55 28 AM" src="https://user-images.githubusercontent.com/107870104/192313184-6144d2e4-fe2f-4414-a9b3-529ee76db245.png">

**Comment by briand44** [comment]
>Can we please change the name of the building currently listed as “Old Museum of Art” on Concept 3D to “Performing Arts Annex” please?

**Comment by briand44** [comment]
Adding blocked label because Jay G. mentioned another change coming. Going to wait until I hear back about that before sending on to Concept3D.

**Comment by briand44** [comment]
The items listed in the issue summary have all been submitted through the CMS as edits "February 2023 updates". I let our success manager know that those have been submitted. I don't think there is anything else for us to do until our success manager gets back to us with a quote/statement of work.

**Comment by joewhitsitt** [comment]
@briand44 it looks like Facilities is reviewing maps.uiowa.edu and finding additional edits:

"The concept3d errantly labels the "Recreation Fields" as the "Rugby Fields""
<img width="532" alt="Screenshot 2023-02-22 at 3 42 50 PM" src="https://user-images.githubusercontent.com/4663676/220766062-7d8905d9-f0a8-4c58-aae2-ef823d8b76da.png">


"Please re-name the old and out-dated "Front Street" to "Museum Drive"....the new Institutional Road name for improved wayfinding and consistent institutional listing"
<img width="886" alt="Screenshot 2023-02-22 at 3 43 17 PM" src="https://user-images.githubusercontent.com/4663676/220766091-2b8540d3-a46e-4d1f-a118-a7558d1e8e6e.png">

**Comment by briand44** [comment]
Noticing there is not a building label on Stanley Museum of Art either.

**Comment by briand44** [comment]
SOW has been signed and returned. Now just waiting for the changes.

**Comment by briand44** [comment]
It looks like these changes have been implemented. Closing.
