### ISSUE TITLE
Minimum height set for text area blocks needs to be scoped for layout builder page only

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#4904]
# Problem
Minimum height set for text area blocks needs to be scoped for layout builder page only

# Steps to reproduce
View https://tippiestudents.prod.drupal.uiowa.edu/undergraduates/global-experiences/locations while logged in and logged out. 

# Proposed solution
Adjust https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/scss/admin.scss to include `.layout-builder-block` class so that this height is scoped to the layout builder edit interface only.

**Comment by makurj** [comment]
I would like to pair on this.
