### ISSUE TITLE
As a site editor, I can add extra margin to the top or bottom of a text area and collections block  

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#4906]
# Story

As a site editor, I can add extra margin to the top or bottom of a text area block that provides more spacing than the current margin top and bottom style. 

Currently, we only provide one option for setting a top and bottom margin on a text area block.  This solution would add a "Top margin extra" and "Bottom margin extra" option to the text area block. 

# Proposed solution

- Create layout builder styles that map to https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/scss/global.scss#L336-L357 and add them to the text area and collections block. 

**Current margin of `1rem`**

<img width="1018" alt="Screen Shot 2022-03-07 at 2 06 12 PM" src="https://user-images.githubusercontent.com/1036433/157109961-27e5060a-a453-4cc1-98dc-cc521eb3717a.png">

**Proposed margin addition of `2rem`**

<img width="1056" alt="Screen Shot 2022-03-07 at 2 06 18 PM" src="https://user-images.githubusercontent.com/1036433/157109991-af0e950a-ad7e-4075-965f-72e243e5ba9e.png">

Ideally, this work would be done paired with https://github.com/uiowa/uiowa/issues/4904.

**Comment by makurj** [comment]
I would like to pair on this.

**Comment by bspeare** [comment]
At grooming it was suggested that we put together a set of layout builder styles defaults that we want to provide to all blocks. 

- Padding
- Margin
- Background colors

I'll create a follow-up issue so that we can collect the next steps for that slice.
