### ISSUE TITLE
Remove law-old.dev.drupal.uiowa.edu

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#4913]
Followed up again and they wanted to keep until Spring if possible but didn't think they would likely need it much if at all. I responded letting them know that that site has been indexed by archive-it.org to see if that could be a possible alternative way of referencing this site.

Waiting for response to ^^

**Comment by briand44** [comment]
Marking this as blocked until Law launches their v3 site.

**Comment by briand44** [comment]
Megan talked with Laura about this on 9/27/24...

>She wants to take a look at the site (https://law-old.dev.drupal.uiowa.edu/) this week because there’s some marketing language and messaging on the website, she’d like to save before it’s taken down. She plans to work on it and go through everything this coming week.

**Comment by briand44** [comment]
Mentioned this to Courtney Hoffman in a meeting with her on 10/29/24

**Comment by briand44** [comment]
Emailed Courtney on 11/20 to see if we can remove.

**Comment by briand44** [comment]
Got permission to remove from Courtney!! Going to close this issue and add it to the deprovisions issue. Waiting to deprovision until 703 gets updated to cloud next.

**Comment by joewhitsitt** [comment]
another one bites...

this one feels different. i am happy.
