### ISSUE TITLE
As a developer, I can apply a default set of layout builder styles to any field or custom block

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#4917]
# Story

As a developer, I can apply a default set of layout builder styles to any new or existing block so that I can add margin, padding, and background colors. 

# Proposed solution
- Allow style options to be added for all field blocks and custom blocks. 
  - Exclude for existing layout builder page inline blocks
    - Our text area block's styles are a good example for possible defaults to offer:
      -   Padding
      -   Margin
      -   Background colors (white, gray)

**Comment by bspeare** [comment]
Related issue: https://github.com/uiowa/uiowa/issues/4906.

**Comment by bspeare** [comment]
Since we have a lot of places in our config where we are adding margin or removing margins, this would be useful to implement for the margin styles alone.   There is a Slack thread where this is discussed recently (https://iowaweb.slack.com/archives/C0164FNN1PV/p1668033414737329) and it would be useful to implement these styles so that this is no longer viewed as a "creative" solution.    Otherwise, let's find another way to adjust the spacing in our layouts.

**Comment by bspeare** [comment]
I don't see a future where we want to make available the margin, padding, and background color sets available for all blocks.   However, having the ability to remove the default margin added to all blocks in a layout is a universal need and useful when building a custom content type so I have put together https://github.com/uiowa/uiowa/pull/7201 to resolve this issue.

**Comment by joewhitsitt** [comment]
>Since we have a lot of places in our config where we are adding margin or removing margins

Should this be expanded to clean up those config files?

**Comment by bspeare** [comment]
Probably a good suggestion.  I think there are a few recent projects where I added those.
