### ISSUE TITLE
As a site owner, I can view a banner on a mobile device with the content separated from the image

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#4919]
# Story

As a site owner, I can view a banner on a mobile device with the content separated from the image so that the content and image are both readable/usable in the small space. 

# Proposed solution

- Add an option to the banner component block so that banner content is not absolutely positioned on top of the banner image for mobile.
- Use https://github.com/uiowa/uids/pull/652 as the starting point.  We will need to create a modifier class to set the mobile styles. 

**Before:**

![IowaMBA_current](https://user-images.githubusercontent.com/1036433/157336928-b680566d-035c-4fe0-8091-bc6d3579a371.jpg)

**After:**

![IowaMBA_future](https://user-images.githubusercontent.com/1036433/157336955-6f56c830-2a37-4234-b063-27f3a77cc41d.jpg)

**Comment by pyrello** [comment]
Is this something that we want to offer as an option instead of forcing this change on everyone? Are there cases where people would prefer the current behavior?

**Comment by bspeare** [comment]
> Is this something that we want to offer as an option instead of forcing this change on everyone? Are there cases where people would prefer the current behavior?

I think it might be a good idea to offer it as an option.

**Comment by joewhitsitt** [comment]
Ignoring the default for now, it sounded like additional work should be done to see how this option affects mobile banners in different situations. For example, patterns/colors were brought up. I believe the team is in agreement that this effect should be restricted to image/video banners and not extend to other background options.

**Comment by bspeare** [comment]
Here are a few additional thoughts:

- Add this as the default for page titles using the featured image
- Add a checkbox to "Display image and text stacked for mobile" only for images.  Add help text that patterns or background colors will not have the same behavior.  
- Video should default to the the stacked behavior. 
- As mentioned in standup, someone could be using three banners in a three column layout that could potentially create a lot of scrolling.  See the details below. 

I think I'd still prefer to see this as an opt-in option for users since there are so many variants. 

<details>
<img width="350" alt="Screen Shot 2022-04-12 at 10 01 06 AM" src="https://user-images.githubusercontent.com/1036433/162992675-002863a7-9e44-4320-9421-1d568f7a2e58.png">
</details>

**Comment by pyrello** [comment]
> I think I'd still prefer to see this as an opt-in option for users since there are so many variants.

Stacked banner is an opt-in option and the current behavior remains the default?

**Comment by bspeare** [comment]
Yes, current banner behavior as default and stacked option as an opt-in option.

**Comment by pyrello** [comment]
@GaryRidgway, correct me if I'm wrong, but it seems like this is going to need to be set up differently than it initially was to accomplish the above. The `banner--layout` class seems like it must encapsulate the current functionality rather than the new stacked option. We need a `banner--stacked` class and corresponding LB style so that this can be turned on. Once this has been done, then we can get rid of the group that we created and just have the new LB style show up in the default "Styles" group.

**Comment by briand44** [comment]
We can get feedback during demo if this opt in option should be available when using background patterns.
