### ISSUE TITLE
SSL for *.admissions.uiowa.edu on uiowa02

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#4924]
we are covering admissions.uiowa.edu and www.admissions.uiowa.edu but not covering grad.admissions.uiowa.edu. Can we add *.admissions.uiowa.edu and remove www.admissions.uiowa.edu?

**Comment by briand44** [comment]
@richardbporter I ask you this about once a month. Can you confirm if we can remove www.admissions.uiowa.edu if we add *.admissions.uiowa.edu? Thanks!

**Comment by richardbporter** [comment]
> @richardbporter I ask you this about once a month. Can you confirm if we can remove [www.admissions.uiowa.edu](http://www.admissions.uiowa.edu) if we add *.admissions.uiowa.edu? Thanks!

Yes

**Comment by joewhitsitt** [comment]
Done. www.admissions.uiowa.edu still works
