### ISSUE TITLE
Title search for Grad Admissions Areas of Study

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#4926]
We need to add a title exposed filter to https://admissionsgrad.prod.drupal.uiowa.edu/areas-of-study so that other search blocks (https://admissionsgrad.prod.drupal.uiowa.edu, https://admissionsgrad.prod.drupal.uiowa.edu/academics, https://admissionsgrad.prod.drupal.uiowa.edu/new-students) can correctly filter Areas of Study results. We will also need to make sure those search blocks are configured correctly.

**Comment by joewhitsitt** [comment]
As I explained to @briand44 this might be a bit tricky given how the views relationships are setup to filter on the content type and not the taxonomy. So the results should filter on the _hidden_ content which might not match the first column name (taxonomy term)

**Comment by pyrello** [comment]
I updated https://admissionsgrad.prod.drupal.uiowa.edu/academics and https://admissionsgrad.prod.drupal.uiowa.edu/new-students to have the search box point to the correct endpoint as they were not already.

**Comment by joewhitsitt** [comment]
If you are working on this @pyrello, I can unassign and work on something else.

**Comment by pyrello** [comment]
> If you are working on this @pyrello, I can unassign and work on something else.

I think you have a better idea of how to get this done.
