### ISSUE TITLE
Signage - Rewrite meeting with organizerName value if IsPrivate

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#4928]
## Issue

The CSI AppDev team plans to make a change to the Hours API related to private events and a customer is requesting that a new `organizerName` value be used as the meeting name when the event is marked as private `isPrivate`.

See its-web email from Chris Dibbern

## Proposed Solution

- [x] Wait for the change to happen on the test server
- [x] Within the outlook pane, change the endpoint temporarily.
- [x] What is the expectation on if organizerName is null but isPrivate is true?
- [x] If IsPrivate = true, use the creator field instead of the summary for the event instance meeting value.
- [x] deploy to signage
- [ ] ~~deploy to uihealthcare~~ doesn't have outlook widget
- [x] communicate that we are ready for the change to go-live

**Comment by joewhitsitt** [comment]
The change has been added to https://hours-test.iowa.uiowa.edu/api/Hours/signage/ (e.g. https://hours-test.iowa.uiowa.edu/api/Hours/signage/res-CPHB-c212?start=03-11-2022&end=03-18-2022)

Need to reach out to Chris Grycki about surfacing some example private events.

Asked and waiting to hear back if this expected functionality should extend to other implementations like fusionrecserv

**Comment by briand44** [comment]
Some test data was added and some additional context in email in its-web. The test data may expire prior to us planning this work though.

**Comment by joewhitsitt** [comment]
Not seeing isPrivate results for either link in that email thread.

**Comment by joewhitsitt** [comment]
Got an example:

<img width="704" alt="Screen Shot 2022-03-21 at 10 29 28 AM" src="https://user-images.githubusercontent.com/4663676/159295189-fd37a170-f8ef-4a72-a41d-0394b7987a08.png">

```json
{
  "$id": "1",
  "20220328": [
    {
      "$id": "2",
      "id": "AAMkADMyN2QxMjZiLTRiYWItNDk3YS1hMTRmLWUwMTE3ZjU4NmE2OQBGAAAAAABosEp5h29hQauY-t8k4hBGBwCXrGCWZZ51S6SBeYvUduT8AAAAAAENAACXrGCWZZ51S6SBeYvUduT8AABBwergAAA=",
      "summary": "[Private Event]",
      "description": "[Private Event - Please contact creator if you need more information.]",
      "textDescription": "",
      "location": "[Private Event]",
      "organizerEmail": "christopher-grycki@uiowa.edu",
      "organizerName": "Grycki, Christopher J",
      "start": "2022-03-28T22:00:00Z",
      "startHour": "17:00:00",
      "end": "2022-03-28T22:30:00Z",
      "endHour": "17:30:00",
      "isAllDay": false,
      "categories": [],
      "iso8601Start": "2022-03-28T17:00:00",
      "iso8601End": "2022-03-28T17:30:00",
      "lastUpdated": "2022-03-21T20:12:56Z",
      "isPrivate": true
    }
  ]
}
```

**Comment by briand44** [comment]
could output "Private event" if organizer is null and isprivate?

**Comment by joewhitsitt** [comment]
Created branch `outlook-private-organizer` in the signage app if anyone would like to take a look.

**Comment by joewhitsitt** [comment]
This has been deployed. I communicated the change with Chris D through Cherwell and Chris G/Chris D through the its-web email thread.
