### ISSUE TITLE
Too many Slack messages for AC cron start/stops

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#4929]
### Problem
Now that cron is running is AC prod via `blt ume`, we get notifications every time it starts/stops. This is multiple times per hour. The messages clutter the drupal-status channel and have lost their value.

### Proposed resolution
Change `blt ume` from notifying start/stop to only if a site encounters an error running the specified command.

**Comment by richardbporter** [comment]
Should our install command be changed as well? Initially, these were set up to notify other devs that commands were running. I'm leaning towards leaving install alone.

**Comment by richardbporter** [comment]
Also looks like our Slack integration is deprecated. Looking into replacing that as well.

**Comment by pyrello** [comment]
This is probably too much for now, but I think it would be nice to be able to decide which `blt ume` commands report back on error or every time. We could set a variable in our blt.yml file and then read that if it existed.
