### ISSUE TITLE
Topic collection shows up in related content under a tag heading

### ISSUE THREAD

**Issue by quamsta** [uiowa/uiowa#4932]
# Problem
Very similar to: https://github.com/uiowa/uiowa/issues/4882

I'd like to exclude Topic Collections from "related content" views, since the Topic Collection is usually a jumping off point for this content, and Topic Collection is "tagged" with terms that it's leading into.

<img width="475" alt="Screen Shot 2022-03-10 at 9 41 46 AM" src="https://user-images.githubusercontent.com/472923/157698092-b0604e56-02a6-446d-9506-64fa6255fbce.png">

# Steps to reproduce
1. Visit a site with a Topic Collection ([basicneeds.uiowa.edu ](https://basicneeds.uiowa.edu) is a good example) and related content enabled.
2. Click on an individual page linked to from the Topic Collection
3. See that the "Find Resources" page that you originated from is included in the related content

# Proposed solution
1. Add a partial split to exclude the Topic Collection content type from the related content view

**Comment by bspeare** [comment]
Closed via https://github.com/uiowa/uiowa/pull/4933.
