### ISSUE TITLE
Some events blocks are requiring a grid selection due to the recent layout builder styles update

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#4949]
# Problem

On https://education.uiowa.edu/student-experience/baker-teacher-leader-center/upcoming-btlc-events:

The layout builder group for grid columns is showing `-select-` on https://education.uiowa.edu/student-experience/baker-teacher-leader-center/upcoming-btlc-events:

<img width="542" alt="Screen Shot 2022-03-11 at 9 23 26 AM" src="https://user-images.githubusercontent.com/1036433/157896693-66bb5ab6-e2b4-4fcc-a5ff-9597127572ff.png">

If you create a new events block the settings look like:

<img width="532" alt="Screen Shot 2022-03-11 at 9 23 41 AM" src="https://user-images.githubusercontent.com/1036433/157896897-1034f7a6-0529-4917-a1ab-98603fd39787.png">

**Comment by joewhitsitt** [comment]
Big shout out to @pyrello for helping with this
