### ISSUE TITLE
Display Registrar Correspondence in table

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#4965]
# Story

As a Registrar site owner, I would like to publicly display some Dispatch email correspondence so that our students, faculty and staff can catch up on communications that have been sent.

# Additional Info

D7 example https://registrar.uiowa.edu/correspondence

Current code in `uiowa703/docroot/sites/registrar.uiowa.edu/modules/custom/registrar_core/registrar_core.module`

Their current display takes a very long time to load. Hoping limiting to 2 years will help with performance.

They would like to display 2 years worth of correspondence that have the public archive option set, have a registrar tag and have an audience of student or faculty & staff.

Ability to filter by audience. (All, Students, Faculty & Staff)

Would like the ability to pass an audience filter in through a query parameter so they can have separate links to student correspondence and faculty & staff correspondence.

Would also like the ability to filter by unit/department tags.

They are ok with how things currently display but would like to replace the Intended Population with Audience. The email column should link to the archive view on Dispatch.

![Screenshot 2024-08-20 at 3 29 37 PM](https://github.com/user-attachments/assets/a17e31fe-cbc8-492f-a10e-c0abb0f2e1a2)

**Comment by joewhitsitt** [comment]
>There are many of these so manually setting up RSS aggregator may not be viable.

If there are shared dispatch campaigns among them, then I believe they can all be entered once and the aggregator block has multi-feed capability to pull these in.

**Comment by joewhitsitt** [comment]
We could still use aggregator to fetch feeds and then create a registrar custom view table (block config filtered or exposed) of it to prevent that client loading issues.

**Comment by joewhitsitt** [comment]
After saying all that, their campaign tagging workflow seems incompatible with how setting up aggregator would be. Still would be good to move the fetch away from the client end.

**Comment by briand44** [comment]
Grooming conversation... Using Dispatch API currently to fetch the correspondence. Probably need to take a look at existing code. Currently caching for an hour. Should reach out to Josh to see if we can cache longer. Using RSS feed doesn't seem like a solution that would work here. Since we are pulling course deadlines and academic calendar info into this site and displaying we probably can do that with correspondence as well and avoid storing.

Scope this slice to getting the data from Dispatch and outputting on a page in a table. Follow up slice could be to add in the filters, theme, accessibility.

**Comment by joewhitsitt** [comment]
The current d7 code calls https://apps.its.uiowa.edu/dispatch/api-ref#/Archives/get_archives but doesn't currently include arguments for hidden and instead filters after fetch. Could help reduce processing by including it in the endpoint call. Looks like the tag filtering happens after the campaign call and does not have a tag argument option.

**Comment by briand44** [comment]
Talked with Josh about caching. Sounds like he would be comfortable with 12 hours, 24 hours would be a stretch here. They are concerned about performance though so if it needed to be 24 hours for performance reasons he could possibly sell that.

**Comment by cory-skeers** [comment]
The way it currently works at https://registrar.uiowa.edu/correspondence is that if ALL is selected, then all archives that are associated with a campaign tagged with REGISTRAR are pulled in and displayed. If STUDENT or STUDENT/FACULTY is selected, then all archives that are tagged with that audience (including both those that are and are not tagged with REGISTRAR) are pulled in.

My assumption is that for any of the select options, we still want to limit only to those tagged with REGISTRAR and not follow what is on the current site?

For instance

All:
<img width="1219" alt="image" src="https://github.com/user-attachments/assets/56668cc5-0336-4e48-9ae0-4fc972c5f1ba">

Student:
<img width="1219" alt="image" src="https://github.com/user-attachments/assets/a9d2d761-b944-411e-969d-0c45c80dd762">

The STUDENT select also has things from UI PSEO, Degree Services, etc., that are not included in ALL.

Update:

Confirmed that every selection should be limited to results tagged with REGISTRAR, so some results such as the UI PSEO ones should not appear in the STUDENT selection, etc.

**Comment by briand44** [comment]
@cory-skeers I can point Josh to ^^ to see if he can answer your question
