### ISSUE TITLE
Home page vertical video captions are not showing up on mobile

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#4971]
# Problem
Home page vertical video captions are not showing up on mobile devices. 

# Steps to reproduce
Watch a vertical video from uiowa.edu on your phone. 

<img width="353" alt="Screen Shot 2022-03-15 at 8 31 43 AM" src="https://user-images.githubusercontent.com/1036433/158388614-b9d532e4-2080-4a36-b263-00a70e297851.png">

# Proposed solution
?

**Comment by joewhitsitt** [comment]
Anyone figure out how to test a local URL with your device? Does BrowserStack work for this?

Quick Google search leads me to believe that something changed in iOS14 that might not be sending the vtt over to the full-screen native player. 🤷

**Comment by bspeare** [comment]
Browserstack does seem able to test this.

**Comment by makurj** [comment]
If I close out of the video player, they are showing up in landscape and orientation:

![image](https://user-images.githubusercontent.com/52135878/165980521-f7787acd-ba38-4390-904d-f0e2d60bdf70.png)

![image](https://user-images.githubusercontent.com/52135878/165980830-d4aeb73a-d84a-4f6a-adf2-8040592a9e69.png)

**Comment by joewhitsitt** [comment]
Wonder if we need to revisit https://github.com/uiowa/uids/pull/149?

This isn't what we use for our video, but some of this solution might apply to this issue: https://github.com/sampotts/plyr/issues/1233#issuecomment-777751492

**Comment by bspeare** [comment]
@joewhitsitt are you just referring to the positioning of the captions?  Could you explain what we are revisiting?

**Comment by joewhitsitt** [comment]
I originally came from https://github.com/uiowa/uiowa/issues/1379 where we are doing non-default things with the track subtitles. Not sure what the JS is doing here exactly as it relates to the track elements

ultimately, we should probably confirm that a default html5 video with subtitles is also having this problem on iOS to decide if we need to seek an upstream solution or be looking at our implementation

**Comment by makurj** [comment]
Should I wait on trying this (https://github.com/sampotts/plyr/issues/1233#issuecomment-777751492) then?

**Comment by bspeare** [comment]
I think the first step would be to test the captions in UIDS and remove these lines https://github.com/uiowa/uids/blob/3.x/src/components/video/vertical/vertical.js#L48-L79 and test in browserstack.  I think we need to revisit that JavaScript there.

**Comment by makurj** [comment]
On it. I'm not seeing "video" in the sidebar when I switch `hidden: false`, so how do I test it?

**Comment by makurj** [comment]
Not sure if this is progress or not but one of the captions is now appearing at the bottom of the video 😄 

![image](https://user-images.githubusercontent.com/52135878/166043789-1085aba4-0646-42e4-8bc7-ad8f17f4b564.png)

**Comment by bspeare** [comment]
@makurj I think that's supposed to be there.

**Comment by makurj** [comment]
Okay, so then no progress 😆

**Comment by bspeare** [comment]
I think this is a CSS issue.  Try deleting https://github.com/uiowa/uids/blob/3.x/src/components/video/vertical/_vertical.scss#L199-L203 and removing https://github.com/uiowa/uids/blob/3.x/src/components/video/vertical/_vertical.scss#L191.   You can edit this file in your `node_modules/uiowa/uids/src/components/video/vertical` folder and then run `yarn workspace uids_base build` to test.

**Comment by makurj** [comment]
That did it! @bspeare you rock!

![image](https://user-images.githubusercontent.com/52135878/166060850-8d6b1a56-8231-4d8a-9a5f-cd5b767bd7a7.png)

So do I need to make the same changes in `uids` now?

**Comment by bspeare** [comment]
Now test Android :)

**Comment by bspeare** [comment]
I tested the local version on Android and the captions did not appear, but with testing uiowa.edu on Android the captions are appearing.

**Comment by makurj** [comment]
Local (https://home.uiowa.ddev.site/) with Android (Galaxy S22) in BrowserStack didn't work for me either.

**Comment by bspeare** [comment]
I think the captions are just being blocked locally.  I'm seeing this error: `Unsafe attempt to load URL https://uiowa.edu/sites/uiowa.edu/files/2022-03/20220201%20Research.vtt from frame with URL https://home.uiowa.ddev.site/. Domains, protocols and ports must match.`

So yes, @makurj make those changes in `uids`
