### ISSUE TITLE
Create community colleges taxonomy and view block

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#4976]
- Term Name - this will be the official name of the Community College
- Locations - Not sure what we want to call this but my understanding is the District name is likely the official name but we will want a place to store/list specific CC's in that district (e.g. Eastern Iowa Community College District would be official name but Clinton Community College, Muscatine Community College and Scott Community College would be colleges in that district). We'll likely want to output these locations in lists since students will identify that easier. Plan info would be the same for all locations in that district.
- Contact Info - text area since some are links and others are individuals contact info

Need to reference what Iowa majors are available for each CC. Not sure how the team wants to architect that reference or where.

Here is a link provided by Admissions to some info about the fields needed here https://iowa-my.sharepoint.com/:w:/g/personal/katmills_uiowa_edu/EaQbdfwQQIJDgKED1dvJ7jQB143-R7ErxZPSZ8B019J6gA?e=j1aece. Provided 3/30/22

**Comment by briand44** [comment]
Would we want to store contact info with the college taxonomy term? It looks like the existing pages have some generic text and a link others have individual contact info.

https://2plus2.admissions.uiowa.edu/majors/western.htm - individual contact info
https://2plus2.admissions.uiowa.edu/majors/dmacc.htm - link

**Comment by briand44** [comment]
Reached out to Scott with some additional questions related to District name, College abbreviation, Contact info, etc.

**Comment by briand44** [comment]
Adding Scott's responses to some of my questions for visibility.

Do we need District Name? (e.g. Clinton Community College also displays Eastern Iowa Community College District. Marshalltown Community College also displays Iowa Valley Community College District)

>This is an area I’m not sure about. I think as CC’s have grown or combined over the years we’ve tried to include old + new names. I don’t know if this is necessary any more. It does look like we have a few combined still and we’d probably list the official name (Eastern Iowa Community College District), but would also need a place to list the specific community colleges in that district. So we’d only have one term page for Easter Iowa CC, but would need to make sure that the specific CC’s in EICC show up since a student would be familiar with the specific CC they’re attending and may not know that it’s part of a larger combination, but we won’t need to duplicate for each specific CC since the plan info would be the same.

Do we need College abbreviation? (North Iowa Area Community College as NIACC)
>Probably not

It appears each college has some sort of contact information. Assuming you would like us to store this in a text area since some are links and others contain individual contact info? Text area would probably allow the most flexibility in content.
>Yes, text area would probably be best for that.

Iowa Majors available for each college – not sure if this relationship will live on a college or a major or where but calling it out here.
>Yes, needed, but how it all hooks together is still up in the air.

**Comment by joewhitsitt** [comment]
Waiting to hear back on whether our solution is adequate for the college/district relationship. Currently we have it setup that the district would be the representing content in the community colleges list with the related locations part of the listing.

<img width="537" alt="Screen Shot 2022-03-23 at 11 33 25 AM" src="https://user-images.githubusercontent.com/4663676/159749660-1ebcc5c8-73c5-44dc-bae1-65b71d8b094f.png">


Other options:
- Redundant data and each community college location would be represented in the list.
- Wacky views rewrite where district are removed from the listing, faux entries for each location are added and those link to the district item.

**Comment by joewhitsitt** [comment]
>Currently we have it setup that the district would be the representing content in the community colleges list with the related locations part of the listing

We can move forward with this, but locations should be displayed below the title instead of the comma-separated.

Abbreviations aren't needed

**Comment by briand44** [comment]
Updated the IS with a link to field info provided by Admissions.

**Comment by joewhitsitt** [comment]
going to see how far i can get without a fresh db from prod.
