### ISSUE TITLE
Change Travis back to using Xenial

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#4979]
Follow-up from https://github.com/uiowa/uiowa/pull/4978

When https://travis-ci.community/t/php-7-4-is-broken-error-while-loading-shared-libraries-libargon2-so-1/12804 is no longer an issue.

**Comment by richardbporter** [comment]
I can try this out: https://travis-ci.community/t/php-7-4-is-broken-error-while-loading-shared-libraries-libargon2-so-1/12804/20

Xenial is what AC is so yea just confirming we want to replicate that.
