### ISSUE TITLE
Add date in footer text on Admissions Areas of Study pdf's

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#4990]
As an Admissions site owner, I would like the last updated date to appear on an Areas of Study PDF so that printed copies at the Visitor Center can be differentiated between what is recent and what is outdated.

**Comment by richardbporter** [comment]
It might be conducive to do this in combination with https://github.com/uiowa/uiowa/pull/4939. I don't think we want to put off that dependency update forever in case a future security update is required.

**Comment by bspeare** [comment]
We might want to add the date into this section: https://github.com/uiowa/uiowa/blob/main/docroot/sites/admissions.uiowa.edu/modules/admissions_core/templates/node--area-of-study--pdf.html.twig#L147-L153

**Comment by briand44** [comment]
lets leave #4939 out of this and we can prioritize that separately.
