### ISSUE TITLE
Pardot Integration

### ISSUE THREAD

**Issue by makurj** [uiowa/uiowa#500]
Description: Pardot Integration - Fields contained within fieldsets do not get passed from Drupal forms.

Example and possible solution: https://www.drupal.org/project/pardot/issues/2426179

Current workaround: remove fieldsets from the Pardot forms.

**Comment by joewhitsitt** [comment]
@makurj what is the status of this? can this be moved to the tippie site repo?

**Comment by makurj** [comment]
@joewhitsitt The user found a workaround so I will close this for now.
