### ISSUE TITLE
increase font size on form labels

### ISSUE THREAD

**Issue by bewoldt** [uiowa/uiowa#5000]
# Problem
Form field labels are currently set at .8rem and are output as 12.8px. I'd like to increase the font size to be more readable.

# Proposed solution

https://github.com/uiowa/uiowa/blob/d30dbaf0b5e7e071e1bd0fa4775a0c836ea3bfe7/docroot/themes/custom/uids_base/scss/components/form/forms.scss#L267-L272

Use the base font size variable instead of the small variable. This will bump it up to 16px.
`font-size: $base-font-size;`

**Comment by bspeare** [comment]
Related issue: https://github.com/uiowa/uiowa/issues/4954

**Comment by bewoldt** [comment]
Fixed with #5130
