### ISSUE TITLE
Relationship tag fields are extending off page

### ISSUE THREAD

**Issue by bewoldt** [uiowa/uiowa#5001]
# Problem
The new relationship tags are extending off screen.

<img width="460" alt="Screen Shot 2022-03-22 at 1 54 26 PM" src="https://user-images.githubusercontent.com/731952/159555105-74ef7292-ae7e-4444-a1c2-e2d712c08b64.png">

<img width="452" alt="Screen Shot 2022-03-22 at 1 55 53 PM" src="https://user-images.githubusercontent.com/731952/159555294-906845be-3891-440e-9f23-b260f4b430ed.png">

**Comment by joewhitsitt** [comment]
Closing in favor of https://github.com/uiowa/uiowa/issues/7470 which provides more detail.
