### ISSUE TITLE
Create structure to capture checkpoints specific to a community college and major.

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5003]
As a 2plus2 transfer student, I would like to be able to see what specific checkpoints and courses I need to complete at my community college to meet the University of Iowa requirements for that major.

# Additional Information
Here are examples of the requirements needed for an American Studies major through Eastern Iowa Community College compared to an American Studies major through Des Moines Area Community College.

https://2plus2.admissions.uiowa.edu/majors/eastern/american-studies.html
https://2plus2.admissions.uiowa.edu/majors/dmacc/american-studies.htm

The majority of information appears to be static with the exception of the community college checkpoints and University checkpoints.

This content will need to reference a community college and an area of study?

Here is a link provided by Admissions to some info about the fields needed here https://iowa-my.sharepoint.com/:w:/g/personal/katmills_uiowa_edu/EaQbdfwQQIJDgKED1dvJ7jQB143-R7ErxZPSZ8B019J6gA?e=j1aece. Provided 3/30/22

# Proposed Solution

**Comment by briand44** [comment]
Scott said he would provide a list of fields needed here. Also mentioned that they are fine with each section being a field and copying static content for each node rather than trying to store some information on a taxonomy term or elsewhere.

**Comment by joewhitsitt** [comment]
Is this is blocked until we know the basic organization of https://github.com/uiowa/uiowa/issues/4976?

**Comment by briand44** [comment]
I didn't think it was blocked because of that issue. It could be blocked until we get the list of fields from Scott but I assumed we could move forward without the CC taxonomy. I had bumped it down the priority list a bit because we didn't have that list yet from Scott.

**Comment by joewhitsitt** [comment]
Use default field content for Student Responsibilities text. TBD.

**Comment by briand44** [comment]
Updated the IS with a link provided by Admissions with field info.

**Comment by e-marie-w** [comment]
Just realized I never checked - were we thinking taxonomy term for this, or something else?

**Comment by joewhitsitt** [comment]
I was thinking content type for majors and that we would require a single community college and a single area of study which would become basis for the content type's title and the URL path (using a pre_save function similar to person). This would allow us to group all of the results for an area of student as well as all of the results for a community college.

**Comment by e-marie-w** [comment]
Oh cool, that pre_save function to make the title sounds awesome! And the content type does sound like a better fit. I can delete that taxonomy PR then.

**Comment by e-marie-w** [comment]
Would you be interested in pairing on this?

**Comment by joewhitsitt** [comment]
I am interested in this work, but focusing on other things at the moment. Maybe you can catch me up on Monday

**Comment by joewhitsitt** [comment]
As this is a new content type, there are a few things to consider/run through: https://wiki.uiowa.edu/display/drupaldev/Content+type+creation+notes

**Comment by e-marie-w** [comment]
I noticed there's a future slice in the epic about creating a 2+2 listing. Setting up a views block would be in the scope of that issue then and not this one, correct?

**Comment by joewhitsitt** [comment]
yeah, this is just to setup the structure to capture the data. if you want to look into hiding the taxonomy term view on community colleges since 2plus2 majors are showing up there, IMO, I feel like that would still be in scope.

**Comment by joewhitsitt** [comment]
Changed the URL pattern: https://github.com/uiowa/uiowa/pull/5120/commits/3eacfcc112c5afaf8c84a604f200c312d265950c

Changed the major's presave title to "At" https://github.com/uiowa/uiowa/pull/5120/commits/8e65825b4249cee9fb8df6c77d2ac944abbf42c2

**Comment by briand44** [comment]
It was requested that we lowercase "At".

**Comment by joewhitsitt** [comment]
>It was requested that we lowercase "At".

https://github.com/uiowa/uiowa/pull/5120/commits/d9e81a624489fbfd570277a8411813621fde9a57
