### ISSUE TITLE
meta description bugs?

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5004]
Grad Admissions Areas of Study aren't rendering any meta descriptions.
It looks like they are setup to use [node:body:value]. Should this just be [node:body]?

**Comment by joewhitsitt** [comment]
If so, we have a few instances to check/fix:

config/features/scholarship/metatag.metatag_defaults.node__scholarship.yml
config/sites/admissions.uiowa.edu/metatag.metatag_defaults.node__student_profile.yml
config/sites/grad.admissions.uiowa.edu/metatag.metatag_defaults.node__area_of_study.yml
config/sites/admissions.uiowa.edu/metatag.metatag_defaults.node__area_of_study.yml

**Comment by briand44** [comment]
Yeah, not sure that is the issue but I am getting even more confused about some meta descriptions after poking around a bit. Not sure how https://admissions.uiowa.edu/node/731 is working?

**Comment by briand44** [comment]
I am not seeing meta descriptions on Admissions site for Scholarships content or Area of study content or student profiles

**Comment by joewhitsitt** [comment]
>Not sure how https://admissions.uiowa.edu/node/731 is working?

https://admissions.uiowa.edu/admin/config/search/metatag/node__student_profile?destination=/admin/config/search/metatag has `[node:body:value]`

731 has `[node:field_teaser:value]` as an override, but the field_teaser value itself is blank so it is reverting back to the meta tag default and grabbing the body value.

**Comment by briand44** [comment]
According to ^^ that would suggest [node:body:value] is an acceptable meta tag token then.

**Comment by briand44** [comment]
https://admissions.uiowa.edu/node/731 is a "Person" not a student profile... It looks like it is setup to use [node:field_teaser:value] https://admissions.uiowa.edu/admin/config/search/metatag/node__person?destination=/admin/config/search/metatag

But there is no teaser so why is it outputting the body for the meta tag description?

**Comment by joewhitsitt** [comment]
Ah. Sorry. https://github.com/uiowa/uiowa/blob/main/docroot/profiles/custom/sitenow/sitenow.profile#L1074

**Comment by joewhitsitt** [comment]
>Should this just be [node:body]?

Long story short. Yes. Pushing a fix for all shortly.

**Comment by briand44** [comment]
Curious on if [node:teaser:value] is acceptable or not? Saw mixed usage related to this as well. Not trying to increase scope here though.

**Comment by joewhitsitt** [comment]
It is an acceptable token but it would be nice to be consistent at some point and remove that extra logic.

<img width="529" alt="Screen Shot 2022-03-23 at 3 27 07 PM" src="https://user-images.githubusercontent.com/4663676/159789800-eac79c10-5a2d-44be-9d3f-68b4d8e7f0b3.png">

There was talk about moving back to a body/summary field setup but I don't think an issue was created.
