### ISSUE TITLE
Determine if smart_date hides wrapper label

### ISSUE THREAD

**Issue by GaryRidgway** [uiowa/uiowa#5009]
Remove if smart_date hides this datetime wrapper label. See
https://github.com/uiowa/uiowa/blob/431392814f38fcdbdfb6d5d595505dfec23cbf66/docroot/modules/custom/grad_custom/grad_thesis_defense/grad_thesis_defense.module#L53

**Comment by joewhitsitt** [comment]
Related issue: https://github.com/uiowa/uiowa/issues/2899
