### ISSUE TITLE
Workbench Access

### ISSUE THREAD

**Issue by makurj** [uiowa/uiowa#501]
Editor role cannot view or edit unpublished pages. 

Also, the "add editor" button takes you to masquerade unless the page is added to a menu. Screen recording attached in email to Brian.

Issue link for unpublished pages: https://www.drupal.org/project/workbench_access/issues/1798584

**Comment by joewhitsitt** [comment]
@makurj what is the status of this? can this be moved to the tippie site repo?

**Comment by makurj** [comment]
@joewhitsitt The solution still eludes me so it's still an issue.

**Comment by richardbporter** [comment]
https://github.com/ITS-UofIowa/tippie.uiowa.edu/issues/19
