### ISSUE TITLE
Utilize body summary field on v3 page.

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#5025]
# Issue

The v3 page body field has a summary field which is not being used for anything. This can be confusing to users.

We have code that uses the body value if field_teaser is not filled out.
https://github.com/uiowa/uiowa/blob/d121ad897e9b45cd3cda38d65b52fd3c2d5ec377/docroot/profiles/custom/sitenow/sitenow.profile#L1083-L1101

# Proposed solution

- Audit to check for filled summary fields? If this is a small list, maybe we can work with folks to prevent a collision when field_teaser is migrated over.
- Use that same code to use the summary first if provided.
- Refactor body field on article/person to use body with summary option. Since this is a different field type, it will probably require an update hook.
- Account for custom content types which use field teaser, make sure they have a body/summary to move to
  - page, person, article, event, housing.uiowa.edu - residence_hall
- Remove field_teaser from v3 default content types and use summary field instead (v2 page doesn't have a body field) - Via update hook, take the field_teaser value and migrate it to the summary field. Flag and follow-up with collisions if the summary is also filled out?
- To make this change more visual and easier for editors to switch to, expand the summary field by default. Could leave the field group for field_teaser around with a note that it has moved to the summary field.
- Future slice
  - Remove field_teaser entirely once all custom content types have been refactored and v2 is no longer

**Comment by quamsta** [comment]
With our old SilverStripe sites, the default behavior was to use the equivalent "summary field" to populate both the meta description and the shortened teaser that would appear on list-like pages if it was filled out, otherwise we'd try to pull in some truncated body text for these purposes.

The two separate fields in SiteNow ("Content description" and "Summary") confuse me a bit. Is it possible to reconcile and merge the two since they seem functionally similar, if not identical? Currently it seems like "Content description" is used in meta descriptions and lists, so I'm not sure where "Summary" would appear.

**Comment by joewhitsitt** [comment]
> Is it possible to reconcile and merge the two since they seem functionally similar, if not identical? Currently it seems like "Content description" is used in meta descriptions and lists, so I'm not sure where "Summary" would appear.

That is kind of what I was getting at with the future slices. Ultimately removing field_teaser.

**Comment by joewhitsitt** [comment]
Marking as a bug because the summary is field that can be populated editors but it is not being used/rendered which is confusing editors.

**Comment by briand44** [comment]
Grooming convo... Let's audit and learn more.

**Comment by joewhitsitt** [comment]
>Future slice
>>Remove field_teaser entirely once all custom content types have been refactored and v2 is no longer

Leave this issue open for this or split it off as part of winddownv2?

**Comment by briand44** [comment]
Let's close it. New issue https://github.com/uiowa/uiowa/issues/6923
