### ISSUE TITLE
Update dompdf/dompdf to latest version

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#5027]
As noted in [dompdf/dompdf](https://github.com/uiowa/uiowa/pull/4447), there are some issues with the admission PDFs when we update `dompdf/dompdf` to the latest version. 

# Problem 

-  Links render multiple times and the margin/spacing is slightly different.
-  It is also adding `-` to random words nearby links as well.

# Proposed solution

Use the dependabot issue https://github.com/uiowa/uiowa/pull/5026 to test on the admissions site and make changes in https://github.com/uiowa/uiowa/blob/main/docroot/sites/admissions.uiowa.edu/modules/admissions_core/sass/pdf.scss.

**Comment by richardbporter** [comment]
I've made code changes to #5026 so we own it now and can essentially use it as a feature branch for this issue.

```
git fetch
git checkout dependabot/composer/dompdf/dompdf-1.2.1
git pull --set-upstream origin dependabot/composer/dompdf/dompdf-1.2.1 
ddev composer install
ddev blt sync --site admissions.uiowa.edu
ddev drush @admissions.local uli /areas-of-study/print-links
```

Compare with https://admissions.uiowa.edu/areas-of-study/print-links

Add /debug to entity print URLs to inspect CSS.

Example
Prod
<img width="1048" alt="Screen Shot 2022-04-14 at 11 41 02 AM" src="https://user-images.githubusercontent.com/1068523/163434920-4bc6b232-7a78-4982-86e8-27b817446a44.png">

Local
<img width="1048" alt="Screen Shot 2022-04-14 at 11 41 10 AM" src="https://user-images.githubusercontent.com/1068523/163434939-c484b0e7-27d1-43d9-b8c4-3ec9e61e15fb.png">

Looks like there is something we need to change with heading styles.

**Comment by richardbporter** [comment]
I was running into https://github.com/drud/ddev/issues/3741 so I added a custom web command for yarn in 8a0c35c71d04b8fbc2906737c9a50e4fc806518a. After that, I'm able to run `ddev yarn workspace admissions_core run sass-watch`.

**Comment by richardbporter** [comment]
>It is also adding - to random words nearby links as well.

Good find. I was able to get around using the suggestion in https://github.com/dompdf/dompdf/issues/2445#issuecomment-988764059 to override that config in 848a4c2 and 8634605 since `isFontSubsettingEnabled` is not part of the entity_print dompdf config.

**Comment by richardbporter** [comment]
>Links render multiple times and the margin/spacing is slightly different.

@bspeare do you remember an AoS where this was happening?

**Comment by richardbporter** [comment]
I think I've got #5026 fairly close to matching the existing PDFs although my CSS might not be ideal. There is a slight line-height difference that I can track down though.

**Comment by richardbporter** [comment]
Noticed a page break issue on some AoS:
<img width="1048" alt="Screen Shot 2022-04-15 at 8 24 02 AM" src="https://user-images.githubusercontent.com/1068523/163577066-a9bc500d-4641-49c7-8768-1d29b73d5e44.png">

Resolved with [8feeb59](https://github.com/uiowa/uiowa/pull/5026/commits/8feeb59c60c7a790357729711413daff2b7134a4). https://github.com/dompdf/dompdf/releases/tag/v1.1.0 mentions improved page-break handling.

**Comment by bspeare** [comment]
Noticing these boxes on a lot of PDFs on prod and local.  Any idea why these are showing up? https://admissions.uiowa.ddev.site/print/pdf/node/3696

<img width="867" alt="Screen Shot 2022-04-15 at 9 24 59 AM" src="https://user-images.githubusercontent.com/1036433/163582999-df8811bb-1fad-4ed0-bb0e-1f7cd119364b.png">

That same one is clashing with the footer too:

<img width="781" alt="Screen Shot 2022-04-15 at 9 29 36 AM" src="https://user-images.githubusercontent.com/1036433/163583114-c8aeac99-5024-4480-92e1-d3c9db871503.png">

**Comment by richardbporter** [comment]
> Noticing these boxes on a lot of PDFs on prod and local. Any idea why these are showing up? https://admissions.uiowa.ddev.site/print/pdf/node/3696
> 
> <img alt="Screen Shot 2022-04-15 at 9 24 59 AM" width="867" src="https://user-images.githubusercontent.com/1036433/163582999-df8811bb-1fad-4ed0-bb0e-1f7cd119364b.png">

I'm able to get rid of those by deleting the spaces around those links and retyping it. Maybe some sort of copy/paste from Word issue?

**Comment by bspeare** [comment]
That's great! Probably copy/paste issues.

**Comment by joewhitsitt** [comment]
Wasn't the careers and outcomes data migrated?

**Comment by richardbporter** [comment]
> That same one is clashing with the footer too:

360b991 seems to fix that and looks to match the appearance of the prod line-height closer. I suppose that footer clash could be happening elsewhere though.

**Comment by richardbporter** [comment]
> Wasn't the careers and outcomes data migrated?

Possibly. I don't see any special characters in the source. I can dig a bit more.

**Comment by richardbporter** [comment]
> > Wasn't the careers and outcomes data migrated?
> 
> Possibly. I don't see any special characters in the source. I can dig a bit more.

Seems like a unicode character for NNBSP. I briefly looked into an update hook to replace it but it might just be easier to delete and re-add spaces where this is happening.

**Comment by richardbporter** [comment]
Marked #5026 ready for review. I'd be inclined to call it close enough.
