### ISSUE TITLE
IISC - Create content type for migrating Partner content.

### ISSUE THREAD

**Issue by e-marie-w** [uiowa/uiowa#5031]
## Story 

As an IISC editor/webmaster, I want to display information about our Project Partners. 

## Solution

Create a Partner content type with the following fields:
- Title (text)
- Photo (image)
- Description (text, long)
- Related links (URL field)
- References section
- - Related individuals (reference People content)
- - Iowa county (currently a checkbox list of all 99, open to suggestions)

Additionally, the displayed page (view?) for Partner content shows 'Related News' (articles tagged with the partner name) and 'Related Projects' (projects tagged with the partner name).

**Comment by joewhitsitt** [comment]
>Iowa county (currently a checkbox list of all 99, open to suggestions)

I think this should be a configuration entity like we did for academic unit. In D7, we had a module that we could use in a very similar fashion. This way other sites can use it in the future which came up often in D7.

Or it should be like the states list that we use for a couple sites and plan on moving to core for more to use: https://github.com/uiowa/uiowa/issues/2764

**Comment by mjoneill** [comment]
Next steps:

* Easy slice is to do the "allowed options" list/allowed values function (similar to states on admissions). If that runs into trouble, we come back and do something else.

**Comment by bspeare** [comment]
Do we want to include this part in this work?

- the displayed page (view?) for Partner content shows 'Related News' (articles tagged with the partner name)

**Comment by e-marie-w** [comment]
> Do we want to include this part in this work?
> 
> * the displayed page (view?) for Partner content shows 'Related News' (articles tagged with the partner name)

At the time I wasn't sure if the News and Partner content needed to be fields in the actual content type to be part of the view. But I understand views better now and don't think it's needed.

So no, the view is not in scope, and I'll create a separate issue to set up the views for all the new content types once they're created (since they all reference each other anyways).
