### ISSUE TITLE
Remove uiowa_core hook_config_schema_info_alter implementation

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#5034]
This was needed to ensure the same export order.

Blocked by https://www.drupal.org/project/drupal/issues/2855675.

[docroot/modules/custom/uiowa_core/uiowa_core.module:25](https://github.com/uiowa/uiowa/blob/bba45460a6924a278b748d0599fc8e81bc7ce3fd/docroot/modules/custom/uiowa_core/uiowa_core.module#L17-L26)

**Comment by pyrello** [comment]
I don't think the workaround that this issue was supposed to remove is necessary anymore. I'm removing it in #6054 and we can re-implement it if we discover issues with exports again.
