### ISSUE TITLE
IISC - Customize Article content type

### ISSUE THREAD

**Issue by e-marie-w** [uiowa/uiowa#5037]
## Story
As an IISC editor/webmaster, I want to associate articles with the people, partners, and projects mentioned in them. This allows me to display relevant news on the person, partner, or project page. 

## Solution

- Add 'Related Partners' field that allows users to add existing Partners
- Add 'Related Projects' field that allows users to add existing Projects
- Add 'Related Individuals' field that allows users to add existing People

**Comment by briand44** [comment]
Use one field that allows referencing multiple bundles.

**Comment by briand44** [comment]
Sean getting clarity on single field vs separate fields.

**Comment by joewhitsitt** [comment]
_if_ we do a single field for this, I'd love it if we keep the door open for it to be merged into default config someday. HR has a similar field on their page content type: https://github.com/uiowa/uiowa/blob/main/config/sites/hr.uiowa.edu/field.storage.node.field_related_content.yml

_if_ this single field is supposed to be broken out into separate groups on the full node, one solution would be to preprocess to explode and group into extra fields. https://github.com/uiowa/uiowa/blob/main/docroot/sites/admissions.uiowa.edu/modules/admissions_core/admissions_core.module#L27

**Comment by pyrello** [comment]
Based on this example (thanks @joewhitsitt!) it looks like the related elements are not displayed on the article page: https://iisc.uiowa.edu/laurian-receives-faculty-service-award-iowa-initiative-sustainable-communities. So it seems like we can move forward with trying out a single field.

**Comment by briand44** [comment]
>Based on this example (thanks @joewhitsitt!) it looks like the related elements are not displayed on the article page: https://iisc.uiowa.edu/laurian-receives-faculty-service-award-iowa-initiative-sustainable-communities. So it seems like we can move forward with trying out a single field.

The article referenced above does not contain any references. I created an article on dev and the references do appear.
![Screen Shot 2022-05-10 at 3 30 14 PM](https://user-images.githubusercontent.com/1017022/167716773-aba34cbf-643b-4d61-bb23-b34cb69224df.png)

**Comment by pyrello** [comment]
To test out using a single field, I tried adding this to #5258, along with a view that using the content type as a grouping field to see if that would allow for listing out the different content types separately. However, my view isn't currently working.
