### ISSUE TITLE
IISC - Create Project content type

### ISSUE THREAD

**Issue by e-marie-w** [uiowa/uiowa#5054]
## Story

As an IISC editor/webmaster, I want a way to showcase our students' projects, including all the details such as what school year was it, who led it, what partner(s) were involved, etc.

## For reference

https://iisc.uiowa.edu/iowa-city-solar-study

## Solution
Create a content type with the following fields:

- Title (text)
- Body (text, long)
- Image (single)
- College/Department (taxonomy)
- Deliverables - usually pdfs
- Academic Year - formatted as 2020-2021 (taxonomy)
- Project Partner (reference Partners content) - If the Partners content type doesn't exist yet, then we can add this field and set up display and form display for it in #5031 
- Led by (reference People content)
- Project Links (URL field)
- Tags (tags)

**Comment by briand44** [comment]
Create display for this information as well as part of this issue. Could output similar to a person with image/info in side region. Possibly large featured image like articles?

**Comment by briand44** [comment]
May need to hold on the reference to partner or other references referencing content types that do not exist. Any term references or other references to content types that do exist should be in scope for this issue.

**Comment by briand44** [comment]
This content will be migrated in the future

**Comment by briand44** [comment]
May be worth looking into how housing is handling academic year. Could potential handle this programmatically and have it auto update?

**Comment by briand44** [comment]
Any view displays could happen as part of a follow up issue. Scoping to just the structure and node display.

**Comment by pyrello** [comment]
I'm going to start working on this.
