### ISSUE TITLE
Visual indicator that tells user that they can click into pages from teaser views

### ISSUE THREAD

**Issue by quamsta** [uiowa/uiowa#5057]
# Story

Similar to/second slice of: https://github.com/uiowa/uiowa/issues/4372

As a user, I'd like to be able to see an indicator on an article teaser within the tag/taxonomy views and other lists that shows that an article is clickable/tappable. 

Currently it's not readily apparent that these articles are only teasers and are able to be clicked into to see more information:

<img width="1379" alt="Screen Shot 2022-03-29 at 8 28 33 AM" src="https://user-images.githubusercontent.com/472923/160622158-c6696fa8-83d8-4fbe-9d4b-5ba7bb27f4c5.png">

# Proposed solution

Expand the scope of the solution in this issue: https://github.com/uiowa/uiowa/issues/4372 and enable the arrow button on article lists.

Copied from: https://github.com/uiowa/uiowa/issues/4372

## List blocks (People, Articles)

- Add checkbox to display a button below each item
  - If box is checked, allow user to add custom link text like "Continue Reading"
  - If no link text is provided, then circle button will be default

Original solution:
<details>
I think adding any of the following to an individual article teaser may help alleviate this:

- Underlined link in the headline indicating that it's clickable (may be less visually appealing, but more functional)
- A "Continue Reading" button (may have accessibility issues, but could be done in a CSS psuedo-class, e.g. `:after { content: "Continue reading" }` to prevent screen readers from repeating "Continue reading" over and over).
- An ellipsis character after the body of the teaser (may be the most elegant, probably also could be done in a pseudo-class
</details>

**Comment by quamsta** [comment]
Thinking about scoping this issue to only in the taxonomy lists that appear when clicking on a tag.

**Comment by quamsta** [comment]
Another proposed solution for this:

Instead of the user manually adjusting items in their list blocks to display arrows, provide them a way to turn on arrows for each content type's teaser automatically.

## Page config (`/admin/config/sitenow/uiowa-pages`)
![Screen Shot 2022-04-27 at 4 43 44 PM](https://user-images.githubusercontent.com/472923/165636703-fb5364ca-9209-4c65-9017-52f6b2b0273d.png)

## Person config (`/admin/config/sitenow/uiowa-people`)
![Screen Shot 2022-04-27 at 4 43 32 PM](https://user-images.githubusercontent.com/472923/165636705-fb366f0a-fcee-4305-a8e6-49cca4f5576f.png)

This solution has a few benefits:

- Shows arrows on all teasers in most contexts that only adjusting list blocks may not cover, including taxonomy and other filters.
- It may be a lot to ask the user to customize individual items in their lists. This solution would give them an option to provide an arrow if they're using a lot of automatic tag-based navigation options.
- Could be later be adjusted with the original proposed solution's "Continue reading"-like field in list blocks in a later slice if we want to give the user the ability to customize the appearance of the arrow and add text to it.

Curious to hear the group's thoughts!

Any thoughts on this idea?

**Comment by bspeare** [comment]
I think that this sounds like a good idea, but when it comes to the featured content block that blends together content types - wouldn't that create inconsistent usage of the arrows?   Some content types could have it turned on while others have it turned off?

**Comment by bspeare** [comment]
We are also planning on adding an option to the card block to turn the arrow off: https://github.com/uiowa/uiowa/issues/4788.  Would it be weird to have multiple ways to turn the arrow on and off?

**Comment by joewhitsitt** [comment]
I am fine with moving in this direction with the idea that https://github.com/uiowa/uiowa/issues/4788 still happens for static card blocks. These are different enough that I think the toggle per card makes sense. 

Though this proposed solution provides consistency across the site, it fragments any pattern across campus. Something to be aware of.

Featured content sticks out to me as a curated list of teasers that the editor might want more control over, but I am not sure how it would be done without complicating the entity references on that block. That said, each content type's teaser is already different (event, person, article) so I don't think inconsistency here is new. It will just have to be an editorial decision to embrace the same setting for all types if featured content is to be used heavily.

I don't think we need to build in all of this documentation into the configuration forms. Teasers can be further defined elsewhere (Docs/training)

**Comment by quamsta** [comment]
PR: https://github.com/uiowa/uiowa/pull/5094


@bspeare 

> I think that this sounds like a good idea, but when it comes to the featured content block that blends together content types - wouldn't that create inconsistent usage of the arrows? Some content types could have it turned on while others have it turned off?

This inconsistency is a possibility, however I haven't seen featured content that mixes together two content types. I've seen featured content blocks featuring people by tag, and pages separately but not both. But this could be resolved by the webmaster if they enable or disable the indicator icons for both content types. 

> We are also planning on adding an option to the card block to turn the arrow off: #4788. Would it be weird to have multiple ways to turn the arrow on and off?

As @joewhitsitt  said, I think it's fine that there's granular control over the arrows in different contexts. As we've discussed in the issue, the arrows make sense in some contexts, but not in others. If there's content where it doesn't make sense contextually to have the arrows, the more options we have to disable them, the better, imho.

@joewhitsitt 

> I am fine with moving in this direction with the idea that #4788 still happens for static card blocks. These are different enough that I think the toggle per card makes sense.

Agreed.

> Though this proposed solution provides consistency across the site, it fragments any pattern across campus. Something to be aware of.

My initial pass at this was just to flip them on universally and I felt it was in line with trying to maintain a sense of consistency, but providing options to the webmaster is probably the route we'll need to go on for this.

> Featured content sticks out to me as a curated list of teasers that the editor might want more control over, but I am not sure how it would be done without complicating the entity references on that block. That said, each content type's teaser is already different (event, person, article) so I don't think inconsistency here is new. It will just have to be an editorial decision to embrace the same setting for all types if featured content is to be used heavily.

Agreed.

> I don't think we need to build in all of this documentation into the configuration forms. Teasers can be further defined elsewhere (Docs/training)

I scaled back some of the documentation in the PR (namely the "What is a teaser?" part), but I left in the screenshot of what the option does, just to give a good hint about what it does to the user. I feel that's important enough for them to see in order to make an editorial decision here.

**Comment by joewhitsitt** [comment]
>I left in the screenshot of what the option does, just to give a good hint about what it does to the user.

We have avoided screenshots in the past because the theme is always changing and things become out of date quickly. Before Alex's training video we also held off on recording one for similar reasons. We have previously expressed interest in supplementing SiteNow v3 documentation with example blocks along side so that changes are immediately reflected. https://github.com/uiowa/uiowa/issues/5175

**Comment by quamsta** [comment]
@joewhitsitt Sounds good, I'll remove the screenshots and I think this should be ready?

**Comment by bspeare** [comment]
@quamsta just wanted to check that you saw this comment: https://github.com/uiowa/uiowa/pull/5094#issuecomment-1119035627.
