### ISSUE TITLE
News migration for Iowa JPEC.

### ISSUE THREAD

**Issue by mjoneill** [uiowa/uiowa#5059]
Anything from 2019 forward.  No need to migrate news content prior to 2019.

They would like to launch by May 1.

Contacts: 
- Westlake, Casey N <casey-westlake@uiowa.edu>
- Miller, Darren <darren-miller@hawkeyesports.com>

**Comment by mjoneill** [comment]
Tagging @briand44 for visibility.

**Comment by briand44** [comment]
I reached out to the contacts with questions before we can move forward on this. Blocking until we hear back.

**Comment by briand44** [comment]
>We should only be migrating over news articles that were created in 2019 or newer correct? 

YES

>Would you like us to migrate over tags associated with news articles? 

If it is a chore, that is not necessary. If it is easy, sure, bring them over.
Lets plan to migrate these tags (bdickey)

>We noticed there are a few news articles that have been created on the new site already. If they exist on the old site as well there may be duplicates once we run the migration. Should we delete all articles on the new site before we run the migration or should those stay? 

I would prefer the stories on the new site stay since they have been formatted already.

>Our url pattern for news on SiteNow v3 is a little different that your current paths. We can create redirects from your existing paths to the new paths as part of the migration. Would you like us to do that?

YES

>The current site has a featured checkbox. That is not something that exists on the new site. Do we need to somehow account for that as part of this migration? We could potentially create a featured tag for those articles that are featured if that would help? I’m not sure I understand this question. 

Would it be OK if you made a recommendation and we follow that suggestion?

I'm getting more clarification on how they intend to use "featured" (bdickey)

>The current site also has a date field. Is that just used to output the date created? There is also an authored date on the current site and the new site to keep track of when content is created. Curious if we should use the “date” field or the “authored on” field to map to the “authored date” on the new site?

If I understand this correctly, we should keep the date field. I story might be written a week in advance and not go live for seven days. We would want the date it actually goes live.

**Comment by joewhitsitt** [comment]
Just to note there are less than 2 content overview pages (<100) of news items that are newer than 2019.

**Comment by joewhitsitt** [comment]
It sounds like Tippie doesn't consider this a high of priority as their launch.

**Comment by briand44** [comment]
Let's ignore mapping the featured field.

**Comment by joewhitsitt** [comment]
created:field_news_date

**Comment by cory-skeers** [comment]
One extra consideration: the previously manually migrated articles won't have redirects created for them. There are only 12 in total, so it's probably faster to create manually than create an automated solution.
