### ISSUE TITLE
Investigate duplicate events bug

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5060]
Occasionally, we have received reports of duplicate events on content.uiowa.edu and events.uiowa.edu. We should investigate to see if we can replicate this issue and understand what is causing this. 

Some examples of duplicates:
https://content.uiowa.edu/node/91446/edit - 2022-03-25 15:05:39 -0500 (has the -0 URL and a redirect from the original URL)
https://content.uiowa.edu/node/91451/edit - 2022-03-25 15:05:49 -0500

https://content.uiowa.edu/node/68656/edit - 2021-03-23 10:36:21 -0500 (looks like this was cloned)
https://content.uiowa.edu/node/87891/edit - 2022-02-05 14:07:09 -0600 (has the -0 URL)
https://content.uiowa.edu/node/87896/edit - 2022-02-05 14:07:13 -0600 (has a -1 URL and a redirect from the -0 URL)

https://content.uiowa.edu/node/90171/edit - 2022-03-07 15:43:34 -0600 (has the -0 URL and a redirect from the original URL)
https://content.uiowa.edu/node/90176/edit - 2022-03-07 15:43:49 -0600

Findings so far:

- Not every event causes duplication.
- In known cases, they are created less than a minute apart.
- Quickly double-clicking save can create a duplicate event (easy to do in Safari), but the time between is much shorter and doesn't cause the redirect issue.
- Clone functionality exists but changes the title so it seems a bit much for the issue. Editor would have to modify the title and then save.

**Comment by joewhitsitt** [comment]
Other reports here: https://iowaweb.slack.com/archives/C0KMREKNU/p1647525467200159

**Comment by joewhitsitt** [comment]
Thinking back through the recent changes since this only started being reported this year, I wonder if this has to do with the changes to the bulk approve functionality?

**Comment by richardbporter** [comment]
I found the thread related to the dashboard changes in the shared inbox sent folder - search for "Content Hub 1210852" to find it. 

Here is what I wrote back in November regarding the changes we were proposing:
>Essentially, the pending and upcoming event views have been merged into one. The view lists the state of each event and allows sorting by state (approved, draft, etc.) and does not use aggregation. The aggregation change means that events will show up multiple times for each tagged unit that a person is a unit admin for. This might seem odd at first but it’s actually more transparent than how the site currently functions – unit admins have to approve the same event multiple times for each tagged unit they are an admin for.

**Comment by joewhitsitt** [comment]
@richardbporter do you recall anything about this "Force" behavior. Looks scary. My hope is that this isn't related, but just throwing out ideas

<img width="876" alt="Screen Shot 2022-03-29 at 10 26 06 AM" src="https://user-images.githubusercontent.com/4663676/160707994-1cb12afb-bdd9-479b-ae13-bba0319443c6.png">

**Comment by richardbporter** [comment]
> @richardbporter do you recall anything about this "Force" behavior. Looks scary. My hope is that this isn't related, but just throwing out ideas

I remember seeing it but I don't think I changed anything about it. Wasn't really clear what it did. :/

**Comment by joewhitsitt** [comment]
```
Notice: Trying to access array offset on value of type null in shs_field_widget_afterbuild() (line 344 of /Users/jwhitsit/acquia/uiowa702-dev/docroot/sites/content.uiowa.edu/modules/contrib/shs/shs.module).
Notice: Trying to access array offset on value of type null in shs_field_widget_afterbuild() (line 344 of /Users/jwhitsit/acquia/uiowa702-dev/docroot/sites/content.uiowa.edu/modules/contrib/shs/shs.module).
Notice: Trying to access array offset on value of type null in shs_field_widget_afterbuild() (line 344 of /Users/jwhitsit/acquia/uiowa702-dev/docroot/sites/content.uiowa.edu/modules/contrib/shs/shs.module).
Notice: Trying to access array offset on value of type null in hs_menu_hierarchical_select_valid_item() (line 219 of /Users/jwhitsit/acquia/uiowa702-dev/docroot/profiles/sitenow/modules/contrib/hierarchical_select/modules/hs_menu.module).
Notice: Trying to access array offset on value of type null in hs_menu_hierarchical_select_valid_item() (line 219 of /Users/jwhitsit/acquia/uiowa702-dev/docroot/profiles/sitenow/modules/contrib/hierarchical_select/modules/hs_menu.module).
Notice: Trying to access array offset on value of type null in hs_menu_hierarchical_select_valid_item() (line 219 of /Users/jwhitsit/acquia/uiowa702-dev/docroot/profiles/sitenow/modules/contrib/hierarchical_select/modules/hs_menu.module).
Notice: Trying to access array offset on value of type null in hs_menu_hierarchical_select_valid_item() (line 219 of /Users/jwhitsit/acquia/uiowa702-dev/docroot/profiles/sitenow/modules/contrib/hierarchical_select/modules/hs_menu.module).
Notice: Trying to access array offset on value of type null in hs_menu_hierarchical_select_valid_item() (line 219 of /Users/jwhitsit/acquia/uiowa702-dev/docroot/profiles/sitenow/modules/contrib/hierarchical_select/modules/hs_menu.module).
Notice: Trying to access array offset on value of type null in hs_menu_hierarchical_select_valid_item() (line 219 of /Users/jwhitsit/acquia/uiowa702-dev/docroot/profiles/sitenow/modules/contrib/hierarchical_select/modules/hs_menu.module).
Notice: Trying to access array offset on value of type null in hs_menu_hierarchical_select_valid_item() (line 219 of /Users/jwhitsit/acquia/uiowa702-dev/docroot/profiles/sitenow/modules/contrib/hierarchical_select/modules/hs_menu.module).
Notice: Trying to access array offset on value of type null in hs_menu_hierarchical_select_valid_item() (line 219 of /Users/jwhitsit/acquia/uiowa702-dev/docroot/profiles/sitenow/modules/contrib/hierarchical_select/modules/hs_menu.module).
Notice: Trying to access array offset on value of type null in hs_menu_hierarchical_select_valid_item() (line 219 of /Users/jwhitsit/acquia/uiowa702-dev/docroot/profiles/sitenow/modules/contrib/hierarchical_select/modules/hs_menu.module).
Notice: Trying to access array offset on value of type null in hs_menu_hierarchical_select_valid_item() (line 219 of /Users/jwhitsit/acquia/uiowa702-dev/docroot/profiles/sitenow/modules/contrib/hierarchical_select/modules/hs_menu.module).
Notice: Trying to access array offset on value of type null in hs_menu_hierarchical_select_valid_item() (line 219 of /Users/jwhitsit/acquia/uiowa702-dev/docroot/profiles/sitenow/modules/contrib/hierarchical_select/modules/hs_menu.module).
Notice: Trying to access array offset on value of type null in hs_menu_hierarchical_select_valid_item() (line 219 of /Users/jwhitsit/acquia/uiowa702-dev/docroot/profiles/sitenow/modules/contrib/hierarchical_select/modules/hs_menu.module).
Warning: count(): Parameter must be an array or an object that implements Countable in paragraphs_field_widget_embed_validate() (line 708 of /Users/jwhitsit/acquia/uiowa702-dev/docroot/profiles/sitenow/modules/contrib/paragraphs/paragraphs.field_widget.inc).
Warning: count(): Parameter must be an array or an object that implements Countable in paragraphs_field_widget_embed_validate() (line 708 of /Users/jwhitsit/acquia/uiowa702-dev/docroot/profiles/sitenow/modules/contrib/paragraphs/paragraphs.field_widget.inc).
Warning: count(): Parameter must be an array or an object that implements Countable in paragraphs_field_widget_embed_validate() (line 708 of /Users/jwhitsit/acquia/uiowa702-dev/docroot/profiles/sitenow/modules/contrib/paragraphs/paragraphs.field_widget.inc).
Warning: count(): Parameter must be an array or an object that implements Countable in paragraphs_field_widget_embed_validate() (line 708 of /Users/jwhitsit/acquia/uiowa702-dev/docroot/profiles/sitenow/modules/contrib/paragraphs/paragraphs.field_widget.inc).
Warning: count(): Parameter must be an array or an object that implements Countable in paragraphs_field_widget_embed_validate() (line 708 of /Users/jwhitsit/acquia/uiowa702-dev/docroot/profiles/sitenow/modules/contrib/paragraphs/paragraphs.field_widget.inc).
Notice: Trying to access array offset on value of type null in _event_sync() (line 100 of /Users/jwhitsit/acquia/uiowa702-dev/docroot/sites/content.uiowa.edu/modules/custom/content_hub_core/inc/content_hub_core.event_sync.inc).
Notice: Trying to access array offset on value of type null in _event_sync() (line 100 of /Users/jwhitsit/acquia/uiowa702-dev/docroot/sites/content.uiowa.edu/modules/custom/content_hub_core/inc/content_hub_core.event_sync.inc).
Notice: Trying to access array offset on value of type null in _event_sync() (line 100 of /Users/jwhitsit/acquia/uiowa702-dev/docroot/sites/content.uiowa.edu/modules/custom/content_hub_core/inc/content_hub_core.event_sync.inc).
Notice: Trying to access array offset on value of type null in _event_sync() (line 100 of /Users/jwhitsit/acquia/uiowa702-dev/docroot/sites/content.uiowa.edu/modules/custom/content_hub_core/inc/content_hub_core.event_sync.inc).
Notice: Trying to access array offset on value of type null in _event_sync() (line 101 of /Users/jwhitsit/acquia/uiowa702-dev/docroot/sites/content.uiowa.edu/modules/custom/content_hub_core/inc/content_hub_core.event_sync.inc).
Notice: Trying to access array offset on value of type null in _event_sync() (line 102 of /Users/jwhitsit/acquia/uiowa702-dev/docroot/sites/content.uiowa.edu/modules/custom/content_hub_core/inc/content_hub_core.event_sync.inc).
Warning: Creating default object from empty value in _event_sync() (line 158 of /Users/jwhitsit/acquia/uiowa702-dev/docroot/sites/content.uiowa.edu/modules/custom/content_hub_core/inc/content_hub_core.event_sync.inc).
Notice: Trying to access array offset on value of type null in _event_sync() (line 211 of /Users/jwhitsit/acquia/uiowa702-dev/docroot/sites/content.uiowa.edu/modules/custom/content_hub_core/inc/content_hub_core.event_sync.inc).
Notice: Undefined index: AH_SITE_ENVIRONMENT in _event_sync() (line 221 of /Users/jwhitsit/acquia/uiowa702-dev/docroot/sites/content.uiowa.edu/modules/custom/content_hub_core/inc/content_hub_core.event_sync.inc).
Notice: Undefined index: AH_SITE_ENVIRONMENT in _event_sync() (line 225 of /Users/jwhitsit/acquia/uiowa702-dev/docroot/sites/content.uiowa.edu/modules/custom/content_hub_core/inc/content_hub_core.event_sync.inc).
The system cannot publicly refresh the changes you just made, because of the following error conditions:

You are not running on Acquia Cloud, this is a mandatory requirement for this module. The module will not process scheduled purges, once deployed scheduled purges will be processed.

There are no load balancers detected which makes it impossible to purge your site. Please contact Acquia Support!

Your site has Drupal page caching disabled, which is of extreme importance to every website that gets traffic. Once enabled your load balancer will be instructed to start serving pages from its cache to offload traffic from your web servers. The more traffic served from your load balancer, the faster your site will be!

Please contact your system administrator or development partner!

Notice: Undefined property: stdClass::$is_new in node_save() (line 1109 of /Users/jwhitsit/acquia/uiowa702-dev/docroot/modules/node/node.module).
Notice: Undefined property: stdClass::$is_new in node_save() (line 1135 of /Users/jwhitsit/acquia/uiowa702-dev/docroot/modules/node/node.module).
Notice: Undefined property: stdClass::$is_new in node_save() (line 1141 of /Users/jwhitsit/acquia/uiowa702-dev/docroot/modules/node/node.module).
Notice: Trying to access array offset on value of type null in _event_sync() (line 100 of /Users/jwhitsit/acquia/uiowa702-dev/docroot/sites/content.uiowa.edu/modules/custom/content_hub_core/inc/content_hub_core.event_sync.inc).
Notice: Trying to access array offset on value of type null in _event_sync() (line 100 of /Users/jwhitsit/acquia/uiowa702-dev/docroot/sites/content.uiowa.edu/modules/custom/content_hub_core/inc/content_hub_core.event_sync.inc).
Notice: Trying to access array offset on value of type null in _event_sync() (line 100 of /Users/jwhitsit/acquia/uiowa702-dev/docroot/sites/content.uiowa.edu/modules/custom/content_hub_core/inc/content_hub_core.event_sync.inc).
Notice: Trying to access array offset on value of type null in _event_sync() (line 100 of /Users/jwhitsit/acquia/uiowa702-dev/docroot/sites/content.uiowa.edu/modules/custom/content_hub_core/inc/content_hub_core.event_sync.inc).
Notice: Trying to access array offset on value of type null in _event_sync() (line 101 of /Users/jwhitsit/acquia/uiowa702-dev/docroot/sites/content.uiowa.edu/modules/custom/content_hub_core/inc/content_hub_core.event_sync.inc).
Notice: Trying to access array offset on value of type null in _event_sync() (line 102 of /Users/jwhitsit/acquia/uiowa702-dev/docroot/sites/content.uiowa.edu/modules/custom/content_hub_core/inc/content_hub_core.event_sync.inc).
Warning: Creating default object from empty value in _event_sync() (line 158 of /Users/jwhitsit/acquia/uiowa702-dev/docroot/sites/content.uiowa.edu/modules/custom/content_hub_core/inc/content_hub_core.event_sync.inc).
Notice: Trying to access array offset on value of type null in _event_sync() (line 211 of /Users/jwhitsit/acquia/uiowa702-dev/docroot/sites/content.uiowa.edu/modules/custom/content_hub_core/inc/content_hub_core.event_sync.inc).
Notice: Undefined index: AH_SITE_ENVIRONMENT in _event_sync() (line 221 of /Users/jwhitsit/acquia/uiowa702-dev/docroot/sites/content.uiowa.edu/modules/custom/content_hub_core/inc/content_hub_core.event_sync.inc).
Notice: Undefined index: AH_SITE_ENVIRONMENT in _event_sync() (line 225 of /Users/jwhitsit/acquia/uiowa702-dev/docroot/sites/content.uiowa.edu/modules/custom/content_hub_core/inc/content_hub_core.event_sync.inc).
Deprecated function: Array and string offset access syntax with curly braces is deprecated in include_once() (line 3542 of /Users/jwhitsit/acquia/uiowa702-dev/docroot/includes/bootstrap.inc).
```

I still haven't been able to reproduce it, but these are the kinds of things we are dealing with based on the status of this website.

**Comment by joewhitsitt** [comment]
Tried watching the logs in PROD. There is just so much noise... I have seen a clone roll by but then confirmed it didn't have the same characteristics as a duplicate (created moments apart and a redirect from the original to the -0 or later version)

**Comment by joewhitsitt** [comment]
Also for the heck of it, I tried updating shs, hierarchical_select, views and paragraphs locally. It cleaned up errors with editor operations but caused the api views displays to break.. (illegal choice or something)

**Comment by joewhitsitt** [comment]
Haven't made progress on this today.

**Comment by richardbporter** [comment]
I'm not seeing any custom code that is creating or cloning events that might be misbehaving. Rules is not enabled. Workflow doesn't seem to have node create/clone functionality but I'm not familiar with that module.

Node clone is enabled and events unit admins and events platform admins have permission to clone nodes. There is button right on the page after you create an event. It seems possible to click that accidentally and save the cloned node within ~10s or so.

**Comment by richardbporter** [comment]
>Quickly double-clicking save can create a duplicate event (easy to do in Safari), but the time between is much shorter and doesn't cause the redirect issue.

This is very easy to do! Maybe the redirects are being added later?

**Comment by joewhitsitt** [comment]
i don't recall if the redirects themselves have a timestamp associated with them. perhaps that could be a lead to look into

**Comment by richardbporter** [comment]
> i don't recall if the redirects themselves have a timestamp associated with them. perhaps that could be a lead to look into

Yea I started on that but I'm not seeing a created field on the table. Last access is the only timestamp.

**Comment by joewhitsitt** [comment]
Wondering if we should prevent the double save and see if the issue keeps happening: https://www.drupal.org/project/drupal/issues/1705618

**Comment by briand44** [comment]
I think preventing the double save is useful but it doesn't really sound like it is the source of our issue. We only started getting reports of this fairly recently and it sounds like attempting to recreate the problem by double saving resulted in different results with the redirects? I suppose it doesn't hurt to try and eliminate a potential cause?

**Comment by joewhitsitt** [comment]
I think it might be worth eliminating a potential cause at this point. Since we haven't been able to reproduce the issue and can't track when the redirect is being created we don't know if that is always the pattern.

I honestly could see an editor getting impatient waiting for the unit logic/purge rules to run for events with several units attached.

I will see if the patch applies and test a couple sites

**Comment by joewhitsitt** [comment]
Moving forward with the core patch from https://www.drupal.org/project/drupal/issues/1705618#comment-12014916 on 701-3:

Commits:
701 - 61ef424f90fd7c9ce20cfb7c04670f8ab72b6faa
702 - 666d35ce8c45fedab905f5490990ea19ec02fd96
703 - 723c1ab5b5da9fdd9922d8f64e3e6d9b29f11dfe

Cleared site and varnish caches for content.uiowa.edu. 🤞

**Comment by pyrello** [comment]
FWIW, I think the above patch might solve this issue. I got a report from a customer about a duplicate event that he accidentally created and based on the report, I think that it is likely that he double-clicked the submit button.

**Comment by joewhitsitt** [comment]
We closed this because there haven't been any reported or noticeable duplicates since the double submit patch was pushed up.

**Comment by joewhitsitt** [comment]
We have recently received reports of duplication again. Keeping this one closed but moving the issue over to https://github.com/uiowa/uiowa/issues/6348
