### ISSUE TITLE
Provision iywp.org site for CLAS.

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#5066]
Provision iywp.org as a new Drupal 9 site for CLAS. The domain was purchased and administered through BlueHost years ago. It is already setup to point to the Acquia LB at 54.163.225.50 and use the UICLAS application, so we shouldn't have to adjust this in BlueHost.

![Screen Shot 2022-03-30 at 12 14 45 PM](https://user-images.githubusercontent.com/3067017/160896469-a5b6e5aa-d150-41e6-b203-1c186b76d0f0.png)

- [ ] Add iywp.org to proper SSL certificate based on application location (uiowa01, uiowa02, uiowa03, etc).
- [ ] Provision iywp.org development site on application.
- [ ] Profit!!

This should be a rather quick and easy migration of content, and should get approval for launch relatively quickly. Just want to draw attention to this, as I have not provisioned a non-uiowa vanity domain on the new system.

**Comment by mark-bennett-uiowa** [comment]
- Provisioned this site on uiowa02 this afternoon.
- Created the org-iywp.prod.drupal.uiowa.edu domain on the prod environment (modeled after the iowajpec.org entry).
- Attempted to create a new SSL cert for uiowa02, but the www.iywp.org domain was unvalidated.
- Submitted a HTTPS DCV order through InCommon for the domain, but still waiting for Validated status.

**Comment by joewhitsitt** [comment]
>Provisioned this site on uiowa02 this afternoon.

I didn't see a PR for this. Is it still on your local?

**Comment by mark-bennett-uiowa** [comment]
Yes, Ill push it up right now. #5092

**Comment by mark-bennett-uiowa** [comment]
I cannot create a new SSL certificate that includes the www.iywp.org or *.iywp.org SANs for some reason. uiclas has iywp.org and *.iywp.org in their SSL cert, and has been working for some time. I am in contact with Hostmaster looking for answers.

**Comment by mark-bennett-uiowa** [comment]
SSL certificate has been updated on uiowa02 to include iywp.org. The *.iywp.org and www.iywp.org domains will be removed by Warren Staal, as they are unnecessary and causing headaches with DCV. SSL certificate is in place and appears to be working on uiowa02. Site has been installed and ready for content creation. Thanks to everyone for the assistance in this little nightmare!

**Comment by pyrello** [comment]
@mark-bennett-uiowa Can this be closed?

**Comment by mark-bennett-uiowa** [comment]
@pyrello yes, just did, ty.
