### ISSUE TITLE
Enable uiowa_maui for Office of the Registrar

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5068]
I would like to enable uiowa_maui for registrar.prod.drupal.uiowa.edu so that they can use https://github.com/uiowa/uiowa/issues/4935 and allow them to test/use additional MAUI features as they become available.

**Comment by pyrello** [comment]
```
ddev drush @registrar.prod config-split:activate uiowa_maui && ddev drush @registrar.prod cim
```

**Comment by pyrello** [comment]
This has been done. Customer has not been notified yet.

**Comment by briand44** [comment]
Thanks @pyrello. I will notify the customer.

**Comment by briand44** [comment]
I let Josh know. Closing this.
