### ISSUE TITLE
Living Learning Communities (LLC)

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5070]
# Story

As a Housing site owner, I would like to display information about LLC's at the University of Iowa so that students can have all the information they need to choose an LLC that relates to them so they can build relationships with others having similar interests and enhance their resident hall experience.

# Additional Information
They are pretty happy with what they currently have https://housing.uiowa.edu/communities. Need to be able to display all LLC's similarly to how they are currently.

They do not need the ability to filter anymore.

They would like the ability to have some intro text explaining the LLC on each individual LLC.

They would like the ability to have a personal student headshot with a quote for each LLC https://housing.uiowa.edu/communities/business

They would like the ability to enter one or more course names that are related to an LLC and have course information display with a link to MyUI (https://housing.uiowa.edu/communities/business). https://github.com/uiowa/uiowa/issues/5071

They would like the ability to list one or more LLC contacts in a card format that display a photo, name, position/title, [pronouns](https://github.com/uiowa/uiowa/issues/2234), phone and email. https://housing.uiowa.edu/communities/business.

They would like the ability to list what majors are open to each individual LLC https://housing.uiowa.edu/communities/iowa-writers

They would like the ability to display upcoming events for a particular LLC.

They would like to output a call to action link on each LLC for "Why LLC's" that would link to a similar page as https://housing.uiowa.edu/why-communities similarly to "Learn More" link on https://housing.uiowa.edu/communities/business

They would like to output a call to action link for information on how to apply for housing. My understanding is these all link to same page.

They would like the ability to reference a location (residence hall) to tell students where the LLC will be for the upcoming year. https://housing.uiowa.edu/communities/business

They would like the ability to display information about who campus partners are and how to contact them. Currently text area. https://housing.uiowa.edu/communities/business

# Proposed solution

- [x] #5453

**Comment by mjoneill** [comment]
Grooming discussion: 

From a dev perspective, it makes sense to continue with these pages as...
- Basic Pages
- Dev team would have to add a custom component for course listings imported in from MAUI
- Dev team would furnish a mockup/prototype of what this experience could look like for one community, using a basic page

Note about complication/assumption/risk: Dev team indicated that if filtering is required, then it might change the approach


Next step: 
- conversation with a partner, "Have you thought about building this as a basic page..."  goal is to identify if there are any reasons why that couldn't work, and understand if they grok how to do it or they need a prototype from us to start
- Verify that they DO NOT need filtering.

**Comment by briand44** [comment]
>Next step:
conversation with a partner, "Have you thought about building this as a basic page..." goal is to identify if there are any reasons why that couldn't work, and understand if they grok how to do it or they need a prototype from us to start
Verify that they DO NOT need filtering.

It was discussed with @meganyoder and it sounded like basic pages are a fine path forward as long as the requirements can be met with a basic page. It was also confirmed that filtering is no longer needed.

A prototype/mockup of an LLC using a basic page provided by the web team would be the next step in my opinion. Once we have all requirements met using a basic page, that page could then be replicated for the remaining LLC's.

**Comment by briand44** [comment]
Create mockup in housing.prod.drupal.uiowa.edu

**Comment by mkyoder** [comment]
Hi! 

I have all these built out now and populated with content and the functionality here works great! There are only two issues I encountered:

**Events**
I created a mock LLC event in content.uiowa.edu and set it as private so that it would not be discoverable on the events calendar but still pull into the site to test it. For some reason it is not pulling into the page. Attached is how I have set it up. Did I miss a step here? I am assuming so, but cannot figure out where I went wrong. 

Here is the link to this mock event: https://events.uiowa.edu/71293 

**Community details**
These look great! However, I think I messed up the code here that Joe did in making these blue. Do I need to put a space in the code here in order to make these not run together and space them out? Sorry, I can't quite figure that piece out.

**Comment by mkyoder** [comment]
![Screen Shot 2022-07-21 at 4 45 28 PM](https://user-images.githubusercontent.com/107870104/180543496-76f0bf73-4010-4e97-b719-af8d25a1052d.png)
![Screen Shot 2022-07-21 at 4 45 54 PM](https://user-images.githubusercontent.com/107870104/180543619-2f2d4a43-6fba-49
![Screen Shot 2022-07-22 at 3 13 12 PM](https://user-images.githubusercontent.com/107870104/180545414-50b47511-20d6-4f4a-8d13-525bead66f1d.png)
ee-9c9c-492f49078b58.png)

**Comment by mkyoder** [comment]
![Screen Shot 2022-07-22 at 3 15 17 PM](https://user-images.githubusercontent.com/107870104/180548127-5591d37b-c58f-4df2-808b-34e53f588cd6.png)
![Screen Shot 2022-07-22 at 3 16 02 PM](https://user-images.githubusercontent.com/107870104/180548158-05d1b3d1-8792-4476-ad66-8b165d072164.png)
![Screen Shot 2022-07-22 at 3 20 04 PM](https://user-images.githubusercontent.com/107870104/180548181-9e9e1984-bc85-4c36-8c8e-e9aabb7cb298.png)

**Comment by briand44** [comment]
@mkyoder For the events issue, looking at the Arts LLC, it looks like you have the past events checkbox checked which limits the results to events in the past. Uncheck that and I think it should work.

**Comment by briand44** [comment]
@mkyoder I updated the community details for the Arts LLC, is that what you are going for? I think you had a`&nbsp` after the text inside your `<span>`. I moved the `&nbsp` outside the `<span>`.
