### ISSUE TITLE
MAUI course autocomplete field

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5071]
The current D7 uiowa_maui module provides an autocomplete field that can be configured for a specific session and allows entering a course name for that session and will return course information for the specified courses. This is needed for SiteNow v3. An example of this field can be seen on the Living Learning Communities content type on the housing site https://housing.uiowa.edu/admin/structure/types/manage/llc/fields/field_llc_course. The D7 uiowa_maui module is a good reference here.

# Proposed Solution

- [ ] Depending on how https://github.com/uiowa/uiowa/issues/5070 is built (basic page with block plugin or custom content type with field), focus on building as a form api or field api type.
- [ ] Structure in such a way that the data callback and such are outside the field type so we can leverage it elsewhere.
- [ ] Look at address and linkit for examples of using the same field widget/formatter.

**Comment by pyrello** [comment]
PSA: There are two Drupal APIs that handle fields: Form API and Field API. 

The Form API is used in situations where we are creating admin forms for custom blocks or using `hook_form_alter`. There are field types that form API understands and can be rendered correctly by adding the correct render array attributes.

The Field API is used for field-able fields (adding fields to block content and other entities). It requires definition of (or reuse of an existing) FieldFormatter, FieldType, and FieldWidget. 

You cannot use a Field API defined field as a field type in a Form API form. A field type defined in Form API can not be added as a field-able field.

It sounds like our initial use case for this means that we'll want to define it as a Field API field. However, it is conceivable that we may want to use it eventually in an Admin form using Form API. Ideally when we design this, we could generalize the code that handles the behavior of the field (e.g. autocompleting with class names when the user types) in a class that can be used by fields defined in both APIs. Possibly we want to build a service for this?

**Comment by briand44** [comment]
Sounds like Housing is ok with using the collection component and manually adding this content. Since I don't believe there were any other existing needs for this functionality, I am going to close this. We can re-open if needed in the future.
