### ISSUE TITLE
Ability to limit number of upcoming deadlines displayed

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5072]
As an editor using the MAUI upcoming dates feature, I would like to limit the number of items displayed, so that I can place a limited number of items on the homepage of my site and link to another page or the Registrar's website for additional upcoming dates.

**Comment by richardbporter** [comment]
I would suggest we model this after other blocks that allow for a limited number of items + link like ListBlock, Events, etc. However if someone configures the block to show 3 dates with no more link, someone might miss an important upcoming deadline. Maybe if a limit is placed, a more link _has_ to be provided?

**Comment by e-marie-w** [comment]
So there's no desire for a pager at this point in time, correct? Just limit the number of displayed items and add a more link if all aren't shown.

**Comment by richardbporter** [comment]
> So there's no desire for a pager at this point in time, correct? Just limit the number of displayed items and add a more link if all aren't shown.

Correct.
