### ISSUE TITLE
As a site owner, I can adjust the button style on the banner block

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#5086]
# Story

As a site owner, I can adjust the button style on the banner block

# Proposed solution

In `uids`:
  - Use https://github.com/uiowa/uids/pull/681 as a starting point. 
  - Test out the button classes in the `banner_link_classes` in UIDS. 

In `uiowa`:

- [x] Add a new "Button style" layout builder style grouping `/admin/config/content/layout_builder_style/group` to the banner block under "Display options" that offer these choices:
  - Primary Gold (default) `bttn bttn--primary bttn--caps`
  - Secondary (Black) `bttn bttn--secondary bttn--caps`
  - Outline `bttn bttn--outline bttn--tertiary bttn--caps`
  - Sans-serif outline `bttn bttn--outline bttn--tertiary bttn--sans-serif`
- [x] Update hook to set `Button: primary (default)`as the selected button style.

**Comment by briand44** [comment]
These options would not be available when just using a background pattern. It would use the default style currently used.

**Comment by bspeare** [comment]
If we want, I think we can use this without the conditional hiding for backgrounds.   Since the buttons are used in the WYSIWYG, the colors are set adjust to adjust if there is a gold button on a gold background.

**Comment by pyrello** [comment]
> Since the buttons are used in the WYSIWYG, the colors are set adjust to adjust if there is a gold button on a gold background.

Trying to make sure I understand this. Does that mean that the user might select a gold button on a gold background and the button would render another color?

**Comment by bspeare** [comment]
Yes, if the primary button is used on a gold background the color will change to keep it accessible. 

<img width="195" alt="Screen Shot 2022-04-15 at 8 42 29 AM" src="https://user-images.githubusercontent.com/1036433/163578024-f07228a7-2d85-4f99-8cd5-3c8cafa1c62e.png">

With gold background:

<img width="188" alt="Screen Shot 2022-04-15 at 8 42 15 AM" src="https://user-images.githubusercontent.com/1036433/163578046-40d925c8-718f-4ea5-b234-23d22356a36d.png">

We could also just make the color shift less extreme and just add a border around the button:

<img width="239" alt="Screen Shot 2022-04-15 at 8 45 41 AM" src="https://user-images.githubusercontent.com/1036433/163578346-8fee65a8-f404-4cd2-84a5-5c72abcf5fd0.png">

**Comment by pyrello** [comment]
I guess if we are going to offer people the option, then it seems like the last option is the least confusing since we wouldn't be overriding their decision.

**Comment by makurj** [comment]
I would like to work/pair on this.
