### ISSUE TITLE
Residence Halls

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5087]
# Story

As a Housing site owner, I would like to display information about Residence Halls so that students can get all the information they need about each specific location.

# Additional Information
They are pretty happy with what they currently have https://housing.uiowa.edu/residence-halls. Need to be able to display all residence halls similarly to how they are currently with the ability to filter on specific categories.

Same filterable categories they currently have (Building type, neighborhood, amenities, room type, furnishings) and would like to add an additional filter for bathroom type (Community style, single-user, suite-style, private restroom).

They would like to make the "Who lives here" section more visible (see screenshot). This is currently a taxonomy (Co-ed, first year, returning, transfer). Honors students live across all halls and they want to be able to designate that as well and more visible. https://housing.uiowa.edu/residence-halls/burge-hall
![Screen Shot 2022-04-01 at 3 44 39 PM](https://user-images.githubusercontent.com/1017022/161339313-bf170f8c-963c-465d-83d8-51d73d3f7116.png)

They need an intro paragraph to describe each residence hall. https://housing.uiowa.edu/residence-halls/burge-hall

Photo Gallery of Hall images. https://housing.uiowa.edu/residence-halls/burge-hall

Video that tells about the Hall. https://housing.uiowa.edu/residence-halls/burge-hall

Ability to show specific [LLC's]( #5070 ) located in each hall. https://housing.uiowa.edu/residence-halls/burge-hall

Denote Furnishings similar to current site. Currently a taxonomy. https://housing.uiowa.edu/residence-halls/burge-hall

Denote amenities similar to current site. Currently a taxonomy. https://housing.uiowa.edu/residence-halls/burge-hall

Show a sample floor plan and 360 view of a typical room. See screenshot for current fields. https://housing.uiowa.edu/residence-halls/burge-hall
![Screen Shot 2022-04-01 at 4 18 14 PM](https://user-images.githubusercontent.com/1017022/161342563-24326063-df0b-43fc-9e23-dfe783bc16d1.png)

They would like the ability to list one or more contacts in a card format that display a photo, name, position/title, [pronouns](https://github.com/uiowa/uiowa/issues/2234), phone, email.

Getting around info. A text area to provide information about proximity to other campus locations.

Cambus Stops - A way to let the customer choose which cambus stops are near and output the stop as a link to the stop on transit app?

Concept3D map of residence hall in relation to rest of campus. They would like this displayed higher up the page if possible.

Gallery of bathroom photos on each residence hall page.

Ability to add and display rates for each residence hall. They like how rates are handled on this site https://housing.umn.edu/bailey

Include a section for mailing address for each particular residence hall. Similar to https://housing.umn.edu/bailey

Neighborhood - (East, West) select list

Year Built

Population 

Front Desk phone

Front Desk Hours

Get Involved Call to action links - These currently have a title and brief desc text
- Connect with your community
- Advocate for Students
- Work for Us

Link to Dining Menu

Link to photo gallery with more building photos

Link to place a work order

Section to place information about emergency policies (This will be text only, so an accordion on each res hall page with this information or link out to a basic page could suffice.)

# Proposed solution

- [x] #5238
- [x] #5227
- [x] #5290
- [x] #5294
- [x] #5354 
- [x] Finish https://github.com/uiowa/uiowa/pull/5268 and add it to the content type
- [x] #5350
- [ ] #2234

**Comment by joewhitsitt** [comment]
As I mentioned in grooming, I wonder if it makes sense to structure all of this. I see layout builder components mixed through out here (people, photo gallery, links, etc.). Maybe this is a good use-case for opening up layout builder to non-page content. It seems like less overall long term maintenance to do that versus making all of this fielded content that then wires up and possibly extends uids templates. It would allow us to also develop blocks that could be used by others (e.g. concept3d map block). I agree that some content should be structured, especially if this is the authoritative source that is pulled into other apps. Their current site is so structured/defined that there is usually continuous requests for development updates.

Marketing aside, this is a building, and it was decided during the concept3d project that Facilities should maintain a lot of this information and we should pull from their data sources.

**Comment by mjoneill** [comment]
Grooming discussion:

- Dev team recommends keeping this as structured content (based largely on the filtering requirements)
- Dev team recommends tackling this before tackling the living learning communities page
- Dev team indicated that some of the filters can go away, but we'll have to add a bathrooms filter

Next step: create slices for this epic.

**Comment by briand44** [comment]
First slice to create basic content type structure and include fields that seem straight forward.

**Comment by briand44** [comment]
leaning towards taxonomies for the other categories so they have the ability to create additional as needed without our team.

**Comment by briand44** [comment]
Closing this. Pronouns are a nice to have for Housing and not a requirement for launch. They will take advantage of them once we have service wide integration.
