### ISSUE TITLE
UICB - How to export images for a set of content types?

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#5091]
Big Slider, Homepage slide, Image, Photo of the Week, and Store Items.

**Comment by joewhitsitt** [comment]
Can this just be an rsync dump locally, zipped up and delivered or does it need to keep a relationship to the particular pieces of content. If so, could a views data export be created to pair with the rsync'd directory with relative path urls for the files?

**Comment by pyrello** [comment]
> Can this just be an rsync dump locally, zipped up and delivered or does it need to keep a relationship to the particular pieces of content. If so, could a views data export be created to pair with the rsync'd directory with relative path urls for the files?

Good point of clarification. I guess I was imagining one directory with all the images in it, but I should check if sorting them into types is important to the customer.

**Comment by pyrello** [comment]
Blocker for #6119

**Comment by briand44** [comment]
This is no longer relevant. D7 UICB site no longer exists.
