### ISSUE TITLE
Implement structured JSON-LD for directory profile people

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5093]
The Directory profiles team has an endpoint that includes structured JSON-LD `{{host}}/api/people/{{slug}}/structured?api-key={{dentistryKey}}`

Place in script element with type attribute `application/ld+json`

**Comment by mjoneill** [comment]
@briand44 can we consider this for inclusion in next sprint?

**Comment by richardbporter** [comment]
I started looking at this but I'm getting a 401 response from the profiles app. What URL(s) did we get added for CORS policy? I've tried default.uiowa.ddev.site and dentistry.uiowa.ddev.site - I thought those were good to use.

**Comment by joewhitsitt** [comment]
*.uiowa.ddev.site was added by Denny a while ago. Keep in mind the keys change per environment and you might have to reach out to Denny to obtain one for Dentistry.
