### ISSUE TITLE
Disable lazy images for CI

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#5095]
Percy is still struggling with lazy loaded images. https://docs.percy.io/docs/capturing-lazy-loading-images

**Comment by pyrello** [comment]
If we are still using the `lazy` module, there is a `lazy.settings:disabled_paths property` that we could possibly force to be set to all paths (*) when on CI via settings.php

**Comment by richardbporter** [comment]
I jumped on this in #5098 because we're almost out of snapshots for this cycle. It appears to work!
