### ISSUE TITLE
Mismatched entity block_content.field_uiowa_headline

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#5108]
# Problem
The status report page is currently reporting the following problem:
```
Mismatched entity and/or field definitions
The following changes were detected in the entity type and field definitions.
Custom block
The block_content.field_uiowa_headline field needs to be updated.
```

# Steps to reproduce
Go to the status report page.

# Proposed solution
TBD.

**Comment by richardbporter** [comment]
I think the field settings for each block using field_uiowa_headline need to be resaved and exported for the default value of `headline_alignment`.

**Comment by richardbporter** [comment]
> I think the field settings for each block using field_uiowa_headline need to be resaved and exported for the default value of `headline_alignment`.

Tried this locally quickly but it didn't seem like enough. :/

**Comment by joewhitsitt** [comment]
Noticed this while we were upgrading to d10.

**Comment by joewhitsitt** [comment]
Closing in favor of https://github.com/uiowa/uiowa/issues/6679
