### ISSUE TITLE
Frontend performance audit

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#5119]
# Problem
The homepage (uiowa.edu) recently took a hit in page load speeds on SiteImprove. We should investigate and remediate issues for that site specifically or better yet, the platform as a whole.

# Proposed solution
Investigate https://iowaweb.slack.com/archives/C0164FNN1PV/p1649254928343819 and create slices of improvements that could be made. Create new issues update this issue with references.

## Slices
- [x] #5121

**Comment by bspeare** [comment]
Another issue that probably increased the page size is the switch from the Hero block to the Banner block.   With the hero block we were able to upload an optimized preview image for the video loop whereas the banner block's poster image is generated by Drupal and is a `png` which probably adds an additional 1mb of extra load to the page.

**Comment by richardbporter** [comment]
> Another issue that probably increased the page size is the switch from the Hero block to the Banner block. With the hero block we were able to upload an optimized preview image for the video loop whereas the banner block's poster image is generated by Drupal and is a `png` which probably adds an additional 1mb of extra load to the page.

I'd like to understand this more. Were we doing that in code somewhere? Could we re-implement it?

**Comment by bspeare** [comment]
Yes, we were requiring the image field if a video was uploaded and then setting it as the poster image: https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/templates/block/block--inline-block--uiowa-hero.html.twig#L59.    Not sure how we would do that with the banner.   Expose an additional image field once a video was selected?   We could also look into why the poster image is being rendered as a `png`.

**Comment by richardbporter** [comment]
> Yes, we were requiring the image field if a video was uploaded and then setting it as the poster image: https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/templates/block/block--inline-block--uiowa-hero.html.twig#L59. Not sure how we would do that with the banner. Expose an additional image field once a video was selected? We could also look into why the poster image is being rendered as a `png`.

Thanks. Turned on webp locally just to confirm that did not magically serve the banner poster image as webp. It doesn't. :) The vertical video posters are also flagged for potential savings. Turning on webp helps but getting those poster images reduced and/or serving them as webp would help even more.

**Comment by richardbporter** [comment]
Looks like media_thumbnails_video is creating the PNG. Looks to be hard-coded and there is no config to change it. 

There are a couple related issues to allow users to upload a different thumbnail. That might be an option.

https://www.drupal.org/project/media_thumbnails_video/issues/3137079 

Another option might be to override the poster attribute in a preprocess function.

**Comment by bspeare** [comment]
Closing this in favor of https://github.com/uiowa/uiowa/issues/7196, which is dedicated to improving the largest image being loaded on uiowa.edu.
