### ISSUE TITLE
As a website visitor, I can load SiteNow websites quickly and save bandwidth with nextgen image formats.

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#5121]
Related #5119 

PageSpeed Insights reports this as the biggest opportunity for mobile and desktop. We initially tried using webp in #1341 but had to roll it back in #1531 to fix #1476.

## Proposed solution

- Clearly define what the problem is with webp and lazy.
- Compare Lighthouse reports with webp vs lazy.
- Reach out on d.o Slack if anyone has experienced this.

**Comment by joewhitsitt** [comment]
https://imagexmedia.com/blog/speed-your-drupal-9-website-webp-images made it sound like responsive, lazy and webp were all possible together now in core 9.2

**Comment by richardbporter** [comment]
I quickly investigated the webp module again just to see if that responsive image style issue still exists and it appears that it does. Although, I can't articulate it perfectly and I'd be curious how it relates to #3614. It seems similar but I might be misunderstanding it.

**Comment by joewhitsitt** [comment]
The lazy module has been trouble in the past, I wonder if it is still needed now that modern browsers support the attribute to some degree now.

**Comment by richardbporter** [comment]
> https://imagexmedia.com/blog/speed-your-drupal-9-website-webp-images made it sound like responsive, lazy and webp were all possible together now in core 9.2

The article mentions:

>The file size reduction results are truly inspiring, but unfortunately, the WebP support in Drupal 9.3 is not yet integrated with Drupal’s responsive image style system. As a temporary solution, you can rely on the [WebP ](https://www.drupal.org/project/webp)or [ImageAPI Optimize WebP](https://www.drupal.org/project/imageapi_optimize_webp) contributed Drupal modules that ship with Drupal’s responsive image styles.

Not exactly sure what that means...

I tried adding a Convert operation to image styles for webp, which appears to work but it doesn't provide any fallback for browsers that don't support webp like Safari.

**Comment by richardbporter** [comment]
> The lazy module has been trouble in the past, I wonder if it is still needed now that modern browsers support the attribute to some degree now.

Yea I wonder too. This still seems to be true: https://github.com/uiowa/uiowa/issues/1476#issuecomment-622458404

**Comment by briand44** [comment]
Seems like this may need to be scoped to an investigation issue first.

**Comment by briand44** [comment]
Ask Drupal community?

**Comment by joewhitsitt** [comment]
> Ask Drupal community?

Started a thread in Drupal's #media channel
https://drupal.slack.com/archives/C1VLTJJD8/p1651607175692989

UPDATE: It saw some activity overnight
- we want the picture element format
- use rendered entity responsive image style on the block/paragraph, use `Responsive Image (lazy)` on the media image type.
- lazy works by processing fields (we may have to adjust how we are adding file/media > block/paragraph images to twig)
- seanb recommended https://www.drupal.org/project/easy_responsive_images

**Comment by joewhitsitt** [comment]
Not sure if @richardbporter saw my update here ^^

**Comment by richardbporter** [comment]
> Not sure if @richardbporter saw my update here ^^

That's awesome. Good info there.

I'm thinking this is going to be a bigger investment than initially planned. #5225 could probably be closed - it was a quick investigation. One thing to keep track of there was that TravisCI might not be set up to generate webp images. That impacts Percy as no images seem to load in the snapshots.

**Comment by joewhitsitt** [comment]
Drupal's lazy loading doesn't work yet with responsive images https://www.drupal.org/project/drupal/issues/3192234

**Comment by joewhitsitt** [comment]
> Drupal's lazy loading doesn't work yet with responsive images [#3192234: Apply width and height attributes to allow responsive image tag use loading="lazy"](https://www.drupal.org/project/drupal/issues/3192234)

This has been added to 10.1 https://www.drupal.org/node/3279032

**Comment by bspeare** [comment]
Since 10.1 has fixed this, can we close?  I think the next big question is https://github.com/uiowa/uiowa/issues/5432.
