### ISSUE TITLE
Grant Bulletin Opportunities

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5124]
They would like to develop something very similar to https://grantbulletin.research.uiowa.edu/.

Current and Archive displays - current means sponsor deadline >= now or null. Archive - sponsor deadline less than now.
Source link that links directly to source.
Want to migrate 2 years worth of opportunities.

# Proposed Solution

**Comment by pyrello** [comment]
This may overlap some with the following features:
* Scholarships feature split
* Opportunities content type in the SPPA site split

**Comment by briand44** [comment]
They shared this today https://iowa.sharepoint.com/:w:/s/vpr/comm/EVMj7xn2czNGolWrwcpkKuYBF-uLkGAXCf8LqIa7z1rrfQ?wdLOR=c38CCF83B-45DD-A642-B77F-70594C134444.

I will talk through it with them and provide addition details as we get closer to this work.

**Comment by briand44** [comment]
The archive by date functionality included in that doc is referring to the ability to schedule unpublishing of pages on a certain date/time.

**Comment by briand44** [comment]
This is no longer relevant as they are using a different application for this information and no longer on SiteNow.
