### ISSUE TITLE
Separate taxonomy term view

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5132]
With Community colleges as a taxonomy vocabulary, 2plus2 majors content are automatically being pulled in due to the default taxonomy term view. Currently it is un-styled, at the bottom and probably by modified date instead of title. 

## Proposed Solution

- [x] Create a separate view of 2plus2 majors contextually filtered based on taxonomy on node displaying all as teasers in alphabetical order.
- [x] Create a teaser template for 2plus2 majors to render similar to basic page teasers with title only for now.
- [x] Similar to Colleges, use TVI to override and replace the default taxonomy term view display with the new view OR override the community colleges template to remove the taxonomy term view and consider an pseudo extra field to display the new view within the content where desired.

## For reference:

https://2plus2.admissions.uiowa.edu/majors/iowa-valley.htm

**Comment by joewhitsitt** [comment]
Blocked by https://github.com/uiowa/uiowa/issues/5003

**Comment by joewhitsitt** [comment]
Until #5120 is approved by Admissions, work on this can could start in this PR. Removing the block.

**Comment by joewhitsitt** [comment]
Got initial template and view created. Running into issues using TVI.

**Comment by joewhitsitt** [comment]
Figured out TVI. Not happy about it. It is working...

**Comment by joewhitsitt** [comment]
I experimented with an extra field instead of TVI just in case. Looks like that could be done instead. Need to dig deeper to see I can mimic field markup a bit more and get the contextually aware title to work.

**Comment by joewhitsitt** [comment]
Scott prefers the pseudo extra field approach. I am going to remove the TVI stuff and see about getting the replacement polished up.
