### ISSUE TITLE
Tables with same image many times are breaking.

### ISSUE THREAD

**Issue by GaryRidgway** [uiowa/uiowa#5138]
# Problem
Putting an image in multiple rows of a table between 5-15 times makes the images not render on the last 2/3 of their instantiations.

![Screen Shot 2022-04-15 at 2 03 44 PM](https://user-images.githubusercontent.com/23122142/163621910-db3f7f21-f2b4-486a-bfdc-28996d6a7c67.png)

![32fd86930bdad4cec6923446b1b57ba5](https://user-images.githubusercontent.com/23122142/163621892-c7d22bf4-e9b9-4007-bb70-afc31ca24dbc.gif)

# Steps to reproduce
Create a table, add the same image many times

# Proposed solution
Probe to see what's happening and then FIXIT

**Comment by joewhitsitt** [comment]
I don't think this is limited to tables. I recall Dustin having an issue with their Intranet's shout out page where the same icon was used for each row. It is also an issue on https://sandbox.prod.drupal.uiowa.edu/node/51 where Sean's image stops displaying towards the end of the page and we have a background "empty" image fallback.

**Comment by joewhitsitt** [comment]
Closing in favor of https://github.com/uiowa/uiowa/issues/6373 which has a link to the upstream issue.
