### ISSUE TITLE
As a webform builder, I would like to have less vertical space between checkbox and radio inputs 

### ISSUE THREAD

**Issue by makurj** [uiowa/uiowa#5147]
Request: As a webform builder, I would like to be able to apply a class to single field checkboxes to reduce the vertical spacing between items.

Why: Integrating with CRM (Salesforce) requires that each selection (true/false) be tied to a different field in Salesforce. Therefore a single multi-select checkbox field won’t suffice. Typically this use is tied to “Programs of Interest.”

Examples: https://tippie.prod.drupal.uiowa.edu/form/profcert-primary-rfi
https://tippie.prod.drupal.uiowa.edu/form/phd-primary-rfi

# Proposed Solution

Make the following updates in https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/scss/webforms/webforms.scss. 

- Increase size of checkboxes and radio buttons to make them better touch targets `height: .6cm; width: .6cm;`
- Increase label size `.webform-submission-form label {font-size: 1.1rem;}`
- Add `.webform-submission-form` override default margin styles `.uids-content [type="checkbox"], .uids-content [type="file"], .uids-content [type="radio"] {margin-bottom: 1.2rem;}`
- Remove left margin from `.webform-submission-form .webform-type-webform-radios-other .fieldset-wrapper {margin-inline-start: 0;}`
- Make sure checkbox is centered/aligned with text. 

The result should look like these screenshots below and get us closer to the 45px touch target. 

<img width="492" alt="Screen Shot 2022-05-03 at 2 57 49 PM" src="https://user-images.githubusercontent.com/1036433/166555963-e2da1221-ce82-41cb-bb09-5d86d049fafd.png">

<img width="494" alt="Screen Shot 2022-05-03 at 2 57 55 PM" src="https://user-images.githubusercontent.com/1036433/166555957-50d023c7-beda-4933-87ef-dafed7f26418.png">

**Comment by briand44** [comment]
>Consider making touch targets at least 48x48dp, separated by 8dp of space or more, to ensure balanced information density and usability. A touch target of 48x48dp results in a physical size of about 9mm, regardless of screen size. The recommended target size for touchscreen objects is 7-10mm.  https://support.google.com/accessibility/android/answer/7101858?hl=en#:~:text=Consider%20making%20touch%20targets%20at,touchscreen%20objects%20is%207%2D10mm.

**Comment by mjoneill** [comment]
Google's Material Design guidance:
>**Touch and pointer targets**
>
>Touch targets are the parts of the screen that respond to user input. They extend beyond the visual bounds of an element. For example, an...
>
>**Touch targets**
>Touch targets are the parts of the screen that respond to user input. They extend beyond the visual bounds of an element. For example, an icon may appear to be 24 x 24 dp, but the padding surrounding it comprises the full 48 x 48 dp touch target.
>
>For most platforms, consider making touch targets at least 48 x 48 dp. A touch target of this size results in a physical size of about 9mm, regardless of screen size. The recommended target size for touchscreen elements is 7-10mm. It may be appropriate to use larger touch targets to accommodate a larger spectrum of users.
>
>Note that on iOS, 44 x 44 pt is the recommended touch target. For platform-specific implementation guidance, visit the [developer resource page](https://material.io/develop).
>
>**Pointer targets**
>Pointer targets are similar to touch targets, but apply to the use of motion-tracking pointer devices such as a mouse or a stylus. Consider making pointer targets at least 44 x 44 dp.

--https://material.io/design/usability/accessibility.html#layout-and-typography

**Comment by bspeare** [comment]
After meeting with Tippie this afternoon, I have updated the proposed solution.

**Comment by briand44** [comment]
Adding grooming label back so we can update the team on the new proposed solution. Thanks @bspeare
