### ISSUE TITLE
As a site owner, I can use a mega menu that has adjusted spacing to accomodate multiple rows

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#5148]
# Story

As a site owner, I can use a mega menu that has adjusted spacing to accomodate multiple rows so that it does not take up so much vertical space. 

# Proposed solution

Test on https://tippie.prod.drupal.uiowa.edu/. 

<img width="1614" alt="Screen Shot 2022-04-27 at 11 44 33 AM" src="https://user-images.githubusercontent.com/1036433/165576304-a7ced9cc-6e6a-4920-b864-09e08b629a97.png">

<details>
![megamenu](https://user-images.githubusercontent.com/1036433/164089105-dbef9ae2-dcc5-4afd-a269-f43ef0cb20d2.jpg)
</details>
- Update `superfish/mega-menu.scss` styles to look closer to the screenshot above by using some of the suggested code chages below.

```
.block-superfish .sf-mega-menu .sf-multicolumn {
    left: calc(50% - 700px);
    width: 71.875em;
}

.block-superfish .sf-mega-menu .sf-multicolumn li {
    line-height: 1;
}

.block-superfish .menu.sf-mega-menu ul li a, 
.block-superfish .menu.sf-mega-menu ul li span {
    font-size: 1.2rem;
}

.block-superfish .sf-mega-menu .sf-multicolumn-wrapper>ol {
    /* width: 100%; */
    gap: 0 2rem;
    margin: 0 1.5rem;
}
```

**Comment by bspeare** [comment]
It seems like we would want to do something like https://tobiasahlin.com/blog/masonry-with-css/, but that solution requires a fixed height to be set on the container.  

- We could either set the height to something like `100vh` but that would change the design requirements suggested by the screenshot above.  
- Implement the above solution and wait for https://drafts.csswg.org/css-grid-3/#masonry-layout-algorithm to be more widely supported. 
- Implement a JS masonry solution and replace it with https://drafts.csswg.org/css-grid-3/#masonry-layout-algorithm when it is ready. 

<img width="1366" alt="Screen Shot 2022-04-26 at 8 22 45 AM" src="https://user-images.githubusercontent.com/1036433/165309942-f067fd8f-26df-4c33-b593-a9feea0f6351.png">

**Edit:** We could also just tighten up the spacing and keep the design in a grid. 


https://user-images.githubusercontent.com/1036433/165350873-81d58cb5-4c63-4f1a-a8ff-0af71d0ae0da.mov

**Comment by mjoneill** [comment]
> Edit: We could also just tighten up the spacing and keep the design in a grid.

^^^ Could this/would this work as a first slice?  Seems like a faster way to get to minimally viable menu without opening up a masonry job.

Next step: Ask/probe Tippie in next convo.

**Comment by bspeare** [comment]
Tippie is OK with moving forward with tightening up the spacing and keeping the design in a grid.  I have updated the issue title and proposed solution screenshot to reflect this decision.
