### ISSUE TITLE
Imagecache External configuration is incorrect

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#5153]
noticed a warning for Imagecache External. fresh in my mind. not sure if it is new, but could we just set this to uiowa.edu for now or is this being used by aggregator in which case we should turn off this validation?

<img width="704" alt="Screen Shot 2022-04-20 at 1 11 11 PM" src="https://user-images.githubusercontent.com/4663676/164295493-43b7578b-6ad6-41ec-a556-c64b4b5f37f5.png">

_Originally posted by @joewhitsitt in https://github.com/uiowa/uiowa/issues/5152#issuecomment-1104266700_

**Comment by briand44** [comment]
may need to audit usage of imagecache_external to know if we can limit to uiowa.edu or not.

**Comment by briand44** [comment]
sounds like turning off the validation seems like a good first step since this is developer implemented
