### ISSUE TITLE
Spacing options for image block

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#5155]
# Story

Follow-up from https://github.com/uiowa/uiowa/pull/5126
As an editor, I want to add spacing around my image block so it doesn't bump up against other blocks within a section.

# Background
https://github.com/uiowa/uiowa/pull/5126#issuecomment-1103198070

# Proposed solution

- [ ] Implement spacing styles on block and wire up to template.

**Comment by bspeare** [comment]
Do we still need this after https://github.com/uiowa/uiowa/pull/5725?

**Comment by joewhitsitt** [comment]
Probably not. Thanks for looking through these.
