### ISSUE TITLE
Link from an AoS transfer tips card to a list of community colleges that participate in a 2 plus 2 plan for that major

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5157]
On an AoS within the transfer tips card, display a link if at least one 2plus2 major references the AoS. This would link to a page similar to https://2plus2.admissions.uiowa.edu/majors/majors/accounting.htm

## Proposed Solution

- [x] Preprocess transfer tip on AoS to check if current AoS is referenced in any of the 2plus2 majors. If so, display a link to a /majors/majors/{aos} views page that lists out all of the 2plus2 majors but labeled as their referenced community college.

**Comment by mjoneill** [comment]
Recommended approach from Groomin': View page with a contextual filter that uses a dynamic route for each area of study.  

Need to get approval for this approach tomorrow and then we can start working with this.  Grok grok grok.

**Comment by briand44** [comment]
My understanding was that the approach outlined here is fine as long as we also have a way to view all available majors for 2 plus 2 students (https://2plus2.admissions.uiowa.edu/majors/index.html) without having to first visit an Area of Study.
