### ISSUE TITLE
Display authored articles on person content type

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#5162]
# Story

As an webmaster, I would like to display articles authored by an individual on their profile (person content).

# Proposed solution

- [ ] Provide a site-wide option with a per node override to display published articles referencing the person node via the author field.

# Potential future slices
- display options similar to articles list block
- bring in other referencing content.=

**Comment by joewhitsitt** [comment]
Just curious the possible intersection with https://github.com/uiowa/uiowa/issues/1503

I understand this probably came from the desire to show in card/image format but since the publications content type could eventually be displayed on the person content as well and since website articles can be formatted similarly, I am wondering if these two sources could be combined in the same list.

"Display referenced content" with checkboxes to include content types (article, publication, etc.) then choose the format (titles, card, citation)

**Comment by briand44** [comment]
#4261 is handling the majority of this with the exception of the per node override. Should we close this or keep it open?

**Comment by joewhitsitt** [comment]
>per node override

We could repurpose if this is still something that is needed. A use-case would be helpful to understand the need.

**Comment by briand44** [comment]
Agree a use case would be helpful. Let's close as a duplicate of #4261 and we can open a new issue if/when we get a request for a per node basis.
