### ISSUE TITLE
UI Press - updates to book content display

### ISSUE THREAD

**Issue by e-marie-w** [uiowa/uiowa#5163]
As a visitor to the UI Press site, when I visit the page for a book I want to immediately be able to tell the price(s) for a book. 

## Solution
Update the book content display so that the Publication Details accordion is at the bottom of the sidebar and closed, while the book type accordion(s) are listed first and opened by default. 

Note: When looking at existing books on prod and dev I see a couple of examples where it's already like this and a couple where it's reversed. Unsure how/why that is happening.

**Comment by joewhitsitt** [comment]
@e-marie-w can you provide examples where this is and isn't already the case?

**Comment by e-marie-w** [comment]
With the demo content deleted, and after spot-checking a dozen random books, I think this is already set up correctly. I also created (and then deleted) a test book quick and everything displayed as expected. Not sure why dev showed mix of some working and not working, but prod seems to be fine. I think we can close this.

**Comment by mjoneill** [comment]
We think this is closed.  @briand44 , do you want to move it/nuke it?
