### ISSUE TITLE
Enable uiowa_maui for Housing

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5167]
As a Housing site owner, I would like the uiowa_maui module enabled so that we can take advantage of #5139 and also to test/use additional MAUI features as they become available.

# Proposed Solution
- [ ] Setup a site split: https://github.com/uiowa/uiowa/blob/21f0a7681674c89c2e5f3dfb0d32504ed669e069/config/sites/grad.uiowa.edu/config_split.config_split.site.yml#L16

**Comment by richardbporter** [comment]
We should address https://github.com/uiowa/uiowa/pull/5139#issuecomment-1112407182 as part of this.

**Comment by richardbporter** [comment]
> We should address [#5139 (comment)](https://github.com/uiowa/uiowa/pull/5139#issuecomment-1112407182) as part of this.

Maybe not. Some "dates" have lots of items and it might be preferable to limit that way instead. Creating a follow-up issue for further discussion: #5191
