### ISSUE TITLE
Bug: Tags and related content don't display if tags are added to a node after it's been saved without them

### ISSUE THREAD

**Issue by quamsta** [uiowa/uiowa#5181]
# Problem
Tags and related content don't display on a page, article, or person if tags are added to a node after it's been saved without them. If you add tags and re-save the node, they won't appear on the published node.

You have to re-save the Article/Page/Person configuration settings in order for them to appear.

# Steps to reproduce
1. Enable the display of tags and/or related content in SiteNow Pages/Articles/Person configuration, 
ex: `/admin/config/sitenow/uiowa-pages`. (I'll just use Page as an example since I believe this bug affects all nodes the same way).
2. Create a new Page.
3. Save the Page.
4. Edit the Page and add a tag in the "Relationships" setting .
5. Save the Page again.
6. Note that the newly added tag isn't showing.

## Workaround:

I noticed if you return to `/admin/config/sitenow/uiowa-pages` and simply re-save this setting, the tags will appear on the newly created page. This may have something to do with caching since I believe we're flushing the cache upon saving `uiowa-pages`.

# Proposed solution

Unsure what's going on here, but we may need to flush out a cached node in a way that affects the display of the Prefooter region (where tags and related content currently reside) upon saving Pages/Articles/Persons.

It seems like that Prefooter region isn't getting the hint that it needs to be added when editing a Page/Article/Person and adding a tag that should trigger its appearance.

**Comment by joewhitsitt** [comment]
@quamsta I just tried these steps with articles on https://default.dev.drupal.uiowa.edu/news/2022/04/new-article and with page on https://default.dev.drupal.uiowa.edu/new-page. i had an anonymous browser window with the article cached before i went back in and added the tag and it displayed the tags. page it seems to be an issue. on the surface, not sure what is different about these.

Might have to do something similar to admissions_core_node_presave() where the Counselors and EventsSeries blocks get invalidated.

**Comment by quamsta** [comment]
@joewhitsitt Thanks for looking and helping narrow it down a bit. Much appreciated

**Comment by quamsta** [comment]
@joewhitsitt This presave hook does seem to resolve the issue, but am I wrong in thinking that it might be too greedy and clearing the cache for every page/article/person upon saving one of them might put too much stress on the server?

```
/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function uiowa_core_node_presave(Node $node) {
  if ($node->getType() == 'article' || $node->getType() == 'page' || $node->getType() == 'person') {
    $tags = ['node_type:' . $node->getType()];
    $tags = $node->getCacheTags();
    Cache::invalidateTags($tags);
  }
}
```

**Comment by joewhitsitt** [comment]
I don't think we would target the nodes. We would register a cache tag like related:tags and put that on the block. when the node is saved, the blocks with the this cache tag would get invalidated and hopefully bubble up like we did for events

**Comment by joewhitsitt** [comment]
still curious what the difference if any between to article and page were here

**Comment by quamsta** [comment]
@joewhitsitt Oop, I forgot to mention: I tried the initial steps to reproduce the bug on articles and it still reproduced the bug for me with that content type. I haven't been able to see what you saw when it worked correctly for articles.

**Comment by quamsta** [comment]
Update: I was able to reproduce the page/article discrepancy with this issue. Trying to narrow it down further...

**Comment by quamsta** [comment]
@joewhitsitt 

I was able to clear out my view block's cache upon presave with the following code:

```
/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function uiowa_core_node_presave(Node $node) {
  if ($node->getType() == 'article' || $node->getType() == 'page' || $node->getType() == 'person') {
    $view = \Drupal\views\Views::getView('tags_list');
    $view->storage->invalidateCaches();
  }
}
```
Needs a bit more testing, but since my block is not really a custom or programmatically created block, I don't think I can register a cache tag specifically for that block. Do you think clearing the view's cache is a good path to follow?

**Comment by joewhitsitt** [comment]
looks like we are already preprocessing the block in uiowa_core `views_block:tags_list-tags_list` and `views_block:related_content-block_related_headings_lists` so I don't see why we can't register a custom cache tag there to target. with that said, i am not sure what all caches are tied to the view and if any of those would have a better chance of bubbling up.

if you stick with the views invalidation code above, I would make sure that this is scoped to sites that have this view placed to prevent it running all of the time.

I am also curious what cache tags exist for the page itself and if the page is aware of being a node page.

ultimately with which ever solution, branch testing will have to be done in DEV to see how it acts with varnish.

**Comment by quamsta** [comment]
@joewhitsitt I attempted to add a cache tag on `preprocess_block`:

```
function uiowa_core_preprocess_block(&$variables) {
  switch ($variables['plugin_id']) {
    case 'views_block:tags_list-tags_list':
      $variables['#attached']['library'][] = 'uids_base/tags';
      $variables['title_attributes']['class'] = 'h6 block__headline headline headline--serif';
      $variables['#cache']['tags'] = ['related:tags'];
(...)
```

However, the cache tag does not appear in the `x-drupal-cache-tags` response header on a page that I've added tags (taxonomy) to until I manually flush the cache or resave the tags/related content page config settings. 

It appears that `preprocess_block` runs a bit too late since neither the tags list or related view blocks are even attempted to be rendered unless the page has tags (taxonomy tags, not cache tags) in the first place.

I may continue down the route of clearing the view's caches if tags list is enabled for the appropriate content type unless you want to pair on this and take a look after grooming today or sometime tomorrow.

**Comment by joewhitsitt** [comment]
>until I manually flush the cache or resave the tags/related content page config settings

Yeah, if the block has been rendered/cached before you add this tag, it won't get called be rendered again/fire this code. This was the same issue with the time based cache tag. An update hook could register this for existing blocks.

Again, I don't know if the custom cache tag is the answer, but it seems more lightweight if it works.

I am on support this week so that is my main priority. If you push what you have, I might be able to peek/huddle at some point.

**Comment by quamsta** [comment]
@joewhitsitt Submitted a PR for the `$view->storage->invalidateCaches();` method of doing this. [The caches are only invalidated in `uiowa_core_node_presave`](https://github.com/uiowa/uiowa/pull/5226/commits/72233ff552f544556e81653801d02b2932d8b02f) if the content types have tags and/or related content enabled on them in the site's config, so sites that aren't using those views shouldn't have the views invalidated. 

If we can figure out a more lightweight way to do this, that'd be great, but that's what I have for now and it works.
