### ISSUE TITLE
Dentistry New Content People Directory Test

### ISSUE THREAD

**Issue by mjoneill** [uiowa/uiowa#5185]
Capturing thoughts, frustrations, and ideas re: people directory.  

1. 04/27 - Google not aware of the following new pages added to Dentistry people directory: https://dentistry.uiowa.edu/directory/viki-mueller and https://dentistry.uiowa.edu/directory/j-michael-tilley
2. 04/27 - Verified that both Viki and Michael's pages were listed in https://dentistry.uiowa.edu/directory/sitemap.txt
3. 04/27 - Deleted and resubmitted sitemap.txt via Google Search Console.  GSC reported no errors.
4. 04/27 - Used GSC to "Test Live URL" for https://dentistry.uiowa.edu/directory/viki-mueller.  Google test agent returned HTML that showed a <title> tag that did not include Viki's name, showed a canonical that is pointing to the correct URL, showed no meta description whatsoever, showed none of the page content, and did not show any schema markup on the page (schema.org validator shows it is there).  See images.

If Google indexes Viki's page (and then Michael's), it suggests that the issue is with recovering and we might be served by changing page URLs for all profiles (so Google thinks everything is new content).

If Google does not index either Viki or Michael, then it suggests whatever has changed, it's affecting all these pages and is not just affecting pages it is trying to recover.

<img width="930" alt="incorrect Title attribute" src="https://user-images.githubusercontent.com/7144234/165642697-a9c4ede9-1d3b-4416-99d6-74b8b069ebe1.png">

<img width="896" alt="correct canonical attribute" src="https://user-images.githubusercontent.com/7144234/165642739-1ff0753a-d1ed-4335-918c-7bf8cba9da1d.png">

<img width="910" alt="google not seeing neta description on page" src="https://user-images.githubusercontent.com/7144234/165642776-29838bf7-ad20-4105-9bbf-be251010ccc8.png">

<img width="1329" alt="google not seeing page content" src="https://user-images.githubusercontent.com/7144234/165642839-0aafd5fe-0318-4673-b95d-e9d99ac71d31.png">

<img width="902" alt="google not discovering schema" src="https://user-images.githubusercontent.com/7144234/165642933-2ce264fb-2583-4f2f-af56-51416b5cdbd6.png">

**Comment by mjoneill** [comment]
tagging @briand44 for visibility.

We've run these tests with Google before and the agent that scans the page on demand sees correct title, description, schema, content, etc...  Today was the first time that I've seen it not interpret any of these correctly (still puzzled by why canonical sorted itself out though. have a read on that?)

I'm starting to think that we are going to have to invest in server side rendering, [dynamic rendering](https://developers.google.com/search/docs/advanced/javascript/dynamic-rendering), caching rendered pages, or something else that doesn't rely on Google to interpret javascript to see the content of each page, meta description, etc...  

Would be nice to discuss options in case we have to go this route.  Again, not quite there yet...but if we're seeing the same experience with new people pages, we might need to explore it.

**Comment by mjoneill** [comment]
Also, Denny's team is planning on rendering an XML sitemap for people directory pages.  I don't suspect this will matter to this core issue, but it will at least allow us (hopefully) the chance to use last mod date/time to give Google a nudge to rescan pages.

**Comment by mjoneill** [comment]
<img width="1319" alt="image" src="https://user-images.githubusercontent.com/7144234/165646246-909252a1-f7f4-45a1-93fc-8800d69dd045.png">

Another screen grab from search console today.  It's pretty revealing...  every profile page is missing profile content, every profile page looks identical.  Every profile page may have a unique canonical (why, i don't know), but the same content, missing meta, same title, etc...

Again, it wasn't always like this...  but today it's consistently reporting this.

**Comment by mjoneill** [comment]
If we did introduce a regression, we're going to need to hop on it right away...otherwise we'll start losing pages out of the index again.

**Comment by mjoneill** [comment]
I would also like to understand what's different about CCOM's implementation (if anything).  They do not appear to be experiencing the same thing.

**Comment by quamsta** [comment]
At a cursory glance using Chrome's throttling/slowing down tools to watch the rendering of the page, it looks like CCOM's implementation shows a `<title>` tag on their profiles (example: https://medicine.uiowa.edu/acb/profile/brad-amendt) very early on in the rendering process if not right away.

On Dentistry the `<title>` and metatags seem to be adjusted very late in the process, almost like they're one of the last things to get rendered out and probably should be rendered a bit sooner if possible?

**Comment by quamsta** [comment]
Confirmed that in "View Source" the CCOM page, the `<title>` and `<meta>` tags are rendered statically upon the first request of a profile.

**Comment by briand44** [comment]
Scoping a first slice of this to understanding if we introduced a regression with the schema.org stuff.

**Comment by richardbporter** [comment]
> Scoping a first slice of this to understanding if we introduced a regression with the schema.org stuff.

#5141 switched from using XHR to fetch. I'm not seeing anything saying that the Fetch API is not supported by GoogleBot but that could be a potential cause. We're using fetch for canonical just like the other metadata so that doesn't quite add up though.

If GoogleBot sends a get request for each person URL, we could set the title, description and schema server-side. Can't do anything about the content though. 

We could try either of these options in dev and parse URLs there.

**Comment by richardbporter** [comment]
@mjoneill This is in dev now. The PR has some links and test steps: https://github.com/uiowa/uiowa/pull/5197#issue-1221413719
