### ISSUE TITLE
Add a date range option for events block

### ISSUE THREAD

**Issue by cory-skeers** [uiowa/uiowa#5187]
# Story

As a site editor I want to specify a date range to pull events based on in addition to displaying past or upcoming events.

# Proposed solution

- Duplicate `past` view display and name it `reverse` on content.uiowa.edu (heads up, might be packaged in features)
- Create a select or radio that allows Sort to be set to Descending or Ascending (defaults to Ascending for upcoming)
- Add a select, "Events query type"? for specifying upcoming (default), past or specific date range which if selected shows the specific dates field.
- https://github.com/uiowa/uiowa/issues/4320
- Add a date field (collect start and end) with date picker - see issue comments about using smart date, getting values, limiting date picker range.
- Update hook to take the past checkbox boolean value on existing to set "events query type" to past and the sort field to descending.
- Validate on all this to prevent dates that extend beyond our min and max (01-01-1970, 19-01-2038).
- Based on query type, take the dates or type and convert/format them to work as parameters.
- Based on sort, change from events to reverse.

# Follow-up

Remove the past boolean field

**Comment by briand44** [comment]
Probe to see how we can pull past and upcoming events events together and sort them.

**Comment by briand44** [comment]
I had a conversation with Education today and they confirmed the need for displaying both past and upcoming together. They are also on board with choosing a start and end date since they said they have some that are semester based and others that may be year based. As far as sorting their preference would be defaulting to oldest to newest but having an option to sort newest to oldest. They said they don't have a need for relative options (+3months) currently.

**Comment by joewhitsitt** [comment]
>Probe to see how we can pull past and upcoming events events together and sort them.

Essentially the `past` and `events` views displays of `event_instances_api` are sorts. They both take a mix of date ranges. `past` could be duplicated and named `reverse` or something and the checkbox on the block could be refactored to do that.

The block is still going to need to handle relative dates as it relates to `now` (especially existing blocks) but that an option could be selected to show absolute date pickers instead.

**Comment by joewhitsitt** [comment]
Been thinking about this for a bit:

- Duplicate `past` view display and name it `reverse`
- Create a select or radio that allows Sort to be set to Descending or Ascending (defaults to Ascending for upcoming)
- Add a boolean "Set specific dates" which if selected disables the relative text fields and shows the specific date field.
- Add relative start and end text fields
- Add a date field (collect start and end) with date picker
- Update hook to take the past checkbox boolean value on existing to set the start and end dates with relative values.
- Validate on all this to prevent dates that extend beyond our min and max (01-01-1970, 19-01-2038). Wonder if there is a php relative date validator as well just to make sure it will properly convert to a timestamp.
- Based on boolean, take the correct values, convert/format them to work as parameters.
- Based on sort, change from events to reverse.

This is more complicated than I would like, but I couldn't think of another way to handle relative, specific dates along with sort preference and maintain functionality for existing blocks.

This also puts the responsibility of sorting on the editor. Depending on which route they take, the will see the result and have to go back in to the block to flip it.

**Comment by briand44** [comment]
would like to chat through ^^ at some point

**Comment by joewhitsitt** [comment]
Mid-sprint discussion summary:

- Suggested changing to a past/upcoming (default)/specific dates select instead of supporting separate relative date text fields.

**Comment by joewhitsitt** [comment]
Updated the issue summary to reflect our discussions at mid-sprint and grooming. The plan is to re-use this issue.

**Comment by joewhitsitt** [comment]
going to poke a bit at the date field to see about collecting a start and end and how validation might be extended to check against min/max dates

**Comment by joewhitsitt** [comment]
By the looks of it, smart date range (date only) seems to do what we want. Makur pointed out that uipress sale date used separate core date fields but doesn't recall if there was a particular reason why. We can see how far we can get with smart date as that is the ideal going forward. https://github.com/uiowa/uiowa/issues/4320

`$block->get('field_uiowa_events_date_range')[0]->end_value` and `$block->get('field_uiowa_events_date_range')[0]->value`

**Comment by joewhitsitt** [comment]
Should be able change the date picker limit by processing the form elements (value and end_value)

`$element["field_uiowa_events_date_range"]["widget"][0]["time_wrapper"]["value"]["#date_year_range"]`

However, additional form validation is needed to prevent submission of manually entered dates that extend beyond our min/max ideals.

**Comment by makurj** [comment]
I'd like to continue pairing on this.
