### ISSUE TITLE
Add a pager option to the events block

### ISSUE THREAD

**Issue by cory-skeers** [uiowa/uiowa#5189]
# Story

As a site editor I want to display events with pager so that long lists of events don't disrupt my other page content

This is less of an issue at the moment, but if/when the events block options open further to allow for larger date ranges of events to be pulled in, a potentially large amount of content needs to be accounted for.

# Proposed solution

- Add a pager option to the events block form
  - Options may be a num results per page, or have each page cover a duration of time (week, month, etc.)
- Update events block rendering logic to include a pager

**Comment by briand44** [comment]
Make sure users cannot pull an infinite amount of events at once.

**Comment by briand44** [comment]
pager and limit should play nicely together

**Comment by joewhitsitt** [comment]
Will be pushing initial progress up here shortly.

Notes:

- referencing aggregator pager for this.
- currently have it setup to get page 0 based on number of items to retrieve the total count. a second call is made if a pager request is made that is not page 0. This limits how much is queried at once. Each page query is cached.
- the number of results field is working correctly IMO (events block) - doesn't allow empty, 0, more than 50.
- still hardcoded at +/-365 days
- limited to v3 block

https://user-images.githubusercontent.com/4663676/179259316-b4545002-7072-4998-93ed-13d9111f2dbf.mov
