### ISSUE TITLE
Provision seru.uiowa.edu

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#521]
D8 site, Wayne Jacobson needs webmaster access. Reassign to me when ready and I will follow up with customer.

**Comment by richardbporter** [comment]
This is done: https://seru.prod.drupal.uiowa.edu/

I'm not finding a communication from them. Did they want the production URL now?

**Comment by briand44** [comment]
No, DNS is setup but I’ve been waiting until they are ready to launch so I can be sure we get the old site deprovisioned. I’ll handle it from here. Thanks!

**Comment by briand44** [comment]
I communicated with the customer. Marking this complete.
