### ISSUE TITLE
As a webmaster, I can display jobs for units on site using the Aggregator functionality with RSS feeds

### ISSUE THREAD

**Issue by makurj** [uiowa/uiowa#5219]
# Story

As a webmaster, I can display jobs for units on site.

Example: https://tippie.prod.drupal.uiowa.edu/job-feeds

Faculty feed is working fine when using: https://jobs.uiowa.edu/jobSearch/rss/feeds/faculty/depts/12/faculty.xml
P&S (https://jobs.uiowa.edu/jobSearch/rss/feeds/pands/depts/12/pands.xml) and Merit do not (https://jobs.uiowa.edu/jobSearch/rss/feeds/merit/depts/12/merit.xml).

P&S did not pull in a job listed on the D7 site either: https://uiowa.referrals.selectminds.com/jobs/administrative-assistant-upo-19541
https://tippie.uiowa.edu/jobs

![image](https://user-images.githubusercontent.com/52135878/166251651-7378993b-1baa-4ce2-9a3b-286607942dca.png)

**Comment by joewhitsitt** [comment]
>P&S (https://jobs.uiowa.edu/jobSearch/rss/feeds/pands/depts/12/pands.xml) and Merit do not (https://jobs.uiowa.edu/jobSearch/rss/feeds/merit/depts/12/merit.xml)

These feeds are empty, so unless there is content to pull this will be hard to work on/debug if it is an issue on our end. 

Or are you saying it is an upstream issue where content for these feeds exists but is not in the feed? If that is the case, we just need to reach out the the development group responsible for these feeds.

**Comment by makurj** [comment]
There is content (https://uiowa.referrals.selectminds.com/jobs/administrative-assistant-upo-19541) for the P&S feed. It's not just display using the XML in D7 or D9. Merit has no content (jobs posted) so there's no way to test that.

**Comment by joewhitsitt** [comment]
The jobs site/XML feeds themselves are not Drupal. So this should be directed to someone else upstream

**Comment by makurj** [comment]
Yep, you mentioned that. Is there a specific person we work with? The "email support" option on the jobs page is linked to ITS HelpDesk email. https://uiowa.referrals.selectminds.com/info/help

**Comment by joewhitsitt** [comment]
That is where I would start. I am not aware of any work of ours that integrates with that site where we would know the contact.

**Comment by makurj** [comment]
Response from jobs.uiowa.edu feeds folks: "The Merit & P&S feeds below do not exist any longer – we switched from our old (homegrown) jobs system to a vended Oracle product called Taleo/OTAC back in 2019.  The new system doesn’t offer XML feeds like our old jobs site did. There is something OTAC calls “Jobs Search Widget” that could be used, but that currently has a bug that has been frustratingly slow to get resolved (and they still haven’t yet).  You could create a static link using any of the search criteria on this page: https://uiowa.referrals.selectminds.com/jobs/search/4203935, but be warned that it expires every 90 days. 
 
The Faculty side is still on the legacy jobs system, which is why those feeds still work."
