### ISSUE TITLE
deprovision 3mlearning.uiowa.edu on uiowa02

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#5222]
being replaced by learning.uiowa.edu

blocked waiting for vulture redirect - its-web email on 2022-05-02 and https://github.com/uiowa/uiowa/issues/4314

related its-web email thread for switching from 3mlearning to learning: "Question re: URL for SiteNow website"

- [x] confirm vulture redirect
- [x] lower ttl and ask hostmaster to point to vulture
- [x] deprovision

**Comment by joewhitsitt** [comment]
no longer blocked, domain removed. ideally do it as part of #4314

**Comment by richardbporter** [comment]
GONE
