### ISSUE TITLE
Create content type for Residence Halls

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5227]
As a Housing site owner, I would like to have a structured content type to store information about residence halls so that information can appear similarly across all residence hall pages.

# Additional Information

Setup content type (https://wiki.uiowa.edu/display/drupaldev/Content+type+creation+notes) as part of housing site split and create fields:

- [x] Building type - taxonomy or select list - (traditional residence hall or suite-style residence hall)
- [x] Room type - taxonomy or select list - (single, double, triple, quad)
- [x] bathroom type - taxonomy or select list - (community style, single-user, suite-style, private restroom)
- [x] Intro/Body - They need an intro paragraph to describe each residence hall. https://housing.uiowa.edu/residence-halls/burge-hall
- [x] Featured image field for top banner
- [x] Image field - multi - Would like to have a photo gallery of images of the residence hall
- [x] Video field - single - Add YouTube video that tells about the hall
- [x] Ability to show LLC's located in each hall - entity reference?
- [x] Furnishings - taxonomy - rabbit holed? (https://housing.uiowa.edu/residence-halls/burge-hall)
- [x] Amenities - taxonomy - rabbit holed? (https://housing.uiowa.edu/residence-halls/burge-hall)
- [x] Floor plans and 360 views - shows a sample floor plan and 360 views of a typical room (screenshot on epic)
- [x] Meet us - reference multiple people - had inline entity form on D7
- [x] Getting around info - A text area to provide information about proximity to other campus locations.
- [x] Links to bus stops - multiple link field with titles to enter stop names - no integration with Bongo.
- [ ] Map - Concept3D map of residence hall in relation to rest of campus. They would like this displayed higher up the page if possible when we get to the display.
- [x] Bathroom images - multi image field to display bathroom photos in some sort of gallery - could possibly link to a page if we feel that makes the most sense? 
- [x] Rates - They like how rates are handled on this site https://housing.umn.edu/bailey
- [x] Address - Include a section for mailing address for each particular residence hall. Similar to https://housing.umn.edu/bailey
- [x] Neighborhood - (East, West) select list
- [x] Year Built - Date (Year granularity)
- [x] Population (text field on D7)
- [x] Who lives here - taxonomy reference? (screenshot on epic) - Honors students live in all halls - want to make that more visible to visitors.
- [x] Front Desk phone - phone
- [x] Front Desk Hours - text area
- [x] Get Involved Call to action links - These currently have an icon, title and brief desc text
  - [x]   Connect with your community - will link to a page within Housing site
  - [x]    Advocate for Students - Links to arh.org.uiowa.edu - Rewrite text to say: Make a difference by being a resident assistant (RA). Would link out to My Housing section.
  - [x]    Work for Us - Links to studentlifejobs.uiowa.edu
 - [x]   Link to Dining Menu - Will link to dining.uiowa.edu
- [x] Link to place a work order - Include a section to place a work order, will link to housing.uiowa.edu/my-housing
- [x] Section to place information about emergency policies (This will be text only, so an accordion on each res hall page with this information or link out to a basic page could suffice.)

**Comment by briand44** [comment]
Not sure if the Map is straight forward, if we need to hold or have more conversations about this that is fine.

Photo Galleries - they mention a rotating gallery of images similar to D7 as well as a link to more photos (D7 opens in modal). Not sure if we want to recommend a different approach here? They also mention a bathroom photo gallery (Link to a gallery or something to show bathroom photos on each res hall page).

Not sure how D7 is handling the Call to Action Links, I wasn't seeing those structured on the content type.

**Comment by joewhitsitt** [comment]
I think we need to investigate options for the map field. Could that be split off into a separate task?

>Video field - single - Add YouTube video that tells about the hall
Could this just be part of the intro/body for mvp?

Date fields do not have the same granularity as in the past (ui press ran into this). Does year built need to be stored as a date or could a text field work for this? Or could this just be part of a "Building information" long text field so other information could be added to it in the future?

**Comment by pyrello** [comment]
It is annoying how it seems like the Drupal core team has given up on solving the issues that were introduced with Date fields in D8.

Here are a couple (less than ideal) contrib modules that might be worth looking into: 
- https://www.drupal.org/project/month_year
- https://www.drupal.org/project/yearonly

**Comment by joewhitsitt** [comment]
Should we experiment with https://www.drupal.org/project/schemadotorg when creating this content type?

**Comment by mjoneill** [comment]
> Should we experiment with https://www.drupal.org/project/schemadotorg when creating this content type?

I would love to participate. I have the sense that I'm a bit misaligned with how Drupal is thinking about implementing, managing, and governing schema...so anything that helps me understand where the opportunity is would be useful.  Not sure if this is the best opportunity to help me, but willing (if not excited) to participate if it seems like this is a good opportunity.

**Comment by bspeare** [comment]
> Should we experiment with https://www.drupal.org/project/schemadotorg when creating this content type?

How much further does that increase the scope of the issue?  Is this blocked until we can agree on this?

**Comment by joewhitsitt** [comment]
>How much further does that increase the scope of the issue? Is this blocked until we can agree on this?

I haven't even tried the module yet, so I don't know. It would also be a departure how we have building. So maybe not worth it for this particular issue, but I do want to explore it at some point in the future (like how we looked at Gin). I think it is developer's choice at the moment.

**Comment by pyrello** [comment]
Trying this out would expand the scope of this, but it might be a good opportunity to do some dabbling. Here's how I would approach this:
* Pick a subset of 5-10 fields and set up the content type based on those.
* Get everything set up as though you were doing this without the Schema.org module, with all the config exported and committed.
* Add the module, test out how it works, see if it seems worthwhile to invest more. Probably check in with the team at this point.
* If we decide to move ahead with this approach, export and commit the related config.
* If we decide not to move ahead with this approach, then re-import config and the changes that were made will be gone.
* Finish building the content type.

**Comment by bspeare** [comment]
It looks like these are listed as either taxonomy or select-list.   Are there any objections to making them all taxonomy?

- Building type
- Room type
- Bathroom type

**Comment by bspeare** [comment]
Are we thinking text or date field for the "Year built" field?  Are you referring to this field in your comments @joewhitsitt @pyrello?

**Comment by joewhitsitt** [comment]
I think in grooming we talked about the editor benefit of having the ability to add/edit options in which taxonomy for now is best suited. Rabbit holed by default until there is a use-case for displaying them.

**Comment by bspeare** [comment]
I have enabled the https://www.drupal.org/project/schemadotorg module and used the `Place` schema.org type and Drupal reminds me `Experimental modules are provided for testing purposes only. Use at your own risk.`.  So here are a few initial observations:

- The fields that you assign to Schema.org properties are all put into `details` toggles on the form edit screen which is cool, yet:
  - It overrides `_sitenow_node_form_defaults` 
  - It puts the Address field into a "Contact Information" `details` and defaults to `-None-` instead of the specified `United States`

**Comment by bspeare** [comment]
~These items all look like they hardcoded fixed links in the D7 site, do we want to do the same here and place these in a custom block?~
<details>
- Get Involved Call to action links - These currently have an icon, title and brief desc text
- Connect with your community - will link to a page within Housing site
- Advocate for Students - Links to arh.org.uiowa.edu - Rewrite text to say: Make a difference by being a resident assistant (RA). Would link out to My Housing section.
- Work for Us - Links to studentlifejobs.uiowa.edu
- Link to Dining Menu - Will link to dining.uiowa.edu
- Link to place a work order - Include a section to place a work order, will link to housing.uiowa.edu/my-housing~
</details>
Edit: going to proceed with adding these fields.

**Comment by bspeare** [comment]
@briand44 Did they want these fields on the content type?

<img width="427" alt="Screen Shot 2022-05-17 at 1 36 06 PM" src="https://user-images.githubusercontent.com/1036433/168887673-d6faf03f-6bc2-4f0a-b2f5-85ef9837748b.png">

<img width="394" alt="Screen Shot 2022-05-17 at 1 48 42 PM" src="https://user-images.githubusercontent.com/1036433/168888003-0edf1c45-0cd7-417c-a507-348a0a7e6428.png">

**Comment by briand44** [comment]
Those are no longer needed. Not sure if you have access to https://iowa.sharepoint.com/:x:/r/sites/UniversityHousingandDining2/_layouts/15/Doc.aspx?sourcedoc=%7B9519e783-5754-4dde-851d-fcdee9e0404d%7D&action=edit&wdinitialsession=f170c4a1-1d68-468a-94f0-5d387cd53ba3&wdrldsc=15&wdrldc=2&wdrldr=BootTimeMismatch&cid=589ae912-8ef0-4b16-8b84-210272641d49 but that is where I was getting all my info.

**Comment by bspeare** [comment]
I did a little layout exploration for this after the Tippie meeting this afternoon to get a better sense of how all these fields might work together: https://sandbox.prod.drupal.uiowa.edu/catlett-hall.

**Comment by joewhitsitt** [comment]
Wondered about using the "schema.org place" sub-module for this as a follow-up task once fields are decided/final. I think https://schema.org/Residence type is the closest you get to a residence hall/dormitory.
