### ISSUE TITLE
Tours - Round 2

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#523]
## Problem
Since the first tour iteration, we have added new functionality that we might want to highlight with tours.

## Proposed Solution
Using the voice and style of the current tours, create additional tours for:

- [x] SiteNow Articles (config page, view page)
- [x] SiteNow People (config page, sort page, view page)
- [x] Person Content Type
- [x] Article Content Type

Expand existing tours to touch on:
- [x] oEmbed
- [x] Featured Image

The basics of adding or modifying a tour:
- start with with the default site
- find the route via /devel/routes
- copy an existing tour config file minus the uuid and config hash.
- run CIM and CRs till the cows come home to test.
- CEX to properly write the config file.

## Test
Make sure tours can be activated for these from a fresh install. Keep in mind that the articles/people view pages and content alias patterns can change through user configuration. so target tours on routes and not URL aliases.

**Comment by dnkemper** [comment]
@joewhitsitt @briand44 @richardbporter Should I add tours for all of the media options as well (ie Instagram, FB, Twitter etc.) or leave it as is?
