### ISSUE TITLE
As a site editor, I can set margins on a card block

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#5234]
# Story

As a site editor, I can set margins on a card block so that I can use multiple card blocks in the same region without having them stack on top of each other. 

Example of two cards in the same region that could use some margin:

![image (6)](https://user-images.githubusercontent.com/1036433/166998202-14c285d2-3c0f-4bae-bcfd-d53a64de328a.png)

# Proposed solution

Add margin top and bottom styles from our `margin` layout builder styles. 

<img width="684" alt="Screen Shot 2022-05-05 at 1 34 00 PM" src="https://user-images.githubusercontent.com/1036433/166998903-93caba05-b716-4ec9-bdae-dcf42d41415d.png">

Related issues:

How will this work with these issues?
- https://github.com/uiowa/uiowa/issues/4317
- https://github.com/uiowa/uiowa/issues/2670
- https://github.com/uiowa/uiowa/issues/4917

**Comment by makurj** [comment]
Checked with @nlichthardt and this has been resolved by https://github.com/uiowa/uiowa/issues/2670.

**Comment by briand44** [comment]
@bspeare should we close this?
