### ISSUE TITLE
Upgrade to BLT 13.4.0 and remove private files code from post-command hook.

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#5236]
https://github.com/acquia/blt/releases/tag/13.4.0 includes a change to set multisite private files directories correctly. Once upgraded, the code referenced below in our post-command hook for `source:build:settings` could be removed.

https://github.com/uiowa/uiowa/blob/13b5e2c6b5233c68bfab57da13fb047ad9a2ca9b/blt/src/Blt/Plugin/Commands/ReplaceCommands.php#L233-L236

**Comment by joewhitsitt** [comment]
We upgraded blt as part of #5611
