### ISSUE TITLE
Figure out path forward for Concept3d and Cambus fields. Any others that we are unsure about?

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5238]
Static maps -https://help.concept3d.com/hc/en-us/articles/360008043454-Static-Maps (requires marker id but could capture that in a field and then construct the markup needed for render.

As for bus stops (currently integrated with bongo module) - could we just tell them to get the stop numbers themselves? if bongo goes away entirely these links will break.

**Comment by joewhitsitt** [comment]
The concept3D API might be a way to do a building => marker lookup but there might be bumps: https://github.com/uiowa/uiowa/issues/4591#issuecomment-1005216374

**Comment by briand44** [comment]
In relation to the bus stops, I have an email out to the app devs. I know they have mentioned transitioning api.ebongo.org to icareatransit.org but not sure if we should continue using api.ebongo.org.

Also, have an email out to Megan for some clarity here on what she is looking for specifically.

**Comment by briand44** [comment]
For the bus stops, the customer is fine with us just creating a multi-valued link field with a link title so they can specify the bus stop name. They will manually input the stops and we can avoid the integration with the Bongo API. I think they would continue to want these links styled as buttons but if we feel differently we can provide an alternate look and get feedback.

**Comment by briand44** [comment]
Even though we don't need this now I wanted to capture it somewhere. api.ebongo.org is fine to continue using and it will eventually move to icareatransit.org.

**Comment by joewhitsitt** [comment]
I wonder if we could just parse a pasted share URL into a static map. This would be easy for editors to get. `!m/579418` is the marker id in this situation.

<img width="488" alt="Screen Shot 2022-05-11 at 11 47 06 AM" src="https://user-images.githubusercontent.com/4663676/167903937-371b4b27-9e0c-467d-a51c-922dca78e2ab.png">

**Comment by joewhitsitt** [comment]
I think a compound field (e.g. addressfield) that takes share link, zoom level, label text (required for alt text). Scale should just be set to 4 with a width 100% on the parent div since we can't do responsive images here. Renders a linked wrapped image with hover/focus effect.

```html
<a href="https://maps.uiowa.edu/?id=1890#!m/579418">
  <img src="https://staticmap.concept3d.com/map/static-map/?map=1890&loc=579418&scale=4&zoom=17" alt="Required label text"/>
</a>
```

Alternatively, we could use background image to control aspect ratio. https://www.wpi.edu/about/locations/alumni-stadium
<img width="1466" alt="Screen Shot 2022-05-11 at 12 15 13 PM" src="https://user-images.githubusercontent.com/4663676/167908557-271f6aa4-20d6-4e0a-9db8-c07e3bff1622.png">

**Comment by joewhitsitt** [comment]
This is growing on me (controlling aspect ratio):

<img width="932" alt="Screen Shot 2022-05-11 at 12 27 57 PM" src="https://user-images.githubusercontent.com/4663676/167910598-ee928ed2-0ee4-4196-a94e-5457d37ac5e5.png">

**Comment by joewhitsitt** [comment]
Noticed though that these are really slow to load initially... There is a 3.8 MB difference between scale 4 and 2 if we don't mind scaling for divs greater than 1024px wide.

**Comment by joewhitsitt** [comment]
Going to dig into this a bit more

**Comment by joewhitsitt** [comment]
Hey look. A static map.
<img width="345" alt="Screen Shot 2022-05-11 at 3 55 25 PM" src="https://user-images.githubusercontent.com/4663676/167946050-8dd69b3c-f1fc-44d9-a9a4-06750cd86141.png">
<img width="1036" alt="Screen Shot 2022-05-11 at 3 55 10 PM" src="https://user-images.githubusercontent.com/4663676/167946107-0d7e4270-9613-4953-8d95-b9d6759deddc.png">

**Comment by joewhitsitt** [comment]
I think this investigation is done. The features are done however but might be addressed in future issues.
