### ISSUE TITLE
Finish SiteNow site

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#524]
theme changing
marketing site
link to docs
portfolio
request form
policies
faqs/known issues
Help Desk Contact
contact sitenow?

**Comment by joewhitsitt** [comment]
- Just swapped out the sitenow white image for high-res version.
- Changed some social media links to provide consistent icons and descriptive menu link text.
- Tweaked FAQ page to spell it out, left the URL path/menu title short.

I have some other ideas for MVP but it will require me to write some content to make a better pitch.

**Comment by dnkemper** [comment]
https://github.com/uiowa/uiowa/issues/564

**Comment by joewhitsitt** [comment]
- [x] Site Request form (@richardbporter)
  - [x] Restricted Access
  - [x] Trigger email buttons
- [x] Change inquiry options (now stored in site split config)
  - General, Billing, Feature Request
  - Support = change to show just markup/alert that says they should initiate a ticket through the help desk.
  - Remove other options
- [x] Vanity Domain policy

**Comment by richardbporter** [comment]
I've got the emails in master now. I think its "done" but feel free to provide feedback and/or alter.

**Comment by joewhitsitt** [comment]
#557, #564 are related but not keeping this task from completion.

**Comment by joewhitsitt** [comment]
Should we create a non-GitHub roadmap for features that we can display to folks?

**Comment by dnkemper** [comment]
@joewhitsitt that would be pretty cool!

**Comment by richardbporter** [comment]
- [x] Updated request form email signatures

> ITS - Custom Solutions & Integrations - Web Services

**Comment by joewhitsitt** [comment]
Added a draft "Future enhancements" page (roadmap). /future-enhancements

**Comment by richardbporter** [comment]
- [x] Redirect docs.sitenow.uiowa.edu to sitenow.uiowa.edu/documentation

- [x] Redirect user to form after logging in
Right now, we're printing the user login block on the form page. We'll probably have to alter the form to append the destination parameter to the SAML login path.

- [x] Copy us on every email sent
Just a CC on all email so we can track what is being sent. Bonus points for creating a rule in the ITS web account that moves all request form emails to a folder.

- [x] Add top level domain email
This would be an another email similar to the hostmaster/customer emails that are _not_ sent automatically. An email to hostmaster copying the customer saying something like "so and so has requested the top level domain XXX. Please advise."

- [x] Improve URL help text, e.g. "current URL" for existing site pattern. 
This should probably be done via a form alter using the states API.

**Comment by richardbporter** [comment]
> Should we create a non-GitHub roadmap for features that we can display to folks?

Timeline paragraph bundle!

**Comment by richardbporter** [comment]
#653 redirects users back to the request form when clicking the link in the block.

**Comment by richardbporter** [comment]
#654 improves the URL field description.

**Comment by joewhitsitt** [comment]
> > Should we create a non-GitHub roadmap for features that we can display to folks?
> 
> Timeline paragraph bundle!

Gosh, another example of a "list" paragraph bundle that could have just had different view modes (accordion, list, timeline, definition list, etc.)

I can see the rows of revisions now! 👀

**Comment by richardbporter** [comment]
I think the site is "done" enough to launch.

**Comment by dnkemper** [comment]
Added a redirect for the docs.sitenow.uiowa.edu page

**Comment by richardbporter** [comment]
👍
