### ISSUE TITLE
Audit D7 sites for usage of bongo module and other references to bongo.org.

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5241]
The bongo.org domain is expiring September 26th. We should see what sites are currently using this module or that reference bongo.org and update.

# Proposed Solution
703:
- [x] Verify the bongo and bongo predictions modules aren't disabled on any sites that would require an uninstall
- [x] Move the Bongo module local to housing and dining.
- [x] Update `uiowa703-dev/docroot/sites/dining.uiowa.edu/themes/dining/includes/field.inc`
- [x] Update `uiowa703-dev/docroot/sites/dining.uiowa.edu/themes/housing/includes/field.inc`
- [x] Remove the Bongo module from the profile
- [x] Run `drush cc all` on housing and dining after deployment

702:
- [x] Verify the bongo and bongo predictions modules aren't disabled on any sites that would require an uninstall
- [x] Remove the Bongo module from the profile

701:
- [x] Verify the bongo and bongo predictions modules aren't disabled on any sites that would require an uninstall
- [x] Remove the Bongo module from the profile
- [x] Remove footer link from Stories site `dev/docroot/sites/stories.uiowa.edu/themes/stories/templates/page/page--front.tpl.php`
- [x] Update `uiowa701-dev/docroot/sites/hawktools.uiowa.edu/modules/custom/bongo/bongo_panes/plugins/content_types/bongo_predictions.inc:`
- [x] Update `uiowa701-dev/docroot/sites/hawktools.uiowa.edu/modules/custom/uiowa_signage_modules/uiowa_signage_panes/plugins/content_types/bongo_predictions_multiple.inc:`
- [x] Remove Bongo text on home page

Signage - I don't think we need to do anything here.
HC Signage - I don't think we need to do anything here.
CLAS - https://github.com/uiowa/uiowa/issues/5241#issuecomment-1256726607

**Comment by briand44** [comment]
Quick search turned up that this module exists on 701, 702, 703, signage, healthcaresignage. Also, noticed some references to bongo.org on Hawktools, Housing, Dining. Could be more

**Comment by briand44** [comment]
We may be able to update bongo.org links to link to icareatransit.org. So https://bongo.org/stop/1050 would be updated to https://icareatransit.org/stop/1050.

**Comment by joewhitsitt** [comment]
Do we need to put out an announcement about this? I know there are some content links pointing there.

**Comment by briand44** [comment]
>Do we need to put out an announcement about this? I know there are some content links pointing there.

My understanding is that the CSI app devs own Bongo and that any communication regarding this should come from them. I can ask if they are planning on any communication once I hear back on if the domain is actually expiring. I think there was previous communication around this long ago but it may not hurt to communicate again.

I'll also ask about the redirect.

**Comment by briand44** [comment]
It looks like if you go to bongo.org it redirects to icareatransit.org?bongo=true and then outputs a message letting folks know they should update bookmarks.

Haven't received any further clarification on this today. It looks like Mark H is out but will be back tomorrow. I will follow up with him tomorrow.

**Comment by briand44** [comment]
So, I went ahead and renewed this for 1 more year. The plan is to pick a date when we want to "turn off" DNS, send comms out (likely UI Web Community, UI App Dev Community, maybe others like Iowa City/Coralville) and then if no push back, go ahead and "turn off" DNS. I can likely figure out this part in combination with the CSI app dev team.

This issue is still relevant since the plan is to still retire the domain bongo.org, just not quite as urgent.

**Comment by briand44** [comment]
## Bongo module usage:

703
housing.uiowa.edu - This site is now on v3. Could likely disable the module here. The D7 site may go away on Tuesday.
dining.uiowa.edu

702
~intranet.oneit.uiowa.edu - doubt it is actually being used here. We could potentially disable this module.~

701
hawktools.uiowa.edu - local bongo module

Signage
signage.uiowa.edu

HC Signage
signage.uihealthcare.org

CLAS
It is here, not sure if it is used. Can't run `drush @sites pmi bongo -y | grep 'enabled'` because there are subdirectory sites

Dentistry
Nope

Grad
Not seeing it here.

Icgov
Nope

## Bongo.org code references:
### 701
- uiowa701-dev/docroot/sites/hawktools.uiowa.edu/modules/custom/bongo/ (This seems to be a custom hawktools module)
- uiowa701-dev/docroot/profiles/sitenow/modules/contrib/bongo/bongo.module
- uiowa701-dev/docroot/sites/hawktools.uiowa.edu/modules/custom/uiowa_signage_modules/uiowa_signage_panes/plugins/content_types/bongo_predictions_multiple.inc
  54,112:     '#description' => t("The Stop IDs from !url. These stops will rotate in one block.", array('!url' => l(t('eBongo.org'), "https://ebongo.org"))),
  54,135:     '#description' => t("The Stop IDs from !url. These stops will rotate in one block.", array('!url' => l(t('eBongo.org'), "https://ebongo.org"))),
- uiowa701-dev/docroot/sites/stories.uiowa.edu/themes/stories/templates/page/page--front.tpl.php
  73,420

### 702
- uiowa702-dev/docroot/profiles/sitenow/modules/contrib/bongo/bongo.module

### 703
- uiowa703-dev/docroot/profiles/sitenow/modules/contrib/bongo/bongo.module
- uiowa703-dev/docroot/sites/dining.uiowa.edu/themes/dining/includes/field.inc
  49,33:             '#path' => 'https://bongo.org/stop/' . $id,
- uiowa703-dev/docroot/sites/housing.uiowa.edu/themes/housing/includes/field.inc
  319,33:             '#path' => 'https://bongo.org/stop/' . $id,

### Signage
- uisignage-dev/docroot/sites/all/modules/contrib/bongo

### HC signage
- uihealthcaresignage-dev/docroot/sites/all/modules/contrib/bongo

### CLAS
- uiclas-dev/docroot/sites/all/modules/bongo

### Dentistry
- Zilch

### Grad
- Zilch

### ICGov
- Zilch

**Comment by briand44** [comment]
How should we handle these changes to the bongo module? My understanding is that we are currently using the contrib module https://www.drupal.org/project/bongo. Should we move this to custom when we make these changes and run a `drush cc all` after? Leave it in contrib and hack it? Update version?

**Comment by briand44** [comment]
Could remove it from the profile on 701-703 and add it local only where needed (maybe just hawktools which it is already local and dining)

**Comment by GaryRidgway** [comment]
what does that look like? are we still able to make the same api calls with [icareatransit.org](http://icareatransit.org/)?

**Comment by GaryRidgway** [comment]
I have started on a feature branch for 701

**Comment by briand44** [comment]
checking to see if we can turn off the Bongo module for OneIT intranet.

**Comment by briand44** [comment]
@mark-bennett-uiowa do you happen to know of any CLAS sites that would be using the Bongo module? It looks like the module is available on the CLAS application, I'm just not sure if it is actually being used.

**Comment by briand44** [comment]
disabled and uninstalled bongo and bongo content panes from the OneIT Intranet

**Comment by mark-bennett-uiowa** [comment]
> @mark-bennett-uiowa do you happen to know of any CLAS sites that would be using the Bongo module? It looks like the module is available on the CLAS application, I'm just not sure if it is actually being used.

The only site that should or would be using that was the old [https://clas.uiowa.edu/signage/](https://clas.uiowa.edu/signage/) that is no longer used and was replaced by signage.uiowa.edu years ago.

I am going to ping Isaac Podolefsky and see if he can check the device/site list to see if any devices are still pointing at the clas.uiowa.edu/signage domain.

I would be fine uninstalling and removing the bongo module from the CLAS application, and then letting any stragglers hiding in the shadows letting me know something is broken.

### UPDATE (9-26-2022):
- Device check was performed by Isaac and no instances were found of digital signs pointing to a clas.uiowa.edu/signage/* location.
- Ran command to check for installed/enabled/disabled BONGO module in remaining uiclas application sites. None were found beyond clas.uiowa.edu/signage site.
- Backed up and deleted old clas.uiowa.edu/signage site from uiclas application.
- Deleted BONGO module from uiclas application.

CLAS is good to go now, no concerns remain for this issue.

**Comment by briand44** [comment]
703:
- [ ] Move the Bongo module local to housing and dining.
- [ ] Update uiowa703-dev/docroot/sites/dining.uiowa.edu/themes/dining/includes/field.inc
- [ ] Update uiowa703-dev/docroot/sites/dining.uiowa.edu/themes/dining/includes/field.inc

**Comment by briand44** [comment]
I updated the IS with a proposed solution

**Comment by briand44** [comment]
703 and 702 have been deployed to prod and are complete. CLAS is also complete. I have deployed 701 to dev and still want to do some testing there before deploying to prod.

**Comment by briand44** [comment]
701 deployed to prod
