### ISSUE TITLE
P2LB - Map paragraph ID to block ID for custom block types in LB

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#5246]
With #3567 done, we now have the ability to map the unique IDs from paragraphs to blocks.

# Proposed solution
Modify the p2lb module to set the unique block ID based on the corresponding paragraph ID.
We will address list blocks, sections, accordion items, etc in a follow up issue.

**Comment by makurj** [comment]
I'd like to work/pair on this.

**Comment by briand44** [comment]
xdebug is your friend
