### ISSUE TITLE
Article migration for research.uiowa.edu

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5248]
# Story

As a site owner of research.uiowa.edu, I would like our articles migrated to our new v3 site so those will continue to be available to visitors and we can avoid manually transitioning all of them.

# Additional Info
My understanding is that they are hoping to launch by end of calendar year 2022.

- What articles should we be migrating? - **We are only migrating "articles" not "articles (deprecated)".**
    - Are we migrating articles or articles (deprecated) or both?
        - ~1,850 articles (deprecated) published
        - ~400 articles published
    - Articles created by feeds? Economic Development and Research feeds from Iowa Now - **They are planning link out to Iowa Now for Research articles. Economic Development is no longer part of this org.**
    - All articles or only articles since x date? **All articles**
- Are we migrating terms?
    - Yes, migrate tags that are tied to a news article
- Creating redirects?
    - Yes
- How to handle fields that are not in default content type for v3?
    - Title -> Title
    - Type -> No longer needed but External and Iowa Now articles types should have the "Link directly to Source" checked
    - By Line -> Organization
    - Publication Source -> Ignore - not used
    - External Url -> Source Url
    - Iowa Now url -> Source Url
    - Body -> Body
    - Image -> Featured Image - Don't display these for ones that are migrated.
    - Image Override -> I think we can ignore this as I am not seeing usage.
    - Contacts -> map to new contact person reference from #5999. We are not creating new people just referencing ones that exist on new site. [Leslie has provided us with mapping info](https://github.com/uiowa/uiowa/issues/5248#issuecomment-1341387260).
    - Tags -> Tags

# Proposed solution

**Comment by cory-skeers** [comment]
List of existing people and how they should be mapped. "person created" refers to people who hadn't previously been added to the site, but should now exist.

| Existing person | New site | Source ID | Destination ID |
|-----------------------|--------------------------|-------------|-------------|
Lauren Galliart  |        Link to existing person |       8201|      756
Leslie Revaux |                     Link to existing person |     4026 |       61
Michael Weaver |                   Link to existing person |     7501 |     241
Leslie Revaux |                       Link to existing person |     2291 |      61
Aaron Kline     |                       Link to existing person |     2736 |    216
Bob Kirby        |                       Link to Robert Kirby |        6126 |     141
Leslie Revaux |                       Link to existing person |     7796 |     61
Cheryl Ridgeway |                  delete contact person, link to Britt Ryan |    6316 |    226
Bob Kirby         |                      Link to Robert Kirby |      6511 |      141
Sarah Tallman |                      Link to existing person |     5921 |     236
Jennifer Brown    |                                person created |      5551 |    766
Michael Pentella |                   Link to existing person |     5036 |     416
Susie Dai                              |   delete contact person, do not show a contact |        4821  |   -
Stephen Pradarelli              |    delete contact person, link to Leslie Revaux |        1123 |     61
Teresa Mangum                 |     Link to existing person          |           3116 |       361
Paul Dymerski                   |      delete contact person, do not show a contact  |           2566 |      -  
Leslie Weatherhead      |         link to Leslie Revaux  |           1766 |      61
Kurt Heiar                         |       person created  |           1657 |      771
Kristi Thiel                       |        delete contact person, do not show a contact  |           1658 |       -
Leslie Weatherhead      |         link to Leslie Revaux  |           1121 |       61
Randy Nessler              |           Link to existing person  |           1104 |      291
Peter Weyer                 |           person created  |           1101 |      776
Leslie Weatherhead   |            link to Leslie Revaux  |           1086 |      61

**Comment by briand44** [comment]
Brian to get IDs for each of the article contacts on the existing site

**Comment by briand44** [comment]
I've updated the contact mappings to include a source id (article contact node id from existing site) and a destination id (person node id on the new site)

**Comment by joewhitsitt** [comment]
>Type -> No longer needed but External and Iowa Now articles types should have the "Link directly to Source" checked

~~AFAIK there are no `Article (Machine name: ovpred_article)` content with external or iowa now types selected but there are values for the related link fields that are revealed for each of these options.~~

Nevermind, I was looking at the wrong field for the content type...

**Comment by joewhitsitt** [comment]
I put #6047 up for review as I think the deliverables have been met and it would be good to have other eyes on it.

**Comment by briand44** [comment]
We got approval to move ahead and run the migration in prod.

**Comment by joewhitsitt** [comment]
PR merged. Needs deploy. Delete existing articles in PROD before running. Give them a heads up to have editors "freeze"

**Comment by joewhitsitt** [comment]
Scheduled to work on this tomorrow morning. Deployment going out now.

**Comment by joewhitsitt** [comment]
This was done in PROD this AM. Customers notified, broken links report attached.
