### ISSUE TITLE
Display jobs on research.uiowa.edu

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5249]
# Story

As the person who lists job opportunities for research.uiowa.edu, I would like the ability to manually create these on our website to have more flexibility on the information and appearance of these postings.

# Additional Info
They would like to be able to schedule these job opportunities to unpublish on a specified date.

Hopefully we can display using feeds and avoid developing this but likely need more conversations around this.

# Proposed solution

**Comment by joewhitsitt** [comment]
Does this intersect at all with https://github.com/uiowa/uiowa/issues/2299?

**Comment by briand44** [comment]
I hope so but it sounds like there is one individual who likes having this structured on their site. I added needs more info and discussion needed labels because I plan to have more conversations around this when we get closer to working on this site.

**Comment by briand44** [comment]
https://github.com/uiowa/uiowa/issues/5219#issuecomment-1121299875

**Comment by briand44** [comment]
Closing this as they created a landing page and are linking out to jobs.uiowa.edu.
