### ISSUE TITLE
Registrar electronic diplomas

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5250]
As an institution offering a CeDiploma, we need to create a page on the Registrar website that will host the validation mechanism in order to meet the requirements of the vendor.

# Additional Information
There is an email with dropbox credentials that contains documentation and assets. I will share in our shared support inbox.

I believe this is going to need to be some sort of custom built form using the D7 Form API. End result will be very similar to https://cecredential.stanford.edu/cecredential/.

Documentation mentions another html page but that is out of scope for our team.

**Comment by mjoneill** [comment]
Timeline: Students are going to be getting emails about their credentials June 1 (+/- 2 days).  June 1 seems like the estimated launch date.  Emails might not go out until the 3rd though.

Drupal component: In the dropbox, there are code examples, including a Drupal module: [Dropbox Root]/Validation Web Page/WebAPIHTML_SampleCode/ServerSide/Drupal 8-9 Plugin

Related web pages:
- https://registrar.uiowa.edu/credential-validation Informational page - no work for dev team 
- https://registrar.uiowa.edu/credential-validation - this is the credential embed page (equivalent of the Stanford example above)

**Comment by joewhitsitt** [comment]
Who should I talk to about this part? @briand44 @mjoneill 

>Display the results of the validation to the user on the Validation web page. Please consult with your Institution administration for preferred formatting of your validation response.

<img width="960" alt="Screen Shot 2022-05-16 at 3 01 02 PM" src="https://user-images.githubusercontent.com/4663676/168672790-ff1d4170-ef76-42be-abe8-7e73ee7814b4.png">

**Comment by briand44** [comment]
forwarded Joe an email with our contacts at the Registrar office in case we need to reach out with questions. They can also help facilitate a call with the vendor if needed.

**Comment by joewhitsitt** [comment]
This has been pushed out to DEV for customer/vendor testing (branch: `cecredential-registrar`)

https://registrar.dev.drupal.uiowa.edu/credential-validation

- Enable the `cecredential` module on registrar
- Customize the page (panelizer) they want it on by adding the CeCredential Validator pane (Miscellaneous) and configuring it with the credentials they specify.

@briand44 is in touch with the customers

**Comment by briand44** [comment]
Remove the validation and field for first name. Add GMT to timestamp. Add CHEA verbiage. 3 links need to be added.

**Comment by briand44** [comment]
>Validation Page:
1.) Please add the “More about CeCredentials” section mentioned above to this page as well. You will swap out the Validation hyperlink with a hyperlink to your Overview page.
2.) Remove the need for the first two letters to validate.
3.) Add GMT to the time stamp when a credential is validated. 
4.) We recently updated our logo to the one attached. Please update the “powered by CeCredential Trust” logo to our new one. It appears you all are harvesting it from our cloud and the URL for the new logo is https://cedimages.blob.core.windows.net/publicimages/Content/Images/CeDiplomaImages/poweredbyCeCredentialTrustLogo_251x50.png 

>Once these updates have been made please let me know. Once the webpages are approved we will move onto the “Go live” phase. That phase includes setting up the enote and page 2 and conducting a final test order in production. If you all have any questions or concerns please don’t hesitate to reach out.

**Comment by briand44** [comment]
And this is the "More about CeCredentials" info mentioned:

>Please add the “More about CeCredentials” section with the hyperlinks
-Validation (Will be hyperlinked to your validation page)
-Features (https://secure.cecredentialtrust.com/cecredential/overview/)
-FAQs (https://secure.cecredentialtrust.com/cecredential/faq/)

**Comment by briand44** [comment]
I believe the way this is setup the customer has the ability to add content (currently above the validation) to this page. The "More about CeCredentials" info could possibly be handled by the customer or us in the body of the page rather than inside the module so we don't have to update code if this info needs to change. Would could also adjust the validator to show first on the page if this info should show below the validator.

**Comment by briand44** [comment]
The other option which may make the most sense is if the "More about CeCredentials" links use the menu system.

**Comment by briand44** [comment]
Similar examples shared by vendor.
https://home.llu.edu/cecredential/validation
https://www.conncoll.edu/tp/certified-electronic-diplomas/cediploma-validation/

**Comment by briand44** [comment]
I removed the field for the first two letters of the first name as well as the validation related to that field. 
Also, added "GMT" after timestamp. 
Added updated logo. 
Added chea logo/verbiage and more info text.

These changes have been deployed to dev. https://registrar.dev.drupal.uiowa.edu/credential-validation

I have not added the three links, I want to touch base with Josh to see if we should add menu links for those rather than adding text on two different pages.

I would be interested in someone pulling this branch locally and at a minimum doing a code review.

**Comment by briand44** [comment]
Met with Josh and he is adding the additional links to the menu system in dev so we can share all the updates with the vendor via links and not have to meet again to demo these changes. https://registrar.dev.drupal.uiowa.edu/credential-validation

This is awaiting review from Vendor again.

**Comment by briand44** [comment]
I checked the master branch back out in dev, merged and deployed this code to prod, enabled the module in prod, added the pane to the page in prod, updated the endpoint to use the production endpoint and communicated with the customers. This should be done now but will wait for confirmation.

**Comment by joewhitsitt** [comment]
Thanks for picking up the work on this

**Comment by briand44** [comment]
Going to close this as it is in production environment. We can create a follow up if anything else comes up.
