### ISSUE TITLE
IISC - Create person content migration

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#5262]
Create a migration and source class to handle the person type.

**Comment by pyrello** [comment]
Per conversation with the customer, we are going to:
- Add Community Partner to the person types. Leave Faculty, Staff, and Student active as person types. Disable Emeritus, Graduate Assistant, and PhD Candidate as person types.
- Map the rest of the current groups to tags.
- Not migrate the Role with IISC field data.

I'm just realizing that this means creating tags that don't already exist and I'm not sure how to do this off the top of my head. @cory-skeers If you happen to know of any examples, that would be much appreciated. If not, maybe we can huddle to chat about it later.

**Comment by cory-skeers** [comment]
> I'm just realizing that this means creating tags that don't already exist and I'm not sure how to do this off the top of my head. @cory-skeers If you happen to know of any examples, that would be much appreciated. If not, maybe we can huddle to chat about it later.

Yup! We can chat about it, but the in-progress Tippie migration @joewhitsitt just worked on has an example kind of like this--it maps some old terms to new, sometimes multiple, with some tag creation as part of it. Basically it all happens within the `prepareRow` instead of a separate term migration, tracking existing terms by a name lookup and creating new if needed, then passing the mapped term ids in as a processed variable.

**Comment by pyrello** [comment]
> Yup! We can chat about it, but the in-progress Tippie migration @joewhitsitt just worked on has an example kind of like this--it maps some old terms to new, sometimes multiple, with some tag creation as part of it. Basically it all happens within the prepareRow instead of a separate term migration, tracking existing terms by a name lookup and creating new if needed, then passing the mapped term ids in as a processed variable.

Since it was only 3 terms, I ended up deciding to just create them in the new site and manually map the old IDs to the new IDs. Thanks for the insight, I'll take a look at that so I can understand how it would be done in the future.
