### ISSUE TITLE
IISC - Create views for new Partner and Project content types

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#5263]
# Views needed
For reference: https://iisc.uiowa.edu/partnerships
- Projects
  - by Partner NID (block)
  - Tags (block)
  - College/Depts (block)
  - All (block)
- Partners
  - ~Current (block)~ - This can be left out.
  - All by Year (block)
  - All (page)
  - Most recent (block)
  - List All (block)
- All colleges and departments (page - grid of term teasers)
- Nope. ~Need to check if actually needed: https://iisc.uiowa.edu/partnerships/all ?~

**Comment by briand44** [comment]
>Need to check if actually needed: https://iisc.uiowa.edu/partnerships/all ?

From what I was hearing it sounded like this was probably not needed? Did we confirm that?

**Comment by pyrello** [comment]
> > Need to check if actually needed: https://iisc.uiowa.edu/partnerships/all ?
>
> From what I was hearing it sounded like this was probably not needed? Did we confirm that?

I sent an email to confirm, but I'm pretty sure we're not including this.

**Comment by cory-skeers** [comment]
@pyrello for the "Current" partners view--it looks like this was previously handled with a "current" boolean on the partner content type. Does that field need to get added, or is there a change to how a partner should be considered current?

**Comment by pyrello** [comment]
> @pyrello for the "Current" partners view--it looks like this was previously handled with a "current" boolean on the partner content type. Does that field need to get added, or is there a change to how a partner should be considered current?

@cory-skeers I forgot that the customer decided to forgo the "Current" checkbox on the partner content type. You can skip that view. Thanks!
