### ISSUE TITLE
Facilities Development

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5264]
Just dumping all this here for now.

- Building lists — pulls up-to-date information from FM-managed building lists including populating building pages with ongoing projects that affect that building. 

- Building information page – brings together SIMS space information, mapping, energy dashboards, art on campus, and project information from BuildUI (Rakesh Rao)

- Building Coordinators — pulls Building Coordinator directory information including building and secondary contacts. 

- Project Information page – brings in custom information from BuildUI and SIMS,  like project description, timeline, budget, etc. Search by building or see featured list (pulled by date and construction phase)  
    - Capital Projects 
    - Featured Projects 
    - Project details (by project number/ by building number) 

- Bid list – brings in bid info from BuildUI (Rakesh Rao) 

- Access and Construction Alert system – construction manager enters details of alert, sets a dispatch email notification to a listserv, email template, subscription button, edit ability of alert, posts to alert website and uploads to the corresponding building information webpage, populates map.  

- Art on Campus page – brings in art gallery section, search by artist, medium, or building, add to map. 

- FM Staff Lists — pulls up-to-date information from FM-managed staff lists, automatically updates with addition/removal of employees from lists. 

# Proposed Solution

- [x] #5803
- [x] #5963
- [x] #5962
- [x] #5659 
- [x] #6086
- [x] #5823
- [x] #6403
- [x] #6398
- [x] #6444
- [x] #6559
    - [x] #6561
    - [x] #6658 
    - [x] #6689 
    - [x] #6813 
    - [x] #6852 
    - [x] alert theming?
- [x] #7020
- [x] #7150 
- [x] #6447 
- [x] #7278 
- [x] #7280
- [x] #7303
- [x] #7291 
- [x] #7292 
- [x] #7199 
- [x] #7200 
- [x] #7361 
- [x] #7326 
- [x] #7327 
- [x] #7235 
- [x] #7401 
- [x] #7427 
- [x] #7450 
- [x] Switch to production population for Facilities Alert template

```[tasklist]
### Tasks
```

**Comment by joewhitsitt** [comment]
@briand44 and I had a meeting with Jay to discuss map embeds. here is something promising to work off of where we can use the building api lat/long to center the iframe: https://codepen.io/joewhitsitt/pen/yLRjgOJ
