### ISSUE TITLE
As a Tippie webmaster, I would like redirects from D7 site imported programmatically into the D9 site.

### ISSUE THREAD

**Issue by makurj** [uiowa/uiowa#5265]
# Story

As a webmaster, I would like redirects from D7 site imported programmatically into the D9 site so that I don't have to manually recreate over 60 pages of redirects manually. 

Prioritize for May 20th sprint to give James time to clean up the URLs and create the spreadsheet.

# Proposed solution

1. Create a spreadsheet. The CSV file must include columns in the following order: "From URL","To URL","Redirect Status","Redirect Language". Make sure you use "/node" instead of custom URLs.
2. Write an update hook to use the spreadsheet to bulk import the bookmarks. Refer to uiowa, HR update hooks.

**Comment by makurj** [comment]
I would like to pair on this.

**Comment by pyrello** [comment]
It seemed like, from our conversation about this in standup yesterday, that this was something we were just going to work on for Tippie. Can we change the title/story to reflect that?

**Comment by joewhitsitt** [comment]
Previous examples: https://github.com/uiowa/uiowa/tree/main/docroot/sites/hr.uiowa.edu/modules/hr_core ,https://github.com/uiowa/uiowa/tree/main/docroot/sites/uiowa.edu/modules/uiowa_edu_core

note the format:
```csv
target,destination
onboarding/public-university,internal:/node/1751/
homepage/downtown,https://uiowa.edu/homepage/creative-corridor
```

**Comment by makurj** [comment]
> It seemed like, from our conversation about this in standup yesterday, that this was something we were just going to work on for Tippie. Can we change the title/story to reflect that?

You mean that this will be in the Tippie site split?

**Comment by briand44** [comment]
We just need a few of these so work can start on this. Only need full list prior to running in prod.

**Comment by briand44** [comment]
James provided the spreadsheet.

https://iowa.sharepoint.com/:x:/r/sites/CSI-Drupal2/_layouts/15/Doc.aspx?sourcedoc=%7B4E6DF90E-7671-4498-BB7A-5E2AB2768880%7D&file=2022%20Tippie%20Redirects.xlsx&action=default&mobileredirect=true

**Comment by briand44** [comment]
FYI, James is going to update some of the redirects that are using absolute url in the "to" field to contain a node id. For example, https://students.tippie.uiowa.edu/page-title will be updated to https://students.tippie.uiowa.edu/node/nid. I'll replace the document linked above when I have the new one. This shouldn't block any work from starting on this.

**Comment by briand44** [comment]
Update on this. Sticking with document linked above. They understand redirects using absolute urls to the url alias could break if the alias changes and are ok with that.

**Comment by joewhitsitt** [comment]
As it relates to https://github.com/uiowa/uiowa/pull/5307#issuecomment-1136095685

I'd be curious to learn more about what happened here for future reference. `InvalidArgumentException: The URI '/people/robin-akers' is invalid. You must use a valid URI scheme.` just makes it seem like these needed to be absolute URLs since they aren't traditional internal drupal paths.
