### ISSUE TITLE
SSO for new uihc.org website

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5280]
As a vendor for the Drupal 9 uihc.org website, I would like to integrate SSO so that users authenticating to the website can log in with their HawkID similar to other campus D9 Drupal websites.

# Additional Information
The application hosting this site is uihealthcare01 

# Proposed Solution
Provided by Rick:
In order for them to set this up and in regards to your questions, Brian/Michael and the rest of the team will need to:
 
- [x] #5300 ~Implement release file uploading specifically for the uiowa_auth module within the uiowa/uiowa repository. This will hopefully make it easier to integrate just that module with the Healthcare applications. It might be possible to use Composer with a custom repository to do this – not entirely sure there.
Internal team reference: https://github.com/uiowa/uiowa/issues/2630 :)~
- [x] Ensure that our Acquia service account has appropriate permissions to access the Cloud API for Healthcare applications.
- [x] Add the application(s) you provided to our internal Shibboleth metadata generation application. - https://git.uiowa.edu/its-web/data.its.uiowa.edu/-/merge_requests/47
- [ ] Assist with configuring the samlauth module similarly to https://github.com/uiowa/uiowa/blob/main/config/default/samlauth.authentication.yml
- [x] Transfer the sensitive samlauth configuration to the secrets.settings.php file (or some other include file outside the application) on the appropriate Healthcare application(s)

**Comment by briand44** [comment]
>I’m optimistic this process will be pretty straightforward, perhaps outside of the TravisCI release uploading. That could be a future enhancement however if you were ok copying/pasting the module initially. I had hoped that would make it easier for other applications to specify an actual code dependency on it.

Comment from Rick

**Comment by joewhitsitt** [comment]
For reference https://github.com/uiowa/uiowa/issues/2630

**Comment by pyrello** [comment]
My opinion is that we should split `uiowa_auth` back out into a separate module and we can go back to consuming it and having UIHC consume it.

**Comment by briand44** [comment]
UI AcquiaGitHub is part of the Signage and Marcom teams on the Healthcare subscription in Acquia. Still need to verify perms for that role.

**Comment by pyrello** [comment]
Created #5300 as a first slice of this that is not dependent on the other parts so that we are all set up to be able to work through the remaining parts.

**Comment by joewhitsitt** [comment]
>Add the application(s) you provided to our internal Shibboleth metadata generation application.

This is done (crow and vulture). https://git.uiowa.edu/its-web/data.its.uiowa.edu/-/merge_requests/47

**Comment by briand44** [comment]
>Ensure that our Acquia service account has appropriate permissions to access the Cloud API for Healthcare applications.

My understanding is this is done as well since we were able to access the domains on the healthcare application

**Comment by briand44** [comment]
I communicated with the vendor that they can move forward with setting this up on their end and to reach out with any questions. Sean and Michael are on that thread as well.

**Comment by briand44** [comment]
>I've got the necessary modules installed locally and am at the point of populating the IDP and SP config items in the secrets.settings.php file. A few questions:
Will this system function from our local environments? We are using Lando (https://lando.dev/) for local development, and the standard domain for the site is: "uihc.lndo.site". Is this something that can be configured for connection as well, even if it's not accessible externally?
Would you send us the necessary config overrides for us to place into the secrets.settings.php file? I'll need to write up instructions for the dev team on adding their own local secrets file so that it can potentially work locally (the file will be ignored from the code repository). Also, I'll then FTP the file up to the Acquia environments. 
Will these config settings differ between environments or will they be consistent?
I guess we can start there. Please let me know any information you'll need from me.

**Comment by pyrello** [comment]
I sent an email replying to the questions and suggesting that someone on our team could log in and set up the secrets. They are good with that.

**Comment by briand44** [comment]
i've added the sensitive information to each environment on the Healthcare application

**Comment by briand44** [comment]
Going to go ahead and close this and we can re-open or create follow up issues if needed
