### ISSUE TITLE
Create mockup for Iowa Now Faculty/Staff home page

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#5283]
Create a landing page mockup for the new ~Iowa Now home faculty news page page and a landing page for the~ Iowa Now Faculty/Staff home page. 

- Look for design inspiration on other university news sites like https://news.duke.edu.   
- Read [this](https://iowa-my.sharepoint.com/:p:/g/personal/bspeare_uiowa_edu/EaMRIHZudJBAt5r4WUrzMfYBylSDdSqntCTmE9xRz0lfhQ?e=0O7sb9) if you want some v3 design tips. 
- Once you have a home page design you are happy with, clone this page and alter it to be the Faculty/Staff home page.

**Comment by briand44** [comment]
https://today.duke.edu/ was an example they referenced for the internal news info

**Comment by bspeare** [comment]
Had a chat with Jack about what they are looking to do with the design on https://now.prod.drupal.uiowa.edu/.  Here's an outline we could follow:

1. Intro section 
2. Section of featured faculty staff news items with images (Can be any number of items)
3. List of latest Iowa Now articles
4. Photo gallery/video section to highlight work of OSC video/photo team 
5. Resources/Quick links to Self-Service, etc.  Maybe show top 3 and link to a full page of resources
6. List of tagged articles for achievements, UI Spotlight, In the news
7. Events section
<details>
Possible conversation topics for the next meeting:

- Discuss mockup
- Talk about names for the site like `Working@Iowa` or something
- Where will the site live?  `hr.uiowa.edu` or `*.now.uiowa.edu`?
- How soon could Iowa Now be migrated to `v3`?
- Will tags/aggregator work for pulling articles from Iowa Now?
- </details>

**Comment by briand44** [comment]
I see the scope decreased to only include the new faculty/staff page. Curious on if they want to keep Iowa Now the same as it currently is or what their thoughts were on that end?

**Comment by bspeare** [comment]
@briand44 after talking with Jack, I think there's some confusion about what we are doing with Iowa Now so it seemed like sticking with a mockup for the Faculty/Staff page made the most sense.  Maybe we can talk about this in PL tomorrow and I can explain further.

**Comment by mjoneill** [comment]
Some of the RSS stuff: 
- https://now.uiowa.edu/subscribe/rss-and-data-feeds
- https://now.uiowa.edu/experts-list

**Comment by bspeare** [comment]
I adjusted the title so reflect that this is just a mockup of the faculty/staff home page.

**Comment by bspeare** [comment]
The current page that they have put together is at https://now.prod.drupal.uiowa.edu/.  You can either clone this page to use a starting point or start something new.

**Comment by bspeare** [comment]
Use the outline in https://github.com/uiowa/uiowa/issues/5283#issuecomment-1130372781 for the page structure.

**Comment by joewhitsitt** [comment]
Took a stab at this. So many revisions... https://now.prod.drupal.uiowa.edu/faculty-staff. I think the required bits are all there. Looking for team feedback before the meeting (when?).

**Comment by bspeare** [comment]
@joewhitsitt I like what you did there! I have a few suggestions below. 

**Headlines section**
- Remove heading and just have the stories display?
- Remove card outline and background and maybe add a thumbnail to each small story?
- Newsletter sign-up - move to a separate section below?  Could we add a small embedded form like https://sandbox.prod.drupal.uiowa.edu/webform-layouts? Then headlines could evenly take up left sidebar space.

**Media highlights**
- Add card outline to get some extra separation for the video from the image gallery?

**Achievements/UI Spotlights**
- Remove card outline and background and add teaser image floated left or right?

**In the news/Events**
- Move to new section with white background to create a break from the previous lists?
- Remove card outline and background and add teaser image floated left or right?

**Comment by joewhitsitt** [comment]
Thanks for the quick feedback. I will try some of these changes and probably add more dummy content to do so

**Comment by joewhitsitt** [comment]
Well, if I understood the notes, that was a relatively painless update.

**Comment by joewhitsitt** [comment]
Just heads up. I don't think achievements, inthenews (external) typically have a featured image

**Comment by bspeare** [comment]
Thanks @joewhitsitt, here are a few more suggestions:

- Move the featured headlines section to have the background color or pattern?  Use the same one from "Subscribe for future updates", or use a different one for both.   Or, move the section below back into a background color like it was initially and remove the background from the webform section. 
- Remove thumbnail images if every item does not have them.
- Add a card border back to the "Exploring work-life boundaries" card.
- Add same center headline style to the "Subscribe to future updates" form.
- Media highlights - remove second paragraph of lorem ipsum so height of card matches height of image thumbnails. Make the card background white so that it is easier to see. 
- Add follow us on social block like one from https://education.uiowa.edu/?
- Turn the CTA at the bottom of the page into a "Share news" CTA and grab the text from https://now.prod.drupal.uiowa.edu/

**Comment by joewhitsitt** [comment]
From a technical standpoint I believe I have handled all of the above bullet points. I am understanding the alternating backgrounds, but don't have an eye on what the combinations should be.

When constructing the "featured headlines," I thought the headline, three col cards, followed by the card list/big card were all one "thing". Alternating backgrounds here breaks that up and the second area seems undefined.

**Comment by joewhitsitt** [comment]
We delivered this as part of a meeting yesterday. Customers plan to review and provide feedback. Moving to blocked/waiting

**Comment by briand44** [comment]
@bspeare can this be closed as well? It looks like you incorporated the lates feedback.

**Comment by bspeare** [comment]
Yes! https://now.prod.drupal.uiowa.edu/news-faculty-and-staff is now updated.

**Comment by briand44** [comment]
Should https://now.prod.drupal.uiowa.edu/faculty-staff be removed?

**Comment by bspeare** [comment]
I archived it to avoid confusion.
