### ISSUE TITLE
Delete iba.biology.uiowa.edu from uiowa01.

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#5285]
# Story

The new isa.uiowa.edu has launched, so we can safely and completely remove the old iba.biology.uiowa.edu site from uiowa01.

# Proposed solution

I am assuming that I can simply perform the following to remove this site (but would like verification before I do this):

Create new branch for this code update.
Run '`blt uiowa:multisite:delete --site=iba.biology.uiowa.edu`'.
Push branch up to origin.
Remove the domain from Acquia web interface.

Is this correct?

**Comment by joewhitsitt** [comment]
Push branch as PR for approval. Once the domain is removed you can also contact hostmaster to reclaim. https://wiki.uiowa.edu/display/drupaldev/Website+requests+via+sitenow.uiowa.edu#Websiterequestsviasitenow.uiowa.edu-GeneralDeprovisionProcess
