### ISSUE TITLE
Delete humanities.uiowa.edu from uiowa01.

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#5286]
# Story

The new humanities.uiowa.edu site is now unnecessary and has been killed by the CLAS Deans Office, so we can safely and completely remove the humanities.uiowa.edu site from uiowa01.

# Proposed solution

I am assuming that I can simply perform the following to remove this site (but would like verification before I do this):

Create new branch for this code update.
Run '`blt uiowa:multisite:delete --site=humanities.uiowa.edu`'.
Push branch up to origin.
Remove the domain from Acquia web interface.

Is this correct?

**Comment by joewhitsitt** [comment]
https://github.com/uiowa/uiowa/issues/5285#issuecomment-1130041461
