### ISSUE TITLE
Move back to using `uiowa_auth` as external module

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#5300]
## For Reference

https://github.com/uiowa/uiowa/pull/5274
https://github.com/uiowa/uiowa/pull/4728
https://github.com/uiowa/uiowa/pull/4681

## Proposed Solution

- https://github.com/uiowa/uiowa_auth was copied from uiowa and doesn't have some original bits that maybe necessary to run standalone again (e.g. composer.json)
- "undo" the uiowa_auth related bits of 5274, 4728, 4681

**Comment by pyrello** [comment]
> https://github.com/uiowa/uiowa_auth was copied from uiowa and doesn't have some original bits that maybe necessary to run standalone again (e.g. composer.json)

Attempted to add these back from a folder that was still around when this was a dependency the last time around.

We might want to consider trying https://github.com/marketplace/actions/setup-drupal-action instead of Travis.

**Comment by joewhitsitt** [comment]
Did the test directory change during the move?

<img width="257" alt="Screen Shot 2022-05-20 at 8 54 12 AM" src="https://user-images.githubusercontent.com/4663676/169543071-38fbf165-f6ed-4dd3-a7ac-aa7b11d0c3c6.png">
<img width="282" alt="Screen Shot 2022-05-20 at 8 54 29 AM" src="https://user-images.githubusercontent.com/4663676/169543077-5399b1b2-1181-457f-bcf5-1d23e75c256f.png">

**Comment by pyrello** [comment]
> Did the test directory change during the move?

Good catch!
