### ISSUE TITLE
Can we remove `embed` module?

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#5312]
As part of trying to understand what was changing in #5311, I think I may have discovered that we no longer need the `embed` module. We used to use it on V2 sites as a dependency for `entity_embed`, which allowed `<drupal-entity>` tags to be transformed via filter to their respective entities. This was the old method for embedding media objects in WYSIWYG text areas, but we changed that in V3 when we built it and eventually updated V2 to match in this PR: https://github.com/uiowa/uiowa/pull/3048

If we are no longer using the module, we should remove it and it associated config footprint so that we don't have to update it for no reason in the future.

**Comment by joewhitsitt** [comment]
I think I added this as a part of https://github.com/uiowa/uiowa/issues/3752 just to be safe but if it is beginning to be a hassle to maintain, I understand the need to handle it sooner.

>After 2 additional weeks or whenever we feel confident that the transition was successful and doesn't need additional mitigation, we can remove all the V2-specific data, configuration, code as well as leftover v2 media stuff like entity_browser.browser.media_wysiwyg_browser.yml, embed button/settings, etc.

**Comment by joewhitsitt** [comment]
entity_embed is not yet compatible with ckeditor5. if we aren't using it, we should remove this module once and for all.

**Comment by joewhitsitt** [comment]
Created a PR for this. https://github.com/uiowa/uiowa/pull/6898

We should probably do one-last database scan for `drupal-entity` markup but that should have been resolved when v2 adopted media.
