### ISSUE TITLE
Incorrect block title/headline values are being set after after P2LB conversion

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#5318]
# Issue

Incorrect block title/headline values are being set after after P2LB conversion

- Events
  -  display/hide value of v3 headline set wrong (it displays if v2 title is set to hide and hides if v2 title set to display)
- People
  - display/hide value of v3 headline set wrong (it displays if v2 title is set to hide and hides if v2 title set to display)
- Featured Content: 
  - display/hide value of v3 headline set wrong (it displays if v2 title is set to hide and hides if v2 title set to display)
- Image Gallery
  - display/hide value of v3 headline set wrong (it displays if v2 title is set to hide and hides if v2 title set to display)
- Webform: 
  - V2 title field not being captured. It displays on the v3 block, but there’s no way to edit the text or set it to hidden.
-  Accordion: 
    -  V2 title field not being captured by v3 headline field.
- Carousel/Slider:
  -   V2 title field not being captured by v3 slider headline field

Example from Featured Content

Live site

<img width="1624" alt="Screen Shot 2022-05-31 at 2 24 15 PM" src="https://user-images.githubusercontent.com/1036433/171269466-49212234-9855-4857-b86a-e54063a67899.png">

Local 

<img width="1553" alt="Screen Shot 2022-05-31 at 2 24 05 PM" src="https://user-images.githubusercontent.com/1036433/171269481-c4d42c8f-73b4-4ba3-8525-5b9a8c501718.png">

# Proposed solution

?

**Comment by cory-skeers** [comment]
Made small changes in #5316 that works for the cases where the title is being captured but incorrectly set for display. Still need to account for those that aren't being captured.

**Comment by briand44** [comment]
setup a page, turn xdebug on and figure out what isn't mapped correctly (specifically re: accordion and carousel/slider).

It may be a matter of mislabeled machine name, may be a more complicated issue with how data from child paragraphs is being handled.

**Comment by cory-skeers** [comment]
> * V2 title field not being captured. It displays on the v3 block, but there’s no way to edit the text or set it to hidden.

This one's a little different. Our current webform blocks don't have a place to add a title (on the block--a webform might have a title or equivalent as an HTML element on the webform itself). Right now it's getting added as a label and being displayed through that, which isn't provided as an editable element.

The fix for the uneditable title is to not put it into the label field (and/or turn off display label). But we still should account for the v2 somewhere.

I'm thinking these are the two options:

- Drop it into a Text Area and formatted as an `h2` element placed above the webform
- Add a headline field to the Webform block for the platform now (similar to Text Area and other blocks, that don't have the children heading controls, but have styling options), and map it to that

**Comment by joewhitsitt** [comment]
Is adding the headline field as simple as adding the unique id field? https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/layout_builder_custom/layout_builder_custom.module#L150

Just want to point out that the webform block (provided by the contrib module) is different than our other blocks, including the views blocks which we forked/extended for other reasons.

**Comment by cory-skeers** [comment]
> Is adding the headline field as simple as adding the unique id field? https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/layout_builder_custom/layout_builder_custom.module#L150
> 
> Just want to point out that the webform block (provided by the contrib module) is different than our other blocks, including the views blocks which we forked/extended for other reasons.

I could be off, but I'm pretty sure it'd be more complicated than that. We have the helper methods for processing the headline field in different contexts, but I think it'd still be some form of programmatically adding the field to the form, processing/storing it with the block, and building/rendering it. I think it's all stuff we're doing elsewhere, but still, non-trivial to add.

**Comment by joewhitsitt** [comment]
without diving into it, i'd lean to the blank text area with headline filled out for p2lb. webform headline in the future (if it is possible without forking/extending like listblock)
