### ISSUE TITLE
Can't edit/replace images on new default homepage template

### ISSUE THREAD

**Issue by bewoldt** [uiowa/uiowa#5321]
# Problem
I can't edit/replace any of the images in the banner and card components on the new default homepage setup. 

When you try to add a new field or choose an existing file and press the button "insert selected" you get the get the loader icon and then nothing happens.

Everything is fine if you create a new banner or card but does not work on existing components.

Current site we are editing. https://powwow.prod.drupal.uiowa.edu/

https://user-images.githubusercontent.com/731952/171436009-14f78b85-b001-47f6-ba17-be4c306b0cb5.mov

# Notes from Grooming 6/14/22

Could test if this problem exists on the showcase page... Cory thinks he checked but it's been awhile. Since this is a regression, we can review the changes to see if we notice anything that stands out.

could use helper update function to fix once we identify the problem

button styles not set in default content, could add those if makes sense or create a follow up issue if there is not one already

**Comment by quamsta** [comment]
According to the developer console Network resources tab, the response header when attempting to submit the image field says:

`{"message":"Non-reusable blocks must set an access dependency for access control."}`

and the Javascript console error is:

```Drupal.AjaxError {message: '\nAn AJAX HTTP error occurred.\nHTTP Result Code: 40…st set an access dependency for access control."}', name: 'AjaxError'}
message: "\nAn AJAX HTTP error occurred.\nHTTP Result Code: 403\nDebugging information follows.\nPath: /media-library?destination=/node/1/layout&_wrapper_format=drupal_ajax&ajax_form=1&media_library_opener_id=media_library.opener.field_widget&media_library_allowed_types%5Bimage%5D=image&media_library_allowed_types%5Bvideo%5D=video&media_library_selected_type=image&media_library_remaining=1&media_library_opener_parameters%5Bfield_widget_id%5D=field_uiowa_banner_image%3A-settings-block_form&media_library_opener_parameters%5Bentity_type_id%5D=block_content&media_library_opener_parameters%5Bbundle%5D=uiowa_banner&media_library_opener_parameters%5Bfield_name%5D=field_uiowa_banner_image&media_library_opener_parameters%5Bentity_id%5D=131&media_library_opener_parameters%5Brevision_id%5D=131&hash=Pf8qmDH25Zw8AaSHOZNN-IZyDV82SGfHeAsCmaWHPrU&views_display_id=widget\nStatusText: error\nResponseText: {\"message\":\"Non-reusable blocks must set an access dependency for access control.\"}"
```

**Comment by bspeare** [comment]
I tested a few recently provisioned sites for this and encountered the same bug.

**Comment by cory-skeers** [comment]
Unrelated to the error, but documenting in case default content needs updating as part of this:

The button styles need to be updated on the banner block. Right now they are not set, and need to be set in order to re-save the block when editing.

**Comment by cory-skeers** [comment]
One workaround is to save the layout--after saving, re-editing the layout then allows for the media entities to be edited.

Found it from https://www.drupal.org/project/section_library/issues/3197589 (marked as duplicate of https://www.drupal.org/project/drupal/issues/3047022, which has a potential patch/mr), haven't dug further into the issue or ways around it, but I think this sheds light on where the issue is coming from.

**Comment by cory-skeers** [comment]
> One workaround is to save the layout--after saving, re-editing the layout then allows for the media entities to be edited.
> 
> Found it from https://www.drupal.org/project/section_library/issues/3197589 (marked as duplicate of https://www.drupal.org/project/drupal/issues/3047022, which has a potential patch/mr), haven't dug further into the issue or ways around it, but I think this sheds light on where the issue is coming from.

Update: Patches from here did not appear to fix the issue, and the workaround (re-saving the layout) is more complicated, and inconsistent, depending on a specific order of changes updated... The issues above still may be relevant--think the problem is a similar breaking of the access dependency chain in how the default content was added.

**Comment by joewhitsitt** [comment]
I might be adding potential noise until I can dive deeper here, but in the last round of default content updates we ran into issues that required patches that sort of sound similar to this issue:

https://github.com/uiowa/uiowa/pull/4999

https://www.drupal.org/project/paragraphs/issues/3090200
https://www.drupal.org/project/default_content/issues/3160146

**Comment by briand44** [comment]
Could test if this problem exists on the showcase page... Cory thinks he checked but it's been awhile. Since this is a regression, we can review the changes to see if we notice anything that stands out.

**Comment by briand44** [comment]
could use helper update function to fix once we identify the problem

**Comment by briand44** [comment]
button styles not set in default content, could add those if makes sense or create a follow up issue if there is not one already

**Comment by joewhitsitt** [comment]
>Could test if this problem exists on the showcase page... Cory thinks he checked but it's been awhile. 

Confirmed. It is occurring on the showcase page as well

**Comment by joewhitsitt** [comment]
I found a provisioned site that still had the original lb default content. From there, I am going to re-trace steps to see where this went wrong.

**Comment by joewhitsitt** [comment]
Progress! 
<img width="365" alt="Screen Shot 2022-06-28 at 11 47 56 AM" src="https://user-images.githubusercontent.com/4663676/176235777-b5591373-166d-4115-851c-4c718d7044a6.png">

**Comment by joewhitsitt** [comment]
Each of these test steps have gone through the process of `dcer` the content (node, media), updating the sitenow.info file, running `dcem` and doing a fresh install on sandbox (deleting files, dropping db, cr, drupal:install)

- Recovered an old version of the default_content layout builder to confirm it wasn't an issue with current versions/patches.
- Updated old default content to set blocks to how they should be today (field sets, etc). No issue.
- Re-added additional news articles. Re-saved old. No issue.
- Added a blank homepage. I was still able to edit the media found on the Component Showcase page.
- Added a single banner with existing image to the homepage. **Could not update the homepage banner image. Could update media on Component Showcase.**
- Tried swapping single banner on the homepage image for a new one. No change.
- Tried removing everything from the homepage (moderation, header, etc.) to simplify and only contain the one banner. No change.
- Tried deleting the homepage, replicating the component showcase, removing all blocks but three cards (existing images). No change.
- Tried latest MR patch and https://www.drupal.org/project/drupal/issues/3047022#comment-14292708
- Debugged to docroot/core/modules/media_library/src/MediaLibraryFieldWidgetOpener.php#L63 where the access check is notAllowed - `// If entity-level access is denied, there's no point in continuing.`

I can seem to understand why I was able to get this working for the component showcase but not the new homepage. The file diffs are pretty identical except for the the content sections. The replicated section attempt (all but three cards), the node and block_content yaml is identical except for the uuids involved.

Thinking about attempting a homepage/about/articles setup and dumping the component showcase (all layout builder media is on one node).

**Comment by joewhitsitt** [comment]
- Tried deleting component showcase and making a new page with a banner image. Did not fix.
- Repurposing the component showcase as the "one" page with media layout builder content works. Did notice the footer contact block was missing. Not sure if that happened previously with this work, but will start to check that going forward.
- One thing that hasn't been tried yet is repurposing component showcase but reverting to defaults before adding new blocks. This would solve this issue (for one page) and start content off correctly with moderation, header, sidebar layout blocks all placed.

**Comment by joewhitsitt** [comment]
Repurposing the component showcase, reverting to defaults and populating it with the "new homepage" content provides a solution to move forward. Still don't know why.

**Comment by pyrello** [comment]
Not totally sure how this is helpful:
- The relevant details of this seem to be happening in `Drupal\block_content\BlockContentAccessControlHandler` in lines 75-80: https://git.drupalcode.org/project/drupal/-/blob/9.5.x/core/modules/block_content/src/BlockContentAccessControlHandler.php#L75-80
- This triggers the instantiation of `Drupal\block_content\Event\BlockContentGetDependencyEvent`: https://git.drupalcode.org/project/drupal/-/blob/9.5.x/core/modules/block_content/src/Event/BlockContentGetDependencyEvent.php
- I set a breakpoint inside the `setAccessDependency()` method and it never gets hit: https://git.drupalcode.org/project/drupal/-/blob/9.5.x/core/modules/block_content/src/Event/BlockContentGetDependencyEvent.php#L67
- When running through debugging again, I noticed that the block content entity for the banner has an `accessDependency` property that is set to `NULL`.
- Hence it appears that never gets set and therefore is always returning false, which is the root cause of the error we are getting.
- I found a place to set a breakpoint where I could inspect a block content entity while using Layout Builder and noticed that it has its `accessDependency` value set to a class related to how the viewing the block in the LB preview.

**Comment by pyrello** [comment]
> Repurposing the component showcase, reverting to defaults and populating it with the "new homepage" content provides a solution to move forward. Still don't know why.

It seems like @joewhitsitt may have found us a way out of this mess for the moment. However, I suspect that if we want to be able to make changes to default content in the future, it will require understanding why it didn't work quite right this time. I'm going to dig through the default content issue queue and potentially open an issue if I don't find anything.

**Comment by joewhitsitt** [comment]
@pyrello thanks for your investigation into this. Not sure where you found the time! I thought I was going crazy. Might still be.

**Comment by pyrello** [comment]
When we get to the point of considering alternatives:
- https://www.drupal.org/project/content_synchronizer
- Another idea discussed was to generate the content in code, although as pointed out by @joewhitsitt, this would require us to manually construct and make any changes based on feature updates.
- Another idea would be to create a migration module that gets installed that runs a migration based on the content on the default site. The benefit of this idea is that new installs would always immediately reflect content changes on the default site without any additional work. This might require https://www.drupal.org/project/drupal/issues/2924549
- Another option would be to create a module that has the default content for the component showcase which is enabled via the CI config split, so it would only be turned on when running our CI setup.

**Comment by joewhitsitt** [comment]
should we just go ahead and turn this into an issue "consider replacing default_content"?

**Comment by pyrello** [comment]
Done.

**Comment by redkrishnam** [comment]
Hi, If you are using group module try this patch.
https://www.drupal.org/project/group/issues/3071489
