### ISSUE TITLE
Tippie launch 6/6/22:

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5322]
**Pre-launch**
- [x] who is handling this - Makur
- [x] agree on timing of launch with James: 8:30 AM
- [x] verify DNS and SSL - tippie.uiowa.edu and www.tippie.uiowa.edu pointing to Acquia. tippie.uiowa.edu and *.tippie.uiowa.edu covered in uiowa02 cert.
- [x] Check for .prod.drupal links
- [x] site name is not url
- [x] email is not admin@example.com

**Launch**
- [x] notify in Tippie Slack channel that you are starting the launch process
- [x] remove tippie.uiowa.edu and www.tippie.uiowa.edu from 703
- [x] add tippie.uiowa.edu and www.tippie.uiowa.edu to uiowa02
- [x] Clear varnish for both domains on uiowa02
- [x] once the site is available at the above url's remove tippie.prod.drupal.uiowa.edu from uiowa02 and add it to 703

**Post-Launch**
- [x] regenerate sitemap using drush or through UI, verify no .prod.drupal in sitemap (if this is done through UI it may take 5 minutes or so before authentication begins working)
- [x] clear site cache and varnish cache
- [x] verify robots.txt is not disallowing all - check with incognito window (site.uiowa.edu/robots.txt)
- [x] update site request notes and lock submission
- [x] _submit sitemaps to Search Console - drupal sitemap and profile sitemap (James)_
- [x] clear Varnish for tippie.prod.drupal.uiowa.edu
- [x] Notify Tippie Slack channel that site is live and old site available
- [x] _run screamingfrog reports (James)_
- [x] Add reminder to its-web calendar to check in to see if still need d7 site after 1 month
- [x] profit!!

**students.tippie.uiowa.edu**
- [x] remove split for students.tippie - clear caches
- [x] Verify robots.txt is not disallowing all
- [x] _submit sitemap for students.tippie to Search Console (James)_
- [x] Communicate this is done in Tippie Slack channel

**Comment by makurj** [comment]
Thanks @briand44 and @pyrello !!
