### ISSUE TITLE
As a developer, I can provide additional options for new 4th level domains when a client requests a new site.

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#5349]
As a followup to our domain name policy meeting this morning, I have suggestions for additional 4th-level domain options through the University. Just putting these out there for more discussion and feedback.

- ~*.center.uiowa.edu~ this has been added
- ~*.conference.uiowa.edu~ this already exists
- *.group.uiowa.edu
- *.institute.uiowa.edu
- *.program.uiowa.edu
- *.research.uiowa.edu
- *.scholar.uiowa.edu

Reasoning behind these:
***.center.uiowa.edu** - from UF example provided by MON.

***.conference.uiowa.edu** - from UF example provided by MON.

***.group.uiowa.edu** - this would be an alternative to *.lab, for those research groups on campus that dont want *.lab. The issue with this would be if a student group would use this as well.

***.institute.uiowa.edu** - from UF example provided by MON.

***.program.uiowa.edu** - for cross collegiate groups or programs.

***.research.uiowa.edu** - an alternative for research groups vs *.group.uiowa.edu.

***.scholar.uiowa.edu** - requested by Lance Bolton previously.

**Comment by briand44** [comment]
*.conference.uiowa.edu is already a pre-approved url pattern.
*.research.uiowa.edu is being used by OVPR

**Comment by makurj** [comment]
Are we introducing more granularity for sites that cannot be provisioned out as *.sites? If so, would this solution not render them obsolete? Or would we continue to offer *.sites option as well?

**Comment by joewhitsitt** [comment]
Just keep in mind that hostmaster has pushed back previously on the number of pre-approved in the past so we will probably need to get their thoughts/approval early in the process.

Additionally, each pre-approved domain, if to be covered on all applications, will take up one SAN per application.

**Comment by briand44** [comment]
>would we continue to offer *.sites option as well?

I think we would continue to offer it. I believe this was intended to be used for personal academic sites as well. If we move away from MyWeb in the future there could be sites that move to SiteNow that would fit under this pattern.

**Comment by briand44** [comment]
I can see the use case for *.center and *.program if the center or program doesn't fall under one particular college or department.
