### ISSUE TITLE
Residence Halls landing page with filters

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5350]
As a visitor to the housing website, I would like to be able to filter residence halls by specific categories so that I can find a residence hall that suits me without viewing all of them individually.

# Additional Info
Need to be able to display all residence halls similarly to how they are currently with the ability to filter on specific categories. https://housing.uiowa.edu/residence-halls

Same filterable categories they currently have (Building type, neighborhood, amenities, room type, furnishings) and would like to add an additional filter for bathroom type (Community style, single-user, suite-style, private restroom).

Overview text at top is needed

**Comment by bspeare** [comment]
Here's a look at the page in https://github.com/uiowa/uiowa/pull/5430. 

https://user-images.githubusercontent.com/1036433/177827759-b1a9a955-6b62-46d1-a2bd-41eab9f4f244.mov
