### ISSUE TITLE
As a prospective student, I can view a virtual tour of my dorm room on housing.uiowa.edu

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#5354]
# Story

As a prospective student, I can view a virtual tour of my dorm room on housing.uiowa.edu

# Problem 

The previous housing.uiowa.edu used https://pannellum.org/. 
 - There is a Drupal module https://www.drupal.org/project/virtual_tour with some issues:
   - The module hasn't been updated in 4 years and uses unsecure `2.3.2` version of pannellum that could be fixed by `libraries-override`  
   - Only works on image field https://www.drupal.org/project/virtual_tour/issues/3273872
   - Pannellum library is hard coded into module directory https://www.drupal.org/project/virtual_tour/issues/3187960
     - This could be fixed by `libraries-override` like in https://github.com/uiowa/uiowa/pull/5330/commits/ea13284d49160ad7a60053bac47e19e8e367ef97

# Proposed solution

- Fork and update the module for our use
- Find a different solution
- Implement the pannellum library locally through a custom implementation

**Comment by joewhitsitt** [comment]
looks like a pretty simple “wrapper” module that is causing headaches. i think with what we learned with banner image/video, vertical videos and panopto, we could reproduce the functionality here.

**Comment by bspeare** [comment]
@joewhitsitt would that push us into a custom implementation or would we update the module to work with media?

**Comment by joewhitsitt** [comment]
I think the headaches extend beyond the media field so I would be more inclined to go custom here and if there is a better library in the future, it would be easier to pivot

**Comment by bspeare** [comment]
We ended up implementing this in our theme and pulling in the library through `npm-asset/pannellum`: https://github.com/uiowa/uiowa/pull/5330/commits/bfb5d8a3341add03c02776c9b30f6a3339972278.
