### ISSUE TITLE
As a prospective student, I can view restroom galleries on each residence hall page on housing.uiowa.edu 

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#5366]
# Story

As a prospective student, I can view a restroom gallery on each residence hall page on housing.uiowa.edu 

Previously, we were going to link out to extra pages for the bathroom galleries.  Now, it seems like it makes more sense to display these images on the content type. 

# Proposed Solution

- Delete `field_residence_hall_bath_images` field and make sure that none of the pages on housing.prod.drupal.uiowa.edu have any content in this field.  
- Add these new fields in a field group:
  - Residence hall restroom description - Long text field
  - Community-style - media photoswipe gallery
  - Single-user - media photoswipe gallery
  - Suite-style - media photoswipe gallery
  - Private - media photoswipe gallery
- Add these fields to at 63/37 layout under the floor plan section.   
- The galleries will need to be in 2x2 grids within the accordions. 

This works should happen in https://github.com/uiowa/uiowa/pull/5330. 

It should look like this:

<img width="1511" alt="Screen Shot 2022-06-13 at 4 30 30 PM" src="https://user-images.githubusercontent.com/1036433/173620712-1dd2afb0-5af1-4117-8a56-0ecf51841178.png">

<img width="1555" alt="Screen Shot 2022-06-13 at 4 30 26 PM" src="https://user-images.githubusercontent.com/1036433/173620730-b254de97-6dc3-4adc-8366-297c4391d02d.png">

**Comment by briand44** [comment]
We will want to test the grouping functionality of photoswipe. Make sure that when clicking on a single image you only see the properly grouped items?

**Comment by briand44** [comment]
Remove data from the field before deleting the field

**Comment by e-marie-w** [comment]
Since we're making a specific field for each restroom type we can also remove the`field_residence_hall_bath_type` field too, right?

**Comment by bspeare** [comment]
@e-marie-w I think that field will be used for filters that we will be building at a later date.   It does not display on the page currently.

**Comment by e-marie-w** [comment]
Ahh okay, cool! Glad I asked first.

**Comment by bspeare** [comment]
Closed via https://github.com/uiowa/uiowa/pull/5330.
