### ISSUE TITLE
As a prospective student, I can view a residence hall map on housing.uiowa.edu

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#5367]
# Story

As a prospective student, I can view a campus map on each residence hall page on housing.uiowa.edu

# Proposed Solution

- From grooming on 6/14/22 , it sounded like we thought moving forward with treating this as a media entity makes sense. There are some notes on the PR linked below about some things to keep in mind (lazy loading, etc)

work was started in https://github.com/uiowa/uiowa/pull/5268 but sounds like we may go a different direction now.

**Comment by briand44** [comment]
Potentially treat this as a media entity

**Comment by joewhitsitt** [comment]
Panopto (UI Capture) is an example of a custom media entity within our codebase

**Comment by joewhitsitt** [comment]
Marie had started this work in https://github.com/uiowa/uiowa/pull/5390 but ran into hurdles and transitioned to support shift.

**Comment by joewhitsitt** [comment]
Our bad for not capturing this on the issue but we had quite a bit of Slack conversation on this. Starting with a fresh PR, avoiding "concept3d" in naming things (in case of a vendor switch later on), adding to sitenow_media_wysiwyg, defining schema (https://iowaweb.slack.com/archives/C0164FNN1PV/p1655903873980259),

https://iowaweb.slack.com/archives/C0164FNN1PV/p1655908943899629

**Comment by joewhitsitt** [comment]
Made progress on this today. Initially followed media_entity_remote_image's formula, but starting to remember the downsides.

- [x] Capture zoom level - by referencing media_entity_remote_image and `$properties['zoom']` in #5268 
- [x] Capture name on the wysiwyg add form (I think @e-marie-w showed this working with a recent commit)
- [x] Adjust formatter to be an image render that uses image view modes. - by referencing imagecache_external_responsive within sitenow events teaser and switching based on wysiwyg selection.
- [x] Wire formatter up to actual data (zoom, media name).

**Comment by e-marie-w** [comment]
Fixed a couple small things mentioned during standup. I will wait on any name change until we've decided on a path forward. I want to spend some time trying to fix the thing where an error message appears on every field of the compound field instead of just the affected one. If it isn't possible or simple I will pivot to investigating the dynamic map option.
