### ISSUE TITLE
As a site user, when I click on the magnifying glass to search the site, I don't want to have to touch the search area to type.

### ISSUE THREAD

**Issue by makurj** [uiowa/uiowa#5372]
# Story

As a site user (desktop and mobile), when I click/touch the magnifying glass to search the site, I don't want to have to click/touch the search area also to type. I would like touching the magnifying to activate my keyboard.

![image](https://user-images.githubusercontent.com/52135878/173633883-0a461c63-7070-4bde-937e-7e6ab183c8d5.png)

**Comment by bspeare** [comment]
We had this working originally and adjusted the behavior due to the reasons outlined in https://github.com/uiowa/uids/issues/55#issuecomment-668052663 and https://github.com/uiowa/uids/pull/241.   I would love to revisit this and try to get a solution working that is accessible.

**Comment by joewhitsitt** [comment]
ITS has expressed interest in this.

**Comment by briand44** [comment]
Grooming conversation... We will probably want to run our solution by TM to get accessibility sign off. It's been awhile since we previously looked at this so we probably want to revisit previous solution to see if we can make that accessible or if we need to go a different route.
