### ISSUE TITLE
Clean up sitenow_find_text from the codebase, finish transition to find_text

### ISSUE THREAD

**Issue by cory-skeers** [uiowa/uiowa#5383]
Blocked by #5363 (needs to be in a later deployment)

sitenow_find_text has moved to https://www.drupal.org/project/find_text. Because of order of operations in the build and deployment process, previous work disabled sitenow_find_text and enabled find_text, but sitenow_find_text still exists in the codebase.

# Proposed solution
Remove sitenow_find_text
Update gh sitenow_find_text label to find_text
Check that any issues in our repo are represented on the project issues, and that any issues in the project repo have a tracker issue here

**Comment by joewhitsitt** [comment]
Getting a warning during Travis `No tests found in class "Drupal\Tests\sitenow_find_text\Functional\FindTextAjaxTest"` so it would be nice to address this sooner than later. If there are no complications, I'd do it now but I don't want the current PR I am working on to get any bigger...
