### ISSUE TITLE
As a site editor, I can select the type of aspect ratio to use in my image gallery block

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#5386]
# Story

As a site editor, I can select the type of aspect ratio to use in my image gallery block.

# Proposed solution

- Add a layout builder style to choose between aspect ratios to add a modifier class to the image block wrapper. 
  - Original/Default (no aspect ratio)
  - Square (1:1)
  - Widescreen (16:9)
  - Portrait (.5)
  - Masonry

https://codepen.io/bspeare/pen/rNvOVZY

**Comment by joewhitsitt** [comment]
Just noticed in assisting a customer that allowing the "original/default" option would also be nice to have.

**Comment by bspeare** [comment]
I put together a Codepen exploring how a solution could work: https://codepen.io/bspeare/pen/rNvOVZY.

**Comment by quamsta** [comment]
@bspeare This would be wonderbar!

**Comment by quamsta** [comment]
@bspeare another option could be to keep the original aspect ratio: 

<img width="1621" alt="Screenshot 2023-07-14 at 8 43 43 AM" src="https://github.com/uiowa/uiowa/assets/472923/11f73da7-04b2-433f-aeae-c4360ed43483">

Similar to how Apple presents photo galleries in their Photos app:

![IMG_8174 2023-07-14 13_51_14](https://github.com/uiowa/uiowa/assets/472923/b3578fdc-429c-49b7-bf09-33d433ff4311)

The "Keep Aspect Ratio" option would be pretty simple and would involve just adjusting the `object-fit` to be `contain` in the existing CSS.
