### ISSUE TITLE
Update Drupal to 9.4.x

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#5389]
https://www.drupal.org/project/drupal/releases/9.4.0

In Drupal 9.4 and higher, drupal/core-recommended allows patch-level vendor updates (e.g. Guzzle)

Drupal 9.3 (current) receives security coverage until the release of Drupal 9.5.0 in
December 2022

Update drupal/core-recommended as part of this

**Comment by joewhitsitt** [comment]
Here is a little taste of what is to come: https://github.com/uiowa/uiowa/pull/5391

**Comment by pyrello** [comment]
I was hoping that 9.4 might be the end of the line for some of our Drupal core patches, but alas only one can be removed: #5433 (looks like we could have removed it a while ago). The rest are all at "Needs work" or "Needs review"

**Comment by joewhitsitt** [comment]
For D9.4, PHP 8.1.6 is recommended to position for D10 https://www.drupal.org/node/3295154

https://github.com/uiowa/uiowa/issues/5315

**Comment by briand44** [comment]
We may need to update code because of things being deprecated. Will need plenty of testing.

**Comment by briand44** [comment]
should consider if this needs off hours deployment, ume cache clear, etc.

**Comment by briand44** [comment]
Are we wanting to go to 9.4.0 or 9.4.5?

**Comment by joewhitsitt** [comment]
Probably. Most are bug/security bumps.

**Comment by makurj** [comment]
I'd like to learn/pair on this.

**Comment by briand44** [comment]
Added blocked label as we would like to finish https://github.com/uiowa/uiowa/issues/5579 first.

**Comment by briand44** [comment]
Scope initial slice to getting the PR ready for review.

**Comment by joewhitsitt** [comment]
At standup, we talked about putting this work in https://github.com/uiowa/uiowa/pull/5625
