### ISSUE TITLE
Residence hall content type needs a layout fallback if video field is empty

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#5396]
# Problem
https://housing.prod.drupal.uiowa.edu/stanley is the only residence hall without a video tour.   Without this video the layout has a large empty space. 

<img width="1889" alt="Screen Shot 2022-06-27 at 9 31 48 AM" src="https://user-images.githubusercontent.com/1036433/175966729-256adcef-51d7-4871-83c1-137b62d1baa9.png">

# Proposed solution
Target the second column in the empty layout with `first-child` selector and style in a three column grid. 

<img width="1814" alt="Screen Shot 2022-06-27 at 9 31 37 AM" src="https://user-images.githubusercontent.com/1036433/175966759-f3ec1533-8b8a-4c0a-b4fd-8b9e063108eb.png">

**Comment by joewhitsitt** [comment]
alternative solution: make a video for stanley or put a general iowa city type video in there?

**Comment by bspeare** [comment]
@joewhitsitt good idea.  Going to go with general video here.
