### ISSUE TITLE
Iowa Now questions

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5403]
As a developer migrating Iowa Now to SiteNow v3, I have all the information needed to begin working on the migration.

# Additional Info
Identify questions for stakeholders so we can be in a position to start working on building the migration or other development needed prior to a migration.

https://github.com/uiowa/uiowa/issues/5335 may be a good place to start

# Questions

- Combine content types (Achievement/InTheNews/News feature into Article, Contact/Person into Person)
- Photo galleries - Does this still need to be inline with the Article or can it link off?
- Are all of the taxonomies still needed? How are they used internally and externally?
- Can Facebook pixel be offloaded to Google Tag Manager?
- Are googlenews and applenews functionality still needed?
- Currently there are workflow tools that don't exist in v3 (content lock, embargo, workflow transitions). Are those still needed? Are there other workflow transitions that are needed?
- Are iframes from storify.com, www.ustream.tv, jwplatform.com still needed?
- Is https://www.drupal.org/project/typogrify still needed? If so, can you provide an example where this is being used?
- Dating back to the beginning 10k+ nodes (Achievement/InTheNews/News feature combined)?
- Do we need to maintain the "Related Items" relationships on News feature?
- Any other fields that are no longer necessary?
- Do we need to maintain any feeds/integrations for external properties/stakeholders?

**Comment by briand44** [comment]
likely a question around photo galleries, google news

**Comment by briand44** [comment]
combining content types

**Comment by joewhitsitt** [comment]
I added a few questions to the IS. In terms of migration, I am mainly curious about what content is being moved over, how we plan to handle their custom wysiwyg formatting (image floats, typogrify) and if image galleries need to be inline with articles or linked to.

**Comment by briand44** [comment]
Are there any custom feeds or API's that need to be accounted for on the new site so we are not breaking integrations with other campus sites?

**Comment by joewhitsitt** [comment]
Generally as it relates to the migration, I think the above is a good set of questions that allow us to start work on a migration. I do foresee more questions coming up as we work on it or depending on their answers to the above so it will likely take more than one-sprint to run in DEV.

I am calling this issue good. Let the migration work begin.

**Comment by joewhitsitt** [comment]
One of the features that currently exists related to workflows is that when an article is no longer embargoed and published, it changes the created date to "now" before save. This came up recently with our Demo announcements where the article was published but the creation date was before the last time the RSS reader checked so it didn't pull it in on the next run.

**Comment by joewhitsitt** [comment]
Notes from 7/20 meeting:

- Experiment combining content types, using type field to show/hide/require specific fields.
- Maintain related content (maintain existing references) (see HR. different than the tag based related content)
- Migrate photo gallery as basic page with image block link to the article using the related content. Maybe use first gallery image as the featured image for teaser references?
- Embargo functionality still necessary (prevents publishing if filled)
- Consolidate all taxonomies (hold off on keywords for now) to tags
- Okay with default editorial workflow
- They plan to send out an announcement article with all of the taxonomies checked before the site is retired to let subscribers know that the current feeds will be going away.

**Comment by joewhitsitt** [comment]
I wonder if we could tap into the current related content (tags) functionality and prioritize direct references from the content before falling back to similarly tagged content.

**Comment by bspeare** [comment]
Do we want to look into https://github.com/uiowa/uiowa/issues/4453 for Iowa Now photo galleries?

**Comment by briand44** [comment]
Closing this as we have come up with initial questions and discussed with Iowa Now partners.
