### ISSUE TITLE
IISC - Display project deliverable file using human readable name

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#5406]
# Motivation

On the current IISC site, when a deliverable is attached to a project, the user can set a human-readable name and that is what displays. On the new site, we figured out how to bring that human-readable name over in the migration, but I cannot figure out how to get it to display.

# Proposed solution

Figure out the appropriate configuration that will allow us to use the human-readable name when displaying a file media entity reference field.

**Comment by pyrello** [comment]
This may be slightly related: https://www.drupal.org/project/drupal/issues/3122051

**Comment by joewhitsitt** [comment]
Noticed this while poking around.

<img width="371" alt="Screen Shot 2022-07-08 at 8 45 49 AM" src="https://user-images.githubusercontent.com/4663676/178004427-b53411bd-92bf-4aed-9d53-d0bc72ddff81.png">

<img width="558" alt="Screen Shot 2022-07-08 at 8 52 30 AM" src="https://user-images.githubusercontent.com/4663676/178005526-ac417bd4-e6e2-4862-9ec1-e243f307ac03.png">

<img width="729" alt="Screen Shot 2022-07-08 at 8 50 16 AM" src="https://user-images.githubusercontent.com/4663676/178005564-87eb9038-d4af-4a6c-83e5-bc1fc24b9881.png">

<img width="482" alt="Screen Shot 2022-07-08 at 8 52 42 AM" src="https://user-images.githubusercontent.com/4663676/178005583-199c9952-cbba-45d3-899a-8b8f911d51fe.png">


If we don't go this route, we will need to create a custom field formatter to replace generic file OR preprocess the field to use media name instead (service wide this could be an issue if folks have been using this an admin name)

**Comment by pyrello** [comment]
Just noting that if we go this route, we will need to update the IISC project migration to set the human readable name to this description field.

**Comment by cory-skeers** [comment]
> Noticed this while poking around[...]
> > If we don't go this route, we will need to create a custom field formatter to replace generic file OR preprocess the field to use media name instead (service wide this could be an issue if folks have been using this an admin name)

This is using the generic File field instead of Entity Reference, right @joewhitsitt? I think that would be okay overall, but the files then don't end up getting media entities created for them, and miss out on the benefits there. I was going to look into the preprocess route (limiting to IISC in scope), but wanted to make sure I wasn't missing anything, because otherwise using the description works like a charm.

**Comment by joewhitsitt** [comment]
No. This is using the entity reference media but the display settings formatter for the field on the media entity is "generic file" There would be no change to the field base with any of my proposed options.
docroot/core/modules/file/src/Plugin/Field/FieldFormatter/GenericFileFormatter.php

**Comment by cory-skeers** [comment]
> No. This is using the entity reference media but the display settings formatter for the field on the media entity is "generic file" There would be no change to the field base with any of my proposed options.
> docroot/core/modules/file/src/Plugin/Field/FieldFormatter/GenericFileFormatter.php

Okay, thanks for the clarification! That looks like a much more appealing route than I'd thought.
