### ISSUE TITLE
Audit usages of the UIDS 3 banner component in SiteNow

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#5409]
# Proposed solution
Generate a list of all instances where the `banner.html.twig` template is used in `uids_base`,  custom modules, and site modules.

**Comment by bspeare** [comment]
Do we need more than this for the audit?

# Templates

- https://github.com/uiowa/uiowa/search?l=Twig&q=banner

# Custom/Site modules

- https://github.com/uiowa/uiowa/blob/9876d09b7f65ce9290800381cf236ac5df600982/docroot/modules/custom/studentlife_topics/studentlife_topics.module
- https://github.com/uiowa/uiowa/blob/5781b81335f160b6ff1fd77f2317fe19c16bf1ba/docroot/modules/custom/layout_builder_custom/layout_builder_custom.module
- https://github.com/uiowa/uiowa/blob/a8627c4af5f4abbdc6d95e3c33399085a89ba713/docroot/themes/custom/uids_base/uids_base.theme
- https://github.com/uiowa/uiowa/blob/d06878a3062264b55d9fd8fa2490af780c991a80/docroot/sites/grad.admissions.uiowa.edu/modules/grad_admissions_core/grad_admissions_core.module
- https://github.com/uiowa/uiowa/blob/0f2a63774524a9b0784b3e5f10708c290d06f6fe/docroot/sites/housing.uiowa.edu/modules/housing_core/housing_core.module
- https://github.com/uiowa/uiowa/blob/e71fda472ed6eb9282d5983bd24e8f70847ee835/docroot/sites/admissions.uiowa.edu/modules/admissions_core/admissions_core.module

**Comment by bspeare** [comment]
@pyrello I think the GitHub search and the module files listed above give us enough information to move forward with the banner work.   Feel free to re-open this if you think there is more work left to be done.
