### ISSUE TITLE
Transition College of Pharmacy from APR profiles to uiowa profiles

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5411]
As a College of Pharmacy site owner, I would like to display people on my website from Directory Profiles rather than APR Profiles, since APR is being phased out.

# Additional Info
This should happen on Monday, July 18th

The current directory lives at https://pharmacy.uiowa.edu/people. We should keep that directory path going forward.

A conversation is ongoing in regards to handling redirects for individual profiles - update, sounds like Pharmacy folks will handle this manually after the switch is made.

I would like to understand what is all involved in making this change? Is it as simple as disabling the APR profiles module and enabling and configuring the Directory Profiles module? Is there a release needed as part of this work? Submit person sitemap?

# Proposed Solution

- [x] Disable APR feature split, uninstall the APR module (removes the uiowa_apr.settings.yml),  run config import?
- [x] Enable Directory Profiles feature split, run config import?
- [x] Configure Directory profiles - API Key - use existing directory path
- [x] Submit/Re-submit profiles sitemap - (bdickey/mjoneill/mkyoder)
- [x] Communicate this with Pharmacy/Directory Profiles stakeholders - (bdickey/mjoneill)

**Comment by briand44** [comment]
Need API Key for Directory Profiles

**Comment by briand44** [comment]
I've updated proposed solution, feel free to edit/update if I got it incorrect. I will add any additional information after meeting on Thursday.

**Comment by briand44** [comment]
Adding blocked label since we do not want to make this switch until Monday, July 18th.

**Comment by briand44** [comment]
A few notes after meeting about this today:
- Confirmed this should happen on July 18th.
- API key is in an email in its-web

Directory Profiles config
- Title = Person Directory
- API Key - in its-web
- Path = /people
- Page size = 30
- Introduction text = Empty

**Comment by briand44** [comment]
This is no longer blocked.

**Comment by joewhitsitt** [comment]
Page size doesn't seem to be accurate

Update: reported the issue to https://git.uiowa.edu/java/profiles/-/issues/529

**Comment by joewhitsitt** [comment]
Remaining issue activity here: https://iowaweb.slack.com/archives/C0164FNN1PV/p1658154647122949

Closing
