### ISSUE TITLE
Transition stories.uiowa.edu to SiteNow v3

### ISSUE THREAD

**Issue by mjoneill** [uiowa/uiowa#5426]
As a reader of OSC stories, I can read content on a Sitenow v3 website. 
-or-
As a dev team, I do not have to maintain the stories site on deprecated Drupal 7 codebase

**Comment by mjoneill** [comment]
Converted this note to an issue because @meganyoder recently interviewed Chris about the website and captures some info related to future site needs in a SNv3 migration.  

Not urgent, not close work.

**Comment by mkyoder** [comment]
Met with Chris C. on 6/29 about stories.uiowa.edu. Would like similar functionality as what is on the current site. 

Chris wants to keep:
- All the features of the story content type 

Chris wants to keep the following brick types:
- Add text
- Add callout
- Add photo
- Add gallery
- Add quote
- Add related items
- Add touts
- Add video
- Add timeline
- Add detail list

Chris does not want to keep:
- Add link collection 
- Add Tweet 
- Add custom block

Chris wants to add:
-Option to tag pieces with taxonomy and allow user to filter stories by taxonomy tags (e.g. see all stories related to healthcare)

Large item for discussion:
-Can this get folded into uiowa.edu? Or will this remain an entirely separate site at stories.uiowa.edu? Ideally, would like to fold it into uiowa.edu.

**Comment by briand44** [comment]
Closing in favor of https://github.com/uiowa/uiowa/issues/8357
