### ISSUE TITLE
Update Housing Links

### ISSUE THREAD

**Issue by makurj** [uiowa/uiowa#5436]
From: Yoder, Megan K <megan-yoder@uiowa.edu>
Sent: Friday, July 8, 2022 8:38 AM
To: ITS Help Desk <its-helpdesk@uiowa.edu>
Cc: Matthes, Anne E <anne-matthes@uiowa.edu>
Subject: Res hall pages sidebar

Hello!

Can we change the URLs that these res hall pages (https://housing.uiowa.edu/residence-halls/burge-hall) point to below? I believe these are hard coded throughout all res hall pages and broke when other UI sites changed, and with working on the new housing site, I forgot to follow up on these. My apologies!

Advocate for students should point to: https://housing.uiowa.edu/leadership
Discover your passion should point to: https://getinvolved.uiowa.edu/
﻿
Thank you so much for all your help! Also, this is not an urgent request. ??

Thank you,
Megan

﻿

﻿

**Comment by briand44** [comment]
@meganyoder Does the subtitle text need to change for either of these as well or just the link? 

`Become a member of the Associated Residence Hall.`
`Connect with Center for Student Involvement and Leadership.`

https://housing.uiowa.edu/residence-halls/burge-hall

**Comment by mkyoder** [comment]
@briand44 No. The subtitle text can stay the same. Just the link needs changed. Thank you so much!

**Comment by briand44** [comment]
I've pushed the updated links and cleared caches and purged varnish. Closing this.

**Comment by mkyoder** [comment]
Thanks so much! Looks great!
