### ISSUE TITLE
Signage solution for Pentacrest Webcam

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5437]
As a consumer of the Digital Signage service, I would like any existing Pentacrest webcam live streams to continue to work as well as any new Pentacrest webcam live stream panes once the server hosting https://webcam.iowa.uiowa.edu/live/ is retired.

# Additional Info
Work has been done in https://github.com/uiowa/uiowa/issues/4825 to transition the live stream to osc.uiowa.edu. We will likely need to refactor the existing pane to account for the new home https://camstreamer.com/embed/WZoa7fiZquZiv6qZxpgA43yloExHdnwmmquO2Aco.

Based on the recommendation to use permanent embed code rather than a YouTube embed, it is starting to look like it makes more sense to refactor the Pentacrest Webcam signage pane rather than deprecating the widget and communicating to folks to use the existing video embed pane.

This likely needs to happen prior to a Vulture redirect and definitely before retiring the server.

Widget code lives at `sites/all/modules/custom/uiowa_signage_modules/uiowa_signage_panes/plugins/content_types/pentacrestcam.inc`
and
`sites/all/modules/custom/uiowa_signage_modules/uiowa_signage_panes/js/pentacrestcam.js`

# Proposed Solution
- [x] Audit usage of pane on Signage and Healthcare Signage
- [x] Refactor widget to work with new url on Signage application
- [x] Implement on Healthcare Signage as well.
- [ ] Continue work in https://github.com/uiowa/uiowa/issues/4825 to setup redirect, etc. in future slice.

**Comment by joewhitsitt** [comment]
Healthcare does have it. Not sure if it is in use though: uihealthcaresignage-dev/docroot/sites/all/modules/custom/uiowa_signage_modules/uiowa_signage_panes/plugins/content_types/pentacrestcam.inc

**Comment by briand44** [comment]
Poked at the audit a bit but only briefly. Not sure if I am heading down the right track but ran this SQL query:
`SELECT pe.entity_id
FROM panelizer_entity pe, panels_pane pp
WHERE pp.did = pe.did
AND pp.type = 'pentacrestcam'`

15 results in prod but wanting to understand these more. Started looking at these entities but going to have to switch gears soon.

**Comment by briand44** [comment]
Looked at these 15 entities and it looks like they are probably a mix of test signs and some that look like they are likely in use. Some examples that look like in use are:

- College of Public Health - IT - https://signage.uiowa.edu/node/73
- Collefe of Public Health - IT - Informatics? - https://signage.uiowa.edu/node/2017
- UIHC Hospital Administration - UCC - https://signage.uiowa.edu/node/11158
- College of Nursing - https://signage.uiowa.edu/node/144326 or https://signage.uiowa.edu/node/148406
- IP - https://signage.uiowa.edu/node/80076 or https://signage.uiowa.edu/node/128241
- College of Law - https://signage.uiowa.edu/node/149061

**Comment by joewhitsitt** [comment]
Higher usage than I thought when I suggested doing away with it. Thanks for looking into it.

**Comment by mjoneill** [comment]
Sounds like you probed and learned its usage is non zero.

**Comment by briand44** [comment]
I did not find any usage on Healthcare Signage but since the widget is available there, my opinion is we should update it there as well.

**Comment by briand44** [comment]
I believe the url changed to https://camstreamer.com/embed/zf6BUqMXKquweRwKYXtwqJ8c0VRIkXq0KdvMZs4d

https://github.com/uiowa/uiowa/issues/4825#issuecomment-1178271562

**Comment by joewhitsitt** [comment]
Capturing Slack discussion: https://iowaweb.slack.com/archives/C0164FNN1PV/p1658773280902139

**Comment by joewhitsitt** [comment]
https://iowaweb.slack.com/archives/C0164FNN1PV/p1658867688935519

Pulling down to test

**Comment by joewhitsitt** [comment]
Fun fact - There seems to be less delay with the new stream when comparing local and prod side-by-side. Also, it is darker/less washed out.

Seems to work for new and existing. hairline differences. Multiple also works fine.

APPROVED

**Comment by briand44** [comment]
We still have the YouTube controls though right? If so, I may reach out to Nick or we may want to communicate this change if it will change appearance of existing signs?

**Comment by joewhitsitt** [comment]
YouTube chrome on load/reload yes. Hidden after moments. Based on the stackoverflow i posted in Slack, sounds like Youtube removed any control over of that stuff (i get why when i put on their shoes). Since it isn't crucial signage info, folks can remove if they don't like the change. is the signage listserv up to date?

**Comment by makurj** [comment]
So good to do this exact work on a feature branch for HC signage?

**Comment by briand44** [comment]
Blocked until we hear back from video team on if there are options to remove controls and info header.

**Comment by briand44** [comment]
Met with Nick and it doesn't seem like there are options to hide the controls or info bar. I have removed the blocked label.

**Comment by makurj** [comment]
Should I push this to prod? Or do we want to send out communication via listserv/email lists first?

**Comment by briand44** [comment]
Personally, I am ok with rolling it out as long as it has passed team reviews. There doesn't seem to be a listserv for these types of announcements. There does seem to be an email address but I am not sure how/when/why folks get added to that so I don't know if it is even reaching the right users. We brought it up in demo and asked if there was concerns and nobody spoke up or reached out.

**Comment by briand44** [comment]
also there have been security updates so if you are going to roll it out, make sure your branch has been updated.

**Comment by makurj** [comment]
Will do!

**Comment by briand44** [comment]
Closing this as it looks like this has been deployed to both applications. Thanks @makurj!
