### ISSUE TITLE
IRRC (D7) reCAPTCHA v3 installation

### ISSUE THREAD

**Issue by makurj** [uiowa/uiowa#5439]
https://iowaweb.slack.com/archives/C0164FNN1PV/p1656622004305319

Emails from Sean Thompson in ITS Web Inbox.

**Comment by makurj** [comment]
@cory-skeers the secret and key in the email thread and on the site (https://iowareadingresearch.org/admin/config/people/captcha/recaptcha) are identical. Why was V3 suggested? Joe's advice for V1 is RCv2.

**Comment by joewhitsitt** [comment]
Related Slack conversations:

https://iowaweb.slack.com/archives/C0164FNN1PV/p1656513437152939

https://iowaweb.slack.com/archives/C0164FNN1PV/p1656622004305319

https://iowaweb.slack.com/archives/C0164FNN1PV/p1657567360599479

**Comment by cory-skeers** [comment]
> @cory-skeers the secret and key in the email thread and on the site (https://iowareadingresearch.org/admin/config/people/captcha/recaptcha) are identical. Why was V3 suggested? Joe's advice for V1 is RCv2.

The secret and key they provided are for RCv3, and incompatible with v2. I wasn't aware of the issues with using rcv3 on v1, and thought we could still handle it with a module change, but we'll need to go back to the customer and have them update their account to v2 and provide those new keys.

**Comment by makurj** [comment]
Do they need to update the keys as they are already on the site or identical to the ones on the site?

**Comment by cory-skeers** [comment]
> Do they need to update the keys as they are already on the site or identical to the ones on the site?

The keys that are currently on the site are the ones they provided--I put them in and from that found out they were v3 keys and incompatible. If they update the account to v2, they should get a new set of key/secret that will need to replace the ones entered on the site.

**Comment by makurj** [comment]
That makes sense. Joe and I were wondering if you had started work on this. I will reach out to the customer.

**Comment by cory-skeers** [comment]
> That makes sense. Joe and I were wondering if you had started work on this. I will reach out to the customer.

Great! Sorry for all the confusion there.

**Comment by makurj** [comment]
No worries :)

**Comment by makurj** [comment]
V2 keys set up, default changed to reCAPTCHA.
