### ISSUE TITLE
Smooth scrolling behavior causes excessive bouncing when editing blocks in Layout Builder

### ISSUE THREAD

**Issue by quamsta** [uiowa/uiowa#5441]
Related: https://github.com/uiowa/uiowa/issues/4647 and https://www.drupal.org/project/drupal/issues/3152561

# Problem
When performing some actions on a block (e.g., removing a block) in Layout Builder, an editor will occasionally get bounced around the page excessively. ~~This is likely due to the introduction of `scroll-behavior: smooth` in [https://github.com/uiowa/uiowa/issues/3688.](https://github.com/uiowa/uids/pull/581).~~ This is more likely an upstream thing with Layout Builder, but our implementation of `scroll-behavior: smooth` may be exacerbating/highlighting the issue.

### Removing a block

https://user-images.githubusercontent.com/472923/178061768-6f75feb8-9d4d-49b2-920d-32888244e1a8.mov

### Adding a section 

https://user-images.githubusercontent.com/472923/178064836-4afea861-ade2-40e5-a2df-877c7dff6c25.mov

### Editing a block

https://user-images.githubusercontent.com/472923/178065185-2b53c188-ac93-4350-9c04-afafc5d8bf27.mov

# Steps to reproduce
1. Remove a block that's far enough down the page that scrolling can occur, watch the page bounce up and down

OR 

1. Configure a block that's far enough down the page that scrolling can occur

OR 

1. Add a section far enough down the page that scrolling can occur

# Proposed solution
It appears that Layout Builder isn't expecting `scroll-behavior: smooth` to be enabled when jumping to several anchors in a row as part of its process when moving or removing a block. If this `scroll-behavior` CSS was overridden or disabled while an editor is logged in and/or editing a page, the site editor wouldn't see the actual scrolling to/from anchors, and their browser would seemingly be placed instantaneously where it should be, as was the case before `scroll-behavior: smooth` was added

While at the same time, a typical user who wasn't logged in could see the desired smooth scrolling behavior.

This could be accomplished by adding a CSS class that disables this behavior to `<html>` via some conditional Javascript that executes only when a user is logged in.

Testing solution via the web inspector tool reduces some of the bouncing around, but the scrolling to the top is a bit jarring. The above solution might be a partial remedy.

**Comment by cory-skeers** [comment]
Possibly related to https://github.com/uiowa/uiowa/issues/4647? That's about the scroll-to-top behavior after removing a block, not the bouncing that might occur so it's a bit different, but could be some overlap.

**Comment by quamsta** [comment]
@cory-skeers Yeah, that seems similar! This issue in particular seems to occur not only when removing a block, but in other situations (like adding a section, which I'm going to edit my original comment and add a video for that scenario too)

**Comment by joewhitsitt** [comment]
I later mentioned when adding a block as well. https://github.com/uiowa/uiowa/issues/4647#issuecomment-1104271034

I don't think separate issues are needed. Since you have video demo on this one, can we just add the drupal.org issue to this and close the older one?

**Comment by quamsta** [comment]
@joewhitsitt Yeah, I'm now seeing this may be an upstream thing that's more like the issue you filed. I thought maybe it was our implementation of `scroll-behavior`, but after looking at that drupal.org issue and doing some minor testing in the inspector, this may be a more complicated than I originally thought. I'll add a link to your issue and the drupal.org one in the original post. Thank you!

**Comment by quamsta** [comment]
@joewhitsitt I edited the original issue, but I did note that if `scroll-behavior: smooth` is removed from our CSS, the bouncing is quite a bit less pronounced. The viewport still scrolls to the top jarringly, but there's less bouncing between the transition between scrolling to the top/bottom so I left my proposed solution as a way to partially resolve this.

**Comment by pyrello** [comment]
I said during standup that we had a separate CSS (SCSS) library for when Layout Builder is loaded, but I guess we actually hadn't implemented that yet and it was just something that had been talked about. I started a PR (#5444) to facilitate those changes.

**Comment by briand44** [comment]
#5444 is being addressed. Upstream issue needs resolved to fully close this issue.

**Comment by pyrello** [comment]
So... to be clear, the real problem here is the jump to top that happens on certain actions in LB. The secondary scrolling that happens to put the highlighted block in the frame is necessary/desirable because most actions in LB open the settings tray, which changes the width of the main page container. The content re-flows and then the highlighting brings the block back into the center of the viewport. 

https://www.drupal.org/project/drupal/issues/3152561 is tracking some version of the jump to top issue, but the patch there does not resolve the issue. In fact it makes it worse because it removes the desired behavior without fixing the jump to top behavior, so the user is just at the top of the page with now idea why.

There is a possibly related issue to limit the scope of when the `transitionend` event listener gets fired here: https://www.drupal.org/project/drupal/issues/3209129. I tried the patch and its effect seems to be the same as the other one. However, the idea that maybe this is a scoping issue of when the event listener fires is an interesting idea.

As a separate side note, LB programmatically sets scrolling to be smooth in some instances, which I believe should be the purview of the theme rather than the UI, so I opened this issue: https://www.drupal.org/project/drupal/issues/3295779

**Comment by pyrello** [comment]
I definitely went down a bit of rabbit hole on this :| 

By stepping through what happens after the block removal form class gets called, I can definitively say that whatever is triggering the jump to top action does not happen until after the AJAX fragment for the form gets returned. The `transitionend` event listener in `layout-builder.js` doesn't cause this: Disabling it merely causes the page to jump to the top without the subsequent scroll back down to the highlighted block. At the moment, I'm stumped about what the mechanism is that is causing the jump.

Another avenue of inquiry on this would be to see if this is happening in a standard Drupal install using Bartik. It was mentioned in https://www.drupal.org/project/drupal/issues/3209129#comment-14196217 that Bartik doesn't implement a `transitionend` event, so doesn't trigger the behavior described there. That makes me wonder whether our theme might be the culprit for triggering the as-yet-to-be-discovered JS event that is causing the jump to top.
