### ISSUE TITLE
A11y issues with Oembed pages

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5454]
SiteImprove is flagging Oembed pages for a couple accessibility issues. An example of an Oembed page is https://dentistry.uiowa.edu/media/oembed?url=https%3A%2F%2Fyoutu.be%2FZYryBApSHnY&max_width=0&max_height=0&hash=_BOtesPCR5PqFhOhBliziNlOTtESmzIKvrlDkL13Bqc

Page has no title - https://my2.siteimprove.com/Accessibility/998437/NextGen/Issue?ruleId=1&pageSegments=&issueKind=1&exceptTags=1,2&conformance=&siteGoal=0,1

Page language has not been identified - https://my2.siteimprove.com/Accessibility/998437/NextGen/Issue?ruleId=4&pageSegments=&issueKind=1&exceptTags=1,2&conformance=&siteGoal=0,1

Should we be disallowing these pages in robots.txt??

**Comment by joewhitsitt** [comment]
I wonder if there is an upstream issue for this because there were steps previously taken to not have local media paths

**Comment by joewhitsitt** [comment]
Could be potentially resolved using this 9.5 change to robots.txt https://www.drupal.org/node/3313604
