### ISSUE TITLE
Audit text format usage in blocks and figure out how to add `<ul>` to minimal

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#5472]
# Story

As a site owner, I can add a `<ul>` within a card block so that I can showcase content with lists. 

# Proposed solution

<img width="997" alt="Screen Shot 2022-07-20 at 4 08 09 PM" src="https://user-images.githubusercontent.com/1036433/180082689-f159996f-7302-4bee-924b-a0fba6539720.png">

- Audit existing block components with text areas to determine if there needs to be any additional formats or if it makes sense to stick with basic, minimal and filtered. Also, consider switching some to alternate formats (banner->basic)?
- Bring recommendations to the team
- Possibly add `<ul>` tag to `minimal_html` format unless another idea is adopted based on prior investigations. 
- Test out inline blocks that use the `minimal_html` format and test how `<ul>` work within each block.

**Comment by bspeare** [comment]
@joewhitsitt mentioned in Slack that this could create visual problems with left/right aligned cards in four column layouts.  Here are some screenshots below.  

I think left/right aligned cards in four column layout with images already look terrible so maybe this wouldn't change much?


Current:

<img width="1398" alt="Screen Shot 2022-07-20 at 4 14 23 PM" src="https://user-images.githubusercontent.com/1036433/180083818-b80bda7e-6d5b-4d91-84c4-ea248284eb88.png">

Proposed:

<img width="1399" alt="Screen Shot 2022-07-20 at 4 15 42 PM" src="https://user-images.githubusercontent.com/1036433/180083864-9dc263dc-754d-4895-a903-9b00f272025f.png">

**Comment by bspeare** [comment]
The banner uses the same text format.

**Comment by joewhitsitt** [comment]
Bump. This is coming up again as we develop new content types.

**Comment by joewhitsitt** [comment]
As I mentioned in planning yesterday, an above and beyond type task would be to grep minimal_text database entries to see what kind of html elements are being used in them. Instead of running on all sites, we could limit to the first_run sites. Off-hand I don't have a magic snippet to run for that, but if we are twiddling thumbs that could be informative.

**Comment by makurj** [comment]
Here is a list of the WYSIWYG buttons available on each block with which text format.
[block-audit.xlsx](https://github.com/uiowa/uiowa/files/10211747/block-audit.xlsx)

Here is what the blocks with "Minimal" and "ul" enabled look like:

![image](https://user-images.githubusercontent.com/52135878/207147419-8b55d4ba-7d01-4499-a35e-2aa3d06aa4e7.png)

**Comment by makurj** [comment]
![image](https://user-images.githubusercontent.com/52135878/207148434-412d6177-12c1-4e90-8a59-e6f244236797.png)

**Comment by bspeare** [comment]
Based on Makur's investigation, my vote is that we:

- Add `<ul>` to Minimal
- Remove `strikethrough, superscript, subscript, special character` from Minimal
- Add `link` to Basic
- CTA should use Basic if we added the ability to link
   - We would need to audit CTA html usage
   - We might need to update blockquote template
- Slider should be moved to something like Basic.  There really is no room in there for a lot of formatting. 
  - We would need to audit Slider html usage

Next steps?  Figure out how we want to audit these blocks (and v2) if we were to pursue these changes.

**Comment by joewhitsitt** [comment]
Thoughts from mid-sprint:

- Starting to feel that changes to minimal or where it is used shouldn't happen until at least v2 is gone. It reduces the sites affected and helps maintain the conversion work already done in p2lb.
- Is basic only used for quote content, quote footer and named_building body? If so, I think it should be expanded (bold, underline, italic, strike, super/sub, special character, link). If the existing fields can't handle the expansion they should be move to `formatted_plain` or something.
- I think creating a temporary in between format basic and minimal with UL would allow sites to move forward until v2 is gone at which point those field can upgrade to minimal and the temp format can be removed.
- Unless we can confirm no site is using an option of minimal, I think we should avoid removing options from it and instead move components off that we don't think can handle UL or other allowed formatting. With each move (done one at a time to avoid overwhelming content editors) there should be a communication guide to help folks identify (find text?) and update their content in preparation for the move.
- The issue with the slider seems like a text length issue more than anything and should be treated separately.

**Comment by joewhitsitt** [comment]
>Remove strikethrough, superscript, subscript, special character from Minimal

Can you elaborate on this? Are these causing problems in minimal text areas?

**Comment by bspeare** [comment]
> Can you elaborate on this? Are these causing problems in minimal text areas?

I agree that these options are "What is too much?" for our block components.   It would be ideal to remove those options from our block components.

**Comment by joewhitsitt** [comment]
Generally I feel like our formats should inherit the options from the lower formats and on campus (that in minimal I should be able to do everything I was able to do in lower formats to prevent stripping), I feel like there are use-cases for formatting strings of text (e.g. underlined titles in MLA citations) where we don't want other options (ul/ol, links, blockquote). That is why I suggest keeping those in minimal and expanding basic.

**Comment by bspeare** [comment]
After discussing this a little with @joewhitsitt, it sounds like this could be our next step:

1. Create a new temporary text format that duplicates Minimal and adds `<ul><ol>`
2. Switch the card block and the facilities text fields to use this new format
3. Create post v2 issues for: 
   - Moving CTA block out of Minimal to something more restricted
   - Expanding Basic format so it could be used by components like the CTA block

**Comment by makurj** [comment]
Couple of questions:
1. https://github.com/uiowa/uiowa/issues/5472#issuecomment-1349258442 is a follow-up issue, or are we doing these steps as part of the current issue?
2. “facilities text fields” are those all fields that the Facilities’ site uses? Or just the one that uses minimal, which is `field_building_honoree_achieve` ? Is it related to https://github.com/uiowa/uiowa/issues/5962?

**Comment by joewhitsitt** [comment]
@makurj to respond to your questions:

1. Yes, I think the idea of this issue was to help generate a path forward. Not address it unless it was simply to add UL to the existing format (not the case).
2. I think we have identified the card and field_building_honoree_achieve yes so far. However, I want say there was another one in mind when I commented https://github.com/uiowa/uiowa/issues/5472#issuecomment-1331082634

**Comment by makurj** [comment]
Based on the comments above, created 2 new issues for next steps https://github.com/uiowa/uiowa/issues/6023 and https://github.com/uiowa/uiowa/issues/6024. Closing this issue.

**Comment by pyrello** [comment]
Re-opening because we did not implement a solution for facilities, which was specified in the IS as part of the work we were committing to.

**Comment by bspeare** [comment]
This work was originally requested by Student Life this past summer.

**Comment by joewhitsitt** [comment]
>Re-opening because we did not implement a solution for facilities, which was specified in the IS as part of the work we were committing to.

Should this be moved out of done? Is https://github.com/uiowa/uiowa/issues/6023 now being done as part of this issue based on https://github.com/uiowa/uiowa/issues/6023#issuecomment-1353277002?

**Comment by makurj** [comment]
Moved it into planned.
