### ISSUE TITLE
Articles ListBlock more link settings link is wrong

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#5473]
Links to: /admin/config/sitenow/sitenow-articles
Should be: /admin/config/sitenow/uiowa-articles

While working on this, check for other instances where our helpful links are not currently helpful.

<img width="463" alt="Screen Shot 2022-07-21 at 9 47 07 AM" src="https://user-images.githubusercontent.com/4663676/180243942-2fb84f78-12c8-46d3-b202-0a96a5340765.png">

**Comment by makurj** [comment]
For followup issue: 
![image](https://user-images.githubusercontent.com/52135878/189424849-b36941aa-3f06-4a89-980e-b25973c052d9.png)
