### ISSUE TITLE
Media reference allows more than the limit, prevents save.

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#5478]
# Problem

When adding new media through the Media Library, it's possible to add more than the allowed number of media items. This prevents the page from being saved and doesn't allow you to open the media library to fix the issue.

_Originally posted by @bspeare in https://github.com/uiowa/uiowa/pull/5477#issuecomment-1191955230_

# Steps to reproduce

- click to add media
- Add a new media in the modal, using a valid URL. Choose to "Save and Select"
- Back at the main modal screen, click to add another new media
- Add a new media in the modal, using a valid URL. Choose to "Save and Select" again.
- Both newly created media items will be selected. Choose to "Insert Selected" and both will be added.

# Upstream

https://www.drupal.org/project/drupal/issues/3059955

# Known Issue

https://sitenow.uiowa.edu/known-issues#uiowa-issue-5478

# Proposed Solution

Try using the upstream patch when stable.

**Comment by cory-skeers** [comment]
Was able to recreate this with the maps field:

1. click to add media
2. Add a new media in the modal, using a valid URL. Choose to "Save and Select"
3. Back at the main modal screen, click to add another new media
4. Add a new media in the modal, using a valid URL. Choose to "Save and Select" again.
5. Both newly created media items will be selected. Choose to "Insert Selected" and both will be added.

Haven't tested with other media fields yet, or if it's only this field. Also unsure if this is the only way to recreate it or not.

**Comment by cory-skeers** [comment]
Can recreate on the Featured Image field using the steps above:

<img width="447" alt="image" src="https://user-images.githubusercontent.com/49074566/180469449-7762ee2e-f41a-4dd4-b369-ef8dd566b1c7.png">

It won't let the node save, erroring on the Featured Image field, but it also won't let me remove the excess media items or replace them with a different (single) item. Workaround then is to back out of the edit and try again--the attempted media adds will exist in the media library, but when re-editing the page no media items will be attached to the media reference field.

**Comment by cory-skeers** [comment]
Probable related issue: https://www.drupal.org/project/drupal/issues/3059955

**Comment by pyrello** [comment]
I don't understand how this has never come up before.

When I tried to replicate, I was using a node that I had already saved. It didn't not offer the "Add media" button in that case.

Thanks for looking into this, @cory-skeers!

**Comment by makurj** [comment]
https://github.com/uiowa/uiowa/issues/5971#issuecomment-1460773704

**Comment by joewhitsitt** [comment]
The referenced issue has been committed to 10.1.x

**Comment by bspeare** [comment]
This looks fixed in 10.1, feel free to reopen if that's incorrect.

**Comment by joewhitsitt** [comment]
Need to remove the known issue

**Comment by bspeare** [comment]
The known issue has been removed.
