### ISSUE TITLE
Set up ClickCease for MBenning

### ISSUE THREAD

**Issue by mjoneill** [uiowa/uiowa#5480]
As a digital marketer, I have click-fraud prevention set up on my landing pages so that I'm not wasting money buying fraudulent clicks.

Install instructions
-  are in the ClickCease help center https://www.clickcease.com/
- I suspect we're going to implement through GTM...  2 local accounts based on landing pages identified (admissions and uiowa).  We would not want to implement this through the campus-wide GTM because of overhead it would impose on every page render.

Landing pages (prelim)
- uiowa.edu
- admissions.uiowa.edu/first-year-visit-options
- admissions.uiowa.edu

**Comment by mjoneill** [comment]
Blocked while MB gets the account set up, etc...

**Comment by briand44** [comment]
Added this to uiowa.edu... I'm using a trigger where `path equals /`. Not sure if this is the appropriate trigger to only fire on the home page? I'm not sure if this should fire if there was a campaign tracking id passed in as well? May need regex to handle that.

**Comment by briand44** [comment]
Also, @mjoneill there was a workspace change where crazyegg was paused but that change hadn't been published. I abandoned that change in order to publish these changes.

**Comment by briand44** [comment]
I updated the trigger to use `page path matches RegEx ^\/(\?(.*))?$` to account for campaigns and other query parameters.

**Comment by briand44** [comment]
>Also, @mjoneill there was a workspace change where crazyegg was paused but that change hadn't been published. I abandoned that change in order to publish these changes.

I did that on both UI Home Page and admissions.uiowa.edu containers.

**Comment by briand44** [comment]
added to uiowa.edu, admissions.uiowa.edu, and admissions.uiowa.edu/first-year-visit-options
