### ISSUE TITLE
clone of vpma.jobs.uiowa.edu for search.csd.uiowa.edu

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5482]
>I'm writing to request that CLAS be provisioned a site that is a copy of the VPMA search site: https://vpma.jobs.uiowa.edu/

>The purpose of this site is it is a time-limited recruitment tool for a DEO search in [Communication Sciences and Disorders](https://csd.uiowa.edu/), a very important leadership position for the college and the university.  We are mapping out the content needs in parallel and just thought it would be best to leverage the existing design than build from scratch.

>URL wise I think we were thinking something like search.csd.uiowa.edu but open to other ideas or hearing any concerns.  Since it won't be a 'public' oriented site like some of the other search sites and will be optimized for the candidates, getting the perfect URL is not as critical to me so we are flexible.

>I'm copying Mark Bennett as our web lead in case of any questions and Mike Cranston will be the primary editor on this so he will need access.

# Proposed Solution
- [x] Determine domain name
- [x] submit site request on behalf of CLAS
- [x] provision site
- [x] sync vpma.jobs.uiowa.edu
- [x] SSL
- [x] data cleanup - webform submissions, user roles, etc.

**Comment by briand44** [comment]
Michael's comment related to webforms...

>if he needs to clone [presidentialsearch.uiowa.edu](http://presidentialsearch.uiowa.edu/), we’ll have to clean up the private data on form submissions, etc…
Joe did that last time.

**Comment by briand44** [comment]
csd.jobs.uiowa.edu was approved and CNAME created

**Comment by GaryRidgway** [comment]
https://github.com/uiowa/uiowa/pull/5486

**Comment by GaryRidgway** [comment]
CSD is created, user not contacted.

https://jobscsd.prod.drupal.uiowa.edu/

**Comment by GaryRidgway** [comment]
Synced over the vpms.jobs site to this one, removed webform submissions, cleared old user roles, added mjcranston to users as webmaster
Resent email with extra info on changing old vpma data, sent to Mike Cranston, Ben Hill, and Mark Bennett
