### ISSUE TITLE
Article content type development to support migrating Iowa Now news

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5485]
As an Iowa Now website owner transitioning to SiteNow v3, I would like to use the article content type to support existing Iowa Now news related content types (In the News, News Feature and Achievements), so that all news related content can be managed in one place.

# Additional Info

Use type field to show/hide/require specific fields - types = in the news, news feature, achievement.
Locking to prevent simultaneous editing is no longer needed.

**In the News**
- Source and Url are a field collection and allow multiples - If we run into multiples during migration, just pull over the first. No specific development needed for this.
- Original Publication Date - currently select list - need to account for this.
- Primary media - allows 1 image or video - No specific development needed for this. When migrating, if there is a primary media item that is a video, we should append to body. Default to hide featured image when migrating.

**News Feature**
- Subhead - no specific development, when migrating prepend to body with "intro light class".
- Broken links message - could be useful for others - https://github.com/uiowa/uiowa/issues/4079#issuecomment-934631596
- Primary media - allows 1 image or video - No specific development needed for this. When migrating, if there is a primary media item that is a video, we should append to body. Default to hide featured image when migrating.
- Primary media caption - https://github.com/uiowa/uiowa/issues/3561
- Photo Gallery - https://github.com/uiowa/uiowa/issues/5474#issuecomment-1191645695 - what if no featured image but is a gallery? Do we show featured image as part of gallery? Need to figure out how this behaves but ok with going this direction.
- Specials - 2012,and 2013 annual report, 2014 commencement - Don't need development to account for this - additional clarification should be coming on how to handle during migration.
- Related Items - reference other articles of all types - this is needed - HR is an example - https://github.com/uiowa/uiowa/issues/4490
- Embargo message - functionality still necessary (prevents publishing if filled)
- Apple News? - Not needed.

**Achievement**
- Category - No development needed - migrate as tags
- Broken links message - could be useful for others - https://github.com/uiowa/uiowa/issues/4079#issuecomment-934631596
- Primary media - allows 1 image or video - No specific development needed for this. When migrating, if there is a primary media item that is a video, we should append to body. Default to hide featured image when migrating.
- Primary media caption - https://github.com/uiowa/uiowa/issues/3561

**Spotlight**
These are currently "In the News" articles that have a source url containing "uiowa.edu". These will need to be handled as part of the migration. Still determining if they will be a separate type or a tag, etc.

# Proposed Solution
**First Slice**
- [x] Set up split
- [x] Add article types
- [x] show/hide/require fields based on selected type - original pub date, embargo

**Comment by joewhitsitt** [comment]
I don't think the content lock is needed anymore. Might want to ask about the trigger that when it is published, the created date is updated to NOW.

**Comment by briand44** [comment]
Let's scope a first slice to setting up site split, adding article types, showing/hiding/requiring fields based on type. Some fields that could be included in this slice... publication date, embargo, achievement category.

**Comment by makurj** [comment]
I would like to pair on this.

**Comment by briand44** [comment]
Updated the IS based on feedback.

- Types - In the News, News Feature, Achievement
- Will be migrating all articles
- Do not need to account for locking to prevent simultaneous editing
- Do not need to account for multiple sources - will migrate first source and url
- primary media will migrate to featured image, if a video append to body during migration - default to hiding featured image on article when migrating.
- subhead can be prepended to body during migration with "intro light" class
- broken links message needed similar to current feature - useful for others on the service
- do not need to account for "specials" field. Clarification coming on how to handle during migration
- approval granted to move forward with multiple images on articles for a gallery feature
- Do not need apple news
- Achievement category - not needed, will migrate as tags

**Comment by cory-skeers** [comment]
Followup work will continue in #5474 and related issues; rest of the custom fields should be able to be handled via migration mappings.
