### ISSUE TITLE
Deprovison printmail.businsvc.uiowa.edu

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#549]
**UPDATE:** We provisioned this site before getting Hostmaster's blessing, which we did not get. Deprovision.

**Comment by ethanstjohn** [comment]
Blocked until given an SSL cert

**Comment by ethanstjohn** [comment]
Then it needs a prod domain and user added.

**Comment by ethanstjohn** [comment]
https://github.com/uiowa/uiowa/issues/554

**Comment by joewhitsitt** [comment]
SSL is done. No longer blocked

**Comment by joewhitsitt** [comment]
Hostmaster doesn't like businsvc. Waiting to hear back from customer about other options. Blocked and most likely will become a deprovision task..

**Comment by joewhitsitt** [comment]
See description. This has changed from a provision to deprovision.
