### ISSUE TITLE
Ability to control summary for events teaser

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5503]
# Story

As a College of Education event admin, I would like the ability to add a summary to events in content.uiowa.edu and have those summaries used as the teaser text on my website so that I have more control over what is output on event teasers.

# Proposed solution

- [x] Communicate in events-calendar Slack that we will be adding the summary option in Content Hub and making it available in the APIs.
- [x] Create summary field above description that is plain text and has help text.
- [x] Add summary to APIs, keeping description in the APIs as it is currently
- [x] Pull in summary as teaser in uiowa_events if exists otherwise fall back to what is currently being displayed.
- [x] css change to make sure hide descriptions continues to work and hides summary.
- [x] Let Chris C. view and approve the help text, etc. before rolling out.
- [x] communicate that the summary field is available in events-calendar Slack and ping Jeremy Dombrock, Andrew Rinner and Raaj in CSI and Chris Clair so he can communicate with event unit admins

**Comment by joewhitsitt** [comment]
In terms of the API task, the new field content will be added to `_return_event_for_api` within modules/custom/content_hub_core/inc/content_hub_core.data_feeds.inc and `_event_sync` within modules/custom/content_hub_core/inc/content_hub_core.event_sync.inc **if the CSI team is ready for it**

Not sure if extra stuff in _event_sync will mess with their setup.

In terms of the teaser, `docroot/modules/custom/sitenow_events/includes/sitenow_events.teaser.inc` should be updated where the current event description is being truncated/cleaned up. If placed, there, no CSS work should be necessary to show or hide it with current functionality.

**Comment by bspeare** [comment]
For the "Communicate with CSI App devs" task, is there a specific contact person for that?  Are we waiting for an "OK" from that group before proceeding to the next step or are we just making our work visible?

**Comment by briand44** [comment]
>For the "Communicate with CSI App devs" task, is there a specific contact person for that? Are we waiting for an "OK" from that group before proceeding to the next step or are we just making our work visible?

Just making our work visible. I already communicated with Jeremy Dombrock (CSI app dev) and Chris Clair to make this visible. I updated the proposed solution to just mention it in Slack and again once it is available. This is just to make others aware we will be doing this if they want to take advantage and a chance for them to chime in if for some reason adding an additional field in the API will cause breaking changes.

**Comment by bspeare** [comment]
I'm going to try to start on this while Joe is still around in case we have some questions.

**Comment by bspeare** [comment]
@joewhitsitt When you say add to `content_hub_core.event_sync.inc` “**if the CSI team is ready for it**”.   Are they ready for it or do we need to get clarification before adding?

**Comment by joewhitsitt** [comment]
@briand44 has been in contact with Jeremy Dombrock and can let him know when it is DEV for them to test

**Comment by briand44** [comment]
I let the CSI Java team know this is available in dev and to verify it won't cause breaking changes to events.uiowa.edu.

**Comment by bspeare** [comment]
Should we truncate this at 500 like we are doing for the description?

**Comment by briand44** [comment]
>Should we truncate this at 500 like we are doing for the description?

On display?? I don't think so... If we wanted to limit the characters we should do it on content hub.

**Comment by briand44** [comment]
Well, maybe not... Since this field could be used elsewhere, maybe we wouldn't want to limit it there. I say leave it all as is until it becomes an issue.

**Comment by joewhitsitt** [comment]
>I say leave it all as is until it becomes an issue.

I think I agree. Generally, the summary in drupal is untouched and is often the override to a truncated description. If it does become an issue, I think we should restrict it on content hub using maxlength js or something so the editor can adjust it before save and not be unknowingly cut off on different websites based on the implementation.
