### ISSUE TITLE
SSL certs for uiowa03

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#5505]
# Certs for uiowa03

- *.its.uiowa.edu / its.uiowa.edu
- svp.uiowa.edu
- bijou.uiowa.edu 
- scope.uiowa.edu 
- dancemarathon.uiowa.edu 
- lectures.uiowa.edu 
- offcampus.uiowa.edu
- archaeology.uiowa.edu

**Comment by bspeare** [comment]
I have updated this issue to be a general issue for new certs needed for uiowa03.

**Comment by briand44** [comment]
This is complete
