### ISSUE TITLE
As a SiteNow editor, I can see the page title and featured image "stacked" for mobile

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#5507]
# Story

As a Iowa Now editor, I can see the page title and featured image "stacked" for mobile so that the page title and featured image have better visibility. 

Currently, article titles get a bit lengthy on mobile.   

<img width="496" alt="Screen Shot 2022-08-01 at 11 15 43 AM" src="https://user-images.githubusercontent.com/1036433/182194717-cde1df8b-ffdc-4a17-98f4-c01fe61824d2.png">

# Proposed solution

<img width="606" alt="Screen Shot 2022-08-01 at 11 34 00 AM" src="https://user-images.githubusercontent.com/1036433/182198949-8b9f4938-29ae-460d-8b81-0bb3c6a29259.png">

Implement the `banner--stacked` class for https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/templates/layouts/layout--onecol--background.html.twig. 
- https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/scss/layouts/onecol--background.scss

Revisit styles using the `page-title` class:

- https://github.com/uiowa/uiowa/blob/09ed2ad1c947325ccd3184dcf1a4565a1296baa7/docroot/themes/custom/uids_base/scss/components/banner.scss
- https://github.com/uiowa/uiowa/blob/09ed2ad1c947325ccd3184dcf1a4565a1296baa7/docroot/themes/custom/uids_base/scss/components/typography/headings.scss

Revisit breadcrumb colors:
- https://github.com/uiowa/uiowa/blob/09ed2ad1c947325ccd3184dcf1a4565a1296baa7/docroot/themes/custom/uids_base/scss/layouts/onecol--background.scss#L44-L50

**Comment by joewhitsitt** [comment]
Not a direct intersection, but something to keep in mind when coming up with a solution: https://github.com/uiowa/uiowa/issues/3561 (article captions)
