### ISSUE TITLE
Remove field_uiowa_events_past from v3 events block

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#5518]
# Reference

https://github.com/uiowa/uiowa/pull/5497/files#diff-22455fd1cfa159b58a0289784a91064192c27738f06b23e252be3a46271afb4cR857-R861

# Proposed Solution

- [ ] Remove field/data from events block/db.
- [ ] Remove logic from layout_builder_custom module and sitenow_events preprocess block.
- [ ] Make sure sitenow_events_paragraph (v2) past functionality is not affected.

# Blocked

- Blocked until https://github.com/uiowa/uiowa/pull/5497 is merged/deployed.

**Comment by briand44** [comment]
Depending on how v2 is working, this may need an update hook and/or possible off hours deployment.

**Comment by joewhitsitt** [comment]
The removal of this block content field shouldn't affect the separate paragraph field used for v2. That was just a "be aware" checkbox.

**Comment by cory-skeers** [comment]
> * Remove logic from layout_builder_custom module and sitenow_events preprocess block.

Was this a general comment, or did you have specific code in mind? I found/removed a bit from layout_builder_custom, but didn't see anything remaining in sitenow_events, and wanted to double check that.

**Comment by joewhitsitt** [comment]
General comment to make sure we do a search. Thanks
