### ISSUE TITLE
Update mglaman/drupal-check

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#5523]
Making a note that this PR is going to require extra work and testing: #5324. This is because the new version of the dependency changes a setting that introduces a lot more deprecation errors. Each of those errors will need to be fixed and we'll need to test that the corresponding functionality still works.

_Originally posted by @pyrello in https://github.com/uiowa/uiowa/issues/5438#issuecomment-1189153592_

**Comment by pyrello** [comment]
Duplicate of #5467

**Comment by joewhitsitt** [comment]
oops and thx
