### ISSUE TITLE
Article photo gallery

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5524]
As a sitenow editor, I would like to be able to add multiple images to an article and display them in an image gallery so that visitors can easily navigate all related photos without having to go to a separate page.

# Proposed Solution

- [ ] Create another image field in addition to the featured image that allows unlimited number of images
- [ ] Output the images below the article body using existing gallery styles with a link to the anchor (https://github.com/uiowa/uiowa/issues/5524#issuecomment-1203211250).
  - Use either these styles (https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/scss/components/image-gallery-block.scss#L12-L35) and refactor to use a more generalized class name
  - Or use https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/scss/components/grid.scss#L58-L67
- [ ] Get feedback on placement

**Comment by briand44** [comment]
Separate image field on articles to support image gallery

**Comment by briand44** [comment]
Larger thumbnail gallery at the bottom with a link to the anchor at the top would be ideal. We'll want to get feedback on placement from Iowa Now as well as community during demo.

**Comment by bspeare** [comment]
Aspect ratio choice would be nice to have with this: https://github.com/uiowa/uiowa/issues/5386

**Comment by bspeare** [comment]
Another aspect of the Iowa Now gallery design is that it is designed as if the thumbnails control a carousel.   The only thing missing are left and right arrows which a user might expect to show up on hover. 

Screenshot from https://now.uiowa.edu/2022/03/nachte-raho-makes-thrilling-return-hancher-auditorium. 

<img width="777" alt="Screen Shot 2022-08-02 at 1 33 19 PM" src="https://user-images.githubusercontent.com/1036433/182448472-4b39c4fe-8c66-4bdd-b2a4-99b04d3564c1.png">

Example carousel UX from https://splidejs.com/tutorials/thumbnail-carousel/. 

<img width="746" alt="Screen Shot 2022-08-02 at 1 33 44 PM" src="https://user-images.githubusercontent.com/1036433/182448509-0856ef94-76b6-4356-b131-b13d32864c9a.png">

Moving the thumbnails further away from the featured image would help clear up the distinction between the featured image and photoswipe gallery.

**Comment by bspeare** [comment]
Added a quick mockup on how https://github.com/uiowa/uiowa/issues/5524#issuecomment-1203072116 could work https://now.prod.drupal.uiowa.edu/community-celebrates-iowa-city-pride-2022.

**Comment by joewhitsitt** [comment]
I believe IISC, SPPA, HR, Admissions, Now are all splitting Articles in some way and will need to be tested against.
