### ISSUE TITLE
admissions.uiowa.edu search showing results for grad.admissions.uiowa.edu

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5525]
When searching admissions.uiowa.edu, results shown include pages from grad.admissions.uiowa.edu.

To reproduce: https://admissions.uiowa.edu/search?terms=cost%20and%20funding

Search settings are using default CSE ID but "limit custom search to this site" is checked.

**Comment by briand44** [comment]
Possibly test to see if other domains/subdomains experience same results. 

Scott mentioned when searching grad.admissions.uiowa.edu correct results were being displayed not results including admissions.uiowa.edu.

**Comment by makurj** [comment]
I'd like to pair on this.

**Comment by bspeare** [comment]
It looks like the default behavior is to show subdomains if "limit custom search to this site" is checked. 

- https://education.uiowa.edu/search?terms=wild - shows wild.education.uiowa.edu
- https://admissions.uiowa.edu/search?terms=cost - shows blog.admissions.uiowa.edu

grad.admissions.uiowa.edu displays the correct results because there is not a further subdomain to search. 

What else do we want to do here?

**Comment by briand44** [comment]
I wonder if that was by design or an oversight? In my mind "limit search to this site" should limit the results only to a single site. If they want to include additional domains in their search results, we would need to set up a separate cse id and include the subdomains or additional domains that should be included in those results. Not sure how this fits with our number of cse id's etc. so may be worth a conversation.

**Comment by bspeare** [comment]
@briand44 that makes sense.  Should we add a blocked and question/conversation needed labels?

**Comment by briand44** [comment]
That's fine, hoping it is a conversation that we can have in standup but if more time is needed I can schedule a separate conversation.

**Comment by joewhitsitt** [comment]
I think it works to a degree
https://developers.google.com/custom-search/docs/element#supported_attributes

We may need to update to prefix to match the following as noted here: https://support.google.com/programmable-search/answer/12397162

| Pattern           | Description                                                    | Matches                                                 | Does not match                                         |
| ----------------- | -------------------------------------------------------------- | ------------------------------------------------------- | ---------------------------------------- |
| www.example.com/* | Matches all URLs beginning with www.example.com or example.com | www.example.com www.example.com/stamps example.com/stamps | host.example.com/host.example.com/stamps |

**Comment by joewhitsitt** [comment]
Going to see what the `as_sitesearch` value is for admissions to see if we need to adjust.

**Comment by joewhitsitt** [comment]
It is added as `admissions.uiowa.edu/`

Based on the docs above (though they are for different things) I would think this would need to be switched to `www.admissions.uiowa.edu/*` to get the proper search results.

I propose creating a new setting to capture an override, deploy that out and see if that affects things. Either that or use the admissions split to try and temporarily manipulate this value for testing in PROD.

**Comment by joewhitsitt** [comment]
@briand44 not sure if our schedules will align today. did you have thoughts about how to move forward?

**Comment by briand44** [comment]
Not specifically, fine with you doing you if I can peak at it at some point. I would think we could test this without deploying to prod though. I would assume there is a way to ping the API and see what results return.

**Comment by joewhitsitt** [comment]
Brian and I were able to hardcode a pattern to test this locally and `www.admissions.uiowa.edu/*` was not the solution. Going to do some more digging on what the pattern should be

**Comment by joewhitsitt** [comment]
I've tried several patterns with no success. The documentation related to this attribute is pretty sparse. I think this is going to require a custom CSE ID.

**Comment by briand44** [comment]
Would a custom CSE ID even work? What patterns did you try?

**Comment by joewhitsitt** [comment]
I temporarily repurposed non-profit 03 to test and this seemed to work:

Sites to include: `admissions.uiowa.edu/*`
Sites to exclude: `grad.admissions.uiowa.edu/*`

Looks like we are capped on IDs though. Creating a new one defaults to ads. For new ones, it sounds like we would need to go through a process of adding a non-profit approved email address. Not sure this would be its-web but maybe a more campus-wide one. https://support.google.com/programmable-search/answer/4542102?hl=en#zippy=%2Cto-register-as-a-nonprofit

**Comment by briand44** [comment]
Yeah, just noticed you could exclude sites. Noticed international has a custom id but being used to show results for subdomains. It may not be needed.

**Comment by briand44** [comment]
Doesn't look like international is even using it

**Comment by joewhitsitt** [comment]
Yeah, I think we can review `international`, `now` at a later date. We do have unused ones for this issue.

**Comment by joewhitsitt** [comment]
not sure if it is worth reaching out to Scott on whether they had an ID previously that we could use

**Comment by joewhitsitt** [comment]
Scott said they used drupal search previously. Moving forward with repurposing non-profit 03 for admissions which fixes the issue:
<img width="1012" alt="Screen Shot 2022-08-18 at 10 03 14 AM" src="https://user-images.githubusercontent.com/4663676/185428911-eea10f5c-1d82-4619-a7e5-5d1daf41c3e4.png">

**Comment by joewhitsitt** [comment]
This is done. I will open a separate issue to audit/clean up existing buckets

**Comment by joewhitsitt** [comment]
Created https://github.com/uiowa/uiowa/issues/5590
