### ISSUE TITLE
As a prospective student, I can view the 2plus2 page content with a clear visual hierarchy and clear document outline

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#5528]
# Story

As a prospective student, I can view the 2plus2 page content with a clear visual hierarchy and document outline

Example page where labels and bold font usage within the content areas are indistinguishable: https://admissions.uiowa.edu/academics/2plus2/economics-iowa-valley-community-college-district

# Proposed solution

Update field labels on Majors content type to use headings.

**Comment by briand44** [comment]
likely these will be `<h2>` but want to make sure that heading structure is correct.
