### ISSUE TITLE
Add very limited HTML markup options to blockquote block `field_uiowa_quote_content` and `field_uiowa_quote_footer` fields

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#5536]
# Story

As a content editor I want to be able to italicize or bold text in the blockquote content or source fields so that have more control over how they look.

This is a request from UI Press.

# Proposed solution

- Maybe we need to consider a new text format in between plain text and minimal to add just the most basic styling options.
- Implement this new option on both fields in the blockquote block type `admin/structure/block/block-content/manage/uiowa_quote/fields`

**Comment by bspeare** [comment]
Bold and italic seem like good starting points.  We could also use this on the Statistic block for the "Excerpt" and "Content" fields.

**Comment by joewhitsitt** [comment]
But the bigger question is what do we name it?! Serious suggestions this time:

- `basic`
- `simple`

**Comment by makurj** [comment]
I vote for "basic".

**Comment by briand44** [comment]
"basic" it is!

**Comment by makurj** [comment]
I'd like to pair on this.

**Comment by bspeare** [comment]
With this new text format, do we want/need to adjust the footer styles in `uids`: https://github.com/uiowa/uids/blob/3.x/src/components/blockquote/blockquote.scss#L56?    Previously, we were setting the entire footer in a bold font weight.  Now that we are offering the ability to add bold or italics in the text editor do we want to make that change?

<img width="1808" alt="Screen Shot 2022-08-15 at 2 03 48 PM" src="https://user-images.githubusercontent.com/1036433/184699906-b39853e3-fb46-4c2f-8f32-04d4d3041b32.png">
