### ISSUE TITLE
Revisit custom code related to menu_per_role

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#5537]
# Story

As a developer I can confirm that recent menu_per_role configuration settings don't replace our custom code, however, if settings do provide the functionality we were providing, maybe switch it from code to settings

# Proposed solution

- [x] Audit the settings (admin/config/system/menu_per_role) with what what we are doing in code.

https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/uiowa_core/uiowa_core.module#L341-L371

**Comment by joewhitsitt** [comment]
To clarify, the changes in https://github.com/uiowa/uiowa/pull/5527 don't seem to affect our current functionality.

**Comment by bspeare** [comment]
The settings in `admin/config/system/menu_per_role` look identical from 1.3 to 1.4.

I looked through the changes in https://github.com/uiowa/uiowa/pull/5527 and it appears that we still need the custom code provided by https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/uiowa_core/uiowa_core.module#L341-L371.   I've listed an audit of the custom functionality below. 

- [x] Hiding roles able to see the menu link functionality
- [x] Hiding all roles except Anonymous for "Roles not able see the menu link"
- [x] Adding a message to the top of the screen alerting any user to the presence of a hidden link
- [x] Only allowing admins to hide menu items

**Comment by joewhitsitt** [comment]
Thanks for doing this. I'll admit when I was running this module update, I didn't do a diff between 1.3 and 1.4 and instead noticed the configuration form but didn't look too much into it beyond test that our current code was still firing. I created this issue to make sure we weren't providing noodle code where it wasn't needed. I think this can be closed.

**Comment by bspeare** [comment]
It was nice to get a refresh on all the custom work we did to make this module work better.
