### ISSUE TITLE
Specifying language on News articles

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#5543]
<meta http-equiv="content-language" content="en"/>

is the wrong language on  

https://diversity.uiowa.edu/news/2022/06/isandra-martinez-marrero-nombrada-como-la-nueva-directora-de-participacion-cultural-y

## Proposed Solution

- Adjust the `Access Content Language in Advanced` permission which should make this available on a piece by piece basis. Default should be english.

**Comment by briand44** [comment]
Confirmed this is part of Metatag and Joe is referring to one of the Metatag extended permissions.

**Comment by briand44** [comment]
@mjoneill I assume this is a service wide addition we want to make and not just for the site mentioned in the Issue Summary? Also, the title specifies this change is only for articles, is that accurate?

**Comment by mjoneill** [comment]
> @mjoneill I assume this is a service wide addition we want to make and not just for the site mentioned in the Issue Summary?

Yes.  Platform-wide (unless there's something about it that gives you pause)

**Comment by mjoneill** [comment]
> @mjoneill the title specifies this change is only for articles, is that accurate?

This slice/ask is for articles, yes.  

I would expect that the ability to toggle this on pages is likely coming next...though no telling when it is coming or who will request it yet.  

If it makes sense to do it for basic pages, articles, and/or other content types...I'm game.  I don't want to step into that by default if that's a (non) split that's hard to implement.

**Comment by briand44** [comment]
> Yes. Platform-wide (unless there's something about it that gives you pause)

Nope, that was my thought as well just wanting to clarify.

**Comment by briand44** [comment]
Add permission, set global default "En", confirm available to webmasters in appropriate places. Ok, to make it available to other content types besides articles if less effort.

**Comment by joewhitsitt** [comment]
The work in https://github.com/uiowa/uiowa/pull/5684 controls `<meta http-equiv="content-language" content="en">` on a per content basis and does not change the `<html lang="en"...`

Looks like our idea missed the mark here as this method has been deprecated and will later be removed: https://www.w3.org/International/questions/qa-http-and-lang#meta_summary
https://www.drupal.org/project/metatag/issues/3217263

@mjoneill is this the attribute that you wanted set? Otherwise, we might need to revisit the solution here. Is there a lighter weight solution besides the WhitmanWeb approach? New field on the content type that preprocess_html that unsets and sets the attribute?

```php
/**
 * Implements hook_preprocess_HOOK().
 */
function [MODULE|THEME]_preprocess_html(&$variables) {
  /** @var \Drupal\Core\Template\Attribute $html_attribute */
  $html_attribute = $variables['html_attributes'];
  if ($html_attribute->hasAttribute("lang")) {
    $html_attribute->removeAttribute('lang');
    $html_attribute->setAttribute('lang', 'de');
  }
}
```
https://drupal.stackexchange.com/a/307531

**Comment by joewhitsitt** [comment]
Moving forward with this for now: https://github.com/uiowa/uiowa/pull/5684#pullrequestreview-1107654882
