### ISSUE TITLE
cbe.engineering.uiowa.edu move to engineering.uiowa.edu

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5547]
# Story

As an owner of cbe.engineering.uiowa.edu, I would like to move this site to engineering.uiowa.edu and have all traffic going to cbe.engineering.uiowa.edu be redirected to engineering.uiowa.edu/cbe so visitors can find relevant information they are looking for.

# Additional Info
Currently planning to launch Oct 12th.

# Proposed solution

- [x] Request redirect be put in place on Vulture to redirect cbe.engineering.uiowa.edu to engineering.uiowa.edu/cbe - this should be tested once in place by updating local hosts file.
- [x] Request TTL be lowered to 5 min for cbe.engineering.uiowa.edu
---Launch Day---
- [x] Setup engineeringcbe.prod.drupal.uiowa.edu on 703 so that the site can be available to our partners at Engineering temporarily in case any content was missed.
- [x] Remove Drupal redirect for engineering.uiowa.edu/cbe (currently redirects to cbe.engineering.uiowa.edu)
- [x] Update DNS to point to vulture at least 24 hrs after TTL has been lowered and Engineering is ready for switch
- [x] Update robots.txt to disallow all on engineeringcbe.prod.drupal.uiowa.edu.
- [x] Add reminder to its-web to check in with Engineering (Hailey, Jason) in one month to see if D7 site can be removed.
---Post Launch Day---
- [x] Request TTL be set back to default once all is well.
- [x] Profit!

**Comment by briand44** [comment]
Added blocked label because there is still content work to be done and until we know specific dates when they are wanting to make the switch. Sounds like by the end of August.

**Comment by briand44** [comment]
emails sent to create redirect and lower TTL. Will update the issue once I hear back.

**Comment by briand44** [comment]
TTL has been lowered. Redirect in place but I haven't tested yet.

**Comment by briand44** [comment]
Tested redirect and it is working.

**Comment by joewhitsitt** [comment]
Brian in Slack:

>The plan is for DNS to be updated at 1pm so we will want to setup the .prod domain prior to the DNS change and remove the Drupal url redirect. Once DNS is updated then just update robots.txt to deny all on the old site and setup the reminder. I will forward the email thread to its-web.

**Comment by joewhitsitt** [comment]
Looks like the /cbe content was published yesterday which takes precedence over the redirect. I removed the redirect.

No update about the DNS change since this morning's email so still assuming a 1PM-ish switch.

**Comment by joewhitsitt** [comment]
engineeringcbe prod domain has been added and robots has been edited

**Comment by joewhitsitt** [comment]
Seems to have worked out nicely. Added a calendar reminder. Waiting to up the TTL.

**Comment by briand44** [comment]
Thank you! Can you email Hailey and let her know the url of the old site if you haven't already?

**Comment by joewhitsitt** [comment]
I blocked it again because of the "post-launch day TTL increase"

**Comment by joewhitsitt** [comment]
Requested the TTL be raised. Closing.
