### ISSUE TITLE
SiteNow updates news article - August

### ISSUE THREAD

**Issue by cory-skeers** [uiowa/uiowa#5548]
## Issue/Solution ##
Provide a "release notes" type article of finished/done features/updates and publish to website, then send out dispatch email.

- [x] Create draft and update the parking lot card with an edit link
- [x] Add "release notes" covering the month of v2/v3 default profile enhancements and webmaster/edit visible bug fixes.
  * See the previous month's article as an example.
  * Bullet points from demo stories slide per week: https://drive.google.com/drive/folders/1EehKUjxCbakaB9FchrGhAbaxuRbqyDGW?usp=sharing..
  * Check recent "done" and "archive" items and finished docs tasks.
  * Take notes during sprint demo presentation.
- [ ] Get at least one team member to look over the draft before publishing.
- [ ] Since the draft was started earlier, adjust the publish date/time, publish, get the link to the article.
- [ ] Dispatch email with link to article. (To get access, send an email to dispatch-support@uiowa.edu to have the account provisioned. Provide your hawkid and mention the CSI:drupal group)
  * Modify SiteNow Announcements Template (tweak opening line, update the article link, any other editorial adjustments)
  * Create new communication off SiteNow Announcements campaign
    * Use SiteNow Announcements population, template, suppression list, bypass approval.
    * When scheduling, check the "archive" option so that there is an RSS instance we can use in the future. I don't think this can be done after the fact.
- [ ] Turn off Dispatch "test mode" to send out email. 
- [ ] Turn on Dispatch "test mode" after email is successfully sent.
- [ ] Take a moment to check dispatch and google analytics on whether these articles are being read.
- [ ] Create the next months's issue and copy all this bullet list into it, removing the checked boxes if any.

**Comment by cory-skeers** [comment]
https://sitenow.uiowa.edu/news/2022/08/updates-august

**Comment by briand44** [comment]
I would like to huddle on the Dispatch side of this so I can be more comfortable and possibly document how to send to SiteNow announcements in the case of an outage.

**Comment by cory-skeers** [comment]
Release notes have been updated based on demo deck stories, and an intro has been added: https://sitenow.uiowa.edu/news/2022/08/updates-august

I haven't checked the archived done column for possible other stories/bug fixes, and there are likely some notable launches that could be added.

**Comment by bspeare** [comment]
I think this looks good.  It has a great intro and the three site launches listed are great.  I added "https://csi.its.uiowa.edu" after finding that they launched in August.  Should we send this out today?

**Comment by bspeare** [comment]
This is complete.

**Comment by briand44** [comment]
>Take a moment to check dispatch and google analytics on whether these articles are being read.

Did we do this??

**Comment by bspeare** [comment]
@briand44 I forgot about that part.  Let me tackle that this afternoon!

**Comment by bspeare** [comment]
August Dispatch analytics:
<img width="1486" alt="Screen Shot 2022-09-07 at 2 19 36 PM" src="https://user-images.githubusercontent.com/1036433/188959853-5f84b609-470a-4f6b-8737-b0e98ddf50e5.png">


July Dispatch analytics:
<img width="1262" alt="Screen Shot 2022-09-07 at 2 18 14 PM" src="https://user-images.githubusercontent.com/1036433/188959601-2840e93e-5d5b-440c-ad27-ceef570c585b.png">

**Comment by joewhitsitt** [comment]
7-9% clicked? doesn't seem very high. okay, how many of the team are subscribed and are the ones clicking it?!

**Comment by bspeare** [comment]
GA since Jan 01. 2021:

<img width="1952" alt="Screen Shot 2022-09-07 at 2 34 12 PM" src="https://user-images.githubusercontent.com/1036433/188961977-29346613-1934-4cca-9ad8-1cdf1e7b5fc3.png">

Perhaps the GA suggests that we have a few popular months like December/April/March and we shift to 2-3 times a year?
