### ISSUE TITLE
Image block documentation

### ISSUE THREAD

**Issue by GaryRidgway** [uiowa/uiowa#5553]
Need to add documentation for the image block to sitenow docs

**Comment by GaryRidgway** [comment]
How is this for the wording? https://sitenow.uiowa.edu/node/126/latest

**Comment by GaryRidgway** [comment]
How does this feel for wording?
https://sitenow.uiowa.edu/image-block

**Comment by cory-skeers** [comment]
Haven't checked if all the blocks' docs have this section, but it looks like we'd been adding this at the bottom:

"Block Restrictions
The collection block is available in the following section layouts:

One column
Two column
Three column
Four column
Page w/ left sidebar"

**Comment by cory-skeers** [comment]
I took a stab at updating the "Link" description that I'd thought was kind of confusing, if you wouldn't mind checking/editing my edit!

Edit: After that, I think this looks good to publish 👍

**Comment by GaryRidgway** [comment]
I've added your suggestions and published it, thanks Cory!
