### ISSUE TITLE
Useful `blt` commands for/during a deployment

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#5557]
# Deploy release

`blt ugd` (assumes new release has been created and is available on each application (post Travis))

## Clear cache during a deployment

`drush @container.prod ssh`
`cd ..`
`./vendor/bin/blt ume cache:rebuild`

## Run config imports 
Do we do this during a deployment or only if we noticed that it failed on the docroot?

`drush @container.prod ssh`
`cd ..`
`./vendor/bin/blt ume cr && ./vendor/bin/blt ume cim`

### What's the difference between `ume` (uiowa:multisite:execute) and `umi` (uiowa:multisite:install )?

- When would we need to use each of these?
  - The file is at https://github.com/uiowa/uiowa/blob/main/blt/src/Blt/Plugin/Commands/MultisiteCommands.php

### When to re-run a release?

- After re-importing config?
  - Go to http://cloud.acquia.com/
  - Click on the code draggable for prod and select the same tag to run it again.
- There are instances where a deployment is only running for the first half of the list. Re-triggering the code switch (same tag) will still run through the a-z list but get further through the list.

**Comment by pyrello** [comment]
`ume` is a command for executing a drush command against every site on the application. You run it as `ume drush status`, which would result in a status output for every site.

`umi` is a command for installing any site that has not already been installed on an application.

**Comment by bspeare** [comment]
Thanks @joewhitsitt and @pyrello for your answers! Moved this to https://wiki.uiowa.edu/display/drupaldev/Useful+blt+commands+for+or+during+a+deployment for now.
