### ISSUE TITLE
Run campus-critical websites first during a deployment

### ISSUE THREAD

**Issue by mjoneill** [uiowa/uiowa#5558]
# Story

As a web team, we can have a mechanism whereby campus-critical websites are the first to recover during a deployment issue like we experienced on 8/5/22.

# Additional Comments

Outages/problems will happen.  What can we do to lessen the impact/speed up recovery when/if they DO happen? 

Probably a number of different things we _could_ do here.  Let's figure out something that would make a material difference.

# Proposed Solution

- [ ] Define list of campus critical websites - This should include colleges, public safety, emergency, admissions, uiowa.edu. Want to keep this list short with specific reasoning, so we don't have to deal with everyone wanting to be on this list.
- [ ] Store ordered list in config and then add those to the beginning of the site list so they run first during deployment similar to how we are currently handling uiowa.edu in https://github.com/uiowa/uiowa/blob/c0b937b6123e3b88498c1b9fb6322c8dcc8b0cb3/blt/src/Blt/Plugin/Commands/ReplaceCommands.php#L29-L35

**Comment by mjoneill** [comment]
Capturing some ideas I heard, voiced, and/or that came up on the team ORID.

- Have a way to establish a custom order for sites to be updated so that we aren't reliant on alpha-sort
- Move all campus-critical sites to one of our extra/empty application servers
- Lessen the number/better balance the number of sites across our application servers
- Manually trigger db updates/config imports for high profile sites if this situation happens again
- Active intervention during an outage to "speed up" recovery of specific sites.  (BD comment?)
Ideas/discuss in comments...
-- Learn how to clear caches, etc during deployment and run other processes that will bring sites back up

**Comment by joewhitsitt** [comment]
Moving original comment here to https://github.com/uiowa/uiowa/issues/5559#issuecomment-1216787111

**Comment by joewhitsitt** [comment]
We should probably define what campus-critical websites are to understand how big of a list we are dealing with. Some strategies might lend themselves better to a short list versus a large list.

**Comment by briand44** [comment]
Agree we should have a list of these. We will need to define these better but something to start with would include colleges, public safety, emergency, admissions, uiowa.edu

**Comment by pyrello** [comment]
In a quick perusal of the potentially relevant docs for BLT, I'm not seeing anything that suggests that we can set the site order through configuration
- https://docs.acquia.com/blt/tech-architect/multisite/
- https://docs.acquia.com/blt/extending-blt/
- https://docs.acquia.com/blt/tech-architect/deploy/

Probably we'll want to ask our account rep or the BLT maintainers if they recommend anything that would allow this.

**Comment by pyrello** [comment]
Here is where we are already doing this with uiowa.edu: https://github.com/uiowa/uiowa/blob/c0b937b6123e3b88498c1b9fb6322c8dcc8b0cb3/blt/src/Blt/Plugin/Commands/ReplaceCommands.php#L29-L35

**Comment by briand44** [comment]
Plan would be to create the list of high profile sites, store that list in config (Sean specifying) and then handle those similarly to how uiowa.edu is already being handled in ^^

**Comment by pyrello** [comment]
We could add some more custom configuration to this file to set the sites that are being prioritized: https://github.com/uiowa/uiowa/blob/c0b937b6123e3b88498c1b9fb6322c8dcc8b0cb3/blt/blt.yml#L70-L76

**Comment by briand44** [comment]
We want to keep the list of high profile sites short with specific reasoning, so we don't have to deal with everyone wanting to be on this list.

**Comment by briand44** [comment]
In the meantime we can run manual commands or in the case that only Intranet's are affected we have the option to manually run config imports, updb's, cache clears, etc.

**Comment by joewhitsitt** [comment]
If we are keeping a list, we should establish workflow to make sure it is up-to-date to avoid, the "oh, we forgot to add you to the list"

**Comment by mjoneill** [comment]
While all sites are important and need to come back as quickly as possible, these are the ones that will be processed first:
- https://emergency.uiowa.edu/ * v1
- https://police.uiowa.edu/ * v1
- https://uiowa.edu/
- https://admissions.uiowa.edu/
- https://grad.admissions.uiowa.edu/
- https://medicine.uiowa.edu/ * **
- https://dentistry.uiowa.edu/
- https://education.uiowa.edu/
- https://engineering.uiowa.edu/
- https://law.uiowa.edu/ * v2
- https://clas.uiowa.edu/ * D7
- https://nursing.uiowa.edu/
- https://pharmacy.uiowa.edu/
- https://www.public-health.uiowa.edu/ * **
- https://tippie.uiowa.edu/
- https://grad.uiowa.edu/
- https://uc.uiowa.edu/ * v1

For every site we add there is a tradeoff. I'm comfortable starting here and learning from it. 

'* indicates non SNv3.

** indicates a site not hosted by us

**Comment by briand44** [comment]
https://www.public-health.uiowa.edu/ * and https://medicine.uiowa.edu/ * are not sites we manage/host

clas.uiowa.edu, emergency.uiowa.edu, police.uiowa.edu and uc.uiowa.edu are D7 sites at the moment.

**Comment by joewhitsitt** [comment]
I had mentioned https://italymba.tippie.uiowa.edu/ on the other issues based on their business hours are during our AM deployment hours. Not sure if that is enough to make the list of "campus-critical" though

**Comment by mjoneill** [comment]
> https://www.public-health.uiowa.edu/ * and https://medicine.uiowa.edu/ * are not sites we manage/host

Clarified.

**Comment by pyrello** [comment]
For my part, I think this list should be as small as possible. To that end, I think it should exclude sites that wouldn't be considered critical for operations. In my mind that means that we would be excluding sites that are high visibility but don't serve an emergency-related purpose or are our main conversion funnel. To that end, I don't think that grad.uiowa.edu should be on this list or any site listed after the first 5.

**Comment by pyrello** [comment]
I think we should implement the change for the first 5 sites on the list and then add the rest of them later when we are clear that there is no noticeable performance hit for adding them.

**Comment by cory-skeers** [comment]
> I think we should implement the change for the first 5 sites on the list and then add the rest of them later when we are clear that there is no noticeable performance hit for adding them.

I like this approach. Even if there is a performance hit, as long as we are aware of what that hit is, I would be okay with making that risk/reward decision. Hesitant on adding a list of sites (as opposed to a few) without understanding that performance cost.

**Comment by mjoneill** [comment]
We are a university; it's a brand failure if college main sites are down for extended periods of time.  Optimization should be inclusive of the list above, but I have zero concerns if we want to start with 5 sites (or 3, or 7, or 2) before extending to the list as indicated above.

**Comment by mjoneill** [comment]
> https://italymba.tippie.uiowa.edu/

What makes this unique is that it is at the intersection of prospective student recruitment and business hours are central European time (which means they get lots of eyeballs if we schedule deployment with downtime overnight). 

I still think we need to solve for primary college sites first. . .

**Comment by pyrello** [comment]
> We are a university; it's a brand failure if college main sites are down for extended periods of time.

I don't think anyone disagrees with this. How long were these sites down the last time this happened?

We also discussed that if a deployment introduced regression that caused an outage that these sites would be down the longest because we don't have the ability to start a new deployment until the previous one has started. So, it is not just as simple as we add these sites to this list and then they automatically have the least downtime.

**Comment by mjoneill** [comment]
> How long were these sites down the last time this happened?

10:20AM - Tippie site DOWN alert
12:15PM - Tippie site UP alert

10:19AM - Education site DOWN alert
10:49AM - Education site UP alert

Colleges should be closer to Education (or better) than Tippie.

**Comment by cory-skeers** [comment]
> We are a university; it's a brand failure if college main sites are down for extended periods of time. Optimization should be inclusive of the list above, but I have zero concerns if we want to start with 5 sites (or 3, or 7, or 2) before extending to the list as indicated above.

I think my main concern here is that if the deployment costs for the list are too high, maybe we need a different approach to this (consider again options like moving these to a dedicated environment) or it might impact our general release schedule (eg account for added lead time for hotfixes). I'm not sure what "too high" would be, or even if it exists, but I'd love some sort of baseline of the impact this change would have.

On a similar note, we should make sure we have baselines ready for comparison before making this update so we can accurately compare.

**Comment by briand44** [comment]
Start with first 5 to make sure there is not any major performance issues or anything. Include v1 sites to test if having those in now causes any issues. Add rest of sites once we have less of a concern.

**Comment by joewhitsitt** [comment]
To answer the question about where `$this->getConfigValue('multisites');` is coming from.

>You have the option to explicitly define your multisites in blt/blt.yml by creating a multisites array. If you don’t manually define this variable, Acquia BLT will set it based on discovered multisite directories - https://docs.acquia.com/blt/tech-architect/multisite/

**Comment by pyrello** [comment]
Should this issue be re-opened for the second batch of sites after we collect some metrics?

Here are the ideas for measuring the impact of this change:
- Select release deployments for the past week and average them across all active applications. Generate a similar sample for the upcoming week. Compare the values before and after.
- Review RAM usage during the times that deployments have happened before and after the release of this update to see if any discernible differences emerge.

**Comment by briand44** [comment]
@pyrello I've added these additional issues as follow ups to this.
