### ISSUE TITLE
Automate and document D8 deprovision process

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#556]

**Comment by richardbporter** [comment]
1. Delete the domain(s).
  This takes the site "down" immediately with the AC 404.
2. Delete the database.
   Possibly make a backup, if we deem that necessary.
3. Delete the site directory.
4. Delete the related sites.php entires.
5. Delete the Drush aliases.
6. Delete the config directory.
7. ~~Delete files directory from each environment.~~
  This is potentially disastrous if done incorrectly.
8. Delete any related cron jobs.
  This would most likely only apply to custom sites.
9. ~~Deploy code as per usual.~~

Steps 1-6 could be automated in a BLT command.

**Comment by richardbporter** [comment]
Crossed out step 8. I don't think a production release has to be done just to delete site code. As long as it is merged into master, the next release is fine. Once the domain(s) is deleted, the site is gone for all intents and purposes.

**Comment by richardbporter** [comment]
Working on `sitenow:multisite:delete` command and adding README docs.

**Comment by richardbporter** [comment]
Forgot the config directory. Added to steps.

- [x] Delete printmail.businsvc.uiowa.edu config directory
