### ISSUE TITLE
Adjust intranet "Access denied" message

### ISSUE THREAD

**Issue by quamsta** [uiowa/uiowa#5563]
# Story

As a user of an intranet site, I'd like to see a friendlier message than "Access denied" when landing on an intranet homepage or other page that I use on a regular basis. Currently this is the message:

<img width="1358" alt="Screen Shot 2022-08-10 at 10 18 58 AM" src="https://user-images.githubusercontent.com/472923/183942278-6f798b83-eed5-45a4-8aa7-6c47d1475b6f.png">

I think it's a bit extreme to tell a user they've been denied access to a resource that presumably they're visiting on a regular basis and when they may not understand that they've been auto logged out or otherwise need to login for other reasons (switched browser, using a different machine).

Some alternatives to this "Access denied" message could be:

- Login required
- HawkID required
- This page requires a login

Open to suggestions though.

From this original intranet issue:

https://github.com/uiowa/uiowa/issues/4241#issuecomment-1006894018
> However, can the "Access Denied" page be a bit more friendly? It might be okay for someone stumbling on or entering an admin section they don't have access to, but seems harsh for an intranet environment.

# Proposed solution

**Comment by joewhitsitt** [comment]
Wasn't this addressed in https://github.com/uiowa/uiowa/pull/4854?

**Comment by bspeare** [comment]
@quamsta you can customize this screen at https://studentlifeconnect.prod.drupal.uiowa.edu/admin/config/sitenow/intranet.

**Comment by joewhitsitt** [comment]
Going to close this as this functionality already exists.

<img width="910" alt="Screen Shot 2022-08-16 at 12 57 09 PM" src="https://user-images.githubusercontent.com/4663676/184947161-06736380-bc8c-479b-b3b7-9f01f0fb9c13.png">
<img width="530" alt="Screen Shot 2022-08-16 at 12 56 54 PM" src="https://user-images.githubusercontent.com/4663676/184947166-8f000281-9b7a-4fdc-81dc-61ef0749f926.png">

**Comment by quamsta** [comment]
Thanks all, sorry, I just didn't know it was customizable
