### ISSUE TITLE
As a developer, I can reuse the image block gallery styles on other block components

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#5566]
# Story

As a developer, I can reuse the image block gallery styles on other block components using photoswipe. 

# Proposed solution

- Refactor https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/scss/components/image-gallery-block.scss#L12-L35 to use a reusable image gallery class. 
- Fix awkward flex layout spacing so that all thumbnails retain their aspect ratios.
- Consider including https://github.com/uiowa/uiowa/pull/5552#discussion_r940704613
- Refactor the work in https://github.com/uiowa/uiowa/pull/5552 to use the updated image gallery class. 
- Reconsider mobile experience. 

<img width="1352" alt="Screen Shot 2022-08-11 at 3 09 58 PM" src="https://user-images.githubusercontent.com/1036433/184233147-676a8464-bf5a-4a50-bae5-211b56ca1594.png">

**Comment by GaryRidgway** [comment]
I think this would be wonderful. I would really love to offer this in more places, and this abstraction should hopefully help with that.

**Comment by bspeare** [comment]
Related issue that could be part of the proposed solution https://github.com/uiowa/uiowa/issues/5386.
