### ISSUE TITLE
Support articles D7 vs D8 plan

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#557]
- [x] Launch D8 SiteNow site.
  - [x] Link to ITS Support Articles, labelled as "SiteNow 1" documentation.
- [x] Update SiteNow Standard stuff "SiteNow" link to "SiteNow 1"
- [ ] ~~Write articles and communication explaining the change/future.~~
- [x] Update InfoCenter overview with message about two flavors of Drupal and explain where the documentation for each resides. _See https://its.uiowa.edu/node/100028/draft_
- [x] Touch each D7 SiteNow support article:
  - [x] Add message at the top of the article that this pertains to SiteNow 1 sites and where they can find the SiteNow 2 docs. _@keeganjm1 is working on this_

**Comment by joewhitsitt** [comment]
SiteNow v1 and v2 logos are on the new site:
/media/301/edit
/media/302/edit

**Comment by joewhitsitt** [comment]
One issue with tagging D7 support articles is that it creates a category on the SiteNow support page within each standard site causing duplication among other things. Tagging is only really beneficial if we have v2 support articles. Gives us something to separate on.

**Comment by joewhitsitt** [comment]
Possible snippet to add to the top of each D7 support article:

>This support article pertains to the SiteNow v1 platform. Click here for SiteNow v2 documentation.

This is the only html that appears to work in our ITS WYSIWYG without being an inaccessible table...
```
<hr>
<p style="text-align: center;"><strong>This support article pertains to the SiteNow v1 platform. <a href="https://sitenow.uiowa.edu/documentation">Click here for SiteNow v2 documentation</a>.</strong></p>
<hr>
```

I did the first one: https://its.uiowa.edu/support/article/105165

**Comment by joewhitsitt** [comment]
I added a page on the current site so that we can start linking to https://sitenow.uiowa.edu/documentation before launch.

**Comment by joewhitsitt** [comment]
Thanks @keeganjm1 for working on those ITS website support articles. I finished up the rest of them.

**Comment by joewhitsitt** [comment]
<img width="1163" alt="Screen Shot 2019-10-08 at 12 13 08 PM" src="https://user-images.githubusercontent.com/4663676/66417306-4b242580-e9c5-11e9-8e38-9c5d9e8cafbe.png">
