### ISSUE TITLE
Support referenced content for articles

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5575]
As a SiteNow site editor creating an article, I would like to be able to choose existing related articles to display to site visitors so that they can more easily find similar articles they are interested in.

# Proposed Solution 

- [x] Add field_content_reference (avoids conflict with HR field_reference) to article content type with the ability to reference other articles.
- [x] Display as stacked cards in a three column grid.
- [x] Adjust site splits (iisc, sppa, hr, admissions)
- [x] ~Update default_content?~

# Follow-up

- Global settings with other display options

**Comment by joewhitsitt** [comment]
I am curious to hear from @quamsta about how this new field could/should interact with the related by tag functionality.

**Comment by cory-skeers** [comment]
> * Integrate related content field with the related content by tag functionality (admin/config/sitenow/uiowa-articles) where referenced items will take precedence over tags or is it a separate option from the dropdown to show those instead of tag based?

For the majority of cases, I would think referenced items first, then related by tags.

In my experience in the past (uihc, library) there've been some cases where it was desired to display only manually related content, and in other cases allow for both manually related and auto/tag-related. It was generally sensitive areas (eg medical, public policy) where it was limited to manual only.

If that is the case, I would lean toward providing the option to do referenced items only, or referenced items then tags, defaulting to the latter. (And with an option, use a form of our 'site-wide default' or override method.)

**Comment by joewhitsitt** [comment]
>And with an option, use a form of our 'site-wide default' or override method.

Yeah, at this point I think establishing a "related content" sidebar section for this, help text and the reference field would be a good idea and by doing so highlights the existing functionality more.

**Comment by bspeare** [comment]
I'd vote to display the related content in a card grid by default and for a future slice, develop different card display options like the screenshots below. 

<img width="550" alt="Screen Shot 2022-08-16 at 1 54 47 PM" src="https://user-images.githubusercontent.com/1036433/184959045-d751c602-582c-4a2a-9d0a-02e29dd54e0b.png">
<img width="484" alt="Screen Shot 2022-08-16 at 1 55 35 PM" src="https://user-images.githubusercontent.com/1036433/184959291-d8021346-3952-4094-9608-abff26a4d5ef.png">

**Comment by briand44** [comment]
I can get on board with having configuration here if the plan is to have different display options outside of "Display" or "Do not display".  If we only have the card display option, my thought is to just display it if there is referenced content otherwise do not display. No need to add additional config.

**Comment by quamsta** [comment]
I was actually just thinking about related content the other day. We could do a lot of neat stuff here that has a range of functionality most of which has been already been mentioned by @cory-skeers:

## Types of related or "more" content

- Referenced and manually selected related content
- Automatically selected related content via tags
- Combination of the above two options
- Randomly selected content for a "more content" section instead of a "related content"  - This one might be a bit more controversial, but I think the option to provide people links to explore a less organized/very large set of posts on some blogs without requiring a lot of tagging to have occurred. We have a few student blogs that aren't tagged well, but could benefit from such a thing, e.g. https://bijou.prod.drupal.uiowa.edu/bijou-blog
- Maybe in the future a "More from this issue"-type set of related content grouped by a taxonomy object for a publication

## Ways to display related or "more content"

Additionally, I think it's important to be able to change the heading that appears above the content, so that instead of "Related," the user could customize it to something like "More from the Bijou Blog" or something similar.

- Display related content titles grouped by tag (existing related content)
- Display related content as a card list
- Display related content as a card grid
- Possibly customize the limit to the number of items shown (especially if there's a "More content"-type randomizer)

**Comment by briand44** [comment]
Not going to add any user options to begin with, we can revisit if we add future display options.

**Comment by bspeare** [comment]
For the first slice, let's display the related articles as stacked cards in a three column grid.

**Comment by bspeare** [comment]
Mid-sprint feedback:

- We need to make the "Content references" headline on the page either customizable or pick something more user-friendly:
  - "Related content" would make the most sense, but there is concern about the conflict with the section called "Related" further down the page. 
  - "Similar articles", "You may also like...", "Promoted content", and "Featured content" were also suggested. 
- ~Hide the teaser text from the cards~ edit: I forgot to run `yarn workspace`
  - Perhaps a future slice of this could set this as an option to turn on/off at `/admin/config/sitenow/uiowa-articles` and override for each page.

**Comment by bspeare** [comment]
A few more ideas:
- Call one section "Related content" and the other section "Related tagged content/Related content by tag"?
- "Read next"
- No heading.  The appearance of the featured cards under the article makes it clear that it is related content.

**Comment by quamsta** [comment]
Some thoughts, apologies if some of these have already been discussed

> - We need to make the "Content references" headline on the page either customizable or pick something more user-friendly:
>   - "Related content" would make the most sense, but there is concern about the conflict with the section called "Related" further down the page. 

What about just "Referenced in this article:" or just "Referenced:"

> A few more ideas:
> 
> * Call one section "Related content" and the other section "Related tagged content/Related content by tag"?

Is it possible to show only one "Related" section if there's specific, referenced content attached to a node and prevent a "Read next"-type section from showing? I feel like doubling up with two "Related"-type sections may be a bit overwhelming to a reader and either dismissing one or the other based on context, or perhaps pooling together both related and specifically referenced content into one singular "Related"-type section might be a bit nicer for a reader.

> * "Read next"

I like this as a heading for related content by tags or even randomized content. It's generalized enough to be used in a lot of cases (blog posts, longform news articles, etc) and doesn't require customization for each site (aka, you'd have to be able to customize the heading per-site to get something like "More from the Bijou Blog" or something similar). 

> * No heading.  The appearance of the featured cards under the article makes it clear that it is related content.

Not sure how I feel about this one. I feel like some kind of separator or heading is necessary to give more article titles/images/other things a bit more context.

**Comment by briand44** [comment]
>I feel like doubling up with two "Related"-type sections may be a bit overwhelming

Yeah, I'm starting to think maybe we should add another configuration option under "Display related content" that says something like "Display manually referenced related content". This could be the default setting and if someone referenced an article manually it would show.

We could then use the headline of "Related Content".

In the future if there were additional config options related to Manually referenced related content, another field could display if that option is selected, allowing different display options (list view, show teaser, etc.)

**Comment by bspeare** [comment]
> Add another configuration option under "Display related content" that says something like "Display manually referenced related content".

I like this idea!  Here's what it could look like:

Under the configuration settings for "Display related content":

<img width="513" alt="Screen Shot 2022-08-31 at 1 03 59 PM" src="https://user-images.githubusercontent.com/1036433/187748334-d4c9ae26-e09c-4297-8cd4-7ee9fd02b0e5.png">

A new option for "Display manually referenced content" would be added:

<img width="468" alt="Screen Shot 2022-08-31 at 1 03 38 PM" src="https://user-images.githubusercontent.com/1036433/187748411-2a97983c-6d98-48a7-b956-f46cd5a00f1e.png">



# Display related content titles grouped by tag

https://user-images.githubusercontent.com/1036433/187745894-a8d60a94-8e3e-46d5-9f4e-15d5fdc46a0d.mov



# Display manually referenced content


https://user-images.githubusercontent.com/1036433/187745944-dc124898-c692-4cea-a777-26c0ad151bdd.mov

**Comment by cory-skeers** [comment]
> Here's what it could look like:

I really like this setup, and moving the manually referenced content down into a separate "Related" content adds some nice space.

I think for the most part, this covers the main intended uses for these related contents. I do wonder if there might be a use case or request for including both types on a page, but 1) I'm not sure that's even the case and 2) going this route doesn't keep us from adding an "include both" in the future. And if it's decided that it's needed, hopefully then we can have a better idea of the use case to help sort out how to fit the two together.

**Comment by briand44** [comment]
>This could be the default setting and if someone referenced an article manually it would show.

If they didn't want to show any related content, they just wouldn't manually reference any.

Thoughts on this??

**Comment by cory-skeers** [comment]
> If they didn't want to show any related content, they just wouldn't manually reference any.

That makes sense to me. 

So just have the options be "Display manually referenced content" or "Display related content titles grouped by tag," and if they currently have "Do not display related content," it'll be updated to "Display manually referenced content" (because functionally, if they don't manually add anything, it's the same as not displaying related content)?

**Comment by briand44** [comment]
@cory-skeers that was my thought, I am not opposed to defaulting to "Display manually referenced content" and keeping an option to "Do not display related content" but not sure of the use case for keeping that option around at this point.

**Comment by quamsta** [comment]
"Display manually referenced content" as the default instead of "Do not display related content" sounds like a good call.

**Comment by briand44** [comment]
@joewhitsitt does this approach cause any issues with HR?

**Comment by joewhitsitt** [comment]
Still wrapping my head around this approach. The field machine name was the biggest conflict which was avoided. HR does not have related content on articles currently (just pages and they aren't rendered).

**Comment by joewhitsitt** [comment]
@bspeare and others, I think this approach is fine. It is along the same lines as I was originally thinking for this issue. I also think manually referenced as the default will be fine since this is a new feature that won’t have content in it initially.
