### ISSUE TITLE
UI Press - Display editors instead of authors if no authors exist for a book and one or more editors do exist

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#5578]
# Motivation

Some books on UI Press don't have an author, but instead have editors who have compiled other people's writing together. The site owners would like to have the list of editors display instead of the author when there are editor(s) and no author. You can see an example of this with the Fame and Fandom book on the homepage: https://uipress.uiowa.edu/

# Proposed solution

- Add the editor(s) field to display on the book teaser
- Add preprocessing logic (limited to teaser view display) to check if there is an author and to disable the display of the editors field when there is an author.
- Do not exclude preview mode for preprocessing logic or when route is an admin route.

**Comment by briand44** [comment]
add additional clarification around `!admin` and preview.

**Comment by joewhitsitt** [comment]
I think my point about node_preview is moot as long as the logic happens within a preprocess_node. The instances I was referring to in grooming were outside in a preprocess_page, etc.

```
$node = \Drupal::routeMatch()->getParameter('node');
        $node = ($node ?? \Drupal::routeMatch()->getParameter('node_preview'));
        if ($node instanceof NodeInterface) {
```
