### ISSUE TITLE
Revisit older splits

### ISSUE THREAD

**Issue by cory-skeers** [uiowa/uiowa#5579]
Original card:
"Is the sppa split correct? Cory and I were looking at it and it seemed like it could be more reasonably done with splits? is that something that is changeable or are we locked in now that we have the config made?

(eg, the article form display looks like it could be handled by a partial split, but is set up as a full split; core.entity_view_display.* is in partial split, but these may need full splits or might not need to be split at all)"

Wondering if it could be a good investment to revisit some site splits, particularly some of our older ones, and see if there's some cleanup or refactoring possible. It also might be a good pair/mob opportunity, and a learning experience for anyone who's not as familiar with the splits.

# Proposed Solution

- [ ] Start from feature/migrate first before moving on to site splits
- [ ] Run https://github.com/uiowa/uiowa/blob/main/blt/src/Blt/Plugin/Commands/ConfigSplitCommands.php commands to identify initial configuration to inspect and update
- [ ] Look back at git log to see where configuration was introduced to understand functionality and the correct config going forward.
- [ ] Adjust configuration so that future exports are identical.

**Comment by joewhitsitt** [comment]
I think we should start with feature splits first as site splits sometimes have the combination of one or more feature splits alongside site specific changes.

This is related: https://github.com/uiowa/uiowa/issues/5540

**Comment by briand44** [comment]
Joe, you mentioned that prioritizing this soon would be ideal but I can't remember what issue(s) it would help with. Was it the 9.4 core update, the drupal-check dependency update, php 8.1 update, September dependency updates or all of the above?

**Comment by joewhitsitt** [comment]
From slack DM:

>probably core update and September dependencies as they will result in config changes.

**Comment by makurj** [comment]
I'd like to pair on this.

**Comment by joewhitsitt** [comment]
Original pinned slack conversation related to partial/full split: https://iowaweb.slack.com/archives/C0164FNN1PV/p1642689940252600

**Comment by joewhitsitt** [comment]
Keep https://github.com/uiowa/uiowa/issues/5427 in mind

**Comment by joewhitsitt** [comment]
For the p2lb split, we cannot use https://github.com/uiowa/uiowa/blob/main/blt/src/Blt/Plugin/Commands/ConfigSplitCommands.php because the feature itself relies on another split (sitenow_v2). To audit this feature, a v2 default site should be used as a base.

**Comment by joewhitsitt** [comment]
For the sitenow_intranet split, it is getting confused with siteimprove locally since we delete those settings. We _do_ want the siteimprove functionality being removed from configuration. A way to try this is to sync default down as a PROD. Add the following to your local.settings:
```
$config['config_split.config_split.local']['status'] = FALSE;  
$config['config_split.config_split.prod']['status'] = TRUE;
```

The issue:

```
   permissions:
     - 'administer sitenow intranet'
     - 'bypass ip restriction'
-removing:
-  dependencies:
-    module:
-      - siteimprove
-  permissions:
-    - 'use siteimprove'
+removing: {  }
```

**Comment by joewhitsitt** [comment]
Update on https://github.com/uiowa/uiowa/issues/5579#issuecomment-1230837834

I think this is just something we need to live with. Tried the possible workaround which didn't work but also made me realize that folks will run into this anyway during development then and have to discard anyway.
