### ISSUE TITLE
Generate a list of code/config change scenarios that could necessitate off-hours deployments

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#5580]
# Motivation

Related to #5559. We would like to better understand the conditions that result in outages during deployments so that we can get better at identifying PRs that are going to result in outages and should be scheduled for off-hours deployments.

# Proposed solution

Every member of the team should contribute what they know about the conditions that result in outages. The list we produce can be added as a wiki page and then referenced when people are reviewing code to identify PRs that might need to be handled off-hours.

**Comment by bspeare** [comment]
Added a point to the proposed solution for template changes in `uids_base`.

**Comment by pyrello** [comment]
For reference, a code review I did where I identify some situations that I'm aware of that can result in outages: https://github.com/uiowa/uiowa/pull/5623#issuecomment-1240813939

**Comment by joewhitsitt** [comment]
During the defensive coding meeting, we worked on an example related to the outage: https://github.com/uiowa/uiowa/pull/5682

**Comment by pyrello** [comment]
I'm going to start working on this.

**Comment by pyrello** [comment]
A little bit of background: The core problem that we deal with when run a deployment is that code updates happen immediately at the beginning of the deployment. File names and locations, as well as PHP class names, are cached in the database per site. Sites are processed sequentially for updates and we have no option affect the database until the site comes up in the queue. This means that we have a gap in time where our codebase potentially does not match up with what is stored in the database. If a file or class gets called at a location that it no longer exists at, this can cause a PHP error or white screen. The amount of time these conditions may exist gets worse the further down the list a site is.

**Comment by pyrello** [comment]
Here are the conditions I can think of that should require an off-hours deployment:
- Moving or changing the name of a file that can be called by PHP directly. These will typically have one of the following extensions:
  - `.php`
  - `.module`
  - `.install`
  - `.profile`
  - `.theme`
  - `.twig`
- Changing a class name or namespace (e.g. `OurListBlock` => `ListBlock` or `\Drupal\layout_builder_custom\ListBlock` => `\Drupal\lb_custom\ListBlock`)
- Dependency updates that introduce any of the above changes.

**Comment by pyrello** [comment]
@joewhitsitt can you clarify "Schema changes?" Do you mean changes to config schema? Or database table definitions?

**Comment by pyrello** [comment]
Conditions under which you should request changes when doing a code review:
- Accessing an object method or property without doing an appropriate check that it exists first. Checking `instanceof` against an interface or class known to contain the property or method works. This can also probably be handled via the null safe operator in PHP 8.
- Trying to access an array element by key without doing an `isset()` or `!empty()` check first.
- Not including an update hook for database schema changes.

**Comment by joewhitsitt** [comment]
I was thinking database like changing field type or adding a column to a table that code acts on

**Comment by bspeare** [comment]
This looks like a great list that we can reference and continue to update as we move forward.

**Comment by pyrello** [comment]
@joewhitsitt suggested that we move this text from a card on our project board to the docs:

Deployment failure on `uiowa.test` was a potential early warning about issues with our scheduled deployment. In most recent case, it was not a showstopper, but maybe we want to make it a prerequisite to setting up a scheduled deployment that we either have a successful stage deployment, or we have investigated it and given it the all clear

Since I believe we are using this issue to handle moving other items to the docs, I'm putting it here until we can agree on that as the next step.

**Comment by pyrello** [comment]
I added https://github.com/uiowa/uiowa/issues/5580#issuecomment-1245844295 to 
https://wiki.uiowa.edu/display/drupaldev/Development+Workflow

**Comment by pyrello** [comment]
I have moved all the sections that were created as part of this issue into the wiki.
