### ISSUE TITLE
As a visitor to uiowa.edu, I can view the Iowa logo that no longer celebrates the 175th anniversary 

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#5581]
# Proposed solution

Undo or update the files that were created in https://github.com/uiowa/uiowa/pull/4263 to display the Iowa logo.

**Comment by e-marie-w** [comment]
Since the 175 logo and regular logo are in separate files, I just changed the used file back to the regular one. 

That leaves the question of what to do with the 175 logo file, though. Can we remove it from our codebase, or is there a reason to keep it?

**Comment by bspeare** [comment]
I think we should remove the file from the codebase.

**Comment by joewhitsitt** [comment]
Removing it now will require a cache rebuild correct?

**Comment by bspeare** [comment]
Yes, good point!

**Comment by e-marie-w** [comment]
I forget, is the cache rebuild something we add in like an update hook, or something we trigger manually after the code deploys?

**Comment by joewhitsitt** [comment]
>or

Yes. ;)

In this instance, I would just add an update hook like https://github.com/uiowa/uiowa/blob/main/docroot/profiles/custom/sitenow/sitenow.install#L2101
