### ISSUE TITLE
Signage slide not showing at scheduled time

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5582]
There is a slide scheduled to display at 5am and it is regularly not displaying at that time. The latest response was that it was still not showing at 6:45am. There is a thread in its-web related to this issue. 

https://signage.uiowa.edu/food-nutrition-services/childrens-cafe-chef-special

**Comment by joewhitsitt** [comment]
I think this is just a varnish issue. The scheduling is used for an uncached slideshow view placed within a cached page. The page itself doesn't change so there is nothing telling varnish to clear here. Cron is run every three hours. APE is setting a 5 min for anonymous users and there is a js refresh of the browser too, but none of that trickles up to varnish to be timely

**Comment by briand44** [comment]
Thanks for the comment Joe. I'm not sure I understand based on your comment but my guess is this issue would exist for other signs that are setup similarly?

**Comment by joewhitsitt** [comment]
On the surface I don't see anything unique here so I assume it is affecting the whole app. Do we know if other signs are having this problem?

**Comment by briand44** [comment]
>Do we know if other signs are having this problem?

We haven't heard of any that I am aware of. This is what @makurj was mentioning yesterday. She thought if this was a service wide issue we would have heard about it from other folks (dining halls, etc.).

**Comment by joewhitsitt** [comment]
I thought dining did something different for menus

**Comment by briand44** [comment]
>I thought dining did something different for menus

You may be right, I was thinking that as well as I typed it.

**Comment by joewhitsitt** [comment]
This is probably the most complex scheduling I have seen for these. Maybe folks haven't reported it because they don't have such a specific expectation.

**Comment by joewhitsitt** [comment]
My hunch since things eventually do show up, that cron is involved and not firing at the right time. it is currently set to 3 hours. The view is not cached, APE has a five minute and there is the js refresh. Reducing to every hour would help but not fix it to be consistent to the granularity of that datetime field. Other v1 sites have cron job running on the hour, etc.

As a test, we could change to 1 hour, manually trigger it at 9:30 and see if the 10:30 FY23 6A lunch-dinner shows up within 5 min on an anonymous browser.

**Comment by joewhitsitt** [comment]
i set to 1 hour and just ran cron at 9:31. sign is currently black. will check in on it later

**Comment by joewhitsitt** [comment]
i didn't check right at 10:30 but this did update when i did shortly after. next change is at 7 tonight. Going to keep site cron at one hour, but then setup a scheduled job for the app to run cron every thirty minutes.

**Comment by joewhitsitt** [comment]
thanks again https://crontab.guru/ for helping me construct "on the hour and again 30 min after the hour" type expression

**Comment by joewhitsitt** [comment]
So I think we have done all that we can. I think I heard that this sign is now powered by one of our sticks, so I am not sure if they have the proper browser refresh functionality. Checking with Issac to see what the default refresh timer is for the sticks. I see some set to 60 seconds. Dare I say it, it would be nice to have a device of our own running to test on (remotely). Is there a need for a PCO sign that we can highjack periodically?

<img width="397" alt="Screen Shot 2022-08-22 at 8 46 51 AM" src="https://user-images.githubusercontent.com/4663676/185936483-81e31156-abfb-4f76-900c-64d642766b92.png">

Views cache is off, APE is 5 min, there is a javascript reload (with forced set to true), cron is running every thirty minutes.

Also looking at the internal docs, I see that there is actually a feature request to make scheduling more granular than _a day_ which leads me to believe this was never working to the minute.

["Granular scheduling of slides (ex. this day at this time)"](https://iowa.sharepoint.com/:o:/r/sites/CSI-Drupal2/Shared%20Documents/Signage/Signage%20Docs?d=wdaaa6395ba3046459e96eebb4881293b&csf=1&web=1&e=kS8KO2)

**Comment by joewhitsitt** [comment]
My anon browser (untouched) just refreshed by itself at 9:34 and the sign updated. Going to see what happens at 10:30 before updating the Cherwell ticket.

I think we just have a few odd timers involved. APE is 5 min. JS Reload (configurable 10, 30, 60 min) is currently set to 10 min for the sign. Cron is running every 30 min starting on the hour.

Issac responded that the default is not to refresh.

**Comment by briand44** [comment]
So the only change we made was adjust cron from running every 3 hours to running every 30 minutes?

Can you explain if/how APE affects Varnish?

I'm trying to understand if we thought this was related to Varnish caching how adjusting cron helps with that?

There is also an email thread in its-web with the sign owners, etc. that we should follow up with after you feel good with your testing and let them know to check it tomorrow morning and let them know the max length of time they should expect before the slide changes.

**Comment by joewhitsitt** [comment]
the 10:30 slide showed up at 10:36.

My varnish hunch is almost a week old. I looked into APE further which eventually led me to cron. It is my understanding that APE is what works around Varnish since there are no content changes to trigger a purge. https://www.drupal.org/project/ape

Instead, cron seems to be the trigger to re-query the view and do the timestamp specific filtering. By using poor man's cron, the time was inconsistent on when they ran and a large window of three-hours. after cron, it is just a matter of what timer is at what point. so far, the slide has shown up under 10 minutes.

**Comment by joewhitsitt** [comment]
Emailed the original thread outside of Cherwell:

```
We have investigated the scheduled slide issue related to UI Signage and came up with a couple changes to improve the timing of the transitions.

Though the scheduling functionality does collect granular timestamps, we are unable to provide up-to-the-minute transitions at this time.

For now, caching for the sign is five minutes and there is a script that reloads the window every ten minutes based on the configuration on the sign. We now have a job running on the hour and every half-hour that will re-query the data/time-filtering for the slideshow.

While testing today using an unauthenticated browser session, the signs refreshed within 10 minutes of the hour and half hour scheduled changes (9:30, 10:30 and 2).

Our recommendation is to maintain the hour/half hour scheduling and let us know if you aren't seeing changes within 10 minutes.
```

**Comment by joewhitsitt** [comment]
Closed the Cherwell ticket this AM noting the changes made to trigger closer to the hour/half hour and test results of transitions within 10 min. An improvement in response time and predictability.

**Comment by joewhitsitt** [comment]
Thinking of adding :15 and :45 to the cron job

**Comment by joewhitsitt** [comment]
`*/15 * * * *` has been implemented

https://crontab.guru/#*/15_*_*_*_*
