### ISSUE TITLE
Banner video play/pause button overlaps the main content button

### ISSUE THREAD

**Issue by bewoldt** [uiowa/uiowa#5585]
# Problem
When adding a video to a banner the play/pause button will overlap the main content button on certain screen sizes.

Example page at https://imu.uiowa.edu/student-involvement.

<img width="743" alt="Screen Shot 2022-08-17 at 9 47 04 AM" src="https://user-images.githubusercontent.com/731952/185170825-7c0faae5-9474-4d9e-9285-40954e229b41.png">

**Comment by bspeare** [comment]
The bug fix work for this should happen in https://github.com/uiowa/uids/issues/721.
