### ISSUE TITLE
Update article docs with gallery info

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#5586]
# Story

As a Sitenow user, I want to know more about what this new gallery field is on the article content type.

# Proposed solution

Update - https://sitenow.uiowa.edu/documentation/article-content-type

**Comment by GaryRidgway** [comment]
how is this for wording? https://sitenow.uiowa.edu/node/126/latest

**Comment by cory-skeers** [comment]
Should we add anything about the jump link that gets added automatically?

Otherwise, looks good! 👍

**Comment by GaryRidgway** [comment]
Ah, good idea! I will add that

**Comment by GaryRidgway** [comment]
@cory-skeers it has been updated, will you check it again?

**Comment by cory-skeers** [comment]
Looks good! I think it's ready to be published.

**Comment by GaryRidgway** [comment]
Published, closing issue.
