### ISSUE TITLE
Update drupal/ctools to 3.11 and add to our composer.json

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#5589]
# Story

As a developer, I can manage the version of ctools we are using instead of relying on other modules' composer files to update it. Since we rely on ctools/ctools_views for ListBlock, we should maintain better control over this dependency.

# Background

Noticed there have been updates to ctools (https://www.drupal.org/project/ctools/releases/8.x-3.11) but that we are still on 3.7.0 because the way it is pulled in is through other modules' composer files (pathauto, paragraphs).

# Proposed solution

- [ ] Add/update ctools within our composer.json. Test our ListBlock functionality and prepare for later versions of Drupal.

**Comment by pyrello** [comment]
Noting that we do not want to upgrade past `3.11` because `3.12` introduces the new exposed filters functionality and we'd be forced to update our list block implementations.
