### ISSUE TITLE
Fix hover effect on search results

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#5591]
# Problem
Hovering on search results shows an incomplete border.

<img width="788" alt="Screen Shot 2022-08-18 at 10 05 51 AM" src="https://user-images.githubusercontent.com/4663676/185437872-a9fc6a34-42d5-4c26-9966-22656efa9299.png">

# Proposed solution
- [ ] Adjust https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/scss/components/search-results.scss

**Comment by bspeare** [comment]
@joewhitsitt are you still seeing this?

**Comment by joewhitsitt** [comment]
Looks like it is an admissions thing: https://admissions.uiowa.edu/search?terms=costs#gsc.tab=0&gsc.q=costs&gsc.page=1

**Comment by bspeare** [comment]
@joewhitsitt thanks, it looks like this needs to be scoped to `.gsc`.
