### ISSUE TITLE
MyWeb error getting account requests from Qualtrics

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5592]
https://git.uiowa.edu/its-web/myweb/-/blob/master/Get-Qualtrics-Responses.ps1

**Comment by briand44** [comment]
https://status.qualtrics.com/incidents/mkxsf46z67qr - Hopefully it is related to this and has resolved itself. We should know at 4pm

**Comment by briand44** [comment]
doubt it was that based on the short time span

**Comment by joewhitsitt** [comment]
We have some docs here that illustrates some things: https://wiki.uiowa.edu/display/sitenow/MyWeb+Service

**Comment by joewhitsitt** [comment]
i am interested in this issue but don't wait

**Comment by briand44** [comment]
I found an issue but I do not have the correct permissions to update the scripts. I let the sysadmin know. Hopefully, this is the only issue and we will be back in business soon.

**Comment by briand44** [comment]
FYI, it doesn't appear the repo (https://git.uiowa.edu/its-web/myweb) is up to date with the actual code on the server.

**Comment by briand44** [comment]
The change to the api endpoint seems to have resolved this issue. We also adjusted some perms so that our team can run these scripts manually as needed. Once @e-marie-w is able to confirm she can add files to her directory I will call this complete.

**Comment by briand44** [comment]
@e-marie-w confirmed she could add files to her directory. Closing this!!
