### ISSUE TITLE
91st Meridian - Add translator field to writing content type

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#5595]
# Story

As a 91st Meridian content editor I want a translator field on the writing content type so that I can display the translator of a piece of writing content.

This is picking up from #5414 and will be a follow-up to #5601.

# Proposed solution

- [x] Add a text area field called "Translator" to the article content type. This will be split configuration for the site split.

**Comment by briand44** [comment]
This work can be included in the existing PR

**Comment by joewhitsitt** [comment]
>Add a text area field called "Translator"

Just noticed this. Is this is a typo? string_long (text area) or string (textfield)?

**Comment by joewhitsitt** [comment]
A DM from Brian:

>text area vs text.... I don't know the answer to this for sure. Sean mentioned this to me the last time we touched base on grad priorities. If Marie or others don't know, I think I would go with a text area. I'm thinking maybe they want the flexibility to capture additional information about the translator?

@e-marie-w do you recall?

**Comment by e-marie-w** [comment]
I don't think we ever discussed this. I'd lean towards text area too, though. I added the Author Bio field for when they want to capture an author and any bio info without creating/referencing a Person entity. Since there is no option for entity reference for translator, it makes sense to have the larger text area again, in case there is extra info.

**Comment by e-marie-w** [comment]
I took a quick look at the d7 site, it looks like there is usually a bio for the translator, so I'm doubling down on text area. Side note there is usually a translator's note, which uses the Introduction field for the content type...now I'm wondering if that can just go in the body or if it's another field we need to add.
