### ISSUE TITLE
Move away from opportunistic Duo enforcement

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5598]
>The opportunistic option will be retired soon, allowing only two options, no Duo enforcement (only a password is required), or mandatory Duo enforcement (both password and Duo are required).

Original issue: https://github.com/uiowa/uiowa/issues/2263

We sent out a communication regarding this so if it is changing we should probably do that again: https://apps.its.uiowa.edu/dispatch/archive/two-factor-authentication-46kkyBn

**Comment by joewhitsitt** [comment]
I say mandatory.

Could ask if there are any hawkids not eligible for duo (e.g. affiliates), but I reckon if hawkid is our only method, we should get on board with this.

**Comment by cory-skeers** [comment]
> I say mandatory.
> 
> Could ask if there are any hawkids not eligible for duo (e.g. affiliates), but I reckon if hawkid is our only method, we should get on board with this.

I'd second this too. Not sure if it's an explicit policy, but if not, there are still enough hawkid-based services that require duo that I'd lean toward following suit.

**Comment by briand44** [comment]
Plan is to make this switch on next Wednesday, September 7th. We should send out a communication to the SiteNow announcements list this week. I can work on an initial draft.

**Comment by briand44** [comment]
> SiteNow users,
> 
> On September 7th, all SiteNow v2/v3 websites will require mandatory two-factor authentication. This is a change from the current experience where only users who have previously configured a two-factor authentication method are required to use two-factor authentication.
> 
> Please see the [ITS website](https://its.uiowa.edu/duo) for details on configuring a two-factor authentication method.
> 
> As always, questions may be directed to [its-web@uiowa.edu](mailto:its-web@uiowa.edu).
> 
> Thanks,
> OSC Web Services

**Comment by briand44** [comment]
Looking for feedback on the above message as well as communication channels. Planning on sending to SiteNow announcements but curious if this should be an ITS alert for a service announcement as well?

**Comment by cory-skeers** [comment]
Only suggestion on the message would be changing "...will begin requiring..." to "...will require..." I don't think many people would read it this way, but "begin requiring" could be interpreted as a gradual rollout and not a hard switch.

Regarding communication channels, I think a SiteNow announcement should be enough, but since it could cause a disruption, I don't think it would hurt to be over-communicative with an ITS alert as well.

**Comment by bspeare** [comment]
The message looks good!  I agree with Cory's point.

**Comment by briand44** [comment]
Thanks for the feedback, I updated the text and I will add an ITS alert as a service announcement as well as the SiteNow announcement email.

**Comment by briand44** [comment]
ITS alert added, not yet published by the HD staff.

**Comment by briand44** [comment]
SiteNow announcement scheduled. I will move back to test mode after the communication sends.

**Comment by briand44** [comment]
Set back to test mode. Closing as there is not any additional work required by our team.

**Comment by joewhitsitt** [comment]
The IAM team considering moving us back to the opt-in MFA setting to better support guest hawkids and other use-cases.
