### ISSUE TITLE
Editor user permission role can access some configuration options

### ISSUE THREAD

**Issue by quamsta** [uiowa/uiowa#5609]
# Problem
A user with the "Editor" permission role can access two sections in the Configuration section of Drupal:

- Region settings
- Layout Builder Direct Add

This allows them to change the "Add Component" button text in Layout Builder and/or create Pre-Footer regions and layouts and apply them to the entire site.

## Screenshot:
<img width="1421" alt="Screen Shot 2022-08-24 at 9 03 07 AM" src="https://user-images.githubusercontent.com/472923/186440413-4fcafac8-08c6-42fd-b344-ebbe96921f47.png">

# Steps to reproduce
1. Add a user to a site and give them an editor role
2. Login as an admin and masquerade as that user
3. Click the "Configuration" section and see that you can edit these two settings

Or

1. Ask a user who currently has the Editor role assigned to them to login
2. Ask them to go to the Configuration section and see that they can edit these two settings

I've tested this by both masquerading as a user and asking an actual user to look at the "Configuration" setting and was able to reproduce this by following the steps above.

# Proposed solution
Restrict those configuration options to Webmaster, Publisher, or a higher level role.
- Update lb_direct_add with patch or release from https://www.drupal.org/project/lb_direct_add/issues/3305765

**Comment by joewhitsitt** [comment]
I've added an upstream issue with lb_direct_add to create a more granular permission to restrict this. This was a known issue, but I don't think we thought it was high-impact at the time. https://www.drupal.org/project/lb_direct_add/issues/3305765

**Comment by joewhitsitt** [comment]
As for the region settings. I'd like to get your thoughts @quamsta or others' on to what extent the region settings functionality should be restricted.

I believe editors can create region_items which are used within region settings. Should they still be able to create but not assign them to the region? We are actively working on expanding region settings to include a new region with per page overrides. https://github.com/uiowa/uiowa/issues/4767 so we would also have to consider restrictions within the page form.

**Comment by quamsta** [comment]
@joewhitsitt 

> Should they still be able to create but not assign them to the region?

I think this sounds right. My initial concern about the Editor role being able to create pre-footer layouts and assign them to a region was the fact that they're able to change or add a block that appears the entire website despite the fact that I believe their "page edit" permissions are restricted to just saving drafts or setting them "for review."

If their permissions for editing pages are that restrictive, IMHO, they probably shouldn't be able to adjust a "global" thing like that without someone reviewing and publishing their work. 

The "Add Component" option isn't really that big of a deal in comparison, unless someone got confused and changed it accidentally and even then, it's not as far-reaching as a change, nor is it visible to a typical user of a website.

**Comment by bspeare** [comment]
- Publishers currently do not have access to layout builder. 
  -  Do we want to keep Publishers completely out of the Region settings page then?  
  -  Publishers can also replicate pages. 
  -  Publishers get a 404 if they try to access https://sandbox.prod.drupal.uiowa.edu/admin/config/sitenow/region-settings.  
- Editors do have access to layout builder.
  -  Editors can't replicate pages.   
  -  Editors do **not** get a 404 accessing https://sandbox.prod.drupal.uiowa.edu/admin/config/sitenow/region-settings.  

If the chart on https://sitenow.uiowa.edu/documentation/user-management-and-roles is correct, shouldn't Publishers have layout and replicate access and the editor role be completely limited?

**Comment by joewhitsitt** [comment]
Publisher is currently setup as a stacked role. Extends the editor role. We need to revisit permissions as a whole https://github.com/uiowa/uiowa/issues/4294

**Comment by bspeare** [comment]
Should we just restrict this to Webmaster only until https://github.com/uiowa/uiowa/issues/4294 happens?

**Comment by pyrello** [comment]
Not sure whether this is unblocked now or not, but the upstream issue for `lb_direct_add` was addressed: https://www.drupal.org/project/lb_direct_add/releases/2.0.0

**Comment by pyrello** [comment]
The Layout Builder Direct Add permission issue part of this has been resolved in #5949.

**Comment by joewhitsitt** [comment]
Removed the upstream label as part of this issue. Now we just need to decide if the editor role should continue to have region settings permissions or if we should close and make a note on https://github.com/uiowa/uiowa/issues/4294
