### ISSUE TITLE
Investigate and clean up P2LB tracking issue

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#5610]
# Motivation
The issue at #3878 has gotten a bit unwieldy and parts of it are unclear as to what our next step should be.

# Proposed solution
- Set up the P2LB module locally and test its usage.
- Review the remaining bullet points and make note of any that are unclear.
- Clarify unclear bullet points with the team/original author.
- Test all incomplete items to ensure that they haven't been fixed.
- Create issues for any outstanding tasks and make sure they have enough detail that you would be able to know how to get started a year from now.

## Setup instructions
- `ddev blt ds --site hawkeyemarchingband.uiowa.edu` or another V2 site.
- `ddev drush rsync @hawkeyemarchingband.prod:%files @hawkeyemarchingband.local:%files`
- `ddev drush @hawkeyemarchingband.local uli admin/config/development/configuration/config-split`
- Enable P2LB split
- `ddev drush @hawkeyemarchingband.local cim`
- Visit converter tool at https://hawkeyemarchingband.uiowa.ddev.site/admin/content/sitenow-converter

**Comment by pyrello** [comment]
I'd like to pair on this.

**Comment by pyrello** [comment]
We discussed in planning that it would make the most sense to limit this investigation to figuring out and clearly defining the next steps that represent functionality that we would like to see for feature completeness. The remaining tasks are related to things that are not working correctly or based on adjusting transformation code to account for changes to our LB blocks. Since those blocks may continue to change, I think we should get to feature completeness for the system, then make an additional investigatory pass through to see what isn't working with our LB blocks.

**Comment by pyrello** [comment]
I'll let this get closed automatically by #5613 getting merged.

**Comment by briand44** [comment]
Comments during Sean's demo:

Potentially hide sections rather than disable after conversion

record editor that converted as the “changed by” person in overview

Change name from SiteNow convertor ("SiteNow Migrade”)

Possibly add convert tab on node page.

inbox zero type message/celebration when no more pages need to be upgraded

**Comment by pyrello** [comment]
I have to say, I'm not sure that I'm a fan of changing the wording from "convert" to "upgrade," as in SiteNow Converter => SiteNow Upgrader.

I believe the original terminology better encapsulated what is happening. While we might consider the entire process of moving a site from V2 to V3 to be an upgrade, upgrading content just sounds weird to me.
