### ISSUE TITLE
Switch to Aggregator contrib

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#5612]
# Story

As a developer, I understand that aggregator has moved out of core into contrib and that starting in 9.4 the core version is deprecated. Knowing this, we should switch to using the contrib version before upgrading to Drupal 10.

https://www.drupal.org/node/3304999

**Comment by quamsta** [comment]
@joewhitsitt Is the contrib module just a fork of the original core module? We don't have to update hook anything to continue using it, right? We've really come around to using it, especially to aggregate a few RSS feeds for our DSL intranet site

**Comment by joewhitsitt** [comment]
Yes, it is a fork, but that might have a new release by the time we switch it out. Also because the location of things will move with this it will require a scheduled deployment and possibly a cache clear.

**Comment by joewhitsitt** [comment]
Closing in favor of #5064
