### ISSUE TITLE
Purge careers aggregator items after 1 month rather than 1 year.

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5614]
# Story

As an owner of the Career Center website, I would like to only keep aggregator items for 1 month rather than the current setting of 1 year, so that the number of items in our feeds doesn't get overwhelming and start causing performance issues and pages to quit working.

# Additional Info

Career Center is using feeds aggregator functionality to display job opportunities for students. They have ~25 different feeds being consumed, some of which have had as many as 7,000 items stored in our db. This has caused a page to break on their site because of memory issues.

A potential long term solution would be to discard/purge items that no longer exist in the feeds source but that is not currently an available option with the aggregator module.

law requested these be kept for 1 year rather than our original setting of 6 months to handle feeds that contain an archive (https://apps.its.uiowa.edu/dispatch/archives/past/--iowa-law---september-25-lxj144j).

# Proposed Solution

- [x] Create a site split for Careers
- [x] Adjust config to limit aggregator items to 1 month
- [x] Truncate aggregator items if it chokes.
- [ ] #5807

**Comment by briand44** [comment]
Maybe this could be a setting exposed to user... 1 year, 6 months, 3 months, 1 month? Not sure if that makes sense if we eventually want to purge items no longer in the feed source? Still need to have a conversation about that as well.

**Comment by joewhitsitt** [comment]
There is this issue about a per feed setting: https://www.drupal.org/project/aggregator/issues/53587 as well as a limit how many are imported https://www.drupal.org/project/aggregator/issues/2975389 but both of these issues are older and have seen very little activity.

**Comment by joewhitsitt** [comment]
There are other settings on the config form that we don't probably want folks interacting with. Future proofing in mind, ideally, we would loop through all fields on the form to set access to false except for this one field. That way if a new field is made available in a later release, we don't have to account for it and it will just be hidden.

Alternatively, we could create a middle man setting that then sets this one setting without exposing the entire form to the webmaster. (I think that is how some colleges allow permission changes by webmasters without exposing all the permissions).
