### ISSUE TITLE
Broken link message feature for articles

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5626]
As a SiteNow editor, I have a way to toggle a message to appear at the top or at the bottom of old news articles so that visitors are made aware of old links.

# Additional Info

The message should be editable and default to say something like, "Links in this article are preserved for historical purposes, but the destination sources may have changed."

This was addressed previously for the D7 Iowa Now website in https://github.com/uiowa/uiowa/issues/4079

# Proposed Solution

**Comment by briand44** [comment]
Grooming conversation... Toggle on/off per article, defaults to off. Display at the top of article, below the title initially and we can evaluate if it should move after content or into existing alert area. Use info alert style.

**Comment by mjoneill** [comment]
Alternative approach (for historical record) dispenses with the "alerts" on articles and instead uses "robust links" approach for news content (in this case).  

https://robustlinks.mementoweb.org/robustify/?anchor_text=This%20is%20google%2C%20yo&url=https%3A%2F%2Fgoogle.com

Perma.cc also takes a similar approach.

**Comment by e-marie-w** [comment]
On their d7 site the editable message is set site-wide (instead of editable per article). Is that how we want it in d9 as well?

**Comment by briand44** [comment]
Yes, I think so.

**Comment by bspeare** [comment]
Thinking about using the card for this instead of the alert - what do people think?

<img width="1388" alt="Screen Shot 2022-09-14 at 3 37 50 PM" src="https://user-images.githubusercontent.com/1036433/190257957-82596e36-00f0-4c8b-86cb-8c1531444796.png">

<img width="1453" alt="Screen Shot 2022-09-14 at 3 38 41 PM" src="https://user-images.githubusercontent.com/1036433/190257987-818da8ec-536e-43be-8bfb-3dc8a8229fc5.png">

**Comment by joewhitsitt** [comment]
Besides looking awesome, is there another reason to introducing a new pattern here?

**Comment by bspeare** [comment]
Do you mean a pattern of alert vs card?  Since this is more of a message about the content instead of an alert, a card seems like it might be more appropriate for delivering an inline message.

**Comment by joewhitsitt** [comment]
I'd say that alert and message have been used interchangeably with our use in uiowa_alerts, wysiwyg styles, drupal messenger and uipress sale codes. hawk-alert has a whole different set of classes.

To me, without diving into it, it seems easier to expand our base alert styles to include another option and handle icons especially when folks see this and want something similar on their sites.

I think back to blockquote where we had base styling in wysiwyg but then made options in the block offering.

As much as I believe that "everything is a card," as long as our alert styles are out there, this seems like an alert.

**Comment by bspeare** [comment]
Sure, I think we either need to refactor our alert component to offer more variants or just turn the alert into a Story of the card component in UIDS4.

**Comment by joewhitsitt** [comment]
For the sake of this issue do we _need_ to have a different styling for this? is alert-info adequate for iowa now and go-live?

Can the refactor or reimagining be a separate issue? I am intrigued by the idea of a card story in uids4

**Comment by bspeare** [comment]
It doesn't _need_ it for sure.  Thanks for sharing your thoughts on this.  I'll put together an issue to move this forward.

**Comment by bspeare** [comment]
I added an issue to UIDS for an alerts refactor: https://github.com/uiowa/uids/issues/770.

**Comment by e-marie-w** [comment]
I added a couple sentences to the documentation: https://sitenow.uiowa.edu/node/241/latest and https://sitenow.uiowa.edu/node/126/latest. Saved them as draft so someone can look at them and then we can publish after the feature goes out as part of a deployment.
