### ISSUE TITLE
Add Collegiate websites to list of sites that run first during deployment

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5628]
As a follow up to https://github.com/uiowa/uiowa/issues/5558, we should add the following sites to that list.

- https://medicine.uiowa.edu/ * **
- https://dentistry.uiowa.edu/
- https://education.uiowa.edu/
- https://engineering.uiowa.edu/
- https://law.uiowa.edu/ * v2
- https://clas.uiowa.edu/ * D7
- https://nursing.uiowa.edu/
- https://pharmacy.uiowa.edu/
- https://www.public-health.uiowa.edu/ * **
- https://tippie.uiowa.edu/
- https://grad.uiowa.edu/
- https://uc.uiowa.edu/ * v1

* indicates non SNv3.
** indicates a site not hosted by us

**Comment by briand44** [comment]
Blocked until we know the impact #5629

**Comment by e-marie-w** [comment]
Is there a specific order we want these added in? Or is something like alphabetical order after the 5 already added sites fine?
