### ISSUE TITLE
Measure impact of adding sites to run first during deployment

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5629]
After addressing https://github.com/uiowa/uiowa/issues/5558, we should make sure that adding those sites doesn't negatively impact our deployments in a way that would make us rethink adding Collegiate sites in https://github.com/uiowa/uiowa/issues/5628.

>Here are the ideas for measuring the impact of this change:
>
>Select release deployments for the past week and average them across all active applications. Generate a similar sample for the upcoming week. Compare the values before and after.
Review RAM usage during the times that deployments have happened before and after the release of this update to see if any discernible differences emerge.

**Comment by joewhitsitt** [comment]
Since this change is live, don't we need to gather old deployment times now before they drop off the task list within AC?

**Comment by cory-skeers** [comment]
As we get the data collected, I'd be interested in looking at how we handle the comparison, since we'll have a fairly low sample size and there may be a decently wide variance depending on what's being deployed.

**Comment by mjoneill** [comment]
Adding some 2022 uptime reporting for a few of our sites. 

Top section is for the past 24 hours or so.  Recent events section goes back to start of 2022.    

![2022-uptime-coronavirus](https://user-images.githubusercontent.com/7144234/187949029-70592a39-44c2-4cf9-9967-5cfb3d60bc42.jpg)
![2022-uptime-education](https://user-images.githubusercontent.com/7144234/187949033-b1e02d6b-54e2-4551-8bcb-59660a7d2544.jpg)
![2022-uptime-uiowa](https://user-images.githubusercontent.com/7144234/187949041-59eea599-4930-471f-8e13-5cdee764b0e1.jpg)
![2022-uptime-pharmacy](https://user-images.githubusercontent.com/7144234/187949045-5879daae-9c50-40ce-afe5-2f30f756d30e.jpg)
![2022-uptime-tippie](https://user-images.githubusercontent.com/7144234/187949050-ef6d067f-8815-4d72-b4a1-a7e30bfe9c79.jpg)

**Comment by briand44** [comment]
Concern of performance hit is low. We have some metrics for length of downtime. Closing this.
