### ISSUE TITLE
Dentistry interactive map brand recommendations

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#5630]
- "Other than page header and footer what else might be needed to bring this page up to brand standards? Interactive Map 
- It is wildly inaccessible, but we're working on that, so just need brand recommendations right now, please.
- https://apps.dentistry.uiowa.edu/IACountyData

**Comment by bspeare** [comment]
@cory-skeers can you share the link to the example you mentioned?

**Comment by cory-skeers** [comment]
@bspeare I'd been hoping to be able to find a specific reference in any old class notes, but couldn't. I think it was an informal set of colors people tended to use and pass around when working on posters and reports.

I did find an example in a six-degree scale for a consulting project I'd worked on, with three degrees of desaturated gold and three degrees of darkening gray/black:
`c('#ffcd00', '#ccb85f','#e8d9ab','grey90','#878684','#000000')`
(I think 'grey90' would be '#e5e5e5' in hex).

**Comment by bspeare** [comment]
# Recommendations:

- Header: https://uids.brand.uiowa.edu/components/detail/iowa-bar--parent_site_name.html
- Footer: https://uids.brand.uiowa.edu/components/detail/footer.html
- Fonts: [Roboto](https://fonts.google.com/specimen/Roboto)
- Use brand colors: https://uids.brand.uiowa.edu/components/detail/colors.html
  - Try not to use red, blue, and green for font colors like on https://apps.dentistry.uiowa.edu/IACountyData/Home/CountyData?cName=greene&fips=19073.   Stick with the brand black and gray. 
- For the charts, use a six-degree color scale: three degrees of desaturated gold and three degrees of darkening gray/black
  - Something like ('#ffcd00', '#ccb85f','#e8d9ab','#e5e5e5','#878684','#000000')
- Design the tabs to look like tabs by moving them closer or more connected to the map?  They could use https://uids.brand.uiowa.edu/components/detail/tabs.html as an example.

**Comment by bspeare** [comment]
I have sent these recommendations to Viki.
