### ISSUE TITLE
White space gap between sections

### ISSUE THREAD

**Issue by bewoldt** [uiowa/uiowa#5631]
# Problem
Removing bottom spacing on a multi-column section that has cards will show a white space gap before the next section begins. Only happens on mobile screen sizes. 

<img width="700" alt="Screen Shot 2022-08-30 at 4 59 20 PM" src="https://user-images.githubusercontent.com/731952/187702978-39980a7e-d134-4eb8-8654-2cdabf80f61c.png">

example pages:
https://sandbox.prod.drupal.uiowa.edu/card-bg-color
https://admissions.uiowa.edu/first-year-visit-options

# Steps to reproduce

1. Create a new 2,3, or 4 column section with a background color.
2. Remove the bottom spacing from the section
3. Create a card to that section with the image position of left or right
4. Create a new section below with a background color and add any component

This might occur with components other than cards but haven't tested those.

**Comment by bspeare** [comment]
The card has a bottom margin hard-coded into the component.  I think this bug should be addressed in the work that will happen in https://github.com/uiowa/uiowa/issues/2670

**Comment by bspeare** [comment]
I think we are going to need to reopen this issue and work on it in https://github.com/uiowa/uiowa/issues/5849.    The current fix is causing other spacing issues for uiowa.edu so I am reverting this change in https://github.com/uiowa/uiowa/pull/5845/commits/75ff68d72dd921350ed757530a332592331a7da8, and hopefully this can addressed when we integrate the UIDS4 card.
