### ISSUE TITLE
SSL Certs for uiowa02

### ISSUE THREAD

**Issue by quamsta** [uiowa/uiowa#5632]
We need the following two certs made on uiowa02 for these already-provisioned sites:

- studentife.uiowa.edu (a wildcard cert for *.studentlife.uiowa.edu exists on uiowa02 already, but I believe according to @briand44, we also need one for the base domain, which we'll be using soon)
- wrac.uiowa.edu

**Comment by briand44** [comment]
This is done.

**Comment by quamsta** [comment]
Thanks @briand44
