### ISSUE TITLE
Investigate and remove or update Cloud API v1 calls

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5636]
API v1 will no longer be available after September 19th, 2022.

```
uiclas | prod | /v1/sites/prod:uiclas/envs/prod/domains.json | 3
 |   | /v1/sites/prod:uiclas/envs/prod/domains.json |  
uiowa703 | prod | /v1/sites/prod:uiowa703/envs/prod/domains/oneit.uiowa.edu/cache.json | 2
uiowa | prod | /v1/sites/prod:uiowa/envs.json | 1
uihealthcaresignage | prod | /v1/sites/prod:uihealthcaresignage/envs/prod/domains.json | 1
uiowa | prod | /v1/sites/prod:uiowa/envs/prod/domains.json | 1
uiowa01 | prod | /v1/sites/prod:uiowa01/envs.json | 1
uiowa02 | prod | /v1/sites/prod:uiowa02/envs/dev/domains.json | 1
uiowa01 | prod | /v1/sites/prod:uiowa01/envs/dev/domains.json | 1
uiowa02 | prod | /v1/sites/prod:uiowa02/envs/prod/domains.json | 1
uiowa03 | prod | /v1/sites/prod:uiowa03/envs/prod/domains.json | 1
uisignage | prod | /v1/sites/prod:uisignage/envs/prod/domains.json | 1
uiowa03 | prod | /v1/sites/prod:uiowa03/envs/dev/domains.json | 1
uisignage | prod | /v1/sites/prod:uisignage/envs/dev/domains.json | 1
uiowa703 | prod | /v1/sites/prod:uiowa703/envs/prod/domains/dining.uiowa.edu/cache.json | 1```

**Comment by briand44** [comment]
Do we happen to still be running the following commands anywhere or has anyone been manually running these commands?

- `drush ac-environment-list`
- `drush ac-domain-list`
- `drush ac-domain-purge`

According to https://cloudapi.acquia.com/, it looks like those commands would result in the hits to 
`/v1/sites/realm:mysite/envs/prod/domains.json` and
`/v1/sites/realm:mysite/envs.json`
`/v1/sites/realm:mysite/envs/prod/domains/foo.com/cache.json`

**Comment by briand44** [comment]
A couple things that come to mind here would be generating metadata for authentication, site counts. Site counts don't look like they are calling these though. Not seeing it in D7 metadata generator either but could be missing something there. Where/How do we generate metadata for D9?

**Comment by joewhitsitt** [comment]
Could it be Acquia DevDesktop?

**Comment by joewhitsitt** [comment]
Brian also had a thought while on the road: "Could it be Slack?" - Maybe, however, that integration is only accessible by Rick.

**Comment by briand44** [comment]
Potentially useful links
https://docs.acquia.com/cloud-platform/develop/api/migrate/
https://support-acquia.force.com/s/article/360043969514-Cloud-API-v1-EOL-Am-I-using-it-and-what-do-I-need-to-do

**Comment by joewhitsitt** [comment]
is it worth reaching out to Rick about the Slack stuff?

**Comment by briand44** [comment]
>is it worth reaching out to Rick about the Slack stuff?

I don't think so at this point. I did reach out to him about Acquia/Slack integration shortly after he left and I never got a response.

This was just a guess. If we end up thinking this is the most likely culprit, I believe we could remove the app and set it up again to get around the permissions issues.

Also, if this is the culprit, it wouldn't be the end of the world if this broke on Sept. 19th.

**Comment by briand44** [comment]
>Could it be Acquia DevDesktop?

It definitely could be, the article below explains how to check which version of Cloud API is being used with Dev Desktop. Mine is saying v2.

https://acquia.zendesk.com/hc/en-us/articles/360044089534-Switching-to-Acquia-Cloud-API-v2-with-Acquia-Dev-Desktop

**Comment by briand44** [comment]
I specifically asked Rick before he left if we were still using API v1 for anything and he said no. He could have missed something but it would seem more likely that it would be some one off instance of Dev Desktop or some other culprit rather than something in our codebase.

**Comment by briand44** [comment]
@mark-bennett-uiowa, visibility since the uiclas application was identified as well.

**Comment by GaryRidgway** [comment]
I have searched 701,702,702, and uiowa for this string, The pipes are ORs in a regex string.

`cloudapi.acquia.com/v1|drush ac-environment-list|drush ac-domain-list|drush ac-domain-purge|/v1/sites/realm:mysite/envs/prod/domains.json|/v1/sites/realm:mysite/envs.json|/v1/sites/realm:mysite/envs/prod/domains/foo.com/cache.json`

This encapsulates all the things said above, and I found no instances of anything across all applications

**Comment by mark-bennett-uiowa** [comment]
I was still using v1 on my Dev Desktop:
<img width="827" alt="Screen Shot 2022-09-06 at 11 57 07 AM" src="https://user-images.githubusercontent.com/3067017/188696788-bd58ead5-fc89-43cb-a245-dcf7ca919496.png">

I created a new API token and connected using v2, and everything seems to be working fine:
<img width="599" alt="Screen Shot 2022-09-06 at 12 00 56 PM" src="https://user-images.githubusercontent.com/3067017/188697023-6a2bbdb1-a259-47a9-b3d3-d30d97e05039.png">

I will let you know if I encounter any errors at all along the way. Thanks for the reminder!

**Comment by briand44** [comment]
@joewhitsitt do you have a way to update your script that runs `ac-domain-purge` or is your plan just to quit running that and use the Cloud UI to clear Varnish for those domains going forward?

**Comment by joewhitsitt** [comment]
i'll probably delete that script and just run it through the UI going forward.

cloud api v2 equivalent
```
POST /environments/{environmentId}/domains/{domain}/actions/clear-varnish
To clear the Varnish cache for a single specific domain.
```

**Comment by joewhitsitt** [comment]
Nevermind. Used my profdev time to update it using the Acquia CLI

**Comment by briand44** [comment]
Update from Acquia...
>I am working with the team to create a report to get more details, and will be rerunning it later this week.

**Comment by briand44** [comment]
Going to close this for now since we've addressed everything we are aware of. If a new report comes from Acquia that exposes additional v1 API calls we can open it back up.
