### ISSUE TITLE
Todo - Remove extra checks when `sitenow_v2` split is removed

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#5637]
# Motivation
As part of #5635 there was code added to check for the submit button the replicate form having already been disabled before setting a new message. This check was handled to accommodate the possibility of the `sitenow_p2lb` module being enabled and a message having already been set. Once `sitenow_v2` is removed, we can be sure that there is no longer a reason for that check to exist and it can be removed.

# Proposed solution

- Remove `!(isset($form['actions']['submit']['#disabled']) && $form['actions']['submit']['#disabled']) && `  from the check before a warning message is set.
- Remove ` && (!isset($data['tabs'][0]['replicate_ui.local_tasks:entity.node.replicate']['#access']) || $data['tabs'][0]['replicate_ui.local_tasks:entity.node.replicate']['#access'] !== FALSE)` from `uiowa_core_menu_local_tasks_alter`

**Comment by pyrello** [comment]
I think this can be closed now, since we decided to delay implementing replicate for pages in V2 until after the transition has been completed.

**Comment by joewhitsitt** [comment]
wouldn't this just be marked as blocked and part of the cleanup PR following the mandatory update
