### ISSUE TITLE
Allow Config Split Commands to be run on a single split

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#5652]
# Story

As a developer, I can run each of the functions in  https://github.com/uiowa/uiowa/blob/main/blt/src/Blt/Plugin/Commands/ConfigSplitCommands.php on a single split by providing an optional split argument.

# Proposed Solution

- [ ] Add an optional split argument that is checked before the foreach.

**Comment by pyrello** [comment]
I started to address this in #5625, although I only added it as an option to the feature split command.
