### ISSUE TITLE
Deprovision asg.clas.uiowa.edu site

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#5655]
Now that the new site alt.clas.uiowa.edu is in place and running smoothly, I need to deprovision the asg.clas.uiowa.edu site. Since this is something I have only done once or twice, I just want to make sure of the process:

Create a new PR
Run `blt umd --site=asg.clas.uiowa.edu` to remove the site from uiowa01.
Commit and push PR

Is this correct, or has this process changed recently? Is there anything else I need to run?

**Comment by joewhitsitt** [comment]
That should do it. The `umd` command was recently updated to remove files. https://github.com/uiowa/uiowa/pull/5244

Not sure if you need to backup beforehand: https://wiki.uiowa.edu/display/drupaldev/Backing+up+a+site+before+deletion

**Comment by mark-bennett-uiowa** [comment]
Thanks @joewhitsitt I should be good on the backup as it was all moved to the alt.clas.uiowa.edu site. I will push this PR up in the next 5-10 mins.
