### ISSUE TITLE
SiteNow updates news article - September

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#5660]
## Issue/Solution ##
Provide a "release notes" type article of finished/done features/updates and publish to website, then send out dispatch email.

- [x] Create draft and update the parking lot card with an edit link
- [x] Add "release notes" covering the month of v2/v3 default profile enhancements and webmaster/edit visible bug fixes.
  * See the previous month's article as an example.
  * Bullet points from demo stories slide per week: https://drive.google.com/drive/folders/1EehKUjxCbakaB9FchrGhAbaxuRbqyDGW?usp=sharing..
- [x] Get at least one team member to look over the draft before publishing.
- [x] Since the draft was started earlier, adjust the publish date/time, publish, get the link to the article.
- [x] Dispatch email with link to article. (To get access, send an email to dispatch-support@uiowa.edu to have the account provisioned. Provide your hawkid and mention the CSI:drupal group)
  * Modify SiteNow Announcements Template (tweak opening line, update the article link, any other editorial adjustments)
  * Create new communication off SiteNow Announcements campaign
    * Use SiteNow Announcements population, template, suppression list, bypass approval.
    * When scheduling, check the "archive" option so that there is an RSS instance we can use in the future. I don't think this can be done after the fact.
- [x] Turn off Dispatch "test mode" to send out email. 
- [x] Turn on Dispatch "test mode" after email is successfully sent.
- [x] Take a moment to check dispatch and google analytics on whether these articles are being read.
- [x] Create the next months's issue and copy all this bullet list into it, removing the checked boxes if any.

**Comment by bspeare** [comment]
https://sitenow.uiowa.edu/news/2022/10/updates-september

**Comment by joewhitsitt** [comment]
Based on the analytics work done on the previous issue, I wonder if we need to spend so much time on crafting the email message and article intro. Can we just turn this into more of a change-log and invite folks to reach out/attend demos if they want to learn more about a particular thing?

**Comment by bspeare** [comment]
@joewhitsitt I like that idea!

**Comment by bspeare** [comment]
@joewhitsitt how would this look?  It would be nice to reduce the steps involved here. 

Reduce the time to craft the article intro and just list:
- New features, bug fixes, site launches?

Reduce the time adjusting the Dispatch template:
- Create standard Dispatch template language that just links to https://sitenow.uiowa.edu/news showing a new article at the top of the list?

**Comment by bspeare** [comment]
Could remove the Dispatch step and instead advertise the monthly article in our Sprint Demo emails?  It would be an interesting experiment to try and then compare the analytics.

**Comment by joewhitsitt** [comment]
So the dispatch list and the ui-web lists are different lists of people.

If we moved away from dispatch for the monthly articles, I think at the very least we should send out one more saying we plan to spam them less but that big announcements will still be sent to this list and that if they want more regular updates, check the website, subscribe to the ui-web list and/or attend our demos.

**Comment by joewhitsitt** [comment]
Mainly, the idea of creating a warm-up paragraph for the article and email might be over the top for the amount of engagement we get and that our bullet items don't need to be borderline documentation.

**Comment by briand44** [comment]
Grooming - conversation... Start by making the communication more of a list and less of a story to speed up the process. If we still feel this takes to much effort, revisit getting rid of the monthly email and just send a communication to that list letting them know we will no longer be sending monthly updates and to just check the website.

**Comment by pyrello** [comment]
Next month's issue: https://github.com/uiowa/uiowa/issues/5817
