### ISSUE TITLE
Use smart_date min and max field settings for events block's range field.

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#5664]
# Story

As a developer, I can re-configure the smart date range field on the events block to use the new min/max field settings.

# Proposed solution (updated 10/11/2022)

- ~~Create separate issues to address undefined array keys for min/max and next hour default value when max is set. https://www.drupal.org/project/smart_date/issues/3300768#comment-14726415~~ being handled in the same issue.
- [x] Submit patches to the module for the two issues.
- [x] Test and implement next stable release of smart_date with the functionality above.
- [x] Update the the range field on the events block and remove the override code from layout_builder_custom.

**Comment by joewhitsitt** [comment]
When updating smart_date to 3.6+ it should resolve a deprecated code warning:

```
Calling static trait method Drupal\smart_date\SmartDateTrait::isAllDay is deprecated, it should only be called on a class using the trait in Drupal\smart_date\Plugin\Field\FieldWidget\SmartDateWidgetBase->massageFormValues() (line 285 of /mnt/www/html/uiowastg/docroot/modules/contrib/smart_date/src/Plugin/Field/FieldWidget/SmartDateWidgetBase.php)
```

This was noticed when streaming logs and workin with the uiowa_events block.

**Comment by e-marie-w** [comment]
Per #5824, waiting until min-max is added in smart_date 3.6.2

**Comment by joewhitsitt** [comment]
We were seeing that the default value was not working as before. Instead of the "next hour" setting it was using the max date.

**Comment by joewhitsitt** [comment]
actually, i am going to take one more look at this.

**Comment by joewhitsitt** [comment]
Looks like we have a typo that is causing the max to be used for the default value:

https://www.drupal.org/project/smart_date/issues/3300768#comment-14726415

**Comment by joewhitsitt** [comment]
Re-scoped based on standup discussion about upstream issues.

**Comment by joewhitsitt** [comment]
Created an MR https://www.drupal.org/project/smart_date/issues/3300768#comment-14739789

**Comment by joewhitsitt** [comment]
Took this opportunity to try https://github.com/shaal/DrupalPod which makes contributing a bit easier.

**Comment by joewhitsitt** [comment]
This patch was merged in. It would be nice to bring this in-scope of #5965

**Comment by joewhitsitt** [comment]
looks like we are on 3.6.1 currently so this worked on.
