### ISSUE TITLE
Update article docs with related content info

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#5665]
# Story
As a Sitenow user, I want to know more about what the related content field is on the article content type.

# Proposed solution
Update - https://sitenow.uiowa.edu/documentation/article-content-type

**Comment by joewhitsitt** [comment]
I don't think we have docs on the related by tag functionality that pre-dates this. That would be nice to add as well.

**Comment by GaryRidgway** [comment]
Wording updated here, hopefully it covers the initial intent and Joe's subsequent comment.
Draft:
https://sitenow.uiowa.edu/node/126/latest
Revision comparison:
https://sitenow.uiowa.edu/node/126/revisions/view/4651/4656/split_fields

**Comment by cory-skeers** [comment]
I added an extra `<h3>` level heading under "Relationships" as "Displaying Related Content." I thought the transition from tags to tags or referenced content got confusing, but that this might help. Let me know what you think of that change, and if that looks good I think it's ready to be published 👍

**Comment by GaryRidgway** [comment]
Looks good! I have published
