### ISSUE TITLE
Move to CKEditor 5

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#5667]
# Motivation

CKEditor 4 is being moved to a contrib module as part of Drupal 10.x and CKEditor 5 will be a core stable module starting in Drupal 9.5.x. I believe it has a semi-automated upgrade path. See details here: https://www.drupal.org/node/3308362

If we move to CKEditor 5 prior to moving to D10, then we won't have to temporarily include the CKEditor 4 contrib module. 

```[tasklist]
# Proposed solution
- [ ] https://github.com/uiowa/uiowa/issues/6061
- [x] Test out semi-automatic upgrade path
- [ ] https://github.com/uiowa/uiowa/issues/7123
- [x] Compare functionality and document any possible regressions
- [x] Re-write any CKEditor JS customizations
- [x] Re-write/replace `FilterIframe` class to be compatible or find a new solution for embedding iframes
- [x] Update `responsive_table_filter` module to 2.0.x
- [x] `iframe_title_filter` module still functioning
- [x] `<pre>` tag
- [x] Test oembed
- [x] Reset formatting not quite working as expected
- [x] `<hr class>` issue
- [x] Transition or move any styles (e.g table styles)
- [x] Crazy markup testing, including developer placed embeds/iframes
- [x] confirm that allowed attributes aren't being stripped out of config (span role, iframe sandbox)
- [x] check that the code block languages work as expected, otherwise remove certain language options (html, javascript, php)
- [ ] Dismiss linkit balloon from image gallery media add form
- [x] Update documentation
- [ ] Communication ahead of deployment pointing out things like `hr` `ul` `ol`
```
- Create follow-up task to remove CKEditor 4 contrib module

**Comment by pyrello** [comment]
Updated IS to clarify that we should do this work after upgrading to Drupal 9.5.x and before upgrading to Drupal 10.0.x. If we do this in that timeframe, we do not need a followup task to remove CKEditor 4 contrib module.

**Comment by joewhitsitt** [comment]
As far as I know, we will need Linkit to be ready. That is our big non-core addition to the WYSIWYG. https://www.drupal.org/project/linkit/issues/3232190

What worries me though is that we are now using https://www.drupal.org/project/linkit_media_library to link files and I don't know what the upgrade will look like for that.

**Comment by pyrello** [comment]
> What worries me though is that we are now using https://www.drupal.org/project/linkit_media_library to link files and I don't know what the upgrade will look like for that.

I've been playing around with CKEditor 5 a bit. It looks like the insert Media document functionality works as would be expected in the new version, so the workaround using `linkit_media_library` should no longer be necessary. Unfortunately, the way that that module handles inserting links does not match up with what it will need to look like after we switch over since the links will just use a `<drupal-media>` element in CKEditor 5, so we'll need an update hook to transition all our text areas with a media button to the new format.

**Comment by joewhitsitt** [comment]
The main reason was for files to be inline (bulleted list, etc) instead of blocks. Has that been addressed with the media button? I can't seem to find the issue related to that.

**Comment by pyrello** [comment]
> The main reason was for files to be inline (bulleted list, etc) instead of blocks. Has that been addressed with the media button? I can't seem to find the issue related to that.

Ah. No, it doesn't appear that it has been addressed. Even when editing the source to place the `<drupal-media>` element in a bulleted list, it gets moved outside of it when you click out of source mode.

I guess I thought we used that plugin because the linking was going to the media element rather than the file.

**Comment by pyrello** [comment]
> As far as I know, we will need Linkit to be ready. That is our big non-core addition to the WYSIWYG. https://www.drupal.org/project/linkit/issues/3232190

At least this appears to be mostly done.

**Comment by pyrello** [comment]
> The main reason was for files to be inline (bulleted list, etc) instead of blocks. Has that been addressed with the media button? I can't seem to find the issue related to that.

This issue appears to be about that: https://www.drupal.org/project/drupal/issues/3168966

**Comment by joewhitsitt** [comment]
Good find. Thanks

**Comment by bspeare** [comment]
This CKEditor 5 feature looks awesome https://www.drupal.org/project/drupal/issues/3274635 and would be very useful after having this conversation with @mkyoder https://iowaweb.slack.com/archives/C0164FNN1PV/p1669916827814409.

**Comment by pyrello** [comment]
Did a little bit of poking at this (using #6526 to be able to test it out). By updating the `responsive_table_filter` module and adding a patch from [this issue](https://www.drupal.org/project/drupal/issues/3326778), I was able to get the "Filtered HTML" configuration page to a point where it was not showing any errors that would prevent it from being submitted. However, upon submitting the page, there is this error:

![Screenshot 2023-06-19 at 3 19 41 PM](https://github.com/uiowa/uiowa/assets/709009/2460784e-c2ff-462e-afb0-52848711e74f)

This appears to be happening because the type of filter we are using for our `FilterIframe` class is triggering a new core constraint validation:
https://github.com/uiowa/uiowa/blob/439b866dde81b2265b2c13dc82d18bd5b560c3e7/docroot/modules/custom/uiowa_core/src/Plugin/Filter/FilterIframe.php#L17

https://git.drupalcode.org/project/drupal/-/blob/9.5.x/core/modules/ckeditor5/src/Plugin/Validation/Constraint/FundamentalCompatibilityConstraintValidator.php#L145-176

As best I can tell, the validator is expecting a list of tags and is causing the error because of our list of allowed sources doesn't meet the expected format.

I'm not sure if this means we need to change the filter type (for what it is doing, it does seem to be the right type of filter from a standpoint of that it is restricting HTML that can be used). Alternately, we might want to consider moving to using a media entity for embeds and using a provider list to handle this (making it the media ecosystem's problem instead of CKEditor).

**Comment by pyrello** [comment]
I don't think this is blocked anymore.

**Comment by pyrello** [comment]
Hmm... maybe this is still blocked: https://www.drupal.org/project/linkit_media_library/issues/3329877

Given the fact that no one who needs to be responding on that issue has responded recently, I'm wondering if we are going to have to find our own path through this to get it done by the end of the year.

**Comment by joewhitsitt** [comment]
> Hmm... maybe this is still blocked: https://www.drupal.org/project/linkit_media_library/issues/3329877
> 
> Given the fact that no one who needs to be responding on that issue has responded recently, I'm wondering if we are going to have to find our own path through this to get it done by the end of the year.

I think we should try our hand at CKEditor plugin making. We will also want to make sure `editor_advanced_link` still works. If it does, we may have a solution to reference for this issue.

People like their inline media references which is the main reason we adopted this module. AFAIK, the core solution is still in development.

**Comment by GaryRidgway** [comment]
Here is a list of changes that I am noticing
- Font size 19.2px -> 16px
- Padding has been added around text
- There is no “Maximize” button
- There is no “Show layout and tags” button
- There is no bar at the bottom to tell you what element you are on
- “Powered by cke5” on focus is strange

**Comment by GaryRidgway** [comment]
Adding comments here about what all else needs to be done so that if I am not the one to finish this issue, the person that comes after me has some idea of where to start.
___
<details><summary> <h2>Re-write any CKEditor JS customizations</h2></summary>

<p>

> I have gotten a fair amount of this done, but there are a few more things to do. These should probably boh be moved in to [the plugin file](https://github.com/uiowa/uiowa/blob/ckeditor5/docroot/modules/custom/sitenow_media_wysiwyg/js/ckeditor5_plugins/sitenowMediaWysiwyg/src/index.js), and their code/files removed afterwards.

<details><summary><h3>Saving nodes with the source view selected:</h3></summary> 

https://github.com/uiowa/uiowa/blob/99b6a4ef217e81eecacf374cbfe51d07f8f61327/docroot/modules/custom/layout_builder_custom/js/layout_builder_custom.overrides.js#L60-L81

</details> 
accounted for in https://github.com/uiowa/uiowa/pull/7132/commits/ff14dd1029e583ef8f9a43a4aa01233b05fd79c1

<details><summary><h3>Ensure that writinguniversity.org gets the serif font in the WYSIWYG:</h3></summary>

https://github.com/uiowa/uiowa/blob/99b6a4ef217e81eecacf374cbfe51d07f8f61327/docroot/modules/custom/sitenow_media_wysiwyg/js/ckeditor_config.js#L1-L32
</details> 
accounted for in https://github.com/uiowa/uiowa/pull/7132/commits/2b685ba94b9f144ca53472eece943875634be4d8

</p>
</details> 

___

<details><summary><h2>Test OEmbed</h2></summary>
<p>

> It seems that [panopto](https://sitenow.uiowa.edu/documentation/media/ui-capture-panopto) is working fine, but [facebook, twitter, and instagram are not working.](https://github.com/uiowa/uiowa/blob/ckeditor5/docroot/modules/custom/sitenow_media_wysiwyg/js/ckeditor5_plugins/sitenowMediaWysiwyg/src/index.js) Twitter renders fine when the node is saved, but in the WYSIWYG it is not. It also seems as though there is no markup being generated in the WYSIWYG for them either.

</p>
</details> 

___

<details><summary><h2>Transition or move any styles</h2></summary>
<p>

> I think the largest chunk of his is transitioning the OEmbed styles. However, I do recommend searching for other styles that need transitioning.

<details><summary><h3>The OEmbed styles can be found here:</h3></summary>

https://github.com/uiowa/uiowa/blob/99b6a4ef217e81eecacf374cbfe51d07f8f61327/docroot/themes/custom/uids_base/scss/sitenow_wysiwyg.scss#L36-L100


</details> 

</p>
</details> 

___
<details><summary> <h2>`pre` tag</h2></summary>

<p>

> In CKE4 we have a text style that allows you to put in a serifed font inside of a `pre` tag. This needs to be transitioned, and has not been investigated yet.

</p>
</details> 


___
After all of this, we must TEST CRAZY HTML

**Comment by joewhitsitt** [comment]
>In CKE4 we have a text style that allows you to put in a serifed font inside of a pre tag. This needs to be transitioned, and has not been investigated yet.

The styles dropdown requires a class with the `<pre>` tag to be available as an option. There is no dedicated button to add to the toolbar for this. The `<pre>` tag is still allowed however by editing source so existing content should be retained. Copy/paste into source also works. The code block button wraps a `<code>` tag with a `<pre>` tag. The user can choose plain text.

<img width="1254" alt="Screenshot 2023-12-15 at 10 54 18 AM" src="https://github.com/uiowa/uiowa/assets/4663676/5aa6b9c0-789a-4b4c-8d92-37c4af82fa29">
<img width="1075" alt="Screenshot 2023-12-15 at 10 54 30 AM" src="https://github.com/uiowa/uiowa/assets/4663676/c61839ec-0d47-444c-b7ef-af3231b4fe4d">

I don't think any further action is needed except for updating documentation which Sean mentioned in our huddle.

**Comment by joewhitsitt** [comment]
Social media (facebook, instagram, twitter) render. Facebook and Instagram require the API keys locally. https://iowa.sharepoint.com/sites/drupal-developer-documentation/SitePages/Miscellaneous/Facebook_Instagram%20Graph%20API%20for%20oEmbed/Facebook_Instagram%20Graph%20API%20for%20oEmbed.aspx

Facebook and Instagram show as blockquotes within the editor. Twitter still has this issue: https://github.com/uiowa/uiowa/issues/2147 but is even more noticeable because there isn't a yellow square so when ckeditor is not focused on it, it is just blank white space.

Facebook, Twitter, Instagram in order:

<img width="521" alt="Screenshot 2023-12-15 at 11 12 59 AM" src="https://github.com/uiowa/uiowa/assets/4663676/864794f0-3fda-4894-bbdd-ad2269270d9a">
<img width="610" alt="Screenshot 2023-12-15 at 11 13 22 AM" src="https://github.com/uiowa/uiowa/assets/4663676/fa8bdf4f-57dd-4f66-bb05-3da6472fdd08">
<img width="576" alt="Screenshot 2023-12-15 at 11 13 38 AM" src="https://github.com/uiowa/uiowa/assets/4663676/77a19000-0323-4966-9879-455560921628">

**Comment by joewhitsitt** [comment]
Ran into an issue with Linkit. What was an issue with CkEditor 4 is slightly different with CkEditor 5.


https://github.com/uiowa/uiowa/assets/4663676/bc3e0770-e8d0-446c-b13d-576f5a37c40f

**Comment by joewhitsitt** [comment]
From what I have been able to test, oEmbed is working fine. Added some styles to provide basic placeholder for Twitter resolving a longstanding issue unrelated to the upgrade.

<img width="867" alt="Screenshot 2023-12-18 at 2 40 00 PM" src="https://github.com/uiowa/uiowa/assets/4663676/1b965fc1-7f14-4cf7-8513-00673b43e8b2">

**Comment by joewhitsitt** [comment]
>Reset formatting not quite working as expected

Having troubles reproducing the button bug Alan, Sean and I witnessed on Friday. Might have been a symptom of the lagging issues I was having while sharing screen. I am able to create a link, style a button, move on and not have the button markup follow me. The remove formatting button does not apply to the styles dropdown (only things like italic, bold, etc.).

**Comment by joewhitsitt** [comment]
Getting some nasty browser crashing errors trying to edit the kitchen sink page.

https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-matcher-pattern-deprecated-attributes-class-key

https://sandbox.uiowa.ddev.site/node/86/layout

**Comment by joewhitsitt** [comment]
In trying to track down the culprit behind https://github.com/uiowa/uiowa/issues/5667#issuecomment-1861638731 I am noticing that `<hr class="element--spacer-thin" />` is getting stripped even though filtered_html `hr class` is allowed. This applies to `<br>` as well.

https://www.drupal.org/project/drupal/issues/3398223

Confirmed that empty _inline_ elements are not stripped https://www.drupal.org/project/drupal/issues/3337298

aka `<span class>`

**Comment by joewhitsitt** [comment]
Also noting that though `<div>` is allowed and can by styled as alerts. You can not type paragraph text and select the alert style from the dropdown and have it auto change to `div`. Instead you must first switch to source. Change from p to div and switch back to rich text to then apply the alert style option. There is no `div` button and isn't available in the heading dropdown.

https://www.drupal.org/project/drupal/issues/3362451

**Comment by joewhitsitt** [comment]
Seems like the switch from source then save issue might be a timing one: https://www.drupal.org/project/drupal/issues/3396742

**Comment by joewhitsitt** [comment]
At least for me, the presence of a fontawesome icon markup appears to be causing lag to the point where the page becomes unresponsive and I am asked to wait/kill the tab.

https://sandbox.uiowa.ddev.site/ckeditor-fontawesome-test
https://sandbox.uiowa.ddev.site/ckeditor-fontawesome-test-without

They are working toward compatibility with ckeditor5, but the work is centered around the plugin and not just rendering icons within the rich text: https://www.drupal.org/project/fontawesome/issues/3274028

It looks like in sandbox.prod.drupal.uiowa.edu/ckeditor-fontawesome-test we aren't rendering the icons in the editor. That might be the solution here.

**Comment by joewhitsitt** [comment]
Looks like I am to blame for auto loading the fontawesome assets. https://github.com/uiowa/uiowa/pull/3322

By unchecking this, it is not causing issues with ckeditor as noted in https://github.com/uiowa/uiowa/issues/5667#issuecomment-1863427580. I am going to sync, clear all the things and test, but I think we are still calling the library as needed (social media menu, ckeditor, frontend components).

**Comment by joewhitsitt** [comment]
So it looks like we have done a lot of spot treatment of `hr` styling in the WYSIWYG. Seeing a lot of gold, centered type stuff for admissions, etc.

I tried to just create a list of allowed options using the style dropdown but it is still stripped out.

Started a thread here to see if others are impacted by this and have workarounds: https://drupal.slack.com/archives/C01GWN3QYJD/p1703025183849849

The update hook to `div` would probably be what allows us to move forward to meet the security deadline for v2/v3. Downside is new technical debt and doesn't allow new `<hr>` with classes.

**Comment by joewhitsitt** [comment]
Tested some placed embeds:

https://recserv.uiowa.ddev.site/intramural-sports (script)
https://recserv.uiowa.ddev.site/groupfit (iframe)
https://osc.uiowa.ddev.site/live/uihc (iframe) _it would be neat if there was a live stream going on, but the js is loading enough to indicate there is not_

For each one, I went in to edit, toggled source and saved it to see if anything vital was getting stripped.

**Comment by joewhitsitt** [comment]
Callout on https://now.uiowa.ddev.site/news/2023/10/reminder-familiarize-yourself-uis-extreme-weather-plan still works. There is no background color in the editor but that is the same as PROD. Renders as expected.

**Comment by joewhitsitt** [comment]
Created an update hook for the `hr` issue. https://github.com/uiowa/uiowa/pull/7132/commits/6d8d0916c3bd70f1090665a45ff6270f99427274, https://github.com/uiowa/uiowa/pull/7132/commits/6f44a7801fe0ff511726654fcf809b75dda7df9d

Seems to be working quite nicely. Quite thankful for the previous update hook (sitenow_update_9067) to find/replace alert classes!

<img width="700" alt="Screenshot 2023-12-20 at 11 40 39 AM" src="https://github.com/uiowa/uiowa/assets/4663676/737c641b-29e1-479e-857f-4c4ac8aee589">
<img width="1160" alt="Screenshot 2023-12-20 at 11 41 04 AM" src="https://github.com/uiowa/uiowa/assets/4663676/eff6a1e4-e34f-46de-9be2-5e680c8a0af7">

**Comment by bspeare** [comment]
@joewhitsitt looks good.  I do like the update of removing and deprecating some of the design elements like the `element--spacer-gold--centered` since we now have the underline on the heading.   Any thoughts that we only preserve the `element--spacer-separator` and `element--spacer-thin`.   Ideally, we would convert the default `hr` styles to `element--spacer-thin` and reduce the need for that extra class and be able to convert the `hr` back to the actual markup when it is supported: https://github.com/uiowa/uids/blob/4.x/src/assets/scss/paragraph.scss#L121-L138

**Comment by joewhitsitt** [comment]
@bspeare i might not completely follow you, but i am open to using this opportunity to clean some stuff up. just feeling happy knowing there won't be undesired data loss here because of the upgrade.

**Comment by bspeare** [comment]
Basically, I would like to clean up the `element--spacer-gold--centered` usage because we have a headline class for that. 
- Remove all hrs with `element--spacer-gold--centered` and manually set headline classes on admissions. 
- Keep `element--spacer-separator` and `element--spacer-thin` and possibly convert back to `<hr />` tags if allowed in the future.

**Comment by joewhitsitt** [comment]
>Remove all hrs with element--spacer-gold--centered and manually set headline classes on admissions.

Are you concerned about this being used anywhere else in the wild or are you hoping to get a report so that we manually spot check and adjust any instances?

**Comment by bspeare** [comment]
I'm not concerned and I'd be happy if they go away.   I think most of these in the wild I have added to sites in our early days.

**Comment by joewhitsitt** [comment]
At EoD, we are going to see if we can audit usage of this `element--spacer-gold--centered` class to determine our next steps.

Also, found that CKEditor's object for table captions is well not a `<caption>`, but a `<figcaption>` outside of the `<table>`... Need to style around this.

<img width="833" alt="Screenshot 2023-12-20 at 4 01 02 PM" src="https://github.com/uiowa/uiowa/assets/4663676/6f449e99-e562-4662-9e2c-7086a6fc1ac6">

**Comment by pyrello** [comment]
> At EoD, we are going to see if we can audit usage of this `element--spacer-gold--centered` class to determine our next steps.

Here is the query for checking the text area block text area field revisions:
```sql
SELECT * FROM block_content_revision__field_uiowa_text_area WHERE field_uiowa_text_area_value LIKE '%element--spacer-gold%' LIMIT 5
```

**Comment by pyrello** [comment]
Some initial results:
<details>
<summary><code>./vendor/bin/blt ume "sqlq \"SELECT count(*) FROM block_content_revision__field_uiowa_text_area WHERE field_uiowa_text_area_value LIKE '%element--spacer-gold%'\""</code></summary>
<pre>
You will execute 'drush sqlq "SELECT count(*) FROM block_content_revision__field_uiowa_text_area WHERE field_uiowa_text_area_value LIKE '%element--spacer-gold%'"' on all multisites. Are you sure? (y/n) y
Executing on 3ddesign.studio.uiowa.edu...
0

Executing on 47things.uiowa.edu...
0

Executing on 91stmeridian.iwp.uiowa.edu...
0

Executing on academics.athletics.uiowa.edu...
0

Executing on ace.uiowa.edu...
0

Executing on admissions.uiowa.edu...
22

Executing on afpcc.org.uiowa.edu...
0

Executing on amcs.uiowa.edu...
0

Executing on andersen.lab.uiowa.edu...
0

Executing on anunsettledbody.sites.uiowa.edu...
0

Executing on appliedphys.lab.uiowa.edu...
0

Executing on arsc.lab.uiowa.edu...
0

Executing on audiogenomics.lab.uiowa.edu...
0

Executing on avclub.org.uiowa.edu...
0

Executing on awards.studentlife.uiowa.edu...
0

Executing on basinanalysis.lab.uiowa.edu...
0

Executing on bcbl.lab.uiowa.edu...
0

Executing on bhattacherjee.lab.uiowa.edu...
0

Executing on blsa.org.uiowa.edu...
0

Executing on boes.lab.uiowa.edu...
0

Executing on camps.athletics.uiowa.edu...
0

Executing on campuscouncil.stanleymuseum.uiowa.edu...
0

Executing on car.lab.uiowa.edu...
0

Executing on carvour.lab.uiowa.edu...
0

Executing on cerebralvascular.lab.uiowa.edu...
0

Executing on cerebrovascular.lab.uiowa.edu...
0

Executing on cgsa.org.uiowa.edu...
0

Executing on chaurasia.lab.uiowa.edu...
0

Executing on cheatum.lab.uiowa.edu...
0

Executing on chinesereadingworld.sites.uiowa.edu...
0

Executing on chowdhury.lab.uiowa.edu...
0

Executing on chtc.sites.uiowa.edu...
0

Executing on cjones.iihr.uiowa.edu...
0

Executing on cld.lab.uiowa.edu...
0

Executing on collections.pharmacy.uiowa.edu...
0

Executing on comeron.lab.uiowa.edu...
0

Executing on compliance.athletics.uiowa.edu...
0

Executing on counseling.uiowa.edu...
0

Executing on csars.org.uiowa.edu...
0

Executing on csomaycenter.uiowa.edu...
0

Executing on csw.uiowa.edu...
0

Executing on cuhal.lab.uiowa.edu...
0

Executing on currents.iihr.uiowa.edu...
0

Executing on dailey.lab.uiowa.edu...
0

Executing on dei.athletics.uiowa.edu...
0

Executing on deroo.lab.uiowa.edu...
0

Executing on developmental-psychopathology.lab.uiowa.edu...
0

Executing on dietrich.lab.uiowa.edu...
0

Executing on eberl.lab.uiowa.edu...
0

Executing on education.uiowa.edu...
5

Executing on efre.iihr.uiowa.edu...
0

Executing on ejanderson.lab.uiowa.edu...
0

Executing on emfisis.physics.uiowa.edu...
0

Executing on engage.uiowa.edu...
0

Executing on engagement.uiowa.edu...
0

Executing on enrollment.uiowa.edu...
0

Executing on executive.jobs.uiowa.edu...
0

Executing on fiegel.lab.uiowa.edu...
0

Executing on firstgen.uiowa.edu...
0

Executing on folland.lab.uiowa.edu...
0

Executing on forbes.lab.uiowa.edu...
0

Executing on freementalhealthclinic.org.uiowa.edu...
0

Executing on freespeech.uiowa.edu...
0

Executing on fritzsch.lab.uiowa.edu...
0

Executing on frrbp.medicine.uiowa.edu...
0

Executing on fskiff.lab.uiowa.edu...
0

Executing on ftoor.lab.uiowa.edu...
0

Executing on futureofficework.sites.uiowa.edu...
0

Executing on fys.uiowa.edu...
0

Executing on gaine.lab.uiowa.edu...
0

Executing on gconstantinescu.iihr.uiowa.edu...
0

Executing on getinvolved.uiowa.edu...
0

Executing on gis.sites.uiowa.edu...
0

Executing on glefevre.iihr.uiowa.edu...
0

Executing on govrel.uiowa.edu...
0

Executing on grad.admissions.uiowa.edu...
18

Executing on grantwood.uiowa.edu...
0

Executing on gravbox.sites.uiowa.edu...
0

Executing on grok.lab.uiowa.edu...
0

Executing on gvillarini.iihr.uiowa.edu...
0

Executing on gwsstellmagazine.sites.uiowa.edu...
0

Executing on hawkeyecaucus.com...
0

Executing on hawkit.athletics.uiowa.edu...
0

Executing on healthydata.sites.uiowa.edu...
0

Executing on hhpatuiowa.org.uiowa.edu...
0

Executing on historyoftechnology.lab.uiowa.edu...
0

Executing on historyofuigeography.sites.uiowa.edu...
0

Executing on hot.lab.uiowa.edu...
0

Executing on huang.lab.uiowa.edu...
0

Executing on humanimmunology.sites.uiowa.edu...
0

Executing on iddrc.uiowa.edu...
0

Executing on iihr.uiowa.edu...
0

Executing on iisc.uiowa.edu...
0

Executing on imfaculty.sites.uiowa.edu...
0

Executing on imu.uiowa.edu...
3

Executing on inclusionteam.uiowa.edu...
0

Executing on iowafloodmaps.iihr.uiowa.edu...
0

Executing on iowajpec.org...
0

Executing on iowaneuroscienceclub.org.uiowa.edu...
0

Executing on ipol.lab.uiowa.edu...
0

Executing on ishla.org.uiowa.edu...
0

Executing on italymba.tippie.uiowa.edu...
0

Executing on itprivacy.uiowa.edu...
0

Executing on iywp.org...
0

Executing on jprineas.lab.uiowa.edu...
0

Executing on jtucker.lab.uiowa.edu...
0

Executing on kang.lab.uiowa.edu...
0

Executing on kawai.lab.uiowa.edu...
0

Executing on kennelty.lab.uiowa.edu...
0

Executing on kliemann.lab.uiowa.edu...
0

Executing on kumar.lab.uiowa.edu...
0

Executing on laborcenter.uiowa.edu...
0

Executing on lamp-mission.sites.uiowa.edu...
0

Executing on learning.uiowa.edu...
0

Executing on licensing.uiowa.edu...
0

Executing on lungimaging.sites.uiowa.edu...
0

Executing on luo.lab.uiowa.edu...
0

Executing on lweber.iihr.uiowa.edu...
0

Executing on mailloux.lab.uiowa.edu...
0

Executing on mcallister.lab.uiowa.edu...
0

Executing on mccleery.lab.uiowa.edu...
0

Executing on messingham.lab.uiowa.edu...
0

Executing on mikiw2022.pharmacy.uiowa.edu...
0

Executing on mnfreund.sites.uiowa.edu...
0

Executing on neiman.lab.uiowa.edu...
0

Executing on newmoonmagazine.org.uiowa.edu...
0

Executing on newstudents.uiowa.edu...
0

Executing on nizar.lab.uiowa.edu...
0

Executing on nlp.uiowa.edu...
0

Executing on nsfurmsts.sites.uiowa.edu...
0

Executing on nsslha.org.uiowa.edu...
0

Executing on nursing.uiowa.edu...
0

Executing on nutrition.athletics.uiowa.edu...
0

Executing on obgynnewsletter.sites.uiowa.edu...
0

Executing on obgynprotocols.sites.uiowa.edu...
0

Executing on ofirl.lab.uiowa.edu...
0

Executing on ohsc.lab.uiowa.edu...
0

Executing on oniowa.uiowa.edu...
0

Executing on parents.uiowa.edu...
3

Executing on passport.uiowa.edu...
0

Executing on peate.lab.uiowa.edu...
0

Executing on pediatricaudiology.lab.uiowa.edu...
0

Executing on pennathur.lab.uiowa.edu...
0

Executing on perlman.lab.uiowa.edu...
0

Executing on pharmacy.uiowa.edu...
101

Executing on physicsresearch.sites.uiowa.edu...
0

Executing on pinnaro.lab.uiowa.edu...
0

Executing on prahlad.lab.uiowa.edu...
0

Executing on presidentialsearch.uiowa.edu...
6

Executing on provost.uiowa.edu...
0

Executing on psycholinguistics.lab.uiowa.edu...
0

Executing on publishing-gallery.iwp.uiowa.edu...
0

Executing on quenchiowa.org.uiowa.edu...
0

Executing on reconnect.psychology.uiowa.edu...
0

Executing on recserv.uiowa.edu...
0

Executing on reinhardt.lab.uiowa.edu...
0

Executing on reno.sites.uiowa.edu...
0

Executing on resch.lab.uiowa.edu...
0

Executing on saa.org.uiowa.edu...
0

Executing on sabharwal.lab.uiowa.edu...
0

Executing on salondeclase.sites.uiowa.edu...
0

Executing on sandbox.uiowa.edu...
10

Executing on schnieders.lab.uiowa.edu...
0

Executing on scholardev.sites.uiowa.edu...
0

Executing on screendancefest.dance.uiowa.edu...
0

Executing on sds.studentlife.uiowa.edu...
8

Executing on se.iowastem.org...
0

Executing on shawgroup.lab.uiowa.edu...
0

Executing on shpe.org.uiowa.edu...
0

Executing on shse.iwp.uiowa.edu...
0

Executing on silkroutes.iwp.uiowa.edu...
0

Executing on sla2021.conference.uiowa.edu...
0

Executing on slc.studentlife.uiowa.edu...
0

Executing on slusarski.lab.uiowa.edu...
0

Executing on song.lab.uiowa.edu...
0

Executing on sportsmedicine.athletics.uiowa.edu...
0

Executing on sppa.uiowa.edu...
0

Executing on stanleymuseum.uiowa.edu...
0

Executing on stephens.lab.uiowa.edu...
0

Executing on strategicplan.uiowa.edu...
0

Executing on strength.athletics.uiowa.edu...
0

Executing on studentlegal.uiowa.edu...
2

Executing on studentlife.uiowa.edu...
0

Executing on students.tippie.uiowa.edu...
0

Executing on studentsuccess.uiowa.edu...
0

Executing on studentwellness.uiowa.edu...
0

Executing on success.course.uiowa.edu...
0

Executing on teachonline.uiowa.edu...
0

Executing on theatrelobby.studio.uiowa.edu...
0

Executing on tippie.uiowa.edu...
0

Executing on tippieconsultingclub.org.uiowa.edu...
0

Executing on transportation.uiowa.edu...
0

Executing on tutor.uiowa.edu...
0

Executing on uichr.uiowa.edu...
0

Executing on uiems.org.uiowa.edu...
0

Executing on uimsa.org.uiowa.edu...
0

Executing on uip.pharmacy.uiowa.edu...
0

Executing on uiprehealth.conference.uiowa.edu...
0

Executing on uisdaa.org.uiowa.edu...
0

Executing on uisps.org.uiowa.edu...
0

Executing on uisrm-internship.sites.uiowa.edu...
0

Executing on umallik.lab.uiowa.edu...
0

Executing on uppu.lab.uiowa.edu...
0

Executing on usg.uiowa.edu...
0

Executing on vakhtangidarjania.studio.uiowa.edu...
0

Executing on ventilator.course.uiowa.edu...
0

Executing on vote.uiowa.edu...
0

Executing on waldschmidt.lab.uiowa.edu...
0

Executing on webcommunity.sites.uiowa.edu...
24

Executing on weber.lab.uiowa.edu...
0

Executing on wei.lab.uiowa.edu...
0

Executing on weiss.lab.uiowa.edu...
0

Executing on whitmanweb.iwp.uiowa.edu...
0

Executing on wild.education.uiowa.edu...
0

Executing on windschitl.lab.uiowa.edu...
0

Executing on wkrajewski.iihr.uiowa.edu...
0

Executing on wrac.uiowa.edu...
0

Executing on yahr.lab.uiowa.edu...
0

Executing on youth.dance.uiowa.edu...
2
</pre>
</details>

Usage is pretty light, but not nothing.

**Comment by joewhitsitt** [comment]
Should we adjust to target the current revision `block_content__field_uiowa_text_area` table instead, run on each app and take note which sites to send an email too?

**Comment by pyrello** [comment]
> Should we adjust to target the current revision `block_content__field_uiowa_text_area` table instead, run on each app and take note which sites to send an email too?

I mean, if we are serious about checking in with the sites that might be affected, then I think we need to target any text area with a compatible filter format. This is why creating a report command would ultimately be a way to get the whole list.

**Comment by joewhitsitt** [comment]
So then I guess I am confused as to the next step. Remove the class in the update hook? More serious scan? Communication? Though "light," that sample was more than I was expecting.

admissions
education.uiowa.edu
grad.admissions.uiowa.edu
imu.uiowa.edu
parents.uiowa.edu
pharmacy.uiowa.edu
studentlegal.uiowa.edu
webcommunity.sites.uiowa.edu
youth.dance.uiowa.edu

**Comment by bspeare** [comment]
@joewhitsitt I'm fine with converting it to a `<div>` and keeping the style around.

**Comment by joewhitsitt** [comment]
>Dismiss linkit balloon from image gallery media add form

I temporarily removed the patch for linkit_media_library and this no longer occurs.


https://github.com/uiowa/uiowa/assets/4663676/bfd969d7-a59d-4ff3-8e8c-c8475ad69e5c

**Comment by joewhitsitt** [comment]
Might now be blocked to avoid data loss with an upgrade to core 10.2

https://www.drupal.org/project/drupal/issues/3410303

**Comment by joewhitsitt** [comment]
The code block works as long as you don't use the source view to write your html, javascript, php. That stuff gets stripped when switched back to rich text. The rich text editor properly escapes the code.

```
<pre><code class="language-html">&lt;strong&gt;hello&lt;/strong&gt;
&lt;script&gt;
alert('asdf');
&lt;/script&gt;</code></pre>
```

**Comment by bspeare** [comment]
I added some testing comments at https://github.com/uiowa/uiowa/pull/7132#issuecomment-1868016673 that we will need to consider before moving forward with this.

**Comment by joewhitsitt** [comment]
Testing 10.1.7 with Linkit and Editor Advanced Link (no linkit_media_library) to see if the weird link balloon dialog issues occur there.

**Comment by joewhitsitt** [comment]
Update to ^^. Seeing https://github.com/uiowa/uiowa/issues/5667#issuecomment-1866676436 within a normal text area block within the layout builder tray. Saving the block and opening it back up closes the persistent balloon. Again, removing the patch also solves the issue.

Hoping to get some help from @GaryRidgway and @pyrello tomorrow.

**Comment by joewhitsitt** [comment]
It looks like editor_advanced_link is adjusting how they implement which may help how linkit_media_library is added as well.

https://www.drupal.org/project/editor_advanced_link/issues/3371633

**Comment by joewhitsitt** [comment]
@GaryRidgway @e-marie-w and I got familiar with the patch and started to step through. The following code seems to be the issue:

```
    linkUI._hideUI = () => {
      const modal = document.querySelectorAll('.ui-dialog-content');
      if (modal.length === 0) {
        _hideUIOriginal.bind(linkUI).call();
      }
    };
```

The modal probably needs to be scoped better and why we are encountering this issue on layout builder instead of node add/edit.

**Comment by joewhitsitt** [comment]
@pyrello and @GaryRidgway not sure if we want to continue to incorporate changes from the community or move forward with what we have. https://www.drupal.org/project/linkit_media_library/issues/3329877#comment-15395871

**Comment by joewhitsitt** [comment]
Moved this draft to teams for review/edits: https://github.com/orgs/uiowa/projects/20/views/1?pane=issue&itemId=50458982
