### ISSUE TITLE
As a site owner, I can have a row of buttons that appears fixed to the bottom of the browser and configure it per page

### ISSUE THREAD

**Issue by makurj** [uiowa/uiowa#5669]
#4767, https://github.com/uiowa/uiowa/pull/5576

Make "after content" configurable on a per-page basis. This is for "Page" content type only, and only for "After Content".

- [x] Add a set of reference fields (one per region that can be overridden) that directly references the region fragment type. We could also potentially allow people to create alternate region fragments inline.
- [x] Update the RegionContentBlock class to check if a page is a node and has override fields set and not empty, in which case it would pull the appropriate fragment from the node instead.
- [ ]  ~~Add a global setting to allow displaying the new region as a fixed area at the bottom of the view port.~~
- [ ] ~~Optional depending on how the previous slice gets rolled out: Update hook to allow setting the global setting to false for any sites that started adding region fragments to this new area.~~
- [x] Preprocess to set a class on the body/footer if there is an after content block to set extra bottom padding https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/scss/components/footer.scss#L8

### Next Slice
- [ ]  https://github.com/uiowa/uiowa/issues/5685
- [x] https://github.com/uiowa/uiowa/issues/5693

**Comment by pyrello** [comment]
We discussed that multiple reference fields are probably a better route than one multi-value reference field that can be used to select multiple region fragment types. This is because it will add a layer of confusion for the user and will require some additional custom code to help make things more clear.

**Comment by pyrello** [comment]
Caching for this block needs to be handled per page rather than globally, so we'll need to figure that out.

**Comment by joewhitsitt** [comment]
We might need to flip/change what is used to render this. As a single block for this might get cached with a different node's value?
