### ISSUE TITLE
As a CRM user, I would like to use IDs or classes for After Content Buttons in my GTM and GA tracking

### ISSUE THREAD

**Issue by makurj** [uiowa/uiowa#5693]
#5669 

As a CRM user, I can use the URL, button text, button classes or IDs (whether in code or manually assigned) to track clicks on individual buttons within the "After Content" block. 

We do not want the class/ID based on their position. For example, 
1st button is “Read More” and its class or ID is bttn-order-1
2nd button is “Info” and its class or ID is bttn-order-2
3rd button is “Apply” and its class or ID is bttn-order-3

> If there’s a unique ID or class on the buttons, regardless of who assigned it (human, robot, whatever), we will track it that way, using logic like this:
>  
> If action = click and id = “xxx” and destination_url contains “XXX”
>  
> We could use a unique class the same way.
>   
> If the ID or class changes, our tracking will not work.

**Comment by joewhitsitt** [comment]
IMO using the accordion item title/id solution here would be fine

**Comment by briand44** [comment]
Waiting on this to see if it is needed or if they can track based on button text per url.

**Comment by makurj** [comment]
From Lydia: "I was able to successfully use the button class to fire an event in Google Analytics when one of the sticky CTA buttons is clicked. For now, the button click is generic and fires anytime any of those buttons is clicked. We could also create specific events that fire if the button is an “apply” button, a “request info” button, or really anything else. I’ve left this turned on, so as we start to use this feature, we can talk about what the right tracking is." 

I will keep this issue around until we can definitively decide we don't need this functionality.

**Comment by makurj** [comment]
User can track the individual buttons via destination URL. Closing this.

**Comment by joewhitsitt** [comment]
I think we aren't going to pursue this for the platform, that it would be helpful to know how explain the setup to other customers since we extend into the analytics business these days.
