### ISSUE TITLE
Registrar Contact Us Taxonomy and Panel Changes

### ISSUE THREAD

**Issue by makurj** [uiowa/uiowa#5701]
From Josh:

I'm hoping you can make a couple programming changes for the Contact Us module(https://registrar.uiowa.edu/admin/structure/taxonomy/registrar_contacts) on registrar.uiowa.edu(https://registrar.uiowa.edu/). With many of our staff working from home or hybrid we don't have physical locations for some of the units listed on that Contact Us page, we're hoping that we could remove the requirement for address info and make the email field required instead. 

Also if possible, we're hoping that maybe we could add a target url field? On the public facing Contact Us page(https://registrar.uiowa.edu/contact) if you click on one of the units it takes you [to a page](https://registrar.uiowa.edu/registrar-contacts/ui-service-center) that kinda just replicates the info in the card. We'd like it if we could redirect folks to a unique url of our choosing that would take users to a page within that had more info.

**Comment by briand44** [comment]
They decided they would prefer just removing the link to the taxonomy term entity rather than linking to an external page

**Comment by briand44** [comment]
This has been deployed
