### ISSUE TITLE
AD role mappings connect.studentlife.uiowa.edu

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5702]
As an owner of the intranet connect.studentlife.uiowa.edu, I would like to grant access to specific AD groups so that we do not have to manually control access.

Examples from other websites:
https://github.com/uiowa/uiowa/blob/main/config/sites/sitenow.uiowa.edu/config_split.patch.uiowa_auth.settings.yml
https://github.com/uiowa/uiowa/blob/main/config/sites/brand.uiowa.edu/config_split.patch.uiowa_auth.settings.yml

**Comment by briand44** [comment]
blocked until we get the list of AD groups

**Comment by briand44** [comment]
The list of AD groups have been provided. These will need to map to the "Viewer" role. There are a lot.

https://iowa.sharepoint.com/sites/CSI-Drupal2/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FCSI%2DDrupal2%2FShared%20Documents%2FStudent%20Life%2FStudent%20Life%20Connect%2Fstudent%2Dlife%2Dconnect%2Dad%2Dgroups%2Etxt&viewid=bf54b9d9%2D0975%2D4fbc%2D9f1b%2D6377bdc2307c&parent=%2Fsites%2FCSI%2DDrupal2%2FShared%20Documents%2FStudent%20Life%2FStudent%20Life%20Connect

**Comment by briand44** [comment]
Grooming conversation: Move forward with this like SiteNow and Brand. Test any potential performance issues in dev. Create a follow up to determine if this is how we want to handle these going forward or if we want to be ignoring this config and only allowing Administrators to change this directly in the UI.

**Comment by pyrello** [comment]
Follow-up issue: #5862

**Comment by quamsta** [comment]
> The list of AD groups have been provided. These will need to map to the "Viewer" role. There are a lot.
> 
> https://iowa.sharepoint.com/sites/CSI-Drupal2/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FCSI%2DDrupal2%2FShared%20Documents%2FStudent%20Life%2FStudent%20Life%20Connect%2Fstudent%2Dlife%2Dconnect%2Dad%2Dgroups%2Etxt&viewid=bf54b9d9%2D0975%2D4fbc%2D9f1b%2D6377bdc2307c&parent=%2Fsites%2FCSI%2DDrupal2%2FShared%20Documents%2FStudent%20Life%2FStudent%20Life%20Connect

@briand44 We have an exceptions group we'd like to add to the list:

`CN=HSG-GSG-IT-SiteNow-Exceptions,OU=Groups,OU=HSG,OU=SSer,DC=iowa,DC=uiowa,DC=edu`

**Comment by briand44** [comment]
@quamsta can you explain the reason for multiple exception groups? It looks like there is already one in the existing list.

`CN=Student-Services-Exception,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu`

**Comment by quamsta** [comment]
> @quamsta can you explain the reason for multiple exception groups? It looks like there is already one in the existing list.
> 
> `CN=Student-Services-Exception,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu`


@briand44 Sorry, I was picking up some slack on Ben Lewis's email threads since he's out and forgot to provide a bit more context. 

That exception group I posted in my comment should replace the one quoted above. The `Student-Services-Exceptions` one was a "guess" of what we might call it, but 

`CN=HSG-GSG-IT-SiteNow-Exceptions,OU=Groups,OU=HSG,OU=SSer,DC=iowa,DC=uiowa,DC=edu` 

Is the actual exception group that Chris Clough created for us the other day.

**Comment by bspeare** [comment]
>  Test any potential performance issues in dev. '

How do we test performance issues for this?

**Comment by briand44** [comment]
>How do we test performance issues for this?

Dev team may have better ideas but at a minimum pushing this out to dev environment and testing authentication using a HawkID and make sure logging in isn't extremely slow.

**Comment by bspeare** [comment]
Thanks @briand44.  I'm going to deploy https://github.com/uiowa/uiowa/pull/5883 to dev on `uiowa03` to test this on studentlifeconnect.dev.drupal.uiowa.edu.

**Comment by bspeare** [comment]
@quamsta this is now ready at https://studentlifeconnect.dev.drupal.uiowa.edu/.   Are you able to test it out?

**Comment by quamsta** [comment]
> @quamsta this is now ready at https://studentlifeconnect.dev.drupal.uiowa.edu/. Are you able to test it out?

Will be testing with users soon. Sorry for the delay.

**Comment by quamsta** [comment]
@bspeare We've tested this with a few users in different groups and it does seem to work well and is performant enough (seems as speedy as a normal login as a webmaster really-- we couldn't tell the difference). We did notice that after logging in, the user is sort of plopped into their `/user` page. 

Is there any way to customize this to, say, drop them off at the homepage upon logging in? I know @joewhitsitt helped make the login text customizable, but I can't remember if the redirect was customizable as well.

**Comment by joewhitsitt** [comment]
We touched on this briefly, but I don't think we found a nice way of doing it:

https://github.com/uiowa/uiowa/issues/4640#issuecomment-1033036113

**Comment by quamsta** [comment]
> We touched on this briefly, but I don't think we found a nice way of doing it:
> 
> [#4640 (comment)](https://github.com/uiowa/uiowa/issues/4640#issuecomment-1033036113)

> The current login link in the footer sets the destination parameter to redirect back to the access denied page

@joewhitsitt That comment referred to the admin login button at the bottom of the page. Is it the same deal with the big gold button that the user logs in with:

<img width="496" alt="Screen Shot 2022-10-27 at 10 31 49 AM" src="https://user-images.githubusercontent.com/472923/198333602-2ac473d4-959b-4bb5-a395-336611954330.png">

That button's path can't be changed to something like:

`/saml/login?destination=/`

?

**Comment by joewhitsitt** [comment]
Duh. Sorry. Yeah, that would work. I think we were so focused on our current destination functionality where it takes you back to the page you initially tried to visit (coming from an email link etc.)

**Comment by quamsta** [comment]
@joewhitsitt Nice! Probably a separate issue though?

**Comment by joewhitsitt** [comment]
I think it would just be a modification to:
https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/sitenow_intranet/sitenow_intranet.module#L93
by adding a `destination` query option https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Url.php/function/Url%3A%3AfromRoute/9.1.x

If anyone had time and wanted to sneak it in. 😉

**Comment by quamsta** [comment]
@joewhitsitt I may have time this afternoon. Will take a look..

**Comment by quamsta** [comment]
> I think it would just be a modification to: https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/sitenow_intranet/sitenow_intranet.module#L93 by adding a `destination` query option https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Url.php/function/Url%3A%3AfromRoute/9.1.x
> 
> If anyone had time and wanted to sneak it in. 😉

@joewhitsitt  Took a stab at this in this draft PR:

https://github.com/uiowa/uiowa/pull/5893

Wasn't able to fully test in local environment though
