### ISSUE TITLE
70(x) updates - Acquia Connector

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5705]
A support ticket was opened for uiowa703 for the acquia_connector module to be updated from 7.x-3.10 to 7.x-3.11.

https://support-acquia.force.com/s/case/5006g00000i5tZl

There hasn't been support issues opened for 701 and 702 yet but it looks like those currently have 7.x-3.10 in the profile so we should update those applications as well.

Looks like we'll need to update this in both the sitenow profile and sitenow_standard_profile.

**Comment by briand44** [comment]
There are db updates with this

**Comment by joewhitsitt** [comment]
i doubt they are changing anything stored in a feature though right?

**Comment by briand44** [comment]
>i doubt they are changing anything stored in a feature though right?

I wouldn't think so. Checked Registrar and no features overridden

**Comment by briand44** [comment]
703 done

**Comment by briand44** [comment]
702 done

**Comment by briand44** [comment]
701 done

**Comment by briand44** [comment]
There are other application still on 7.x-3.10 but I guess we should wait for RA. Closing this.
