### ISSUE TITLE
Migration comparison operators

### ISSUE THREAD

**Issue by GaryRidgway** [uiowa/uiowa#5708]
Currently, migration scripts still have comparison operators, but it would be very difficult to discern the actual intent of what they are trying to do without running amok migration. This issue is to track all of the old migration scripts that have these comparison operators in them.

https://github.com/uiowa/uiowa/blob/6616743f51645bd0679b19b76bbfe3d12b956015/docroot/sites/tippie.uiowa.edu/modules/tippie_migrate/src/Plugin/migrate/source/Articles.php#L215-L221

**Comment by joewhitsitt** [comment]
I think given that these themselves won't be run again that maybe we just make sure going forward copy/pasta migration code is checked.
