### ISSUE TITLE
IISC - Refactor projects page to allow for passing in a search term

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#5714]
# Motivation

To improve discoverability for projects on the IISC site, I would like to refactor the Projects page (https://iisc.prod.drupal.uiowa.edu/projects) to add a search filter that can return results based on the title of the project or the partner name. The current set of filters already looks kind of crowded and this is before adding a "Reset" button:
<img width="1332" alt="Screen Shot 2022-09-19 at 1 45 39 PM" src="https://user-images.githubusercontent.com/709009/191092407-9a9715ca-9e3a-4d62-bedf-28c6e3ef1738.png">

To handle this more gracefully, I would like to pursue a design that allows for the search filter to act as the "basic" version of the form and then present the other filters as "advanced" options.

@bspeare found a cool mockup that suggests a way we might handle this: https://cdn.dribbble.com/users/2173663/screenshots/16032266/media/4eeb625b62c50f96939e3379bca68680.jpg?compress=1&resize=1600x1200&vertical=top

# Proposed solution
- [ ] Create a design for basic/advanced search.
- [ ] Update the view per below.
- [ ] Add/update templates and CSS for exposed filters to account for new design.

## View updates
- [ ] Use the "force fields" setting.
- [ ] Add a relationship for "Content referenced by the field_project_partner field."
- [ ] Add a "Content: title" field which uses the Relationship added earlier and give it a different label to distinguish it from the "Content: title" field that already exists.
- [ ] Add a combined search exposed filter that uses both "Content: title" fields.

**Comment by briand44** [comment]
The text search would be the primary/default search

**Comment by bspeare** [comment]
Here's an update from the discussion this morning. 

- Set filters to auto submit
- Adjusted "reset" button to look like UIDS4 small button with light font
- Adjusted teaser template to show partners (It now shows tons of bold text)
- Changed summary marker to use a font awesome icon instead

https://user-images.githubusercontent.com/1036433/192608462-c2b75106-40d0-4099-b920-e6a2edc72173.mov
