### ISSUE TITLE
Upddate to version 3.5.0 of the Snowplow/Radar JS tracking code.

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5721]
>There are some breaking changes to take note of around activity tracking. I have also made some changes to the collector configuration so that it will accept a custom path to receive event messages. This allows us to get around some ad blockers (at least the ones I tried) when the JS tracking configuration is updated to use the custom post path. 
> 
>See https://radar-cdn.its.uiowa.edu/docs/js-how-to.html for information.

# Proposed Solution

- [x] Understand the updates and breaking changes and what effect that has
- [ ] Update to 3.5.0

**Comment by GaryRidgway** [comment]
Deadline?

Michael: doesn't have to be next sprint, would like to understand changes and the why. Until we learn otherwise, consider important but not urgent.

**Comment by joewhitsitt** [comment]
>Understand the updates and breaking changes and what effect that has

In terms of breaking changes, It looks like they changed the structure to be easier to read and more extendable in the future. They also got got rid of whitelist and blacklist terminology.

There are other non-breaking changes listed here: https://docs.snowplow.io/docs/collecting-data/collecting-from-own-applications/javascript-trackers/javascript-tracker/v2-to-v3-migration-guide/#new-tracking-api-breaking-change

We can take this a step further to compare the existing implementation (on our end) to what needs to change to adopt the latest version.

**Comment by joewhitsitt** [comment]
<img width="1044" alt="Screen Shot 2022-10-21 at 9 06 18 AM" src="https://user-images.githubusercontent.com/4663676/197215223-c4f04652-0a4f-40a9-9f84-dd486fb48851.png">

**Comment by joewhitsitt** [comment]
`post has been removed. Set eventMethod instead, the available options are: 'post' (default), beacon or get.`

Looks like `performanceTiming` still exists and can be added back in.

**Comment by joewhitsitt** [comment]
Talked to @mjoneill about this in our 1:1. Going to send the adjust snippet to the radar/snowplow team for review before making the switch.

**Comment by joewhitsitt** [comment]
We got confirmation that our snippet looked good. With @mjoneill's permission, I'd like to move forward with deploying the snippet to Google Tag

**Comment by mjoneill** [comment]
> With @mjoneill's permission

Make it so!  :P

**Comment by joewhitsitt** [comment]
Went out as part of version 61. Snowplow team will monitor for any unexpected differences.
