### ISSUE TITLE
PHP 8.1 issues

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#5729]
A place to collect any issues we notice while testing the rollout on stage of #5611

**Comment by bspeare** [comment]
- The “Event Series” block on https://admissions.stage.drupal.uiowa.edu/test-page-0 is WSOD.
- The "Student Profiles Grid" block on https://admissions.stage.drupal.uiowa.edu/california-hawkeyes is WSOD.

**Comment by makurj** [comment]
https://default.uiowa.ddev.site/admin/config/system/site-information
`TypeError: htmlspecialchars(): Argument #1 ($string) must be of type string, Drupal\system\Entity\Menu given in htmlspecialchars() (line 424 of core/lib/Drupal/Component/Utility/Html.php)`

**Comment by joewhitsitt** [comment]
Looking into this basic site settings error ^^

update: this should be fixed by https://github.com/uiowa/uiowa/pull/5730/commits/73daf26b48097a237dbe33ae5c0eac4a5f4ff8db

**Comment by joewhitsitt** [comment]
TypeError: array_search(): Argument #2 ($haystack) must be of type array, string given in array_search() (line 1115 of /mnt/www/html/uiowa02stg/docroot/modules/custom/layout_builder_custom/layout_builder_custom.module)

https://admissions.stage.drupal.uiowa.edu/academics

**Comment by pyrello** [comment]
> TypeError: array_search(): Argument #2 ($haystack) must be of type array, string given in array_search() (line 1115 of /mnt/www/html/uiowa02stg/docroot/modules/custom/layout_builder_custom/layout_builder_custom.module)
> 
> https://admissions.stage.drupal.uiowa.edu/academics

This sounds like an issue I already fixed.

**Comment by joewhitsitt** [comment]
```
Deprecated function: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in Drupal\Component\Utility\Unicode::validateUtf8() (line 478 of core/lib/Drupal/Component/Utility/Unicode.php).
Drupal\Component\Utility\Unicode::validateUtf8(NULL) (Line: 65)
Drupal\Component\Utility\Xss::filter(NULL) (Line: 271)
Drupal\diff\DiffEntityComparison->getRevisionDescription(Object, Object) (Line: 359)
Drupal\diff\Form\RevisionOverviewForm->buildRevision(Object, Array, Object, Object) (Line: 228)
Drupal\diff\Form\RevisionOverviewForm->buildForm(Array, Object, Object)
call_user_func_array(Array, Array) (Line: 531)
Drupal\Core\Form\FormBuilder->retrieveForm('revision_overview_form', Object) (Line: 278)
```
https://www.drupal.org/project/diff/issues/3256598
https://www.drupal.org/project/diff/issues/3310332

Fixed by https://github.com/uiowa/uiowa/pull/5730/commits/4f2ad84cf93acd5f1a5783dba877f1e7cf46246b

**Comment by joewhitsitt** [comment]
Since folks might be testing today in stage, I think it would be good to merge in these fixes.

**Comment by joewhitsitt** [comment]
Ha. Actually, we should update menu_admin_per_menu to 1.4 (1.5 if we want d10 compatibility, new permissions) https://www.drupal.org/project/menu_admin_per_menu/issues/3261472

**Comment by GaryRidgway** [comment]
Found this:
![Screen Shot 2022-09-27 at 11 39 36 AM](https://user-images.githubusercontent.com/23122142/192588597-bc84d0ae-3ea6-4b66-8516-6ee4f91b5f9a.png)

The line in question is `$values['value'] = $random->word(mt_rand(1, $field_definition->getSetting('max_length')));`

**Comment by joewhitsitt** [comment]
Addressing https://github.com/uiowa/uiowa/issues/5729#issuecomment-1259788951

>given that this is a backend developer issue (generateSampleValue for iowa now's embargo field), i don’t think it is a blocker for our php 8.1 switch

that a separate issue to address this would be better.

**Comment by joewhitsitt** [comment]
Though https://github.com/uiowa/uiowa/pull/5730 was merged in, kept this issue open as https://github.com/uiowa/uiowa/issues/5729#issuecomment-1259788951 has not been addressed yet.

**Comment by joewhitsitt** [comment]
Created a separate issue (https://github.com/uiowa/uiowa/issues/5741) for https://github.com/uiowa/uiowa/issues/5729#issuecomment-1259788951. Wondering if we can close this issue in favor of that and the other issues we have discovered https://github.com/uiowa/uiowa/issues?q=is%3Aopen+label%3Aphp+is%3Aissue
