### ISSUE TITLE
Add TikTok to fontawesome picker in social media menu

### ISSUE THREAD

**Issue by bewoldt** [uiowa/uiowa#5734]
# Problem
TikTok doesn't show up as a fontawesome icon to choose from in the social media menu.

**Comment by joewhitsitt** [comment]
@bewoldt we are currently in a rough spot as it relates to fontawesome. The icon is available but it doesn't show up in the picker: https://github.com/uiowa/uiowa/pull/2136

`fab fa-tiktok`

I think this should be repurposed to explore our future with fontawesome and how to move away from fontawesome_iconpicker

https://github.com/uiowa/uiowa/pull/5511#issuecomment-1206852059
https://www.drupal.org/project/fontawesome_iconpicker

**Comment by joewhitsitt** [comment]
This is available since we updated fontawesome. Whether or not is should be used is the current question on campus.

https://github.com/uiowa/uiowa/pull/6752, https://github.com/uiowa/uiowa/pull/7099
