### ISSUE TITLE
Update typhonius/acquia-php-sdk-v2

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#5738]
Noticing deprecated code when provisioning websites. https://github.com/typhonius/acquia-php-sdk-v2

```
PHP Deprecated:  Return type of League\OAuth2\Client\Token\AccessTokenInterface::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /acquia/uiowa/vendor/league/oauth2-client/src/Token/AccessTokenInterface.php on line 71
```

```
PHP Deprecated:  http_build_query(): Passing null to parameter #2 ($numeric_prefix) of type string is deprecated in /uiowa/vendor/league/oauth2-client/src/Tool/QueryBuilderTrait.php on line 31

Deprecated: http_build_query(): Passing null to parameter #2 ($numeric_prefix) of type string is deprecated in /uiowa/vendor/league/oauth2-client/src/Tool/QueryBuilderTrait.php on line **31**
```

This is what calls https://github.com/thephpleague/oauth2-client

**Comment by joewhitsitt** [comment]
I think this might need to wait until core 9.5

To get to typhonius/acquia-php-sdk-v2 2.1 (php 8.1), it requires guzzlehttp/guzzle ^7.2 and is locked at 6.5.8 by core-recommended.

https://www.drupal.org/project/drupal/issues/3225966

**Comment by pyrello** [comment]
It might be worth checking if we can make the jump to the newest version of this library. Here is full diff:
https://github.com/typhonius/acquia-php-sdk-v2/compare/2.0.15...3.0.9

There are a couple breaking changes in the 3.x branch, but it seems like those may not affect us or would be easy enough to update our code to fix: https://github.com/typhonius/acquia-php-sdk-v2/releases/tag/3.0.0

**Comment by pyrello** [comment]
If we are going to close this issue with #6994, I think we should create another issue to upgrade to the 3x version.

**Comment by joewhitsitt** [comment]
That is fine. The d10 pr resolves the warnings of the original IS. Added test instructions to the PR.

**Comment by joewhitsitt** [comment]
Created https://github.com/uiowa/uiowa/issues/7031
