### ISSUE TITLE
PHP error deprecated strlen()

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5739]
```php-error web-33204 [28-Sep-2022 13:32:20 UTC] PHP Deprecated: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /usr/local/php7.4/lib/php/Net/DNS2/Socket/Sockets.php on line 112 request_id="v-fa861ea6-3f31-11ed-a9e7-4f670571d918"```

# Problem
Not currently sure what problem this is causing

# Steps to reproduce
Not sure how to produce just seeing this in the logs a lot on the uiowa application

# Proposed solution

**Comment by pyrello** [comment]
I was watching the logs while logging into brand.uiowa.edu and saw this error occur. Not sure if it is a coincidence or not.

**Comment by pyrello** [comment]
> I was watching the logs while logging into brand.uiowa.edu and saw this error occur. Not sure if it is a coincidence or not.

Seems like it must have been a coincidence because I did not see it an entry of the above show up when I logged into law.uiowa.edu.

**Comment by pyrello** [comment]
Here are some instances where the value we are passing to `strlen` could be `NULL`:
https://github.com/uiowa/uiowa/blob/30d334922427556992da6ebace7143949a1c7782/docroot/modules/custom/layout_builder_custom/layout_builder_custom.module#L585-L592
https://github.com/uiowa/uiowa/blob/30d334922427556992da6ebace7143949a1c7782/docroot/themes/custom/uids_base/theme-settings.php#L20
https://github.com/uiowa/uiowa/blob/30d334922427556992da6ebace7143949a1c7782/docroot/themes/custom/uids_base/uids_base.theme#L167

**Comment by pyrello** [comment]
Context: https://php.watch/versions/8.1/internal-func-non-nullable-null-deprecation

**Comment by bspeare** [comment]
Just looked at the php error logs for `uiowa` `uiowa01`and`uiowa02` and I don't see this error in the logs.  Should we close this until we notice the error again?

**Comment by joewhitsitt** [comment]
Just did a "year to date" query in splunk and got the same no result.
