### ISSUE TITLE
IowaNow - Embargo field errors within generateSampleValue

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#5741]
![Screen Shot 2022-09-27 at 11 39 36 AM](https://user-images.githubusercontent.com/23122142/192588597-bc84d0ae-3ea6-4b66-8516-6ee4f91b5f9a.png)

The line in question is `$values['value'] = $random->word(mt_rand(1, $field_definition->getSetting('max_length')));`

_Originally posted by @GaryRidgway in https://github.com/uiowa/uiowa/issues/5729#issuecomment-1259788951_

```
ValueError: mt_rand(): Argument #2 ($max) must be greater than or equal to argument #1 ($min) in mt_rand() (line 75 of /mnt/www/html/uiowa03/docroot/core/lib/Drupal/Core/Field/Plugin/Field/FieldType/StringItem.php) #0 /mnt/www/html/uiowa03/docroot/core/lib/Drupal/Core/Field/Plugin/Field/FieldType/StringItem.php(75): mt_rand(1, NULL)
```

# How to reproduce
- Go to Iowa Now's article display settings

**Comment by joewhitsitt** [comment]
Before we rush to add a max_length to this, I want to point out that no `string_long` type fields have this currently. Only type `string` has it.

<img width="839" alt="Screen Shot 2022-09-28 at 9 57 36 AM" src="https://user-images.githubusercontent.com/4663676/192813500-cbb92aec-1e8d-4fdc-895d-fb13a00c4457.png">
<img width="899" alt="Screen Shot 2022-09-28 at 9 57 51 AM" src="https://user-images.githubusercontent.com/4663676/192813504-61492d3c-06d2-47a7-b497-3face835447a.png">

**Comment by joewhitsitt** [comment]
Not sure why we are seeing a stacktrace for StringItem when docroot/core/lib/Drupal/Core/Field/Plugin/Field/FieldType/StringLongItem.php exists and has a separate generateSampleValue()

**Comment by cory-skeers** [comment]
> Not sure why we are seeing a stacktrace for StringItem when docroot/core/lib/Drupal/Core/Field/Plugin/Field/FieldType/StringLongItem.php exists and has a separate generateSampleValue()

I'm getting a little confused here too. Looking at the field settings in the UI, it comes up with an empty max length, which would be expected if it was a plain text string, but shouldn't be there for a plain, long text string. 🤷

**Comment by joewhitsitt** [comment]
> Looking at the field settings in the UI, it comes up with an empty max length

And why this field and not on field_teaser?

**Comment by GaryRidgway** [comment]
this is so confusing...

**Comment by joewhitsitt** [comment]
Started a thread in https://drupal.slack.com/archives/C0T77ULN9/p1664384152371669

**Comment by joewhitsitt** [comment]
My hope is that it isn't related to patch or some dev commit elsewhere in our codebase.

**Comment by GaryRidgway** [comment]
![Screen Shot 2022-09-28 at 12 25 27 PM](https://user-images.githubusercontent.com/23122142/192848797-2fdcb8a6-9e29-4c7f-b7a3-7884aa3108b9.png)
I think I am on to something

**Comment by GaryRidgway** [comment]
![Screen Shot 2022-09-28 at 12 27 04 PM](https://user-images.githubusercontent.com/23122142/192849295-0c4e5c66-e1f8-4e4b-aee5-a1790331216a.png)

**Comment by GaryRidgway** [comment]
![Screen Shot 2022-09-28 at 12 35 36 PM](https://user-images.githubusercontent.com/23122142/192850702-febc34c8-2a20-4a27-823a-ba1526f29fec.png)

**Comment by cory-skeers** [comment]
> I think I am on to something

Interesting! That definitely looks like it could do it. Looks like field_storage and field config definitions aren't matching... Can we just update the field config file to match the field storage, without breaking things?

**Comment by joewhitsitt** [comment]
Ah i see. The field instance is `string.` The field instance for teaser is `string_long.` not sure if that would work, but now I am wonder how it got that way. was there a field type change during development?

**Comment by cory-skeers** [comment]
> Ah i see. The field instance is `string.` The field instance for teaser is `string_long.` not sure if that would work, but now I am wonder how it got that way. was there a field type change during development?

I don't remember there being any changes during development, but the initial PR had this discrepancy too, so it at least didn't break during any follow-up development.

I'm surprised it was able to end up in this state, and that we didn't see anything broken before now. 

My guess would be that if we are able to get here, changing the config definition for field should work to fix it without breaking anything further, but that changing the config for field storage could potentially.

**Comment by GaryRidgway** [comment]
https://github.com/uiowa/uiowa/compare/main...now-contact#diff-a18715ef3d4dacfebb5337ca35b0aaca8baa88a3e7c3f8b14eec6ab1f4902fc4R46

this is the only manual thing i changed for the embargo info

**Comment by cory-skeers** [comment]
I tested locally adjusting
`config/sites/now.uiowa.edu/field.field.node.article.field_embargo_information.yml ` `field_type` from `string` to `string_long`, and updating `config/sites/now.uiowa.edu/config_split.patch.core.entity_form_display.node.article.default.yml` `type` to `string_textarea` with `rows: 2` in place of size...

It appears to work after importing the changes, and I can push them up for others to test, but didn't want to overlap anything else you may have done @GaryRidgway.

**Comment by GaryRidgway** [comment]
I have nothing to push up, you can push your changes. So my question in the end here is, did I do this? I can't remember doing so?

**Comment by cory-skeers** [comment]
> I have nothing to push up, you can push your changes. So my question in the end here is, did I do this? I can't remember doing so?

Alright, I'll push it up. And nope! This was somehow in here already, and it just didn't get noticed until now.

**Comment by cory-skeers** [comment]
> > I have nothing to push up, you can push your changes. So my question in the end here is, did I do this? I can't remember doing so?
> 
> Alright, I'll push it up. And nope! This was somehow in here already, and it just didn't get noticed until now.

Pushed, and I think if you do a config import or fresh sync, you should now be able to proceed.

**Comment by GaryRidgway** [comment]
Thanks cory!
