### ISSUE TITLE
Add pop up javascript to all pages of OSC website

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5743]
As an OSC website stakeholder, I would like to present a survey to site visitors when they are attempting to leave the site so that we can gain feedback on who they are, what they were looking for, if they were successful and any other feedback related to their experience.

# Additional Information

The popup will be presented by Unbounce and link to a Qualtric survey.

The Qualtrics survey url is...

# Questions
How do we want to add this JS to all pages?
- Google Tag Manager?
- page.tpl file?
- preprocess function?

# Proposed Solution

- [ ] Create full html block that renders on all pages and add the script provided below

**Comment by briand44** [comment]
@mkyoder do we have the JS that will need to be added or is that not available yet?

**Comment by mkyoder** [comment]
@briand44 Yep! I can add that link here.

**Comment by mkyoder** [comment]
Qualtrics survey link: https://uiowa.qualtrics.com/jfe/form/SV_8CFaAGGPlf2vxI2
JS: <script src="https://8ee990345a6d4219b91e150f646944df.js.ubembed.com" async></script>
<img width="1076" alt="Screen Shot 2022-09-28 at 3 57 41 PM" src="https://user-images.githubusercontent.com/107870104/192887384-84939907-1125-4b01-b91d-8d7ff8205ec5.png">

**Comment by briand44** [comment]
Adding blocked label until the Unbounce popup is finalized.

**Comment by mkyoder** [comment]
I'm not seeing anything from my view that the JS needs to be placed anywhere special on the site. Here is what I can see. 

<img width="1068" alt="Screen Shot 2022-10-04 at 2 24 09 PM" src="https://user-images.githubusercontent.com/107870104/193908114-81a2e3ab-1641-42b3-a703-4e62d79d7f0a.png">

**Comment by mjoneill** [comment]
There's another layer of description which indicates this JS needs to be in the `<head>` section.
https://documentation.unbounce.com/hc/en-us/articles/360020659971 


> <script src="https://8ee990345a6d4219b91e150f646944df.js.ubembed.com"/ async></script>
> 
> Here’s instructions for installing the script:
> https://documentation.unbounce.com/hc/en-us/articles/360000509643-Installing-Your-Popup-Sticky-Bar
> 
> And, here’s a one-page FAQ from Unbounce, made for awesome developers just like you:
> http://unbounce.com/docs/faq-web-dev.pdf

**Comment by mkyoder** [comment]
Whoops - sorry! Thanks for catching that Michael!

**Comment by bspeare** [comment]
I'd imagine that they suggest the `<head>` because that is a common practice for managing scripts on the page.  Do we want to start with the original proposed solution and move to `html.tpl.php` or preprocess function if this is not working as expected?

**Comment by mjoneill** [comment]
I'm open for anything if we're up for learning and adjusting as we need to.

**Comment by mjoneill** [comment]
> Whoops - sorry! Thanks for catching that Michael!

Well, the info took a bit of digging...I think three clicks in from where it would have been helpful to have it  :P  

> “But the plans were on display…”
> “On display? I eventually had to go down to the cellar to find them.”
> “That’s the display department.”
> “With a flashlight.”
> “Ah, well, the lights had probably gone.”
> “So had the stairs.”
> “But look, you found the notice, didn’t you?”
> “Yes,” said Arthur, “yes I did. It was on display in the bottom of a locked filing cabinet stuck in a disused lavatory with a sign on the door saying ‘Beware of the Leopard.”

**Comment by mkyoder** [comment]
Unbounce pop-up added to osc.uiowa.edu pages. Megan will publish it once Jeneane has had a chance to review the pop up and corresponding Qualtrics survey this week.

**Comment by mkyoder** [comment]
Going to publish the pop-up this morning.

**Comment by mkyoder** [comment]
![Screen Shot 2022-10-21 at 9 22 55 AM](https://user-images.githubusercontent.com/107870104/197218996-de80dee4-db59-46a5-8ede-ac118a4ebebf.png)

**Comment by mkyoder** [comment]
Pop-up has been published now. I sent a test response to the Qualtrics survey and it seems to be working for me.

**Comment by mkyoder** [comment]
As an update, we have a total of 249 responses in the Qualtrics survey that links from this pop-up. After meeting with OSC leadership about the OSC redesign, I am going to close this Qualtrics survey and unpublish this pop-up in Unbounce. Let me know if there are any questions/concerns here.

**Comment by mkyoder** [comment]
Qualtrics survey is closed to participant responses now and unpublished pop up for osc.uiowa.edu.
