### ISSUE TITLE
Custom class attributes are not being added to event series block

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#5752]
# Problem
On https://admissions.uiowa.edu/next-step-iowa-admitted-student-days, the custom classes for the `<ul>` are no longer being added. 

<img width="1412" alt="Screen Shot 2022-09-29 at 1 58 35 PM" src="https://user-images.githubusercontent.com/1036433/193119522-13912bf3-1e06-472f-a77b-638dea509057.png">

# Proposed solution
Figure out why https://github.com/uiowa/uiowa/blob/main/docroot/sites/admissions.uiowa.edu/modules/admissions_core/src/Plugin/Block/EventSeriesEventsBlock.php#L123 is not working.

**Comment by briand44** [comment]
Ben to reach out to Scott.

**Comment by bspeare** [comment]
It sounds like Scott is about to use this content type to create a bunch of events.   It would be great to fix this ASAP.
