### ISSUE TITLE
As an editor, I can customize Person results in custom People blocks to multiple Person types rather than one.

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#5758]
For custom People blocks, an editor can add one option for person type to filter on, but not multiple. This creates an issue when a unit wants to include two or more types rather than one. They are forced to create multiple pages or separate blocks that are not combining results.

![Screen Shot 2022-09-30 at 4 27 58 PM](https://user-images.githubusercontent.com/3067017/193360607-2191c749-a1f4-460b-a9d3-20c63288c4bd.png)

**Comment by bspeare** [comment]
Closing as this is a duplicate of https://github.com/uiowa/uiowa/issues/7024.
