### ISSUE TITLE
Religious Studies D9 site

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#5784]
Standard checklist for site provision, installation, and creation:
- [ ] Provision and install site
- [ ] Copy default content and settings from CLAS Template
- [ ] Migrate existing content into new D9 site
- [ ] Add strategy and messaging content from CLAS MarCom
- [ ] Web copy updates from CLAS MarCom
- [ ] New photography as needed
- [ ] Add Google Analytics GA4 web property ID from CLAS GA account
- [ ] Unit approves launch
- [ ] Launch site
- [ ] Create .htaccess redirect from D7 site (if needed)

Existing site: [https://clas.uiowa.edu/religion](https://clas.uiowa.edu/religion)

**Comment by e-marie-w** [comment]
https://religiousstudies.uiowa.edu/ launched February 2024
