### ISSUE TITLE
English D9 site

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#5794]
Standard checklist for site provision, installation, and creation:
- [ ] Provision and install site
- [ ] Copy default content and settings from CLAS Template
- [ ] Migrate existing content into new D9 site
- [ ] Add strategy and messaging content from CLAS MarCom
- [ ] Web copy updates from CLAS MarCom
- [ ] New photography as needed
- [ ] Add Google Analytics GA4 web property ID from CLAS GA account
- [ ] Unit approves launch
- [ ] Launch site
- [ ] Create .htaccess redirect from D7 site (if needed)

Existing site: [https://english.uiowa.edu](https://english.uiowa.edu)

**Comment by joewhitsitt** [comment]
This site has launched spring 2023
