### ISSUE TITLE
Earth and Environmental Sciences D9 site

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#5796]
Standard checklist for site provision, installation, and creation:
- [x] Provision and install site
- [x] Copy default content and settings from CLAS Template
- [x] Migrate existing content into new D9 site
- [ ] Add strategy and messaging content from CLAS MarCom
- [ ] Web copy updates from CLAS MarCom
- [ ] New photography as needed
- [ ] Add Google Analytics GA4 web property ID from CLAS GA account
- [ ] Unit approves launch
- [ ] Launch site
- [ ] Create .htaccess redirect from D7 site (if needed)

Existing site: [https://clas.uiowa.edu/ees](https://clas.uiowa.edu/ees)

New site: [https://ees.uiowa.edu](https://ees.uiowa.edu)

**Comment by mark-bennett-uiowa** [comment]
https://ees.prod.drupal.uiowa.edu/

**Comment by joewhitsitt** [comment]
This site has launched at https://ees.uiowa.edu/
