### ISSUE TITLE
CLAS Finance Group D9 site

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#5799]
Standard checklist for site provision, installation, and creation:
- [x] Provision and install site
- [x] Migrate existing content into new D9 site
- [ ] Add strategy and messaging content from CLAS MarCom
- [ ] Web copy updates from CLAS MarCom
- [ ] New photography as needed
- [ ] Add Google Analytics GA4 web property ID from CLAS GA account
- [ ] Unit approves launch
- [ ] Launch site
- [ ] Create .htaccess redirect from D7 site (if needed)

New site: [https://finance.clas.uiowa.edu](https://finance.clas.uiowa.edu)

**Comment by mark-bennett-uiowa** [comment]
https://clasfinance.prod.drupal.uiowa.edu/

**Comment by joewhitsitt** [comment]
This site has launched at https://finance.clas.uiowa.edu/
