### ISSUE TITLE
As an editor, I can select a Circle (S,M,L) image format for images within the WYSIWYG.

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#5805]
As an editor, I can select a 'Circle - small', 'Circle - medium', or 'Circle - large' image format option from the list of current image formats. This has been requested by a few departments that have created custom profile pages for Recent Graduates, Alumni Spotlights, etc. that do not pull from existing Person content.

**Comment by bspeare** [comment]
The circle option is now available within the image block.   I'm going to close this and feel free to reopen if we would like to see this feature within the WYSIWYG.
