### ISSUE TITLE
classrooms.uiowa.edu mockups

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5814]
# Story

As a developer, I can see mockups of a classroom page as well as a UCR-SPS page so that I have a good idea of how the fields and references will need to be displayed which will help us understand how to structure them.

# Additional Info

Our classrooms partners put together this page as a reference. https://classrooms.prod.drupal.uiowa.edu/art-building-west-240

Existing classrooms page https://classrooms.uiowa.edu/abw-240

We will want to include an image gallery as well as a single featured image.

There are quite a few fields and references that are only displayed on the UCR-SPS search page. We should put together a mockup of this as well to help understand how we handle those fields/references. We shouldn't worry about the display of the filters at this point.

Existing UCR-SPS page https://registrar.uiowa.edu/ucr-sps

# Proposed Solution

- [ ] Create mockup of a classroom page: https://sandbox.prod.drupal.uiowa.edu/art-building-west-240
- [ ] Create mockup of UCR-SPS search page: https://sandbox.prod.drupal.uiowa.edu/university-classrooms-ucr-and-specialty-spaces-sps-0
- [ ] Get feedback from classroom partners on mockups

**Comment by bspeare** [comment]
I've updated the classroom page after the feedback from MSD: https://sandbox.prod.drupal.uiowa.edu/art-building-west-240.    Let me know if you have any feedback!

**Comment by briand44** [comment]
Ok, if I am understanding this correctly some of the UCR/SPS info is found https://sandbox.prod.drupal.uiowa.edu/university-classrooms-ucr-and-specialty-spaces-sps-0 and some lives on the classroom entity https://sandbox.prod.drupal.uiowa.edu/art-building-west-240#cover.

If that is the case my concern is that some current metadata is not represented at all (Descriptions for room type, seating type, category, responsible unit). Maybe they will be ok with that but it may be worth having an idea of how we would represent that if they ask for it.

**Comment by bspeare** [comment]
That's correct @briand44.  I think we will want to create a glossary page to point each general metadata link towards for this mockup.  For custom information like "Responsible unit" we will need to display that text inline and we will update the mockup with that.   For information like "Moveable Tablet Arms", it seems like we could link to an a-z list page of definitions.

**Comment by e-marie-w** [comment]
Glossary page of what previously were tool tips: https://sandbox.prod.drupal.uiowa.edu/glossary. Registrar site currently has a [glossary page](https://registrar.uiowa.edu/glossary-of-terms) so we in theory can just add to that when they migrate.

**Comment by bspeare** [comment]
After our meeting today, I'm going to move forward with these items during the current sprint:

- Update https://sandbox.prod.drupal.uiowa.edu/art-building-west-240 with feedback suggestions
  - Swap events and technical details section
  - Update background color of icon badges on banner
  - Add Report and issue button
  - Remove additional information/data
- Update https://sandbox.prod.drupal.uiowa.edu/university-classrooms-ucr-and-specialty-spaces-sps-0
  - Add all the information back into the results
  - Link to the glossary pages they have built
  - Add search filters

**Comment by bspeare** [comment]
I've updated https://sandbox.prod.drupal.uiowa.edu/art-building-west-240 and https://sandbox.prod.drupal.uiowa.edu/university-classrooms-ucr-and-specialty-spaces-sps-0 with the changes from today's meeting and created a search page mockup at https://classrooms.prod.drupal.uiowa.edu/find-university-classroom-copy.

**Comment by briand44** [comment]
Thanks! A couple questions... is the idea that the details would be expanded by default on the Specialty Space page? Also, should we share this with Classrooms folks for feedback or are you looking for more feedback from the team first?

**Comment by bspeare** [comment]
@briand44 I meant to have the details closed by default and I have updated the page with that setting.    

I think we can share these with the classrooms folks with the caveat that the search filters design(s) could change once we start building this.

**Comment by bspeare** [comment]
I have updated the mockups based on this feedback for https://sandbox.prod.drupal.uiowa.edu/university-classrooms-and-specialty-spaces. 

- Not all rooms have this so that field can be hidden if they do not have another name, but for example, room 101 BBE has “Room Name: Kollros Auditorium”.
- There is also one field that can be eliminated from the details toggle section as well. We feel that the “Instructional Room Category” under the toggle is redundant at this time.

**Comment by bspeare** [comment]
I think we can mark this work as done.
