### ISSUE TITLE
Allow 10 MB uploads again for Signage to maintain 4K support

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#5816]
# Problem

In addressing https://github.com/uiowa/uiowa/issues/4049, I lowered the file size limit to 8 MB which removes half of our 4K support https://github.com/uiowa/uiowa/issues/3209 which we changed it to 10 MB.

# Proposed Solution

- [x] Change all instances from 8 MB to 10 MB (signage, healthcare) in features and deploy

**Comment by briand44** [comment]
group image, slide image, promotional image, default media add... Could use git log to see what was changed previously.

**Comment by briand44** [comment]
Signage and Healthcare Signage both use features so keep that in mind.

**Comment by briand44** [comment]
Also, remember we can remote in to test Healthcare Signage.

**Comment by joewhitsitt** [comment]
0936ba1f6c95fef7fa1a7abf8a1602876e519776 on uihealthcaresignage-dev
41d4826a229733fe19fb8aeb0f6c6d767e123a85 on uisignage-dev

**Comment by joewhitsitt** [comment]
both have been deployed/feature-reverted in PROD
