### ISSUE TITLE
SiteNow updates news article - October

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#5817]
## Issue/Solution ##
Provide a "release notes" type article of finished/done features/updates and publish to website, then send out dispatch email.

- [x] Create draft and update the parking lot card with an edit link
- [x] Add "release notes" covering the month of v2/v3 default profile enhancements and webmaster/edit visible bug fixes.
  * See the previous month's article as an example.
  * Bullet points from demo stories slide per week: https://drive.google.com/drive/folders/1EehKUjxCbakaB9FchrGhAbaxuRbqyDGW?usp=sharing..
- [x] Get at least one team member to look over the draft before publishing.
- [x] Since the draft was started earlier, adjust the publish date/time, publish, get the link to the article.
- [x] Dispatch email with link to article. (To get access, send an email to dispatch-support@uiowa.edu to have the account provisioned. Provide your hawkid and mention the CSI:drupal group)
  * Modify SiteNow Announcements Template (tweak opening line, update the article link, any other editorial adjustments)
  * Create new communication off SiteNow Announcements campaign
    * Use SiteNow Announcements population, template, suppression list, bypass approval.
    * When scheduling, check the "archive" option so that there is an RSS instance we can use in the future. I don't think this can be done after the fact.
- [x] Turn off Dispatch "test mode" to send out email. 
- [x] Turn on Dispatch "test mode" after email is successfully sent.
- [x] Take a moment to check dispatch and google analytics on whether these articles are being read.
- [x] Create the next months's issue and copy all this bullet list into it, removing the checked boxes if any.

**Comment by e-marie-w** [comment]
https://sitenow.uiowa.edu/news/2022/10/updates-october

**Comment by joewhitsitt** [comment]
I think we have only included items about the v2/v3 service and not customer specific stuff (e.g. admissions) unless we mention in the intro which we aren't doing anymore

**Comment by cory-skeers** [comment]
<img width="1368" alt="image" src="https://user-images.githubusercontent.com/49074566/199333530-a862c6b9-34a4-4dcb-a9b5-848f035db7b5.png">

About a 50% open rate, 10% link clink rate
~200 messages sent, 20 unique link clicks. At quick glance at the emails for those who clicked, they are 1) not us (yay) and 2) pretty familiar names. Not the highest interaction rate, but the people using it do so regularly, so there might be some value/desire there.
