### ISSUE TITLE
Paragraphs within layout builder cannot be removed

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#5818]
# Problem
There is an overlay issue with the paragraphs action buttons

# Steps to reproduce
In v3, remove a collection item.

https://user-images.githubusercontent.com/4663676/194397011-7be0168a-e620-423e-ac60-c7f4960379a8.mov

# Proposed solution
- [ ] Check the paragraphs/layout builder issue queue for upstream issues/solutions
- [ ] Adjust admin css to make sure these buttons don't overlap.

**Comment by bspeare** [comment]
The logs are complaining about `TypeError: array_shift(): Argument #1 ($array) must be of type array, null given in array_shift() (line 1026 of /var/www/html/docroot/modules/custom/layout_builder_custom/layout_builder_custom.module)` which is at  https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/layout_builder_custom/layout_builder_custom.module#L1026

**Comment by joewhitsitt** [comment]
Thanks for digging into this @bspeare. Are you working on it? I can help debug if needed

**Comment by bspeare** [comment]
I'm not actively working on it.  I was just curious about what the logs said.

**Comment by joewhitsitt** [comment]
Looks like it originally came from https://github.com/uiowa/uiowa/issues/2104 and just needs an if not empty check around it. I think the collection item title (headline) is required but not always set when this code runs.
