### ISSUE TITLE
UIAcquiaGithub deploy key

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#5819]
I believe Rick setup a Slack reminder to do this periodically. Let's do it.

https://wiki.uiowa.edu/display/drupaldev/Rotate+Deploy+Key

**Comment by joewhitsitt** [comment]
@e-marie-w, @makurj  and I attempted this today only to run into several bumps since the last time this was done. Ultimately, we are not getting the right output from following the instructions and have contacted Travis for assistance.

**Comment by joewhitsitt** [comment]
Several edits have been made to the wiki doc: https://wiki.uiowa.edu/display/drupaldev/Rotate+Deploy+Key

**Comment by joewhitsitt** [comment]
I think the slack reminder was tied to Rick's account. Created a repeating its-web calendar event

**Comment by joewhitsitt** [comment]
According to the wiki docs, now that the PR was merged into main, the old ssh keys can be removed from acquia and github.

**Comment by e-marie-w** [comment]
The old ssh keys have now been removed from acquia and github. Closing issue since that was the last step in the process.
