### ISSUE TITLE
Migrate Iowa Now people

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5821]
# Story
As an Iowa Now website owner, I would like people migrated from our current site to our new site so that this content doesn't have to be manually created again.

# Additional Info

Fields:
First Name
Last Name
Job Title->Title/Position
Email
Phone
Photo
Areas of Expertise->Research Areas
About->Bio
Type->Tags (Expert, OSC Staff)
OSC Contact->Person reference

# Questions

- Does Iowa Now plan on using person type? - No, we won't map this in the migration and it won't be used to populate experts list or OSC staff list.

- Path - currently at /person/title. Do we keep this the same or move to people/title? Redirects? - Whatever is easiest for us. Seems like that would be to keep the existing path at /person/title?

- How do we handle person reference during a person migration?

# Proposed Solution

- [x] Extend base node migration for people?
- [x] Keep existing url pattern /person/title
- [x] Verify no redirects are needed
- [x] Run in dev so we can get feedback
- [x] Run in prod

**Comment by joewhitsitt** [comment]
>OSC Contact->Person reference

Isn't this dirty data, aka contact name is a single string? Should this initially migrate to the contact type and manually transition certain contacts to person nodes later on?

**Comment by joewhitsitt** [comment]
@briand44 the migration was performed in DEV: https://now.dev.drupal.uiowa.edu/person , https://now.dev.drupal.uiowa.edu/experts-list

Do you want to contact the Iowa Now team to review?

**Comment by briand44** [comment]
Sure I can contact them. The link you provided, https://now.dev.drupal.uiowa.edu/person, is not going to be used correct? That will likely be disabled and they will just have https://now.dev.drupal.uiowa.edu/experts-list and the staff directory?

**Comment by joewhitsitt** [comment]
>The link you provided, https://now.dev.drupal.uiowa.edu/person, is not going to be used correct?

It can be disabled at anytime. Temporarily serves as a content overview of the migration result

**Comment by joewhitsitt** [comment]
Looked at this for two minutes and I am not sure why only some of the images migrated. The email appears to have just been a bad mapping. `/0/email` perhaps might need to be added to the mapping?

**Comment by cory-skeers** [comment]
I think the image issues are due to spaces in filenames (eg "simon balto.jpeg"). The files are listed in the database with the space, and that's what is used to construct the path that gets passed to `file_get_contents` in the ProcessMediaTrait.

**Comment by cory-skeers** [comment]
Ran locally again, and the photos and emails all appear to be coming over correctly.

Emails have some capitalizations that look out of place, but I don't know if that's an actual style issue, and it's what the current site has...so might not be worth jumping into adding extra process plugins.

I think we can rerun this on dev and re-deliver

**Comment by joewhitsitt** [comment]
Re-ran in DEV. Noticed a bit more terminal chatter (perhaps because of the `mr`), but emails and photos are now migrated. Emailed the Now staff to re-review. Thanks @cory-skeers again for your attention to this today.

**Comment by joewhitsitt** [comment]
Planning on merging https://github.com/uiowa/uiowa/pull/5882 in to main so we will leave this issue open for any further feedback before the migration is run in PROD

**Comment by briand44** [comment]
We have approval to run in prod.

**Comment by joewhitsitt** [comment]
This has been run in PROD https://now.prod.drupal.uiowa.edu/experts-list

**Comment by briand44** [comment]
Does it make sense to disable https://now.prod.drupal.uiowa.edu/person now?

**Comment by joewhitsitt** [comment]
>Does it make sense to disable https://now.prod.drupal.uiowa.edu/person now?

Sure.

Update: done.
