### ISSUE TITLE
Display Facilities Management building info from API

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5823]
# Story
As a Facilities Management website owner, I would like to see building information from our APIs displayed on building pages.

# Additional Info

**Data Feeds**
https://bizhub.facilities.uiowa.edu/bizhub/ext/buildings
https://bizhub.facilities.uiowa.edu/bizhub/ext/building?bldgnumber=0004

**Existing building**
https://www.facilities.uiowa.edu/building/0003

**Mockups**
https://sandbox.prod.drupal.uiowa.edu/chemistry-building-mockup
https://sandbox.prod.drupal.uiowa.edu/pappajohn-biomedical-discovery-building

# Scope

This is just the first slice of these building pages which includes creating structure, getting info from API and outputting that information for each building page. Additional information and theming can come in future slices. The information in scope is:

Building Name - I believe we already have this from the API and it should be using `buildingCommonName`
Building Number - I believe we already have this from the API and it should be using `buildingNumber`
Building Abbreviation - I believe we already have this from the API and it should be using `buildingAbbreviation`
Building Address - Structure needed and should come from `address`
Area - Structure needed and should come from `grossArea ` - displayed in `sq. ft.`
Year Built - Structure needed and should come from `yearBuilt `
Ownership - Structure needed and should come from `owned `
Photo - Structure needed and should come from `imageUrl` - no need to override this like on the existing site
Named Building - Structure needed?? The link text can come from `namedBuilding` or from the named building entity "last, first". The actual link needs to come from the named building entity. There is a `building id` on the named buildings.
Single user restrooms men - Structure needed and should come from `singleUserRestroomsMen`
Single user restrooms women - Structure needed and should come from `singleUserRestroomsWomen`
Multi user restrooms men - Structure needed and should come from `multiUserRestroomsMen`
Multi user restrooms women - Structure needed and should come from `multiUserRestroomsWomen`
Gender Neutral restrooms - Structure needed and should come from `singleUserRestrooms`
Lactation rooms - Structure needed and should come from `lactationRooms`
Accessibility links - Structure needed?? The links for Accessibility Map, Hearing Loops, Gender Inclusive restrooms and Lactation rooms will be hard coded. Waiting for updated links for some of these.

# Remaining info for future slices

Contact info - Primary and alt building coordinators
Project Info
Map - want to use Concept 3D map but need to discuss how to handle this. Update, they now want to use FM Sims map.
Artwork
Drush command creates buildings, we need to wire this up to a scheduled job.

# Questions

When/how are the buildings created?
Named Building - do we want to structure this? If so, would it be a reference field.
Accessibility links - is there any reason to structure this?
Schema - https://github.com/uiowa/uiowa/issues/5823#issuecomment-1335431828

# Notes

For buildings that are named buildings, we could potentially get a description and the map url from the named building content but that would only work if it is a named building and that info is captured.

# Proposed Solution

**Comment by briand44** [comment]
We will want to link to the address schema for these buildings from the named buildings. @pyrello does this capture this accurately?

**Comment by pyrello** [comment]
> We will want to link to the address schema for these buildings from the named buildings. @pyrello does this capture this accurately?

- Build a schema.org output for buildings.
- Reference the building page URL in named building schema. Potentially using `SameAs`.

**Comment by briand44** [comment]
Grooming conversation... Include schema.org as part of this but any altering that would need to be done would be out of scope for this slice.

Hard code accessibility links for now and if they change in the future we could add a settings page where they control those links.

**Comment by pyrello** [comment]
Going to work on this.

**Comment by pyrello** [comment]
A lot of these fields have this text: "Structure needed..."

@briand44 What does that mean?

**Comment by briand44** [comment]
@pyrello The ones that say "Structure needed" I assumed we would create some sort of field on the content type. For something like the accessibility links I wasn't sure if it made sense to field those vs just hardcoding those in a template or something since they will be the same for all buildings. Feel free to go a different direction if I am just getting in the way here.

**Comment by pyrello** [comment]
I just wasn't sure if that meant that the field was supposed to be a field collection or paragraph. Thanks for the clarification!

**Comment by pyrello** [comment]
It looks like `imageUrl` is present but empty in the API call for all buildings. It appears to be populated in the individual building API call. I'm wondering if this is a bug with the API and whether its possible to have it fixed? Otherwise, it seems like we'll need to make an extra API call for every single building.

**Comment by pyrello** [comment]
In the case of all the restroom and lactation rooms fields, it looks like those are only populated on the individual API endpoint feed and don't even have empty records on the buildings API endpoint feed. I'm guessing this means we'll have to make separate calls no matter what.

**Comment by briand44** [comment]
I had a call with Rakesh this morning and they are not able to add the `imageUrl` to the all buildings endpoint. There is something special about that field so we are going to need to move forward with calling the specific building endpoint for the remaining data.

**Comment by pyrello** [comment]
We are expanding scope on this a bit to investigate implementing a repeatable process for syncing entity fields from an source such as an API. This is going to happen in tandem with #6180. In the case of this issue, the process will handle the creation/update/deletion of entire building records to sync them with the API sources. In the case of #6180, it will be the partial automated update of classroom nodes to sync some fields.
