### ISSUE TITLE
Tippie profiles not indexing: module?

### ISSUE THREAD

**Issue by makurj** [uiowa/uiowa#5826]
Profiles not showing up in Google Search: Wiaguo Fan, Kurt Anstreicher, Lon Moeller, Mark Penno, and Hope Koch.
http://tippie.uiowa.edu/people/ramji-balakrishnan
http://tippie.uiowa.edu/people/thomas-r-berry-stoelzle

For Hope Koch, if do a search for "Hope Koch Tippie", the /people page does show up. But not if I only search for "Hope Koch", at least not the first 10 results.

![image](https://user-images.githubusercontent.com/52135878/194893472-27e94212-90b8-4207-a76a-fae63c2e4b98.png)

From Michael:
"Starting to see a flood of Server error 500 errors in search console related to people directory pages. 

If you are seeing folks drop out of search, this is likely the root cause. 

When the issues are addressed, resubmitting the sitemap is probably in order…as will be clicking the “Verify issue is fixed” button search console."
[https___tippie.uiowa.edu_-Coverage-Drilldown-2022-10-06.xlsx](https://github.com/uiowa/uiowa/files/9746934/https___tippie.uiowa.edu_-Coverage-Drilldown-2022-10-06.xlsx)

**Comment by makurj** [comment]
Tippie sitemap resubmitted on Monday, October 10, 2022 after the creation of this issue to see if it resolves this problem.

**Comment by briand44** [comment]
Closing this as I think things are in good shape now.
