### ISSUE TITLE
Images missing on Academic Groups page

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5827]
>We lost the images on the top of the blocks on our Academic Groups page: https://admissions.uiowa.edu/academics/groups.
>
>There use to be a photo at the top of all of them.

Wayback still has the file names listed that we could use to add the images back https://web.archive.org/web/20220703143743/https://admissions.uiowa.edu/academics/groups. (bspeare)

**Comment by e-marie-w** [comment]
Added back the images and cleared caches (site and Varnish). Going to respond to Scott's message in Slack and let him know it's fixed.

**Comment by e-marie-w** [comment]
Scott gave thumbs-up so closing.
