### ISSUE TITLE
Iowa Summer Writing Festival D9 site

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#5829]
Standard checklist for site provision, installation, and creation:
- [x] Provision and install site
- [ ] Create internal Festival --< Session >--< Workshop >--< Instructor custom structure for use on the site #5732 
- [x] Migrate existing content into new D9 site
- [ ] Add strategy and messaging content from CLAS MarCom
- [ ] Web copy updates from CLAS MarCom
- [ ] New photography as needed
- [ ] Add Google Analytics GA4 web property ID from CLAS GA account
- [ ] Unit approves launch
- [ ] Launch site
- [ ] Create .htaccess redirect from D7 site (if needed)

Existing site: [https://iowasummerwritingfestival.org](https://iowasummerwritingfestival.org)

New site: [https://iowasummerwritingfestival.uiowa.edu](https://iowasummerwritingfestival.uiowa.edu)

**Comment by joewhitsitt** [comment]
This site has launched spring 2023
