### ISSUE TITLE
Deprovision `shops.clas.uiowa.edu` site on `uiowa01`

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#5831]
- This has a prod domain [classhops.prod.drupal.uiowa.edu](http://classhops.prod.drupal.uiowa.edu/AH_VIEW) and database on uiowa01. 
- Remove from https://cloud.acquia.com/ 
- Check local sites and blt files for any drush aliases

<details>
Standard checklist for site provision, installation, and creation:
- [ ] Provision and install site
- [ ] Copy default content and settings from CLAS Template
- [ ] Migrate existing content into new D9 site
- [ ] Add strategy and messaging content from CLAS MarCom
- [ ] Web copy updates from CLAS MarCom
- [ ] New photography as needed
- [ ] Add Google Analytics GA4 web property ID from CLAS GA account
- [ ] Unit approves launch
- [ ] Launch site
- [ ] Create .htaccess redirect from D7 site (if needed)

Existing site: [https://clas.uiowa.edu/shops](https://clas.uiowa.edu/shops)
</details>

**Comment by bspeare** [comment]
It sounds like they are considering putting this into the new clas.uiowa.edu redesign.   Do we need to deprovision anything here?

**Comment by bspeare** [comment]
This has a prod domain [classhops.prod.drupal.uiowa.edu](http://classhops.prod.drupal.uiowa.edu/AH_VIEW) and database on `uiowa01`.    Do we just remove these from the https://cloud.acquia.com/ or is there more to do here?

**Comment by joewhitsitt** [comment]
> This has a prod domain [classhops.prod.drupal.uiowa.edu](http://classhops.prod.drupal.uiowa.edu/AH_VIEW) and database on `uiowa01`. Do we just remove these from the https://cloud.acquia.com/ or is there more to do here?

I believe so. `classhops` and `shops.clas` do not appear in our codebase which is the other part of our deprovision script.

**Comment by joewhitsitt** [comment]
This is done.
