### ISSUE TITLE
Committee on Sustainability and the Environment D9 site

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#5832]
Standard checklist for site provision, installation, and creation:
- [ ] Provision and install site
- [ ] Migrate existing content into new D9 site
- [ ] Add strategy and messaging content from CLAS MarCom
- [ ] Web copy updates from CLAS MarCom
- [ ] New photography as needed
- [ ] Add Google Analytics GA4 web property ID from CLAS GA account
- [ ] Unit approves launch
- [ ] Launch site
- [ ] Create .htaccess redirect from D7 site (if needed)

Existing site: [https://clas.uiowa.edu/cse](https://clas.uiowa.edu/cse)

**Comment by bspeare** [comment]
This site hasn't been touched since 2017 and I doubt it will need to be migrated to D10.

**Comment by briand44** [comment]
removed D7 site
