### ISSUE TITLE
iowamommoodbooster.org D9 site

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#5836]
Standard checklist for site provision, installation, and creation:
- [x] Provision and install site
- [ ] Migrate existing content into new D9 site
- [ ] Add strategy and messaging content from CLAS MarCom
- [ ] Web copy updates from CLAS MarCom
- [ ] New photography as needed
- [ ] Add Google Analytics GA4 web property ID from CLAS GA account
- [ ] Unit approves launch
- [ ] Launch site
- [ ] Create .htaccess redirect from D7 site (if needed)

Existing site: [https://iowamommoodbooster.org](https://iowamommoodbooster.org)

**Comment by briand44** [comment]
Closing this issue because this site is no longer needed.
