### ISSUE TITLE
OSTC D9 site

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#5838]
Standard checklist for site provision, installation, and creation:
- [ ] Provision and install site
- [ ] Migrate existing content into new D9 site
- [ ] Add strategy and messaging content from CLAS MarCom
- [ ] Web copy updates from CLAS MarCom
- [ ] New photography as needed
- [ ] Add Google Analytics GA4 web property ID from CLAS GA account
- [ ] Unit approves launch
- [ ] Launch site
- [ ] Create .htaccess redirect from D7 site (if needed)

Existing site: [https://ostc.uiowa.edu](https://ostc.uiowa.edu)

**Comment by joewhitsitt** [comment]
@briand44, @bspeare  do you know anything about this site?

**Comment by bspeare** [comment]
OSTC is no longer a site: https://iowaweb.slack.com/archives/C0164FNN1PV/p1646419032793829.

**Comment by joewhitsitt** [comment]
Looks like it is still pointed at Acquia. Should we ask hostmaster to reclaim and close this issue?

**Comment by bspeare** [comment]
Yes, I will email hostmaster now.
