### ISSUE TITLE
Record one tutorial for a SiteNow v3 video library

### ISSUE THREAD

**Issue by mkyoder** [uiowa/uiowa#5848]
# Story
As a web community site visitor, I can see a short training video tutorial showing an aspect of Layout Builder in SiteNow v3.

# Additional Information
Training videos would be hosted on the web community site, showing various aspects of Layout Builder (e.g. how to add person, events, articles, collection item, call to action, etc). 

# Proposed Solution
As a first slice, want to record one video for now in order to get feedback from the OSC web team and Iowa Web Community before additional videos are recorded or even considered. 

Screen recording would be done by Megan with voice-over by Alan.

**Comment by briand44** [comment]
Should these be hosted on the web community site or should they be hosted on the SiteNow site and linked to from the web community site?

**Comment by bspeare** [comment]
@mkyoder are you able to share the outline for the video training with the web team?

**Comment by mkyoder** [comment]
@bspeare Sure! Here is a short script/outline for just one training video. I didn’t write out other scripts since just doing one video would be a first slice. 

I choose the element of how to add an event in layout builder for this particular video.

Link here: https://iowa.sharepoint.com/:w:/s/OSCWebTeam/ETLP7EFmZPdAhfoEk0hbuGcBP4Ff8ZwZP-rkCpoRRwUegA?e=OK4uS1 

Let me know if you have questions and happy to talk through anything. :)

**Comment by bspeare** [comment]
@mkyoder Thanks for sharing!

**Comment by briand44** [comment]
Sounds like this is no longer relevant based on our current trainings and the ability to jump to specific chapters in the training videos.
