### ISSUE TITLE
Epic - As a developer, I can use the new 4.x card component in uids_base

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#5849]
# Story

As a developer, I can use the new 4.x card component in uids_base

# Proposed solution
All slices will be done in the same pull request and distributed over multiple sprints. 

- [x] #5970 
- [x] #5971 
- [x] #5972

**Comment by briand44** [comment]
blocked by https://github.com/uiowa/uids/issues/781

**Comment by bspeare** [comment]
I briefly investigated integrating https://github.com/uiowa/uids/pull/785 into `uids_base`.  I was wrong that we could possibly scope this to just the card block since all the other list blocks use the same layout builder styles.   

It's probably best to update everything in one sprint   I have updated the proposed solution to reflect this.

**Comment by briand44** [comment]
Added needs grooming again because at a minimum we need to point/size this.

**Comment by briand44** [comment]
I will create separate issues for the slices and link to them from this epic.

**Comment by pyrello** [comment]
This is done.
