### ISSUE TITLE
Add subtitle to Area of Study PDFs

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5858]
# Story

As an Admissions website owner, I would like to display the Area of Study subtitle on the PDFs.

# Additional Info

>We would like the “subtitle” areas of study field to be added to the PDF version if there is content. We don’t use this a lot now, but will be bringing that into more in the near future. It can show up under the main heading in larger type than the body copy.

Since they will be using the subtitle for the AoS display at the visitor center, they will be using this field more and increases the desire to display on printable pdfs.

We have flexibility to figure out what looks best here.

Here is an example of an Area of Study that contains subtitle info.
https://admissions.uiowa.edu/node/2716/edit
https://admissions.uiowa.edu/print/pdf/node/2716

# Proposed solution

- Add subtitle to printable pdf, which could cause multiple pages (need to print in twig file)
- Share with Scott so they can be aware they may need to adjust content to keep within single page

**Comment by briand44** [comment]
Question from inbox... Are we still trying to keep these within a single page?

**Comment by bspeare** [comment]
I looked at this locally and because only a few majors have the subtitle content so far, it's hard to know if this will overflow some pages.    I think we can proceed with this planned work and they can make edits to each area of study as needed to keep some majors within a single page.

**Comment by bspeare** [comment]
I added a question in Slack for Scott on the placement of the field and the styling: https://iowaweb.slack.com/archives/C019B2C8K8U/p1688153694392559

**Comment by bspeare** [comment]
Response is "Yes, it does need a little styling to make it stand out a bit."
