### ISSUE TITLE
Investigate long term strategy for managing custom AD role mappings

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#5862]
Follow-up to #5702.

When we groomed #5702, we discussed that we want to use a site split to handle setting up custom AD role mappings for the Student Life intranet site. We decided to go with the site split because that would more easily allow us to determine what sites were overriding it should some issue with security come up. If this becomes a more widely-used feature, it would be desirable to not have to create a site split for every site that wants to customize its AD role mappings. This would require us to better understand the security implications so we can have confidence in moving away from customizations via site splits.

# Proposed solution

- Appropriate config ignore settings
- Remove existing splits
- Construct a query to get a list of sites with custom mappings using `blt ume`

**Comment by joewhitsitt** [comment]
`config:get uiowa_auth.settings role_mappings` will print the values which will have defaults. looking to see if i can filter it a bit to see just the non-default ones.

**Comment by joewhitsitt** [comment]
Sites with existing config splits:

- brand
- connect.studentlife (only thing in split, so remove split)
- sitenow
- sppa

**Comment by joewhitsitt** [comment]
```
ddev drush @studentlifeconnect.prod config:get config_split.config_split.site status
 [error]  Config config_split.config_split.site does not exist 
```

Was there a reason why this split was not yet turned on? https://github.com/uiowa/uiowa/pull/5883

Turning this on in PROD before removing or manually adding after this deploys needs to happen

<details>
<summary>plain list for populating manually</summary>
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Womens-Resource-and-Action-Center-S4635,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Womens-Resource-and-Action-Center-D4635,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Vending-Service-D4770,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-University-Counseling-S4660,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-University-Counseling-D4660,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Support-Service-Programs-D4630,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Student-Services-S4600,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Student-Services-D4600,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Student-Organizations-S4690,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Student-Organizations-D4690,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Student-Health-Service-S4695,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Student-Health-Service-D4695,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Student-Disability-Services-S4640,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Student-Disability-Services-D4640,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Student-Activities-S4625,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Student-Activities-D4625,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Retail-Operations-S4742,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Retail-Operations-D4742,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Residence-System-General-Administration-S4780,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Residence-System-General-Administration-D4780,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Residence-System-Facilities-D4775,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Residence-Services-S4899,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Residence-Services-Other-Funds-D4898,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Residence-Services-D4899,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Residence-Hall-Routine-Maintenance-S4726,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Residence-Hall-Routine-Maintenance-D4726,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Residence-Hall-Residence-Life-S4720,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Residence-Hall-Residence-Life-D4720,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Residence-Hall-Food-Service-D4750,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Residence-Hall-Educ-and-Cultural-Programs-D4735,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Residence-Hall-Custodial-Services-S4724,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Residence-Hall-Custodial-Services-D4724,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Residence-Hall-Assignments-D4730,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Res-Hall-Educ-and-Cultural-Pgms-S4735,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Recreational-Services-S4685,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Recreational-Services-D4685,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Rape-Victim-Advocacy-Program-D4603,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Quadrangle-Food-Service-D4752,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-OSMRC-D4602,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Old-Capitol-Museum-S4670,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Old-Capitol-Museum-D4670,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Museum-of-Natural-History-D4605,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-MISSE-D4616,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Iowa-Memorial-Union-S4655,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Iowa-Memorial-Union-D4655,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Hillcrest-Food-Service-S4754,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Hillcrest-Food-Service-D4754,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Dean-of-Students-D4604,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Catlett-Marketplace-D4758,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Career-Development-Services-D4610,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Campus-Dining-Operations-S4740,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Campus-Dining-Operations-D4740,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Campus-Dining-Administration-S4750,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-C-Stores-S4744,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-C-Stores-D4744,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Burge-Food-Service-S4756,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Burge-Food-Service-D4756,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Banquets-and-Catering-S4746,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Banquets-and-Catering-D4746,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Apartment-Maintenance-and-Grounds-D4765,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Apartment-Housing-S4760,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Apartment-Housing-D4760,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Alumni-Services-S4680,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services-Alumni-Services-D4680,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=Student-Services,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
'viewer|urn:oid:2.5.4.31|CN=HSG-GSG-IT-SiteNow-Exceptions,OU=Groups,OU=HSG,OU=SSer,DC=iowa,DC=uiowa,DC=edu'
</details>

**Comment by joewhitsitt** [comment]
Went ahead and turned the connect.studentlife split on to populate the role mappings.

**Comment by joewhitsitt** [comment]
Moving forward with writing the query in a custom drush command to be run with blt ume as the config-get returns all values (including the defaults). There is no `--filter` option for config-get.
