### ISSUE TITLE
Investigate adding ID's to ListBlock block types (articles, people)

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5863]

**Comment by briand44** [comment]
Challenge is we don't have an entity to attach a field to.

May depend on a core patch.

**Comment by pyrello** [comment]
Unless I'm misunderstanding this issue, it seems like this functionality already exists. Just looking at the Sandbox site and configuring an existing articles block I see the unique ID field and when I set the value it gets stored and renders in the HTML markup.

> Challenge is we don't have an entity to attach a field to

Maybe we thought this was the case before we actually implemented it? The ID doesn't get stored with the block, but rather is part of the third party setting in the component (added via a patch).

I think this is done.
