### ISSUE TITLE
Create remaining CLAS site provisions on uiowa04 once created

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#5864]
- [x] Remove the existing *.prod.drupal.uiowa.edu domains from the uiclas application.
- [x] Edit the new uiowa04 SSL certificate to cover the following sites with the addition of the SSL code below.
- [x] Add prod.drupal domains to uiowa04 for each site listed below.
- [x] Run site provision process for following lists.
- [ ] Run cleanup on SSL and domains as listed below. #5973 

### Here are previous subdirectory sites that need to be provisioned:
~~https://linux.clas.uiowa.edu (adding to uiowa01)
https://gwss.uiowa.edu
https://hhp.uiowa.edu
https://philosophy.uiowa.edu
https://politicalscience.uiowa.edu
https://productionunit.uiowa.edu
https://religion.uiowa.edu
https://rhetoric.uiowa.edu~~

### and here are existing subdomain sites that need to be provisioned:
~~https://clas.uiowa.edu
https://art.uiowa.edu
https://biology.uiowa.edu
https://chem.uiowa.edu
https://dance.uiowa.edu
https://deltacenter.uiowa.edu
https://dpa.uiowa.edu (may be deprovisioned later)
https://english.uiowa.edu
https://instructional-resources.physics.uiowa.edu (added to uiowa01)
https://iowamommoodbooster.org
https://math.uiowa.edu
https://music.uiowa.edu
https://nanotech.uiowa.edu
https://pda.uiowa.edu
https://psychology.uiowa.edu
https://sloancenter.uiowa.edu
https://speakingcenter.uiowa.edu
https://stat.uiowa.edu
https://geemap.stat.uiowa.edu
https://sustainability.uiowa.edu
https://theatre.uiowa.edu
https://writersworkshop.uiowa.edu
https://writingcenter.uiowa.edu~~

### SSL certificate will need to be created that adds the following domains:
uiowa04.prod.drupal.uiowa.edu, *.biology.uiowa.edu, *.conference.uiowa.edu, *.course.uiowa.edu, *.grad.uiowa.edu, *.lab.uiowa.edu, *.org.uiowa.edu, *.prod.drupal.uiowa.edu, *.research.uiowa.edu, *.sites.uiowa.edu, *.stat.uiowa.edu, *.studio.uiowa.edu, art.uiowa.edu, biology.uiowa.edu, cheec.uiowa.edu, chem.uiowa.edu, clas.uiowa.edu, dance.uiowa.edu, deltacenter.uiowa.edu, dpa.uiowa.edu, english.uiowa.edu, gwss.uiowa.edu, hhp.uiowa.edu, iowamommoodbooster.org, math.uiowa.edu, music.uiowa.edu, nanotech.uiowa.edu, pda.uiowa.edu, philosophy.uiowa.edu, politicalscience.uiowa.edu, productionunit.uiowa.edu, psychology.uiowa.edu, religion.uiowa.edu, rhetoric.uiowa.edu, sloancenter.uiowa.edu, speakingcenter.uiowa.edu, stat.uiowa.edu, sustainability.uiowa.edu, theatre.uiowa.edu, writersworkshop.uiowa.edu, writingcenter.uiowa.edu

## Followup

See #5973 for cleanup after this issue.

**Comment by joewhitsitt** [comment]
uiowa04 has been created, but I think some of these are on hold since there is an open discussion about the rest of the sub directory acronym sites like gwss and hhp that stemmed from the ctgl request

**Comment by briand44** [comment]
Closing this as gwss and hhp have been provisioned.
