### ISSUE TITLE
Setup Uiowa Hours for Law Library

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5874]
# Story

As an owner of library.law.uiowa.edu, I would like to use Exchange to manage Library and Reference hours similar to Rec Services so that we can schedule hours and not have to make updates to the website when hours are regularly changing.

# Additional Information
The resources need to be setup in Outlook first.
CSI app devs need to add resources to API

# Proposed solution

- [x] Turn on feature split "uiowa hours"
- [x] Configure group for Law Library on settings page.
- [x] communicate with partners at Law Library

**Comment by briand44** [comment]
>Okay, these are set up. Web Team, you can access them at the usual API location:
 >
>https://hours.iowa.uiowa.edu/api/hours/lawlibrary/res-law-lib-libhrs
https://hours.iowa.uiowa.edu/api/hours/lawlibrary/res-law-lib-refhrs
> 
>Please let me know if you have any questions.

**Comment by joewhitsitt** [comment]
enabled, configured and emailed Amy on the original hours request email thread.
<img width="679" alt="Screenshot 2023-04-21 at 11 01 21 AM" src="https://user-images.githubusercontent.com/4663676/233683103-e6eaedd8-cee8-4fd3-a6f3-0e95d74826ed.png">
