### ISSUE TITLE
Law Library service areas for people

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5876]
# Story

As an owner of library.law.uiowa.edu, I would like to be able to enter service areas related to a staff member and be able to filter by those service areas on the staff directory page so users can quickly find the correct contact person.

# Additional Info
I put Law Library in touch with Ed and Denny because they have a desire to output faculty publications at some point and Law Library was interested in learning more about Directory Profiles.

# Questions
Assuming they don't go with Directory Profiles at this point in time would we want to use the existing research areas field and rename the label to be service areas or is this a custom field and filter for Law Library?

### Next steps:
- [ ]  Deploy with current PR
- [ ]  Update sites manually to "Service Areas" for Law Library and "Practice Areas" for Pharmacy
- [ ]  Remove patched config for Pharmacy
- [ ]  Deployment

**Comment by briand44** [comment]
Blocked until Law Library has a conversation about Directory Profiles.

**Comment by pyrello** [comment]
It seems that this is a not uncommon request, being able to change the label for "Research areas". I'm wondering if it would make sense for us to invest in allow the label to be customizable?

Also, or alternately, I'm wondering if "Research areas" should be renamed as a default to something like "Areas of focus" which would allow for a much broader application without the need to re-label?

**Comment by joewhitsitt** [comment]
I feel like we have resisted a few times but we have already caved once. Pharmacy has "Practice areas." In reality, if we are serving the entire campus here, faculty terminology is not always going to apply. Fair warning, if we cave here, I imagine expanding person types will be next.

I like the idea of a customizable label that could be set in SiteNow People's config. It is a pretty small footprint of what would be ignored.

https://github.com/uiowa/uiowa/blob/main/config/sites/pharmacy.uiowa.edu/config_split.patch.taxonomy.vocabulary.research_areas.yml
https://github.com/uiowa/uiowa/blob/main/config/sites/pharmacy.uiowa.edu/config_split.patch.field.field.node.person.field_person_research_areas.yml

**Comment by briand44** [comment]
I got some updates from Law Library. They are transitioning to use the Libraries Esploro for their faculty bibliographies and such. They still do want to output a staff directory on their site and would still like to have the label "Service Area" in place of the "Research Area" filter.

**Comment by briand44** [comment]
Grooming conversation... Let's plan to make the label configurable for the service. There is also research area terminology on the config page. Not sure if that is updatable as well? Identifying areas where existing splits could be resolved by this would be nice but they would be addressed in future slices.
