### ISSUE TITLE
in progress events

### ISSUE THREAD

**Issue by cory-skeers** [uiowa/uiowa#5878]
We want events to be able to pull in events that are currently in progress (ie start date prior to today, end date after today). Currently there is no way to pull these in without having both the start date and end date encompass the event.

# Proposed Solution
Add a new display_id to events api that is a copy of Events from the Events API. Remove the Start Date constraint. Change End Date constraint to events with an end date after the provided date.
Update sitenow_events.module parameter handling in the case that it is upcoming (ie not date_range or past): Remove the start date and set the end date to Today instead of 31-12-2037
Update help text on the block
Let Chris C. know this is happening.

**Comment by briand44** [comment]
Could communicate with events-calendar Slack to let folks know of this new endpoint.

**Comment by briand44** [comment]
Normal communications fine for this.. Demo and monthly article.

**Comment by joewhitsitt** [comment]
Update help text around the upcoming selection to make it clear that in-progress events will be displayed as well.

**Comment by bspeare** [comment]
How do we want to deploy https://github.com/uiowa/uiowa/pull/5892 and the content hub work on `702` so these roll out at the same time?

**Comment by briand44** [comment]
>How do we want to deploy https://github.com/uiowa/uiowa/pull/5892 and the content hub work on 702 so these roll out at the same time?

Do they need to role out at the same time? Can Content Hub work go out first?

**Comment by bspeare** [comment]
I think since we are only creating new views in Content Hub and not touching existing views, we should be able to push those out first.
