### ISSUE TITLE
SiteNow events parent/child functionality

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5879]
Capturing from internal-demo:

- [x] - CLAS approval to move forward with single content type parent/child representation and event type classification.
- [x] - Keep reference field to the parent event (superEvent) and removing the child event (subEvent) reference field.
    - [x] Remove add new event?
- [x] - Views block to list out child events chronologically based on parent relationship.
- [x] - Rip out the schema.org subtype field and module (schemadotorg_subtype). Instead move forward with event category to designate festival, session, workshop for now by changing it to a single value/dropdown and consider moving it out from the sidebar. Remove sitenow_events_event_types_options_allowed_values
- [x] - Update Series Link label to Source Link (communicate this change to be more generic with Scott)
- [x] - Make sure admissions, oniowa can accept changes (no config import issues)
- [x]   - Change the schema prefix to `field_` to match our field naming convention.
- [x] - [Alter json-ld](https://github.com/uiowa/uiowa/blob/99fe091eb33c0e3a0ab76591c3a4252331f0fec3/docroot/modules/custom/sitenow_events/sitenow_events.module#L659) to include subEvent info of all child events (view results).
    - [ ] Bare minimum has been done here, is there more to do? 
- [x] - Basic styling based on new content being output (reference to other events, performer, event categories).
- [x] - Update the event path to include the nid to aid with multiple events with the same name. - > Capturing eventID for pathing, e.g. /event/12345/human-readable-title - https://github.com/uiowa/uiowa/issues/5810#issuecomment-1282972378
- ~Currently blueprint modules are on for default. Decide if these can still be here or if they and the related config should move to the event feature for now.~ - https://github.com/uiowa/uiowa/issues/5879#issuecomment-1292291442

Separate issue: making person content type more flexible to single line value name or offer another content type to handle multiple types of event performers.

Scope this to events feature and not iswf split in this slice.

**Comment by joewhitsitt** [comment]
I wonder if we can change event category to be a single value dropdown and move it out of the sidebar on the form. It looks like Admissions is currently only using one value per event for this field. By changing this, I think it allows better control over showing additional fields, changing styles, etc. later on.

If Admissions needs this, we can update their split to remain unchanged.

**Comment by joewhitsitt** [comment]
>Changes based on workflow decision such as removing one of the relationships and replacing with a programmatic view to represent it and alter the json-ld to include it.

Post parking lot discussion was leading towards a reference field to the parent event (superEvent) and removing the child event (subEvent) reference field. The event would then have a views block that listed any children events chronologically and the json-ld would be altered to include sub event items.

Team also was on-board with changing event category to a single value and communicating with Admissions about the change to see if they would accept the change or like to be split further from the feature.

**Comment by joewhitsitt** [comment]
In the huddle we realized how "Event categories" is admissions specific and not a good base for what we want to do in the future. It also does not really handle ISWF's needs.

Proposed solution:

- Remove event categories (field, taxonomy, permissions) from the event split after making sure it stays in the admissions split (complete item). OnIowa should be able to accept the removal because no content has been added to it.

**Comment by GaryRidgway** [comment]
So i would be removing the item manually from the config in events, adding it to admissions, and then checking that it works?

**Comment by joewhitsitt** [comment]
Sync admissions while on the PR branch. In the site config split interface, add the taxonomy, field storage items to the complete split. `config-split:export site` and see that the config items move from feature/event to site/admissions.uiowa.edu. Then on your default site, remove the field and taxonomy from the structure interface, update the split to remove those declarations and `config-split:export event` to see those things remove. Try syncing admissions again to see that event categories is still functional

**Comment by joewhitsitt** [comment]
Here is the expected structure of subEvents in the json-ld

```json
  "startDate" : "2016-08-06",
  "endDate" : "2016-08-13",
  "subEvent" : "http://www.olympic.org/rio-2016-summer-olympics",
  "subEvent" : "http://www.olympic.org/london-2012-summer-olympics"
```

**Comment by joewhitsitt** [comment]
>Currently blueprint modules are on for default. Decide if these can still be here or if they and the related config should move to the event feature for now.

Based on the possibility of other content types using the functionality in the near future, I think leaving them where they are should be fine, so no action there I think.

>Change the schema prefix to field_ to match our field naming convention.

config/default/schemadotorg.settings.yml
field_prefix: ''

**Comment by joewhitsitt** [comment]
>[Alter json-ld](https://github.com/uiowa/uiowa/blob/99fe091eb33c0e3a0ab76591c3a4252331f0fec3/docroot/modules/custom/sitenow_events/sitenow_events.module#L659) to include subEvent info of all child events (view results).

Took a bare minimum stab at this with EnityQuery and following https://stackoverflow.com/questions/60524805/schema-org-nesting-events since https://github.com/uiowa/uiowa/issues/5879#issuecomment-1292285831 with same keys doesn't work well for php or json.

https://github.com/uiowa/uiowa/pull/5869/commits/b7a0519913ba229eac4f669a4337eb960ff4f69f

**Comment by joewhitsitt** [comment]
>- Alter json-ld to include subEvent info of all child events (view results).
>   - Bare minimum has been done here, is there more to do?

I've seen examples where almost all of the sub event info is provided as well. Not sure how far we need to go. It currently only establishes that there are sub events by printing the names of the sub events. Establishing the relationship in schema.org was kind of add-on to begin with. We can extended it as needed later on.

Currently no-errors/warnings

<details>

```json
{
    "@context": "https:\/\/schema.org",
    "@type": "Event",
    "@url": "https:\/\/default.uiowa.ddev.site\/event\/8-test-parent-event",
    "url": "https:\/\/events.uiowa.edu",
    "identifier": [
        {
            "@type": "PropertyValue",
            "propertyID": "uuid",
            "value": "2f93587d-9c9f-4837-9e4e-c58d83ed956b"
        }
    ],
    "inLanguage": "en",
    "name": "Test Parent Event",
    "description": "Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Nunc nonummy metus. Phasellus volutpat, metus eget egestas mollis, lacus lacus blandit dui, id egestas quam mauris ut lacus.",
    "eventSchedule": {
        "@type": "Schedule",
        "startDate": "2022-11-03",
        "startTime": "17:00:00",
        "endTime": "18:00:00",
        "duration": "PT1H"
    },
    "location": [
        {
            "@type": "PostalAddress",
            "addressCountry": "US",
            "addressRegion": "IA",
            "addressLocality": "Iowa City",
            "postalCode": "52242",
            "streetAddress": "201 S Capitol Street"
        },
        {
            "@type": "VirtualLocation",
            "url": "https:\/\/zoom.us\/asdf"
        }
    ],
    "subEvent": [
        {
            "@type": "Event",
            "name": "Sub Event One"
        }
    ]
}

```
</details>

**Comment by joewhitsitt** [comment]
Moved forward with `event/[node:nid]-[node:title]` because we wanted to avoid 404s with folks visiting `event/[node:nid]/` and prefixed it to avoid collision with the `-0`, `-1` unique title functionality that drupal implements

**Comment by joewhitsitt** [comment]
There was more discussion about `event/[node:nid]/[node:title]` but to avoid the 404 we will want to eventually handle the redirect. If we can alter route based on `event/[node:nid]` to send it to `node/[node:nid]` drupal already sends this back to the aliased path.

Curious to get @mjoneill's thoughts about the ideal path for this.

**Comment by mark-bennett-uiowa** [comment]
Thoughts for discussion from latest huddle:

Link directly to source checkbox is outside of the fieldset region of the Series/Source Link fields.
![Screen Shot 2022-10-28 at 11 26 49 AM](https://user-images.githubusercontent.com/3067017/198686498-e5b321c1-3987-4950-b470-86931341d2e7.png)

Rather than have the label "Parent event:" at the bottom, which points to the super event on a specific event, can we change this label to "Part of:" OR build out the breadcrumb trail to show hierarchy of events?
![bread](https://user-images.githubusercontent.com/3067017/198696387-92f596ec-ef81-4457-99c3-c0a702178c87.jpg)

- If we are doing this for ease of navigation for users, does it make sense to solve one way or the other?
- Do we actually need to link to parent events?
  - Drupalcon does not link back to a "parent event": [https://events.drupal.org/portland2022/sessions/ladies-who-launch-tech-leadership-taking-business-new-heights](https://events.drupal.org/portland2022/sessions/ladies-who-launch-tech-leadership-taking-business-new-heights)
  - And neither does HighEdWeb: [https://events.highedweb.org/heweb22/session/897391/kss-on-my-list-building-a-living-style-guide-and-pattern-library-with-kss-node](https://events.highedweb.org/heweb22/session/897391/kss-on-my-list-building-a-living-style-guide-and-pattern-library-with-kss-node)

One other note, is that highedweb does the session/ID/title URL, and if you remove the title, it still loads the same session as session/ID.

**Comment by joewhitsitt** [comment]
>Link directly to source checkbox is outside of the fieldset region of the Series/Source Link fields.

This is the same as AoS and would be the same for Article if link title was available. Both AoS and Article only display the boolean if the link URL is filled. That might help. Not saying it is ideal, but this is a link field wrapper and it would be work to move that checkbox (separate field) into it. This is already out there and I believe is out of scope for this issue.

---

I think "Part of" or "As featured in" or something else sounds like a good slice to me. Breadcrumbs are currently menu link based so work would have to be done similar to sitenow_articles_preprocess_breadcrumb to wrangle it if a parent exists. I think a linked entity label is best for MVP.

**Comment by mark-bennett-uiowa** [comment]
Sounds good on both of the above @joewhitsitt thank you. I think Ill just go with "Part of:" or "As featured in:" for now.

Another question about this is the formatting of the "meta data" in the right column:
On our current articles and events view lists and node view, we are displaying the full date as "Monday, January 1st, 2022 1:30pm to 2:30pm" in Zilla Slab font.
- articles list the published data underneath the article title.
- content hub events list the event date(s) in the right-hand column on the individual event page.

The local events view listing does not show date/time currently, and the node view displays the date/time in the right-hand column in Roboto font and have a prepended FA icon, and are currently using a shorthand date format of "Mon, Jan 1 2022, 12 - 1pm".

Do we want to make the date format of these local events similar in date format and style?
Did the team want to standardize this moving forward (out of scope of this project)?

- Date/time
- Location
- Links
- etc. for Articles, Events, People, Local events

**Comment by joewhitsitt** [comment]
@bspeare do you recall anything about why those fonts/formats were chosen? I'd look to https://admissions.uiowa.edu/ (articles and events blocks). I know Admissions had opinions and then this: https://github.com/uiowa/uiowa/issues/2727

**Comment by bspeare** [comment]
@joewhitsitt the sitenow event template needs to be updated (https://github.com/uiowa/uiowa/issues/4916).  I think the hope is that we will update that template with the design that is finalized here.

**Comment by joewhitsitt** [comment]
So @mark-bennett-uiowa maybe keep date format and font style out of scope?

**Comment by mark-bennett-uiowa** [comment]
Sounds good

**Comment by mjoneill** [comment]
> There was more discussion about event/[node:nid]/[node:title] but to avoid the 404 we will want to eventually handle the redirect. If we can alter route based on event/[node:nid] to send it to node/[node:nid] drupal already sends this back to the aliased path.
> 
> Curious to get @mjoneill's thoughts about the ideal path for this.

Anyone available at 2:00 to discuss?  

I'm not sure I'm picking up on all the nuances of the ask here.

**Comment by joewhitsitt** [comment]
I believe one of us should be available. Just reach out when it works

**Comment by joewhitsitt** [comment]
@mjoneill ^^

**Comment by joewhitsitt** [comment]
Thanks Michael for zooming with us. We have updated the todo on #5869 to address the discussion
