### ISSUE TITLE
Migrate In the News, News Feature and Achievements to articles

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5887]
# Story

As an Iowa Now website owner, I would like In the News, News Feature and Achievements programmatically migrated to our new SiteNow v3 site so that we don't have to manually re-create all of this content.

# Additional Info

**Achievements**
Migrate all achievements
When migrating set the Article type = Achievement

Title -> Title
ByLine -> Organization
Category - migrate as tags
Contacts -  ignore this since their contacts are a mess and they wanted to start fresh
Primary Media -> Featured Image - When migrating, if there is a primary media item that is a video, we should append to body. Default to hide featured image when migrating
Primary Media Caption -> Caption? #3561 
Teaser -> Article Summary
Body -> Body
Display Expired link message -> Preserve Links
News From - migrate as tags
News About - migrate as tags
News For - migrate as tags
Keywords - migrate as tags

**In the News**
Migrate all In the News content
When migrating set Article type = Spotlight when source url contains uiowa.edu otherwise Article type = In the News
*Source and Url are a field collection and allow multiples - If we run into multiples during migration, just pull over the first.

Title -> Title
*Source -> Organization
*Url -> Source Link
Original Pub Date -> Original Pub Date
Body -> Body
Primary Media -> Featured Image - When migrating, if there is a primary media item that is a video, we should append to body. Default to hide featured image when migrating
News From - migrate as tags
News About - migrate as tags
News For - migrate as tags
Keywords - migrate as tags

**News Feature**
Migrate all News Feature content
When migrating set the Article type = News Feature

Title -> Title
Subhead -> when migrating prepend to body with "intro light class"
ByLine -> Organization
Contacts -> ignore this since their contacts are a mess and they wanted to start fresh
Teaser -> Article Summary
Body -> Body
Display expired links -> Preserve Links
Primary Media -> Featured Image - When migrating, if there is a primary media item that is a video, we should append to body. Default to hide featured image when migrating
Primary Media Caption -> Caption? #3561 
*Photo Gallery -> Gallery
News From - migrate as tags
News About - migrate as tags
News For - migrate as tags
Keywords - migrate as tags
Related Items -> Related Content
Embargo Message -> Embargo Information

# Questions
By Line - map to organization and we can get feedback once it is in dev.
Contacts - ignore
Specials - Ignore this as there dosen't appear to be any existing published articles that reference a Special

Do we need to do anything special to migrate photo galleries since they are a reference to a separate piece of content

# Proposed Solution

- [x] Get clarification on questions
- [x] Setup migrations
- [x] Run in Dev
- [x] get customer feedback
- [x] Run in prod

# Running in production
Enable `now_migrate` in prod
Log in, visit /admin/config/sitenow/sitenow-migrate and complete the form following the help text, using data from ac
`ddev drush @now.prod ms` to check the migration status and that everything's set up
`ddev drush @now.prod mim MIGRATION_ID --limit=XXX` to run each migration. Outside of `now_news_feature`, most migrations should be able to run without a limit. Recommend limiting `now_news_feature` after the first 1000 or so, likely limiting to around 200-300 per run.
Babysit it, watch for errors. Some are expected, particularly ones related to things like 'orientation' exif metadata or `problem at 0x64` and such--these are related to image data and either don't cause an issue or are auto-fixed by the system
Run the `MIGRATION_ID_redirects` migrations.
Spot check
Communicate to the partners.

**Comment by joewhitsitt** [comment]
Ideally, https://github.com/uiowa/uiowa/pull/5882 should merge to main first. I will put it up for technical review.

**Comment by cory-skeers** [comment]
This has been run in dev and comms sent out--awaiting feedback and/or green light to run in prod.

**Comment by bspeare** [comment]
After looking at the migrations in dev, can we change the way we are treating the embedded videos?  Ideally, we would align the videos to the left or right in the content.   @cory-skeers demoed that this alignment often clashes with other media and mentioned that we could possibly add logic to check if there was other media in the body, and align if not or center.  

I think there are enough embedded videos on this site that it would make sense to try and make these pages look a bit better.

**Comment by cory-skeers** [comment]
Migration has been completed in prod along with the redirects, and communications sent out to our partners.
