### ISSUE TITLE
Pager is showing on Community College taxonomy pages

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#5894]
# Problem
We previously set this up so that no pager would show, but that doesn't seem to be the case anymore:

https://admissions.uiowa.edu/academics/2plus2/des-moines-area-community-college

# Proposed solution
- [ ] Take a look at recent config changes around this taxonomy, tvi and taxonomy_term view.

**Comment by cory-skeers** [comment]
I dug a little at this, though not fully clear on when a change could have happened or how.

The pager itself is coming from:
https://admissions.uiowa.ddev.site/admin/structure/views/view/taxonomy_term

I'm not seeing any changes to that view in default or the site split that would account for it not being there previously, but appearing now.

**Comment by bspeare** [comment]
I took a brief look at this and it looks like we could fix this with these options:

## TVI Global setting

- Check this box on https://admissions.uiowa.ddev.site/admin/config/user-interface/tvi
<img width="1625" alt="Screen Shot 2022-11-07 at 2 22 39 PM" src="https://user-images.githubusercontent.com/1036433/200407667-0a9f8f77-57c9-4bda-9cbe-d80459c8bf2d.png">

- And then set a view for each taxonomy vocabulary that we want to display like https://admissions.uiowa.ddev.site/admin/structure/taxonomy/manage/tags?destination=/admin/structure/taxonomy. 

<img width="784" alt="Screen Shot 2022-11-07 at 2 23 03 PM" src="https://user-images.githubusercontent.com/1036433/200407739-8e54b276-5b5b-421b-bd8e-eb94910d0938.png">

- A few other vocabs are using this override (Academic groups, Colleges)

## Override the taxonomy term view for Community Colleges only

- Duplicate the default taxonomy term view and rename for Community Colleges
- Set the view up to work with the taxonomy term https://admissions.uiowa.ddev.site/admin/structure/taxonomy/manage/community_colleges?destination=/admin/structure/taxonomy

<img width="939" alt="Screen Shot 2022-11-07 at 2 25 20 PM" src="https://user-images.githubusercontent.com/1036433/200408158-0f18035d-0225-40fe-9099-9a85676144ac.png">

- Set the view to `disabled`.  

## Or another option?

**Comment by joewhitsitt** [comment]
Perhaps this just wasn't showing because there wasn't two pages of content yet?

**Comment by bspeare** [comment]
@joewhitsitt I think that's correct.

**Comment by joewhitsitt** [comment]
So given that this appears to be a bloated TVI issue, I think the proposed solution makes sense, but that we check grad.admissions too since it is the other site that uses TVI.

**Comment by joewhitsitt** [comment]
Devel Generate could be used to create enough entities to cause the paging on other vocabularies to trigger.

**Comment by joewhitsitt** [comment]
The current proposed solution creates more config than ideal. Going to try another approach real quick.

**Comment by joewhitsitt** [comment]
This was more unique than I originally thought. Community Colleges is not using TVI in the same way that other vocabularies are. Because community colleges is using an extra field instead of a replacement view, the TVI configuration is not filled out. We have custom code to unset the view results but not until after the pager is created. Added a one line change to also unset the pager.

So with that said, I don't think we need to check other vocabularies on sites where the TVI module is enabled

**Comment by joewhitsitt** [comment]
Going to take a moment to see if there is a better point in the view process to do this besides prerender.

**Comment by joewhitsitt** [comment]
Found a way in pre_view to prevent further execution of the view.
