### ISSUE TITLE
Ability to reference a building when creating a room

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5895]
# Story

As a Classrooms content editor, when creating a room I would like to be able to choose a building from a predefined list of buildings that contain university classrooms or specialty spaces so that we can relate each room to a single building.

# Proposed solution
- Config entity definition and scaffolding
- Write service to call API and return building results
- Write a (drush?) command to run the service and build the config entity files

# Additional Information

- Reference a single building
- building code will be used with room number for MAUI identifier
- Building name will be used as part of room display title and as a link to the building from the room entity and sps search page
- Used as a filter on search pages

MAUI endpoint
- https://api.maui.uiowa.edu/maui/api/pub/registrar/courses/AstraBldgRmCompleteList/list

Facilities endpoints
- https://bizhub.facilities.uiowa.edu/bizhub/ext/buildings
- https://bizhub.facilities.uiowa.edu/bizhub/ext/building?bldgnumber=0037

Code references
- https://git.uiowa.edu/its-web/data.its.uiowa.edu/-/blob/main/app/Http/Controllers/ClassroomsController.php#L16-35
- /docroot/sites/registrar.uiowa.edu/modules/custom/registrar_feeds/registrar_feeds.module.

# Future Slice?
    
- Additionally, they would like to have a building page that displays some basic building info (Building name, image, address, building hours, accessibility info, link to Facilities building page). Accessibility info and building hours are not yet in any APIs so that may have to wait or just not be included for launch.
    - - >There has been discussion with Jan Bringman with Public Safety Key and Access Services on pulling the building hours from the access control system.  The goal was to integrate the main building entry door daily schedule into the SIMS building inventory and push it to DWPROD.  We should loop Jan into this discussion to see where this process is at a point where the data can be fully integrated into the new site. Having the Building Hours fully integrated is very important, not only for Classroom Scheduling but other UI users. 
    - This page would also display classrooms in this building and some additional call to actions. 
    - https://classrooms.prod.drupal.uiowa.edu/art-building-west
    - Should pull building information from Facilities Management so that it is only managed in one place and kept up to date and link off to Facilities for additional building information.

# Questions
Are these the correct categories of rooms that we will need to get buildings from?
```$category = array_intersect(array(
                    "1) University Classrooms - Level 1",
                    "1) University Classrooms - Original",
                    "1) University Classrooms",
                    "1) University Classrooms - Study Space",
                  ), $room['regionList']);
```

```$category = array_intersect(array(
        2959 => "1) University Classrooms - Level 1",
        2960 => "1) Programmed Classrooms - Level 2",
        2958 => "1) University Classrooms - Original",
        3011 => "1) Specialty Spaces",
        3426 => "1) University Classrooms",
        3506 => "1) University Classrooms - Study Space",
      ), $room['regionList']);
```

**Comment by briand44** [comment]
Adding blocked label until I hear back from Classrooms folks

**Comment by briand44** [comment]
Scope to reference list. Ask Classrooms about using MAUI Building name vs Facilities Building Name to determine if we need to interact with one or two APIs as part of this.

**Comment by joewhitsitt** [comment]
My suggestion is to provide a building select list field (allowed options) based on looping through the the api feed (https://api.maui.uiowa.edu/maui/api/pub/registrar/courses/AstraBldgRmCompleteList/list) and pulling out unique building codes.

Editorial restraint will keep buildings they don't want from appearing on the website by not making room content with those building codes selected.

Assuming a dynamic building page (no content lives on Drupal), routing and a controller similar to uiowa_profiles will query existing room content on the website looking for building codes to determine which buildings should resolve to visitors.

**Comment by briand44** [comment]
Thanks Joe! How would we handle filtering by building on https://classrooms.prod.drupal.uiowa.edu/find-university-classroom and https://sandbox.prod.drupal.uiowa.edu/university-classrooms-ucr-and-specialty-spaces-sps-0? Would those filters have the extra buildings listed?

**Comment by joewhitsitt** [comment]
>Would those filters have the extra buildings listed?

Ugh. Probably if we use views and don't do some kind of "views selective filters" magic on them.

**Comment by briand44** [comment]
There is another MAUI endpoint that has building/room information https://api.maui.uiowa.edu/maui/api/pub/facilityBuildingRoom/list. This doesn't solve the discrepancy between building name and Facilities Common Name but it does have the ResponsibleAcademicUnit which Classrooms wanted us to ignore Buildings that only have a room without a responsible unit.

**Comment by joewhitsitt** [comment]
A pitch for a config entity was made so that we aren't continually querying an external source for information that shouldn't change _too_ often.

As a configuration entity it allows us to potentially house building hours information temporarily if needed.

Perhaps a "Building" configuration entity base in default that could be used differently on a site-by-site basis.

**Comment by briand44** [comment]
config entity definition, write service to do API call, embed in command that generates these for output

**Comment by pyrello** [comment]
Tasks:
- Config entity definition and scaffolding
- Write service to call API and return building results
- Write a (drush?) command to run the service and build the config entity files

**Comment by briand44** [comment]
Brian to verify if we should use

```
"1) University Classrooms - Level 1",
                    "1) University Classrooms - Original",
                    "1) University Classrooms",
                    "1) University Classrooms - Study Space",
                  ), $room['regionList']);
```

**Comment by bspeare** [comment]
Did we want to use https://github.com/uiowa/uiowa/pull/5718 for this work or is that something completely different?

**Comment by joewhitsitt** [comment]
It would be nice to add this to #5718 or at least continue to extend the MAUI API code. There are some things in that PR that probably won't be in the final deliverable. If I understand correctly though, this will be a different endpoint https://api.maui.uiowa.edu/maui/api/pub/registrar/courses/AstraBldgRmCompleteList/list, and we may need to establish a FacilitiesAPI (separate module?) call as well?

**Comment by joewhitsitt** [comment]
@briand44 since we hope to use the uiowa_maui module for the data call, do you think the filtering here https://github.com/uiowa/uiowa/issues/5895#issuecomment-1315771362 would be useful to other websites (aka baked into the module) or should it be limited to the classrooms website (aka classrooms_core filtering after the data call)

**Comment by briand44** [comment]
Sorry, I guess my audio wasn't working in the huddle. I am not aware of that filtering being valuable to other websites at this point. I am not even sure that API endpoint would be used by others.

**Comment by joewhitsitt** [comment]
>I am not even sure that API endpoint would be used by others.

Oye. For maintenance, I think the initial data call should still be located in uiowa_maui instead of trying to build something similar just for classrooms.

**Comment by joewhitsitt** [comment]
With the call and filtering that Ben established, I created the building config entity, added caching around the filtering, added the programatic creation of building entities and moved it to a drush command. I also cleaned up the initial probe fields/functionality that are no longer in-scope.

If we plan on capturing hours info on the config, it would be easier to establish that now than after the module is enabled in PROD.

**Comment by briand44** [comment]
Facilities is supposed to be checking on the status of building hours. My understanding was Classrooms wanted to avoid managing this information if possible and were willing to launch without it if it was something that would be available from Facilities in a reasonable time frame (sounds like they'd be willing to wait at least 3 months after launch if they have to).

**Comment by joewhitsitt** [comment]
Hoping to get thoughts on the approach in https://github.com/uiowa/uiowa/pull/5718 today and to see if there is anything missing.

**Comment by joewhitsitt** [comment]
Oh. One thing that is missing is that it is manually run right now. Not sure if setting up the hook_cron with the drush command and getting the timing/caching right is part of this work for it to run periodically.

**Comment by joewhitsitt** [comment]
Todo

- Update filters to also include:
```
"1) Programmed Classrooms - Level 2",
"Classroom-Programmed",
```
- Store building name (buildingName) from endpoint as part of config entity label
- Daily cron run of command

**Comment by joewhitsitt** [comment]
I mentioned Brand in zoom as having the cron/drush command, but it is actually a PROD scheduled job on uiowa that triggers the drush command. So once this is out in PROD, that would be setup. If once a day, we might want to adjust the six hour cache on the drush command to make sure it expires before the next automated run.

**Comment by bspeare** [comment]
The 36 buildings imported match the building list on https://classrooms.uiowa.edu/admin/structure/taxonomy/buildings.  After updating the filters to include https://github.com/uiowa/uiowa/issues/5895#issuecomment-1329324899, the import is up to 45 buildings created.

**Comment by bspeare** [comment]
@joewhitsitt is there anything left to do here?

**Comment by joewhitsitt** [comment]
I am biased, but nobody objected to the approach, the proposed solution has been covered and the remaining todos have been addressed.

**Comment by joewhitsitt** [comment]
Oops on the issue reference ^^

**Comment by pyrello** [comment]
If we are going to update this building list as a drush command that runs every so often, I think that calls into question the wisdom of using config entities. When we originally discussed using config entities, the idea was that a developer would periodically run the command to update the config and those changes would be committed and deployed. Having a process that runs without developer intervention and updates a set of entities means that they will have to be entirely ignored by config management. If we are going to completely ignore them via config management, I'm not sure what the benefit of using config is.

**Comment by bspeare** [comment]
After our discussion this morning, does this sound like our current plan?

Remaining work:
- Remove config_split.patch.config_ignore.settings.yml

Future work:
- Add the ability to update existing buildings instead of delete and recreate
