### ISSUE TITLE
bme.engineering.uiowa.edu move to engineering.uiowa.edu/bme

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5912]
# Story

As an owner of bme.engineering.uiowa.edu, I would like to move this site to engineering.uiowa.edu and have all traffic going to bme.engineering.uiowa.edu be redirected to engineering.uiowa.edu/bme so visitors can find relevant information they are looking for.

# Additional Info
Currently planning to launch Nov 9th.

# Proposed solution

- [x] Request redirect be put in place on Vulture to redirect bme.engineering.uiowa.edu to engineering.uiowa.edu/bme - this should be tested once in place by updating local hosts file.
- [x] Request TTL be lowered to 5 min for bme.engineering.uiowa.edu
---Launch Day---
- [x] Setup engineeringbme.prod.drupal.uiowa.edu on 703 so that the site can be available to our partners at Engineering temporarily in case any content was missed.
- [x] Update DNS to point to vulture at least 24 hrs after TTL has been lowered and Engineering is ready for switch
- [x] Update robots.txt to disallow all on engineeringbme.prod.drupal.uiowa.edu.
- [x] Add reminder to its-web to check in with Engineering (Hailey, Jason) in one month to see if D7 site can be removed.
---Post Launch Day---
- [x] Request TTL be set back to default once all is well.

**Comment by briand44** [comment]
Requested the redirect be added.

**Comment by briand44** [comment]
Blocked until launch day

**Comment by briand44** [comment]
Redirect has been created and I updated my hosts file and tested. Seems to work for me.

**Comment by joewhitsitt** [comment]
Fun fact, there is a v3 bme site living on uiowa.prod

**Comment by joewhitsitt** [comment]
Set reminder about uiowa703 AND uiowa in case we can't move forward right away in removing the uiowa v3 instance.
