### ISSUE TITLE
BUG: Provision errors after move to PHP 8?

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#5913]
Provisioning productionunit.uiowa.edu on uiowa04 as a test for the new application.

After running ./vendor/bin/blt umc productionunit.uiowa.edu I did receive these notifications/warnings:
```
% ./vendor/bin/blt umc productionunit.uiowa.edu
 [Acquia\Blt\Robo\Tasks\GitTask] Running git commands...
 [Acquia\Blt\Robo\Tasks\GitTask] git rev-parse --abbrev-ref HEAD
Note: Multisites should be grouped on applications by domain since SSL certificates are limited to ~100 SANs. Otherwise, the application with the least amount of databases should be used.
PHP Deprecated:  http_build_query(): Passing null to parameter #2 ($numeric_prefix) of type string is deprecated in /Users/mbennett/Sites/uiowa/vendor/league/oauth2-client/src/Tool/QueryBuilderTrait.php on line 31

Deprecated: http_build_query(): Passing null to parameter #2 ($numeric_prefix) of type string is deprecated in /Users/mbennett/Sites/uiowa/vendor/league/oauth2-client/src/Tool/QueryBuilderTrait.php on line 31
PHP Deprecated:  Return type of League\OAuth2\Client\Token\AccessTokenInterface::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/mbennett/Sites/uiowa/vendor/league/oauth2-client/src/Token/AccessTokenInterface.php on line 71

Deprecated: Return type of League\OAuth2\Client\Token\AccessTokenInterface::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/mbennett/Sites/uiowa/vendor/league/oauth2-client/src/Token/AccessTokenInterface.php on line 71
```

AFTER selecting uiowa04, and continuing, I received these warrnings:

```
PHP Deprecated:  http_build_query(): Passing null to parameter #2 ($numeric_prefix) of type string is deprecated in /Users/mbennett/Sites/uiowa/vendor/league/oauth2-client/src/Tool/QueryBuilderTrait.php on line 31

Deprecated: http_build_query(): Passing null to parameter #2 ($numeric_prefix) of type string is deprecated in /Users/mbennett/Sites/uiowa/vendor/league/oauth2-client/src/Tool/QueryBuilderTrait.php on line **31**
```

Rest of provisioning process seemed to work correctly without warnings/errors.

**Comment by mark-bennett-uiowa** [comment]
Renamed this issue in order to better scope this for later fixes.

**Comment by joewhitsitt** [comment]
I think the jsonseralize() issues are captured in https://github.com/uiowa/uiowa/issues/5738

**Comment by mark-bennett-uiowa** [comment]
UPDATE: I also noticed that after running this, there is a /config/productionunti.uiowa.edu directory, outside of /config/sites. Is this normal?

**Comment by joewhitsitt** [comment]
I think we have noticed that as well. Not uiowa04 specific for sure. It is not part of the provision git commit. I think you can safely delete the directory.

Should probably figure it out though.

I am going to re-open this because of http_build_query and that config directory

**Comment by joewhitsitt** [comment]
Moved the http_build_query issue to #5738 as it also appears to be related.

Created a separate issue for the site configuration directory issue: https://github.com/uiowa/uiowa/issues/5918

**Comment by mark-bennett-uiowa** [comment]
> I think we have noticed that as well. Not uiowa04 specific for sure. It is not part of the provision git commit. I think you can safely delete the directory.

@joewhitsitt if I delete that directory in /config, will it need to be pushed as changes, or is this just a local ENV thing?

**Comment by joewhitsitt** [comment]
it isn't currently tracked in git so it would not show as a change that needs committing
