### ISSUE TITLE
Update acquia_connector module

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#5920]
# Issue

On Friday, 31 March 2023, 3.x versions of the Acquia Connector Module will no longer be compatible with the Acquia Cloud Platform. 

# Proposed Solution

- [x] Update v2/v3 with the latest 4.x version
- [x] Update v1 with the latest 4.x version

- ~701~
- ~702~
- ~703~
- ~signage~
- ~HC signage~
- ~Dentistry~
- ~icgov~
- ~clas~
- grad

**Comment by joewhitsitt** [comment]
An example where the deadline property of the new Github projects would be helpful in re-surfacing.

**Comment by joewhitsitt** [comment]
@pyrello addressed v2/v3 with https://github.com/uiowa/uiowa/pull/6146

**Comment by briand44** [comment]
Since the CLAS application has subdirectory sites (symlinks) we cannot run `drush @sites`. Ben provided me with an old alias file and I went through and cleaned everything up and committed it to the repo so now we should be able to run `drush @clas1.[env]` locally to execute commands on all the sites in each environment on the server. We will want to keep these up to date as we deprovision sites.

**Comment by briand44** [comment]
The following sites had errors in production when running `updb`:

- som-director - temporarily unavailable
- report - temporarily unavailable
- psychologyradleylab - redirect
- physicsfaraday - too long to respond
- phdw - redirect
- international-relations - redirects to a page not found
- dean-search - temporarily unavailable
- classustainability - this site can't be reached
- claspolicy - siteNow v3
- api - temporarily unavailable

The errors are similar to the following:
```
Error: require(): Failed opening required '/var/www/site-php/uiclas/drupal_somdirector-settings.inc'
(include_path='.:/usr/local/php7.4/lib/php') in /mnt/www/html/uiclas/docroot/sites/clas.uiowa.edu.som-director/settings.php, line
629
```

I will create a follow up issue to audit and address the sites mentioned above.

some sites had existing db updates that hadn't been ran:

```
physics.prod                        >>  System        7085  Remove FLoC-blocking variable.
physics.prod                        >>  Acquia_agent  7002  Uninstall Acquia SPI module.
physics.prod                        >>  Acquia_agent  7003  Update the API address.
physics.prod                        >>  Acquia_agent  7004  Remove NSPI Variables, update subscription data.
physics.prod                        >>  Link          7100  Rebuild the menu cache to make the settings page use the correct permission.
physics.prod                        >>  Redirect      7103  Change fields 'redirect_options', 'source_options' to blob type.
physics.prod                        >>  Redirect      7104  Add an index on the redirect column in the redirect table.
```


```
iowamommoodbooster.prod             >>  System       7085  Remove FLoC-blocking variable.
iowamommoodbooster.prod             >>  File_entity  7227  Remove deprecated views_plugin_access_menu plugin.
iowamommoodbooster.prod             >>  Panels       7309  Add primary key to panels_allowed_types table.
iowamommoodbooster.prod             >>  Wysiwyg      7206  Delete YUI profiles.
```


```
cs.prod                             >>  System        7085  Remove FLoC-blocking variable.
cs.prod                             >>  Acquia_agent  7002  Uninstall Acquia SPI module.
cs.prod                             >>  Acquia_agent  7003  Update the API address.
cs.prod                             >>  Acquia_agent  7004  Remove NSPI Variables, update subscription data.
cs.prod                             >>  Link          7100  Rebuild the menu cache to make the settings page use the correct permission.
cs.prod                             >>  Redirect      7103  Change fields 'redirect_options', 'source_options' to blob type.
cs.prod                             >>  Redirect      7104  Add an index on the redirect column in the redirect table.
```


```
comsci.prod                         >>  System    7085  Remove FLoC-blocking variable.
comsci.prod                         >>  Panels    7309  Add primary key to panels_allowed_types table.
comsci.prod                         >>  Redirect  7103  Change fields 'redirect_options', 'source_options' to blob type.
comsci.prod                         >>  Redirect  7104  Add an index on the redirect column in the redirect table.
```

**Comment by pyrello** [comment]
`cs` and `physics` have SiteNow V3 sites now, so maybe we don't need to update them?

**Comment by briand44** [comment]
Those updates were ran when running the acquia connector updates so they are up to date now, I was just making it visible in case there were any issues post updates.

**Comment by pyrello** [comment]
Grad is done.
