### ISSUE TITLE
ISWF View Listing

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#5931]
# Issue

Create searchable view listing for events by date, genre, and presenter.

# Proposed Solution

- [x] Try to use existing view display otherwise create a ISWF specific view, adding it to the site split.
  - Just filtered events that are not referenced as a parent. So, if there are multiple types this applies to, the view might need to look at certain relationships ("lowest layer")
- [x] As a visitor, I want to pick a date or date range (depending on what we discover while building) that I am available and see events that meet that criteria (on that date or in-progress).
- [x] As a visitor, I want to filter by genre
- [x] Filtered dropdown or autocomplete of person published (not hide on lists) that have been referenced by an event. This would require an entity reference view display to filter so that not all person content on the website is available for selection.
- [x] Ensure consistency of different event listing displays. Excludes event list block because that has an explicit option to change how it looks so that is handled differently.
- [x] If the "Performer" person type is not necessary to create the above views, remove it from the ISWF site split.
- [x] Based on today's conversation (12/05/2022), add an image field for visual conformity. To do this, you’ll want to use the default site and then turn on the event feature.
- [x] Look into genre dropdown opening when "Apply" is clicked.
- [x] Date filter should show events that have date ranges including the date selected.

**Comment by briand44** [comment]
Ensure consistency of different event listing displays. Excludes event list block because that has an explicit option to change how it looks so that is handled differently.

**Comment by joewhitsitt** [comment]
Should this be blocked until https://github.com/uiowa/uiowa/pull/5925 merges in? I think we assumed it would be done before this was pulled in.

**Comment by joewhitsitt** [comment]
From standup, it sounds like this work can be added to #5925 and is not blocked

**Comment by pyrello** [comment]
I made [some updates](https://github.com/uiowa/uiowa/pull/5925/commits/6c30f6f28e595ac4bead9d7def27ae0cc6a35999) and updated the checked boxes in the IS to reflect my changes.

**Comment by pyrello** [comment]
Did we decide that we did not want the base event feature to include the ability to search by date or presenter?

**Comment by pyrello** [comment]
Looks like we are going to need Better Exposed Filters to get a datepicker for the when field: https://www.drupal.org/docs/contributed-modules/smart-date/smart-date-and-views-including-fullcalendar-view#s-adding-a-date-picker-exposed-filter

**Comment by pyrello** [comment]
I was able to accomplish limiting the people that can be searched for to just people attached to events, so I don't believe that we need the Presenter person type.

**Comment by makurj** [comment]
Based on grooming discussion, we can remove "all genres" as an option.

**Comment by makurj** [comment]
Questions for team:

1. For the ISWF split, we have additional fields that are being output in `node--event--teaser.html.twig`, genre, registration link, etc. See screenshot below.

![image](https://user-images.githubusercontent.com/52135878/204850805-ce436d91-95c1-4691-ae5c-58d50948e8d7.png)

How do we want to handle the display of these? A new template or preprocessing? We feel like the registration link should render the text "Register for this event" keeping in line with the event display.

2. Also, adding in this template is the person icon. Should that be in line with the text? What's our strategy for handling these?

**Comment by GaryRidgway** [comment]
In looking at the view, I feel like `/events` may not be the best place for this? Currently, there is an omission of events that do not have the `Part of` field filled out. I find it a little odd to not display events on the `/events` page, which, to me, seems like a page that should display ALL events.

**Comment by makurj** [comment]
I would agree. `/events` should list ALL events. The view we worked on was set to `/events/upcoming` so we could have a different path for "I don't have a parent" events.

**Comment by pyrello** [comment]
> In looking at the view, I feel like `/events` may not be the best place for this? Currently, there is an omission of events that do not have the `Part of` field filled out. I find it a little odd to not display events on the `/events` page, which, to me, seems like a page that should display ALL events.

> I would agree. `/events` should list ALL events. The view we worked on was set to `/events/upcoming` so we could have a different path for "I don't have a parent" events.

The events that should not be showing up on `/events` are events that are referenced as a parent. This is to prevent a listing like:
- Event not related to the Writing Festival
- Writing Festival
- Session that is part of the Writing Festival
- Workshop that is part of the Session that is part of the Writing Festival

Instead we would just end up with:
- Event not related to the Writing Festival
- Workshop that is part of the Session that is part of the Writing Festival

This was a deliberate choice and was discussed during grooming on this issue. 

If you are seeing something other than the above described behavior, then its not working correctly.

**Comment by pyrello** [comment]
<img width="1326" alt="Screen Shot 2022-12-08 at 10 14 33 AM" src="https://user-images.githubusercontent.com/709009/206501165-b658d2df-2a85-4082-b66b-5f19b86ff66d.png">

Is this supposed to be showing a placeholder image? Or should the event align to left when there is no image?

*Side note: I have not added a child event to that parent event, which is why its showing up there.*

**Comment by mark-bennett-uiowa** [comment]
I also pulled this down for testing, and saw the same issue as Sean mentioned above.

- Search fields seemed to work correctly no matter what I did to confuse it.
- Checked results based on events with no children vs children.

Also, are we removing the border from this list but leaving it for the subevent lists?
<img width="873" alt="Screen Shot 2022-12-08 at 11 48 45 AM" src="https://user-images.githubusercontent.com/3067017/206526808-07125f6f-bf63-4c1b-a86b-ca84b566f021.png">
<img width="692" alt="Screen Shot 2022-12-08 at 11 48 57 AM" src="https://user-images.githubusercontent.com/3067017/206526829-6373b09c-1d01-4522-b95f-38c446adb476.png">

**Comment by pyrello** [comment]
> Also, are we removing the border from this list but leaving it for the subevent lists?

My understanding is that subevents will continue to have the border, but we are not adding it to other lists, to be consistent with how we don't generally containerize lists like this.

**Comment by mark-bennett-uiowa** [comment]
> > Also, are we removing the border from this list but leaving it for the subevent lists?
> 
> My understanding is that subevents will continue to have the border, but we are not adding it to other lists, to be consistent with how we don't generally containerize lists like this.

Sounds good, can we at least have the borders on the next piece of events listed for individual presenters?

**Comment by pyrello** [comment]
> > > Also, are we removing the border from this list but leaving it for the subevent lists?
> > 
> > 
> > My understanding is that subevents will continue to have the border, but we are not adding it to other lists, to be consistent with how we don't generally containerize lists like this.
> 
> Sounds good, can we at least have the borders on the next piece of events listed for individual presenters?

I'd note that is the direction you'd like to go on that issue and if we need to discuss it, we can do it over there.
