### ISSUE TITLE
Probe - Display submitted timestamp on webform results for each submission

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#5938]
Investigate:
As an administrator of the diversity website, I can see form submission times (in addition to dates) on the submissions table.  

Note: it appears that currently you have to download an excel file of sensitive information to see submission times.

Note: perhaps useful for all sites? 

Note: Submission results are controlled by views, but it's a bit more complicated for webforms. Need to investigate the complexity and path forward. Might involve creating a new view and assigning it to default webform results config, a display preprocess to change date formatting, or something else.

**Comment by bspeare** [comment]
It looks like we could do something like https://github.com/uiowa/uiowa/pull/5943 where that adjustment will display https://github.com/uiowa/uiowa/blob/main/config/default/views.view.webform_submissions.yml with a long date format that shows the time.    Reference: https://www.drupal.org/node/2994274.

**Comment by bspeare** [comment]
If we do something like https://github.com/uiowa/uiowa/issues/5938#issuecomment-1312205958, then we would possibly need to adjust the view to be more like the default webform submission list:

<img width="1538" alt="Screen Shot 2022-11-15 at 1 16 16 PM" src="https://user-images.githubusercontent.com/1036433/202006551-5f2efb13-fcbc-4f05-86fe-5d7816f5d63e.png">

Here's the view with the submission date that would need to be updated:

<img width="1530" alt="Screen Shot 2022-11-15 at 1 17 18 PM" src="https://user-images.githubusercontent.com/1036433/202006632-f8031823-6a01-417b-97b9-68ecf756f201.png">

If that seems like too much work, then I would recommend that we just alter the default submission list through a process similar to https://blog.dcycle.com/blog/2022-02-07/alter-list-view/.  The code we are trying to alter is here: https://git.drupalcode.org/project/webform/-/blob/6.1.x/src/WebformSubmissionListBuilder.php#L865.

**Comment by joewhitsitt** [comment]
So if I understand this correctly, using views is an option but we would have to make changes to mirror the existing submissions display?

If we want the quick change, the alter sounds fine, but if we can do this in config (views), I think that will be the better long term solution given how often webform is updated.

**Comment by bspeare** [comment]
@joewhitsitt Yes, for the views route we would need to decide if want to make the changes to mirror the existing display.

**Comment by joewhitsitt** [comment]
One thing I just thought of is how much SiteNow has customized the site request submissions using the built-in functionality.  Maybe the alter is the better path. Any regression would probably be fixable.
