### ISSUE TITLE
As a site editor, I can designate the EventStatus of a local event as Active, Cancelled, or Rescheduled.

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#5939]
# Story

As a site editor, I can designate the EventStatus of a local event as Active, Cancelled, or Rescheduled to inform viewers of the status of an event.

[https://schema.org/eventStatus](https://schema.org/eventStatus) - This is the schema.org property defined for the status of the event.

<img width="1486" alt="Screen Shot 2022-11-10 at 11 27 31 PM" src="https://user-images.githubusercontent.com/3067017/201270004-85c508fd-5282-4c09-8c66-202dba55bc80.png">

# Proposed solution

- Add a new field_event_status field to the local event type at the default level.
- Attach field value to schema.org property "eventStatus".
- ~Does this need to carry over to all "child" or "subEvents" within the updated event???~ - No
- Output badge for rescheduled and cancelled using a single color badge on teasers and entity

**Comment by briand44** [comment]
Grooming conversation... Let's not do anything for past dates on rescheduled events. Not carrying this status to child or subEvents.
