### ISSUE TITLE
As a site editor, I can designate the AttendanceMode of a local event as Online, Onsite, or Mixed/Blended.

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#5940]
# Story

As a site editor, I can designate the AttendanceMode of a local event as Online, Onsite, or Mixed/Blended to inform viewers of the attendance mode for the event.

[https://schema.org/eventAttendanceMode](https://schema.org/eventAttendanceMode) - This is not approved yet by schema.org but is available as a property in schema assignment and would be helpful to prepare for an anticipated approval. Useful for ISWF's mixed festivals (one Onsite, one Online).

<img width="1484" alt="Screen Shot 2022-11-10 at 11 27 25 PM" src="https://user-images.githubusercontent.com/3067017/201269902-aa737ebd-5760-4423-9550-788fac5a2db6.png">

# Proposed solution

- Add a new field_event_attendance_mode field to the local event type at the default level as required.
- Attach field value to schema.org property "eventAttendanceMode".
- ~Does this need to carry over to all "child" or "subEvents" within the updated event???~ - this is out of scope for this issue
- Update hook to set this field for existing events.

**Comment by briand44** [comment]
OnIowa is also asking for the ability to designate an event as virtual, in person, or hybrid. They also want the ability to filter by these options on their display. The filtering can be a separate issue.

**Comment by briand44** [comment]
Planning conversation... Check how classes refer to these different options but currently leaning towards virtual, in person and hybrid for display names, Machine names can match schema. Lets not worry about display of this information as part of this slice. We probably need an update hook here for existing events. Check if there is an address or virtual designation to determine how this field should be set. If neither are set default to in person.
