### ISSUE TITLE
Investigate top_links_limit logic to see why law.uiowa.edu has unlimited top links

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#5945]
# Problem
law.uiowa.edu has a **Unlimited** top links when the limit is 2. 

<img width="417" alt="Screen Shot 2022-11-14 at 11 26 20 AM" src="https://user-images.githubusercontent.com/1036433/201728460-4b8b549d-992f-4426-b5cd-d7f59a643107.png">

# Steps to reproduce
law.uiowa.edu

# Proposed solution
Investigate theme setting logic https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/theme-settings.php#L103 and why law.uiowa.edu is bypassing it.

**Comment by joewhitsitt** [comment]
Probably a communication element as well if we are cutting their links down.

**Comment by joewhitsitt** [comment]
On immediate glance, law's top_links_limit is null...

Running a report on uiowa -> uiowa04, there is more than a few sites that have null instead of the default 2.

**Comment by joewhitsitt** [comment]
These are the sites with null for top links limit. If anyone sees a pattern here, let me know. This is across uiowa, uiowa01, uiowa02.

latinxstudies.uiowa.edu
latinamericanstudies.uiowa.edu
internationalstudies.uiowa.edu
interdisciplinaryprograms.uiowa.edu
interdepartmentalstudies.uiowa.edu
globalhealthstudies.uiowa.edu
geriatricpain.org
csi.its.uiowa.edu
bmess.org.uiowa.edu
biomonitoring.shl.uiowa.edu
shpe.org.uiowa.edu
obgynnewsletter.sites.uiowa.edu
kliemann.lab.uiowa.edu
italymba.tippie.uiowa.edu
dietrich.lab.uiowa.edu
cerebrovascular.lab.uiowa.edu
avclub.org.uiowa.edu
appliedphys.lab.uiowa.edu
staff-council.uiowa.edu
law.uiowa.edu
kroska.lab.uiowa.edu
itaccessibility.uiowa.edu
ighn.international.uiowa.edu
cognitivecontrol.psychology.uiowa.edu

**Comment by joewhitsitt** [comment]
actually, i think these are uiowa_bootstrap sites that transitioned to uids_base but haven't re-saved uids_base theme settings

**Comment by joewhitsitt** [comment]
restricting top links was a uids_base thing https://github.com/uiowa/uiowa/pull/1846 before uids_base was turned on for all https://github.com/uiowa/uiowa/pull/1806

**Comment by joewhitsitt** [comment]
I re-saved (aka set limit to 2) all but appliedphys.lab.uiowa.edu and law.uiowa.edu as they had more than two links displaying. I will write an email to site owners before those settings are saved so that they can adjust their navigation.

**Comment by joewhitsitt** [comment]
Added a card to PL to discuss the communication.

**Comment by joewhitsitt** [comment]
Comms went out yesterday. Deadline is 12/6. I will add an its-web calendar reminder.

**Comment by joewhitsitt** [comment]
I just realized that I won't be here 12/6.

So, assuming there is no emails telling us to wait/adjust the deadline...

- For law.uiowa.edu and appliedphys.lab.uiowa.edu go into Appearance > uids_base theme settings and save the settings as-is. This will set the 2 link limit config value.

**Comment by joewhitsitt** [comment]
We explained the situation to Hannah H. (law.uiowa.edu) yesterday in a meeting. Hannah is temporarily taking over website responsibilities for Laura K.. For now, we are keeping to the same deadline.

**Comment by briand44** [comment]
I removed two of the top links for Law on behalf of Hannah and saved theme settings.

**Comment by briand44** [comment]
I updated the other site to use the parent organization functionality, removed the link from top links and saved theme settings.

**Comment by briand44** [comment]
Also deleted the calendar reminder.
