### ISSUE TITLE
Blocks in grid layouts overflow layout columns at smaller column widths

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#5946]
# Problem
As you can see with the four-column grid on https://csd.uiowa.edu/research, at smaller breakpoints the grid is no longer equal-width. 

<img width="1034" alt="Screen Shot 2022-11-14 at 1 59 03 PM" src="https://user-images.githubusercontent.com/1036433/201754080-5c7f919b-9195-4875-828f-50712ebb32f4.png">

# Proposed solution
Items within grid layouts need a min-width to maintain the grid: https://css-tricks.com/preventing-a-grid-blowout/. 

- Add `min-width: 0` to https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/scss/global.scss#L54. 

Once that is set, the grid widths are maintained but the cards will still overflow.  See details for more information:

<details>

<img width="1025" alt="Screen Shot 2022-11-14 at 2 01 49 PM" src="https://user-images.githubusercontent.com/1036433/201754640-5e040f36-5c82-4f4e-9ed8-a7b136a43b02.png">

This line is causing the overflow: https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/scss/global.scss#L16.   Removing this line will cause words to break:

<img width="1027" alt="Screen Shot 2022-11-14 at 2 04 37 PM" src="https://user-images.githubusercontent.com/1036433/201754964-52c20426-3015-49ec-a69b-d389bc6375f8.png">

Some options to fix that:
- Investigate implementing https://developer.mozilla.org/en-US/docs/Web/CSS/hyphens
- We could adjust this to use CSS clamp and container queries to adjust the sizing of these headings at these smaller widths to maintain 
- Break the grid into three columns earlier to maintain a certain width. 
- 
</details>

# Follow up tasks
- [x] https://github.com/uiowa/uiowa/issues/4678

**Comment by bspeare** [comment]
One downside of the hyphens approach is that the "_The browser is free to automatically break words at appropriate hyphenation points, following whatever rules it chooses_."  As you can see in the example below, it knows how to break the word "Cookies" but not "Audiogenomics".    In order to get a hyphen in "Audiogenomics" you would have to manually insert an invisible soft hyphen like `<span class="headline__heading">Audiogen&shy;­omics cookies having Lab</span>`

<img width="238" alt="Screen Shot 2022-11-15 at 2 46 37 PM" src="https://user-images.githubusercontent.com/1036433/202022341-5c7604fe-7813-4c3f-9187-4c741ea5775d.png">

**Comment by briand44** [comment]
Step 1 - make grids stay even
Step 2 - Separate issue to address overflow issue

**Comment by bspeare** [comment]
I updated the proposed solution and added the followup issue reference to https://github.com/uiowa/uiowa/issues/4678 which I think will help the four column crunch/overflow.
