### ISSUE TITLE
Theme named building pages

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5962]
As a Facilities website owner, I would like the named building pages to look nice and quickly provide information about the Facility and the Honoree to site visitors.

# Additional Info
They are ok with us putting together the layout and getting feedback though they prefer the Facility description and Honoree info (photo, name, etc. near the top).

- https://sandbox.prod.drupal.uiowa.edu/hardin-library-health-sciences-0

There are some named buildings with two honorees (https://www.facilities.uiowa.edu/named-building/blank-honors-center), and can be accounted for similar to https://github.com/uiowa/uiowa/pull/5934#issuecomment-1335806496, but there may be styling considerations there (like pluralizing the Honoree label).

**Comment by briand44** [comment]
Cohesive design where information is grouped and not separated so much.

**Comment by briand44** [comment]
Ben to share some more thoughts or examples.

**Comment by bspeare** [comment]
I put together an example mockup that groups the information together in sections: https://sandbox.prod.drupal.uiowa.edu/hardin-library-health-sciences, https://sandbox.prod.drupal.uiowa.edu/hardin-library-health-sciences-copy

**Comment by joewhitsitt** [comment]
I just made a change to the aerial link field to just capture the link because I think the button text should be consistent. We felt it is ok to have building info lower since the majority of traffic to these pages comes from the building page rather than the named building search.

**Comment by briand44** [comment]
In grooming folks seemed to be leaning towards https://sandbox.prod.drupal.uiowa.edu/hardin-library-health-sciences-copy.

**Comment by briand44** [comment]
Adding blocked label since it sounds like the team would prefer to merge https://github.com/uiowa/uiowa/pull/5934 prior to beginning this work.

**Comment by pyrello** [comment]
Removed the blocked label since #5934 was merged.

**Comment by joewhitsitt** [comment]
Seeing if I can help move this forward.
