### ISSUE TITLE
Allow gclid and fbclid to pass through to Webform fields

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#5964]
# Problem
Webform has pre-populate functionality that fills in matching fields with query string parameter values, but there are at least two ids, `gclid` and `fbclid` that don't get passed when Acquia's varnish is in front of the request.

https://support-acquia.force.com/s/article/360004119294-Acquia-s-default-Varnish-VCL-strips-Google-Analytics-and-Facebook-Ads-query-string-parameters

# Proposed solution
- [ ] Using https://github.com/uiowa/uiowa/pull/5961 as a reference
- [ ] Check all webforms for elements with gclid/fbclid machine names with type hidden and prepopulate checked. Attach JS if it exists.
- [ ] prepopulate info is available when the js is attached, however, we don't want the js blindly applying to each element without further checking (multiple forms). capturing info in drupalSettings or setting an attribute on the element to check against with JS would be neat.

# Additional

Working example as of 11/18: https://tippie.dev.drupal.uiowa.edu/form/gclid-test?gclid=123456789123456789aaaaa

**Comment by joewhitsitt** [comment]
Crud. Thought this would be quick pre-standup work. I think drupalsettings will be needed to deal with the possibility of multiple forms on the same page containing these fields but different behaviors.

**Comment by bspeare** [comment]
Joe will adjust proposed solution after grooming.

**Comment by makurj** [comment]
I would like to pair on this.
