### ISSUE TITLE
February Dependencies

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#5965]
We should try to review and merge in dependency updates on a monthly basis. Until this is automated more, here is a guide:

- Review the [outstanding dependency updates](https://github.com/uiowa/uiowa/pulls?q=is%3Aopen+is%3Apr+label%3Adependencies) and add a list of current ones below.
- Dependencies related to our frontend build tools (not executed on the websites) are usually safe to merge as-is but might cause issue with other packages. Check travis build for messages related to `blt frontend`.
- Each @dependabot PR can be worked on separately. Each dependency PR you merge will cause merge conflicts with all the other ones. As long as you don't alter the branch (e.g. merge in `main`, push a commit), you can fix the merge conflicts by running `@dependabot rebase`.
- If a @dependabot PR does require some type of modification (e.g. removing a patch, updating incompatible code), it is okay to make those changes directly in relevant PR. However, it is a good idea to wait until you have merged all the other "easy" dependency PRs first because you will lose the ability to use `@dependabot rebase` to have the PR's merge conflicts resolved.
- Periodically check [locked dependencies](https://github.com/uiowa/uiowa/blob/main/README.md#locked-packages) for new versions. Make notes about why a dependency was/is locked in the repo Readme.
- Review the changelog for each version we are jumping to and the versions in-between. Make note of certain functionality in our codebase that is using the functionality for testing instructions later.
- It can also be helpful to review the git diff comparison between the old version and the new one to see how extensive the code changes are and to get an idea of what things you might need to test.
- Use https://github.com/uiowa/uiowa#updating-dependencies as a guide to test for update hooks, configuration changes and commit. This command is helpful if there are a lot of configuration changes across feature/site splits: https://github.com/uiowa/uiowa/blob/main/blt/src/Blt/Plugin/Commands/ConfigSplitCommands.php
- Dependency PR's with update hooks or requiring a cache rebuild may require off-hours deployment. If this is the case, add the appropriate label to the PR.
- Once this issue is completed, copy these notes to the next month's issue and introduce it in parking lot.

# Updates in-scope

## NPM
- [x] #6065 
- [x] #6081
- [x] #6136  
- [x] #6140
- [x] #5989 
- [x] #6161
- [x] #6157

## Composer
- [x] #5980 
- [x] #6134 
- [x] #6146  
- [x] #5987
- [x] #6144 
- [x] #6156
- [x] #6155
- [x] #5988 
- [x] #5985
- [x] #5984
- [x] #5982
- [x] https://github.com/uiowa/uiowa/pull/6171

**Comment by briand44** [comment]
drupal_check will likely not be included as part of this. We have a separate issue to address that https://github.com/uiowa/uiowa/issues/5467.

**Comment by pyrello** [comment]
I'm going to work on these in between other things.

**Comment by joewhitsitt** [comment]
I think the following are blocked (photoswipe needs core 9.5 to get rid of a patch, fontawesome needs fontawesome 6 library which we can't upgrade to yet because of fontawesome_iconpicker https://github.com/uiowa/uiowa/pull/5511#issuecomment-1206852059).
- Bump bower-asset/photoswipe from 4.1.3 to 5.3.4 #5983
- Bump drupal/fontawesome from 2.19.0 to 2.24.0 #6154

**Comment by pyrello** [comment]
I updated the IS to remove the items that @joewhitsitt mentioned in https://github.com/uiowa/uiowa/issues/5965#issuecomment-1416139524. The only item left is #6149.

**Comment by joewhitsitt** [comment]
dompdf has been merged. @pyrello do you want the pleasure of closing this?

**Comment by pyrello** [comment]
> dompdf has been merged. @pyrello do you want the pleasure of closing this?

Thanks, @joewhitsitt! And @bspeare!
