### ISSUE TITLE
Show events on person page (presenter)

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5968]
# Story
As a SiteNow events user, I would like events that reference a person (presenter) to be displayed on that person's profile page so that users can easily find more events where that person is presenting.

# Additional Info
[https://iowasummerwritingfestival.org/zach-savich](https://iowasummerwritingfestival.org/zach-savich)

# Proposed Solution

- [x] Establishing a view block that takes a contextual argument for entity id
- [x] Output using sub event display format (title, date, presenter, short description)
- [x] Show both upcoming and past events
- [x] Display in reverse chronological order
- [x] Limit number of items to 10

**Comment by mark-bennett-uiowa** [comment]
I would like to see borders around the events for this slice similar to the borders around the subevents listing. This is driven by the previous display of events for ISWF presenters and I think it looks cleaner.

**Comment by bspeare** [comment]
@mark-bennett-uiowa Instead of borders, what if we just had subtle dividers?  The borders around each box is a bit strong and takes up a lot of space. 

<img width="1142" alt="Screen Shot 2022-12-09 at 9 25 36 AM" src="https://user-images.githubusercontent.com/1036433/206735528-9362aec5-751e-4cf7-a2fa-89c0edd4cc62.png">

**Comment by mark-bennett-uiowa** [comment]
@bspeare Considering we already have the borders for the sub-events, and these lists (at least for ISWF) include < 4-5 events usually, I am personally not too worried about the space. However, I need to consider how this will affect the other sites that will use this. Are we worried about these lists being as long as you show above?

**Comment by bspeare** [comment]
Grooming notes: 

- Put this in the ISWF site split or event feature?

**Comment by briand44** [comment]
>Put this in the ISWF site split or event feature?

I thought we had discussed putting it in the event feature and that is why I created this story "As a SiteNow events user..." but I may have missed some of the conversation around this yesterday.

**Comment by bspeare** [comment]
We discussed where the border was being set in planning, I think it is being set here for the split https://github.com/uiowa/uiowa/blob/main/config/sites/iowasummerwritingfestival.uiowa.edu/core.entity_view_display.node.event.default.yml#L173.

**Comment by pyrello** [comment]
I'm going to take a pass at this.

**Comment by pyrello** [comment]
I'm wondering while working on this if we want to add some filtering similar to what we added to the `/events` view to exclude parent events from what gets listed?

**Comment by joewhitsitt** [comment]
For ISWF, that would make sense to me, but is that the behavior for the default?

**Comment by joewhitsitt** [comment]
If that is the behavior in default, we should probably document the differences between event feature and ISWF because I am quite confused

**Comment by pyrello** [comment]
> For ISWF, that would make sense to me, but is that the behavior for the default?

I'm not sure where the confusion entered into this, but I was under the impression that this was something we were adding this to the event feature. Maybe this was a conversation when I was out during the last grooming?

**Comment by pyrello** [comment]
> > For ISWF, that would make sense to me, but is that the behavior for the default?
> 
> I'm not sure where the confusion entered into this, but I was under the impression that this was something we were adding this to the event feature. Maybe this was a conversation when I was out during the last grooming?

If you are asking whether the behavior to not show parent events in the event list is the behavior in the event feature, then the answer is yes.

**Comment by joewhitsitt** [comment]
it was a long set of PRs that started one way and then went the other way while I was out. i am fine with the shift, just lost visibility into the work.

**Comment by pyrello** [comment]
> it was a long set of PRs that started one way and then went the other way while I was out. i am fine with the shift, just lost visibility into the work.

It was definitely hard to keep track of everything, even without being gone.
