### ISSUE TITLE
Card : Update hook and miscellaneous testing for card stuff that we missed.

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5972]
- [ ] Set update hook to set that `Remove card border` value on cards that did not have `Card: border` selected. 
  - [ ] Review custom `.card` styles in `uiowa` repo and see if they are still needed. 
  - [ ] Update `V2` card templates and scss.
  - [ ] Review `card--list` modifier and see it can be removed and possibly move back some adjustments to UIDS4 like https://github.com/uiowa/uiowa/pull/5925#discussion_r1022048173
  - [ ] This list will be added to as the first and second slice are worked on.

**Comment by pyrello** [comment]
Added these bullet points to #5971
