### ISSUE TITLE
Domain, SSL, DB cleanup after CLAS additions - affects uiowa01, uiowa02, uiowa03

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#5973]
# Followup from #5864 

- [x] Delete art.uiowa.edu database from uiowa01. There is no DNS or SSL coverage of this domain on uiowa01. Not sure why it has a database here.
- [ ] Install the https://shops.clas.uiowa.edu/ site on uiowa01. DB, domain already exist, SSL covers.

Cleanup existing SSL certificates on existing applications (uiowa, uiowa01, etc.)
- [x]  uiowa01: remove *.biology.uiowa.edu from SSL
- [x]  uiowa02: remove psychology.uiowa.edu from SSL
- [x]  uiowa03: remove *.dance.uiowa.edu, *.psychology.uiowa.edu, and latham.uiowa.edu from SSL

**Comment by joewhitsitt** [comment]
>Install the https://shops.clas.uiowa.edu/ site on uiowa01. DB, domain already exist, SSL covers.

Should we reach out to CLAS to see if this is still the plan?

I was going to see if I could pick off a couple of these items today

**Comment by joewhitsitt** [comment]
Just noticed that https://github.com/uiowa/uiowa/issues/6005 didn't include the deprovision of latham.uiowa.edu from uiowa03

**Comment by joewhitsitt** [comment]
Created a separate task for that https://github.com/uiowa/uiowa/issues/6487

**Comment by joewhitsitt** [comment]
Contacted CLAS about this site. It is on their spreadsheet to move but will talk about it internally first and get back to us.

**Comment by joewhitsitt** [comment]
Closing as shops.clas will be addressed in https://github.com/uiowa/uiowa/issues/5831
