### ISSUE TITLE
Change domain of nads.uiowa.edu to dsri.uiowa.edu

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#5996]
We’d like to launch our new name in late January to February timeframe. Is it possible to change our URL from nads.uiowa.edu to dsri.uiowa.edu

# Proposed Solution

- [x] Provision dsri.uiowa.edu
- [x] request DNS from hostmaster
- [x] SSL cert
- [x] request TTL be lowered for nads.uiowa.edu
- [x] request Vulture redirect be setup
- [x] test Vulture redirect locally once setup
- [x] Sync database and files from old site to new site
----- On Feb 10th-------
- [x] Release to get provision out?
----- On or after Feb 13th-------
- [x] Sync to new site and make new site live
- [x] update DNS for nads.uiowa.edu to point to vulture - This should happen 24 hours after TTL has been lowered
- [x] Screaming Frog reports
- [x] set TTL back to default for nads.uiowa.edu once all is well

And then follow-up with:
#6181

**Comment by mjoneill** [comment]
Waiting on Kristine R to provide an identity launch date.

**Comment by bspeare** [comment]
Requesting a go-live date of Friday, Feb. 10, or Monday the 13th? We’re flexible, though, if your team needs more time.

**Comment by joewhitsitt** [comment]
looks like this has not be provisioned, ssl, or domain pointed

**Comment by briand44** [comment]
Noticed these comments from Michael in email in its-web

>After launch, we’ll need to scan the site again with ScreamingFrog and look for anything as well.  We can furnish you reports afterwards that you’ll want to use to address anything that is still linking to the old site.

>We’ll also want to set up a vulture redirect to redirect all traffic from nads.uiowa.edu to your new site.  This is something we can assist with.

**Comment by briand44** [comment]
@joewhitsitt @sean I added a proposed solution in the initial comment from Ben. I might have missed something so feel free to update. We should request TTL be lowered for nads.uiowa.edu asap (assuming it isn't already at 5 minutes). We may actually want to launch this on Monday if TTL is not already lowered.

>Can we shoot for a go-live date of Friday, Feb. 10, or Monday the 13th? We’re flexible, though, if your team needs more time.

**Comment by pyrello** [comment]
> request Vulture redirect be setup

@briand44 or @e-marie-w I'm not sure what this entails, if you wouldn't mind providing additional details.

**Comment by pyrello** [comment]
> Screaming Frog reports

I'm not set up to do this. Is this something you can handle @briand44? Or @mkyoder?

**Comment by briand44** [comment]
There is some info https://wiki.uiowa.edu/display/drupaldev/Setting+up+a+redirect+on+Vulture.

**Comment by briand44** [comment]
I can send the email if you prefer?

**Comment by pyrello** [comment]
> I can send the email if you prefer?

I'm working on it.

**Comment by mkyoder** [comment]
I am happy to run a Screaming Frog report on this. Just let me know once the site has launched, if it hasn't already. I didn't see it marked off on the Upcoming Launches card, so wanted to double-check.

**Comment by pyrello** [comment]
> I am happy to run a Screaming Frog report on this. Just let me know once the site has launched, if it hasn't already. I didn't see it marked off on the Upcoming Launches card, so wanted to double-check.

It has not. It should be later today or Monday.

**Comment by briand44** [comment]
Because of the TTL issue, we are going to launch this on Monday morning. This has been approved by Kristine. They will be sending communications Monday afternoon.

**Comment by briand44** [comment]
A new SSL cert has been activated on uiowa04.

**Comment by pyrello** [comment]
> test Vulture redirect locally once setup

@briand44 I'm not seeing anything about how to do this in the docs linked above. Do you have any extra information you can provide?

**Comment by briand44** [comment]
Update your hosts file. You should be able to enter something like 
`128.255.103.24        nads.uiowa.edu`

Then when you go to nads.uiowa.edu on your machine your local DNS should point to Vulture (128.255.103.24). If the redirect works, we should be in good shape and you can remove your local hosts file changes. If it doesn't work then something isn't right somewhere.

You will want to test that nads.uiowa.edu redirects but also test that nads.uiowa.edu/something-else also redirects.

**Comment by joewhitsitt** [comment]
i've had to flush dns before: `sudo killall -HUP mDNSResponder`

**Comment by pyrello** [comment]
This is done.
