### ISSUE TITLE
Article contact for SiteNow Articles

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5999]
# Story

As an editor creating articles, I would like the ability to reference a person as a contact for an article so that readers with questions know who to reach out to.

# Additional Information

# Proposed solution

- Use some of the Iowa Now work and move it to default, but still keep the extra Iowa Now functionality separate.
  -  Person reference only - allows multiple
- Check splits and features for article content type
- Possibly reorganize fields on form display

**Comment by briand44** [comment]
Should this be just for Research or does it make sense to add this to default?

**Comment by bspeare** [comment]
Grooming notes:
- Use some of the Iowa Now work and move it to default, but still keep the extra Iowa Now functionality separate.
  -  Person reference only
- Check splits and features for article content type
- Possibly reorganize fields on form display
