### ISSUE TITLE
Law Journal Content example using Article type

### ISSUE THREAD

**Issue by mjoneill** [uiowa/uiowa#6002]
As a marketing director for Law, I can see what a journal entry looks like using the article content type.

* Example of article on Basic Page with abstract copy: https://lawjgrj.prod.drupal.uiowa.edu/online-edition/volume-25-issue-2/improving-res-ipsa-loquitur-doctrine-in-child-abuse-cases-a-step-toward-racial-justice?utm_source=pocket_reader

* Example of article on Basic page with NO abstract copy:  https://lawjgrj.prod.drupal.uiowa.edu/online-edition/volume-25-issue-2/the-watchmans-time-to-kill-the-right-to-vigilante-justice-in-the-jim-crow-south?utm_source=pocket_saves

Important:
* Partner considers it important for the Download PDF button to be Above the Fold
* Some articles may start without abstracts, but those will be added in the future.

**Comment by mjoneill** [comment]
@briand44 @bspeare @mkyoder Visibility: We will need to recreate a couple article pages to show Law what the current experience would be in Article format (even before we get thin width).

**Comment by briand44** [comment]
I'm curious if it would be helpful to create an example of an issue page as well? Example https://lawjgrj.prod.drupal.uiowa.edu/online-edition/volume-25-issue-2

Do we think there is a better way of handling these if they start using the "article" content type? Could these be pulled in dynamically based on tags? (tag for volume/issue, article/note)?

**Comment by mark-bennett-uiowa** [comment]
So without any custom development, I created two example articles for the two journal entries linked at the top:

- [https://lawjgrj.prod.drupal.uiowa.edu/news/2022/12/example-improving-res-ipsa-loquitur-doctrine-child-abuse-cases-step-toward-racial](https://lawjgrj.prod.drupal.uiowa.edu/news/2022/12/example-improving-res-ipsa-loquitur-doctrine-child-abuse-cases-step-toward-racial)
- [https://lawjgrj.prod.drupal.uiowa.edu/news/2022/12/example-watchmans-time-kill-right-vigilante-justice-jim-crow-south](https://lawjgrj.prod.drupal.uiowa.edu/news/2022/12/example-watchmans-time-kill-right-vigilante-justice-jim-crow-south)

This includes cleaning up the text style (the author name was a h5 -> changed to a bold normal font), and adding a "Download PDF" link button just below. This would force the editor to understand how to create and enter these directly into the Body field. Another option would include a custom PDF/URL field in the article type, that could be displayed as a button link. I also added the PDF link to the Source Link field so they could see what that looks like as well.

![Screen Shot 2022-12-12 at 3 30 59 PM](https://user-images.githubusercontent.com/3067017/207158905-6d361e1b-cae9-4334-bdde-9d0cf9c09465.png)

I also tagged these both with a "Volume 25" and "Issue 2" tag, and enabled display of tags on the PROD site, which creates a page like this:

- [https://lawjgrj.prod.drupal.uiowa.edu/tags/volume-25](https://lawjgrj.prod.drupal.uiowa.edu/tags/volume-25)

The problem with the tagging as I created it will be multiple "Issue X" entries across each Volume, which will create an issue where articles from Volume 25, Issue 2 and Volume 26, Issue 2 will show up in the same "Issue 2" list. It might work to create the Issue tags as "Volume 25, Issue 2" instead, which would avoid this problem. I also entered this as a tag for an example.

![Screen Shot 2022-12-12 at 3 31 10 PM](https://user-images.githubusercontent.com/3067017/207158945-fd3f086a-c6a7-4a51-8eb7-0634e796fd90.png)

**Comment by mark-bennett-uiowa** [comment]
Based on discusion with @joewhitsitt we created another example using authors and a organization field value of "Download PDF":

<img width="1188" alt="Screen Shot 2022-12-12 at 4 16 49 PM" src="https://user-images.githubusercontent.com/3067017/207167021-ca401a41-44c4-45e1-a9fb-0d8b46b7f48d.png">

The issue with this, is that if a Organization is not provided, the links look like this:

<img width="1177" alt="Screen Shot 2022-12-12 at 4 20 23 PM" src="https://user-images.githubusercontent.com/3067017/207167625-6cded923-bf1b-4600-914e-facc6a689a2c.png">

**Comment by joewhitsitt** [comment]
Similar examples that remove the button but keep the author in the structured field:

<img width="880" alt="Screen Shot 2022-12-12 at 4 28 42 PM" src="https://user-images.githubusercontent.com/4663676/207168908-58f4d105-6278-4da2-9c01-c3e96ae8cc29.png">
<img width="875" alt="Screen Shot 2022-12-12 at 4 28 23 PM" src="https://user-images.githubusercontent.com/4663676/207168914-00871ac3-6aa3-4277-9455-b31df94e356d.png">

**Comment by mark-bennett-uiowa** [comment]
For future cleanup of the PROD site, depending on their responses to these examples, we need to:

- Remove the 3 articles with "EXAMPLE: ..." in the title.
- Remove the 2 example authors.
- Remove the 1 page with "Example:..." in the title.
- Turn off tagging display on articles.
- Remove the tags we created

**Comment by joewhitsitt** [comment]
My understanding from yesterday's standup is that "dev" work for this is done and that @briand44 and/or @mjoneill  will meet with the customers to explain the options that were created, pulling in Mark or another dev to assist.

If so, should this move to blocked/waiting?

**Comment by briand44** [comment]
I made some adjustments to this and am going to share it with Law folks. I also updated https://github.com/uiowa/uiowa/issues/6002#issuecomment-1348815257 based on the changes I made.

I removed the full url link from the source field on the following two articles and used the author field for the author. I also created a new tag to denote these as an "article" vs a "note" for the dynamic display.

https://lawjgrj.prod.drupal.uiowa.edu/news/2022/12/example-watchmans-time-kill-right-vigilante-justice-jim-crow-south
https://lawjgrj.prod.drupal.uiowa.edu/news/2022/12/example-improving-res-ipsa-loquitur-doctrine-child-abuse-cases-step-toward-racial

I created the following example article as a "note" to demonstrate the dynamic display.
https://lawjgrj.prod.drupal.uiowa.edu/news/2022/12/example-protecting-transgender-and-gender-nonconforming-children-and-adolescents-iowa

This is the dynamic display using two article list blocks, one for articles and one for notes.
https://lawjgrj.prod.drupal.uiowa.edu/about-us/blog/example-volume-25-issue-2

**Comment by joewhitsitt** [comment]
Update from the customer:

>... has started converting the "pages" to "articles" so we will give these features a try and reach out if we have any questions.
