### ISSUE TITLE
Deprovision https://ui-lsamp.sites.uiowa.edu/ and https://latham.uiowa.edu.

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#6005]
Both sites are now part of the https://isa.uiowa.edu site and no longer needed as individual sites.
- [x] Deprovision [https://ui-lsamp.sites.uiowa.edu/](https://ui-lsamp.sites.uiowa.edu/) site.
- [x] Deprovision [https://latham.uiowa.edu](https://latham.uiowa.edu) site from uiclas application.

**Comment by mark-bennett-uiowa** [comment]
latham.uiowa.edu has been deleted from the uiclas application.

**Comment by briand44** [comment]
if the domain latham.uiowa.edu is no longer in use, we should let hostmaster know they can reclaim that domain.

**Comment by joewhitsitt** [comment]
@mark-bennett-uiowa did you see @briand44 comment about latham.uiowa.edu being reclaimed by hostmaster? https://github.com/uiowa/uiowa/issues/6005#issuecomment-1359528365

For ui-lsamp.sites.uiowa.edu the reclaim is part of our deprovision process once the #6062 goes out to PROD.

**Comment by mark-bennett-uiowa** [comment]
@joewhitsitt Ill send hostmaster an email right now. Thanks you two!

**Comment by joewhitsitt** [comment]
Deployment went out and email to reclaim ui-lsamp.sites.uiowa.edu has been sent.
