### ISSUE TITLE
Iowa Now migration updates

### ISSUE THREAD

**Issue by cory-skeers** [uiowa/uiowa#6006]
Work can continue in #5941 

Some feedback has been received (full copy is available at https://github.com/uiowa/uiowa/pull/5941#issuecomment-1341109882).

Todos:

- [x] #6017
- [x] #6018 
- [x] #6019
- [x] #6020
- [x] #6021
- [x] #6022
- [x] #6060
- [x] There was also the comment "Sub headlines look out of place. Is there a way to get them directly underneath the headline and above the date/byline?" Currently the subhead is being prepended to the body and styled as an intro-light. Might be other options there.

**Comment by bspeare** [comment]
Grooming notes:
- Changed this issue to an epic
- Cory will look to slice up the checkboxes 
- We will decide size in planning

**Comment by bspeare** [comment]
> Sub headlines look out of place. Is there a way to get them directly underneath the headline and above the date/byline?

We do have the subhead that we use on the person profile.  Maybe we could introduce something similar for articles?   https://sandbox.prod.drupal.uiowa.edu/people/celebration-herky-hawk

**Comment by briand44** [comment]
We got approval to run the migration in prod so closing this. If anything else comes up we can create a follow up.
