### ISSUE TITLE
SiteNow updates news article - December

### ISSUE THREAD

**Issue by cory-skeers** [uiowa/uiowa#6008]
## Issue/Solution ##
Provide a "release notes" type article of finished/done features/updates and publish to website, then send out dispatch email.

- [x] Create draft and update the parking lot card with an edit link
- [x] Add "release notes" covering the month of v2/v3 default profile enhancements and webmaster/edit visible bug fixes.
  * See the previous month's article as an example.
  * Bullet points from demo stories slide per week: https://drive.google.com/drive/folders/1EehKUjxCbakaB9FchrGhAbaxuRbqyDGW?usp=sharing..
- [x] Get at least one team member to look over the draft before publishing.
- [x] Since the draft was started earlier, adjust the publish date/time, publish, get the link to the article.
- [x] Dispatch email with link to article. (To get access, send an email to dispatch-support@uiowa.edu to have the account provisioned. Provide your hawkid and mention the CSI:drupal group)
  * Modify SiteNow Announcements Template (tweak opening line, update the article link, any other editorial adjustments)
  * Save
  * Clone an old communication off SiteNow Announcements campaign
    * Use SiteNow Announcements population, template, suppression list, bypass approval.
    * Turn off Dispatch "test mode" to send out email. 
    * When scheduling, check the "archive" option so that there is an RSS instance we can use in the future. I don't think this can be done after the fact.
- [x] Turn on Dispatch "test mode" after email is successfully sent.
- [x] Take a moment to check dispatch and google analytics on whether these articles are being read.
- [x] Create the next months's issue and copy all this bullet list into it, removing the checked boxes if any.

**Comment by cory-skeers** [comment]
Draft created: https://sitenow.uiowa.edu/news/2022/12/updates-december

**Comment by joewhitsitt** [comment]
Added a couple bullets to try and stay on top of it this time.

**Comment by joewhitsitt** [comment]
Added a few more bullets

**Comment by bspeare** [comment]
This looks good. I adjusted one bullet point to scope the google search results bug to admissions.uiowa.edu.

**Comment by makurj** [comment]
November analytics:

![image](https://user-images.githubusercontent.com/52135878/210840291-10759e08-5530-492f-88e9-b12a54ecf611.png)
