### ISSUE TITLE
ITS Service Catalog

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6009]
# Story

As an ITS website owner, I would like to be able to structure services and present them to users so that they (students, faculty and staff) can understand what services are available to them and how to use them.

# Additional Info

Would like to have a landing page that can be searched and filtered by various things.
- Some flexibility in how this is put together. Currently there are a lot of services so listing all of these may be overwhelming for students. Could potentially display featured services and allow searching/filtering all services. Possibly something like https://uihc.org/services. We may want to create some mockups and get feedback on this.
- Way to filter based on an audience (faculty, staff, students, etc.) - ITS folks will provide the list of audiences
- Way to search just services based on title, any synonyms (icon vs canvas), description
- Display just title in list since there are so many additional info could be too much?

**Expired Content** - needed but it is not perfect currently - not easy to maintain - only exists for infocenters
**Workgroup owner**
- Workgroup unit names with emails
- Each infocenter has a workgroup owner
- Workgroup owner assigns expiration date max 365 days 
- Workgroup owner sets emails to receive an email notification every few weeks
- Message displays on infocenter for authenticated folks when an infocenter is expired
- Also user page shows expired content for that user - this is a nice to have and email is more valuable.
- Internal reporting would be nice to have to help hold people accountable.

**Tying to alerts?**
- may or may not directly relate to an infocenter. What is the source of truth for services

Naming conventions?

News articles relate to services

**Support Articles related to services**

Want to be able to relate projects to services. Projects could be a type of infocenter but infocenters may be too structured.

**Fields**

If a content migration is possible, they would like that.

# Proposed solution

- [x] #6563
- [x] #6666 
- [x] #6806
- [x] #6826
- [x] #6190 
- [x] #6872
- [x] #6890 
- [x] #723  
- [x] #6190 
- [x] Turn on site split in prod
- [x] Migration of Infocenters/Services?

**Comment by bspeare** [comment]
Seems like the "catalog" aspect of this could be the same as we are thinking for teach.its:

- Develop a list block with exposed search for pages https://github.com/uiowa/uiowa/issues/6420#issuecomment-1593116835
- Then pair that with a resource content type: https://github.com/uiowa/uiowa/issues/6420#issuecomment-1591995158.

**Comment by briand44** [comment]
Grooming conversation... potentially establish site split. Determine if infocenters are basic pages?

1st slice - mockups of a service catalog page with filters/searching capabilities. Also a mockup for an individual service/infocenter.
