### ISSUE TITLE
IGEC - Require a webform to be submitted prior to being able to view a specific piece of content.

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6010]
As an IGEC website owner, I would like to require users fill out a form that captures demographic information prior to having access to a particular piece of content.

# Additional Information

IGEC offers free courses to a variety of folks both inside and outside the University. Currently have around 9 courses.

This is grant funded and capturing counts and demographic information related to each registrant is a requirement. The grant ends in a year (end of 2023?) and they would like to have a good solution for when they re-apply for the grant.

Capture information such as age, gender, race, if live in rural area, etc. Not asking for name or other identifiable information.

The course materials are just static content and embedded YouTube videos.

Currently using UI Learn but this solution hasn't been ideal.

**Comment by briand44** [comment]
Do we have a way or does anyone have any ideas on if we could require a webform or other form to be filled out and submitted before allowing access to specific course material?

**Comment by briand44** [comment]
Ben S. suggested just having the content public but not linked to from anywhere and when the form gets submitted it would take you to the specific course material.

**Comment by briand44** [comment]
From Michael:

Brian, possible solution for Iowa Geriatric?
https://wistia.com/for/demo-video

**Comment by joewhitsitt** [comment]
>Ben S. suggested just having the content public but not linked to from anywhere and when the form gets submitted it would take you to the specific course material.

Yeah, the confirmation page could just have a link to a file. If they needed to they could rotate the link periodically (e.g. move within onedrive or something).

Alternatively (custom), we could introduce logic to trigger a file download without revealing the stored path. We have something similar for brand's lockups.

**Comment by briand44** [comment]
@joewhitsitt I think the customers were envisioning the course materials to be content (likely basic pages) within the website and not files in O365. Maybe I am not understanding your references to downloading files, rotating the link, etc.

**Comment by joewhitsitt** [comment]
gotcha. just thinking about obscure links that are easy to change by moving the file around.

if it was content within the site, nofollow could be set for individual pages. i don't think we have that no-follow granularity with files.

**Comment by briand44** [comment]
It sounds like they are going to try out having a webform for each course and setting up the webforms to redirect to the specific course materials. I've showed them how to use the SEO settings to not have search engines index those pages. Going to close this as there is not anything our team needs to do at this point.
