### ISSUE TITLE
Periodical feature - Breadcrumbs without menus

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#6013]
# Motivation

Our current system requires nodes to be in the menu to have a breadcrumb trail. The periodical feature was designed to work without using the menu system. Articles and issues would benefit from the context of breadcrumbs to help the user navigate through their structure.

# Proposed solution

Investigate using Easy Breadcrumbs or another solution to provide breadcrumbs without menu links. Ensure that the new solution doesn't conflict with how our system is currently set up.

**Comment by joewhitsitt** [comment]
This has come up with the local events feature recently:
https://github.com/uiowa/uiowa/issues/5879#issuecomment-1295305915

We did something for 2plus2 on Admissions and have altered breadcrumbs for Articles in the past

**Comment by briand44** [comment]
breadcrumb structure from article would be home->issue->article

**Comment by joewhitsitt** [comment]
If easy breadcrumbs works but conflicts should we look into removing menu_breadcrumb and relying on easy breadcrumbs to provide both solutions? I feel like this was a "which was d8 ready first" decision initially

**Comment by briand44** [comment]
Grooming conversation.... We discussed some investigation can be in scope here to different breadcrumb solutions but the goal is to address the breadcrumb issue for periodicals and we don't want to blow this into a giant epic.

**Comment by joewhitsitt** [comment]
FWIW both easy_breadcrumb and custom_breadcrumbs didn't have a d8 stable release when we originally went looking. usage for easy_breadcrumb is now higher than menu_breadcrumb. custom_breadcrumbs was late to the game and hasn't exploded with usage.

**Comment by joewhitsitt** [comment]
So far, I have been able to achieve the desired result without uninstalling menu breadcrumb. I forgot that the periodical paths are not backed by contextual views listings, so they are unlinked.

<img width="711" alt="Screenshot 2023-05-23 at 10 45 52 AM" src="https://github.com/uiowa/uiowa/assets/4663676/4727b84a-96ec-4209-94e3-65578c55a609">
<img width="491" alt="Screenshot 2023-05-23 at 10 40 08 AM" src="https://github.com/uiowa/uiowa/assets/4663676/e4b7aa8d-d997-4a5c-8913-00ff3ff324ea">
<img width="750" alt="Screenshot 2023-05-23 at 10 45 30 AM" src="https://github.com/uiowa/uiowa/assets/4663676/ae5a08b9-3ea5-4e76-916f-bbcc20ef2f5f">

Maintaining menu based breadcrumbs where an overridden alias was involved was an initial concern but with menu breadcrumb that is retained:

<img width="764" alt="Screenshot 2023-05-23 at 10 51 01 AM" src="https://github.com/uiowa/uiowa/assets/4663676/b61cd81f-5c8b-4ecb-a557-7299e50d7b33">

I believe these can coexist surprisingly well as it favors the menu based path if it exists:

<img width="981" alt="Screenshot 2023-05-23 at 10 55 11 AM" src="https://github.com/uiowa/uiowa/assets/4663676/220f9c1d-cf34-4a51-80ea-28d3c48f8b5d">

Trying to find a situation where things break down.

**Comment by joewhitsitt** [comment]
Didn't break for Admissions (https://admissions.uiowa.ddev.site/first-year-admissions).

Concerns so far:

- Having core plus two modules works until it doesn't and then how complex will it be to sort out where one piece of functionality ends and the other begins? I might try to achieve the same result with just custom_breadcrumbs installed.
- Introducing this functionality goes against our original definition of breadcrumbs by creating faux-crumbs with no links. Have we already done that somewhere? I know we have broken from the menu pattern but they have always been linked right? 2plus2, articles, etc. This introduces a new inconsistency for the user about what to expect around these. Wouldn't this also be solved with an "Issues" views page and a contextual based "Volume/Issue" views page with menu entries?

**Comment by joewhitsitt** [comment]
Trying custom_breadcrumbs now

Update: I think I know why the other module is called easy breadcrumbs...
