### ISSUE TITLE
Periodical feature might be hiding the article date for all articles

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#6015]
# Problem

While reviewing https://github.com/uiowa/uiowa/pull/5993 I noticed that all articles are missing the published date (created) on render regardless of whether or not they have a reference to a periodical. This is an issue to confirm that this an issue with the feature and/or the 91st Meridian site split and correct it if so.

# Steps to reproduce

- Default site with the periodical feature turned on and/or the 91st Meridian synced down.
- Create an article with no reference to a periodical.
- Check to see if the published date is rendered on the full node.

# Proposed solution
- TBD

**Comment by briand44** [comment]
Closing this as a bug. We still haven't addressed the theming slice of this yet and also the customer reviewed and didn't bring this up so closing for now and can be addressed in a separate issue.
