### ISSUE TITLE
BUG: No separation between author and source link (no ORG) for Article display

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#6016]
# Problem
If an article contains Authors and a Source Link, but the Organization is not provided by a site editor for an individual article, then the Authors and Source Link run together with only a blank space separator.

<img width="1177" alt="Screen Shot 2022-12-12 at 4 20 23 PM" src="https://user-images.githubusercontent.com/3067017/207167625-6cded923-bf1b-4600-914e-facc6a689a2c.png">

# Steps to reproduce

- Create a new article.
- Attach one or more authors.
- Add a URL to the Source Link field.
- Leave the Organization field empty.

# Proposed solution

1. Move the Organization and Source Link display to the following line under the Authors, OR
2. Add a separator if Authors and Source Link are provided (e.g. Source: label or additional characters)
3. If the Organization is provided, then continue to use that as a separator.

<img width="1188" alt="Screen Shot 2022-12-12 at 4 16 49 PM" src="https://user-images.githubusercontent.com/3067017/207167021-ca401a41-44c4-45e1-a9fb-0d8b46b7f48d.png">

**Comment by bspeare** [comment]
We are also missing the line in the teaser view as well: https://sandbox.prod.drupal.uiowa.edu/tags/tippie-blog.
