### ISSUE TITLE
Now Migration: Update primary video logic

### ISSUE THREAD

**Issue by cory-skeers** [uiowa/uiowa#6017]
Update Primary Media Video logic to check if there is other existing media in the body. If there is, center align at the top. If there is not, left-align at the top of the body.

Applies to Achievements, possibly News Feature (can check if there are any videos in that field first).

Continue work in https://github.com/uiowa/uiowa/pull/5941

**Comment by joewhitsitt** [comment]
Update: I pulled down the now site locally and created a view to filter ~~on primary media (not empty) and body contains (media-element). 888 results~~ files of `application/octet-stream` mimetype (oembed video) and a relationship to the primary media field with body containing media-element. 23 results.

<details>
<summary>nids</summary>
14772
14811
14866
14957
14969
14999
15068
15322
15567
15579
15587
15589
15597
16097
16181
16231
17108
17836
18946
19126
20661
21601
22891
</details>

**Comment by cory-skeers** [comment]
> Update: I pulled down the now site locally and created a view to filter ~on primary media (not empty) and body contains (media-element). 888 results~ files of `application/octet-stream` mimetype (oembed video) and a relationship to the primary media field with body containing media-element. 23 results.

Thanks @joewhitsitt!

I added a query condition to the News Feature source based on this, so the migration should only recognize the 23 nodes from this list instead of going through everything. After this issue is closed, we can tear it out to get back to the full results set.

**Comment by cory-skeers** [comment]
Looks like it is only relevant for News Feature and not Achievements, based on the list of example NIDs.

After taking a closer look at some of the examples, I also adjusted the work @GaryRidgway had started to left-align if there was no media within a certain character count (700 seemed to work).

There are some articles where there's media on the page, but it's not until far down where adding the video left-align doesn't affect it (https://now.uiowa.edu/2016/09/engineering-library-opens-new-creative-space), whereas others the media is close to the top, leading to the awkward overlaps (https://now.uiowa.edu/2015/05/student-experience-alex-zeppieri).

**Comment by GaryRidgway** [comment]
With what has been done today, I believe we are ready for testing. We have left the NIDS for relevant content that would be affected by this in the code for testing purposes

**Comment by bspeare** [comment]
Maybe we should right-align the video?  I think right alignment is a little more forgiving than left when it comes to the text wrapping. 

<details>
<img width="1396" alt="Screen Shot 2022-12-22 at 8 55 36 AM" src="https://user-images.githubusercontent.com/1036433/209162905-0f8eeedc-2ad6-448f-a373-8eca78b48c8d.png">

<img width="1379" alt="Screen Shot 2022-12-22 at 8 58 49 AM" src="https://user-images.githubusercontent.com/1036433/209162934-ff56b205-465d-4433-9e7c-dcd12150ece8.png">

</details>

**Comment by cory-skeers** [comment]
> Maybe we should right-align the video? I think right alignment is a little more forgiving than left when it comes to the text wrapping.

I've updated it to right; haven't checked it yet, but it should work the same. 👍

**Comment by cory-skeers** [comment]
Closing this out. There's an overlap with this issue and https://github.com/uiowa/uiowa/pull/5941#issuecomment-1367469186, but that would be fixed by #6060.
