### ISSUE TITLE
Now Migration: In-body Callout updates

### ISSUE THREAD

**Issue by cory-skeers** [uiowa/uiowa#6018]
- Update the (`NewsFeature`) https://github.com/uiowa/uiowa/blob/7428cb6e5cef6acc82f4e26e7c92c184641dc94d/docroot/sites/now.uiowa.edu/modules/now_migrate/src/Plugin/migrate/source/Achievement.php#L195-L233
   and (`Achievement`) https://github.com/uiowa/uiowa/blob/7428cb6e5cef6acc82f4e26e7c92c184641dc94d/docroot/sites/now.uiowa.edu/modules/now_migrate/src/Plugin/migrate/source/NewsFeature.php#L338-L376 Both need the same updates to map the source callout to the new callout structure.
   - Adjust hardcoded defaults to determined size (small) and background (gray)
   - Test in the migration and check that the hardcoded callout construction replacements work well with various different bits of content from the source
   - Can find a query adjustment to ease the testing burden of this and pull in only nodes which contain callouts

**Comment by bspeare** [comment]
I looked at the callout boxes and I'm not sure if the blockquote is the best option here.   

<details>
<img width="1594" alt="Screen Shot 2022-12-14 at 12 54 55 PM" src="https://user-images.githubusercontent.com/1036433/207687250-6e0e0f2b-346e-4310-a84d-46487f10c97d.png">

</details>

What if we used some of our block styles here? Using these classes `<div class="align-right block-padding__all bg--gray"></div>` would create this page appearance. 
<details>
<img width="1445" alt="Screen Shot 2022-12-14 at 12 48 12 PM" src="https://user-images.githubusercontent.com/1036433/207685677-a1df4a40-3e4f-4f33-9db4-ea3daf9059a9.png">
</details>

I think either style could work here.  Since the callout boxes are not quotes, it seems like a poor use of the blockquote tag.   Either way, we currently don't have a way to insert inline floated boxes within the WYSIWYG.

**Comment by bspeare** [comment]
> Some stylized headings didn't get brought over. 

The fallback to heading tag styles looks appropriate in comparing https://now.dev.drupal.uiowa.edu/news/2022/05/dates-and-times-spring-2022-commencement-ceremonies-announced with https://now.uiowa.edu/2022/05/dates-and-times-spring-2022-commencement-ceremonies-announced.  What type of fix are they looking for here?

**Comment by joewhitsitt** [comment]
>What if we used some of our block styles here

Are we ready to encourage that kind of usage? Like others have said, seeing Iowa Now may give other websites ideas about what they want.

**Comment by bspeare** [comment]
Will ckeditor 5 allow for placement of inline blocks (https://github.com/uiowa/uiowa/issues/5667)?  If so, would we want to introduce a "callout" style for long passages of text?  Or are we sticking with blockquote which people use for phone numbers, addresses, etc.

**Comment by cory-skeers** [comment]
> > Some stylized headings didn't get brought over.
> 
> The fallback to heading tag styles looks appropriate in comparing https://now.dev.drupal.uiowa.edu/news/2022/05/dates-and-times-spring-2022-commencement-ceremonies-announced with https://now.uiowa.edu/2022/05/dates-and-times-spring-2022-commencement-ceremonies-announced. What type of fix are they looking for here?

Good question! To me, that looks like simply the difference between former and current styles, but like it fits the overall aesthetic and intention of the headings. Maybe there are other examples they can provide that would need addressing, but this might be a case of works as intended.

**Comment by bspeare** [comment]
I've added an issue to build out the callout component in UIDS: https://github.com/uiowa/uids/issues/844/.

**Comment by briand44** [comment]
We may not be able to address the stylized headings since there aren't specific classes currently.

**Comment by cory-skeers** [comment]
Updated byline for News Feature and Achievements migrations.

There's a small discrepancy between these faux bylines (plain text in the article source) and true bylines (referenced author) where the "Written by: " is bold in the latter but not the former.
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/49074566/212380707-1667eb91-20d6-4663-b6d3-1f77d9b55c02.png">

I think this could be acceptable, as the author reference also includes a link to differentiate it from the migrated sources, and it's a small difference for what will be old articles compared to new; but we should get feedback on this.

**Comment by cory-skeers** [comment]
Update for the callouts has been added into #5941, along with `@todos` for updating the markup once callouts are implemented. Will need testing, but it's fairly small and contained as far as regex replacements go.

**Comment by briand44** [comment]
Planning conversation - use small size and default to gray background
