### ISSUE TITLE
Create a new temporary text format

### ISSUE THREAD

**Issue by makurj** [uiowa/uiowa#6023]
1. Create a new temporary text format that duplicates Minimal and adds `<ul><ol>`
2. Switch the card block and the facilities text fields to use this new format

Reference: https://github.com/uiowa/uiowa/issues/5472#issuecomment-1349258442

**Comment by briand44** [comment]
Can someone help me understand this?

**Comment by makurj** [comment]
This is the next step for https://github.com/uiowa/uiowa/issues/5472#issuecomment-1349258442.

**Comment by briand44** [comment]
I understand that but curious to why we are creating a temporary text format? I didn't see any conversation about why it is temporary or when it can be removed?

**Comment by makurj** [comment]
My understanding is this would be temporary until after V2 https://github.com/uiowa/uiowa/issues/6024.

**Comment by joewhitsitt** [comment]
@briand44 see my comments https://github.com/uiowa/uiowa/issues/5472#issuecomment-1348991536 related to leaving minimal untouched for now.

**Comment by briand44** [comment]
Was there a big concern with using filtered html for the Facilities fields? I would like to unblock the named building content work as soon as possible so trying to understand why we didn't just go that route for those fields? Also, not sure who has been asking for the ability to have lists in cards and how high of priority that is? Do we need to get this prioritized right away or should we push Facilities forward with filtered html and revisit this later?

**Comment by bspeare** [comment]
I think the amount of work involved switching facilities back to `filtered_html` vs duplicating `minimal_html` and a creating a temporary text format to attach to the card block and the facilities fields is about the same.  I vote that we move forward with the temporary text format now and make sure we note to circle back to facilities in the https://github.com/uiowa/uiowa/issues/6024 issue.
