### ISSUE TITLE
Content/Design changes for Iowa Now

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6025]
Meeting notes from 12/13

- Move https://now.dev.drupal.uiowa.edu/news-faculty-and-staff to be the home page without a special Faculty and Staff label
- Featured story at the top of the page
  - Remove main featured story section.  They are not ready for it yet. 
- Featured Headlines
  - Move "Featured Headlines" up to the first spot.  Switch to 6 items and show images and use migrated content in an article list block. 
- Headlines
  - Change to "Around campus"
  - They are considering whether to use aggregator here or create duplicate copies on their site and adjust the canonical url to point to the story source. 
- Resources
  - They still like the idea of this in a sidebar.  Perhaps clone the updated home page after all the changes have been made and experiment with its placement.  
- Media Highlights
  - This can be removed for now.  They are not ready for it yet. 
- Share News CTA and webform
  -  They are wondering if Share your news webform can be split with https://now.uiowa.edu/grant-awards-intake-form.   Perhaps having users select "Share your news" or "Grant Awards Intake Form" to conditionally show different form fields.

**Comment by mkyoder** [comment]
Completed so far:

- [x] Move https://now.dev.drupal.uiowa.edu/news-faculty-and-staff to be the home page without a special Faculty and Staff label
- [x] Featured story at the top of the page
- [x] Remove main featured story section. They are not ready for it yet.
- [x] Featured Headlines
- [x] Move "Featured Headlines" up to the first spot. Switch to 6 items and show images and use migrated content in an article list block.
- [x] Headlines
- [x] Change to "Around campus"
- [ ] They are considering whether to use aggregator here or create duplicate copies on their site and adjust the canonical url to point to the story source.
- [x] Resources- They still like the idea of this in a sidebar. Perhaps clone the updated home page after all the changes have been made and experiment with its placement.
- [x] Media Highlights - This can be removed for now. They are not ready for it yet.
- [x] Share News CTA and webform - They are wondering if Share your news webform can be split with https://now.uiowa.edu/grant-awards-intake-form. Perhaps having users select "Share your news" or "Grant Awards Intake Form" to conditionally show different form fields.

**Comment by mkyoder** [comment]
Webform would have the box that you check when you fill out the webform whether it is Grant Awards form. Checkbox - Is this a grant or some sort of news? User could checkbox and then submit it.

**Comment by mkyoder** [comment]
Resources towards the top on the sidebar - clone the page to see what it looks like without the sidebar.

**Comment by mkyoder** [comment]
Remove "News for Faculty and Staff" staff naming and just make homepage of site.

**Comment by mkyoder** [comment]
Find images of for featured headlines for all six cards so that the team can see what it looks like.

**Comment by bspeare** [comment]
@mkyoder are you working on https://now.dev.drupal.uiowa.edu/ or https://now.prod.drupal.uiowa.edu/?

**Comment by mkyoder** [comment]
@bspeare I was working on https://now.dev.drupal.uiowa.edu. Should I be making these changes on the prod site instead?

**Comment by bspeare** [comment]
@mkyoder I think we should be working on the prod site.   @briand44 please correct me if I'm wrong on that.

**Comment by briand44** [comment]
yeah, prod site

**Comment by mkyoder** [comment]
Got it! Thanks for letting me know! :)

**Comment by briand44** [comment]
Resources from Tricia.

Employee Self-Service
Directory
Academic Calendar
Office365 email
University Billing Office (specifically to the faculty/staff page: https://ubill.fo.uiowa.edu/facultystaff-u-bill)
Human Resources
ITS (https://its.uiowa.edu/)
Parking and Transportation (https://transportation.uiowa.edu/)
Campus Map
Campus Safety
Emergency Info
Mental Health at Iowa (mentalhealth.uiowa.edu)
Division of Diversity, Equity, and Inclusion (https://diversity.uiowa.edu/)
ICON
MAUI
General Catalog
Free Speech at Iowa
Jobs at Iowa

**Comment by mkyoder** [comment]
Okay, one more question here before I start changing content. Can what is in dev be mirrored to what is on the prod site? Since these two pages are laid out differently here: https://now.dev.drupal.uiowa.edu and here: https://now.prod.drupal.uiowa.edu/, I'm assuming I'll just need to build out what is currently on dev to mirror the prod site site within LB. But just wanted to make sure before I start it. :)

**Comment by bspeare** [comment]
@mkyoder the page is at https://now.prod.drupal.uiowa.edu/news-faculty-and-staff on prod.  You just need to make that the home page and remove the current home page.

**Comment by mkyoder** [comment]
Got it! Thank you! Okay, last thing...I set the articles block to display 6 and had the tag as 'featured.' But it's only pulling in three articles. Does that mean there are only three to display that are with that tag? 

![Screen Shot 2022-12-21 at 12 10 49 PM](https://user-images.githubusercontent.com/107870104/208974891-8e5c18b4-0004-4d3a-8374-115b545cc112.png)

**Comment by mkyoder** [comment]
Never mind, I figured it out. :) Sorry for all the comments here.

**Comment by bspeare** [comment]
@mkyoder yes, the content hasn't been migrated yet.

**Comment by mkyoder** [comment]
All these tasks are done now here: https://now.prod.drupal.uiowa.edu/.

I duplicated this page here: https://now.prod.drupal.uiowa.edu/home-copy and placed the resources on as a sidebar to see what the Iowa Now team thinks of this layout as another option. 

Let me know if I missed anything else here.

**Comment by mkyoder** [comment]
Resource links added to the footer now instead of as a sidebar on this page: https://now.prod.drupal.uiowa.edu/.

**Comment by briand44** [comment]
@bspeare @mkyoder What is the next step here? Should this be moved to blocked waiting? Do we need any other eyes on this or are we ready to share this with Iowa Now folks? Is that something we should wait on until we have the articles migrated or can that happen now? Do we need to schedule a meeting to talk through these changes or can we share through email? Would love to hear your thoughts on this since I missed that last meeting.

**Comment by briand44** [comment]
Also, is there any context around the last comment...

> Resource links added to the footer now instead of as a sidebar on this page: https://now.prod.drupal.uiowa.edu/.

Did we experiment with these in a sidebar?

**Comment by mkyoder** [comment]
Some context for the resource links in the footer. I duplicated the home page and put the resources link in the sidebar as an example for the Iowa Now team and to experiment with its placement on the page.

However, Ben and I chatted about this version of the page and determined that putting the links in the footer would be a better solution rather than the sidebar that the Iowa Now team was looking for because: 

•	Users will go to [uiowa.edu](http://uiowa.edu/) or Google for the resource links instead of IowaNow as a first stop in their web journey in looking for these types of resources
•	We could put links in footer like we do on [uiowa.edu](http://uiowa.edu/) or link to a-z list in the footer
o	We are trying to encourage colleges and departments to use the footer links for this type of link grouping for a consistent user experience across the platform. See [tippie.uiowa.edu](http://tippie.uiowa.edu/) as another example.
•	A-Z list is a managed list of all university resource links.
o	A link grouping on a website can easily go out of date

I think this can be moved to blocked waiting. But maybe the next step would be to meet about the new placement and the rationale behind putting these links in the footer (rather than the sidebar) before meeting with the Iowa Now team.

**Comment by briand44** [comment]
Moved this to blocked/waiting since it is not currently being worked on.

We may want to chat about the resources...

>Users will go to [uiowa.edu](http://uiowa.edu/) or Google for the resource links instead of IowaNow as a first stop in their web journey in looking for these types of resources

My understanding is that Iowa Now folks would like to become the first stop for faculty/staff when looking for these types of resources so I am not sure they will be happy with the links in the footer. I don't have strong feelings about this, just not sure they will be happy with it.

A separate thought I had if their goal is for this site to be more focused at internal audiences is that this could possibly be the default web page for campus computers at some point? Currently the Hawktools website is (at least for ITC's) and the future of that site is uncertain. Jack mentioned that he liked some of the things with that Hawktools website. Something to think about anyway if we want to get rid of Hawktools website and make Iowa Now more internally focused.

**Comment by mjoneill** [comment]
I know they want a sidebar container where they can highlight links...links that are likely to change with the season/etc...    I'm OK with recommending static links in the footer, but I think we have committed to container/treatment for links under their control that they can feature on a page.  I've been calling them a sidebar/sidebar container.  

Does this intersect at all your last conversation with them?

Some things that they might want to feature could include:
* Seasonal flu clinics
* Benefits enrollment deadlines
* Wellness links
* etc...

**Comment by bspeare** [comment]
The other option @mkyoder and I discussed was to create a "Resources" page in the top navigation so that we could dedicate a page to these resources.   The issue with putting a grouping of 19+ links in the middle of their home page is that it is a lot of links to add and read through.    Wouldn't it be better if we created a page that we could design and put these links into readable categories that would make for a better user experience?  

Something like:

- A grouping of cards with category headings (https://sit.indiana.edu/academic-campus-resources/campus-resources.html )
- An A-Z list (https://resources.depaul.edu/Pages/default.aspx)
- Topics collection-like page (https://mentalhealth.uiowa.edu/help)

**Comment by briand44** [comment]
Thanks Ben, I appreciate you having some alternative approaches in our back pocket if they don't like what we have now. Do you think we should schedule some time to go over these changes with them now or is this something that would be more valuable to share with them once we have the migration issues worked out and have migrated the articles over?

**Comment by mjoneill** [comment]
I think it's worth a conversation internally first.  I'd like to understand all the ideas, with the request to have landing page experience with lots of ways to feature news, links to other sites, etc...

**Comment by bspeare** [comment]
Next steps after our discussion this morning:
- Remove links from the footer and instead add a section of cards for Email, Employee Self-Service, and Human Resources like:

<img width="1252" alt="Screen Shot 2023-01-06 at 10 10 28 AM" src="https://user-images.githubusercontent.com/1036433/211051554-e8845619-b8ea-4db0-88a7-c45dff4c45cd.png">

- Link to full Resources page of all the links like https://sit.indiana.edu/academic-campus-resources/campus-resources.html on a page using a grid of cards with possible groupings and headings.

**Comment by mkyoder** [comment]
Hi! 

Here is an updated homepage: https://now.prod.drupal.uiowa.edu/home-copy. I can’t take credit for this page refresh as this was all Ben. 😊

Link to a full resources page with all the links like Indiana and put in a grid of cards with various groups and headings by resource type. I took all 19 resources listed above and broke these down into the following categories: Employee Resources, Campus and Safety Resources, Academic Resources, Mental Health Resources, and DEI and Free Speech Resources. https://now.prod.drupal.uiowa.edu/resources

**Comment by briand44** [comment]
Thanks @mkyoder & @bspeare! Is there a reason we have a menu link for Iowa Now? Also, is the page currently set as the homepage the changes they specifically asked for and the new homepage just an alternate approach we put together? Just hoping to understand this prior to meeting with them. I will work on getting something scheduled with them to go over this.

**Comment by bspeare** [comment]
I think it might be useful to present https://now.prod.drupal.uiowa.edu/home-copy as the updated home page and only pull pieces from the old versions for reference if necessary.

**Comment by briand44** [comment]
Going to close this out since we completed these items and got feedback. Additional items will be addressed in https://github.com/uiowa/uiowa/issues/6092
