### ISSUE TITLE
Add database handling for Sitenow Migrate

### ISSUE THREAD

**Issue by cory-skeers** [uiowa/uiowa#603]
## Problem
The Sitenow Migrate module, which can be used to migrate files, basic pages, articles, and people from a Sitenow Standard D7 site to D8 currently requires hardcoding database information in one file and a base file URL in another (sitenow_migrate/config/install/migrate_plus.migration_group.sitenow_migrate.yml and sitenow_migrate/config/install/migrate_plus.migration.d7_file.yml, respectively).
This prevents the module from being included as a default with new site provisions as they'd require a config split or custom work.

## Proposed Solution
If possible, use aliases and/or site config variables to programmatically update these two config files on install.

Otherwise, create a UI to edit and update these.

## Additional Info
More details on sitenow_migrate can be found in #379

**Comment by joewhitsitt** [comment]
So i worked on this and pushed up a working example to the migrate branch (i think).

I moved config to the profile, enabled the modules by default, the config is empty initially. This still assumes an admin role is configuring and then running the drush commands for the site using a locally synced site.

@richardbporter had concerns about trying to store any database credentials as part of this process as well as possible issues communication between acquia applications.

So I think the workflow would be to LSP and Sync the D7 site local with dev desktop (port hardcoded), provision the d8 site normally and sync the site locally. configure and run the migration, sql-sync and rsync the site back up upon successful migration.
