### ISSUE TITLE
AD role mappings thelightbox.radiology.uiowa.edu

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6037]
# Story

As an owner of the intranet thelightbox.radiology.uiowa.edu, I would like to grant access to specific AD groups so that we do not have to manually control access.

Examples from other websites:
https://github.com/uiowa/uiowa/blob/main/config/sites/sitenow.uiowa.edu/config_split.patch.uiowa_auth.settings.yml
https://github.com/uiowa/uiowa/blob/main/config/sites/brand.uiowa.edu/config_split.patch.uiowa_auth.settings.yml

# Additional Info
https://radiologythelightbox.prod.drupal.uiowa.edu

The AD groups that needs access can be found on the existing live site https://thelightbox.radiology.uiowa.edu/admin/config/people/simplesamlphp_auth/sync

#5862 

# Proposed solution

**Comment by briand44** [comment]
Blocked until https://github.com/uiowa/uiowa/issues/5862

**Comment by joewhitsitt** [comment]
This is no longer blocked. Would you like me to do this @briand44 ?

**Comment by briand44** [comment]
Sure! I can follow up with the customer when complete. Just add the same groups as their D7 site with viewer role.

**Comment by joewhitsitt** [comment]
This is done.

```
ddev drush @radiologythelightbox.prod uicore-crm
 [notice] 3: 'viewer|urn:oid:2.5.4.31|CN=radiology-all-staff,OU=Groups,DC=iowa,DC=uiowa,DC=edu'
4: 'viewer|urn:oid:2.5.4.31|CN=Medicine-Radiology-D3265,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
5: 'viewer|urn:oid:2.5.4.31|CN=Medicine-Radiology-S3265,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
6: 'viewer|urn:oid:2.5.4.31|CN=UIHC-Radiology-D7310,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'
7: 'viewer|urn:oid:2.5.4.31|CN=UIHC-Radiology-S7310,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu'

Connection to uiowa03.ssh.prod.acquia-sites.com closed.
```

**Comment by briand44** [comment]
Thanks, I've communicated this to the customer. Closing
