### ISSUE TITLE
Classrooms - Remaining Fields

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6041]
# Additional Info

- Tile Details
    - multiple items - text field
    - when we migrate we will need to combine the existing two fields into one
    - There does not need to be a filter on the search page for this
- Design Details
    - multiple items - text field
    - when we migrate we will need to combine the existing two fields into one
    - There does not need to be a filter on the search page for this
- Classroom Furniture
    - multiple items - text field
    - when we migrate we will need to combine the existing two fields into one
    - There does not need to be a filter on the search page for this
- Scheduling Region - comes from MAUI room data API https://api.maui.uiowa.edu/maui/api/pub/registrar/courses/AstraRoomData/ajb/e105
    - "SC SW" is an example from the room in the API link above
    - From the regionList
    - This sounds to me like a taxonomy similar to the features where they will need to populate the list of terms, have control over how it outputs on the page vs how it is in the API (API Name field).
    - There will be a filter on the search page to filter by scheduling region.
    - https://classrooms.prod.drupal.uiowa.edu/university-classroom-scheduling-regions

# Proposed solution

**Comment by joewhitsitt** [comment]
would three text areas (instead of multi textfields) be an option here too or is that inviting too much inconsistency with styling, content length?

**Comment by briand44** [comment]
Possibly... These fields all look like text fields currently so I don't think we will run into any issues migrating the content over. They haven't asked for any changes with how that info is handled and based on the styling in the mockup (https://sandbox.prod.drupal.uiowa.edu/art-building-west-240) it seems like multi text fields will better allow styling similar to other room features
