### ISSUE TITLE
Theme Classroom rooms based on mockup 

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6044]
# Story

As a classrooms website owner, I would like to see rooms designed similar to what we were shown in the mockup.

# Additional Info

New mockup as of Monday, January 9, 2023: https://sandbox.prod.drupal.uiowa.edu/art-building-west-240-alt
Old Mockup - https://sandbox.prod.drupal.uiowa.edu/art-building-west-240

I believe we are missing a few fields in the mockup. A couple that come to mind are:

- Design Details - similar to Furniture and Tile Details
- Scheduling Region - This will need to be output somewhere on a room. I think we can put it where we feel works best and get feedback. This will output the scheduling region name as a link to https://classrooms.prod.drupal.uiowa.edu/university-classroom-scheduling-regions

Bringing these over from #5769

- [x] Map link - output link from static map media field (This should be done in the theming slice)
- [x] Link - title and url - multiple (Will be handled through custom block/theming https://github.com/uiowa/uiowa/issues/5769#issuecomment-1346884646)
- [x] Building - link to building page on classrooms site like https://classrooms.prod.drupal.uiowa.edu/art-building-west / https://classrooms.uiowa.edu/building/abw. 
  - The building pages will be programmatically put together and rendered so we will construct a link in the theming slice and place it into the layout. 

# Proposed Solution

**Comment by briand44** [comment]
Icon picker to technology features taxonomy

**Comment by makurj** [comment]
@briand44 Are we missing the accessibility field in the content type? Or should I be adding it in this issue?

**Comment by briand44** [comment]
>Are we missing the accessibility field in the content type? Or should I be adding it in this issue?

Good question. I am guessing that was an oversight on my end previously. I will get clarification on that. I wouldn't worry about it right now.

**Comment by joewhitsitt** [comment]
Realized the schedule info piece got fragmented across a couple issues.

~~See `getRoomSchedule` in docroot/modules/custom/uiowa_maui/src/MauiApi.php for what is needed to call and get the information. Historically, we have made a block plugin to place and render this information and the caching will have to be hourly on it (similar to the sitenow_events block) so that the information can change daily.~~ moved comment to #6045 

>I want to mention one more thing about the Scheduling Region. I don't know for sure if/how this is going to be output on a room. I have an outstanding question to understand if it needs to output on a room and if so, if it is just text or a link to https://classrooms.prod.drupal.uiowa.edu/university-classroom-scheduling-regions or somewhere else. That can likely be handled on the theming issue. -  https://github.com/uiowa/uiowa/issues/6032#issuecomment-1361513945

@briand44 did you get clarity about it?

**Comment by briand44** [comment]
@joewhitsitt Yes, they want to output the scheduling region on a room as a link to https://classrooms.prod.drupal.uiowa.edu/university-classroom-scheduling-regions

**Comment by makurj** [comment]
I added it to the "Additional Information" block in the [mockup](https://sandbox.prod.drupal.uiowa.edu/art-building-west-240). Planning to work on getting that hooked up.

**Comment by briand44** [comment]
@makurj The accessibility info is something that is missing from the content type. This is something Classrooms folks will manually enter similar to tile details, design details and furniture. If that field can squeeze in as part of this issue, that would be awesome!

**Comment by makurj** [comment]
Good to know. I meant the "Scheduling region" in my comment above though. Will see what can be done with the accessibility features.

**Comment by briand44** [comment]
Understood, just heard back from Classrooms about the accessibility stuff right after you posted about the scheduling region so wanted to share that info.

**Comment by bspeare** [comment]
@briand44 should we add an `University Classroom Technology Guide link` field to the content type?  It looks like we might have missed adding that field.

**Comment by bspeare** [comment]
It looks like the Guide link is just a static link to https://teach.uiowa.edu/basic-university-classroom-guide from  https://classrooms.uiowa.edu/cb-w228.   Do we need to reach out to the classrooms folks and ask about this?
