### ISSUE TITLE
Classroom Schedule for room

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6045]
# Story

As a classrooms website owner, I would like to see the room schedule for today when viewing a particular room so that visitors can see what is happening.

# Additional Info

Mockup - https://sandbox.prod.drupal.uiowa.edu/art-building-west-240

It sounds like this needs ported over from D7 uiowa_maui module.

There was talk of potentially expanding on this in the future and possibly showing the schedule for additional days as well.

From Joe:
> For the room schedule, we will want this to be JS or we need to cache bust a block similar to the time hourly cache tag used by UI Events block.

Include the design of this schedule as part of this slice.

# Proposed Solution

**Comment by joewhitsitt** [comment]
Moved from https://github.com/uiowa/uiowa/issues/6044

>See getRoomSchedule in docroot/modules/custom/uiowa_maui/src/MauiApi.php for what is needed to call and get the information. Historically, we have made a block plugin to place and render this information and the caching will have to be hourly on it (similar to the sitenow_events block) so that the information can change daily.

**Comment by makurj** [comment]
Would the block be similar to docroot/sites/classrooms.uiowa.edu/modules/classrooms_core/src/Plugin/Block/AdditionalInfoButtons.php? Also, if I try to hit something like https://api.maui.uiowa.edu/maui/api/pub/registrar/courses/AstraRoomSchedule/abw/110, I get a 404. Is that expected?

**Comment by joewhitsitt** [comment]
Probably more similar to the build() in docroot/modules/custom/uiowa_maui/src/Plugin/Block/AcademicDatesBlock.php

https://api.maui.uiowa.edu/maui/api/pub/registrar/courses/AstraRoomSchedule/2023-01-17/2023-01-17/abw/240


Also note, I mentioned sitenow_events block (sitenow_events_preprocess_block) for caching:
>caching will have to be hourly on it (similar to the sitenow_events block) so that the information can change daily.

```
// Set custom time-based cache tag to clear on a regular basis.
      $variables['#cache']['tags'][] = 'time:hourly';
      $variables['#cache']['max-age'] = 60;
```

**Comment by joewhitsitt** [comment]
@makurj are you working off of https://github.com/uiowa/uiowa/pull/6082 or main with the hope the PR will be merged soon?

**Comment by makurj** [comment]
Been going off of main with the hope that #6082 will be merged in soon. I'm adding to some of the same files and I'm worried there may be conflicts, and also having had that PR done would have been better visually when building this out. No worries though, I'm going to continue working on it. Thanks for the caching info.

**Comment by bspeare** [comment]
We will need to address https://github.com/uiowa/uiowa/issues/6044#issuecomment-1387738350 in this work as well.

**Comment by briand44** [comment]
>We will need to address https://github.com/uiowa/uiowa/issues/6044#issuecomment-1387738350 in this work as well.

Got some clarification here. For the majority of classrooms it will be a static link to https://teach.uiowa.edu/basic-university-classroom-guide but some classrooms with more specialized equipment it links to a page specific to that room (e.g. https://classrooms.uiowa.edu/mh-aud links to https://teach.uiowa.edu/macbride-hall-201-macbride-auditorium-mh-201-mac-aud-classroom-guide).

**Comment by makurj** [comment]
^^ From planning, more conversation needed on how to tackle this part.

**Comment by bspeare** [comment]
Do we just want set up a link field with a default value https://teach.uiowa.edu/basic-university-classroom-guide and allow users to change that?

**Comment by makurj** [comment]
That works for me.

**Comment by makurj** [comment]
Will this be a required field?

**Comment by bspeare** [comment]
It probably doesn't need to be required if it has a default value.
