### ISSUE TITLE
UI Press - Figure out solution to allow for linking book cover images in the Feature Books section of the homepage

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#6070]
# Motivation

In the Featured Books section of https://uipress.uiowa.edu/, the book cover images are not linked. On their D7 site, they were linked. We launched without this with the understanding that it would be fixed eventually.

# Proposed solution

Developers choice! Here are some options you could choose:
- Add an image format option to view an un-cropped image in the card block.
- Add an image format option to view an un-cropped image in the image block.
- Fix the WYSIWYG bug that prevents linking an image.

**Comment by briand44** [comment]
A couple approaches I heard in grooming was using a card and having an image style that would work for the book cover. Fixing the linking of images in WYSIWYG. Use block quote.

**Comment by pyrello** [comment]
Updated the proposed solution.

**Comment by bspeare** [comment]
> Fix the WYSIWYG bug that prevents linking an image.

Is there a bug?  I was able to update the images on uipress to link to another node.

**Comment by bspeare** [comment]
I've updated all the links on https://uipress.uiowa.edu/, and I'm going to look into updating the image block to use a non-cropped image as an option for the solution.   @pyrello reminded me that https://github.com/uiowa/uiowa/issues/3167 is the reason why linking images through the WYSIWYG is not ideal.

**Comment by pyrello** [comment]
@maramcconnell FYI, you should be good to report to UI Press that we have addressed linking the images on UI Press.
