### ISSUE TITLE
IISC - Investigate fixing publish dates on migrated content

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#6071]
# Motivation

When we migrated content for IISC, it appears that the published date was set to the date/time that the item was migrated. They would like to be able to have projects listed in reverse chronological order by the published date, but this isn't possible because those dates are all wrong.

# Proposed solution

The custom migration module for that site is still turned on. This means that we still have migration mapping tables that we can reference as well as the connection information to connect to the D7 database. I think the easiest thing to do would be write an update hook that goes through all the project nodes that were migrated, look up the original node published date, then update the current node record's publish date. I think this could all be accomplished via the database layer instead of needing to load nodes and save them. It might require a batching mechanism because I think the nodes would need to be looked up one at a time because of the data being stored in multiple databases and I'm not sure it would wise to run a query with a WHERE IN clause that passed in several hundred node IDs.

**Comment by briand44** [comment]
Potentially see if we can handle this through the existing migration by just running a migration update. If not possibly an update hook.

**Comment by briand44** [comment]
Grooming conversation..... Probe into understanding if/how this can be handled through the migration or if an update hook is necessary.

**Comment by cory-skeers** [comment]
There might be more digging needed for this, but there are some issues related to created/changed: https://www.drupal.org/project/migrate_tools/issues/3280140 (running a migration update is setting the changed timestamp to now, even if the update is supposed to map the changed field). And at Core, https://www.drupal.org/project/drupal/issues/2329253 (any change to a node changes the `changed` timestamp to now, even if the change was to the `changed` timestamp).

These don't seem to directly impact the `created`, so I think we should still be in the clear here, but if there are issues, these might serve as a good starting point when debugging.

**Comment by bspeare** [comment]
Taking a look at this.

**Comment by bspeare** [comment]
I'm not able to find examples of the migrated published dates on iisc.uiowa.edu.    I've reached out to Travis at iisc to see if he can provide some links.

**Comment by cory-skeers** [comment]
> I'm not able to find examples of the migrated published dates on iisc.uiowa.edu. I've reached out to Travis at iisc to see if he can provide some links.

Poking at a few projects, I'm seeing created dates for 2016 and 2017, which seems like they . Do we just need to update the sort for the view on https://iisc.uiowa.edu/projects? Right now it's sorting alphabetical by title first, and then created date.

**Comment by bspeare** [comment]
@cory-skeers that was my thought as well but I wanted to check with Travis to make sure that we aren't missing anything.

**Comment by joewhitsitt** [comment]
there was an academic year taxonomy on the old site. was that recreated on the new site?

the old projects "utility" view was sorted by academic year then by title. taxonomy term displays were probably just chronological based on created date.

**Comment by cory-skeers** [comment]
> there was an academic year taxonomy on the old site. was that recreated on the new site?

There's an extra field on the project with a select list for academic year that looks like it was set from the old taxonomy term in the migration.

**Comment by bspeare** [comment]
Response from Travis:

When you go to the project page, projects appear in alphabetical order.  Same for filtering by community, department, etc.  This means very old projects can appear at the top.  Our preference would be for them to be sorted by the date created.  Is that possible?
