### ISSUE TITLE
Example page(s) to display events on performing arts

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6078]
# Story

As a "performing arts" site owner, I would like to see an example page(s) that displays events that are currently on arts.uiowa.edu so that we can better understand how we can incorporate the Arts Iowa site into the new Performing Arts site.

# Additional Info

Arts Iowa site - https://arts.uiowa.edu - also something was started at https://arts.prod.drupal.uiowa.edu
New Performing Arts site - https://performingarts.prod.drupal.uiowa.edu

Let's see if we can put together something with default functionality that will make them happy.

# Proposed Solution

**Comment by mjoneill** [comment]
Partners reached out Jan 18 and asked if this was still on our radar. I indicated it was, but that we haven't yet prioritized this work.  Likely in the next couple/few sprints.

**Comment by briand44** [comment]
It looks like there is a thread in its-web related to performing arts that could be used to follow up once we have something in place. jen-knights@uiowa.edu is another contact that should be included as well.

**Comment by bspeare** [comment]
I've been communicating with Kayla in the its-web inbox on this issue.  Their team is meeting this afternoon and will get back to us if they have any further questions.

**Comment by bspeare** [comment]
Kayla will reach out to its-web inbox if they need further assistance.  I think we can close this issue for now.
