### ISSUE TITLE
Mockups for Facilities building page

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6086]
# Story
As a developer, I can see mockups of a Facilities building page so that I have a good idea of how the fields and references will need to be displayed which will help us understand how to structure them in a way that Facilities will be happy with.

# Additional Info
https://www.facilities.uiowa.edu/building/0003 is an example of an existing building.

**Space Information**
Building number
Building name
Building address
Building abbreviation
Gross square foot
Year built
Ownership

**Contact Information**
Primary building coordinator
Alternate building coordinators

**Project Information**

**Artwork**

**Links**
Keep links but more visibility - Accessibility Map, Lactation Rooms, Hearing Loop Systems, Gender Inclusive Restrooms - Hearing Loop and Gender Inclusive Restrooms likely will have new links.

**Photo**
- from data feed - no need to override

**Map**
 - want to use Concept 3D map but need to discuss how to handle this.

**Named Building**
e.g [Adler, Philip D.](https://www.facilities.uiowa.edu/named-building/philip-d.-adler-journalism-and-mass-communication-building)

**Accessibility Info**
There will likely be some accessibility info that needs to appear on building pages as well but I don't have an example of what that information will consist of at this point. It sounds like this should be available in the BizHub API 4/3/23.

# Proposed Solution

Mockup: https://sandbox.prod.drupal.uiowa.edu/chemistry-building-mockup

**Comment by briand44** [comment]
Add grooming label again to discuss slicing smaller and if we feel mockups are helpful/useful/necessary

**Comment by joewhitsitt** [comment]
from grooming: @bspeare suggested that inspiration can be drawn from the recent classrooms work which includes a lot of similar information

**Comment by briand44** [comment]
Grooming convo... Brian to ask about a building that has all of the accessibility info.

**Comment by makurj** [comment]
Wondering if "Space Information" should be "Building Information" and then I can remove "building" from name, address and abbreviation. The URL is also "building" not "space".

![image](https://user-images.githubusercontent.com/52135878/229174976-a3994912-ccb2-436c-b1be-970cb95ca5fa.png)

**Comment by makurj** [comment]
Will we have "Aerial View of Building" for all buildings or just named buildings or none?

http://maps.facilities.uiowa.edu/php/ipa.php?lat=41.660614&lon=-91.538824&ori=s
![image](https://user-images.githubusercontent.com/52135878/229175475-b59695fa-4353-4788-80bc-e2e10f746402.png)

**Comment by makurj** [comment]
A mockup is taking shape: https://sandbox.prod.drupal.uiowa.edu/chemistry-building-mockup. Thanks @bspeare for your ideas and feedback!

**Comment by makurj** [comment]
Is this something we will have a checkbox for, and then programmatically display it based on the selection?

![image](https://user-images.githubusercontent.com/52135878/229522226-c6da9d07-5871-48e0-bfca-f88cd8097fe0.png)

**Comment by joewhitsitt** [comment]
>Aerial View of Building

Do you know of an example where it is on the building page currently? Named building content has already been accounted for.

>Artwork Status

That is a separate content type that is pulled in by a building reference.

**Comment by makurj** [comment]
Don't have a regular building with the aerial view example right now. I only asked because "named building" was mentioned in the issue description above.

**Comment by joewhitsitt** [comment]
Yeah the current building pages have a link to the named building content where that information is already captured

**Comment by briand44** [comment]
Some thoughts....

Top Image - I originally thought this image was an image of the building but now realizing it is not. Would it be better if we just had a background pattern? I believe they mentioned they were trying to get better and larger building photos but I don't think they have done that yet.

Named Building Info - I'm not sure we need to output all of this info here since we already have pages for named buildings. Linking from the building to the named building page is a requirement though.

Accessibility Information - They previously mentioned they wanted these links more visible. We may want to consider displaying these higher up the page. Also, there is now some accessibility information available to us in the Bizhub api (https://bizhub.facilities.uiowa.edu/bizhub/ext/building?bldgnumber=0003). We will want to account for this information in the mockup ("singleUserRestroomsMen","singleUserRestroomsWomen","multiUserRestroomsMen","multiUserRestroomsWomen","singleUserRestrooms","lactationRooms")

**Comment by makurj** [comment]
Top image: replaced it with a gray background.
Named building info: Removed that section. The link is already there in description area.

![image](https://user-images.githubusercontent.com/52135878/229622817-5b721189-92cc-4d00-93d1-ad76408f89a8.png)

Accessibility Information: Moved it up higher on the page.

![image](https://user-images.githubusercontent.com/52135878/229623045-4d1a08ba-f8ea-4ea4-ab15-0f38466969dd.png)


Looking into the API values.

**Comment by makurj** [comment]
@briand44 How's this? https://sandbox.prod.drupal.uiowa.edu/chemistry-building-mockup

**Comment by bspeare** [comment]
I added an additional building that has multiple pieces of art: https://sandbox.prod.drupal.uiowa.edu/pappajohn-biomedical-discovery-building.

**Comment by makurj** [comment]
Did we switch the accessibility buttons back to the lighter ones? My last saved version has the black and gold option with bold text. Also, the art and additional info block look like they went from 50-50 to 33-66. The map is also looking more zoomed in.

**Comment by bspeare** [comment]
I forgot to mention this morning that on Friday, I:
- Added an additional page with more artwork https://sandbox.prod.drupal.uiowa.edu/pappajohn-biomedical-discovery-building
  - Switched that section to a 33-66 layout to make more room for the art and art grid. 
- Updated the map section to use our map block, we may need to adjust the zoom level. 
- Adjusted the "Accessibility Information" button row to use outlined buttons instead of gold so that they don't overpower the visual hierarchy of the page.

**Comment by briand44** [comment]
Just noticed that we aren't representing an alert on these mockups. That is my fault as I didn't include that originally. Here is an example of the current website with an alert https://www.facilities.uiowa.edu/building/0112. Also, here is the alert page https://www.facilities.uiowa.edu/alerts

**Comment by makurj** [comment]
> Just noticed that we aren't representing an alert on these mockups. That is my fault as I didn't include that originally. Here is an example of the current website with an alert https://www.facilities.uiowa.edu/building/0112. Also, here is the alert page https://www.facilities.uiowa.edu/alerts

I can work on the alert on the page. Do we also have to create the alerts page for this issue?

**Comment by briand44** [comment]
>Do we also have to create the alerts page for this issue?

No, I just added that for reference in case there was additional information there that wasn't on the building page.

**Comment by makurj** [comment]
How's this for the alert?

![image](https://user-images.githubusercontent.com/52135878/230988326-06c33dc2-c3d2-4f76-8129-2e1b4aa60016.png)

**Comment by briand44** [comment]
Would we be linking off for additional information or would the additional information show on the building like it does now?

**Comment by makurj** [comment]
Updated alert.

![image](https://user-images.githubusercontent.com/52135878/230991455-9d04c001-befb-4483-818f-01111571142b.png)

Created a separate page for alert info: https://sandbox.prod.drupal.uiowa.edu/chemistry-building-alerts

![image](https://user-images.githubusercontent.com/52135878/230991482-2342c3e4-6480-440f-9a92-c476ea50db23.png)

Thanks @bspeare!

**Comment by briand44** [comment]
So is ^^ a single alert or all alerts for that building? At this point I think linking to the specific alert is the simplest.

**Comment by makurj** [comment]
I updated the alert page to be for that specific alert: https://sandbox.prod.drupal.uiowa.edu/chemistry-building-alert-0792201

We could have an "All Alerts" page, then list buildings on it, then alerts per building.

**Comment by makurj** [comment]
@briand44 https://sandbox.prod.drupal.uiowa.edu/chemistry-building-mockup, https://sandbox.prod.drupal.uiowa.edu/pappajohn-biomedical-discovery-building

with requested changes and some design changes.

**Comment by briand44** [comment]
Thanks for the changes. The only question I have is related to the links for the accessibility resources. Are we not linking those currently in the mockups because we are not sure of where those will link to? I think wiring those links up would still be helpful for the mockup even if we expect some or all of those to change.

**Comment by makurj** [comment]
Yeah, I was not linking because they're going to change. I've added the old ones back in for mockup purposes on both pages.

**Comment by briand44** [comment]
Ok thanks! I think I have what I need to send off to Facilities. Just to make sure I am not missing anything, the main changes here are the description is gone, we reworked the accessibility area (restroom information now there, background changed, link design changed) and the map is now at the bottom?

**Comment by makurj** [comment]
Yep.

**Comment by briand44** [comment]
Sent

**Comment by briand44** [comment]
We have a conversation scheduled about displaying FM GIS map otherwise this has been approved. Going to close this and we can have a follow up related to the map work in a separate issue after that conversation.

**Comment by pyrello** [comment]
![Screenshot 2023-05-02 at 2 03 38 PM](https://user-images.githubusercontent.com/709009/235761263-618f7a96-c92c-432d-bcff-074a3a90e476.png)

I'm very late to this, but as I was looking at this while working on #5823, I had the following thoughts:
- Lactation rooms and gender neutral/inclusive restrooms are both represented in two separate places in this section.
- I think this makes it confusing about you should be looking for the relevant information about each of these topics.
- As a user, I might see one of those areas about the topic and then think that I had found all the information about it.
- Having standalone links to a map of gender neutral/inclusive restrooms and lactation rooms presents kind of an odd workflow. The assumption here is that someone ends up on this individual building page and then uses that to find these maps.
- I'd like to see the links to _more_ information next to the lists of specific resources in the building.

**Comment by bspeare** [comment]
After our meeting yesterday, I have created an alternative mockup to use the building image in the featured image: https://sandbox.prod.drupal.uiowa.edu/chemistry-building-mockup-final-wbanner-image.
