### ISSUE TITLE
Develop view and filters for Classrooms search page

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6098]
# Story

As a Classrooms website owner, I would like the ability to see all rooms and have the ability to search and filter to quickly find the room I am interested in.

# Additional Info

There is a mockup that lives at https://classrooms.prod.drupal.uiowa.edu/find-university-classroom.

**Search**
Search by title (building + room)

**Filters**
Building
Room Type
Room Features
Technology Features
Capacity
Furniture
Scheduling Region

# Proposed Solution

- [x] Build out views and filters
- [x] Theme filters and teasers

**Comment by briand44** [comment]
Should follow similar styles to events and iisc. Styles should be in scope for this issue. Teaser styling also included as part of this slice.

**Comment by joewhitsitt** [comment]
Welp. This is not what I thought it was...

![huge mistake](https://media.giphy.com/media/11BAxHG7paxJcI/giphy-downsized.gif)

**Comment by bspeare** [comment]
@joewhitsitt What did you think it was?

**Comment by joewhitsitt** [comment]
building is a config entity which is going to make search and dropdown a bit more difficult

**Comment by joewhitsitt** [comment]
Capacity (max occupancy) is a bit of a curve ball too compared to the mockup

**Comment by briand44** [comment]
>building is a config entity which is going to make search and dropdown a bit more difficult

I am hoping search can just search title since the title includes the building, correct?

**Comment by joewhitsitt** [comment]
Yeah. I originally thought the "value" was the building id and not the name. search is no longer an issue. I had to use previous workaround code for person types filter to get building as a dropdown as well. Moved from huge mistake to not as easy as I thought.

**Comment by joewhitsitt** [comment]
Running into an issue with the min/max filter not being added to the "filters" secondary thing. Last image is the lightest/best situation so far.

<img width="709" alt="Screen Shot 2023-01-24 at 11 39 31 AM" src="https://user-images.githubusercontent.com/4663676/214373238-7c98aada-b18c-4714-8445-fc106cb269a7.png">
<img width="1163" alt="Screen Shot 2023-01-24 at 11 39 49 AM" src="https://user-images.githubusercontent.com/4663676/214373240-244269eb-12d2-42ac-9804-9cc46a801a08.png">
<img width="979" alt="Screen Shot 2023-01-24 at 11 41 02 AM" src="https://user-images.githubusercontent.com/4663676/214373242-9e5d8742-4bd8-4668-8efc-16d4db6a4bd4.png">
<img width="668" alt="Screen Shot 2023-01-24 at 12 05 58 PM" src="https://user-images.githubusercontent.com/4663676/214373243-30a02b88-a291-4eca-9754-36d42576ad55.png">

**Comment by bspeare** [comment]
With the amount of filters turning out to be larger than expected in the mockup, should we switch this to a:
- Sidebar filter like https://housing.uiowa.edu/residence-halls?
- Sidebar filter like https://admissions.uiowa.edu/areas-of-study?
- Exposed search at the top of the content with Sidebar filter block?

**Comment by joewhitsitt** [comment]
I'd be okay with a sidebar. That would probably solve the filter grouping issue. Do we have general styling in place for those or would it be site specific css?

**Comment by bspeare** [comment]
I think we could just tweak the existing bef styles for sidebar implementation so that it looks like:

<img width="405" alt="Screen Shot 2023-01-24 at 4 30 36 PM" src="https://user-images.githubusercontent.com/1036433/214435736-cff80099-57c3-46f6-83a1-21598ff2201f.png">

Let me know if you'd like help with that!

**Comment by joewhitsitt** [comment]
@bspeare if you have capacity for that, I won't refuse your help. I am working in classrooms_core.module currently.

**Comment by bspeare** [comment]
@joewhitsitt sounds good.  I'll add something to the pr tomorrow morning.

**Comment by joewhitsitt** [comment]
Talking with @briand44, removing the room type link on the card for now and setting rabbit hole for the vocabs. Brian mentioned that maybe the room type "button" on the full node should link to /types-university-classrooms

**Comment by joewhitsitt** [comment]
Looks like they are already setup with rabbit hole (access denied) except for Units. I forget, is units supposed to be linked and contain contact info or should it be access denied as well? The building link is actually not shown to anonymous visitors because it links to the config entity edit page?

**Comment by joewhitsitt** [comment]
Captured some todos over on https://github.com/uiowa/uiowa/pull/6122 based on these findings. There were contact info fields on the unit. Moving forward with keeping that visible and updating the rest.

**Comment by briand44** [comment]
Units will be linked to and they will manually populate the additional content for units.
