### ISSUE TITLE
Deprovision midwestdnarepair.centerforconferences.uiowa.edu on uiowa

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6109]
This site is a v2 site and has been replaced with a v3 site at https://midwestdnarepair.conference.uiowa.edu. https://midwestdnarepair.centerforconferences.uiowa.edu now points to Vulture and redirects to the V3 site. There is no need for the v2 site on our platform anymore.

**Make sure we deprovision the v2 site on uiowa and not the v3 site, we also do not want hostmaster to reclaim the CNAME since it is needed for the redirect**

**Comment by joewhitsitt** [comment]
>do not want hostmaster to reclaim the CNAME since it is needed for the redirect

noted. thanks for spelling it out.
