### ISSUE TITLE
Move json feeds to grad.uiowa.edu production site

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#6124]
This can be handled by downloading the JSON files from https://grad.prod.drupal.uiowa.edu and adding them as files on https://grad.uiowa.edu. Instructions have been communicated to the Grad web team.

**Comment by maramcconnell** [comment]
This has been done.

**Comment by arjenkin** [comment]
Just want to make sure the site at grad.prod.drupal.uiowa.edu remains up until I get a chance to change our links on the workflow forms to point to the files on grad.uiowa.edu.  Is there a timeline that exists for shutting down grad.prod.dupal.uiowa.edu?

**Comment by pyrello** [comment]
> Just want to make sure the site at grad.prod.drupal.uiowa.edu remains up until I get a chance to change our links on the workflow forms to point to the files on grad.uiowa.edu. Is there a timeline that exists for shutting down grad.prod.dupal.uiowa.edu?

This is the issue to track that: https://github.com/uiowa/uiowa/issues/6119. It is currently in the backlog, so no planned timeframe for it. This issue was one of the issues blocking it, but there are several others related to other sites that we'll need to handle before we plan that task. So I think you have plenty of time.
