### ISSUE TITLE
UI Press - Export rights and permissions webform submissions for D7 site.

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#6127]

**Comment by pyrello** [comment]
Blocker for #6119

**Comment by joewhitsitt** [comment]
From grooming I was only going to ask what role should have these permissions? Additionally, is there concern about non-authors of the form having access to the results (this is an issue on ITS website)

**Comment by pyrello** [comment]
> From grooming I was only going to ask what role should have these permissions? Additionally, is there concern about non-authors of the form having access to the results (this is an issue on ITS website)

I'm not sure I understand your questions. I'm assuming that we are going to export this into a spreadsheet somehow and deliver it to the site owner. 

Also, here is a link to the form for reference: https://uipress.prod.drupal.uiowa.edu/contact/rights-and-permissions-request

**Comment by joewhitsitt** [comment]
Sorry, I misunderstood. From the title it sounds like "UI Press - {Give} export rights and permissions {for} webform submissions for d7 site."

**Comment by briand44** [comment]
This is no longer relevant. The D7 site no longer exists.
