### ISSUE TITLE
Deprovision gencousel.uiowa.edu on 703

### ISSUE THREAD

**Issue by makurj** [uiowa/uiowa#6129]
Deprovision gencousel.uiowa.edu on 703

**Comment by makurj** [comment]
1/26/23: Added the domain gencounsel.prod.drupal.uiowa.edu to 703 prod to check on GA and GTM. Neither module is enabled.

![image](https://user-images.githubusercontent.com/52135878/214907376-dbe6c0ee-575d-48d7-8a94-1288e003de3d.png)

Not removing the domain just yet, in case other data is needed. Remove during deprovision.

**Comment by briand44** [comment]
This is done
