### ISSUE TITLE
Programmed Classroom page and filters

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6131]
# Story

As a classrooms website owner, I would like to see a separate page that lists programmed classrooms so that they are not confused with University Classrooms.

# Additional Info

- We should only show rooms where the Instructional Room Category is Programmed Classroom.
- Page will be linked from the main menu under Spaces -> Find a Department Classroom.
- They would like the ability to filter by building (requires `uiowa_core_config_entity_filter_select()`).
- They would like to group the display of rooms by building, sorted alpha.
- Can use some design elements from https://sandbox.prod.drupal.uiowa.edu/university-classrooms-and-specialty-spaces if we want.
- Fields to output
    - Room number
    - Building
    - Capacity
    - Seating Type
    - Room Name
    - Responsible Unit.
- Will link to room node.

**Comment by briand44** [comment]
Blocked until we get the fields that should be output. We should get this tomorrow.

**Comment by bspeare** [comment]
I'm going to see if I can pick this up today.

**Comment by e-marie-w** [comment]
To Do:
- [ ] Output seating type (currently part of features list and not its own field)
- [ ] Update display of existing room view block and the new programmed classrooms view block (I have been trying to do styling in the preprocess function but you could use the template instead)
- [ ] Fix fields displaying even when empty on the blocks (probably related to my messy styling in the preprocess function)

Not necessarily needed but would nice:
- [ ] Refactor blocks code (right now the two blocks have a lot of shared code that could be simplified I think)
- [ ] Fix the export weirdness (export keeps trying to add permissions to the config_split.patchuser.role.* files when the permissions are already part of default. This is my bad from the people list link directly to source PR, not this work).
