### ISSUE TITLE
clicka11y.js is not retriggered on AJAX calls

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#6138]
# Problem

Discovered in https://github.com/uiowa/uiowa/pull/6122, card and banner are using docroot/themes/custom/uids_base/uids3/assets/js/click-a11y.js to implement the click on card/faux button. This works for page load when the JS is being attached to the component through libraries, but because it isn't a drupal.behaviors it isn't getting re-triggered when an ajax views filter or page is fired.

# Steps to reproduce
https://sandbox.prod.drupal.uiowa.edu/people-directory on the first block, click the pager, the card is no longer clickable besides the card title.

# Proposed solution

- One possible solution is to wrap click-a11y.js in a function that can then be called through a drupal.behavior.

<details>
<summary>click-a11y.js</summary>

```js
function triggerClickA11y() {
  const items = document.querySelectorAll('.click-container:not([data-uids-no-link])');
  const link_elements = ['.click-target'];
  const RIGHT_BUTTON_CODE = 2;

  Array.prototype.forEach.call(items, item => {
    let up, down, link, i;
    // Loop through options and break on the first match.
    for (i = 0; i < link_elements.length; i++) {
      if (link = item.querySelector(link_elements[i])) {
        break;
      }
    }

    // If we have a match, attach behaviors.

    if (!link) {
      return;
    }
    item.style.cursor = 'pointer';
    item.onmousedown = (e) => {
      if (!ignoreClick(e)) {
        down = +new Date();
      }
    }
    item.onmouseup = (e) => {
      if (!ignoreClick(e)) {
        up = +new Date();
        // Trigger click event if the duration is short enough.
        if ((up - down) < 200) {
          link.click();
        }
      }
    }
  });

  /**
   * Ignore right button and <a> or <button> clicks.
   */
  function ignoreClick(e) {
    return e.button === RIGHT_BUTTON_CODE || ['A', 'BUTTON'].indexOf(e.target.nodeName) !== -1;
  }
}

triggerClickA11y()
```
</details>

Then in a separate file also attached to the component:

```js
(function ($, Drupal) {

    "use strict";

    Drupal.behaviors.clickA11y = {
        attach: function (context, settings) {
            triggerClickA11y();
        }
    }
});
```

There might be multiple calls then that would have to be addressed.

**Comment by joewhitsitt** [comment]
Hat tip to @GaryRidgway for guiding me through why this was tripping up.

**Comment by pyrello** [comment]
I think we would ideally want to make our solution indifferent to the class being used to attach the behavior.

I think we could do this by passing an argument to the trigger function like `triggerClickA11y(selector)`. The selector argument could then be determined per implementation.

**Comment by pyrello** [comment]
I dug into this a bit and it appears that our script isn't even working in UIDS 4 at this point in time. I think it was previously, but it appears to have been broken at some point and we didn't notice.

I think this hasn't come up before because while both Fractal and Storybook both allow hot-swapping, the process entirely replaces the iframe that contains the component, so the script is reloaded as well.

I think we should fix this in UIDS 4, then incorporate those changes to UIDS Base.
