### ISSUE TITLE
Now migration - keywords are not being migrated due to typo

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#6150]
# Problem
The migrations have not been moving over keywords to tags as mentioned in https://github.com/uiowa/uiowa/issues/5887 due to a typo, however, given that keywords has 15k terms, we may have to change our approach to migrating these to reduce memory consumption.

# Steps to reproduce
Notice an absence of 15k rows: https://now.dev.drupal.uiowa.edu/admin/structure/taxonomy/manage/tags/overview
Notice 151 pages of keywords here https://now.uiowa.edu/admin/structure/taxonomy/keywords

# Proposed solution
- Try fixing the typos:
  - https://github.com/uiowa/uiowa/blob/main/docroot/sites/now.uiowa.edu/modules/now_migrate/src/Plugin/migrate/source/Achievement.php#L65
  - https://github.com/uiowa/uiowa/blob/main/docroot/sites/now.uiowa.edu/modules/now_migrate/src/Plugin/migrate/source/InTheNews.php#L122
  -  https://github.com/uiowa/uiowa/blob/main/docroot/sites/now.uiowa.edu/modules/now_migrate/src/Plugin/migrate/source/NewsFeature.php#L44

OR

- Refactor term migrations so that the migration is still able to run.

Refactoring would only be required if there are potential memory issues with holding the mapping table in memory during migration. Including all keywords, there are ~15k terms. How the migration is currently set up, and how it's run in past migrations, ALL migrated terms are held in memory in order to provide a mapping from `name => tid` in order to avoid extra queries and consolidate duplicates with existing terms.

If memory usage is a concern, we should refactor to not hold a static mapping, and instead do streaming lookups to move it to a process-intensive rather than memory-intensive process. For each tid the new process would be:

1. query the source database to get the taxonomy name
2. query the destination database for taxonomy terms matching that name
  a. if found, grab that tid
  b. if not found, create a new term, save, and get the saved term's new tid
3. add the new tid to the tids array and attach to source properties (final step in the current process as well)

Overall, the process is very similar to the steps we have now, but the destination database querying would have to be handled on an individual basis (either once per term or slightly more efficient once per node) rather than once at the start of each migration run.

**Comment by joewhitsitt** [comment]
Maybe it is worth confirming with the customer one more time that keywords should be brought over before work is started on this.

**Comment by cory-skeers** [comment]
Taking a look at an example migration during some of the work in #6167, to hopefully get a sense of whether it's just a typo or if refactoring is needed for memory.
