### ISSUE TITLE
Unable to center table header row

### ISSUE THREAD

**Issue by makurj** [uiowa/uiowa#6170]
Unable to center the table header row content even though "text-align-center" class is used. Using center alignment from the WYSIWYG doesn't work either. See example here: https://tippie.uiowa.edu/node/5876/layout

![image](https://user-images.githubusercontent.com/52135878/217355364-b4112405-58d2-4f3c-a44f-3c8daf6dd686.png)
![image](https://user-images.githubusercontent.com/52135878/217355389-b5906e3c-3f9d-4240-8ca5-b48f867e4da9.png)

**Comment by bspeare** [comment]
@makurj it looks like you can center the `<th>`, just update the markup with `<th align="center" scope="col">Amet</th>`.  Knowing that, can we close this issue?

**Comment by makurj** [comment]
Great and easy solution! Thanks @bspeare!
