### ISSUE TITLE
Large menu page not loading/changes not saving

### ISSUE THREAD

**Issue by makurj** [uiowa/uiowa#6176]
Response from Acquia:
  https://support-acquia.force.com/s/article/360004542293-Conditionally-increasing-memory-limits
  https://docs.acquia.com/cloud-platform/manage/php/#php-mem

Refer to: 
https://github.com/uiowa/uiowa/issues/1996
https://github.com/uiowa/uiowa/issues/1996#issuecomment-1424305613
https://github.com/uiowa/uiowa/issues/1996#issuecomment-1424415304

**Comment by makurj** [comment]
@cory-skeers @joewhitsitt Do we want to increase the limit for all /admin paths or just the menu ones?

> Would we want to get more specific, and just apply it to the menu page(s) if the rest of admin pages are okay?

**Comment by joewhitsitt** [comment]
I'd like to see if we can limit it to /admin/structure/menu paths. AFAIK, most of our other backend pages are as of now working. In d7, the full permissions list became a problem but we should only be working with that page locally where the memory limit is more out of the box.

**Comment by cory-skeers** [comment]
> @cory-skeers @joewhitsitt Do we want to increase the limit for all /admin paths or just the menu ones?
> 
> > Would we want to get more specific, and just apply it to the menu page(s) if the rest of admin pages are okay?

My inclination would be to limit it to just the menu ones as it's the only known problem, and expand from there in the future if needed.

**Comment by makurj** [comment]
With DDEV lowered to 128 and the code in Engineering's settings.php, I was able to edit the menu and save changes as a webmaster.

`if (isset($_SERVER['REQUEST_URI']) && strpos($_SERVER['REQUEST_URI'], 'admin/structure/menu') !== false ) {
  ini_set('memory_limit', '256M');
}`

Looking for a non-manual way to add the code above to all sites' settings.php file.

**Comment by joewhitsitt** [comment]
Mentioned in Slack that this might be more simple. A one file change docroot/sites/settings/global.settings.php (included per site via blt.settings.php)
