### ISSUE TITLE
Migrate remaining classroom room data from existing D7 site

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6179]
# Story

As a Classrooms website owner, I would like existing University Classroom rooms migrated from our existing D7 website so that we do not have to manually transition all of the manually controlled content.

# Additional Info

We only need to migrate University Classrooms (from classrooms.uiowa.edu) and not Programmed Classrooms (registrar.uiowa.edu). Programmed Classrooms will be manually created by Classrooms team by entering Building and room number as all the rest of the content comes from MAUI.

https://github.com/uiowa/uiowa/issues/6279 was created to address migrating the Building and room id.

**Fields**
- Building -> Building - I believe the D9 select list has a key of building code so hopefully we don't need some lookup or something tomigrate building code to building name
- Room ID -> Number
- Image Gallery -> Images - multiple
- Accessibility -> Don't need to map because this field didn't previously exist
- Tile Details -> Tile Details - combine name and details field collection items into string - multiple values
- Design Details -> Design Details - combine name and detail field collection items into string - multiple values
- Furniture -> Classroom Furniture - combine type and details field collection items into string - multiple values
- Body -> Don't need to map because this field didn't previously exist - Can this go away?
- Technology Guide -> Link - The source field allows multiple, the destination does not. If there are instances with multiple values, we may need to adjust the destination field. (`field_room_link`)
- Seating Chart -> Seating Chart
- Video -> Video
- Map -> lets not do anything with this. We can ask our Classroom partners to manually add these.

# Proposed Solution

- [x] #6279
- [x] Second slice - add additional fields to migration

Additionally:
> we either need to account for redirects or
update the destination's path alias to match. Customer input is probably needed for
this.

**Comment by cory-skeers** [comment]
> * Technology Guide -> Link - The source field allows multiple, the destination does not. If there are instances with multiple values, we may need to adjust the destination field.

Checked the database, and it looks like there aren't currently any instances of multiple values. Should double-check at runtime because the field allows multiple, but we should be good there.

**Comment by joewhitsitt** [comment]
Rick previously investigated creating a static mapping of abbrev. to markerid: https://github.com/uiowa/uiowa/issues/4591#issuecomment-1005216374

**Comment by briand44** [comment]
adding grooming label to see if we can split

**Comment by briand44** [comment]
are we only migrating published rooms? I will ask.

**Comment by briand44** [comment]
>are we only migrating published rooms? I will ask.

Yep, only published

**Comment by cory-skeers** [comment]
A note re: the Seating Chart. The source site has a "display" option, but as of 2023/04/11, every chart is listed to display, so it is not accounted for in the migration (setting all to display).

**Comment by cory-skeers** [comment]
Looks like there aren't currently any videos on the source. It's in the migration YAML, but would need additional processing if there are videos available at the time of the migration. Otherwise, having it in the definition with no content doesn't hurt anything.

**Comment by cory-skeers** [comment]
@briand44 Do you happen to know if/how we should account for the difference in auto-created aliases?

For example, https://classrooms.uiowa.edu/ajb-e105 becomes https://classrooms.uiowa.edu/adler-journalism-building-e105. We can do a redirect migration like we usually do for articles, or adjust the alias itself (we have mappings for the building abbreviation, so it should be pretty straightforward to set this, but it'd also require removing the "Generate automatic URL alias" option on the migrated nodes).

**Comment by briand44** [comment]
I have an email out to Classroom folks to get an answer on ^^

**Comment by joewhitsitt** [comment]
FWIW `[node:field_room_building_id:target_id]-[node:field_room_room_id]` pattern for room should keep it the way they have it.

**Comment by briand44** [comment]
If we think it is as easy as ^^ and won't require additional refactoring anywhere, we can go that route, I don't have strong feelings either way just trying to make a quick decision that our partners can live with and that doesn't make a lot of additional work for us.

**Comment by joewhitsitt** [comment]
there currently isn't a pattern for this. so it would involve setting the pattern and adding it to the site split

**Comment by briand44** [comment]
starting to think that setting the pattern and keeping the paths the same seems like the best path forward

**Comment by briand44** [comment]
Let's go with ^^. They will be happy and urls won't change. If any issues arise we can deal with them or adapt. Thanks for chatting through it.

**Comment by briand44** [comment]
There are about a dozen rooms already created on the new site. Not sure if those are new or if there will be dupes after migration. The reason I bring those up though is because I assume those will need re-saved if they are staying around so that they will get the updated alias pattern once that gets to prod?
