### ISSUE TITLE
Classroom room scheduled update

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6180]
# Story

As a Classrooms website owner, I would like our room information to update daily from MAUI so that our users are getting up to date information that doesn't require us to manually save all rooms. 

# Additional Information

Need to setup periodic import via node_save. Ideally, it would be adjusted to check for a diff before running the full save. I believe the facilities building import process does this check. Once a day should be sufficient.

# Proposed Solution

- [x] Move presave processing to a separate process that can get called separately from a save trigger
- [x] Write a drush command to process and update all rooms; do not double up in presave check

**Comment by briand44** [comment]
Grooming Conversaton... Scheduled job in AC to trigger a drush command, run node save if changes.

**Comment by joewhitsitt** [comment]
For inspiration (drush command that checks for changes before saving the node) docroot/sites/facilities.uiowa.edu/modules/facilities_core/src/Commands/FacilitiesCoreCommands.php
