### ISSUE TITLE
3-column articles list block overflow

### ISSUE THREAD

**Issue by makurj** [uiowa/uiowa#6182]
At smaller breakpoints, some text is overflowing for the 3-column grid for articles list block:
![image](https://user-images.githubusercontent.com/52135878/218518522-1098f26b-5df4-4675-8a8c-808bd1f969b8.png)

One column section with normal container and:
![image](https://user-images.githubusercontent.com/52135878/218518710-eac4dde0-6c1f-4293-a2ae-76b28f8cc339.png)

Reference:
https://github.com/uiowa/uiowa/issues/4678
https://github.com/uiowa/uiowa/pull/6159#issuecomment-1428248544

**Comment by bspeare** [comment]
I'm going to close this in favor of https://github.com/uiowa/uiowa/issues/4678.
