### ISSUE TITLE
Content/Design Changes for Iowa Now - Part 3

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6184]
- [x] Separate Grant Awards Intake Form from contact form since there are specific fields for the intake form https://now.uiowa.edu/grant-awards-intake-form
- [x] Combine the submit news (https://now.prod.drupal.uiowa.edu/contact) and submissions pages (https://now.prod.drupal.uiowa.edu/submissions). 
- [x] Be consistent in pointing folks to contact page vs saying email now@uiowa.edu.
- [x] Make sure site email and webforms are setup to email now@uiowa.edu
- [x] Make sure Share your news call to actions are linking to the combines submissions page and not just the webform.
- [x] Add content about City of Iowa City to Around Campus page - Tricia can provide content
- [x] Possibly add something related to work/life balance - worklife.uiowa.edu on Around Campus page
- [x] Update Topics in main navigation once Iowa Now partners provide the appropriate topics.

**Comment by mkyoder** [comment]
- [X] Combined Grant Awards Form and Share Your News Form here: https://now.prod.drupal.uiowa.edu/form/share-your-news and set conditional formatting. 
- [X] Combined submit news and submissions page and renamed to Submit News as that is what Jack had it called. https://now.prod.drupal.uiowa.edu/submit-news
- [X] Removed old submissions page (https://now.prod.drupal.uiowa.edu/submissions)
- [X] Removed mention of Iowa email now@uiowa.edu on Submit News page and pointed users to webform.

![Screen Shot 2023-02-14 at 11 47 47 AM](https://user-images.githubusercontent.com/107870104/218818564-72e75dc6-41af-4dff-ac9c-a4efdad76e78.png)

**Comment by mkyoder** [comment]
- [X] Changed menu url to match Jack's renaming of this page (https://now.prod.drupal.uiowa.edu/around-campus) was previously called More Sources and changed in the footer as well for consistency. 

![Screen Shot 2023-02-14 at 11 53 45 AM](https://user-images.githubusercontent.com/107870104/218818799-976539e4-fd52-4dc9-b0e8-bdb0903935e7.png)

**Comment by mkyoder** [comment]
- [X] Set up webform handler for Share Your News to go to now@uiowa.edu.

![Screen Shot 2023-02-14 at 11 57 29 AM](https://user-images.githubusercontent.com/107870104/218819217-9348572c-4683-41f6-87ea-b1096e88b513.png)

**Comment by mkyoder** [comment]
- [X] Set up site settings to go to Iowa Now email address.

![Screen Shot 2023-02-14 at 11 58 37 AM](https://user-images.githubusercontent.com/107870104/218819436-9d3e12be-2d92-49ec-864e-0b28e91b6391.png)

**Comment by mkyoder** [comment]
- [X] Share your news call to actions on https://now.prod.drupal.uiowa.edu/ and https://now.prod.drupal.uiowa.edu/about are now linking to combined submissions page at https://now.prod.drupal.uiowa.edu/submit-news (formerly Contact Us Page).

**Comment by mkyoder** [comment]
Question: Does work/life balance on this page (https://now.prod.drupal.uiowa.edu/around-campus) need to be a separate category altogether? Or could it be part of the General Information section since it is just linking to https://worklife.uiowa.edu/?

![Screen Shot 2023-02-14 at 12 07 30 PM](https://user-images.githubusercontent.com/107870104/218821175-43dd42ec-8db5-4ef2-a89b-94770edbe557.png)

**Comment by briand44** [comment]
work/life balance.... I think Tricia was going to review that website/information. Tricia still needs to provide information about the City of Iowa City for us to include on that page. When she provides that I would ask if/how she would like us to include work/life balance info as well.

**Comment by mkyoder** [comment]
Got it -- sounds good! I think that is it from my end on the content changes list above and just waiting on info for those remaining items that the Iowa Now folks need to provide.

**Comment by mkyoder** [comment]
Reached out to Tricia regarding information we need on: 

- Updated copy for achievements section
- Pointing to the webform instead of now@uiowa.edu for Iowa Now emails
- Content about Iowa City 
- Content about work/life balance

**Comment by mkyoder** [comment]
@bspeare I got this in a flexbox all by myself (I'm really proud) :) But now I have the formatting all strange here on one line. Do you need to add another flexbox for the elements I want on a separate line? How do I fix it? 

https://now.prod.drupal.uiowa.edu/submit-news

![Screenshot 2023-02-15 at 5 00 16 PM](https://user-images.githubusercontent.com/107870104/219208849-86b10ed6-adb4-438c-9b1d-376a7501fc14.png)

**Comment by mkyoder** [comment]
- [X] Be consistent in pointing folks to contact page vs saying email [now@uiowa.edu] https://now.prod.drupal.uiowa.edu/submit-news

- [X] Possibly add something related to work/life balance - worklife.uiowa.edu on Around Campus page
https://now.prod.drupal.uiowa.edu/around-campus

- [X] Add content about City of Iowa City to Around Campus page - Tricia can provide content
https://now.prod.drupal.uiowa.edu/around-campus

**Comment by mkyoder** [comment]
I’d love to get your thoughts on the layout of this page sometime @bspeare  (https://now.prod.drupal.uiowa.edu/around-campus).

Tricia attached a document with a lot of information about Iowa City and 7 stats. I only pulled out 3 of the 7 key stats she sent as I felt it might be too busy if I add all 7 stats. 

[About Iowa City.docx](https://github.com/uiowa/uiowa/files/10761817/About.Iowa.City.docx)

**Comment by bspeare** [comment]
@mkyoder it looks good!  Maybe add extra top/bottom spacing to the top of "About Iowa City" and the bottom of the accordion?

**Comment by mkyoder** [comment]
- [X] Update Topics in main navigation once Iowa Now partners provide the appropriate topics.

**Comment by mkyoder** [comment]
- [X] Moved Grant Awards checkbox to the top of the webform and added required fields for some elements so that a user cannot submit without any information.

**Comment by mkyoder** [comment]
Content changes from this list are done now. Not sure if we want to talk through these before we meet with the Iowa Now team again.

**Comment by briand44** [comment]
Closing this as we demoed the changes and feedback was positive.
