### ISSUE TITLE
Set focus on search text field when search button is clicked

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#6185]
# Story

As a site visitor I want my cursor to be focused in the search box when I click the search button so that I don't have to click into the box, which confuses me.

# Proposed solution

Add JS to set focus on the click event.

**Comment by bspeare** [comment]
@pyrello is this a duplicate of https://github.com/uiowa/uiowa/issues/5372?

**Comment by pyrello** [comment]
It is. I did search for existing issues, but did not see this.
