### ISSUE TITLE
News articles on services

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6190]
# Story

As an ITS website owner, I would like to have the ability to relate a news article to one or more infocenters/services and display those articles on the service page so that we can showcase recent news about our services. 

# Additional Information
They are going to start fresh with news and not migrate any news articles from their existing website.
They no longer need audience specific tagging with news.
Joe mentioned using point of contact field for infocenter relationship??

# Proposed solution

- Add ability to reference a service from news article (new field or contact field)
- output news article on service [as designed in mockup] https://sandbox.prod.drupal.uiowa.edu/its-service-office-365-mockup
- output service on news article

**Comment by joewhitsitt** [comment]
Clarification: similar to Iowa Now and their contact content type, the point of contact field can be split to include the info center content type once it exists.

**Comment by briand44** [comment]
Grooming conversation... Currently have list of checkboxes to reference. Joe suggested ^^ as a possible smaller split option. Looks like they are outputting the references service on the article as well. We should see if they still desire that. We may want to understand if they would be ok with the way point of contact would output before pursuing that path.

**Comment by briand44** [comment]
I reached out to Adrienne to see if they would still like to output the service as a link on the article and ideally yes, she would like that. She was ok with outputting that info similar to how the point of contact information gets output but the label would need to change.

**Comment by briand44** [comment]
Learned today that they don't think they will use the contact reference field to reference people.

**Comment by GaryRidgway** [comment]
As I am working on this, small things are popping up where a field will need a class, or a style will need to be applied, or things of this sort. To me if services ever have the possibility of being something for the entire sitenow service, shouldn't there be a module for them to go with the split?

**Comment by joewhitsitt** [comment]
>To me if services ever have the possibility of being something for the entire sitenow service, shouldn't there be a module for them to go with the split?

We decided that for ITS, services was custom enough not to build it as a feature for all. `its_core` already exists as part of the site split and that should go there.

**Comment by GaryRidgway** [comment]
> We decided that for ITS, services was custom enough not to build it as a feature for all. `its_core` already exists as part of the site split and that should go there.

Okay, that's fine then, I guess we could always refactor later if it seems necessary.
