### ISSUE TITLE
Add mediowa application to metadata generator

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6192]
# Story

As a UIHC MarCom developer, I would like to integrate SSO on the medicineiowa.org website so that users authenticating to the website can log in with their HawkID similar to other campus D9 Drupal websites.

# Additional Information

This is for the mediowa application.

We need to add the application to the metadata generator.
https://git.uiowa.edu/its-web/data.its.uiowa.edu/-/blob/main/app/Http/Controllers/ShibbolethController.php

# Proposed solution

- [x] Add application to metadata generator
- [x] Deploy
- [x] Communicate with Sean Davis that this is done

**Comment by joewhitsitt** [comment]
Going to do this as part of the data.its working session.

**Comment by joewhitsitt** [comment]
This was merged and deployed: https://git.uiowa.edu/its-web/data.its.uiowa.edu/-/merge_requests/81
