### ISSUE TITLE
Support ICGov and MPOJC new site launches

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6195]
# Story

As owners of ICGov and MPOJC, we would appreciate your support as we transition these websites to a new platform so that we make sure everything goes smoothly and we still have a way to access our old sites for a period of time after our new sites launch.

# Additional Information

Plan is to launch March 30th
They would like to keep their sites available after launch for six months. I let them know we would check in with them after three months.
The plan will be to use the stage environment to make these sites available after launch. stg.icgov.org and stg.mpojc.org will continue to point to Acquia.
We will want to sync the production environments (db, files) to stage a day or two prior to launch so they have the up to date content.
We will likely need to make sure the stage sites are not being indexed by Google after the syncs.

Not sure what else we will need to be involved in at this point.

# Proposed solution

- [x] Sync prod icgov db and files to stage
- [x] Sync prod mpojc db and files to stage
- [x] Make sure stage sites are not being indexed
- [x] Create a reminder to check in with icgov folks in 3 months
- [x] Share the stage url's with our icgov contact
- [ ] anything else?
- [ ] 🍻

**Comment by briand44** [comment]
Marking this as blocked because we want to wait until closer to launch. Let's plan to do this on March 29th.

**Comment by briand44** [comment]
Grooming conversation... make sure private files are synced as well. Not sure if this happens via Cloud drag and drop maybe need to rsync?

**Comment by joewhitsitt** [comment]
Followed https://acquia.my.site.com/s/article/360009608553-How-to-prevent-crawling-of-non-public-ACSF-domains to add to master to prevent crawling. May need help to construct something similar for stg.icgov and stg.mpojc

**Comment by joewhitsitt** [comment]
Brian suggested last night that we just override the original robots.txt once they go live and push it to prod

**Comment by joewhitsitt** [comment]
Created `update-robots-post-launch` feature branch to remove the stuff I did yesterday in favor of an updated robots.txt that is gutted except for the following:

```
#
# robots.txt
#
# This file is to prevent the crawling and indexing of certain parts
# of your site by web crawlers and spiders run by sites like Yahoo!
# and Google. By telling these "robots" where not to go on your site,
# you save bandwidth and server resources.
#
# This file will be ignored unless it is at the root of your host:
# Used:    http://example.com/robots.txt
# Ignored: http://example.com/site/robots.txt
#
# For more information about the robots.txt standard, see:
# http://www.robotstxt.org/robotstxt.html

User-agent: *
Disallow: /
```

**Comment by joewhitsitt** [comment]
Brian said this can move to stage (merge into master and deployed to stage)

Update: This is done. All three stage domains are showing the disallow.

**Comment by joewhitsitt** [comment]
Propagation aside, they have launched. I have deployed the robots txt change to PROD.

**Comment by briand44** [comment]
Closing this as there is nothing else we are aware of that we need to address.
