### ISSUE TITLE
Remove/Update Iowa Now news feeds on Hawktools

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6196]
# Story

As an owner of the Hawktools website, I would like to avoid breaking changes to our site when the Iowa Now website goes live.

# Additional Info 

This is a follow up issue from https://github.com/uiowa/uiowa/issues/6093

Module exists at the following path:
`uiowa701-dev/docroot/sites/hawktools.uiowa.edu/modules/custom/hawtools_iowanow`

For reference here is an example of the API: https://now.uiowa.edu/api/v2/news-for/faculty (xml with specific non-spec RSS output)

Example pages:
https://hawktools.uiowa.edu/staff
https://hawktools.uiowa.edu/faculty
https://hawktools.uiowa.edu/students

# Questions
What should we do here?
- Update this to work with the new site?
- Remove this feature and place content that links out to Iowa Now
- Other thoughts/ideas?

# Proposed solution

**Comment by briand44** [comment]
Plan on linking out to the Iowa Now homepage for each audience.

**Comment by joewhitsitt** [comment]
If we get push back on just linking out, I believe I still have an old careers_handshake widget that is basically a RSS panel pane widget that could be lifted and repurposed to display rss titles.

**Comment by e-marie-w** [comment]
I'd be interested in pairing on this.

**Comment by joewhitsitt** [comment]
i can help knock it out after grooming

**Comment by joewhitsitt** [comment]
This is what we came up with for now:

<img width="896" alt="Screenshot 2023-04-25 at 3 17 02 PM" src="https://user-images.githubusercontent.com/4663676/234393074-cbd6c4ca-be0b-471e-a7b3-3fe45e084882.png">

At the same time we removed the recserv hours (broken) and changed the order so that events showed first (more visual)

https://hawktools.uiowa.edu (check it!)

**Comment by joewhitsitt** [comment]
Closing. If it needs to be more flashy, a follow-up issue can be setup.
