### ISSUE TITLE
Update/Remove Iowa Now integration with Signage.uiowa.edu

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6197]
# Story

As an owner of signage.uiowa.edu, I would like to avoid breaking changes to the marquee when the Iowa Now website goes live.

# Additional Information

This is a follow up issue from https://github.com/uiowa/uiowa/issues/6093.

Code exists at the following path:
`/docroot/sites/signage.uiowa.edu/modules/custom/uiowa_signage/uiowa_signage.panelizer.inc`

My understanding is that when a new sign is created it defaults to having a Marquee that displays Campus News from Iowa Now via the following source https://now.uiowa.edu/taxonomy/term/18883/feed

We will want to check Healthcare Signage and address this there as well if the same feature exists there.
**Update** My quick check revealed that Healthcare Signage does not include a marquee by default when creating a new sign and if a user were to add a marquee to a sign it does not default to having a Iowa Now feed.

# Questions

What should we do here?
- Update the default source to use a source from the new site?
- Update to use a different source altogether?
- Remove having a default Marquee on signs?
- Other thoughts/ideas?

# Possible future slice

As an owner of a digital sign using a marquee with an Iowa Now feed, I would like to avoid breaking changes to my sign when the Iowa Now website goes live.

# Questions

Do we want to try to update existing signs to map feeds to a new feed url if one exists or should this just be handled through communication from Iowa Now?

# Proposed solution

**Comment by makurj** [comment]
I'm okay with removing the Iowa Now marquee by default when a new sign is created. We could try to get more info on this from users. Not sure how to get the broadest reach. its-signagecontent@list.uiowa.edu, as @joewhitsitt mentioned may not be up-to-date.

**Comment by briand44** [comment]
Grooming conversation.... Let's remove the default marquee when new signs are created. We can talk with Iowa Now folks on how they want us to handle existing signs with Iowa Now feeds. HC Signage does not need updated.

**Comment by joewhitsitt** [comment]
I can stream this work in a bit, or if someone else wants to drive and would like me to join, ping me.

update: "in a bit" has turned into "after grooming"

**Comment by joewhitsitt** [comment]
Uh. Not seeing it here (new sign)
<img width="1383" alt="Screenshot 2023-05-03 at 9 52 11 AM" src="https://user-images.githubusercontent.com/4663676/235953476-582eb5e5-058d-41a4-b9d1-8f60cf43653b.png">

Or here (panelizer defaults)
<img width="1280" alt="Screenshot 2023-05-03 at 9 53 07 AM" src="https://user-images.githubusercontent.com/4663676/235953916-e16b70f2-77d0-4598-919f-bbc1db847c15.png">

**Comment by joewhitsitt** [comment]
Did someone already do this and not update features?

<img width="1264" alt="Screenshot 2023-05-03 at 9 55 22 AM" src="https://user-images.githubusercontent.com/4663676/235954732-ca1a6edc-231b-4f69-88ec-8dc83fa857f4.png">

**Comment by joewhitsitt** [comment]
Talked with Brian. Started to understand why some of these changes happened. Group logo might have been removed from the defaults for UI brand reasons. Without it there, the date/time takes up space and the display title is optional on the right.

There might have also been complaints that there was a lot of default stuff to remove in setting up new signs.

Since we haven't heard complaints, I am going to assume these were intentional changes and move forward with just repackaging the feature in the current state (without the marquee) and pushing it to PROD.

**Comment by joewhitsitt** [comment]
updated feature has been deployed to prod and is in a default state.

commit 53ac8db03ceb977ba2d54aa62b4d3232252c30da
