### ISSUE TITLE
Display Content Hub event website URL on Commencement event display

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#6199]
# Story

As a website visitor, I can see the event URL, if it exists for the commencement event displayed.

https://content.uiowa.edu/college-engineering-undergraduate-commencement-4
https://commencement.uiowa.edu/ceremony/spring-2023/college-engineering-undergraduate-commencement

# Additional information

- The website manager is currently working around this.
- Request via its-web. 2/21/2023

# Proposed solution

- Include website URL in the import/pull process and render it above the contact information as `Collegiate Website: url from content hub.`

**Comment by briand44** [comment]
I have deployed this to production. Just waiting to hear back from the customer that all is well.

**Comment by joewhitsitt** [comment]
Thanks for taking this on @briand44
