### ISSUE TITLE
Update building label in MapBox for Facilities building map

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6200]
# Story

As as a Facilities website owner, I would like the label for the Performing Arts Annex updated from Old Museum of Art to Performing Arts Annex so it accurately describes the building name.

# Additional info

Example of Facilities website:
https://www.facilities.uiowa.edu/building/0222

Docs:
https://wiki.uiowa.edu/display/sitenow/maps.uiowa.edu

# Proposed solution

**Comment by briand44** [comment]
Good pairing opportunity

**Comment by joewhitsitt** [comment]
v3 Facilities website launched. Closed as not planned
