### ISSUE TITLE
Theme setting to adjust colors to non-brand

### ISSUE THREAD

**Issue by GaryRidgway** [uiowa/uiowa#6204]
As a sitenow developer, I want to be able to change the colors of the theme by setting a theme setting. 

## Potential solution
An example of the basic idea is set here, where we replace css variables with javascript (Or PHP, if we desire, by creating an imported style element ).

What might seem most daunting is using this in conjunction with SCSS variables. A solution to this is changing the definitions of the SCSS variables as such:

From:
```
$uiowa-gold: #FFCD00
$uiowa-blue: #00A9E0
```

To:

```
:root {
  --uiowa-gold: #FFCD00;
  --uiowa-blue: #00A9E0;
}


$uiowa-gold: #{var(--uiowa-gold)};
$uiowa-blue: #{var(--uiowa-blue)};
```

`#{CONTENT}` is the way to define interpolation in SCSS. This allows it to just simply print exactly the text inside, and not try to evaluate it as some type of expression.

This way, the variables will still be cascaded to where they are currently, and additionally, changing them in `:root{}` will thus cascade as well.

**Comment by joewhitsitt** [comment]
Should work continue in https://github.com/uiowa/uiowa/pull/5085?

**Comment by bspeare** [comment]
Are we still planning on altering these variables through Javascript?

If we are, I have a couple of questions: 
  - Would low bandwidth devices load the gold theme first?
  - This could be a bad implementation, but if you look at the dark mode on https://lukelowrey.com/css-variable-theme-switcher/ you can see the page flashes the light mode colors for a quick second before the javascript loads. 
  - Script blockers like Brave will not load the js.

**Comment by GaryRidgway** [comment]
An option to not use JS with this would be to construct a small `<style>` block that we embed with php at the end of our stylesheet imports that resets the variables, so then on render the variables are already changed.

**Comment by bspeare** [comment]
For the initial slice of this work, let's perhaps set a body class that changes the `:root` variables?  Here's an example: https://codepen.io/bspeare/pen/eYLgypv.

**Comment by GaryRidgway** [comment]
That is a much better idea, lol.
