### ISSUE TITLE
etc.engineering.uiowa.edu move to engineering.uiowa.edu/etc

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6207]
# Story

As an owner of etc.engineering.uiowa.edu, I would like to move this site to engineering.uiowa.edu and have all traffic going to etc.engineering.uiowa.edu be redirected to engineering.uiowa.edu/etc so visitors can find relevant information they are looking for.

# Additional Info
There are also a few additional one to one redirects that want to handle.

# Proposed solution

- [x] Request redirect be put in place on Vulture to redirect etc.engineering.uiowa.edu to engineering.uiowa.edu/etc - this should be tested once in place by updating local hosts file.
- [x] Request TTL be lowered to 5 min for etc.engineering.uiowa.edu
---Launch Day---
- [x] Setup engineeringetc.prod.drupal.uiowa.edu on 703 so that the site can be available to our partners at Engineering temporarily in case any content was missed.
- [x] Update DNS to point to vulture at least 24 hrs after TTL has been lowered and Engineering is ready for switch
- [x] Update robots.txt to disallow all on engineeringetc.prod.drupal.uiowa.edu.
- [x] Add reminder to its-web to check in with Engineering (Hailey, Jason) in one month to see if D7 site can be removed.
---Post Launch Day---
- [x] Request TTL be set back to default once all is well.

**Comment by joewhitsitt** [comment]
>There are also a few additional one to one redirects that want to handle.

From standup, it sounded like this is blocked because there is an outstanding question about what one-to-one redirects they require.

**Comment by briand44** [comment]
not sure if we can update robots.txt to disallow all on this site since it is a standard site and we are not allowing access to that config page.

**Comment by briand44** [comment]
I was able to update robots.txt as user/1
