### ISSUE TITLE
OneIT website tasks to prep for launch

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6208]
# Story

As an owner of the One IT website, I would like to make sure we have everything in order to launch our new site on SiteNow v3 so that no issues arise during or post launch.

# Additional Information

They would like to launch by the end of March because the year in review content is on the new site and they want to promote that content then.

- We will need redirects setup for ~itpmo.uiowa.edu~ and techforum.uiowa.edu on Vulture.
- We need to implement the Thank You feature.
- The OneIT intranet site pulls in some general news from the OneIT site’s content–unsure what we’ll need to do to continue that functionality until we can migrate that site as well.

# Questions
Determine if they need to continue pulling in news from oneit.uiowa.edu on the Intranet site. If so figure out best way to implement that. If not, make sure we disable the feed importer on intranet.oneit.uiowa.edu during launch.

# Proposed solution

- [x] Enable Thank You feature split?
- [x] #6251
- [ ] #6268 - this is a future slice
- [x] Get redirect setup for techforum.uiowa.edu
- [x] Launch CIO.stage.drupal.uiowa.edu site at same time so they can communicate the two launches together
- [x] Remove techforum site
- [x] Set TTL back to default for techforum.uiowa.edu when all is well

**Comment by joewhitsitt** [comment]
Looks like news is pulled from http://oneit.uiowa.edu/feeds/its-news and is not generic RSS

**Comment by briand44** [comment]
I enabled the Thank You feature and they are going to test it out and provide feedback. They would like the ability to have a checkbox on the public form to have folks specify if they want to include the thank you in the CIO listening post. They would prefer this be available for launch but they likely wouldn't delay launch if it wasn't available.

They would like to continue pulling in news from OneIT to the OneIT intranet as well. They likely wouldn't delay launch if this was not ready either.

**Comment by briand44** [comment]
TTL has been lowered for techforum.uiowa.edu to 5 minutes

**Comment by briand44** [comment]
I also requested the redirect for techforum.uiowa.edu to https://oneit.uiowa.edu/projects/tech-forum be put in place on Vulture.

**Comment by briand44** [comment]
keep the old oneit site around for 1 month... add calendar reminder.

**Comment by joewhitsitt** [comment]
techforum v2 has been removed from uiowa01

**Comment by briand44** [comment]
Closing this as we have a separate issue for the news stuff.
