### ISSUE TITLE
Public Safety Development Phase 1

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6215]
Phase 1 development is for safety.uiowa.edu - Timeline - July 1, 2023

- Integration with Clery Edge
    - [x] #6217
    - [x] #6426
    - [x] #6397
    - [x] #6443 
    - [x] #6484
Your report has been submitted to the Office of Clery Compliance. Please keep in mind this is NOT a police report. To file a report with law enforcement for follow-up and investigation, please call 319-335-5022. In an emergency, call 911.
   - [x] #6558 
    - [Link to Documents](https://iowa.sharepoint.com/sites/CSI-Drupal2/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FCSI%2DDrupal2%2FShared%20Documents%2FPublic%20Safety&viewid=bf54b9d9%2D0975%2D4fbc%2D9f1b%2D6377bdc2307c)
- [x] #6439
- [x] #6647 
- [x] #6672 
- [x] Integrate Crowdfind on Lost & Found Page - https://police.uiowa.edu/services/lost-found - This has been embedded https://safety.prod.drupal.uiowa.edu/lost-and-found - The bottom one is the newly provided embed from the vendor with a11y enhancements based on TM's review. We have recommended they just link out for a better usability experience. Hayley was going to see if they can just link out.

# Possible future enhancements

- Integrate Kinnick Weather Stem of EM page - low priority, not required for launch
- Reporting Process Inforgraphic or Interactive Page (complaint response action item) - TBD - not required for launch

Phase 2 is work related to police.uiowa.edu and has a timeline of December 2023. We can track this work in a separate issue as we get closer to that work/timeline.

**Comment by joewhitsitt** [comment]
I think we should try to use the Weatherstem [CDN for signage](https://github.com/uiowa/uiowa/issues/6281), but for public safety, I think it would be good to use Weatherstem APIv2:

https://www.weatherstem.com/apiv2_docs

>You must be logged in to manage API V2 keys.
>Don't have an account? Get one! They're free!

**Comment by briand44** [comment]
Conversations in todays meeting with Public Safety....

- Crime log and fire log
    - we should limit to show 60 days in the past
    - they are going to provide us updated wording for captions
    - they are going to add more fire incidents
- CSA reporting
    - they tested csa report and things seemed to be working fine except they tried uploading a pdf and word document and weren't seeing those in Clery Edge
- Crowdfind embed - I emailed TM to see if he could review and provide feedback/recommendations

**Comment by briand44** [comment]
Closing this as the site launched today and all launch tasks have been completed. We can open separate issues for possible future enhancements items when those are needed.
