### ISSUE TITLE
Audit and Remove APR module if no usage

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6216]
# Story

As a developer, I would like to remove the APR module for D9 since we don't believe it is in use anymore so that we can reduce our technical debt.

# Additional Info

I believe Pharmacy was the only site using this for D9 and I believe they have since transitioned to Directory Profiles.

# Proposed solution

- [x] Audit to see if there is any usage
- [x] Remove if there is no longer any usage

**Comment by joewhitsitt** [comment]
Did a scan on 10/23/2023 of uiowa->uiowa06 and _no websites_ have the `apr` split enabled.

**Comment by joewhitsitt** [comment]
Noticed that we updated this module to work with drush 12 just because it is still in the codebase. Looking for the go ahead to JDI
