### ISSUE TITLE
Investigate crime log reporting from Clery Edge

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6217]
# Story

As a member of Public Safety and an owner of safety.uiowa.edu, we need to integrate the daily crime log reporting from Clery Edge in order to be Federally compliant.

# Additional Info

A component that could be placed on any layout builder page would be ideal but if that complicates this, let's discuss.

https://iowa.sharepoint.com/sites/CSI-Drupal2/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FCSI%2DDrupal2%2FShared%20Documents%2FPublic%20Safety%2FExternalReports%2FExternalReports%2FDailyCrimeLog&viewid=bf54b9d9%2D0975%2D4fbc%2D9f1b%2D6377bdc2307c

**Comment by joewhitsitt** [comment]
I tried the stored example earlier and got errors when trying it in a codepen.

I am able to parse out the endpoint expectations and get campuses for the example details. additionally, i can get the crime log endpoint to not error with the example but it is blank.

using the same method with our details, I get incorrect login for both campuses and crime log. is it domain restricted?

i have captured the endpoints I was experimenting with locally to show during grooming.

**Comment by briand44** [comment]
I fwd an email with vendor contact information to its-web related to this.

**Comment by briand44** [comment]
Grooming/Planning conversation.... For the first slice here let's just get the crime log form on a page on the safety site and get in contact with support to help us understand the issues we have been seeing in initial probing.

**Comment by joewhitsitt** [comment]
Added it here: https://safety.prod.drupal.uiowa.edu/clery-edge-test

I realized their html examples include scripts in the head which we aren't able to do with a full_html drop-in. Tried to work around that, but getting all kinds of cross-origin errors in addition to the failed to load errors from earlier.

@briand44 will you take a look at the draft I have in its-web to make sure I am approaching this correctly and that the correct people are on it?

**Comment by briand44** [comment]
@joewhitsitt I think you can leave the Dave's off for now. We'll also need to provide the additional IPs for tha allow list

**Comment by joewhitsitt** [comment]
@briand44 okay. Do you mean the web-3320* elastic ips?

**Comment by briand44** [comment]
Double check but I believe these are what we need added to an allowlist to cover all environments https://wiki.uiowa.edu/display/drupaldev/On-premise+server+ACL

**Comment by joewhitsitt** [comment]
Looks like the wiki is up to date. Email sent without Dave attached. Thanks!

**Comment by joewhitsitt** [comment]
Based on the quick response, I talked with Brian about pushing this a bit more forward so we can have a better understanding at the end of the sprint what we are dealing with to successfully implement this.

I am going to place the firelog and the CSA report embeds (https://github.com/uiowa/uiowa/issues/6215) and respond to the email to try and get a better understanding what what scripts need to be included for each of the embeds.

To load certain things in the head or to include our own libraries (e.g. datepicker), we might want to move these to block plugins.

**Comment by joewhitsitt** [comment]
Created the additional pages, moved them into blocks and sent a follow up email with more questions and a request to cover our dev and stage IPs.

https://safety.prod.drupal.uiowa.edu/clery-edge-crimelog-test (uses our institution's id)
https://safety.prod.drupal.uiowa.edu/clery-edge-firelog-test (demo id)
https://safety.prod.drupal.uiowa.edu/clery-edge-csareports-test (demo id)

**Comment by joewhitsitt** [comment]
I think the response from CleryEdge paves the way for us to do our own block plugin implementations so that we can control which libraries are added and how it operates/looks. https://github.com/uiowa/uiowa/issues/6397

**Comment by joewhitsitt** [comment]
I think this slice is complete and further work should be done in #6397

**Comment by joewhitsitt** [comment]
Going to respond to the email and ask a few more questions about the submission form

**Comment by joewhitsitt** [comment]
Asked questions whether we can hardcode the campus id and not provide a select list for the data logs.

Asked about the submission form and whether or not that needed to be embedded or can be linked off to since it is going to be capturing personally identifiable information. If we do need to embed it are we able to test post to it.

**Comment by briand44** [comment]
Grooming conversation... We want to put a couple more hours into this to see if we can strip things out and add css and use this or if we need to adjust and move towards a block component.

**Comment by joewhitsitt** [comment]
Capturing the node id path for when they change the page title and path: /node/311
