### ISSUE TITLE
Periodically expiring image style derivatives

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#6228]
# Story

As a site owner, I can be assured hosting costs won't be passed down to me _just_ because of some unused image styles eating up the University's storage quota.

# Background

Unless `drush image-flush` all or specific image styles is run on a site, these do not get cleaned up or expire by themselves. Content with placed images that is not getting much traffic could have several derivatives stored from original guess and check editing. For one site, there was over 3 GB of derivatives just hanging around where only a fraction are probably called upon.

# Proposed solution

- [ ] Flush image styles across all v2/v3 sites to free up space. If the image is being used, only the current image style will be regenerated on load.
- [ ] Future slice can be to implement cron job if makes sense and have better understanding of how often to run

**Comment by joewhitsitt** [comment]
imagecache_external has a configurable # of days to clear images on cron which we have set at 7 days.

i think it would make a huge difference if we looped through all of the image styles over the course of 6 months or an image style per month. this would at least clean up all of the initial content creation trial and error image styles that sites generate when they first start out.

**Comment by briand44** [comment]
Grooming conversation... Team proposed just flushing them for now and understanding what file storage that saves. `df -h` seems to be the most reliable way of identifying file storage space. Should run that on production environment pre and post image flush. We're not sure if there are concerns about flushing all sites at once and load for regenerating all the image styles. If not, let's just do them all. If so, we could schedule for off hours. `blt ume` per app was suggested. Do one app (maybe a smaller application) and then evaluate before doing all apps.

**Comment by GaryRidgway** [comment]
So the `df -h` didn't exactly work for every app because I think they are all on the same hardware, so if you go to[ this sheet ](https://iowa.sharepoint.com/:x:/r/sites/CSI-Drupal2/_layouts/15/Doc.aspx?action=editNew&sourcedoc=%7B542a4a46-3099-42d0-85d3-79031aba590c%7D&wdOrigin=TEAMS-WEB.teamsSdk.openFilePreview&wdExp=TEAMS-CONTROL&wdhostclicktime=1715702508537&web=1)and look at the `UIowa before` and the `UIowa after`, that should tell you the proper amount of data and usage we saved.

**Comment by joewhitsitt** [comment]
Did we create a follow-up slice to do other apps, or revisit to see if they are growing again and would benefit from a periodic clearing?

**Comment by briand44** [comment]
I am not seeing a follow up issue. Didn't we do all the v2/v3 apps?

**Comment by joewhitsitt** [comment]
The comments here make it sound like only uiowa was done. I don't recall personally. Still we were unsure how much they would fill up again and if we would need to do it again or setup a job.

**Comment by briand44** [comment]
Yep, I think it would be good to understand if we should setup a job. I think we ended up doing all the D10 apps but I could be wrong.

**Comment by joewhitsitt** [comment]
Created https://github.com/uiowa/uiowa/issues/8025 for you to run with @briand44 ;)
