### ISSUE TITLE
Search functionality for off-brand sites

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6231]
# Story

As a site owner of a SiteNow v3 website using an off-brand theme, I would like to still have the ability for folks to use the site search so that they can search for content on our site.

# Questions

Does anything need to happen for this?
Should we address [the favicon](https://github.com/uiowa/uiowa/issues/6232) here? That will be addressed in the linked issue.

**Comment by briand44** [comment]
Grooming conversation. Lets do some probing to understand if any changes need to be made in order for search to work for a site using a off-brand theme. Should we make an option to hide the link to search all University of Iowa sites? Do these sites need a custom CSE ID? It sounds like vanity domains currently exist in the default CSE.

**Comment by GaryRidgway** [comment]
Possibly fix https://github.com/uiowa/uiowa/pull/5085/commits/a8801e2de9ef5ade721321ead1758af06c8af98d
