### ISSUE TITLE
ise.engineering.uiowa.edu move to engineering.uiowa.edu/ise

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6235]
# Story

As an owner of ise.engineering.uiowa.edu, I would like to move this site to engineering.uiowa.edu and have all traffic going to etc.engineering.uiowa.edu be redirected to engineering.uiowa.edu/ise so visitors can find relevant information they are looking for.

# Additional Info

# Proposed solution

- [x] Request redirect be put in place on Vulture to redirect ise.engineering.uiowa.edu to engineering.uiowa.edu/ise - this should be tested once in place by updating local hosts file.
- [x] Request TTL be lowered to 5 min for ise.engineering.uiowa.edu - this was done at 10am Friday March 3rd
---Launch Day---
- [x] Setup engineeringise.prod.drupal.uiowa.edu on 703 so that the site can be available to our partners at Engineering temporarily in case any content was missed.
- [x] Update DNS to point to vulture at least 24 hrs after TTL has been lowered and Engineering is ready for switch
- [x] Update robots.txt to disallow all on engineeringise.prod.drupal.uiowa.edu.
- [x] Add reminder to its-web to check in with Engineering (Kristine R, Hailey, Jason) in one month to see if D7 site can be removed.
---Post Launch Day---
- [x] Request TTL be set back to default once all is well.

**Comment by briand44** [comment]
Redirect is in place on Vulture and tested

**Comment by bspeare** [comment]
All of the launch day tasks for this are complete.

**Comment by briand44** [comment]
I let Engineering Hostmaster know it should be safe to set TTL back to default. Closing this.
