### ISSUE TITLE
Add vertical display option for SiteNow service video embeds

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#6243]
# Story

As a site owner, I can display video content from YouTube shorts. 

# Proposed solution
-  Add a “Vertical” display option in addition to “Large, Medium, Small” for embedded videos. 

<details>
Currently the vertical video block on uiowa.edu is a manual process of uploading local files:
- Manual .vtt file upload and subtitle positioning
- Manual file upload
- Manual poster image upload
- Works with H264 encoding only

# Proposed solution

- Update the vertical video block to use youtube short video links
  - Requirements
    - Needs to still work with our custom play/pause button
    - Needs to not display recommended ads/videos at the end of the video
</details>

Here are links to the YouTube shorts versions of the homepage videos.

- https://youtube.com/shorts/GAdS3JW3KSM
- https://youtube.com/shorts/ofQsz0O_CTg
- https://youtube.com/shorts/QOqQOgV8juc

**Comment by bspeare** [comment]
Shorts can be embedded in our WYSIWYG, but render as 16:9.  We would need to offer a "Vertical" display option in addition to "Large, Medium, Small" that we currently offer.

**Comment by joewhitsitt** [comment]
>Needs to not display recommended ads/videos at the end of the video

Is that something we can control or is that an upstream setting for creators to do? Instead of covering .vtt they are also responsible for adding a transcript on youtube right?

**Comment by joewhitsitt** [comment]
i put a question out on drupal slack: https://drupal.slack.com/archives/C1VLTJJD8/p1678221285495789. we will see if there are any bites

**Comment by bspeare** [comment]
@joewhitsitt it could be something on their end to set but useful for us to know.  https://brown.edu/ has just the "watch again" screen at the end of their videos.

**Comment by briand44** [comment]
Just noting that College of Education is asking for this as well as a few other campus partners

**Comment by briand44** [comment]
Grooming conversation... PR currently started. Questions around view modes. This slice does not affect the homepage site and its vertical videos. Include docs as part of this slice. Write them with containing column placement in mind. There is a testing page on the PR. Sized as medium but we think only small size left.

**Comment by joewhitsitt** [comment]
>Include docs as part of this slice. Write them with containing column placement in mind

Have draft docs been started for this? If not, I can pick that part up as well as testing the PR tomorrow morning if nobody else beats me to it.

**Comment by bspeare** [comment]
@joewhitsitt a draft doc hasn't been started yet.

**Comment by joewhitsitt** [comment]
Started a draft here: https://sitenow.uiowa.edu/node/176/latest

**Comment by pyrello** [comment]
Capturing some notes from  Slack conversation with @bspeare and @joewhitsitt:
- Default, S, M, and L options are still shared with images, so just changing the labels in config is not an option because it would change the labels for image selection too. Possibly we could change the label just for remote videos. Or we could provide help text under the selection widget when that media type is selected.
- We discussed setting a maximum width for vertical videos to prevent gigantic videos displaying in 1 or 2 column layouts.
- Ideal labels for the available options are:
  - `Default` => `Horizontal (16 x 9) - Full width`
  - `Small` => `Horizontal (16 x 9) - Small`
  - `Medium` => `Horizontal (16 x 9) - Medium`
  - `Large` => `Horizontal (16 x 9) - Large`
  - `Vertical` => `Vertical (9 x 16) - Full width` (or possibly `Full width*` with a help message about max width size or link to docs).

**Comment by joewhitsitt** [comment]
Thinking over lunch, my guess is that this will be more difficult to do now that we would be trying to alter options as part of a CKEditor5 plugin. \Drupal\ckeditor5\Plugin\CKEditor5Plugin\Media::configureViewModes

So far, I am looking in the wrong place...

<img width="630" alt="Screenshot 2024-05-23 at 1 58 37 PM" src="https://github.com/uiowa/uiowa/assets/4663676/d738fb3c-5323-45d4-b8f6-f4bd56b09065">

**Comment by briand44** [comment]
upped this to a large but not a large still left.

**Comment by joewhitsitt** [comment]
I was looking in the wrong place, but I am on track now..
<img width="225" alt="Screenshot 2024-05-23 at 3 49 23 PM" src="https://github.com/uiowa/uiowa/assets/4663676/ee5085e2-cb20-4286-a993-784d48978eb2">

Update: still in the wrong place if I want this to be media type specific...

**Comment by joewhitsitt** [comment]
I technically think the Drupal/CKEditor5 solution here is to have separate view modes as the plugin is "compiled" and loaded once for the ckeditor instance. When it loops through the view modes it attaches which media types can use it and then is only referenced when the media type is being edited.

I don't think we want to create a custom plugin for this.

This thread talks about reordering which can be done, but is then troublesome when the discussion turns to bundle specific sorting https://drupal.slack.com/archives/C01GWN3QYJD/p1683298109712969

I was able to do https://drupal.slack.com/archives/C01GWN3QYJD/p1683302713327509?thread_ts=1683298109.712969&cid=C01GWN3QYJD as the screenshot above shows, but `$dynamic_plugin_config` is not aware of the media type.

**Comment by bspeare** [comment]
@joewhitsitt would the next step be to set up video specific view modes and an update hook to switch out the old view modes for the new ones?

**Comment by joewhitsitt** [comment]
Open to brainstorming on this as I might be missing something, but short of implementing a JS MutationObserver to modify labels on the fly, I think the smallest slice would be to ship what we have with a modified Vertical label, possibly add a link to the documentation on the balloon, and then follow up with https://github.com/uiowa/uiowa/issues/7195 so that the only media type that uses small/medium/large would be remote video.

**Comment by bspeare** [comment]
I think your smallest slice solution makes sense along with the container query work that we discussed.

**Comment by joewhitsitt** [comment]
>I think your smallest slice solution makes sense along with the container query work that we discussed.

9 x 16 or 9:16?

**Comment by bspeare** [comment]
We are using `:` elsewhere: https://github.com/search?q=repo%3Auiowa%2Fuiowa+16%3A9&type=code

**Comment by joewhitsitt** [comment]
This is probably revealing my inexperience with this stuff, but for the container query would it make sense for that to get implemented starting at a certain viewport? on mobile the vertical video is pretty constrained and small.

**Comment by pyrello** [comment]
I've reviewed the previous comments as well as the Drupal slack thread mentioned above. I think there are potentially paths forward, but nothing quickly and easily attainable, so I think we should go ahead with the limited slice we have planned already and revisit this when we're ready to do bigger things to make the CKE5 + media systems work better.
