### ISSUE TITLE
Updates to uiowa.edu for One Day at Iowa

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6250]
# Story

As a marketer for One Day at Iowa, I would like to see some content changes on the uiowa.edu website to help promote this day.

# Additional Info

- This year the event takes place on March 29th. 
- Ideally this would be published on Monday March 27th or the 28th.
- It can be removed first thing on March 30th.

Waiting for more info about specific changes but here are some of the assets from last year.

Banner image:
![1dfi-uiowa-webbanner-22](https://user-images.githubusercontent.com/1017022/223792195-b26a68f4-8c58-4e59-a0f7-6f0f2bc7e50e.jpg)

Banner text:
Get in the game on One Day for Iowa! [header text]
March 29 is the University of Iowa’s 24-hour online giving day. Hawkeyes can level-up their support and unlock bonus dollars by participating in limited-time challenges and matches that make their donation go farther.
Give now! [button]

Additional screenshots:
![uiowa takeover](https://user-images.githubusercontent.com/1017022/223793550-25ee983e-b609-43e4-9793-b53dc29fb41b.png)

![uiowa_homepage2](https://user-images.githubusercontent.com/1017022/223793578-eccac2fc-51a8-4468-a3f5-a09e3d9a5d92.JPG)

# Questions

- What is the destination link and campaign tracking code? - They will provide these with the graphic.
- How far in advance do we need these assets?

# Proposed Solution

**Comment by briand44** [comment]
Grooming Conversation... I will ask them to provide us with the graphic, text, link, etc. as soon as possible. We may want to create a draft and then publish that draft when it is time and revert when it is time to remove.

**Comment by briand44** [comment]
I asked them to provide us with an updated graphic, text and link

**Comment by briand44** [comment]
I received the following assets:

![Image](https://user-images.githubusercontent.com/1017022/225960806-445d2705-4674-41c9-ba4f-8a5152d51996.jpg)

Get in the game on One Day for Iowa! [header text]
March 29 is One Day for Iowa, the University of Iowa’s 24-hour online giving day. Join fellow Hawkeyes to make an important and meaningful impact by donating now!
Give now! [button link https://1dayforiowa.org/3ZAlLsx]

**Comment by briand44** [comment]
removed blocked label because we could potentially make these changes in a draft prior to actually publishing on March 27th.

**Comment by GaryRidgway** [comment]
These changes have been made and published to uiowa.edu

**Comment by briand44** [comment]
I reached out to the original requester to see if all looks good and if there is any additional tracking code for the link. I will update when I hear back.

**Comment by briand44** [comment]
>Thank you so much! It looks great. All the tracking code we need is included in the URL we gave you so we should be good to go.

**Comment by briand44** [comment]
reverted to previous published page. Closing this.
