### ISSUE TITLE
Callout alignment, color, other classes

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#6254]
# Proposed solution

- Create a `callout` component library in `uids_base`.   
- Attach the library to the IowaNow article. 
- Add additional `bg_gray` and alignment and sizing classes.

**Comment by bspeare** [comment]
Do we want to use the inline sizes component classes (https://github.com/uiowa/uids/blob/4.x/src/components/inline/inline.scss#L62-L92) for these or recreate our own sizes for the callout within `uids_base`?    Attaching the `align-right` class to the callout will only float the callout to the right if there is a small amount of text in the callout.   We will need to apply a width to the callout to get it working.

**Comment by cory-skeers** [comment]
> Do we want to use the inline sizes component classes (https://github.com/uiowa/uids/blob/4.x/src/components/inline/inline.scss#L62-L92) for these or recreate our own sizes for the callout within `uids_base`? Attaching the `align-right` class to the callout will only float the callout to the right if there is a small amount of text in the callout. We will need to apply a width to the callout to get it working.

My thought was to use the inline classes. Even more than images, I think the inline sizing is closest to what an editor would expect when setting it up, and since there aren't any callouts existing in the wild, there's less complication in setting it up than with media.
