### ISSUE TITLE
Create 2 new resources for Rec Serv: Rain Out Line – Rec Fields, Rain Out Line – Softball

### ISSUE THREAD

**Issue by makurj** [uiowa/uiowa#6259]
"We are in the process of switching two more of our internal calendars over to Fusion and would like the option to post them on the website.  The two calendars are called:
 
Rain Out Line – Rec Fields
Rain Out Line – Softball
 
I have created them both in Fusion – can you help to create that as an option to embed in our website?  They will need to be separate."

**Comment by joewhitsitt** [comment]
Can this be closed since it is an upstream issue involving ITS App-Dev Hours API (https://hours.iowa.uiowa.edu/api/Hours/)? Once available, it should only be cached for a short period of time before it can be fetched in the block config.
