### ISSUE TITLE
D7 Security Updates

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6266]
- [x] 701
- [x] 702
- [x] 703
- [x] Dentistry
- [x] ICGov
- [x] Clas
- [x] Grad
- [x] Signage
- [x] Healthcare Signage

**Comment by briand44** [comment]
Just noting there is an update to .htaccess as well as a db update.

**Comment by pyrello** [comment]
Grad application DEV (master branch) has been updated. Still needs to be tested in dev. I recommend the old GC site and IWP. As noted above, there is a DB update and this requires SSH into the Grad application and running the `drush updb` command in the specific sites folder for those sites. If nothing is obviously broken on either of those sites, the update can be moved to Prod and the DB updates will need to run on all sites there.

**Comment by pyrello** [comment]
I went ahead and rolled this out for GC.
