### ISSUE TITLE
Feed news from OneIT website to OneIT Intranet

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6268]
# Story

As a owner of the OneIT and OneIT Intranet sites, I would like to be able to continue pulling in news from the OneIT website into the OneIT Intranet site so that Intranet visitors and folks subscribed to the Intranet digests can still have visibility to this information.

# Additional Info

Would like this for launch of the new OneIT website at the end of March but they would launch without this.
Currently a feed importer on the intranet
Looks like news is pulled from http://oneit.prod.drupal.uiowa.edu/feeds/its-news and is not generic RSS

# Proposed Solution

**Comment by joewhitsitt** [comment]
Need to be aware of what it will import as the feed unique ids will change. Will it delete existing, import all from the new site or just newer items.

**Comment by briand44** [comment]
Grooming conversation... Does the summary need to be unique or does truncating the body work? Categories are present in the importer but not in current feed. Is that working as desired or do we need to account for it. Is it going to import duplicate content if we don't address unique ids?

We need to be careful testing on the Intranet because there are email notifications/digests related to news.

**Comment by briand44** [comment]
The category "OneIT" is being populated through a feeds tamper so it does not need to be accounted for in any other way.

**Comment by briand44** [comment]
As far as the summary, my understanding is the summary is what comes over in the v3 rss. So, OneIT folks will need to make sure they are entering a summary for all their news and we should map the source description to both summary and body.

**Comment by briand44** [comment]
Not sure about the unique identifier/duplicates. Also seeing that the feed importer is currently setup to delete non-existent source items. So if our v3 rss only contains 10 items, items will begin to be deleted from the intranet once they are no longer in the feed.

**Comment by briand44** [comment]
Ok, I noticed there is actually a node id in the feed. There will also be duplicates, ~9 I believe, unless we only import items with a publish date after x. Also noticed that the current news links on the Intranet that were fed in from OneIT are currently broken/incorrect. I have an importer working from the new site locally. We may need to see if we can disable sending notifications for the dupes?

I have scheduled some time with our partners to discuss the following:

- Not having all items in the feed
    - This means that any updates to items that are no longer in the feed or any news items deleted from the OneIT site will not get updated/removed from the Intranet.
    - They will need to enter a summary for all news items.
    - Concerns about notifications?
    - Duplicates

**Comment by briand44** [comment]
Just realized the same feed is consumed by the ITS website.

**Comment by briand44** [comment]
Discussed with OneIT folks and they are ok postponing this work until they have conversations about the future of the OneIT Intranet. In the meantime, they will manually post any OneIT news on the Intranet. Still waiting to hear about the ITS website.

**Comment by briand44** [comment]
I disabled the feed importer on the OneIT Intranet

**Comment by briand44** [comment]
Disabled the importer on the ITS website. Closing this as there isn't anything needed at this point.
