### ISSUE TITLE
Update Admissions site with new student profile block

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#6274]
Follow-up to #6270 (split out from #6054)

Add new "Student profile card grid" block to https://admissions.uiowa.ddev.site/international-student-ambassadors, https://admissions.uiowa.edu/california-hawkeyes, https://admissions.uiowa.edu/texas-hawkeyes and remove previous block

**Comment by briand44** [comment]
Grooming conversation... We should communicate with Admissions that we will be doing this. If the new block exists that we should be able to move forward with these changes.

**Comment by bspeare** [comment]
This is complete.
