### ISSUE TITLE
Buttons and other styles within CKEditor are not displaying correctly

### ISSUE THREAD

**Issue by bewoldt** [uiowa/uiowa#6282]
# Problem
Buttons style using the Primary and Secondary styles are not showing up correctly within the editor window. The live site looks correct.

<img width="364" alt="image" src="https://user-images.githubusercontent.com/731952/227027428-202f63b1-b21f-464b-b905-bb4c149d9d98.png">

# Proposed solution

Audit the styles that are added to the wysiwyg, and which are not.

Additional styles can be pulled into ckeditor through https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/uids_base.info.yml,
or included through https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/scss/components/sitenow/sitenow_wysiwyg.scss

For styles that might need tweaks to work correctly within the wysiwyg, alterations can be added to `sitenow_wysiwyg.scss` with minimal impact outside of this.

https://github.com/uiowa/uiowa/pull/1712/files#diff-3e2f505910782c55036ebbe9cabac6fb649ee875a4588beeed62d0c70f533057

**Comment by bewoldt** [comment]
Maybe related, the table header row background color is also not showing in the editor. It should have a gold background.

<img width="930" alt="image" src="https://user-images.githubusercontent.com/731952/228298306-fce5a100-5d99-4b30-b080-470ae8d7b81a.png">

**Comment by cory-skeers** [comment]
> Maybe related, the table header row background color is also not showing in the editor. It should have a gold background.

Thanks for bringing this up! I think the two are related, and there are likely some other styles that are missed. I've updated the issue summary with a few more details for when this gets prioritized and worked.
