### ISSUE TITLE
Content/Design Review for https://uip.pharmacy.uiowa.edu/uip-careers

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6284]
# Story

As a content editor for the UI Pharmaceuticals website, I would like the OSC web team to review our new careers page (https://uip.pharmacy.uiowa.edu/uip-careers) from a content and design perspective to make sure we are following best practices.

# Additional Info

>I have been working on re-designing the [Careers page](https://uip.pharmacy.uiowa.edu/careers) of UIP’s website to draw more applicants in to our organization (i.e. turning this page into a fully-fledged ‘Careers’ page with information on culture, benefits, education, etc.).

# Proposed Solution

- [ ] Review https://uip.pharmacy.uiowa.edu/uip-careers
- [ ] Gather feedback or create a draft mockup
- [ ] Schedule time to walk through feedback with UI Pharmaceuticals

**Comment by mkyoder** [comment]
- [X] Review https://uip.pharmacy.uiowa.edu/uip-careers
- [X] Gather feedback or create a draft mock up

**Comment by mkyoder** [comment]
Here is the current page that Julia created: https://uip.pharmacy.uiowa.edu/uip-careers and here is the new mock up: https://uip.pharmacy.uiowa.edu/uip-careers-copy. Would love your thoughts here @bspeare I tried to channel the admissions and uiowa sites in this layout.

**Comment by mkyoder** [comment]
Additional notes and feedback is here: 

[Website Recommendations - 3-23-2023.pdf](https://github.com/uiowa/uiowa/files/11055051/Website.Recommendations.-.3-23-2023.pdf)

**Comment by mkyoder** [comment]
@briand44 Ben had a chance to review this and said this mock-up is good to go. I think we can schedule a time to walk through this with the UI Pharmaceuticals team.

**Comment by mkyoder** [comment]
Meeting set up with Julia for 3/27
