### ISSUE TITLE
Update icons.brand.uiowa.edu with new icons

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#6294]
# Story

As a brand manager, I can see the icons.brand.uiowa.edu site updated with new icons that have been recently designed. 

Jake needs this by **4/14.** 

# Proposed solution

1. Reach out to Jake Sorg in OSC to get the new icons. 
2. Follow Dustin's instructions at https://github.com/uiowa/brand-icon-browser.

**Comment by briand44** [comment]
I've uploaded the icons to https://iowa.sharepoint.com/sites/CSI-Drupal2/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FCSI%2DDrupal2%2FShared%20Documents%2FBrand%20Icons&viewid=bf54b9d9%2D0975%2D4fbc%2D9f1b%2D6377bdc2307c

**Comment by bspeare** [comment]
This is ready for review: https://github.com/uiowa/brand-icon-browser/pull/105.   Overall, it took around 2 hours of work.
