### ISSUE TITLE
Revisit featured image breadcrumb code in uids_base.theme

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#6296]
>Is this code still necessary?

# Reference
https://github.com/uiowa/uiowa/blob/a304a98fc8e341609ee082844ed230fb39265585/docroot/themes/custom/uids_base/uids_base.theme#L493-L499

**Comment by pyrello** [comment]
Unless this is somehow represented somewhere else in code, it seems like it would still be necessary. Otherwise, we wouldn't be able to display the breadcrumb. I'd be in favor of just removing this.
