### ISSUE TITLE
Layout section does not clear a floated image

### ISSUE THREAD

**Issue by bewoldt** [uiowa/uiowa#6301]
# Problem
Came across this bug on the UI Pharmaceuticals site. Looks like the layout container does not clear an image that is floated.

https://uip.pharmacy.uiowa.edu/services/sterile-manufacturing/clinical-and-commercial-manufacturing

<img width="1461" alt="image" src="https://user-images.githubusercontent.com/731952/228571593-f6e25515-a100-41af-ad3a-486220d273c6.png">

**Comment by bspeare** [comment]
Thanks @bewoldt!
