### ISSUE TITLE
Update "Anchor Links" to use "Unique ID" field

### ISSUE THREAD

**Issue by makurj** [uiowa/uiowa#6307]
# Story

As a website owner, I'd like the latest steps listed here (https://sitenow.uiowa.edu/documentation/wysiwyg) for adding an anchor link to a page which include using the "unique ID" field.

**Comment by cory-skeers** [comment]
Added the Unique ID option to the docs here. Left the original instructions on creating a link as well, as they are still relevant outside of Layout Builder.
