### ISSUE TITLE
Timeline - timeline line doesn't start at the top of the block for all timelines

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#6308]
# Problem
I think https://github.com/uiowa/uiowa/pull/6209 introduced a bug where depending on the total length of the timeline, the top 5% starting point for the line mask is further down the page.

# Steps to reproduce
Inspect https://175.uiowa.edu/milestones-university-iowa-history or https://stanleymuseum.uiowa.ddev.site/about/history compared to newstudents.uiowa.edu

<img width="385" alt="Screenshot 2023-03-31 at 2 41 13 PM" src="https://user-images.githubusercontent.com/4663676/229214328-8c7eb775-65d0-4e68-9506-b28f9c2298f5.png">

<img width="443" alt="Screenshot 2023-03-31 at 2 43 40 PM" src="https://user-images.githubusercontent.com/4663676/229214821-97fd7839-676b-4ea9-8af1-140f5b0fc76b.png">

# Proposed solution
?

**Comment by briand44** [comment]
grooming conversation... revert fix in https://github.com/uiowa/uiowa/pull/6209 since we think that was a less intrusive bug. Prioritize fixing that again after.
