### ISSUE TITLE
Redirects plan for 91st Meridian

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#6316]
- Set up redirects on 91stmeridian.iwp.uiowa.edu using the portion of the old URL after `/91st/`.
- Add an .htaccess rule redirecting traffic from `iwp.uiowa.edu/91st/*` to `91stmeridian.iwp.uiowa.edu/*` OR Set up redirects on IWP D7 site using match redirect/individual redirects from full path to path excluding `/91st/`.

**Comment by makurj** [comment]
Chatted with Brian. As this will be done in the UI via match redirect (for redirecting to homepage) or one-on-one via URL redirect on the D7 site, no development required from OSC web team, so closing this issue.
