### ISSUE TITLE
Body WYSIWYG area jumps during edits

### ISSUE THREAD

**Issue by makurj** [uiowa/uiowa#6325]
The WYSIWYG jumps around when trying to edit an article. This was in Chrome. See screen recording below.

URL: https://sitenow.uiowa.edu/news/2023/04/updates-march-2023

https://user-images.githubusercontent.com/52135878/230390186-f42bfed9-b5f8-4974-958e-ae2f02307e68.mp4

**Comment by joewhitsitt** [comment]
This is no longer an issue with the upgrade to CKEditor5
