### ISSUE TITLE
Have SiteNow Request emails reply to email be the customer who requested the site

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#6326]
# Motivation

If you want to have a follow-up conversation with the customer about a site request, you cannot simply reply to the request email to start that process. That seems like an obvious starting point because all the information in contained in the original request. Instead, it is necessary to copy the customer's email and paste it into the To email field in Outlook. Having it already set as the reply to value would save a step and reduce the possibility of operator error.

# Proposed solution

TBD

**Comment by briand44** [comment]
I'm not sure if this is managed through config or not? If not, I can just make this change.

**Comment by joewhitsitt** [comment]
that part is not managed config

https://github.com/uiowa/uiowa/blob/main/config/default/config_ignore.settings.yml#L51

**Comment by briand44** [comment]
Ok, I made the change. Let's confirm it worked when the next site request comes in. Marking as blocked/waiting.

**Comment by briand44** [comment]
double checked and confirmed that the setting was still intact after latest release

**Comment by joewhitsitt** [comment]
This worked. Thanks
