### ISSUE TITLE
Sitenow April 2023 Newsletter

### ISSUE THREAD

**Issue by makurj** [uiowa/uiowa#6327]
https://sitenow.uiowa.edu/news/2023/04/updates-april-2023

### Issue/Solution
Provide a "release notes" type article of finished/done features/updates and publish to website, then send out dispatch email.

- [ ] Create draft and update the parking lot card with an edit link
- [ ]  Add "release notes" covering the month of v2/v3 default profile enhancements and webmaster/edit visible bug fixes.
- [ ] See the previous month's article as an example.
- [ ] Bullet points from demo stories slide per week: https://drive.google.com/drive/folders/1EehKUjxCbakaB9FchrGhAbaxuRbqyDGW?usp=sharing.. and/or from Web Community sprint demo announcements https://webcommunity.sites.uiowa.edu/updates/2023/02/sprint-demo-149-february-16-2023
- [ ]  Get at least one team member to look over the draft before publishing.
- [ ]  Since the draft was started earlier, adjust the publish date/time, publish, get the link to the article.
- [ ]  Dispatch email with link to article. (To get access, send an email to [dispatch-support@uiowa.edu](mailto:dispatch-support@uiowa.edu) to have the account provisioned. Provide your hawkid and mention the CSI:drupal group)
  - [ ] Modify SiteNow Announcements Template (tweak opening line, update the article link, any other editorial adjustments)
  - [ ] Clone an old communication off SiteNow Announcements campaign
    - [ ] Use SiteNow Announcements population, template, suppression list, bypass approval.
    - [ ] Turn off Dispatch "test mode" to send out email.
    - [ ] When scheduling, check the "archive" option so that there is an RSS instance we can use in the future. I don't think this can be done after the fact.
- [ ]  Turn on Dispatch "test mode" after email is successfully sent.
- [ ]  Take a moment to check dispatch and google analytics on whether these articles are being read.
- [ ]  Create the next months's issue and copy all this bullet list into it, removing the checked boxes if any.

**Comment by bspeare** [comment]
https://sitenow.uiowa.edu/news/2023/04/updates-april-2023 is now ready for review with all the work we released in April!

**Comment by cory-skeers** [comment]
> https://sitenow.uiowa.edu/news/2023/04/updates-april-2023 is now ready for review with all the work we released in April!

Proofread this, and looks good to go 💯

**Comment by bspeare** [comment]
This is done. 

<img width="1272" alt="Screenshot 2023-05-03 at 11 18 54 AM" src="https://user-images.githubusercontent.com/1036433/235977714-76426945-b113-4938-a2dd-525a3568a2fb.png">
