### ISSUE TITLE
Event Pagination 

### ISSUE THREAD

**Issue by bewoldt** [uiowa/uiowa#6334]
# Problem

When displaying events with the Grid layout option, if you have an uneven number of events the pagination will show up in one of the grid spaces instead of across the bottom.

<img width="1404" alt="image" src="https://user-images.githubusercontent.com/731952/230459432-0bce58ac-2d74-4770-b6e9-bfe1d3ec553d.png">

https://sandbox.prod.drupal.uiowa.edu/event-test

### Other issues

Pagination background when using gray.

<img width="905" alt="image" src="https://user-images.githubusercontent.com/731952/230623131-0e5b6fd3-6f74-4020-bf57-1eda9345c86e.png">

Padding when images are disabled.

<img width="450" alt="image" src="https://user-images.githubusercontent.com/731952/230623319-186d7487-6f8a-4e3c-9546-e5cc6c36e1ab.png">

**Comment by bspeare** [comment]
This could be solved in `grid.scss` with something like:
```
[class*="grid--"] .pager {
  grid-column: 1 / -1;
}
```

**Comment by bewoldt** [comment]
Updated the issue to include other bugs I found.

**Comment by bspeare** [comment]
Looks like the padding and pager issues will be fixed in https://github.com/uiowa/uiowa/pull/6054.
