### ISSUE TITLE
*.center.uiowa.edu coverage on other applications

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6335]
This is covered on uiowa04 but it may be nice to cover this on all the D9 applications so future sites can live anywhere.

- [x] uiowa
- [x] uiowa01
- [x] uiowa02
- [x] uiowa03
- [x] uiowa04
- [x] uiowa05

**Comment by joewhitsitt** [comment]
uiowa05 is setup

**Comment by joewhitsitt** [comment]
This is done
