### ISSUE TITLE
Add "un-cropped" media shape for (Iowa) Events block

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#6336]
# Story

As a site editor I want to have the images that display in the (Iowa) events block from content hub appear un-cropped because I specifically designed it to have certain information and the cropping is removing/obscuring it.

Original request:
> I am reaching out with a question regarding the Events module for websites on the Drupal platform. Our office, the RDO, utilizes this module to import and display upcoming events that we create on the UI events calendar. One issue we have been experiencing is distortion of media thumbnails between the events.uiowa.edu postings and how they are captured on our [upcoming events page](https://research.uiowa.edu/research-development-office/rdo-events).
>
>For example, we host informational sessions on the Pivot platform, for which we use the program’s logo as a media thumbnail to accompany the event ([calendar link](https://events.uiowa.edu/77909)). On the Events calendar, the image is clear and displayed in its native aspect ratio. However, on our website, the picture is stretched and blurred.
>
>
![download](https://user-images.githubusercontent.com/709009/230629178-4d6f38f3-24d6-4f23-9340-d428dbc63a94.png)
>
>Ideally, we would like for the Events module to display previews that do not distort the image. Unfortunately, we are not aware of features that allow us to properly customize the image previews on this module. We have experimented with the “Image Format” options in Drupal, including Widescreen, Square, and Circle previews; however, Widescreen format seems to be the “best” option despite mixed results for each posting. Is there a way for us to further customize how pictures are displayed? Would we need each picture on the events calendar to be posted in widescreen format if that is how we selected it on the website?

# Proposed solution

**Comment by pyrello** [comment]
Contact Jack O'Halloran when we make a decision about whether to go forward with this or not.

**Comment by joewhitsitt** [comment]
@pyrello is this related or separate from https://github.com/uiowa/uiowa/issues/3274

**Comment by pyrello** [comment]
Separate, I think, since it is specifically about being able to set the media shape in the context of the (Iowa) Event block.

**Comment by bspeare** [comment]
I'd advise Jack to try and upload a 16:9 or 3:2 aspect ratio image to content hub.  The content hub guidelines advise for 3:2 https://content.uiowa.edu/photo-guidelines.    The image in question is a square https://content.uiowa.edu/sites/content.uiowa.edu/files/pivot_logo_small.png.  Un-cropped images for card blocks might be useful, but for lists or grids where we want visual consistency it would be visually disruptive.

**Comment by joewhitsitt** [comment]
Reached out through the cherwell ticket with the recommendation above for the events they are able to edit.

**Comment by joewhitsitt** [comment]
>Un-cropped images for card blocks might be useful, but for lists or grids where we want visual consistency it would be visually disruptive.

The team decided that as written, this is not something we plan to do.
