### ISSUE TITLE
Card 4_x post launch: As a SiteNow user, I can adjust the headline style on a list/events/aggregator block

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#6339]
# Story

As a SiteNow user, I can adjust the headline style on a list/events/aggregator block so that I can have control over serif or sans-serif fonts on the list cards. 

Since https://github.com/uiowa/uiowa/issues/5232 is implemented in https://github.com/uiowa/uiowa/pull/6054, we will need to provide the "Headline style" option to the list/content hub/local events/aggregator block. 

# Proposed solution
- Provide the "Headline style" option to the list/content hub/local events/aggregator block.
- Set defaults in code.
- Possibly create an update hook to set the headline style so that.
  - `stacked` cards are set to sans-serif fonts.
  - `left/right aligned` cards are set to serif fonts.

**Comment by pyrello** [comment]
I'm going to work on this while the knowledge of how everything works is still fresh.

**Comment by pyrello** [comment]
In some cases, we already have the ability to set a headline style for block in which a list is presented. So, setting the card headline style will set the style of the individual card elements within a list, but not affect the block headline.
