### ISSUE TITLE
As a content creator, I would like to be able to link to draft pages with auto-complete

### ISSUE THREAD

**Issue by makurj** [uiowa/uiowa#6343]
# Problem
As a content creator, I would like to be able to link to draft pages with auto-complete whether the page I'm on is draft or published, because I create many draft pages at one time that go live later, sometimes at the same time. It works if I grab the relative URL manually and paste it.

# Steps to reproduce

https://user-images.githubusercontent.com/52135878/231269950-c44db6f5-391d-4e7b-876d-f95025e8a94d.mp4

# Proposed solution

**Comment by joewhitsitt** [comment]
This currently works as designed. Are you suggesting an enhancement instead? https://github.com/uiowa/uiowa/blob/main/config/default/linkit.linkit_profile.default.yml#L23

**Comment by makurj** [comment]
Good to know, thanks.

Yes, this being addressed as an enhancement is fine. I'll remove the bug label.

**Comment by joewhitsitt** [comment]
Can you adjust it then to be a user story? Is there a use-case for linking to unpublished pages?

**Comment by makurj** [comment]
Done, and yes. Use case in issue summary.

**Comment by joewhitsitt** [comment]
I this this should be done for all as default. Change the setting https://github.com/uiowa/uiowa/blob/main/config/default/linkit.linkit_profile.default.yml#L23 and update the matcher to include published status here https://github.com/uiowa/uiowa/blob/main/config/default/linkit.linkit_profile.default.yml#L18

**Comment by pyrello** [comment]
When you turn this setting on the behavior is that you can see the link when logged out, but when you click it, it takes you to a 403 page (which now conveniently includes a login link). The autocomplete results do not indicate that the node is unpublished, which I think would be desirable.

**Comment by joewhitsitt** [comment]
>The autocomplete results do not indicate that the node is unpublished, which I think would be desirable.

That is what I meant by "update the matcher to include published status here https://github.com/uiowa/uiowa/blob/main/config/default/linkit.linkit_profile.default.yml#L18"

**Comment by joewhitsitt** [comment]
actually, i don't know if a token for node:status exists and a node moderation state token is not available yet.

https://www.drupal.org/project/drupal/issues/3225851
