### ISSUE TITLE
remove revision module paypal link

### ISSUE THREAD

**Issue by bewoldt** [uiowa/uiowa#6347]
# Problem
When deleting a revision I get to a page where I am asked to make a donation to the module owners paypal. Is there a way to remove this link? 

<img width="955" alt="image" src="https://user-images.githubusercontent.com/731952/231529895-a212e2b3-1c0d-436b-9437-0e54fd169c67.png">

# Steps to Reproduce

1. Edit any page that has historical edits
2. click on Revisions
3. select Delete from the dropdown next to a revision

**Comment by joewhitsitt** [comment]
This has been removed in the next version https://www.drupal.org/node/3336453 (alpha)

https://github.com/uiowa/uiowa/pull/6226#issuecomment-1535264036
