### ISSUE TITLE
Transition to api.icareatransit.org from api.ebongo.org

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6358]
# Story

As a web team, we should transition away from api.ebongo.org to icareatransit.org so that we can retire bongo.org and ebongo.org at the same time.

# Additional Info

The domain expires on 6/3/23 and we should have this done at least a week prior so that we can communicate to campus in advance of the domain expiration.

**Places using api.ebongo.org**
Signage
HC Signage
Hawktools
Dining

**Note**
It was mentioned that api.icareatransit.org seems quite a bit slower than api.ebongo.org. We should verify that using api.icareatransit.org doesn't cause any new issues.

# Proposed Solution

- [x] Update Signage and HC Signage
- [x] Update Hawktools
- [x] Update Dining
- [x] The prod site for icareatransit.org will need to be updated to reference api.icareatransit.org - CSI app devs will do this
- [x] Determine date to shut off DNS - May 22nd
- [x] Send comms to app dev community, web community any others that CSI needs to communicate with (Our transit partners)?
- [x] Request Hostmaster comment out these records until we are sure they are no longer needed.
- [ ] Let the domains expire assuming we don't learn of any reasons to renew
- [x] Have Hostmaster delete these records entirely.

**Comment by joewhitsitt** [comment]
Does the name need to be updated for any of the user interfaces?

**Comment by briand44** [comment]
>Does the name need to be updated for any of the user interfaces?

I believe it already has been with the exception of readme files and docs in code. If you know of a place, let's make it visible.

**Comment by briand44** [comment]
Initial Draft:

> Subject: Domains retiring
> 
> [App Dev Community,]
> [Web Community,]
> 
> We would like to inform you that the domains bongo.org and ebongo.org are being retired on May 22nd, 2023. If you are linking to bongo.org or ebongo.org, you should update your links to point to https://icareatransit.org prior to this date for your links to continue working.
> 
> If you have any questions or concerns, please reach out.
> 
> - OSC Web Team

**Comment by briand44** [comment]
Just a note in case we end up needing this - both domains currently are A records pointing to 128.255.102.218

**Comment by briand44** [comment]
sent an email to hostmaster to see if they are able to turn these off when we are ready since they use uiowa nameservers.

**Comment by briand44** [comment]
Hostmaster said they can comment them out for a few weeks and once we are confident they are no longer needed they can remove them entirely from their DNS records.

**Comment by briand44** [comment]
Marking this as blocked until May 22nd. At that time we can email hostmaster and have then "turn off" these domains assuming we don't have anyone reach out with concerns between now and then.

**Comment by briand44** [comment]
some comments prior to me being out.

>Both bongo.org and ebongo.org have been turned off. ebongo.org is expiring June 3rd. If anyone reaches out with major concerns between now and then about these domains going away we still have the option to renew. I would consult with the CSI app devs (Brandon Mills, Ted F, Mark H and potentially Tim E.) if something comes up that requires us to consider renewing. bongo.org doesn't actually expire until September but again it has been turned off. If it is determined we need to renew we may need to work with Kelly H. for payment information if the payment information on file with Hover is not up to date.
>
>I don't anticipate anything coming up, just wanted to share details just in case.

**Comment by briand44** [comment]
I'm going to mark this as complete. I let Hostmaster know they can permanently remove the DNS records and ebongo.org as already expired. bongo.org will expire in September but doesn't seem to make sense to leave this hang around until then.
