### ISSUE TITLE
Show closures in UIowa Hours

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6361]
# Story

As a site owner for Recreational Services, I would like to be able to display closures with details as to specific spaces so that we can represent to our users when a Facility is open but a specific court or other space is closed.

# Additional Info

>Right now our website simply displays closures when no hours are entered.  However, we have the option on the back end to distinguish between open and closed for our activity type so we would love to be able to show closures with details as to specific spaces, etc.

**Joe's comments related to this on Epic**
https://github.com/uiowa/uiowa/issues/4570#issuecomment-1500420781
https://github.com/uiowa/uiowa/issues/4570#issuecomment-1507647501 

# Proposed solution

**Comment by joewhitsitt** [comment]
Enough attention has been given to this with emails and meetings that it was just easy to knock out now that I know this is what we should use.
