### ISSUE TITLE
OnIowa Event API for Hawktools app

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6363]
# Story

As a Hawktools app owner, I would like to consume a JSON API/feed so that we can continue showing OnIowa events in the Hawktools app once we launch on SiteNow v3.

# Additional Info

**API for Hawktools**
We need to expose events in an API/feed for the Hawktools app to consume. Mark H. in CSI app dev group is the contact with questions about the feed.

I currently see the following on the existing site. I will confirm what is actually in use.
https://oniowa.uiowa.edu/api/hawktools/v1/events.json
https://oniowa.uiowa.edu/api/events.json
https://oniowa.uiowa.edu/api/highlighted.json

# Proposed Solution

- Expose endpoint at https://oniowa.uiowa.edu/api/hawktools/v1/events.json similarly to https://oniowa.prod.drupal.uiowa.edu/api/hawktools/v1/events.json

**Comment by joewhitsitt** [comment]
I think on similar issues I brought up the JSON API core module as a possible solution. I remembered we turned it off and found where/when that was done: https://github.com/uiowa/uiowa/issues/3179

Rick had mentioned that there were security considerations with using it and I think we could slice it smaller than turning it on for everyone and every entity type, keeping it read-only, etc. https://www.drupal.org/docs/core-modules-and-themes/core-modules/jsonapi-module/security-considerations

**Comment by joewhitsitt** [comment]
For #profdev, I enabled core's JSON API module with jsonapi_extras. Between the two I was able to keep it read-only, change the default path, disable all by default, enable just the event content type, configure what node data is available. Though the structure and properties change, this should be able to provide oniowa replacements for:

https://oniowa.uiowa.edu/api/hawktools/v1/events.json
https://oniowa.uiowa.edu/api/events.json

To provide more initial filtering (only upcoming, highlighted), I think https://www.drupal.org/project/jsonapi_views would have to be added and specific view displays be configured. Problem with that module is that I think all are exposed by default, so work would have to be done to update config for all existing view displays and to consider when creating new views.

**Comment by briand44** [comment]
From Mark H.

>The Hawktools app uses this endpoint:
>
>https://events.uiowa.edu/api/oniowa19
>
>The events application is using https://oniowa.uiowa.edu/api/hawktools/v1/events.json. I believe the events app does some post processing to the data before it makes it available at the .../oniowa19 endpoint. So, as long as the ...hawktools/v1/events.json endpoint were kept available, it should be fine.

**Comment by briand44** [comment]
Grooming conversation... Let's note any major changes to the existing endpoint so that the app devs can be aware and account for those changes.

**Comment by joewhitsitt** [comment]
>Grooming conversation... Let's note any major changes to the existing endpoint so that the app devs can be aware and account for those changes.

Looks like the structure changes quite a bit and not all fields are 1:1 matches. Is it just simply noting the differences or will we be required to massage the data a bit for oniowa?

NEW JSON API
<img width="754" alt="Screenshot 2023-06-26 at 10 17 00 AM" src="https://github.com/uiowa/uiowa/assets/4663676/8d755879-30e5-44c6-82e7-98941df711cb">


OLD JSON API
<img width="638" alt="Screenshot 2023-06-26 at 10 19 42 AM" src="https://github.com/uiowa/uiowa/assets/4663676/86c281a7-9f84-4ee6-b8d4-f10ea77e2484">

**Comment by briand44** [comment]
As long as all the data is available, I don't think we need to do any massaging at this point. We can share the endpoint with the CSI app devs and let them know structure and fields are changing and see if they are able to work with the changes.

**Comment by joewhitsitt** [comment]
Using this comment to start capturing the api old->new mapping:

```csv
hawktools_v1,sitenow_v3
events[id],data[drupal_internal__nid]
events[title],data[title]
events[required],data[field_event_attendance]
events[categories],data[field_event_category]
events[image],data[field_image][field_media_image][uri][url]
events[description],data[field_teaser]
events[long_description],data[body][value]
events[start date],data[field_event_when][value]
events[end date],data[field_event_when][end_value]
events[location],data[field_event_location][organization]
events[lat],data[field_event_geolocation][lat]
events[long],data[field_event_geolocation][lon]
events[status],data[field_event_status]
events[event type],data[field_event_attendance_mode]
```

`events[address]` is now split up within `data[field_event_location]` (address_line1, locality, administrative_area, postal_code)

**Comment by joewhitsitt** [comment]
was able to get referenced event categories and image using this URL after enabling the vocab, media image and file--file resources

`https://oniowa.uiowa.ddev.site/jsonapi/events?include=field_event_category,field_image.field_media_image&fields[event_categories]=name&fields[file--file]=uri`

**Comment by joewhitsitt** [comment]
This appears to be a winning endpoint with similar callback `https://oniowa.uiowa.ddev.site/api/node/event?include=field_event_category,field_image.field_media_image&sort=-field_event_when.value&jsonapi_include=1`

Added the jsonapi_include module to merge relationships in to simplify the structure. Also added a sort based on event date.

**Comment by joewhitsitt** [comment]
In EoD, it was mentioned that we should get ITS CSI AppDev visibility on this sooner than later. I will communicate with them tomorrow.

**Comment by joewhitsitt** [comment]
Sent an email to the hawktools developer this AM
