### ISSUE TITLE
SiteNow event categories

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6364]
# Story

As an OnIowa site owner using the SiteNow events feature, I would like to be able to have customizable event categories.

# Additional Info

We discussed bringing Admissions and ISWF along for the ride.

- Existing categories for OnIowa
     ![Screen Shot 2023-01-24 at 10 59 10 AM](https://user-images.githubusercontent.com/1017022/214358350-6c791fd5-41ec-42b4-a944-8a916473e6cf.png)

# Proposed Solution

**Comment by briand44** [comment]
Grooming conversation... Update event feature split to allow customizable taxonomy of event categories. Bring Admissions and ISWF back into this as well.

**Comment by briand44** [comment]
Webmaster and Publishers should be able to create/edit/delete these terms.

**Comment by joewhitsitt** [comment]
Admissions has these term pages public and webmaster/publisher have add/edit/delete permissions. If this is to bring things back to "default" we should probably match that for all.

Update hook to move select values to terms and update existing for ISWF will be needed.

**Comment by GaryRidgway** [comment]
What does this look like on the user end? As I am starting to spin this up, I am seeing that admisions has an autocomplete in the "Relationships" dropdown with tags, ISWF has checkboxes, and oniowa has nothing.

Do we want it to behave like Admissions, ISWF, or something else entirely?

**Comment by briand44** [comment]
We want to discuss with ISWF to see if they are ok with autocomplete like Admissions before we actually make this change in prod.

**Comment by briand44** [comment]
I'm not meeting with ISWF until Thursday after standup. I think we should avoid changes to ISWF since they are actively trying to get their site launched.
