### ISSUE TITLE
OnIowa event filters and theming

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6365]
# Story

As an owner of oniowa.uiowa.edu, I would like to have special filters for our event content and to group the events by day.

# Additional Info

**Display**
Would like filters for the following items:
- Attendance Required - Yes/No
- Category - Select List
- Event type - virtual/hybrid/in person
- select list of each day to filter by

They would like to group events by day on the display and output title and time similar to https://web.archive.org/web/20220815131834/https://oniowa.uiowa.edu/events

# Proposed Solution

- Determine if we want to make filters configurable by site webmasters or determine which should be in default vs custom to OnIowa
- See how we can handle the select list by day
- Add any additional theming
- Alter display for OnIowa to group by day

**Comment by bspeare** [comment]
Could we use the horizontal navigation here and set up 6 pages that use the events block with each date set?  Then the only custom work would be to add a "Date range" option to the Events block?  Or are we still unable to have blocks with exposed views filters on them?

<img width="470" alt="Screenshot 2023-05-10 at 1 31 44 PM" src="https://github.com/uiowa/uiowa/assets/1036433/807b9730-939b-45f3-8dc5-5f782deafe73">

**Comment by joewhitsitt** [comment]
Exposed filters is still out there https://github.com/uiowa/uiowa/issues/3804 and the events block uses custom functionality for this, not a views date range filter.

**Comment by briand44** [comment]
Grooming conversation... We discussed if making the filters configurable should be an option for the events feature. Presenters, Category, Attendance required, Date range, Attendance mode? This could cause some difficulties with theming.

Also discussed potentially outputting the attendance mode on teasers but decided to keep that out of scope of this issue

**Comment by briand44** [comment]
Also discussed potentially outputting the attendance mode on teasers but decided to keep that out of scope of this issue

**Comment by bspeare** [comment]
With all of these new filters, maybe we should switch to the sidebar filter like on https://github.com/uiowa/uiowa/pull/6502#issuecomment-1583056629?
