### ISSUE TITLE
As a SiteNow editor I can use a Banner without a gradient

### ISSUE THREAD

**Issue by bewoldt** [uiowa/uiowa#6368]
# Story

As a SiteNow editor I can add a Banner to a page without it have a gradient. Currently you have to option to select a gradient option as Dark (default) or Light. There are certain scenarios where I need to use a Banner without a Title so that I can have a flexible height image which would then not need a gradient.

One example. This section with image and content side by side looks fine of large screens because the image is larger than the content.
<img width="1516" alt="image" src="https://user-images.githubusercontent.com/731952/233426768-ea86ea93-9976-4b3c-b55d-b7937fd6a208.png">

but on smaller screens the image and content do not have equal heights.
<img width="967" alt="image" src="https://user-images.githubusercontent.com/731952/233427053-4b7dde49-9a69-4ff3-9076-c40f44bbff2e.png">

Using a Banner solves this issue since it is a background image with 100% height, but now I have a gradient I don't need.
<img width="1422" alt="image" src="https://user-images.githubusercontent.com/731952/233427456-60c95429-c8dc-4a8c-b2e6-aca2521dadaf.png">

# Proposed solution

Make the gradient required if there is a Title filled out.

**Comment by bspeare** [comment]
Since no fields are required on the banner block, it would make sense to add the `banner--transparent` class to banner if all fields are empty.  Here's the issue where we added that class: https://github.com/uiowa/uiowa/pull/4596.

**Comment by pyrello** [comment]
I think another solution for this would be to add an LB style and related CSS class for a new media format that works the way this is requested to work, with 100% height. We could add the media format LB style to the image block and I think that would fulfill this request.

**Comment by bspeare** [comment]
@bewoldt Would https://github.com/uiowa/uiowa/issues/6803 fix this issue for you?  We have an existing CSS class that we could use for this in the image block.

**Comment by bspeare** [comment]
@bewoldt I'm going to close this one in favor of https://github.com/uiowa/uiowa/issues/6803.  Please feel free to reopen this if you think that this specific issue still needs to happen.
