### ISSUE TITLE
Webmaster unable to view some unpublished content

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#6377]
# Problem
> I started a web article today titled, “Alumni Spotlight: Joe Wilensky” but I can’t find it now. I’m looking in Content and selected the Type (Article) and Published status of “any” and also “unpublished.” But it’s not coming up. I had this same problem last week with another “draft” document.
- Janet at SPPA

![image](https://user-images.githubusercontent.com/709009/234359828-40c8d277-7e95-4184-a94f-25f59725bcf3.png)

# Steps to reproduce
1. https://sppa.uiowa.edu/admin/content?status=2 and note the first two items.
2. https://sppa.uiowa.edu/admin/people?user=jabell and masquerade as `jabell`.
3. https://sppa.uiowa.edu/admin/content?status=2 and note the first two items are now missing.

# Proposed solution
1. Investigate to understand what the problem is.
2. TBD

**Comment by joewhitsitt** [comment]
Feels similar to https://github.com/uiowa/uiowa/issues/6338. Did you try clearing cache?

**Comment by cory-skeers** [comment]
> Feels similar to https://github.com/uiowa/uiowa/issues/6338. Did you try clearing cache?

Tried clearing the cache (locally), and no luck--was still able to recreate the issue. Looks like a different issue.

**Comment by cory-skeers** [comment]
Did a little more poking. Problem persists for all users without an administrator role (and locally, adding an admin role to another user and masquerading as them you can see unpublished content).

It also seems to be the case for all content types except for Opportunity, where a webmaster is able to see them.

Lastly, using direct links to the content, webmaster is able to view the content; it's only on the admin/content view where they cannot see it.

**Comment by joewhitsitt** [comment]
Uninstalling private_content from the site locally makes that content available to `jabell` Something with the module must be misfiring.

**Comment by joewhitsitt** [comment]
The user can still see the unpublished node https://sppa.uiowa.ddev.site/news/2023/04/test but just can't see it in the content overview where status_extra filter is applied "Filters out unpublished content if the current user cannot view it." Not sure where that filter is evaluated though

**Comment by joewhitsitt** [comment]
The readme of private_content, docroot/modules/contrib/private_content/README.md, warns that access checking for unpublished might not work correctly and references a d7 module that tries to explain it https://www.drupal.org/project/unpublished_access

Not sure where to go from here if private_content is to stay as-is

**Comment by briand44** [comment]
Grooming/Planning conversation... Investigate to see if we can resolve this, if not we could remove some access check on the content overview as a temporary workaround.

**Comment by joewhitsitt** [comment]
This seems like a better explanation than that other module was doing:

```
/**
 * STRATEGY
 * 1) Node grants are not helpful for this module because they give extra access, whereas we need to remove it.
 * 2) Hence use hook_node_access as far as possible.  In this hook it's easy to selectively remove access with NODE_ACCESS_DENY.
 * 3) However hook_node_access is not called for "node listings" - bulk read requests such as views.
 *    These must be handled via node grants.
 */
```

https://git.drupalcode.org/project/private_content/-/blob/8.x-2.x/private_content.module#L11-15

**Comment by e-marie-w** [comment]
Thank you @joewhitsitt! I've been trying to build something based off that other module, maybe this will help me understand what I'm doing wrong.

**Comment by e-marie-w** [comment]
Discoveries so far today:
- customer confirmed they could previously see unpublished content in the view.
- searching`AccessResult::neutral()` turned up [this](https://drupal.stackexchange.com/questions/247734/how-does-accessresultneutral-work#247737) which confirms it sometimes denies access. 
- that led to https://www.drupal.org/project/drupal/issues/2991698 which I'm still trying to comprehend.

Based on all that, I think recently we must've denied access in some specific case and `AccessResult::neutral()` is applying it to everything that isn't marked private. Only thing is the examples sound like they're talking about the node and not a view.

**Comment by pyrello** [comment]
I did some investigation into this today to try to understand what was going on better. I set some breakpoints to see what was going on and ultimately ended up with breakpoints at:
https://git.drupalcode.org/project/drupal/-/blob/9.4.x/core/lib/Drupal/Core/Access/AccessResult.php?ref_type=heads#L66
and
https://git.drupalcode.org/project/drupal/-/blob/9.4.x/core/lib/Drupal/Core/Access/AccessResult.php?ref_type=heads#L97

It appeared that the Layout Builder Operations Link module was triggering something, so I tried uninstalling it. No change in behavior. I was also getting a hit from the Masquerade module, so I tried uninstalling it. Also no change in behavior. At this point, when I'm logged in as the customer (using `drush uli`) and hitting the `/admin/content` page, I'm not getting any hits on the two breakpoints above, so it doesn't seem to be an issue where the access check is the problem.

My next point of investigation is going to be spending some time looking into how access is checked when views queries are run, as that seems like it would be relevant.

**Comment by joewhitsitt** [comment]
We talked about this in planning. Leaving open for others to continue to investigate, but otherwise move forward with the possible workaround... which... unfortunately did not work for me.

<img width="455" alt="Screenshot 2023-05-04 at 3 54 30 PM" src="https://user-images.githubusercontent.com/4663676/236327616-69f2e3bb-6d95-4365-9aa4-0011570e4c6c.png">

**Comment by joewhitsitt** [comment]
Here is a larger discussion I just found: https://www.drupal.org/project/drupal/issues/2971902
