### ISSUE TITLE
Cards showing up cached differently than configured

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#6383]
# Problem

After the card_4x deployment. Student life reported two instances on two different sites where individual cards within a list were displaying differently than configured. Clearing site cache and varnish cache worked for both instances.

# Background
https://iowaweb.slack.com/archives/C0164FNN1PV/p1682630789734159

![Screen Shot 2023-04-27 at 4 18 22 PM](https://user-images.githubusercontent.com/4663676/235460838-c420cafa-75dc-41f2-99ba-0393ee0f58e3.png)
![Screen Shot 2023-04-27 at 4 24 05 PM](https://user-images.githubusercontent.com/4663676/235460841-39d7218b-93cb-48af-8cc7-e018fe0e8667.png)

**Comment by cory-skeers** [comment]
Cropped up again:
> We’re noticing an error in our people lists. Some people in the list are showing up backwards compared to everyone else on the list. For example, the configuration block is set to “media on right, text on left” but some of the people being filtered in are showing up with their picture on the left and the text on the right.
It seems to change every day which people are affected. This error is only visible when logged out, viewing the page as the public would. When logged in as an admin, they look normal.
Here’s some examples of it:
https://engineering.uiowa.edu/industrial-and-systems-engineering/ise-people-research/ise-faculty-directory
https://engineering.uiowa.edu/civil-and-environmental-engineering/cee-people
https://engineering.uiowa.edu/people/me-people
Any thoughts on a fix? Thank you,
Hailey (hailey-boileau@uiowa.edu)

Streamed the logs while poking around a bit, and nothing stood out.

Locally, a full cache clear fixes it. In production, saving an individual person whose card is showing up with inconsistent styles fixes it for that person's card on other pages. Guessing that it's the clearing of the individual node's related cache tags that's fixing it, then.

Engineering has pretty extensive usage of people blocks on the site, and so it may be that a specific card style is being cached on the node from one list and carrying over to others, but I have not narrowed down a specific instance of this.

Examples:
<img width="1322" alt="image" src="https://user-images.githubusercontent.com/49074566/236928209-bae3c54a-2bbe-42c8-ba06-d3a77fd46663.png">

<img width="1329" alt="image" src="https://user-images.githubusercontent.com/49074566/236928323-2c9e18a4-62ed-44ef-8b1e-bc9a75a39632.png">

<img width="996" alt="image" src="https://user-images.githubusercontent.com/49074566/236928392-70ea3930-29a7-4f68-b976-13c5b42de79f.png">

**Comment by cory-skeers** [comment]
Looks like a recurring issue. Previously cleared/fixed examples have returned:
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/49074566/236934821-c21a48be-6498-4c23-98e0-0ccbabb2d2ae.png">
https://slc.studentlife.uiowa.edu/team
https://gpsg.uiowa.edu/about/meet-your-representatives

**Comment by joewhitsitt** [comment]
Since they seem to be reproducible, we may need to get this acting up in DEV so we can test it longer

My guess is that we will want to start looking around here: https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/uiowa_core/src/Entity/NodeBundleBase.php#L63

**Comment by cory-skeers** [comment]
Next steps:
Sync engineering.uiowa.edu to dev as a good test subject to recreate the issue. (engineering may be easier to recreate, but alternatively, if it can be reliably recreated using the studentlife examples, they may be easier to narrow down with fewer overlapping pieces)
Test patterns like a person being included in at least two separate, differently configured people blocks (and /people page), and see if the cache of one is being carried to the other. This was an issue during card_4x that was squashed, but may have cropped back up.
Dig through the layers of caching and determine which is the culprit.

And this:
> My guess is that we will want to start looking around here: https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/uiowa_core/src/Entity/NodeBundleBase.php#L63

**Comment by joewhitsitt** [comment]
Going to poke a bit locally

**Comment by joewhitsitt** [comment]
Looks like it is fairly easy to reproduce locally. Clear site cache. Go to https://engineering.uiowa.ddev.site/people (unauthenticated). Scroll down to 
James Andrews and Christoph Beckermann. Then load https://engineering.uiowa.ddev.site/people/me-people (unauthenticated) and notice that despite the block config, James' and Christoph's photo is now on the left.

**Comment by joewhitsitt** [comment]
@bspeare said in [slack](https://iowaweb.slack.com/archives/C0164FNN1PV/p1683831644037859?thread_ts=1683754256.811849&cid=C0164FNN1PV):
>removing these checks on https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/uiowa_core/src/Entity/NodeBundleBase.php#L61-L62 seem to fix the caching issue.

**Comment by joewhitsitt** [comment]
>I tried substituting $this->values[‘view’] for $this->view. Only certain views are sending that info along with the node at that time. So the view page doesn’t have it and then passes through with those caches key in place so then when you visit the the list block that whole section of code is not called. We either need to find another way to identify a view is involved or we should remove that check, unset if they exist and test caching so that we didn’t just open a hole where nothing gets cached. My hope is we are okay because there are several other layers before that code is called (page, block, view) where things are cached successfully and with the correct card styles.

**Comment by joewhitsitt** [comment]
I think I have determined the reason that articles is not affected but people are. Goes back to how the view is constructed. Articles view page is using content teaser which passes the view information along. People is using teaser via Rendered Entity which does not and needs to do so for exposed filtering and draggableviews. Early in card_4x my fix for this was to pass the view into the entity.

```php

function sitenow_people_views_pre_render(ViewExecutable $view) {
  if ($view->id() === 'people' && $view->current_display === 'page_people_table') {

    ...

    // Add the view object to each row entity for card rendering use.
    foreach ($view->result as $row) {
      if (isset($row->_entity)) {
        $row->_entity->view = $view;
      }
    }
  }
}
```

Since not all views are created the same, I don't think we can rely on the view info being there. We could implement some other kind of flag for all views but if the caching costs aren't too much, it might just make more sense to clear those keys anytime NodeBundleBase is called.
