### ISSUE TITLE
Classroom room migration updates

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6395]
# Story

As a Classrooms website owner, I would like the first image in our image gallery to be used as our featured image for migrated rooms in addition to the gallery.

# Proposed Solution

- [x] Update migration to map first gallery image to the featured image
- [x] sync dbs
- [x] re-run migration in dev

**Comment by joewhitsitt** [comment]
Going to see if I can figure this out

**Comment by joewhitsitt** [comment]
This was re-run in DEV
