### ISSUE TITLE
Implement fire log report similar to crime log report

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6397]
# Story

As a member of Public Safety and an owner of safety.uiowa.edu, we need to integrate the daily fire log reporting from Clery Edge in order to be Federally compliant.

# Additional Info

crime log issue #6217

link https://safety.prod.drupal.uiowa.edu/clery-edge-crimelog-test

https://iowa.sharepoint.com/sites/CSI-Drupal2/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FCSI%2DDrupal2%2FShared%20Documents%2FPublic%20Safety%2FExternalReports%2FExternalReports%2FFireLog&viewid=bf54b9d9%2D0975%2D4fbc%2D9f1b%2D6377bdc2307c

**Comment by joewhitsitt** [comment]
Testing will probably have to occur in DEV which has been marked as allowed upstream. Since it is domain/ip restricted I don't think there are issues with key security so I don't know if the block/module needs to capture any config related to it.

**Comment by joewhitsitt** [comment]
Was able to mimic a lot of what was done for the crime log. Recent doesn't seem to do the same thing. Go back to Jan 1, to get a result. https://safety.prod.drupal.uiowa.edu/clery-edge-firelog-test



![Image](https://github.com/uiowa/uiowa/assets/4663676/717a711e-174f-4941-b8d5-35686f6236d0)

**Comment by joewhitsitt** [comment]
And yes, the output comes with it's own `<br>` tags
<img width="337" alt="Screenshot 2023-05-18 at 10 37 11 AM" src="https://github.com/uiowa/uiowa/assets/4663676/aec9bf3d-12eb-4a1a-a29c-69fbffb1f16f">

**Comment by briand44** [comment]
Have a question out to Clery Edge support about the most recent endpoint not having any results. They said they would look into this more and follow up with us when they have additional info. Email in its-web inbox.

**Comment by briand44** [comment]
>We've investigated the firelog report issue and found a bug in our code. The fix has been implemented, and the issue will be resolved with the next PROD release, which is scheduled for early next week.

**Comment by joewhitsitt** [comment]
It feels like we are the first customers to actually implement their stuff..

**Comment by joewhitsitt** [comment]
So except for the upstream issue (on-load recent fire log), I feel like this is ready for technical review and should move to blocked waiting. It stops short of https://github.com/uiowa/uiowa/issues/6443 and just gets the firelog setup similar to the crimelog.

**Comment by joewhitsitt** [comment]
As @briand44 mentioned in standup, there is now at least one result showing for the "5 recent" on load display.

**Comment by bspeare** [comment]
Will this have no results text when https://github.com/uiowa/uiowa/issues/6397#issuecomment-1555248092 is fixed or should we add some no results text in the JavaScript?

**Comment by briand44** [comment]
I think whatever fix they were going to do has already been implemented. We probably need to add no results text ourselves.

**Comment by joewhitsitt** [comment]
should that be done for both as an a11y enhancement in #6443?

**Comment by briand44** [comment]
I think ^^ makes sense if we haven't already started this work.

**Comment by bspeare** [comment]
OK, I added a fix for the responsive table and added some simple no results text.  I think we can close this.

**Comment by joewhitsitt** [comment]
Thanks @bspeare . i see you added it to the crimelog too!
