### ISSUE TITLE
Facilities scheduled job

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6403]
# Story

As a Facilities website owner, I would like our building information to be updated at a regularly scheduled interval so our content can stay up to date and doesn't require interaction from us or a developer.

# Additional Info

My understanding is we currently have a drush command we can run to create/update buildings. Let's wire this up to a scheduled job.

Looking to see how often this currently runs but likely once a day is sufficient.

**Comment by bspeare** [comment]
Added this to `uiowa03` jobs at https://cloud.acquia.com/a/environments/117303-3d87eca7-89d1-47e2-84db-bc7ad52a9363/cron.

**Comment by bspeare** [comment]
I checked facilities this morning and there are imported rooms: https://facilities.prod.drupal.uiowa.edu/building/0018.

**Comment by bspeare** [comment]
From Splunk: `385 buildings were created, 0 updated, 0 deleted. That is neat.`
