### ISSUE TITLE
Update compliance with Facebook oEmbed API by 2023-05-16

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#6405]
We got a nastygram that if we don't properly show that we _aren't_ violating their terms with our use of the oEmbed API for Facebook and Instagram they will give us the boot. This API is required for the media embeds to successfully be requested and rendered.

# Resources

https://wiki.uiowa.edu/pages/viewpage.action?pageId=276466961

**Comment by joewhitsitt** [comment]
I am currently the only admin for the Facebook Developer account. Sean is pending. Anyone else interested in being on there, reach out with your facebook id in a DM and I will add you to the account.

During planning, updates to the privacy policy were mentioned. If we can't circumvent that request somehow, this might be a bigger issue than our team.

**Comment by joewhitsitt** [comment]
Logged in to add Ben and noticed a big popup that says they have introduced new "levels" of access for each feature and that we might only need to be on the basic level for our needs. the basic level doesn't have the app review process which we have had to provide details like a privacy policy for.

We might just be able to return to basic, test things and be done?! Fingers crossed

https://developers.facebook.com/apps/327906444997100/app-review/permissions/

**Comment by bspeare** [comment]
I changed this to "standard access" and all of our embeds stopped.   I have since switched it back. 

<img width="1285" alt="Screenshot 2023-05-05 at 9 52 57 AM" src="https://user-images.githubusercontent.com/1036433/236492997-e7faf792-2096-4a88-a935-1a919258d3bf.png">

Is this the one that you were hoping would work?

**Comment by bspeare** [comment]
> Please make the requested changes by 2023-05-16 09:00:00 PDT.
  
> We encourage you to request screenshots from us to determine the violating behavior. 

First step on this, should we request screenshots of our violating behavior?

**Comment by bspeare** [comment]
I have requested screenshots and a time extension so we can determine our next steps.

**Comment by joewhitsitt** [comment]
>Is this the one that you were hoping would work?

Yea.. :(

**Comment by bspeare** [comment]
The latest response:

To ensure your app and Privacy Policy are compliant with these standards, please update your Privacy Policy to include a clause/sentence that clearly states how Users can delete their Personal Data. Please also ensure to include one of the following within your Privacy Policy:

1.) A method for users to request the deletion of their Personal Data

2.) A clear statement that indicates users' Personal Data will be deleted upon request Failure to comply with these standards can result in your app being restricted.

**Comment by joewhitsitt** [comment]
Here are the v2/v3 usage stats to aid with our decision making process:

Facebook oembeds: 80 across all sites (27 on diversity)
Instagram oembeds: 154 across all sites (25 on pentacrestmuseums, 37 on diversity)

**Comment by joewhitsitt** [comment]
Sounds like Michael is making this visible higher up, but just wanted to capture a few other things from our meeting.

- Wordpress.com moved away from their oEmbed integration when the api key/app review was established. They do offer an alternative though. 
- https://www.drupal.org/project/media_entity_facebook/issues/3232041 is trying to adapt to offer a solution without app review, but I don't see a similar issue for instagram. existing entities would have to be re-saved. also, part of why oembed is so popular is that there is a more predictable call and response compared to these vendor specific one-offs.
- I have a link to ask the community if they are running into similar issues: https://drupal.slack.com/archives/C1VLTJJD8/p1683557637839399
- https://developers.facebook.com/docs/development/create-an-app/app-dashboard/data-deletion-callback/ makes it seem like there are non-website users of our app which i don't think is the case since there are private api keys to access it. perhaps there is a setting or a way to setup that would reduce the hoops we need to jump through.
- Neither module provides a "how-to" for getting the correct API settings.

**Comment by joewhitsitt** [comment]
Tried to create a basic app with basic oembed access but ran into the same bumps. Apps must be live to use without test users, privacy policy linked, etc.

**Comment by briand44** [comment]
Sprint 164... Make changes visible to team, update privacy page, notify Meta.
