### ISSUE TITLE
Informatics faculty page displaying current students and alumni

### ISSUE THREAD

**Issue by maramcconnell** [uiowa/uiowa#6406]
The faculty page for https://informatics.grad.uiowa.edu/faculty is also displaying current students and alumni.

**Comment by bspeare** [comment]
It looks this is using the standard people page which displays all person nodes: https://informatics.grad.uiowa.edu/admin/config/sitenow/sitenow-people.   They could either enable the filters to sort or disable the page and add a list block instead.
