### ISSUE TITLE
Uiowa MAUI module to feature split

### ISSUE THREAD

**Issue by makurj** [uiowa/uiowa#6407]
Move the uiowa_maui module to a feature split so it can be enabled per site. 

Annette Beck would like to recreate it on https://ucbasbls.prod.drupal.uiowa.edu/

Example: https://basbls.uc.uiowa.edu/

![image](https://user-images.githubusercontent.com/52135878/235951561-7a5c4f64-4999-440d-aee5-de686df4021e.png)

Please reach out to Annette when this is ready. Email flagged in ITS Web inbox.

**Comment by briand44** [comment]
Grooming conversation... Move module to a feature split and enable for https://ucbasbls.prod.drupal.uiowa.edu. Audit sites that have this in a split so we can tackle those later.

**Comment by makurj** [comment]
Looks like grad.uiowa.edu, housing.uiowa.edu and https://classrooms.prod.drupal.uiowa.edu/ have `uiowa_maui` enabled.
