### ISSUE TITLE
Set up Room import cron

### ISSUE THREAD

**Issue by cory-skeers** [uiowa/uiowa#6409]
# Story

As a Classrooms website owner, I would like our room information to update daily from MAUI so that our users are getting up to date information that doesn't require us to manually save all rooms. 

Follow-up to #6180.
Blocked until #6370 merges

# Proposed solution

Set up crontab for a daily run of the `classrooms_core:rooms_import` (`classrooms-rooms`) drush command created in #6370.

Note: This does not necessarily need to wait for the classrooms rooms migration to run in prod, as it only checks and updates for rooms that have already been created. Having it run prior to migration will just complete very quickly with no other effect on prod.

**Comment by joewhitsitt** [comment]
I don't think we have documented scheduled jobs previously, but there are already examples on a few of the applications that can be copied and modified.

**Comment by bspeare** [comment]
I've added the job to `uiowa` at https://cloud.acquia.com/a/environments/16667-6bcc006f-9a0e-425e-aba0-198585dd2b56/cron, should I paste the command here for someone to review or is it better to view the job on acquia?

**Comment by cory-skeers** [comment]
> I've added the job to `uiowa` at https://cloud.acquia.com/a/environments/16667-6bcc006f-9a0e-425e-aba0-198585dd2b56/cron, should I paste the command here for someone to review or is it better to view the job on acquia?

I've checked this out on ac. I haven't set up a job before, but comparing it to existing jobs and judging from the command it should be running, it looks ready to go.

**Comment by bspeare** [comment]
No results in Splunk for `index=uiowa-acquia "classrooms_core"`, but I did find one for the other facilities cron job.

**Comment by bspeare** [comment]
```
5/10/237:00:19.000 AM | <133>1 2023-05-10T12:00:19+00:00 web-33201 uiowa.drupal-watchdog - - - May 10 12:00:18 web-33201 uiowa[14531]: http://classrooms.uiowa.edu\|1683720018\|classrooms_core\|127.0.0.1\|http://classrooms.uiowa.edu/\|\|1\|\|Update batch operations ended.
-- | --
```

**Comment by bspeare** [comment]
This ran and can close.
