### ISSUE TITLE
Add sitenow identification for Help Desk

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#641]
This would help for site identification with HelpDesk tickets and doesn't seem like too intrusive. Could just be a link to the new SiteNow site.

Don't think this belongs in the uiowa_footer module.

**Comment by joewhitsitt** [comment]
I'd like to think about other options. meta info for example and then just train the helpdesk? I feel like custom sites will request it be "turned off" therefore making things difficult to identify again.

Whenever I have used a "free" website, one of the first things I always tried to do was remove the geocities, angelfire, blogger, wordpress branding

**Comment by joewhitsitt** [comment]
If anything, we need to require the placement of the site email in the page to comply with https://itaccessibility.uiowa.edu/policy/web which would also help reduce support tickets because the helpdesk can reach out to the siteowner first about content issues.

**Comment by richardbporter** [comment]
@GaryRidgway is working on a console.log message. If we train the HD going forward, I'm okay with this approach.

**Comment by joewhitsitt** [comment]
Is it going to say `SiteNow v2 (https://sitenow.uiowa.edu) - Now with more vitamins!`?

**Comment by richardbporter** [comment]
No.
