### ISSUE TITLE
SiteNow May 2023 Newsletter

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#6410]
https://sitenow.uiowa.edu/news/2023/06/updates-may-2023

### Issue/Solution
Provide a "release notes" type article of finished/done features/updates and publish to website, then send out dispatch email.

- [x] Create draft and update the parking lot card with an edit link
- [x]  Add "release notes" covering the month of v2/v3 default profile enhancements and webmaster/edit visible bug fixes.
- [x] See the previous month's article as an example.
- [x] Bullet points from demo stories slide per week: https://drive.google.com/drive/folders/1EehKUjxCbakaB9FchrGhAbaxuRbqyDGW?usp=sharing.. and/or from Web Community sprint demo announcements https://webcommunity.sites.uiowa.edu/updates/2023/02/sprint-demo-149-february-16-2023
- [x]  Get at least one team member to look over the draft before publishing.
- [x]  Since the draft was started earlier, adjust the publish date/time, publish, get the link to the article.
- [x]  Dispatch email with link to article. (To get access, send an email to [dispatch-support@uiowa.edu](mailto:dispatch-support@uiowa.edu) to have the account provisioned. Provide your hawkid and mention the CSI:drupal group)
  - [ ] Modify SiteNow Announcements Template (tweak opening line, update the article link, any other editorial adjustments)
  - [ ] Clone an old communication off SiteNow Announcements campaign
    - [x] Use SiteNow Announcements population, template, suppression list, bypass approval.
    - [x] Turn off Dispatch "test mode" to send out email.
    - [x] When scheduling, check the "archive" option so that there is an RSS instance we can use in the future. I don't think this can be done after the fact.
- [x]  Turn on Dispatch "test mode" after email is successfully sent.
- [x]  Take a moment to check dispatch and google analytics on whether these articles are being read.
- [x]  Create the next months's issue and copy all this bullet list into it, removing the checked boxes if any.

**Comment by joewhitsitt** [comment]
The article is available for review https://sitenow.uiowa.edu/news/2023/06/updates-may-2023

**Comment by bspeare** [comment]
The article looks good!

**Comment by joewhitsitt** [comment]
Thanks. I will move forward with sending it out this morning

**Comment by joewhitsitt** [comment]
<img width="1179" alt="Screenshot 2023-06-06 at 10 24 17 AM" src="https://github.com/uiowa/uiowa/assets/4663676/549cea2d-c732-42c7-bad7-b1fd306b59c9">

**Comment by joewhitsitt** [comment]
June - https://github.com/uiowa/uiowa/issues/6516
