### ISSUE TITLE
ISWF Events: Pager needed

### ISSUE THREAD

**Issue by makurj** [uiowa/uiowa#6414]
# Problem
Mike Cranston "They’ve entered in all the events (workshops) for a particular session, but they are not all showing up when they scroll down from the Session page. Is there a limit to the number of events it will show? And can that be changed?"

https://iowasummerwritingfestival.prod.drupal.uiowa.edu/event/96/weeklong-session-july-9-july-14-2023

Also see #6413

**Comment by joewhitsitt** [comment]
>Is there a limit to the number of events it will show? And can that be changed?"

Yep: https://github.com/uiowa/uiowa/blob/main/config/features/event/views.view.events.yml#L87

**Comment by makurj** [comment]
Thanks, Joe. Is this something we want to change or give control to the user over? More than 10 may make this already long page even longer: https://iowasummerwritingfestival.prod.drupal.uiowa.edu/event/96/weeklong-session-july-9-july-14-2023. Maybe a "Show more" button?

**Comment by joewhitsitt** [comment]
The IS points to the main events view which can be updated to use a pager. Just seems like an oversight compared to our other view pages. You are pointing to subevents on a event page which might have had different requirements at the time of development.

**Comment by makurj** [comment]
I should probably update the link to https://iowasummerwritingfestival.prod.drupal.uiowa.edu/event/96/weeklong-session-july-9-july-14-2023 because he does say "They’ve entered in all the events (workshops) for a _particular session_, but they are not all showing up when they scroll down from the _Session page_."

**Comment by makurj** [comment]
Update the main events view also to "show more" as part of this issue?

**Comment by joewhitsitt** [comment]
they are all the same view, different displays. if we update the main to use full pager and ajax, set it to update all displays it should solve it for all.

we probably should do a look back to through the issues to see if there was a reason why it was set to a limit of 10 for main, sub, events by presenter

**Comment by makurj** [comment]
Heard back from Mike: a pager would meet their needs.

**Comment by cory-skeers** [comment]
Looks like it was part of an earlier setup to limit to 10: https://github.com/uiowa/uiowa/issues/5968
> Limit number of items to 10

I don't see an explanation for why; I'd guess that it was a concern for if someone presented a lot, and possibly year after year, and ended up with a long list. But it does look like it was intended to be limited to the event presenters view but got applied to all. https://github.com/uiowa/uiowa/commit/4486b47a05e2960c46679733ee4867537a2ac4ca
