### ISSUE TITLE
Update event status visibility or badge color based on value

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#6417]
# Story

As a site visitor, if an event is scheduled, I am not sure I need to see that or if I should see it, that it should be green to indicate that it is open and continuing as planned.

# Proposed solution

- [ ] unset the field from render if the event status is scheduled
- [ ] show different colored badge than orange for rescheduled (gray?)

**Comment by briand44** [comment]
My thoughts are don't show the badge if it is scheduled, show the orange badge for cancelled and the green badge for rescheduled.

**Comment by bspeare** [comment]
<img width="600" alt="Screenshot 2023-05-05 at 8 08 01 AM" src="https://user-images.githubusercontent.com/1036433/236465916-24aba5e2-820b-4024-9fd7-ebcd8f1fadd3.png">

We probably want to update the placement of the badge on the full node (https://admissions.uiowa.ddev.site/event/5376/summer-hawkeye-visit-day).  Either below the date or at the bottom of the card?

**Comment by briand44** [comment]
I like it below the date

**Comment by GaryRidgway** [comment]
I like below the date as well because it lines up with how it is displayed on the event listing page
