### ISSUE TITLE
Assist with uihcsn01 setup

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6418]

**Comment by joewhitsitt** [comment]
Meeting is planned for 2pm. Unblocking

**Comment by joewhitsitt** [comment]
- app added to codebase
- main-build has successfully been mirrored across applications.
- MARCOM is going to work on SSL. 
- New Relic was not setup. 
- Log Forwarding needs assistance from ISPO. 
- Secrets added to dev/test/prod
- Authentication is ready for dev/stage and prod.


Working on getting develop-build to uihcsn01. Sounds like there will be a tagged release tomorrow.

**Comment by joewhitsitt** [comment]
this is done. latest release is on PROD. MARCOM got log forwarding setup and is working on SSL.
