### ISSUE TITLE
Update https://admissions.uiowa.edu/ar to read right to left

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6419]
# Story

As an Admissions website owner, we would like the content on https://admissions.uiowa.edu/ar to read right to left since it is in Arabic.

# Additional info

This page won't get a lot of traffic so they are looking for the simplest solution from us.

They are not currently concerned about this content being duplicate content or making sure we are appropriately letting search engines know the language of this page and which page it is duplicating.

They have reduced the components on the existing page to use mostly text areas but there are cards, a statistic and I believe a call to action.

# Proposed Solution

**Comment by bspeare** [comment]
I just looked at this again and I think the proposed solution is they can go into the page and add `<p dir="rtl">Text</p>` to their html elements used on the /ar page in the WYSIWYG source.  I've added an example to the first paragraph on the page and the browser reads the direction without any CSS changes required. 

@briand44 do you want to share this information with admissions and tell them that they can go into the page and make adjustments?

<img width="912" alt="Screenshot 2023-05-12 at 10 46 16 AM" src="https://github.com/uiowa/uiowa/assets/1036433/0db46c9b-ebb5-4797-b570-442e44bf56d0">

**Comment by briand44** [comment]
Let them know to give this a try. It looks like Katelyn is out until mid next week.

**Comment by briand44** [comment]
It looks like they have published this page so I am assuming there isn't anything needed from us at this point and am closing this issue. If they need further assistance we can reopen.
