### ISSUE TITLE
teaching strategy resources for teach.its

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6421]
# Story

# Additional info

https://itsteach.prod.drupal.uiowa.edu is their v3 site they are transitioning to. They want to launch by August 1st.

Existing resource content is at https://teach.its.uiowa.edu/resources/collections

They plan to get rid of all these documents and transition them to content. I believe they will have 30-40 pieces of content at most.

They may rename this to teaching strategies or something less generic than resources.

They will want to categorize these.

Here is an example of a teaching strategy piece of content they created https://itsteach.prod.drupal.uiowa.edu/supporting-difficult-dialogues

>A simple outline of a teaching strategies category and its associated content:  
> 
>
>- DEI
    - Supporting Difficult Dialogues
    - Using an Inclusive Syllabus to Build Connections with Students
    - Embracing Embodied Learning in Higher Education
    - Supporting Belonging in the Classroom
    - Environments That Support Belonging
    - Personalizing Syllabus DEI Statements
    - What Would You Do? Scenarios and Reflections for Instructors Preparing Inclusive, Equitable, and Trauma-Informed Classrooms

# Proposed solution

**Comment by briand44** [comment]
a mockup may be useful here to get feedback on if we can get enough information to put one together.

**Comment by bspeare** [comment]
For the teaching resources, I think we should try to see if they can use the `Topic page` feature.   I've asked Amanda to provide us with two Resource Collection categories and related articles so that we could set them up using the topic page.

**Comment by briand44** [comment]
We discussed recommending basic pages and tagging and enhancing functionality in the future with a page list block and exposed filters for list blocks. Closing this for now as work will continue in separate issues starting with https://github.com/uiowa/uiowa/issues/6550
