### ISSUE TITLE
Implement CSA Reporting form

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6426]
# Story

As a member of Public Safety and an owner of safety.uiowa.edu, we need to integrate the CSA reporting form from Clery Edge in order to be Federally compliant.

# Additional Info

Let's see if we can do this similar to the crime log issue #6217

link https://safety.prod.drupal.uiowa.edu/clery-edge-crimelog-test

https://iowa.sharepoint.com/sites/CSI-Drupal2/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FCSI%2DDrupal2%2FShared%20Documents%2FPublic%20Safety%2FExternalReports%2FExternalReports%2FCSAReports&viewid=bf54b9d9%2D0975%2D4fbc%2D9f1b%2D6377bdc2307c

**Comment by briand44** [comment]
We are trying to understand security/privacy concerns and if there are any fields that can be omitted and still be compliant. Lets try to strip things out and make it on brand similar to crime log report.

We should use a text area block to do this rather than the body.

**Comment by joewhitsitt** [comment]
https://safety.prod.drupal.uiowa.edu/clery-edge-csareports-test

**Comment by bspeare** [comment]
@briand44 is there a way for us to test this form and see if the data is coming through?

**Comment by briand44** [comment]
Good question. I'm guessing we don't have access to the data on Clery Edge side of things. Their support said:

>Once the report is submitted, you should be able to access the newly created incident report on the Clery Edge page under Incidents, CSA. This report should be automatically populated with the data from the external report.

I can reach out to the internal stakeholders here? Not sure if they will be able to grant us access but maybe can verify if data is coming through?

**Comment by bspeare** [comment]
Yes, please reach out and see if they can check?

**Comment by bspeare** [comment]
I started work on this at https://safety.prod.drupal.uiowa.edu/csa-reporting after not seeing the page Joe created.  It's currently unclear whether or not they are receiving all of the form data.   The Request Payload in devtools shows me some of the data, but not all of it.   Hopefully, we can get a look at what is being submitted.

**Comment by briand44** [comment]
submission messge:

CSA Report Confirmation Message
Your CSA report has been submitted to the Office of Clery Compliance. Please keep in mind this is NOT a police report. To file a report with law enforcement for follow-up and investigation, please call 319-335-5022. In an emergency, call 911.

**Comment by bspeare** [comment]
I was able to get the dates working with `moment.js` thanks @joewhitsitt!   I was also able to send a `jpg` so it might just be an issue about specifying file formats.

**Comment by bspeare** [comment]
Still to do:
- Find out required fields and the very least mark them with asterisk
- Find out file formats allowed and add help text
- Possibly add placeholder text

**Comment by bspeare** [comment]
@joewhitsitt I found the filter error by running xdebug on `FilterHtmlCorrector.php` - thanks for the tip!

**Comment by bspeare** [comment]
Ran xdebug on the form and found that `FilterHtmlCorrector.php` is finding a lot of errors.  At this point I am going to stop my investment in this and let someone else take a second look at this form.

**Comment by joewhitsitt** [comment]
taking a look

**Comment by joewhitsitt** [comment]
To illustrate the issue a bit, something like:

<img width="449" alt="Screenshot 2023-05-16 at 3 54 52 PM" src="https://github.com/uiowa/uiowa/assets/4663676/47c65627-ada0-42bb-a29b-ff1ad8367c85">

Is being stripped to 
<img width="406" alt="Screenshot 2023-05-16 at 3 54 27 PM" src="https://github.com/uiowa/uiowa/assets/4663676/b9260415-3c7e-4953-b7d1-7a94cc4549cf">

Over time, this is causing weird html nesting because nothing is properly closed. I was able to get that select to render correctly by moving it up in the form, but at the cost of something else not properly rendering.

We might have to move this to a custom block or consider removing that filter from our full_html format. Surprised we aren't seeing more of a problem with the crimelog.

**Comment by bspeare** [comment]
What are our options?
- Site split removing that filter from full_html format
- Add custom `safety_core` module to attach JS to the page
- Add code in custom block

**Comment by joewhitsitt** [comment]
all of those would be a split, so the "easiest" would be to split full_html for the site.

other options would be:

- remove the filter for all full_html in default
- construct a separate text format for default/admins only that passes it through
- look at re-writing their js to start with an individual and unknown individual and have "add more" buttons that duplicate the wrapping html and inner. as long as the values get passed correctly, we have some flexibility.
- try moving to webform with remote post handlers (still a site split, also PII issue of storing submissions in DB at least temporarily)

**Comment by bspeare** [comment]
Thanks @joewhitsitt, I think I might have this working with rewriting the individual and unknown individual js.

**Comment by joewhitsitt** [comment]
I took a peek. Nice work @bspeare 

Do you think we should do the same for crimelog and firelog or hold off until something isn't working as expected?

**Comment by bspeare** [comment]
I'd say that we hold off until something isn't working as expected.

**Comment by briand44** [comment]
We got a response from Clery Edge related to the required fields and supported file types. The email should be in its-web inbox. This is no longer blocked in my opinion so moving back to planned.

**Comment by bspeare** [comment]
I've added the required fields and supported file types text.

**Comment by bspeare** [comment]
I did some more investigation and it looks like the native form validation is not working because the submit button is using `type="button"`to perform actions of submitting each part of the form.    If the button used  `type="submit"`, then the native browser validation would work, but that would require us to rewrite their form submission JavaScript.

**Comment by bspeare** [comment]
I added some custom styles/JavaScript to highlight the required fields if they are left empty.  

@briand44 what do we want to do about the CAPTCHA request?

**Comment by briand44** [comment]
I'm not opposed to visiting the CAPTCHA request as a separate slice. That question came in after the issue was already in progress and I'm guessing they would want that on the other form we haven't built yet as well. So unless you have a quick and easy solution I would consider it out of scope of this slice.

**Comment by bspeare** [comment]
Thanks, I think it makes sense as a separate slice.

**Comment by bspeare** [comment]
I think this is ready for the customer to test: https://safety.prod.drupal.uiowa.edu/csa-reporting.

**Comment by briand44** [comment]
Since we have already shared the link with them and told them any additional testing would need to be done by them, I would be fine with calling this complete and opening up new issues for anything that comes up in the future.

**Comment by bspeare** [comment]
I've added the unaltered source code from Clery at https://safety.prod.drupal.uiowa.edu/test-csa-page.     The one thing I changed is `let BaseHref = "https://uat.cleryedge.com";` to `let BaseHref = "https://cleryedge.com";`.  

## Errors from https://safety.prod.drupal.uiowa.edu/test-csa-page

The submission error is the same, but maybe their jQuery date solution is not working here?

- POST Status Code: 400 Bad Request: Message : "Malformed Request Object"
  - All of the required fields are being filled out:
    - First name
    - Last name
    - Phone
    - Exact Date/Time
    - What is the specific location of the incident?

<img width="1502" alt="Screenshot 2023-07-19 at 11 29 21 AM" src="https://github.com/uiowa/uiowa/assets/1036433/563fadc1-1cf7-423b-8d87-dabcc5446287">
<img width="1244" alt="Screenshot 2023-07-19 at 11 28 50 AM" src="https://github.com/uiowa/uiowa/assets/1036433/b7206532-dd9e-4b5c-943a-e6e73bdb5e79">
<img width="1766" alt="Screenshot 2023-07-19 at 11 28 33 AM" src="https://github.com/uiowa/uiowa/assets/1036433/0e914eb2-1527-4a78-9ba6-0a2b6eecce7f">

## Errors from https://safety.prod.drupal.uiowa.edu/csa-reporting

<img width="1575" alt="Screenshot 2023-07-19 at 11 32 24 AM" src="https://github.com/uiowa/uiowa/assets/1036433/d8689fbb-561b-4c0b-b814-90936437595b">
<img width="1431" alt="Screenshot 2023-07-19 at 11 32 18 AM" src="https://github.com/uiowa/uiowa/assets/1036433/c96bb784-1604-44f5-a500-567280f25422">
<img width="1644" alt="Screenshot 2023-07-19 at 11 32 13 AM" src="https://github.com/uiowa/uiowa/assets/1036433/2e418367-369a-47c4-9a19-d1a82e3a9afe">
<img width="1548" alt="Screenshot 2023-07-19 at 11 31 28 AM" src="https://github.com/uiowa/uiowa/assets/1036433/846bf7c7-a7cb-46fb-b5d0-b8484a57d7e0">

If you are wondering if the "Invalid Date" option here is causing this, I also submitted with those dates entered as well.
