### ISSUE TITLE
Classroom search page enhancements

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6434]
# Story

As a Classrooms website owner, I would like to enhance the search/filtering capabilities on the Classroom search page so that users have a better experience finding what they are looking for.

# Additional Info

Search page - https://classrooms.prod.drupal.uiowa.edu/find-university-classroom

- They would like the ability to sort by occupancy asc/desc as well as building asc/desc - There is an example of this on the D7 Registrar site https://registrar.uiowa.edu/ucr-sps.
- They would like to be able to choose multiple items in the building, type, technology and room features filters.

# Proposed solution

- [x] Provide sort by functionality for occupancy and building
- [x] Allow choosing multiple options in filters
- [x] may need to adjust design of filters

**Comment by bspeare** [comment]
I was looking at the multiple options in the filters and getting this error when I tried to set the room type to multiple options:  https://www.drupal.org/project/better_exposed_filters/issues/3299926.

**Comment by briand44** [comment]
Grooming conversation.... See if these requests can be accommodated if we struggle we could see if it is needed for launch or if we just use a table display to make sorting easier.

**Comment by bspeare** [comment]
If we do add the sort options, let's place it outside the exposed form near the card grid so that it appears as more of a list control instead an advanced filter. 


<img width="1414" alt="Screenshot 2023-05-16 at 3 25 36 PM" src="https://github.com/uiowa/uiowa/assets/1036433/6422eb0b-87b5-4331-8524-49894f9ab3c1">

**Comment by bspeare** [comment]
Regarding the error in https://github.com/uiowa/uiowa/issues/6434#issuecomment-1545883719, I was able to get the Room Type checkboxes working if I removed the "Building" exposed filter.   The Operator > Value settings seem to be where this is breaking.  


<img width="1023" alt="Screenshot 2023-05-23 at 11 53 08 AM" src="https://github.com/uiowa/uiowa/assets/1036433/b83e2a82-c0cc-4389-9fa1-6045a963dc8d">

**Comment by joewhitsitt** [comment]
This probably has something to do with our custom code to turn config entity filters from string filter to dropdowns. `uiowa_core_config_entity_filter_select`

We have been watching a core issue that is supposed to provide better filter support, but I think config entities have been lost in the thread. https://www.drupal.org/project/drupal/issues/2429699#comment-14122220

**Comment by bspeare** [comment]
@joewhitsitt is it too late to switch the buildings to taxonomy?

**Comment by joewhitsitt** [comment]
I don't think it is ever too late. We will just want to make sure we are doing it for the right reasons and we are okay with the cost of doing so.

Here was some captured reasoning around the original decision: https://github.com/uiowa/uiowa/issues/5895#issuecomment-1307720073

I think there was this idea that other sites could use it and it didn't need editorial access and wasn't as "bloated" as node/taxonomy, but we have been burned by config entities at least twice now.

**Comment by bspeare** [comment]
Recap from grooming:

We discussed changing this from a config entity to a node or taxonomy import process.   Based on https://github.com/uiowa/uiowa/issues/6434#issuecomment-1559820196, I don't think these search page enhancements will work without making this change.

**Comment by joewhitsitt** [comment]
Taking a look at our existing noodle code to see if we can limp this a bit further along without biting off a refactor right now.

It makes sense to me that Room type is what makes things WSOD because the building is relying on that field to pass the necessary BEF bits to it instead of writing it all itself.

**Comment by joewhitsitt** [comment]
@bspeare and @e-marie-w,

Mind if I push a change related to https://github.com/uiowa/uiowa/blob/main/docroot/sites/classrooms.uiowa.edu/modules/classrooms_core/classrooms_core.module#L521-L560 that will make Room Type like the other multi selects?

Getting building to work the same is still unsolved.

**Comment by e-marie-w** [comment]
Go for it!

**Comment by joewhitsitt** [comment]
As close as I get, on load, the building filter is passing a string to an array party...

<img width="448" alt="Screenshot 2023-05-24 at 11 00 11 AM" src="https://github.com/uiowa/uiowa/assets/4663676/0125d3ef-f538-4a3a-99eb-938eb3d845e7">

**Comment by e-marie-w** [comment]
> As close as I get, on load, the building filter is passing a string to an array party...

And that is...bad, I'm guessing?

I just noticed a duplication issue. If I set type to classroom-computer, technology to apple air play, and features to a/c and whiteboard - glass, the same room is listed twice. I'm going to see if there's a reduce duplicates setting that will help.

**Comment by joewhitsitt** [comment]
I was able to get this a bit farther with setting the value on load to an array:

```php
/**
 * Implements hook_views_pre_build().
 */
function classrooms_core_views_pre_build(ViewExecutable $view) {
  $view_display = $view->getDisplay();
  $block_id = $view_display->display['id'];

  if (in_array($block_id, ['block_rooms', 'block_programmed_rooms_list'])) {
    if ($view->filter['field_room_building_id_target_id']->value === '') {
      $view->filter['field_room_building_id_target_id']->value = [];
    }
  }
}
```

At the very basic level though, a text filter does not handle the possibility of multiple values and that is where I am getting stuck because we are forcing that via BEF. 

docroot/core/lib/Drupal/Core/Form/FormBuilder.php's handleInputElement is processing not only the grouping checkboxes but then attaching each option as a separate checkbox. The value that is then passed on looks something like:

```php
'abw' => 'abw',
'bb' => 0,
...
```

instead of just the selected `abw`

As things stand currently, room type is now like the rest and buildings is better suited as a node/term for view filter purposes.

**Comment by bspeare** [comment]
@joewhitsitt is the next step / follow-up issue to change this from a config entity to a node or taxonomy import process?

**Comment by joewhitsitt** [comment]
if a multi-select building filter is _required_, then i believe so. i haven't reviewed the rest of the PR.

**Comment by joewhitsitt** [comment]
Looks like the code is working but they have bad API data that they should consider cleaning up:
<img width="655" alt="Screenshot 2023-05-25 at 8 45 03 AM" src="https://github.com/uiowa/uiowa/assets/4663676/c5468696-5255-47b1-95b4-effcc9bf9a8c">
<img width="639" alt="Screenshot 2023-05-25 at 8 45 08 AM" src="https://github.com/uiowa/uiowa/assets/4663676/c2df729a-c156-4e36-af4a-1ce6b2a23137">

**Comment by briand44** [comment]
I can let Classrooms folks know about this. It looks like there are other dupes similar to this as well.
