### ISSUE TITLE
Temporary redirect for safety.uiowa.edu

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6439]
# Story

As an owner of safety.uiowa.edu, we would like this domain and any paths off this domain to redirect to the homepage of https://police.uiowa.edu until we are ready to launch so that we can move forward with marketing safety.uiowa.edu on print materials.

# Questions

~Do we use vulture or .htaccess?~ We're going with .htaccess on 703

# Proposed solution

- [x] SSL coverage on uiowa703 for safety.uiowa.edu
- [x] add .htaccess redirect on 703 as 307 redirect
- [x] add safety.uiowa.edu domain on 703

**Comment by mjoneill** [comment]
Please use a 307 redirect for this.

**Comment by joewhitsitt** [comment]
Does this look correct to anyone?

```
RewriteCond %{HTTP_HOST} safety\.uiowa\.edu$ [NC]
RewriteRule ^ https://police.uiowa.edu/ [L,R=307]
```

**Comment by cory-skeers** [comment]
> Does this look correct to anyone?
> 
> ```
> RewriteCond %{HTTP_HOST} safety\.uiowa\.edu$ [NC]
> RewriteRule ^ https://police.uiowa.edu/ [L,R=307]
> ```

That looks generally correct to me, although admittedly not super confident in my htaccess stuff.

But, I also tested it with https://htaccess.madewithlove.com/, and it checked out.

**Comment by joewhitsitt** [comment]
That is where I wrote/tested it based on examples I saw on stackoverflow. Doesn't look to different than

https://github.com/uiowa/uiowa/blob/main/docroot/.htaccess#L109-L111 (removal of extra subdomain and 307 instead of 301)

**Comment by pyrello** [comment]
Because this involves the removal of an option from field storage config, I don't think we can simply remove the option because we'll get an error that prevents loss of data. If that is the case, we'll likely need an update hook that creates a new field, copies the data over to it, and then deletes the existing field.

**Comment by pyrello** [comment]
> Do we use vulture or .htaccess?

I'm not seeing where this has been answered in the comments

**Comment by joewhitsitt** [comment]
we updated the proposed solution with the htaccess option on 703. question is outdated

**Comment by joewhitsitt** [comment]
>Because this involves the removal of an option from field storage config, I don't think we can simply remove the option because we'll get an error that prevents loss of data. If that is the case, we'll likely need an update hook that creates a new field, copies the data over to it, and then deletes the existing field.

I think this is meant for #6485

**Comment by pyrello** [comment]
This is done.
