### ISSUE TITLE
Determine our plan for Wiki

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6442]
# Story

As a web team, we have a plan in place for our Wiki spaces for when the current wiki.uiowa.edu service will be removed in December 2023.

# Additional Info

**Options**

1. Move your content yourself to [another service](https://link.uiowa.edu/l/9b733e00-d6a9-4b4d-ae77-ff9965f09e88?m=f138818f-6e92-46f0-836d-5b8d55945f39&c=d.OTLT-EIT&i=202305)
2. Have the Office of Teaching, Learning and Technology (OTLT) [migrate your content to SharePoint](https://link.uiowa.edu/l/033a9ecf-7442-41aa-b752-9fcc93124229?m=f138818f-6e92-46f0-836d-5b8d55945f39&c=d.OTLT-EIT&i=202305)
3. [Purchase a Confluence (Wiki) license ](https://link.uiowa.edu/l/be6fef5a-bf65-4967-a79e-02f370c7b705?m=f138818f-6e92-46f0-836d-5b8d55945f39&c=d.OTLT-EIT&i=202305)from University of Iowa ITS. To determine what you have and the cost, visit the [Wiki Space and User Inventory page](https://link.uiowa.edu/l/79fbfc35-c699-42ba-b25e-90dc22eb2952?m=f138818f-6e92-46f0-836d-5b8d55945f39&c=d.OTLT-EIT&i=202305).

# Proposed solution

- [x] Capture both sitenow and drupaldev including page comments

**Comment by joewhitsitt** [comment]
> I think we should take advantage of OTLT's migration service even if it just becomes a read-only archived version of our internal docs.

https://github.com/uiowa/uiowa/issues/4270#issuecomment-1540458070

**Comment by joewhitsitt** [comment]
They have changed their banner from yellow to orange. Things are getting serious.

**Comment by joewhitsitt** [comment]
Added a note about capturing the comments as part of this. Some good stuff in those comments.

**Comment by briand44** [comment]
Grooming conversation... Request OTLT migrate our two spaces to Sharepoint. If we aren't happy with that we can always consider purchasing wiki licenses.

**Comment by briand44** [comment]
I have submitted the request for OTLT to migrate our two Wiki spaces. I also let them know we currently have some sort of SharePoint group and asked how that plays into this if at all.

**Comment by briand44** [comment]
>Yes, comments -do- migrate over as well.  Your Wiki space will be unchanged, but no changes you make there will carry over to the SharePoint after the migration – this is just taking what is currently in your Wiki and duplicating it in the SharePoint sites.

**Comment by briand44** [comment]
> I did some testing, but couldn’t figure out how to get our tool to migrate the content from your Wiki spaces into the already-existing SP site without overwriting your content.  Since I didn’t want to overwrite your existing content, the two sites I migrated can be found here:
>  
> https://iowa.sharepoint.com/sites/Drupal-7-ITS-Docs
> https://iowa.sharepoint.com/sites/drupal-developer-documentation/
>  
> I did a quick spot check and everything appeared to have migrated okay, but we do ask that you take a look and confirm for us that there isn’t anything notably missing from the migration.

**Comment by joewhitsitt** [comment]
With some spot checking, it appears to have brought over the things I was concerned about (images, rick's sidebar content, plain text formatting, comments)

In terms of next steps though, it would be nice to somehow bring this into our Teams area (at least link out to it) and build new docs there or find [a new home for it](https://github.com/uiowa/uiowa/issues/4270#issuecomment-1448495956).

**Comment by joewhitsitt** [comment]
Welp. It isn't exactly clear to me how to add a new page within our current nav structure..

Trying to find a spot to post this: https://data.uiowa.edu/item/424315701/data

**Comment by briand44** [comment]
I got it posted but there has to be a better way than what I did. After I added a new page I noticed you had already created one so I deleted yours 😁 

https://iowa.sharepoint.com/sites/drupal-developer-documentation/SitePages/Miscellaneous/EI%20Active%20Server%20Inventory.aspx

**Comment by joewhitsitt** [comment]
Yeah but how does one create a folder to keep related assets tidy...

https://iowa.sharepoint.com/sites/drupal-developer-documentation/SitePages/Forms/ByAuthor.aspx?viewpath=%2Fsites%2Fdrupal%2Ddeveloper%2Ddocumentation%2FSitePages%2FForms%2FByAuthor%2Easpx

**Comment by briand44** [comment]
Yeah, I struggled with that and accidentally renamed the miscellaneous folder while trying to create a new folder so I gave up on that before I really messed something up

**Comment by briand44** [comment]
Maybe we should transition these docs into our web services Sharepoint group using oneNote?

**Comment by mjoneill** [comment]
Confirmed personal access.  Did not try reconciling how comments got migrated, etc...
