### ISSUE TITLE
Facilities map on building pages

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6444]
# Story

As a Facilities website owner, I would like our Facilities map to be displayed on each of our building pages since that map is more up to date than Concept3D map.

# Additional info

It sounds like we can pass in a lat/long (from bizhub api for each building) for a center point and render the map embed for each building. Joe put together a code example https://codepen.io/joewhitsitt/pen/yLRjgOJ.

# Proposed Solution

- [x] Programmatically construct iframe object from lat/long in Bizhub API
- [ ] Factor in zoom level
- [ ] Not sure if we need to use css in codepen
- [x] Place at bottom of building pages like in mockup

**Comment by briand44** [comment]
I need to reach out to ask where the lat/long is coming from in the bizhub endpoints to make sure those are not null and up to date when new buildings become available.

**Comment by joewhitsitt** [comment]
Jay provide these zoom levels that we could test against to find the happy medium for most buildings on campus for the space on the page. The codepen example above is "9"

![E096D840-C43C-412B-9722-8090C6E546B6](https://github.com/uiowa/uiowa/assets/4663676/f70f0289-ac86-49e8-8447-8195de678e71)

**Comment by briand44** [comment]
Grooming Conversation... Possibly block plugin that is placed in the layout that fetches stored lat/long values captured from API call. Some buildings don't currently have lat/long so we want a decent fallback.

**Comment by bspeare** [comment]
Is this what we want to use for the API call to grab the lat/long?  https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/uiowa_facilities/src/FacilitiesAPI.php

**Comment by joewhitsitt** [comment]
I guess I imagined this would be another field captured with the facilities_core functionality which leverages the uiowa_facilities API. I know that isn't what the proposed solution says, but all other data is captured that way.

docroot/sites/facilities.uiowa.edu/modules/facilities_core/src/BuildingItemProcessor.php
docroot/sites/facilities.uiowa.edu/modules/facilities_core/src/BuildingsProcessor.php
