### ISSUE TITLE
Facilities fields for project data coming from API

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6447]
# Story

As a webteam, we would like to have structured fields for the project data coming from the Facilities APIs so that we can store this data similar to how we are storing the building information.

# Additional Info

We currently have a project content type with fields that will be manually populated.

Current code example on 702 `/docroot/sites/www.facilities.uiowa.edu/modules/custom/facilities_projects/includes/facilities_projects.single_project.inc`

single project endpoint - https://buildui.facilities.uiowa.edu/buildui/ext/projectinfo?projnumber=0897601
projects by building endpoint - https://buildui.facilities.uiowa.edu/buildui/ext/projects?bldgnumber=0025
capital projects endpoint - https://buildui.facilities.uiowa.edu/buildui/ext/capitalprojects
featured projects endpoint - https://buildui.facilities.uiowa.edu/buildui/ext/featuredprojects

**Info coming from API - don't need add/edit ability**
- [ ] Title - `buildingName . ' ' . projectTitle` is currently being used on the project page. Building page outputs `buiProjectId - projectTitle`. Capital and Featured projects pages outputs `buildingName . ' - ' . projectTitle`
- [x] Project Number - looks like these are always a number - `buiProjectId`
- [x] Project Scope - plain text text area - `projectScope`
- [x] Project Status - text? I've seen examples of "Construction" and "Design", there could be others `projectStatus`
- [x] Square Footage - number - `number_format($d, 0, '.', ',')` - `grossSqFeet`
- [x] Estimated Cost of Construction - needs to support both numbers and text (e.g. "TBD"). if `is_numeric` we want to output `'$' . number_format($d, 2, '.', ',')`
- [x] Construction start date - data comes over as unix timestamp output as `format_date(($d / 1000), 'custom', 'F Y')` comes from `constructionStartDate` - it can be `null`
- [x] Substantial Completion Date - similar as above - comes from `substantialCompletionDate`
- [x] Pre Bid Date - similar to other date fields  - `preBidDate` - looks like only output if is greater than today
- [x] Pre Bid Location - assume text? - `preBidLocation` - looks like only output if pre bid date is greater than today
- [x] Bid Date - similar to other date fields - `bidOpeningDate` - looks like only output if pre bid date is greater than today
- [x] Awarded To - text - `vendorName`
- [x] Architect(s) - text - `primaryConsultant`
- [x] Building - reference field
- [x] Building alt - text field
https://buildui.facilities.uiowa.edu/buildui/ext/projectinfo?projnumber=0660601 is an example where there is a building related to this project but the building doesn't exist currently on the Facilities website.

# Proposed Solution

- Create fields listed above.
- Build upon docroot/modules/custom/uiowa_facilities/src/FacilitiesAPI.php to establish calls to project endpoints
- Extend EntityProcessorBase in uiowa_core to move data into fields
- Disabling fields populated from API so it can't be manually added/edited

**Comment by joewhitsitt** [comment]
Meeting notes:

- Sounds like they have been working on including outdoor spaces, changing UIHC projects and making sure the right checkboxes have been checked to make featured projects more accurate.

**Comment by briand44** [comment]
Grooming Conversation... Discussed having both a building name text field and the building reference field. We would using text field in title where needed. Building reference would be used to show projects on the building page. Projects can live in more than one of the endpoints so we will want to use the projectID as a unique identifier and make sure we don't have dupes. Not much theming currently but let's keep that separate from this slice. Displaying project info on buildings is also out of scope for this slice

**Comment by pyrello** [comment]
Whomever picks up this work should review the previous PRs where we set this same functionality up for buildings. There were a lot of gotchas in terms of how data can change that we need to test for to ensure that we aren't inadvertently letting data get stale. It would be good to articulate for each field being added how the data might change over time (e.g. no value => value, value => no value, value => different value) so that we can make sure we are covering those cases during development and testing.

**Comment by pyrello** [comment]
Previous work to review:
- https://github.com/uiowa/uiowa/pull/6076
- https://github.com/uiowa/uiowa/pull/6370
- https://github.com/uiowa/uiowa/pull/6449
- https://github.com/uiowa/uiowa/pull/7093

**Comment by briand44** [comment]
From Facilities:

>It’s more important that the project info updates in more “real-time” than the buildings if possible. As soon as bid information, budgets, etc are available, multiple stakeholders look for it on the project pages. Is it cumbersome to set it up that way? If so, maybe twice a day is a good compromise

**Comment by bspeare** [comment]
Remaining work:

- [ ] `Biomedical Research Support Facility - Expand Facility` creates a node even though https://buildui.facilities.uiowa.edu/buildui/ext/projectinfo?projnumber=0941301 is empty. 
- [x] `Van Allen Hall - Replace Roof` is not being included as a capital project, I am getting 90 capital projects when there should be 91. 
- [ ] Find the total count of projects from the endpoint and compare that against what is imported.

**Comment by briand44** [comment]
Does the import currently remove/unpublish items as well? So if the drush command runs and imports a project but then the project gets removed from the endpoint, does the project get removed/unpublished from the site the next time the import runs?

**Comment by joewhitsitt** [comment]
>Does the import currently remove/unpublish items as well? So if the drush command runs and imports a project but then the project gets removed from the endpoint, does the project get removed/unpublished from the site the next time the import runs?

i assume so since it is based on the same facilities building stuff. would be nice to test if we can find one and coordinate with facilities
