### ISSUE TITLE
Update uiowa blt to be flexible with multiple acquia organizations

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#6455]
# Problem

Our current multisite/git commands have hardcoded calls to the uiowa organization on Acquia. If we are to share our SiteNow platform across orgs, we should considering adapting our code to work with the Healthcare organization as well.

# Background

In setting up uihcsn01 for UI Healthcare, we realized the application is not available for the following commands:

- [umc](https://github.com/uiowa/uiowa/blob/main/blt/src/Blt/Plugin/Commands/MultisiteCommands.php#L440) (create)
- [umd](https://github.com/uiowa/uiowa/blob/main/blt/src/Blt/Plugin/Commands/MultisiteCommands.php#L292) (delete)
- [umt](https://github.com/uiowa/uiowa/blob/main/blt/src/Blt/Plugin/Commands/MultisiteCommands.php#L738) (transfer)
- [ugd](https://github.com/uiowa/uiowa/blob/main/blt/src/Blt/Plugin/Commands/GitCommands.php#L95) (deploy)
- ?

There might also be an issue when the [update sites replace](https://github.com/uiowa/uiowa/blob/main/blt/src/Blt/Plugin/Commands/ReplaceCommands.php#L30) code fetches a list of multisites to run through.

# Workaround

Do these things manually, which might mean we will want to invest in creating and maintaining a fallback set of instructions. These would be helpful if there is a technical issue with one of them or with our CI where we need to do steps manually.

# Proposed Solution

TBD

**Comment by briand44** [comment]
blocking until leadership has a chance to touch base on this.

**Comment by joewhitsitt** [comment]
If there was just one org for applications running sitenow, this wouldn't be a problem. For example, if we "owned" the application within our org and they "manage" it/reserved for their sites, no changes are needed.

**Comment by joewhitsitt** [comment]
As Sean hinted, another piece of this might be that UIAcquiaGithub needs access to the Healthcare subscription. It has a special "Service Accounts" role that has limited permissions.

**Comment by pyrello** [comment]
We are missing an entry in our blt config under `uiowa.applications` for the new `uihcsn01` application. I started a PR to fix this: https://github.com/uiowa/uiowa/pull/6474. With the change in that PR, when running `blt ugd`, the `uihcsn01` application shows up, but then fails with an error saying I might not be authorized. Looking at the code that runs up to this point, I see that a key and secret are pulled from blt config settings. The key and secret are necessarily unique to each developer and stored in `local.blt.yml` to prevent exposing them. I do not currently have access to the application, so I'm assuming it is failing to connect based on that.

**Comment by joewhitsitt** [comment]
With application access I was able to see uihcsn01 during `umc` this week and was just able to run `ugd` this morning which automatically checked out the release in prod for uihcsn01. Assuming we can figure out a reasonable set of permissions, I don't this is an issue anymore.
