### ISSUE TITLE
Alternate recommendations for Iowa Now resources

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6458]
# Story

As an Iowa Now site owner, I would like recommendations on how to better display a growing list of resources.

# Additional Info

Resources page (https://now.prod.drupal.uiowa.edu/resources). 

>Had a discussion last week with Tricia and Jack about web strategy and this page was also discussed. Iowa Now team’s question was: Is there a better solution or recommendation for this content on this page other than using cards as this resource list gets larger in the future?

# Proposed Solution

- [x] provide recommendations or a mockup/prototype of an alternative option than using cards.
- [x] Share with Tricia and Jack and get feedback

**Comment by briand44** [comment]
If our recommendation is to link elsewhere rather than having this page of resources, that is fine but lets accompany that recommendation with an alternate option to cards as well.

**Comment by bspeare** [comment]
A few suggestions:

- Update these to use the left or right aligned card, remove the border, and make these look like article lists to make the page more compact and easier to read/scan.  Add an anchor menu to the top of the page. 
- Move to the `topic_page` feature.
- Link off to the uiowa.edu A-Z list.
  - Maybe there is work we could do on the A-Z list to allow for images and categories like these?
- Implement a jump menu block like https://github.com/uiowa/uiowa/issues/6420#issuecomment-1548536195 that takes user to separate resource pages. 
- Update the area of study feature to be more of a generic "Resource finder" tool: https://github.com/uiowa/uiowa/issues/3837.

**Comment by GaryRidgway** [comment]
@bspeare and I worked on this today. We decided that the `topic_page` feature would be really nice for this, so we made some content on dev to try it out. A benefit of this option is that it allows us to utilize a premade content type that is made for something similar to this. 
		Enchancements needed would be to:
			- Have the topic_page links respect the article's external links, and if needed, have an image for each topic. I think the image is extraneous, and we could probably make an argument that the images are not helpful to navigating dense information, and thus only serve to elongate the page.
			- Scope the search to the page, or the described tags. Currently, It just searches the whole site.

https://now.dev.drupal.uiowa.edu/resources-0

**Comment by GaryRidgway** [comment]
[Click here for material on this issue](https://iowaweb.slack.com/archives/C0164FNN1PV/p1685115169140089)

**Comment by mkyoder** [comment]
The updated resources page is now available here: https://now.prod.drupal.uiowa.edu/resources. I have one question on this for @GaryRidgway 

My question is: Is the reason that these cards are slightly off is because of the text contained on the cards themselves? For example, adding an additional sentence to one card versus another would throw off the card alignment.

**Comment by GaryRidgway** [comment]
> The updated resources page is now available here: https://now.prod.drupal.uiowa.edu/resources. I have one question on this for @GaryRidgway
> 
> My question is: Is the reason that these cards are slightly off is because of the text contained on the cards themselves? For example, adding an additional sentence to one card versus another would throw off the card alignment.

Correct, so for things like the titles of the groups and the number of sentences on a card, those things can affect the cards that come after them. 

Perhaps you could suggest some small changes to the Now team of ways to shorten the copy for those cards to allow them to come more in line with each other?

**Comment by mkyoder** [comment]
Shared updated Resources page with Tricia via email and provided suggestions to make copy similar on all card content types in order to come more in line with each other.

**Comment by mkyoder** [comment]
Tricia presented the Iowa Now prod site the other day to OSC staff at a staff meeting and I didn't hear anything else back from her for additional changes. So I think this is done now.
