### ISSUE TITLE
Typos in tour text

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#646]
https://github.com/uiowa/uiowa/blob/master/docroot/profiles/custom/sitenow/config/sync/tour.tour.getting-started.yml#L37

https://github.com/uiowa/uiowa/blob/531f7e6ca480a6a8c20d41c931c323986cdc32a4/docroot/profiles/custom/sitenow/config/sync/tour.tour.content-add.yml#L22

**Comment by dnkemper** [comment]
Fixed it in [i523](https://github.com/uiowa/uiowa/pull/611)
