### ISSUE TITLE
`uiowa_maui` feature follow-up tasks

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#6462]
# Story

As a developer, I am able to enable the uiowa_maui feature for a website without establishing a site split.

# Proposed Solution

Now that the `uiowa_maui` feature is out there (https://github.com/uiowa/uiowa/pull/6446), we need to clean up the site splits of the MAUI module so that a split isn't needed for the feature to be on:

- https://github.com/uiowa/uiowa/blob/main/config/default/core.entity_view_display.node.page.banner.yml
- https://github.com/uiowa/uiowa/blob/main/config/sites/classrooms.uiowa.edu/config_split.config_split.site.yml
- https://github.com/uiowa/uiowa/blob/main/config/sites/classrooms.uiowa.edu/core.entity_form_display.node.room.default.yml
- https://github.com/uiowa/uiowa/blob/main/config/sites/grad.uiowa.edu/config_split.config_split.site.yml
- https://github.com/uiowa/uiowa/blob/main/config/sites/grad.uiowa.edu/config_split.patch.core.entity_view_display.node.page.default.yml
- https://github.com/uiowa/uiowa/blob/main/config/sites/housing.uiowa.edu/config_split.config_split.site.yml

**Comment by pyrello** [comment]
Noting that this is also going to require turning on the feature split for:
- grad.uiowa.edu
- housing.uiowa.edu

**Comment by pyrello** [comment]
Not sure if I would choose to update https://github.com/uiowa/uiowa/blob/c4d8cc842109fdc6f9b7efee62157130e0b637c7/config/default/core.entity_view_display.node.page.banner.yml#L86 based on the move from site to feature splits.

**Comment by joewhitsitt** [comment]
From https://github.com/uiowa/uiowa/issues/6407#issuecomment-1545901314 would classrooms.uiowa.edu need it too?
