### ISSUE TITLE
Attendance required for events

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6469]
# Story

As a SiteNow events creator, I would like to be able to designate if attendance is required for events on our website since so participants of OnIowa events know which events are mandatory.

# Additional Information

- Boolean field (Yes/No) to designate if attendance is required
- Output on full node
- Should we output on teaser? They will have the ability to filter based on this value in a future slice so I am not sure if it is needed. Their current site has an asterisk before the event title on the event search page https://web.archive.org/web/20220815131834/https://oniowa.uiowa.edu/events

# Proposed Solution

- [x] Add boolean
- [x] Output on full node
- [ ] Output on teaser?

**Comment by makurj** [comment]
Do we want to display this field on iowasummerwritingfestival and admissions?

**Comment by cory-skeers** [comment]
> Do we want to display this field on iowasummerwritingfestival and admissions?

Is the display always on (as in, if an event is not required, it says so?). My thought would be if that's the display, it maybe should only be on oniowa, but if it only shows up if an event _is_ required, then we can just display on all, and if admissions/iswf don't turn it on for any event, then there's no change.

**Comment by briand44** [comment]
>but if it only shows up if an event is required, then we can just display on all, and if admissions/iswf don't turn it on for any event, then there's no change.

It should only show up if it is required, therefore show it on all sites by default as Cory mentions.

**Comment by makurj** [comment]
Currently, the field is on to always display on the node for default and oniowa. I'm not sure I understand what you mean by "but if it only shows up if an event is required'. Do you mean if the **attendance** is required for an event, and in that case it displays on all sites?
