### ISSUE TITLE
Classrooms room schedule display pager?

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6476]
# Story

As a classrooms website owner, I would like our room schedule to be paginated or scrollable so that when there are many items it doesn't push the rest of the content down the page.

# Additional info

Example https://classrooms.prod.drupal.uiowa.edu/ucc-1100

# Proposed solution

- pager or scroll

**Comment by joewhitsitt** [comment]
See `createPager` in sitenow_events as an example of pagers for content that doesn't live in the db. https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/sitenow_events/sitenow_events.module#L262-L274

It was brought up in grooming that scroll seems like the smallest slice, but is inconsistent with our patterns so far and could present problems for mobile as all of the content within are linked cards.

**Comment by bspeare** [comment]
Scroll-driven animation might be nice enhancement if we want to implement a scrollbar:

- https://codepen.io/bramus/pen/oNYEgEQ
- https://scroll-driven-animations.style/demos/contact-list/css/

**Comment by joewhitsitt** [comment]
was this planned as developer choice?

**Comment by briand44** [comment]
That is my understanding.

**Comment by joewhitsitt** [comment]
Going to try to implement the pager similar to https://github.com/uiowa/uiowa/issues/6476#issuecomment-1568963945. Stop me if you feel strongly otherwise.
