### ISSUE TITLE
Additional Classroom updates

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6477]
- [x] alphabetize order of rooms on unit pages - https://classrooms.prod.drupal.uiowa.edu/units/office-registrar
    - see if there is a workable solution without a split, otherwise split it.
- [x] Building names - lower case `and, of`
- [x] ~alphabetize order of technology features~ done
- [x] display number of results on search page - this is a nice to have not absolutely necessary.
- [x] display 4 items on room schedule rather than 3
- [x] remove extra space before colon as seen in https://github.com/uiowa/uiowa/issues/6477#issuecomment-1592069474
- [x] lessen space between sections as seen in https://github.com/uiowa/uiowa/issues/6477#issuecomment-1592069474

**Comment by e-marie-w** [comment]
Yesterday I looked into some of these. There's a customizable Result summary that can be added to the header or footer of a view, that displays like this: 

![Screenshot 2023-05-25 at 9 24 04 AM](https://github.com/uiowa/uiowa/assets/68179015/f4326b15-1696-489d-9b93-52a06253f3c8)

**Comment by joewhitsitt** [comment]
>Alphabetize on unit pages is a taxonomy view change from created…

**Comment by joewhitsitt** [comment]
If we can't push back, a TVI setup for this vocab that calls a custom view (alpha, count) sounds like the smallest slice. Not a fan of the TVI/split burden though.

An exposed filter on taxonomy_term view default (platform-wide) might work but could be useless for some vocabs and/or break on large results like Iowa Now's featured news.

**Comment by joewhitsitt** [comment]
They came to us with a couple more items:

- Change the schedule pager to 4 items.

- There seems to be trailing spaces here before the colon. Quick fix to the human readable label?

![thumbnail_image005](https://github.com/uiowa/uiowa/assets/4663676/c00ba035-0ed4-4ff8-9efb-ffaa9d4f56ae)

- The would like the space "lessened" in this particular area between details and tech features

![thumbnail_image006](https://github.com/uiowa/uiowa/assets/4663676/a9fd9c06-6001-48a1-a802-94fbac272a8e)

**Comment by joewhitsitt** [comment]
Not sure what is causing this label to have a space. I thought it was just a missed space on the field config.

<img width="1040" alt="Screenshot 2023-06-15 at 10 46 32 AM" src="https://github.com/uiowa/uiowa/assets/4663676/b1c57486-a34e-4142-b327-668d9b1af709">

**Comment by bspeare** [comment]
~~@joewhitsitt We probably just need to adjust this: https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/scss/fields/fields.scss#L9~~

Or not, I see your point.  That extra space is weird.  It's not on other fields like "Research Areas:" here: https://now.prod.drupal.uiowa.edu/person/karim-abdel-malek.

**Comment by joewhitsitt** [comment]
Just saw this in [Drupal Slack](https://drupal.slack.com/archives/C6SQM2J94/p1686842068888049) for moving the results count (untested). I remember Marie poking at this [earlier](https://github.com/uiowa/uiowa/issues/6477#issuecomment-1563196013)

```
/**
 * Implements hook_views_pre_render()
 *
 * Move the "results" block (with the "record N of N of NNN" verbiage) out of
 * the header and into the space between the exposed filters and the query
 * results.
 *
 * @param ViewExecutable $view
 *
 * @return void
 */
function my_theme_views_pre_render(ViewExecutable $view) {
  if (
    my_theme_is_advanced_filter_view($view, $view_options)
    && !!($handler = $view->display_handler->getHandler('header', 'result'))
  ) {
    // render the "result" block content with a custom wrapper around it (as it
    // renders without a wrapper by default).
    $handler->options['content'] =
      '<div class="results-header">'
      . $handler->options['content']
      . '</div>';
    $render = $handler->render();
    $view->attachment_before[] = $render;

    // re-render the "result" block so that it will display nothing in the
    // header area.
    $handler->options['content'] = '';
    $handler->render();
  }
}
```

**Comment by joewhitsitt** [comment]
FWIW, I am seeing this elsewhere beyond classrooms site. New field in event feature (untouched)

<img width="113" alt="Screenshot 2023-06-16 at 11 26 25 AM" src="https://github.com/uiowa/uiowa/assets/4663676/0886061f-1311-4ab1-9726-f2eb785784d6">

**Comment by bspeare** [comment]
I'm going to start working on this unless anyone else has.

**Comment by bspeare** [comment]
@briand44 do they want "display number of results on search page" for the programmed search list too?

**Comment by bspeare** [comment]
If we want a custom combined sort filter for taxonomy on the platform, it looks like we would need to turn on `bef` for all sites or write that custom filter code ourselves.   Do we want to make that investment or does TVI look more appealing?

<img width="499" alt="Screenshot 2023-06-19 at 11 57 31 AM" src="https://github.com/uiowa/uiowa/assets/1036433/d32779d3-9dbe-4e22-9452-17ab2af82f31">



Otherwise, the default exposed filter looks like:


<img width="1474" alt="Screenshot 2023-06-19 at 12 03 42 PM" src="https://github.com/uiowa/uiowa/assets/1036433/45e656f8-3fae-4e21-b1f4-c6a3350d72a3">

**Comment by joewhitsitt** [comment]
:shudder: tvi is starting to sound better...

**Comment by briand44** [comment]
>do they want "display number of results on search page" for the programmed search list too?

Not that I am aware of.

**Comment by bspeare** [comment]
I got this working at https://github.com/uiowa/uiowa/pull/6551/commits/9d737fee928f20527e311fd612ec713cb413951d since we already had a `hook_views_pre_view()` running for the units vocab.   Any concerns with doing it this way?

**Comment by joewhitsitt** [comment]
>I got this working at https://github.com/uiowa/uiowa/commit/9d737fee928f20527e311fd612ec713cb413951d since we already had a hook_views_pre_view() running for the units vocab. Any concerns with doing it this way?

Does that work with paging? If it does, I am fine with it.

**Comment by bspeare** [comment]
Good question! It seems to be working with https://classrooms.uiowa.ddev.site/units/office-registrar?page=27 as I page through it.
