### ISSUE TITLE
Provision cogaresearch.lab.uiowa.edu

### ISSUE THREAD

**Issue by ethanstjohn** [uiowa/uiowa#648]
Waiting on pull request approval.

https://sitenow.uiowa.edu/node/16/submission/986

**Comment by ethanstjohn** [comment]
https://github.com/uiowa/uiowa/pull/647

**Comment by joewhitsitt** [comment]
Waiting on CNAME request after deploying release Stage/Prod.

**Comment by joewhitsitt** [comment]
Done
