### ISSUE TITLE
Content/Design review for lawlibrary.prod.drupal.uiowa.edu

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6481]
# Story

As a site owner for the Law Library website, I would like feedback from a content and design perspective to make sure we are following best practices as we get ready for our website launch.

# Proposed solution
 
- [x] Review https://lawlibrary.prod.drupal.uiowa.edu
- [x] Gather feedback and recommendations
- [x] Schedule time to walk through feedback Law Library (Amy Koopmann)

**Comment by mkyoder** [comment]
@maramcconnell and I provided content review feedback for this site here: https://iowa.sharepoint.com/:w:/s/OSCWebTeam/EZvkFeGqPdRMmAIk216WG7ABS-HEET6t5_94L0vjtiZBOw?e=h37P62

**Comment by mkyoder** [comment]
Will set up a meeting to review feedback with Amy.

**Comment by briand44** [comment]
@mkyoder I feel like we can close this since we delivered feedback yesterday. Reopen if needed.
