### ISSUE TITLE
Pharmacy person updates

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#6485]
# Story

As a Pharmacy editor, I don't want to see the international recruitment option (copied from Admissions) in the person state field dropdown.

# Proposed solution

- [ ] check for any content that uses the value and switch to another option.
- [ ] remove the option https://github.com/uiowa/uiowa/blob/main/config/sites/pharmacy.uiowa.edu/field.storage.node.field_person_territory.yml#L14-L16

**Comment by cory-skeers** [comment]
Likely need an update hook to handle this, as may not be able to change the available options while there is data in the db.

One example of this includes https://github.com/uiowa/uiowa/pull/5569/files#diff-fead566a578ea17efbda9b82e2a399962f8d578c39998fedf5bb87ceebd7d3f6.

Essentially need an update hook to

1. Grab all the info currently stored in the field (including revisions)
2. Update the field definitions
3. Re-insert all the temporarily copied info

**Comment by pyrello** [comment]
> Because this involves the removal of an option from field storage config, I don't think we can simply remove the option because we'll get an error that prevents loss of data. If that is the case, we'll likely need an update hook that creates a new field, copies the data over to it, and then deletes the existing field.

Accidentally posted this in the wrong issue: https://github.com/uiowa/uiowa/issues/6439#issuecomment-1568867824

**Comment by joewhitsitt** [comment]
I think we should implement it using allowed options this time around: uiowa_core_state_options (sppa and admissions are already using it). We can alter to add their own options if need be

**Comment by cory-skeers** [comment]
Checked the distinct values currently in use, and thankfully there are no instances of the international option.

```
+------------------------------+
| field_person_territory_value |
+------------------------------+
| AR                           |
| AZ                           |
| CA                           |
| IA                           |
| IL                           |
| KY                           |
| MI                           |
| MN                           |
| MO                           |
| TX                           |
| WA                           |
+------------------------------+
```
