### ISSUE TITLE
Update admissions contact info on Grad Admissions

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6489]
# Story

As a content editor for grad.admissions.uiowa.edu, I would like to have our contact information on Areas of Study be updated to reflect our new location so that we do not have to manually update hundreds of nodes.

# Additional Info

The old info:
Office of Admissions
The University of Iowa
108 Calvin Hall
Iowa City, IA 52242-1396

The new info:
Enrollment Management
The University of Iowa
2900 University Capitol Centre
201 S. Clinton St.
Iowa City, IA 52242

Scope only to field_area_of_study_contact

# Proposed Solution

- Update hook or database find/replace to update contact info

**Comment by cory-skeers** [comment]
An example SQL query for this (it matches address exactly as it is, so would miss some variations, if say something wasn't exactly bolded in this manner; it does use wildcards for the line breaks though).

Comes up with 155 results.

```
SELECT * FROM node__field_area_of_study_contact WHERE field_area_of_study_contact_value LIKE "<p><strong>Office of Admissions</strong><br />%The University of Iowa<br />%108 Calvin Hall<br />%Iowa City, IA 52242-1396<br />%<a href=\"mailto:admissions@uiowa.edu\">admissions@uiowa.edu</a><br />%<a href=\"tel:1-319-335-1523\">1-319-335-1523</a></p>%";
```

One way to handle this would be an update hook using an entity query based on this, update the field for each of the nodes, set revision and revision user, and save.

**Comment by briand44** [comment]
I can check to see if they would be ok with us linking to an existing contact page or somewhere else where this info lives so they are not duplicating content.

**Comment by briand44** [comment]
I've asked about linking to the contact us page in the redesign admissions Slack channel

**Comment by briand44** [comment]
They want to keep the address listed on every area of study.

>while we understand the reasoning behind that idea we think it would provide a better user experience to leave that address listed on each page. Prospective students are more likely to need our contact info than the department's information, and if they do need the department's info they usually still need ours as well, so forcing them to jump to a separate page wouldn't be ideal.

**Comment by pyrello** [comment]
Going to start poking at this.

**Comment by pyrello** [comment]
My proposed approach is to target the 3 strings that I'm seeing above that are changing. I'll check for instances of the contact field where any of those strings are present and then convert those instances to the new string. For example, I'll target instances of `Office of Admissions` and convert them to `Enrollment Management`.

@briand44 raise a concern that `108 Calvin Hall` might be used by some unit other than Admissions. I checked with Scott and he said he believes that shouldn't be an issue.
