### ISSUE TITLE
Provision help.maui.uiowa.edu

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#649]
I would just create this at the production url and not worry about the internal prod domain unless the customer asks for it. We will need to grant Bill Evanson webmaster access. We also will need to cover this in our SSL cert. Follow up with me when ready and I can communicate with the customer.

**Comment by ethanstjohn** [comment]
Update: I have sent CNAME request and created prod domain. Waiting on CNAME.

**Comment by ethanstjohn** [comment]
The site is ready to be communicated with the customer.

**Comment by richardbporter** [comment]
Rolling a cert now...

**Comment by richardbporter** [comment]
Its covered now.

**Comment by briand44** [comment]
Awesome! I was just getting ready to create a new cert.

**Comment by briand44** [comment]
I've communicated with the customer.
