### ISSUE TITLE
ITS-Web - Site launch - performingarts.uiowa.edu

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#6493]
# Story

As an owner of dpa.uiowa.edu, I would like to move this site to performingarts.uiowa.edu and have all traffic going to dpa.uiowa.edu be redirected to performingarts.uiowa.edu so visitors can find relevant information they are looking for.

# Proposed solution

- [x] Request redirect be put in place on Vulture to redirect dpa.uiowa.edu to peformingarts.uiowa.edu
- [x] Request TTL be lowered to 5 min for dpa.uiowa.edu
- [x]  Test redirect once in place by updating local hosts file.
- [x] Normal backup of dpa.uiowa.edu placed on Teams
---Launch Day---
- [x] [Go-live process for performingarts.uiowa.edu](https://wiki.uiowa.edu/display/drupaldev/Launching+a+Site+in+Drupal+9)
- [x] Update dpa.uiowa.edu DNS to point to vulture at least 24 hrs after TTL has been lowered and CLAS is ready for switch
---Post Launch Day---
- [x] Request TTL for dpa.uiowa.edu be set back to default once all is well.

**Comment by joewhitsitt** [comment]
The team is okay with moving forward with launching, but we plan to make the content/technical aspects of our launch process visible to CLAS and others.

Will do pre-launch checks and update CLAS once we know the vulture redirect is in place.

**Comment by joewhitsitt** [comment]
Confirmed SSL on uiowa04 for performingarts.uiowa.edu

**Comment by bspeare** [comment]
The site is launched and redirect is in place.   Only post-launch tasks remain.

**Comment by bspeare** [comment]
Requested TTL lowered back to default and created deprovision issue.
