### ISSUE TITLE
Deprovision tippie.prod.drupal.uiowa.edu

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#6520]
https://wiki.uiowa.edu/display/drupaldev/Backing+up+a+site+before+deletion

**Comment by briand44** [comment]
I think we want these docs https://wiki.uiowa.edu/display/sitenow/Backing+up+a+site+before+deletion

**Comment by briand44** [comment]
I had some trouble with the backup because the site was erroring out locally. cc and rr were not helping. The backup did not include the site directory and files so I manually added those to the directory with the db backup and zipped them up. This is done.
