### ISSUE TITLE
Consistent Moderation Status labeling

### ISSUE THREAD

**Issue by cory-skeers** [uiowa/uiowa#6525]
# Story

As a site editor I want consistent labeling of content moderation status so that I can more easily audit content and media based on a content entity's moderation state.

From Viki in demo:
In most content views (eg content overview, entity usage) the only distinction for content is "published" or "unpublished." As they are also using content moderation for workflow, these views include both content that has not yet been published (draft, in review) and archived content as "unpublished." They would like to be able to cull old pages and/or media that is used on archived pages, but are having difficulty easily distinguishing between these two types of unpublished pages.

Relates to #6509 

# Proposed solution

Check for community solutions
???
Profit

**Comment by joewhitsitt** [comment]
Is this a duplicate of https://github.com/uiowa/uiowa/issues/1684 or is there a different angle here?

**Comment by cory-skeers** [comment]
> Is this a duplicate of #1684 or is there a different angle here?

I think #1684 covers it. I'm guessing I either missed it or was thrown of by the title, but closing in favor of #1684 sounds good.
