### ISSUE TITLE
Update Photoswipe library and module

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#6543]
# Motivation

There is work being done to support the latest version of the photoswipe library in the photoswipe module: https://www.drupal.org/project/photoswipe/issues/3232070. We closed #5420 because that work is not quite done and the module and library need to be updated at the same time. Personally, I'd like to see a module maintainer confirm the RTBC status before we commit.

# Proposed solution

- If we pick up this work before a 5.x release, we'll need to find a working patch version. Or we'll need to update the module to the 5.x series.
- Review that the functionality we need has not been removed
- If the library is not provided by the module, update the library to the most recent compatible version. If the library is provided by the module, then I think we can remove it as a composer dependency.

**Comment by joewhitsitt** [comment]
We have a similar issue here https://github.com/uiowa/uiowa/issues/5332

**Comment by pyrello** [comment]
> We have a similar issue here #5332

Whenever we take on this work, I think we'll want to address #5332, but I think this is a broader task than that issue.

**Comment by joewhitsitt** [comment]
I think we can close this in favor of the remaining slice https://github.com/uiowa/uiowa/issues/6965
