### ISSUE TITLE
Disable AddThis module for D7 sites

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6545]
https://www.addthis.com

Should we audit what D7 sites have this enabled and decide what to do from there?

**UPDATE**

702 - no sites using this module

703
- animal.research.uiowa.edu - not seeing a field for this
- arts.uiowa.edu - there is a field on an event instance - nothing rendering anymore except the empty pane
- cmrf.research.uiowa.edu - not seeing a field for this
- dsp.research.uiowa.edu - they have launched a v3 site
- ehs.research.uiowa.edu - not seeing a field for this
- hancher.uiowa.edu - removed overridden title from pane so nothing but empty pane outputting.
- hso.research.uiowa.edu - not seeing a field for this
- library.law.uiowa.edu - used on article content type - pane title still outputting - launching v3 at end of month **Update** - disabled this pane.
- now.uiowa.edu - used on achievement and news feature - nothing rendering - moving to v3 in August
- outreach.uiowa.edu - redirects to another site except for a map
- ovproperations.research.uiowa.edu - not seeing a field for this
- rcouncil.research.uiowa.edu - redirects
- ris.research.uiowa.edu - not seeing a field for this

701 - no sites using this module

CLAS - no sites using this module

**Comment by joewhitsitt** [comment]
If we can just remove these from rendering, it should prevent the functionality from being loaded. Disabling the module completely (dealing with features) does not seem worth the squeeze.

<img width="264" alt="Screenshot 2023-06-14 at 9 00 49 AM" src="https://github.com/uiowa/uiowa/assets/4663676/703e78a6-d666-44fc-bc6c-60ad0818e0c7">

**Comment by briand44** [comment]
How do we do that?

**Comment by joewhitsitt** [comment]
Leave features in an overridden state and remove the panes completely from the default panelizer?

**Comment by briand44** [comment]
can you verify if Law Library shows addthis like in your screenshot? I disabled the pane on that site

**Comment by joewhitsitt** [comment]
<img width="543" alt="Screenshot 2023-06-14 at 9 59 38 AM" src="https://github.com/uiowa/uiowa/assets/4663676/b07bd0da-720b-4435-941e-14e7917b8fd3">

**Comment by briand44** [comment]
ok, so based on the audit, we should disable the pane on arts.uiowa.edu, hancher.uiowa.edu and now.uiowa.edu and then we could close this?

**Comment by briand44** [comment]
i've disabled those panes.
