### ISSUE TITLE
Timeline Block

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#655]
Possible collection type block that captures labels and/or dates as points and provides a content region for more detail.

**Comment by joewhitsitt** [comment]
Modified to capture idea for a possible block implementation

**Comment by bspeare** [comment]
@joewhitsitt mind if we close this in favor of https://github.com/uiowa/uiowa/issues/3314?  I added your idea to the proposed solution.

**Comment by joewhitsitt** [comment]
Closing in favor of #3314
