### ISSUE TITLE
Updates to Clery forms based on Public Safety feedback

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6558]
- Crime log and fire log
    - we should limit to show 60 days in the past
    - update wording for captions (https://github.com/uiowa/uiowa/issues/6558#issuecomment-1625605587)
- CSA reporting form
    - Can we implement a Captcha?
- Public incident reporting form
    - Can we implement a Captcha?

**Comment by bspeare** [comment]
@briand44 is it worth finding out the sizes of the pdf and word documents uploaded to rule out size issues?

**Comment by joewhitsitt** [comment]
Pilot using https://www.hcaptcha.com/?

**Comment by joewhitsitt** [comment]
Not sure what it would take to extend antibot or honeypot to these non-drupal forms

**Comment by briand44** [comment]
Grooming convo... Limit to 60 days on both reports, Brian will get wording for captions, Probe CAPTCHA by first asking Clery Edge.

**Comment by briand44** [comment]
I've reached out to Hayley about the table captions.

**Comment by briand44** [comment]
> Will this work?
>  
> Crime Log – Crimes occurring on campus or within the patrol area of University of Iowa Police within the last 60 days.
>  
> Fire Log – Fires reported in on-campus housing facilities within the last 60 days.

I'm guessing we can still keep the date ranges that are selected rather than just saying 60 days if we feel that more accurately represents the data.

**Comment by GaryRidgway** [comment]
> > Will this work?
> > Crime Log – Crimes occurring on campus or within the patrol area of University of Iowa Police within the last 60 days.
> > Fire Log – Fires reported in on-campus housing facilities within the last 60 days.
> 
> I'm guessing we can still keep the date ranges that are selected rather than just saying 60 days if we feel that more accurately represents the data.

Do we still want to keep the maximum that a single page will display to 60? Does that mean we need to swap the captions based on what filters are selected?

**Comment by GaryRidgway** [comment]
The Date restrictions and captions have been updated. I will move on to emailing CleryEdge.

**Comment by briand44** [comment]
I've created a new issue to possibly address Captcha since we got feedback from Clery late in the sprint. #6647

**Comment by briand44** [comment]
Based on ^^ should this be closed as completed?

**Comment by GaryRidgway** [comment]
Based on the info given, If people would live to review the code 
[Here for the crime log](https://safety.prod.drupal.uiowa.edu/crime-log)
and [Here for the fire log](https://safety.prod.drupal.uiowa.edu/fire-log)
That would be awesome!

**Comment by joewhitsitt** [comment]
Hard to "test" the fire log as I get no results for the maximum allowed time frame. Crime log looks as expected. It was weird to see 2023 already filled out and disabled but it make sense. I'll be curious to see what happens when the timeframe allows the past yet. 

RemindMe! February 1st 2024.

"Approved" ✅
