### ISSUE TITLE
Page title not hidden in preview

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#656]
If a page is configured to visually hide the title, the preview mode still displays it. This is confusing.
![image](https://user-images.githubusercontent.com/1068523/66848474-c6905480-ef3a-11e9-9c7a-d89f1a4adc40.png)

**Comment by joewhitsitt** [comment]
Featured image, sidebar, etc. is also affected by this as it is outside of the node and like this, is handled at the page level, but that might be a separate task. Quite the rabbit hole
