### ISSUE TITLE
Accessibility features filter on Classrooms search page

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6560]
# Story

As a Classrooms website owner, I would like users to be able to filter classrooms by accessibility features so they can easily find rooms that meet their needs.

# Additional Info

They want the ability to select multiple accessibility features

We have discussed possibly moving the filters to the side to better accommodate all of the filters.

# Proposed solution

- Expose filter
- Allow multiple to be selected
- Move filters to sidebar?

**Comment by briand44** [comment]
Blocked until https://github.com/uiowa/uiowa/issues/6488 is finished

**Comment by briand44** [comment]
Planning conversation... We should share a screenshot of the filters in the sidebar with them prior to fininshing/closing out this issue.

**Comment by bspeare** [comment]
Here is a screen recording of the sidebar display:

https://github.com/uiowa/uiowa/assets/1036433/15f066d5-9f71-4403-aa41-39800f0cc407
