### ISSUE TITLE
UIHC icons

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6565]
>Just a heads up that UIHC is developing like 85 icons that will live on our icon browser. It’s my understanding that these will just be part of the whole set and not something else entirely. I have seen these in a draft stage, so they have more work to do on them yet – and they still need to build out a keyword list, but wanted to let you know they’ll be coming your way. If they do have a hard deadline in mind to get these posted, does your team have a typical lead time needed for something like this? I’m just looking to manage expectations on their end. Thanks!

We got the icons and keywords. They are in the directory InfantsChildrenAndTeenagersIcons_Final at https://iowa.sharepoint.com/sites/CSI-Drupal2/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FCSI%2DDrupal2%2FShared%20Documents%2FBrand%20Icons&viewid=bf54b9d9%2D0975%2D4fbc%2D9f1b%2D6377bdc2307c.

>They provided 2 versions of the single color icons, but they’re they same. Just some miscommunication as to what was needed.

>We’ll need a new category for these, titled “Kids”.

# Proposed Solution

**Comment by briand44** [comment]
not sure if this issue was created for the right repo or not?

**Comment by GaryRidgway** [comment]
[Here is a tool that I amde to help turn a list of tags in to a usable json string for the iconbrowser.](https://codepen.io/purple_salmon/full/wvRgVBv)

**Comment by GaryRidgway** [comment]
This is done, thought i will be updating the redme's for both repos to make things easier.

**Comment by briand44** [comment]
Looking back in my email thread, "Kids" is what we should be using for the category. Looks like it was originally going to be " Infants, Children, and Teenagers" but decided to change tentatively to "Kids" and then they got final approval to use "Kids".
