### ISSUE TITLE
Accordion items do not maintain open/closed state

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#657]
When clicking a link within an accordion item and then navigating back to the page. The accordion item should stay open.

**Comment by joewhitsitt** [comment]
I don't think that is built in to bootstrap. Since we are implementing straight bootstrap for this component, this sounds like a feature enhancement instead.

**Comment by richardbporter** [comment]
Since its not in BS, lets wait until #371

**Comment by richardbporter** [comment]
Outdated.
