### ISSUE TITLE
v2 card title color regression

### ISSUE THREAD

**Issue by cory-skeers** [uiowa/uiowa#6572]
V2 site. Card titles changed to white on white background.

https://pentacrestmuseums.uiowa.edu/visit/group-visits-tours

(Cherwell ticket: 1809993 Site Text Changed Color Question)

<img width="1700" alt="Screenshot 2023-06-27 at 11 25 09 AM" src="https://github.com/uiowa/uiowa/assets/1036433/e8f0a96f-9d28-4e17-a3ea-f5aeed68c6ac">

**Comment by joewhitsitt** [comment]
Anyone know when this might have been introduced? was it card_4x or after?

**Comment by GaryRidgway** [comment]
unsure, guess we could check the wayback machine?

**Comment by bspeare** [comment]
I've found where this issue is in UIDS and I will work on moving through a bug fix for it.
