### ISSUE TITLE
Concept3D - more base layer edits

### ISSUE THREAD

**Issue by e-marie-w** [uiowa/uiowa#6575]
Concept3D support article - https://help.concept3d.com/hc/en-us/articles/360001865534-How-Do-I-Make-Map-Updates

>We have a process called map updates where you request changes, and then I get a quote for the cost of the work and I send you a Statement of Work (SOW). Once the SOW is signed we complete the work. Typically this process takes about 4-6 weeks. We can do it for one building, or if you know of more updates coming down the road we can do them all at one time. 

List of edits to eventually submit to Concept3D.

Athletics requests:

> Yes, we are working on our project with Concept3D for athletics parking and Kinnick/Carver interiors with wayfinding and they started out by copying the current buildings and parking lots from your main map. We want to get that building added. The new Gymnastics/Spirit Squad building is under construction. Could we get its location added now?
> Additionally, can we add in the new parking ramp that is going up next to Kinnick (even though it isn’t done – but maybe the polygon exists)? I’d really love to have that area not show up as a giant parking lot since it doesn’t exist anymore. As well as reflecting the changes to the parking lots next to the baseball stadium where the water tower is going in.
> If we can’t do the buildings, could we change those lots to only show the available area they now have?

Separate message from Athletics:

>I would also note we have not budgeted the additional athletic buildings.  We are merely focusing on venues that we host fans and the parking lots they use.  We can postpone these other buildings until funds are available or campus feels it is important.

- [x] Move Pride Alliance Center building label from current location 125 Grand Avenue Court to 601 Melrose Avenue (aka where map marker has already been moved to).
- [x] Add Wrestling building to our campus map - Athletics
- [x] The new Gymnastics/Spirit Squad building is under construction. Could we get its location added now? - Athletics
- [x] Can we add in the new parking ramp that is going up next to Kinnick - Athletics
- [x] Reflecting the changes to the parking lots next to the baseball stadium where the water tower is going in.
- [ ] Facilities requested changes https://github.com/uiowa/uiowa/issues/6575#issuecomment-2206992970

**Comment by joewhitsitt** [comment]
>the university plans to raze the homes along Grand Avenue Court as part of its 10-year facilities master plan.

https://now.uiowa.edu/2023/04/pride-alliance-center-finds-new-home-melrose-avenue

something to keep in mind with batching edits

<img width="615" alt="Screenshot 2023-06-23 at 1 15 46 PM" src="https://github.com/uiowa/uiowa/assets/4663676/66cecca4-7849-4d53-ac9b-e41320d11491">

Other big changes coming soon: https://now.uiowa.edu/2023/04/ui-makes-space-new-adult-inpatient-tower-improve-health-care-access-iowans

**Comment by joewhitsitt** [comment]
From Patrick at Concept3D:

>Recently the Iowa Athletics Department signed on for an interactive map. During the onboarding process, Wendy mentioned that there was a new Wrestling building on campus, as well as a couple of new parking lots and areas on campus.

>I wanted to reach out and see if you had been thinking about map updates over this summer. 

Tagging @mjoneill for visibility.

**Comment by briand44** [comment]
The checked items from above have been added to Concept3D under "Summer 2024 Updates" in the Map Edits category. I reached out to Facilities to see if there are additional updates they want included in the round of updates. Waiting to hear from them before submitting. Athletics is hoping to have these changes done by August and it can take some time to get through this process so we likely don't want to wait long.

**Comment by briand44** [comment]
Feedback from Facilities:

> Here are the changes on our end.  
>  
>Remove South Quad
> Add Health Sciences Academic Building in old Lot 14 location
> Remove Grand Ave CT and houses and add Lot 14 new location
> Add Lot 53 at 307 Melrose Court
> Change Building Labels to new UI Healthcare branding standards - [https://uihealthcare.org/ui-health-care-launches-first-phase-brand-update](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuihealthcare.org%2Fui-health-care-launches-first-phase-brand-update&data=05%7C02%7Cbrian-dickey%40uiowa.edu%7Cf4d0baaf22644e853d2808dc9b8cba9c%7C1bc445959aba4fc3b8ec7b94a5586fdc%7C1%7C0%7C638556275938523581%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=rs40k%2BUmZOW4i%2BQRcWBmBBs%2F%2Bfyw%2FJ9XzCtWBtmPuUI%3D&reserved=0)
> Add Lot 73 expansion
> Add Lot 48 expansion
> Add University of Iowa Health Care Downtown Campus
> Add University of Iowa Health Care North Liberty Campus
> Add new roads and landscape elements for Newton/Fountain Drive roundabout
>Remove Continuing Education Facility
>Add Nonfiction Writing House
>Add State Hygienic Lab Addition
>Add Xtream Arena
>Add Public Policy Research Building name
>Add High Strength Waste Treatment Building 1820
>Remove 401 Westcor Drive
>Add UIHC 2nd Street Warehouse
>Add 9 Melrose Place
>Add UIHC Iowa City Northgate Drive
>Add UIHC Iowa City First Avenue
>Add UIHC Coralville Oakdale Road
>Add UIHC Coralville Heartland Drive
>Add UIHC Warehouse East
>Add UIHC Office Building East
>Remove Grandview Office Plaza
>Update East ADA Ramp Access to Van Allen
>  
> Aesthetic updates
> Hawkeye Recreation Fields painted lines have changed during conversion from grass to turf. A Tigerhawk has also been added to the west fields
>Relocate High Adventure Course to Hawkeye Recreation Fields
> Pearl Softball Field batting cages moved and updated branding on field
> Add Expansion onto UIHC Centralized Emergency Power Generation Facility
> Remove Old Laundry Building and Landscape Garages – Buildings have been removed but are low impact for visitors
> ChildServe Building and parking lot expansion
> Kirkwood Regional Center parking lot expansion
>Update Gibson Square layout
>Update Seashore Green layout
>Add Madison Street Patio
>Add Tiger Hawk logos at Jefferson St and Market St on T. Anne Cleary Walkway

**Comment by briand44** [comment]
moving forward with the original requests from Athletics so we can meet the end of August timeline. Going to create a new issue with the Facilities changes so we can start getting those added for the next quarter of updates. We discussed getting a SOW for the Facilities changes and comparing that to the "managed updates" package in case that is more cost effective.

**Comment by briand44** [comment]
waiting for SOW from Concept3D.

**Comment by briand44** [comment]
Concept3D responded saying the edits are completed and available to review.

>If everything looks good, I can tell the team to push the updates live! If there are further edits needed on these map updates, please create a category within the CMS and place the edits there, that way I can send them directly to our production team!

I am not seeing the Gymnastics/Spirit Squad Training Center.

**Comment by briand44** [comment]
Going to close this issue as Concept3D has pushed these changes live. Going to create a follow up issue because I believe we want to add the linkable building icon and images/content for these new buildings.
