### ISSUE TITLE
[Bug] Safari is displaying video controls for banner videos

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#6582]
# Problem
Safari is displaying video controls for banner videos

# Steps to reproduce
Go to https://protostudios.uiowa.edu and look for video controls at the bottom of the banner. 

# Proposed solution
<img width="1887" alt="Screenshot 2023-06-26 at 2 38 24 PM" src="https://github.com/uiowa/uiowa/assets/1036433/02e8eb72-1523-4cd9-bc2e-4976b5070b9c">

**Comment by bspeare** [comment]
Using Version 16.5.1 (18615.2.9.11.7).

**Comment by bspeare** [comment]
I don't see this version available on Browserstack, older versions are not showing it.  It might be my machine.   Running Ventura and Version 16.5.1 of Safari.

**Comment by joewhitsitt** [comment]
Can't reproduce on Safari 16.5.1  Ventura 13.4.1 (22F82). Do you have any extensions that might be causing it?

<img width="942" alt="Screenshot 2023-06-27 at 2 38 35 PM" src="https://github.com/uiowa/uiowa/assets/4663676/11720266-13fa-4994-8567-d9067b4edf59">

**Comment by bspeare** [comment]
@joewhitsitt Can you post a full screenshot of the banner?

**Comment by joewhitsitt** [comment]
<img width="1342" alt="Screenshot 2023-06-27 at 2 44 33 PM" src="https://github.com/uiowa/uiowa/assets/4663676/bdf31400-f376-45d1-a4f6-8e890b9ef08b">

do you have some mobile emulation going on? idk, just throwing out ideas.

**Comment by bspeare** [comment]
Can't reproduce on another machine.   Closing this unless it pops up again.  Thanks @joewhitsitt!
