### ISSUE TITLE
Deprovision VPMA Site

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6587]
First thing Monday morning, can you or someone from your team unpublish the VPMA website? Pete says July 1, but since that’s a Sunday, July 2 is fine.

What does unpublish mean? - unpublish = deprovision (bdickey)

# Proposed Solution

- ~remove domain from Acquia~
- deprovision as time permits

**Comment by briand44** [comment]
blocked until Monday, July 3rd.

**Comment by pyrello** [comment]
I'll be working on Monday, so I can handle this.
