### ISSUE TITLE
link classrooms to facilities building pages 

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6592]
# Story
As a Classrooms site owner, I would like links to buildings to go to the building pages on Facilities rather than having building pages on the Classrooms website.

# Additional Info

It was decided that Facilities is going to add hours info from Sims into Bizhub which will allow us to output hours on the Facilities website. Since Facilities will have the hours listed at some point, Classrooms is ok with just linking to those building pages.

We need to get the building number since we only have the building abbreviation and building name currently. The building number doesn't currently exist in the endpoint we are using to get the list of buildings.

Current endpoint to get buildings https://api.maui.uiowa.edu/maui/api/pub/registrar/courses/AstraBldgRmCompleteList/list

**Possible other endpoints**

- Could maybe get building number with an additional call to https://bizhub.facilities.uiowa.edu/bizhub/ext/buildings
- Could maybe change endpoints and get list of buildings from https://api.maui.uiowa.edu/maui/api/pub/facilityBuildingRoom/list or
https://api.maui.uiowa.edu/maui/api/pub/facilityBuildingRoom/list?roomCategory=UNIVERSITY_CLASSROOM and https://api.maui.uiowa.edu/maui/api/pub/facilityBuildingRoom/list?roomCategory=PROGRAMMED_CLASSROOM
    - Need to understand if this endpoint contains same rooms as https://api.maui.uiowa.edu/maui/api/pub/registrar/courses/AstraBldgRmCompleteList/list plus our logic to filter out some categories

# Proposed Solution

- Get building number and store on config entities
- Update links on rooms to go to facilities building pages

**Comment by briand44** [comment]
Grooming Conversation.... If we use the different endpoint lets filter by the roomCategory parameter rather than looping through the entire list.

**Comment by cory-skeers** [comment]
As part of the update for this, there are 4 buildings that no longer appear in the API. To clean up the filters, if they are no longer in use we should remove the building config entities for each of these. Prior to those removals, though, any rooms associated to each building should be removed from the prod site.

@briand44 can we confirm that the following buildings should be removed, and make sure the associated rooms are removed prior to moving forward with that?

- Calvin Hall
  - [CALH 208](https://classrooms.prod.drupal.uiowa.edu/calh-208)
- Kirkwood Regional Center
  - [KRC 2C](https://classrooms.prod.drupal.uiowa.edu/krc-2c)
  - [KRC 2D](https://classrooms.prod.drupal.uiowa.edu/krc-2d)
- Pharmaceutical Sciences Research Building
  - [PHAR S538](https://classrooms.prod.drupal.uiowa.edu/phar-s538)
  - [PHAR S543](https://classrooms.prod.drupal.uiowa.edu/phar-s543)
  - [PHAR S552](https://classrooms.prod.drupal.uiowa.edu/phar-s552)
  - [PHAR 100A](https://classrooms.prod.drupal.uiowa.edu/phar-100a)
  - [PHAR 100B](https://classrooms.prod.drupal.uiowa.edu/phar-100b)
  - [PHAR 304](https://classrooms.prod.drupal.uiowa.edu/phar-304)
  - [PHAR 318](https://classrooms.prod.drupal.uiowa.edu/phar-318)
  - [PHAR 321](https://classrooms.prod.drupal.uiowa.edu/phar-321)
- South Quad
  - [SQ 104](https://classrooms.prod.drupal.uiowa.edu/sq-104)
  - [SQ 14](https://classrooms.prod.drupal.uiowa.edu/sq-14)
  - [SQ 3](https://classrooms.prod.drupal.uiowa.edu/sq-3)

**Comment by briand44** [comment]
Sent email to Classrooms
