### ISSUE TITLE
Add subtitle field to area of study pdfs

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#6593]
# Story

As a prospective student, I can see the area of study subtitle information appear on the area of study pdf

Is it possible for the Subtitle field in the areas of study content type to appear at the top of the PDFs that generate from that content? Since the subtitle is at the top of each AOS page and will now be the main source of information for the slideshow, I feel like it would make sense for it to appear on the PDFs too.

**Comment by briand44** [comment]
Duplicate of #5858

**Comment by briand44** [comment]
Closing this because it is a duplicate
