### ISSUE TITLE
Group events by date

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6607]
# Story

As an owner of the OnIowa website, we would like our events page to display the events grouped by date so that users can quickly glance to see where one days events end and another begins.

# Additional Info

Previously displayed like https://web.archive.org/web/20220815131834/https://oniowa.uiowa.edu/events

Current display https://oniowa.uiowa.edu/events

# Proposed solution

- Override default events view for OnIowa to group by date?
- Updates to event teaser display (show time rather than date and time)

**Comment by briand44** [comment]
Grooming convo.... See if we can export view as a partial split keeping as unformatted list.

**Comment by joewhitsitt** [comment]
Going to take a look at this later to see if there is a smaller slice workaround by suggesting a template or something.

**Comment by joewhitsitt** [comment]
I was able to get something working using preprocess_field, checking if view display (not route match), suggesting a custom template. Works with ajax pager. Trying to figure out how to handle multiple dates.

<img width="266" alt="Screenshot 2023-07-14 at 1 10 47 PM" src="https://github.com/uiowa/uiowa/assets/4663676/cdcd9684-c2e9-43c3-b111-6870a67a3c9e">

**Comment by joewhitsitt** [comment]
If multi day range, it falls back to the original format.

<img width="512" alt="Screenshot 2023-07-14 at 2 08 32 PM" src="https://github.com/uiowa/uiowa/assets/4663676/c0b8c81e-34ea-4237-8740-fd57e84cc7c9">

Pushed this solution https://github.com/uiowa/uiowa/pull/6626/commits/29b3efbd4e74dfc307bc762eb117cc6e1f80d719
