### ISSUE TITLE
Event location display updates

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6608]
# Story

As an OnIowa site owner, I would like to output the event location information in a way that makes it easier for attendees to find the location.

# Additional Info

- Can we output a map of the location or at a minimum link the location to a map?
- Can the additional directions be output near the rest of the location information?

# Proposed solution

- Output map link if lat/long filled out that links to Google Maps.
- Additional directions in details toggle near other location info.

**Comment by bspeare** [comment]
I know it will make the page a bit lopsided, but most of this should go into the card column. 

<img width="1472" alt="Screenshot 2023-07-03 at 4 23 53 PM" src="https://github.com/uiowa/uiowa/assets/1036433/d602089e-5adb-4bf1-b629-a882e5be0623">

We could also look into putting everything into the card?

<img width="1526" alt="Screenshot 2023-07-03 at 4 36 11 PM" src="https://github.com/uiowa/uiowa/assets/1036433/cc293c45-5ea7-4726-8ae9-3d2c160bb749">

**Comment by joewhitsitt** [comment]
>at a minimum link the location to a map

Originally I was thinking of displaying the lat long that is linked out to google maps https://github.com/uiowa/uiowa/issues/6402#issuecomment-1597237958

In my example directions I lifted the directions used to get people to PCO and it was quite lengthy. I guess if they are requesting the sidebar, hopefully they will keep the directions short.

**Comment by briand44** [comment]
Grooming conversation.... Output map link if lat/long filled out that links to Google Maps. Additional directions in details toggle. We can get feedback at that point and if we need a future slice to alter design more we can. This would be implemented as part of the default feature
