### ISSUE TITLE
Statistic Paragraph Bundle

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#661]
## Problem

Our clients want to highlight statistics on their sites. In D7 we offered many different variations of statistic solutions, most notably, snp_stat which tied in with sitenow_paragraphs. Additionally, we have seen in OSC's mockups that they also call for a variation of statistic and should be integrated with the HDS.

### Phase 1

- Start with a fresh sync of the default site locally.
- Login and through the UI, create a new paragraph bundle type called Statistic (statistic)
- Create the following fields:
  - Title (stat_title) (textfield, single)
  - Summary (stat_summary) (long text formatted no summary, single, minimal text format)
- Add a new paragraph scss partial for the statistic bundle and jumbofy the font-size of the statistic field and make sure `blt frontend` is working locally. Don't go too crazy with styles as this feature probably won't launch with uiowa_bootstrap
- `drush -l default cex` to export all the new config.
- create a draft PR in uiowa.

### Phase 2 (HDS home stretch)

- Link (title (accessible sr-only), url, single) (stat_link)
- Media Image Field (Background Image) (stat_image)
- Global paragraph settings fields (classes, unique id, column width)
- Integrate into HDS (#371)

### Phase 3 (Twiddling thumbs)

- Hide certain fields (column width) and make it compatible with Carousel

## HDS Implementation:

<img width="613" alt="Screen Shot 2019-10-16 at 8 31 53 AM" src="https://user-images.githubusercontent.com/4663676/66924147-b5ede600-efef-11e9-97ad-a2858498dda7.png">

**Comment by joewhitsitt** [comment]
Brought this up in the working session as a good example to start with that folks are welcome to work and create draft PRs for but ultimately is postponed. Ideally this would be done in conjunction with #371

**Comment by joewhitsitt** [comment]
This would be a good test for HDS

**Comment by joewhitsitt** [comment]
Initial work on this has been done. https://github.com/uiowa/uiowa/pull/749. We should do a find/replace to align with HDS machine names. I have updated the issue description with what I believe are the fields.

**Comment by dnkemper** [comment]
@joewhitsitt I changed 'Statistic' -> 'Title' and 'Caption' -> 'Summary'. **OR** should I redo Statistic altogether with one commit?

**Comment by joewhitsitt** [comment]
This could be refactored/revisited now that the stat component for UIDS has been finalized and work towards #371 has been started. We should adopt the same fields since nothing has been deployed to PROD yet.

**Comment by dnkemper** [comment]
@joewhitsitt I can quick do that!

**Comment by joewhitsitt** [comment]
This issue is largely outdated, but https://github.com/uiowa/uiowa/pull/749 is only blocked from merging in the current state. Work can be done to refactor to align with custom block type and build out a paragraphs compatible variant of the stat component in uids_base.

**Comment by joewhitsitt** [comment]
This is no longer planned and already existing in layouts.
