### ISSUE TITLE
D7 Debt Visibility

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6612]
# Story

As a web team, I have visibility into the shape of our D7 debt/backlog so that I can understand & help groom and plan team priorities through D7 EoL.

# Additional Info

Some things that might help are ways to represent:

- What D7 sites are standard and owners can move on their own
- What D7 sites are custom but might be able to move to SnV3 on their own
- What D7 sites are custom and will require custom development in order to migrate
- What D7 sites are abandoned
- What D7 sites are decoys and have already been replaced by a new SNv3 site
- More…

**Resources**
Historic team Sharepoint inventory (out of date, but represents the last inventory)
- [Drupal 7 Sites.xlsx](https://iowa.sharepoint.com/:x:/r/sites/CSI-Drupal2/Shared%20Documents/General/Drupal%207%20Sites.xlsx?d=wa3958afafa30492a948e0a3368521d3d&csf=1&web=1&e=9yX4V2)

**Domain Language** (proposed)

Abandoned site: 
- No users have signed in within the last [duration]

Unmaintained site:
- Have clear/obvious unaddressed content or quality issues in SiteImprove or upon visual inspection and nobody fixing issues/keeping it current

Decoy site:
- Website has already been replaced by a newer version but the old site still exists

Standard site:
- A website that does not have custom development (and can migrate to SNv3 without needing to invest in custom development)

Custom Constrained site:
- A website that has custom development and is blocked from migrating to SNv3 until development investments are made to support the website on SNv3

Custom Unconstrained site:
- A website that has custom development but could be migrated without development investments because the previously custom functionality is addressed by features in SNv3

Under
Important to define what our terms mean, what does it mean to have a site be abandoned? what happens if a site is abandoned? After that discernation, what paths do we go down if it is, and what do we do if it isn't? We need to have boundaries for our D7 sites and how far we are willing to go.

**For a different epic (likely related to future steps):**

"If you don’t migrate your site, it will be decommissioned on mm/dd/yy because it is on a platform that will no longer be supported." -mjo

# Proposed Solution

- [x] #6669
- [ ] Using the recent spreadsheet, determine how many sites are left needing custom development work
- [x] #6787
- [ ] Combine inactive data with the custom development list and see if the list is potentially reduced

**Comment by mjoneill** [comment]
@briand44 I drafted some initial domain language for this work.  Let's try to avoid collisions, make clear what might otherwise not be, and make sure we have a shared understanding.  Please change whatever you'd like, add, etc...

**Comment by briand44** [comment]
Grooming conversation.... First identify Drupal 7 sites that likely need custom development. We need to include Grad and Clas as part of this. Spreadsheet with more usable/filterable columns than our current SiteNow D7 spreadsheet.

Medium

**Comment by joewhitsitt** [comment]
I still think auditing what still needs custom development is more valuable, but I was just curious how much of a potential dent we could make in the overall counts:

<details>
<summary>129 websites that are 6 months inactive on uiowa701-3 as of 2023-07-18</summary>

```
# 701

abboud.lab.uiowa.edu
abel.lab.uiowa.edu
accessibility101.course.uiowa.edu
ahmad.lab.uiowa.edu
amendt.lab.uiowa.edu
apo.org.uiowa.edu
asme.org.uiowa.edu
ballas.lab.uiowa.edu
banfi.lab.uiowa.edu
brahma.lab.uiowa.edu
brainworkshop.sites.uiowa.edu
brenner.lab.uiowa.edu
brogden.lab.uiowa.edu
buchanan.lab.uiowa.edu
cbml.lab.uiowa.edu
colgan.lab.uiowa.edu
communication-memory-mind.lab.uiowa.edu
copstudy.lab.uiowa.edu
cromwell.lab.uiowa.edu
cssa.org.uiowa.edu
cytogenetics.lab.uiowa.edu
dai.lab.uiowa.edu
davidplowden.studio.uiowa.edu
dayal.lab.uiowa.edu
diekema.lab.uiowa.edu
dodd.lab.uiowa.edu
econsent.lab.uiowa.edu
elcock.lab.uiowa.edu
elliott.lab.uiowa.edu
engelhardt.lab.uiowa.edu
evaluation.org.uiowa.edu
fab.law.uiowa.edu
fethke.lab.uiowa.edu
fluids.lab.uiowa.edu
fuentes.lab.uiowa.edu
geerling.lab.uiowa.edu
geyer.lab.uiowa.edu
giudici.lab.uiowa.edu
globalwealth.law.uiowa.edu
grobe.lab.uiowa.edu
guymon.lab.uiowa.edu
hackiowa.org.uiowa.edu
hawkeyeoptimistchapter.org.uiowa.edu
hawktools.uiowa.edu
hodgson-zingman.lab.uiowa.edu
hoth.lab.uiowa.edu
huang.lab.uiowa.edu
humangames.lab.uiowa.edu
ieee.org.uiowa.edu
imai.lab.uiowa.edu
immigrantrefugeehealth.org.uiowa.edu
ince.lab.uiowa.edu
interprofessional.uiowa.edu
iowavirology2019.sites.uiowa.edu
irani.lab.uiowa.edu
jalal.lab.uiowa.edu
jprineas.lab.uiowa.edu
lamping.lab.uiowa.edu
lee.lab.uiowa.edu
legge.lab.uiowa.edu
m-ashley-spies.lab.uiowa.edu
maps.org.uiowa.edu
maretzky.lab.uiowa.edu
maria-spies.lab.uiowa.edu
mark.lab.uiowa.edu
matthew-arndt.sites.uiowa.edu
meier.lab.uiowa.edu
mickelsen.lab.uiowa.edu
mokadem.lab.uiowa.edu
moore.lab.uiowa.edu
musicianshpd.lab.uiowa.edu
nasa.org.uiowa.edu
nauseef.lab.uiowa.edu
ncbc.medicine.uiowa.edu
newell.lab.uiowa.edu
nhlp.law.uiowa.edu
niciu.lab.uiowa.edu
nizar.lab.uiowa.edu
oneill.lab.uiowa.edu
orsc-colloquium.sites.uiowa.edu
outlaws.law.uiowa.edu
pennathur.lab.uiowa.edu
perlman.lab.uiowa.edu
peters.lab.uiowa.edu
pierce.lab.uiowa.edu
pufall.lab.uiowa.edu
radiologycore.lab.uiowa.edu
radley.lab.uiowa.edu
religion-secularism-novel.sites.uiowa.edu
richerson.lab.uiowa.edu
robert-weiss.lab.uiowa.edu
rohlman.lab.uiowa.edu
roman.lab.uiowa.edu
rugby.org.uiowa.edu
sanderlab.lab.uiowa.edu
shea.lab.uiowa.edu
shinozaki.lab.uiowa.edu
sigmaalphaiota.org.uiowa.edu
sigmund.lab.uiowa.edu
simonsburnett.lab.uiowa.edu
sinn.lab.uiowa.edu
sits.org.uiowa.edu
smubeen.lab.uiowa.edu
stapleton.lab.uiowa.edu
stevens.lab.uiowa.edu
stoltz.lab.uiowa.edu
tanas.lab.uiowa.edu
tco.sites.uiowa.edu
thomas.lab.uiowa.edu
tranel.lab.uiowa.edu
turkish.org.uiowa.edu
uirobotics.org.uiowa.edu
uisrmsymposium.sites.uiowa.edu
uisug.org.uiowa.edu
uitransalliance.org.uiowa.edu
vandervelde.studio.uiowa.edu
waldschmidt.lab.uiowa.edu
washington.lab.uiowa.edu
weeks.lab.uiowa.edu
wemmie.lab.uiowa.edu
wilson.lab.uiowa.edu
wold.lab.uiowa.edu
wrl.lab.uiowa.edu
yaf.org.uiowa.edu
yorek.lab.uiowa.edu

# 702

drivingassessment.uiowa.edu
mbhd2020.centerforconferences.uiowa.edu

# 703

hawkeyespaces.uiowa.edu
outreach.uiowa.edu
```
<details>

**Comment by cory-skeers** [comment]
Next step: Use the recent spreadsheet work to answer the question of how many custom sites needing development work are left.

**Comment by cory-skeers** [comment]
Other useful step: integrate the inactive data into the spreadsheet, and combine this with the custom development list to get the full(er) picture.

**Comment by briand44** [comment]
Grooming convo... Brian to slice off inactive part into a separate issue. likely a medium

**Comment by briand44** [comment]
Closing this in favor of #7161
