### ISSUE TITLE
SiteNow July 2023 Newsletter

### ISSUE THREAD

**Issue by cory-skeers** [uiowa/uiowa#6613]
DRAFT: https://sitenow.uiowa.edu/news/2023/07/updates-july-2023

### Issue/Solution
Provide a "release notes" type article of finished/done features/updates and publish to website, then send out dispatch email.

- [x] Create draft and update the parking lot card with an edit link
- [x]  Add "release notes" covering the month of v2/v3 default profile enhancements and webmaster/edit visible bug fixes.
- [x] See the previous month's article as an example.
- [x] Bullet points from demo stories slide per week: https://drive.google.com/drive/folders/1EehKUjxCbakaB9FchrGhAbaxuRbqyDGW?usp=sharing.. and/or from Web Community sprint demo announcements https://webcommunity.sites.uiowa.edu/updates/2023/02/sprint-demo-149-february-16-2023
- [x]  Get at least one team member to look over the draft before publishing.
- [x]  Since the draft was started earlier, adjust the publish date/time, publish, get the link to the article.
- [x]  Dispatch email with link to article. (To get access, send an email to [dispatch-support@uiowa.edu](mailto:dispatch-support@uiowa.edu) to have the account provisioned. Provide your hawkid and mention the CSI:drupal group)
  - [x] Modify SiteNow Announcements Template (tweak opening line, update the article link, any other editorial adjustments)
  - [x] Clone an old communication off SiteNow Announcements campaign
    - [x] Use SiteNow Announcements population, template, suppression list, bypass approval.
    - [x] Turn off Dispatch "test mode" to send out email.
    - [x] When scheduling, check the "archive" option so that there is an RSS instance we can use in the future. I don't think this can be done after the fact.
- [x]  Turn on Dispatch "test mode" after email is successfully sent.
- [x]  Take a moment to check dispatch and google analytics on whether these articles are being read.
- [x]  Create the next months's issue and copy all this bullet list into it, removing the checked boxes if any.

**Comment by joewhitsitt** [comment]
Taking a look at the draft

**Comment by joewhitsitt** [comment]
Should we highlight any of the following?

Find text updates, establishing a SiteNow alerts feature add-on, support for Academic profiles (replacement for directory profiles)

otherwise, looks fine to me

**Comment by cory-skeers** [comment]
> Should we highlight any of the following?
> 
> Find text updates, establishing a SiteNow alerts feature add-on, support for Academic profiles (replacement for directory profiles)

I updated to include the following in the New Features and Improvements section:

- Updates to the Find Text tool
  - 'Enter' key press when the search field is in focus submits the form
  - Validation requiring at least 3 characters for the search string
- Establishment of a SiteNow Alerts feature, for use on sites creating notice content, such as for road closures or service outages
- Updates to support Academic Profiles in place of Directory Profiles

**Comment by joewhitsitt** [comment]
:shipit:

**Comment by cory-skeers** [comment]
Little bit of a drop from last month in the opens; same clickthroughs to the article though.

<img width="1176" alt="image" src="https://github.com/uiowa/uiowa/assets/49074566/a6b54fae-4449-4730-a2d8-0199ece85603">

**Comment by cory-skeers** [comment]
Newsletter sent out, and next month's issue created https://github.com/uiowa/uiowa/issues/6758
