### ISSUE TITLE
Uiowa Profiles non-production endpoint update

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6617]
# Story

As an owner of Academic Profiles (previously known as Directory Profiles), we would like the endpoint used for the SiteNow integration on non-production environments updated so that we can test the SiteNow integration with the new Academic Profiles service.

# Additional Info

current non-production endpoint https://profiles-test.uiowa.edu
new non-production endpoint https://profiles-demo.uiowa.edu

Here are a couple places this endpoint is used
https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/uiowa_profiles/uiowa_profiles.libraries.yml
https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/uiowa_profiles/src/Client.php

There could be additional places.

I believe there are tests for this module as well so not sure if updates will need to happen there?

They are planning to go live around Aug 1st with Academic Profiles for CCOM. This means any updates on our end will need to fall in line with that timeline. We will also need to coordinate deployment of any future changes outside of this slice with the Academic Profiles team.

# Proposed Solution

- Update non-production endpoints from https://profiles-test.uiowa.edu to https://profiles-demo.uiowa.edu
- Sync a site (Pharmacy or Tippie) to an appropriate non-production environment
- Communicate directory link of non-production site using new non-production endpoint with Denny and Beth

**Comment by cory-skeers** [comment]
> Here are a couple places this endpoint is used
https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/uiowa_profiles/uiowa_profiles.libraries.yml
https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/uiowa_profiles/src/Client.php
There could be additional places.
I believe there are tests for this module as well so not sure if updates will need to happen there?

I think these two cover it. There's a `ClientMock` class that gets added onto it for testing that keeps the functional tests from being reliant on the API.

**Comment by cory-skeers** [comment]
We should put this out to dev, as the way it's currently set up, both stage and prod environments pull from the production endpoint.
