### ISSUE TITLE
Development Feature - CCOM Logo in header and footer

### ISSUE THREAD

**Issue by ethan-fry** [uiowa/uiowa#6629]
# Story

As a UIHC MarCom web team, we would like to explore the approach to adjusting the site logo in the header and footer for CCOM sites to represent current CCOM brand requirements.

# Additional Info

We likely will not have our branding fully adopting the block IOWA at the time of launching CCOM sites under V3. This is going to require us to adjust our logo treatment until branding is fully approved for UI Health Care.

# Proposed Solution

**Pair with UIHC MarCom on:**

- Add a theme setting option for CCOM branding available to administrators https://github.com/uiowa/uiowa/issues/6629#issuecomment-1697882535
- Display appropriate CCOM approved header/footer logos
- Favicons https://github.com/uiowa/uiowa/issues/6629#issuecomment-1697981607

**Comment by mjoneill** [comment]
For team grooming: Non-regents option currently allows logo swap. Is there a slice through this where it makes sense for us to use that functionality to allow logo option?

**Comment by maxwell-freund** [comment]
To do:

Add in current logo file needed.

**Comment by bspeare** [comment]
Does the header require a custom logo for "Carver College of Medicine" here or can that be live text?

<img width="788" alt="Screenshot 2023-08-18 at 11 08 37 AM" src="https://github.com/uiowa/uiowa/assets/1036433/34c507b0-e905-4fdb-a449-94b2b6881d69">

**Comment by maxwell-freund** [comment]
@bspeare I think the simple answer is we are open to options.

Some conversations that have occurred lead me to thinking the path of least resistance, while staying compliant with current branding requirements of CCOM would be to use our tab-oriented / shaped version of the CCOM logo within the current SiteNowV3 header.

Logo file attached.

Rough visual mock up example here:

![Screenshot 2023-08-18 at 11 38 36 AM copy](https://github.com/uiowa/uiowa/assets/102074414/b3f97172-d5ad-4ba9-9177-28f395e9d856)

While this approach is certainly not 100% ideal from a visual space perspective. It feels like the path of least resistance, and aligns with a known future where eventually CCOM will be rolling out the block IOWA logo as its preferred logo, and we could see a future where CCOM site headers stay perfectly in lock step with other college headers.

Example:


<img width="912" alt="Screenshot 2023-08-18 at 11 42 00 AM" src="https://github.com/uiowa/uiowa/assets/102074414/a92677af-d834-40eb-94ff-7c567f2df6a5">


Certainly do not want to close the door on other creative solutions. But this was where my head was going to stay compliant with current logo requirements.

**Comment by bspeare** [comment]
Thanks @maxwell-freund, that is useful to see your screenshots!

**Comment by pyrello** [comment]
> For team grooming: Non-regents option currently allows logo swap. Is there a slice through this where it makes sense for us to use that functionality to allow logo option?

I think it would be preferable to just add an appropriate CCOM logo file to the theme and then set the path to the logo based on a theme setting. Using the custom logo option means that we would be uploading the same logo to all CCOM sites that get set up on the SiteNow platform, which is both redundant and introduces the possibility of human error. 

Here is my proposed solution:
Add an option at the top of the theme settings form to allow selecting a branding option:
- Iowa
- CCOM
- Regents

This option would only be visible to Administrators (CCOM and OSC web teams).

Based on that selection, we could set the appropriate logo image and favicon (or expose the fields for changing them based on selecting the regents option). We might be able to do away with the Color Palette section until we introduce another regents option color palette).

**Comment by briand44** [comment]
Grooming conversation... Max double check on using UIHC Golden dome in header. Pair with UIHC MarCom developer. Implement based on theme setting Sean suggested above. Use dome favicon.

**Comment by joewhitsitt** [comment]
For the favicons, we will need the dome to be run through https://realfavicongenerator.net/ or https://favicon.io/ for full coverage with our current set of options (ios, android, etc.)

**Comment by maxwell-freund** [comment]
Team, 

Providing an update, the suggestion to add the UI Health Care "Golden Dome" logo into the black tab, and then levarage the parent gold bar text space to read: Carver College of Medicine, followed by the h1 white secondary header space to show the variable site name "Department of Family Medicine" for instance, has been selected by our CMO as preferred to the single large block icon in the tab.

We can proceed with this plan to adjust IOWA logo to UI Health Care in tab.

**Comment by bspeare** [comment]
@ethan-fry do you have availability to pair on this today?

**Comment by ethan-fry** [comment]
@bspeare 
![logo](https://github.com/uiowa/uiowa/assets/54082244/4e547963-ce8b-4f1f-8d38-cccf1c8b5fd5)
Here is the svg of the icon for CCOM

**Comment by ethan-fry** [comment]
![Image](https://github.com/uiowa/uiowa/assets/54082244/d0e58c16-683a-438e-8091-f0b2998153b4)

**Comment by maxwell-freund** [comment]
Regarding Title Tag Architecture / Adjustments.
If a site is tagged for College of Medicine Branding, adjust the title tag architecture as follows:

{Page H1} | {Subsite Name} - Carver College of Medicine

Thank you

**Comment by ethan-fry** [comment]
@bspeare see comment above
