### ISSUE TITLE
Development Feature - CCOM Report an issue footer link

### ISSUE THREAD

**Issue by maxwell-freund** [uiowa/uiowa#6630]
# Story

As a team managing CCOM websites, we would like to include our "Report an issue with this page" link, with automated URL parameter inclusion in the link so that users can quickly report issues for a particular page to the appropriate place.

**Comment by joewhitsitt** [comment]
>"Report an issue with this page"

https://github.com/uiowa/uiowa/issues/1881

**Comment by maxwell-freund** [comment]
@joewhitsitt I am assuming you tagged #1881 to tie together a previous ask to this one?  No further action / discussion needed from me on this ask currently?

**Comment by joewhitsitt** [comment]
Yeah I am just linking similar ideas together

**Comment by maxwell-freund** [comment]
Current code on Drupal 7 CCOM that populates this link:

```javascript
!(function ($, Drupal) {
  'use strict';
  Drupal.behaviors.footerLinkBehavior = {
    attach(context) {
      const redmineReferrer = window.location.href;
      const redmineLink =
        '<li class="link-list__item"><a href="http://hc-vbugtracker.healthcare.uiowa.edu/projects/uihc-org/issues/new?issue[custom_field_values][1]=' +
        redmineReferrer +
        '" target="_blank">Report an issue with this page</a></li>';
      const linkList = $(
        '.link-list-menu__title:contains(\'Employees & Community\')'
      )
        .parent()
        .find('.link-list');

      linkList.append(redmineLink);
    }
  };
})(jQuery, Drupal);
```

**Comment by ethan-fry** [comment]
@joewhitsitt 

All the code in @maxwell-freund comment is not being included. But I can share more when necessary.

**Comment by joewhitsitt** [comment]
fyi, github supports markdown `code snippets` and

```
code blocks
```

**Comment by ethan-fry** [comment]
@joewhitsitt 

```
!(function ($, Drupal) {
  'use strict';
  Drupal.behaviors.footerLinkBehavior = {
    attach(context) {
      const redmineReferrer = window.location.href;
      const redmineLink =
        '<li class="link-list__item"><a href="http://hc-vbugtracker.healthcare.uiowa.edu/projects/uihc-org/issues/new?issue[custom_field_values][1]=' +
        redmineReferrer +
        '" target="_blank">Report an issue with this page</a></li>';
      const linkList = $(
        '.link-list-menu__title:contains(\'Employees & Community\')'
      )
        .parent()
        .find('.link-list');

      linkList.append(redmineLink);
    }
  };
})(jQuery, Drupal);

```

**Comment by joewhitsitt** [comment]
I wonder if this could be built in a way it could default to filling in the contact form that ships with v3 default_content but then can be configured to point to http://hc-vbugtracker.healthcare.uiowa.edu/projects/uihc-org/issues/new or that constructs a mailto and allows mapping of the window.location.href, page title, timestamp, etc.

It can be turned on per site and would also resolve https://github.com/uiowa/uiowa/issues/1881

**Comment by ethan-fry** [comment]
@joewhitsitt curious as to if we can use the current branding options in uids_base and then create an alternate footer--socket-menu.twig if ccom has been selected that would include the "Report and issue with this page"  link including the js that would be needed to create the link?

**Comment by joewhitsitt** [comment]
`footer--socket-menu.twig` is hardcoded all the way back to uids. if that is where you think it should be placed i think work could be done to make it more flexible for things like this. of course it would be easier to just to add another item similar to footer_login_link to docroot/themes/custom/uids_base/templates/layout/footer.html.twig

I imagined there would be backend config to opt-in and configure it. Wherever the link is placed, the necessary js to grab the current page information would be loaded.

Out of the box for all sites though I was thinking it would link/fill in details of the [default contact form](https://default.prod.drupal.uiowa.edu/form/contact) on the site or construct a `mailto` link to the site email address with the same details so all sites could just run with it. Then for more advanced usage, it can be configured to do what you have here and fill out your bugtracker form where you would map each value to a parameter and provide the URL endpoint.

**Comment by briand44** [comment]
- Users submitting issues - anyone on healthcare prem currently can submit. This may change to anyone on University campus. Mostly Healthcare employees and specifically CCOM departmental folks are submitting these.
- Bug tracking system users - MarCom web content team and occasionally MarCom devs.
- publicly available webform probably wouldn't work in this case because they don't want to open it up to the public.
- Placement - some flexibity, feels like similar to admin login link.
- Existing privacy notice link , accessibility link , etc. are the appropriate links for CCOM.
- Need some way to enable this for all CCOM sites, whether that is the theme setting or some other approach
- URL is only field that gets auto populated

**Comment by briand44** [comment]
Grooming conversation...  focus this on CCOM's needs for now. Likely a feature split.

**Comment by briand44** [comment]
@GaryRidgway Any chance you can comment here on how someone would go about turning this on for a CCOM site?

**Comment by briand44** [comment]
Also, closing this as the work is done here

**Comment by GaryRidgway** [comment]
> @GaryRidgway Any chance you can comment here on how someone would go about turning this on for a CCOM site?

No problem!

You can either do:
`ddev drush @SITE.ENV config-split:activate ccom -y`
or, you can enable it through the config split configuration page at:
https://default.uiowa.ddev.site/admin/config/development/configuration/config-split

**Comment by ethan-fry** [comment]
@GaryRidgway apologies it took me so long to get to this I ran the command on the medicineappil.prod.drupal.uiowa.edu site and everything ran fine and looks good. Thanks for the work on this!
