### ISSUE TITLE
Development Feature - Jobs @ Iowa Integration - Exploration of Data Feeds

### ISSUE THREAD

**Issue by maxwell-freund** [uiowa/uiowa#6631]
One of our most common points of feedback received from site owners when we probed them on additional data integrations was the desire to showcase open positions on their sites.

Currently we lack any integration with the Jobs @ Iowa website to showcase a feed/widget of any kind.

This task is to explore the possibility of a feed that could be leveraged for this kind of visualization on a specific subsite. Preferably with some level of filtering / segmentation possible.

**Comment by joewhitsitt** [comment]
We are running into [limitations](https://github.com/uiowa/uiowa/issues/5615#issuecomment-1721685903) with folks trying to display job feeds with just the RSS Feed block/aggregator.

Careers has previously had issues as well using Handshake feeds. https://github.com/uiowa/uiowa/issues/5614

I think it is worth creating a jobs specific block where listings can be displayed and they fall off once they are no longer in the source.

**Comment by maxwell-freund** [comment]
@joewhitsitt would love to hear more about how you have tried to support showcasing jobs via RSS feed block/aggregator in the past. Or what other work has been explored.

I will share that I emailed with Matt Mason who is an app dev that supports the jobs platform about 2 months ago regarding any update from him on making it easier to query the jobs platform for a subset of results.

His correspondence back is as follows:

"Hi Max - I have been actively working on a custom solution that is just about ready to go into beta testing.  Oracle simply isn’t going to fix the issue with the widget, and I/we realize it’s a need across campus. The solution is an RSS feed very similar to Faculty, that will be able to be sliced and diced in many different ways.  You are one of the folks on my list to contact when it’s ready – I would say in the coming weeks/month (barring any issues)."


I have yet to hear back from him on that becoming available. And what exactly would be required to query, or then of course, how we would even approach making that user-friendly and a component that someone could add to a page. 

All very much TBD... But this acknowledgement of a more structured and available way to query results was exciting, so, sharing that here, and happy to re-ping him soon to get an updated status.

**Comment by joewhitsitt** [comment]
@maxwell-freund what brought me to this issue today is a support email with Matt. It has been observed that the RSS Feed block does work with the feeds he is producing, but the block itself acts in a way that items are 'aggregated' and don't expire/fall off requiring manual intervention. This is the limitation I linked: https://github.com/uiowa/uiowa/issues/5615#issuecomment-1721685903

**Comment by maxwell-freund** [comment]
@joewhitsitt gotcha. Then you are further along / more informed on Matt's progress than I was.

Happy to learn more at the appropriate time, and will watch the tickets as they unfold.

**Comment by joewhitsitt** [comment]
Matt provided us with some documentation about the feed(s) that are available (its-web inbox Matthew Mason). [I've uploaded it to the Teams docs](https://iowa.sharepoint.com/:b:/r/sites/CSI-Drupal2/Shared%20Documents/General/Staff%20Job%20RSS%20Feed%20Reference.pdf?csf=1&web=1&e=vQehix).

>the feed can be also be consumed as XML or JSON

> Happy to go over this when Web Technology Services is ready.

**Comment by ethan-fry** [comment]
@joewhitsitt @maxwell-freund @briand44 

Meeting with Matt Mason is scheduled for Oct 13th at 11am

**Comment by briand44** [comment]
@maxwell-freund @joewhitsitt 

Here are my takeaways from todays meeting. Feel free to add anything I missed.

- The ability to have a block/component that takes a valid RSS endpoint (URL) and returns the results
- Results would include title (linked to value of `<link>`)
- An option to show description
- An option to show category
- The ability to page results (ability to set items per page?)
- 1-3 hour cache lifetime (sounds like the jobs feed updates every 3 hours starting at midnight)
- Discussed possible headline field, discussed possible field to enter more link

There is a need for this on the SiteNow platform (CCOM and others) as well as a need for UIHC. Should probably discuss if these are two separate builds, one module that can be used in either, or somewhere in between.

If existing RSS block/Aggregator functionality had the option to purge items no longer in the feed source, that would be a workable solution. https://github.com/uiowa/uiowa/issues/5615

**Question**
I don't see PubDate in the jobs RSS. Is that something we would want the ability to show as well?

**Jobs feed Docs**
https://iowa.sharepoint.com/sites/CSI-Drupal2/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FCSI%2DDrupal2%2FShared%20Documents%2FGeneral%2FStaff%20Job%20RSS%20Feed%20Reference%2Epdf&parent=%2Fsites%2FCSI%2DDrupal2%2FShared%20Documents%2FGeneral

**Comment by maxwell-freund** [comment]
@briand44 @joewhitsitt @ethan-fry 

I have read through everything you listed from Friday, and agree with it. This represents the scope of the conversation. I do want to add 3 more points to the list for consideration:

1. is there more grooming needed to discuss whether this jobs block/component would have settings that are applied site-wide for a given site on SiteNow, or could be used many times within a single site, if that site chose to fragment out their recruitment funnel by different pages / purposes? 
2. The collaboration of development/design between a sitenow version and a uihc.org version. Ethan thinks the code will diverge quickly due to some structural differences. But we are 100% supportive in aligning on filtering strategy / functionality supported, and if possible, the design.
3. I wanted to make sure we document that the faculty feed. Example seen here: https://jobs.uiowa.edu/jobSearch/rss/feeds/faculty/depts/17/faculty.xml That the people on the call thought the value of an intermingled jobs widget of faculty and non faculty jobs, was a low value. And so we do not need to plan for that. However, the idea of a faculty jobs widget is of high value to colleges. And so if we want to stub out a second ticket to represent the faculty jobs feed -> having it take inspiration in design, and functionality from this non faculty jobs feed. It might be best to look at those two in tandem? While knowing they are separate asks / needs / data sources.

**Comment by briand44** [comment]
My quick thoughts in response to https://github.com/uiowa/uiowa/issues/6631#issuecomment-1765289367.

1. My assumption is that this would be a component that could be used multiple times within a single site and there would not be any site-wide settings.
2. Sounds good, I'll let the OSC devs weigh in here as well but that was the feeling I got from Joe when he brought up headline field, etc.
3. I envision that the single block/component that is developed here could be used for staff jobs, faculty jobs, or for pulling in any type of content that meets RSS spec. They would just need to specify the faculty jobs endpoint in the block/component settings. I do see that the faculty feed has more data (PubDate, image, etc), which may give us a reason to include PubDate (My question from https://github.com/uiowa/uiowa/issues/6631#issuecomment-1762036669).

**Comment by briand44** [comment]
Initial grooming discussion... Sounds like it will likely need to be developed separately since uihc.org is not using layout builder. We should align on functionality, editor experience and design though where possible.

Will need to groom more

**Comment by briand44** [comment]
Grooming conversation... We feel we should probe aggregator more before moving forward with a new component.

**Comment by joewhitsitt** [comment]
It hasn't been deployed yet, but we moved forward with a solution to purge items routinely through aggregator/rss feed block in sitenow. There is now a per source (not block) option to "purge items" each time the feed is fetched.

https://sitenow.uiowa.edu/documentation/layout-builder/rss-feeds

I am still interested to see what comes of the agolia method and could be something with incorporate into sitenow down the road.

**Comment by briand44** [comment]
Communicated that our aggregator enhancements are currently being deployed to our UIHC MarCom partners and based on feedback provided by Max, I am going to close this. If issues arise while implementing jobs or other feeds on CCOM or other SiteNow v3 sites, we can open a new issue.
