### ISSUE TITLE
Ability to schedule publishing/unpublishing alert content

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6637]
# Story

As an editor using the SiteNow alert feature, we would like to be able to schedule alerts to be published/unpublished at a period of time in the future.

# Additional Info

Summary from probe https://github.com/uiowa/uiowa/issues/6585#issuecomment-1631098306

Scoping to alert feature not just Facilities.

Alert feature does not currently have content moderation so we don't currently need https://www.drupal.org/project/scheduler_content_moderation_integration.

We would also want to remove the field that is part of the Facilities split that is related to publishing date. 

# Proposed solution

- Use https://www.drupal.org/project/scheduler to allow scheduling when to publish/unpublish alerts for the alert feature
- Verify publishing happens within an hour of chosen time
- Verify we are not seeing any performance concerns
- Remove the field on the Facilities split that is related to when to publish
- Communicate with Facilities that it will publish/unpublish within an hour and that if we run into issues of performance down the road, they may need to manually publish/unpublish alerts while we chart a new path.

**Comment by quamsta** [comment]
Related https://github.com/uiowa/uiowa/issues/5861

**Comment by bspeare** [comment]
Any suggestions on this help text adjustment for the scheduler?

<img width="617" alt="Screenshot 2023-07-18 at 11 13 28 AM" src="https://github.com/uiowa/uiowa/assets/1036433/1d71ee7a-4a2d-41e2-a5ef-0285044ca8b5">

Edit:

<img width="649" alt="Screenshot 2023-07-18 at 11 26 17 AM" src="https://github.com/uiowa/uiowa/assets/1036433/49fd25b6-9458-4b03-8719-bcc4a542ecfa">

**Comment by briand44** [comment]
If it is easier to keep the help text the same for each, then I think it looks fine from my perspective. Otherwise, you could change scheduled to published and unpublished accordingly?

**Comment by bspeare** [comment]
Here's what the updated fieldset placement looks like.  Should we move it here?

https://github.com/uiowa/uiowa/assets/1036433/367f58ec-6856-4831-8f56-24a8b8ad5a21

**Comment by pyrello** [comment]
> Here's what the updated fieldset placement looks like. Should we move it here?

I was actually thinking that it should go below the "Published" checkbox.

**Comment by bspeare** [comment]
It doesn't seem to move the position on `/admin/structure/types/manage/alert/form-display` - are you thinking that we form alter that?

**Comment by briand44** [comment]
From the Facilities perspective, since they currently schedule all of their alerts and will continue to schedule the vast majority of alerts, I think it makes sense for the scheduling to appear before the published field.

**Comment by joewhitsitt** [comment]
i'm fine with the fieldset as shown in https://github.com/uiowa/uiowa/issues/6637#issuecomment-1642768464. A quick change with UX improvement that we can shop around for feedback.

As Ben mentioned, the published checkbox is not part of the form display and would be more involved to work with.

**Comment by bspeare** [comment]
Thanks for chiming in, @joewhitsitt could you pull that down one more time and verify that the form placement matches the screencast and then I'll merge it?

**Comment by pyrello** [comment]
> From the Facilities perspective, since they currently schedule all of their alerts and will continue to schedule the vast majority of alerts, I think it makes sense for the scheduling to appear before the published field.

I'm good with leaving it where it is for the time being. If/when this functionality becomes more widely available, my thought was that we could show/hide the scheduled publish and unpublish based on whether the user had already selected "Published" or not. It doesn't really make sense to publish a node and then schedule a node to be published.

**Comment by joewhitsitt** [comment]
>could you pull that down one more time and verify that the form placement matches the screencast and then I'll merge it?

Sorry, I can in a bit. Got another branch checked out ATM.

FWIW, the commit looks fairly clean.

**Comment by quamsta** [comment]
> > From the Facilities perspective, since they currently schedule all of their alerts and will continue to schedule the vast majority of alerts, I think it makes sense for the scheduling to appear before the published field.
> 
> I'm good with leaving it where it is for the time being. If/when this functionality becomes more widely available, my thought was that we could show/hide the scheduled publish and unpublish based on whether the user had already selected "Published" or not. It doesn't really make sense to publish a node and then schedule a node to be published.

Unless I'm misunderstanding, would hiding fields based on the state of the node make it more difficult if something was accidentally published and someone wanted to unpublish and schedule in one edit?

Also, if the publish/unpubplished date fields are hidden, is there a way to see when an alert was set to be published while editing the published node?
