### ISSUE TITLE
Only show upcoming events for OnIowa

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6646]
# Story

As an OnIowa site owner, I would like to only see events occurring today or future days so that users don't have to sift through events that have already taken place.

# Additional Info

Currently past events are showing https://oniowa.uiowa.edu/events

# Proposed Solution

- Limit events display to show only current day and upcoming
- possibly limit cache lifetime of event day filter

**Comment by joewhitsitt** [comment]
Thanks for capturing this @briand44

**Comment by pyrello** [comment]
As far as changing the cache lifetime goes, do we want to have it expire at midnight?

**Comment by briand44** [comment]
I think that would work from our partners perspective...

**Comment by pyrello** [comment]
This is done in #6626.
