### ISSUE TITLE
Captcha on CSA and Public Clery forms

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6647]
# Story

As a safety website owner, we would like to limit spam submissions through the CSA and Public reporting forms.

# Additional Info

Feedback from Clery Edge:

> On our side, we have implemented throttling measures to help protect against such issues. Additionally, we recommend considering the following recommendations:
> 
> Implement CAPTCHA: Consider incorporating CAPTCHA (Completely Automated Public Turing test to tell Computers and Humans Apart) as an extra security measure. It can help differentiate between automated bots and genuine human users.
> 
> Use IP/URL Blocking/Whitelisting: Identify and block suspicious IP addresses/URLs known to be associated with spam or malicious activities. This is what we have also implemented in our external reports. We whitelist the client's URL so they can hit our endpoints.

# Proposed Solution

**Comment by briand44** [comment]
grooming convo... see if we can extend existing spam prevention measures to non-drupal forms, if not try something new.

**Comment by joewhitsitt** [comment]
i did implement hcaptcha on a personal website this weekend and have some lessons learned if we end up going that way.

**Comment by pyrello** [comment]
I'm trying to follow the thread of this back to the relevant site/page where these updates would be made, but failing. Can someone provide a link to where these updates are being made?

**Comment by joewhitsitt** [comment]
I believe these are the forms:

https://safety.prod.drupal.uiowa.edu/csa-reporting
https://safety.prod.drupal.uiowa.edu/public-incident-reporting-form

**Comment by joewhitsitt** [comment]
@pyrello are you taking this on?

**Comment by joewhitsitt** [comment]
>i did implement hcaptcha on a personal website this weekend and have some lessons learned if we end up going that way.

looks like i misunderstood the docs and have not properly implemented hcaptcha.

**Comment by pyrello** [comment]
Did some initial digging for this:
- The form is generated and submitted client-side. That means that any spam protection needs to be entirely handled client-side.
- hCaptcha (as Joe noted) does not appear to have a client-side validation mechanism.
- It looks like maybe reCaptcha v2 has a mechanism for validating the response client-side. If such a thing exists in v3, it isn't well documented.
- I'm not finding anything besides reCaptcha v2 for captcha libraries supporting client-side validation.
- We could potentially implement our own basic honeypot (Add a field that should not be filled in, then hide the field using JavaScript and prevent form submissions if the field is filled in). 
- We could also potentially implement a timer and reject submissions that occur in less than n seconds.
- However, the testing and maintenance of custom solutions (or even reCaptcha) is complicated by the fact that this form is built inside a text area.
- I would like to get some clarity on the desired path forward before I invest more time in this.

**Comment by pyrello** [comment]
- Honeypot does not have a client-side component.
- Antibot does have a client-side component, but we would have to figure out how to get around the fact that their script checks a list of allowed forms.

**Comment by joewhitsitt** [comment]
We have previously used reCaptcha v2 for SiteNow v1 custom sites (e.g. Engineering, etc.). As we wait for Kirk from ISPO to respond our email (its-web), I am curious if @mjoneill has any concerns about using Google reCAPTCHA v2 for this site only and not as a part of a platform-wide change.

Given that CleryEdge already has some protection in place, I'd vote to keep this investment as minimal as possible.

**Comment by mjoneill** [comment]
> I am curious if @mjoneill has any concerns about using Google reCAPTCHA v2 
> for this site only and not as a part of a platform-wide change.

I think my concern would more likely to surface if we decided to jump into a platform-wide change without first learning about it. It sounds like deploying it to one site gives us the opportunity to learn from an actual deployment of it, and keeps options open for making it a standard, etc.  It does come at the cost, however, of increased debt burden of yet another one-off thing.

**Comment by pyrello** [comment]
I'm going to move forward with reCaptcha v2 for this site. 

From my perspective, there is not much to learn from a standpoint of the platform because I don't think we would want to implement the v2 version of reCaptcha on the SiteNow platform since it is likely to be deprecated at some point. The specific conditions that make reCaptcha v2 appropriate for this are not the conditions that we normally need to meet, so we probably would pick another library or the v3 reCaptcha library.

**Comment by bspeare** [comment]
Since Clery has "_implemented throttling measures to help protect against such issues_", should we delay this work for launch and see if spam becomes an issue?

**Comment by joewhitsitt** [comment]
>Since Clery has "implemented throttling measures to help protect against such issues", should we delay this work for launch and see if spam becomes an issue?

I wasn't sure if the request from Public Safety was because they were already seeing spam or if they just assumed they would need it based on past experience.

Re-reading the docs for reCaptcha (v2), it suggests server-side validation as well. You can do some client-side validation but I believe all they would have to do is hit it without JS enabled. Still it would be more protection than not. I think I could move that forward if desired.

If we want more protection given what they have given us, we should expect them to handle/provide the server-side verification whether that is filtering out a honeypot submission or validating a CAPTCHA response.

**Comment by bspeare** [comment]
@joewhitsitt I think the CAPTCHA request was originally just a preventative ask.  They have not mentioned that they were being spammed yet.

**Comment by joewhitsitt** [comment]
might want to see if we can fly without it. that said i put a simple example out here
https://safety.prod.drupal.uiowa.edu/spam-protection-test

this does not properly implement recaptcha. this, with JS makes "filling" out captcha required and it doesn't fill out without a result from the captcha.

**Comment by joewhitsitt** [comment]
I arrived late to the meeting this morning but Ben said, they can launch without this and see if the spam hits.

**Comment by mjoneill** [comment]
Possibly a case of, "Simplicity--the art of maximizing the amount of work not done--is essential"?

Glad we asked the question!

**Comment by pyrello** [comment]
@briand44 Are we good with closing this?

**Comment by joewhitsitt** [comment]
Capturing the faux-CAPTCHA

```html
<style type="text/css">
  #g-recaptcha-response {
    display: block !important;
    position: absolute;
    margin: -50px 0 0 0 !important;
    z-index: -999999;
    opacity: 0;
  }
</style>
<form action="?" method="POST"><label>Your message:<textarea name="message"></textarea> </label>
  <div class="g-recaptcha" data-sitekey="{INSERT SITE KEY}">&nbsp;</div>
  <br />
  <input type="submit" value="Submit" />&nbsp;
</form>
<script src="https://www.google.com/recaptcha/api.js" async defer></script>
<script>
  window.addEventListener('load', () => {
    const $recaptcha = document.querySelector('#g-recaptcha-response');
    if ($recaptcha) {
      $recaptcha.setAttribute('required', 'required');
    }
  })
</script>
```

**Comment by mjoneill** [comment]
> i did implement hcaptcha on a personal website this weekend and have some lessons learned if we end up going that way.

@joewhitsitt I'd be interested in reading your opinion on whether or not it's worth exploring.  Concerns? Red flags?  Things you liked?

**Comment by joewhitsitt** [comment]
> > i did implement hcaptcha on a personal website this weekend and have some lessons learned if we end up going that way.
> 
> @joewhitsitt I'd be interested in reading your opinion on whether or not it's worth exploring. Concerns? Red flags? Things you liked?

It was revealed through Sean's probe that I did not properly implement hCaptcha on the site because of the need for server-side verification. instead i switched to a form provider formspree.io that offers google recapatcha and proper verification on their end.
