### ISSUE TITLE
Photo Gallery Block: Last few images crop strangely

### ISSUE THREAD

**Issue by quamsta** [uiowa/uiowa#6650]
Hi all, greetings from the other side of the river! I'm working on some lab websites over here in the Department of Pathology with photo galleries and while I noticed this before, I'm not sure if there's already an issue made for this.

# Problem

On some display sizes, if there aren't enough images to fill a column, the remaining images in the non-masonry image gallery block are super wide and look strange:

https://labkarandikar.prod.drupal.uiowa.edu/lab-photos/group-photos-over-years

<img width="1575" alt="Screenshot 2023-07-13 at 1 26 21 PM" src="https://github.com/uiowa/uiowa/assets/472923/2ed08fd0-bd53-406f-b32a-0bd5e6cbf26c">

https://labkarandikar.prod.drupal.uiowa.edu/lab-photos/2013-2020-iowa-years

<img width="1416" alt="Screenshot 2023-07-13 at 1 32 03 PM" src="https://github.com/uiowa/uiowa/assets/472923/b9838ef0-111d-4186-b607-b01fdade29e8">

# Steps to reproduce

1. Create an image gallery with at least four images
2. Resize your browser viewport until one or two images "spill over"
3. Note the super wide crop

# Proposed solution

If we are to maintain the square image aspect ratio on the non masonry grid, this (or something similar) may work:

```
.uiowa-image-gallery photoswipe-gallery{
  display: flex;
  flex-wrap: wrap;
}

.contextual-region media media--type-image media--view-mode-image-gallery{
  flex: 0 0 auto; 
  width: 25%; 
  padding: 10px; 
  position: relative; 
}

.contextual-region media media--type-image media--view-mode-image-gallery:before {
  content: "";
  display: block;
  padding-top: 100%; 
}

.block-field-blocknodearticlefield-gallery-images .media--view-mode-image-gallery img, .block-inline-blockuiowa-image-gallery .uiowa-image-gallery .media--view-mode-image-gallery img{
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  object-fit: cover;
  padding: 5px;
}
```

Result:

https://github.com/uiowa/uiowa/assets/472923/0d406dc2-f8b1-4a40-b002-ce80a9416782

**Comment by bspeare** [comment]
Thanks for this @quamsta, what are your thoughts on this solution: https://github.com/uiowa/uiowa/issues/5386?

**Comment by bspeare** [comment]
@quamsta can you review the screenshots and videos on https://github.com/uiowa/uiowa/pull/6881#issuecomment-1720057208 and provide any feedback that you might have?

**Comment by quamsta** [comment]
@bspeare Will check on this! Missed this comment somehow, thanks!
