### ISSUE TITLE
ITS Services content type

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6666]
# Story

As an ITS webmaster, I would like to to be able to create service content so that services can be dynamically displayed to our users.

# Additional Info

**Existing mockups - based on initial feedback**
All services page: https://sandbox.prod.drupal.uiowa.edu/all-services-and-software-copy
Results page: https://sandbox.prod.drupal.uiowa.edu/results-page
Services page: https://sandbox.prod.drupal.uiowa.edu/its-service-office-365-mockup

**Fields we are fairly confident ITS needs**
Title
Also known as (alias/synonym/alternate name)
Description/Body/teaser
Need a way to feature
Way to designate audience
Service category
Related services

Fees?
Website?
Quick Links?

# Proposed Solution

- [x] Setup site split
- [x] Create content type and path alias according to https://wiki.uiowa.edu/display/drupaldev/Content+type+creation+notes
- [x] layout builder

**Comment by pyrello** [comment]
I definitely like the version of the service full node page without accordions better.

**Comment by bspeare** [comment]
@pyrello I do too!

**Comment by joewhitsitt** [comment]
Grooming conversation:

Wait for more feedback from ITS, get more input on the desire for a resources content type to see where the similarities/differences are: https://github.com/uiowa/uiowa/issues/6723

**Comment by bspeare** [comment]
Reached out to Adrienne last week and she said they are hoping to get us feedback soon.

**Comment by briand44** [comment]
Grooming conversation... Site split + content type + path alias + layout builder. Follow https://wiki.uiowa.edu/display/drupaldev/Content+type+creation+notes

Address fields in a separate future slice.
