### ISSUE TITLE
Identify D7 sites (SiteNow/Clas/Grad) that likely need custom development

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6669]
# Story

As a web team, we would like to understand how many Drupal 7 sites still exist on our platform that likely need custom development so we have a good understanding of how much work is left to get those on v3.

# Additional Info

Need to include SiteNow/Clas/Grad as part of this list.

Discussed creating a more usable/filterable spreadsheet.

Existing spreadsheet
https://iowa.sharepoint.com/:x:/r/sites/CSI-Drupal2/_layouts/15/Doc.aspx?sourcedoc=%7Ba3958afa-fa30-492a-948e-0a3368521d3d%7D&action=edit&wdinitialsession=1ce0992b-4080-437c-bae6-43d57bcc688d&wdrldsc=8&wdrldc=2&wdrldr=BootTimeMismatch&cid=a06d1b79-7b6c-4998-9b66-f534e0eccbf3

Spreadsheet Michael created using ScreamingFrog
https://iowaweb.slack.com/archives/C0164FNN1PV/p1689710115728239?thread_ts=1689709668.699789&cid=C0164FNN1PV

# Proposed Solution

**Comment by e-marie-w** [comment]
Can I assume the site is completely done if marked green in the existing spreadsheet, or should I double-check each one?

**Comment by joewhitsitt** [comment]
> Can I assume the site is completely done if marked green in the existing spreadsheet, or should I double-check each one?

Nope. Some say site launch, but not all have been removed, etc.

**Comment by briand44** [comment]
>Nope. Some say site launch, but not all have been removed, etc.

@joewhitsitt is that true? I only mark something as green once it has been removed. My assumption was anything that is green is no longer in D7 land.

**Comment by briand44** [comment]
I guess I see wirrc.org as green. Shouldn't be in my mind but it is.

**Comment by joewhitsitt** [comment]
yeah, law is in as green too. can't assume all.

**Comment by e-marie-w** [comment]
I started off with a new sheet for all sites, but since this slice is specifically for identifying custom development I made a sheet for just that. I copy pasted our existing list over and am currently removing green sites - they aren't necessarily done, but they at least have a v2 or v3 site launched, a redirect, or removed. Cross-referencing with the screamingfrog spreadsheet is really helpful for double-checking the status.

**Comment by e-marie-w** [comment]
I do have a question, how are the weekly site counts calculated? Is it the list of domains on the app, minus any .prod.drupal and redirects?

**Comment by joewhitsitt** [comment]
site counts are scheduled jobs (separate for v2/v3) that runs `blt ume` on the remote (prod) and checks to see if the v2 feature is enabled and keeps a count, sends an email.

it doesn't know if the site has "launched," only that the database is not empty and the configuration is set. the counts go up as soon as the site is installed.

**Comment by e-marie-w** [comment]
Yeah that makes sense. I'm specifically looking at the misc. d7 for grad. Since the app in acquia has more domains and databases listed I was trying to figure out what caused the lower reported number. Some of it is the different writing university domains I know.

**Comment by joewhitsitt** [comment]
the grad app has a mix of domains for redirects, www coverage, keeping old sites around and not immediately deprovisioning.

Without looking myself, I wanna say that Brian said earlier that there are only like 3 sites left on grad?

**Comment by e-marie-w** [comment]
This slice is completed.
