### ISSUE TITLE
Public Incident reporting form changes

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6672]
# Story

As an owner of safety.uiowa.edu, we would like some updates to the Public Incident reporting form so that it operates as desired for launch.

# Additional Info

They would like to remove the "Have you previously reported this incident?" field.

There are likely changes to the "Type of Incident" select list. https://github.com/uiowa/uiowa/issues/6672#issuecomment-1644208939

The file upload is still not showing up on the Clery side after submitting the form. Public Safety is talking with Clery Edge about this.

# Proposed Solution

- [x] remove previously reported field
- [x] Any necessary changes to the type of incident field
- [x] any potential changes around the file upload? https://github.com/uiowa/uiowa/issues/6672#issuecomment-1650136440

**Comment by briand44** [comment]
>Cathy and I spoke about this. I do not think we need the drop down menu unless it is going to cause a problem in not having it. If we have to have it, then one entry “Report a crime the The Office of Clery Compliance” and “Other” would work.

**Comment by GaryRidgway** [comment]
I have created a draft of the new form [here](https://safety.prod.drupal.uiowa.edu/node/371/latest), but I as I start to move on to the document submission I am trying to think of ways that we could debug this. Does Clery have some example code of a file upload that they know works?

**Comment by briand44** [comment]
I would hold off on working on the file submission unless something jumps out at you that looks wrong. The vendor is supposed to be looking into this.

**Comment by GaryRidgway** [comment]
Sounds good, I will block this for now then

**Comment by bspeare** [comment]
I looked at the form and I can confirm `incidentpreviouslyreported` field has been removed.  Too bad https://safety.prod.drupal.uiowa.edu/node/371/revisions/view/4861/6326/split_fields doesn't really show you the code changes.  I have published the updated page.

**Comment by briand44** [comment]
Had some conversations with public safety and it sounds like they would like some additional help text on the file upload field on this form and the CSA form stating the following restrictions:

Allowed extensions: "PDF", "DOCX", "XLSX" - I think this is already there.
Max size for a file that is being uploaded: 1024KB
The name of the file should not exceed 80 characters

**Comment by briand44** [comment]
I think we can consider this done once we add the help text to the forms ^^

**Comment by cory-skeers** [comment]
Added help text to the public incident reporting form (https://safety.prod.drupal.uiowa.edu/public-incident-reporting-form)
<img width="578" alt="image" src="https://github.com/uiowa/uiowa/assets/49074566/20f7b984-3319-4468-b64e-2f06461508e6">


And CSA reporting form (https://safety.prod.drupal.uiowa.edu/csa-reporting)
<img width="578" alt="image" src="https://github.com/uiowa/uiowa/assets/49074566/d4f0f149-42d3-4a06-8db7-ca9f6e9c128c">

I left it as `Allowed types: pdf, docx, xlsx.` since that was what was already there (rather than `Allowed extensions: "PDF", "DOCX", "XLSX"`)

@briand44 any extra changes or conversations needed, or is this fully good to close?

**Comment by briand44** [comment]
There isn't anything else that I am aware of unless someone else on the team wants to review your changes. There is a meeting scheduled for Monday with Public Safety. I am good with closing this and creating follow up issues if anything comes up on Monday.

**Comment by cory-skeers** [comment]
I did a diff check on the revisions to make sure, and this is the only flagged difference on the CSA reporting form.

<img width="1048" alt="image" src="https://github.com/uiowa/uiowa/assets/49074566/454aac02-3281-4c20-8843-5a99e465f704">

Public incident reporting form flags as a lot more changes, but outside the expected changes, they all appear to be related to the removal of spaces between html elements and not substantive changes to the form itself.

I think they were small enough changes then that it's safe to close out and we'll see what Monday brings.

**Comment by briand44** [comment]
I let Public Safety know we made the help text updates for the file restrictions.
