### ISSUE TITLE
Transition teaser content into the body summary field

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6674]
Epic: https://github.com/uiowa/uiowa/issues/5025

# Story

As a web team, we can have our teaser content in the body summary field so that we are in good position to remove the teaser field in order to reduce technical debt.

# Additional Info

Do we need to run the audit again to make sure a large amount of additional instances aren't identified that require more comms?

# Proposed Solution
- [ ] Change field_person_bio type to long text with summary field type.
- [ ] Write an update hook that loops through page, article, person, event, residence_hall and moves field_teaser value over to summary if it isn't empty and different.
- [ ] Update all list blocks' hide field value from field_teaser to body
- [ ] Remove field_teaser from entity_form_display, entity_view_display
- [ ] Add temporary help text to content description fieldset.
- [ ] Enable summary for use on content types (person, event, article) and expand by default (all).
- [ ] Add body summary/trimmed smart_trim in place of field_teaser for templates.
- [ ] Audit whether the [following](https://github.com/uiowa/uiowa/blob/d121ad897e9b45cd3cda38d65b52fd3c2d5ec377/docroot/profiles/custom/sitenow/sitenow.profile#L1083-L1101) can be slimmed down
- [ ] Re-run the scan from https://github.com/uiowa/uiowa/issues/6610#issuecomment-1670305947
???
profit

Likely needs scheduled deployment since we're touching content.

**Comment by cory-skeers** [comment]
> Audit whether the [following](https://github.com/uiowa/uiowa/blob/d121ad897e9b45cd3cda38d65b52fd3c2d5ec377/docroot/profiles/custom/sitenow/sitenow.profile#L1083-L1101) can be slimmed down

The short answer is it can be removed completely, but the end functionality is slightly different.

Out of the box, using `[node:summary]` in place of `[node:field_teaser]` has this functionality built in, with the difference that the trimming needs to be set at the metatag level itself. So even if someone entered a summary of >300 characters, the description would be trimmed down to 300 (sort of...it trims to the end of the word that crosses the 300 character limit).

The old setup, using this code:

1. If there's a `field_teaser` entered, that gets used in the description
2. If there's no `field_teaser` entered, the body gets trimmed to ~300 characters and gets used

In the new setup, without this code:

1. If there's a `body summary` entered, that gets used in the description _and is trimmed to ~300 characters_
2. If there's no `body summary` entered, the body gets trimmed to ~300 characters and gets used

I think it's a fair change, and in fitting with the intent of meta descriptions, but it would be a change, so wanted to note it.

Note: this would be the case for each of the description metas (opengraph, ~twitter~X, etc)

> trimming needs to be set at the metatag level itself

Point of clarity edit: it needs to be set at each individual metatag field, as opposed to globally for all metatag info.

**Comment by cory-skeers** [comment]
> Change field_person_bio type to long text with summary field type.

As part of this work or followup, do we want to transition away from a separate `field_person_bio` field and into the standard `body` field? We could still label it "biography", but currently it's the only reason for certain separations or the need to account for multiple fields (different prop mappings from the Person bundle class as compared to the base Node, differences in filter naming convention in list blocks, etc.

With an initial code search, there doesn't look to be a lot of updates we'd need to make to accommodate this change, and since we already need an update hook to do a data-fetch, field-create, data-dump to transition field type, this might be a good time to just make the full switch.

**Comment by briand44** [comment]
needs an update to v2 meta stuff and then ready for review
