### ISSUE TITLE
Setup/verify appropriate perms for UIHC MarCom

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6675]
# Story

As a member of the UIHC MarCom team, I have the appropriate permissions to work with the SiteNow platform.

# Additional Info

Access to sites for devs, Max and content folks?
Appropriate access to UIowa Acquia applications for developers.
Github
Wiki

# Proposed Solution

- [x] D9 role mappings for MarCom developers
- [x] D9 role mapping for Max
- [x] D9 role mappings for content folks
- [x] Developer access to Uiowa Acquia applications with appropriate role
- [x] Grant UIHC MarCom devs access to the Wiki Space Drupal Developer Documentation
- [x] Grant UIHC MarCom devs access to GitHub as part of Developer team
- [x] Add max to GitHub as part of the Leader team

**Comment by briand44** [comment]
@ethan-fry @maxwell-freund Can you provide the names of the content folks who will need webmaster access to sites? I think I heard you mention Nola Riley but not sure who the others are these days.

**Comment by ethan-fry** [comment]
@briand44

- Dan Holterhaus 
     email: daniel-holterhaus@uiowa.edu 
     HawkID: dholterh
- Nola Riley 
     email: nola-riley@uiowa.edu 
     HawkID: rileyn
- Benjamin Nelson 
     email: benjamin-nelson@uiowa.edu 
     HawkID: bnelson3

**Comment by joewhitsitt** [comment]
@ethan-fry does Sean and Brady have Github accounts?

**Comment by joewhitsitt** [comment]
Nevermind. Found [bzalasky-uiowa](https://github.com/orgs/uiowa/people/bzalasky-uiowa) and [seandui](https://github.com/orgs/uiowa/people/seandui)

**Comment by joewhitsitt** [comment]
I believe this is done short of users actually testing their new access.

Wiki: https://wiki.uiowa.edu/display/drupaldev

There is a "SiteNow D7" wiki but it is mostly deprecated stuff that doesn't relate to the uiowa->uiowa05 apps, so I didn't extend access there. We are going to have to move stuff off the Wiki soon anyway though. #6442 

Looks like @bzalasky-uiowa did not accept the Acquia invite the first time around when the team was created so I sent it again.

![with great power](https://media.giphy.com/media/MCZ39lz83o5lC/giphy.gif)
