### ISSUE TITLE
Question: Can we add embed code for additional live streaming pages on the osc.prod.drupal.uiowa.edu site?

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6676]
Nick from the OSC video team sent along more pages to add to the OSC production site that will also need embed codes to them. Here are the additional pages that were created on the prod site and their corresponding embed codes.
 

https://osc.prod.drupal.uiowa.edu/live/test01
Add embed code from current OSC site
 
https://osc.prod.drupal.uiowa.edu/live/test02
Add embed code from current OSC site
 
https://osc.prod.drupal.uiowa.edu/live/testAWS
Add embed code from current OSC site
 
https://osc.prod.drupal.uiowa.edu/live/bor
Add embed code from current OSC site
 
https://osc.prod.drupal.uiowa.edu/live/cph
Add embed code from current OSC site
 
https://osc.prod.drupal.uiowa.edu/live/hancher
<div style="position:relative;overflow:hidden;padding-bottom:56.25%"><iframe src="https://cdn.jwplayer.com/players/IeovY81O-7EaCFiXK.html" width="100%" height="100%" frameborder="0" scrolling="auto" title="Hancher" style="position:absolute;" allowfullscreen></iframe></div>

 
https://osc.prod.drupal.uiowa.edu/live/imu
<div style="position:relative;overflow:hidden;padding-bottom:56.25%"><iframe src="https://cdn.jwplayer.com/players/5gtp7jvb-7EaCFiXK.html" width="100%" height="100%" frameborder="0" scrolling="auto" title="IMU" style="position:absolute;" allowfullscreen></iframe></div>

 
https://osc.prod.drupal.uiowa.edu/live/oldcap
<div style="position:relative;overflow:hidden;padding-bottom:56.25%"><iframe src="https://cdn.jwplayer.com/players/cWAVfBpn-7EaCFiXK.html" width="100%" height="100%" frameborder="0" scrolling="auto" title="Old Cap (oldcap)" style="position:absolute;" allowfullscreen></iframe></div>

 
https://osc.prod.drupal.uiowa.edu/live/music2
<div style="position:relative;overflow:hidden;padding-bottom:56.25%"><iframe src="https://cdn.jwplayer.com/players/exAodeEw-7EaCFiXK.html" width="100%" height="100%" frameborder="0" scrolling="auto" title="Music2" style="position:absolute;" allowfullscreen></iframe></div>

 
https://osc.prod.drupal.uiowa.edu/live/opencaps1
<div style="position:relative;overflow:hidden;padding-bottom:56.25%"><iframe src="https://cdn.jwplayer.com/players/bYIWwLJw-7EaCFiXK.html" width="100%" height="100%" frameborder="0" scrolling="auto" title="OpenCaps1" style="position:absolute;" allowfullscreen></iframe></div>

 
https://osc.prod.drupal.uiowa.edu/live/opencaps2
<div style="position:relative;overflow:hidden;padding-bottom:56.25%"><iframe src="https://cdn.jwplayer.com/players/yORDAKpf-7EaCFiXK.html" width="100%" height="100%" frameborder="0" scrolling="auto" title="OpenCaps2" style="position:absolute;" allowfullscreen></iframe></div>

**Comment by joewhitsitt** [comment]
As noted in standup, the trick seems to be to include a non-breaking space or it will think the body content is empty. For the previous pages I helped do, it was switch to full_html, view source, add `<p>&nbsp;</p>` followed by the embed code.

**Comment by joewhitsitt** [comment]
@mkyoder i wasn't able to find:

https://osc.prod.drupal.uiowa.edu/live/cph
Add embed code from current OSC site

**Comment by joewhitsitt** [comment]
I think this is done except for CPH https://github.com/uiowa/uiowa/issues/6676#issuecomment-1646185881

**Comment by mkyoder** [comment]
@joewhitsitt Thank you!! I sent an email to Nick to get us the CPH one just now. I'll comment back here once I hear back from him.

**Comment by mkyoder** [comment]
@joewhitsitt Here is the code for CPH

<div style="position:relative;overflow:hidden;padding-bottom:56.25%"><iframe src="https://cdn.jwplayer.com/players/LMYaGJoc-7EaCFiXK.html" width="100%" height="100%" frameborder="0" scrolling="auto" title="College of Public Health (CPH)" style="position:absolute;" allowfullscreen></iframe></div>

**Comment by joewhitsitt** [comment]
This is done. https://osc.prod.drupal.uiowa.edu/live/cph
