### ISSUE TITLE
Rabbit hole alert category term pages

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6677]
# Story

As a web team, we would like to rabbit hole the alert feature category term pages so that folks aren't going to those pages and seeing published alerts where the alert end date is passed.

# Additional Info

If there is a use case for going to these term pages we can re-evaluate in the future.

# Proposed Solution

**Comment by GaryRidgway** [comment]
Rabbit hole alert category term pages to the `/alerts`

**Comment by joewhitsitt** [comment]
I think we should use the access denied option since an /alerts view page doesn't exist yet
