### ISSUE TITLE
CLAS template sites

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6678]
# Story

As a CLAS MarCom team, we would like three already provisioned departmental sites to be updated to use the CLAS template site so that we can have a quicker and more efficient build process.

# Additional Info

There is an email related to this in its-web

Already provisioned department sites:

- https://theatre.prod.drupal.uiowa.edu/
- https://music.prod.drupal.uiowa.edu/
- https://dance.prod.drupal.uiowa.edu/

Template site

- https://template.clas.uiowa.edu/

# Proposed solution

- ~We should validate that they are ok with blowing up any content already there.~ They approved

**Comment by joewhitsitt** [comment]
https://wiki.uiowa.edu/display/drupaldev/Copy+a+website

**Comment by briand44** [comment]
Grooming conversation... We should validate that they are ok with blowing up any content already there.

**Comment by briand44** [comment]
Reached out to Maggie, etc. through the thread in its-web to get confirmation we can blow away any existing content.

**Comment by briand44** [comment]
Maggie gave approval to move forward!

**Comment by bspeare** [comment]
I can work on this today.

**Comment by bspeare** [comment]
This is done.
