### ISSUE TITLE
P2LB - Add ID's to collection items

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#6681]
In V2, there is the option to add unique HTML ID's to collection items (such as accordion items). To have a place to map this data to, we need to add this functionality here.

# Proposed solution
- Add the unique ID field to the appropriate paragraph item forms
- Figure out how to store the unique ID value (with LB blocks, we could store it in third party settings, not sure if something like that exists for Paragraphs)
- Preprocess the paragraphs to add the ID to the HTML attributes
- Possibly update templates if the above item doesn't cause it to just be added automatically

**Comment by joewhitsitt** [comment]
So collection already gets auto ids based on the title. So if this value (third-party or paragraph field) is filled out, it would take precedence over the auto id correct?

**Comment by pyrello** [comment]
> So collection already gets auto ids based on the title. So if this value (third-party or paragraph field) is filled out, it would take precedence over the auto id correct?

Makes sense to me.

**Comment by joewhitsitt** [comment]
>with LB blocks, we could store it in third party settings, not sure if something like that exists for Paragraphs

I've investigated this a bit. Unless my google results are dated, I think the third-party-settings functionality is not meant for content entities and that we should use a field instead.

Should still be able to use `_layout_builder_custom_unique_id` for an ajax callback

**Comment by joewhitsitt** [comment]
Oops. https://github.com/uiowa/uiowa/pull/6732 (merged) resolves this.
