### ISSUE TITLE
Display Facilities alerts on buildings

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6689]
# Story

As a site owner for Facilities, I would like to see all active alerts that relate to a building displayed on that building page so that users viewing a building page can be aware of alerts for that building.

# Additional Info

Alert should link to full alert node

Initial mockup https://sandbox.prod.drupal.uiowa.edu/chemistry-building-mockup

Also dependent upon work done in https://github.com/uiowa/uids/issues/770

# Proposed Solution

**Comment by briand44** [comment]
blocked by https://github.com/uiowa/uids/issues/770

**Comment by cory-skeers** [comment]
Grooming convo: After uiowa/uids#770 we need to integrate that work into `uids_base` and update styles for existing implementations of alerts. And along with that, we can use the `uids_base` implementation to create the facilities alerts.

**Comment by briand44** [comment]
Grooming convo... Can move forward with outputting alert info on a building and in a future slice update component to add to uids_base and style facilities alerts on buildings.
