### ISSUE TITLE
Update 9.5 with the refactored off-canvas tray styles from 10

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#6692]
# Proposed solution

Try out the patch from https://www.drupal.org/project/drupal/issues/3291797

**Comment by pyrello** [comment]
Tried to `JDI` this and it didn't "just work." Looks like we have some conflicting styles and the patch causes our custom drag handle to disappear.

**Comment by pyrello** [comment]
Looks like whether we do this or when we upgrade to 10.x, we'll need to do some refactoring on our `chosen` styles.

**Comment by joewhitsitt** [comment]
Can we close this? I feel like we have managed to workaround this and have documented specific issues elsewhere.

**Comment by bspeare** [comment]
You have my vote to close.
