### ISSUE TITLE
Add "center" option to SiteNow site request form

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#6693]
# Proposed Solution

Can I just add this here to the form or is there more to this?

<img width="515" alt="Screenshot 2023-07-25 at 9 57 44 AM" src="https://github.com/uiowa/uiowa/assets/1036433/2828e123-f79c-4668-b589-336d94046242">

**Comment by joewhitsitt** [comment]
I believe so

**Comment by bspeare** [comment]
This is done.  Also updated the help text pop-up.
