### ISSUE TITLE
Switch ITS alert emails from ListServ to Office 365 mail-enabled group

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6701]
# Story

As an ITS website owner, I would like to update our alert emails from ListServ to an Office 365 mail-enabled group as our email mechanism.

# Additional Info

> Thanks to your help over the last couple of months, our IT Service Alert email testing has been successful as we work towards making the switch from Listserv to an Office 365 mail-enabled group as our email mechanism. Tracy presented our plan to Ops Team last week, and we got approval to make these changes official on Tuesday, August 8. Does that date work for your team to make this update? Morning would be preferred so we have the rest of the day to field comments/complaints/issues, though I’m not picky on a specific time.

Link to config page
https://its.uiowa.edu/admin/config/system/its

Joe previously mentioned we should update the help text when we make these changes as well so it represents what the production value should be.

# Proposed Solution

- Update the email addresses and help text on the ITS website used for IT Service Alerts:
    - In the “Email for alert content creation” switch the email address to: HelpDesk-Notify@uiowa.edu and 51923d18.iowa.onmicrosoft.com@amer.teams.ms
    - IT Service Alerts emails to subscribers should go to IT-Service-Alerts@uiowa.edu (This change should be updating the field "Email address for Alert to" field)
    - Update docroot/sites/its.uiowa.edu/modules/custom/its_core/its_core.module as it relates to the help text. Around L266 and L285
- Can we add a link to the bottom of the alerts emails (daily digest, outage, degradation of service) that says: “[Why am I receiving this email](https://its.uiowa.edu/support/article/127441)?”
  - Update template "related links" here: docroot/sites/its.uiowa.edu/modules/custom/its_core/theme/alerts-digest.tpl.php
- The blue menu on the IT Service Alerts landing page has a link, “Subscribe to all alerts via email”. Can we switch that link to mailto:(mailto:[its-helpdesk@uiowa.edu](mailto:its-helpdesk@uiowa.edu))
  - Update docroot/sites/its.uiowa.edu/modules/custom/its_core/its_core.moduleL143

**Comment by briand44** [comment]
If we don't think we can accommodate this on Tuesday, August 8th, we should reach out to Adrienne and have that conversation.

**Comment by briand44** [comment]
Added blocked label since they don't want these changes until Tuesday, August 8th.

**Comment by briand44** [comment]
Updated the IS based on the latest conversation with Adrienne. Email thread in its-web for visibility.

**Comment by bspeare** [comment]
Updated with email change request to [its-helpdesk@uiowa.edu](mailto:its-helpdesk@uiowa.edu) that Adrienne sent on 7/27.

**Comment by joewhitsitt** [comment]
updated the proposed solution with direct references to code

**Comment by joewhitsitt** [comment]
created `update_its_alert_notifications` branch with the following diff:

```
diff --git a/docroot/sites/its.uiowa.edu/modules/custom/its_core/its_core.module b/docroot/sites/its.uiowa.edu/modules/custom/its_core/its_core.module
index 711220da5..49b9d53ff 100644
--- a/docroot/sites/its.uiowa.edu/modules/custom/its_core/its_core.module
+++ b/docroot/sites/its.uiowa.edu/modules/custom/its_core/its_core.module
@@ -140,7 +140,7 @@ function theme_rss_info($variables) {
     $markup['container']['rss_subscribe_email'] = array(
       '#type' => 'markup',
       '#prefix' => '<p class="rss_subscribe_email">',
-      '#markup' => '<i class="fa fa-envelope"></i> <a href="https://list.uiowa.edu/scripts/wa.exe?SUBED1=HELPDESK-ALERTS">Subscribe to all alerts via email.</a>',
+      '#markup' => '<i class="fa fa-envelope"></i> <a href="mailto:its-helpdesk@uiowa.edu">Subscribe to all alerts via email.</a>',
       '#suffix' => '</p>'
     );
   }
@@ -258,7 +258,7 @@ function its_core_form($form, &$form_state) {
   $form['its_core_alert_email_list_fieldset']['its_core_alert_to'] = array(
     '#type' => 'textfield',
     '#title' => t('Email address for Alert to'),
-    '#description' => t('Production value should be: <strong>') . check_plain('helpdesk-alerts@list.uiowa.edu') . t('</strong>'),
+    '#description' => t('Production value should be: <strong>') . check_plain('IT-Service-Alerts@uiowa.edu') . t('</strong>'),
     '#default_value' => variable_get('its_core_alert_to'),
     '#required' => TRUE,
     '#access' => user_access('administer its website debug'),
@@ -285,7 +285,7 @@ function its_core_form($form, &$form_state) {
   $form['its_core_alert_content_creation_fieldset']['its_core_alert_creation'] = array(
     '#type' => 'textfield',
     '#title' => t('Email for alert content creation.'),
-    '#description' => t('Production value should be: <strong>') . check_plain('helpdesk-notify@list.uiowa.edu') . t('</strong>'),
+    '#description' => t('Production value should be: <strong>') . check_plain('HelpDesk-Notify@uiowa.edu, 51923d18.iowa.onmicrosoft.com@amer.teams.ms') . t('</strong>'),
     '#default_value' => variable_get('its_core_alert_creation'),
     '#required' => TRUE,
     '#access' => user_access('administer its website debug'),
diff --git a/docroot/sites/its.uiowa.edu/modules/custom/its_core/theme/alerts-digest.tpl.php b/docroot/sites/its.uiowa.edu/modules/custom/its_core/theme/alerts-digest.tpl.php
index a6c757d53..c8972a77d 100644
--- a/docroot/sites/its.uiowa.edu/modules/custom/its_core/theme/alerts-digest.tpl.php
+++ b/docroot/sites/its.uiowa.edu/modules/custom/its_core/theme/alerts-digest.tpl.php
@@ -110,6 +110,7 @@
     <div class="links">
       <h2>Related Links:</h2>
       <ul>
+        <li><?php print l(t('Why am I receiving this email?'), $GLOBALS['base_url'] . '/support/article/127441'); ?></li>
         <li><?php print l(t('IT Service Alerts page'), $GLOBALS['base_url'] . '/alerts'); ?></li>
         <li><?php print l(t('Calendar view of alerts'), $GLOBALS['base_url'] . '/alerts/calendar'); ?></li>
       </ul>
```

**Comment by joewhitsitt** [comment]
Going to check the branch out on 703 DEV

**Comment by joewhitsitt** [comment]
Screenshots from DEV. Config values have not yet been updated, but the help text/code has.

<img width="744" alt="Screenshot 2023-08-04 at 11 38 41 AM" src="https://github.com/uiowa/uiowa/assets/4663676/d464d8ec-795b-43e3-90f3-84209ae21143">
<img width="639" alt="Screenshot 2023-08-04 at 11 39 44 AM" src="https://github.com/uiowa/uiowa/assets/4663676/e10ad72a-532a-4995-884a-c8302a6cfd30">
<img width="423" alt="Screenshot 2023-08-04 at 11 47 46 AM" src="https://github.com/uiowa/uiowa/assets/4663676/c40a563b-56b1-4ab4-9e4a-0e5b20a265ea">

**Comment by joewhitsitt** [comment]
Remaining to do on 8/8:

- [x] merge `update_its_alert_notifications` into master on uiowa703 and deploy to PROD.
- [x] update the settings here: https://its.uiowa.edu/admin/config/system/its to match the production values mentioned in the help text.
- [x] notify Adrienne once done.

**Comment by joewhitsitt** [comment]
The remaining steps are done.

**Comment by joewhitsitt** [comment]
Update: there was a mix up on which emails should be assigned to what after the digest email did not fire at 7 AM. PROD config and the form help text have been updated and the digest email was manually triggered at 10:25 AM. Successful.
