### ISSUE TITLE
P2LB - Create action to revert to V2 version of page

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#6707]
# Motivation

When we migrate a page from its v2 to v3 version, we capture the revision ID of the node before its migration so we can fall back to it. The migration is accomplished via an action that can be applied to one or many pages via the SiteNow Converter tool. This task is to create a complimentary action that reverts the migration.

## Question

If the customer migrates a piece of content and then makes changes to it, there will be multiple revision IDs after the one that we are reverting back to. Should this process simply be a nice wrapper for the option to revert to a previous revision in the revision system? Or do we need to remove any revisions after the revert point revision ID so that the user can start fresh?

# Proposed solution
- Create an action ([reference](https://github.com/uiowa/uiowa/tree/main/docroot/modules/custom/sitenow_p2lb/src/Plugin/Action)) which:
- Gets the fallback revision ID from the node (the last revision before it was converted)
- Make the fallback revision the current revision

**Comment by GaryRidgway** [comment]
I think we should be removing any revisions after the conversion, as I think leaving them around would create confusion. This is a heavier lift though, so if we want to just allow people the option to go back to the version before, they could just revert to the old revision, and then this is technically already done.

**Comment by mjoneill** [comment]
> If the customer migrates a piece of content [to LB] and then makes changes to it, there will be multiple revision IDs after the one that we are reverting back to. Should this process simply be a nice wrapper for the option to revert to a previous revision in the revision system? Or do we need to remove any revisions after the revert point revision ID so that the user can start fresh?

To me, "removing revisions after the revert point" seems to change the paradigm of the existing functionality in a way that I wouldn't really understand as an editor (without explanation).  I'd expect continuity in behavior.  If I'm following correctly, that would mean I'd be against "removing revisions after the revert point" and for "a nice wrapper for the option to revert to a previous revision" (even if that means reverting from LB to SNv2 paragraphs).  <--- I'd want to know that this is moving back to paragraphs though.

What are the constraints around this?  Hugely expensive? Can't maintain reversions back into SNv2/paragraphs after some period of time?

**Comment by pyrello** [comment]
This is how it currently happens when a revision is reverted: https://git.drupalcode.org/project/drupal/-/blob/11.x/core/modules/node/src/Form/NodeRevisionRevertForm.php#L124-147

**Comment by GaryRidgway** [comment]
Should this action only go on the `converted` page? That feels correct to me as it can't really be used easily on the main content page, right? Any ideas on that?

**Comment by cory-skeers** [comment]
> Should this action only go on the `converted` page? That feels correct to me as it can't really be used easily on the main content page, right? Any ideas on that?

Ideally, I think including it only on the 'converted' page makes sense, as that's the primary place where there's really context for it.

But, if it was available elsewhere, I don't think that's a huge problem as long as doing the action on a non-converted page didn't lead to any issues (similar to doing something like "archive current revision" doesn't error if the content is already archived).

**Comment by pyrello** [comment]
> > Should this action only go on the `converted` page? That feels correct to me as it can't really be used easily on the main content page, right? Any ideas on that?
> 
> Ideally, I think including it only on the 'converted' page makes sense, as that's the primary place where there's really context for it.
> 
> But, if it was available elsewhere, I don't think that's a huge problem as long as doing the action on a non-converted page didn't lead to any issues (similar to doing something like "archive current revision" doesn't error if the content is already archived).

Yes, this should only go on the "Converted" page.
