### ISSUE TITLE
Update Mapbox

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#671]
## Problem

Mapbox is changing things up Nov 20. To avoid crazy prices, we need to update mapbox across all of our instances.

Here is a github search of D7 instances:
https://github.com/search?p=1&q=org%3AITS-UofIowa+api.mapbox.com%2Fmapbox-gl-js&type=Code

- [x] uiowa.edu/stories
- [x] law.uiowa.edu
- [x] facilities.uiowa.edu
- [x] dining.uiowa.edu
- [x] sitenow_maps
- [x] maps.uiowa.edu
- [x] sitenow_paragraphs
- [x] commencement.uiowa.edu

Can anyone think of other instances?

## Proposed solution
Switch on each instance to the latest stable 1.4.1 release. Test map instances locally to make sure things are still clickable and the mapbox features each map is utilizing still work.

- [x] Once all instances have been updated, we need to "upgrade our pricing" agreement.

```
<script src='https://api.mapbox.com/mapbox-gl-js/v1.4.1/mapbox-gl.js'></script>
<link href='https://api.mapbox.com/mapbox-gl-js/v1.4.1/mapbox-gl.css' rel='stylesheet' />
```

**Comment by joewhitsitt** [comment]
So far, I am not seeing any noticeable issues with these.

**Comment by ethanstjohn** [comment]
https://github.com/ITS-UofIowa/dining.uiowa.edu/pull/99

**Comment by ethanstjohn** [comment]
https://github.com/ITS-UofIowa/uiowa.edu.stories/pull/3

**Comment by ethanstjohn** [comment]
Facilities needs reviewed before merging code. Facilities for sure has some sort of issue displaying the map pins.

**Comment by joewhitsitt** [comment]
facilities was merged and deployed after some fixin'

**Comment by joewhitsitt** [comment]
Filed an issue with mapbox to track down the last remaining stuff. The last checkbox is to opt-in before automatically being switched later.

**Comment by joewhitsitt** [comment]
Calling this good for now. opted in.

**Comment by joewhitsitt** [comment]
<img width="894" alt="Screen Shot 2019-11-08 at 12 09 19 PM" src="https://user-images.githubusercontent.com/4663676/68500188-a0e82980-0220-11ea-8894-f478137da47f.png">
