### ISSUE TITLE
P2LB - Handle all V2 card cases

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#6714]
# Motivation

As a SiteNow v2 site owner, all the potential ways that I could have used the V2 card component will be covered by the migration process so that I don't have to worry about losing data and/or I know what data I might have to lose.

```[tasklist]
### Cases
- [ ] If there's a link + link text, and a title - link the title only and delete the link text?
- [ ] If there's a link + link text, and no title - display circle button?
- [ ] V2 card body format is less restrictive than V3 card excerpt format https://github.com/uiowa/uiowa/issues/6706#issuecomment-1656234510
```

**Comment by pyrello** [comment]
><img width="1044" alt="Screenshot 2023-07-28 at 5 01 20 PM" src="https://github.com/uiowa/uiowa/assets/1036433/d3e65840-c34c-4488-b8cd-3aa62d640f30">
>
> Cards previously did not have buttons. Are we ok with all P2LB cards having buttons?
>
> It seems like we should ignore migrating the link text for cards?  Since it was required but never displayed I don't think we should automatically add a button to each card.  
>
> Card conditions:
>
> - If there's a link + link text, and a title - link the title only and delete the link text?
> - If there's a  link + link text, and no title - display circle button?

_Originally posted by @bspeare in https://github.com/uiowa/uiowa/issues/6706#issuecomment-1656375933_

**Comment by pyrello** [comment]
There are two central problems, as far as I can tell, with converting V2 cards into V3 cards: 

**V2 card titles are not required and V3 card titles are required.**
This means that we are not able to convert any V2 cards without titles unless we convert them to something other than a V3 card or we make the title not required for V3 cards.

**V2 card body field format is Filtered HTML - which allows `<drupal-media>`, `<table>`, and `<hr>` tags to name a few - and the V3 card excerpt field format is Minimal +, a much more restrictive filter.**
Similar to the previous issue, we could change the V3 card excerpt field format to Filtered HTML or we could convert instances of cards that use markup that is not allowed in V3 cards to another block type, probably a text area. There is an example of such a card on this page: https://hawkeyemarchingband.uiowa.edu/2021-virtual-awards-banquet

Here's my attempt at a logical path for deciding how to handle each card:
- If a V2 card has no title:
  - If the V2 card only has the image field and optionally the link field filled in (but not title, subtitle, or text fields), then convert it to an Image block.
  - Otherwise, convert it to a text area block.
- Otherwise:
  - If the V2 card body has contents that would result in data loss when converted to the Minimal + format, convert it to a text block.
  - Otherwise, convert it to a card since there should be no issues.

The main upside to this approach is that we find a home for all the existing content and it roughly corresponds to what the user created originally. The main downside to this approach is that cards converted to non-cards will lose their structured data and not inherit card block behaviors (like the indicator button). Also, the LB styles available for cards converted to text areas will be different so likely there is going to be some visual regressions that occur despite our best efforts to avoid them.

**Comment by pyrello** [comment]
On the HMB site, I found the following pages that contain cards with body values that would be changed by converting them:
https://hawkeyemarchingband.uiowa.edu/node/1
https://hawkeyemarchingband.uiowa.edu/node/111
https://hawkeyemarchingband.uiowa.edu/node/2
https://hawkeyemarchingband.uiowa.edu/node/401
https://hawkeyemarchingband.uiowa.edu/node/471
https://hawkeyemarchingband.uiowa.edu/node/586

I found these using adding a code snippet like the following to the beginning of `Drupal\sitenow_p2lb\Form\P2LbSettingsForm::buildForm`:
```php
    // Get entity IDs for all card paragraphs.
    $query = \Drupal::entityQuery('paragraph')
      ->condition('type', 'card')
      ->accessCheck(TRUE);

    $pids = $query->execute();

    $form['nid_wrapper'] = [
      '#type' => 'container',
    ];

    // Load each paragraph. 
    foreach ($pids as $pid) {
      /** @var \Drupal\paragraphs\ParagraphInterface $paragraph */
      $paragraph = $this->entityTypeManager->getStorage('paragraph')->load($pid);
      // Get the body field if it exists.
      $body = $paragraph->field_card_body?->value;
      if (is_null($body)) {
        continue;
      }

      // Generate the rendered output for the body field against the current
      // format (filtered_html) and the V3 card excerpt field format
      // (minimal_plus) and check to see if they are the same.
      $current_markup = check_markup($body, 'filtered_html');
      $future_markup = check_markup($body, 'minimal_plus');
      if ($current_markup === $future_markup) {
        continue;
      }
      
      // They are not the same, so find the node this card is attached to and
      // print out a link to it.
      $parent = $paragraph->getParentEntity();
      $parent = $parent->getParentEntity();
      if (!is_null($parent)) {
        $form['nid_wrapper'][$parent->id()] = [
          '#type' => 'markup',
          '#markup' => '<div><a href="/node/' . $parent->id() . '">' . $parent->id() . '</a></div>',
        ];
      }
    }
```

**Comment by pyrello** [comment]
> @pyrello can we migrate the video into the media field or are these cards with images and videos?

_Originally posted by @bspeare in https://github.com/uiowa/uiowa/issues/6706#issuecomment-1656811039_

@bspeare The bigger issue is that a video or image can show up in the V2 card body field because the field format allows that. So, if we were going to have a case that we handle where we move an embedded video into the V3 card media image (media) field, we have to make sure that there is only one video/image in the V2 body field. When you also factor in the fact that some cards will already have an image in the dedicated image field, then the logic to try to handle the cases where everything is right to move a media embed to the media field is pretty complex and I'm not sure its worth adding the complexity if we can find a more straightforward way to handle most cases.

**Comment by bspeare** [comment]
If we find multiple media items, convert it to a text area block? The last card on https://hawkeyemarchingband.uiowa.edu/2021-virtual-awards-banquet seems like a good candidate for a text area.

**Comment by pyrello** [comment]
> If we find multiple media items, convert it to a text area block? The last card on https://hawkeyemarchingband.uiowa.edu/2021-virtual-awards-banquet seems like a good candidate for a text area.

I think this is the relevant part from above:
> - If the V2 card body has contents that would result in data loss when converted to the Minimal + format, convert it to a text block.
> - Otherwise, convert it to a card since there should be no issues.

**Comment by pyrello** [comment]
@bspeare and I discussed earlier in slack what to do when a card is being converted to a text area (based on having content that's incompatible with the minimal plus format or lacking a title). I think this is roughly what we settled on:
```html
<h2>Card Title</h2>
Card subtitle
<p>Card Body</p>
<a class="bttn bttn--primary bttn--transparent bttn--light-font" href="/link-url">Card link text</a>
```

I just realized that we could end up in a situation where we are converting a card to a text area and it has an image in its image field. One way to handle that would be to convert it to a media embed code and just append it to the string of text that is going to be saved in the new text area. Another option would be to convert it to a separate image block. I was kind of leaning towards the latter option because it seemed less difficult to create a new block than to convert a media field reference to a media embed. But I also don't love the idea of splitting it out into a separate block.

**Comment by pyrello** [comment]
I went ahead and implemented the conversion from media reference to media embed. The screenshot below is showing the last two cards on https://hawkeyemarchingband.uiowa.edu/2021-virtual-awards-banquet, the last of which has to be converted to a text area.

![Screenshot 2023-07-31 at 6 21 02 PM](https://github.com/uiowa/uiowa/assets/709009/ca51cf3c-04dd-4144-813c-db1d1b13bce2)

**Comment by cory-skeers** [comment]
> I just realized that we could end up in a situation where we are converting a card to a text area and it has an image in its image field. One way to handle that would be to convert it to a media embed code and just append it to the string of text that is going to be saved in the new text area. Another option would be to convert it to a separate image block. I was kind of leaning towards the latter option because it seemed less difficult to create a new block than to convert a media field reference to a media embed. But I also don't love the idea of splitting it out into a separate block.

I'd also vote for converting it to a media embed (especially if you've already gone and implemented it). I like the idea of keeping it all in a block that the editor can either a) adjust to make their makeshift "card" or b) make a new card to take its place, and easily delete the whole thing after.

**Comment by pyrello** [comment]
In my last screenshot, the title isn't displaying for the text area. Here is what it looks like with the title displaying:
![Screenshot 2023-08-01 at 8 24 13 AM](https://github.com/uiowa/uiowa/assets/709009/f9d3ae1a-77cd-4661-82e9-b9ede8819dba)

Question: Does it matter that the title is displayed out of order (compared to a card)? That is, should I instead set the title as part of the contents of the text area and not set the actual headline field? Or is it already broken looking enough that we should just not worry about it and let it be something the user is going to fix most of the time.

**Comment by pyrello** [comment]
Another thing that is coming up: In V2, the link is never displayed but instead used to wrap the card. In the case where we are turning the card into a text area, we have no mechanism for doing that (short of using the text area to fully mimic the markup of a card). Furthermore, we don't have a clear target for wrapping the link around something. If there is a title, we could potentially attach it to that, but if we don't have a title, I'm not sure if it makes sense to wrap the remaining content. We also can't print out the link because that would be unexpected to suddenly have a link showing where previously there was none.

**Comment by cory-skeers** [comment]
> Another thing that is coming up: In V2, the link is never displayed but instead used to wrap the card. In the case where we are turning the card into a text area, we have no mechanism for doing that (short of using the text area to fully mimic the markup of a card). Furthermore, we don't have a clear target for wrapping the link around something. If there is a title, we could potentially attach it to that, but if we don't have a title, I'm not sure if it makes sense to wrap the remaining content. We also can't print out the link because that would be unexpected to suddenly have a link showing where previously there was none.

Between this and the mention in daily scrum, if it's possible to render it as a card and place that into the text area, I think that sounds like a good compromise. It fits into the pattern of "this isn't quite right, but content is there, and once you recreate the card/text area/whatever replacement in v3, you can delete the whole thing," while giving them something as a reference on the page of what the content was, and maybe even in a publishable state while refinements can be made.

If that doesn't work out or starts down a rabbit hole of complication, I think the next priority is keeping everything in one place, but have a concession like displaying the link at the bottom, even if previously there hadn't been one. Especially if we go further with the "there's a card that couldn't be converted because..." type route, and set that expectation that it wasn't all a perfect matchup.
