### ISSUE TITLE
Provision planning-and-development.fo.uiowa.edu

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#672]
via: https://sitenow.uiowa.edu/admin/structure/webform/manage/request_a_site/submission/136
Initial user: mconnll

Site owners want content transferred from https://uiowa.edu/planning-and-development by students. ~Need MFK (@briand44) before migration work begins~.

*.fo is covered under uiowa SSL.

Might be a good test/chance to document for `migrate` branch before merging in.

Follow-up task to deprovision sub-directory site.

**Comment by joewhitsitt** [comment]
This #673 has stalled due to build/check errors.

**Comment by briand44** [comment]
I've received an MFK from Maggie Vogel.

**Comment by joewhitsitt** [comment]
This now needs a CNAME request and student migration.

**Comment by richardbporter** [comment]
#673 is in prod now.

**Comment by cory-skeers** [comment]
Site content migrated in and setup -- https://planning-and-development.fo.uiowa.edu/

Some cleanup needed yet.
