### ISSUE TITLE
Update facilities alerts to have a structured title

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#6722]
# Story

As a user of the SiteNow Alerts module, I can create an alert that has a structured alert title so that each alert title has a consistent alert pattern. 

# Proposed solution
- Remove the title field from the alert content type and generate the page title based on multiple fields. 

Original discussion at https://github.com/uiowa/uiowa/issues/6659#issuecomment-1645783308. 

Based on feedback from Lauren at Facilities:

- Facilities has mentioned that "Building + Project title/work description” would be ideal.
  - Check with ITS if their alerts could also benefit from "Building/Product + Project title/work description”
- Add a separate field for project number or code since that is not meaningful to most of our audience
  - Add this project number field to display separately from the title 
    - (like the other fields “Closure Category,” “Location,” etc.) to display just below the title, or would display elsewhere, like in the body of the alert, I believe that would be the best solution for all parties.

**Comment by briand44** [comment]
Grooming convo.... For Facilities lets construct title from Building + Project title and see how that works. If no building just use project title. Output project number separately. Initial investigation and exploring should probably happen before just jumping into the work.

**Comment by bspeare** [comment]
Feedback from our meeting today with Facilities:

In https://github.com/uiowa/uiowa/issues/6722:
- [ ] Change "Short work description" to "Project title"
- [ ] Delete "Details and location of closure" and use the Body field
- [ ] Adjust Body field label to "Reason and details for closure" 
- [ ] Change Body field to Minimal Plus text format
- [ ] Change Building field to a prepopulated multiple select list of all buildings with an "Other" option
  - [ ] If "Other" option is selected, then show the "Other location description" field which, if filled out, overrides the title
- [ ] Change "Category" field to a prepopulated multiple select list

**Comment by briand44** [comment]
Discussed with Ben and we decided to close this issue and open a new issue for the updates based on Facilities feedback. #6805
