### ISSUE TITLE
More Admissions Slideshow fixes

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#6738]
Reporting that their laptop can't handle the slideshow. 

Possible fixes:
- Investigate image size reduction
- Investigate removing shutter effect
- Investigate switching to background patterns instead of images
- Investigate what kind of laptop they have

# Proposed solution

```[tasklist]
### Tasks
```

**Comment by cory-skeers** [comment]
Grooming convo: Need more context on what's not working with it. May be possible for someone from PCO to walk over and check it out in person.

**Comment by bspeare** [comment]
Scott emailed this today:

This display is running off an intel stick PC, so it’s probably not able to handle the transitions. I doubt we’d be able to swap that PC out since it’s tucked behind the display/tv. What options do we have for a lighter animation? I may try to go over there and see if it’s consistently choking on at the same time. It does run when it initially boots, but I’m curious if it dies 5 min after running or if it’s some other issue. We might just need to pull back on the animations a bit to keep this thing running. I wonder if a programmed refresh every X minutes on that page would help clear things out? I honestly don’t know what that stick is running as a browser.

**Comment by bspeare** [comment]
Next step might be to move to a simple fade animation and get rid of the shutters?

**Comment by bspeare** [comment]
I added a task list to this after additional email communications with Scott.

**Comment by briand44** [comment]
Grooming convo. Alan to see this in person and if a performance issue go with proposed solution
