### ISSUE TITLE
Iowa Now 404s and redirects

### ISSUE THREAD

**Issue by e-marie-w** [uiowa/uiowa#6745]
Identify list of news articles without redirects in place
Non-article content needs redirects as well. 

https://iowaweb.slack.com/?redir=%2Farchives%2FC0164FNN1PV%2Fp1691070415427759

Possible solutions:
Keywords, match redirect

**Comment by joewhitsitt** [comment]
@mjoneill is a match redirect of keywords/* to the homepage (301) okay with you or should we be trying to do 1:1 fixes as they come up?

**Comment by mjoneill** [comment]
> @mjoneill is a match redirect of keywords/* to the homepage (301) okay with you or should we be trying to do 1:1 fixes as they come up?

@joewhitsitt I think I would be fine with this provided that we don't already have redirects for /keywords/something specific and these are just a subset of those that we don't understand/missed/etc...

Also, I'm assuming you are just talking about /keywords/* and not /news-about/*, etc...

**Comment by joewhitsitt** [comment]
Got to https://now.uiowa.edu/news/2023/07/5-steps-easy-email-etiquette and Michael said he would push it further tonight.

No keywords specific redirects yet: https://now.uiowa.edu/admin/config/search/redirect?redirect_source__path=keywords&redirect_redirect__uri=&status_code=All&language=All

I figure the /news-about/ ones we need to find a proper home to redirect to.

**Comment by joewhitsitt** [comment]
Added https://now.uiowa.edu/admin/config/search/redirect/edit/53371 (match redirect for keywords/* to send to the homepage (301)).

@cory-skeers confirmed that keywords were removed from the migration https://iowaweb.slack.com/archives/C0164FNN1PV/p1691159533879089?thread_ts=1691070415.427759&cid=C0164FNN1PV

**Comment by joewhitsitt** [comment]
Created redirects for:

news-about/athletics to tags/athletics
news-about/international to tags/international
news-about/research to tags/research
news-about/campus to tags/campus
news-about/health-care to tags/health-care

**Comment by joewhitsitt** [comment]
`/404.html?page=/2023/05/denise-jamieson-named-vice-president-medical-affairs-carver-college-medicine-dean&from=https://now.uiowa.edu/news-about/health-care`

This seems like pre-launch since it was coming from a now non-existent route `news-about/health-care`

**Comment by joewhitsitt** [comment]
I temporarily copied Michael's explore report in GA4 to update the date range so we have a better idea of what is left.

Seeing results for /news/news-media 

Not sure what the replacement for that should be: https://now.prod.drupal.uiowa.edu/news/news-media

I want to say we have covered _everything_ else that has popped up. We can update the range again next week to see what is left/new after our solutions have been in place for a bit.

**Comment by joewhitsitt** [comment]
I've been working on a new set of 404s that Michael provided. See conversation here: https://iowaweb.slack.com/archives/C0164FNN1PV/p1691501065231679

Seems like a lot of previous redirects that the old site had in place for article date changes, title changes, special character encoding.

Not sure how we want to handle files that have been directly linked to.

**Comment by joewhitsitt** [comment]
>Seems like a lot of previous redirects that the old site had in place for article date changes, title changes, special character encoding.

Based on this, there will be more paths popping up unless we import their old site's redirects. If we don't import them, when do we stop the whackamole?

**Comment by joewhitsitt** [comment]
This one keeps getting a lot of hits:

https://now.prod.drupal.uiowa.edu/2023/06/ui-approves-p3-funding-support-4-new-projects-fy24

but refers to an unpublished article and seems to have a published replacement.

<img width="1191" alt="Screenshot 2023-08-10 at 8 59 29 AM" src="https://github.com/uiowa/uiowa/assets/4663676/f427b97f-5b75-4927-9b66-35914caf6331">

published: https://now.uiowa.edu/news/2023/07/ui-approves-p3-funding-support-4-new-projects-fy24
unpublished: https://now.uiowa.edu/news/2023/06/ui-approves-p3-funding-support-4-new-projects-fy24

We should probably get the content owners to weigh in on this one.

**Comment by joewhitsitt** [comment]
The other one is https://now.prod.drupal.uiowa.edu/news/news-media which I don't think has a new site replacement.

Ideally we would point this traffic somewhere other than the homepage or 404

**Comment by mkyoder** [comment]
@joewhitsitt I am meeting with Tricia tomorrow to ask and will comment in here.

**Comment by mkyoder** [comment]
For the news-media one, this one seems like a similar candidate: https://now.uiowa.edu/tags/news-media? But I will ask Tricia.

**Comment by joewhitsitt** [comment]
d'oh! mix up on my part. yes, i will create a redirect for news/news-media to point to tags/news-media. Instead I was meaning to point out /media-relations which was a basic page. https://now.prod.drupal.uiowa.edu/media-relations

**Comment by mkyoder** [comment]
All good! :)

**Comment by mkyoder** [comment]
I will ask about that one :) I think it would point to the osc.uiowa.edu site, but I will ask.

**Comment by mkyoder** [comment]
I removed the unpublished version of the P3 article that was authored by Jack (screenshot above).

**Comment by mkyoder** [comment]
This link: https://now.prod.drupal.uiowa.edu/media-relations has now been redirected to https://osc.uiowa.edu/media-resources.
