### ISSUE TITLE
Request to fix event breadcrumbs from OnIowa!

### ISSUE THREAD

**Issue by e-marie-w** [uiowa/uiowa#6746]
We can do this by changing the event path alias pattern to `/events/[node:title]`

Scope to events feature?

**Comment by pyrello** [comment]
If we don't do this for ISWF for some reason, we should definitely do it for Admissions while they are still showing no events.

**Comment by mjoneill** [comment]
Looks like ISWF concluded festivities at the end of July. 

Might make it easy to change for them: https://iowasummerwritingfestival.uiowa.edu

**Comment by cory-skeers** [comment]
The way it works in updating the pathauto path, is that after the change new events will have the new pattern. For existing events, they won't get the change until the node gets saved. (At that point, a redirect is also created to point from the old alias to the new.)

So, the way it is currently set up in #6749:

- Admissions will get the new pattern going forward, and with no current events, it's a fairly silent change
- Oniowa will get the new pattern going forward, and all current events will get a save to
  - update their existing paths to the new `events/title` pattern, adjusting the breadcrumbs accordingly
  - create redirects from the existing `event/id/title` path to the new `events/title` pattern
- ISWF will get the new pattern going forward
  - All existing events (that have passed) will keep their current URL
  - If any previous events are saved, they will get the updated pattern (and a redirect put into place)

Looking back through issues/PRs I'm finding snippets of crafting the event url pattern like avoiding 404s or collisions with the content hub events (like surrounding https://github.com/uiowa/uiowa/issues/5879#issuecomment-1294109202), but not finding anything specific to ISWF needing that pattern. It seems to me like they were our first big user of the event feature, and so were the ones we were working with when creating the initial url pattern? If that's the case, I think we could move forward with the pattern change (especially given old events will keep their pattern and/or get redirects).

**Comment by pyrello** [comment]
I may have injected some confusion when I wrote up the original request for this. I don't think we should change the general format of the path alias pattern, just `event/` becomes `events/`. So the new pattern should be `events/[node:nid]/[node:title]`.

**Comment by cory-skeers** [comment]
> I may have injected some confusion when I wrote up the original request for this. I don't think we should change the general format of the path alias pattern, just `event/` becomes `events/`. So the new pattern should be `events/[node:nid]/[node:title]`.

Thanks for chiming in. So yeah, I think we are okay with making the pattern to the events feature, and update-hooking oniowa to get them the new pattern for existing (and yet upcoming) events. I don't think there's a need for the update hook for iswf, since the events are already passed, and the change won't break any existing URLs, even if one does get updated for any reason in the future.
