### ISSUE TITLE
Update Twitter icon to their new X

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#6753]

**Comment by bspeare** [comment]
I think that we can make this update and I have added some testing instructions: https://github.com/uiowa/uiowa/pull/6752.   Version 5 icons should continue to work and regarding https://www.drupal.org/project/fontawesome_iconpicker/issues/3299831 the newest 6 icons will not display in the preview, but the icon classes can be placed in the field and they will work.

**Comment by briand44** [comment]
Grooming conversation... Font awesome icon picker doesn't support 6 in preview. We should add some sort of documentation to help folks understand how to place the icon. There will be some additional changes as part of this upgrade. Possibly use an FAQ or Known issue to document this.

**Comment by joewhitsitt** [comment]
was trying to see if updating to the 3 alpha of https://www.drupal.org/project/fontawesome_iconpicker would help at all. seems like there are composer issues with it and the readme is in the wrong format: https://www.drupal.org/project/fontawesome_iconpicker/issues/3332843 but that it uses a non-jquery library https://github.com/AppoloDev/vanilla-icon-picker

**Comment by joewhitsitt** [comment]
I think I got something going!

<img width="824" alt="Screenshot 2023-08-23 at 5 36 27 PM" src="https://github.com/uiowa/uiowa/assets/4663676/b14fb077-8bc8-42b9-8086-d0ad73fa08be">

**Comment by bspeare** [comment]
That looks great @joewhitsitt !
