### ISSUE TITLE
Site Request "resend" email receipts

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#676]
## Problem

It would make me feel better getting a confirmation email at the same time we send anything out from the request form. It would be a low-tech way of knowing the acquia mail system is actually working without going through logs and anxiously waiting for a reply from hostmaster, etc.

## Proposed Solution

Adding our site mail token to the BCC of each of those emails. drush cex and pushing up. By doing a BCC, we don't touch TO or CC and then if they respond back, it should all be in the same email thread.

**Comment by richardbporter** [comment]
ITS Web is already CC'ed on all emails. Is that not working?
