### ISSUE TITLE
Deprovision hawkalert.uiowa.edu and set up redirect

### ISSUE THREAD

**Issue by e-marie-w** [uiowa/uiowa#6764]
Followup from safety.uiowa.edu launch #6720 

Deprovision hawkalert.uiowa.edu and redirect to https://safety.uiowa.edu/emergency-notifications instead.

**Comment by briand44** [comment]
Was this ever discussed? Is the plan to use a Vulture redirect?

**Comment by briand44** [comment]
I submitted a request to the EI SAS group to setup this redirect on Vulture.

**Comment by briand44** [comment]
TTL has been lowered

**Comment by briand44** [comment]
Redirect is in place and has been tested. Emailed Hayley to make sure she is ok with us proceeding.

**Comment by briand44** [comment]
DNS has been updated. Going to deprovision the site. We will still need to tell hostmaster to set TTL back to default.

**Comment by briand44** [comment]
Let Hostmaster know they can set TTL back to default at their convenience.
