### ISSUE TITLE
Classrooms room order

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6767]
>We did just notice something a little strange. When we go to the classroom search tool and filter to Lindquist Center, room N105 is out of order from the rest of the rooms. Instead of coming after N104, it’s last on the page.

It looks like Room N105 has the "Room Name" of "TILE-Flex (BYOD)". I'm guessing it's ordered by that and not necessarily Title?

^ Maybe not. Leonard Feldt Lecture Room is still in the correct order by room title.

I'm also seeing inconsistencies in the order prior to filtering vs post filter applied (AJB W240 on initial load vs filtering by building).

**Comment by briand44** [comment]
screenshot of LC N105 when filtering by building (shows last)

![Image](https://github.com/uiowa/uiowa/assets/1017022/b2c26f90-82b8-4613-9533-9b6e75fa5eb5)


screenshot of LC N105 without filtering but using pager

![Image](https://github.com/uiowa/uiowa/assets/1017022/4e290f6f-5966-4fac-9754-cfbabc254f42)


screenshot of AJB W240 without filtering by building

![Image](https://github.com/uiowa/uiowa/assets/1017022/5090009f-8172-44b5-b69e-9f5bddbccb03)

screenshot after filtering by building



![Image](https://github.com/uiowa/uiowa/assets/1017022/67e76b38-25f5-4fd8-8b36-08e253cf2d13)

**Comment by joewhitsitt** [comment]
I think this is because the A-Z sorts are based on building name only and don't factor in the room. I am going to change the sort from that to title since that is what seems to be expected here.

**Comment by joewhitsitt** [comment]
As noted on https://github.com/uiowa/uiowa/pull/6804, the sort still wasn't quite as expected. The expected A-Z sort on card title isn't available in views. I tried to get the URL path slug to the sort but was unsuccessful. Any kind of views rewriting is also not a sort option in views.


Adding a "computed field" to the node that is populated on presave. This is targetable in views and can help achieve the expected A-Z sorting.
