### ISSUE TITLE
AMCS Menu Ordering

### ISSUE THREAD

**Issue by makurj** [uiowa/uiowa#6779]
https://iowaweb.slack.com/archives/C0164FNN1PV/p1692028451931749
 
The AMCS site’s menu order is out of order again: https://amcs.uiowa.edu/ I haven’t fixed it so you can troubleshoot. This is not happening on deployment days (Wednesdays).
 
Here’s what it currently is:

![image](https://github.com/uiowa/uiowa/assets/52135878/14260277-1e59-4f54-b405-b6fd10ca5c23)

Here’s what it should be:

![image](https://github.com/uiowa/uiowa/assets/52135878/8c0b2c03-8dbd-44f0-8969-db0f7b55ba09)

 
When I look at the main menu, https://amcs.uiowa.edu/admin/structure/menu/manage/main, I don’t see a weight for “Faculty/Research” and “Graduates”, the two items that are out of order:
 
![image](https://github.com/uiowa/uiowa/assets/52135878/33d5f20a-5135-4c89-8d60-b2f757bf1318)

 
However, both items have a weight on their individual pages: https://amcs.uiowa.edu/admin/structure/menu/link/views_view%3Aviews.custom_people.page_1/edit, https://amcs.uiowa.edu/admin/structure/menu/link/views_view%3Aviews.custom_people.page_2/edit

Based on Sean’s point regarding views possibly intersecting with content, I did notice “views” in the URL.
 
![image](https://github.com/uiowa/uiowa/assets/52135878/9dfe1cd0-796c-41fb-86d7-eaf81cbc551d)

![image](https://github.com/uiowa/uiowa/assets/52135878/969a738c-8543-4ac0-a347-59c3503d0345)

**Comment by briand44** [comment]
Adding the needs grooming because we didn't size this yet.

**Comment by joewhitsitt** [comment]
i thought in planning we talked about removing these menu assignments from view config and creating manual links in the db?

**Comment by e-marie-w** [comment]
> i thought in planning we talked about removing these menu assignments from view config and creating manual links in the db?

Ah okay I couldn't remember. I can switch to trying that.
