### ISSUE TITLE
Adjust location of P2LB converter

### ISSUE THREAD

**Issue by cory-skeers** [uiowa/uiowa#6783]
As a SiteNow P2LB user, I'd like an easy way to get to the converter/converted pages.

Currently, when using the horizontal admin bar, there is no direct link to these pages. In the sidebar admin menu, it appears nested under content.

# Proposed solution

- Move the link to a top level so it is visible in both toolbars?
- Include another way to get to these overview pages?

Note: It is also possible to get to directly from the Edit screen of a v2 page.

**Comment by pyrello** [comment]
I moved the link to the top level of the Admin menu in #6775.
