### ISSUE TITLE
Integrate the inactive data into the spreadsheet

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6787]
# Story

As a web team member, I can see inactive websites represented in our spreadsheet so that we can understand if any of the sites we think may need custom development are no longer actively being maintained.

# Additional Info

https://iowa.sharepoint.com/:x:/r/sites/CSI-Drupal2/_layouts/15/Doc.aspx?sourcedoc=%7Ba3958afa-fa30-492a-948e-0a3368521d3d%7D&action=edit&wdinitialsession=1ce0992b-4080-437c-bae6-43d57bcc688d&wdrldsc=8&wdrldc=2&wdrldr=BootTimeMismatch&cid=a06d1b79-7b6c-4998-9b66-f534e0eccbf3

Related to #6612 

# Proposed Solution

**Comment by joewhitsitt** [comment]
Work was done as part of https://github.com/uiowa/uiowa/issues/7506
