### ISSUE TITLE
Pair while provisioning a CCOM site on uiowa06

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6798]
# Story

As a UIHC MarCom developer, I would like to be able to submit and process a site request according to normal processes so we can contribute to CCOM provisions and not be dependent on others to process all CCOM provisions.

# Additional Info

   - Submit a site request using the UIHC site type
   - Process the site request according normal processes (Wednesday provision deployment)
   - Request DNS/SSL certs, etc. if necessary

**Comment by briand44** [comment]
@ethan-fry has the uihc-web inbox been setup yet?

**Comment by briand44** [comment]
SSL cert should be good since that was handled as part of setting up the application

**Comment by briand44** [comment]
I got confirmation from Max that the existing request for NCBC can be processed with the other few initial CCOM sites.

**Comment by bspeare** [comment]
Most of this is done.  What remains:
 - [ ] Request DNS/SSL certs, etc. if necessary
   - [ ] Request domains to be pointed to acquia-dlb.its.uiowa.edu with a Cherwell - HCIS-TO-Hostmaster with a “Hostmaster Request” 
 - [ ] Figure out what to do with SiteNow form submission

**Comment by briand44** [comment]
The UIHC MarCom team plans to handle provisioning for the CCOM sites so we can likely archive those site requests after a quick peak if there is no concerns.

The UHC MarCom team also plans to follow our process of adding notes to the webform submissions and starring/locking when appropriate.

As far as DNS, we have a meeting next week to discuss with UIHC Hostmaster and Luke Maloney, but at this point it sounds like those requests will be submitted through Cherwell by the UIHC MarCom team and we don't need to worry about those.

The one question that came up is if the CCOM provisions should be part of our sprint provision PR or should that be a separate provision PR?

**Comment by briand44** [comment]
I will grant the UIHC MarCom devs access to the Sharepoint Docs so they have access to those.

**Comment by briand44** [comment]
I want to keep this open until:

- ~Access is granted to Sharepoint docs~
- ~Existing CCOM site request submissions have been updated with notes, etc.~
- ~We determine if the CCOM provisions are part of the normal sprint provision PR or separate~

**Comment by briand44** [comment]
I've granted access to Sharepoint docs. @ethan-fry @seandui @bzalasky-uiowa can you confirm access?

**Comment by joewhitsitt** [comment]
>The one question that came up is if the CCOM provisions should be part of our sprint provision PR or should that be a separate provision PR?

There have been merge conflicts before with sites.php so if we can have just one provisions/deprovisions per sprint, I think that would be ideal. With that said, there have been times where we have had a separate one go out if it was deemed important.

**Comment by briand44** [comment]
It was discussed that it would be preferable to just have one provision PR

**Comment by briand44** [comment]
It looks like @ethan-fry updated the site request form submissions with notes for the recently provisioned CCOM sites. I think this can be closed now.
