### ISSUE TITLE
Add "cover" or "stretch" layout builder style to the image block

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#6803]
# Story

As an editor, I can place an image block and text area in a 50/50 column and have the image fill the vertical space. 

# Proposed solution

- Add an image style to the image block that sets the image to vertically fill the container space. 

Before

<img width="1734" alt="Screenshot 2023-08-21 at 3 30 52 PM" src="https://github.com/uiowa/uiowa/assets/1036433/a05bbabd-fe03-422e-b6c0-bd4c74485425">

After

<img width="1723" alt="Screenshot 2023-08-21 at 3 26 11 PM" src="https://github.com/uiowa/uiowa/assets/1036433/02a8d1e6-d492-4129-a301-96152a91901b">

**Comment by bspeare** [comment]
I put together a quick pr for this to make sure that it would work https://github.com/uiowa/uiowa/pull/6802.

**Comment by quamsta** [comment]
@bspeare this looks cool, any chance that this could respect the focus coordinates selected when uploading/editing the image using the CSS property [object-position](https://www.w3schools.com/cssref/css3_pr_object-position.php)?

**Comment by bspeare** [comment]
@quamsta That's a great suggestion that could either be done here or delivered as a future enhancement.

**Comment by bspeare** [comment]
Some good suggestions at https://github.com/uiowa/uiowa/pull/6802#issuecomment-1692513141 for a proposed solution.
