### ISSUE TITLE
Facilities alert updates

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6805]
Feedback from our meeting today with Facilities:

In https://github.com/uiowa/uiowa/issues/6722:
- [x] Change "Short work description" to "Project title"
- [x] Delete "Details and location of closure" and use the Body field
- [x] Adjust Body field label to "Reason and details for closure" 
- [x] Change Body field to Minimal Plus text format
- [x] Change Building field to a prepopulated select list of all buildings using Chosen or Chosen successor
- [x] Change "Category" field to checkboxes
- [x] Disable the ability to schedule unpublishing (in sitenow_alerts)
- [x] Add alert categories to facilities.prod.drupal.uiowa.edu

**Comment by bspeare** [comment]
These updates were pretty easy to make.  I can demo them at Eod.   For the building list, I think we could just leave it as a single select list since it was already set to only allow one value.  So we might not need to integrate Chosen here?
