### ISSUE TITLE
Create fields for Services content type

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6806]
**Existing mockups**
All services page: https://sandbox.prod.drupal.uiowa.edu/all-services-and-software-copy
Results page: https://sandbox.prod.drupal.uiowa.edu/results-page
Services page: https://sandbox.prod.drupal.uiowa.edu/its-service-office-365-mockup

**Fields we are aware of based on mockups**
Title
Also known as (alias/synonym/alternate name)
Description/Body/teaser
Need a way to feature
Way to designate audience
Service category
Related services
Fees
Website
Quick Links
Contact Info/Getting Help?

# Proposed Solution

- [x] Create fields
- [x] theme full node
- [x] theme teaser

**Comment by joewhitsitt** [comment]
>Also known as (alias/synonym/alternate name)

Lesson learned from previous attempts: To make it available for filtering in a view, it needs to be a long text vs multi text field.

**Comment by briand44** [comment]
Grooming conversation... Let's theme the full node and teaser display as part of this slice as well.
