### ISSUE TITLE
Update icons.brand.uiowa.edu with new icons from OSC

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6819]
# Story

As a brand manager, I can see the icons.brand.uiowa.edu site updated with new icons that have been recently designed.

# Additional Info

https://iowa.sharepoint.com/sites/CSI-Drupal2/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FCSI%2DDrupal2%2FShared%20Documents%2FBrand%20Icons%2FAugust2023&viewid=bf54b9d9%2D0975%2D4fbc%2D9f1b%2D6377bdc2307c

> Attached are a handful of our icons to upload along with a list of keywords. If you could put these in the following categories, that would be great:
>  
> Business and Technology
> Fundraising
> Fax Machine
>  
> Nature and Recreation
> Volleyball
> Inclement Weather
> Tornado
>  
> Entertainment and dining
> Dancing
>  
> Home and Personal
> Big Candle
>  
> If there’s anything I missed, or if you need additional file formats, please let me know. Thanks!

# Proposed solution

- Manually add the new icons, keywords, etc.
- Think about future improvements to this process

**Comment by GaryRidgway** [comment]
This has been completed with 
https://github.com/uiowa/brand-icons/pull/23
and 
https://github.com/uiowa/brand-icon-browser/pull/106
