### ISSUE TITLE
Services results page

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6826]
# Story

As an ITS website owner, I would like to have a services landing page where I can search for a service and see results like the mockups provided or choose a featured service so that our users can find the service they are looking for.

# Additional Info

Use basic page for services landing page https://sandbox.prod.drupal.uiowa.edu/all-services-and-software-copy?

Create results page and wire it up to search block https://sandbox.prod.drupal.uiowa.edu/services?

Do we just use cards for featured services or should we wire services up to be used in the featured content component?

# Proposed Solution

- Develop results view based on mockup https://sandbox.prod.drupal.uiowa.edu/services
- Any additional theming for results/exposed filters
- Confirm the search block will work with this

**Comment by pyrello** [comment]
Having these two separate pages seems a little bit convoluted to me. It makes it more difficult to design a path-based organizational hierarchy (and therefore a coherent breadcrumb). It also breaks with previous UX patterns established on sites like [IISC](https://iisc.uiowa.edu/projects) and [Admissions](https://admissions.uiowa.edu/areas-of-study) where we have the search and results on the same page.

**Comment by bspeare** [comment]
https://sandbox.prod.drupal.uiowa.edu/services does follow the IISC and Admissions examples - the search and results are all on the same page.   https://sandbox.prod.drupal.uiowa.edu/all-services-and-software-copy is just like using the home page search block on https://admissions.uiowa.edu/ to get to the majors and minors list.

**Comment by briand44** [comment]
Grooming conversation.... Focus this slice on the results view page with exposed filters. We can recommend they add the search feature to the homepage or have a featured services page, which they could build themselves with basic page functionality.

**Comment by joewhitsitt** [comment]
In the mockup, there is a quick jump a-z. Is that something we want to pursue? If so, I think in Views, that means the view has to be a view page and not a block. Is that okay?

**Comment by briand44** [comment]
This was some previous feedback from Adrienne:

>The one thing that gives me pause is the pagination. If we’re only showing 10 services per page, I imagine it would be difficult to find a service in the middle of the alphabet. Arguably, users would use the search or faceted search options. However, if they didn’t know exactly what they were looking for or what category it was in, this might be difficult. It feels like it’s missing the A-Z jump links. Or a way to scan all of the options? I don’t have any good solutions or suggestions, but wanted to provide this feedback.

**Comment by bspeare** [comment]
I had suggested "Maybe we can try to remove the pager and add a “sort options” select list that can narrow down the search to each letter" and she seemed to like that idea.  Is that possible? I think that's fine if that means that it has to be a page.

**Comment by joewhitsitt** [comment]
~If so, I think in Views, that means the view has to be a view page and not a block. Is that okay?~

Good news: I was able to do a block. Bad News: Views no longer has a jump menu option built in for this a-z contextual filter.

Update on the jump menu: It was deemed no longer suitable for ctools in d8... It hasn't upgraded from a sandbox project: https://www.drupal.org/project/ctools/issues/2647508

**Comment by joewhitsitt** [comment]
@bspeare `circle-list` is not defined currently in UIDS and the current group headings are using h3 > span. Should we update uids to extend `uids-component--circle-list` to cover this or should I create a one-off in uids_base that works outside of `ul/li`?

**Comment by bspeare** [comment]
@joewhitsitt maybe just start with a basic heading?  Maybe we could set them to be `headline--uppercase` to start?

**Comment by joewhitsitt** [comment]
Running into an issue with "starts with" number services. For the homepage, we have all a-z items that need this start with `#` which works there (not displayed anywhere else) but not so here. Instead they will be output like `3` etc.

For ITS (v1), we don't use views to construct the list and have a bunch of manipulation going on.

<img width="535" alt="Screenshot 2023-09-11 at 12 04 33 PM" src="https://github.com/uiowa/uiowa/assets/4663676/f55a116e-33fa-4d55-9d0c-9ffa2439bd74">

**Comment by joewhitsitt** [comment]
Learned enough twig to hack something together:

<img width="892" alt="Screenshot 2023-09-11 at 2 44 55 PM" src="https://github.com/uiowa/uiowa/assets/4663676/e3ea731b-39f2-4067-a802-700d194604b5">
