### ISSUE TITLE
Block ChatGPT for Tippie paths

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6835]
# Story

As a SiteNow webmaster, I would like to block ChatGPT from some of my content but allow search engines to still index those pages in order to protect our information.

# Additional Information

Seems like currently this would need to be handled by administrators manually updating robots.txt?

Looks like you can target a specific User-agent `User-agent: GPTBot`

# Questions

Would we want to allow webmasters ability to edit robots.txt?

Is there anything available or in the works as part of metatag?

I would assume dev and stage environments would be handled already since we are disallowing all?

# Proposed Solution

**Comment by joewhitsitt** [comment]
https://thehackernews.com/2023/08/how-to-prevent-chatgpt-from-stealing.html

This article mentions user-agent: CCBot

**Comment by briand44** [comment]
interesting... I've seen a couple articles mention GPTBot but they were published in early August.

**Comment by cory-skeers** [comment]
> https://thehackernews.com/2023/08/how-to-prevent-chatgpt-from-stealing.html
> 
> This article mentions user-agent: CCBot

ccbot is used by https://commoncrawl.org/, which gets used for a lot of tools/research and was probably used by gpt originally. It's my understanding that for future models, gpt will be using only its own crawlers (largely for tracking/legal reasons), but it's still in flux, so may or may not stay the case.

It does raise the question though--what is the purpose in blocking GPT? If it's to prevent OpenAI specifically, then I think gptbot should cover it. But if it's protecting content from being crawled and used in tools like language models, we should also cover ccbot, and will likely need to expand it even more.

**Comment by joewhitsitt** [comment]
starting to sound like a rabbit hole of sorts... chatgpt is not the last one that is going to make folks uneasy over this.

**Comment by mjoneill** [comment]
OpenAI's documentation on robots exclusion for Plugins:

`User-agent: ChatGPT-User`

https://platform.openai.com/docs/plugins/bot

**Comment by mjoneill** [comment]
OpenAI's documentation for exclusion on core bot:

`User-agent: GPTBot`

https://platform.openai.com/docs/gptbot

**Comment by JKurtzlebenUI** [comment]
I meant to add our business reason for this earlier, and it fell off my list.

The first reason is for Tippie's content marketing section, The Advisor, and only The Advisor, we want to block any and all generative app crawlers like ChatGPT. For this specific use case, the info is ours, we invested significant labor and to have something/someone like topmba.com appropriate it and repackage it on a site like theirs where they sell ad space for content, would really stink. One could broadly say the information is what we’re selling on these pages.
 
Second, we don’t want someone to get this information without coming to The Advisor. It’s valuable to anyone, regardless of their choice of schools, but traffic and brand awareness are our goals, so we want them to come here. The attribution of the content is incredibly important for The Advisor and this would be lost to a generative crawler.
 
The rest of the Tippie we properties can certainly be open to generative app crawlers. For The Advisor, I’ll continue to look for every way I can find to block generative app crawlers.

**Comment by mjoneill** [comment]
I dropped specific crawlers used by ChatGPT core + plugins, but it's in a
different issue.  Will have to find it.

Now, if ChatGPT respects conventional standards, and the concern is high
enough, you can just turn on the meta robots noindex tag on a per-page
basis (advanced SEO settings, I believe?).  That's going to stop all
indexing bots that respect the convention.

Not what our partner is asking for, but there's the emergency cord if you
have to pull it for some reason.

**Comment by briand44** [comment]
@mjoneill are these what you are looking for?

https://github.com/uiowa/uiowa/issues/6835#issuecomment-1701660352

https://github.com/uiowa/uiowa/issues/6835#issuecomment-1701664127

If we know the crawlers that need blocked, could add something like the following in robots.txt configuration:

```
User-agent: GPTBot
Disallow: /advisor
```

**Comment by briand44** [comment]
>OpenAI has two separate user agents for web crawling and user browsing, so you know which use-case a given request is for. Our opt-out system currently treats both user agents the same, so any robots.txt disallow for one agent will cover both.

**Comment by mjoneill** [comment]
> @mjoneill are these what you are looking for?
> 
> [#6835 (comment)](https://github.com/uiowa/uiowa/issues/6835#issuecomment-1701660352)
> 
> [#6835 (comment)](https://github.com/uiowa/uiowa/issues/6835#issuecomment-1701664127)
> 
> If we know the crawlers that need blocked, could add something like the following in robots.txt configuration:
> 
> ```
> User-agent: GPTBot
> Disallow: /advisor
> ```

Yep.  GPT-User and GPTBot, as referenced in the issues above. 

Thanks @briand44

**Comment by briand44** [comment]
I went ahead and added the snippet from https://github.com/uiowa/uiowa/issues/6835#issuecomment-1771695474. Going to close this since it is complete for Tippie. If we get more requests for similar things we can take a look at allowing webmasters to have this ability in the future.

**Comment by briand44** [comment]
sounds like this config is not ignored so these changes will likely be reverted on next deployment. Sounds like we will need to split this?

**Comment by briand44** [comment]
Also, we should update our docs under post-launch checklist about adding custom robots.txt entries https://iowa.sharepoint.com/sites/drupal-developer-documentation/SitePages/SiteNow%20Drupal%209/Launching%20a%20Site%20in%20Drupal%209/Launching%20a%20Site%20in%20Drupal%209.aspx

**Comment by joewhitsitt** [comment]
My guess is that our student worker migrated this over from the D7 post-launch checklist and it didn't evolve with our robotstxt strategy in d8+ https://wiki.uiowa.edu/pages/viewpage.action?pageId=281025351&navigatingVersions=true

https://github.com/uiowa/uiowa/pull/1589 where it later becomes https://github.com/uiowa/uiowa/commits/main/config/default/robotstxt.settings.yml

**Comment by joewhitsitt** [comment]
Embarrassed I feel. Going to push up a "hotfix"
