### ISSUE TITLE
Enable p2lb on staff council and get them going

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6841]

**Comment by pyrello** [comment]
I turned on the P2LB split. @bspeare got in touch about it.

**Comment by briand44** [comment]
Meeting scheduled for Monday, Sept. 11th. Keeping this open until that meeting happens.

**Comment by briand44** [comment]
@pyrello how did the meeting go yesterday? Can this be closed?

**Comment by pyrello** [comment]
Meeting went well. Yes, this can be closed.
