### ISSUE TITLE
Remove sites/domains

### ISSUE THREAD

**Issue by makurj** [uiowa/uiowa#6845]
These sites/redirects/domains can be removed/deprovisioned/deleted:

- [x] clip.grad.uiowa.edu - htaccess redirect to https://dsps.lib.uiowa.edu/clip/ which then redirects to https://carnegielibrariesiowa.org/
    - [x] no database to remove
    - [x] removed domain in prod
    - [x] removed files in dev and stage. There were no files in prod
    - [x] no site directory
    - [x] no sites.php entry
    - [x] removed .htaccess redirect
    - [x] hostmaster reclaim CNAME
    - [x] update spreadsheet - nothing in spreadsheets
    - [x] deploy

- [x] facstaff.grad.uiowa.edu - redirects to https://grad.uiowa.edu/faculty-staff
    - [x] no database
    - [x] removed prod domain
    - [x] no files
    - [x] no site directory
    - [x] no sites.php entry
    - [x] .htaccess - removed redirect
    - [x] cname
    - [x] not in spreadsheet
    - [x] deploy

- [x] forms.grad.uiowa.edu
    - [x] no database
    - [x] domains - removed dev domain
    - [x] removed files directories
    - [x] no site directory
    - [x] no sites.php entry
    - [x] .htaccess - no redirect
    - [x] cname
    - [x] not in spreadsheet
    - [x] no deployment necessary

- [x] iwp.grad.uiowa.edu - redirects to https://iwp.uiowa.edu/
    - [x] no database
    - [x] domains - removed prod domain
    - [x] no files directories
    - [x] no site directory
    - [x] no sites.php entry
    - [x] removed .htaccess
    - [x] cname
    - [x] not in spreadsheet
    - [x] deploy

- [x] postdoc.grad.uiowa.edu - redirects to a page not found at https://grad.uiowa.edu/postdoc/home?portal=postdocs
    - [x] no database
    - [x] domains - removed prod domain
    - [x] no files directories
    - [x] no site directory
    - [x] no sites.php entry
    - [x] removed .htaccess
    - [x] cname
    - [x] not in spreadsheet
    - [x] deploy

- [x] ogi.grad.uiowa.edu - redirects to a page not found at https://grad.uiowa.edu/ogi
    - [x] no database
    - [x] domains - removed prod domain
    - [x] no files directories
    - [x] no site directory
    - [x] no sites.php entry
    - [x] removed .htaccess
    - [x] cname
    - [x] not in spreadsheet
    - [x] deploy

**Not hosted with Acquia**
- [x] www.pageturnpro.com/University-of-Iowa-Graduate-College/ - no idea what this is but doubt it is anything we manage.
- [x] http://ogei.grad.uiowa.edu/ - points to itsnt921.iowa.uiowa.edu
- [x] poroi.grad.uiowa.edu - points to itsnt921.iowa.uiowa.edu
- [x] signs.grad.uiowa.edu - points to itsnt889.iowa.uiowa.edu

**note**
previous tag was 2023-07-17.1

**Comment by briand44** [comment]
@makurj I think I did as much cleanup as I could as it relates to this issue. Some of these seem like they are/were properties that were managed outside of Acquia/Drupal. Also none of these were part of the 15 grad college sites that appear in the weekly site count reporting so we will want to investigate those 15 as well to see if any can be removed. While investigating ogei.grad.uiowa.edu I did find ogi.grad.drupal.uiowa.edu that does have some remnants in Acquia land. Should I clean that up or not?

**Comment by briand44** [comment]
Here are the sites I see locally on the grad app in dev desktop:

admissions_grad         	
~amcs~	 	       		     	
~book~		   	   		     	 
default
gc
~genetics~
images
~isrp~
iwp
iwp.uiowa.edu.whitmanweb
~neuroscience~
placement
~slis~
~uipress~
~urban~

Maybe we see if any of these can go away and address them in a separate issue?

**Comment by makurj** [comment]
https://github.com/uiowa/uiowa/issues/6845#issuecomment-1712134670
Yes, I think that can go away.

**Comment by makurj** [comment]
https://github.com/uiowa/uiowa/issues/6845#issuecomment-1712149482

Placement, gc (if it's the htaccess record), and images will go away when the app is deleted. The rest would be D7 databases, right?

**Comment by briand44** [comment]
I've cleaned up ogi.grad.uiowa.edu, thanks!

As far as the other list I provided, those are site directories which means that the D7 site likely still exists on the grad application. The site may or may not have a domain associated with it to access the site though.

- admissions_grad - D7 site exists but no domain pointing to it - https://github.com/uiowa/uiowa/issues/4981 - v3 lives at https://grad.admissions.uiowa.edu/
- amcs - https://amcs.prod.drupal.uiowa.edu/
- book - https://uicb.prod.drupal.uiowa.edu/
- default - 
- gc - https://grad.prod.drupal.uiowa.edu/
- genetics - https://gradgenetics.prod.drupal.uiowa.edu/
- images - https://images.grad.uiowa.edu
- isrp - D7 site exists but no domain pointing to it - v3 lives at https://iowasuperfund.uiowa.edu/
- iwp - https://iwp.uiowa.edu/
- iwp.uiowa.edu.whitmanweb - https://iwp.uiowa.edu/whitmanweb
- neuroscience - https://gradneuroscience.prod.drupal.uiowa.edu/
- placement - https://placement.grad.uiowa.edu
- slis - https://slis.prod.drupal.uiowa.edu/
- uipress - https://uipress.prod.drupal.uiowa.edu/
- urban - https://sppa.prod.drupal.uiowa.edu/

Do you think we can close this issue out and create separate issues if any of the sites listed above can be removed?

**Comment by makurj** [comment]
Okay with closing this issue and creating another one for https://github.com/uiowa/uiowa/issues/6845#issuecomment-1714457954. Going to check with team about removal/deletion.

**Comment by briand44** [comment]
Thanks, closing this!

**Comment by makurj** [comment]
@briand44 We would like to make backups of all these before removing them. I'm also having the library archive them so please don't remove these until that is completed. Some sites cannot go away just yet and I've removed them from the list below.

amcs - https://amcs.prod.drupal.uiowa.edu/
book - https://uicb.prod.drupal.uiowa.edu/
default - ???
genetics - https://gradgenetics.prod.drupal.uiowa.edu/
isrp - D7 site exists but no domain pointing to it - v3 lives at https://iowasuperfund.uiowa.edu/
neuroscience - https://gradneuroscience.prod.drupal.uiowa.edu/
slis - https://slis.prod.drupal.uiowa.edu/
uipress - https://uipress.prod.drupal.uiowa.edu/
urban - https://sppa.prod.drupal.uiowa.edu/
