### ISSUE TITLE
Config import issue with schemadotorg

### ISSUE THREAD

**Issue by cory-skeers** [uiowa/uiowa#6847]
# Problem
Relates to #6821 

# Steps to reproduce
```
ddev blt ds --site=its.uiowa.edu && ddev drush @its.local config:import --source ../config/sites/its.uiowa.edu --partial
```
See an error
```
In ConfigImportCommands.php line 324:
                                                                                             
  The import failed due to the following reasons:                                            
  Deleted and replaced configuration entity "core.entity_form_display.node.service.default"  
  Deleted and replaced configuration entity "core.entity_view_display.node.service.default"  
                                                                                            
```

# Proposed solution

The workaround is to remove `config/sites/its.uiowa.edu/schemadotorg.schemadotorg_mapping.node.service.yml`, run the import, then re-add and import it alone. Somewhere along the line, data appears to be changing while config imports are in process, leading to the broken import.

Investigate whether it's `schemadotorg` or another module having a bad reaction to its config.

**Comment by briand44** [comment]
Grooming conversation... Investigate whether it's schemadotorg or another module having a bad reaction to its config. Possibly ask maintainer, see if they plan a stable 9.5

**Comment by joewhitsitt** [comment]
Started a slack thread and waiting for bites: https://drupal.slack.com/archives/C043L3ABESE/p1694535732095319

**Comment by joewhitsitt** [comment]
It is on us that we were using DEV/Alpha in production. There is no upgrade path and there was an issue related to this https://www.drupal.org/project/schemadotorg/issues/3345244.

We may need to remove what we have and start fresh or revisit if/when there is a stable release. Part of what is slowing down a stable release is co-maintainers/sponsoring orgs. https://git.drupalcode.org/project/schemadotorg/-/blob/1.0.x/docs/ROADMAP.md

Jacob suggested trying schemadotorg_starterkit "which will generate the configuration file on the fly"

**Comment by briand44** [comment]
grooming conversation.... possibly remove all schemadotorg stuff and try with alpha5 version. Drupal 10.1 is required for alpha 6 & above. Person content type would be affected in default if removed, classrooms, facilities, ITS.

**Comment by joewhitsitt** [comment]
technically https://www.drupal.org/project/schemadotorg/releases/1.0.0-alpha5 has d9 support but I may have landed on alpha-4 earlier for a reason.

perhaps it was that i was trying to use existing config that presented problems. we have used the module with other content type features such as events, periodical, alert

**Comment by joewhitsitt** [comment]
Not sure if https://www.drupal.org/project/schemadotorg/issues/3345244 solves the issue. I think it was merged in for Alpha1. I tried Alpha5 yesterday and turned on some sub modules the patch touches like content moderation and sitemap thinking those were involved. No luck with the ITS partial import process.

**Comment by joewhitsitt** [comment]
Ben encountered an issue during uiowa06 default site install and we have seen the person config issue with site provisions and local installs lately. Removing the module and everything seems to fix the issue. Created #6902 if we can't figure out something else.

**Comment by joewhitsitt** [comment]
This issue also caused problems with a hook_entity_delete() not being scoped enough. https://app.travis-ci.com/github/uiowa/uiowa/builds/266065904#L2268

**Comment by bspeare** [comment]
Since we are so close to D10, should we just do https://github.com/uiowa/uiowa/pull/6902 and start over with D10?  @joewhitsitt if our current version was working, what would our process be for updating to a D10 version?

**Comment by joewhitsitt** [comment]
I wish I could say that the D10 version solves our issue, but I don't know. I put the PR together as a safety net and I am fine with using it if other sets of eyes can't find a path forward. I think the PR only currently touches config. There is some code related to this, event location? that probably assumes the module is enabled and will need to be tested/commented out/removed

**Comment by joewhitsitt** [comment]
The maintainer is not planning on providing an upgrade path through the alphas so we will probably need to re-configure from scratch once a stable version is released.

**Comment by e-marie-w** [comment]
> I think the PR only currently touches config. There is some code related to this, event location? that probably assumes the module is enabled and will need to be tested/commented out/removed.

This is the only non-config thing I've found as well. Commenting out the `sitenow_events_schemadotorg_jsonld_schema_type_entity_alter` function in `sitenow_events.module` is not causing any errors on default or sandbox for me, do we want to just remove it now?

Also, removing schemadotorg from composer would be a follow-up issue, correct?

**Comment by joewhitsitt** [comment]
Since the function is scoped to the module, I think we should remove it for now and re-implement later. We will have the git history to reference.

**Comment by joewhitsitt** [comment]
Created https://github.com/uiowa/uiowa/issues/6986 as a follow-up. Closing this issue based on the merge of https://github.com/uiowa/uiowa/pull/6902
