### ISSUE TITLE
SiteNow logins in Chrome: Status 400 – Bad Request login

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#6853]
# Problem 

SiteNow logins in Chrome often return a Status 400 – Bad Request login message. 

<img width="1159" alt="Screenshot 2023-09-05 at 10 28 46 AM" src="https://github.com/uiowa/uiowa/assets/1036433/986d9c89-660f-4f52-b0bb-a19d0c8b5938">

# Proposed solution

Contact IAM team to see if they have any suggestions.

**Comment by bspeare** [comment]
I submitted a ITS Help Desk ticket for this issue. (1898249)

**Comment by bspeare** [comment]
Response from IAM:


> The IAM Team was unable to reproduce the error in Google Chrome and they watched others log into the Admin portal of Sitenow pages as well.
>  
> Please instruct the users to delete their cookies in Chrome, this will probably fix the issue:[ https://its.uiowa.edu/support/article/719](https://its.uiowa.edu/support/article/719). Chrome has been doing the same thing in ICON for students this semester.
>  
> For further help, people can share their screen with us via our Live Chat Portal:[ https://helpdesk.its.uiowa.edu/connect/](https://helpdesk.its.uiowa.edu/connect/).
>  
> Please do not hesitate to contact the Service Desk if you have any questions, or use our Customer Portal to view [Incident 1898249](https://service.uiowa.edu/CherwellPortal/ESCPortal/Incident/1898249) for more details.

**Comment by cory-skeers** [comment]
Can confirm that clearing cookies worked for me. I hit the bad request trying to log into its.uiowa.edu (d7) with Chrome, cleared cookies and retried, and it worked.

**Comment by bspeare** [comment]
Added this as a known issue: https://sitenow.uiowa.edu/known-issues#uiowa-issue-6645

**Comment by joewhitsitt** [comment]
was this happening before IAM had all of this beginning of semester auth issues?

**Comment by joewhitsitt** [comment]
Since we are still running into this periodically, we opened another ticket:

Ticket id 2011533.
>Completely clearing the browser cache is often a bit excessive. I would probably just delete the cookies and close all browser windows and restart. Could also try incognito or other private browsing method

In the future, for cherwell tickets we can try to reassign if there is a timestamp associated with the ticket, but since this seems to be largely a cookie/user issue, I doubt they will be able to help the user further.
