### ISSUE TITLE
SiteNow September 2023 Newsletter

### ISSUE THREAD

**Issue by cory-skeers** [uiowa/uiowa#6862]
DRAFT: https://sitenow.uiowa.edu/news/2023/09/updates-september-2023

### Issue/Solution
Provide a "release notes" type article of finished/done features/updates and publish to website, then send out dispatch email.

- [x] Create draft and update the parking lot card with an edit link
- [x]  Add "release notes" covering the month of v2/v3 default profile enhancements and webmaster/edit visible bug fixes.
- [x] See the previous month's article as an example.
- [x] Bullet points from demo stories slide per week: https://drive.google.com/drive/folders/1EehKUjxCbakaB9FchrGhAbaxuRbqyDGW?usp=sharing.. and/or from Web Community sprint demo announcements https://webcommunity.sites.uiowa.edu/updates/2023/02/sprint-demo-149-february-16-2023
- [x]  Get at least one team member to look over the draft before publishing.
- [x]  Since the draft was started earlier, adjust the publish date/time, publish, get the link to the article.
- [x]  Dispatch email with link to article. (To get access, send an email to [dispatch-support@uiowa.edu](mailto:dispatch-support@uiowa.edu) to have the account provisioned. Provide your hawkid and mention the CSI:drupal group)
  - [x] Modify SiteNow Announcements Template (tweak opening line, update the article link, any other editorial adjustments)
  - [x] Clone an old communication off SiteNow Announcements campaign
    - [x] Use SiteNow Announcements population, template, suppression list, bypass approval.
    - [x] Turn off Dispatch "test mode" to send out email.
    - [x] When scheduling, check the "archive" option so that there is an RSS instance we can use in the future. I don't think this can be done after the fact.
- [x]  Turn on Dispatch "test mode" after email is successfully sent.
- [ ]  Take a moment to check dispatch and google analytics on whether these articles are being read.
- [x]  Create the next months's issue and copy all this bullet list into it, removing the checked boxes if any.

**Comment by e-marie-w** [comment]
Draft updated and now ready for review: https://sitenow.uiowa.edu/news/2023/10/updates-september-2023

**Comment by joewhitsitt** [comment]
>Additionally, preparations for moving the SiteNow platform to Drupal 10 began.

There was concern when we mentioned this in a meeting today. I wonder if there is a way to phrase this so that v2/v3 sites need not worry about being put on an island again like v1.

**Comment by joewhitsitt** [comment]
Also, dug a bit in the support canvas and spotted a few non-lab/sites website launches.

innovation.uiowa.edu and ees.uiowa.edu?

**Comment by e-marie-w** [comment]
Oooooh I'll add those sites and work on rewording that one line.

**Comment by joewhitsitt** [comment]
Enlisted the help of chatgpt and quite a bit of hand holding...

`We're gearing up for a transition to Drupal 10 from Drupal 9.5, ensuring SiteNow v2/v3 websites experience a seamless upgrade with no expected action from website owners.`

<img width="706" alt="Screenshot 2023-10-10 at 5 02 40 PM" src="https://github.com/uiowa/uiowa/assets/4663676/d160c7ee-67ad-4faf-b07f-f215d7a11541">

**Comment by e-marie-w** [comment]
Lol that works, I've replaced that one line with this. Am I good to proceed with publishing and dispatch?

**Comment by e-marie-w** [comment]
Closing as done - article published, Dispatch communication sent (and test mode turned back on), and new issue for October updates created.
