### ISSUE TITLE
As an owner of brand.uiowa.edu, I can start using P2LB on my site

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#6864]
As an owner of brand.uiowa.edu, I can start using P2LB on my site on Oct 1st so that I can try out the page conversion process before meeting with the OSC web team on Oct 17.

**Comment by bspeare** [comment]
This is blocked until https://github.com/uiowa/uiowa/issues/6859 is fixed.

**Comment by pyrello** [comment]
Looks like we completed this too.
