### ISSUE TITLE
Site Request Email - BLT command includes https://

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#687]
## Problem
copy/paste command cannot be used as-is due to https:// being included.

**Comment by joewhitsitt** [comment]
Could do something custom similar to https://github.com/uiowa/uiowa/blob/master/docroot/sites/brand.uiowa.edu/modules/brand_core/brand_core.module#L170 otherwise it might make more sense to just leave out the blt command and reinforce the step within developer documentation

**Comment by richardbporter** [comment]
Whoops. There is another field set which is just the host. Just need to replace the token from uri to host.
