### ISSUE TITLE
Show category in breadcrumb on services

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6872]
# Story

As an ITS website owner, I would like to output the category associated with a service in the breadcrumb on the service page so that users can click the link to view all services that are associated with that particular category.

# Additional Info

The category field exists on the service content type but is not currently being output anywhere

We should output the category in the breadcrumb as a link to that term page.

At this point we don't need to output the category anywhere else on the service.

# Questions

Do we need to output the category in the breadcrumb? - Yes
Do we need the category to be reflected in the url alias? - No

There is some internal conversation around these questions https://github.com/uiowa/uiowa/pull/6821#issuecomment-1703245392

# Proposed solution

- Output breadcrumbs on services - Home - Services - Service Category - Title of service

**Comment by briand44** [comment]
I got some feedback from Adrienne. She feels stronger about having the category be represented in the breadcrumb then in the url alias. The only concern about outputting the category on the service page was that she wants to avoid confusion between the related services and the category.

**Comment by briand44** [comment]
Grooming conversation... Establish category as link to term page in breadcrumb, possibly using easy breadcrumb similar to periodicals and update service category vocabulary pattern to match.

**Comment by cory-skeers** [comment]
> I got some feedback from Adrienne. She feels stronger about having the category be represented in the breadcrumb then in the url alias.

@briand44 I remember a fair bit of the back and forth about this, but I don't recall if there was specifically a desire _not_ to include the category in the url alias.

In the initial setup for the Service content type we'd already had a url pattern for `services/[node:title]`, and so updating it to `services/[node:field_service_category:entity:name]/[node:title]` and having the url match the breadcrumb makes it a quick and easy update without involving adding Easy Breadcrumb or any other work beyond the existing pathauto alias.
