### ISSUE TITLE
Updating display of multiple person education

### ISSUE THREAD

**Issue by cory-skeers** [uiowa/uiowa#6874]
> Is there another way to differentiate between the separate line items for the education field outside of commas? I ask because it basically makes it impossible to use commas within those fields without becoming comma city. Example (https://theatre.prod.drupal.uiowa.edu/people/art-borreca):

![Image](https://user-images.githubusercontent.com/49074566/267121208-404acc98-30d9-47ce-9668-98de988d2655.png)

Requested by Brynne Schweigel w/CLAS

**Comment by cory-skeers** [comment]
Also might want to look into how multiple websites are displayed. as the other multi-field that gets displayed in the sidebar card here.

**Comment by joewhitsitt** [comment]
Credentials is a single value text field and there is an open text area to capture the education background they are trying to display here.

**Comment by cory-skeers** [comment]
> Credentials is a single value text field and there is an open text area to capture the education background they are trying to display here.

Labeling this as credentials was my mistake. I think that field is working/displaying as expected.

For education, it's a text area that allows for multiple values
<img width="808" alt="image" src="https://github.com/uiowa/uiowa/assets/49074566/515a5799-ec67-479e-b99a-ca28d1495e2f">
I think the expectation/ask is that each should display on a separate line without commas, or if it were a single open text field where the editor would be responsible for deciding how the separation should be handled.

**Comment by bspeare** [comment]
Can we just remove the comma from the field delimiter?

<img width="532" alt="Screenshot 2023-09-12 at 3 30 06 PM" src="https://github.com/uiowa/uiowa/assets/1036433/cd1c3fa2-9675-415b-8393-d9ab85d82c84">

**Comment by cory-skeers** [comment]
> Can we just remove the comma from the field delimiter?

Looks good to me!
