### ISSUE TITLE
GC: Old Sites to Remove

### ISSUE THREAD

**Issue by makurj** [uiowa/uiowa#6877]
Follow-up from https://github.com/uiowa/uiowa/issues/6845
Not hosted with Acquia

- [x]  [www.pageturnpro.com/University-of-Iowa-Graduate-College/](http://www.pageturnpro.com/University-of-Iowa-Graduate-College/) - no idea what this is but doubt it is anything we manage.
- [x]  http://ogei.grad.uiowa.edu/ - points to itsnt921.iowa.uiowa.edu
- [x]  poroi.grad.uiowa.edu - points to itsnt921.iowa.uiowa.edu
- [x]  signs.grad.uiowa.edu - points to itsnt889.iowa.uiowa.edu

Remove record or whatever information exists:
- [x] forms.grad.uiowa.edu

Remove these once an Acquia backup and library archive has been completed:

- [x] amcs - https://amcs.prod.drupal.uiowa.edu/
- [x] book - https://uicb.prod.drupal.uiowa.edu/
- [x] genetics - https://gradgenetics.prod.drupal.uiowa.edu/
- [x] isrp - D7 site exists but no domain pointing to it - v3 lives at https://iowasuperfund.uiowa.edu/
- [x] neuroscience - https://gradneuroscience.prod.drupal.uiowa.edu/
- [x] slis - https://slis.prod.drupal.uiowa.edu/
- [x] uipress - https://uipress.prod.drupal.uiowa.edu/
- [x] urban - https://sppa.prod.drupal.uiowa.edu/

**Comment by briand44** [comment]
>Remove these once an Acquia backup and library archive has been completed:

I'm curious about the library archive. Since these sites no longer live at the live url and only live at the internal production domains, can/should the library archive these? Also, isrp does not even have an internal prod domain pointing at the old site so not sure how the library would archive that.

**Comment by makurj** [comment]
I heard back from the library. There are archived versions from before, so these can be backed up in Acquia (please share the backup with me) and removed.

amcs - https://amcs.prod.drupal.uiowa.edu/
book - https://uicb.prod.drupal.uiowa.edu/
genetics - https://gradgenetics.prod.drupal.uiowa.edu/
neuroscience - https://gradneuroscience.prod.drupal.uiowa.edu/
slis - https://slis.prod.drupal.uiowa.edu/
uipress - https://uipress.prod.drupal.uiowa.edu/
urban - https://sppa.prod.drupal.uiowa.edu/

**Comment by briand44** [comment]
Documenting some failures rsyncing some files from slis:

`- rsync reported a partial failure. Some file(s) were not transfered, see details below.
rsync: mkstemp "/Users/bdickey/Sites/devdesktop/uigraduatecollege-dev/docroot/sites/slis/files/images/.AndreI`\#201Brock.homepagenews.jpg.Nzwej4" failed: Illegal byte sequence (92)
rsync: mkstemp "/Users/bdickey/Sites/devdesktop/uigraduatecollege-dev/docroot/sites/slis/files/images/.AndreI`\#201Brock.jpg.oADQbh" failed: Illegal byte sequence (92)
rsync: mkstemp "/Users/bdickey/Sites/devdesktop/uigraduatecollege-dev/docroot/sites/slis/files/images/.AndreI`\#201Brock.nodesidebar.jpg.zZoJir" failed: Illegal byte sequence (92)
rsync: mkstemp "/Users/bdickey/Sites/devdesktop/uigraduatecollege-dev/docroot/sites/slis/files/images/.AndreI`\#201Brock.preview.jpg.bGwAap" failed: Illegal byte sequence (92)
rsync: mkstemp "/Users/bdickey/Sites/devdesktop/uigraduatecollege-dev/docroot/sites/slis/files/images/.AndreI`\#201Brock.quicklink.jpg.wXxRFz" failed: Illegal byte sequence (92)
rsync: mkstemp "/Users/bdickey/Sites/devdesktop/uigraduatecollege-dev/docroot/sites/slis/files/images/.AndreI`\#201Brock.studentspotlight.jpg.CTZbpw" failed: Illegal byte sequence (92)
rsync: mkstemp "/Users/bdickey/Sites/devdesktop/uigraduatecollege-dev/docroot/sites/slis/files/images/.AndreI`\#201Brock.thumbnail.jpg.wtKwUT" failed: Illegal byte sequence (92)
rsync: mkstemp "/Users/bdickey/Sites/devdesktop/uigraduatecollege-dev/docroot/sites/slis/files/images/.AndreI`\#201Brock123.homepagenews.jpg.xyNVSv" failed: Illegal byte sequence (92)
rsync: mkstemp "/Users/bdickey/Sites/devdesktop/uigraduatecollege-dev/docroot/sites/slis/files/images/.AndreI`\#201Brock123.jpg.ZQTX57" failed: Illegal byte sequence (92)
rsync: mkstemp "/Users/bdickey/Sites/devdesktop/uigraduatecollege-dev/docroot/sites/slis/files/images/.AndreI`\#201Brock123.nodesidebar.jpg.azaoP2" failed: Illegal byte sequence (92)
rsync: mkstemp "/Users/bdickey/Sites/devdesktop/uigraduatecollege-dev/docroot/sites/slis/files/images/.Andre...`

**Comment by briand44** [comment]
Had to alter our documented archive-dump command to get the backups to work. Used `drush archive-dump [directoryName] --no-core` instead

**Comment by briand44** [comment]
@makurj All of the sites from https://github.com/uiowa/uiowa/issues/6877#issuecomment-1719757408 have been backed up and are available https://iowa.sharepoint.com/sites/CSI-Drupal2/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FCSI%2DDrupal2%2FShared%20Documents%2FGeneral%2Fsite%2Dbackups%2FGraduate%20College%20Websites&viewid=bf54b9d9%2D0975%2D4fbc%2D9f1b%2D6377bdc2307c.

SLIS had a problem with a few files as noted https://github.com/uiowa/uiowa/issues/6877#issuecomment-1721808809.

It might be a little confusing that the backup for https://sppa.prod.drupal.uiowa.edu is named urban but evidently that's where it is.

Is there a reason isrp didn't make the list of sites to remove even though there currently is no domain pointing to it?

Do I have your approval to start removing the sites that just got backed up?

**Comment by makurj** [comment]
@briand44 Update from library: They are going to archive the .prod latest versions so please wait to remove until that is complete. We can proceed with Acquia backups.

**Comment by makurj** [comment]
@briand44 We can remove ISRP. 

I have an update from the library: they will archive the .prod sites' again so we have their latest versions instead of 5-6 years old ones, so we would like to wait until that is done before removing these sites.

**Comment by makurj** [comment]
Pageturnpro was an old application, which no longer exists. Nothing to remove.
These were on-prem GC servers, which are no longer there. Nothing to remove/delete.
   http://ogei.grad.uiowa.edu/ - points to itsnt921.iowa.uiowa.edu
   poroi.grad.uiowa.edu - points to itsnt921.iowa.uiowa.edu
   signs.grad.uiowa.edu - points to itsnt889.iowa.uiowa.edu

**Comment by briand44** [comment]
It would probably be a good idea to email hostmaster and have them reclaim those CNAMES since they are not in use.

**Comment by makurj** [comment]
I added forms.grad.uiowa.edu to the list above as that was another one we could get rid of. Gives a "Website not found".

**Comment by briand44** [comment]
forms.grad.uiowa.edu was cleaned up as part of https://github.com/uiowa/uiowa/issues/6845

**Comment by makurj** [comment]
Can we also remove the redirect for molcellbio.grad.uiowa.edu to https://medicine.uiowa.edu/mcb/?

**Comment by briand44** [comment]
^^ This redirect has been removed. I removed the domain as well from Acquia Cloud. Can I have hostmaster reclaim this CNAME?

**Comment by makurj** [comment]
https://github.com/uiowa/uiowa/issues/6877#issuecomment-1734012762: Thanks! And yes.

**Comment by briand44** [comment]
Email sent to hostmaster

**Comment by makurj** [comment]
@briand44  Just heard back from the library and these have been archived. They can now be deprovisioned.
  amcs - https://amcs.prod.drupal.uiowa.edu/
  book - https://uicb.prod.drupal.uiowa.edu/
  genetics - https://gradgenetics.prod.drupal.uiowa.edu/
  neuroscience - https://gradneuroscience.prod.drupal.uiowa.edu/
  slis - https://slis.prod.drupal.uiowa.edu/
  uipress - https://uipress.prod.drupal.uiowa.edu/
  urban - https://sppa.prod.drupal.uiowa.edu/

**Comment by briand44** [comment]
@makurj it looks like book.grad.uiowa.edu domain exists on the Grad application and redirects to https://uicb.uiowa.edu/. Do you want to keep that domain and redirect in place for now?

**Comment by makurj** [comment]
I'll check with the team and let you know.

**Comment by briand44** [comment]
@makur Should the slis.grad.uiowa.edu redirect to slis.uiowa.edu continue to exist?

**Comment by makurj** [comment]
I'll check with the team and let you know.

**Comment by makurj** [comment]
@briand44 We can remove the SLIS redirect. 
https://grad.admissions.uiowa.edu/ looks like it's a functioning site, so we will let Scott decide on the remnants on the GC app.
For Book, **_wait_** as I have to let them know prior to redirect removal.

**Comment by briand44** [comment]
@makurj Thanks!. I've removed the SLIS redirect and had Hostmaster reclaim the cname.

I got approval from Scott and I will move forward with removing the Grad Admissions D7 site.

I'll hold off on book.

Are you ok if I close this since there is already a separate issue for Grad Admissions https://github.com/uiowa/uiowa/issues/4981? We can create a new issue whenever book or other sites/redirects are ready to be removed.

**Comment by makurj** [comment]
I'm fine with closing. I did send book an email about it. I'll give them another day or two to respond with any questions/concerns. I think Wednesday or Thursday of this week should be okay to proceed. I can put a reminder on my calendar for it since this issue will be closed.

**Comment by makurj** [comment]
@briand44 Book is using brochures with the old address. New brochures are in the works. We would like to keep book.grad.uiowa.edu around for a few more months. I will check with them January 2, 2024 and let you know.
