### ISSUE TITLE
[Probe, P2LB] Check a random assortment of V2 sites with P2LB to gain confidence on edge cases.

### ISSUE THREAD

**Issue by GaryRidgway** [uiowa/uiowa#6879]
Recently when working on https://github.com/uiowa/uiowa/pull/6830 I found a [small bug](https://github.com/uiowa/uiowa/pull/6830#issuecomment-1717895020) that hindered the hawkeyemarchingband site from converting properly. I was able to fix it, but it made me think that perhaps a larger scale of testing on some sites might be valuable before really rolling out P2LB. @joewhitsitt was able to talk my 'Larger scale testing' down to a 'Slightly larger scale testing', and we agreed that taking roughly a third of the V2 sites at random and running a full P2LB conversion would allow us to see a breadth of potential issues that could arise from the conversions.

### Expected value gained
Either:  
- A list of bugs that can be fixed for P2LB
- Or no bugs at all and we are amazing.

### Proposed solution
1. Compile a list of all V2 sites from all applications by SSHing in to each one (ex. `ddev drush @uiowa.prod ssh` then `cd ../`) and running `./vendor/bin/blt ume "config:get config_split.config_split.sitenow_v2 status"`
2. Select a third of them at random.
3. Run P2LB for each site, observe errors  in any fashion, conversion, publishing, and cleanup.
4. Compile a list of those errors broken down by their relevant categories.
5. Post results here to act upon in later issues.

**Comment by pyrello** [comment]
I'm wondering if this is still necessary or maybe if we have already done this work? P2LB conversion has been started or completed on 11 sites according to our tracking spreadsheet. I think it is unlikely that we are going to prioritize this before we get done with D7 migrations unless we encounter more issues. If we encounter more issues, we will probably just focus on those and not do this type of randomized testing.
