### ISSUE TITLE
UTM parameters are being stripped out from webforms

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#6883]
# Problem

UTM parameters are being stripped out from webforms. 

Test out the link below in Safari or Chrome, try viewing the link while you are logged in and logged out - are the fields prepopulated?

https://sandbox.prod.drupal.uiowa.edu/form/utm-test?utm_source=newsletter&utm_medium=cpc&utm_campaign=middle-amana,%20for%20example&source=chrome&medium=cpc&utmcampaign=middle-amana
 

## Relevant links

- https://acquia.my.site.com/s/article/360004119294-Acquia-s-default-Varnish-VCL-strips-Google-Analytics-and-Facebook-Ads-query-string-parameters
- https://github.com/uiowa/uiowa/pull/5961
- https://github.com/uiowa/uiowa/issues/5964

# Proposed Solution

- [ ] include utm_campaign, utm_source, utm_medium, utm_content similarly to fbclid and gclid

**Comment by briand44** [comment]
>The Acquia platform, as a means to maximize performance via the Varnish caching layer, removes web analytics parameters from URLs (for example, Google Analytics' utm_source and others).

https://acquia.my.site.com/s/article/360022954014-Handling-redirects-while-keeping-web-analytics-UTM-query-parameters

**Comment by briand44** [comment]
Seems like we'll need to handle these like we did with gclid and fbclid.

**Comment by JKurtzlebenUI** [comment]
in the test case from above, it looks like you're already testing for:
Utm_campaign
Utm_source
Utm_medium

i'm not sure if it's already there, but we'd like to also capture: 
Utm_content

Thanks!
James

**Comment by briand44** [comment]
Grooming conversation... Piggyback off of previous work for FBCLID and GCLID. Difficult to test until behind Varnish.

**Comment by pyrello** [comment]
I'm going to work on this.
