### ISSUE TITLE
Additional Dance Icons

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6891]
>Dance had a need for a couple icons that we didn’t want to push off until next round. They can both use the same category/keywording listed below. Could we get these added when you get a chance? Thanks!
 
Category:
Entertainment and Dining
 
Keywords:
Dancing
Pointe
Ballet
Gala
Music
Perform
Performance

# Additional Info

https://iowa.sharepoint.com/sites/CSI-Drupal2/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FCSI%2DDrupal2%2FShared%20Documents%2FBrand%20Icons&viewid=bf54b9d9%2D0975%2D4fbc%2D9f1b%2D6377bdc2307c

^^ the Brand-Icons_DanceAddition.zip file

# Proposed Solution

- [x] Add the additional dance icons with the category and keywords mentioned
- [x] Add the keyword "Dance" to any additional dancing/dance-related icons, including the ones that have already been added https://github.com/uiowa/uiowa/issues/6891#issuecomment-1729604924

**Comment by quamsta** [comment]
@briand44 @GaryRidgway I'd recommend also adding the keyword "Dance" to any additional dancing/dance-related icons, including the ones that have already been added:

e.g., these two searches should show the same results, but currently aren't:

https://icons.brand.uiowa.edu/search/dancing

https://icons.brand.uiowa.edu/search/dance

**Comment by e-marie-w** [comment]
Completed via https://github.com/uiowa/brand-icons/pull/24, https://github.com/uiowa/brand-icons/pull/25, and https://github.com/uiowa/brand-icon-browser/pull/108. New icons are correctly appearing on the prod site, and searches for 'dance' and 'dancing' now return the same results.
