### ISSUE TITLE
Operations Manual name change

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6893]
The Operations Manual is being renamed to Policy Manual.

Potential changes needed:

- request new domain
- create domain in acquia on 703
- Updated sites.php to direct new domain to opsmanual.uiowa.edu directory
- setup redirect for opsmanual.uiowa.edu on vulture and test locally
- lower ttl of opsmanual.uiowa.edu
- update DNS for opsmanual.uiowa.edu to point to vulture
- Update site name
- regenerate sitemap and submit

**Comment by joewhitsitt** [comment]
Can we push back on this a bit and suggest they stay at the current domain until they move to v3? We can change the site name and they can update all of their content language. We can have policymanual.uiowa.edu redirect to opsmanual.uiowa.edu for the time being.

**Comment by joewhitsitt** [comment]
Also, do we have an epic/strategy card/issue for this site to move off d7?

**Comment by briand44** [comment]
Leadership has said the domain name can stay as is until this site moves to v3. So I think the only thing in our court would be to update the site name when they are ready for that.

**Comment by briand44** [comment]
Going to close this since it shouldn't take and dev capacity and I'm not sure when they will be ready for us to update the site name.
