### ISSUE TITLE
Update default GTM config

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6900]
# Story

As a site owner using Google Tag Manager, I would like my scripts to fire on appropriate pages so that we can get the expected data for those pages.

# Additional Info

The default GTM config is excluding `/admin*` which prevents GTM scripts from firing on pages such as `/administration`.

Should exclude `/admin` and `/admin/*`

Check for `/admin*` and similar `/batch*` etc. Compare with Google Analytics setup.

And may be an upstream issue with GTM

# Proposed Solution

- [ ] Update GTM /admin* to /admin and /admin/*
- [ ] Update GTM /batch* to /batch and /batch/*

**Comment by briand44** [comment]
Grooming convo... Default container settings that are tracked and used for new containers but then ignored.

GA:
    /admin
    /admin/*
    /batch
    /node/add*
    /node/*/*
    /user/*/*


GTM:
    /admin*
    /batch*
    /node/add*
    /node/*/edit
    /node/*/delete
    /user/*/edit*
    /user/*/cancel*

**Comment by joewhitsitt** [comment]
config/default/google_tag.settings.yml

**Comment by pyrello** [comment]
I included this as part of the updates to a new version of the Google Tag module in #6970
