### ISSUE TITLE
FireLog CategoryCause not properly mapped to table output

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#6904]
# Problem
CleryEdge pegged an issue being on our end where the CategoryCause is not being properly output as part of the table.

```xml
<ArrayOfApiFL xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.datacontract.org/2004/07/TripWeb.Data">
<ApiFL>
<CaseNumber>FIRE-2023-9</CaseNumber>
<CategoryCause>Unintentional / Cooking</CategoryCause>
<Location>Mayflower Hall / 4th Floor</Location>
<Occurred>09/17/2023 18:40</Occurred>
<Reported>09/17/2023 18:43</Reported>
</ApiFL>
<ApiFL>
<CaseNumber>FIRE-2023-6</CaseNumber>
<CategoryCause>Unintentional / Cooking</CategoryCause>
<Location>Burge Hall / Dining Room</Location>
<Occurred>08/16/2023 16:15</Occurred>
<Reported>08/17/2023 08:10</Reported>
</ApiFL>
</ArrayOfApiFL>
```

<img width="1011" alt="Screenshot 2023-09-19 at 12 48 35 PM" src="https://github.com/uiowa/uiowa/assets/4663676/14f6dd0a-895f-4939-b99e-fb2cdc87e364">

# Proposed solution
- [x] Fix loop to grab this data and display it.
- [x] "The disposition box is not needed."

**Comment by bspeare** [comment]
This has been updated to display the Classification and removed the Disposition: https://safety.uiowa.edu/fire-log.   Can someone take a look at this and confirm that it is working?

**Comment by joewhitsitt** [comment]
>Can someone take a look at this and confirm that it is working?

Looks good to me. You are on the thread. Do you want to respond to them that this is done?

**Comment by bspeare** [comment]
Thanks! I have emailed them that it is fixed now.
