### ISSUE TITLE
Update docs related to field_teaser/summary changes

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#6907]
With the merge/deployment of https://github.com/uiowa/uiowa/pull/6769 we now live in a world where we have different summary strategies between v2/v3. We should make this clear on our SEO docs, content type(s) docs.

**Comment by bspeare** [comment]
I have updated these pages with the new "Summary" field:

- https://sitenow.uiowa.edu/documentation/person-content-type
- https://sitenow.uiowa.edu/documentation/search-engine-optimization
- https://sitenow.uiowa.edu/documentation/basic-page-content-type
- https://sitenow.uiowa.edu/documentation/article-content-type

**Comment by joewhitsitt** [comment]
I'll take a look at this after standup

**Comment by joewhitsitt** [comment]
https://sitenow.uiowa.edu/documentation/basic-page-content-type needs a v2/v3 difference explainer for the short-term. There are links at the bottom, but with the body/summary and content block differences now, maybe we should highlight that higher up in the doc.

Should the same `between 50–160 characters, although the “optimal” length will vary depending on the situation` and `You can also leave blank to use a trimmed value of the Body full text as the summary.` be used for all three content types?

**Comment by bspeare** [comment]
I've updated all of the Summary descriptions for all three content types to follow the same pattern:

`Type a short summary of your content here. It will be used if there are any displays around the site that reference this content. By default, this is also used by search engines when they crawl and index your site. We recommend descriptions between 50–160 characters, although the “optimal” length will vary depending on the situation. You can also leave blank to use a trimmed value of the Body full text as the summary.`

For the Basic Page Content Description I have added a v2/v3 difference explainer:
`Content Description: This teaser field has been deprecated in v3 and replaced by the Summary field.  This field still exists in v2 and works similar to the Summary field described above.`

**Comment by joewhitsitt** [comment]
Thanks! I am fine with closing this then

**Comment by bspeare** [comment]
Thanks for the feedback @joewhitsitt!
