### ISSUE TITLE
Update extensions that have moved into or out of core

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6931]
We got a report of deprecated or obsolete core extensions that are installed. These will be removed in the next major version. [Aggregator (read more)](https://www.drupal.org/node/3223395#s-aggregator), [CKEditor (read more)](https://www.drupal.org/node/3223395#s-ckeditor)
We have these issues thus far:

Aggregator: https://github.com/uiowa/uiowa/issues/5064
Ckeditor: https://github.com/uiowa/uiowa/issues/5667 (we may need to use cke4 contrib at first)

Finally, we should have more control over our ctools by declaring it in our composer.json file:

ctools: https://github.com/uiowa/uiowa/issues/5589

**Comment by joewhitsitt** [comment]
Added some more specifics from the probe issue and other issues in our backlog related to d10

**Comment by briand44** [comment]
Sounds like we may need to do these as part of the update to D10 to avoid namespace collisions.

**Comment by pyrello** [comment]
I updated the IS to reflect that Allowed Formats and Block Content Permissions in core is not happening until 10.1 so they are both blocked until then.

I also removed the information about classy and stable because that was addressed already in #6277

**Comment by pyrello** [comment]
It seems like we (I) was wrong about the assumption that these modules could not be added prior to being removed from core. I noticed there was a version of aggregator that is compatible with Drupal 9.4, which wouldn't make sense if you couldn't have the contrib module at the same time as the core version still existed. I opened #6997 to try this out.

**Comment by pyrello** [comment]
I added all the items from here to #6959 and I'm going to close this in favor of just managing those items individually through that issue.
