### ISSUE TITLE
News article showing twice on studentlife.uiowa.edu

### ISSUE THREAD

**Issue by bewoldt** [uiowa/uiowa#6956]
# Problem
A news article is showing up twice on the homepage of studentlife.uiowa.edu. The Articles block on the right is offset by 1 so this shouldn't be happening.

<img width="1336" alt="image" src="https://github.com/uiowa/uiowa/assets/731952/023ccad3-1fd7-40ec-ab32-a44d1c43ca5e">

**Comment by joewhitsitt** [comment]
@bewoldt is this no longer an issue?

**Comment by bspeare** [comment]
I tested this morning and it appeared to be working again so perhaps it was a momentary glitch.

**Comment by bewoldt** [comment]
@joewhitsitt It seemed to fix itself once a new article was published.

**Comment by bewoldt** [comment]
Reopened because I saw it happening again. Closing **again** because it was just a user error by a student duplicating content.
