### ISSUE TITLE
Lazy Load Images Using Blazy

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#697]
## Problem
Our web performance score is low. I don't know what that means but off-screen images on page load have something to do with it and with basic page we are indirectly encouraging long pages and lots of images.

https://www.drupal.org/project/blazy

https://www.symphonythemes.com/drupal-blog/speed-your-drupal-8-sites-image-lazy-loading

Probably not for section images, but everything else makes sense to me.

**Comment by bspeare** [comment]
@joewhitsitt, having this or https://www.drupal.org/project/lazy could greatly help the page load speed for the new image heavy home page.   Do you have any thoughts on whether we could implement this?

**Comment by joewhitsitt** [comment]
@bspeare I think this is past whether we _can_ and more about _how and when_ we implement it. We postponed it for SiteNow because we didn't have time to think about it. Blazy definitely has the usage compared to Lazy. I don't have experience with either and don't know how it works with everything else (responsive images, etc.).

**Comment by bspeare** [comment]
Yes, blazy has some good numbers behind it.  I'll add it to the parking lot for further discussion.

**Comment by pyrello** [comment]
Some notes about using Blazy:
- It does integrate with responsive images.
- It appears that the aforementioned integration requires using a Blazy formatter, which means that it would become a dependency of every image field and require swapping all of those out.

**Comment by joewhitsitt** [comment]
Prioritizing for the homepage project with #1262 . Attempted to do SiteNow as well and things broke. The way we are rendering images programmatically is no longer ideal for all the things we want to do going forward.
