### ISSUE TITLE
Update Facilities alert templates

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6973]
# Story

As a Facilities site owner, I would like the order of the fields on the alert nodes and in the email template to match the order we provide.

# Additional Info

They should be sending over the order of fields. https://github.com/uiowa/uiowa/issues/6973#issuecomment-1749295647

They said they would prefer removing the sidebar on alert nodes and just listing the information in the order they provided.

https://github.com/uiowa/uiowa/issues/6880#issuecomment-1749192065

# Proposed solution

- Update alert node design to remove sidebar and list in order they provided
    - Is this custom to Facilities or are we updating default?
- Update Dispatch email template so fields output in the order they provided

**Comment by briand44** [comment]
> Here’s the order of alert items for the email and the webpage:
> 
> Title as you currently have it and then...
> 
> Closure Category:
> Date:
> Building:
> Location:
> Traffic Control:
> Traffic Control Plan:
> Accessible Route:
> Alternative Route:
> Affected Bus Routes:
> Reason for Closure:
> Project Number:
>  
> And then the closer : You can view a list.....
>  
> Thanks!

**Comment by briand44** [comment]
I reached out to Facilities to get clarity on if we should be outputting the sidebar first on mobile view and if the category should then be included in the sidebar so it appears first.
https://facilities.prod.drupal.uiowa.edu/dental-science-building-and-carver-hawkeye-arena-steamcondensate-and-forced-sewer

**Comment by briand44** [comment]
They determined they would prefer to remove the sidebar.

**Comment by joewhitsitt** [comment]
A note about links in email templates. While showing my screen, some links were print styled (url in brackets) in Outlook Web. I am seeing that in other emails (e.g. oneit) so I think we can ignore that as something we need to fix.

**Comment by briand44** [comment]
Grooming conversation... Lets remove sidebar for default alerts and cleanup and we can revisit if needed by ITS or others in the future.

**Comment by joewhitsitt** [comment]
>Update Dispatch email template so fields output in the order they provided

This is done.


```
<p>The following Access &amp; Construction Alert has been issued from Facilities Management at the University of Iowa. Construction activity may impact road, sidewalk, parking lot, elevator or building entrance access. Please review the alert below for specific details. Contact Facilities Management at 319-335-5500 if you require additional information.</p>
<h2>${AlertSubject}</h2>
<p>&lt;/#if&gt; &lt;#if AlertCategory??&gt;</p>
<h3>Closure category</h3>
<div>${AlertCategory}</div>
<p>&lt;#if AlertDate??&gt;</p>
<h3>Date</h3>
<div>${AlertDate}</div>
<p>&lt;/#if&gt; &lt;#if AlertBuilding??&gt;</p>
<h3>Building</h3>
<div>${AlertBuilding}</div>
<p>&lt;/#if&gt; &lt;#if AlertBuildingsLocations??&gt;</p>
<h3>Location</h3>
<div>${AlertBuildingsLocations}</div>
<p>&lt;/#if&gt; &lt;#if AlertTrafficControl??&gt;</p>
<h3>Traffic control</h3>
<div>${AlertTrafficControl}</div>
<p>&lt;/#if&gt; &lt;#if AlertTrafficControlPlan??&gt;</p>
<h3>Traffic control plan</h3>
<div>${AlertTrafficControlPlan}</div>
<p>&lt;/#if&gt; &lt;#if AlertAccessibleRoute??&gt;</p>
<h3>Accessible route</h3>
<div>${AlertAccessibleRoute}</div>
<p>&lt;/#if&gt; &lt;#if AlertAlternateRoute??&gt;</p>
<h3>Alternative route</h3>
<div>${AlertAlternateRoute}</div>
<p>&lt;/#if&gt; &lt;#if AlertAffectedBusRoutes??&gt;</p>
<h3>Affected bus routes</h3>
<div>${AlertAffectedBusRoutes}</div>
<p>&lt;/#if&gt; &lt;#if Body??&gt;</p>
<h3>Reason and details for closure:</h3>
<div>${Body}</div>
<p>&lt;/#if&gt; &lt;#if AlertProjectNumber??&gt;</p>
<h3>Project number</h3>
<div>${AlertProjectNumber}</div>
<p>&lt;/#if&gt;</p>
<p>You can view <a href="https://facilities.uiowa.edu/alerts/">a list</a> or <a href="https://maps.facilities.uiowa.edu/closures/">an interactive map</a> of current UI Access &amp; Construction alerts on the Facilities Management website. If you do not wish to continue receiving these automatic e-mail notices and are not a Building Coordinator, please #unsubscriptionlink#.</p>
```

**Comment by joewhitsitt** [comment]
>Lets remove sidebar for default alerts and cleanup and we can revisit if needed by ITS or others in the future.

@briand44 the default and facilities are completely split from each other for this. Should I proceed to reset default to a one-column template or just update the facilities version?

**Comment by briand44** [comment]
I'm fine with updating just the Facilities version but we determined this path as a team in grooming so maybe start there and bring up at EOD to see if the rest of the team is on board with this approach?

**Comment by briand44** [comment]
Team seemed ok with just making the change for Facilities.

**Comment by joewhitsitt** [comment]
Oops. https://github.com/uiowa/uiowa/pull/7013 resolves this issue.
