### ISSUE TITLE
Icon Library Integration

### ISSUE THREAD

**Issue by ethan-fry** [uiowa/uiowa#6978]
**Story**

As an site author I would like to be able to take advantage of the uiowa icon library without having to download from the icon library then upload to my site.

<details><summary>UIHC.org has taken advantage of implementing the icon library through a taxonomy and an icon library picker:</summary>
<p>

![Image](https://github.com/uiowa/uiowa/assets/54082244/7c8fc7a9-01ea-4cd9-b305-6c6003885810)

</p>
</details> 

<details><summary>UIHC.org has implemented the taxonomy picker in multiple content elements as seen below:</summary>
<p>

![Image](https://github.com/uiowa/uiowa/assets/54082244/32f18b47-cc33-4577-bcfa-b37da8901070)
![Image](https://github.com/uiowa/uiowa/assets/54082244/a3e957c4-33cb-48ea-ae2e-6a8debea4093)

</p>
</details> 

```[tasklist]
### Tasks
- [ ] https://github.com/uiowa/uiowa/issues/8211
- [ ] https://github.com/uiowa/uiowa/issues/8212
```

**Comment by maxwell-freund** [comment]
To add to this, as a site admin on uihc.org I have found icons I did not know would be what I wanted to use before, because they were added to our picker. So it has given me a lot more access and opportunity to leverage visuals when I lack a photo.

I also have appreciated that since this is systematized via a taxonomy and not manual upload of images, I have 0 risk of file duplication in our admin (forgetting I uploaded an icon before and uploading it again), and can be assured that the dev team has coded the experience (banner, icon card, icon list) to look good and resize well, using the SVG version of the icon.

It has been a frequently used feature by our site admins on uihc.org on a myriad of components. Some page examples:

https://uihc.org/your-visit
https://uihc.org/services/cochlear-implant
https://uihc.org/appointment

**Comment by joewhitsitt** [comment]
Capturing some detail from https://github.com/uiowa/uiowa/issues/2119 and closing in favor of this one:

>Consider remote media implementation so they can be used similar to images on the site and that Brand team and update the icons and have them deploy to all sites.

>https://www.drupal.org/project/remote_stream_wrapper or https://www.drupal.org/project/media_entity_remote_image potentially

>With the recent work to get fontawesome working with menu links it might be fairly easy if the icons are available to reference in the same json format that iconify uses. This would be different than a media reference approach however.

>https://github.com/iconify/icon-sets/blob/master/json/fa6-solid.json

>https://github.com/uiowa/uiowa/pull/6752#issuecomment-1691854236

**Comment by ethan-fry** [comment]
@briand44 

Here are two documents one outlines how we set up the icons select and the other is the main component's we have that use icons on UIHC.

[Icon Card Paragraph.docx](https://github.com/user-attachments/files/16944864/Icon.Card.Paragraph.docx)
[UIHC Icon Components.docx](https://github.com/user-attachments/files/16944882/UIHC.Icon.Components.docx)

**Comment by bspeare** [comment]
@ethan-fry are you also able to find out how/where you are using the icons on your SiteNow websites?

**Comment by maxwell-freund** [comment]
@bspeare I have talked to some of our web editor team about use of icons.

Candidly the pickup on SiteNow V3 migrated sites has been limited. We did not exercise any mass upload of icons into their libraries, and so it has been individual icons uploaded as images, and added to pages.

By in large the use has either been as stand alone visual markers such as:
https://ogps.medicine.uiowa.edu/general-guidelines
or
Added as an image in an image card such as this:
https://medicinepsychiatry.prod.drupal.uiowa.edu/education/fellowship-programs/inspire-fellowship
or
https://medicinepsychiatry.prod.drupal.uiowa.edu/education/fellowship-programs

If I can stand on a soapbox for a moment here, i think both of these psychiatry use cases show the limitation of this approach in two edges. One visualizes the icon in a nice, tight circle, but by the nature of it being sized as an image, we cut off the bottom left corner of the icon. While the other lets the icon fill the full frame of the column space, but that results in a very large image. Which to me, is not the ideal way to represent the icons.

We do have examples of yet-to-migrate D7 CCOM sites using icons through our icon-based components. 

Some examples:
https://medicine.uiowa.edu/internalmedicine/about-us/why-iowa
https://medicine.uiowa.edu/anesthesia/patient-care/locations/ambulatory-surgery-center
https://medicine.uiowa.edu/anesthesia/patient-care/locations/main-operating-rooms

And then I believe in an earlier comment from @ethan-fry he shared a number of UIHC.ORG icon-based components that our teams use with significant frequency.

Please let me know if that helps answer your question, happy to expand further in any area.

**Comment by bspeare** [comment]
Thanks for the examples @maxwell-freund! I agree with your soapbox points.  If we integrated the icons into the card component, for example, we would definitely want to ensure that they are rendered at fixed smaller size without being cropped.

**Comment by GaryRidgway** [comment]
Grooming...
- Integrate into one component. Make them available in a single component, you can choose media or icon, etc. Want to make sure that we can control things within one component.
- We do not need to do hosting right now.
- We want to upload a version of the icons to the codebase and have a component just use those icons.
- Do we want a static process where we copy over the svgs from brand
- is svg going to be accessible?
    - do the SVGs already have alt text?
    - No. they do not.
- That component can then be added to whatever we want to add icons to parent components.


Slicing
- How are we making these available to sitenow? **Large**
    - Static job?
    - Copy paste?
    - Remote hosting?
    **Proposed solution**:
- Implement previously gotten images into a single component  **Large**
    - Make an icon component that can be consumed by a card?
    - Card is the parent block that could use the icon component?
    **Proposed solution**:
