### ISSUE TITLE
Upgrade to Drush 12

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#6981]
Supposedly there is an EOL of November 2023...

https://www.drush.org/12.x/install/#drupal-compatibility

https://github.com/drush-ops/drush/releases/tag/12.0.0

**Comment by briand44** [comment]
Grooming conversation.... Checkout changelog. Update Drush locally to most recent version of Drush 12 using composer similar to other contrib type updates. Test scripts - Rick's user commands hosted on his github profile, site specific commands like Facilities Import, toggle Gtag, Classrooms import, migrate commands, etc. We also invoke drush throughout some of our BLT commands. We'll want to make sure those commands are still supported by Drush 12 and if any additional arguments/options need to be supplied. If all goes well, merge and deploy through regular processes. If not, we may need to update some drush commands.

**Comment by joewhitsitt** [comment]
also this drush/Commands/UiowaCommands.php and migrate related commands

**Comment by GaryRidgway** [comment]
It looks like I have to update Some other things for this including BLT.

Aggregator is the only contrib module that  got updated when we ran the dependency updates, [we should look over its release notes.](https://www.drupal.org/project/aggregator/releases/2.2.0)


<details><summary>SOME OTHER THINGS</summary>
<p>

```
- Upgrading symfony/yaml (v6.3.8 => v6.3.12): Extracting archive
- Upgrading symfony/twig-bridge (v6.3.8 => v6.3.12): Extracting archive
- Upgrading symfony/string (v6.3.11 => v6.3.12): Extracting archive
- Upgrading symfony/console (v6.3.11 => v6.3.12): Extracting archive
- Upgrading symfony/config (v6.3.2 => v6.4.0): Extracting archive
- Upgrading symfony/process (v6.3.11 => v6.3.12): Extracting archive
- Upgrading enlightn/security-checker (v1.10.0 => v1.11.0): Extracting archive
- Upgrading symfony/var-dumper (v6.3.11 => v6.3.12): Extracting archive
- Upgrading symfony/event-dispatcher (v6.3.11 => v6.3.12): Extracting archive
- Upgrading nikic/php-parser (v4.18.0 => v5.0.0): Extracting archive
- Upgrading psy/psysh (v0.11.22 => v0.12.0): Extracting archive
- Upgrading consolidation/annotated-command (4.9.1 => 4.9.2): Extracting archive
- Upgrading symfony/var-exporter (v6.3.11 => v6.3.12): Extracting archive
- Upgrading symfony/dependency-injection (v6.3.11 => v6.3.12): Extracting archive
- Upgrading chi-teck/drupal-code-generator (2.6.2 => 3.3.0): Extracting archive
- Upgrading drush/drush (11.6.0 => 12.4.3): Extracting archive
- Upgrading acquia/blt (13.7.3 => 13.7.4): Extracting archive
- Upgrading symfony/validator (v6.3.11 => v6.3.12): Extracting archive
- Upgrading symfony/serializer (v6.3.11 => v6.3.12): Extracting archive
- Upgrading symfony/routing (v6.3.11 => v6.3.12): Extracting archive
- Upgrading symfony/http-foundation (v6.3.11 => v6.3.12): Extracting archive
- Upgrading symfony/mime (v6.3.5 => v6.3.12): Extracting archive
- Upgrading symfony/error-handler (v6.3.5 => v6.3.12): Extracting archive
- Upgrading symfony/http-kernel (v6.3.11 => v6.3.12): Extracting archive
- Upgrading doctrine/deprecations (1.1.2 => 1.1.3): Extracting archive
- Upgrading phpunit/phpunit (9.6.15 => 9.6.16): Extracting archive
- Upgrading laminas/laminas-stdlib (3.18.0 => 3.19.0): Extracting archive
- Upgrading drupal/aggregator (2.1.4 => 2.2.0): Extracting archive
- Upgrading richardbporter/drush-users-commands (3.2.1 => 4.0.0): Extracting archive

```

</p>
</details> 

- [ ] Check changelog of drush from version on main to most recent version
- [x] Rick's user commands hosted on his github profile
- [ ] site specific commands like:   
    - [x] Facilities Import
    - [x] toggle Gtag
    - [x] Classrooms import
    - [x] migrate commands
    - [ ] etc
- [x] Check arguments of migrate or custom drush commands that contain `object &$context` because the argument type may have changed to `array`  
    - [x] P2LB command needs testing, as it is the only other function with `&$context` explicitly declared as an object.
- [ ] some of our BLT commands.  
    - [x] BLT frontend
    - [x] `uicore-crm` no resultes on default, mappings on [connect.studentlife.uiowa.edu](http://connect.studentlife.uiowa.edu/)
    - [x] `blt dsa` / `blt ds`
    - [ ] Any others?
- [x] [Check aggregator](https://git.drupalcode.org/project/aggregator/-/compare/2.1.4...2.2.0?from_project_id=82541&straight=false)

**Comment by pyrello** [comment]
It feels like we might be over-testing this a little bit.

> Existing commands should run without modification unless you are doing something exotic.
- https://github.com/drush-ops/drush/releases/tag/12.0.0

To get this to done, I think we only need to focus on mission critical scripts. Anything else, if we find a bug we can fix it. I don't think we need to have complete certainty that nothing is broken to make this change.

**Comment by GaryRidgway** [comment]
> It feels like we might be over-testing this a little bit.
> 
> > Existing commands should run without modification unless you are doing something exotic.
> 
> * https://github.com/drush-ops/drush/releases/tag/12.0.0
> 
> To get this to done, I think we only need to focus on mission critical scripts. Anything else, if we find a bug we can fix it. I don't think we need to have complete certainty that nothing is broken to make this change.

If this is the case, I think this can be moved to review. I have been using core functionality drush commands for a while on this branch and nothing has worked incorrectly
