### ISSUE TITLE
Turn on ITS site split in prod?

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6998]

**Comment by cory-skeers** [comment]
I believe the full process should be 

```
ddev drush @its.prod config:import --source ../config/sites/its.uiowa.edu --partial -y && ddev drush @its.prod cim -y && ddev drush @its.prod cr
```
The extra `cim` should take care of enabling `its_core`, which won't get enabled by enabling the partial alone.

**Comment by joewhitsitt** [comment]
Did you "just do it" @cory-skeers ?!

**Comment by cory-skeers** [comment]
> Did you "just do it" @cory-skeers ?!

I didn't, at least not yet. But was setting things up locally for demo, and those were (most of) the commands I ran to get it up and going, minus syncing and such.

**Comment by joewhitsitt** [comment]
This is done in PROD.

<img width="586" alt="Screenshot 2023-10-12 at 11 53 01 AM" src="https://github.com/uiowa/uiowa/assets/4663676/87237e3b-02e9-4c31-8e30-2f411b485ed8">

**Comment by briand44** [comment]
Thanks, I let the ITS folks know.
