### ISSUE TITLE
Remove vertical gap between columns on mobile

### ISSUE THREAD

**Issue by bewoldt** [uiowa/uiowa#7023]
# Story
As a webmaster I want to remove the vertical column space on mobile between to content areas within a section. I can remove the default column space in a section but that only applies to the desktop horizontal spacing.

**desktop view** (2 column section with default column spacing removed)
<img width="1273" alt="Screen Shot 2023-10-20 at 11 10 39 AM" src="https://github.com/uiowa/uiowa/assets/731952/11283d3f-860f-4949-a985-735d92b1f589">

**mobile view**
<img width="686" alt="Screen Shot 2023-10-20 at 11 11 29 AM" src="https://github.com/uiowa/uiowa/assets/731952/a3dc8a59-1249-4507-918f-386a1df7d874">

# Proposed solution

When selecting the option to remove default column spacing, you are also removing default vertical spacing between to content areas on mobile.

**Comment by bspeare** [comment]
@bewoldt can you share the link to this page?

**Comment by bewoldt** [comment]
> @bewoldt can you share the link to this page?

https://wellbeing.prod.drupal.uiowa.edu/diet-and-nutrition

**Comment by bspeare** [comment]
This will also help layouts like https://tippie.uiowa.edu/kira-price-story-undergraduate. 

Before:
<img width="587" alt="Screenshot 2023-10-24 at 11 31 55 AM" src="https://github.com/uiowa/uiowa/assets/1036433/81e7041c-c443-422f-89c3-616f6d34543c">


After:
<img width="465" alt="Screenshot 2023-10-24 at 11 31 36 AM" src="https://github.com/uiowa/uiowa/assets/1036433/87da8583-b7f6-46ca-8a5f-7d81b4f72776">
