### ISSUE TITLE
Facilities Artwork Content Type

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7026]
# Story

As a Facilities site owner, I would like our content editors to have the ability to create artwork content so that our users will eventually be able to browse a filterable gallery, see artwork on buildings and see works of art by a particular artist.

# Additional Info

Seems specific to this site.

**Content type create notes**
https://iowa.sharepoint.com/sites/drupal-developer-documentation/SitePages/Miscellaneous/Content%20type%20creation%20notes/Content%20type%20creation%20notes.aspx

They would like to keep their same url pattern otherwise they will need to update the urls on their maps https://uiadmin.maps.arcgis.com/apps/webappviewer/index.html?id=c4bcf56619a241deb3e8f490ce1b9ed6. Their current pattern is `art-on-campus/artwork/[node:title]`

# Question

Should https://github.com/uiowa/uiowa/issues/7028 be done as part of this or separate slice?

# Proposed Solution

**Comment by pyrello** [comment]
> _"It looks like someone got tired of working on this site and never did the part where they made the artwork page look good"_
>
> Me from yesterday's meeting with regard to https://www.facilities.uiowa.edu/art-on-campus/artwork/2-3-1-1

**Comment by joewhitsitt** [comment]
Grooming convo: Team believed we would be able to establish the content type and add the fields/design from https://github.com/uiowa/uiowa/issues/7028 at the same time. Keeping the date field as an integer, none of the fields give much pause.
