### ISSUE TITLE
Audit sites on the list of suspected D7 sites needing customization

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#7027]
# Motivation

To better understand what work is yet to be done to migrate our custom D7 sites. We have a list of sites we suspect will need customizations. While we may need to do more work to figure out if there are other sites that belong on that list, there is no reason we can't start the process of auditing the sites that we are already aware of.

# Proposed solution

For each site:

- Check in with Brian to see if there is any important historical information or work he has already done.
- Review any custom features that were added
- Determine whether any of those features can be handled in the current standard SiteNow platform
- Document any features that cannot currently be handled by the current standard SiteNow platform

**Comment by briand44** [comment]
FYI, chatted with our partners at UIHC and it sounds like chsciowa.org may not be a custom site we need to worry about moving to v3. I have not added a comment in the spreadsheet in relation to this yet.

**Comment by pyrello** [comment]
I added a bullet point to check with Brian since he may have already done some of this work or has important historical context.

**Comment by joewhitsitt** [comment]
Grooming convo: Joe to provide that whittled down list to start with (approx 30-35 sites). In terms of documenting, starting with the issue sounds good and if it gets unruly, move it to another location that can easily be referenced.

**Comment by joewhitsitt** [comment]
Here is the list I came up with earlier from the `updated all` sheet of the Drupal 7 Sites spreadsheet (from 10/17/2023).

Filter criteria: type !== 'standard', custom development !== 'no' , is V2 !== 'yes', v3 site launched !== 'yes', d7 site deprovisioned !== 'yes'

<table border="0">
 <tr>
    <td><b style="font-size:30px">Site</b></td>
    <td><b style="font-size:30px">Notes</b></td>
 </tr>
 <tr>
    <td>  cheec.uiowa.edu</td>
    <td>
<p><strong>Content types/features that don't match up with SiteNow:</strong></p>
<ul>
<li>Event content type</li>
<li>News content type</li>
<li>Research content type</li>
<li>Research Project content type</li>
<li>Research Publication content type</li>
<li>Research search page <a href="https://cheec.uiowa.edu/research/study-archive">here.</a></li>
</ul>

<p>V3 site provisioned at  <a href="https://cheec.prod.drupal.uiowa.edu/">https://cheec.prod.drupal.uiowa.edu/</a></p>
    </td>
 </tr>
 <tr>
    <td>clas.uiowa.edu</td>
    <td>

<p><strong>Content types/features that don't match up with SiteNow:</strong></p>
<ul>
<li>Publication content type</li>
<li><a href="https://clas.uiowa.edu/deos/mailing/archive">DEO Mailing archive</a> and related content types</li>
</ul>
<p>V3 site provisioned at <a href="https://clas.prod.drupal.uiowa.edu">clas.prod.drupal.uiowa.edu</a></p>
    </td>
 </tr>
 <tr>
    <td>
<a href="https://arts.uiowa.edu/">https://arts.uiowa.edu</a>
</td>
    <td>
<ul>
<li>V3 site provisioned at  <a href="https://arts.prod.drupal.uiowa.edu">arts.prod.drupal.uiowa.edu</a>. </li>
<li>There was some discussion in June 2023 about having them switch to using events.uiowa.edu instead view the card at <a href="https://github.com/orgs/uiowa/projects/20/views/1?pane=issue&itemId=31412246">https://github.com/orgs/uiowa/projects/20/views/1?pane=issue&itemId=31412246</a>.  </li></ul>
    </td>
 </tr>
 <tr>
    <td><a href="https://catering.uiowa.edu/">catering.uiowa.edu</a></td>
    <td>
<p><strong>Content types/features that don't match up with SiteNow:</strong></p>
<ul>
<li>Some custom commerce integration</li>
<li>Product content type</li>
<li>Menus and Menu item content types</li>
<li>Venue content type</li>
</ul>
<p>V3 site provisioned at <a href="https://catering.prod.drupal.uiowa.edu/">https://catering.prod.drupal.uiowa.edu/</a></p>
    </td>
 </tr>
 <tr>
    <td><a href="https://chsciowa.org/">chsciowa.org</a></td>
    <td>
<a href="https://github.com/uiowa/uiowa/issues/7027#issuecomment-1783160795">Notes</a>
    </td>
 </tr>
 <tr>
    <td><a href="https://commencement.uiowa.edu/">https://commencement.uiowa.edu</a></td>
    <td>
<p><strong>Content types/features that don't match up with SiteNow:</strong></p>
<ul>
<li>Event content type</li>
<li>Event search <a href="https://commencement.uiowa.edu/ceremonies">page</a></li>
</li>
</ul>


<p>V3 site provisioned at <a href="https://commencement.prod.drupal.uiowa.edu/">https://commencement.prod.drupal.uiowa.edu/</a>.</p>
    </td>
 </tr>
 <tr>
    <td>https://content.uiowa.edu/</td>
    <td>
AIS has agreed to work on the next version and it won't be in Drupal.
    </td>
 </tr>
 <tr>
    <td><a href="https://ctsdmc.uiowa.edu">ctsdmc.uiowa.edu</a></td>
    <td>
<p><strong>Content types/features that don't match up with SiteNow:</strong></p>
<ul>
<li>Project content type<ul><li>Project search page</li></ul></li>

<li>Publication content type<ul><li>Publication search page</li></ul></li>
</ul>
    </td>
 </tr>
 <tr>
    <td><a href="https://dining.uiowa.edu/">dining.uiowa.edu</a></td>
    <td>
<p>V3 site provisioned at <a href="https://dining.prod.drupal.uiowa.edu/">https://dining.prod.drupal.uiowa.edu/</a></p>
    </td>
 </tr>
 <tr>
    <td>emergency.uiowa.edu</td>
    <td>
<p><strong>Content types/features that don't match up with SiteNow:</strong></p>
<ul>
<li>Hawk Alert content type</li>
<li>https://emergency.uiowa.edu/api/active.xml</li>
<li>https://emergency.uiowa.edu/api/active.json</li>
<li>Feeds importer from https://content.getrave.com/cap/uiowa/channel1</li>
<li>Hawk alert archive</li>

</ul> 
    </td>
 </tr>
 <tr>
    <td>
<a href="https"//fmb.fo.uiowa.edu">fmb.fo.uiowa.edu</a></td>
    <td>
<p><strong>Content types/features that don't match up with SiteNow:</strong></p>
<ul>
<li>Record Retention content type</li>
</ul>
    </td>
 </tr>
 <tr>
    <td>
<a href="https://fo.uiowa.edu">fo.uiowa.edu</a></td>
    <td>

<p><strong>Content types/features that don't match up with SiteNow:</strong></p>
<ul>
<li>Deparment/Unit content type for <a href="https://fo.uiowa.edu/departments-units">https://fo.uiowa.edu/departments-units</a></li>
</li>
</ul>


<p>V3 site provisioned at <a href="https://fo.prod.drupal.uiowa.edu/">https://fo.prod.drupal.uiowa.edu/</a></p>
    </td>
 </tr>
 <tr>
    <td>
<a href="https"//grantbulletin.research.uiowa.edu">grantbulletin.research.uiowa.edu</a></td>
    <td>
<p><strong>Content types/features that don't match up with SiteNow:</strong></p>
<ul>
<li>Opportunities content type <a href="https://github.com/uiowa/uiowa/issues/5124">Github issue</a>
</li>
</ul>
<p>Provisioned as V3 intranet site at <a href="https://researchgrantbulletin.prod.drupal.uiowa.edu/">https://researchgrantbulletin.prod.drupal.uiowa.edu/</a></p>
    </td>
 </tr>
 <tr>
    <td>
<a href="https"//hancher.uiowa.edu">hancher.uiowa.edu</a></td>
    <td>
<p><strong>Content types/features that don't match up with SiteNow:</strong></p>
<ul>
<li>Residency Event content type</li>
<li>Hancher Event content type</li>
<li>News item content type</li>
<li>Events search <a href="https://hancher.uiowa.edu/upcoming-events">page</a></li>
</ul> 
    </td>
 </tr>
 <tr>
    <td>

<a href="https://inrc.law.uiowa.edu">inrc.law.uiowa.edu</a></td>
    <td>

<p><strong>Content types/features that don't match up with SiteNow:</strong></p>
<ul>
<li>Association content type</li>
<li>Book content type</li>
<li>Consultant content type</li>
<li>Event content type</li>
<li>FAQ content type</li>
<li>Government agent content type</li>
<li>Grant content type</li>
<li>Nonprofit org content type</li>
<li>Publication content type</li>
<li>Grants faceted search <a href="https://inrc.law.uiowa.edu/iowa-grants-guide">page</a></li>
<li><a href="https://inrc.law.uiowa.edu/register-accountability">Register of accountability</a></li>
<li><a href="https://inrc.law.uiowa.edu/events#!events-map">Events map by county</a></li>
<li>This site has Discuss integration on Articles</li>  
<li>Ridiculously Responsive Social Share Buttons.</li>
</ul>
    </td>
 </tr>
 <tr>
    <td>

intranet.oneit.uiowa.edu</td>
    <td>

<p><strong>Content types/features that don't match up with SiteNow:</strong></p>
<ul>
<li>Discussion content type</li>
<li>Event content type</li>
<li>News content type</li>
<li>Categories sidebar filter for news</li>
<li>Project content type</li>
<li>Search pages for Projects, Events, Resources</li>
<li>Resource content type</li>
<li>Showcase content type</li>
</ul>
<p>Email notifications digest for news, events, projects.  There was project integration with Workflow that has stopped working and they are now manually adding projects.     They are evaluating SharePoint as a possible replacement. </p>
    </td>
 </tr>
 <tr>
    <td>
intranet.pharmacy.uiowa.edu</td>
    <td>
<p><strong>Content types/features that don't match up with SiteNow:</strong></p>
<ul>
<li>Discussion content type</li>
<li>Event content type</li>
<li>News content type</li>
<li>Funding Opportunity content type</li>
<li>Resource content type</li>
</ul>
    </td>
 </tr>
 <tr>
    <td>
iowareview.org</td>
    <td>

<p><strong>Content types/features that don't match up with SiteNow:</strong></p>
<ul>
<li>Artist content type</li>
<li>Blog post content type</li>
<li>From the issue content type</li>
<li>Hero item content type</li>
<li>Highlighted news content type</li>
<li>Issue content type</li>
<li>AddToAny Share buttons</li>
</ul>
    </td>
 </tr>
 <tr>
    <td>
its.uiowa.edu</td>
    <td>
V3 site provisioned at  <a href="https://its.prod.drupal.uiowa.edu">https://its.prod.drupal.uiowa.edu</a>
    </td>
 </tr>
 <tr>
    <td>
neuronext.org</td>
    <td>
<p><strong>Content types/features that don't match up with SiteNow:</strong></p>
<ul>
<li>Clinical site content type</li>
<li>FAQ content type</li>
<li>Organization content type</li>
<li>Project content type</li>
<li>Publication</li>
</ul>
    </td>
 </tr>
 <tr>
    <td>
opsmanual.uiowa.edu</td>
    <td>
<p><strong>Content types/features that don't match up with SiteNow:</strong></p>
<ul>
<li>Chapter content type</li>
<li>Division content type</li>
<li>Headings content type</li>
<li>Sub-chapter content type</li>
</ul>
    </td>
 </tr>
 <tr>
    <td>
outreach.uiowa.edu</td>
    <td>
Redirects to <a href="https://engagement.uiowa.edu/">https://engagement.uiowa.edu</a>
Still using custom map solution at <a href="https://outreach.uiowa.edu/map/county">https://outreach.uiowa.edu/map/county</a>
    </td>
 </tr>
 <tr>
    <td>
portalpages.research.uiowa.edu</td>
    <td>
Looks to be mainly basic pages.  What else is on this site?
    </td>
 </tr>
 <tr>
    <td>

registrar.uiowa.edu</td>
    <td>
<p><strong>Content types/features that don't match up with SiteNow:</strong></p>
<ul>
<li>Final exam schedule content type</li>
<li>FAQ content type</li>
<li>Policy content type</li>
<li>Report content type</li>
<li>University Classrooms content type</li>
</ul>

<p>V3 site provisioned at <a href="https://registrar.prod.drupal.uiowa.edu/">https://registrar.prod.drupal.uiowa.edu/</a> with a lot of custom development needs at <a href="https://github.com/uiowa/uiowa/issues?q=is%3Aissue+is%3Aopen+registrar">https://github.com/uiowa/uiowa/issues?q=is%3Aissue+is%3Aopen+registrar</a></p>
    </td>
 </tr>
 <tr>
    <td>
report.hancher.uiowa.edu</td>
    <td>
<p><strong>Content types/features that don't match up with SiteNow:</strong></p>
<ul>
<li>Parrallax scrolling</li>
<li>Background image sections </li>
</ul>
    </td>
 </tr>
 <tr>
    <td>
shl.uiowa.edu</td>
    <td>
<p>V3 site provisioned at <a href="https://shl.prod.drupal.uiowa.edu/">https://shl.prod.drupal.uiowa.edu/</a> with a lot of possible iframe embeds</p>
    </td>
 </tr>
 <tr>
    <td>
signage.uihealthcare.org</td>
    <td>
<p><strong>Content types/features that don't match up with SiteNow:</strong></p>
<ul>
<li>Organic groups</li>
<li>Signage group content type </li>
<li>Signage slide content type </li>
<li>Sign content type</li>
<li>Promotional image content type</li>
<li>Weather widgets</li>
<li>And much more...</li>
</ul>
    </td>
 </tr>
 <tr>
    <td>
signage.uiowa.edu</td>
    <td>
<p><strong>Content types/features that don't match up with SiteNow:</strong></p>
<ul>
<li>Organic groups</li>
<li>Signage group content type </li>
<li>Signage slide content type </li>
<li>Sign content type</li>
<li>Promotional image content type</li>
<li>Weather widgets</li>
<li>And much more...</li>
</ul>
    </td>
 </tr>
 <tr>
    <td>
stories.uiowa.edu</td>
    <td>
<p><strong>Content types/features that don't match up with SiteNow:</strong></p>
<ul>
<li>Story content type with lots of paragraph options</li>
</ul>
Worth revisiting <a href="https://github.com/uiowa/uiowa/issues/5426">https://github.com/uiowa/uiowa/issues/5426</a> and <a href="https://github.com/uiowa/uids/labels/stories.uiowa.edu">https://github.com/uiowa/uids/labels/stories.uiowa.edu</a>
    </td>
 </tr>
 <tr>
    <td>
teach.its.uiowa.edu</td>
    <td>
<p><strong>Content types/features that don't match up with SiteNow:</strong></p>
<ul>
<li>Blog content type</li>
<li>Event content type</li>
<li>External resource content type</li>
<li>File resource content type</li>
<li>FAQ content type</li>
<li>Guide content type</li>
<li>Hub content type</li>
<li>News content type</li>
<li>Publication content type</li>
<li>Technology tool content type</li>
</ul>

<p>V3 site provisioned at  <a href="https://itsteach.prod.drupal.uiowa.edu/">https://itsteach.prod.drupal.uiowa.edu/</a>.  They have some outstanding Resource and search needs like <a href="https://github.com/uiowa/uiowa/issues/6578">https://github.com/uiowa/uiowa/issues/6578</a>. </p>
    </td>
 </tr>
 <tr>
    <td>
<a href="https://ukchoralcomposers.lib.uiowa.edu/">ukchoralcomposers.lib.uiowa.edu</a></td>
    <td>
<p><strong>Content types/features that don't match up with SiteNow:</strong></p>

<ul>
<li>Album content type</li>
<li>Essay content type</li>
<li>Media content type</li>
<li>Work content type</li>
<li>Text content type</li>
<li>Lots of faceted search pages</li>
<li>Person content type
<ul>
<li>Author, Composer, Poet, types</li>
<li>End date field</li>
<li>City field</li>
</ul>
</li>
</ul>
 </td>
 
 </tr>
 <tr>
    <td>
www.facilities.uiowa.edu</td>
    <td>
<p>V3 site provisioned at  <a href="facilities.prod.drupal.uiowa.edu">facilities.prod.drupal.uiowa.edu</a>
    </td>
 </tr>
 <tr>
    <td>
<a href="https://instructional-resources.physics.uiowa.edu">https://instructional-resources.physics.uiowa.edu</a></td>
    <td>
<p><strong>Content types/features that don't match up with SiteNow:</strong></p>
<ul>
<li>Demo content type</li>
</ul>

<p>Heavy usage of hierarchical select taxonomy to create pages like <a href="https://instructional-resources.physics.uiowa.edu/demos/mechanic">https://instructional-resources.physics.uiowa.edu/demos/mechanics</a> of these "Demo" content types. </p>
    </td>
 </tr>
 <tr>
    <td>
iwp.uiowa.edu</td>
    <td>
<p>V3 site provisioned at <a href="https://iwp.prod.drupal.uiowa.edu/">https://iwp.prod.drupal.uiowa.edu/</a></p>
    </td>
 </tr>
 <tr>
    <td>
iwp.uiowa.edu/whitmanweb</td>
    <td>
<p>V3 site provisioned at <a href="https://whitmanweb.iwp.uiowa.edu/">https://whitmanweb.iwp.uiowa.edu/</a></p>
    </td>
 </tr>
</table>



































33 sites after removing chsciowa and content hub. 32 if you consider the signage functionality to be roughly the same for signage and healthcare signage.

**Comment by bspeare** [comment]
Moved https://github.com/uiowa/uiowa/issues/7027#issuecomment-1800098628 to https://iowa-my.sharepoint.com/:x:/r/personal/bspeare_uiowa_edu/Documents/D7%20Custom%20Sites.xlsx?d=w3acd3082337447a0937d7d3eba5621e1&csf=1&web=1&e=A1KVo8 and I'm going to start looking at the overlapping fields on the shared content types today based on EoD feedback yesterday.

**Comment by bspeare** [comment]
I added content type comparison tabs on https://github.com/uiowa/uiowa/issues/7027#issuecomment-1812689295 for Resource, FAQ, Blog, Project, News, Publications, and Event content types.

**Comment by bspeare** [comment]
Here's my initial summary from https://github.com/uiowa/uiowa/issues/7027#issuecomment-1812689295.  I'll be updating this with edits throughout the day.

**_Overall, a number of sites would benefit from using shared Project (IISC), Local Events, Resource, and Publication (https://iro.uiowa.edu/esploro/) content types._** 


## Likely not much development 

- ﻿﻿iwp.uiowa.edu - [V3 Site](https://iwp.prod.drupal.uiowa.edu/)
- iwp.uiowa.edu/whitmanweb - [V3 Site](https://whitmanweb.iwp.uiowa.edu/)
- shl.uiowa.edu - [V3 Site](https://shl.prod.drupal.uiowa.edu/)
- fo.uiowa.edu - [V3 Site](https://fo.prod.drupal.uiowa.edu/)
- dining.uiowa.edu - [V3 Site](https://dining.prod.drupal.uiowa.edu/)

## Some custom development 

- teach.its.uiowa.edu - [V3 Site](https://itsteach.prod.drupal.uiowa.edu/)
- grantbulletin.research.uiowa.edu - [V3 Site](https://researchgrantbulletin.prod.drupal.uiowa.edu/)
- commencement.uiowa.edu - [V3 Site](https://commencement.prod.drupal.uiowa.edu/)
- catering.uiowa.edu - [V3 Site](https://catering.prod.drupal.uiowa.edu/)
- clas.uiowa.edu - ﻿﻿[V3 Site](https://clas.prod.drupal.uiowa.edu/)
- cheec.uiowa.edu - [V3 Site](https://cheec.prod.drupal.uiowa.edu/)
- stories.uiowa.edu

## A lot of custom development 

- its.uiowa.edu - [V3 Site](https://its.prod.drupal.uiowa.edu)
- facilities.uiowa.edu - [V3 Site](https://facilities.prod.drupal.uiowa.edu)
- registrar.uiowa.edu - [V3 Site](https://registrar.prod.drupal.uiowa.edu/)
- emergency.uiowa.edu 
- iowareview.org 
- neuronext.org
- intranet.oneit.uiowa.edu
- ctsdmc.uiowa.edu
- opsmanual.uiowa.edu


## Could just be a basic V3 site

- fmb.fo.uiowa.edu
- report.hancher.uiowa.edu
- hancher.uiowa.edu - They _might_ be able to use local events with a few additions. 
- intranet.pharmacy.uiowa.edu
- portalpages.research.uiowa.edu - This is currently a home page with a login button to another site. 
- Has structured content, but could be a basic V3 site with a lot of hard work
  - ﻿instructional-resources.physics.uiowa.edu

## Not moving to V3

- content.uiowa.edu
- [chsciowa.org](https://chsciowa.org/)

## Unknown future

- signage.uiowa.edu
- signage.healthcare.org

## Need more information about future plans

- arts.uiowa.edu - [V3 site](https://arts.prod.drupal.uiowa.edu)
- outreach.uiowa.edu/map/county

**Comment by joewhitsitt** [comment]
Thanks for your work on this @bspeare. I think it is good to have a set of non-biased eyes on some of these sites.

Just one note as it stuck out to me: outreach.uiowa.edu/map/county was supposed to stay around because it was still being referenced by higher-ups but AFAIK, the stats haven't been updated for like three years.

I am also curious to hear about how the oneit intranet survey went. With the project workflow integration no longer being considered for v3 and more IT activity moving to Teams, are there still custom features to be built here?

**Comment by briand44** [comment]
>I am also curious to hear about how the oneit intranet survey went.

me too.

>With the project workflow integration no longer being considered for v3 and more IT activity moving to Teams, are there still custom features to be built here?

The big thing here that they will want to keep is the messaging and notifications stuff. Folks have the ability to subscribe to notifications about projects, news, events, discussions. They can also subscribe to a digest and configure the send internal, determine if they get notifications about their own posts, subscribe to specific taxonomy terms, etc.

**Comment by joewhitsitt** [comment]
Yeah I didn't know how much of that could just be moved to Teams based on the results of the survey. I guess wondering if they still need a Drupal based intranet at all with that workflow integration no longer in the mix.

**Comment by briand44** [comment]
@bspeare I notices opsmanual.uiowa.edu isn't represented in https://github.com/uiowa/uiowa/issues/7027#issuecomment-1814678821. Was that by design or just happened to miss that?

**Comment by bspeare** [comment]
@briand44 thanks, I just added it in!

**Comment by pyrello** [comment]
You may have already heard me make comments to this effect already. This report has me spooked and I think we need to start talking about what options we have to figure out a path through this. Here is my thinking: 

Currently, our best idea of when we will no longer be able to support D7 sites is October 2024 when Acquia's free PHP 7.4 EOL extension ends. Maybe they will offer extended support, but they are being cagey about the details at this point, so I'm not sure we can count on it.

There are 9 sites in the *A lot of custom development* list. For the sake of argument, let's assume that we are far enough along in Facilities to not have to worry about it, so let's say we have 8 sites that need major customizations. We have roughly 45 sprints left until the EOL deadline, but let's use 44 for cleaner numbers. That means we have approximately *5.5 sprints per site* to do all that customization work. Thinking about how long it has taken us to get through some previous custom sites, that does not seem doable. And that is not even considering the rest of the sites that need customization or all the sites that don't need customization, but still need to be provisioned and migrated.

We may need to adopt a different stance with customers about what features we can build now versus later. Already having a feature may no longer be a good enough reason to commit to building it before launch anymore. We may need to have some difficult conversations about the value of certain features. I believe there is a way through this, but it is going to require us to be creative and open minded.

**Comment by pyrello** [comment]
Part of the issue I think we are going to run into is that our recent velocity is too slow to get everything done. As part of being creative and open minded, here are my thoughts about what slows us down:
- Thin slices: Thin slices allow us to prioritize for not carrying WIP. It allows us to have more confidence that we are going to get the work to done in a single slice. However, small slices inherently limits how fast we can get to done. I also suspect that the overall investment is greater when slicing thinner because there are certain sunk costs with doing any task.
- Detailed grooming and proposed solutions: Detailed plans prioritize for the ability of any team member to more easily pick up the work. It also ensures that there is greater predictability about what a team member will produce as a result of picking up the work. However, it delays how quickly we can get into the work and start learning things. Sometimes we delay starting work until we know a lot of details about it and can feel confident about the solution.
- Iterating on mockups: Mockups are a good way to have a clear idea about what we are going to build and helps to ensure alignment with the customer about what they want. However, the process of getting and responding to feedback often slows the process down because we can't move forward until we get the feedback from customers and they are often not operating on our schedule.

**Comment by mjoneill** [comment]
Thin slices that don't deliver value  == slower.  

Thin slices that allow you to get something to done and in a potentially shippable state so you can move on == faster, lower risk.

Big slices == typically slower + riskier. 

The goal of thin isn't just "small".  It's small + valuable + appropriate risk. Small is a relative term, but usually is understood as something that's achievable in a sprint.  Small + deliverable also reduces waste.

Also a slice is a story (or sometimes bigger), not a task.

There are exceptions to everything.

**Comment by pyrello** [comment]
> Thin slices that allow you to get something to done and in a potentially shippable state so you can move on == faster.

I don't believe this is always true. I think that you can define a slice that delivers value that is small enough that it slows you down because you end up having many very small slices delivering very incremental value. I think we sometimes go out of our way to make slices thinner because it makes us feel more certain we can get them done. If they are very thin, we'll almost certainly get them to done. But I think there is a point of diminishing returns with making slices thinner and after that, you are just creating more work based on the administrative overhead (opening a PR, code review, merging, deployments) associated with accomplishing each slice.

**Comment by mjoneill** [comment]
Agree.

Size, value, risk.  

Thinner for the risk of "thin" alone gets you nothing useful if it's disconnected from risk and value.

**Comment by cory-skeers** [comment]
> > Thin slices that allow you to get something to done and in a potentially shippable state so you can move on == faster.
> 
> I don't believe this is always true. I think that you can define a slice that delivers value that is small enough that it slows you down because you end up having many very small slices delivering very incremental value. I think we sometimes go out of our way to make slices thinner because it makes us feel more certain we can get them done. If they are very thin, we'll almost certainly get them to done. But I think there is a point of diminishing returns with making slices thinner and after that, you are just creating more work based on the administrative overhead (opening a PR, code review, merging, deployments) associated with accomplishing each slice.

I've thought about this too, and I think there's a bit here where we could do better separating the concept of "slices" from the administrative (ie github) things, like issues and PRs. We gravitate toward slice = PR, and that makes sense a lot of times (merging the PR means literally providing that incremental value, and there is a cost for keeping a PR open for an extended period of time), but doesn't always need to be the case.

Dependency update PRs are a good example of where we've sometimes split the planning up into several slices of obvious (simple dependabot check/merge) and complicated (big module updates, or ones we're especially dependent on), and those slices get planned independently despite their overlaps in issues and open PRs.

> Thinner for the risk of "thin" alone gets you nothing useful if it's disconnected from risk and value.

Definitely. We could split a new content type into a vertical slice per field, where it gets added to the node, the form, and the display, and this would be a good example of multiple slices using a single PR, but that probably doesn't give us any added value. But if there's a field we need clarity on from the client, considering that a separate slice might be useful, and depending on when it gets clarified, maybe it's another slice that gets pulled into the existing PR.

^ Not the best example, but I like the spirit of being open-minded in how we define these types of things and work them into the administrative processes we use.

**Comment by joewhitsitt** [comment]
Going to miss the first part of the upcoming meeting, but IMO, the next step should be to jumpstart our communication plan. the first email essentially saying, "the EOL is for real this time. we looking into ways to still extend this deadline but this is the deadline for sites to be done with transition as of today so that we can safely retire the v1 service. we will doing another round of [inactive sites cleanup per our policy](https://sitenow.uiowa.edu/policies), but then reaching out to specific customers to start planning transitions. we may have tools to help aid in the transition. we will have specific milestone dates a bit later."

**Comment by briand44** [comment]
whitman web is planning on launching without custom development. That site can likely be removed from our list. I updated the "updated all" sheet of our D7 sites list but haven't updated any of the spreadsheets related to this issue.

We won't know until late January about iwp.uiowa.edu but they are hoping to not need any custom development.
