### ISSUE TITLE
artwork fields and design

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7028]
**Current Fields**

- [x] Title
- [x] Media - Currently allows unlimited images and video but looks like every piece of artwork has one image and some have one video. The images don't all have the same aspect ratio. (e.g. https://www.facilities.uiowa.edu/art-on-campus/artwork/diapason, https://www.facilities.uiowa.edu/art-on-campus/artwork/2-3-1-1). Teaser images all render the same size currently.
- [x] Date - Year only, integer text field currently
- [x] Artist - entity reference to a artist content type currently
- [x] Building - reference an existing Facilities building - currently select list
- [x] Location - long text text area restricted to plain text currently
- [x] Medium - term reference to tag type taxonomy, allows multiple, gallery allows filtering by medium.
- [x] Dimension - text field currently
- [x] Website - Requires title if there is a url currently but seems like they are always outputting "Artist's Website" in the title field. Single url field
- [x] Status - single value, required field. Currently select list with following options (Uninstalled, Active, Not Currently On View)
- [x] Description - body? long text text area using filtered html text format
- [ ] Notes - no longer needed
- [ ] Geo - no longer needed

**Design**

Current artwork node - https://www.facilities.uiowa.edu/art-on-campus/artwork/voyage
Mockups - #7042

**Comment by joewhitsitt** [comment]
Grooming convo: Discussed adding this to https://github.com/uiowa/uiowa/issues/7026

https://github.com/uiowa/uiowa/issues/7026#issuecomment-1799810299
