### ISSUE TITLE
Turn on Alert feature and add additional ITS specific fields

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7035]
# Story

As an ITS website owner, we would like to be able to create alert content so we can notify students, faculty and staff when there is a problem/change with a service so that they can be aware of any impacts to them.

# Additional Info

Help Desk full time staff and webmasters should have the ability to publish alerts.
Other site editors can create alerts but not publish so moderation is needed.

**Fields**

- Title - generated based on name of service + alert type
    - If additional title details is not empty use additional title details + alert type
    - need clarity on title when multiple services selected and no additional title details?
    - need clarity on if building populates title?
- Description (filtered html)
- Date - require start date, end date optional
- Closed - boolean, need some clarity on how this functions.
- Alert types - Outage, Service Announcement, Maintenance, Degredation of Service (Degredation of Service may have a name change)
- Ability to specify multiple services that are affected
- Ability to specify multiple buildings that are affected
    - Currently they manually maintain a building taxonomy - need clarity on if they continue with that or integrate with Facilities Buildings
- Additional title details

# Proposed Solution

- Enable alert feature
- Add moderation functionality
- Add additional ITS specific fields
- Roles and perms?

**Comment by briand44** [comment]
Grooming conversation... Let's hold off on buildings until we get more clarity on manual curated taxonomy vs Facilities integration. Replicate title functionality like they have now but we'll need to revisit once we have the building field figured out. Setup permissions similar to normal moderated content for now (editors can create, publishers/webmasters can publish). We'll need to revisit once we have a better understanding of roles across the site.

**Comment by cory-skeers** [comment]
> Alert types - Outage, Service Announcement, Maintenance, Degredation of Service (Degredation of Service may have a name change)

Is this separate from Alert Category that's available in the default Alert feature?

Category is set up as a multi-value reference to a taxonomy.

Type (as I've set it up) is a single-value, controlled select list with the above categories (handled by an allowed values function, so things like a rename of Degradation of Service or option additions can be handled as needed).

These make sense as separate in my mind, but the more I look at it, the less sure I am that these should be considered separate.

**Comment by joewhitsitt** [comment]
IMO, I had thought alert category could be used for ITS' alert type and that it would just be changed to a single value, we would populate the terms for ITS and not allow them access to the taxonomy so that we can do what is needed programmatically to display/handle them without them deleting terms, etc. That way we are using the field instead of just hiding it for ITS.
