### ISSUE TITLE
Further branding style changes are welcome for https://clrpass.its.uiowa.edu/ and pages within (requires vpn, authentication)

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7038]
https://clrpass.its.uiowa.edu/

Some of these pages weren't presented to us.

- Change heading color on main page and all text using (color: #FFCD00;) on white background.
- Wrap main content in a responsive container `mainContainer`
```
    margin: 0 auto;
    width: 100%;
    max-width: 1310px;
    padding-top: 3rem;
```
- Footer links were supposed to be changed to #ffcd00

**Comment by briand44** [comment]
inbox conversation seemed like we should just send off these recommendations.

**Comment by joewhitsitt** [comment]
Email was sent to Neil today. This is done.
