### ISSUE TITLE
Remove uiowa/block_content_template repo

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7041]

**Comment by joewhitsitt** [comment]
Can I get a bit of a history refresher on this? This module was brought local to the uiowa repo and so we don't need https://github.com/uiowa/block_content_template anymore?

**Comment by briand44** [comment]
I have no idea

**Comment by briand44** [comment]
Sean thinks this is functionality that got added in 10.2 core and we possibly don't need this module anymore but we should investigate first what we were using this for and that there are no regressions by removing it. Ben may have a good understanding of where we are using this.

**Comment by bspeare** [comment]
Since we are swapping out templates, this will need either a cache rebuild / scheduled deployment.   Do we need to include an update hook to clear the caches for the new files to register?

**Comment by joewhitsitt** [comment]
For this I would probably do both (update hook cache clear, scheduled deploy)
