### ISSUE TITLE
D7 sites to deprovision

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#7045]
- ~waldschmidt.lab.uiowa.edu on 701 -> went to v3~
- ~dai.lab.uiowa.edu on 701 DNS reclaimed~
- ~music.uiowa.edu on CLAS -> went to v3~
- ~theatre.uiowa.edu on CLAS -> went to v3~
- osc.uiowa.edu on 703 ? https://iowaweb.slack.com/archives/C0164FNN1PV/p1698253403354939
  - Wait a few weeks

**Comment by briand44** [comment]
Added reminder on its-web calendar to follow up on osc.prod.drupal.uiowa.edu in a month. Closing this issue as completed
