### ISSUE TITLE
Facilities Alerts Dispatch Template is broken

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#7048]
https://iowaweb.slack.com/archives/C0164FNN1PV/p1698162812124159

**Comment by bspeare** [comment]
It looks like the template is not broken, but as noted in previous alert issues, https://apps.its.uiowa.edu/dispatch/communications/1238605612 can break when it is resaved because the conditionals are turned into markup.   

The workaround is:

- Paste in template code from https://apps.its.uiowa.edu/dispatch/templates/1238199082
- Save the communication https://apps.its.uiowa.edu/dispatch/templates/1238199082

Hopefully, the communication will not need to be saved once this is finalized and this won't be a problem?

**Comment by joewhitsitt** [comment]
Thanks for looking into it.

Apologies for not being aware of that occurring each save. I had added my email back to the manual list.

**Comment by bspeare** [comment]
@joewhitsitt the saving hasn't stopped it working like this previously.   But now we know what to do when it errors out like that.

**Comment by bspeare** [comment]
I'm going to close this for now.
