### ISSUE TITLE
Dynamically embedded map on event node

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7052]
# Story

As an OnIowa site owner, I would like to have an embedded map appear on each event node dynamically so that a site visitor can interact with the map directly on the site and not have to link out to Google Maps.

# Additional Info

Trying to get clarity on using lat/long vs address.

Trying to understand if they have a preference on placement.

# Questions

How would we want to implement this? Google Maps? This would require an API key and potentially costs, correct? Other preferences on implementation?

# Proposed solution

**Comment by briand44** [comment]
> We used OpenStreetMap on the old site if that helps in the API/cost issues.
> Yes, we can/will still enter lat/lon for even locations… not everything will have a solid street address.
> I think sidebar would be ok for maps, we just want to make sure there is enough visible for a student to quickly glance at the location. I think sidebar is fine given it’s not too small.
> 
> -Scott

**Comment by bspeare** [comment]
Archival link: 

https://web.archive.org/web/20230105064319/https://oniowa.uiowa.edu/events/whats-it-all-about-recreational-services

Screenshot:

<img width="1452" alt="Screenshot 2023-12-01 at 9 28 22 AM" src="https://github.com/uiowa/uiowa/assets/1036433/a37a08f8-e3cb-4b7d-a300-b4be0c783b07">

**Comment by joewhitsitt** [comment]
To answer @briand44 's question about oniowa.prod, i think it can go away and we don't need to keep it around for this issue. Thanks for the screenshot @bspeare

Knowing they are okay with OSM, makes this much easier. We already have Leaflet and the event feature is using geofield to capture lat/long.

**Comment by joewhitsitt** [comment]
The leaflet library is already loaded via composer to provide the viewer necessary for Admissions/Pharmacy Counselors/Alumni maps. To date though, we have avoided loading a base map like google, mapbox, OSM.

https://www.drupal.org/project/geofield_map should be an easy way to configure and display a map based on the existing lat/long geofield.

**Comment by briand44** [comment]
Grooming conversation... Check geofield to see if there is some sort of formatter already included with the module. Potentially use geofield_map as mentioned ^^. Link to Google Maps is no longer needed and will be repurposed to show the map.

**Comment by e-marie-w** [comment]
Started on this today. Base geofield does not have a map formatter and I could not find a way to get geofield_map to work without using a Google Maps API key. It must be possible based on past issues, but the module in general seems very Google Maps focused. So, I tried the leaflet module instead. It works with the existing geofield data and uses OpenStreetMap. I think it's a good option just out of the box, all I've done so far is adjust the zoom level.

![Screenshot 2023-12-27 at 4 55 08 PM](https://github.com/uiowa/uiowa/assets/68179015/7159db62-12b2-430e-a368-a309cf5752bc)
