### ISSUE TITLE
CCOM Specific Analytics / Tag Manager

### ISSUE THREAD

**Issue by maxwell-freund** [uiowa/uiowa#7091]
As the development/web strategy team supporting CCOM websites, we want to adjust the tag manager (and analytic) environments used by our CCOM sites for compliance, and strategy reasons.

What this means is:
1. We would like to explore a way to exclude CCOM sites from including the global SiteNow Google Tag Manager.
2. We would like to include our own tag manager environment.
3. The tag manager we likely will be using (still in contracting) is Piwik Pro.

This is being done due to our legal and compliance team's interpretation of what Google products mean for health care properties. While CCOM sites are not direct patient care sites, they are adjacent and still a part of our single covered entity footprint.

For this reason we believe longterm, it is best to remove 3rd party Google products from the web experience.

The current "plan" is to leverage Piwik Pro, https://www.drupal.org/project/piwik_pro

# Proposed Solution

- Identify what is all in campus wide GTM.
- Stop campus wide GTM from running on CCOM sites
- Enable and allow admins to configure https://www.drupal.org/project/piwik_pro for CCOM sites
- Possibly turn off piwik in dev and stage environments (are we doing this with google analytics?)
- Turn off google analytics functionality for CCOM sites if easy - nice to have but not requirement
- Hopefully this can be controlled by the existing CCOM feature split

**Comment by maxwell-freund** [comment]
@mjoneill @briand44 @ethan-fry 

A first pass issue related to a CCOM specific tag manager (piwik pro) and removal of universal GTM container. for further grooming.

Thanks

**Comment by briand44** [comment]
Some notes from our meeting...

- clarified removal of universal GTM container rather than removal of GA deployed through universal GTM container
- clarified that snowplow is in universal GTM container and not deployed separately through brand bar
- would prefer disabling of Google Analytics module/functionality as well but this is low risk and more of a nice to have than a requirement
- GTM functionality can stay since that can only be enabled by an admin
- There isn't anything currently saying CSE or other Google needs to go

**Comment by briand44** [comment]
A couple questions...

Who would have the ability to configure the piwik settings? Would that just be admins (developers) or should webmasters have the ability to configure these settings?

Also, if there are certain default values that you would want set that differ from the module defaults, that could be good to know as well.

**Comment by maxwell-freund** [comment]
@briand44 I think we will be controlling the Piwik instance at the "global" level, and not at an individual site author level.
And since our in-house content editors (dan, nola, ben) are given the same admin level as a site author, it makes sense then to keep this as a developer only task, and likely would become a part of our site spinup checklist.

As far as default values we want to set that differ from the module defaults, I have not done enough research on the Piwik module to have an opinion settings. Is there a ReadMe that you have in hand that outlines these settings?

I might need some time with it, and want our agency partner who is more knowledgable about Piwik to weigh in.

**Comment by briand44** [comment]
Thanks Max. You can see some settings from the screenshot on the project page https://www.drupal.org/files/images/Piwik%20Admin%20Section%20Screenshot.png but not all of them. As long as someone from your team is available to help or to answer questions when this work is in progress, it's probably not that important to identify all of the defaults ahead of time.

**Comment by joewhitsitt** [comment]
The current global GTM implementation is fairly basic:

https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/uiowa_core/uiowa_core.module#L631-L643

Loads a library/plain JS in PROD for all sites (uiowa_core is enabled on all sites). It is separate from the google tag manager module + drush toggle stuff. Early on we found that the two coexisted just fine together.

Google Tag Manager module is on for all sites but does "fire" without the drush toggle.

This can be adapted to look for a split or another module that is enabled before attaching or depending on when the feature split module fires, can unset this library before things kick in.

**Comment by cory-skeers** [comment]
Current inventory of what is tied to the global GTM container:
<img width="557" alt="image" src="https://github.com/uiowa/uiowa/assets/49074566/32e0c6fd-bd44-4386-ae82-850a18b3cefa">

On the plus side, removing it also cleans up a lot of the GA outside of having the GA module enabled.
It also removes snowplow, which I think was expected.

Two parts I hadn't thought of that are also added through this: Siteimprove and OneTrust. We probably want to make sure these (especially OneTrust) are accounted for elsewhere for CCOM sites.

**Comment by maxwell-freund** [comment]
@cory-skeers thanks for the screenshot. The one item that concerns me being removed is SiteImprove. What does this site improve code do for a CCOM site?

Is it what adds that little site improve overlay when logged in?

**Comment by cory-skeers** [comment]
> @cory-skeers thanks for the screenshot. The one item that concerns me being removed is SiteImprove. What does this site improve code do for a CCOM site?
> 
> Is it what adds that little site improve overlay when logged in?

The overlay should be added separately form a siteimprove drupal module and be unaffected by this.

I believe it handles tracking for any of the analytics/insights in Siteimprove, and should be separate from the traditional accessibility/quality scans. I'm not sure that the same js doesn't have some overlap between the two though, and would need to look into that a bit more.

**Comment by cory-skeers** [comment]
> > @cory-skeers thanks for the screenshot. The one item that concerns me being removed is SiteImprove. What does this site improve code do for a CCOM site?
> > Is it what adds that little site improve overlay when logged in?
> 
> The overlay should be added separately form a siteimprove drupal module and be unaffected by this.
> 
> I believe it handles tracking for any of the analytics/insights in Siteimprove, and should be separate from the traditional accessibility/quality scans. I'm not sure that the same js doesn't have some overlap between the two though, and would need to look into that a bit more.

Coming back to this after a deeper dive, and it does look like the siteimprove js here is only used for the analytics and behavior tracking options within siteimprove. The regular accessibility and qa scans as well as the overlay and its interactions (when logged in) should all remain unaffected.

This js, if desired, could still be added in through the piwik tag manager when that is ready for primetime, or it could be added through any GTM container using the standard GTM module.

If the siteimprove analytics is wanted on CCOM sites, we'll want to make sure that gets in place through one of those two avenues prior to or in addition to pushing the code in #7279 to avoid creating a period of data loss.

Similarly, if/when things move forward with rolling the OneTrust privacy acknowledgement out to the full platform (#6490) we'll need to account for that as well.

For now, @mjoneill @briand44 @ethan-fry: Do we want to maintain the siteimprove analytics (pageviews and behavior, heatmaps, etc) on CCOM sites? If so, is a Piwik container on the nearer horizon where that could be used, or should it be added through a CCOM-specific GTM container?

**Comment by maxwell-freund** [comment]
@cory-skeers thanks for the clarification. I can tell you that Piwik will offer us similar page view / behavior / and heat mapping options within their standard analytics suite offering.

So I would be inclined to not double up on that within SiteImprove, especially if a BAA is not in place with Siteimprove.

The QA and accessibility checking being outside of the code is good to know.

Regarding onetrust, good catch. That certainly could be triggered in Piwik, I will add a note to review that code and integrate with Piwik when it comes online.

As far as timeline to get Piwik off the ground, we are still in contract phase, so it likely is weeks away, if that causes us to pause on the implementation of these changes. But welcome other's thoughts on how these things tier out.

**Comment by cory-skeers** [comment]
> @cory-skeers thanks for the clarification. I can tell you that Piwik will offer us similar page view / behavior / and heat mapping options within their standard analytics suite offering.
> 
> So I would be inclined to not double up on that within SiteImprove, especially if a BAA is not in place with Siteimprove.

Sounds good @maxwell-freund! I think in that case, moving forward with #7279 as-is will work, and include a little extra tidying up beyond what was initially thought.

> Regarding onetrust, good catch. That certainly could be triggered in Piwik, I will add a note to review that code and integrate with Piwik when it comes online.
> 
> As far as timeline to get Piwik off the ground, we are still in contract phase, so it likely is weeks away, if that causes us to pause on the implementation of these changes. But welcome other's thoughts on how these things tier out.

In that case, I would think we can move forward with this now (eg review and test, then roll out). It'd be easiest to implement OneTrust through piwik if that is ready when time comes to expand that, but this doesn't preclude us from implementing it through a separate container or another workaround.
