### ISSUE TITLE
Ask DNA Team to add no-index to saml/login

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#710]
If #709 doesn't work, we should reach out to the DNA team about adding a no-index header to the saml/login as it is being flagged on our sites by Google since I guess our footer links to it.

`<meta name="robots" content="noindex">`

**Comment by richardbporter** [comment]
Did #709 work?

**Comment by joewhitsitt** [comment]
Google flagged the 4th because maybe it wasn't pushed out yet. I don't see anything for the 5th but it might not crawl every day. I will close this for now, but may reopen.
