### ISSUE TITLE
Replicate for layout builder is getting order incorrect

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#7102]
# Problem
Using replicate for layout builder based pages, the order of items is not always correct.

**Before**

![before](https://github.com/uiowa/uiowa/assets/4663676/3f2b44c1-11c7-4507-8b6f-ce137c432dee)

**After**
![after](https://github.com/uiowa/uiowa/assets/4663676/bc33f646-6efd-49aa-af22-4b79903a548c)

# Steps to reproduce
- Try replicating a complex layout builder page.

# Proposed solution
- [ ] The replicate module recently updated as part of the D10 upgrade and we still have some custom code. Perhaps we need to revisit and determine if code needs to be adjusted or removed. (https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/layout_builder_custom/src/EventSubscriber/ReplicateSubscriber.php can likely be removed completely)
- [ ] Test patch mentioned in https://github.com/uiowa/uiowa/issues/7102#issuecomment-1811235901

**Comment by bspeare** [comment]
I think that I've always noticed this with replicate.  Usually one or two blocks are not in right spot.

**Comment by pyrello** [comment]
Possibly related: #7119

**Comment by cory-skeers** [comment]
Looks like an upstream issue: https://www.drupal.org/project/replicate/issues/3392959

Component weights are lost during the new component creation process, and need to be accounted for. And that seems to explain why it doesn't always happen--sometimes the array ordering will match the correct ordering by chance.

**Comment by pyrello** [comment]
> Possibly related: #7119

Actually, probably not related since this is an issue with block (component) ordering and not sections, per: https://www.drupal.org/project/replicate/issues/3392959

**Comment by cory-skeers** [comment]
Patch seems to be working great, except for list blocks. Some of our custom code is meant to address list blocks that weren't replicated properly from core replicate, and that may be the source of the issue there, but still investigating if it is even still needed.
