### ISSUE TITLE
Revisit use of the scheduler module for alerts/articles

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#7106]
Given the struggles with https://github.com/uiowa/uiowa/pull/7044 and the fact that no site has launched yet with the functionality I think we should revisit what we are trying to accomplish and understand if it would be better to do it without scheduler.

# Example struggles

- We already need to supplement default help text to explain the one-hour window to publishers/webmasters.
- Scheduler will set the core status for the node back to 0 without consideration of the moderation state causing mismatches. Validation logic had to be added to account for transitions from the node edit form, layout builder interface, content overview bulk publishing.
- The add-on module adds their own access checking which prevents editors from editing an article while it is awaiting to be published.
- Additional messaging collide with other messages triggered by Scheduler that are not sufficient. 
- Setting defaults for the add-on module, hiding the field and then dealing with possible validation messages that link to the hidden field.

# Requirements

- Compatibility with moderation or just core status
- Runs on 1 hour cron interval
- Allows publishing/unpublishing/archiving depending on content type requirements
- Ability to restrict settings access to only those who can publish
- Capture date hour/minute. Ignore seconds on input
- Light footprint. Scheduler is implemented without adding an actual field to the content type.
- Dealing with difference between a moderated ITS alert, and a default Facilities alert. Iowa Now embargo.
- ??

# Notes

Facilities v1 has non-scheduler functionality for publishing alerts.
uipress has date based show/hide functionality.
```[tasklist]
### Tasks
- [ ] Investigate alternative modules
- [ ] Write up a possible solution in an issue with enough detail to be executed on
```

**Comment by bspeare** [comment]
Prove that we can schedule moderated content with less hiccups than the scheduler module.  Field, cron hook, check field.

**Comment by pyrello** [comment]
Some alternatives I found to look into:
- https://www.drupal.org/project/scheduled_publish
- https://www.drupal.org/project/scheduler_field
- https://www.drupal.org/project/scheduled_updates
- https://www.drupal.org/project/scheduled_transitions
- https://www.drupal.org/project/advanced_scheduler - I'm including this for additional scrutiny but I'm skeptical that it is actually useful.

**Comment by joewhitsitt** [comment]
Reviewing these at a glance, I am not sure any of these handle our situation of "why not both" when it comes to dealing with core status or content moderation.

https://www.drupal.org/project/scheduled_updates
https://www.drupal.org/project/scheduled_transitions

IMO, these two seem most promising (untested), but with that said, I doubt either of these will be plug and play and won't result in similar amounts of bloat.

I think there are a lot of little things in scheduler that are starting to sound nice to have instead of trying to account for them in custom code.

**Comment by pyrello** [comment]
> I am not sure any of these handle our situation of "why not both" when it comes to dealing with core status or content moderation.

Is there a reason we are trying to use both? It seems like it would be easier to just adopt one approach and stick with it.

**Comment by joewhitsitt** [comment]
As it stands right now, Facilities Alerts is using core status for publishing/unpublish. We have a few other content types in our ecosystem that are the same (either it was forgotten or by choice). For Facilities they wanted to ensure Construction Managers were able to post a quick alert without any kind of friction.

I'd be interested in adopting consistency across our content types even if it means adding a more direct workflow for some content types than our editorial workflow.

I don't want to overthink it quite yet, but I doubt we will fully pick moderation over core status. Scheduler and some of these others support other entity types (taxonomy terms, blocks) that we may want to add scheduling to some day. https://github.com/uiowa/uiowa/issues/5861 https://github.com/uiowa/uiowa/issues/5405

**Comment by pyrello** [comment]
> For Facilities they wanted to ensure Construction Managers were able to post a quick alert without any kind of friction.

Wouldn't this just be a matter of potentially updating the default content moderation state, so that it's set to "Published" instead of "Draft" when the form is loaded? I guess I'm unclear as to why content moderation can't be used to handle a simple published/unpublished paradigm.

Or maybe its just setting different permissions on the workflow transitions for Facilities?

**Comment by joewhitsitt** [comment]
>Wouldn't this just be a matter of potentially updating the default content moderation state, so that it's set to "Published" instead of "Draft" when the form is loaded? I guess I'm unclear as to why content moderation can't be used to handle a simple published/unpublished paradigm.

>Or maybe its just setting different permissions on the workflow transitions for Facilities?

Before this issue there wasn't a strong reasoning to do so. Just using core status was the thin slice through the original requirement and has been for other content types as well.

Again, I'd be fine with adopting more consistency here. Instead of form alters, I'd probably suggest an additional workflow that is captured in config. Moderation transition permissions might be tricky because they aren't granular per content type.

**Comment by joewhitsitt** [comment]
After a week of sitting on it (but not really diving into other options), I am leaning toward just moving forward with what we have with `scheduler` and `scheduler_content_moderation_integration` with the hope that both will continue to improve.

I am also optimistic that upcoming hosting changes might allow for better cron management which would allow us to remove some of this additional help text.

I'd be interested to see if folks had some suggestions on how to improve/simplify the custom logic here: https://github.com/uiowa/uiowa/pull/7044/files

A lot of this code was reactionary to the bumps in the road along the way. For example the complexity surrounding uiowa_core_preprocess_node is that I was trying to reduce duplicate type messages, when really we could just simplify the message we are trying to add so that it supplements existing messages and doesn't try to replace them.

Seans suggestions about adopting moderation for all content types would also help some of the if/else logic surrounding this functionality.
