### ISSUE TITLE
Update file_mdm to version 3.0.0

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#7108]
https://www.drupal.org/project/file_mdm/releases/3.0.0 (10.1)

We are starting to see a lot of "Uncaught exception 'TypeError' with message 'base_convert(): Argument #1 ($num) must be of type string, array given' in /mnt/www/html/uiowa04/vendor/lsolesen/pel/src/PelConvert.php:143" in #drupal-status and we are still on a version that uses an archived `pel` library.

My hope is that this will help with these messages. I think they can be linked back to photo uploads on webforms.

## Reproduce

![stella](https://github.com/uiowa/uiowa/assets/4663676/8beeafa0-6c2f-4571-abd7-e5db64f6f170)

![58499406-b6233d00-8145-11e9-882e-d3e1e1db59f1](https://github.com/uiowa/uiowa/assets/4663676/b5649808-630b-42fc-8cef-98558615e32d)

## Known Issue

https://sitenow.uiowa.edu/known-issues#uiowa-issue-7108

# Proposed Solution

- [x] Upgrade file_mdm to version 3.0.0
- [x] test that iphone image exif rotation still works
- [ ] monitor logs and cherwell

**Comment by joewhitsitt** [comment]
Connected to Cherwell 1971782

International Programs form is having issue with certain images being uploaded to their form. https://international.uiowa.edu/award-testimonial-form-faculty

The above errors align with Ajax errors related to the `photo` form element.

**Comment by briand44** [comment]
blocked until we are on 10.1

**Comment by joewhitsitt** [comment]
no longer blocked

**Comment by joewhitsitt** [comment]
ugh, thought this could be an easy morning win. running into chicken/egg composer issues between this and imagemagick

**Comment by joewhitsitt** [comment]
https://www.drupal.org/project/imagemagick/issues/3408541
https://www.drupal.org/project/file_mdm/issues/3408540

**Comment by bspeare** [comment]
Is this blocked again?

**Comment by joewhitsitt** [comment]
Blocked if we need to wait for an upstream solution. Not blocked if we want to be part of the solution with a patch to either module. Since it wasn't the small we planned, I am fine with letting this sit a bit.

**Comment by joewhitsitt** [comment]
Actually, I think I figured out the composer issue. Pushing something up.
