### ISSUE TITLE
Facilities Artist content

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7113]
# Story

As a Facilities site editor, I would like to be able to create artist content so that site visitors can see information about artists and their artwork.

# Additional Info

Artist pages should show artist info along with teasers of their artwork.
They'll need the ability to filter artwork by artist when we build the gallery.
If we build a content type for this we will need to update the reference on the artwork content type as that currently is a reference to the person content type.

Examples of artist pages
https://www.facilities.uiowa.edu/art-on-campus/artist/lynn-basa
https://www.facilities.uiowa.edu/charles-ray

**Current Fields**
- Title - generated from first and last name
- First Name - required - text
- Middle - text - no longer needed
- Last - required - text
- Nationality - text
- Birth Year - integer
- Death Year - integer
- Bio - filtered html
- Website - title and url

# Proposed Solution

- Create a split for the person content type for Facilities
- Facilities split should have a new person type for "Artist"
- Facilities split should contain artist specific fields
    - Nationality
    - Birth Year
    - Death Year
    - Website
- Show/hide appropriate fields based on person type
- Output artist specific fields on Facilities person nodes
- #6660

**Comment by briand44** [comment]
Grooming conversation... Sounds like the team would like to use the person content type rather than creating an artist content type. Discussed tackling https://github.com/uiowa/uiowa/issues/6660 as part of this. Output artist specific fields on person nodes.

**Comment by cory-skeers** [comment]
As a part of this, take a second look at whether artists should be able to be created inline on Artwork content (https://github.com/uiowa/uiowa/pull/7104#issuecomment-1812793274)

**Comment by briand44** [comment]
I have an email out asking if we can omit the middle name field

**Comment by briand44** [comment]
We don't need the middle name field
