### ISSUE TITLE
Test UI Signage and UIHC Signage non-production env's

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7114]
# Story

As a web team, we would like to make sure our Signage non-production environments are working correctly after the upgrade to cloud next so that we don't have issues when the production environments are updated on Nov 20th.

# Proposed Solution

**Comment by briand44** [comment]
Grooming conversation... make sure signage routing is still working (error we occassionally get in its-web from data.its). Test Outlook calendar integration functionality and other integrations. Verify HC Signage is still locked down.

**Comment by GaryRidgway** [comment]
I'm testing a little bit here. I moved DB and files over to UIowa signage dev and all normal functionality seems to be working so far. I have not moved on to any integrations yet

**Comment by joewhitsitt** [comment]
weather and bus info seems to be pulling at the moment:

city-iowa-city/downtown-interchange-stop-0001

content hub events:

law/college-law-events-signage

As I mentioned earlier, hawkid authentication worked.

outlook integration:

cph-calendars/cphb-c401

**Comment by joewhitsitt** [comment]
FWIW, https://signage.uihealthcare.org/ is available to me with just a VPN connection. I don't need to remote into the OSC on-campus computer. not sure if dev/stage have been synced for healthcare to test.

**Comment by GaryRidgway** [comment]
I have tested all the integration panes and the only one that looks like it is not working is the earthquake pane, which has the "For development only" watermark plastered over it.

<details><summary>I tested the following</summary>
<p>

- [x] outlook
- [x] mazevo event listing panes
- [x] astra room schedule
- [x] HC wait times
- [x] ER wait
- [x] dining location
- [x] pentacrest webcam
- [ ] earthquake
- [x] Uiowa events pane listing

</p>
</details>

**Comment by GaryRidgway** [comment]
I will start syncing uihc signage

**Comment by GaryRidgway** [comment]
Files and DB were synced to dev on friday
I don't think I will have any more time to work on this today

**Comment by briand44** [comment]
I am getting a 500 error when trying to hit https://signage-dev.uihealthcare.org/ and https://signage-stage.uihealthcare.org/. Not seeing anything in the logs.

**Comment by briand44** [comment]
I was able to troubleshoot a bit and was able to get dev loading on a feature branch https://signage-dev.uihealthcare.org/. It appears to be some issues with having the memcache module in multiple locations.

There is a version in the profile and a version in sites/all. They are two different versions. Removing the one in sites/all got the site to load. Removing the one in the profile just caused different error message related to it not being found.

Another thing to note is that prod is reporting that memcache is not enabled.

Regular signage has this module in sites/all and not in profile. It is also enabled and using a more updated version than both the versions on HC Signage.

I'm going to check out master branch in dev again and not implement any changes at this time. I do not think any of these issues are related to the update to Acquia Cloud Next.

**Comment by briand44** [comment]
Created https://github.com/uiowa/uiowa/issues/7133 as a follow up. Closing this.
