### ISSUE TITLE
Patch `linkit_media_library` to work with CKEditor5

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7123]
# Story

As a web team, we would like to keep our existing linking experience after upgrading to ckeditor 5.

# Additional Info

https://github.com/uiowa/uiowa/issues/5667#issuecomment-1810972829
https://github.com/uiowa/uiowa/issues/5667#issuecomment-1811253058

## Getting setup for patch contributions
```
cd docroot/modules/contrib && \
rm -rf ./linkit_media_library && \
git clone git@git.drupal.org:project/linkit_media_library.git && \
cd linkit_media_library && \
git remote add linkit_media_library-3329877 git@git.drupal.org:issue/linkit_media_library-3329877.git && \
git fetch linkit_media_library-3329877 && \
git checkout -b '3329877-not-compatible-with' --track linkit_media_library-3329877/'3329877-not-compatible-with'
```

# Proposed Solution

```[tasklist]
### Tasks
- [x] Start a PR with the config changes necessary to switch to CKEditor 5. This PR will eventually turn into the work for #5667
- [ ] Write a patch that replicates enough of the current functionality that it works for our use case
```

**Comment by joewhitsitt** [comment]
For reference, I think this is the current core issue related to inline media https://www.drupal.org/project/drupal/issues/3168966

"What a Long Strange Trip It's Been"

I think the main goal originally was to have a linked media document file (internal link path that is kept up to date) inline with things like a bulleted list. Linkit alone does this, but this contrib project allowed us to move away from the clunky workflow of, create the media item first at /admin/media/add, then reference existing through autocomplete in the LinkIt modal.

**Comment by pyrello** [comment]
It occurred to me that to test whatever we come up with to solve for this we are going to have to essentially go through the process of updating to CKEditor 5 on a local site so we can test a patch or custom plugin code. Therefore, in my mind it makes sense that we would create a PR that encapsulates those config changes, which would essentially be starting #5667 even though we wouldn't be committing to finishing that work in the same sprint.

**Comment by pyrello** [comment]
**Setup instructions to work on this, just in case:**
These instructions assume that you have ssh keys setup for Drupal. It is also easier if you open up an extra terminal tab to work with the module's git repo so you can have a tab where you are still in the project root to run `ddev` commands.
```
cd docroot/modules/contrib && \
rm -rf ./linkit_media_library && \
git clone git@git.drupal.org:project/linkit_media_library.git && \
cd linkit_media_library && \
git remote add linkit_media_library-3329877 git@git.drupal.org:issue/linkit_media_library-3329877.git && \
git fetch linkit_media_library-3329877 && \
git checkout -b '3329877-not-compatible-with' --track linkit_media_library-3329877/'3329877-not-compatible-with'
```

**Comment by pyrello** [comment]
So far, I have a button showing up (in the wrong location - @GaryRidgway is looking into this). When you click the button the media library shows up. If you actually select a file and insert it, it works just like the the media library button, which makes sense since I copied a snippet of code from the core ckeditor5 drupal media plugin.

**Comment by pyrello** [comment]
Update: @bspeare sent me a link (https://www.drupal.org/project/ckeditor5_entity_browser) that I was able to use to get examples of behavior similar to what we are trying to do here. I was able to get the plugin to a functional state. I have updated the issue and requested that the community test the plugin to tell me what isn't working: https://www.drupal.org/project/linkit_media_library/issues/3329877#comment-15347047

**Comment by joewhitsitt** [comment]
woot! fantastic work! just curious if that one comment on the community issue about the rest of the module not being linkit 6.1/core 10.1 compatible is a reason for concern (separate slice?)?

**Comment by pyrello** [comment]
> woot! fantastic work! just curious if that one comment on the community issue about the rest of the module not being linkit 6.1/core 10.1 compatible is a reason for concern (separate slice?)?

I'm not sure it would be a concern for us. As far as I can tell, the plugin is working with our current setup using core 10.1 and linkit 6.1. It may be that it is not compatible with CKEditor 4. I haven't checked because it isn't pertinent to the work we are focused on.
