### ISSUE TITLE
ITS Alert Status

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7147]
# Story

As an ITS site owner, I would like to be able to display a status history of services over the last 5 days (current and four previous).

# Additional Info

Current page - https://its.uiowa.edu/alerts/status-history

Some notes - https://github.com/uiowa/uiowa/issues/7147#issuecomment-1832309215

- Display of all services
- Ability to see if service was operational, or if there was an outage, planned maintenance, service announcement, service degradation or multiple alert types over the last 5 days.
- Ability to filter/sort?
- Ability to view alert(s) details
- Legend depending on display?

# Proposed Solution

**Comment by briand44** [comment]
Dumping some notes here from our previous meeting:

- Prefer to order these by important first rather than just alpha. Ordering by category would be ok.
- If we provided filters/searching/sorting, the initial order may not be as important
- instructors use this to verify statuses of learning tools when students say they couldn't get their work done because the learning tool was down
- They mentioned not putting a ton of time into this feature

**Comment by joewhitsitt** [comment]
>If we provided filters/searching/sorting, the initial order may not be as important

I would imagine it would be a chronological listing that is filterable this time around. We could make some services "sticky" and then [differentiate those some way](https://github.com/uiowa/uiowa/issues/6695) to help achieve the "Prefer to order these by important first rather than alpha."

**Comment by briand44** [comment]
Grooming conversation... Develop a page with search/filtering capabilities for all published alerts (future, current and past).

**Comment by GaryRidgway** [comment]
Taking a look at the poor request today, I was confused at the fact that there [was an entire patch file being removed](https://github.com/uiowa/uiowa/pull/7293/files). Sean and I had a huddle and he explained to me that adding the dependency for better exposed filters makes config split patching not work, and it makes it change to a complete split. While this is confusingly intentional behavior, it begs the question of, if we are going to add better exposed filters to many other views, should we just be adding it to the entire platform as a dependency for all sites?

**Comment by cory-skeers** [comment]
> Taking a look at the poor request today, I was confused at the fact that there [was an entire patch file being removed](https://github.com/uiowa/uiowa/pull/7293/files). Sean and I had a huddle and he explained to me that adding the dependency for better exposed filters makes config split patching not work, and it makes it change to a complete split. While this is confusingly intentional behavior, it begs the question of, if we are going to add better exposed filters to many other views, should we just be adding it to the entire platform as a dependency for all sites?

At least my initial reaction is that _we_ have a dependency on BEF if we're using it multiple places, and that that could warrant it being a platform dependency even if it's not technically.

**Comment by joewhitsitt** [comment]
Ugh. It was originally supposed to be just that one site (Admissions). We have definitely crossed the sites/all threshold and haven't found anything "better". As much as I dislike the amount of buggy bloatedness of that module, it is probably time if it simplifies our config process.

**Comment by pyrello** [comment]
I'm in favor of adding BEF as a platform-wide module dependency and shifting this out of the individual config splits where it is being used.

**Comment by bspeare** [comment]
Do we need a "Consider moving away BEF" issue like https://github.com/uiowa/uiowa/issues/4973 to document the bloat?
