### ISSUE TITLE
Check the status of our known issues

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#715]
We should handle our known issues page a bit better

First someone should go through to confirm these are all still issues and that the workarounds still work.

We should structure each one similarly:
issue:

additional details:

workaround:

Additionally, we should somehow match the issue to a github issue by using unique id to reference the github issue (e.g. uiowa-issue-999 aka repo-issue-number). In turn, I think if there is a github issue, we should link out to it so we know to clean it up when something is fixed.

The reason I thought about this is that I am pretty sure we pushed an iPhone exif fix but I don't have an iPhone to test it with.

IMO, I think we should get rid of the alternating bg colors as well.

**Comment by joewhitsitt** [comment]
Ethan was working on this, but doesn't have an iPhone to confirm the rotation issue has been fixed

**Comment by dnkemper** [comment]
@joewhitsitt @ethanstjohn I added rotated images to a page and can confirm that the iPhone issue has been fixed
