### ISSUE TITLE
Update uiowa_core exposedFormEnhancements to work with core bulk operations form

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#7162]
> I think docroot/modules/custom/uiowa_core/js/exposedFormEnhancements.js is affecting this new form by not making the selection contrast compliant. follow up issue?

<img width="1192" alt="Screenshot 2023-12-01 at 9 54 09 AM" src="https://github.com/uiowa/uiowa/assets/4663676/3f85378f-bb26-4e8f-9625-ce313f308bb3">

_Originally posted by @joewhitsitt in https://github.com/uiowa/uiowa/issues/7098#issuecomment-1836352534_

**Comment by joewhitsitt** [comment]
Noticing this again. It seems like there has been a regression.

**Comment by briand44** [comment]
Grooming conversation... Reference previous work in #7198 as a starting point. This was something we resolved previously and is now happening again. This was noticed while doing bulk deletions in preparation for running ITS migrations.
