### ISSUE TITLE
Drupal 9 Code Audit

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#717]
## Problem
We should probably start preparing our codebase for Drupal 9 and making sure our contrib modules will be ready for Drupal 9.

## Proposed Solution
https://www.drupal.org/project/site_audit
https://www.drupal.org/project/upgrade_status
https://github.com/mglaman/drupal-check/

Create separate issues for things that come up, look into the community to see if a solution has already be figured out.

**Comment by joewhitsitt** [comment]
i am getting nowhere fast with these so far... upgrade_status is stuck initializing the scan of one module. drush 9 isn't recognizing site_audit's command.

**Comment by richardbporter** [comment]
I would avoid site_audit.
