### ISSUE TITLE
Responsive images bug

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#7184]
# Problem
The 10.1 update included a responsive images width and height attribute fix (https://www.drupal.org/project/drupal/issues/3192234#comment-14787534) that now properly sets width and height properties for the "Small - no crop" image style".  Each "no crop" image style was previously not getting these attributes set. 

Before:

<img width="1495" alt="Screenshot 2023-12-05 at 3 00 28 PM" src="https://github.com/uiowa/uiowa/assets/1036433/6a675513-9aa7-4000-9c9e-4dbed81405f6">

After:

<img width="1484" alt="Screenshot 2023-12-05 at 3 00 19 PM" src="https://github.com/uiowa/uiowa/assets/1036433/966ae79b-ea1c-4245-ac45-caccf3a27327">

# Steps to reproduce
Remove image attributes on https://whitmanweb.iwp.uiowa.edu/song-myself/turkce-turkish/bolum-17-kendimin-sarkisi as an example. 

# Proposed solution
- [x] Apply patch from https://www.drupal.org/project/drupal/issues/3377420, update fallback small image styles.
- [x] Develop SiteNow article announcing the change using bits from https://apps.its.uiowa.edu/dispatch/archive/an-update-to-inline-element-sizing-Q76x0l0. 
  - [x] Show before and after examples
  - [x] Outline image sizes in SiteNow documentation that we can link to at https://sitenow.uiowa.edu/documentation/media/images-and-files
  - [x] Possibly explain difference between Drupal core image styles and SiteNow image styles
  - [x] Suggest looking at GA for high value pages to inspect
  - [x] Suggest using Find Text module for `data-view-mode="small__no_crop"` and `data-view-mode="large__no_crop"` searches

```[tasklist]
### Remaining tasks
- [ ] Create Dispatch campagin from https://github.com/uiowa/uiowa/issues/7184#issuecomment-1847320410
- [ ] Publish https://sitenow.uiowa.edu/node/326/latest
- [ ] Publish https://sitenow.uiowa.edu/news/2023/12/important-update-sitenow-image-display-styles
```

**Comment by joewhitsitt** [comment]
Here is our original inline sizing announcement. Strategy and bits and pieces could be pulled from this: https://apps.its.uiowa.edu/dispatch/archive/an-update-to-inline-element-sizing-Q76x0l0

**Comment by bspeare** [comment]
I started an email draft at https://iowa-my.sharepoint.com/:w:/r/personal/bspeare_uiowa_edu/Documents/SiteNow%20Media%20display%20options.docx?d=w7a78c92c98284f67becbd7ca38eb1c72&csf=1&web=1&e=mdf4s5 and gave access to `CSI-Drupal` members.

**Comment by joewhitsitt** [comment]
Thanks for moving forward with this @bspeare. Generally I think this looks good. I keep getting hung up on this wording though: "...when selecting display options such as "Small," "Medium," "Large," or "Full" for images in WYSIWYG text areas..." because my understanding is that small, medium, large image styles (core) are actually rendering as expected but that the responsive image styles (anything with the dash separator) are the ones that display at 768px.

**Comment by bspeare** [comment]
@joewhitsitt I agree with that point.  Maybe adjusting to something like  "...when selecting display options such as "Small - [image style]," "Medium - [image style]" "Large - [image style]" or "Full  - [image style]" would help clear that up?

**Comment by joewhitsitt** [comment]
Also, from yesterday I realized we were putting the Sitenow monthly updates on the Sitenow website and only the demo articles on web community. If we aren't stirring up a change right now, I feel like this article should be on the Sitenow site instead.

**Comment by joewhitsitt** [comment]
Ugh. We haven't been even on this:
https://webcommunity.sites.uiowa.edu/updates/2023/05/important-information-sitenow-partners
https://sitenow.uiowa.edu/news/2020/12/changes-look-and-feel-person-page
https://sitenow.uiowa.edu/news/2020/07/sitenow-v2-websites-will-be-getting-new-look-and-feel

**Comment by bspeare** [comment]
Draft with screenshots at https://sitenow.uiowa.edu/news/2023/12/important-update-sitenow-image-display-styles.  Feel free to update or comment here!

**Comment by bspeare** [comment]
Added new image style documentation table to https://sitenow.uiowa.edu/node/326/latest - please take a look and provide feedback!

**Comment by joewhitsitt** [comment]
>Added new image style documentation table to https://sitenow.uiowa.edu/node/326/latest - please take a look and provide feedback!

Wow! This is great. Nice use of tables. Maybe note that these styles can show up in other places as options beyond the WYSIWYG.

**Comment by joewhitsitt** [comment]
Should have reviewed both before commenting.

>Draft with screenshots at https://sitenow.uiowa.edu/news/2023/12/important-update-sitenow-image-display-styles. Feel free to update or comment here!

WOW! Very detailed. Nice work.

**Comment by bspeare** [comment]
> Maybe note that these styles can show up in other places as options beyond the WYSIWYG.

Great suggestion! I added a note.
