### ISSUE TITLE
recserv hours not showing on homepage

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7194]
Got a report hours were not showing on https://recserv.uiowa.edu. They added a message to direct users to their hours page where they were showing correctly https://recserv.uiowa.edu/hours. 

I disabled js aggregation as a temporary workaround and hours started showing again on the homepage.

Creating this to address the problem so we that we can turn on js aggregation again in the future.

**Comment by briand44** [comment]
Grooming we discussed we probably should set preprocess = FALSE similar to profiles.

**Comment by bspeare** [comment]
I tried `preprocess: false` and could not get a quick win on that.  I'm going to unassign myself if anyone else wants to work on this.
