### ISSUE TITLE
Current outages/degredation of service landing page component

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7197]
# Story

As an ITS site owner, I would like to be able to display current outages and degradation of services on our services landing page so users can quickly find these and get more information about them.

# Additional Details

Mockup - https://sandbox.prod.drupal.uiowa.edu/mockup-its-alerts-landing-7

View block that shows active (not closed) outages and degredation of service alert types.

Order - currently term weight (outage first), then post date

May need some cache busting since they are date/time based.

"View more" needs accessible link titles similar to card component.

Outages and Degradation of Services should have different style. 

No results text

# Proposed Solution

- [ ] Use additional details as a build spec.

**Comment by briand44** [comment]
Grooming conversation... Severity no longer needed. Category should be singular and required. Category work will happen in the currently in progress slice. Outages and Degradation of Services should have different style. No results text

**Comment by cory-skeers** [comment]
Alerts will have an `isClosed()` method. We either want to make sure the logic matches up with that, or it could be possible to use the computed value as part of the views setup. https://www.drupal.org/node/2904410

**Comment by cory-skeers** [comment]
I'm thinking as part of this we should probably also 1) make sure both "outage" and "service degradation" are alert category terms in prod and 2) include code to prevent their deletion (like we've done with other controlled taxonomies)
