### ISSUE TITLE
Create references on the fly

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#720]
We have lost the ability to create new terms on the fly in D8 requiring the user to click a link to go create the term(s) and then come back to their content to reference them and are currently using an entity references views widget.

This might be done by creating an entity browser field with two tabs. reference existing like above or IEF for creating new.

**Comment by joewhitsitt** [comment]
@dnkemper I think the idea in #775 was close, but unfortunately in the wrong "buckets."

I would start a new branch and try the following (i am guessing on the naming conventions):

Using the existing References view, create a new entity browser display showing the entity browser checkboxes, the term name and the vocabulary in a table. exposed filters on term name and vocabulary. show 50? pager?

Create an new entity browser "References" standalone modal that includes the new view display.

Change field_references to an inline entity form complex form widget. If you need to select tags for the vocabulary on the default site to get it to create if not existing, i think that is fine and HR will just have to split. Check the entity browser option and reference the new References entity browser.

In my head, think this will work. Might need to move the field out of the advanced sidebar to make it more usable (remove the switch case in sitenow.profile)

If it does, we will need to split the field config on HR to include units. not faq categories. we will need to audit if HR is using any faq categories in that field currently.

The downside to all of this is that we are still using an entity reference field for taxonomy reference type stuff. Supposedly, taxonomy references were going to go away which is why entity reference was used in the first place.

**Comment by dnkemper** [comment]
I couldn't do it off of the existing References. I created a new view to grab all existing taxonomy terms (not just tags), because multiple sites use more than just one Taxonomy. So I set it up where they can only create new Tags for the Tag taxonomy but pull from all other existing terms from existing taxonomies. I can't remember off the top of my head, but the References view created errors, which is why I created a new one. I'll go back and mess around again, but other than that, the other requirements you listed were on previous code submission thankfully

**Comment by joewhitsitt** [comment]
Brain dump (no immediate action):

Disable inline edit:
https://www.drupal.org/project/inline_entity_form/issues/2913571 (RTBC waiting on tests)

Prevent duplicates:
https://www.drupal.org/project/inline_entity_form/issues/3083447 (Custom code solution)

[ ] Split HR field.field.node.page.field_reference.yml

**Comment by dnkemper** [comment]
Pull request https://github.com/uiowa/uiowa/pull/778 needs to be tested please!

**Comment by joewhitsitt** [comment]
We are going to go in a different direction with #598 and #839
