### ISSUE TITLE
Primary and alt building coordinators on building pages

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7200]
# Story

As a Facilities site owner, I would like to display the the primary and alternative building coordinators on Facilities building pages so that site users can quickly find who to contact with questions about the building.

# Additional Info

Building coordinator info is available at API endpoint https://bizhub.facilities.uiowa.edu/bizhub/ext/bldgCoordinators

Current example - https://www.facilities.uiowa.edu/building/0003

>In order to be a building coordinate they have to have at least one building under their responsibility.

Based on ^^, it sounded like we want to store this information on building entities.

**Primary Building Coordinator**
Name - mainFullName
Job Title - mainJobTitle
Department - mainDepartment
Email - mainCampusEmail
Phone - mainCampusPhone

**Alternate Building Coordinators (Up to 4)**
Name - alternateFullName[1-4]
Job Title - alternateJobTitle[1-4]
Department - alternateDepartment[1-4]
Email - alternateCampusEmail[1-4]
Phone - alternateCampusPhone[1-4]

Maintenance Manager - maintenanceManagerFullName
Custodial Assistant Manager - custodialAssistantManagerFullName

Currently outputting Primary and Alternate Building Coordinators name as a mailto link.

# Question

Do we need to store the maintenance manager and custodial assistant manager email addresses? It doesn't look like the current site outputs these anywhere.

# Proposed Solution

**Comment by briand44** [comment]
Grooming conversation... Grab building coordinators as part of current building call. Paragraphs to capture these fields as a collection. Reference field to that paragraph type. Multiple values with a boolean to represent if they are primary building coordinator or not. Discussed not limiting to 5 values in case they increase in future.

I will get clarity on if the maintenance manager custodial manager email is needed

**Comment by briand44** [comment]
response on maintenance manager and custodial manager emails is on https://github.com/uiowa/uiowa/issues/7199#issuecomment-1922217872

**Comment by joewhitsitt** [comment]
Based on https://github.com/uiowa/uiowa/issues/7199#issuecomment-1944149471 and the grooming conversation, https://github.com/uiowa/uiowa/issues/7199#issuecomment-1944451895

We are pausing this work and shifting it to all be stored on the building node.

**Comment by joewhitsitt** [comment]
Going to kick this off and open it up in Slack.

**Comment by joewhitsitt** [comment]
>Discussed not limiting to 5 values in case they increase in future.

The amount of field config this produces makes it feel dirty but with Paragraphs being a performance concern, the only other idea I have if we are going to continue to store this in Drupal is to use a compound field (e.g. addressfield). Moving forward with separate fields, but if they expand these contacts in the future, we may want to revisit.
