### ISSUE TITLE
deprovision covidresponse.research.uiowa.edu on uiowa

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7202]
This is a v2 site that we removed the production domain for to deactivate the site upon the owners request. They did not want us to remove it at that time in case they needed to quickly restore it. They have now granted us approval to remove the site.

**Comment by joewhitsitt** [comment]
going to test the updated deprovision script i am working on in https://github.com/uiowa/uiowa/pull/7246 with this site.
