### ISSUE TITLE
[Bug] People list block hidden fields regression

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#7203]
# Problem
`Content: website` and `Content: Link directly to website` are now options in the People list block. 
<img width="1278" alt="Screenshot 2023-12-12 at 11 28 53 AM" src="https://github.com/uiowa/uiowa/assets/1036433/500ff978-0445-4b52-8b9b-7ba85c0c212a">

# Steps to reproduce
Configure a people list block on https://sandbox.prod.drupal.uiowa.edu/node/51/layout. 

# Proposed solution
- Add the website as an option to the teaser and set an update hook to keep it hidden.  

## Considerations
- Doing this will make the website field appear on /people but it seems like we need to make the People view configurable: https://github.com/uiowa/uiowa/issues/7101
- The featured content card will also display the website field without an ability to hide (you can't hide the email or the phone number fields either).

**Comment by joewhitsitt** [comment]
Should test with an existing block where link directly is checked. If this is removed, does it create an issue on next save or do we need an update hook to unset any we find?

**Comment by joewhitsitt** [comment]
I wonder if we have a problem of not accounting for new fields in this and other listblocks, because the view config is "restrict fields" not "allow fields." If so, this will be something we need to account for every time we add a field to the content type(s).
