### ISSUE TITLE
Planned Maintenance component for Alert landing page

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7216]
# Story

As an ITS site owner, I would like to be able to display planned maintenance alerts that will be happening over the next 7 days on our alerts landing page so that users can easily find information about upcoming maintenance and how it will affect them.

# Additional Info

Mockup - https://sandbox.prod.drupal.uiowa.edu/mockup-its-alerts-landing-7

View block that shows active (not closed) planned maintenance alerts where the start date is less than or equal to now + 7 days.

Order by start date - asc

Theme according to mockup

No results text

Cache busting since date/time based?

# Proposed solution

- [ ]  Use additional details and https://github.com/uiowa/uiowa/issues/7216#issuecomment-1861518009 as a build spec.

**Comment by briand44** [comment]
Grooming conversation... Cache busting should be similar to the work in progress related to outages and degradation of services, so hopefully we can reuse that. Teaser might need some adjustments to match mockup but some of this is already in place from SiteNow Alerts. Show all for now, if we need a pager later we can add it then.

**Comment by cory-skeers** [comment]
I was testing the coverage of some of the updates I was making for #7197, and it got to the point where it was helpful to pull this in as well and work the two simultaneously.
