### ISSUE TITLE
Service Announcement component on alert landing page

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7217]
# Story

As an ITS website owner, I would like to be able to display active service announcements on our alerts landing page so that users can easily find information about these important announcements and how it affects them.

# Additional Info

Mockup - https://sandbox.prod.drupal.uiowa.edu/it-service-alerts-copy

View block that shows published and active (not closed) service announcement alerts.

Order by post date

Theme according to mockup

No results text

# Question

Do we want to continue pushing on these being articles vs alerts?

# Proposed solution

**Comment by briand44** [comment]
Grooming conversation.... ITS wants to keep these as alerts. Can use cache tag from previous work if needed, may want to rename to be more generic. Doesn't need to match the mockup if we run into any hiccups. Can make it look more like an alert if we want since it is an alert.

**Comment by pyrello** [comment]
I'm interested in working on this. I feel like I missed the whole conversation about this being alerts vs. articles. Looking at the mockup and the type of information being presented here, it seems obvious that these should be articles. Can someone provide some context as to why the customer wants these to be alerts?

**Comment by briand44** [comment]
@pyrello This was discussed in the last meeting with them. I didn't take great notes but they mentioned they see service announcements separate from a news article and that these service announcements need to be displayed on the alert calendar, in alert emails, on the alert status history page, etc. so they would prefer to keep these as alerts like they are now.

I believe we intentionally mocked them up to be more like an article because that was what we were suggesting at that time. We mentioned while grooming this that we may need to make these look more like alerts rather than how they are currently mocked up since they didn't want to use articles here.

**Comment by GaryRidgway** [comment]
In the mockups, we don't have the badges for service announcements on the teaser view for them. Additionally, the teaser view doesn't have the arrow circle either. Should I be making a new display, working with some sort of pre-process, or leaving them how they are for consistency?

<details><summary>This is an example of the current treatment</summary>
<img src="https://github.com/uiowa/uiowa/assets/23122142/5e62233e-1a39-4e85-bd0a-5c54712c6152">
</details> 

<details><summary>And this is how the original mockup looked</summary>
<img src="https://github.com/uiowa/uiowa/assets/23122142/eeb55cbe-be8a-4d4d-ac47-6a8ff55d93a3">
</details>

**Comment by joewhitsitt** [comment]
> I believe we intentionally mocked them up to be more like an article because that was what we were suggesting at that time. We mentioned while grooming this that we may need to make these look more like alerts rather than how they are currently mocked up since they didn't want to use articles here.

@GaryRidgway I think based on the recent meeting, maybe these instead look like alerts but as "info" instead of warning/danger.

Thoughts @bspeare?

**Comment by GaryRidgway** [comment]
> @GaryRidgway I think based on the recent meeting, maybe these instead look like alerts but as "info" instead of warning/danger.
> 
> Thoughts @bspeare?

That is basically what I was hearing from cory too. So that means leave the badges?

**Comment by GaryRidgway** [comment]
Heard back from Ben, going to go forward with keeping the current treatment as is.

**Comment by e-marie-w** [comment]
Closed via #7219
