### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#722]
## Problem/Vision
We know the request is coming sooner than later. Similar to #718 if implemented it would be great if we could be consistent in our approach.

Drupal comments have been re-written and might be more manageable now in D8 to "just turn on"

**Comment by richardbporter** [comment]
I'd be inclined to wait for a more concrete use case on this one.

**Comment by pyrello** [comment]
After avoiding comments for this long, I would love it if we could never turn them on. They are a vector for spam and often times don't age well. I would suggest that we close this and re-open it if we ever get real pressure to add them.

**Comment by joewhitsitt** [comment]
Fair enough. I figured we would have run into it by now. This issue doesn't provide much value as-is.
