### ISSUE TITLE
Identify public facing instances of CKEditor 4 on D7 sites

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7224]
# Story

As a web team, we would like to understand where there are instances of public facing CKEditor 4 usage on D7 sites so we can better plan our path forward as it pertains to CKEditor 4 end of life.

# Proposed solution

**Comment by joewhitsitt** [comment]
For example, you can search for anonymous permissions for `use text format filtered_html` but there could be other formats with the WYSIWYG available. So doing a permission contains `use text format` will get you part of the way.

**Comment by briand44** [comment]
Grooming conversation.... potentially check permissions on text formats. LAWINRC has some anonymous user posting. Any commenting modules or discus module?

**Comment by joewhitsitt** [comment]
Started to think about this a bit:

```
SELECT *
FROM role_permission
JOIN role
ON role_permission.rid = role.rid
WHERE permission LIKE "%use text format%"
  AND role.name IN ("anonymous user")
```

Which I think can be compared with `SELECT name from filter_format`

Most sites have Filtered HTML, Full HTML and Plain text. Any matches for those or other formats would be an indication to me that there might be some public facing wysiwyg inputs worth looking into more. INRCLAW returns back for filtered_html.

We can dive deeper at that point (field list report, allowed formats, etc.), but that will at least give us size of the issue.

**Comment by joewhitsitt** [comment]
Results for 701-3:

~~dsp.research.uiowa.edu, use text format plain_text~~ _site launched v3 just hasn't been deprovisioned_
hawkeyespaces.uiowa.edu, use text format filtered_html - _might have been for the site-wide contact form. recommend removing the permission_
inrc.law.uiowa.edu, use text format filtered_html -  _used for crowd sourced content types. recommend changing permission to plain text and ensuring links and line breaks work. need to communicate this change._
iowareview.org, use text format filtered_html -  _not sure where it would be in use. probably just an oversight. recommend removing the permission_
medforms.sports.uiowa.edu, use text format filtered_html _not sure where it would be in use. probably just an oversight. recommend removing the permission_

**Comment by joewhitsitt** [comment]
From what I can tell the query should still work on CLAS and there are none. 

Logged in to math.uiowa.edu to check the permissions structure:

<img width="859" alt="Screenshot 2024-01-16 at 10 02 35 AM" src="https://github.com/uiowa/uiowa/assets/4663676/3bcba2e9-eb11-4633-8618-ca817e24e9e1">

**Comment by joewhitsitt** [comment]
Does the grad application have `@sites` type drush functionality?

**Comment by briand44** [comment]
>Does the grad application have @sites type drush functionality?

No, I believe there are only 6 sites left on that app though. Only three will be transitioning.

**Comment by joewhitsitt** [comment]
Graduate College results:

default - yes _(not active right?)_
gc - yes _(not active right?)_
iwp - yes - _available on comments. recommend changing permission to plain text and ensuring links and line breaks work. need to communicate this change._

**Comment by joewhitsitt** [comment]
I think removing the permission in these situations should be enough. We will most likely need to send an email for IWP and INRC.LAW.

Some of this might be packaged in features. We don't want this permission to revert so if that is the case, there might be a bit more work to repackage this and only this change.

**Comment by joewhitsitt** [comment]
@makurj we identified IWP as having the WYSIWYG editor exposed to anonymous users. Originally I thought this was through the comment form, but it appears anonymous users can no longer comment (e.g. https://iwp.uiowa.edu/comment/reply/2990#comment-form). With CKEditor4 reaching end of life, this seems like an unnecessary exposed risk for us and we would like to switch the permission off for anonymous users. If Anonymous users did have access to the editor anywhere, they will instead see a plain text editor. Do you need time to communicate this change or can we go ahead and proceed?

**Comment by joewhitsitt** [comment]
I have sent an email to INRC.LAW

**Comment by makurj** [comment]
https://github.com/uiowa/uiowa/issues/7224#issuecomment-1895959071

Thanks for bringing this to our attention. I would like this week to email IWP, and will reply here once I have confirmation from them.

**Comment by makurj** [comment]
IWP is okay proceeding with this change.

**Comment by joewhitsitt** [comment]
permission removed on:

hawkeyespaces.uiowa.edu
iowareview.org
medforms.sports.uiowa.edu
grad.prod.drupal.uiowa.edu
iwp.uiowa.edu

thankfully we didn't package up permissions often in features.

looking into dentistry. considering options for inrc.law.

**Comment by joewhitsitt** [comment]
no changed needed for dentistry. sent a follow-up to inrc.law with further detail.

**Comment by joewhitsitt** [comment]
waiting to hear back from inrc.law

**Comment by joewhitsitt** [comment]
Got the go ahead from inrc.law today. Going to pull the site locally as I think permissions are tracked.

**Comment by joewhitsitt** [comment]
Small snag. inrc.law allows edit submissions existing non-profit/grant content (reviewed, approved), but saved to the db as filtered_html format, the field is now disabled for anonymous.

<img width="844" alt="Screenshot 2024-01-23 at 11 25 37 AM" src="https://github.com/uiowa/uiowa/assets/4663676/43826d2c-ad00-4cca-8c90-0b535bcdef22">

**Comment by joewhitsitt** [comment]
Bigger snag than I originally thought.

- Accept the risk on this one site and do nothing. Perhaps move them up in the development queue?
- Accept the risk but with more spam protections in place to prevent database inserts.
- Accept the risk but provide a more stripped down text format would run into the same issue without a massive database update.
- Remove the ability for anonymous users to submit edits through the content type and setup webforms for each content type, duplicating fields for fairly easy copy/paste handling by site editors.
- Remove the ability for anonymous users to interact at all with these content types. Setup webforms for anonymous users to submit new/edits to existing.
- ?

Events probably gets the most submissions. I'd have to ask them how much content new/existing is submitted by non-hawkid visitors, but there was enough reason back when to develop this way in the first place.

**Comment by pyrello** [comment]
> Perhaps move them up in the development queue?

I'd be in favor of prioritizing the work sooner to move them off D7.

I'm not sure I'm following all of this, but it seems like the smallest slice that also removed the danger would be to set up a workflow for submitting edits to existing content via email or a webform submission.

**Comment by joewhitsitt** [comment]
Yes, the smallest slice for us. Quite a big change late in the game (d7) for the folks that own/use the website. Not disagreeing, just want to make sure that side of it is known.

**Comment by joewhitsitt** [comment]
Just wanted to remind myself on the "why" of this issue. Going to https://github.com/ckeditor/ckeditor4/blob/major/CHANGES.md and searching through the `Security updates` reveals several instances where carefully crafted content can get around sanitizing/validation and lead to XSS/JS execution.

**Comment by joewhitsitt** [comment]
Thinking ahead to d10+, this site will still need a solution if crowd-sourcing content is still needed.

**Comment by joewhitsitt** [comment]
I've reached out to the main website manager to get an idea about numbers (anonymous submissions, new vs edits, small edits, big re-writes, increasing/decreasing overall)

**Comment by joewhitsitt** [comment]
They don't have exact numbers but they estimate roughly six submissions every 4-6 weeks. Mostly edits. This is lower than I thought. Some of them are through webforms already because a while back we allowed uploads to the public file system while the content was being reviewed before publishing. This triggered a huge spam issue with stuff showing up in Google search results. Because these documents are needed for some of the content, those are routed through webform/email and web editors make the edits.

If we were to shut these content types down for anonymous users, there are a couple call to action buttons that would need to be updated and possibly a few webforms adjusted/created.

**Comment by joewhitsitt** [comment]
Emailed INRC and got the go-ahead to lock these content type forms down to anonymous users after setting up replacement webforms and updating the call to action buttons to point to them.

**Comment by joewhitsitt** [comment]
Created/repurposed webforms as a replacement to directly add/editing node content.
https://inrc.law.uiowa.edu/submit-grant
https://inrc.law.uiowa.edu/submit-event
https://inrc.law.uiowa.edu/submit-organization
https://inrc.law.uiowa.edu/submit-update

Updated call to action sidebar blocks and anonymous user permissions. `2e85889885ce94f691b0c8a3758a070a10d0931f` Going to deploy to prod and contact the site owners.

**Comment by joewhitsitt** [comment]
As mentioned in EoD, inrclaw customers could come back with requests related to their replacement setup, but we won't be adding anonymous access to CKE4 back so in terms of the issue, this is done. All other sites have already been addressed.
