### ISSUE TITLE
calendar view of alerts

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7234]
# Story

As an ITS site owner, I would like to have a calendar display of alerts so that users can quickly navigate the calendar to find alerts affecting particular dates.

# Additional Info

- Current calendar view of Alerts - https://its.uiowa.edu/alerts/calendar
- Displays all types of alerts
- Differentiate by category
- Include legend here
- Ability to view future and past alerts on calendar
- Would like improvements on mobile view of calendar

# Proposed Solution

**Comment by briand44** [comment]
Grooming conversation... There is a list option that can be turned on with FullCalendar that could be an option to make this more mobile friendly. Should be able to create a view using FullCalendar similar to Grad and Admissions.

**Comment by pyrello** [comment]
Here is an alternative module that might be worth looking into for calendar displays: https://www.drupal.org/project/calendar_view

It appears to be responsive for mobile out of the box: https://www.drupal.org/project/calendar_view

**Comment by joewhitsitt** [comment]
>Here is an alternative module that might be worth looking into for calendar displays: https://www.drupal.org/project/calendar_view

I'd be curious to know if it can handle differentiating based on alert category.

**Comment by cory-skeers** [comment]
https://www.drupal.org/project/calendar_view has a lot of promise, but there are some cons that would require some investment to get it to a workable state.

- Smart date's "all day" option doesn't translate correctly, and any "all day" events span two days
- Styling all needs to be re-created and added
- Multi-day events spanning over a week needs particular attention in styling
- The list view (eg mobile) displays all days in the month, leading to a long scroll even if there aren't many events to see

All in all, I think this could be a great module to change to in the future, but that the investment required could/should come at a different time.

**Comment by cory-skeers** [comment]
Question re: ongoing events. How should they be displayed on the calendar? By default, they display on the single day with the start time

Here we have two ongoing, a service degradation and an outage.
<img width="393" alt="image" src="https://github.com/uiowa/uiowa/assets/49074566/9b335c8d-1990-4602-a601-a956394d186a">

Once they are closed and an end time provided, they will span multiple days as needed, and so appear accurately as part of a historical record. But I'm unsure of how it works currently, or what the intended view would be, and if a single day without some other indicator of "ongoing-ness" might give the wrong impression.

**Comment by joewhitsitt** [comment]
Isn't the start and end date the same until they update the node with more detail? Ongoing was 0 duration right?

The current site has the start and end time in the bubble (when different) so when it does close it will illustrative of that.

**Comment by cory-skeers** [comment]
> Isn't the start and end date the same until they update the node with more detail? Ongoing was 0 duration right?

Yup, that's right, and translates to the default appearing on the calendar as a single day with a start time displayed.

> The current site has the start and end time in the bubble (when different) so when it does close it will illustrative of that.

That sounds like it function similarly to this, then. I think it's mostly in working with this calendar in isolation with made up examples that it stands out as a potentially odd pattern. I'm looking at it on the 13th, for instance, with ongoing outages/degradations going back to the 10th, so it appears on the calendar like there is nothing going on today, when both of those are still active.

But that's where after stepping away overnight I'm starting to think it's just my looking at only the calendar. The current alerts and status blocks we've just developed are the more appropriate source for that information than this.
