### ISSUE TITLE
Image Gallery Paragraph Bundle

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#724]
I think Drupal 8.8 fixes multi-media-uploading (alt text) so we could move forward with this paragraph bundle.

Single paragraph bundle with similar global fields (column-width, unique id, styles) and a multiple media upload reference field.

for MVP, I think we need to pick a lightbox type solution to render square thumbs similar to https://github.com/ITS-UofIowa/sitenow_paragraphs/tree/master/snp_image_gallery .

If media image doesn't already, we will need a title or caption field.

**Comment by joewhitsitt** [comment]
OSC has requested this be done similarly to the one we have here without image cropping: https://uiowa.edu/stories/committed-conquering-cancer

**Comment by joewhitsitt** [comment]
Done:

- [x] Paragraph bundle with multiple media upload and share sitenow paragraph fields (display title, title, styles, unique id, column width)
- [x] Masonry style/image style to meet OSC requirement
- [x] Colorbox grouping, prev/next/slideshow start-stop buttons and close button. Keyboard navigatable.

Left to do?
- [ ] Colorbox style adjustments (more flat, square, uiowa_bootstrap like)
- [ ] ~~Grid as default (SiteNow square?), masonry as a style option~~
- [ ] Caption field available upon upload, linked up to colorbox
- [ ] ~~Reveal focal point functionality on upload (needed for grid option).~~
- [ ] Accessibility improvements? https://www.drupal.org/project/colorbox/issues/3038515

**Comment by joewhitsitt** [comment]
I have asked @briand44 for service MVP left to do, but @pyrello if you want to work on any of these, feel free, otherwise I will revisit once I finish another lockup related task

**Comment by richardbporter** [comment]
~~Is there an example on the brand site of where/how this is used?~~
https://github.com/uiowa/uiowa/issues/724#issuecomment-582119918

**Comment by richardbporter** [comment]
> Grid as default (SiteNow square?), masonry as a style option

I don't think this needs to be done now.

**Comment by richardbporter** [comment]
>Reveal focal point functionality on upload (needed for grid option).

This is also not required now.

**Comment by richardbporter** [comment]
>Colorbox style adjustments (more flat, square, uiowa_bootstrap like)

Did the styles you wrote that I pushed address this?

**Comment by richardbporter** [comment]
>Title or Caption field available upon upload, linked up to colorbox

I'm struggling with this.

**Comment by joewhitsitt** [comment]
I think the grid option is necessary because it gives a more intuitive out-of-the-box sorting relationship between backend and frontend. I know this is an OSC sprint task, but we are building this as part of the SiteNow service. I can talk more about the hiccups with this option, but I have added enough to make it a working demo.

**Comment by joewhitsitt** [comment]
The a11y patch above does not apply and I found several colorbox accessbility concerns/issues I don't know what is needed to launch.

**Comment by joewhitsitt** [comment]
https://github.com/jackmoore/colorbox/issues/765

**Comment by joewhitsitt** [comment]
```joewhitsitt Feb 21st at 2:08 PM
Image “title” attribute: is not recommended as it can cause problems with screen readers. We were going to use the title field on media image to provide lightbox type image captions. Should we create an caption field instead? The same images can be placed in the wysiwyg and could confuse editors with the caption data attribute with the new media library functionality
3 replies

andrewmacpherson  3 days ago
It's not just screen readers. It presents accessibility problems for many other groups of users too. 
Suggest reading this article (from 2013 and still relevant; nothing much has changed).  https://developer.paciellogroup.com/blog/2013/01/using-the-html-title-attribute-updated/
Yes, I recommend using a separate field to manage visible lightbox captions. You'll have much more flexibility in the long run, with view modes, twig templates, etc.
Many old lightbox plugins use the HTML title attribute to store caption text, just because it was a convenient "spare" attribute. These days data-* attributes are a better thing to use, if you just need a temporary place to keep it until the lightbox is shown. You can use Drupal preprocess functions to put these attributes in place.
TPGTPG
Using the HTML title attribute – updated
tl;drIf you want to hide content from mobile and tablet users as well as assistive tech users and keyboard only users, use the title attribute.The detailsThe HTML title attribute is problematic.
Jan 15th, 2013

andrewmacpherson  3 days ago
We should probably update that help text from the imagefield configuration form. I'll file an issue about that.```

**Comment by joewhitsitt** [comment]
Added a long formatted "Global Caption" field to the image media type and adjusted Colorbox styles to deal with the potentially long text. Changed carousel to display global caption if provided with the ability to override locally on the carousel item. Added a11y improvements version of colorbox as a libraries override.

The big downside to all of this is the global caption field and the data-caption faux field implemented on the WYSIWYG. Might be nice to link the two up at some point.

**Comment by joewhitsitt** [comment]
Seeking a11y review: #1104
