### ISSUE TITLE
IWP D7: Delete File

### ISSUE THREAD

**Issue by makurj** [uiowa/uiowa#7243]
The user would like https://iwp.uiowa.edu/sites/iwp/files/BTL%20IDB%20NEW%20Final_10_2020_small%20file_0.pdf file deleted from IWP D7's site. It was linked from this page: https://iwp.uiowa.edu/page/2020-between-the-lines.

Deleting it from the "Browser server" pop-up did not work. It could be file perms or something else that's causing the deletion to not go through.

![image](https://github.com/uiowa/uiowa/assets/52135878/6c3deab9-aef0-423e-811f-66cb6efa7479)

Thanks, @pyrello for helping troubleshoot this.

**Comment by pyrello** [comment]
My best guess is that this needs to be directly deleted from the server.

**Comment by briand44** [comment]
When I try to delete through file browser I get a message that pops up quick saying the file is in use by another application. Couldn't get a screenshot because the message disappeared to quickly.

**Comment by briand44** [comment]
I was able to ssh into the server and remove the file.

**Comment by makurj** [comment]
Great! Thanks, Brian!
