### ISSUE TITLE
Second email - V1 standard site request campaign

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#7248]
# Motivation
We would like to send a follow-up reminder to folks who have not yet requested a site by 1/31 or 2/1 (2 weeks before the deadline to request a V3 site).

# Proposed solution
- Draft a second email
- Generate a new email list using report command and filter out invalid emails
- Get approval from team/comms committee
- Send it!

**Comment by briand44** [comment]
Grooming conversation... Testing command to make sure sites that have been requested are dropping off as expected and draft the email. We will need to run the command to get the list prior to sending to make sure the list is up to date.

**Comment by joewhitsitt** [comment]
>Testing command to make sure sites that have been requested are dropping off as expected

Spot checked based on recent provision PRs and compared with the population list currently in dispatch. websites like wold, price, chen, fisher are no longer included in the output. Also, the list is ~202 compared to the 359 members of the population.

**Comment by joewhitsitt** [comment]
Added a draft doc for the reminder email (access through project card): https://github.com/orgs/uiowa/projects/20/views/1?pane=issue&itemId=50803708

**Comment by joewhitsitt** [comment]
Will re-run the email list command before email goes out and will remove idcard.fo.uiowa.edu from the list.

**Comment by joewhitsitt** [comment]
Looking for more feedback and/or approval https://github.com/orgs/uiowa/projects/20/views/1?pane=issue&itemId=50803708

**Comment by joewhitsitt** [comment]
Moved the finalized draft to https://apps.its.uiowa.edu/dispatch/communications/1290784634 and forwarded an example email to its-web.

Closing this with the plan to finish in https://github.com/uiowa/uiowa/issues/7296
