### ISSUE TITLE
SSL for new sites

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#7250]
~SSL for *.advisingcenter.uiowa.edu on uiowa03~
~SSL for transparency.uiowa.edu on uiowa05~
~SSL for drivingassessment.uiowa.edu uiowa05~
~SSL for iowateacherintern.org on on uiowa05~
~SSL for  iaapt.us  on uiowa05~

**Comment by briand44** [comment]
not sure how we decided to put *.advisingcenter.uiowa.edu on uiowa03 but the new certs have been created. Closing this.
