### ISSUE TITLE
Allowlist new EIPs

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7252]
# Story

As a web team, we would like to have our new EIPs for all of our applications allowlisted so that all of our existing functionality continues to work as expected as we transition to Acquia Cloud Next.

# Additional Info

Allowlists needing updated:

- Splunk firewall
- CleryEdge
- I don't think the Thank You functionality requires allowlisting anymore. The existing IPs could likely be removed from that allowlist.
- Any others?

If we do need to update allowlists to include EIPs from all applications there would be a large number compared to what we have allowlisted in the past. 2 for each application for each environment. So uiowa01 would have 6 EIPs (2 for prod, 2 for stage, 2 for dev). Log forwarding is only setup for prod environments currently.

Current applications with new EIPs:

- uiowa01
- uiowa02
- uiowa03
- uiowa04
- uiowa05
- uiowa06
- uiowa701
- uiowa702
- uiowa703
- UIClas
- UIGradCollege
- Dentistry
- uiowa

# Proposed solution

- Communicate with ISPO about the new production EIPs so that log forwarding will work once we are on Cloud Next
    - Currently still trying to sort through an issue with Firewall rules for the secondary load balancer as well. There is a ticket open with Acquia about this.
    - Only prod EIPs currently need allowlisted for Log Forwarding since we aren't currently forwarding logs for dev and stage.
- Communicate with Clery Edge about the new EIPs for dev?, stage? and prod for uiowa04?
- Communicate with HR (Thank You Program API) that they can remove previously allowlisted IPs
- Update our documentation about what IPs have been allowlisted https://iowa.sharepoint.com/sites/drupal-developer-documentation/SitePages/Miscellaneous/On-premise%20server%20ACL/On-premise%20server%20ACL.aspx
- Respond/Close acquia tickets once all new EIPs have been allowlisted - **Update** This may no longer be needed as I believe these were closed by Acquia.

**Comment by joewhitsitt** [comment]
Sent the uiowa04 IPs to CleryEdge contacts.

**Comment by joewhitsitt** [comment]
>Update our documentation about what IPs have been allowlisted

https://iowa.sharepoint.com/sites/drupal-developer-documentation/SitePages/Miscellaneous/On-premise%20server%20ACL/On-premise%20server%20ACL.aspx

It wasn't easy, but this part is done. Noticed that grad/uiowa06 doesn't have dev/stage EIPs. @briand44 is that something we need to follow-up on or is that expected?

**Comment by joewhitsitt** [comment]
Sent an email to Alex and ISPO-Splunk about allow listing the new prod EIPs

**Comment by joewhitsitt** [comment]
Sent an email to the AIS HR Manager Lookup API team.

**Comment by briand44** [comment]
>Noticed that grad/uiowa06 doesn't have dev/stage EIPs.

Hmm... I reached out to Brittany about this. I assumed these had EIPs based on the tickets

https://acquia.my.site.com/s/case/500Pb000006E1C5IAK/network-configuration-changes-may-be-needed-for-uiowa06-before-your-acquia-cloud-next-upgrade

https://acquia.my.site.com/s/case/500Pb000006Dz76IAC/network-configuration-and-minor-site-changes-needed-for-uigraduatecollegeuiowa701-before-acquia-cloud-next-upgrade

**Comment by joewhitsitt** [comment]
Marie says that CleryEdge has allowed the new IPs

**Comment by joewhitsitt** [comment]
ISPO is going to review firewall rules and make sure the new EIPs will be let through for log forwarding.

**Comment by joewhitsitt** [comment]
>The firewall rules for the datacenter are in place, I’m just waiting on a second set of firewall rules on the Splunk server. Once that’s in place we should be good to go.

A response from AIS HR folks is not a blocker to this.

I think that we are just waiting on Acquia to establish non-production EIPs for uiowa06 and UIGradCollege.

**Comment by briand44** [comment]
>I think that we are just waiting on Acquia to establish non-production EIPs for uiowa06 and UIGradCollege.

Waiting on ^^ for what? We don't need to allowlist those for anything currently do we?

>I’m just waiting on a second set of firewall rules on the Splunk server.

Seems like ^^ is what we are waiting on to consider this done, right?

**Comment by joewhitsitt** [comment]
Seems like you tied the Acquia ticket to this issue. Wasn't sure.

It sounded like the splunk part was just a matter of time and that there was not going to be any action need from us.

**Comment by briand44** [comment]
From Alex:

>I just got notified that the host firewall rules are also in place now, so we should be good. Let me know if you notice any issues.

I think we can close this now.

**Comment by briand44** [comment]
>I think that we are just waiting on Acquia to establish non-production EIPs for uiowa06 and UIGradCollege.

This is done now as well.
