### ISSUE TITLE
Limit artist filter on gallery to only show people of type artist

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7260]
https://facilities.prod.drupal.uiowa.edu/campus-spaces/art-campus/art-campus-gallery

![Image](https://github.com/uiowa/uiowa/assets/1017022/f8bb185b-27f4-4473-ad92-b8a96758c553)

The artist filter should only show people of type artist rather than all people.

# Proposed Solution

- Adapt existing code example to limit options in drop down to just artist person type

**Comment by briand44** [comment]
Grooming conversation... We think we need to write code to process and remove the options we don't want to show (people that don't have a person type of "artist"). We have some existing code examples but not sure where exactly those are right now. Possibly IISC has an example.

**Comment by bspeare** [comment]
Pulled this work in between reviewing prs today: https://github.com/uiowa/uiowa/pull/7274.
