### ISSUE TITLE
WhitmanWeb site has a very large menu and the “technical difficulties” 

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#7266]
# Problem
The WhitmanWeb site has a very large menu and the “technical difficulties” screen popping up when navigating to the page or trying to make a change has become more frequent recently.

# Steps to reproduce
Go to https://whitmanweb.iwp.uiowa.edu/admin/structure/menu/manage/main. 

# Proposed solution
Revisit https://github.com/uiowa/uiowa/pull/6178/files?

**Comment by briand44** [comment]
Grooming conversation... Previously we updated memory for specific menu routes. We should check logs see if it is max_input_vars or out of memory, etc.

PR where this was addressed for engineering and cmd? https://github.com/uiowa/uiowa/pull/6178

Workaround would be to modify menu items from the nodes themselves.

**Comment by briand44** [comment]
Discussed slicing this to a small probe to understand better.

**Comment by bspeare** [comment]
The log message for this is:

 `php-error web-33204 [12-Jan-2024 15:53:26 UTC] PHP Warning: Unknown: Input variables exceeded 3000. To increase the limit change max_input_vars in php.ini. in Unknown on line 0 request_id="v-b90065f0-b162-11ee-b51c-2fd1557d3881"`

**Comment by bspeare** [comment]
As @joewhitsitt mentioned in https://github.com/uiowa/uiowa/issues/1996:

Our options remain the same:

1. Up our max_input_vars number... again.
2. Wait for core to fix this issue
3. https://www.drupal.org/project/bigmenu, however bigmenu doesn't look very active these days https://www.drupal.org/project/bigmenu/issues/3117891

Seems like option 1 is still our best option.  Does anyone have a preference?  Would we go to `ini_set('memory_limit','512M')` next?

**Comment by joewhitsitt** [comment]
Wait. memory_limit and max_input_vars are different things. Did you see what the error was specifically? If it is "exhausted allocated" whatever that points to memory_limit and as Brian mentioned we might not be able to raise it higher than 256.

**Comment by joewhitsitt** [comment]
just saw the message above... so in this case we would not change the memory_limit  in that existing code.

**Comment by joewhitsitt** [comment]
>Acquia does not recommend setting your environment’s max_input_vars value higher than 2500. Larger values are considered a risk to site performance and security, and should be avoided whenever possible.

**Comment by bspeare** [comment]
@joewhitsitt what is our current setting?

**Comment by joewhitsitt** [comment]
3000

**Comment by joewhitsitt** [comment]
At this point, I'd vote to create a feature split with big menu and turn it on for sites we need it. they have d10 compatibility release and is a pretty simple module. there is a core scaling issue here and until they resolve it we can't offer the same experience for some big sites that choose to structure their content this way.

**Comment by bspeare** [comment]
It sounds like the core solution is to just add a message to increase `max_input_vars` if this error occurs on a page: https://www.drupal.org/project/drupal/issues/1565704.    Instead of big menu, would we ever want to create a "Secondary menu" option to reduce users from using the main menu for all links?
