### ISSUE TITLE
SiteNow January 2024 Newsletter

### ISSUE THREAD

**Issue by e-marie-w** [uiowa/uiowa#7269]
### Issue/Solution
Provide a "release notes" type article of finished/done features/updates and publish to website, then send out dispatch email.

- [x] Create draft and update the parking lot card with an edit link (https://sitenow.uiowa.edu/node/586/edit)
- [ ] Add "release notes" covering the month of v2/v3 default profile enhancements and webmaster/edit visible bug fixes.
- [ ] See the previous month's article as an example.
- [ ] Bullet points from demo stories slide per week: https://drive.google.com/drive/folders/1EehKUjxCbakaB9FchrGhAbaxuRbqyDGW?usp=sharing.. and/or from Web Community sprint demo announcements https://webcommunity.sites.uiowa.edu/updates/2023/02/sprint-demo-149-february-16-2023
- [ ] If any notable site launches are included, make sure the sites are linked.
- [ ] Get at least one team member to look over the draft before publishing.
- [ ] Since the draft was started earlier, adjust the publish date/time, publish, get the link to the article.
- [ ] Dispatch email with link to article. (To get access, send an email to [dispatch-support@uiowa.edu](mailto:dispatch-support@uiowa.edu) to have the account provisioned. Provide your hawkid and mention the CSI:drupal group)
  - [ ] Modify SiteNow Announcements Template (tweak opening line, update the article link, any other editorial adjustments)
  - [ ] Clone an old communication off SiteNow Announcements campaign
    - [ ] Use SiteNow Announcements population, template, suppression list, bypass approval.
    - [ ] Turn off Dispatch "test mode" to send out email.
    - [ ] When scheduling, check the "archive" option so that there is an RSS instance we can use in the future. I don't think this can be done after the fact.
- [ ]  Turn on Dispatch "test mode" after email is successfully sent.
- [ ]  Take a moment to check dispatch and google analytics on whether these articles are being read.
- [ ]  Create the next months's issue and copy all this bullet list into it, removing the checked boxes if any.

**Comment by e-marie-w** [comment]
Draft article: https://sitenow.uiowa.edu/news/2024/01/updates-january-2024

**Comment by bspeare** [comment]
https://sitenow.uiowa.edu/news/2024/01/updates-january-2024 is ready to review.

**Comment by cory-skeers** [comment]
> https://sitenow.uiowa.edu/news/2024/01/updates-january-2024 is ready to review.

This looks good to go to me!

**Comment by bspeare** [comment]
Thanks @cory-skeers!

**Comment by bspeare** [comment]
This is done.
