### ISSUE TITLE
Theme Facilities Projects

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7278]
# Story

As a Facilities site owner, I would like our projects to look nice.

# Additional Info

The majority of projects only contain info from the API so we should try to theme them in a way where they look good with just that info but also when an image and additional supporting info is added manually.

Current example with image and webcam:
https://www.facilities.uiowa.edu/project/0614902

Current example with just info from API:
https://www.facilities.uiowa.edu/project/0847001

# Proposed solution

- Mockup not needed
- Setup template in layout builder
- Style similar to existing site
- Make sure looks good if not all manual info added

**Field instructions:**
- [x] Pre Bid Date - only output if is greater than today.  
- [x] Pre Bid Location - only output if pre bid date is greater than today 
- [x] bidOpeningDate - looks like only output if pre bid date is greater than today 
- [x] Estimated Cost of Construction, if this field is empty output "TBD" text. 
- [ ] Title - `buildingName . ' ' . projectTitle` is currently being used on the project page on https://www.facilities.uiowa.edu/project/1062101 creating duplicate titles like "Parking Lots and Ramps Parking Lots and Ramps - 2024 Surface Lot Maintenance"
- [ ] Building page view outputs `buiProjectId - projectTitle`. 
- [ ] Capital and Featured views projects pages outputs `buildingName . ' - ' . projectTitle`

**Comment by briand44** [comment]
We may want to confirm the size is appropriate once all the fields have been created for projects.

**Comment by bspeare** [comment]
This is ready for review at https://github.com/uiowa/uiowa/pull/7285.

**Comment by briand44** [comment]
From Facilities...

>No need to prepend the project title with the building name.
