### ISSUE TITLE
Scheduled job to run project import

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7303]
# Story

As a Facilities site owner, I would like projects to get updated twice a day so that people can get up to date project info.

# Additional Info

>It’s more important that the project info updates in more “real-time” than the buildings if possible. As soon as bid information, budgets, etc are available, multiple stakeholders look for it on the project pages. Is it cumbersome to set it up that way? If so, maybe twice a day is a good compromise.

# Proposed solution

- scheduled job that runs twice a day that calls the drush command to import/update/remove projects
- `fm-projects` is the drush command to set a scheduled job on uiowa03
- Look at `facilities.uiowa.edu - building import` as an example in the scheduled jobs

**Comment by briand44** [comment]
Grooming conversation.... Right now we don't have specific times when this needs to run. I can try and get clarity there but assuming once overnight and once during business hours should be acceptable. Maybe noon and midnight but I'm not sure what all other things run and at what times so open to suggestions here. Also curious if there are any concerns about this running twice a day.

**Comment by briand44** [comment]
They mentioned running the import mid-morning and mid-afternoon would be their preference if that works from our end.

**Comment by briand44** [comment]
Joe suggested 9 and 1

Reasoning is that it is after scheduled deployments and often before any morning deployment and then again after the lunch spike but before we are able to get a security release out.

**Comment by joewhitsitt** [comment]
^^ reasoning is that it is after scheduled deployments, early scheduled jobs in the AM and often before any morning deployment. Then again after the lunch spike but before we are able to get a security release out after it is announced.

**Comment by joewhitsitt** [comment]
I don't think a single crontab can be structured to handle both of these times daily so I created an AM and PM scheduled job for 15 UTC (9AM CT?) and 19 UTC (1PM CT?)

**Comment by joewhitsitt** [comment]
It fired at 9:00. I was able to see the content overview change with project content updates. No splunk data :(
