### ISSUE TITLE
Day after notification for SiteNow v1 Standard sites that did not request a v3 site

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7308]
“This site is now queued for removal in the future...reach out if you believe this to be in error.”

# Proposed Solution

- Draft comms and get approval

**Comment by joewhitsitt** [comment]
Whipped up a little something here for review: https://iowa.sharepoint.com/:w:/r/sites/CSI-Drupal2/Shared%20Documents/General/day_after_sitenow_v1_standard_email.docx?d=w8703675c8f9848319d65006124f7d65a&csf=1&web=1&e=bpCcpA

**Comment by joewhitsitt** [comment]
If folks have a moment, a quick review of the draft would be appreciated ^^

**Comment by briand44** [comment]
Looks good to me. My only thought/question/suggestion would be should we include the link to https://sitenow.uiowa.edu/sitenow-v1-standard-platform-shutdown in there somewhere to provide some additional context if folks somehow missed the previous emails?

**Comment by joewhitsitt** [comment]
I added something but willing to adjust if needed.

**Comment by mjoneill** [comment]
Reviewed. Made some changes.  Not sure if we can actually put the site URL in the subject line.  

Reject anything you feel passionate about.

**Comment by pyrello** [comment]
Not sure if you're still looking for feedback, but I thought that it looked good and I liked how concise it was.

**Comment by joewhitsitt** [comment]
Thanks all for the feedback. The draft has been updated by accepting changes. I went with Word on the grammar change. Calling this done. I'll update #7329 with a reference to the doc.
