### ISSUE TITLE
Send third ("day before") communication for SiteNow v1 Standard sites

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7314]
# Info

We drafted third email as part of https://github.com/uiowa/uiowa/issues/7307 but we still need to send it.

Notes from last communication https://github.com/uiowa/uiowa/issues/7296#issuecomment-1919758694

# Proposed solution

- Run report to get population list and update in Dispatch
- Confirm list is up-to-date with https://github.com/uiowa/uiowa/issues/7261
- Schedule communication and send

**Comment by briand44** [comment]
Blocked until Feb 13th.

**Comment by joewhitsitt** [comment]
Had to temporarily downgrade to pull the list [(see thread)](https://iowaweb.slack.com/archives/C0164FNN1PV/p1707839215031869). Scheduled for 11.
