### ISSUE TITLE
Extra <span> breaking button text styling

### ISSUE THREAD

**Issue by cory-skeers** [uiowa/uiowa#7325]
short version: Manually moving content over from D7 site, and it's adding a few extra `<span>`, which in the button removes the text styling.

![Image](https://github.com/uiowa/uiowa/assets/49074566/9ea7e09d-7aca-45a6-a5e8-d6ad7c36f5b1)

The fix is just to remove the extra span(s), but with lots of manual migrations on the horizon, might be worth looking into.

The example page this one came from was https://clas.uiowa.edu/philosophy/resources/news/prof-carrie-figdor%E2%80%99s-online-video-lectures-basics-folk-psychology-have-been-released. There is some extra HTML within and surrounding the button that is not in `<span>` tags, but I think as part of copy-pasting and saving in a ckeditor field, resulted in excess plain `<span>` tags.

![Image](https://github.com/uiowa/uiowa/assets/49074566/f0737f1f-e459-4a64-9075-9b980dd60c78)

**Comment by bspeare** [comment]
To fix this we might just want to adjust https://github.com/uiowa/uids/blob/4.x/src/scss/components/button.scss#L71 to be `span[class*="fa-"]` and it should solve the problem.
