### ISSUE TITLE
Send day after communication for SiteNow v1 Standard sites

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7329]
# Info

We drafted the day after email as part of https://github.com/uiowa/uiowa/issues/7308 but we still need to send it.

Notes from 2nd communication https://github.com/uiowa/uiowa/issues/7296#issuecomment-1919758694
Third Communication - https://github.com/uiowa/uiowa/issues/7307

# Proposed solution

- Run report to get population list and update in Dispatch
- Add [draft](https://iowa.sharepoint.com/:w:/r/sites/CSI-Drupal2/Shared%20Documents/General/day_after_sitenow_v1_standard_email.docx?d=w8703675c8f9848319d65006124f7d65a&csf=1&web=1&e=bpCcpA) to dispatch 
- Schedule communication and send
- Share with Michael/team for visibility to help guide #7351

**Comment by joewhitsitt** [comment]
With https://github.com/uiowa/uiowa/issues/7354, downgrading to get the report will be necessary

**Comment by joewhitsitt** [comment]
waiting for a test email to reach the its-web inbox, otherwise it i think it is ready for scheduling this morning.

**Comment by joewhitsitt** [comment]
It was mentioned in standup that www domains might be getting reported back even though a non-www site has been requested and merged into main.

I've removed www.iowateacherintern.org (non-www in main), perception.radiology.uiowa.edu (redirect, its-web email), www.iowahumanrights.org (non-www in main)

**Comment by joewhitsitt** [comment]
scheduled for 10:15
