### ISSUE TITLE
Email to nearest local web/comms leadership indicating that a site in their ecosystem is slated for removal.

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7351]
# Story

As a web team, we would like to notify local web/communications leadership about any SiteNow v1 standard sites that are in their ecosystem that are queued for deactivation.

# Proposed Solution

- Run report
- Share with Michael/Team.
- Manually audit/identify what unit/department/college the site falls under?
- send emails to local web/comms contact with the list of sites relevant to them to verify deactivation?
- Provide timeline for them to follow up with us?
- Ali asked that MO look at the analytics for these sites and make sure we aren't about to nuke something that sends high volumes of high value traffic

**Comment by briand44** [comment]
Grooming conversation... Give unit leaders/marketers an opportunity to be made aware of any sites that are queued for deactivation. Share with OSC leadership as well. Can we share the entire list with Campus Communicators or is there sensitivity there? Site url, contact/requestor, webmasters would be useful info to share. Should be around 40 sites based on current report. Socializing this can be happen through Michael.

Going to pull the report and share with Michael/team as part of #7329 and then we can groom what to do with it as part of this slice.

**Comment by joewhitsitt** [comment]
Keep in mind that the report is returning some WWW domains for websites that have requested a non-www v3

https://github.com/uiowa/uiowa/issues/7329#issuecomment-1946321272

**Comment by bspeare** [comment]
Grooming conversation:

1. MO to update Sharepoint doc where the 40 sites have "Nearest local governance" column
2. Update Sharepoint doc with recent sites that have clearance to be removed from its-web inbox (list below)
3. Email (MO will email) nearest local governance contact regarding the site deactivation
4. Wait for email responses from nearest local governance before deactivating sites
5. After two emails with no response, we plan to remove the site

**Recent sites that can be removed from its-web email correspondence:** 
- https://copstudy.lab.uiowa.edu/
- https://immigrantrefugeehealth.org.uiowa.edu/
- https://interprofessional.uiowa.edu/
- https://www.interprofessional.uiowa.edu/
- https://tranel.lab.uiowa.edu/

**Comment by briand44** [comment]
Blocked from sending to local web/comms leaders until we get the go ahead from our leadership.

**Comment by pyrello** [comment]
Any update on this?

**Comment by mjoneill** [comment]
In process, was stuck with me on scheduling. Lower priority than other things cropping up.  I should have all the conversations scheduled before I leave for MA.

**Comment by mjoneill** [comment]
> In process, was stuck with me on scheduling. Lower priority than other things cropping up. I should have all the conversations scheduled before I leave for MA.

MTGs with all local governing authorities are scheduled.

**Comment by briand44** [comment]
I am closing this as local unit leaders were communicated with long ago. We have two sites left that we need to work through (got answers on 1, still waiting to hear on the other) but we can work through those on #7355
