### ISSUE TITLE
ITS Feedback on alerts

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7360]
**Alert node add/edit form**

- Can we remove the title field? It's a mandatory field, but it appears that it is overwritten with type of alert, service impacted, and building. If it's going to be overwritten, do we need to include it AND make it mandatory? title vs. additional title details. We don't currently have a title field on the alert template, only additional title details. If nothing is entered into additional title details, the title of the alert will programmatically be created based on type of alert, service and building selected. 
- Scheduling options will be new for editors, and we'll need to focus on training here to make sure folks know when to use it and how it works.  Can we modify the explainer text? Don't have it drafted yet, but I can put something together. Is that something I'll have access to do?
- Can we remove the Summary box since we're asking people to leave it blank? 

**Alert Status page** - https://its.prod.drupal.uiowa.edu/testing-new-alert-thing

- Can we move the Apply and Clear buttons below filters...both James and I thought it only applied to the search box
- Jamie commented that the search box was huge, but I don't hate it. 
- The planned maintenance and service announcements look very similar. Outage and Service Degradation stand out because of their coloring and the icon. Can we change the look for either planned maintenance or service announcement so they differ? 

**Alert Update display**

- Need the word "Update" on the display of alert updates somewhere...the clock icon doesn't scream "update"
- Can we get the list of updates to display in chronological order where most recent update is at the top? 

# Proposed Solution

- [x] title has been removed, just be careful to not reintroduce (config should be updated manually)
- [x] #7384
- [x] Make summary collapsed
- [x] offer sidebar option but we can't move the buttons with this design - similar to https://classrooms.uiowa.edu/spaces/find-university-classroom
- [x] Add "Update" heading to updates
- [x] get the list of updates to display in chronological order where most recent update is at the top - either through code or views

**Comment by joewhitsitt** [comment]
>Can we remove the title field? It's a mandatory field...

This is a config bug that @cory-skeers mentioned while working on https://github.com/uiowa/uiowa/pull/7359

**Comment by briand44** [comment]
@cory-skeers mentioned he thinks he resolved the issue with the title showing here.

**Comment by briand44** [comment]
Badges have been updated https://github.com/uiowa/uiowa/pull/7359#issuecomment-1947191944

**Comment by briand44** [comment]
I reached out to Adrienne and James about putting the alert status filters in the sidebar. It looks like Adrienne is out until Wednesday though so we might not get an answer right away. If we get to a point where this answer is holding us up, I would try the sidebar approach.

**Comment by cory-skeers** [comment]
Unassigning myself for now, in case anyone else wanted to jump in on this.

Didn't get very far this morning. I'd started with the form updates, but running into issues making any changes to the alert form, including just changing it to not show the summary by default. Any updates and export I do then leads to mismatched config errors.

**Comment by bspeare** [comment]
I started some of the work here in https://github.com/uiowa/uiowa/pull/7375/files and added checkboxes on the proposed solution if someone wants to pick this up and finish the remaining items.

**Comment by cory-skeers** [comment]
> update help text on scheduling once they provide it and address weight issue - should this even be here?

https://github.com/uiowa/uiowa/issues/6637 looks like we did intend to include the scheduling across the alerts feature, and not just facilities, so we likely just need to update the weighting to get it in the right spot.

I'm leaving that part for now, so it can be done alongside the help text once we have that.
