### ISSUE TITLE
Remove vulture redirect on perception.radiology.uiowa.edu

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#7372]
perception.radiology.uiowa.edu vulture redirect is no longer needed.

**Comment by briand44** [comment]
I put in the request for this to be removed. Once removed we'll want to let Hostmaster know they can reclaim.

**Comment by briand44** [comment]
They changed their mind and decided they still need this redirect as they have print materials referencing this url. I cancelled the request to SAS.
