### ISSUE TITLE
Daily digest emails

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7373]
# Story

As an ITS site owner, I would like an email digest of alerts to be sent to our subscribers daily so subscribers can be notified about any active alerts.

# Additional Info

Current example

![Image](https://github.com/uiowa/uiowa/assets/1017022/34048bc6-22b1-4161-80b9-47cf04c63a8a)

**Email info**

Sends daily at 7 a.m.

Subject, From and To can stay the same.

Format date and times according to #7122 

Output Planned Maintenance below the other alert types similar to how it is currently being handled and Ongoing Maintenance last.

Keep related links

# Proposed Solution 

- Construct a drush command similar to brand_core that triggers an email that can then be scheduled for 7 AM daily in PROD.
- Building off of #7350 by trying to use the same EmailBuilderBase but with a different subtype, the email details and output should largely be the same. Since alert node titles now combine services, make sure services and buildings are included if multiple.
- Make sure the drush command or the email writes to drupal watchdog so that we can trace whether problems are with Drupal or Teams.
- Account for the different buckets of alerts: active outages, service degradation and service announcements. Planned Maintenance - upcoming planned maintenance in next 7 days. Ongoing Maintenance - Planned maintenance that has already started but is not yet closed.
- Prevent sending to teams outside of PROD by using an environment check.

**Comment by joewhitsitt** [comment]
In D7 - its.uiowa.edu/modules/custom/its_core/its_core.cron.inc `alerts_digest()`

its.uiowa.edu/modules/custom/its_core/theme/alerts-digest.tpl.php

**Comment by briand44** [comment]
Grooming conversation... Date formatting - Follow the lead of work done in #7350. `EmailBuilderBase` class has subtypes, should call that and than add any additional logic for this email type? Alerts - active outages, service degradation and service announcements. Planned Maintenance - upcoming planned maintenance in next 7 days. Ongoing Maintenance - Planned maintenance that has already started but is not yet closed. Refer to current logic in ^^ if needed. Schedule job that calls drush command to run daily at 7am similar to building import. Syslog logging would be nice to trace sending of email. Drush command is not currently part of #7350. Include services and building references if multiple. Check environment to avoid sending from dev/stage.

**Comment by joewhitsitt** [comment]
EmailBuilderBase subtypes https://github.com/uiowa/uiowa/pull/7397/files#diff-a6aea6ff90caefd0312c50d901e664c029bba591f87535f0e2dc701bd67cfe20R16

**Comment by joewhitsitt** [comment]
Depending on if this is pulled together via a query or views, the function here https://github.com/uiowa/uiowa/blob/main/docroot/sites/its.uiowa.edu/modules/its_core/its_core.module#L162 could adjusted to reduce duplication of constructing a render array.

**Comment by joewhitsitt** [comment]
i'd like to finish this as it is fresh in my head
