### ISSUE TITLE
Mockups of a support article and support landing page

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7378]
# Story

As a web team, we would like to create some mockups of a support article and a landing page to search/filter support articles so we can get feedback and help determine how we should build these.

# Additional Info

Epic with some info - https://github.com/uiowa/uiowa/issues/6191
- They would like to migrate support articles from their existing website.
- Separate content type? title, short desc, body, faqs (accordions), infocenter, category (single), tags, moderation.
- Published date is not important but last updated date is.
- Accordions are still important
- Categorization and sorting on the infocenter still a big thing (draggable views?). They are looking for suggestion on how to best categorize and display these support articles. Some infocenters have over 100.
- Single infocenter assignment (serves as content owner)
- Don't need internal support information on support articles and no longer need separate internal support article content type.
- They also are looking into Chat Bots. This is something they have seen others have success with. Not sure how this relates at this point but worth noting.
- **They mentioned the Help Desk currently references/uses the node id when supporting campus. I'm not sure I understand exactly how they are currently using this and if there would be a reason to migrate the old node id into a field on the new site or if they can just change their process to not be dependent upon the node id?

Exist examples of support articles:
- https://its.uiowa.edu/support/article/111136
- https://its.uiowa.edu/support/article/125731

Existing landing page - https://its.uiowa.edu/support - currently using Google Search to search only content at `site:its.uiowa.edu/support/article/*`

# Proposed Solution
- Support landing page could look similar to https://sandbox.prod.drupal.uiowa.edu/all-services-and-software-copy
  - Can search knowledge base and support library be combined?
- Article mockup could use card sidebar layout with card showing meta info like:
  - Article number
  - Last updated
  - Service
  - Category

**Comment by bspeare** [comment]
Here is the support article mockup: https://sandbox.prod.drupal.uiowa.edu/phishing-examples-0

**Comment by bspeare** [comment]
Here is the search landing page: https://sandbox.prod.drupal.uiowa.edu/search-our-knowledge-base

**Comment by bspeare** [comment]
These are ready for feedback:

- **Article mockup:** https://sandbox.prod.drupal.uiowa.edu/phishing-examples-0
- **Support landing page mockup:** https://sandbox.prod.drupal.uiowa.edu/search-our-knowledge-base

For https://sandbox.prod.drupal.uiowa.edu/search-our-knowledge-base, the key difference from https://its.uiowa.edu/support is that the search and article service library filters have been combined in the same form and I have set the "Popular Support" Articles as the default display under the form.

**Comment by joewhitsitt** [comment]
I like the sidebar on that support article! I am curious if that would be a good pattern for other content in the future or if our traditional boxed sidebar is preferred for most situations.

**Comment by bspeare** [comment]
I like that suggestion @joewhitsitt.  It is currently in use in the narrow articles: https://ilr.law.uiowa.edu/news/2024/01/major-questions-doctrine-boundaries-interpretive-law.

**Comment by briand44** [comment]
>have set the "Popular Support" Articles as the default display under the form.

Curious about your thinking as to how we output popular support articles by default on this display? Is this separate from the views search/filter? Would we need to provide ability to use the Featured Content for support articles? Something else?

**Comment by bspeare** [comment]
@briand44 how often do they change them?  If not very often, this could be the no results text of the view or a block placed under the view.

**Comment by bspeare** [comment]
I've updated https://sandbox.prod.drupal.uiowa.edu/search-our-knowledge-base to have better distinction between the view results and the popular support articles.

**Comment by briand44** [comment]
We didn't get much feedback on the mockups today as we were running out of time when we got to this. They did mention that most traffic to support articles is from the service pages since all the support articles are currently listed there. They don't think they need the support article landing page with searching/filtering capabilities going forward if they can get to all of these from an individual service page.

They also mentioned they don't use keywords currently for support articles. I don't think these were represented in the mockups but is a field they currently have but don't need going forward.
