### ISSUE TITLE
BLT/Drush Commands - deprovisions, etc.

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7380]
# Motivation

The deprovision and transfer commands currently call getApplicationFromDrushRemote which fetches a modified `status` drush command that includes the application name. There is code related to this customization here: \Drush\Commands\UiowaCommands::alterStatus and \Drush\Commands\UiowaCommands::initStatus

The application name is no longer being returned and the commands fail early on in the process.

Seems to be a unrelated issue for the reporting commands: https://github.com/uiowa/uiowa/issues/7354

# Proposed Solution

**Comment by joewhitsitt** [comment]
Just saw this related to the Drush 12 upgrade. Noticing a difference we might need to update with our stuff: https://github.com/drush-ops/drush/pull/5452/files

**Comment by briand44** [comment]
Comment from Sean... Two hooks, alter hook and init. Alter hook populates application value and then used in init hook. They don't seem to run in that order though.

**Comment by briand44** [comment]
Sean is going to spend some time this sprint understanding this better and will comment or add a proposed solution with his findings. Team agreed to temporarily size as a medium and we can adjust based on Sean's findings.
