### ISSUE TITLE
ITS Feedback on alerts part 2

### ISSUE THREAD

**Issue by cory-skeers** [uiowa/uiowa#7384]
- ~remove/hide/change perms for scheduling because they don't plan to use it.~
- ~Update alert url path to match existing site `/alert/[nid]`~
- ~Move category down on alert node display - they mentioned it seemed redundant since it was listed in title and the services affected should be listed higher.~

These ^^ have already been addressed in https://github.com/uiowa/uiowa/commit/a49862344a3de281a0f9c00c2102a6cae19e3222

- On the alert status page, they would like the alert categories filter to be a select list rather than autocomplete.
- any ideas on how to prevent refocus to the date filter on submit? Having the date picker popup each time is kind of annoying as it covers the other filters (sidebar filter on /testing-new-alert-thing)

# Proposed Solution
- Change the widget for the alert categories to a select list
    - There was some worry that this might not work, but until it doesn't, DO THE ABOVE

**Comment by briand44** [comment]
Blocked until we receive help text for scheduling.

**Comment by briand44** [comment]
No longer blocked because they said they don't need the ability to schedule alerts.

**Comment by briand44** [comment]
Updated the issue summary here based on feedback from the meeting with ITS on 2/27/24

**Comment by joewhitsitt** [comment]
I have some of these changes in https://github.com/uiowa/uiowa/pull/7397/commits/a49862344a3de281a0f9c00c2102a6cae19e3222

**Comment by briand44** [comment]
Grooming conversation... Alan suggested that the order of the filters could be a factor in the date popup focus. Lowering them in the order also prevents them from covering other filters. Also could do something with JS. See if any related issues on D.O.

**Comment by bspeare** [comment]
I created a separate issue for the focus issues at https://github.com/uiowa/uiowa/issues/7447.
