### ISSUE TITLE
search.uiowa.edu

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7398]
CSI app dev are planning to retire the LAMP service.

>Our current plan / hope is to be able to turn both services down by June of 2025.  There is a caveat in that date, however.  If end users have a site(s) on the LAMP service running PHP 5, we’ll likely have to act quicker / sooner due to the CentOS à Ubuntu migration happening before June of 2024 and the fact that we can’t lift and shift any sites running an outdated / unsupported version of PHP.

>Here are the alternatives our communications will recommend:
SiteNow Service:
If users require content hosting and management, we encourage them to consider migrating to the SiteNow service.
Virtual Machines (VMs):
For more complex requirements beyond content management, users can stand up new VMs. 
Cloud Services:
Users with specific Software as a Service (SaaS) needs or those seeking a more scalable solution can explore cloud services.

search.uiowa.edu is currently hosted on the LAMP service. We will need to figure out how to handle this going forward.

Docs on how to access located https://iowa.sharepoint.com/sites/sharedlamp

Credentials stored in our password manager. (I updated the description for the correct credentials and was able to connect using an SFTP client).

Repo located at https://git.uiowa.edu/its-web/search.uiowa.edu

# Questions

Could we host this on data.its?
Transition to JS only and use github pages?
Is this even needed? Does uiowa.edu site search search all of .uiowa.edu? (https://uiowa.edu/search?terms=zoom) vs (https://search.uiowa.edu/?q=zoom&client=our_frontend&btnG=Search&output=xml_no_dtd&proxystylesheet=our_frontend&sort=date&entqr=0&oe=UTF-8&ie=UTF-8&ud=1&site=default_collection)

# Proposed Solution

- [x] Update uiowa_search module to send link clicks to uiowa.edu/search instead of search.uiowa.edu
- [ ] Update uiowa_bar on d7 applications (see issue labels) to do the same.
- [x] Turn off link on homepage (confirmed on home.stage.drupal... that this works)

**Comment by mjoneill** [comment]
> Does uiowa.edu site search search all of .uiowa.edu?

My understanding is that it DOES.  I'd be fine if the new search.uiowa.edu could be uiowa.edu/search...

**Comment by mjoneill** [comment]
This gets a surprising amount of traffic.

A lot/most of the traffic has some interesting parameters attached to it (after the search query).  Does this suggest anything to you?

https://search.uiowa.edu/?q=&btnG=Search&client=our_frontend&output=xml_no_dtd&proxystylesheet=our_frontend&sort=date&entqr=0&oe=UTF-8&ie=UTF-8&ud=1&site=default_collection

Update: Looks like the parameters are [described in Google Dev Docs](https://developers.google.com/custom-search/docs/xml_results#wsQueryTerms). Maybe it's not something we're doing unique...

<img width="1056" alt="image" src="https://github.com/uiowa/uiowa/assets/7144234/c3c913ab-f126-4427-a227-e868659e7947">

**Comment by joewhitsitt** [comment]
AFAIK, we aren't adding those in code

> > Does uiowa.edu site search search all of .uiowa.edu?
> 
> My understanding is that it DOES. I'd be fine if the new search.uiowa.edu could be uiowa.edu/search...

Maybe the work is just adjusting the header search bar from "Search this site" to "Search" and then updating our script link here instead, hide the link on the homepage.

**Comment by briand44** [comment]
Grooming conversation... Any cleanup of LAMP would not be in scope here. Update existing search functionality so the Search all uiowa link goes to uiowa.edu/search. We would want to remove this link from uiowa.edu, maybe the hide option for regents theme could work here? We have similar functionality on D7 (701-703, clas). Vulture redirect can be handled in a future slice.

**Comment by joewhitsitt** [comment]
@mjoneill related to the search parameters, I think we will need to gut those. Is that a concern? The homepage is expecting the query differently than what is sent to search.uiowa.edu

https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/uiowa_search/src/Controller/UiowaSearchResultsController.php#L27-L39

For example, SiteNow uses `terms` instead of `q` and that one change causes the results to be blank if the other parameters are left in. If I gut it all, it works as expected.

The page you reference doesn't seem to apply to us in this situation.

>This page refers to the XML version of the Custom Search JSON API, which is available only to [Google Site Search](http://www.google.com/sitesearch/) customers.

**Comment by mjoneill** [comment]
@joewhitsitt 

> related to the search parameters, I think we will need to gut those. Is that a concern?

My only concern was that I was curious if we were adding those to do something with an application on campus.  Less concerned once I saw that they were standard parameters defined by Google, etc...

If we move to uiowa.edu/search, I'd expect it to continue to use the entrenched "terms" that SiteNow has standardized on.

**Comment by joewhitsitt** [comment]
uiowa701-3 look straightforward but going to take a brief look at neuronext and iowalionseyebank as they have the customized bar with modified search.

**Comment by joewhitsitt** [comment]
Creating branches `update_uiowa_bar_search` on uiowa701-3, uiclas

**Comment by joewhitsitt** [comment]
v2/v3 merged into main. all d7 have been deployed. closing.
