### ISSUE TITLE
IOWA HEALTH CARE BRANDING - SiteNow V3

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7403]
As the digital strategy team for UI Health Care, we want to be able to assist more directly and completely with new website requests that span our main public brands so that site requests can be fulfilled accurately, on brand, and in a platform we are investing in.

Asks:
1. Right now an Iowa, CCOM, and REGENTS branding option exists. We would like to explore adding an additional branding option for UI Health Care.
2. This would impact site logo, Favicon, Title/Meta Tag details, and possibly default URL architecture. (*.uihealthcare.org) - Needs discussion.
3. In order to be better stewards of these requests and reroute off brand requests, explore uncovering on the SIteNOw request wbeform the option to select: CCOM or UI HEALTH CARE. If selected, explore how those requests get routed to our UI Health Care team for review, and approval.

# Proposed Solution

```[tasklist]
### Tasks
- [x] Review CCOM theme changes in https://github.com/uiowa/uiowa/pull/6869 and update those changes with new logo and favicon below
- [x] Rename CCOM theme setting to UIHealthCare
```

**Comment by briand44** [comment]
Grooming conversation... CDD is a center but should fall under Healthcare branding. Likely others as well. Similar branding to CCOM but a little different. Ethan has some capacity and is interested in taking this on.

Provisioning process may need to be updated to allow for a new domain option? Updates to site request form? Actual theme changes needed. Should address these as separate slices.

Need to clarify if the sites using the Healthcare branding fall under the "No Google" mandate. If so, that may be a major impediment for using SiteNow for these sites. Currently have Google for search, GTM, Analytics, etc.

- Seems like this may be the question we want to understand first
- Do we know if the IP address is passed to Google as part of the Search?

Should assume that all Healthcare properties fall under the "No Google". Max needs to understand the Google Search side of things a little more.

Does any of the marketing campaign work that OSC is working on cause concern as it relates to Healthcare properties on SiteNow.

Should this be part of the existing CCOM feature or would this be a separate feature? Max mentioned that these seem closely aligned with CCOM sites as far as what currently exists in the CCOM feature with different visuals.

How many sites are we currently thinking? CDD, it is not a regents center so it falls under Healthcare. Another site that falls under UIHC but isn't patient care related.

This could help solve for other sites like chsciowa.org.

If the number of sites grows very large, we may want a way of programmatically tracking which sites are CCOM vs UIHC vs UIowa.

**Comment by ethan-fry** [comment]
![UIHC_GoldWhite](https://github.com/uiowa/uiowa/assets/54082244/7b1881f4-ac83-4cc9-beb6-5d4906234d93)
![favicon-16x16](https://github.com/uiowa/uiowa/assets/54082244/4ec8334f-03f7-4ff8-897f-14ac48174674)
@briand44 I have attached the health care logo and favicon svg files it would not allow me to attach the actual .ico file but can provide that in another way if necessasary.

**Comment by maxwell-freund** [comment]
Title Tag Structure -> {PAGE H1} | {Parent Org If Filled Out} - University of Iowa Health Care
Logo Link -> uihealthcare.org

**Comment by joewhitsitt** [comment]
For reference here is how we handle the meta and favicons for regent sites:

https://iowa.sharepoint.com/sites/drupal-developer-documentation/SitePages/SiteNow%20Drupal%209/Notes%20for%20regent%20option%20websites/Notes%20for%20regent%20option%20websites.aspx

**Comment by briand44** [comment]
Grooming conversation 5-1-24... Since CCOM is transitioning to Iowa brand option, we can replace the CCOM option with this option for UI Health Care. If there are easy wins related to the Regents Option while we are in here we can see about addressing those.

**Comment by briand44** [comment]
Ethan is interested in pairing on this but may be difficult if this gets pulled in next sprint with Sean and Brady at DrupalCon.

**Comment by joewhitsitt** [comment]
We are getting errors trying to access the assets from @ethan-fry's comment. Could the assets be provided in a zip?

**Comment by maxwell-freund** [comment]
@joewhitsitt yes we can get you them in a zip. were they SVG or PNG?

**Comment by joewhitsitt** [comment]
Thanks @maxwell-freund, @bspeare just sent them over in Slack

**Comment by maxwell-freund** [comment]
ah ok! great. @joewhitsitt

**Comment by joewhitsitt** [comment]
@maxwell-freund maybe you can answer this one for us. We got a bit confused picking this issue up and are a little foggy since we groomed this issue.

To what extent is the `ccom` option is supposed to be repurposed? Like should existing `ccom` selected sites be transition automagically (machine name stay the same or an update hook is triggered to keep existing sites with this selected option) or if this is essentially a new option (new machine name) that replaces the `ccom` option that existing sites (db value stored as `ccom`) will need to resave theme settings in order to adopt?

**Comment by joewhitsitt** [comment]
Brian is talking with us now.

**Comment by joewhitsitt** [comment]
CCOM sites using this option are transitioning to use the default brand option _today_ so we need not worry about basically renaming the current option (including machine name) and repurposing existing code to be UIHC specific.

For now we are moving forward with using the same logo for header and footer as it was for the CCOM option.

ccom_core is _not_ part of this work.

**Comment by joewhitsitt** [comment]
We are having troubles with the SVG view box bounds. I know that @bspeare has previously wrangled this before but we don't know how to do it. Beyond that, things are looking good.

**Comment by joewhitsitt** [comment]
Ben suggested that only adjustments to the stylesheet were necessary, not the svg viewbox.
