### ISSUE TITLE
Spike: Investigate patch for Ctools to get multiple views blocks with exposed filters working

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7407]
# Proposed solution

- Add patch from https://git.drupalcode.org/project/drupal/-/merge_requests/6791
- Probe getting Ctools Views to work with patched Drupal core to allow multiple views blocks on a single pages with exposed filters to work.

**Comment by GaryRidgway** [comment]
[Here are the notes that we took while grooming this issue.](https://github.com/uiowa/uiowa/issues/7385#issuecomment-1967419272)

**Comment by pyrello** [comment]
## Setup to recreate exposed filter testing setup
```
git pull && git checkout views_multiple_exposed_filters_core_patch && ddev composer install && ddev blt ds --site sandbox.uiowa.edu && ddev drush @sandbox.local uli node/add/page
```
- Add the page and then go to the layout tab.
- Add the `adfsafas` list block to the page twice.
- Confirm broken behavior first. One block might work correctly, but the other one will trigger a non-ajax reload and both blocks will show filtered results.
## Test "fixes"
To test each fix, make the change indicated, clear cache, then test the blocks again.
1. Change `parameters.twig.config.debug` to `FALSE` in `docroot/sites/development.services.yml`
2. Comment out the contents of the `block_content_template_theme_suggestions_block_content` function in `docroot/modules/custom/block_content_template/block_content_template.module`.

**Comment by joewhitsitt** [comment]
i'll pull this down and see if I can reproduce

**Comment by joewhitsitt** [comment]
> both blocks will show filtered results

only the second block was filtered, both had the filter value. i don't think i witnessed a non-ajax reload of the page. URL didn't change either.

1. didn't work for me. same observations as above.
2. didn't work for me. same observations as above.

Out of curiosity, I switched the theme to olivero, and commented out most of layout_builder_custom.module (tried to uninstall but the headline field prevented me) and got the same result.

**Comment by joewhitsitt** [comment]
FWIW, i tested on simplytest with core 10.2 and the patch from https://www.drupal.org/project/drupal/issues/3163299#comment-15389450 and encountered similar issues. main difference seems to be the exposed filter disappeared for the second view.

<img width="811" alt="Screenshot 2024-02-29 at 10 30 56 AM" src="https://github.com/uiowa/uiowa/assets/4663676/9fc4d381-00c7-4388-b6f1-b2b2b6fa9211">

**Comment by pyrello** [comment]
> FWIW, i tested on simplytest with core 10.2 and the patch from...

Small nitpick and we should definitely test this with exposed and non-exposed filters, but the test is meant to be with multiple blocks with exposed filters.

**Comment by joewhitsitt** [comment]
>main difference seems to be the exposed filter disappeared for the second view.

<img width="686" alt="Screenshot 2024-02-29 at 10 46 41 AM" src="https://github.com/uiowa/uiowa/assets/4663676/25be3b8d-bcda-46a3-9ca3-0e73ccb3a17d">

**Comment by briand44** [comment]
Planning conversation... Does this get fixed in 10.3? Can Alan reproduce on a fresh default install.

**Comment by GaryRidgway** [comment]
I was able to produce the incognito instance again, though i did recognize that I had to do an additional composer install because it didnt seem like it actually applied the patches the first time

**Comment by GaryRidgway** [comment]
I was also able to get it to work by setting `docroot/sites/development.services.yml ln.9` to `false`

**Comment by GaryRidgway** [comment]
@joewhitsitt could you try again without changing anything to see if it works running `ddev composer install` twice?

**Comment by joewhitsitt** [comment]
thumbs'd up too soon. i can tomorrow in the AM. should the branch referenced above be updated with the latest from main now that ctools has been merged in?

**Comment by joewhitsitt** [comment]
gremlins for sure. no changes except for new sync, multiple composer installs, and cache rebuilds. the views blocks are working as expected. i can search them independently, they don't fill in each other, no stuck spinner. magic?

anonymous and logged in.

<img width="642" alt="Screenshot 2024-03-01 at 8 48 03 AM" src="https://github.com/uiowa/uiowa/assets/4663676/7c369c0f-1322-4339-9abc-ac6962056b68">

**Comment by GaryRidgway** [comment]
Maybe we should all huddle this morning and do some gremlin checks?

**Comment by pyrello** [comment]
On Friday, I thought I was seeing an issue with introducing the pager to the block. However, this also turned out to be an issue with me switching between branches and when I got everything set up correctly again, it worked without issues.

The only issue that I'm encountering is that I can't set the filter in the block config and have it persist. This does seem to be working correctly in 10.3. Going to poke at this just a little bit more.

**Comment by pyrello** [comment]
I think this is completed. I ended up creating #7431 and I was able to squash all the issues I was seeing.
