### ISSUE TITLE
F&O chatbots

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7410]
# Story

As a site owner of transportation.uiowa.edu and ap-purchasing.fo.uiowa.edu, I would like to have a chatbot similar to the experience on admissions.uiowa.edu so site visitors can quickly get their questions answered and have a similar brand experience.

# Additional Info

We will likely get more requests similar to this.

Iframes exist on the following stage sites:
**SiteNow v3**
https://transportation.stage.drupal.uiowa.edu/chat-test
https://transportation.stage.drupal.uiowa.edu/chat-test-accordion
**SiteNow v2**
https://fofbis.stage.drupal.uiowa.edu/parking-chat-bot 

# Proposed Solution

**Comment by bspeare** [comment]
My vote here is that we ask them to develop a button that opens the chatbot similar to https://admissions.uiowa.edu/ that we can deploy through tag manager.

**Comment by cory-skeers** [comment]
Possibly related PRs/Issues: https://github.com/uiowa/uiowa/issues/3609 and https://github.com/uiowa/uids/issues/423

**Comment by joewhitsitt** [comment]
I see the email in its-web and it seems stale. @briand44 did recently connect with them directly?

**Comment by briand44** [comment]
Yeah, we meet with them on Monday.

**Comment by briand44** [comment]
Closing this as there isn't currently any dev work we need to do. They are implementing through their tag manager.
