### ISSUE TITLE
Accessible name on back to top link

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#7411]
SiteImprove is flagging the back to top button. I think there was a disconnect where it isn't able to grab the correct labelledby element.

<img width="855" alt="Screenshot 2024-02-28 at 1 00 55 PM" src="https://github.com/uiowa/uiowa/assets/4663676/e2d4bbe2-a290-47de-98fc-bbb51c616b34">

**Comment by joewhitsitt** [comment]
SiteImprove recommends text within the `<a>` tag, an `alt` attribute or an `aria-label`. I think we have been doing the aria-label

**Comment by briand44** [comment]
Grooming conversation... Looks like a one line change https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/templates/navigation/top-scroll.html.twig
