### ISSUE TITLE
Email notification to ITS Help Desk about alert creation

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7417]
# Story

As a member of the ITS Help Desk, I would like to be notified via email when an alert is created that requires review/publishing so that we can promptly review, publish and send any necessary communications about the alert.

# Additional Info

https://github.com/uiowa/uiowa/issues/7417#issuecomment-1984771012

Email to send to `HelpDesk-Notify@uiowa.edu`

Update help text around alert updates for off-hours process

Comment from Joe on https://github.com/uiowa/uiowa/issues/7456#issuecomment-1995021108

> help desk notify needs to be expanded to alert add/edit transitions to "needs review" and help text around alert updates needs to mention off-hours process for alerting helpdesk on-call staff to publish.

# Proposed Solution

```[tasklist]
- [ ] Add workbench_email to ITS site split
- [ ] Configure/export module config to send email to HelpDesk-Notify@uiowa.edu when alerts transition to Needs Review
- [ ] See https://github.com/uiowa/uiowa/issues/7417#issuecomment-1984771012 for email body content
```

**Comment by joewhitsitt** [comment]
Currently this is a simple email that sends an email to helpdesk staff. See `_alert_creation_notify` in its_content_types.helper.inc

Subject: `[node:title] alert has been created.`
Body: `[node:title] alert has been created by [node:author]. <a href="[node.url]"> Please review and publish the alert </a>.`

Similar functionality that works already with moderation in v2/v3 is in use on brand.uiowa.edu related to lockup approvals. Once published/approved, the node author is notified about the approved lockup and details are provided. This uses the `workbench_email` module.

**Comment by briand44** [comment]
Grooming conversation... Brian to get some clarity around the help text for on call. We could leverage the approach from the Brand site. There is interest in a more service wide notification system when content moves from one state to another. Workbench email is what Brand uses and should be leveraged here. Keeping this scoped to ITS for now but hopefully it gets us closer to expanding for the service.

**Comment by briand44** [comment]
No need to do any additional help text.

>I think we were talking about adding help text if we were going to allow editors/service owners to publish updates and close alerts to let them know about off hours. but ultimately, we aren't going to do that so we don't need to worry about adding any help text

**Comment by bspeare** [comment]
Do we want to adjust `workflows.workflow.editorial` for this or create a `workflows.workflow.alert` to reduce the amount of config added?

Edit: going to try a separate `workflows.workflow.alert`

**Comment by joewhitsitt** [comment]
I feel like an ITS partial split to `workflows.workflow.editorial` is the smaller amount of config in this situation.

**Comment by bspeare** [comment]
Thanks @joewhitsitt, when I try the partial split it ends up changing all of these files. Is this expected?

<img width="907" alt="Screenshot 2024-03-22 at 11 30 27 AM" src="https://github.com/uiowa/uiowa/assets/1036433/0534248d-6c2a-443d-b83d-4eabbac4d5f1">

Example diff:


<img width="848" alt="Screenshot 2024-03-22 at 11 31 19 AM" src="https://github.com/uiowa/uiowa/assets/1036433/94ec9667-8d5d-4cf1-9cde-53c274eb1d00">

**Comment by joewhitsitt** [comment]
That doesn't seem to be a workbench_email related cause. If anything it seems like saving the workflow in general is capturing moderation config that wasn't properly captured in the default or sitenow_alerts config.

If you look at brand's config, there aren't new workbench_email-isms scattered all over the lockup config. just the workflow config the modules own config.

**Comment by bspeare** [comment]
Thanks @joewhitsitt, when I try that approach with the partial split on `workflows.workflow.editorial` it deletes `config/sites/its.uiowa.edu/config_split.patch.workflows.workflow.editorial.yml` and replaces it with `workflows.workflow.editorial.yml` - perhaps because these settings are added (example lines from workflow.workflow.alert)? https://github.com/uiowa/uiowa/blob/2311d3af286f52605b8d22ca22341d2dd6babe08/config/sites/its.uiowa.edu/workflows.workflow.alert.yml#L9-L17

**Comment by joewhitsitt** [comment]
Config-wise it should still be able to be a partial split, but I'll allow creating a separate workflow for different reason. ;) The relationship is reverse of what is ideal in that the email template is triggered on `needs review` for _all content types_ selected in the workflow, not just the alert content type.

So yes, go forth with the alert specific workflow.
