### ISSUE TITLE
Authenticate to BizHub endpoints for v1 sites

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7427]
# Story

As a web team, we need to authenticate to existing Facilities APIs for v1 sites so that we can continue to pull data from them once they deploy their basic authentication to production servers.

# Additional Info

Emails in its-web for both buildui and bizhub with credentials.

**Bizhub Endpoints**
- All buildings api: https://bizhub-stage.facilities.uiowa.edu/bizhub/ext/buildings
- Individual building api (example): [https://bizhub- stage.facilities.uiowa.edu/bizhub/ext/building?bldgnumber=0013](https://bizhub-%20stage.facilities.uiowa.edu/bizhub/ext/building?bldgnumber=0013)
- Building Coordinators json response: https://bizhub-stage.facilities.uiowa.edu/bizhub/ext/bldgCoordinators
- All FM Staffs api: https://bizhub-stage.facilities.uiowa.edu/bizhub/ext/fmstaffs
- FM Latest News: https://bizhub-stage.facilities.uiowa.edu/bizhub/ext/fmlatestnews
- All Rooms Information: https://bizhub-stage.facilities.uiowa.edu/bizhub/ext/rooms

**BuildUI Endpoints**
- https://bui-test.facilities.uiowa.edu/buildui/ext/projectinfo?projnumber=0897601
- https://bui-test.facilities.uiowa.edu/buildui/ext/projects?bldgnumber=0025
- https://bui-test.facilities.uiowa.edu/buildui/ext/capitalprojects
- https://bui-test.facilities.uiowa.edu/buildui/ext/featuredprojects

Facilities and snp_map are the only calls to bizhub on v1 - https://github.com/uiowa/uiowa/issues/7401#issuecomment-1973845553

Need to check for calls to buildUI based on https://github.com/uiowa/uiowa/issues/7427#issuecomment-1979183537

# Proposed Solution

- add basic authentication for snp_map
- v1 Facilities - if this gets complicated we can reasess.

**UPDATE**:

The endpoints have been moved out from under VPN to the following:
https://bui-preprod.facilities.uiowa.edu/buildui/ext/
https://bizhub-preprod.facilities.uiowa.edu/bizhub/ext/

**Comment by briand44** [comment]
For D7, those repos are not public so maybe we don't need to worry about storing credentials in code? Likely don't need a config setting for D7 since deployments are quicker.

**Comment by briand44** [comment]
I just heard back from Rakesh and he said they have the same mechanism in place for BuildUI API's as well. I followed up asking for a stage url for testing.

**Comment by briand44** [comment]
Rakesh responded...

> Here are the stage url related to the build UI endpoints for projects to test against.
> 
> https://bui-test.facilities.uiowa.edu/buildui/ext/projectinfo?projnumber=0897601
> https://bui-test.facilities.uiowa.edu/buildui/ext/projects?bldgnumber=0025
> https://bui-test.facilities.uiowa.edu/buildui/ext/capitalprojects
> https://bui-test.facilities.uiowa.edu/buildui/ext/featuredprojects

Going to forward the email to our shared inbox because it contains credentials.

**Comment by joewhitsitt** [comment]
Grooming conversation:

Because this data is meant to be public as-is and we are just trying to reduce unintentional usage, I think the creds can be kept in the non-public repos without further protection. I think most of these use [drupal_http_request](https://api.drupal.org/api/drupal/includes%21common.inc/function/drupal_http_request/7.x) or drupal_http_build_query and can be modified to include `$options['headers']['Authorization']` with basic auth user/pass.

Should be two instances, one of which would then be copy/pasta to the other profiles/apps

**Comment by joewhitsitt** [comment]
First up, i've added the creds and notes to esaccess under Web Services > API Keys

Update: 

Different email for each. Updated esaccess related to this.

There is now separate entries for Facilities buildui API and Facilities bizhub API

**Comment by joewhitsitt** [comment]
~~It looks as though the current prod endpoints disregard the authentication info so this could be deployed in advance of the switch.~~ Seems to be the case with bizhub, not build-ui.

Tested the changes with the test endpoints. Without the user/pass info it returns unauthorized. With it included, the facilities and snp_map functionality works as expected.

Going to put some feature branches together for 701-3

**Comment by joewhitsitt** [comment]
Created feature branches `auth_facilities_api` on 701-3

**Comment by joewhitsitt** [comment]
To test

- checkout auth_facilities_api on 702 in DevDesktop
- Sync www.facilities.uiowa.edu.
- For `_snp_map_get_api_data()` in docroot/profiles/sitenow/modules/custom/sitenow_paragraphs/snp_map/snp_map.module and `_get_api_data` in docroot/sites/www.facilities.uiowa.edu/modules/custom/facilities_core/facilities_core.module change the endpoint string to bizhub-stage and bui-test for bizhub and build-ui endpoints.
- Clear cache on facilities.
- Go to https://www.facilities.uiowa.edu.dd:8443/buildings and see that the table is returned with building data. Click into the building and see that the building info is returned.
- On a basic page, create an SNP section and add a map to it. Select a building from the dropdown to center on (e.g. Kinnick). Save. See that the map is as expected.
- For buildui, go to https://www.facilities.uiowa.edu.dd:8443/projects/project-information/featured-projects

**Comment by joewhitsitt** [comment]
Actually, I am having an authentication issue with https://bui-test.facilities.uiowa.edu/buildui/ext/ endpoints currently using the same creds as bizhub. I will email Rakesh.

**Comment by joewhitsitt** [comment]
At first I thought this could go out right away, but I think we need to wait for the build-ui switch over. 

>~~It looks as though the current prod endpoints disregard the authentication info so this could be deployed in advance of the switch.~~ Seems to be the case with bizhub, not build-ui. - https://github.com/uiowa/uiowa/issues/7427#issuecomment-1997987679

I think this is ready for review and testing.

**Comment by joewhitsitt** [comment]
Updated the IS to include the test endpoints that don't require VPN. Otherwise, the testing instructions should still be the same: https://github.com/uiowa/uiowa/issues/7427#issuecomment-1998015863

**Comment by joewhitsitt** [comment]
701 and 703 have been deployed (master to stage, stage to prod).

**Comment by joewhitsitt** [comment]
I think this can be closed. Thanks to @pyrello for the late-night 702 deployment.
