### ISSUE TITLE
Lost spacing between events on v2 site

### ISSUE THREAD

**Issue by e-marie-w** [uiowa/uiowa#7430]
# Problem
Laura K. emailed about https://law.uiowa.edu/events and the new lack of spacing between listed events

![Screenshot 2024-03-04 at 10 40 45 AM](https://github.com/uiowa/uiowa/assets/68179015/b1e68661-4bd9-4ec0-84de-c83c1d84840f)

# Proposed solution

**Comment by e-marie-w** [comment]
I pulled down a different v2 site locally and experienced the same behavior when I added an events block. Law has images disabled but when enabled they touch if there's no description. Checked computed styles and there's no padding, border, or margin at all.

**Comment by briand44** [comment]
Grooming conversation... We removed some margin from somewhere and allowlisted some blocks but maybe not v2 blocks (https://github.com/uiowa/uiowa/pull/7201). Fix styles and test. Reported on 2/29
