### ISSUE TITLE
Deprovision evaluation.org.uiowa.edu from uiowa04

### ISSUE THREAD

**Issue by e-marie-w** [uiowa/uiowa#7436]
V3 domain successfully changed from evaluation.org.uiowa.edu to pubhealtheval.org.uiowa.edu, so no longer any need for this to stick around on uiowa04.

**Comment by joewhitsitt** [comment]
There is also a v1 standard site evaluation.org.uiowa.edu. I am going to ask if that can be removed when pubhealtheval.org.uiowa.edu launches

UPDATE: it can be queued up for removal when the other website is launched.

**Comment by joewhitsitt** [comment]
For the v1 standard site, added it for removal here https://github.com/uiowa/uiowa/issues/7261
