### ISSUE TITLE
Update icons.brand.uiowa.edu with new icons

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7443]
# Story

As a brand manager, I can see the icons.brand.uiowa.edu site updated with new icons that have been recently designed.

# Additional Info

https://iowa.sharepoint.com/sites/CSI-Drupal2/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FCSI%2DDrupal2%2FShared%20Documents%2FBrand%20Icons%2FIOWA%2DIcon%2DSet%2D030624%2Ezip&viewid=bf54b9d9%2D0975%2D4fbc%2D9f1b%2D6377bdc2307c&parent=%2Fsites%2FCSI%2DDrupal2%2FShared%20Documents%2FBrand%20Icons

> Attached is a new set of 1 and color icons along with keywords.
>  
> The benefits icon in this set should replace the current version on the site for greater usability. Please let me know if you have any issues/questions. Thanks!

# Proposed solution

- Manually add the new icons, keywords, etc.
- replace existing benefits icon with new one provided

**Comment by joewhitsitt** [comment]
Grooming convo: business as usual, these are usually sized as medium.

**Comment by cory-skeers** [comment]
Updated icons branch here: https://github.com/uiowa/brand-icons/pull/29

**Comment by cory-skeers** [comment]
> The benefits icon in this set should replace the current version on the site for greater usability. Please let me know if you have any issues/questions. Thanks!

Benefits is in the list of keywords with a different set of keywords (no overlap) than what is currently there. In https://github.com/uiowa/brand-icons/pull/29 I've added those keywords to the existing list, but we might want to check in case the original keywords were intended to be removed and replaced by these.

<details>
<summary>
Benefits
</summary>

<img width="209" alt="image" src="https://github.com/uiowa/uiowa/assets/49074566/cc4669b3-86b9-4438-a11a-866484f8442a">

</details>

**Comment by joewhitsitt** [comment]
I forget, is there a way to test this or is it just a review/approve?

Did we reach out to confirm the intent with https://github.com/uiowa/uiowa/issues/7443#issuecomment-1989454904?

**Comment by cory-skeers** [comment]
> I forget, is there a way to test this or is it just a review/approve?
> 
> Did we reach out to confirm the intent with [#7443 (comment)](https://github.com/uiowa/uiowa/issues/7443#issuecomment-1989454904)?

Not sure about the workflow for testing, but for https://github.com/uiowa/uiowa/issues/7443#issuecomment-1989454904, we confirmed that both existing and new keywords should be included.

**Comment by cory-skeers** [comment]
These have been added and rolled out.
