### ISSUE TITLE
Add logging back to our Drush commands

### ISSUE THREAD

**Issue by cory-skeers** [uiowa/uiowa#7444]
Follow-up from #7345 

After upgrading to Drush 12, our Drush Commands are logging to the terminal but not db logging. From the probe, the best solution seems to be to call the `\Drupal::logger()` directly. This can be done either in a module process which is called from the drush command, or by using the `LoggerChannelTrait`, like in https://github.com/uiowa/uiowa/commit/866f51001a7af52e03410d71726b9334b95b149f

Each of our drush commands (search our codebase for `DrushCommands` for the related classes) needs this done, outside the `alertsDigest` in `ItsCoreCommands`.

# Proposed solution

- Look at the files changed in https://github.com/uiowa/uiowa/pull/7310/files#diff-99429ce72219f6e2187c56f69cf3eafe16693c9419c44e8b1b0abd84f8d778f5
- For each class that extends `DrushCommands` and makes a call to `$this->logger()`
  - Add the `LoggerChannelTrait` to the class
  - For each call to `$this->logger()->notice($message)`, add an additional call like `$this->getLogger('module_name')->notice($message)` using the same log level (notice, error, etc) and same message
  - (https://github.com/uiowa/uiowa/commit/866f51001a7af52e03410d71726b9334b95b149f can be used as a reference for how the end result should appear)

For testing db logging:
`ddev drush @site.local en dblog`
Run the drush command you are testing
`ddev drush @site.local watchdog-show --count=10`
Any messages from the drush command should appear here

**Comment by joewhitsitt** [comment]
We can just revisit the files touched in https://github.com/uiowa/uiowa/pull/7310/files to keep this slice small. Then going forward, we just keep this gotcha in mind when adding/editing other commands.

**Comment by briand44** [comment]
Sized as a medium to account for testing each of these drush commands. Cory to provide additional comments and proposed solution.

**Comment by cory-skeers** [comment]
Note from grooming convo:

There are two main ways to go about this. One is the proposed solution with adding the Drupal logger alongside Drush logger within each of our drush commands. This is the quickest path forward, and is the closest to matching previous functionality.

The other option would be an code organization change to move the actual "work" from these commands entirely into methods that reside within a module or api file, and use the Drupal logger there. The benefits there would be that all logging would be handled through Drupal and we're not reliant on drush for that anyway, and that if other services called the same methods, the actual running of that process would be logged the same. (And if we needed to differentiate from a drush process or anything else, those could log as their own things.) For instance, most of `classrooms::getBuildings` is processing that isn't specific to it being a Drush command and could be moved into `classrooms_core.module` with appropriate Drupal loggers, which could then be called from the Drush command. 

But that's a fair amount of refactoring, with the risk of breaking stuff along the way; not necessary to get db logging in, and also not immediately beneficial if we're not in a situation where these processes may need to trigger in more than one way.

**Comment by pyrello** [comment]
Something I'm noticing while working on #7449 is that the logging that is triggered in the actual drush command is output to the screen, while all the logging that is triggered in other classes does not. This is even after making sure the logging implementations are identical (in this case using the `LoggerChannelTrait`). Not sure what this means or how it relates to this work, but I thought I'd note it here in case it seems relevant.

**Comment by pyrello** [comment]
I referenced this to get syslog working locally: https://stackoverflow.com/questions/61511046/how-get-syslogd-running-on-ddev

**Comment by pyrello** [comment]
Just noticed this comment while working on #7449: https://git.drupalcode.org/project/drupal/-/blob/11.x/core/lib/Drupal/Core/Logger/LoggerChannelTrait.php#L8-11

Noting it here because I was implementing this trait in service classes and it seems like that is not its intended usage.

**Comment by cory-skeers** [comment]
> Just noticed this comment while working on #7449: https://git.drupalcode.org/project/drupal/-/blob/11.x/core/lib/Drupal/Core/Logger/LoggerChannelTrait.php#L8-11
> 
> Noting it here because I was implementing this trait in service classes and it seems like that is not its intended usage.

Maybe it's worth pivoting to 

>> The other option would be an code organization change to move the actual "work" from these commands entirely into methods that reside within a module or api file, and use the Drupal logger there. 

We have fewer Drush commands that have been effected than it had appeared from initial glance / memory, and while we can keep the actual Drush logging by going this route for if/when it gets logged in the db later, we can address the actual issue at hand here (that we don't have visibility for certain processes when they are triggered through cron drush commands).

**Comment by cory-skeers** [comment]
Taking notes of some of the quirkiness in this as I've been working on this:

_If dblog is not enabled_
Drush logger displays output to the terminal, but drupal logger from calls to internal methods does not.

_If dblog is enabled, and cache has not been cleared after_
Drush logger displays output to the terminal as well as internal drupal logger.

_If dblog is enabled and cache has been cleared after_
Drush logger displays output to the terminal, but drupal logger from calls to internal methods does not.

The middle case is where some of the doubled terminal outputs have appeared where in other cases they have not, and should be the overall expected behavior. The third case may be tied to an upstream drush issue where certain services are not being re-registered after a cache clear. If it is the same issue (https://github.com/drush-ops/drush/issues/5862), then a later drush release will resolve it and we'll be in the nice boat when dblog is enabled where we see everything. It doesn't exactly help the case where we don't have dblog enabled, where logger messages from internal methods end up hidden from the terminal output.

In both cases with dblog enabled (before/after cache clear), the drupal logger from calls to internal methods is logged appropriately, even when they may not reach the terminal.
