### ISSUE TITLE
Better exposed filters focus

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#7447]
# Problem
Certain filter combos cause the focus order to mess up, see https://iowaweb.slack.com/archives/C0164FNN1PV/p1709566223488189 for more discussion. 

# Proposed Solution

- Investigate if the ordering of the filters changes what is focused when you submit the filters. Based on that, we could proceed in one of the following ways:
    - If the ordering change works fine enough, neato.
    - Otherwise, potentially look up issues on drupal.org for things that might be tied to this.
    - Worst case scenario, we can always manually change the focus on submit with Javascript.

**Comment by briand44** [comment]
Grooming conversation... Look for existing issues with better exposed filters and if not Sean mentioned it would be good to contribute a patch for better exposed filters to help community and not keep us entirely responsible. It may make sense to start a new PR here for the new approach.

**Comment by joewhitsitt** [comment]
Can I get a quick update on the direction here? Is the plan to still submit a patch upstream?
