### ISSUE TITLE
Enable directory profiles for Facilities

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7450]
# Story

As a Facilities site owner, I would like to have the ability to display a staff directory from Directory Profiles on our new website so that site visitors can find contact information for appropriate staff members.

# Additional Info

Will need an API key from Directory Profiles at some point but we don't need that to enable this.

# Proposed solution

- Turn on the Directory Profiles feature split in prod
- config imports?

**Comment by joewhitsitt** [comment]
Done. Waiting for keys.


![Image](https://github.com/uiowa/uiowa/assets/4663676/af0ce958-09bc-41cb-af76-dc5584905237)
