### ISSUE TITLE
Roles/Permissions for ITS

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7456]
# Motivation

ITS has said they are ok with moving forward with the existing roles and would utilize the editor role for folks like service owners and help desk students.

They would also like editors to have the ability to create and publish support articles.

My understanding is that in order for editors to publish support articles we either need to remove the default moderation workflow from support articles or create a new workflow.

Adrienne said we can remove moderation from support articles because it would become a huge bottleneck.

# Proposed Solution

- [x] Remove the default workflow moderation from support articles
- [x] Update permissions for support articles so editors can create/edit/publish
- [x] Provide summary of what roles on existing site would transition to which default roles on the new site

**Comment by joewhitsitt** [comment]
meeting notes:

Sounds like they might be able to see how far they get with a three role system (editor (HD student), publisher (helpdesk staff), webmaster (web admins))

- Service owner (editor) can create/add updates to an alert but not publish/send email.
  - Gap would be that they can't publish support articles currently.
- Helpdesk (editor/publisher) can do most content tasks and publish. Trained not to create new services without approval.
- Web admins (webmaster) can do all the things and the site administrative stuff like user management, site settings.
- Gap would be news editors would either need the editor/publisher role or be elevated to webmasters to publish articles.

webform editor was an issue with non-authors being able to see webform submissions.

- help desk notify needs to be expanded to alert add/edit transitions to "needs review" and help text around alert updates needs to mention off-hours process for alerting helpdesk on-call staff to publish.

**Comment by briand44** [comment]
Grooming conversation... If we want to understand the need to remove the default moderation workflow we can dig into that a bit and change our approach if necessary. Same workflow is being used for alerts and they do not want editors to have the ability to publish. There could be value in having moderation even if it is just draft->published. We may want an eventual state where there is another default workflow to keep consistency and transition other sites without moderation to this new workflow. For now, lets move foward with removing workflow and we can revisit later.

**Comment by cory-skeers** [comment]
> ...We may want an eventual state where there is another default workflow to keep consistency and transition other sites without moderation to this new workflow. For now, lets move foward with removing workflow and we can revisit later.

Relates to https://github.com/uiowa/uiowa/issues/7127

**Comment by joewhitsitt** [comment]
Created a word document with role mapping recommendations:


[its_role_recommendations.docx](https://github.com/uiowa/uiowa/files/14728281/its_role_recommendations.docx)

Emailed this to Adrienne.
