### ISSUE TITLE
ITS Alert Feedback part 3

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7458]
> Here's some feedback on the alerts: 
> 
> I created an outage for [Gartner test alert](https://its.prod.drupal.uiowa.edu/alert/826). I modified the end date with the intention of closing it, but it's still showing up as a presumably active alert. I was expecting it to fall off the /alerts page since I modified the end time to the past. (unless i did it wrong?) 
> 
> There is no clear, visual indicator that an alert is closed once the end date/time is modified. It would be nice to have "start" and "end" headers like we do on current alerts. Example: 
> https://its.uiowa.edu/alert/129126
> 
> Related, when services are impacted [it] is critical info. It might be nice to move that out of the sidebar like it's currently showing: https://its.prod.drupal.uiowa.edu/planned-maintenance-gartner
> 
> Nice to have: When we edit an alert end date, the date is prepoluated to the start date. Would be nice if it prepopulated to the current date instead of the original time. For example, when editing this alert from Feb 28, when switching Duration to Custom and modifying the end date time, it autopopulates Feb 28 instead of March 6 (today). Not a deal breaker, but I could see editors missing this when they're trying to quickly edit these. (Happy to have a convo about this since I'm not sure I'm explaining it well)
> 
> I'm not sure how often 30 mins, 1hr, 90 mins, 2 hrs will be selected in the dropdown. Might be better to just have date and time field and forgo those options, but I'll get reactions from Help Desk on this.
> 
> Something might be up with the[ Calendar view](https://its.prod.drupal.uiowa.edu/alerts/calendar). March is showing two pages. Is that by design because we have a lot of test alerts going on currently? 
> 
> Question:
> Jamie has asked for an additional alert type: "emergency maintenance" (when a service needs to undergo an urgent, unplanned update). I'm still trying to understand the need and how often it would be used. I also don't like the term "emergency" because is it really an emergency? Regardless, how difficult is it to add an additional alert type?

# Notes

- Need to revisit logic behind views closed behaviors
- [Closed] text in title?
- Move alert date info out of sidebar and place before alert description and update info
- simplify duration options... "Ongoing" and "Set end date".
- Show all items on alert calendar
- Nice to have - Default end date to today rather than start date
- Additional alert type? - hold on this
- Order alerts on alert landing page by most recent start date first

# Proposed Solution

**Comment by briand44** [comment]
Grooming conversation:

Need to revisit logic behind views closed behaviors.

The emails are getting a closed indicator, but the nodes' themselves are not. Need to sprinkle in [CLOSED] text into the title. That would then simplify the email logic.

Not clear on service/alert sidebar ask. Might need more info. We haven't included alerts into the service pages yet, but the mockup had them in the sidebar.

Re alert end dates: Currently if the duration is switched to custom from ongoing to close an alert, the original date is pre-populated with no time. It shouldn't be too difficult to watch for that action and pre-populate the field with the current date and time.

For duration we could simplify the options, and change the "custom" label to "set end date" or something.

Hopefully for the calendar, it was just set to show pager after 10 items as is default. Possibly switch to show all items.

If a new term is added we will want to protect the term from deletion, wire it up to outages and degradations views. They can control the term description for these. Probably don't want this to be the first option in the list.

**Comment by joewhitsitt** [comment]
Meeting notes:

>Not clear on service/alert sidebar ask. Might need more info. We haven't included alerts into the service pages yet, but the mockup had them in the sidebar.

They want all info in the main column (dates, etc.). This is probably a departure from the sitenow_alerts default display settings.

>Jamie has asked for an additional alert type: "emergency maintenance"

Lift depends on whether we can just group this with an existing view and have minimal styling changes. `Unplanned maintenance` to establish the term in PROD and protect the `tid`. They are going to discuss.

**Comment by joewhitsitt** [comment]
Start date affected sorting on views

**Comment by joewhitsitt** [comment]
Besides the latest comments, the rest of https://github.com/uiowa/uiowa/issues/7458#issuecomment-1989190930 still applies (checking closed logic, calendar pager, etc.)

**Comment by briand44** [comment]
Grooming... Need to revisit logic behind views closed behaviors. Prepend [Closed] text to alert title similar to email when an alert is closed (we'll have to update emails as well so we don't have dupes). Move date into main content (no strong opinions if this is done for the default feature or just ITS). Pre-populating end date may require JS. We could revisit having a different way of closing alerts. For duration we could simplify the options, and change the "custom" label to "set end date" or something. We don't plan to remove any options at this point. We could consider transitioning to core date field if this is giving us problems (would require deleting test alerts so we don't need an update hook). Hopefully for the calendar, it was just set to show pager after 10 items as is default. Possibly switch to show all items. Order alerts on alert landing page by most recent start date first.
