### ISSUE TITLE
Retire search.uiowa.edu from LAMP

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7464]
Follow up from #7463 

# Proposed solution

- [x] Let Hostmaster know they can set TTL back to default for search.uiowa.edu
- [x]  Archive git repo
- [x]  anything need backup not in git repo?
- [x]  Remove credentials for LAMP service from password manager
- [x] Let LAMP folks know search.uiowa.edu application is no longer needed?
- anything else?

**Comment by briand44** [comment]
blocked for a couple weeks after we finish #7463

**Comment by briand44** [comment]
its-lamp-help@uiowa.edu

**Comment by joewhitsitt** [comment]
Archived https://git.uiowa.edu/its-web/search.uiowa.edu

**Comment by briand44** [comment]
I've completed the rest of the tasks. Closing this.
