### ISSUE TITLE
Demo content requires authentication but does not indicate so

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#747]
Possible solutions:

- Add some basic text
- Adjust URLs to use destination parameter
  - Ex. `saml/login?destination=/admin/content/?tour=1`

**Comment by dnkemper** [comment]
Removing myself from this issue. I've been having a hard time. When I added basic text, it still didn't work for me. When I adjusted the URLs to use the destination parameter, it would error out on me.
