### ISSUE TITLE
Create initial draft of comms to SiteNow v1 custom that we believe can transition with out development

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7482]
# Story

As a web team, we would like to create an initial draft of comms to SiteNow v1 custom sites that we believe can transition without development so we can get feedback from the rest of the team and make sure we are communicating the necessary information.

# Additional Info

**Main points of a first comm:**
Request a new site
Let us know if you don’t want your site
If you think it’s a mistake you’re included in this cohort…
Love, Michael and the OSC Web Team - not Phishing

# Proposed Solution

**Comment by briand44** [comment]
Grooming conversation... Do we want to identify any timelines here? We want to identify a timeline for requesting the new sites but we can just have a placeholder for the date in this slice. Get it to potentially shippable understanding the date might still be in flux and the other work could impact this.

**Comment by bspeare** [comment]
I'm going to work on this.

**Comment by bspeare** [comment]
I've created an initial draft at https://iowa.sharepoint.com/:w:/r/sites/CSI-Drupal2/Shared%20Documents/Comms%20for%20SiteNow%20v1%20custom.docx?d=w6c159018e4b54d32809d643bdf6fb00e&csf=1&web=1&e=Sdxa9w.

**Comment by mjoneill** [comment]
> I've created an initial draft at https://iowa.sharepoint.com/:w:/r/sites/CSI-Drupal2/Shared%20Documents/Comms%20for%20SiteNow%20v1%20custom.docx?d=w6c159018e4b54d32809d643bdf6fb00e&csf=1&web=1&e=Sdxa9w.

Thanks!  I've gone in and tried to clarify audience + objective and revised to that.  Passing the baton to ......  ?
