### ISSUE TITLE
SSL - emergency.uiowa.edu and www.emergency.uiowa.edu on uiowa07

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#7485]
From https://github.com/uiowa/uiowa/pull/7473

**Comment by briand44** [comment]
curious about www.emergency.uiowa.edu #7487

**Comment by briand44** [comment]
holding on this until we can get clarification on e.uiowa.edu and www.emergency.uiowa.edu

**Comment by briand44** [comment]
going to move forward with SSL for www.emergency.uiowa.edu. Leaving e.uiowa.edu out for now to discuss as part of #7582

**Comment by briand44** [comment]
This is done.
