### ISSUE TITLE
Admissions counselors map

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#7489]
# Problem
Admissions counselors map is not filtering after initial map click. 

# Steps to reproduce
Go to https://admissions.uiowa.edu/counselors and click around states.  Notice that the territory filter doesn't change. 
- Select Mississippi, then Minnesota

# Proposed solution
1. Find the code for this map
2. Start poking around in the JS to see where things are getting submitted to the form.
3. Understand the submission code
4. Now try and get it to work on subsequent clicks.
5. Now remove any `*.es6` files and replace them with `*.js` files because we don't need to transpile from `.es6` to `.js` anymore.
6. Now try and fix the Pharmacy Palliative Care Alumni map as well, as it is using the same code.

**Comment by briand44** [comment]
Grooming conversation... Pharmacy Palliative Care Alumni is using a copy of the same JS so we want to test and update that as well if the issue is happening there. Remove ES6

**Comment by bspeare** [comment]
Here's the pharmacy link: https://pharmacy.uiowa.edu/pharmd/dual_cert/palliative/certificate_graduates.
