### ISSUE TITLE
Well Being Filters

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7497]
# Story

As a Well Being site owner, I would like our audience, topic, and type filters to be exposed as a drop down list of checkboxes so that users can choose multiple terms for each to filter by.

# Proposed solution

```[tasklist]
### Tasks
- [ ] Set page list block filters to allow multiple and try to preprocess filters to use details and checkboxes like BEF does
- [ ] Use BEF styles https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/scss/views/bef/view-bef.scss#L82
```

**Comment by pyrello** [comment]
> I would like our audience, topic, and type filters to be exposed as a drop down list of checkboxes

Is this in the context of the page list block? Also, were the filters already implemented and we are just changing the way they work (making them a drop-down list of checkboxes) vs implementing them for the first time?

**Comment by briand44** [comment]
@pyrello They are using the page list block but have a split that adds additional taxonomies and exposes those additional taxonomies. The filters already exist as exposed autocompletes, they would just like these as drop-down lists of checkboxes.

**Comment by briand44** [comment]
Grooming conversation... Conversation around styles for these select lists of checkboxes.  Some hesitation on having better exposed filters available for page list block. Queries could get complex with allowing multiple selections for each filter. Do we want to investigate alternate solutions to BEF? Preprocess to use details toggle and try applying styles from Classrooms? If proposed solution doesn't work, let's re-groom a new path.

**Comment by joewhitsitt** [comment]
I pulled this down briefly to investigate. BEF rewrites the markup more than just changing the input type so I don't think this will be the easy path forward unless we just go with BEF.

>If proposed solution doesn't work, let's re-groom a new path.

Using Chosen does work. Though it doesn't provide the checkboxes, it is an autocomplete multi dropdown that does allow you to see the options available. The view would still need to be modified to allow multiple selections to generate the select boxes. Could use some styling tweaks if we went this direction. Then again, we were trying to move on from this too: https://github.com/uiowa/uiowa/issues/2412

```php
/**
 * Implements hook_form_FORM_ID_alter().
 */
function wellbeing_core_form_views_exposed_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form['#id'] === 'views-exposed-form-page-list-block-list-page') {
    $form['#attached']['library'][] = 'sitenow/chosen';
  }
}
```

<img width="853" alt="Screenshot 2024-03-29 at 1 53 46 PM" src="https://github.com/uiowa/uiowa/assets/4663676/a6300bae-61c8-44d9-af56-a4c52e7732b9">

**Comment by bspeare** [comment]
@joewhitsitt should we try using select2 and something like https://github.com/wasikuss/select2-multi-checkboxes?

**Comment by joewhitsitt** [comment]
@bspeare nice idea/find. I think it would be worth exploring, but is definitely a pivot from this issue. Looks like there are several multi-checkbox mods that work for Select2 to evaluate. I wonder if there is a feature request to bake this directly into Select2.

**Comment by bspeare** [comment]
Based on looking at the libraries out there https://www.drupal.org/project/virtual_select and https://sa-si-dev.github.io/virtual-select/#/?id=get-started look to be recently maintained.

**Comment by bspeare** [comment]
I think chosen could work here.   We can always swap it out for another library whenever we are ready to replace it. 

<img width="1394" alt="Screenshot 2024-03-29 at 4 40 08 PM" src="https://github.com/uiowa/uiowa/assets/1036433/faec5250-1cc4-4b7a-a08e-8432dd8a569b">
