### ISSUE TITLE
Group sites in new D7 site list

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7506]
# Story

As a web team, we would like to know which D7 sites remaining are custom D7 sites that we believe can transition to SiteNow v3 without any development so that we can communicate our transition strategy and timelines with them.

# Additional Info

Group sites from new D7 site list spreadsheet into buckets to differentiate v1 standard, v1 custom that can be standard and v1 custom that need customizations
```[tasklist]
### Tasks
- [x] Use the work from https://github.com/uiowa/uiowa/issues/7481 and combine data from https://github.com/uiowa/uiowa/issues/6669 and https://github.com/uiowa/uiowa/issues/7027
```

**Comment by joewhitsitt** [comment]
There was discussion about putting together an up-to-date feature list for not only customers to reference but for our own purposes in determining whether or not they need custom work.

I feel like we have previously done this. Is this just taking all the lists and combining them? https://github.com/uiowa/uiowa/issues/7481#issuecomment-2018960339

Marie's work: https://github.com/uiowa/uiowa/issues/6669
Ben's work: https://github.com/uiowa/uiowa/issues/7027

Also see an intersection with https://github.com/uiowa/uiowa/issues/6787

**Comment by briand44** [comment]
Grooming conversation... We can verify custom vs standard, the more difficult part would be differentiating those custom sites and which ones we think can be standard on v3. We have some data (yes, no, maybe) in a previous spreadsheet that could help but likely some manual review of that to confirm. Didn't commit to the feature list as part of this slice but if it helps whoever picks this up to make the determination of which bucket it falls in, feel free.

**Comment by joewhitsitt** [comment]
As a first step, I got an updated list of site directories from the PROD environments. Made some tweaks and replaced the sheet from #7481 with the latest data. This number aligns closer with the site counts, retains the data captured in the last slice and still captures some sites that have yet to be deprovisioned.

I then copied this list over to the Drupal 7 Sites spreadsheet as `Remaining v1`. I am going to continue to work to merge some of these sheets together.

**Comment by briand44** [comment]
>This number aligns closer with the site counts

Took a look at the site counts command and that command is returning 1 less than the actual number of sites per application. So our site counts are reporting 3 less total D7 sites than there actually are on 701-703. The new spreadsheet is accurate.

The problem is related to the command `drush hls --ignore --fields=site --pipe | wc -l`. I believe `--pipe` is possibly the culprit as the last site is not output on its own line, therefore possibly not getting included in `wc -l`

**Comment by joewhitsitt** [comment]
Update on the spreadsheet. I've got an `All` sheet that is taking the value from most of the previous spreadsheets and including our new spreadsheets. And thanks for the tip from @pyrello I've got a double FILTER() function running in `Automatic Remaining v1` that is displaying the same columns as `Remaining v1` but should automatically update if something changes in the `All` spreadsheet. Further filtering and calculations can occur in `Automatic Remaining v1` but cell changes should always happen in `All`

Looking for input from @briand44 on whether the old sheets can be removed or moved out/archived leaving just All and Automatic Remaining v1

`=FILTER(FILTER(All!A:Q, All!D:D = "Active"),{1,1,1,1,0,0,0,0,0,1,1,0,1,0,0,0,1})` pulls all the columns (A->Q) from the All sheet and filters on Active in the status column (D), and then I am showing and hiding the columns I want.

**Comment by joewhitsitt** [comment]
I've gone through and made some initial selections for our recommendation. I wouldn’t mind running through my thoughts with at least one other person. Some of them I think are active but I am fuzzy on if a v3 site is needed at all or if they planned to go standard already.

**Comment by joewhitsitt** [comment]
Deleted `Remaining v1` sheet as it already became out of date. Long live the `Automatic Remaining v1` sheet.

**Comment by joewhitsitt** [comment]
Brian gave me the go ahead to "move" the old sheets from the spreadsheet so I created a copy of the spreadsheet in CSI-Drupal > Documents > General > Archive

https://iowa.sharepoint.com/sites/CSI-Drupal2/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FCSI%2DDrupal2%2FShared%20Documents%2FGeneral%2FArchive&viewid=bf54b9d9%2D0975%2D4fbc%2D9f1b%2D6377bdc2307c

**Comment by joewhitsitt** [comment]
I think I am done with this work. Hoping someone will take a look at the recommendations in Remaining D7. Added a few more statuses than originally stubbed out. Included `MiscD7->...` type entries, `Going away` and `Needs more info`

Went ahead and added all known D7 (e.g. uigrad, uiclas) regardless of the future plan for them to get more in line with the site counts.

**Comment by joewhitsitt** [comment]
Brian and I went over the spreadsheet together yesterday. In terms of tracking overall numbers, it might be beneficial to include != "Removed" rows in the Remaining D7 sheet to have better visibility into the "Moved," "Replaced" and any other instances that aren't "Active"

Also compared to the sheet that Michael has been using to coordinate standard site removals with related units. It seems that Michael's sheet is tracking a few sites still that have already been addressed and is off by a couple.

**Comment by briand44** [comment]
Reviewing the sites that we grouped as SiteNow v1 custom -> SiteNow v3 standard, there are only two that stand out to me as questionable. Dining and opsmanual. Dining needs hours functionality, which we have but I think we need to turn it on for them and not completely sure if what we have fully meets their needs. Opsmanual seems like it should be in this list until we understand why it can't move without development.

**Comment by joewhitsitt** [comment]
Just saw your comment Brian. I am fine if you want to adjust those recommendations. I paused on the same ones when stepping through earlier.

Otherwise, after talking in standup, it seems like this slice is done.

**Comment by briand44** [comment]
Sorry, also want to mention iowalionseyebank.org here. They will likely not be using the Iowa brand. Should they still be on this list? If so, we will want to include Max and Dan Fischer along with the ILEB contact because they are currently in conversations around branding for this site.

**Comment by joewhitsitt** [comment]
>They will likely not be using the Iowa brand. Should they still be on this list?

Would they be handled by the regents option? If so, there is no custom development (site split) really so I would think they would be included. I'll update the contacts.

**Comment by briand44** [comment]
>Would they be handled by the regents option?

Probably, but those conversations are still happening. Fine if they are included here, just wanted to make sure if site uses Regents Option, they still fall in this category.

> I'll update the contacts.

Thanks!
