### ISSUE TITLE
Display active hawk alerts on emergency front page

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7520]
# Story

As a site owner of emergency.uiowa.edu, I would like active hawk alerts to be easily visible at the top of the front page so that visitors can quickly get Emergency information or see that there are no current emergencies.

# Additional Info

If there are no active Hawk Alerts they want a message like they have currently Showing the campus status is normal and there are no emergencies at this time.

**Current text - https://emergency.uiowa.edu**

> Campus Status Normal
> There are no known emergencies at this time. The campus is operating normally.
> In the event of an emergency, this space will be used to provide timely information to the University community. It will be updated regularly as new information becomes available.

Any and all active hawk alerts should be displayed.

If more than one active hawk alert, they should be stacked and ordered with most recent first. Show all alert info including updates,  currently not linked to full node here.

# Proposed Solution
```[tasklist]
### Tasks
- [ ] Create a view to display active alerts.  Use field display and use alert classes.
```

**Comment by briand44** [comment]
Grooming conversation... Should lean towards alert styling vs card for this.

**Comment by joewhitsitt** [comment]
We confirmed in grooming that status updates are included in the output if they exist. See https://emergency.stage.drupal.uiowa.edu/
