### ISSUE TITLE
Wrong media placed upon selection from media library

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#7537]
# Problem
Wrong media placed upon selection from media library

https://github.com/uiowa/uiowa/assets/1036433/25713ebc-f344-4d13-a1bf-f9432107ec43

# Steps to reproduce
Brand, Whitman Web, and International Studies have reported this issue where the media library item selected does not match the media placed onto the page. 

# Proposed solution
- ?

**Comment by quamsta** [comment]
@bspeare I don't think the attached video shows it but I'm curious if they clicked "Update block" after selecting and seeing the wrong preview image if the actual block will end up using the incorrect image or if the panel is showing the wrong preview, but is actually attaching the correct image to the block?

**Comment by bspeare** [comment]
@quamsta Yes, it ends up showing the incorrect image in the block once updated.

**Comment by quamsta** [comment]
@bspeare Ah. A few more things to maybe check for: 

- does this happen only when filtering for results by title (like in the video) or does it happen even when paging through the media manually and selecting it?
- does the issue occur to the same media entities each time/gets the same ones wrong, or does it change based on things like filtering for different terms? this may help narrow down whether or not it's that media picker dialog that's mismatching the IDs or if it's something deeper/more related to the media entities themselves

**Comment by joewhitsitt** [comment]
The next time we run into this, in addition to what Dustin said, we should be asking:

- What browser. Same issue in another browser?
- Browser extensions?
- Console log messages?

**Comment by briand44** [comment]
Grooming conversation.. Ben wasn't able to reproduce but might be worth some more team members trying to reproduce. Once we are able to reproduce we can re-groom and determine a path forward.

**Comment by bspeare** [comment]
I've tried to recreate this again today using different user roles, private browsing, filters, blocks, browsers, temp storage and I still could not recreate.    I did find a previous screen recording of the same issue happening for Whitman web from January that I have attached below. 


https://github.com/uiowa/uiowa/assets/1036433/f7d89da3-2dcf-4d7d-a7f3-761d6f97a26d

**Comment by cory-skeers** [comment]
The issue looks to be: https://www.drupal.org/project/drupal/issues/3388913 and specifically related to using exposed filters in the media modal while in the Grid view. From comments and personal testing, the Table view seems to be unaffected. 

**To Reproduce:**
In the media library modal, choose to sort by A-Z and apply the filter. Now choose to sort Z-A and apply the filter. Select a media item and insert. Often, the wrong media item will end up inserted.

I didn't have any luck trying to apply the changes as a patch, and then saw this comment in the thread:
"Committed/pushed to 11.x and cherry-picked to 10.3.x, thanks! There's enough changes here I'm not sure about backporting to 10.2.x, so leaving fixed against 10.3.x for now."

Overall, it's an issue that comes about from the media library's interaction with Views' AJAX, so there's also not likely a good path in for us to fix it prior to the fix in 10.3 core. I'll create a known issue for this, with the workaround being to use the Table view when using filters.

**Comment by cory-skeers** [comment]
Known issue added: https://sitenow.uiowa.edu/known-issues#incorrect-media-placed

**Comment by cory-skeers** [comment]
With the known issue added, workaround available, closing this. Full fix will come with Drupal 10.3.
