### ISSUE TITLE
Update memory limit on uiowa01 to 256

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7539]
We decided to slowly continue to update applications to 256M since we haven't noticed any issues on uiowa02 and are still seeing out of memory errors on other applications.

Epic https://github.com/uiowa/uiowa/issues/7525

Grooming conversation
https://github.com/uiowa/uiowa/issues/7525#issuecomment-2035571046

# Proposed Solution

- Update php memory limit on uiowa01
- See if it resolves the issues with BAM
- monitor memory usage to see if we notice any concerns

**Comment by briand44** [comment]
Moving this to blocked/waiting because we want to wait a bit before monitoring memory usage.

**Comment by joewhitsitt** [comment]
Not seeing any big shifts:


![Image](https://github.com/uiowa/uiowa/assets/4663676/be4d30de-a5e1-4dfc-821f-ea2e7af52ba3)



![Image](https://github.com/uiowa/uiowa/assets/4663676/3b304a27-35dc-450e-a327-182b1260943f)

No new instances of memory errors on uiowa01. Last known for this app was in January.
