### ISSUE TITLE
Facilities Alert questions/issues

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7543]
> - Previously there was a user role called  “construction managers” for Alerts. I believe it restricted them from making any changes to the rest of the website. I don’t see that user role on the new site. Is there a role already there that would give us the same control or does it need be created?

We have the collaborator role that construction managers should be assigned to correct?

> - I got an error on the traffic control link in the email when I created a test alert and uploaded a traffic control plan .pdf. It looks like the link doesn't have "prod.drupal" in the name so that might be the issue, which should correct itself when the site is live? Also, the old site has very specific naming restrictions for .pdfs or else the system would throw an error when it was clicked on in the alert email/site. For this site, can we use any naming convention or are their restrictions like no spaces, or something else?

> - The active Engie alert uses an image file for the traffic control plan and we couldn't upload it to the new system. Can we allow image files in this field please?

> - See the screenshots below for how my test alerts are displaying in Lauren’s email. For fields that are linked (the building and traffic control plan) her browser email is displaying the link information in brackets instead of making them hyperlinks. If she clicks "View message in browser" it fixes the issue and it doesn't seem to be happening on her desktop app version of Outlook. These links appear correctly in my email alerts; however, again the building and traffic control links don’t work (maybe b/c in prod?)
```[tasklist]
### Proposed Solution
- [x] Let Facilities know the Collaborator role should be used for Construction Managers
- [ ] Let Facilities know if there are any naming restrictions for traffic control file uploads (no spaces, etc.)
- [x] Make sure links to traffic control plan files work
- [x] Allow images to be uploaded to traffic control plan
- [x] Make sure building link works in alert emails
```

**Comment by joewhitsitt** [comment]
@bspeare feel free to add to https://github.com/uiowa/uiowa/pull/7544, otherwise I get it ready for review.

**Comment by bspeare** [comment]
@joewhitsitt I can add to that pr.
