### ISSUE TITLE
Incomplete webform submission results download

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#7551]
# Problem
Downloading submissions from webforms with lots of results is inconsistent.  It took me 4-6 downloads to get a file that contained all of the submissions. 

# Steps to reproduce
- https://uiowa.edu/admin/structure/webform/manage/landing_page_introduce_yourself_/results/download

# Proposed solution
- Look at the suggestions in https://www.drupal.org/project/webform/issues/3284953?

```[tasklist]
### Tasks
- [ ] Try the webform specific settings.php temp dir solution here https://docs.acquia.com/acquia-cloud-platform/manage-apps/files/broken
- [ ] Deploy to DEV for testing, using the webform:generate functionality to make a boat load of submissions to try downloading
```

**Comment by briand44** [comment]
Grooming conversation... We had similar issue with D7 in the past. Not sure if/how we ever resolved that. We are on a version of webform that would include the fix committed in https://www.drupal.org/project/webform/issues/3284953. Seems like it could be related to load balancer like others have mentioned. May want to test this in dev. Drush webform:generate may be a tool for us to create submissions in dev to test against. https://docs.acquia.com/acquia-cloud-platform/manage-apps/files/broken could have some useful information or options to try out.

**Comment by cory-skeers** [comment]
Couple notes as I've been working on this:
Related issue specific to the acquia environment: https://www.drupal.org/project/webform/issues/2980276
Also of note: I was able to successfully download both the contact and sitenow request submissions tables without any issue. The webform in the 'to reproduce' description I was able to reproduce the issue.
In the acquia docs there are two options, one to force the tmp file path for all file uploads, and one for just webforms. I'd be inclined to go the just webforms route and let the system continue to do its thing and optimize outside of this use case.

**Comment by joewhitsitt** [comment]
>I'd be inclined to go the just webforms route and let the system continue to do its thing and optimize outside of this use case.

👍

**Comment by pyrello** [comment]
Testing on DEV and I encountered an error:
![Screenshot 2024-05-03 at 10 31 45 AM](https://github.com/uiowa/uiowa/assets/709009/c29ca97d-1183-4c83-ab0f-3a7ccfa1a51f)

This corresponds to this error in the logs:
```
php-error staging-15039 [03-May-2024 10:30:33 America/Chicago] Uncaught PHP Exception TypeError: "fputcsv(): Argument #1 ($stream) must be of type resource, bool given" at /mnt/www/html/uiowa01dev/docroot/modules/contrib/webform/src/Plugin/WebformExporter/DelimitedWebformExporter.php line 100 request_id="v-14bdc2aa-0962-11ef-82d5-5b2888672ca3"
```

**Comment by joewhitsitt** [comment]
There was discussion on the PR on whether or not we would need to create the directory for each app/env. That is my only "at a glance" thought about what could be wrong.

**Comment by cory-skeers** [comment]
> There was discussion on the PR on whether or not we would need to create the directory for each app/env. That is my only "at a glance" thought about what could be wrong.

Ope. My bad. I'd given the short update on what needed to be done, and forgot that part.

Assuming we create the directory and it then works, then we have the benefit of knowing for sure!
