### ISSUE TITLE
update memory limit on uiowa

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7553]
We decided to slowly continue to update applications to 256M since we haven't noticed any issues on uiowa02 and are still seeing out of memory errors on other applications.

Epic https://github.com/uiowa/uiowa/issues/7525

Grooming conversation
https://github.com/uiowa/uiowa/issues/7525#issuecomment-2035571046

# Proposed Solution

- Update php memory limit on uiowa
- See if it resolves issues with engineering
- monitor memory usage to see if we notice any concerns

**Comment by joewhitsitt** [comment]
This has been done on uiowa PROD. We can move this to blocked waiting to see about engineering and to monitor effects platform wide.

**Comment by joewhitsitt** [comment]
Closing. Seeing less and less out of memory errors come in to #drupal-status. Overall memory usage appears to be about the same. Seems like we have a file storage issue instead.
