### ISSUE TITLE
Probe emergency endpoint usage

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7556]
# Story

As a web team, we would like to understand the traffic to emergency.uiowa.edu endpoints so we can determine if we need both json and xml endpoints and if we should try and replicate the existing endpoints or if we can create new endpoints.

# Additional Info

Grooming conversation https://github.com/uiowa/uiowa/issues/7550#issuecomment-2048200354

We want to understand if https://emergency.uiowa.edu/api/active.xml is being used or not and if it is being used, is it being used by other teams or just our stuff?

We want to understand if https://emergency.uiowa.edu/api/active.json is being used by other groups or just by us (Signage, SiteNow v1, SiteNow v2/v3)

After understanding the traffic, we want to make a determination on:

- do we need both endpoints or just the json endpoint
- should we replicate the existing endpoint(s) or create new endpoint(s)
- Whether there needs to be any communication and if so, who we should be communicating with.

# Proposed solution

- audit Splunk logs to understand traffic to https://emergency.uiowa.edu/api/active.xml
- audit Splunk logs to understand traffic to https://emergency.uiowa.edu/api/active.json
- Based on the traffic, determine what endpoint(s) are needed and if we should replicate existing or create new
- If creating new endpoint(s), determine if/who we need to communicate with

**Comment by joewhitsitt** [comment]
During demo, both Ken from Libraries (json) and Patrick from Public Health (not sure if xml or json) mentioned that they use the endpoint coming out of emergency.uiowa.edu

**Comment by briand44** [comment]
From Patrick

> We use a Javascript to bring in Hawk Alerts to WordPress sites. We use the JSON endpoint. Here’s the code:
>  
> https://www.public-health.uiowa.edu/wp-content/themes/uiowacph/js/hawk-alert.js?ver=1.0.0

**Comment by joewhitsitt** [comment]
Ken sent me an email which we can follow-up with.

**Comment by cory-skeers** [comment]
Not seeing any indications of usage of the `.xml` endpoint. Mostly the logs are associated with Acquia processes or the occasional one-off like a tiny bit of traffic coming from links issue #7550.

Looking more into the `.json` yet

**Comment by bspeare** [comment]
I removed my assignment to this after getting errors using Splunk.  Maybe it will work tomorrow?

**Comment by joewhitsitt** [comment]
`index=uiowa-acquia "/active.json" referrer="*"| top limit=1000 referrer` year to date

I wish i knew more to only grab unique subdomains but i did some clean up of the export which revealed the top 60-ish referrers. There are several hits that don't have referrer information though so I am not sure what else is hitting these endpoints. This same search seems to reveal popular destinations. For example, Tippie dominated the top with unique marketing URLs that were all counted separately and that recserv's kickball rules are quite popular.

```
https://admissions.uiowa.edu/
https://adsforruralamerica.uiowa.edu
https://ap-purchasing.fo.uiowa.edu
https://archaeology.uiowa.edu/
https://art.uiowa.edu
https://bam.sites.uiowa.edu/
https://beckermann.lab.uiowa.edu
https://bijou.uiowa.edu/
https://crisp.org.uiowa.edu
https://cs.uiowa.edu/
https://csd.uiowa.edu
https://dentistry.uiowa.edu
https://dos.uiowa.edu/
https://dsri.uiowa.edu/
https://education.uiowa.edu/
https://engineering.uiowa.edu
https://french-italian.uiowa.edu/
https://geriatricpain.org/
https://grad.admissions.uiowa.edu/
https://hawkeyemarchingband.uiowa.edu
https://hbrl-neurosurgery.lab.uiowa.edu
https://history.uiowa.edu
https://housing.uiowa.edu/
https://ilr.law.uiowa.edu
https://inbc.medicine.uiowa.edu
https://indiancinema.sites.uiowa.edu
https://international.uiowa.edu/
https://iowajpec.org/
https://irrc.education.uiowa.edu
https://iyws.clas.uiowa.edu
https://jacobsoninstitute.org
https://law.uiowa.edu
https://mentalhealth.uiowa.edu
https://music.uiowa.edu/
https://nativeamericancouncil.org.uiowa.edu/
https://newstudents.uiowa.edu
https://now.uiowa.edu/
https://nursing.uiowa.edu/
https://obermann.uiowa.edu/
https://oniowa.uiowa.edu/
https://osc.uiowa.edu/
https://pharmacy.uiowa.edu/
https://presidentialsearch.uiowa.edu/
https://proteomics.medicine.uiowa.edu/
https://recserv.uiowa.edu/
https://rvap.uiowa.edu/
https://stanleymuseum.uiowa.edu/
https://teach.its.uiowa.edu/
https://tippie.uiowa.edu
https://transportation.uiowa.edu/
https://uiowa.edu/
https://uip.pharmacy.uiowa.edu/
https://uipress.uiowa.edu/
https://voice-academy.uiowa.edu/
https://wessel.lab.uiowa.edu/
https://writersworkshop.uiowa.edu
https://writinguniversity.org/
https://www.lib.uiowa.edu/
https://www.public-health.uiowa.edu/
```

With more time we can parse out what is SiteNow and what is not, but it still won't give a complete picture.

**Comment by joewhitsitt** [comment]
Realizing this morning that it is basically SiteNow sites, Libraries, Public health. Did CLAS/Grad ever have hawk alerts?

Interesting to not see more d7 sites in this list though. Where is signage?

What are all the requests without referrer info...

**Comment by briand44** [comment]
>Interesting to not see more d7 sites in this list though.

I don't think the D7 standard service even has this functionality. Custom sites are probably hit and miss.

**Comment by cory-skeers** [comment]
> Interesting to not see more d7 sites in this list though. Where is signage?

I wasn't ever able to get to a full list without running into errors, but was taking a similar approach and did see signage as a hit. I did usually have event sampling turned on which could make a difference, or if there was a difference in timeframe we were searching that might've impacted how high or low it was on the number of hits?

**Comment by joewhitsitt** [comment]
- You might have to show me how to do the event sampling.
- Mine was year-to-date time range

>do we need both endpoints or just the json endpoint?

Based on Cory's investigation, I don't think the xml is needed.

Trying to answer the other questions of this issue, but going to dig a bit.

**Comment by joewhitsitt** [comment]
>should we replicate the existing endpoint(s) or create new endpoint(s)

I think we should try to do new endpoints. Poked a little to see how close we can get. I think more could be done with the date format.

We could communicate these changes far and wide and provide a guide on how to adjust with 1:1 mapping changes.

**Current JSON**
/api/active.json
```json
// 20240425100046
// https://emergency.stage.drupal.uiowa.edu/api/active.json

{
  "uihphawkalert": [
    {
      "hawkalert": {
        "alert": "Test Hawk Alert: This is a test of the Hawk Alert System conducted by Cindy Schooley. This is only a test.",
        "date": "1710320280",
        "more_info_link": "e.uiowa.edu"
      }
    }
  ]
}
```

**New JSON API:**
/api/active

`complete` was necessary to filter out closed alerts from this endpoint.
sounds like the more_info_link will be changing and will be the same each time.

```json
// 20240425104316
// https://emergency.uiowa.ddev.site/api/active

{
  "jsonapi": {
    "version": "1.0",
    "meta": {
      "links": {
        "self": {
          "href": "http://jsonapi.org/format/1.0/"
        }
      }
    }
  },
  "data": [
    {
      "type": "node--hawk_alert",
      "id": "a76b6646-9dd7-4294-aa9f-52a941caa3c7",
      "links": {
        "self": {
          "href": "https://emergency.uiowa.ddev.site/api/active/a76b6646-9dd7-4294-aa9f-52a941caa3c7?resourceVersion=id%3A79"
        }
      },
      "attributes": {
        "alert": "HAWK ALERT NWS has issued a tornado warning for Johnson County until 4:45pm. Seek immediate shelter. See emergency.uiowa.edu for further information.",
        "date": "2024-04-16T21:21:37+00:00",
        "complete": false
      }
    }
  ],
  "links": {
    "self": {
      "href": "https://emergency.uiowa.ddev.site/api/active"
    }
  }
}
```

**Comment by briand44** [comment]
Can we add additional info to a new JSON API endpoint like the more_info_link if we end up still needing that?

**Comment by joewhitsitt** [comment]
i think it would have to be another field on the entity that would show up in the attributes array similar to the other fields. we can change the property names to match. originally it was title, created, field_alert_complete or whatever.
