### ISSUE TITLE
Facilities email form showing for other content types

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7557]
When logged in to facilities.prod.drupal.uiowa.edu as a webmaster, I see the notifications tab always, rather than it just appearing on alert nodes.

When logged in as a collaborator, I do not see the notifications tab, not even on alert nodes.

From Joe:

> The routing file appears to not be working [https://github.com/uiowa/uiowa/blob/4dcc53034f937faa43c0e3e0b5618fb91e470769/docro[…]s.uiowa.edu/modules/facilities_core/facilities_core.routing.yml](https://github.com/uiowa/uiowa/blob/4dcc53034f937faa43c0e3e0b5618fb91e470769/docroot/sites/facilities.uiowa.edu/modules/facilities_core/facilities_core.routing.yml), and the link is not scoped [https://github.com/uiowa/uiowa/blob/4dcc53034f937faa43c0e3e0b5618fb91e470769/docro[…]iowa.edu/modules/facilities_core/facilities_core.links.task.yml](https://github.com/uiowa/uiowa/blob/4dcc53034f937faa43c0e3e0b5618fb91e470769/docroot/sites/facilities.uiowa.edu/modules/facilities_core/facilities_core.links.task.yml)

**Comment by joewhitsitt** [comment]
Saw this when inspecting the routing file https://www.drupal.org/node/3155569
