### ISSUE TITLE
export of hawk alert content from D7 site

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7578]
# Story

As an Emergency site owner, I would like an export of all hawk alert content from the current live site so that we have a record of all of these past alerts.

# Additional Information

Views Data Export?

Export of all hawk alert content
Share with Hayley Bruce and Anna Lumpkin

Title
Body
Situation Updates (Date and Description)
Status
Complete
Notes

# Proposed Solution

Developers choice on best representation of the data in a single excel compatible file. We can get feedback on what we produce and create a new slice if they determine there are any changes needed with the output.

**Comment by pyrello** [comment]
Desired output format?

**Comment by briand44** [comment]
Mentioned CSV to them in the meeting and they are good with that. If we have other recommendations, we can check with them.

**Comment by briand44** [comment]
Grooming conversation... There may be some rewriting to handle the situation updates. Any images or special formatting won't come over to the CSV as it is on the site. Developers choice on best representation of the data in a single excel compatible file. We can get feedback on what we produce and create a new slice if they determine there are any changes needed with the output.

**Comment by briand44** [comment]
Additional thought... If we have multiple rows for a single Hawk Alert it may be good to output an id associated with the alert so it is easy to differentiate between alerts

**Comment by briand44** [comment]
going to poke at this a bit.

**Comment by briand44** [comment]
I have something, going to send to our Campus Safety partners for feedback. Since it is a bit rough, I created an export of the view and uploaded the csv to https://iowa.sharepoint.com/sites/CSI-Drupal2/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FCSI%2DDrupal2%2FShared%20Documents%2Femergency%2Euiowa%2Eedu%2Fviews%20data%20export%204%2D22%2D24&viewid=bf54b9d9%2D0975%2D4fbc%2D9f1b%2D6377bdc2307c.

**Comment by briand44** [comment]
Closing this as it sounds like they are ok with what we have provided.
