### ISSUE TITLE
ITS alert updates

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7579]
**Alert node add/edit form**
- move additional title field after services and building reference fields 
- Confusion with the body summary. Asking if we can remove?
- Confusion with seo settings and url alias as well. Asking if we can remove?
- Date affected - can it default to now rather than the next hour? If I create a new alert at 10:01 am the date affected defaults to 11am
- Alert updates - on the node edit form can we remove the text "to update" to the right of the "Add alert update" button
- I got some feedback regarding setting the end date and the word "Duration" not resonating. Would it mess everything up if we went back to our current world with the "Show end date" check box? Checking the box populates a date and time field to close the alert. Happy to discuss this one if you need more info. 

**Alert landing page - https://its.prod.drupal.uiowa.edu/alerts**
- If we wanted to remove the border around Service Announcements, how do we do that?
- The outage, service degradation and planned maintenance tags/buttons (thingies with color) are 2-3 lines below the title. Seems out of place.
- What is the little "i" in a black circle next to the service name supposed to indicate? Do we need it?

**Alert node display**
- Update date/time reformatting--can it be consistent with other dates time? (Apr. 15 2024 vs. April 15, 2024)
- I got the following feedback regarding the styling of the updates. Can someone take a look at the styling?
Not sure how I feel about the gray box for the update. It makes the original outage text look odd. Is the update font smaller than the “ICON is down” font. I don’t like how the bold “Update:” is so far away from the actual update. I think I’d like it better without the gray box.

**Daily Digest Email**

- Can we see a daily digest email with everything that's been added so far?
```[tasklist]
### Proposed Solution
- [x] move additional title field after services and building reference fields on alert add/edit form
- [x] Remove body summary for alerts
- [x] Remove SEO Settings and Url Aliase settings
- [x] Default date affected to now rather than the next hour
- [x] Remove or update "to update" text to the right of the "Add alert update" button
- [x] Change the word "Duration" to "End Date" or somthing similar to avoid confusion
- [x] remove border around service announcements on alerts landing page
- [x] remove/replace the "i" on alerts landing page displaying before the services/buildings affected
- [x] consistent use of date/times on individual alert nodes
- [x] Alert Updates theming - at least address spacing with the label
- [x] Provide daily digest email example
```

**Comment by cory-skeers** [comment]
Turns out there's a quick setting when editing the Body field of Alerts that can remove the summary display entirely.

/admin/structure/types/manage/alert/fields/node.alert.body
![Image](https://github.com/uiowa/uiowa/assets/49074566/f9da50c3-ec53-4e98-bf30-63893d695d28)

We'll just want to decide whether this should be ITS Alerts specific or SiteNow Alerts default.

**Comment by briand44** [comment]
Grooming conversation.. 

Can move additional title down but want to make sure we don't make the title field show up again.
We would prefer to hold on the body summary and right sidebar things (Seo, url alias) until further conversation with them.
We can investigate the default date affected time with smart date.
We can adjust/remove/hide "to Update".
Related to "Duration", we can change label but we would prefer to keep the drop down and functionality similar to now. May not even be able to build it the way it was before based on using smart date.

We can remove border on service announcements.
Only so many places we can put the badges. date, service and badge can be arranged. We should find out where they want it so we can move it once.
The "i" is not needed, just away to catch the eye so that information is more easily visible. Will get clarification if they want to remove or replace with different indicator.

We can apply the same format the alert updates is using to the other alert dates and future updates once more brand alignment is available.
We can try to address the update label...

We can trigger a daily digest email. Scheduled job is not setup yet.

**Comment by joewhitsitt** [comment]
Here are some notes I jotted down from the meeting:

```
- The alert card does not have a link button so the black text doesn't look like a link.
- They thought the badge could move up and be inline with the title.
  - This would be a bit of a technical hurdle as we are constructing the title to include the alert type and that the badges aren't part of the alert emails/digest.
- I think James mentioned the badge could be shortened to the icon/color with screen reader text and be placed next to the service, but that otherwise the existing icon can just be removed.
  - There isn't always a service or a building associated with alerts.
- Talked about creating other form of separation between alerts.
```

**Comment by bspeare** [comment]
> - The alert card does not have a link button so the black text doesn't look like a link.

I think we should just add the circle button. 

> - They thought the badge could move up and be inline with the title.

For all of our cards, we usually keep the badges displaying after the main meta information before the summary.  That is our existing design pattern and it makes sense to try to keep that consistent across sites. Below is how we show the event status on iowasummerwritingfestival.uiowa.edu.

<img width="1379" alt="Screenshot 2024-04-25 at 10 42 09 AM" src="https://github.com/uiowa/uiowa/assets/1036433/dd85819a-1481-4e39-8790-26e653dd804a">

**Comment by bspeare** [comment]
I'm going to keep the info icon, but I have added a `title` that displays on hover. 

<img width="670" alt="Screenshot 2024-04-25 at 10 54 57 AM" src="https://github.com/uiowa/uiowa/assets/1036433/6a017f86-fc32-4472-8be3-504848a3ac43">

**Comment by cory-skeers** [comment]
> I'm going to keep the info icon, but I have added a `title` that displays on hover.

Nice! I like this as a middle-ground of keeping it but adding an interactive element to fit the expectation of hover/click interactiveness.

**Comment by briand44** [comment]
I believe the buildings affected are also displayed with the services affected. Does that need represented in the `title`?

**Comment by bspeare** [comment]
Great point, @briand44.  Here are all the variations:

<img width="467" alt="Screenshot 2024-04-25 at 11 10 49 AM" src="https://github.com/uiowa/uiowa/assets/1036433/bb1d3002-00f7-4c6a-aa61-8f4bb014bc66">
<img width="517" alt="Screenshot 2024-04-25 at 11 10 41 AM" src="https://github.com/uiowa/uiowa/assets/1036433/95d85b60-8979-45bc-8341-3d9642ab2d27">
<img width="520" alt="Screenshot 2024-04-25 at 11 10 35 AM" src="https://github.com/uiowa/uiowa/assets/1036433/6782c0b5-779d-4111-a187-dd9a4d5aa8af">
