### ISSUE TITLE
Rotate ACN Drush Cron Logs

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#7583]
# Problem

The `/shared/logs/drush-cron.log` that was established for uiowa07 and other applications is not periodically rotated out which leads to a big file. We need a solution to handle this ourselves.

Background discussion: https://iowaweb.slack.com/archives/C0164FNN1PV/p1712950319169699

# Proposed Solution
- Scheduled job on a single app to make a zip copy of the current log, truncate the file, and remove older zipped versions?

**Comment by joewhitsitt** [comment]
Thinking on this a bit. Here is a bash script similar to how we are handling the 1 min job for Hawk Alerts. We could deploy this and have it run on one app daily. I am not a bash scripting expert and I haven't actually looked to see what a normal rotation script looks like. Just thinking this will grab everything daily and then delete older compressed files after 30 days.

```sh
#!/bin/bash

# Directory where log files are stored
LOG_DIR="/shared/logs"

# Directory for storing rotated logs
ROTATED_DIR="$LOG_DIR/rotated_logs"

# Check if rotated directory exists, if not, create it
if [ ! -d "$ROTATED_DIR" ]; then
    mkdir -p "$ROTATED_DIR"
fi

# Date format for naming tar files
DATE=$(date +"%Y-%m-%d")

# Change directory to parent directory of logs
cd "$(dirname "$LOG_DIR")" || exit

# Tar and gzip log files, excluding rotated_logs directory
tar -czf "$ROTATED_DIR/logs_$DATE.tar.gz" --exclude="$(basename "$ROTATED_DIR")" "$(basename "$LOG_DIR")"

# Empty log files after compression
find "$LOG_DIR" -type f -exec cp /dev/null {} \;

# Delete log files older than 30 days
find "$ROTATED_DIR" -type f -name "logs_*.tar.gz" -mtime +30 -exec rm {} \;
```

**Comment by briand44** [comment]
Grooming conversation... We discussed having this run less frequently than daily. Open to other approaches, don't have to go the direction outlined ^^. `uiowa07` is the only application with Cloud Next in prod so may make sense to do this there but doesn't have to be implemented there.

**Comment by joewhitsitt** [comment]
Just poked enough to realize `logrotate` is available on the acquia servers... Maybe we should start with a support ticket since a google search doesn't seem to bring up any acquia specific docs on the subject.

**Comment by joewhitsitt** [comment]
there is /etc/logrotate.d dir that contains several files with their own configuration for rotating. there is also /etc/logrotate.conf that has a few separate handlers but also a comment at the end of the file:

>system-specific logs may be configured here

**Comment by joewhitsitt** [comment]
Both appear to be read only for me... No response from the Drupal Slack #acquia-support message. Going to open a ticket.

**Comment by joewhitsitt** [comment]
Got a response on Slack right after opening a ticket. It was suggested to place the logrotate.conf file in our repo home and then schedule a job through the cloud UI to run it.

**Comment by joewhitsitt** [comment]
Added `rotate /shared/logs` scheduled job to uiowa07.prod that runs weekly on Sunday 00:00 UTC.

**Comment by joewhitsitt** [comment]
ssh'd in to uiowa and there wasn't the same `/shared/logs` directory so it appears to be ACN infrastructure specific, not subscription specific. going to add it to uiowa07.stage too to prevent logs from growing out of control for dev/stage as well.

**Comment by joewhitsitt** [comment]
I've set a calendar reminder to check that it is work on Monday and then next month to check that the compressed files are limited to 3.
