### ISSUE TITLE
Turn off default Hawk Alert functionality on emergency.uiowa.edu

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7586]
# Motivation

We developed an active alert block that will display at the top of the homepage of emergency.uiowa.edu. With the default Hawk Alert functionality on all SiteNow sites, there will be duplicate alert messages on emergency.uiowa.edu. We should not be displaying the default Hawk Alert functionality on this site.

# Proposed Solution
```[tasklist]
### Tasks
- [x] `ddev drush @emergency.prod config:delete uiowa_alerts.settings hawk_alert.display`
```

**Comment by joewhitsitt** [comment]
There is a conditional wrapper around hawk alerts here: https://github.com/uiowa/uiowa/blob/0894875cc673f6e00e2d1725ef953ad977c3e0b0/docroot/modules/custom/uiowa_alerts/src/Plugin/Block/AlertsBlock.php

There is no UI for the config setting. config/default/uiowa_alerts.settings.yml

This config is ignored already.

**Comment by briand44** [comment]
Grooming conversation.. We have a true/false config for this it just doesn't have a UI. So we just need to do a config set. We should check config ignore to see if this is ignored.

**Comment by joewhitsitt** [comment]
This is done. Because of how the if check is on the block, I deleted the config instead of setting it to false.

```
jwhitsit@ITS-02342 uiowa % ddev drush @emergency.prod config:get uiowa_alerts.settings hawk_alert.display    
Warning: Permanently added the ECDSA host key for IP address '54.152.45.28' to the list of known hosts.
'uiowa_alerts.settings:hawk_alert.display': true

Connection to uiowa07prod.ssh.prod.acquia-sites.com closed.
jwhitsit@ITS-02342 uiowa % ddev drush @emergency.prod config:delete uiowa_alerts.settings hawk_alert.display
Connection to uiowa07prod.ssh.prod.acquia-sites.com closed.
jwhitsit@ITS-02342 uiowa % ddev drush @emergency.prod config:get uiowa_alerts.settings hawk_alert.display   
'uiowa_alerts.settings:hawk_alert.display': null

Connection to uiowa07prod.ssh.prod.acquia-sites.com closed.
```
