### ISSUE TITLE
Concept3D has changed the share URLs for Static Map media

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#7593]
# Problem
https://maps.uiowa.edu/?id=1890#!m/590647

has become:

https://maps.uiowa.edu/?id=1890#!ce/58422?m/590647?mc/41.6629197739891,-91.54511300000001?z/16?lvl/0

And our code is only looking for the fragment and then stripping the `!m/` so this new URL fails validation and media creation. It looks like the old URL is still supported and those URLs resolve on the website.

# Steps to reproduce
- Go to maps.uiowa.edu and get a marker share URL.
- Try creating a static map image on a SiteNow website. You will get a validation error if the URL does not contain the `#!m/590647` type pattern.

# Proposed solution
- Update validation and processing logic to handle this new marker pattern while maintaining support for the old pattern.
- Update the media content overview page to include this media type as a filterable selection.

# Known issue

https://sitenow.uiowa.edu/known-issues#uiowa-issue-7593

**Comment by briand44** [comment]
Grooming conversation... Need to expand validation for these URLs. Regex may be the answer since we are matching against complex patterns. Shouldn't need any db updates. Decided we will commit to updating the media content overview filters as part of this slice as well.
