### ISSUE TITLE
Filterable list of writers bio content

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7610]
# Story

As an IWP site owner, I would like to be able to have a page that lists all writers bio content and has the ability to filter by year and country.

# Additional Info

filter by year - ability to select just one year, default set to latest year published? Can we require a year to be set on the filter?
filter by country - ability to select just one country  
fields - show photo, title, country, year, bio, writing samples 
sorted by family name
Display all results

# Question

How do we determine the year we are displaying?
  Can we use the published status on the taxonomy? So they could create a new year to start adding the next years writer bio's but it not show up in the filter until that term is published, then it would default to the latest published year?

**Comment by briand44** [comment]
Grooming conversation... Default year filter by weighted term. Cory asked about the hierarchical taxonomy of countries that they currently have but we are keeping this as a flat taxonomy that they manage for now at least. Have some wiggle room here on what fields are displayed as I just want to get something in front of them to discuss. Their preference would be to show everything in this display. Ben mentioned teaser is already setup as part of previous work.

**Comment by bspeare** [comment]
It looks like unpublished taxonomy terms will appear in the exposed filter.  There is a patch that might fix that in the future https://www.drupal.org/project/drupal/issues/3108322, but not yet.
