### ISSUE TITLE
Scheduled job to import ceremonies

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#7628]
# Story

As a commencement site owner, I would like new ceremonies added to content hub to automatically get created on the website as part of a regular process that runs.

# Additional Info

On the existing site this runs once a day and Josh has the ability to manually trigger as needed. He likes this but said if we can't allow him to trigger the import then running this twice a day should work. He mentioned noon and midnight.

```[tasklist]
### Tasks
- [x] Setup scheduled job in prod to run event importer
```

**Comment by briand44** [comment]
Grooming conversation... Decided to run twice a day, may be overkill during certain times of the year but no big concerns. Determine when it makes sense to run based on existing jobs/cron. Drush command exists currently that does the import.

**Comment by bspeare** [comment]
This has been configured.
