### ISSUE TITLE
Ability to link directly to collection section on venues

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7637]
# Story

As a Commencement site owner, I would like the ability to use anchor links to link directly to the additional information collection sections on venues so that we can quickly provide links to the appropriate information.

# Additional Information

Currently on the venue content type there is a unique id for the collection item but there is not for the collection section. They would like to have this for the section so they can create anchor links similar to the Information and Policies on https://commencement.uiowa.edu/venue/carver-hawkeye-arena.

# Proposed Solution
```[tasklist]
### Tasks
- [x] ~Follow the code pattern established for adding the unique ID to the collection item to add it to the collection section~ Created a new way of implementing this logic for fields
- [x] ~Add a twig template to allow outputting the unique ID~ Not necessary
```

**Comment by briand44** [comment]
Grooming conversation... The collection section and collection item were built in a way they could be reusable. Probably want to add the unique id field to the collection section so this could be available if used in other places as well. Will may need to establish a template for this entity to output the unique id in the markup. May also need to update parent/child relationship for accessibility with the addition of unique id.

**Comment by pyrello** [comment]
> May also need to update parent/child relationship for accessibility with the addition of unique id.

Actually, I think this may not be necessary. Collection items get organized inside a parent container that is based on the field referencing them. So the collection section is above that and shouldn't affect that relationship.

**Comment by pyrello** [comment]
To adopt the functionality we have where the unique ID gets re-written after its changed to replace spaces with dashes, I'm thinking about adjusting the logic in the `layout_builder_custom` module which currently does this and scopes it to the `uiowa_collection_item`:
https://github.com/uiowa/uiowa/blob/d1bf4ecdda9ef3f42a9a7a1b9ccd75f879d6ae03/docroot/modules/custom/layout_builder_custom/layout_builder_custom.module#L1089-L1101
I'm thinking about moving the `if (isset($element['subform']['field_unique_id'])) {...` block outside the switch statement and just letting the presence or absence of the field in the form determine whether it gets added or not.

Looking for any feedback about downsides to this approach.

**Comment by cory-skeers** [comment]
> I'm thinking about moving the `if (isset($element['subform']['field_unique_id'])) {...` block outside the switch statement and just letting the presence or absence of the field in the form determine whether it gets added or not.

That makes sense to me. If we have a subform, we have some sort of child we're editing in the context of a parent block, right? It feels a little iffy in that we don't know for sure what it is in that context, but as far as assumptions and what gets added based on that, it feels fairly safe.

**Comment by pyrello** [comment]
Just ran into an issue after implementing the logic to add our ajax handler to the unique ID field that if you save the form before the handler has run, then value that gets saved is wrong. We have some logic that checks for this in the case of a block, but there we are using third-party settings instead of a field. This seems to be an issue with the collection item as well, at least in the context of the collection section. I haven't tested yet if its an issue with blocks. Going to look into fixing this.

**Comment by joewhitsitt** [comment]
Following up from EoD, I don't think we have an example yet in our code base, but I think it would be that ConstraintValidator type stuff. The closest we have is a custom field widget (https://github.com/uiowa/uiowa/blob/757d5cf402fff29c38cfa455b2fec8e95a230c70/docroot/modules/custom/sitenow_media_wysiwyg/src/Plugin/Field/FieldWidget/StaticMapUrlWidget.php) and a Webform element (https://github.com/uiowa/uiowa/blob/4e7ba8e372ec33dd235a5f55c478aaddb263122b/docroot/sites/sitenow.uiowa.edu/modules/sitenow_core/sitenow_core.module)

Using hook_entity_base_field_info_alter() to filter on the base field and attach the custom logic via #element_validate
