### ISSUE TITLE
Probe - Entity usage seems to still be holding on to media usage

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#7644]
# Problem
Three know situations now where after cleaning up referenced revisions, the media still shows usage to the node(s).

- Setting up ned.uiowa.edu behind authentication and deleting default files
- Education (single file two pages)
- Rhetoric (multiple files one page)

# Steps to reproduce
Try delete files as described by our documentation (https://sitenow.uiowa.edu/documentation/media#delete-media)

# Workaround

I've been pulling the site down locally, finding the corresponding `fid` for each media entity id using the `file_usage` and `file_managed` tables.

Locally, I try using `drush entity:delete media {comma-separated media ids}` and then expecting the files in `file_managed` to make sure their status is set to `0`

# More info

It doesn't seem to show up in find text but I have had some results in finding the media in various tables `paragraph__field_collection_body` like `media/123` but then it is kind of a pain to track back from there.

# Proposed solution

- [ ] Look for upstream issues with entity_usage, linkit_media_library or Drupal 10.2 as this wasn't an issue when we released https://github.com/uiowa/uiowa/pull/7389
- [ ] ?

**Comment by briand44** [comment]
Some recent conversation around having to remove all usages of a media item before deletion https://iowaweb.slack.com/archives/C8SM82ZFZ/p1715964062834389.

**Comment by joewhitsitt** [comment]
This looks to be a messy issue upstream. https://www.drupal.org/project/drupal/issues/1239558

We are essentially working with a broken system here.

To cover both ideals (user's ability to delete without dealing with referencing revisions and our ability to properly delete files from the server as expected), I think we are going to have to experiment what happens if we do part of the garbage collection ourselves (query and remove rows from entity_usage, file_usage and update the status in file_managed for the file) and then one of those previous revisions is reverted, etc.

**Comment by briand44** [comment]
Grooming conversation... Discussed focusing on the bug reported here and not an entire overhaul at this point. We could do a default install and try to delete default files as described with NED to reproduce. We could use sandbox.prod to try and reproduce this issue as well.

**Comment by joewhitsitt** [comment]
I think I was able to reproduce it here https://sandbox.prod.drupal.uiowa.edu/media/351/edit/usage

On the referencing page. I removed the image from the block, but didn't save the layout. Instead I went to the node edit form and made a change to the body and saved. I then went back to the layout and saved the changes (removed the image). I deleted all of the visible revisions except the current published one. The image isn't on the published version and there is no revision for me to delete through the UI. Possibly a tempstore gremlin in this case?

Here is a different example:

Added the image to the same node. In the body first. Then in layout using text editor. No tricks. I then removed it from layout and saved. then removed it from the body and saved. deleted revisions. revisions says no usage, but the media is not allowed to be deleted. https://sandbox.prod.drupal.uiowa.edu/media/1746/edit/usage

**Comment by cory-skeers** [comment]
https://docs.prod.drupal.uiowa.edu/ is another example of this we can use to investigate.

Setup of a behind authentication site, all remaining media is not used but cannot be deleted. I was able to delete media that had only been used/removed from image fields on person/article content. Content that was used within layouts and removed through reverting layout and deleting revisions cannot be deleted.

**Comment by e-marie-w** [comment]
Summary of my research/findings so far:

I reproduce the bug by uploading a new media item and then creating a new page. Then go to layout builder, add a text area block, and add the image to the text area block. Save. Reopen layout builder and remove the entire block, save again. Go to revisions and delete all but the current revision. Go to the media list and try to delete, discover cannot despite no entity usage listed.

I've discovered the block_content and the block_content__field_uiowa_text area are also holding onto that text area block even after I've deleted it and every revision using it. Like the media it persists through cron, unless I delete the whole entire node. After deleting the node and running cron, the entry in the block_content tables disappears and I am then able to delete the media item successfully. 

Next I'm going to pull down a behind authentication site, as it sounds like despite deleting the nodes and cron being run the media still cannot be deleted. Additionally, since I've only been using an image and the text area block I want to check what happens with other media types and blocks and also what happens if I just remove the media instead of the entire block. I also need to test those existing examples on the sandbox site. Maybe the deleting the whole node only helps if the page if new, I'm not sure yet. 

But I cautiously think there may be a connection here with the blocks. This issue https://www.drupal.org/project/drupal/issues/3042418 sounds like it describes what I'm seeing, but the comments shift to talking about deleting the block type itself instead of just an instance so I'm not sure how helpful it is, but I still want to make it visible.

**Comment by joewhitsitt** [comment]
>I've discovered the block_content and the block_content__field_uiowa_text area are also holding onto that text area block even after I've deleted it and every revision using it. Like the media it persists through cron, unless I delete the whole entire node. After deleting the node and running cron, the entry in the block_content tables disappears and I am then able to delete the media item successfully.

I wonder if this is tempstore coming back to bite us. What if instead of deleting the node, you used the /node/123/layout/discard-changes option to see if that clears out the block?

**Comment by joewhitsitt** [comment]
Marie was able to track down the main issue with this in that block_content is not removed from the database when it is removed from a page layout. no amount of cron garbage collection, etc. currently deletes theses entities until the host entity (node, fragment, etc.) is deleted.

However, when it comes to SiteNow, we have no customer facing way once a node revision is deleted of resurfacing those child entities (paragraphs, block_content, etc.) so there is minimal risk in deleting the media even though entity_usage is still counting it. Right now, by counting in entity_usage the warning message displays and the button is disabled.

We also know that once node revisions related to the media entity are cleaned up when we run `drush entity:delete media ...` they are properly freed and marked for deletion.

So with a bit of extra querying, we could identify whether or not it is safe to delete.

`$usage_data = \Drupal::service('entity_usage.usage')->listSources($form_object->getEntity());` returns back the usage for the media entity. In the situations we have been running into the results are grouped by entity type (e.g. block_content) and inside it lists all of the instances by the `vid`. With these two bits of info, we can then query the same entity_usage table to determine if the entity referencing the media (e.g. block_content) is itself being used (e.g. node). If not, it means the block can't resurface through reverting a node revision, etc. and that it is essentially an orphan until the parent node is deleted.

The downside with this gap solution is that each time the media delete is called, there could potentially be several additional queries to the database if the file is used a lot.

**Comment by cory-skeers** [comment]
> The downside with this gap solution is that each time the media delete is called, there could potentially be several additional queries to the database if the file is used a lot.

If it's only needed on media delete and only needing to query the one table (potentially multiple or even many times), I think this is good to note but sounds like a very fair trade-off.

👍 from me

**Comment by joewhitsitt** [comment]
In poking at this, it does get a bit messy if it is nested. If for example we are talking about a media image on a timeline paragraph item within the timeline block_content attached to the node revision. If the node revision is deleted the paragraph item is still used by our stubborn block_content entity. We would probably want to check nesting in v2 too.

So if we could generalize and say unless the resulting parent db entry is a node/taxonomy?/fragment?, it is essentially detached from ever coming back.

**Comment by joewhitsitt** [comment]
Here is what I have so far https://github.com/uiowa/uiowa/pull/7801

**Comment by joewhitsitt** [comment]
After the merge seeing Marie's demo, I saw that the usage page was blank but the warning message was up for the delete page. Not sure why I didn't previously connect the two.

That led me to \Drupal\entity_usage\Controller\ListUsageController::getRows where it calls the same listSources() that the delete page does but then does some filtering to further weed out things. If the getRows is more accurate and still allows safe deletion, we could potentially use that instead of doing our own stuff.

**Comment by joewhitsitt** [comment]
^^ it is protected, but I am taking a peek to see if we can lift a bit of the logic out for our purposes.

**Comment by joewhitsitt** [comment]
This seems to be where the magic happens for things like block_content and paragraphs: \Drupal\entity_usage\Controller\ListUsageController::getSourceEntityLink

If it can't be linked to itself or it's parent, then it returns null and if null it skips over it. Not exactly lightweight in how they determine and I am not sure if it would change anything for the example Ben brought up.

**Comment by joewhitsitt** [comment]
I'd like to re-open this issue, because #7801 didn't fully solve this for SiteNow websites. There is still a pretty big and common gap related to block_content where orphaned/published blocks aren't tied to a node but still reference a media item.

**Comment by joewhitsitt** [comment]
Related threads:

https://iowaweb.slack.com/archives/C0164FNN1PV/p1731444587721289
https://iowaweb.slack.com/archives/C0164FNN1PV/p1732044464634149

>There are a couple contrib modules that will find parent entities and remove references to a child entity that is being deleted. Not sure if that is what we want though and I am more concerned about the block_content entities that end up as published orphans without a UI to re-use them. Thinking about a helper similar to entity_reference_revisions' Orphan composite revision deletion functionality for paragraphs targeting block_content where it's uuid is no longer in a layout section or revision layout section. https://iowaweb.slack.com/archives/C0406A9VB5L/p1731702081487689

**Comment by briand44** [comment]
Grooming conversation.. Core hasn't solved this yet so we will want to be careful we aren't causing additional issues here. Cory mentioned how this relates in a way to the recent find text enhancement request. Joe to add some additional thoughts/ideas here.

One direction could be:
>Thinking about a helper similar to entity_reference_revisions' Orphan composite revision deletion functionality for paragraphs targeting block_content where it's uuid is no longer in a layout section or revision layout section.

More conversations and familiarization to happen before pulling this.

**Comment by joewhitsitt** [comment]
>Joe to add some additional thoughts/ideas here.

Original thought here was to tackle the media usage issue indirectly by ensuring block content entities are cleaned up and removed from the database since there isn't a UI or other method to resurrect them currently and attach them to another entity (node/fragment/etc.). This is a gap caused by core similar to the issue Paragraphs ran into a while back. With the block entities removed (safely), the media usage within entity_usage will free up. On cron or drush trigger, check to see if block content entities (following their UUIDs) are in any layout builder related table. As the only current vessel for using/displaying block content entities besides the footer contact block?, we can safely remove it and other related bits using entity:delete type functionality. If entity_usage's query runs after this will update the file_usage table and allow deletion of any media that was stuck a s reference.

The contrib modules that I have seen, are not solving the issue by letting media be deleting but then navigating up through the parent references, removing the reference and re-saving the parent entity. Given the level of nesting we have, I am not sure how this would work and could have big consequences if the editor isn't aware of the media's usage at the time of deletion.

There could still be a solution with https://github.com/uiowa/uiowa/issues/7644#issuecomment-2181341627 that would just allow deletion but keep the block entities and the media reference. Extra querying to determine if it is safe to allow deletion and then make sure that status is set to 0 regardless of what the file_usage table says. I think this leaves remnants in the database though.

I almost forgot, there could be another solution YOU 👇 have but haven't voiced yet! Let's hear it!

**Comment by pyrello** [comment]
Idea: Soft "delete" for files that are still in use. They get moved to a location that can't be accessed but don't actually get deleted until all references are removed or age out (revisions).

**Comment by briand44** [comment]
Grooming conversation... Capturing some comments from chat...

>AFAIK, the usage I’ve been targeting and the issue people complain about are orphans outside of the node/page revision table (can’t be reverted back). These media references are on block_content entities that don’t have a parent anymore and can’t be resurrected unless there is a way to attach it to a new parent.

>Or a parent that only exists in a temp_store situation…which is a limited area, but still potentially a thing
>Block gets created, but page never saved

We could circumvent entity usage.

Joe has some additional ideas that he would like to investigate. Lets give him some time to add those ideas here and we can discuss an investigation around those as a next slice for the team.

**Comment by briand44** [comment]
Grooming conversation... What is the trigger to mark a file status as `0`? Is there a way we can do that ourselves on entity delete and cleanup what we need to cleanup? What are the effects of this if someone reverts? Should we be displaying some sort of message to users so they are aware of the effects of reverting once a file has been removed? Could get feedback at demo around this. 

>What do you value more?  The ability to delete a file and have it gone, or the ability to preserve a file through past revisions?

Is there a narrow slice of this? Identify all the situations where the gap exists where we can't trace a file back to its parent entity. Fragments and Nodes are the only parents than can leverage layout builder.

End result would be that editors will be able to remove media file from site without developer assistance.

Some concern about deleting tempstore. 

tempstore
blocks
fragments?

Editors are unable to delete certain media. Let's investigate these situations to try to identify them all, understand them more and document any possible ideas for solutions. There could be different solutions to each situation.

**Comment by cory-skeers** [comment]
Summing up a few notes that have been discussed but maybe not written down.

There are several ways entities get referenced in content. The most straightforward is through reference fields and the like, in which case they get associated with their parent through the `entity_usage` table, and overall usage gets tracked.

For things like blocks (not block_content), it gets stored as config, and no association gets created in the `entity_usage` table.

For block_content used in layout builder, there are two "types" of blocks--one that gets created while editing the page, and exists only in the tempstore, and the one that actually gets saved and revisioned. The first acts like blocks, and the only references created to other things like media are in the block config which is saved within the layout builder JSON stored in the tempstore. Once the page gets saved, the block_content entity gets created, and while it has an association in the layout builder JSON config, it also gets added to the `entity_usage` table, as well as the usage of anything attached to it.

For this very last instance, a block_content entity that has been created through layout builder, it is possible for it to become an orphan if it is no longer included in any revision of any page layout, and it will not have a usage entry in the `entity_usage` table. Ideally, these should be cleaned up, which would then release referenced media etc for possible removal. In some cases, like our footer contact info block, the ex/inclusion in the `entity_usage` table is less a guarantee, and more a "this is a good indicator." 

The main problem with these orphans is that an editor has no way of accessing these old revisions of blocks (for instance, add a PDF link in the footer contact, save, delete it, save, and the file is now tied to revision usage that you can't access). In the case of a footer edit, we can probably safely ignore it and just allow the file to be deleted (or remove all old orphaned revisions), but in those various possible scenarios listed above, "usage" and how it gets assigned may vary.

**Comment by joewhitsitt** [comment]
Getting off-track a bit, but updating the module at least seems to help the messaging around "Translations or previous revisions." https://www.drupal.org/project/entity_usage/issues/3366527

**Comment by joewhitsitt** [comment]
First off, I wanted to remind myself of the consequences of force deleting media.

WYSIWYG (form api field, not registered with entity_usage):
![Image](https://github.com/user-attachments/assets/f616eea2-af65-427e-91c5-37f7f60ff35b)
![Image](https://github.com/user-attachments/assets/20c361ef-2dac-4511-8342-eaaa66748731)

For field media references, it seems to fallback gracefully, the entity is not rendered and the form field is empty like it was never placed. It is still in the database on the field and still tracked in entity_usage until it is saved again and past attainable revisions are removed. Even in the case of orphaned block_content entities, using entity:delete media {mid} or deleting through the UI with the guard rails off, the entry from file_usage was removed, the file_managed entry is marked as 0.

So far my Friday afternoon summary seems to be if the goal is to fix that "Editors are unable to delete certain media," since I haven't encountered a situation where status is not changed to 0 or a WSOD, I feel like we just remove the guardrail for now. This seems to separate the "files aren't being deleted when the media entity is deleted issue" from the "child entities aren't removed until the parent is removed," and "we currently don't track everywhere media can be used" issue.

Maybe there have been changes to core, entity_usage (currently using the latest version) that have allowed the file (not media) to be released even though there is recorded usage.

Planning on coming back to this on Monday with fresh eyes.

**Comment by joewhitsitt** [comment]
I went back in time to when we first started encountering issues. At the time it was because there were multiple media revisions to each file which was reflected in the file_usage table which is ultimately what keeps the file permanent (status = 1) and prevents cleanup. This issue became more apparent with the introduction of file replacing. When the parent media entity was updated, the original doesn't get properly marked as the revision still existed which is why https://www.drupal.org/project/drupal/issues/1239558 is still active and unsolved in core.

We solved part of this issue by preventing more than one media revision at a time #4641. The original file's media revision is replaced as well. However, there were still old revisions out there and we split that work out for a future slice. Folks were still running into this issue because of those old revisions so we created https://github.com/uiowa/uiowa/issues/4810 and tied it to entity_usage. We didn't take this slice up right away though.

Instead we did end up cleaning up those old revisions, essentially solving the original issue of files not being marked as 0 upon media deletion.

#4810 was still out there and we _confused_ the entity_usage being reported by that module as the same issue of not properly cleaning up files after media deletion. There is "media" usage in those block_content and such that ends of becoming an orphan because it is no longer tied to the page, but it is _not the kind of usage that is tracked in file_usage and prevents file_managed from being updated_. We recently took on that issue (Joe went rogue) and not only did we add the warning, but we prevented deletion through the UI. In the instances that were then reported, our work around was either to delete the block and create a new block or delete the media through drush. The workflow included checking file_usage and file_managed tables to make sure the file would get cleaned up based on the original issue. The workaround just worked. The drush command is not doing anything special compared the button in the UI. I haven't seen a situation documented where we actually had to manually drop a row or change status in the database since #4900.

I have tried several different combinations of reproducing the issue and I am certainly able to create instances where there is orphaned content still holding on to the media entity as it would with a taxonomy term reference, but I have been unable to create a situation where the _file_ is kept at status = 1.

I am going to put a PR together that updates entity_usage and removes the deletion prevention. entity_usage will still warn about recorded usage.
