### ISSUE TITLE
[IWP] Writers Bio updates

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7653]
# Proposed Solution

- [x] On the map interview - sounded like they were fine with just a multi-valued link field with text and url components.  This will allow us to migrate old data and be flexible for them to link internally or externally. They plan to use this for podcasts, videos and other types of interviews with folks. It won't be specific to On the Map Interviews. Label "Media".
- [x] Use square photo for Writers Bio rather than circle
- [x] Session/Status label should just be Session. This should be updated everywhere displayed (filter, node display, when creating content, taxonomy, etc.)
- [x] They would like the session filter to default to a session of their choosing. Possibly a default session boolean field on the session taxonomy or config form to set?
- [x] Asked about pdf icon for the writing samples or some better way to represent those - put in list item first. 
- [x] Adjust writing sample link text to be `[Person Name] Writing Sample` and `[Person Name] Writing Sample in Original Language` for accessibility

**Comment by joewhitsitt** [comment]
So, yesterday when we were grooming https://github.com/uiowa/uiowa/issues/7649 the taxonomy weight idea didn't get a lot of traction, something I thought we were originally going to try for this https://github.com/uiowa/uiowa/issues/7610

The problem with the boolean on the term as discussed yesterday is that more than one term could have this checked and so then who wins out? Term weight that isn't an issue, Global form setting that isn't an issue.

~~I am rusty on when and how to set the exposed filter value (same would have to be solved for the global form setting)~~ _nevermind, updated with working example_, but fetching the first term is fairly simple:

```php
/**
 * Implements hook_views_pre_build().
 */
function hook_views_pre_build(ViewExecutable $view) {
  if ($view->id() == 'myview') {
    // Load the vocabulary by machine name.
    $vocabulary = Vocabulary::load('myvocabulary');

    // Get the first term in the vocabulary.
    $terms = \Drupal::entityTypeManager()
      ->getStorage('taxonomy_term')
      ->loadTree($vocabulary->id(), 0, 1, TRUE);

      $filter = $view->display_handler->getHandler('filter', 'field_reference_target_id');
      $filter->value['value'] = $terms[0]->id();
    }
}
```

**Comment by briand44** [comment]
Grooming conversation... Discussed outputting the writing samples in a bulleted list rather than with an icon. Discussed the default session some more. Seemed like the taxonomy weight felt a little more appropriate here than with Commencement because they may need to set the order of the sessions anyway. Not sure if their sessions will be ascending or descending.

**Comment by joewhitsitt** [comment]
After seeing the work in #7649, i think it will be fine to mimic for this as well.

**Comment by joewhitsitt** [comment]
For the "Media" are these displayed on full only, teaser, comma-separated, grouped with the bulleted samples, etc.?

**Comment by briand44** [comment]
>For the "Media" are these displayed on full only, teaser, comma-separated, grouped with the bulleted samples, etc.?

My best guess is that these should be on both teaser and full and listed after the writing samples

**Comment by joewhitsitt** [comment]
Almost feel like they should be added to the bulleted list of samples

![Image](https://github.com/uiowa/uiowa/assets/4663676/d9716576-43e8-43c5-ab7d-3604c3da0ffe)

**Comment by bspeare** [comment]
@joewhitsitt definitely add them to the list.

**Comment by joewhitsitt** [comment]
<img width="549" alt="Screenshot 2024-05-10 at 4 53 14 PM" src="https://github.com/uiowa/uiowa/assets/4663676/aa4c8011-1152-4bb5-bc68-71754178d37d">
