### ISSUE TITLE
Run migration in prod

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7658]
# Story

As a Commencement site owner, we would like to have the events migrated from our D7 site into our new website.

# Additional info
 
We ran the migration in dev as part of #7638. Josh is reviewing, once we get the go ahead we need to run this on the production site.

```[tasklist]
### Proposed Solution
- [x] backup V3 prod db
- [x] Run migration in prod
- [x] Let Josh know this is done
```

**Comment by pyrello** [comment]
Migrations have been run and customer is notified.
