### ISSUE TITLE
Probe issue with Content Hub events losing keywords in revisions created by unit approval.

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#7663]
# Problem
https://iowaweb.slack.com/archives/C0KMREKNU/p1715270154284459

International programs has referenced several events in which they publish with existing keywords that then get removed as other units approve the event for their unit.

Talking with one of the other unit admins, they usually perform the bulk approval and don't touch the node directly.

# Historical examples
https://content.uiowa.edu/node/129811/revisions/view/513206/513211
https://content.uiowa.edu/node/133516/revisions/view/475211/475551

As a unit admin, there are two ways to approve. Editing the event directly, selecting approve and saving the node. Bulk approval through https://content.uiowa.edu/admin/dashboard/upcoming-events

# Proposed solution

**Comment by briand44** [comment]
Grooming conversation... Digital Signage has a unit we can use to debug. Joe had tried using this and wasn't able to recreate. Do we need to create multiple units locally for testing so we aren't sending emails? Decided to commit to probing this and see if we can identify the issue and provide a workaround. Not committing to a fix as part of this slice in case we determine we don't want to put additional resources into this knowing it is going away in the future.

**Comment by cory-skeers** [comment]
I tried recreating the issue locally to no avail.

Tried lots of combinations of multiple units, different varieties of which masqueraded user creates and approves in different orders, various approving methods, combos of rejecting/approving, bulk approval from events from different current states...anything I could think of that might give it issues.

I think there might have been a blip with the bulk update (there's a message in the thread asking if the issue has continued to come up), or possibly something in production that isn't matching the local environment.

We can try testing in production using the digital signage unit, but it might be helpful to wait to hear confirmation that it is still an issue.

**Comment by briand44** [comment]
Discussed sending an email to folks in the Slack channel around this issue to get further feedback.

**Comment by cory-skeers** [comment]
> Discussed sending an email to folks in the Slack channel around this issue to get further feedback.

Sent an email out 2024/05/29 to see if it's been seen since originally being reported. If so, next steps would probably be to try and recreate the issue in prod to narrow it down.
