### ISSUE TITLE
Only show upcoming events for default session on venues

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7672]
# Story

As a Commencement site owner, I would only like to show events for the default session on Venue pages.

# Additional Info

I think we are showing all events for a particular venue currently. https://commencement.prod.drupal.uiowa.edu/venue/carver-hawkeye-arena

Link to the ceremonies list in case they need to see past/future session ceremonies for a particular venue.

# Proposed 

- [x] Limit view results to the configured "default" session - through views relationship or preprocess
- [x] If view title/heading is still "Upcoming Events", change to something like "Events at [node:title]" or "Ceremonies at [node:title]"
- [ ] Add a link to the ceremonies landing page so visitors can easily see all ceremonies

**Comment by briand44** [comment]
Grooming conversation... Discussed possibly being able to handle this by having a relationship on the view with the session taxonomy term based on the default boolean. If this can't be done through the views ui, we could potentially preprocess the view and manually load the term that is the default session and limit results to that session.

We also discussed changing the title/heading of the list from "Upcoming Events" since there will be times it shows events that are past. Possibly something like "Events at [node:title]" or "Ceremonies at [node:title]". Also not sure if this still says "Upcoming Events" after the theming work was done. Just going off of what is currently displayed in the v3 prod site.

**Comment by pyrello** [comment]
I'm going to work on this.
