### ISSUE TITLE
Update Signage/HC Signage to consume Hawk Alerts from new Emergency endpoint

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7686]
# Story

As a Digital Signage service owner, we would like the Signage and HC Signage services to be able to consume Hawk Alerts from the new Emergency endpoint so that our campus partners signs will alert viewers of any active Hawk Alerts.

# Additional Info

https://github.com/uiowa/uiowa/issues/7550#issuecomment-2098621468

> Removed the /api/active.xml endpoint option.
> We couldn't determine significant usage for this endpoint. Consumers are encouraged to switch to the JSON format.
> Changed the /api/active.json endpoint to /api/active
> It is still JSON but without the file extension. The endpoint won't resolve with .json appended.
> 
> The other changes are in order to follow the JSON 1.0 specification:
> The outside wrapper uihphawkalert becomes data.
> The inside wrapper hawkalert becomes attributes.
> date changes from UNIX timestamp to ISO-8601 YYYY-MM-DDThh:mm:ssTZD
> more_info_link has been updated to output the website URL with https:// prefix.
> Public Safety would like to deprecate use of e.uiowa.edu going forward.
> 

We don't want to deploy this until launch of the new endpoint.

**Comment by joewhitsitt** [comment]
with https://github.com/uiowa/uiowa/issues/7667#issuecomment-2120592522 this is taking a bit of detour. i think more needs to be done on the emergency website to allow read requests.

**Comment by joewhitsitt** [comment]
Ignoring the local environment issues for the moment. Started a feature branch `update_signage_hawkalert` that I'd like to test on signage.dev

Update: Not a local issue.

>Access to XMLHttpRequest at 'https://emergency.stage.drupal.uiowa.edu/api/active' from origin 'https://signage-dev.uiowa.edu' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by joewhitsitt** [comment]
Next step I think is to get https://github.com/uiowa/uiowa/pull/7698 to emergency.dev and change the domain over from d7 to point at the v3 site. observe that signage-dev is no longer having console errors related to CORS and then create a hawk alert in emergency.dev to see if the alert shows on signage-dev (there is a 1 hour window for signage to display new alerts).

**Comment by joewhitsitt** [comment]
Woot! CORS errors went away. Now just testing the 1 hour time check.

<img width="1338" alt="Screenshot 2024-05-21 at 9 25 04 AM" src="https://github.com/uiowa/uiowa/assets/4663676/63e09916-16a1-4c63-b322-da8a0508035a">

**Comment by joewhitsitt** [comment]
One hour time check worked. Duplicated changes to the same branch, `update_signage_hawkalert`, on Healthcare signage.

<details>

```diff
jwhitsit@VPER-OSC-194 signage.uiowa.edu % git diff master update_signage_hawkalert
diff --git a/docroot/sites/all/modules/custom/uiowa_signage_modules/signage_hawkalert/js/hawkalert.js b/docroot/sites/all/modules/custom/uiowa_signage_modules/signage_hawkalert/js/hawkalert.js
index a88d8374..70c53fbb 100755
--- a/docroot/sites/all/modules/custom/uiowa_signage_modules/signage_hawkalert/js/hawkalert.js
+++ b/docroot/sites/all/modules/custom/uiowa_signage_modules/signage_hawkalert/js/hawkalert.js
@@ -39,22 +39,31 @@
         // If parent node contains child nodes, then consider the alert as an
         // active HawkAlert and parse the feed.
         // Only show Hawk alert created less than 1 hour ago.
-        var timestamp = Math.floor(Date.now() / 1000);
-        if(json.uihphawkalert.length > 0 && json.uihphawkalert[0].hawkalert.date >= (timestamp - 3600))
-        {
-          // We take the first array key in the alert feed.
-          var hawkalert = json.uihphawkalert[0].hawkalert;
-          $('#hawkalert-info').html('<li><strong>HAWK ALERT: ' + hawkalert.alert + '</strong>' + ' For more information, see ' + hawkalert.more_info_link + '</li>').marquee();;
 
-          // Hide the standard digital signage content container and show the
-          // HawkAlert container.
-          $('#hawkalert').show();
-        }
-        else
-        {
-          // The HawkAlert message contains no child nodes and is considered
-          // empty. Show standard content until a new HawkAlert is detected.
-          $('#hawkalert').hide();
+        if (json.data.length > 0) {
+          // Parse the ISO-8601 date string into a Date object
+          var dateFromJSON = new Date(json.data[0].attributes.date);
+          // Get the current time as a Date object
+          var currentDate = new Date();
+          // Calculate the difference in milliseconds
+          var differenceInMilliseconds = currentDate - dateFromJSON;
+          // Define the threshold for one hour in milliseconds
+          var oneHourInMilliseconds = 60 * 60 * 1000;
+          if (json.data.length > 0 && differenceInMilliseconds < oneHourInMilliseconds) {
+            // We take the first array key in the alert feed.
+            var attributes = json.data[0].attributes;
+            $('#hawkalert-info').html('<li><strong>HAWK ALERT: ' + attributes.alert + '</strong>' + ' For more information, see ' + attributes.more_info_link + '</li>').marquee();
+
+            // Hide the standard digital signage content container and show the
+            // HawkAlert container.
+            $('#hawkalert').show();
+
+          }else
+          {
+            // The HawkAlert message contains no child nodes and is considered
+            // empty. Show standard content until a new HawkAlert is detected.
+            $('#hawkalert').hide();
+          }
         }
       }
     });
diff --git a/docroot/sites/all/modules/custom/uiowa_signage_modules/signage_hawkalert/signage_hawkalert.install b/docroot/sites/all/modules/custom/uiowa_signage_modules/signage_hawkalert/signage_hawkalert.install
index 940e66c1..5089e0db 100755
--- a/docroot/sites/all/modules/custom/uiowa_signage_modules/signage_hawkalert/signage_hawkalert.install
+++ b/docroot/sites/all/modules/custom/uiowa_signage_modules/signage_hawkalert/signage_hawkalert.install
@@ -9,7 +9,7 @@
  */
 function signage_hawkalert_install() {
   // Set default variables.
-  variable_set('signage_hawkalert_url', 'https://emergency.uiowa.edu/api/active.json');
+  variable_set('signage_hawkalert_url', 'https://emergency.uiowa.edu/api/active');
 }
 
 /**
```

</details>

**Comment by joewhitsitt** [comment]
Deployed as part of launch process. Endpoint changed in config for both flavors of signage. FYI our OSC Windows machine appears to be offline. Was able to access healthcare signage through another remote
