### ISSUE TITLE
Update SiteNow v1 to consume Hawk Alerts from new Emergency endpoint

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7688]
# Story

As a SiteNow v1 service owner, we would like the SiteNow v1 service to be able to consume Hawk Alerts from the new Emergency endpoint so that our visitors can be notified of any active Hawk Alerts.

# Additional Info

https://github.com/uiowa/uiowa/issues/7550#issuecomment-2098621468

> Removed the /api/active.xml endpoint option.
> We couldn't determine significant usage for this endpoint. Consumers are encouraged to switch to the JSON format.
> Changed the /api/active.json endpoint to /api/active
> It is still JSON but without the file extension. The endpoint won't resolve with .json appended.
> 
> The other changes are in order to follow the JSON 1.0 specification:
> The outside wrapper uihphawkalert becomes data.
> The inside wrapper hawkalert becomes attributes.
> date changes from UNIX timestamp to ISO-8601 YYYY-MM-DDThh:mm:ssTZD
> more_info_link has been updated to output the website URL with https:// prefix.
> Public Safety would like to deprecate use of e.uiowa.edu going forward.
> 

We don't want to deploy this until launch of the new endpoint.

Looks like the uiowa_alerts module is only in the custom profile and only enabled on the Hawktools website.

**Comment by joewhitsitt** [comment]
Grooming convo:

- Again pay attention to date handling. Date might not even be involved with the output/function of this.
- Test against hawktools but we want a synced copy across all applications. Alan doesn't like that this involves v1 Hawktools.
- Wait to deploy feature branches similar to the signage ones.
- Medium mainly because of v1.

**Comment by joewhitsitt** [comment]
Started a `update_uiowa_alerts` branch on uiowa701 (Hawktools), 702, 703. Had to add momenjs timezone to modify existing moment date handling and do the timezone offset.

<img width="723" alt="Screenshot 2024-05-24 at 12 15 39 PM" src="https://github.com/uiowa/uiowa/assets/4663676/8bb20eb1-29fb-4a06-95c1-27e0f1f4e3dd">

**Comment by joewhitsitt** [comment]
Deployed as part of site launch process. Hawktools is now redirected though so there isn't an active site to test with tomorrow.

**Comment by briand44** [comment]
>Hawktools is now redirected though so there isn't an active site to test with tomorrow.

We can test with https://hawktools.prod.drupal.uiowa.edu/, right?

**Comment by joewhitsitt** [comment]
but why? 😏
