### ISSUE TITLE
91st Meridian author biographies text format is not set

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#7690]
# Problem
91st Meridian author biographies text format is not set and can't be edited by a webmaster. 

# Steps to reproduce
https://91stmeridian.iwp.uiowa.edu/node/1536/edit
<img width="1112" alt="Screenshot 2024-05-16 at 9 42 07 AM" src="https://github.com/uiowa/uiowa/assets/1036433/cefd42ab-117b-42d9-ab54-603b80853eb0">
<img width="1049" alt="Screenshot 2024-05-22 at 1 57 26 PM" src="https://github.com/uiowa/uiowa/assets/1036433/29a8d732-704f-4597-8a3e-b4051ae3f68d">

# Proposed solution
- Set update hook similar to https://github.com/uiowa/uiowa/blob/fb7c160b39eae2bb8bbeb4c714f77b568ebaa301/docroot/sites/grad.admissions.uiowa.edu/modules/grad_admissions_core/grad_admissions_core.install#L23

**Comment by bspeare** [comment]
How it looks to them:

![Uploading Screenshot 2024-05-22 at 1.56.29 PM.png…]()

**Comment by joewhitsitt** [comment]
Grooming convo: The team thought that the solution to this was straightforward and would be an easy bug win that helps with our d7 goal.

**Comment by pyrello** [comment]
It looks like we don't have any custom functionality for this site, so I'll plan on putting the updates in `sitenow.install`. I'm going to look for an example of an update hook that we limited to just a single site in there. If anyone sees this and knows of an example, feel free to ping me.

**Comment by pyrello** [comment]
> It looks like we don't have any custom functionality for this site, so I'll plan on putting the updates in `sitenow.install`. I'm going to look for an example of an update hook that we limited to just a single site in there. If anyone sees this and knows of an example, feel free to ping me.

Found it.
