### ISSUE TITLE
migrate writers bio content

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7699]
# Story

As an IWP site owner, I would like our writers bio content to be migrated from the current site to the new site so we do not have to manually recreate all that content.

# Additional Info

They thought there was more value in getting these migrated sooner than later and worth the cost of any duplicate updates.

They want to migrate all writer bio content

They want us to create redirects from old paths to new paths as part of the migration.

**Mappings - v3 - v1**

- [x] Title - title
- [x] Writer Image - field_image_attach - current allows unlimited, v3 only allows 1.
  - alt
  - title
- [x] Photo Credit - field_writer_photo_credit
- [x] Session - field_writer_session_status - migrating select list into taxonomy - create term as part of migration - current allows unlimited v3 only allows 1
- [x] Countries - taxonomy_vocabulary_1 - create terms as part of migration - current is hierarchical - no need to keep hierarchy - just migrate deepest terms - can have multiple
- [x] Language - field_writer_lang - migrating select list into taxonomy - create terms as part of migration - can have multiple
- [x] Summary - body summary - not sure if they used this currently but is available
- [x] Body - body
- [x] Family Name - field_writer_family_name
- [x] Given Name - field_writer_given_name
- [x] Writing Sample - field_writer_sample - 1
- [x] Writing Sample Original Language - field_writing_sample_in_original - 1
- [x] Media - field_writer_yt_link - map link to link and set the text to "[name] On the Map Interview"

```[tasklist]
### Proposed Solution
- [x] Create migration locally and test
```

**Comment by bspeare** [comment]
Grooming notes:

- Sessions - check for unlimited usage, delete taxonomy terms on prod before migrating
- Images - check for unlimited usage
- Countries - new site flat taxonomy, want to migrate deepest terms.   Country needed.  Don't need hierarchy. Delete taxonomy terms on prod before migrating
- Language - Delete taxonomy terms on prod before migrating

**Comment by bspeare** [comment]
Here's a list of all writer bio's with multiple sessions:

<details>

  <ul>          <li class="views-row views-row-1 views-row-odd views-row-first">
    <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/%C3%B6z-fahri" class="views-ajax-processed-processed">ÖZ, Fahri</a></span>  </div></li>
    <li class="views-row views-row-2 views-row-even">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/ya-hsien-%E7%98%82%E5%BC%A6" class="views-ajax-processed-processed">YA Hsien 瘂弦</a></span>  </div></li>
    <li class="views-row views-row-3 views-row-odd">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/anja-utler-0" class="views-ajax-processed-processed">UTLER, Anja </a></span>  </div></li>
    <li class="views-row views-row-4 views-row-even">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/daniel-simon" class="views-ajax-processed-processed">SIMON, Daniel  </a></span>  </div></li>
    <li class="views-row views-row-5 views-row-odd">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/poon-yiu-ming-%E6%BD%98%E8%80%80%E6%98%8E" class="views-ajax-processed-processed">POON Yiu Ming 潘耀明 </a></span>  </div></li>
    <li class="views-row views-row-6 views-row-even">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/tim-parks" class="views-ajax-processed-processed">PARKS, Tim</a></span>  </div></li>
    <li class="views-row views-row-7 views-row-odd">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/pola-oloixarac-0" class="views-ajax-processed-processed">OLOIXARAC, Pola </a></span>  </div></li>
    <li class="views-row views-row-8 views-row-even">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/sadek-mohammed-0" class="views-ajax-processed-processed">MOHAMMED, Sadek </a></span>  </div></li>
    <li class="views-row views-row-9 views-row-odd">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/luljeta-lleshanaku-0" class="views-ajax-processed-processed">LLESHANAKU, Luljeta </a></span>  </div></li>
    <li class="views-row views-row-10 views-row-even">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/li-di-an-%E6%9D%8E%E7%AC%9B%E5%AE%89" class="views-ajax-processed-processed">LI Di An 李笛安 </a></span>  </div></li>
    <li class="views-row views-row-11 views-row-odd">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/lorna-goodison-0" class="views-ajax-processed-processed">GOODISON, Lorna </a></span>  </div></li>
    <li class="views-row views-row-12 views-row-even">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/alberto-fuguet-0" class="views-ajax-processed-processed">FUGUET, Alberto </a></span>  </div></li>
    <li class="views-row views-row-13 views-row-odd">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/jin-feng-%E9%A6%AE%E9%80%B2" class="views-ajax-processed-processed">FENG, Jin 馮進 </a></span>  </div></li>
    <li class="views-row views-row-14 views-row-even">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/dung-kai-cheung-%E8%91%A3%E5%95%9F%E7%AB%A0" class="views-ajax-processed-processed">DUNG Kai-cheung 董啟章 </a></span>  </div></li>
    <li class="views-row views-row-15 views-row-odd">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/luis-bravo" class="views-ajax-processed-processed">BRAVO, Luis </a></span>  </div></li>
    <li class="views-row views-row-16 views-row-even">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/bi-feiyu-%E6%AF%95%E9%A3%9E%E5%AE%87" class="views-ajax-processed-processed">BI Feiyu 毕飞宇 </a></span>  </div></li>
    <li class="views-row views-row-17 views-row-odd">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/yvonne-ouwuor" class="views-ajax-processed-processed">OWUOR, Yvonne </a></span>  </div></li>
    <li class="views-row views-row-18 views-row-even">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/ya-hsien" class="views-ajax-processed-processed">Ya Hsien</a></span>  </div></li>
    <li class="views-row views-row-19 views-row-odd">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/eliot-weinberger" class="views-ajax-processed-processed">Eliot Weinberger</a></span>  </div></li>
    <li class="views-row views-row-20 views-row-even">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/daniel-weissbort" class="views-ajax-processed-processed">Daniel WEISSBORT</a></span>  </div></li>
    <li class="views-row views-row-21 views-row-odd">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/simon-tay" class="views-ajax-processed-processed">Simon TAY</a></span>  </div></li>
    <li class="views-row views-row-22 views-row-even">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/tomaz-salamun" class="views-ajax-processed-processed">Tomaz SALAMUN</a></span>  </div></li>
    <li class="views-row views-row-23 views-row-odd">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/aleksandr-mikhaylovich-ulanov" class="views-ajax-processed-processed">Aleksandr Mikhaylovich ULANOV</a></span>  </div></li>
    <li class="views-row views-row-24 views-row-even">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/mani-rao" class="views-ajax-processed-processed">Mani RAO</a></span>  </div></li>
    <li class="views-row views-row-25 views-row-odd">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/motoi-oda" class="views-ajax-processed-processed">Motoi ODA</a></span>  </div></li>
    <li class="views-row views-row-26 views-row-even">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/u-sam-oeur" class="views-ajax-processed-processed">U. Sam OEUR</a></span>  </div></li>
    <li class="views-row views-row-27 views-row-odd">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/ur-anantha-murthy" class="views-ajax-processed-processed">U.R. ANANTHAMURTHY</a></span>  </div></li>
    <li class="views-row views-row-28 views-row-even">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/artur-miedzyrzecki" class="views-ajax-processed-processed">Artur MIEDZYRZECKI</a></span>  </div></li>
    <li class="views-row views-row-29 views-row-odd">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/li-rui-0" class="views-ajax-processed-processed">LI Rui (李锐)</a></span>  </div></li>
    <li class="views-row views-row-30 views-row-even">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/yen-lo" class="views-ajax-processed-processed">LO Yen (商禽)</a></span>  </div></li>
    <li class="views-row views-row-31 views-row-odd">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/yen-lo" class="views-ajax-processed-processed">LO Yen (商禽)</a></span>  </div></li>
    <li class="views-row views-row-32 views-row-even">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/xi-chuan" class="views-ajax-processed-processed">XI Chuan (西川)</a></span>  </div></li>
    <li class="views-row views-row-33 views-row-odd">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/eddin-bu-eng-khoo" class="views-ajax-processed-processed">Eddin Bu-Eng KHOO</a></span>  </div></li>
    <li class="views-row views-row-34 views-row-even">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/kerry-shawn-keys" class="views-ajax-processed-processed">Kerry Shawn KEYS</a></span>  </div></li>
    <li class="views-row views-row-35 views-row-odd">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/peter-jay" class="views-ajax-processed-processed">Peter JAY</a></span>  </div></li>
    <li class="views-row views-row-36 views-row-even">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/leonardo-iramain" class="views-ajax-processed-processed">Leonardo IRAMAIN</a></span>  </div></li>
    <li class="views-row views-row-37 views-row-odd">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/taufiq-ismail" class="views-ajax-processed-processed">Taufiq ISMAIL</a></span>  </div></li>
    <li class="views-row views-row-38 views-row-even">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/hwang-jaewoo" class="views-ajax-processed-processed">HWANG Jaewoo</a></span>  </div></li>
    <li class="views-row views-row-39 views-row-odd">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/julia-hartwig" class="views-ajax-processed-processed">Julia HARTWIG</a></span>  </div></li>
    <li class="views-row views-row-40 views-row-even">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/ayurzana-gun-aajav" class="views-ajax-processed-processed">Ayurzana GUN-AAJAV</a></span>  </div></li>
    <li class="views-row views-row-41 views-row-odd">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/janusz-glowacki" class="views-ajax-processed-processed">Janusz GLOWACKI</a></span>  </div></li>
    <li class="views-row views-row-42 views-row-even">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/janusz-glowacki" class="views-ajax-processed-processed">Janusz GLOWACKI</a></span>  </div></li>
    <li class="views-row views-row-43 views-row-odd">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/patricio-esteve" class="views-ajax-processed-processed">Patricio ESTEVE</a></span>  </div></li>
    <li class="views-row views-row-44 views-row-even">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/jose-donoso" class="views-ajax-processed-processed">José DONOSO</a></span>  </div></li>
    <li class="views-row views-row-45 views-row-odd">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/fernando-del-paso" class="views-ajax-processed-processed">Fernando DEL PASO</a></span>  </div></li>
    <li class="views-row views-row-46 views-row-even">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/alain-delahaye" class="views-ajax-processed-processed">Alain DELAHAYE</a></span>  </div></li>
    <li class="views-row views-row-47 views-row-odd">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/maria-van-daalen-0" class="views-ajax-processed-processed">Maria van DAALEN</a></span>  </div></li>
    <li class="views-row views-row-48 views-row-even">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/elizabeth-azcona-cranwell" class="views-ajax-processed-processed">Elizabeth Azcona CRANWELL</a></span>  </div></li>
    <li class="views-row views-row-49 views-row-odd">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/hsun-chiang" class="views-ajax-processed-processed">CHIANG Hsun (蒋勋)</a></span>  </div></li>
    <li class="views-row views-row-50 views-row-even">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/wen-tao-cheng" class="views-ajax-processed-processed">CHENG Wen-tao </a></span>  </div></li>
    <li class="views-row views-row-51 views-row-odd">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/wen-tao-cheng" class="views-ajax-processed-processed">CHENG Wen-tao </a></span>  </div></li>
    <li class="views-row views-row-52 views-row-even">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/alan-cherchesov" class="views-ajax-processed-processed">Alan CHERCHESOV</a></span>  </div></li>
    <li class="views-row views-row-53 views-row-odd">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/edward-carey" class="views-ajax-processed-processed">Edward CAREY</a></span>  </div></li>
    <li class="views-row views-row-54 views-row-even">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/eavan-boland" class="views-ajax-processed-processed">Eavan BOLAND</a></span>  </div></li>
    <li class="views-row views-row-55 views-row-odd">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/zbigniew-bienkowski" class="views-ajax-processed-processed">Zbigniew BIENKOWSKI</a></span>  </div></li>
    <li class="views-row views-row-56 views-row-even">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/zbigniew-bienkowski" class="views-ajax-processed-processed">Zbigniew BIENKOWSKI</a></span>  </div></li>
    <li class="views-row views-row-57 views-row-odd">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/alberto-o-blasi" class="views-ajax-processed-processed">Alberto O. BLASI</a></span>  </div></li>
    <li class="views-row views-row-58 views-row-even">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/carlos-german-belli" class="views-ajax-processed-processed">Carlos Germán BELLI</a></span>  </div></li>
    <li class="views-row views-row-59 views-row-odd">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/ricardo-rey-beckford" class="views-ajax-processed-processed">Ricardo Rey BECKFORD</a></span>  </div></li>
    <li class="views-row views-row-60 views-row-even views-row-last">
      <div class="views-field views-field-title">        <span class="field-content"><a href="https://iwp.uiowa.edu/writers/roberto-ampuero-0" class="views-ajax-processed-processed">Roberto Ampuero</a></span>  </div></li>
  </ul>

</details>
