### ISSUE TITLE
Ceremonies filterable list updates

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7707]
Josh got feedback from additional stakeholders and they are wanting some changes to this to make it easier to view only college ceremonies.

- Asked if there is a way to select all for the college filter?
- Noticed the college filter never wraps when choosing multiple colleges
- Said they would be ok with having two separate pages, the existing page could be called Ceremonies and Celebrations and then have a new page for College Ceremonies that would not have the Other Celebrations filter. The venue pages "See all Events" link would link to the Ceremonies and Celebrations page.

Alan tried selecting all colleges and creating a url redirect from a short url to the url with all of the query parameters but that wasn't working as expected.

**Comment by joewhitsitt** [comment]
Grooming convo:

- To achieve the select all and wrapping request, bite the bullet and switch to BEF over Chosen. We would like to do this first and see if that reduces the need for separating out the functionality out into two views. Sized based on this first slice.
- If they still want separation, the thought is to go ahead and create the two views, one with the filter and one with out.

**Comment by bspeare** [comment]
Here's a preview of the proposed solution:

https://github.com/uiowa/uiowa/assets/1036433/c85364e1-4d07-430e-86c7-5dd91cf84221
