### ISSUE TITLE
Update media_entity_twitter to cover x.com URLs

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#7709]
https://www.drupal.org/project/media_entity_twitter/issues/3392584

I think they are dropping support for mirroring twitter.com links and [oembed](https://oembed.com/providers.json) now has X.com coverage

**Comment by GaryRidgway** [comment]
Should we be doing this now before it is merged in to the main branch of `media_entity_twitter` or should we be waiting? It still hasn't merged yet.

**Comment by joewhitsitt** [comment]
Not sure if customers have run into this issue yet, but I saw this comment in HighEdWeb, https://highedweb.slack.com/archives/CDA11KT2L/p1715972383269619 and noticed the issue/patch with the module.

I think this might be a good candidate for patching since the last stable release was November 2022 and no maintainers have chimed in on the issue.
