### ISSUE TITLE
Move SiteNow Drupal 9 section of docs

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7737]
# Story

As a web team, we want to transition our docs to SiteNow v3 behind authentication so that we don't have to fight SharePoint any longer and that we can have more content interaction with the service we provide.

# Additional Info

Epic https://github.com/uiowa/uiowa/issues/4270

Move SiteNow Drupal 9 section of docs from SharePoint to https://docs.prod.drupal.uiowa.edu/

Site has been requested and provision started - https://docs.prod.drupal.uiowa.edu

Scope to SiteNow Drupal 9 page and children of the Drupal Developer Documentation in SharePoint https://iowa.sharepoint.com/sites/drupal-developer-documentation/SitePages/SiteNow%20Drupal%209/SiteNow%20Drupal%209.aspx.

Not refactoring as part of this slice just moving.

Grooming conversation https://github.com/uiowa/uiowa/issues/4270#issuecomment-2138035442

We should link that section from Sharepoint to the new docs.
```[tasklist]
### Tasks
```

**Comment by e-marie-w** [comment]
SiteNow Drupal 9 section now on new docs site, with links on old site to new.
