### ISSUE TITLE
Deprovision pharmacy-dean.jobs.uiowa.edu

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#7741]
Deprovision pharmacy-dean.jobs.uiowa.edu v3 site and create a backup.

**Comment by bspeare** [comment]
Before deprovisioning:

Please pull in the content and menu structure from the pharmacy-dean.jobs.uiowa.edu if possible to provide me with a template that I can work from to develop the site.

**Comment by joewhitsitt** [comment]
>Please pull in the content and menu structure from the pharmacy-dean.jobs.uiowa.edu if possible to provide me with a template that I can work from to develop the site.

Can you expand on this @bspeare?

Is this a site-backup to onedrive and shared with someone like the IS describes or something more?

**Comment by bspeare** [comment]
@joewhitsitt just a standard copy https://docs.prod.drupal.uiowa.edu/sitenow-drupal-9/copy-website.

**Comment by bspeare** [comment]
Copy to law-dean.jobs.uiowa.edu was not mentioned here, sorry!

**Comment by bspeare** [comment]
Support thread: https://iowaweb.slack.com/archives/C05NDUQ7VKN/p1717105390679569

**Comment by joewhitsitt** [comment]
Clarified with @pyrello that the sync to law-dean was performed and the customer was notified through the resend email

>As requested, this site has been synced with the Pharmacy Dean Search site to speed up the process of development.

**Comment by joewhitsitt** [comment]
followed-up with a backup located on Teams/Sharepoint. emailed saying we would be queuing it up for removal
