### ISSUE TITLE
Reminders about August 1st deadline to transition

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7744]
# Story

As a web team, we would like to remind SiteNow v1 Standard sites that are transitioning to SiteNow v3 that August 1st deadline is approaching so that they don't forget and miss the deadline.

# Additional Info

**Comment by briand44** [comment]
Is this blocked until we finish conversations with College/Department/Unit leaders about sites that did not request a site https://github.com/uiowa/uiowa/issues/7351? My thinking is that we still are not sure if these sites are going away or not so we don't know if they should be included in this communication.

**Comment by briand44** [comment]
Grooming conversation... We can keep the sites Michael is communicating with out of scope for this. Those never requested a v3 site.  We can draft both emails with minimal changes between them. Schedule first reminder. We will want to adjust the population prior to scheduling and sending the final reminder. Initial reminder we can schedule for as soon as we are comfortable. Final reminder sometime the week of July 10th.

**Comment by joewhitsitt** [comment]
Wait, we don't have a population list for this group of folks right? Previously we targeted D7 with no v2/v3 request which was modified/reduced each time we sent a reminder.

This seems like it is a list of v2/v3 site owners (requesters) that have not launched but have a v1 site still. Correct?

**Comment by briand44** [comment]
>This seems like it is a list of v2/v3 site owners (requesters) that have not launched but have a v1 site still. Correct?

Seems accurate. v1 standard site contacts that have requested a new site but haven't launched.

**Comment by joewhitsitt** [comment]
Started a population here: https://apps.its.uiowa.edu/dispatch/populations/1330094574/configure

Going the manual route for this one. Using the D7 spreadsheet filtered down to standard, active, requested I am looking up the entry in the site request form that has a recent point of contact (requester), the v1 URL and the internal-production URL.

Bad news so far is that I am seeing a lot of fresh demo content...

**Comment by joewhitsitt** [comment]
population list is done. i'd say ~90% have not removed demo content from the homepage. 😬

**Comment by joewhitsitt** [comment]
Here is the draft for the two emails:

https://iowa.sharepoint.com/:w:/r/sites/CSI-Drupal2/Shared%20Documents/v1standard-transition-reminder.docx?d=wb4f9224d1bbb4592a226514261b8bf36&csf=1&web=1&e=RXZCiv

>After this date, we will launch the replacement website at ${v1domain} with the content that has been migrated.

Open to discussion about the consequence here. I looked through the previous issues about this and it wasn't clear, particularly for this [segment 2 of v1 standard websites](https://github.com/uiowa/uiowa/issues/7156#issuecomment-1858083731).

Also added in a "need extension" and a "no longer need either" bit which I think can be discussed as well.

The final reminder is a short/blunt reminder but with different possible off ramps.

**Comment by joewhitsitt** [comment]
Comment and review are still open on the drafts, but I have moved what we have to a dispatch campaign in order to get the variables to work. Updated the population to remove https:// and have instead handled those instances in the template.

<img width="644" alt="Screenshot 2024-06-19 at 10 10 26 AM" src="https://github.com/uiowa/uiowa/assets/4663676/e82c9c00-1bef-4461-affd-86eaf55fc0d2">

**Comment by joewhitsitt** [comment]
Test email in its-web: `[Test] Action Required: Transition accessibility101.course.uiowa.edu from SiteNow v1 Standard by August 1, 2024`

**Comment by joewhitsitt** [comment]
Scheduled for 9:45 AM tomorrow, so standup will be last chance to stop it.

https://apps.its.uiowa.edu/dispatch/communications/1331262751

**Comment by briand44** [comment]
I thought we removed the text about launching even if they aren't finished. Are you just testing us Joe? Also, the request an extension?

**Comment by joewhitsitt** [comment]
Good eye. Copy/pasta/track changes issue. Fixed. Test message sent again.

**Comment by joewhitsitt** [comment]
Email went out. The email for michaelson.lab.uiowa.edu didn't get delivered. Going to login to the website, fetch another contact and send them an email.

Update: ✅
