### ISSUE TITLE
Enable Local Event Feature for Law INRC

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7754]
# Story

As a site owner for Law INRC, we would like to have the local event feature enabled on our site so we can see if the existing functionality will meet our needs for promoting our events to our statewide audiences.

# Proposed solution

```[tasklist]
### Tasks
- [x] Enable local event feature
- [x] Communicate to stakeholders that this is now available
```

**Comment by briand44** [comment]
Blocked until the site has been provisioned.

**Comment by pyrello** [comment]
This has been completed.
