### ISSUE TITLE
CCOM Article migration only pulling title

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7759]
Ethan and Brady reported that while trying out the CCOM article migration locally they were only getting the title to migrate over. They would appreciate us taking a look and/or pairing on it to try and troubleshoot.

I believe the site they were trying to migrate from was https://medicine.uiowa.edu/biochemistry-molecular-biology/ to bmb.medicine.uiowa.edu

**Comment by bspeare** [comment]
This has been resolved.  We walked through https://github.com/uiowa/uiowa/pull/7090 and the articles were migrated successfully.
