### ISSUE TITLE
Import of url redirects for CLAS

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7761]
# Story

As a site owner of clas.uiowa.edu, I would like our CSV of redirects imported to our new v3 website, so we don't have to manually recreate all of them prior to launch.

# Additional Info

We created an export in #7399 

CLAS has removed entries no longer needed.

We imported redirects for Tippie previously and likely can reuse some of that work.

Grooming conversation https://github.com/uiowa/uiowa/issues/7399#issuecomment-2148358869

It was mentioned that we can probably move forward on some of this prior to having the final csv.

**Comment by briand44** [comment]
blocked because we are waiting to see how many redirects there are once they go in and remove all the redirects that have a node id in the source or destination or other redirects that should not be migrated.

**Comment by briand44** [comment]
Maggie got me the list of redirects she wants to keep. https://iowa.sharepoint.com/:x:/r/sites/CSI-Drupal2/_layouts/15/Doc.aspx?sourcedoc=%7B0C204BD8-5F2E-414B-BC9F-74BA57F8E56C%7D&file=redirect_export_keep.xlsx&action=default&mobileredirect=true

**Comment by briand44** [comment]
Grooming Conversation....

In addition to Tippie, we may have done something similar for HR and the Homepage site as well. Tippie may have some additional code to handle some special characters. We do now have a site split for clas.uiowa.edu and a module `clas_core` that is enabled where we could place the update hook. Discussed that it would be good to run this in dev first and have CLAS folks spot check before running in prod.

Tippie work

`docroot/sites/tippie.uiowa.edu/modules/tippie_core/redirects/2022_tippie_redirects.csv`

https://github.com/uiowa/uiowa/blob/3c0a288f6739a82320504326bfc11a6a9f701bb5/docroot/sites/tippie.uiowa.edu/modules/tippie_core/tippie_core.install#L13

HR: 
https://github.com/uiowa/uiowa/blob/757d5cf402fff29c38cfa455b2fec8e95a230c70/docroot/sites/hr.uiowa.edu/modules/hr_core/hr_core.install#L311
Homepage: 
https://github.com/uiowa/uiowa/blob/757d5cf402fff29c38cfa455b2fec8e95a230c70/docroot/sites/uiowa.edu/modules/uiowa_edu_core/uiowa_edu_core.install#L50

**Comment by bspeare** [comment]
The redirects have run in dev: https://clas.dev.drupal.uiowa.edu/.
