### ISSUE TITLE
SiteNow June 2024 Newsletter

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#7770]
### Issue/Solution
Provide a "release notes" type article of finished/done features/updates and publish to website, then send out dispatch email.

- [ ] Create draft and update the parking lot card with an edit link (https://sitenow.uiowa.edu/node/636/edit)
- [ ] Add "release notes" covering the month of v2/v3 default profile enhancements and webmaster/edit visible bug fixes.
- [ ] See the previous month's article as an example.
- [ ] Bullet points from demo stories slide per week: https://drive.google.com/drive/folders/1EehKUjxCbakaB9FchrGhAbaxuRbqyDGW?usp=sharing.. and/or from Web Community sprint demo announcements https://webcommunity.sites.uiowa.edu/updates/2023/02/sprint-demo-149-february-16-2023
- [ ] If any notable site launches are included, make sure the sites are linked.
- [ ] Get at least one team member to look over the draft before publishing.
- [ ] Since the draft was started earlier, adjust the publish date/time, publish, get the link to the article.
- [ ] Dispatch email with link to article. (To get access, send an email to [dispatch-support@uiowa.edu](mailto:dispatch-support@uiowa.edu) to have the account provisioned. Provide your hawkid and mention the CSI:drupal group)
  - [ ] Modify SiteNow Announcements Template (tweak opening line, update the article link, any other editorial adjustments)
  - [ ] Clone an old communication off SiteNow Announcements campaign
    - [ ] Use SiteNow Announcements population, template, suppression list, bypass approval.
    - [ ] Turn off Dispatch "test mode" to send out email.
    - [ ] When scheduling, check the "archive" option so that there is an RSS instance we can use in the future. I don't think this can be done after the fact.
- [ ] Turn on Dispatch "test mode" after email is successfully sent.
- [ ] Take a moment to check dispatch and google analytics on whether these articles are being read.
- [ ] Create the next months's issue and copy all this bullet list into it, removing the checked boxes if any.

**Comment by bspeare** [comment]
Draft at https://sitenow.uiowa.edu/news/2024/06/updates-june-2024

**Comment by pyrello** [comment]
I think we should consider having the person who prepares the email sign it on behalf of the team as a nice personal touch. Something like:

> Best regards,
> Sean and the OSC Web Team

**Comment by pyrello** [comment]
This message seems odd since there is only 5 revisions. As a content editor, this might unnerve me a bit.

![Screenshot 2024-07-02 at 9 49 22 AM](https://github.com/uiowa/uiowa/assets/709009/966e42b4-3aad-4b9d-88fa-c156e0aaf762)

**Comment by joewhitsitt** [comment]
Yeah, @bspeare brought that up earlier for something else. I briefly looked to see if the module/issue queue allows suppressing that message but didn't find anything.

On node save we could query the list of messenger items and remove it ourselves similar to what I had previously done for scheduler. https://github.com/uiowa/uiowa/pull/7044/commits/48b08b246608462602f50a32f6c6157787679775

**Comment by joewhitsitt** [comment]
Made a small addition. ✅

**Comment by pyrello** [comment]
According to our Dispatch analytics, since the beginning of the year:

**Total messages delivered:** 1,816 (88.63%)
**Messages that have been opened:** 819 (45.1%)
**Messages that have been clicked:** 266 (14.65%)

Not bad.
