### ISSUE TITLE
Emergency Hawk Alerts - Clean up dual endpoint functionality for v2/v3

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#7778]
There is code to switch from the old functionality to the new functionality based on the `.json` extension being present. Once the new site is launched, this old code can be cleaned up (js, library, block logic).

See https://github.com/uiowa/uiowa/pull/7733 for more info.

**Comment by joewhitsitt** [comment]
https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/uiowa_alerts/es6/uiowa_alerts.es6
https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/uiowa_alerts/uiowa_alerts.libraries.yml

https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/uiowa_alerts/src/Plugin/Block/AlertsBlock.php#L76-L81

**Comment by briand44** [comment]
Grooming conversation... Now that we are no longer hitting the old endpoint, there is some cleanup that can happen. One of the JS files can be removed.

**Comment by joewhitsitt** [comment]
A test could be to switch to emergency.stage (api/active) to make sure the alert there is still populating a site locally.
