### ISSUE TITLE
Run writers bio migration in prod

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7783]
In #7702 we ran the migration in dev. Once approved, we need to run the migration in prod. After they will need to update any sessions, add any additional writers bios that had multiple sessions in the past, etc.

They should wait to make updates until we add the visitor checkbox.

```[tasklist]
### Tasks
- [x] Run migration in prod
- [x] communicate and share list of writers bios with multiple sessions https://github.com/uiowa/uiowa/issues/7699#issuecomment-2140682924
```

**Comment by briand44** [comment]
blocked until they approve.

**Comment by briand44** [comment]
Grooming conversation... Shouldn't need to remove any test data since I believe that was removed in prod before we ran the migration in dev. Brian can handle the communication with IWP if he's available. We may want to deploy https://github.com/uiowa/uiowa/issues/7810 prior to running this in prod so that boolean will have a FALSE value rather than NULL.

**Comment by joewhitsitt** [comment]
boolean deployed. backing up database. about to run it

**Comment by joewhitsitt** [comment]
Migration seemed successful.

>Brian can handle the communication with IWP if he's available.

@briand44 do you still want to do this?

**Comment by briand44** [comment]
sure

**Comment by briand44** [comment]
done communicating.
