### ISSUE TITLE
Communicate with v1 custom -> v3 standard sites that haven't requested a v3 site

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7793]
6 sites that have not requested a site:
- ~animal.research.uiowa.edu~
- ~ehs.research.uiowa.edu~
- hawkeyespaces.uiowa.edu
- ~portalpages.research.uiowa.edu~
- ~report.hancher.uiowa.edu~
- ~ris.research.uiowa.edu~

Next step another communication? Since four sites have the same contact we could just do it manually via its-web instead of a dispatch communication.

**Comment by briand44** [comment]
Grooming conversation... Follow up with the contacts for these sites individually to understand if they plan to transition or not.

**Comment by briand44** [comment]
Keeping this in blocked/waiting for now to see if we get responses on the three remaining sites. If not, we may need to include other contacts.

**Comment by GaryRidgway** [comment]
If we dont hear by tuesday the 25th of june 2024 we contact wendy

**Comment by bspeare** [comment]
Resent the email to Wendy.

**Comment by bspeare** [comment]
Repsonse: planning to migrate the site contents to the main athletics website, not on SiteNow. I will need a month or two to get this completed.

**Comment by briand44** [comment]
I updated our spreadsheet to include the comment from ^^ and set the recommendation column to "Going Away". I think we can close this now that we have a response for all of these.
