### ISSUE TITLE
limit imageMagick memory

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7809]
# Story

As a webteam, we would like to limit the amount of memory imageMagick uses so we can avoid risk of an outage.

# Additional Info

Related to https://acquia.my.site.com/s/case/500Pb00000DoZBHIA3/action-required-out-of-memory-issue-detected

> So what needs to be done to resolve this is to limit the available memory for the convert utility. I was told that something like this may work, but I am also looking for more clarity on this:
>  
> `- convert -limit memory 256MB -limit map 512MB input.jpg -resize 50% output.jpg`
> 
> Please let me know if this makes sense, and I am also going to see about getting more clarity on this for you. 

https://www.imagemagick.org/script/command-line-options.php#limit

# Proposed Solution

- Possibly add `-limit memory 256MB -limit map 512MB` to the Prepend Arguments field on the Execution Options tab https://default.prod.drupal.uiowa.edu/admin/config/media/image-toolkit#edit-imagemagick-exec-prepend
- Config changes to `imagemagick.settings`
- Testing?
- Let Acquia know we made this change and possibly close?
  - https://acquia.my.site.com/s/case/500Pb00000DoZBHIA3/action-required-out-of-memory-issue-detected
  - https://acquia.my.site.com/s/case/500Pb00000DiHDqIAN/campus-websites-went-down-today-can-you-offer-any-insight

**Comment by briand44** [comment]
Grooming conversation... As part of testing, we can test to make sure we are not breaking anything with this change locally. Can push to dev and test. All media image uploads are processed with imageMagick. Image style generations (preview) all are also ran through this so we could verify those still function as expected.

**Comment by joewhitsitt** [comment]
Just looking at the future, this change might be short lived.

https://www.drupal.org/project/imagemagick/releases/4.0.0 for Drupal 10.3+

Deprecates `convert` in favor of `magick`

**Comment by joewhitsitt** [comment]
Additionally, stepping up a minor version might involve a bunch of testing again to make sure file_mdm and such still operate as expected - https://www.drupal.org/project/imagemagick/releases/8.x-3.7

**Comment by briand44** [comment]
We still need to remember to follow up with Acquia and let them know we've implemented this, once this is deployed.
