### ISSUE TITLE
Content Overview Filter By Tags

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#781]
With #598 and #720 we will have adopted tags on all content types so why not allow people to filter content by it to get some backend use out of it.

## Proposed Solution
Add filter by tag autocomplete on the content overview page without compromising the view to future core updates.

<img width="1184" alt="Screen Shot 2020-04-30 at 10 14 12 AM" src="https://user-images.githubusercontent.com/4663676/80727493-65d9fb00-8acb-11ea-9d6d-49deda4cc53e.png">

**Comment by joewhitsitt** [comment]
field_tags as implemented by #598 . Need to do this in a way that it does not fork the overview view implemented by Drupal core. @briand44 mentioned something about programmatically adding the filter.

**Comment by briand44** [comment]
Here is a similar example for a D7 site where the filter is being added programmatically. https://github.com/ITS-UofIowa/registrar.uiowa.edu/blob/master/modules/custom/registrar_feeds/registrar_feeds.module#L125

**Comment by dnkemper** [comment]
Lost work from environment issues.

**Comment by joewhitsitt** [comment]
So, I think since "admin_views" is in core now, all that needs to happen is that we disable the current (core-provided) view, duplicate it, add the tags filter, maybe remove the language filter, enable the view and export.

**Comment by briand44** [comment]
or we could try to add it programmatically, that way we still get any new updates if there are any.
