### ISSUE TITLE
add visitor boolean to writers bios

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7810]
# Story

As an IWP site owner, I would like to have a boolean field for visitors on the writers bio content type so that while we are updating content after the migration, we can denote visitors in case we want to do something different with them in the future.

# Additional Info

Boolean option to designate a writers bio as a visitor.

No need to output this anywhere at this point.

**Comment by briand44** [comment]
Grooming conversation... Do we need to worry about null vs FALSE? Yes, we either need to create this field before we run the migration in prod so all nodes get saved as FALSE or we will need an update hook or some other way of saving each node to make sure they are FALSE and not NULL.

**Comment by cory-skeers** [comment]
> ...we either need to create this field before we run the migration in prod so all nodes get saved as FALSE or we will need an update hook or some other way of saving each node to make sure they are FALSE and not NULL.

Another thought right as we left grooming:

If we don't add the field prior to migration and go the save/update route, revisions should be accounted for as well to avoid the possibility a node gets reverted to a revision with a null and doesn't get re-saved after. If added before migration, all bios will always have a value here.
