### ISSUE TITLE
Enable uiowa_maui for Commencement

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7812]
# Story

As a commencement site owner, I would like to have the ability to show upcoming academic dates so that visitors to our site can find any deadlines related to graduation and commencement.

# Additional Information

Functionality already exists in `uiowa_maui` from https://github.com/uiowa/uiowa/issues/2714 and https://github.com/uiowa/uiowa/issues/4935

We just need to enable uiowa_maui and import config

`ddev drush @commencement.prod config-split:activate uiowa_maui && ddev drush @commencement.prod cim`

```[tasklist]
### Tasks
```

**Comment by e-marie-w** [comment]
This is done!
