### ISSUE TITLE
Communicate Emergency site launch date for folks updating integrations

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7815]
As part of https://github.com/uiowa/uiowa/issues/7654, we communicated with the app dev and web community lists. We should send another communication to those lists letting folks know when the new site (and new endpoint) will be live.

# Additional Info

Send communication to app dev list
Send communication to web community list
Do we need to update https://sitenow.uiowa.edu/news/2024/05/upcoming-changes-hawk-alerts-api?

**Comment by briand44** [comment]
blocked until we know the launch date.

**Comment by briand44** [comment]
Launch date set for Wednesday, July 31st. Will perform a test Hawk Alert in production on August 1st.

**Comment by joewhitsitt** [comment]
Here is my draft to send to app-dev and ui-web. Suggested changes or emoji approval?

>The University of Iowa Emergency website will be launching a new version on Wednesday, July 31st between 8 AM and 12 PM. As noted previously, the website contains an API for consuming information about Hawk Alerts and it will be changing. On launch, the endpoint URL will change to https://emergency.uiowa.edu/api/active and we have detailed the other changes in this article (https://sitenow.uiowa.edu/news/2024/05/upcoming-changes-hawk-alerts-api). 
>
>On Thursday, August 1st at 10 AM, a test Hawk Alert will go out to the website so that developers across campus can confirm everything is working as expected and that the system will be ready in the case of an actual Hawk Alert.
>
>Please contact the OSC Web Team (its-web@uiowa.edu) or Campus Safety (campus-safety@uiowa.edu) if you have further questions about the Emergency website launch.

**Comment by joewhitsitt** [comment]
Sent to both uiweb and ui-appdev 7/16 ~09:52
