### ISSUE TITLE
SSL for pre-approved `*.program.uiowa.edu` pattern.

### ISSUE THREAD

**Issue by GaryRidgway** [uiowa/uiowa#7817]
Hostmaster is waiting until the middle of July to create the `*.program.uiowa.edu` pattern and point it to acquia. They will contact us when they are ready for this, and then we can proceed with creating the SSL Cert on uiowa07 for `*.program.uiowa.edu`.

We can then make another issue to add SSL certs to other apps with this pattern if we deem it necessary.

**Comment by joewhitsitt** [comment]
Should we check in on the status of this?

**Comment by joewhitsitt** [comment]
Sent an email to Austin and Hostmaster to check on the status.

**Comment by bspeare** [comment]
The pattern has been established and this is no longer blocked.

**Comment by bspeare** [comment]
As mentioned in the issue summary, eventmanagement.program.uiowa.edu is on uiowa07.

**Comment by briand44** [comment]
This has been added to uiowa07. Didn't add to other apps. We should create an issue for other apps when the need arises.

**Comment by joewhitsitt** [comment]
> This has been added to uiowa07. Didn't add to other apps. We should create an issue for other apps when the need arises.

We never created that follow up issue. https://github.com/uiowa/uiowa/issues/8383
