### ISSUE TITLE
Test Hawk Alert for emergency.stage.drupal.uiowa.edu

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7818]
# Stories

As a web team getting ready to launch a new Emergency website, we want to communicate to campus that we will be having a test Hawk Alert on emergency.stage.drupal.uiowa.edu so that campus partners can test their updated integrations with the Emergency website.

As a web team getting ready to launch a new Emergency website, we want to have a test Hawk Alert in our stage environment so we can verify things are working as expected prior to launch.

# Additional Info

Test Hawk Alert will be scheduled for Wed, June 26th at 11am.

Communicate this to app dev list and web community list.

Preparations for test Hawk Alert:
  SiteNow v1
  Signage/HC Signage
  SiteNow v2/v3

Verify things are working as expected during the test alert.

# Questions

Do we need to sync stage from prod? Any config adjustments if we do?
Do we need to remove existing test alerts?
```[tasklist]
### Proposed Solution
- [x] Send short email to appdev and web community with the date and time of the test
- [x] Re-sync down emergency from Prod to Stage and confirm endpoint is still set to the RAVE test channel
- [x] Re-sync admissions from Prod to Stage and set the endpoint to emergency.stage to test v2/v3 functionality
- [x] Confirm signage dev has the feature branch checked out and is configured to use emergency.stage
- [x] At the time of the test, confirm emergency.stage gets an active alert on the homepage and is showing an entry for /api/active
- [x] Check admissions and signage to see if they are receiving the hawk alert from emergency.stage
- [ ] If emergency.stage fails to recieve the alert from RAVE, create a manual hawk alert on emergency stage saying we are dealing with technical diffuculties and will schedule another test
```

**Comment by joewhitsitt** [comment]
Talked about this with Brian a bit. I think a heads up email with the date and time could be drafted/sent as a JDI this sprint if folks start twiddling thumbs in order to get it out ahead of the test.

**Comment by briand44** [comment]
Capturing a comment from Joe

> For v2/v3 temp sync [admissions.stage.drupal.uiowa.edu](http://admissions.stage.drupal.uiowa.edu/) or another site and set the endpoint to https://emergency.stage.drupal.uiowa.edu/api/active. For signage, confirm feature branch is still checked out and ready in DEV. v1 disregard or also check that feature branch is checked out and configured. We probably should clean up existing content on emergency stage. Close the actual alerts. Delete the test content.

**Comment by briand44** [comment]
Grooming conversation... Disregard v1/HC Signage. Hawktools is now redirecting and was the only v1 site with the uiowa_alert functionality enabled. HC Signage has same code as Signage. Testing we want to make sure the alert shows within 1 minute on the Emergency site and that the endpoint has the new alert. V2/v3 get new alerts, signage gets new alert. If something goes wrong, post alert manually through stage so folks who do have code they are testing can still test.

**Comment by joewhitsitt** [comment]
Draft email idea:

>On Wed, June 26th at 11am, the OSC Web Team will be performing a test of the new Hawk Alerts functionality for the University of Iowa Emergency website. This is an opportunity for developers who integrate with the emergency website to test their modifications before the new website is launched. The test alert will be posted to https://emergency.stage.drupal.uiowa.edu/api/active

Update: Sent 6/21 8:45ish

**Comment by pyrello** [comment]
How is the test alert actually getting populated for this? Do we need to have our RAVE developer partners populate one?

**Comment by joewhitsitt** [comment]
Brian asked Haley to coordinate the RAVE end and she confirmed.

**Comment by pyrello** [comment]
> Brian asked Haley to coordinate the RAVE end and she confirmed.

Has this been done? Are we waiting?

**Comment by joewhitsitt** [comment]
Waiting for the actual test at Wed, June 26th at 11am yes. Other parts of this task though can move forward with the assumption the alert will show up at that time.

**Comment by pyrello** [comment]
I'll work on the parts of this that can be done ahead of time. I'll be gone for the actual test, so someone else will need to pick this up for that part.

**Comment by pyrello** [comment]
I think I have everything setup for tomorrow.

**Comment by joewhitsitt** [comment]
Ken emailed me saying there is still a CORS issue. I just went to signage-dev and noticed it in the console as well. Something must be getting cached and it isn't always allowing.

Ken is using a proxy to bypass CORS but would love not to rely on it.

**Comment by joewhitsitt** [comment]
Can't tell if this is a feature or a bug. Clearing site and varnish cache (which should happen when a hawk alert is imported and saved) fetches the correct CORS headers, but at some point it regresses and doesn't send the correct headers leading to CORS errors for the consumers like Signage. The benefit is the cached copy that helps with DoS type stuff.

From what I am reading we could have an issue with our Varnish VCL file in that headers are not part of the cached copy.

**Comment by joewhitsitt** [comment]
Opened a ticket with Acquia

**Comment by joewhitsitt** [comment]
>The Vary header tells caching mechanisms (like Varnish or browser caches) to cache different versions of the response based on the value of specified request headers. For CORS, this often involves the Origin header.

Might look into adding this to the code but want to understand what the "at what cost" is.

**Comment by joewhitsitt** [comment]
showed up in rave a bit after 11:01 for me with a 11:00:52 timestamp. looks like most got it by 11:02.

![Image](https://github.com/uiowa/uiowa/assets/4663676/43970890-c044-470f-aef2-b89f23d9df09)
![Image](https://github.com/uiowa/uiowa/assets/4663676/f63192a6-2b6f-486c-a343-77a2ef69fc42)
![Image](https://github.com/uiowa/uiowa/assets/4663676/936d7094-07d5-40a9-a4f2-be2bbcd972fb)

**Comment by joewhitsitt** [comment]
>the emergency homepage does not auto-refresh a user's browser if they were sitting on that page waiting. not sure if that is a issue or not

Update: looks like we could just set this on the homepage using the meta refresh option

![Image](https://github.com/uiowa/uiowa/assets/4663676/cba5049e-8a80-4fb9-8708-14af00b1b8c6)

Update: set this to 55 seconds on emergency.prod. image fade makes it quite noticeable though. removing images on this page could help. everything seems cached except for tag manager and newrelic

**Comment by joewhitsitt** [comment]
> > The Vary header tells caching mechanisms (like Varnish or browser caches) to cache different versions of the response based on the value of specified request headers. For CORS, this often involves the Origin header.
> 
> Might look into adding this to the code but want to understand what the "at what cost" is.

I updated the Acquia ticket with this, but it sounds like if Varnish handles this as expected, there will be a cached varnish copy with the correct headers for each origin. The "cost" is that this could grow in size and then it isn't clear if site cache/acquia_purge will properly invalidate them all.

Still not clear to me how incorrect headers are getting served. Ken temporarily switched over and said it was no longer an issue but will keep using the proxy until more information from Acquia is provided.

**Comment by joewhitsitt** [comment]
In terms of the test and this issue, I think this is done.

**Comment by joewhitsitt** [comment]
The response back from Acquia was this knowledge-base article that I have seen before: https://acquia.my.site.com/s/article/360016601133-Using-CORS-in-Drupal-8-with-Varnish-may-lack-some-Access-Control-Allow-headers

If I interpret the issues correctly we should proceed with the Vary, Origin header.

Still don't know the true cost of this will be in terms of varnish resources, but at least our exposure is less than enabling CORS for the whole site/platform.
