### ISSUE TITLE
commencement import

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7822]
Josh said he has created some new commencement events on content hub and they are not showing on the new website.

Example of content hub event https://content.uiowa.edu/143441/college-pharmacy-doctor-pharmacy-commencement-ceremony

Verified the event is approved and has the unit "Commencement" (7266) and the type "Commencement" (355).

**Comment by briand44** [comment]
Grooming conversation... Not sure if we ever had a successful import in the production environment so sizing a little bigger based on that.

**Comment by e-marie-w** [comment]
The scheduled jobs were using the old alias name for the event import. I've updated them to use the new. We should be able to see if it worked later this afternoon.

**Comment by e-marie-w** [comment]
Update: event importer now running fine and the migrated duplicates were removed. I noticed that paragraph breaks and link tags were being lost, however, so fixing in #7849.
