### ISSUE TITLE
SSL for 4 sites on uiowa07

### ISSUE THREAD

**Issue by GaryRidgway** [uiowa/uiowa#7827]
We need SSL coverage for these 4 sites on uiowa07

* https://ris.research.uiowa.edu/
* https://ehs.research.uiowa.edu/
* https://animal.research.uiowa.edu/
* https://report.hancher.uiowa.edu/

**Comment by joewhitsitt** [comment]
*.research.uiowa.edu to reduce number of SANs

**Comment by joewhitsitt** [comment]
This is done.
