### ISSUE TITLE
re-install https://courseaccessibility101.prod.drupal.uiowa.edu

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7831]
> I have a site at https://courseaccessibility101.prod.drupal.uiowa.edu/; it was a project that stalled during pandemic and on which I changed direction. Will you please wipe that instance entirely and replace it with an out of the box provision of SiteNow v.3? If you can do that, I will test SNv.3 as thoroughly as I can on my own using automated, manual, and heuristic tests, as well as assistive technology (screen readers, keyboard, voice command). The standard will be WCAG 2.1 AA, with common sense markers for issues that may not be explicitly addressed in those guidelines.

**Comment by bspeare** [comment]
This is done.  Emailed TM.
