### ISSUE TITLE
Dates by session

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7843]
# Story

~As a Registrar site owner, we would like the ability to configure the academic calendar to group by session so that we can maintain similar functionality as our existing dates by session.~ - This should already be addressed.

As a Registrar site owner, we would like the ability to show calendar dates going back two years and forward 2 years since that is how far out the academic calendar committee plans the calendar dates.

# Additional Info

https://registrar.uiowa.edu/dates-by-session

They liked what we demoed them for the Academic Calendar when we had that grouped by session. Will likely need its own page still and have more sessions available than the academic calendar.

They mentioned 2 years back and 2 years forward but it looks like they may currently be showing more than that. Possibly current session +/- 10?

Filter by category - same as academic calendar categories
is web display - similar to academic calendar
is reviewed - similar to academic calendar
more used internally by departments so they don't have to scroll through each month

**Comment by briand44** [comment]
Grooming conversation... Plan to use existing academic calendar block. Need to expand sessions to meet the needs here.

**Comment by GaryRidgway** [comment]
So, If I am looking at this right, the calendar already does the getting of the dates for ALL published calendar events. Currently, sessions are populated only if that session has an event. if the session isn't in the dropdown, it doesn't have anything to display.

Are we wanting to populate sessions with no content in the dropdown menu?

**Comment by briand44** [comment]
My understanding is that there is currently block config to determine the sessions to display. The calendar needed to be able to display the current session +5 sessions. The dates by session needs to display something like +/- 2 years or +/- 10 sessions. I believe there should be a block config option to display the appropriate sessions for this feature that will then return dates for the additional sessions being displayed.
