### ISSUE TITLE
searchable/filterable display of grants

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7844]
# Story

As a site owner for LAWINRC, I would like to have the ability to search and filter grants so organizations can search for funders with a connection to Iowa.

# Additional Info

Their existing functionality has been working well for them and they would like us to develop this feature very similar to their existing functionality.

They want us to eventually migrate the ~700 funders from their current site.

https://inrc.law.uiowa.edu/iowa-grants-guide

- Block component that can be placed on layout builder page
- Alpha search - ability to search grants by the first letter of filter friendly name
- Search Grantor Name - search filter friendly name "contains"
- Filter by NTEE Classification - select multiple
- Filter by areas of interest - select multiple
- Filter by counties - select multiple
- Grant size range filter
- Display teaser which should include Grantor Name (link), purpose/mission, Application Deadline (if exists), application details

**Comment by briand44** [comment]
Grooming conversation... Let's see if we can avoid the alpha search for now. Grant size filter may not get used as much as the others. If that is complex we could try to avoid that as part of this slice as well.

**Comment by bspeare** [comment]
Do we want to do something like this for the view alpha search request? https://its.prod.drupal.uiowa.edu/services

<img width="1391" alt="Screenshot 2024-06-28 at 2 35 02 PM" src="https://github.com/uiowa/uiowa/assets/1036433/76cca0e1-9c50-45e2-b73a-0f90d2645986">

Or a "sort by" field like on Classrooms?

<img width="359" alt="Screenshot 2024-06-28 at 2 29 35 PM" src="https://github.com/uiowa/uiowa/assets/1036433/56c24e41-d2f1-4e41-b3a0-c7614424fd73">

**Comment by bspeare** [comment]
What about this for the grant sizes range?  Should this be broken up even further?  <img width="308" alt="Screenshot 2024-07-03 at 8 57 03 AM" src="https://github.com/uiowa/uiowa/assets/1036433/97ef5fc1-0a72-4aa9-a8e9-5dafa4869852">

**Comment by joewhitsitt** [comment]
Without looking at the existing content, i'd say this was fine to start with and get their reaction. As for the A-Z options:

> Grooming conversation... Let's see if we can avoid the alpha search for now.
