### ISSUE TITLE
theme/mockup grants

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7846]
Current filter page - https://inrc.law.uiowa.edu/iowa-grants-guide
Current node - https://inrc.law.uiowa.edu/grants/iowa-foundation-agricultural-advancement

- theme node teaser and full node
- theming on filter page
- do we want a mockup?

**Comment by briand44** [comment]
Grooming conversation... Probably a little bit of theming on the filter page (# of items in grid, placement of filters). Mockup could be useful here. Decided to leave it up to developer on building within site or a separate mockup.

**Comment by bspeare** [comment]
Here's a mockup of the grant content type. 

![Screenshot 2024-07-08 at 10-38-14 Iowa Foundation for Agricultural Advancement The Larned A  Waterman Iowa Nonprofit Resource Center - The University of Iowa](https://github.com/uiowa/uiowa/assets/1036433/ef5c003c-1f1a-4e62-89d2-eeab8b39f4bd)

**Comment by GaryRidgway** [comment]
For people looking at a glance, it may be logistically better for the grant sizes and totals to be at the top? I'm not sure about the visuals of that, but it may be something to try.

Additionally, I think the white dot pattern runs in to the white body a bit. perhaps another pattern with a darker background would give better separation? 

Other than that, I love the division of the areas, I think the placement of all other information is nice, and the whole thing feels crisp and clean!

**Comment by pyrello** [comment]
A couple quick thoughts:
- I'm curious about the use of the collapsible element for "Application Info." My default is to be skeptical that collapsible elements are actually necessary. If it is, wouldn't it look better to use a regular full width details element? It would be easier to see at a glance that it is a collapsible element and should be clicked for more info.
- Minor nit: With the spacing between each element with an icon in the sidebar, the first element looks weirdly close to the contact name. I think it either needs space before the phone number or to not have the extra space between those elements.

**Comment by bspeare** [comment]
The "Application Info" gets a little messy and long with the formatting/spacing so I was trying to clean that up a bit by putting it into the details.   

Without details:
![Screenshot 2024-07-08 at 11-07-15 Iowa Foundation for Agricultural Advancement The Larned A  Waterman Iowa Nonprofit Resource Center - The University of Iowa](https://github.com/uiowa/uiowa/assets/1036433/c2203cab-95be-4339-99fa-45b626068179)


With basic details:
![Screenshot 2024-07-08 at 11-07-48 Iowa Foundation for Agricultural Advancement The Larned A  Waterman Iowa Nonprofit Resource Center - The University of Iowa](https://github.com/uiowa/uiowa/assets/1036433/f7876f5d-2d9c-45e5-ac9c-109109f831cc)

**Comment by bspeare** [comment]
Sidebar spacing update:

![Screenshot 2024-07-08 at 11-19-06 Iowa Foundation for Agricultural Advancement The Larned A  Waterman Iowa Nonprofit Resource Center - The University of Iowa](https://github.com/uiowa/uiowa/assets/1036433/4d95c3d5-db83-4c36-af5f-db004a7aa33f)

**Comment by pyrello** [comment]
> The "Application Info" gets a little messy and long with the formatting/spacing so I was trying to clean that up a bit by putting it into the details.
> 
> Without details: ![Screenshot 2024-07-08 at 11-07-15 Iowa Foundation for Agricultural Advancement The Larned A Waterman Iowa Nonprofit Resource Center - The University of Iowa](https://private-user-images.githubusercontent.com/1036433/346636930-c2203cab-95be-4339-99fa-45b626068179.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0NTUyNzMsIm5iZiI6MTcyMDQ1NDk3MywicGF0aCI6Ii8xMDM2NDMzLzM0NjYzNjkzMC1jMjIwM2NhYi05NWJlLTQzMzktOTlmYS00NWI2MjYwNjgxNzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDhUMTYwOTMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTAwNGE0ZmY5ZTlmNmUxMDM4MzVhMDY1NTZiZmExODBlYWQ4Mzk5OTc4NTZkYjRmMTkwNjA5MmFjMWQyMDkxOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.NOgPlR7MNpLhfyRhpWkm6o2PZ3VnZs7kz2TfUDWDoGc)
> 
> With basic details: ![Screenshot 2024-07-08 at 11-07-48 Iowa Foundation for Agricultural Advancement The Larned A Waterman Iowa Nonprofit Resource Center - The University of Iowa](https://private-user-images.githubusercontent.com/1036433/346636995-f7876f5d-2d9c-45e5-ac9c-109109f831cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0NTUyNzMsIm5iZiI6MTcyMDQ1NDk3MywicGF0aCI6Ii8xMDM2NDMzLzM0NjYzNjk5NS1mNzg3NmY1ZC0yZDljLTQ1ZTUtYWM5Yy0xMDkxMDlmODMxY2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDhUMTYwOTMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjEyYmU3NDdhYzlkMDNjOGQ2YmFlZGExNTgwYzNiOWIwZWRkMjBiNzUxN2FkMGI0NjA3NzI4ZjY2MjY4M2M2YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.cePnTLUnfl5QoGWiy7px8r46Y3OjWpKz42W-Xz86eJ8)

I guess I was thinking about our gray accordion details not a plain one.

**Comment by bspeare** [comment]
Here's an accordion view of the application details moved down into the order that it is on the current site:

![Screenshot 2024-07-08 at 11-38-57 Iowa Foundation for Agricultural Advancement The Larned A  Waterman Iowa Nonprofit Resource Center - The University of Iowa](https://github.com/uiowa/uiowa/assets/1036433/40fafd34-0e82-4159-8ceb-ebabdb098f82)

**Comment by pyrello** [comment]
> Here's an accordion view of the application details moved down into the order that it is on the current site:
> 
> ![Screenshot 2024-07-08 at 11-38-57 Iowa Foundation for Agricultural Advancement The Larned A Waterman Iowa Nonprofit Resource Center - The University of Iowa](https://private-user-images.githubusercontent.com/1036433/346647348-40fafd34-0e82-4159-8ceb-ebabdb098f82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0NTc1NzIsIm5iZiI6MTcyMDQ1NzI3MiwicGF0aCI6Ii8xMDM2NDMzLzM0NjY0NzM0OC00MGZhZmQzNC0wZTgyLTQxNTktOGNlYi1lYmFiZGIwOThmODIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDhUMTY0NzUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTk2YTg3YzM4YWYxOWExMDQ4NTIzOGZkODk1MmFlNWUzOTExYjg3ODQ3ODMyZjU3YjQ0ODM3MTg0MGU3NWFlYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-sFWBGg9STAAmRMUxmCBfPB6k_HcuauulQOA4O516DA)

I like this better if we end up going with a collapsible element.

**Comment by briand44** [comment]
This may be a little late but I think the Date of Last Financial Data we want to only be outputting Month/Year. We have the granularity for day because we have to with the date module we are using but the day will be irrelevant. Let me know if this should be added to #7895 instead?
