### ISSUE TITLE
Add validation to listblock items_per_page to prevent blank/non-values

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#7848]
# Problem

With https://github.com/uiowa/uiowa/pull/7819 and https://github.com/uiowa/uiowa/pull/7847 we discovered that a blank/non-value can be saved for the items_per_page override on listblocks. Previously this was a loophole for displaying all items. Now it defaults to 10 items.

The offset number field has some kind of validation in place to prevent save, but items_per_page does not. Offset does not use the normal validation messages however.

# Proposed Solution

- Prevent blank items_per_page values

# Possible additional slice

- Update hook to set a value for existing blocks

**Comment by briand44** [comment]
Grooming conversation... If we do an update hook what would we set it to? 10 based on the fallback? 50? Could potentially try to audit  first? Let's hold on the update hook until we learn more or someone reaches out with a related issue. We should test for Cory's test case that he is going to add a comment about below.

**Comment by cory-skeers** [comment]
Concerned about blocks that have been created in layout builder but have not yet been saved, and if the page then gets saved after these changes have been implemented.

To test:

1. on `main`, edit a page layout and add a list block with a blank `items_per_page` value
2. "Update" the block, but do not save the layout
3. pull the branch which implements these changes
4. Save the page layout _without_ editing/updating the block created in `1`
5. See what happens?

My concern is a block which does not yet exist as an entity has a blank value and gets created as part of a page save without the user having seen the block edit form between this change and the page layout save, and possibly hitting/skipping validation without a form submit and leading to an error. My inclination is that it'll be a path to creating more blocks with blanks, but not a wsod or other error.

**Comment by pyrello** [comment]
> The offset number field has some kind of validation in place to prevent save

I'm not finding this. @joewhitsitt do you know where it is?

**Comment by joewhitsitt** [comment]
I don't. I just know that something is preventing save when that field is blank.

**Comment by pyrello** [comment]
As best I can tell, the "validation" on offset is a constraint that won't allow the offset to be set to a non-integer, which halts the process of building the view, which halts the process of rendering the list block, and returns an error in the console but nothing visible to the user. Still working on trying to understand if/why this happens before the block form gets saved.

**Comment by joewhitsitt** [comment]
was this you? https://iowaweb.slack.com/archives/CSQA18BK4/p1719851382286129

we may want to handle both better then.

**Comment by pyrello** [comment]
> was this you? https://iowaweb.slack.com/archives/CSQA18BK4/p1719851382286129

Looks like the right error...

**Comment by pyrello** [comment]
> See what happens?

@cory-skeers I just ran through your test instructions and I'm not seeing what happens. Could you provide more information about what I should expect to see?

**Comment by cory-skeers** [comment]
> > See what happens?
> 
> @cory-skeers I just ran through your test instructions and I'm not seeing what happens. Could you provide more information about what I should expect to see?

It'll depend on how this gets addressed, but with the fix in place, it should not error and not end up with a block saved with a blank/non-value.

If it's something like a form validation that expects a user form submit, it might be possible to have a block that was created prior to the update but that was never saved (existing only in the lb temp key store) end up saving without a value. Edge case that came up during grooming that we wanted to document, but that isn't currently an issue and might only be a problem depending on how things are implemented.

**Comment by pyrello** [comment]
> Update hook to set a value for existing blocks

If we were going to do an update hook, I think the thing that makes the most sense to convert any blank value to 50, as that will be closest to the behavior that they should be currently experiencing. I'm going to poke at this a bit.
