### ISSUE TITLE
GPA Calculator

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7852]
# Story

As a site owner of registrar.uiowa.edu, I would like to have a GPA calculator so transfer students and other users that do not have a hawkid, still have access to a University branded GPA Calculator.

# Additional Info

They are happy with existing GPA calculator - https://registrar.uiowa.edu/gpa-calculator

Allows for figuring out gpa for credits/grades entered as well as overall gpa if cumulative gpa and number of credits are entered.

Current site has a configuration page that contains letter grade to GPA mappings and additional config. They didn't think this is necessary as they didn't think this has been updated since it was launched.

Last time I checked there was a D10 compatible release of the module we used for D7 https://www.drupal.org/project/gpa_calculator.

Block component would be great so they can add supporting text themselves.

Open to this being a little different if necessary (if add row functionality is complex, we could possibly just have a specific number of rows available).

UNI example https://registrar.uni.edu/students/gpa-calculator.

**Comment by briand44** [comment]
Grooming conversation... Discuss if there is need from others for this functionality. Sean thinks we should build this for Registrar and not the platform. Joe mentioned we could create a D10 compatible branch and possibly take over maintainership of the module https://www.drupal.org/project/gpa_calculator/issues/3237572. Already a site split so it would be just enabling this once it is ready.

**Comment by pyrello** [comment]
I started the process of becoming a maintainer of the existing module: https://www.drupal.org/project/projectownership/issues/3237572#comment-15670915

**Comment by pyrello** [comment]
I'm now a maintainer and I've opened an issue to add a D10 branch: https://www.drupal.org/project/gpa_calculator/issues/3459970
