### ISSUE TITLE
Second reminder about August 1st deadline to transition

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7859]
In https://github.com/uiowa/uiowa/issues/7744 we identified the population and sent out a reminder that the deadline to transition v1 standard to v3 is August 1st. We should send another reminder prior to August 1st.

- Get population from spreadsheet
  - list of v2/v3 site owners (requesters) that have not launched but have a v1 site still. 
- Draft/schedule/send communication
  - Can likely be very similar to last

**Comment by briand44** [comment]
The doc from the last issue had a draft for the second email as a starting point: https://iowa.sharepoint.com/:w:/r/sites/CSI-Drupal2/Shared%20Documents/v1standard-transition-reminder.docx?d=wb4f9224d1bbb4592a226514261b8bf36&csf=1&web=1&e=RXZCiv

**Comment by briand44** [comment]
Grooming conversation... In regards to the population list we may need to start with the previous population list and check against the its-web emails, spreadsheet, etc. We think we did a good job updating the spreadsheet when we got responses after the last communication.

Let's move forward with the assumption we keep the communication similar to last and don't add any new info about extensions or repercussions.

**Comment by briand44** [comment]
Let's send sometime the week of July 8th. Adding blocked label until then.

**Comment by bspeare** [comment]
Added a new and updated population at https://apps.its.uiowa.edu/dispatch/populations/1334310334.  This has 74 entries on it while the previous list had 98 entries.

**Comment by bspeare** [comment]
Can we use the same email from https://github.com/uiowa/uiowa/issues/7859#issuecomment-2197519582 for this or do we need to add anything about this being their second (and final) reminder?  Seems like everything in the first email is still relevant here.

**Comment by briand44** [comment]
I think there was already a draft of the "final reminder" email in that document

**Comment by bspeare** [comment]
Thanks @briand44.  I've updated the final draft communication at the bottom of https://github.com/uiowa/uiowa/issues/7859#issuecomment-2197519582.  I also created a new communication with the updated population at https://apps.its.uiowa.edu/dispatch/communications/1335002162 within the "Campaign: Finish transition from SiteNow v1 Standard" at https://apps.its.uiowa.edu/dispatch/campaigns/1330092596.

**Comment by briand44** [comment]
just glancing at the population, I think drivingassessment.uiowa.edu had an updated contact (should be Kristine Roggentein). Not sure if there are others in a similar situation. There was an email in its-web about this one.

**Comment by bspeare** [comment]
Thanks, I updated that one and the contact for tlcp.law.uiowa.edu which came in through Cherwell.

**Comment by bspeare** [comment]
I have scheduled this to go out today at 1:15.  Please review the email in its-web and let me know if you have any further feedback.

**Comment by joewhitsitt** [comment]
Email looks fine to me. 🚀

**Comment by bspeare** [comment]
The email has been sent.
