### ISSUE TITLE
IWP updates

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7863]
Initial feedback from IWP on the media gallery work. There will likely be more feedback once this is all deployed and they start creating content.

- Replace the icon used for Genre to be "fa-book".
- display image on resource node if video type selected but no video added to the media field.
- They would like to be able to link to the gallery with some filters already applied but they don't know what urls to use since the view is using ajax
  - Update filter identifiers so that the query parameters passed in via the url will be cleaner
  - Document examples of how to pass query parameters to the gallery display through the url to share with IWP
- Update /residency/participants teaser image to use "Large - Square" format at `/admin/structure/types/manage/writer_bio/display/teaser`

**Comment by briand44** [comment]
Grooming conversation... We may want to update the filter identifiers so that linking to pre-filtered results uses cleaner query parameters.

**Comment by bspeare** [comment]
Single search for type, country, and genre:`https://iwp.prod.drupal.uiowa.edu/media-gallery?search=&type%5Bvideo%5D=video&country%5B266%5D=266&genre%5B1821%5D=1821`

Multiple search for type, country, and genre: `https://iwp.prod.drupal.uiowa.edu/media-gallery?search=&type%5Bvideo%5D=video&type%5Baudio%5D=audio&country%5B266%5D=266&country%5B151%5D=151&genre%5B1821%5D=1821&genre%5B1822%5D=1822`

Single search term: `https://iwp.prod.drupal.uiowa.edu/media-gallery?search=Guangzhou`

Search with search string, type, country, and genre: `https://iwp.prod.drupal.uiowa.edu/media-gallery?search=Guangzhou&type%5Bvideo%5D=video&country%5B371%5D=371&genre%5B1821%5D=1821`

**Comment by briand44** [comment]
can you add an example with a search string?
