### ISSUE TITLE
Deprovision v3 https://arts.prod.drupal.uiowa.edu/

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7864]
I assume we can deprovision this v3 site since the D7 arts.uiowa.edu site has been removed and is redirecting to https://performingarts.uiowa.edu/events.

If I remember correctly, this site was provisioned as a way for us to showcase options for transitioning to v3.

**Comment by cory-skeers** [comment]
This has been done, last bit of cleanup will merge with https://github.com/uiowa/uiowa/pull/7857.
