### ISSUE TITLE
Required fields in Carousel

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#787]
## Problem

Carousel item is not a required field for Carousel resulting in a WSOD related to the count().

I don't think it is working by design but Carousel Item does not have a required field which means that a blank slide will render within the carousel.

## Proposed Solution

- Require the carousel paragraphs field.
- Require the image field within carousel item.

**Comment by cory-skeers** [comment]
@joewhitsitt pushed up requiring a carousel item. For the image field, there's a bug with making it required (validation fails when trying to insert an image). Looks like there's a patch in 8.8: https://www.drupal.org/project/drupal/issues/3003150

Want to wait on that, or do a PR on the carousel item and leave the image field alone for now?

**Comment by joewhitsitt** [comment]
push what you have, i'd like to take care of the fatal error. thanks!
