### ISSUE TITLE
Commencement site review

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7887]
They plan on launching in July and could use some help.  Should we reach out and offer a site review consultation?

https://commencement.prod.drupal.uiowa.edu

**Comment by mkyoder** [comment]
Met with Josh on 7/12 to discuss feedback and shared recommendations and mock up pages here [https://iowa.sharepoint.com/:w:/s/OSCWebTeam/ETFJ0HO4J8hLtjLqG9kqAP8Br6s_IwbuaEhOOXGESJElEQ?email=megan-yoder%40uiowa.edu&e=UsvBGx](url)
