### ISSUE TITLE
Docs - Moderation/Revisions

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#789]
We should revisit and and extend the https://sitenow.uiowa.edu/documentation/content-moderation-and-workflow documentation to include more about revisions:

- capped at 10 revisions and are automatically queued and deleted periodically
- you can view revision differences and revert to a previous revision
- there are never more than two "active" revisions (published/live version and one going through draft/review)

**Comment by ethanstjohn** [comment]
I added some docs
