### ISSUE TITLE
implement brand suggestions and subsession sorting for academic calendar

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7898]
# Stories

As a Registrar site owner, I would like subsessions to display in the appropriate order in the academic calendar list display and in the filter.

As a member of the brand team, I would like to have our feedback reflected in the design of the academic calendar.

# Additional Info

We decided to combine these two stories because the work in one could impact the other.

Grooming comments related to subsession sorting:
https://github.com/uiowa/uiowa/issues/7897#issuecomment-2220846170
https://github.com/uiowa/uiowa/issues/7897#issuecomment-2221172093

Subsessions should display in the following order:

- 4 wk
- 6 wk I
- 6 wk II
- 8 wk
- 12 wk

```[tasklist]
### Subsession sorting
- [x] Determine whether this sorting can be done in PHP in the controller
- [x] Add logic to sort events by date, by subsession order (specified above) within each date, and finally by alphabetical order if there are multiple events that exist in the same date and subsession type (in the controller if possible)
- [x] Refactor frontend JS to accommodate keeping the sort order intact, if necessary
```

```[tasklist]
### Brand recommendations
- [x] In UIDS, change date circle to just be a gold outline instead of gold fill like screenshot in https://github.com/uiowa/uiowa/issues/7851#issuecomment-2215093324
- [x] Review UIDS PR and update hash: https://github.com/uiowa/uids/pull/936
- [x] Visually group repeating dates by only displaying the circle date for the first item? `element-invisible` on the `media--date` div will visually hide the contents but keep the space.
- [x] Change date display in card__subtitle to include day of the week
```

**Comment by joewhitsitt** [comment]
>Visually group repeating dates by only displaying the circle date for the first item?

The api callback is what constructs the card and it isn't aware of where the event is in the list whatever the filters might be. I imagine it would quite a bit of processing logic to group by day and then CSS hide. Interested to hear about how else this could be done.

**Comment by briand44** [comment]
Grooming conversation... Some concern about the grouping of dates both from a technical standpoint and from usability standpoint. Usability not as big as a concern since we will be outputting the date in the card subtitle as well.

Combine this and the subsession sort since they may impact each other. Size as a large.

**Comment by briand44** [comment]
Discussed working what we can in to the existing PR.

**Comment by pyrello** [comment]
As discussed, I'm going to fold this into #7890.
