### ISSUE TITLE
Nonprofit organizations content type

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7900]
# Story

As a site owner for LAWINRC, I would like to be able store information about nonprofit organizations so that we can produce The Iowa Register of Accountability for our visitors to be able to search and connect with these nonprofit organizations.

# Additional Info

Their existing functionality has been working well for them and they would like us to develop this feature very similar to their existing functionality.

They want us to eventually migrate the ~800 nonprofit organizations from their current site.

https://inrc.law.uiowa.edu/register-accountability

currently uses a path at `non-profit-organizations/[node:title]` - let's continue to use this path?

Accreditation fields, Register of Accountability checkbox and Activity Log are no longer needed.

# Fields
**General Information**
- Organization Name - title
- EIN - text field
- Contact Name - text field - required
- Contact Title - text field - required
- Address - address field - country, address 1, address 2, city, state, zip
- Telephone Number - required
- NTEE Numbers - text field
- Email - required
- Website - link - option title and url
- Image/Logo - media
- Category - term reference, required, checkboxes, unlimited
- Denomination - ?? seeing it on https://inrc.law.uiowa.edu/admin/structure/types/manage/nonprofit-org/fields but not seeing it on https://inrc.law.uiowa.edu/node/add/nonprofit-org
- Notes - text area - filtered html
**Financial Information**
- Assets - integer - prefix with `$`
- Income - integer - prefix with `$`
- Revenue - integer - prefix with `$`

**Register of Accountability Information**
- Documents - media - multiple (currently allows 10)
- Part of Register of Accountability - no longer needed
- Expiration Date - date - popup - year/month/day granularity
**Register by Board Resolution**
- Board Resolution Date - date - popup - year/month/day granularity
**Register by Completed Training**
- Last Training Date - date - popup - year/month/day granularity
- Training Attendees - text area - filtered html
- Training Location - text field
**Register by Accreditation**
- the accreditation fields are no longer needed

```[tasklist]
### Remaining Tasks
- [x] Look into Denomination
- [x] Configure address field like grants
```

**Comment by bspeare** [comment]
Looks like three nodes are using the denomination field:

- [Des Moines Area Religious Council](https://inrc.law.uiowa.edu/non-profit-organizations/des-moines-area-religious-council)
- [First United Methodist Church of Iowa City Foundation](https://inrc.law.uiowa.edu/non-profit-organizations/first-united-methodist-church-iowa-city-foundation)
- [Wartburg Theological Seminary](https://inrc.law.uiowa.edu/non-profit-organizations/wartburg-theological-seminary)

**Comment by bspeare** [comment]
The denomination field appears only if the "religion" category is checked.  <img width="558" alt="Screenshot 2024-07-16 at 3 10 09 PM" src="https://github.com/user-attachments/assets/151b6292-122f-423d-9c3b-6b7c461a1dca">
