### ISSUE TITLE
CeDiD label font size increase

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7909]
https://registrar.prod.drupal.uiowa.edu/credential-validation

>heard back from the team and the field displays all look good, but they did have one request is that if the "Please enter CeDiD:" statement could be a little larger font? Not sure if that's part of the vended package but said I would pass along.

Sounded like it is our normal label font size but webform label font size is a little larger.
```[tasklist]
### Tasks
- [ ] Update CeDiD label font size to match webform label size
```

**Comment by bspeare** [comment]
Added a follow-up issue to address this for `uids_base` https://github.com/uiowa/uiowa/issues/7913.
