### ISSUE TITLE
theme nonprofits

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7915]
Current filter page - https://inrc.law.uiowa.edu/register-accountability
Current node - https://inrc.law.uiowa.edu/non-profit-organizations/aging-resources-central-iowa

- theme node teaser and full node
- theming on filter page?
- do we want a mockup?

**Comment by bspeare** [comment]
Here's a look at the nonprofit page:

![Screenshot 2024-07-17 at 15-49-12 Des Moines Film Society The Larned A  Waterman Iowa Nonprofit Resource Center - The University of Iowa](https://github.com/user-attachments/assets/af18584c-fc69-412d-a9ad-adc4c45efba3)

**Comment by bspeare** [comment]
I switched the telephone field to be a text field after we discussed doing the same for grants today in planning: https://github.com/uiowa/uiowa/issues/7906#issuecomment-2237245211.
