### ISSUE TITLE
https://obermann.uiowa.edu is displaying incorrectly on iOS

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#7922]
# Issue

On iPhone 15 running iOS 17.5.1 using Chrome:
![Image](https://github.com/user-attachments/assets/12caf120-b716-4361-b7e3-46c2bea05fe5)

On iPhone SE running iOS 17.5.1 using Chrome:
![Image](https://github.com/user-attachments/assets/65eb29bd-75ee-4f1b-af86-c7fde638a89c)

On Obermann, when the mega menu and a banner exist on the same page with Aggregation turn on, the menu fails to switch to mobile when the viewport is reduced.

# Steps to reproduce
- Turn on aggregation for obermann (TRUE). docroot/sites/obermann.uiowa.edu/settings/local.settings.php
- Visit a page with a banner. Mobile viewports does not cause the menu to switch.
- Delete the banner(s) or comment out the `assets/js/click-a11y-init.js` js dependency within docroot/themes/custom/uids_base/uids_base.libraries.yml and cache rebuild. See that the menu responds.

# Workaround

- Switch from mega menu to horizontal.

# Proposed solution

**Comment by bspeare** [comment]
This could be the same problem as https://github.com/uiowa/uiowa/pull/7330.   I noticed the alerts.es6 (https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/uiowa_alerts/es6/alerts.es6) is being compiled with `'use strict';` globally scoped.

**Comment by quamsta** [comment]
It does look like the superfish menu will eventually trigger on some pages at some really small widths (~240px), but not on the homepage. For example:

https://github.com/user-attachments/assets/1d072f79-63a3-45f6-a091-c7aed3ed3acc

**Comment by briand44** [comment]
Groom conversation... Not sure how many sites use mega menu. Mega menu interacts with Superfish. Only happens with mega menu on a page with a banner component. Can consistently reproduce by commenting out banner component JS or removing banner component.
