### ISSUE TITLE
Theme course deadlines

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7932]
# Story

As a Registrar site owner, I would like the course deadline information themed similarly to current but with new University Branding so that we better represent the University Brand and visitors have a cohesive look and feel across the entire site.

# Additional Information

Not a lot of direction here so we can take a stab and get feedback.

Want to make sure it meets WCAG 2.1 aa accessibility.

Make sure we are displaying:

- Course Name/Title
- Course Number - e.g. ACCT:2100:0AAA
- If it is an off-cycle course
- Begin Date
- End Date
- Deadlines for this course - e.g. last day to add/drop
- Collegiate Office Contact
- Time and Locations - link to building
- Instructors

Are we ok using the building info from data.its still?
```[tasklist]
### Tasks
- [ ] Theme course deadline info
- [ ] make sure meets WCAG 2.1 aa - https://github.com/uiowa/uiowa/pull/7928#issuecomment-2276458747
```

**Comment by briand44** [comment]
Grooming conversation... All built as a render array within the block so will need styled by adding classes to an array.

**Comment by pyrello** [comment]
These are not currently themed as cards. If we want to theme them as cards, there will be the extra step of implementation.

**Comment by bspeare** [comment]
Is this the part that we are theming?  If so, I think we should definitely theme this as a card. 

<img width="916" alt="Screenshot 2024-08-08 at 4 05 00 PM" src="https://github.com/user-attachments/assets/75a370fd-a8b4-4422-8418-506b9f75ad6a">

**Comment by cory-skeers** [comment]
> Is this the part that we are theming? If so, I think we should definitely theme this as a card.

Any and all (form fields, highlighted section, and the results below the highlighted) is open for theming adjustments, but that's the biggest section that _needs_ theming atm.

**Comment by joewhitsitt** [comment]
going to give this a go. In the comments, card was mentioned. Should the entire callback output be within the card?



![Image](https://github.com/user-attachments/assets/bb0e43b0-bfd4-495d-b1c6-d34591c8e137)

**Comment by bspeare** [comment]
@joewhitsitt seeing that screenshot, maybe we just put it in a table like D7?

**Comment by joewhitsitt** [comment]
Capturing feedback from EoD

- Team seemed okay with deadlines only in a table.
- Move the contact bit out since it isn't related and not currently set that way.
- Perhaps the course id as a badge under the human readable course name/subtitle.

**Comment by joewhitsitt** [comment]
SiteImprove is noting that we don't have a form submit button on this and that adding one would change quite a bit about how it currently operates. Not sure what do here. We could have a fallback button but it would just re-submit what already happens once the a section is selected. It would also need validation to ensure all select boxes have a selection.

Update: went ahead and added a submit button that is enabled when the section is filled.
