### ISSUE TITLE
Failed Deployments

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7937]
As far as I can tell, there was an issue with the update hook that we rolled out as a fix for v2 sites. I'm not sure it failed on all sites, but one of the queries results in a condition that doesn't allow the update hook to finish for some sites. I saw it on at least 3.

Every time we do a deployment now, it tries to run that update hook for any sites it previously failed on again.

I'm not sure if it might have succeeded on some sites and not others.
```[tasklist]
### Tasks
- [x] Sync one of the sites that failed locally, run the update hook, and use xdebug to see what's going wrong
- [x] Update the existing update hook to fix the issue
```

**Comment by pyrello** [comment]
> Sync one of the sites that failed locally, run the update hook, and use xdebug to see what's going wrong

It may be necessary to do this via `drush sql-sync` instead of `blt ds` because I believe that `blt ds` will run the update hook as part of that and it won't give us the opportunity to turn on xdebug (without having it on the whole time).

> Update the existing update hook to fix the issue

The assumption here is that the update hook won't run for any sites that have already successfully run it and it *will* be re-run for sites that failed on it previously.

**Comment by briand44** [comment]
medium based on uncertainty on what is wrong.

**Comment by joewhitsitt** [comment]
Found an example where it failed. Going to pull down and poke.

```
> drupal:update
 [Acquia\Blt\Robo\Tasks\DrushTask] Running /var/www/html/uiowa.prod/vendor/bin/drush @self updb --uri=accreditation.uiowa.edu --no-interaction in /var/www/html/uiowa.prod/docroot
 -------------------- ----------- --------------- ---------------------------- 
  Module               Update ID   Type            Description                 
 -------------------- ----------- --------------- ---------------------------- 
  sitenow_paragraphs   9001        hook_update_n   9001 - Update articles and  
                                                   people column width to      
                                                   `Full` after removing       
                                                   `-none-`.                   
 -------------------- ----------- --------------- ---------------------------- 

>  [notice] Update started: sitenow_paragraphs_update_9001
>  [error]  Query condition 'pi.id NOT IN ()' cannot be empty. 
>  [error]  Update failed: sitenow_paragraphs_update_9001 
 [error]  Update aborted by: sitenow_paragraphs_update_9001 
 [error]  Finished performing updates. 
 [Acquia\Blt\Robo\Tasks\DrushTask]  Exit code 1  Time 5.371s
 [error]  Failed to execute database updates!
For troubleshooting guidance and support, see https://docs.acquia.com/blt/support/ 
The command failed. This often indicates a problem with your configuration. Review the command output above for more detailed errors, and consider re-running with verbose output for more information.
 [error]  Failed deploying updates to accreditation.uiowa.edu.
```

**Comment by joewhitsitt** [comment]
I got severe monday brain, but it appears that sites like accreditation don't have any article or people blocks so the additional queries have a condition that requires _something_
