### ISSUE TITLE
Banner JS causes aggregation issue with superfish menu

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#7942]
# Problem
Noticed on Obermann, when the mega menu and a banner exist on the same page with Aggregation turn on, the menu fails to switch to mobile when the viewport is reduced.

# Steps to reproduce
- Turn on aggregation for obermann (TRUE). docroot/sites/obermann.uiowa.edu/settings/local.settings.php
- Visit a page with a banner. Mobile viewports does not cause the menu to switch.
- Delete the banner(s) or comment out the `assets/js/click-a11y-init.js` js dependency within docroot/themes/custom/uids_base/uids_base.libraries.yml and cache rebuild. See that the menu responds.

# Proposed solution
?

**Comment by joewhitsitt** [comment]
Sent a email to Jenna at Obermann to suggest using the Horizontal menu option as a workaround for now.

**Comment by quamsta** [comment]
Duplicate of https://github.com/uiowa/uiowa/issues/7922 ?

**Comment by joewhitsitt** [comment]
Yes, thanks @quamsta. Will close this and move details over.
