### ISSUE TITLE
investigate auth issues in dev/stage

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7959]
https://iowaweb.slack.com/archives/C0164FNN1PV/p1722537768242329

8/6 Update:

> We were able to find a message from Rick Porter in our email archives that states: "I've switched our metadata generation application to use the OneLogin PHP-SAML utility classes for signing and validation."
> 
> https://github.com/onelogin/php-saml#settings
> 
> You should be resigning the metadata after every modification you make.

8/2 Update: ticket [2242918] started with helpdesk/IAM about lawinrc and emergency DEV authentication. dentistry, iwp in addition to ITS also worked.

>John from the IAM Team came back with this:

>We started receiving this error in the logs on July 23 at 15:10.

>Metadata Resolver FileBackedHTTPMetadataResolver UiowaDrupal8StageMD: Error retrieving metadata from https://data-test.its.uiowa.edu/shibboleth/drupal: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

>Validate that you are signing the metadata file correctly. Currently it is not being updated on our servers. Eventually, if I remember correctly, the validity of the backup file will expire (2 weeks from when the issue started) and none of the ACS endpoints will work. I'm not seeing the same error in prod, only test. Perhaps try reverting the changes to the metadata file to a known good state before we started getting the cert validation errors.

>It doesn't look like the metadata has a validuntil flag set, so it should keep working in its current form without expiring, but still won't get updated until the signature issue is resolved.

Is this a fancy way of saying the SSL for data-test.its.uiowa.edu needs updating? Who is our contact for this?

Added "On behalf of" as Brian.

# Other info:
$config['samlauth.authentication']['idp_certs'] = {not included here}
$config['samlauth.authentication']['sp_private_key'] = {not included here}
$config['samlauth.authentication']['sp_x509_certificate'] = {not included here}
$config['samlauth.authentication']['sp_entity_id'] = 'https://saml.stage.drupal.uiowa.edu';
$config['samlauth.authentication']['idp_single_log_out_service'] = 'https://idp-test.uiowa.edu/idp/profile/SAML2/Redirect/SLO';
$config['samlauth.authentication']['idp_single_sign_on_service'] = 'https://idp-test.uiowa.edu/idp/profile/SAML2/Redirect/SSO';
$config['samlauth.authentication']['idp_entity_id'] = 'iowafed-test:idp:uiowa.edu';

Are all located in our secrets.settings.php file that we copy from app.env to app.env when setting up new applications. I don't think I have changed any of these values. I believe Rick was the one to originally set these up.

# Resources

https://data-test.its.uiowa.edu/shibboleth/drupal
https://git.uiowa.edu/its-web/data.its.uiowa.edu/-/blob/main/app/Http/Controllers/ShibbolethController.php?ref_type=heads
https://git.uiowa.edu/its-web/data.its.uiowa.edu#environment-variables

Authentication knowledge transfer from Rick - https://uicapture.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=ebe93040-ec79-45b1-88b0-ae90010ebee9

**Comment by briand44** [comment]
Grooming conversation... Not much familiarity on the team with authentication and what the problem is here. Decided to scope this to an investigation to understand the problem and possible solutions. Might be good to watch the video from Rick and take a look at the links here to familiarize ourselves more as a first step. If fix is small we can include it here. We just delivered CSI site in stage environment but they can't log in to use it.

**Comment by cory-skeers** [comment]
When this is resolved, may be helpful to reach out to IWP and let them know as they have the media gallery resource migration in DEV for review.

**Comment by briand44** [comment]
Also should let Jason Lin know as we synced the csi to stage for them to play around with.

LAWINRC has a migration in dev as well and cannot log in.

**Comment by joewhitsitt** [comment]
Saw this (8/6) update to the ticket this morning. Not sure if this was discussed at all within the team:

```
We were able to find a message from Rick Porter in our email archives that states: "I've switched our metadata generation application to use the OneLogin PHP-SAML utility classes for signing and validation."

https://github.com/onelogin/php-saml#settings

You should be resigning the metadata after every modification you make.
```

**Comment by joewhitsitt** [comment]
Just checked the linked video and I think that one only really pertains to the d7 auth. there is a data.its one as well but i don't recall how in-depth it goes into the auth piece.

**Comment by joewhitsitt** [comment]
Ultimately if we continue to struggle, perhaps we can request an audience with the IAM to walk through our setup and see if they spot any obvious pain points or ask if they have an integration guide for developers to follow when setting up. But with that said, given what we know about the metadata file not signing correctly which then doesn't update on their server we may want to check some of the following:

- Cert expiration (ssh in and check certificate expiration date)
- Confirm that composer install for crow isn't doing something with dependencies that vulture isn't - https://git.uiowa.edu/its-web/data.its.uiowa.edu/-/blob/main/Envoy.blade.php?ref_type=heads
- Pull locally with [.env variables](https://git.uiowa.edu/its-web/data.its.uiowa.edu/-/tree/main?ref_type=heads#environment-variables) and check the signing functionality: https://git.uiowa.edu/its-web/data.its.uiowa.edu/-/blob/main/app/Http/Controllers/ShibbolethController.php?ref_type=heads#L206-212 then compare with the .env vars of vulture to see if there is a difference beyond it having a different cert.
- Rick mentioned in the videos about contacting the data.its sysadmins about inspecting logs or if there have been updates to the server that have not been announced.

>Perhaps try reverting the changes to the metadata file to a known good state before we started getting the cert validation errors.

My understanding is that we can't do this based on how it is dynamically generated when the route is hit (5 min cache on the assertions). Each time, it fetches the list of domains from AC, so we would have to re-trace our steps and remove the potentially problematic domains to get back to "a known good state."

If we needed to update the metadata file cert or anything, I don't understand how IAM syncs or gets that.

My hope that whatever this is, if was to also start happening in PROD would only affect new domains added and not break authentication for existing.

**Comment by joewhitsitt** [comment]
Hearing about @e-marie-w's find about the metadata file being too big for the memory allocation upstream, we might want to consider testing that and/or getting back "to a known good state" by removing domains we no longer need in DEV/STAGE.

However, the if it _is_ the memory allocation upstream, I would assume they have more allocated to PROD as that file is much larger.

**Comment by joewhitsitt** [comment]
We ssh'd into data-test.its and found that the metadata cert file expires `notAfter=Jun 15 18:49:27 2026 GMT` so we are good there but will probably be needing to do work here in 2026.

**Comment by e-marie-w** [comment]
Not sure it's related, but this error started on July 23 and a new SSL cert for data-test.its.uiowa.edu (Crow) was issued on July 22.

**Comment by joewhitsitt** [comment]
We just pulled locally and stepped through the controller after scp the data-test metadata.crt, metadata.key and the .env files.

There appeared to be no issue in generating the file locally. Whatever the `Utils::validateSign` does passes without issue and the response header says valid. Throwing in some junk values causes an error so it must like what it currently has.

The cert/key that are called in the metadata file haven't been changed since 2018.

**Comment by joewhitsitt** [comment]
So far we have removed emergency.dev and dentistry.dev in order to test memory reduction/file size as well as a step towards a last good known state. We had difficulty tracking down what domains have been added/removed to dev/stage envs that could have caused a difference in the XML output which is mashed together with the cert and key to sign the file.

**Comment by joewhitsitt** [comment]
While inspecting the tail end of various log files we have access to on Crow, we notice this item. Not sure if it is related or not. Really grabbing at straws now.

```
[dataits@crow crow.its.uiowa.edu]$ pwd
/local/www/logs/vhosts/crow.its.uiowa.edu
[dataits@crow crow.its.uiowa.edu]$ tail www.err
[Wed Aug 14 09:48:24.870139 2024] [ssl:error] [pid 80721] [client 44.220.185.44:48594] AH02042: rejecting client initiated renegotiation
```

**Comment by joewhitsitt** [comment]
An email was sent to the IAM team directly from its-web. Waiting for a response.

**Comment by joewhitsitt** [comment]
so far this has been the best layman's terms explanation of this signing functionality i have seen, but I am still perplexed as to how it can suddenly go wrong or how to fix.

https://blog.samlsecurity.com/post/matadata-exchange-trust/

**Comment by joewhitsitt** [comment]
Response from IAM:

>The issue has been resolved.
>Your astute observation that the certificate for data-test.its.uiowa.edu renewed at the same time that the issue manifested led me to notice that the server hosting the certificate was no longer including the certificate chain with it so TLS verification was failing. I have disabled TLS verification as signing the metadata is sufficient for validating the authenticity of the metadata. If you change the behavior to TLS for data.its.uiowa.edu in a similar manner during the next certificate renewal this same issue will occur for any metadata the IdP fetches from that URI.

Sounds like we are good, but it might be worth following up with the Crow sysadmins to determine if an adjustment should be made related to the cert.

I can respond to the IAM team thanking them for their attention to this.

I looks like Ben reached out to Jason about the CSI site. @briand44 will you notify INRC/IWP?

**Comment by briand44** [comment]
Closing but we want to make sure we communicate with all affected sites so they are aware they can now log in. Also want to understand if we need a follow up issue or not.

**Comment by joewhitsitt** [comment]
Talked to Brian briefly about this after planning.

Sent emails to both IAM and EI-SAS from its-web with follow-up questions.
