### ISSUE TITLE
Report of expired NPO's

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7964]
# Story

As a LAWINRC website owner, we would like to be able to view/export a report or nonprofit organizations that are expired so that we can communicate with them appropriate information needed.

# Additional Information

There is an expiration date field on the nonprofit organization content type. They would like a report that displays all of the organizations where the expiration date is in the past with the ability to export to a csv file.

The report should have at minimum the following fields:

- Organization Name
- Contact Name
- Email
- Expiration Date
- Link to node would likely be helpful

**Comment by briand44** [comment]
Grooming conversation... My understanding is webmasters should have access to this and not available to public. There is a D10 compatible release for views data export https://www.drupal.org/project/views_data_export/releases/8.x-1.4, we could try that out. We should provide a link on the backend to view this report so they don't need to try and remember the link.

**Comment by joewhitsitt** [comment]
We might want to ask if it should only return published results or all in the db. That is just a simple views config change though depending on the answer.

Update: Brian saw this comment and immediately fired off an email. Diane fired an email back saying there aren't too many unpublished and to just include them in the list.
