### ISSUE TITLE
Accounting and Financial Reporting Epic

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7965]
> For the [event page](https://foafr.prod.drupal.uiowa.edu/events) itself, we do have some additional questions.

- > Can the header of the page be updated to something besides “Upcoming Events”?
- > Can information be added below the header and before the search menu? We would be interested in including additional year-end documentation on the page similar to how we had done this in the past (example: https://foafr.stage.drupal.uiowa.edu/calendar/fiscal-year-end-close/year-end-fy24-close)
- > Is there a way to automatically only display current events or have the “starts on or after” field automatically populated and filtered with the date the page is being accessed?   
- > Is there any way to adjust how the individual events are displayed? For example something similar to the “[On Iowa](https://oniowa.uiowa.edu/events)” page that helps distinguish the dates.
- > Would there be a way to download the events as a calendar file? I don’t think this is a big issue if we cannot but I just wanted to confirm if that still was available or not.
- > Additionally, in the meeting, it sounded like the web team would prefer us to move away from sending the CSV file. We were wondering if the web team would be able to upload the most recent CSV file initially to the new website as unpublished items and we would adjust those items going forward so the file does not need to be sent every year and the initial events would already be created.
```[tasklist]
### Tasks
- [x] Local Event list block with exposed filters - category, date range, search - https://github.com/uiowa/uiowa/issues/7967
- [x] Want file urls without month and year - https://github.com/uiowa/uiowa/issues/7966
```

**Comment by cory-skeers** [comment]
> ...wondering if the web team would be able to upload the most recent CSV file initially to the new website as unpublished items...

I believe the only CSVs we've used have been for redirect uploads, but we do have those as an example of how to use those. Using a CSV as a source for a migration is also pretty straightforward and a possibility, but may end up being surprisingly complicated if we build it off `sitenow_migrate`, as there may be some assumptions baked in there that we're pulling from a database. If we do an update hook similar to redirects, I think it'd essentially be

- read in CSV
- grab some rows in batches
- `Node::create([...fields...])->save()`
- Done

Full migrations also have added bonuses like tracking where sources came from for rollbacks, followup migrations, etc in the lookup tables which we (likely) don't need, so it might be nice to avoid some of that extra overhead in this case.

Might be a different thought depending on the size of the CSV, but there's also the option of breaking it up over several update hooks and even possibly deployments if it's large enough.

**Comment by briand44** [comment]
Grooming conversation... Want to avoid risk of having to solve platform level problems with this. It wouldn't be too difficult to handle the first two items for the service as part of the events page config. Discussed a very small probe to see if exposing filters on the local event list block will just work like we want or if that is going to get complex.

**Comment by briand44** [comment]
Heard back from AFR. They are going to just manually put together a table of year end dates. Because of this, we no longer need to make additional adjustments to the local event feature. The main thing left is that they want their uploaded documents to be available at the same path they currently are rather than having dates in the file path.
