### ISSUE TITLE
Local Event list block with exposed filters

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7967]
# Story

As a webteam, we would like to give folks the ability to expose filters on the local events list block so that they have more flexibility to customize content on the page while still giving users the ability to search and filter by categories and date range.

# Proposed solution

**Comment by briand44** [comment]
@bspeare should this be closed by https://github.com/uiowa/uiowa/issues/8041?

**Comment by bspeare** [comment]
@briand44 yes!
