### ISSUE TITLE
Required image in Carousel image

### ISSUE THREAD

**Issue by cory-skeers** [uiowa/uiowa#797]
### Problem
Image field is not required, so a blank slide will render within a carousel.

### Solution
- Require the Carousel Item image field

### Delay
Patch in core 8.8 (https://www.drupal.org/project/drupal/issues/3003150) which fixes validation error on required image fields in paragraphs.

**Comment by joewhitsitt** [comment]
Thanks for the follow-up issue. Though it gracefully renders a blank slide, I am going to call this a bug.

**Comment by joewhitsitt** [comment]
maybe this could be resolved as part of #811
