### ISSUE TITLE
run iwp media gallery migration in prod

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7973]
In #7940  we ran the migration in dev. Once approved, we need to run the migration in prod. 

```[tasklist]
### Tasks
- [x] Run migration in prod
- [x] communicate
```

**Comment by briand44** [comment]
blocked until we have approval. Should hear by Thursday afternoon.

**Comment by briand44** [comment]
Grooming conversation... We shouldn't have to migrate locally since this is on uiowa01 and is Cloud Classic.

**Comment by cory-skeers** [comment]
https://iwp.prod.drupal.uiowa.edu/media-gallery

**Comment by cory-skeers** [comment]
This is done and has been communicated.
