### ISSUE TITLE
Look into webform spam issues

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#798]
## Problem

Honeypot, if setup correctly, is not protecting our webforms effectively by the look of our own email inbox as it relates to our sitenow.uiowa.edu contact form.

We need make sure honeypot is configured correctly and if so, consider other preventative options.

**Comment by joewhitsitt** [comment]
This seems to be helping folks: https://www.drupal.org/project/honeypot/issues/2811189

**Comment by dnkemper** [comment]
According to users, the patch made the honeypot field visible BUT didn't prevent spam. Researching other options

**Comment by dnkemper** [comment]
Waiting for next Webform release

**Comment by joewhitsitt** [comment]
Next version of Honeypot: https://www.drupal.org/project/honeypot/issues/3081238

**Comment by joewhitsitt** [comment]
In looking at #924, I noticed we haven't configured and enabled Honeypot time limit. Do we also want to try that?

**Comment by joewhitsitt** [comment]
Also, https://www.drupal.org/project/recaptcha v2 checkbox was given the semi-thumbs up by Todd. We could ask Bill how it is working on Engineering

**Comment by joewhitsitt** [comment]
i think we updated honeypot but the release didn’t include that patch. opinions about whether the patch was effective or not aside. so we could try to apply that patch or move forward with removing honeypot and adding recaptcha v2 checkbox and establishing an its-web recaptcha account to use by default.

**Comment by joewhitsitt** [comment]
Marking this as a bug, because honeypot is not doing what it is meant to do.

**Comment by joewhitsitt** [comment]
From: https://www.drupal.org/project/honeypot/issues/3009566, it sounds like the defaults are ineffective in this machine learning age. geerlingguy, maintainer has resorted to reCAPTCHA for a few forms. Some are seeing success with the timeout set higher than 0.

**Comment by joewhitsitt** [comment]
Evaluation (sitenow.uiowa.edu) of the timeout cannot happen until a successful deployment of 2.4.6 on uiowa occurs.

**Comment by joewhitsitt** [comment]
Closing for now. The spam has been reduced utilizing the timeout option

**Comment by joewhitsitt** [comment]
_if_ we need to investigate another solution. https://www.hcaptcha.com/ is a new service that prioritizes privacy more than reCAPTCHA. I don't think there is a contrib project yet for Drupal.
