### ISSUE TITLE
academic calendar filter feedback

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7984]
https://registrar.prod.drupal.uiowa.edu/calendars-and-deadlines/academic-calendar.

- ~~Josh said we can show sub-sessions by default and remove that toggle altogether.~~
- Josh said we can remove the end date filter. I think Ben hid this in the accessibility work. We should probably remove this from the code if it's going to stay this way.

**Comment by GaryRidgway** [comment]
The subsession toggle removal is happening [here](https://github.com/uiowa/uiowa/issues/7984)

**Comment by briand44** [comment]
Since the subsession work got done in a different PR and because of the amount of testing required with this, we decided to move the removing of date filter to the existing work as well. Going to close this.
