### ISSUE TITLE
ITS feedback re: editor role

### ISSUE THREAD

**Issue by cory-skeers** [uiowa/uiowa#7987]
From James to its-web:

Hey,

Adrienne noticed something during our first training session for the ITS website today and it will need to be addressed soon.

I was using the editor role to train people (not stacked with any other roles). As an editor, I also had the ability to edit the alerts pages using Layout Builder. This is not okay for an editor to do.

We would like to restrict the editor role from using Layout Builder; we think in doing that we should also remove the ability to create/edit 'pages' or 'basic pages' from the editor role. 

If we want people to be able to modify (basic) pages then we can give them the publisher role stacked.

Open to discussing this and open to your thoughts and ideas on how to best address this issue. Sorry that we didn't catch it earlier.
```[tasklist]
### Tasks
- [ ] Remove the ability to create and edit basic pages for the editor role
- [ ] Test to make sure there are not any undesired consequences from the permissions changes
```

**Comment by joewhitsitt** [comment]
The concern you brought up in standup about how we were trying to limit custom permissions on this website was more how it relates to roles. We didn't want to create a bunch of custom roles like they previously had. If they are okay with the impact of editors losing the ability to work with pages,  I think I am okay with that as long as it is documented on their end as that. The complication is that when an ITS editor sees the documentation on SiteNow saying they should have access that it gets to be confusing.

**Comment by briand44** [comment]
Grooming conversation.... Sounded like we are ok with making these changes but some concern about the need arising for layout builder in the future. We can deal with that if/when it arises. Publisher role by itself doesn't have the permission to use layout builder so stacking editor/publisher roles wouldn't be a viable workaround. Cory said that removing the ability to edit pages for the editor role would align with what they are asking and still allow stacking editor/publisher when someone needs to edit pages.

Some conversation about possibly using layout builder lock to lock all sections on individual pages.

Brian to check with James to verify if the main issue is editors changing the layout of the `/alerts` page or if they really don't want them to have the ability to edit "pages".

First option would probably be a small but some testing time, second option probably a JDI.

**Comment by briand44** [comment]
I got feedback from ITS and they want us to move forward with removing the ability to create and edit basic pages for the editor role.
