### ISSUE TITLE
Make `umd` command more foolproof

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7996]
# Story

As a web team, we would like to make our `umd` command more foolproof so that we don't have any more incidents where the wrong database is deleted.

# Additional Info

https://github.com/uiowa/uiowa/issues/7958#issuecomment-2287150540

>We could potentially solve the problem that we encountered before by adjusting the deletion command to use the information that is already known about the application the site lives on to ensure that the database is deleted from that application specifically.

>Add a warning for when a domain would produce a duplicate database name. A developer would still need to decide what to do in that situation. Lightweight, but more potential for developer error.

https://github.com/uiowa/uiowa/issues/7958#issuecomment-2287192372

>I'd lean towards a slice to make the umd more foolproof to ensure the site that was selected in the command is what is deleted. If that means the umd command needs to go beyond the human name and confirm the application and/or the database machine name by fetching more info about the site before deleting I think that would be good. We have worked hard to make deprovisions a JDI type task and I'd like to be confident we can continue treat them as such once all of the administrative checking is out of the way.

> An optional additional slice would be to make sure the provision command would stop if the $databases->create() failed.
> 
> Though we have some validation on the request form our provisioning process still requires some human checking for issues. Like you said their could be a use-case for a particular near duplicate domain name and that we should just continue to take more than a glance at what we are moving forward with.
```[tasklist]
### Tasks
- [x] Use application/machine name to target deletion of database
- [ ] Warning prior to creating duplicate database name?
```

**Comment by briand44** [comment]
Grooming conversation.... Application is present at the time we are getting the db name because we use the application when targeting the files for deletion. It would be ideal to provide a warning when creating a duplicate database name but if this gives us problems it is not required for completion of this issue.

**Comment by joewhitsitt** [comment]
I am going to start to work on this and use https://github.com/uiowa/uiowa/issues/7834 for testing just incase parts of the `simulate` option don't work.

**Comment by joewhitsitt** [comment]
forgot to probe the provision warning bit

**Comment by joewhitsitt** [comment]
I've been digging into the provision command. The $database->create() seems to only trigger a request to Acquia and the response message that gets returned whether or not the databases actually get created in the end is "The database is being created"

https://github.com/uiowa/uiowa/blob/d078a24fefc29fd0d90c7645942dbf212ec36153/blt/src/Blt/Plugin/Commands/MultisiteCommands.php#L533

So a try/catch could be wrapped around this, but the exception would only happen if it fails to communicate with Acquia and start the database creation process. This failure would be discovered when attempting to install the website later in the process as the database won't be found.

```diff
diff --git a/blt/src/Blt/Plugin/Commands/MultisiteCommands.php b/blt/src/Blt/Plugin/Commands/MultisiteCommands.php
index eefaf026f..bb2a25d0c 100644
--- a/blt/src/Blt/Plugin/Commands/MultisiteCommands.php
+++ b/blt/src/Blt/Plugin/Commands/MultisiteCommands.php
@@ -536,8 +536,25 @@ public function create($host, array $options = [
     $app_id = $applications[$app];
 
     if (!$options['no-db']) {
-      $databases->create($app_id, $db);
-      $this->say("Created <comment>{$db}</comment> cloud database on {$app}.");
+      try {
+        // Attempt to create the database.
+        $response = $databases->create($app_id, $db);
+
+        // Check if the operation message indicates success.
+        if (stripos($response->message, 'created') !== FALSE) {
+          $this->say("Created {$db} cloud database on {$app}.");
+        }
+        else {
+          // If the message doesn't indicate success, handle as an error.
+          $this->logger->error("Failed to create the cloud database {$db} on {$app}. Message: " . $response->message);
+          throw new \Exception("Database creation failed for {$db}. Message: " . $response->message);
+        }
+      }
+      catch (\Exception $e) {
+        // Log the exception and stop the script.
+        $this->logger->error('An error occurred: ' . $e->getMessage());
+        throw $e;
+      }
     }
     else {
       $this->logger->warning('Skipping database creation.');
```

By selecting an application, the risk of database naming conflicts are reduced compared to the how the umd command were and is now protected against.

The only other thing I could see us doing is fetching all of the database names, mimic what the database name will be and checking for similar databases. Ultimately, if the the app with a conflict is picked, the database->create will fail and show in the cloud UI. if the provision progresses to prod, the multisite install won't show it as one of the sites to install as it will already been populated with database content. I'd be willing to discuss this more, but I am starting to think there isn't much value-add here.

**Comment by joewhitsitt** [comment]
At EoD the team expressed interest in trying to identify potential conflicts during the provision command so that we are less likely to have a mess to clean up after things are already to PROD.

Sean had suggested looking for potential conflicts in the site directory vs fetching from all applications looping through the existing databases for a match.

I plan to take a crack at producing something that covers this.

**Comment by joewhitsitt** [comment]
Re-opening. PR merge auto closed. Going to try to push a bit more work related to this.
