### ISSUE TITLE
Documentation for References

### ISSUE THREAD

**Issue by dnkemper** [uiowa/uiowa#800]
Update Reference documentation to include new functionality

**Comment by dnkemper** [comment]
@joewhitsitt could you please review this? [Here](https://sitenow.uiowa.edu/documentation/article-content-type)

I wasn't sure if I should separate the Organization and Source Links or not? Also, you're very good with words haha

**Comment by joewhitsitt** [comment]
I think this is fine. Thanks!

**Comment by joewhitsitt** [comment]
Wait, this is a separate issue related to the references, not the source/org fields on article. The source/org docs look fine.

**Comment by dnkemper** [comment]
Blocked until https://github.com/uiowa/uiowa/pull/778 is merged in

**Comment by joewhitsitt** [comment]
#778 has been closed/not merged
