### ISSUE TITLE
Audit list of v1 standard sites who missed the deadline

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#8006]
# Story

As a web team, we would like additional information about the SiteNow v1 standard sites that did not meet the deadline so we can determine the appropriate communication to these sites owners and unit leaders.

# Additional Info

As part of https://github.com/uiowa/uiowa/issues/7886, we generated a list of v1 sites that missed the Aug. 1st deadline. This is a follow up to gather further information about those sites in https://github.com/uiowa/uiowa/issues/7886#issuecomment-2296783668.

We want to identify unit leaders for these sites.

~We also want to understand if they are actively working to transition or if they haven't made progress with their transition.~ Done

We don't need to worry about the sites that never requested or those that we already provided an extension for.

https://github.com/uiowa/uiowa/issues/7886#issuecomment-2302961039

**Comment by briand44** [comment]
Grooming conversation... Could have a new column for "Unit contact" that is a comma separated list of contacts.

**Comment by GaryRidgway** [comment]
### Checklist of sites.

- [x] accessibility101.course.uiowa.edu
- [x] anthony.lab.uiowa.edu
- [x] atasoy.lab.uiowa.edu
- [x] blsa.org.uiowa.edu
- [x] brogden.lab.uiowa.edu
- [x] campbell.lab.uiowa.edu
- [x] celp.org.uiowa.edu
- [x] chen.lab.uiowa.edu
- [x] clp.law.uiowa.edu
- [x] cssa.org.uiowa.edu
- [x] cui.lab.uiowa.edu
- [x] econsent.lab.uiowa.edu
- [x] english-society.org.uiowa.edu
- [x] fab.law.uiowa.edu
- [x] fisher.lab.uiowa.edu
- [x] geerling.lab.uiowa.edu
- [x] hultman.lab.uiowa.edu
- [x] ieee.org.uiowa.edu
- [x] lira.lab.uiowa.edu
- [x] masongroup.lab.uiowa.edu
- [x] matthew-arndt.sites.uiowa.edu
- [x] michaelson.lab.uiowa.edu
- [x] mil.lab.uiowa.edu
- [x] nasa.org.uiowa.edu
- [x] nhlp.law.uiowa.edu
- [x] niciu.lab.uiowa.edu
- [x] orsc-colloquium.sites.uiowa.edu
- [x] parekh.lab.uiowa.edu
- [x] pcit.lab.uiowa.edu
- [x] perception.lab.uiowa.edu
- [x] quelle.lab.uiowa.edu
- [x] radley.lab.uiowa.edu
- [x] rahmouni.lab.uiowa.edu
- [x] richerson.lab.uiowa.edu
- [x] rohlman.lab.uiowa.edu
- [x] roman.lab.uiowa.edu
- [x] sebag.lab.uiowa.edu
- [x] tedabel.lab.uiowa.edu
- [x] turkish.org.uiowa.edu
- [x] uisrmsymposium.sites.uiowa.edu
- [x] uitransalliance.org.uiowa.edu
- [x] usachev.lab.uiowa.edu
- [x] victorianfboos.studio.uiowa.edu

**Comment by GaryRidgway** [comment]
So I think I've finished the audit on the [D7 site sheet](https://iowa.sharepoint.com/:x:/r/sites/CSI-Drupal2/Shared%20Documents/General/Drupal%207%20Sites.xlsx?d=wa3958afafa30492a948e0a3368521d3d&csf=1&web=1&e=CJLMqB&nav=MTVfezA2MjBDMUM5LTUzNDMtNDM5Qi04OEE2LUQwMjI1NTM3RjIxOX0). I remember @joewhitsitt  making the columns move to the remaining D7 sheet too, but that sheet is protected so I don't think I can edit. Is there anything else I could do to ensure this issue is resolved?

**Comment by joewhitsitt** [comment]
You should have the permission to "pause protection" on the sheet, but the formula to populate that sheet is very touchy. I went ahead and included that new column with the remaining sheet.

**Comment by GaryRidgway** [comment]
> You should have the permission to "pause protection" on the sheet, but the formula to populate that sheet is very touchy. I went ahead and included that new column with the remaining sheet.

Thanks Joe! Does this sufficiently complete this issue then?

**Comment by joewhitsitt** [comment]
At a glance, i see unit names for all rows that need them except for the victorianfboos site (i think CLAS). when it comes time to actually do something with this though I think we will want an email address contact for these right? like Maggie in CLAS, etc? I don't know if something different was discussed with the PO.

**Comment by GaryRidgway** [comment]
> At a glance, i see unit names for all rows that need them except for the victorianfboos site (i think CLAS). when it comes time to actually do something with this though I think we will want an email address contact for these right? like Maggie in CLAS, etc? I don't know if something different was discussed with the PO.

I will add the victorianfboos site to the unit leaders, but when @briand44 and I talked he confirmed to me that we just wanted department, college, or otherwise so far, and that we would get emails later.
