### ISSUE TITLE
Filter list of sites during deployment to sites on that application

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#8015]
# Story

As a web team, we would like to filter the list of sites during a deployment to only includes sites on the application running so that we can increase performance.

# Additional Info

From Sean:

>Our current process doesn't pre-filter the list of sites to just include sites from the application it is being run on. Instead it checks if a config file exists for each site and then only continues execution for sites where it finds one. We have 1259 v2/v3 sites as of this writing, but the largest application has only 223 sites. That means we are doing at least >1000 checks for a non-existent file. Even with parallel processing, that means that each of those sites that doesn't exist on that application gets to temporarily occupy one of the 3 processing slots. We could create a mechanism to filter the list before the site updates are initiated and it would likely save us some time vs checking sites that aren't there as part of the update process. This would also help us clean up the log output and make it easier to read the logs because there wouldn't be a lot of noise related to 1000+ sites being "skipped".

Grooming conversation:
- https://github.com/uiowa/uiowa/issues/8004#issuecomment-2310826574
- https://github.com/uiowa/uiowa/issues/8004#issuecomment-2310834335
- https://github.com/uiowa/uiowa/issues/8004#issuecomment-2310850017

**Comment by pyrello** [comment]
Going to pick this up as Alan is out the rest of the week.
