### ISSUE TITLE
Draft comms for remaining v1 standard sites to share with leadership

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#8018]
# Story

As a web team, we would like to draft a communication to site owners and unit leaders of SiteNow Standard sites that missed the deadline so that they are aware they are at risk of their site being deactivated.

# Additional Info

- [x] Draft communication for remaining v1 standard sites - include final deadline
- [x] Share comms and list of sites with OSC leadership to get their feedback
- [x] Probably need some work identifying email addresses for unit leaders

**Comment by GaryRidgway** [comment]
I think with this we decided on trying to find the population of people that were not still working on their sites or that we had communication with. Then, we would create an email for them telling them that if they didnt respond, we would shut down their site.

**Comment by briand44** [comment]
Grooming conversation... Let's try to include all remaining SiteNow v1 sites. If there is a couple we are in other communications with we could decide to exclude those or include a line in the comms related to those. We will likely want to identify a final date before we would deactivate sites but we may not be able to determine that until we understand how quickly we can get approval from OSC leadership. I think there are around 35 sites that would be included here.

**Comment by bspeare** [comment]
I've started a draft here: https://iowa.sharepoint.com/:w:/r/sites/CSI-Drupal2/Shared%20Documents/%5BDraft%5D%20Comms%20for%20remaining%20v1%20standard%20sites.docx?d=w429f950e1c124268a993d755842151d4&csf=1&web=1&e=UxNp50.

**Comment by pyrello** [comment]
Reviewed the comms and made a few edits. Looks good. Stern but fair.

**Comment by bspeare** [comment]
Here is the link to the remaining D7 sites with unit contacts: https://iowa.sharepoint.com/:x:/r/sites/CSI-Drupal2/Shared%20Documents/D7%20v1%20Sites%20for%20leadership.xlsx?d=wbf3c7653cd0e4802a35eda1f2a32a8bf&csf=1&web=1&e=NUTCHA&nav=MTVfezAwMDAwMDAwLTAwMDEtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMH0

**Comment by mjoneill** [comment]
OK. I have reviewed the site list and planned comms.  

There are a couple of sites in the list that probably deserve some care in handling.  

If we are ready for me to make the list, planned email, and plan of action visible to leadership, I will do so. 

For clarity, my understanding is that this list represents:
- Historic v1 standard sites that either never responded to any comms, or requested a v3 site and have made no progress.

There is another cohort of sites not included in this list that represent:
- Historic v1 custom sites that can move to v3 standard (self migration)

And there is the custom dev cohort we are working on.
- Historic v1 custom sites that require additional custom development by the central web team to be able to migrate

Let me know if I misapprehend anything above.

**Comment by briand44** [comment]
> For clarity, my understanding is that this list represents:
> 
> Historic v1 standard sites that either never responded to any comms, or requested a v3 site and have made no progress.

All of the sites in this list have requested a v3 site. The sites that originally didn't request a v3 site have either been removed or a request got submitted eventually. Some of these sites have made no progress, others made some progress but are not actively working on the transition and there are three sites that we identified looked launch ready (https://github.com/uiowa/uiowa/issues/8063). One of those three 
https://studiovictorianfboos.prod.drupal.uiowa.edu/ just responded that we can move forward with the launch so that site should likely be removed from this list prior to sharing with leadership.


> There is another cohort of sites not included in this list that represent:
> Historic v1 custom sites that can move to v3 standard (self migration)

Correct.

> And there is the custom dev cohort we are working on.
> Historic v1 custom sites that require additional custom development by the central web team to be able to migrate

Correct

**Comment by briand44** [comment]
>One of those three
https://studiovictorianfboos.prod.drupal.uiowa.edu/ just responded that we can move forward with the launch so that site should likely be removed from this list prior to sharing with leadership.

This site has launched and I have removed this row from the spreadsheet in https://github.com/uiowa/uiowa/issues/8018#issuecomment-2436316938

**Comment by mjoneill** [comment]
Shared the spreadsheet with Jeneane and Ali.  Copied the email text into tab 2 so they could easily see it.  

I'll check in on Thursday if no response.

**Comment by mjoneill** [comment]
One request so far: In the email comms, link to https://sitenow.uiowa.edu/sitenow-v1-standard-platform-shutdown messaging that we link to in the alert displayed at the top of all D7 sites (when signed in).  

^^^ good practice to reference past/current comms.

**Comment by briand44** [comment]
Closing this as we got some feedback from leadership (https://github.com/uiowa/uiowa/issues/8018#issuecomment-2444894129) and I have added that feedback as a task in the next slice https://github.com/uiowa/uiowa/issues/8177
