### ISSUE TITLE
IWP Residency participants breadcrumb

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#8019]
https://iwp.prod.drupal.uiowa.edu/residency/participants - displays a link to the current page and the current page title not linked.

I would expect it to be `Home / Residency / Residency Participants` where Residency Participants is not a link.

**Comment by joewhitsitt** [comment]
Just looked at this, and I think it is a gap created by menu_breadcrumb and views pages.

**Comment by joewhitsitt** [comment]
Unless I am missing something we might need to do something similar to [sitenow_articles](https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/sitenow_articles/sitenow_articles.module#L131):

```php
/**
 * Implements hook_preprocess_HOOK().
 */
function iwp_core_preprocess_breadcrumb(&$variables) {
  // Get the current route name.
  $route_match = \Drupal::routeMatch();
  $current_route_name = $route_match->getRouteName();

  // Check if this is the views page.
  if ($current_route_name === 'view.writer_bio.page_writer_bio') {
    foreach ($variables['links'] as $key => $link) {
      $url = $link->getURL();
      // Test for external paths.
      if ($url->isRouted()) {
        $route_name = $url->getRouteName();
        // Remove linked breadcrumb if it matches the view route.
        if ($route_name === 'view.writer_bio.page_writer_bio') {
          unset($variables['links'][$key]);
        }
      }
    }
  }
}
```

**Comment by joewhitsitt** [comment]
@e-marie-w Just curious if you investigated others views pages we have done? The ones I spot checked were pretty top-level menu items so I think it was just good enough. I was curious if we have handled this differently before.

**Comment by e-marie-w** [comment]
> @e-marie-w Just curious if you investigated others views pages we have done? The ones I spot checked were pretty top-level menu items so I think it was just good enough. I was curious if we have handled this differently before.

When I searched breadcrumb in the codebase I didn't see any other views changing it, besides the articles and now this. But we are using preprocess_breadcrumb function in a few other places, like for webforms. 

Web search results mentioned using the BreadcrumbBuilderInterface instead, but I didn't seen a reason for using one over the other, just some claims that using the interface was better. The preprocess function seemed easier and your code just needed a single word change, so I used that.

**Comment by bspeare** [comment]
@joewhitsitt any idea why this local version displays the crumbs for the view but the live site does not for https://now.uiowa.edu/experts-list?

<img width="740" alt="Screenshot 2024-09-04 at 3 18 22 PM" src="https://github.com/user-attachments/assets/d6d16cbd-a426-4363-8de6-a0a2b1a48023">
<img width="729" alt="Screenshot 2024-09-04 at 3 18 39 PM" src="https://github.com/user-attachments/assets/9f4b6f01-0d05-4755-84d3-aa0d4989a898">

**Comment by joewhitsitt** [comment]
@bspeare i didn't notice that local/prod diff which is part of why I was thinking we previously shipped it as "good enough" and didn't really care that they had a menu link but not a breadcrumb.
