### ISSUE TITLE
ITS Website Launch Tasks

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#8037]
Launch Date Tuesday, 9/17/2024

**Michael/Megan**
- Michael to add sitemap to search console
- Michael/Megan to run lots of screaming frog scans post launch
- GA4 reporting - Michael to update date ranges as appropriate
- Michael/Megan - Scan site for existing prod.drupal links (encourage partner to use the Find feature also).  Scans will also check for stage.drupal, test.drupal, and dev.drupal (IIRC) by default

```[tasklist]
### Dev Tasks
- [x] notify adrienne/James when going to start the launch
- [x] cron job to run drush command for daily digest as part of launch
- [x] make sure all current alerts are accounted for on the new site with redirects?
- [x] Keep D7 site around - add reminder to its-web calendar
- [x] notify Adrienne/James when launch is finished.
- [x] Create ITS alert for uiowa04 cloud next production upgrade
```

**Comment by joewhitsitt** [comment]
```
/var/www/html/${AH_SITE_NAME}/vendor/bin/drush -l its.uiowa.edu its-digest  --no-interaction &>> /var/log/sites/${AH_SITE_NAME}/logs/$(hostname -s)/drush-cron.log
```

This will need to be updated with the ACN upgrade, as will the other scheduled jobs on uiowa03.prod

**Comment by briand44** [comment]
Grooming conversation... We don't need to run the cron job for the Digest just setup the job to run the drush command daily at 7am. Not seeing a cron job related to this in non-production environments. We do have other cron jobs running drush commands that we could reference. comment above untested

**Comment by bspeare** [comment]
Site is launched and dev tasks complete.   Set a its-web reminder for November 4th for its.prod.drupal.uiowa.edu.

**Comment by mkyoder** [comment]
- [x] Megan - submit new sitemap
- [x] Megan - search for prod.drupal and stage.drupal, test.drupal, and dev.drupal using Find Text feature
