### ISSUE TITLE
Pagination issue causing the skipping of articles in /news

### ISSUE THREAD

**Issue by quamsta** [uiowa/uiowa#8049]
# Problem

During a content migration and audit for the Department of Pathology, I noticed that a single article that was migrated was not showing up in `/news` despite it existing in the system, being dated correctly, and showing up in taxonomy views.

# Steps to reproduce

1. Visit https://medicinepathology.prod.drupal.uiowa.edu/news
2. Go to page 9 -- note that the "**Iowa Association of Pathologists Award Winners from May 4, 2021**" is the last article on page 9.

<img width="907" alt="Screenshot 2024-09-06 at 8 19 47 AM" src="https://github.com/user-attachments/assets/07ed94c5-4fc3-4e10-b53a-bc3592b009e4">

3. Go to page 10 -- note that the same article is at the top of the page.

<img width="776" alt="Screenshot 2024-09-06 at 8 24 12 AM" src="https://github.com/user-attachments/assets/b3ca6c79-907c-4748-b7d7-6f0d1ed1e921">

4. Go to May, 2021's filtered-by-date page: https://medicinepathology.prod.drupal.uiowa.edu/news/2021/05
5. Note that there are two articles from May, 2021 from the same day, but the article "**Steven Moore receives Impact Scholar award...**" is also in May 2021 listings, but does not show up on the main `/news` page.

<img width="1039" alt="Screenshot 2024-09-06 at 8 25 09 AM" src="https://github.com/user-attachments/assets/cc0c0b57-d2bd-45cd-9290-6875ca9669d6">

This also seems to affect article list blocks, since you can see the same behavior on an article list block here:
https://medicinepathology.prod.drupal.uiowa.edu/news-events

# Proposed solution

Review any internal offsets used by the pagination system to ensure that we aren't skipping over items in a page.

As an enhancement, maybe figure out a way to adjust the URL when navigating through pages in order to retain back button functionality when navigating through the pagination. It was a bit of a challenge to write this issue when pagination was reset while using the web browser's back/forward navigation through the news section.

**Comment by briand44** [comment]
Grooming conversation... Discussed trying to recreate this in sandbox environment. Look for upstream issues if nothing obvious sticks out. Should be coming from views, we don't have custom code affecting pagination. Could see if we can reproduce through views ui. Could remove some filters to see if any of those are culprits. Fix it if we find the problem and not a huge undertaking. If it is big we can discuss fixing in a separate slice.

**Comment by quamsta** [comment]
@briand44 Thanks for looking into it. I've left our news page alone in hopes that the issue could be recreated by pulling down a copy of the Pathology site, but I may need to update our news in the near future, so let me know if you're able to recreate it in sandbox or somewhere else.

**Comment by bspeare** [comment]
I took a quick look at this.  Both items have the exact same published date and time.  If you change one to 12:00:01 AM it will show up in the list.

**Comment by briand44** [comment]
so do we need an additional sort criteria on title so it doesn't get confused on which article to display in order?

**Comment by quamsta** [comment]
@bspeare @briand44 I think we'd need an additional sort criteria. Apparently the import/migration of articles done by the CCOM devs have left most if not all of the migrated items set to midnight as their "Authored on"/published date. Not sure if it's reasonable to go in and edit dozens of articles published dates... 😬

Random examples:

<img width="369" alt="Screenshot 2024-09-18 at 9 02 37 AM" src="https://github.com/user-attachments/assets/362b610a-9313-48a9-a8b6-4ca95c192bbc">
<img width="371" alt="Screenshot 2024-09-18 at 9 02 56 AM" src="https://github.com/user-attachments/assets/aed07d6f-a3c8-41f0-97ad-1e7193527b61">

**Comment by bspeare** [comment]
Yes, it does look like adding additional sort criteria for the title fixes the issue.  I'll put together a pull request.
