### ISSUE TITLE
Full calendar resets to default view around 10-20 seconds after navigating to a different month

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#8074]
# Problem
Our full calendar resets to the default view around 10-20 seconds after navigating to a different month.

# Steps to reproduce
Try navigating to a different month on one of the sites below and notice how it will reset after around 10 seconds. 

- https://grad.uiowa.edu/academics/thesis-defenses
- https://its.uiowa.edu/alerts/calendar

# Proposed solution
- ?

**Comment by quamsta** [comment]
The calendar resetting seems to correspond to when the request for https://emergency.uiowa.edu/api/active occurs. Maybe they're connected?



https://github.com/user-attachments/assets/dd14cd24-0a29-4f25-95bb-d4aaeeef8de4

**Comment by joewhitsitt** [comment]
Nice find @quamsta

**Comment by joewhitsitt** [comment]
https://www.drupal.org/project/fullcalendar_view/issues/3323399 - Calendar view refreshes and jumps to current month on any ajax update

**Comment by joewhitsitt** [comment]
@GaryRidgway, would a small slice through this just be into adjust the scope in which the rebuild happens?

https://git.drupalcode.org/project/fullcalendar_view/-/blob/5.x/js/fullcalendar_view.js?ref_type=heads#L441-445

**Comment by GaryRidgway** [comment]
I made an [issue fork here](https://www.drupal.org/project/fullcalendar_view/issues/3323399#comment-15778682) that should provide some relief, though its not perfect.
