### ISSUE TITLE
Display Final Exam Schedule

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#8077]
# Story

As a Registrar site owner, after placing the final exam schedule block for a give session, I would like to be able to click the link that is output and view that sessions final exam schedule.

# Additional Information

In #4967, we are creating the block plugin. Now we would like to grab and display the Final Exam Schedule based on the legacy code for the session chosen while placing the block.

Use views xml backend or custom api call to pass in legacy code in render exam schedule.

**Comment by briand44** [comment]
Grooming conversation... Discussed if we go the custom API call route, we should consider making the call in `uiowa_core` vs `uiowa_maui` https://github.com/uiowa/uiowa/issues/8024#issuecomment-2332163774. Sizing this as a large in case we end up doing a little cleanup as part of this.

**Comment by GaryRidgway** [comment]
I added a container for responsive tables to the table of the block.

I found that the data that is being put into the table is still encoded. For example, html tags are being output as plain text, `nbsp`'s are still being output as plain text, etc.

Conversed with Cory, and I am going to continue on and try to decode the text.
