### ISSUE TITLE
ITS permissions/roles updates

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#8087]
> Ok, I have some answers and a new request. Yes, can we go ahead and move forward with the update on giving editors the ability to delete any support article. Thank you for looking at that so quickly.
>
> Here's a new request: I think we need a new role. We realized that all publishers have the ability to modify pages that have layout builder. And all Help Desk staff have the publisher role so that they can publish alerts. We like those 15+ people having the ability to edit and publish alerts, but we definitely do not want them to have the ability to modify the homepage or any other top-level pages. I understand we're trying to limit the amount of roles we have and not go back to having 7 or 8 roles like we did on the old site, but this one feels important enough to add. I'd like to limit the amount of folks who could edit these pages down to maybe 4 or 5 max, and I have a list of people who I would need to give access to.
> I'd be happy to have a meeting about this to discuss further. I hope this isn't a big lift.

**Comment by briand44** [comment]
Grooming conversation... Seems like the ability for editors to delete any support article is straight forward enough.

If we add the new role, we will likely want to review all the perms again. It was brought up that we could remove the permission of publishers to to modify pages but ITS would need to be ok with the 4 or 5 people being webmasters that they want to modify pages. It was discussed that we should verify what they are saying is true since the perms on this site are way different than the default and is causing quite a bit of confusion. Once we wrap our heads around the current perms, if we don't see a straight forward path to solve their issue, we can meet with them and talk through it and see where things land.

**Comment by joewhitsitt** [comment]
Going to review where we've been so far with ITS and then see what additional adjustments we can make to keep it to the roles already defined.

**Comment by joewhitsitt** [comment]
Okay, so the original recommendation was that their third-tier role would have the editor role and that basic page editor and HD full-time would have the editor/publisher role which meant full page permissions.

In https://github.com/uiowa/uiowa/pull/8031/files#diff-296ec8e3252ae14a0985ef9eec514cf837c0045eb4cd8b9ceb0319f3c4aeefca we removed the ability for editors and publishers to work with fragments and edit the footer contact block. editors lost the ability to touch pages at all along the way.

So yea, if we want to nerf the publisher role surrounding basic pages that is a path forward here. Folks that need to touch pages would need the webmaster role going forward.

They currently have ~18 editor/publishers and 3 webmasters. Michael and Megan of OSC are also webmasters on the site. Curious who the additional users needing page access are.

**Comment by joewhitsitt** [comment]
@briand44 I've captured the changes to the editor and publisher role here as well as provided a [list of permissions](https://github.com/uiowa/uiowa/issues/8087#issuecomment-2383838139) a webmaster would have over an editor/publisher user.

https://github.com/uiowa/uiowa/pull/8108

Do you want me to contact ITS with this?

**Comment by briand44** [comment]
If you would that would be great. It sounds like Adrienne is out next week so if there is any way we can get her thoughts and have a path forward that would be awesome

**Comment by joewhitsitt** [comment]
Based on the response from ITS, I almost wonder if Publisher should go back towards default (page editing ability) and we finally tackle the fragments portion of https://github.com/uiowa/uiowa/issues/5609 to limit it to webmasters in the default. Then we create a separate role for Helpdesk Full-Time for alert related work anyone currently with the editor/publisher combined roles would get moved to the new role through an update hook.

**Comment by joewhitsitt** [comment]
Looks like Admissions' publisher/webmaster roles has additional permissions to manage stat fragments. And editors/publishers/webmasters have permissions for fragments on grad that need to be checked against to make sure there is no regression there.

**Comment by joewhitsitt** [comment]
Removed a comment from the PR and placing it here as it no longer relates to the PR:

> Here is a brief summary of the additional permissions a webmaster has over a editor/publisher on the ITS website with this PR's changes:
> 
> * Aggregator (RSS Feeds)
> * Page
> * Service
> * Webforms
> * Fragments (pre-footer, after content)
> * Banner videos
> * Manage menus
> * Manage all taxonomy vocabularies
> * User management
> * Advanced SEO settings
> * Redirects
> * Administer Google Analytics/Google Tag manager (on-site, not upstream)
> * Administer SiteNow page, people, articles, dispatch, alerts, search, theme and site settings

**Comment by joewhitsitt** [comment]
Might want to check with them, but my guess is they will now want the help desk role to be able to configure the site-wide alert functionality.

**Comment by joewhitsitt** [comment]
>want the help desk role to be able to configure the site-wide alert functionality

they want it. i'll try to add it here soon and push it out to DEV.

Update: It is out in DEV and they say they are working on reviewing the changes.

**Comment by briand44** [comment]
From James...

> I went in this morning to try and test the new role on dev but it doesn't appear to be available.
> 
> There are some users on the site that have the Help Desk Full-Time role...but these users are not clickable/editable. Adrienne reports seeing the same behavior when she goes into the People tab. 
> 
> Something appears to be amiss here. Can you please help? We'd like to be able to test the roles out.

Joe reached out to me in Slack....

>The email from James. The PR needs to be adjusted to allow webmaster to manage that role. Administer users by role or something like that.

**Comment by joewhitsitt** [comment]
Had to resync the db down from PROD after the `main` branch update hooks changed and threw off the dev database. notified james and adrienne.

**Comment by joewhitsitt** [comment]
James is finishing up some testing and mapping out a comms plan. Hopes to be done and ready to deploy by Thurs/Friday

**Comment by joewhitsitt** [comment]
ITS will be ready for this to go out Monday (after the scheduled deployment) so that they can go in and make the manual changes needed to assign certain users to the editor/publisher stacked combo.

**Comment by joewhitsitt** [comment]
This was deployed today and they have been notified via email that they are able to make any post-deployment changes (e.g. changing a few users from helpdesk role back to publisher)
