### ISSUE TITLE
CKEditor media link button is not clear that it is a button

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#8099]
# Problem
CKEditor media link button is not clear that it is a button and users often skip using it and directly upload media files at `admin/content/media` instead. 

# Steps to reproduce
<img width="442" alt="Screenshot 2024-09-24 at 1 40 38 PM" src="https://github.com/user-attachments/assets/1cf64adb-9deb-4206-a954-fc497b3fa606">

# Proposed solution
Style the button to look like something you can click. 

<img width="415" alt="Screenshot 2024-09-24 at 1 40 54 PM" src="https://github.com/user-attachments/assets/2870e938-63b4-4cac-932f-1e4edd2dbb4b">

**Comment by quamsta** [comment]
Alternate idea? Old school underline!

<img width="232" alt="Screenshot 2024-09-25 at 10 57 58 AM" src="https://github.com/user-attachments/assets/2c7659a2-b26b-4b0b-b99e-3978cad9aab5">

**Comment by bspeare** [comment]
@quamsta love that simple idea.

**Comment by bspeare** [comment]
Updated to look more like a link:


<img width="433" alt="Screenshot 2024-09-26 at 1 54 47 PM" src="https://github.com/user-attachments/assets/be93114d-ce6e-4dde-9fe6-8c8f552e4585">

**Hover:**


<img width="248" alt="Screenshot 2024-09-26 at 1 54 53 PM" src="https://github.com/user-attachments/assets/4118c1d3-0aa3-4d3d-92b6-12879015c263">
