### ISSUE TITLE
https://legalclinic.org.uiowa.edu/ URL change request

### ISSUE THREAD

**Issue by cory-skeers** [uiowa/uiowa#8111]
From Laura K, requesting to change to legalclinic.law.uiowa.edu

Check on apps, if ssl needs to be updated to the *.law anywhere else.
SEO hit to consider
Vulture redirect needed?

**Comment by joewhitsitt** [comment]
Reported 2000 views in GA over the past 12 months. Responded with this information. Seeking approval to move forward, preferably without the redirect as a big time saver.

**Comment by bspeare** [comment]
Site has been migrated to v3 and moved to https://lawlegalclinic.prod.drupal.uiowa.edu/.   Currently waiting to hear if they want a redirect for https://legalclinic.org.uiowa.edu/.

**Comment by e-marie-w** [comment]
Update: they do want the redirect.

**Comment by e-marie-w** [comment]
Can I submit the Vulture redirect request now, or do we need to launch the site first?

**Comment by joewhitsitt** [comment]
The request can go in now. Heck, it might even bump this other request: https://github.com/uiowa/uiowa/issues/8164. For existing domains, TTL will need to be lowered and then it is the re-point of DNS that makes the redirect start working.

**Comment by e-marie-w** [comment]
Redirect request submitted!

**Comment by e-marie-w** [comment]
Just received message that the redirect has been set up.

**Comment by joewhitsitt** [comment]
So my understanding is that the next step is to sync the site over now and repoint DNS for the old website to redirect from Vulture? If so I can continue this as part of support.

**Comment by joewhitsitt** [comment]
It looks like this might have already been synced?

https://legalclinic.org.uiowa.edu/
https://lawlegalclinic.prod.drupal.uiowa.edu/

Asking the customers if we are clear to launch and re-point/redirect legalclinic.org.uiowa.edu to legalclinic.law.uiowa.edu

**Comment by bspeare** [comment]
Yes, I synced it back on https://github.com/uiowa/uiowa/issues/8111#issuecomment-2450080879.

**Comment by joewhitsitt** [comment]
Got permission to launch the site and enable the redirect by repointing dns.

**Comment by joewhitsitt** [comment]
This is done
