### ISSUE TITLE
SSL cert on uiowa01 for iwp.uiowa.edu

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#8113]
Just noting we should be using the new multi domain general profile and not the deprecated v2 profiles or customized for University of Iowa profiles.

**Comment by joewhitsitt** [comment]
Done.
<img width="524" alt="Screenshot 2024-10-04 at 1 17 09 PM" src="https://github.com/user-attachments/assets/fb699008-c2f5-426d-a600-92f2c8307563">
