### ISSUE TITLE
SiteNow October 2024 Newsletter

### ISSUE THREAD

**Issue by GaryRidgway** [uiowa/uiowa#8121]
## Task

Provide a "release notes" type article of finished/done features/updates and publish to website, then send out dispatch email.

Step-by-step instructions: https://docs.prod.drupal.uiowa.edu/sitenow-drupal-10/monthly-newsletter

```[tasklist]
### Tasks
- [x] Add updates, bugs, notable site launches
- [x] Get a team member to review
- [x] Publish article
- [x] Send dispatch communication
- [x] Create next month's issue
```

**Comment by joewhitsitt** [comment]
Draft: https://sitenow.uiowa.edu/node/686/edit

**Comment by joewhitsitt** [comment]
Made a small tweak to highlight the contact feature add-on as a whole and not just the URL alias update.

Published. Moving towards sending it out via dispatch.

**Comment by joewhitsitt** [comment]
scheduled for 10 AM: https://apps.its.uiowa.edu/dispatch/communications/1371080435

**Comment by joewhitsitt** [comment]
#8204 created, PL card updated with new draft article. dispatch mode moved back to test.
