### ISSUE TITLE
Department codes

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#8122]
# Story

As a Registrar site owner, we would like to be able to place a component on a page that would output department code information from MAUI so we don't have to keep that list up to date manually every time there is a change.

# Additional Info

https://registrar.uiowa.edu/department-codes-and-numbers
https://registrar.prod.drupal.uiowa.edu/department-codes-and-numbers

https://api.maui.uiowa.edu/maui/api/pub/lookups/registrar/coursesubjects

This endpoint contains the data for `active` department codes.

They want us to display the `naturalKey`, `itchCode` and `description` as "Subject", "Legacy Code" and "Description".

They want a search filter that would search `naturalKey` and `itchCode`.

This information would only need to be updated at most once a day.

# Question 

Should we also output Status? - https://github.com/uiowa/uiowa/issues/8122#issuecomment-2399914619

**Comment by briand44** [comment]
Setting this to blocked as the endpoint mentioned above only seems to contain active department codes and Reigstrar wants to chat internally about this. Said they would follow up by the end of this week.

**Comment by briand44** [comment]
> Yes, if you could please look into bringing what we currently have in MAUI (active) over to the website that would be great. We will deal with the inactives manually for now.
> 
> We are planning on submitting a JIRA to the MAUI folks to see if they can add inactives to the api but doubt that will happen in the near future. So don't know if it's possible to kinda pre-program for that to occur? Maybe have a "status" column and if inactives are added down the line they will pop up?

**Comment by briand44** [comment]
Grooming conversation... Sounds like we want to output `status` as well in the case that inactive get added to the endpoint at a later date. Not grouping by College like their current site. Just one table that is searchable.

**Comment by bspeare** [comment]
Here's what the table currently looks like:

<img width="1432" alt="Screenshot 2024-10-22 at 9 05 27 AM" src="https://github.com/user-attachments/assets/b9ba8587-204b-40cb-ad87-e0fd5b2452d3">
