### ISSUE TITLE
LAWINRC Topics and FAQs example

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#8125]
# Story

As a site owner for the LAWINRC website, we would like to see an example of how we could use existing tools to recreate our topics pages and faqs.

# Additional Info

https://inrc.law.uiowa.edu/topics

Currently they have a FAQ content type with the ability to categorize via a hierarchical taxonomy.

Seems like this could be created using existing tools (pages with collections).

Currently there are ~115 FAQ nodes.

**Comment by briand44** [comment]
Grooming conversation... Could do a csv export and import. csv update hook. for each category, create a page with a collections block and these collection items. CSV export may be helpful even if we don't do anything with it, it may make it easier for them to manually transition since there is a JS issue with the load more. First, Brian going to follow up and let them know we think they can transition with existing tools and offer to put an example together for them if they are able to manually transition all the faqs.

**Comment by briand44** [comment]
Diane responded and she is willing to try to manually transition the content if we can provide an example for her to follow.

**Comment by briand44** [comment]
Talked with Ben and we thought this would be a small and could be developer choice on how we put this together (likely some combination of basic pages and collection items).

**Comment by bspeare** [comment]
Added the topics page at https://lawinrc.prod.drupal.uiowa.edu/topics.  I moved over the pages that had JavaScript problems instead of providing an csv export.  The rest of the pages listed below can be moved over through copy and paste.   

- [Administration](https://lawinrc.prod.drupal.uiowa.edu/topics/administration) - **Moved**
    - [Governance](https://lawinrc.prod.drupal.uiowa.edu/topics/administration/governance) - **Moved**
    - [Human Resources](https://lawinrc.prod.drupal.uiowa.edu/topics/administration/human-resources) - **Just need to copy over FAQs**
    - [Management](https://lawinrc.prod.drupal.uiowa.edu/topics/administration/management) - **Just need to copy over FAQs**
- [Communication](https://lawinrc.prod.drupal.uiowa.edu/topics/communication) - **Moved**
    - [Advocacy](https://lawinrc.prod.drupal.uiowa.edu/topics/communication/advocacy) - **Just need to copy over FAQs**
    - [Community Development](https://lawinrc.prod.drupal.uiowa.edu/topics/communication/community-development) - **Just need to copy over FAQs**
    - [Public Relations](https://lawinrc.prod.drupal.uiowa.edu/topics/communication/public-relations) - **Just need to copy over FAQs**
    - [Reports](https://lawinrc.prod.drupal.uiowa.edu/topics/communication/reports) - **Just need to copy over FAQs**
        - [Funding](https://lawinrc.prod.drupal.uiowa.edu/topics/communication/reports/funding) - **Just need to copy over FAQs**
        - [Nonprofit Employment](https://lawinrc.prod.drupal.uiowa.edu/topics/communication/reports/nonprofit-employment) - **Just need to copy over FAQs**
        - [Other Reports](https://lawinrc.prod.drupal.uiowa.edu/topics/communication/reports/other-reports) - **Just need to copy over FAQs**
- [Funding](https://lawinrc.prod.drupal.uiowa.edu/topics/funding) - **Moved**
    - [Foundations](https://lawinrc.prod.drupal.uiowa.edu/topics/funding/foundations) - **Just need to copy over FAQs**
    - [Fundraising](https://lawinrc.prod.drupal.uiowa.edu/topics/funding/fundraising) - **Moved** 
- [Law & Tax](https://lawinrc.prod.drupal.uiowa.edu/topics/law-tax) - **Moved**
    - [Legal](https://lawinrc.prod.drupal.uiowa.edu/topics/law-tax/legal) - **Just need to copy over FAQs**
    - [Organization](https://lawinrc.prod.drupal.uiowa.edu/topics/law-tax/organization) - **Moved**
    - [Risk Management](https://lawinrc.prod.drupal.uiowa.edu/topics/law-tax/risk-management) - **Just need to copy over FAQs**
    - [Tax](https://lawinrc.prod.drupal.uiowa.edu/topics/law-tax/tax) - **Moved**
- [Technology](https://lawinrc.prod.drupal.uiowa.edu/topics/technology) - **Moved**

**Comment by bspeare** [comment]
I emailed Diane with some instructions yesterday and this work is complete.
