### ISSUE TITLE
SSL - Remove rvap.uiowa.edu from uiowa

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#8129]
From https://github.com/uiowa/uiowa/pull/8127

**Comment by joewhitsitt** [comment]
@cory-skeers are we also clear to have hostmaster reclaim the domain?

**Comment by cory-skeers** [comment]
> @cory-skeers are we also clear to have hostmaster reclaim the domain?

They set up a redirect to the replacement site, so there shouldn't be anything for us to deal with re: the domain.

**Comment by joewhitsitt** [comment]
Ah. I should have just visited the site. Missed the details of what was happening earlier in the thread(s). Thanks.

**Comment by benlewzz** [comment]
Thanks y'all!

**Comment by joewhitsitt** [comment]
This is done.
