### ISSUE TITLE
Course Deadlines Feature Enhancements

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#8134]
> First is that when you select a course/section with cross-references it displays the administrative home subject only. Please see fall '24 - NURS:3600:EXW. The admin home and not the one selected shows up in the data pull (MGMT:3600:EXW)

<img width="596" alt="image" src="https://github.com/user-attachments/assets/af4e4748-7649-4a96-aa98-64929ab6e774">

>Would it be possible to show the selected subj/course/section instead of the admin home? Or maybe show all cross-references? For this one it would be: RELS:3701:EXW SSW:3600:EXW MGMT:3600:EXW. Or maybe just don't show that bubble? Any thoughts?

---

>And secondly, when there isn't a section being offered in a specific session, the session field stays blank and the submit button never shows up. ASIA:3208 in fall '24 for instance.

<img width="581" alt="image" src="https://github.com/user-attachments/assets/3275d0b8-d5fd-449e-b552-41b4efd9f23b">

>Would it be possible that if there are no section available, could it say something like no subject/course/section is being offered for this session. Or just something instead of kinda stopping?

**Comment by joewhitsitt** [comment]
Oops. We do have a drupal.announce saying "No sections available for the selected 3208. Please try again." but no visual change.

**Comment by briand44** [comment]
Grooming conversation... For the first ask, not sure if the cross-references are available to us but sounds like we have alternate options if not. For second part that is part of the ajax, shouldn't be an issue.

**Comment by e-marie-w** [comment]
In EoD yesterday I noticed a new issue where course deadlines besides the start and end date were no longer appearing. I thought it was related to my code change but I'm seeing it on main and on the prod site now so I suspect it's related to a recent change. My first thought was #8116, as it made some change to our MAUI code, but on first look nothing stood out.

Debugging I can see our data pull is reporting all those deadlines are null when previously it was not, so I'm going to look at the MAUI endpoints next. If that doesn't reveal anything obvious I'm going to switch back to the scoped work for this and investigate more after.

**Comment by e-marie-w** [comment]
![Screenshot 2024-10-18 at 9 40 33 AM](https://github.com/user-attachments/assets/1f534ab0-82ae-4223-8cd7-62ebf71a02db)
Progress!

**Comment by e-marie-w** [comment]
![Screenshot 2024-10-22 at 8 51 56 AM](https://github.com/user-attachments/assets/59ff12bb-cc3f-4e62-8eb0-9f87e3dc264b)
![Screenshot 2024-10-22 at 8 52 11 AM](https://github.com/user-attachments/assets/cf3410bc-0d13-4500-91c7-afa1f672e163)
More progress!
