### ISSUE TITLE
Allow webform integration with Prospector app to be more widely distributed

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#8138]
# Story

As a web team, we would like to avoid having to touch each webform that needs to integrate with the Prospector app so that we can use our resources elsewhere.

# Additional Info

In #8103 we tested integrating a webform with the prospector app middleware. Since it sounds like there will be potentially a lot of these forms on the Education site and likely other sites as well, we would like to make this easier to distribute. 

Make it more widely available or document or make it easier for webmasters to set this up without our team having to be involved with each form.

**Comment by briand44** [comment]
Grooming conversation... Possibly try and remove the aspects of this that would require higher technical knowledge. Possibly settings page to enter uuid that needs to be passed to the endpoint. Abstracting out basic authentication - possibly store in secrets file and intercept guzzle request and pass those credentials (Could look through what hooks are available at that point: docroot/modules/contrib/webform/webform.api.php - Probably hook_webform_handler_info_alter
?). Possibly a setting on webform to say this is a webform posting to the Prospector app. If enable remote handler to use with prospector app, we could add the endpoint so webmaster not required to and if it changed it would only need updated in one place. 

Team liked the sound of possibly creating a specific remote post handler so user would choose "Prospector remote post handler" rather than a basic remote post handler and we can make assumptions based on the handler chosen.

Keep in mind Tippie and UIP Pharmacy have the existing remote post functionality (advanced webform feature).

**Comment by pyrello** [comment]
The following links were useful in seeing the work that was previously done to implement a new webform handler:
- The specific handler class: https://github.com/uiowa/uiowa/blob/316d7964ab5bf8724e02cd3f5702fba67b048dce/docroot/sites/tippie.uiowa.edu/modules/tippie_core/src/Plugin/WebformHandler/PardotRemotePostWebformHandler.php
- The commit where the above class was replaced by different logic: https://github.com/uiowa/uiowa/pull/4698/commits/ad05212688fb2d9e3b0e7f4589bd18679fa01c76

**Comment by pyrello** [comment]
I have added some basic setup to the testing instructions in #8155, which will be necessary to setup and test locally. I was in the process of getting this to work, but the code that pulls in the auth details from config isn't working yet (they are stored in a local settings file for testing but will be stored a global security settings file on each application when this gets deployed). I have not tested functionality beyond that point. Hopefully the comments help illuminate what is happening.

**Comment by joewhitsitt** [comment]
I haven't dug too far, but I think an example worth looking at is the dispatch thank you program.

https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/sitenow_dispatch/src/Form/ThankYouSettingsForm.php#L107

when called the settings file keys show up in this settingsOverride array
<img width="170" alt="Screenshot 2024-10-28 at 5 03 44 PM" src="https://github.com/user-attachments/assets/4917324d-5608-4bbd-b88a-a1bb9bfb6dcd">

```
$config['sitenow_dispatch.settings']['thanks']['api_key']
$config['sitenow_dispatch.settings']['thanks']['hr_token']
```
