### ISSUE TITLE
Course Deadlines not showing all info

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#8153]
> Got a report that the Course Deadline tool isn't displaying all the date fields for off-cycle courses. See example below. 
> 
> I could've sworn that this was working before but didn't know if that was in a local demo or something I saw on the prod side. Here's what the current tool is outputting for that HPAS:1002:0300 for fall '24:

![Image](https://github.com/user-attachments/assets/1d5343da-8083-498a-a0ce-06cc51f546b7)

![Image](https://github.com/user-attachments/assets/3b18c79c-a33d-4e56-8ddd-0e1c684bee8a)

**Comment by briand44** [comment]
Grooming conversation... This was working at one point. I don't think this issue is specific to off-cycle courses as I was seeing the same issue with another course. Probably just need to jump in and debug. Marie mentioned a PR that restructured some stuff with our MAUI calls that could be the culprit. She will link to that PR here. We should verify that the data is still in MAUI endpoint.

**Comment by e-marie-w** [comment]
PR I mentioned: https://github.com/uiowa/uiowa/pull/8116. I haven't had a chance to really dive in, nothing stands out but it was merged in and released around the time I noticed the issue happening. 

Example Maui endpoint: https://api.maui.uiowa.edu/maui/api/pub/registrar/sections/1037439. 
There's no data there related to the "Last day to..." deadlines. If you put Fall 2024, ACCT, 9020, any section into https://registrar.prod.drupal.uiowa.edu/calendars-and-deadlines/course-deadlines it will reflect this. But put the same values into https://registrar.uiowa.edu/course-deadlines and you will get results. 

If I use https://api.maui.uiowa.edu/maui/pub/webservices/documentation.page and find the above maui call and put in the matching section, it will return the lastDay deadlines but with null being the values. So, I am now wondering if the Drupal 7 code is using a different endpoint or what.

**Comment by e-marie-w** [comment]
Found a possible fix, there is a different MAUI endpoint: https://api.maui.uiowa.edu/maui/api/pub/registrar/sections/20243/ACCT/2100/0A01 that actually shows the additional deadline and was easy enough to switch to in our code. 

I still don't understand why the original endpoint (https://api.maui.uiowa.edu/maui/api/pub/registrar/sections/1021852) isn't working, though. The d7 code looks to be using the original endpoint and again, that works fine, even though visiting the endpoint itself doesn't. I think visiting the direct link is XML, though, and using the MAUI documentation page I can see the JSON and it has those missing deadlines. They are set to null, though, so I still don't understand how the D7 site is working.

**Comment by joewhitsitt** [comment]
>They are set to null, though, so I still don't understand how the D7 site is working.

I was curious about this too and spent a little time looking into it. Reproduced date values returned in d7. null in d10. I am still scratching my head..

**Comment by joewhitsitt** [comment]
I think this is it:
```diff
diff --git a/docroot/modules/custom/uiowa_maui/src/MauiApi.php b/docroot/modules/custom/uiowa_maui/src/MauiApi.php
index fc68923ce..22c0b7387 100644
--- a/docroot/modules/custom/uiowa_maui/src/MauiApi.php
+++ b/docroot/modules/custom/uiowa_maui/src/MauiApi.php
@@ -258,7 +258,9 @@ public function getClassroomsData($room_category = 'UNIVERSITY_CLASSROOM') {
    */
   public function getSection($section, $exclude) {
     return $this->get("pub/registrar/sections/{$section}", [
-      'exclude' => json_encode($exclude),
+      'query' => [
+        'exclude' => json_encode($exclude),
+      ],
     ]);
   }
```

It was passing options, but it was being applied to the endpoint as something other than `?exclude=...` which is what was expected and how it was passed to `_uiowa_maui_request` in D7 (params)
