### ISSUE TITLE
Law Viewbook Updates

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#8162]
# Story

As a Law Viewbook owner, I would like some updates made to keep the data current.

# Additional Info

https://viewbook.law.uiowa.edu/

> Attached are updates for the Iowa Law digital viewbook. I’ve highlighted all the changes for reference. Our photo change requests are at the bottom of the document, along with the corresponding file names from Photoshelter.

https://iowa.sharepoint.com/:w:/r/sites/CSI-Drupal2/_layouts/15/Doc.aspx?sourcedoc=%7BA697F6CB-E76F-43BB-8510-7F10B88BCBD9%7D&file=Digital%20Viewbook%20Updates%202024.docx&action=default&mobileredirect=true

# Proposed Solution

- [x] Make updates based on shared documents
- [x] Reach out to our partners for review prior to deployment - Hannah Huston, Laura Kivlighan
- [x] Deploy

**Comment by e-marie-w** [comment]
Unassigning myself until I can get the viewbook to work locally for me. I'd forgotten I've had issues with them in the past.

**Comment by cory-skeers** [comment]
Updates have been approved/deployed.
