### ISSUE TITLE
Review logic between academic dates feature and academic calendar feature

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#8186]
Josh wants to make sure the logic with the Academic Dates block (Used on grad.uiowa.edu, commencement.uiowa.edu, housing.uiowa.edu) is aligned with the logic in the Academic Calendar.

Academic Dates Block - https://commencement.uiowa.edu

![Image](https://github.com/user-attachments/assets/efe31a00-e4d0-4198-af21-2ddaba7a49c8)

Academic Calendar - https://registrar.prod.drupal.uiowa.edu/calendars-and-deadlines/academic-calendar

Examples:

- `reviewed = true`
- `printDate = true`
- any other logic

Can we document that logic here to share with Josh?

---

Also, Josh is curious if it would be possible to further limit the dates being pulled in to dates that have certain contexts? For example "Registrar Contexts" in the screenshot below? He's not wanting us to move forward with this at this point in time, just wanting to understand if it would be possible.

<img width="971" alt="Screenshot 2024-10-29 at 1 21 10 PM" src="https://github.com/user-attachments/assets/690eb22f-4e0f-4431-9247-277a63db1b2f">

**Comment by briand44** [comment]
Grooming conversation... While investigation we should capture some sort of summary of the logic here for the academic calendar and academic dates block for historical purposes as well as sharing with Josh.

**Comment by joewhitsitt** [comment]
If it isn't too much scope creep, maybe we can fix https://github.com/uiowa/uiowa/issues/5608 while we are looking at academic dates

**Comment by e-marie-w** [comment]
Quick summary of the basic functionality differences between the two (I did not have a chance to dive into the code logic):

Academic Dates Block (used on commencement.uiowa.edu and others):
- can pick from sessions ranging from +/-4 of current session
- can only display one session at a time
- cannot filter by subsession
- can pick categories
- no option to group by month

Academic Calendar Block (custom to registrar.uiowa.edu):
- can pick from sessions ranging from +/- 10 of current session
- can display all sessions at once or choose a single session
- can filter by subsession
- can pick categories
- can group by month

**Comment by joewhitsitt** [comment]
Generally, it looks like both fetch from / pub/ registrar/ session-dates via [searchSessionDates](https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/uiowa_maui/src/MauiApi.php#L129) but with the academic dates block only the session id and date category arguments are supplied whereas the academic calendar has print_date set TRUE.

Post-fetch, the calendar is looping through the dates and skipping non-reviewed dates.

```
// Skip the reviewed check for five-year calendar.
        if (!$isFiveYearCalendar && $date->reviewed !== TRUE) {
          continue;
        }
```

**Comment by joewhitsitt** [comment]
It also looks like we could adapt the code to pull from a context specific endpoint. `GET /pub/registrar/session-dates/{sessionId}/{contextLookup}/{dateLookup}` - https://api.maui.uiowa.edu/maui/pub/webservices/documentation.page

<img width="1411" alt="Screenshot 2024-11-11 at 12 16 01 PM" src="https://github.com/user-attachments/assets/5cb5f382-1135-4cc7-820d-ef7553d61cd4">

**Comment by briand44** [comment]
>Generally, it looks like both fetch from / pub/ registrar/ session-dates via [searchSessionDates](https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/uiowa_maui/src/MauiApi.php#L129) but with the academic dates block only the session id and date category arguments are supplied whereas the academic calendar has print_date set TRUE.

What about is_reviewed? Does the academic dates block check to see if the dates have been reviewed? Do they both handle five year dates the same?

**Comment by joewhitsitt** [comment]
>Post-fetch, the calendar is looping through the dates and skipping non-reviewed dates.

Sorry, i updated the comment with the is_reviewed stuff

So for the calendar it is skipping dates where reviewed is FALSE. For the five year calendar it is including dates that are reviewed = FALSE. This was adjusted slightly in the five-year work: https://github.com/uiowa/uiowa/pull/8012/files#diff-2a4f5378c573b7d600040665593e8fb44c96a0899cf8141283d047349c4d9186R227

**Comment by joewhitsitt** [comment]
>Does the academic dates block check to see if the dates have been reviewed?

Doesn't appear so.

>Do they both handle five year dates the same?

I don't see any five-year specific code in the academic dates code.

**Comment by joewhitsitt** [comment]
After the meeting the code differences between the block and the calendar align with Josh's suspicions and asked that the academic dates block be updated to also filter by print date and reviewed.

As for the contexts, Josh was hoping to add the context value (human readable version) to the date renders but it doesn't seem like that info is passed into what we are currently pulling. I wonder if we can request that info is added to the existing endpoint so we can avoid additional calls (if one exists) to fetch that information.

**Comment by briand44** [comment]
For visibility, there is already another issue related to updating the academic dates block. https://github.com/uiowa/uiowa/issues/7962

**Comment by joewhitsitt** [comment]
And on second glance it appears the context is added to the dates. I got lost/confused in the dateLookup portion of the entry

sessionDateDTO > contextLookup > naturalKey

**Comment by joewhitsitt** [comment]
Given that https://github.com/uiowa/uiowa/issues/8232 and https://github.com/uiowa/uiowa/issues/7962 exist, is this issue done? Asking for a friend ;)

**Comment by briand44** [comment]
Yup!
