### ISSUE TITLE
toggle to turn off GA

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#8190]
# Story

As a web team, we would like the ability to quickly toggle off Google Analytics for a site in case it is required because of HIPPA or other reasons.

# Additional Info

Initial slice related to the Epic https://github.com/uiowa/uiowa/issues/8180

Discussed adding a toggle to turn off GA similar to the toggle for GTM. Should output a message on the GA config page saying that this is turned off and to contact our team. Talked about moving forward with this for now and continue learning and working towards giving site owners more control to take this responsibility on in future slices.
```[tasklist]
### Tasks
- [x] Look for a contrib patch could allow them to just remove their property id to remove tracking
- [x] Add toggle to turn on/off GA on uiowa_core settings page
```

**Comment by GaryRidgway** [comment]
Grooming discussion... 
- Brian was going to try and get some clarity from Michael on whether we will need to do this on per site or per page?  
- Per site to start, don't scope this per page
- Webmaster permission? Admin only currently, new config page if we want to make it available to webmasters.
    - Perhaps just start with current config page, offer to webmasters later?
    - At minimum, keep space for handlebars
- A contrib patch could allow them to just remove their property id to remove tracking.
    - Anyone have the patch to link?

**Comment by bspeare** [comment]
The patch in https://github.com/uiowa/uiowa/pull/8221 works great for deleting GA IDs on ` /admin/config/services/google-analytics`.  Is that an acceptable solution for this work or are other pieces needed?

**Comment by joewhitsitt** [comment]
I think having the "shut it down" option without potentially losing the customer's GA ID would still be nice but it isn't exactly the same scenario as a rogue js script in a GTM that we don't have access to.
