### ISSUE TITLE
SiteNow November 2024 Newsletter

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#8204]
## Task

Provide a "release notes" type article of finished/done features/updates and publish to website, then send out dispatch email.

Step-by-step instructions: https://docs.prod.drupal.uiowa.edu/sitenow-drupal-10/monthly-newsletter

```[tasklist]
### Tasks
- [x] Add updates, bugs, notable site launches
- [x] Get a team member to review
- [x] Publish article
- [x] Send dispatch communication
- [x] Create next month's issue
```

**Comment by bspeare** [comment]
This is ready for review https://sitenow.uiowa.edu/news/2024/11/updates-november-2024.

**Comment by joewhitsitt** [comment]
Looks good to me. Thanks for working on it @bspeare

**Comment by bspeare** [comment]
This is complete.
