### ISSUE TITLE
Make icon library available to SiteNow

### ISSUE THREAD

**Issue by GaryRidgway** [uiowa/uiowa#8211]
[Grooming conversation was started here.](https://github.com/uiowa/uiowa/issues/6978#issuecomment-2460642513)
- How are we making these available to SiteNow?
    - Static job?
    - Copy paste?
    - Remote hosting?

**Proposed solution**:
- Talk with the team about a way of moving forward with importing/copying/remote hosting the icons
- Proceed to do so
- THIS DOES NOT INCLUDE IMPLEMENTING THEM IN ANYTHING

**Comment by joewhitsitt** [comment]
Before you assigned yourself @cory-skeers I was starting to stomach the idea of picking this up and started to weigh the pros and cons between different methods. Let me know if you want to brainstorm

**Comment by cory-skeers** [comment]
I initially did some poking at using https://www.drupal.org/project/media_entity_remote_image, but it's being in alpha and from their project page

> Need to leverage image styles?
In many cases it may be appropriate to instead leverage [Remote Stream Wrapper](https://www.drupal.org/project/remote_stream_wrapper), which copies remote files to your site's local file system. This allows you to manipulate them as you would any other local Drupal image. Configuration is slightly complex but is outlined in [this issue comment](https://www.drupal.org/project/remote_stream_wrapper/issues/2875444#comment-12881516).

is proving to be accurate. I tried to finagle things to get it to work, but didn't have great luck.

https://www.drupal.org/project/remote_stream_wrapper looks promising as a path forward for incorporating a remote hosted image, but is also a bit more involved in getting setup and doesn't "just work," and don't want to go too much further without more team input.

My leaning toward remote hosting as an option comes from a desire to be able to update (or remove the option of) icons based on Brand's needs. We've recently had some icons that needed to be removed for various reasons, as well as accessibility improvements for others, and if we're going to incorporate icons in SiteNow, it seems like a good time to set up to keep them in line with brand, and remote hosting feels like the most direct way for that.

Maintaining the full list in the codebase can handle that too, likely with a scheduled job to refresh and get said updates. I'm just partial to keeping code in code and not duplicating files between the dedicated repository and the SiteNow platform. But there might be some benefits there that I haven't considered.

**Comment by joewhitsitt** [comment]
What about a hybrid approach here? Custom media entity that is pretty much read-only for site editors. Icons are pulled/pasted in uids_base theme directory along with https://github.com/uiowa/brand-icons/blob/main/icons.json. Updates would go out as part of code releases. As needed, an update hook creates/updates media entities on each site with a path/metadata to the icon in uids_base. Then the card could be updated to allow a different media entity that can leverage the media library UI for filtering/selecting all icons. Yes, each site would have database rows for these, but not the file storage impact. It reduces issues external source reliability/performance.

Work would have to be done to have a better unique identifier (vs text machine names) as well as SVG icon alternative text.

**Comment by cory-skeers** [comment]
> What about a hybrid approach here? Custom media entity that is pretty much read-only for site editors. Icons are pulled/pasted in uids_base theme directory along with https://github.com/uiowa/brand-icons/blob/main/icons.json. Updates would go out as part of code releases. As needed, an update hook creates/updates media entities on each site with a path/metadata to the icon in uids_base. Then the card could be updated to allow a different media entity that can leverage the media library UI for filtering/selecting all icons. Yes, each site would have database rows for these, but not the file storage impact. It reduces issues external source reliability/performance.

I think this is sounding more appealing to me than it was initially. Good point on the bonus of being less reliant on an external source. I'd liked the idea of keeping it separate, but the extra complexity with getting things to play nicely with the rest of the system I don't think are justifying the "this would be nice."

**Comment by bspeare** [comment]
@joewhitsitt @cory-skeers what sort of work were you thinking we needed to do for better unique identifiers with https://github.com/uiowa/brand-icons/blob/main/icons.json?

**Comment by cory-skeers** [comment]
> @joewhitsitt @cory-skeers what sort of work were you thinking we needed to do for better unique identifiers with https://github.com/uiowa/brand-icons/blob/main/icons.json?

My thought was to use https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Component%21Uuid%21UuidInterface.php/interface/UuidInterface/10 to generate a standard UUID like other entities. I hadn't thought through the impact of doing that and wanting/needing to keep it consistent across sites, when it would be instantiated, etc... I don't think there's a way to feed it a string or anything to get a consistent hash for the UUID to use.

**Comment by joewhitsitt** [comment]
I am curious how https://github.com/uiowa/brand-icons/blob/main/icons.json is currently put together, but was just thinking of adding an `id` property (e.g. 1, 2, 3) to the current items and then any new ones will increment off that. If alpha sort is still needed that could be incorporated in as a last step.

of course the icon id will be different than the mid on each site so it will get stored and compared against separately

**Comment by bspeare** [comment]
@joewhitsitt the `icons.json` is manually put together so we can definitely add an id property from there.

**Comment by pyrello** [comment]
Just read through this again with fresh eyes after discussing #8212 with @bspeare. I want to take a step back and look at this from a big picture lens and think about what an ideal state would look like for us:

**Icon browser reimplemented as a SiteNow website, possibly as part of the brand website or as a continued standalone site.** 

This would put the power of making icon updates in the hands of content editors for that site and would get us out of the business of having to maintain the icon browser application. While the maintenance is not much for this site currently, it is built in Vue.js and will eventually require some type of updates as current dependencies will become insecure or abandoned. Having a bespoke application as part of our portfolio is not desirable when we could pretty easily build this type of thing in Drupal.

This would also give us all the tools of Drupal to leverage for the icon browser application such as revisions, feeds, etc.

**A scheduled job to import/update icons as media entities**

It would be great to have our icon implementation in SiteNow be as maintenance free as possible. A process that could keep the set of available icons up-to-date automatically without increasing the bloat of build or deployment times would be ideal. We have implemented a similar pattern for several sites, with the one that is coming to mind for me now being Commencement. The basic pattern is that we have a service that fetches data from a resource endpoint and a processor that creates, updates, and deletes entities based on the data pulled from the endpoint. A scheduled job triggers the service. 

Longer term, I think we would use a feed on the SiteNow-based Icon Browser site as the resource endpoint. In the near term, I think we could build an implementation that parse the icon browser repo for the required information.

**Comment by joewhitsitt** [comment]
I feel like we left the door open for https://github.com/uiowa/uiowa/issues/6704 to still happen.

**Comment by joewhitsitt** [comment]
I want to capture my concern from EoD about 1200+ websites all importing and processing these assets on a periodic schedule and needing additional logic to compare whether the icon needs to be updated or not.

I also want to point out that though the recently introduced processing is cumbersome but necessary, I see it only temporarily living in sitenow_media_wysiwyg. If we move forward with #6704 that processing can happen upstream, once. We can then fetch and track through git when we update icons for the service.

**Comment by pyrello** [comment]
> I also want to point out that though the recently introduced processing is cumbersome but necessary, I see it only temporarily living in sitenow_media_wysiwyg. If we move forward with https://github.com/uiowa/uiowa/issues/6704 that processing can happen upstream, once. We can then fetch and track through git when we update icons for the service.

Because the icons are going to be represented as media entities on every site, there still needs to be a point where the import happens (and comparisons made to determine whether icons are new or not). How do you envision this process working in the future state you are describing?

**Comment by joewhitsitt** [comment]
So right now the media entity only stores the relative path for the file in uids_base, so caching is the only impediment to serving an updated file as the current import is updating all based on id. There isn't a comparison in code currently. With that said, new/updated/deleted icons would still imported to uids_base by a developer as part of tracked git and then deployed with the hook to update sites. The alteration to the svgs would be the piece moved upstream. The comparison happens when we know there are updates and we make the update.

My goal in recommending the initial solution has never been to fully automate this. We do the same essentially with each UIDS update. To me, these icons are just an asset of UIDS/uids_base and served by way of media entities so it can blend with existing functionality.

Again, no strong opinion on which way we go, but highlighting some tradeoffs by switching.
