### ISSUE TITLE
Implement Icon library into card component

### ISSUE THREAD

**Issue by GaryRidgway** [uiowa/uiowa#8212]
[Grooming conversation was started here.](https://github.com/uiowa/uiowa/issues/6978#issuecomment-2460642513)

```[tasklist]
### Tasks
- [x] In `uiowa` Go to `/admin/structure/block-content/manage/uiowa_card/fields/block_content.uiowa_card.field_uiowa_card_image` and set "Brand Icon" as a media type
- [x] In `uids`, update the brand icon story (https://uids.brand.uiowa.edu/?path=/story/components-card--image-using-uiowa-icon) for the card component that uses brand icon svg in an `img` tag using the two color version of the icon. Styles for the size of the icon will need to be set through all of the media shapes and sizes. Work with Jess in OSC to make sure the icon is sized correctly within the media slot for all the variants. The background for the img svg will always need to be `#fff`.
```
* Remember that container queries on the "Grid" story will show the alignment variants. 

**Example sizing:**
Circle:
<img width="394" alt="Screenshot 2024-11-19 at 8 55 10 AM" src="https://github.com/user-attachments/assets/13c5303f-1cfc-450f-b405-bab7754b5328">
Widescreen:
<img width="443" alt="Screenshot 2024-11-19 at 8 59 06 AM" src="https://github.com/user-attachments/assets/11d2daee-6596-4f31-853c-2a8c753c5048">
Square:
<img width="449" alt="Screenshot 2024-11-19 at 8 59 30 AM" src="https://github.com/user-attachments/assets/4b62be53-aeaf-4534-a1f0-750e2c29da86">

**Comment by pyrello** [comment]
Noting that there has been some conversation in #8211 that will affect the future direction of this issue and being able to finish #8268. I'm firmly in the camp of wanting to automate as much of the processing that is necessary to keep icons up-to-date as media entities on each website. There have been some good points raised about the duplication of processing for each site unnecessarily increasing load on server resources with the idea I put forward in https://github.com/uiowa/uiowa/issues/8211#issuecomment-2501647362 (A scheduled job to import/update icons as media entities). I'm planning on taking a look at this with fresh eyes after the holiday break.

**Comment by pyrello** [comment]
Hmm... https://www.drupal.org/node/3490350

> New API for icon management
>
> A new API has been added to allow modules and themes to define icons as 'packs', and within the pack there are a series of icons each with a unique ID.

**Comment by bspeare** [comment]
Should we look into testing out https://www.drupal.org/project/ui_icons?  It seems to work fine as a defined field on the card block. 

<img width="1720" alt="Screenshot 2024-12-02 at 11 10 04 AM" src="https://github.com/user-attachments/assets/17b5b9c3-b3c7-4341-aeeb-598004d38e08">


If we used the `ui_icons` field our remaining work would be:
- Still need a build process for importing and adjusting the svgs or use the current `yarn_workspace` and custom drush command to adjust the icons and commit them to `uids_base`. 
- Update card template to work with new icon field in the media slot.
- Create show/hide logic on card block to hide image field when icon is selected.

I added https://github.com/uiowa/uiowa/pull/8298 to capture testing config.

**Comment by pyrello** [comment]
> * Still need a build process for importing and adjusting the svgs or use the current `yarn workspace` and custom drush command to adjust the icons and commit them to `uids_base`.

If we could avoid committing the icons, then we could potentially move the manipulation of the SVG into the frontend workflow and avoid needing a manual process for incorporating new icons.

**Comment by pyrello** [comment]
Here are thoughts about what needs to happen to the SVG files in frontend processing:
- The contents of the SVG file is written to a string.
- The height and width values in the `<svg>` tag in the string output are updated to the correct values.
- The string value is written back into the contents of the SVG file.

There is very likely a library we could use for processing changes to the SVG without having to do the low-level string manipulation.

**Comment by joewhitsitt** [comment]
So the Drupal icons method moves away from media entities right? Are the benefits of using media entities no longer desired? Easier integration with existing blocks, potential support in WYSIWYG?

I think this Icons feature in core would be great for fontawesome replacement for social media links, event block, timeline but I am not sure I understand using it for card image type situations.

**Comment by bspeare** [comment]
Seems like ui_icons supports WYSIWYG if we ever want to add them there.  Whether it is the media library or icon picker, both seem like decent ways to select icons.

**Comment by pyrello** [comment]
The downside of media entities was that it required some type of process to update each site to get new icons as media entities. Update hooks and scheduled jobs were two of the ideas we were discussing. 

One potential downside of moving the logic for updating the SVG into the frontend workflow is that it will slow down builds some amount. Builds are already really slow, but it is still desirable to not make them slower if possible, since it happens every time we push commits and the process represents a block for subsequent actions.

Maybe we could move the logic for creating a set of icons that is formatted for SiteNow specifically into the upstream repo for now? It could potentially be a part of the build process there meaning it would only need to run when we were cutting a new release. Then SiteNow could just import the icon set that is specifically formatted for it.

**Comment by bspeare** [comment]
The local workspace uids_base build goes from 4.41s to 4.88s after adding in the svg processing to our gulp file.
