### ISSUE TITLE
Advanced Webform Prospector application integration adjustments

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#8213]
Follow-up from https://github.com/uiowa/uiowa/issues/8138

Currently enabled and setup on https://sandbox.prod.drupal.uiowa.edu/form/prospector-test-form

Met with Siddharth and Ashani today to go over the work done in #8138. The good news is that the authentication portion was successful and the data was posted on their end. They also think the existing credentials will stay the same but the endpoint might change.

They clarified that the UUID was webform specific and not website specific, meaning the global configuration page was not necessary and that the UUID would be added to the handler itself. The Education website for example could have multiple forms and that each one would have a specific UUID.

The other thing they pointed out was that it was not limiting in what information from the form could be posted. Instead of hardcoding and passing only first_name, last_name, phone, email, it should be similar to the default remote post handler where the webmaster can select which webform fields are submitted.

It sounded like a representative from a college is able to go in to the AIS application and create their own "interaction" which supplies them with a UUID to use. In their minds, the support responsibility for them would be minimal in terms of getting setup and information posting. Interested groups would contact us to turn it on, the AIS group's contact info could be on the handler configuration form in case there are issues with the UUID, but that they would know what fields to include and configure the handler as necessary.

---

# Story

As a webmaster with Graduate RFI webforms, we would like the ability to pass collected information off to the Prospector application through AIS middleware, so that information can automatically be collected for further use in marketing and recruitment efforts.

# Additional Info

We would like to separate this from the existing advanced webform feature so that we have more control over what sites this gets turned on for and sites like Tippie and UIP who are using the advanced webform feature don't automatically have the ability to use these handlers.

Discussed having separate handlers for Graduate and Undergraduate forms with a shared base class. Scope of this issue would be the Graduate forms. We will address undergraduate forms in a future slice.

We determined that initially we do not plan to include any default form fields and that it will be up to the form creator to create all of the fields needed.

For Graduate forms we need to pass the following info in addition to the endpoint and credentials:

- Client Key - for Graduate forms this is `prospector`
  - This should be passed through the handler at a form level
- siteInteractionUuid - set by webmaster - string
- allow webmaster to choose additional form fields to be passed in similar to the default remote post handler

# Proposed Solution

- [x] Separate from advanced webform feature
- [x] Pass client key through handler `prospector`
- [x]  Switch from using a site-wide configuration form for UUID to a handler specific UUID, removing the configuration form in the end.
- [x] Allow webmasters the ability to select which fields from the webform should be submitted with the remote post handler similar to the default remote post handler that webform provides.
- [ ] Obtain a shared contact address to use in the help text of the handler in case they need assistance with the UUID.
- [ ] Confirm that the remote post handler does not try to post to the endpoint without a UUID.

**Comment by briand44** [comment]
>Obtain a shared contact address to use in the help text of the handler in case they need assistance with the UUID.

I sent an email to try and get this info.

**Comment by pyrello** [comment]
I have the arbitrary field selection functionality in place as well as refactoring to change names of things to not use Prospector since that no longer seems like the appropriate naming mechanism. Still need to split the new  functionality from the existing `advanced_webform` functionality. I have not added anything related to `clientKey` yet.

**Comment by pyrello** [comment]
Based on our conversation in EoD yesterday, we are waiting on the meeting with the AIS developers to have the work in #8295 reviewed by the team.
