### ISSUE TITLE
UKChoralComposers - Establish site split

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#8219]
```[tasklist]
### Tasks
- [ ] Establish site split - example pr with site split https://github.com/uiowa/uiowa/pull/8149
- [ ] Create a "Work" content type based on our best practices at https://docs.prod.drupal.uiowa.edu/development-workflow/content-type-best-practices
```

**Comment by bspeare** [comment]
Grooming notes:
- Work would be the first content type to work with.  
- Just establish content type and not the fields.  
- Follow best practices in our docs.  
- Establish the site split.

**Comment by bspeare** [comment]
@briand44 can we move forward with this as a first issue for James?

**Comment by briand44** [comment]
Just got word that they have decided not to move forward with transitioning so we won't want to move forward with this for this site.

**Comment by joewhitsitt** [comment]
Closing, but for onboarding purposes it would be nice to do something similar for another d7 custom website if possible.
