### ISSUE TITLE
Establish proper scheduled job logging/rotation for D7 ACN applications

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#8222]
Realized half way through that there are a couple production scheduled jobs on the D7 applications that have moved to ACN but there isn't proper log rotating similar to what we have setup for SiteNow v2/v3. https://github.com/uiowa/uiowa/blob/main/logrotate.conf

At the time of writing this, uidentistry, uigraduatecollege, uiowa702 have production cron or safe-cache-form-clear jobs that have been updated and are feeding into /shared/logs

I would assume we can place a similar logrotate.conf in each of those application repos and then place similar rotate /shared/logs jobs in stage and prod of those applications to ensure proper log rotation.

**Comment by joewhitsitt** [comment]
OneIT Intranet has a five min job on 702 so we probably want to address this before the end of the month (Nov 2024)

**Comment by briand44** [comment]
Grooming conversation... logrotate.conf can be done for all applications now. Updating scheduled jobs and creating the new scheduled job should happen once the applications are upgraded. 

These will all be on Cloud Next by Nov 15th.
Clas
Grad
Dentistry
701
702

703 upgrading Nov 20th

**Comment by joewhitsitt** [comment]
Creating a task list for myself:

- [x] 701 logrotate.conf
- [x] 701 DEV/STAGE/PROD jobs
- [x] 701 DEV/STAGE/PROD log clean slate
- [x] 702 logrotate.conf
- [x] 702 DEV/STAGE/PROD jobs
- [x] 702 DEV/STAGE/PROD log clean slate
- [x] 703 logrotate.conf
- [x] 703 DEV/STAGE jobs
- [x] 703 DEV/STAGE log clean slate
- [x] 703 PROD jobs _postponed_
- [x] 703 PROD log clean slate _postponed_
- [x] CLAS DEV/STAGE/PROD log clean slate
- [x] Grad logrotate.conf
- [x] Grad DEV/STAGE/PROD jobs
- [x] Grad DEV/STAGE/PROD log clean slate
- [x] Dentistry logrotate.conf
- [x] Dentistry DEV/STAGE/PROD jobs
- [x] Dentistry DEV/STAGE/PROD log clean slate
- [x] uiowa02 DEV rotate job
- [x] uiowa02 DEV/STAGE/PROD log clean slate
- [x] uiowa03 DEV rotate job
- [x] uiowa03 DEV/STAGE/PROD log clean slate
- [x] uiowa04 DEV rotate job
- [x] uiowa04 DEV/STAGE/PROD log clean slate
- [x] uiowa05 DEV rotate job
- [x] uiowa05 DEV/STAGE/PROD log clean slate
- [x] uiowa07 DEV rotate job
- [x] uiowa07 DEV/STAGE/PROD log clean slate
- [x] uiowa08 DEV rotate job
- [x] uiowa08 DEV/STAGE/PROD log clean slate
- [x] uiowa09 DEV rotate job
- [x] uiowa09 DEV/STAGE/PROD log clean slate

~CLAS logrotate.conf~
~CLAS DEV/STAGE/PROD jobs~

**Comment by joewhitsitt** [comment]
For 703, we will need to make sure the safe-cache-form-clear jobs are following the `*-safe-cache-form-clear.log` format.

**Comment by joewhitsitt** [comment]
I know for consistency sake, but I don't think uiclas needs logrotate.conf. DEV/STAGE/PROD were pretty much empty except for a few slow query files from like 2018. No scheduled cron and since it uses CAS, there isn't any simplesamlphp logging.

**Comment by joewhitsitt** [comment]
I think this is done besides 703 and checking the other apps on Monday to see how everything is going.

**Comment by joewhitsitt** [comment]
```
content-safe-cache-form-clear.log		 simplesamlphp-20241115.log-20241116.gz
content-safe-cache-form-clear.log-20241117.gz	 simplesamlphp-20241115.log-20241117.gz
content-safe-cache-form-clear.log-20241118.gz	 simplesamlphp-20241116.log-20241117.gz
drush-cron-oneit-intranet.log			 simplesamlphp-20241116.log-20241118.gz
drush-cron-oneit-intranet.log-2024-11-16.log.gz  simplesamlphp-20241117.log
drush-cron-oneit-intranet.log-2024-11-17.log.gz  simplesamlphp-20241117.log-20241118.gz
drush-cron-oneit-intranet.log-2024-11-18.log.gz  simplesamlphp-20241118.log
```

I think I am going to have to tweak the conf around simplesamlphp

**Comment by joewhitsitt** [comment]
just realized we have signage and healthcare signage too :drupal_cry:

**Comment by joewhitsitt** [comment]
deleted a lot of logs from signage and healthcare signage. setup jobs and logrotate.conf there too with the updated simplesamlphp conf i pushed up to the other d7 apps.

**Comment by joewhitsitt** [comment]
```
-rw-r--r--.  1 uiowa702.prod uiowa702    6198 Nov 19 05:12 simplesamlphp-20241118.log
-rw-r--r--.  1 uiowa702.prod uiowa702   21456 Nov 18 23:22 simplesamlphp-20241118.log.1.gz
-rw-r--r--.  1 uiowa702.prod uiowa702  171403 Nov 19 14:44 simplesamlphp-20241119.log
```
i might have my datetime calculations off, but I am starting to think that because the logs are rotated at UTC but the logs themselves are CT, the secondary `simplesamlphp-20241118.log` is created after the first one is rotated.

i could switch these to weekly to reduce the issue to just a sunday quirk, i could change the scheduled jobs to run at midnight CT instead of UTC, i could do nothing as the main objective of not letting /shared/logs fill up is still going to be achieved with what has been done so far.

**Comment by joewhitsitt** [comment]
leaning towards, "i could do nothing as the main objective of not letting /shared/logs fill up is still going to be achieved with what has been done so far." these apps will soon be retired and the logging with it.

consider this documentation for our future selves when we scratch our heads why the logs are like this.

**Comment by joewhitsitt** [comment]
updated 703. with that the original scope of D7 should be _done_. Separate tasks/reminders for remaining ACN upgrades

**Comment by briand44** [comment]
I've created separate issue for uiowa and uiowa01

#8275 
#8274
