### ISSUE TITLE
Deprovision v3 sites from uiowa04

### ISSUE THREAD

**Issue by cory-skeers** [uiowa/uiowa#8226]
* matthew-arndt.sites.uiowa.edu
* nanotech.uiowa.edu - https://nanotech.prod.drupal.uiowa.edu - Maggie said this can be removed.

Per Mike Cranston
> I have checked with Matthew Arndt, and he no longer needs the v1 site and doesn’t plan to replace it.

**Comment by joewhitsitt** [comment]
Emailed hostmaster to reclaim CNAMEs
