### ISSUE TITLE
Add building information to new buildings on maps.uiowa.edu

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#8227]
# Story

As a web team, we would like the new buildings that have been added to maps.uiowa.edu by Concept3D to have the building marker, images and supporting content so that visitors can find these buildings easily and have additional information about them.

# Additional Info

- Goschke Family Wrestling Training Center
- Gymnastics/Spirit Squad Training Center
- Hawkeye Parking Ramp
- West Campus Pumping Station

# Question

Is anything different now that Athletics has some sort of map as well? Does the content need to be consistent between the two or does theirs just show the content from the main map?

Wendy DeCora would be a good contact in Athletics about content and if/how this affects Athletics map.

# Proposed solution

**Comment by joewhitsitt** [comment]
https://help.concept3d.com/hc/en-us/articles/115005790267-Creating-A-New-Location

**Comment by joewhitsitt** [comment]
Example content of a point in addition to a building image and title:

```
Address: 801 Newton Road, Iowa City, IA 52242

Year built: 1973

Building abbreviation: DSB

Lactation room information:

S124, S126 (Lactation Room)

Gender-inclusive restroom information:

N303, S474, W304

[More building information](https://www.facilities.uiowa.edu/building/0278)
```

Regardless of a specific map category (Academic, etc.), all buildings are also added to the "All buildings" category

**Comment by briand44** [comment]
@GaryRidgway I'm seeing red circles. Do you see this?

<img width="1014" alt="Screenshot 2024-11-19 at 11 16 02 AM" src="https://github.com/user-attachments/assets/8e578dcf-2c25-468f-a161-a8ba00d0ca05">

**Comment by GaryRidgway** [comment]
This should be fixed now
