### ISSUE TITLE
'Temporarily Unavailable' message appears when attempting to compare revisions for a page

### ISSUE THREAD

**Issue by e-marie-w** [uiowa/uiowa#8231]
# Problem
Reported by Jean on education site, also happening on labtabel.prod.drupal.uiowa.edu. Probably related to the New Relic E_Compile_Errors we've been getting for these sites: https://iowaweb.slack.com/archives/CSQA18BK4/p1731014062988989. In my testing it happened on pages and people, but not articles.

# Steps to reproduce
Go to the Revisions tab of a page or person on an affected site and try to compare revisions.

# Proposed solution
 * Check entity_reference_revisions for patches, and if not one available, find or create an issue and add a patch. 
 * Test comparing revisions on different pieces of content, and see if new errors arise or if all is good
 * Repeat the above until you are able to compare revisions without error

**Comment by joewhitsitt** [comment]
Been seeing this in #drupal-status lately. Perhaps something with https://github.com/uiowa/uiowa/pull/8133 (updated diff module)

**Comment by cory-skeers** [comment]
This looks related: https://www.drupal.org/project/diff/issues/3480456

**Comment by cory-skeers** [comment]
> This looks related: https://www.drupal.org/project/diff/issues/3480456

It is. I tried the fix from the smart_date issue referenced there, and it resolved. (Adding a return type declaration for each function in EntityReferenceRevisionsFieldDiffBuilder.)

**Comment by cory-skeers** [comment]
I think technically we could fix this for all possible modules that extend it by patching `diff\src\FieldDiffBuilderBase` and remove the return type declarations, so that classes that extend it which don't declare it, like EntityReferenceRevisionsFieldDiffBuilder don't throw errors.

But it's for sure an upstream issue for either `diff` or any module that includes plugins extending it for their fields that haven't included a return type declaration.

**Comment by joewhitsitt** [comment]
As mentioned on the smart_date issue, code should be moving this direction as best practice so I wonder if we can pinpoint the problem modules as the error occurs and see if they have a d10/11 php8.2/8.3 release where these kinds of things were probably fixed.

**Comment by briand44** [comment]
Planning conversation... Any piece of content that has an entity reference revisions will throw this error. Could be other fields as well but entity reference triggers the errors first. Hoping for upstream patches in the modules that supply those fields. Check entity_reference_revisions for patches, and if not one available, find or create an issue and add a patch. After that, test revisions on different pieces of content, and see if new errors arise or if all is good.

**Comment by cory-skeers** [comment]
https://www.drupal.org/project/entity_reference_revisions/issues/3460600 Yay

Available in v1.12 (we're on 1.5) so it's a couple versions ahead. Should check on if we can safely update, and if not, can patch it from that issue (and then check on if other modules are throwing the error or not).

**Comment by joewhitsitt** [comment]
Slightly concerned what updating entity_reference_revisions means for us given closely tied it is to paragraphs. SiteNow v2, default_content spring to mind. Go get em! You got this! Thanks!

**Comment by cory-skeers** [comment]
Some of the version updates like 1.8 -> 1.9 are reeeeally small.
<img width="1103" alt="image" src="https://github.com/user-attachments/assets/99d24cbb-5982-45a7-acb3-8e61752e52bd">

The first update (for us) introduces support for translations, so it _shouldn't_ effect any of our stuff, but it's at least bigger to the point that review/testing would be good, but I'm feeling better about potentially being able to just update the module.

Edit: Ope. Set the comparison up wrong. It's bigger than that.

**Comment by cory-skeers** [comment]
(potentially ongoing) list of updates need so far:

- [x] layout_builder_custom
- [x] geofield (https://www.drupal.org/project/geofield/issues/3467827)
- [x] entity_reference_revisions
- [x] smart_date
- [x] address (https://www.drupal.org/project/address/issues/3460590)
