### ISSUE TITLE
Display context if not "Default" on academic calendar dates

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#8232]
# Story

As a Registrar site owner, we would like to display the "context" when not "Default" when outputting academic dates in the academic calendar to provide more clarity when there are multiple dates with the same info.

# Additional Info

![Screenshot 2024-11-12 at 2 05 14 PM](https://github.com/user-attachments/assets/efcb9782-10ac-47c1-80fc-fd990d4410e7)

>sessionDateDTO > contextLookup > naturalKey - available in https://api.maui.uiowa.edu/maui/api/pub/registrar/session-dates https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/uiowa_maui/src/MauiApi.php#L129C19-L129C37

https://github.com/uiowa/uiowa/issues/8186#issuecomment-2471434493

| Description    | Natural Key |
| -------- | ------- |
| Registrar Dates  | DEFAULT    |
| Orientation | ORIENTATION     |
| Grades    | GRADES    |
| College of Dentistry    | DENTISTRY    |
| Billing Dates    | BILLING    |
| Carver College Of Medicine    | MEDICINE    |
| College of Nursing    | NURSING    |
| Tippie College of Business    | BUSINESS    |
| College of Public Health    | PUBLIC_HEALTH    |
| College of Liberal Arts and Sciences    | LIBERAL_ARTS_SCIENCES    |
| College of Education    | EDUCATION    |
| University College    | UNIVERSITY_COLLEGE    |
| National Student Clearinghouse Dates    | NSC    |
| Data Warehouse    | datawarehouse    |
| Graduate College    | GRADUATE    |
| College of Pharmacy    | PHARMACY    |
| College of Engineering    | ENGINEERING    |
| College of Law    | LAW    |
| Tippie College of Business Professional Programs    | TCOB_GMP    |
| Admissions Dates    | ADMISSIONS    |
| Financial Aid Dates    | FINAID_DATES    |

# Proposed solution

**Comment by briand44** [comment]
Grooming conversation... Description appears to exist in the endpoint in addition to the Natural key. It was suggested to append to the title with a hyphen. Didn't seem like we wanted to use badges here.

**Comment by e-marie-w** [comment]
Screenshot of how it looks now:
![Screenshot 2024-11-18 at 4 10 11 PM](https://github.com/user-attachments/assets/a028dd1d-c732-48cf-be4b-3f03724f496e)
