### ISSUE TITLE
Move UIDS4 Footer component into uids_base

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#8236]
The UIDS4 footer component is ready for review and integrated into uids_base. 

# Proposed solution
- Review https://github.com/uiowa/uids/pull/894

**Comment by briand44** [comment]
Grooming conversation... Currently a direct transfer from Fractal converted into a Vue component. Sounds like that should be fine. Sounds like team doesn't want to over-invest and is anxious to get these components moved so we no longer need to keep linking to UIDS3 components. Some steps in the PR to do once merged.

**Comment by bspeare** [comment]
This is complete.
