### ISSUE TITLE
[ITS] Anchor IDs in headings on service pages

### ISSUE THREAD

**Issue by e-marie-w** [uiowa/uiowa#8241]
# Story
As an ITS web editor, I want anchors/id’s in the headings for the views blocks (e.g., “Alerts” and “Support and Training”) on service pages so that I can send users directly to these portions of the pages

# Proposed solution
Edit the config on the blocks and add IDs they can use.

**Comment by e-marie-w** [comment]
Blocked by #8246, at least for me.

**Comment by briand44** [comment]
Grooming conversation... These headings/id's will need to be deployed through code because it is contained in config. Communicate ids once places to James and Adrienne so they know how to create their anchors.
