### ISSUE TITLE
uiowa06 cron/log rotate

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#8247]
This app is scheduled for upgrade on Nov 19th. We should update the cron job and add the schedule job to rotate the logs similar to the other apps that have already been upgraded.

**Comment by joewhitsitt** [comment]
>Remove cron jobs on DEV/STAGE. Copy paste the cron job from uiowa07 and update the cron job, modifying the filename. Copying the rotate /shared/logs job from uiowa07 and scheduling it weekly on sundays.

**Comment by james917** [comment]
Updated uiowa06 prod to new crons ![Image](https://github.com/user-attachments/assets/93674002-322a-41ac-b766-c794666a901a)
![Image](https://github.com/user-attachments/assets/79749fe7-fcb7-4e7e-8764-63a684a626c3)
![Image](https://github.com/user-attachments/assets/4a70a257-0eb9-42de-9eaa-f39bf4f1ed5e)
