### ISSUE TITLE
Audit Vulture/Crow

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#8263]
# Story

As a web team, it would be good to audit and document applications/functionality running on Vulture as we prepare for a server migration so that we have a better understanding of what is still needed, what can go away and what we will need to be testing.

# Additional Info

There is some useful information in the readme for the data.its repo https://git.uiowa.edu/its-web/data.its.uiowa.edu/-/blob/main/README.md?ref_type=heads

Identify and document any additional functionality not already documented

Identify any functionality that is no longer needed

Remove what is no longer needed?

**Comment by briand44** [comment]
Grooming conversation... Was mentioned we should take our time with this and not immediately start removing stuff. Lets scope this to identifying things we believe are no longer in use and have follow ups to remove. It was mentioned that Crow hosts our authentication for non-production environments. Vulture has all of our redirects hosted there but we have not been involved in that. Should look at crontab to see what jobs exist there and document. Documentation that is not appropriate for readme can go in our internal docs site. Was mentioned long term goal could be to only rely on this for authentication and redirects.

**Comment by joewhitsitt** [comment]
@GaryRidgway i'd be willing to mob on this while sharing what I know about how things are setup

**Comment by joewhitsitt** [comment]
Calls to data.its from v2/v3 SiteNow websites:

https://github.com/uiowa/uiowa/blob/b1aa3c8e1dc46f480b18aa6da608b0a96bea3c66/docroot/sites/registrar.uiowa.edu/modules/registrar_core/src/Form/CourseDeadlinesForm.php (building number lookup)

https://github.com/uiowa/uiowa/blob/1455c7be617bce1548b96ad8437f04b56bf2b4b4/docroot/modules/custom/sitenow_dispatch/src/Form/ThankYouForm.php (supervisors)

---

As it relates to the crontab, there is only one on vulture (none on crow) that is visible to the dataits user.
```
[dataits@vulture ~]$ crontab -l
* * * * * /opt/remi/php74/root/usr/bin/php /local/www/vhosts/data.its.uiowa.edu/artisan schedule:run --quiet
```

**Comment by GaryRidgway** [comment]
[Issue here on gitlab](https://git.uiowa.edu/its-web/data.its.uiowa.edu/-/issues/22)

**Comment by joewhitsitt** [comment]
Started a draft MR to incorporate audit into the readme: https://git.uiowa.edu/its-web/data.its.uiowa.edu/-/merge_requests/133

**Comment by joewhitsitt** [comment]
It looks like the User CRUD commands that Alan documented go back to https://git.uiowa.edu/its-web/data.its.uiowa.edu/-/merge_requests/30#69e3bd8ddf957a32ec5a3b80a87f8cc4bfe36a27 which references the Thank You program's supervisors functionality.

Following the instructions in the PR there is a database that has one user snv3/its-web@uiowa.edu with an API token. I assume all of this was to hold creds for authentication with HRIS?

**Comment by joewhitsitt** [comment]
I put https://git.uiowa.edu/its-web/data.its.uiowa.edu/-/merge_requests/133 up for review. I think it is a decent summation of things and will be helpful for the upcoming slices.
