### ISSUE TITLE
Italy MBA homepage timeout issue

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#8265]
# Problem
The Italy MBA homepage has been triggering Pingdom notifications. @pyrello has also observed the page not loading. @quamsta noted that the form on the page seems to prevent the page from being cached in Varnish.

Additionally, Acquia opened a case for the application this site is hosted on (uiowa02): https://acquia.my.site.com/s/case/500Pb00000SHeovIAD/courtesy-investigation

https://italymba.tippie.uiowa.edu/

# Steps to reproduce
TBD

# Proposed solution
TBD

**Comment by briand44** [comment]
Grooming conversation... Have received a few Pingdom alerts on separate days related to the Italy MBA site. Sean also was able to observe the issue with the homepage not loading. We should keep an eye on https://acquia.my.site.com/s/case/500Pb00000SHeovIAD/courtesy-investigation in addition to investigating ourselves. We should see if we can find anything in the logs related to this (Splunk/Acquia). Pingdom notifications came on 11/19 around 1:27pm and on 11/20 around 9:22am. We may want to follow up on the Acquia ticket and share the information about this site going down to make sure they have all the info and that these things are related. No splits enabled for this site.

**Comment by cory-skeers** [comment]
Splunk logs around the timeframe:
https://splunk.its.uiowa.edu/en-US/app/search/search?earliest=%40d&latest=now&q=search%20index%3Duiowa-acquia%20italymba.tippie.uiowa.edu&display.page.search.mode=smart&dispatch.sample_ratio=1&display.prefs.events.count=50&display.events.timelineEarliestTime=1732118400&display.events.timelineLatestTime=1732122000&sid=1732130320.309627

**Comment by pyrello** [comment]
I added a comment to the existing Acquia support ticket with the information about the alerts and this site.

**Comment by pyrello** [comment]
Response from Acquia:

>I have discovered few 500 Errors around the timeframe 19/11/2024 11:00:00 PM to 19/11/2024 11:59:59 PM UTC on 19th Nov
>
>\#	Time	log	Source Host	status_code
>1	19/11/2024 11:33:13.479 PM +0000	[19/Nov/2024:23:33:13 +0000] laborcenter.uiowa.edu GET /sites/laborcenter.uiowa.edu/files/js/js_N6L4gPY5SYkZIJ4SmXa9wtAapeLLEjteC3iw69R4nuc.js?scope=footer&delta=2&language=en&theme=uids_base&include=eJx9j-EOgzAIhF_Iro9ksGJLgsUUqnFPv5otzh9uv7jkO-BukmywocqMfvrqh66xqzRqP4CijywDsFPbmfIBZIM-SGnEIHZKhlm20xYKLaaXfYbn7lhgdJBpBiPJF6pMI5bPVWAspv49Oq0Llok0-VP1SVYslNtLu-UmNaSWATHfcp2B-R-vyyKt0hHyB8eidbhNd62FUEJyJjEyvgDRJI_u http_code=500 query=scope=footer&delta=2&language=en&theme=uids_base&include=eJx9j-EOgzAIhF_Iro9ksGJLgsUUqnFPv5otzh9uv7jkO-BukmywocqMfvrqh66xqzRqP4CijywDsFPbmfIBZIM-SGnEIHZKhlm20xYKLaaXfYbn7lhgdJBpBiPJF6pMI5bPVWAspv49Oq0Llok0-VP1SVYslNtLu-UmNaSWATHfcp2B-R-vyyKt0hHyB8eidbhNd62FUEJyJjEyvgDRJI_u uid=0 php_pid=18 php_time=0.103 queue_wait=0 request_id="v-a5015b06-a6ce-11ef-a6a3-8b6a41239631" drupal_version="10.3.6"	54.87.10.190	500
>2	19/11/2024 11:33:13.479 PM +0000	127.0.0.1 -  19/Nov/2024:23:33:13 +0000 "GET /index.php" 500 memory_kb=30720 %cpu=38.22 duration_ms=104.665 request_id="v-a5015b06-a6ce-11ef-a6a3-8b6a41239631"	54.87.10.190	500
>3	19/11/2024 11:33:13.464 PM +0000	166.181.81.195 - - [19/Nov/2024:23:33:13 +0000] "GET /sites/laborcenter.uiowa.edu/files/js/js_N6L4gPY5SYkZIJ4SmXa9wtAapeLLEjteC3iw69R4nuc.js?scope=footer&delta=2&language=en&theme=uids_base&include=eJx9j-EOgzAIhF_Iro9ksGJLgsUUqnFPv5otzh9uv7jkO-BukmywocqMfvrqh66xqzRqP4CijywDsFPbmfIBZIM-SGnEIHZKhlm20xYKLaaXfYbn7lhgdJBpBiPJF6pMI5bPVWAspv49Oq0Llok0-VP1SVYslNtLu-UmNaSWATHfcp2B-R-vyyKt0hHyB8eidbhNd62FUEJyJjEyvgDRJI_u HTTP/1.1" 500 61 "https://laborcenter.uiowa.edu/" "Mozilla/5.0 (iPhone; CPU iPhone OS 18_0_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0.1 Mobile/15E148 Safari/604.1" vhost=uiowa02.prod.acquia-sites.com host=laborcenter.uiowa.edu hosting_site=uiowa02 pid=17 request_time=99196 forwarded_for="166.181.81.195, 10.26.111.27" request_id="v-a5015b06-a6ce-11ef-a6a3-8b6a41239631" location="-"	54.87.10.190	500
4	19/11/2024 11:33:13.460 PM +0000	[19-Nov-2024 17:33:13 America/Chicago] Uncaught PHP Exception Exception: "Only file JavaScript assets with preprocessing enabled can be optimized." at /var/www/html/docroot/core/lib/Drupal/Core/Asset/JsOptimizer.php line 34 request_id="v-a5015b06-a6ce-11ef-a6a3-8b6a41239631"	54.87.10.190	
5	19/11/2024 11:33:13.460 PM +0000	https://laborcenter.uiowa.edu|1732059193|php|166.181.81.195|https://laborcenter.uiowa.edu/sites/laborcenter.uiowa.edu/files/js/js_N6L4gPY5SYkZIJ4SmXa9wtAapeLLEjteC3iw69R4nuc.js?delta=2&include=eJx9j-EOgzAIhF_Iro9ksGJLgsUUqnFPv5otzh9uv7jkO-BukmywocqMfvrqh66xqzRqP4CijywDsFPbmfIBZIM-SGnEIHZKhlm20xYKLaaXfYbn7lhgdJBpBiPJF6pMI5bPVWAspv49Oq0Llok0-VP1SVYslNtLu-UmNaSWATHfcp2B-R-vyyKt0hHyB8eidbhNd62FUEJyJjEyvgDRJI_u&language=en&scope=footer&theme=uids_base|https://laborcenter.uiowa.edu/|0||Exception: Only file JavaScript assets with preprocessing enabled can be optimized. in Drupal\Core\Asset\JsOptimizer->optimize() (line 34 of /var/www/html/docroot/core/lib/Drupal/Core/Asset/JsOptimizer.php). request_id="v-a5015b06-a6ce-11ef-a6a3-8b6a41239631"	54.87.10.190	
> 
>indicating an error related to --
> 
>Uncaught PHP Exception Exception: "Only file JavaScript assets with preprocessing enabled can be optimized."
> 
>Traffic counts from the IP around that time:
>
>\#	src_ip	info	country	state	asn	organization	_count	_count_1d	_count_2d
>1	35.156.240.123	IP info	DE	Hessen	AS16509	amazon.com  inc.	3,354	7,307	793
>2	13.74.145.68	IP info	IE	Dublin	AS8075	microsoft corporation	609		
>
>Traffic counts from the UA around that time:
>
>\#	bot_name	user_agent	_count	_count_1d	_count_2d
>1	Siteimprove	Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; Trident/6.0) LinkCheck by Siteimprove.com	3,147	>6,863	609
>2		Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko	980	1,481	1,062
> 
>for the above error:
> 
>The exception "Only file JavaScript assets with preprocessing enabled can be optimized" in a Drupal context suggests that there is an attempt to optimize JavaScript files that haven't been set for preprocessing. This typically involves the assets being aggregated or minimized during rendering.
> 
>whenever you encounter these kind of errors, you need to check by going --
> 
>In the Drupal admin interface, check the performance settings to ensure that JavaScript and CSS aggregation are enabled. Navigate to Configuration > Performance and confirm the settings under "Bandwidth optimization."
> 
>also 
> 
>Clear the site cache to make sure that any changes to your asset configuration or performance settings are recognized.

**Comment by joewhitsitt** [comment]
Have we heard more reports about this? It looks like Acquia is about to close the ticket. I just noticed the error furnished by Acquia doesn't even mention italymba, but just groups it based on being on the same application (uiowa02)

**Comment by james917** [comment]
unable to replicate issue
