### ISSUE TITLE
Provide taxonomy data and users export to AIS for consumption

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#8267]
Initial Slice of Epic https://github.com/uiowa/uiowa/issues/8266

We want to provide taxonomy data and files to AIS so they can begin consuming.

https://content.uiowa.edu/events-api

**Taxonomies**

Audiences - https://content.uiowa.edu/api/v1/views/filters_api.json?display_id=filters
Event Types - hierarchical - https://content.uiowa.edu/api/v1/views/filters_api.json?display_id=filters
General Interests - hierarchical - https://content.uiowa.edu/api/v1/views/filters_api.json?display_id=filters
Keywords - https://content.uiowa.edu/api/v1/views/filters_api.json?display_id=keywords
Places -  contains additional metadata (address, etc.) - https://content.uiowa.edu/api/v1/views/places_api.json?display_id=places
Units - relationship with event unit admin

**Users**
CSV export of user information and if they are an even_unit_admin, the unit(s) they are an admin for.

# Questions
  - What are we using to get lat/long
  - Is lat/long being used for anything
  - Is there any need to keep content.uiowa.edu domain
    - Are we ok if API endpoints move to events.uiowa.edu

Grooming conversation - https://github.com/uiowa/uiowa/issues/8266#issuecomment-2489440188

# Proposed solution

```[tasklist]
### Proposed Solution
- [x] Review existing endpoints (filters, keywords, places) to make sure they contain all relevant data for importing taxonomy info
- [x] Share endpoints with AIS as we confirm ok to use
- [x] Provide answers to the questions from AIS
- [x] export of user info and event_unit_admin relationship to units
```

**Comment by briand44** [comment]
I wonder if the Units could be imported from the Filters API and then we provide the event unit admins and their respective unit as part of the Users export? If so, that may allow us to have one less export needed if we do end up deciding we need to create an export for the users.

**Comment by e-marie-w** [comment]
The endpoints listed contain most of the same fields as on the taxonomies on the site. There is a 'description' field for each taxonomy but on the random terms I clicked on it was never used, so I think it's safe to ignore it. I think grabbing the Units from the Filters API (they are labelled Departments there) should be fine. Event admins are not in that API as previously mentioned and an export of that data would be best.

**Comment by e-marie-w** [comment]
I think I figured out some of the lat/long stuff. For the Places taxonomy on the site there is an Address fieldgroup with country, address line 1, address line 2, city, state, and zip code fields. There is also a geo field which plugs the address info into Google Geocoder to get the lat/long values.

**Comment by briand44** [comment]
Discussed changing the scope in EOD. Based on some uncertainty with the files and some clarity and urgency with users and event unit admin info, lets move forward with a views_data_export of user info that also outputs the department if the user is an event_unit_admin. Providing files for consumption can be in the next slice with the event info.

**Comment by briand44** [comment]
Remaining work for this slice is to create a csv export of user data (hawkid, email, status, role, department they are an event_unit_admin of) that we can easily run again in the future and provide it to our AIS partners.

**Comment by joewhitsitt** [comment]
I tried to help out real quick and get this list, but there is an views aggregation related issue here that I can't remember how to solve.

Users based view with a relationship to the referencing field on the taxonomy term. Add the taxonomy term name (with relationship) to the output.

This creates a separate row for every unit the user is referenced on. My attempts to aggregate and group together did not immediately work. I feel like I am missing something obvious here.

**Comment by joewhitsitt** [comment]
@briand44 and I looked at this a bit more but still didn't find an easy way to combine the units on a single user row.

I've added the view to https://content.uiowa.edu/admin/structure/views/view/Users/edit (disabled).

I told Brian I could take the output of this and clean it up in Excel before passing it off as a worse-case solution, but I see the value in trying to make it easy to pull again in the future.

The is supposedly a contrib solution out there but not one that is available in sites/all. I am surprised we haven't run into this before.
https://www.drupal.org/project/views/issues/693664#comment-9441209
https://www.drupal.org/project/views_aggregator

**Comment by joewhitsitt** [comment]
views_aggregator is a separate views formatter, so i can't use it and use the csv export at the same time.

**Comment by joewhitsitt** [comment]
Taking a quick stab at trying to bypass Views here with a custom callback entityquery.

Update: i got a barebones version working. i just need to make sure access check is correct, and the rest of the data is fetched and output correctly.

**Comment by joewhitsitt** [comment]
I am going to deploy this out to DEV and have someone try it.

**Comment by joewhitsitt** [comment]
Git branch: `content_hub_users_export` on uiowa702

Example output:
```
id,user,email,status,roles,units
86,jwhitsit,joe-whitsitt@uiowa.edu,1,"administrator, events unit admin","GIS Technical Advisory Committee, Digital Signage"
```

# To Test

- content.dev.drupal.uiowa.edu as anonymous, try to go to /admin/reports/user-export (should be access denied)
- Login and go to the path again. This time it should trigger an CSV download. Save the file to your machine and open.
- Should consist of a list of users (with at least one role, not user 0/1).
- The list should include values for their uid, name, email, status, roles, units.
- roles and units should be safely comma-separated within double-quotes
- the list should consist of a few users with status = 0 showing that both active and blocked users are included.

**Comment by briand44** [comment]
Test instructions all checked out for me. My only question is if we need to be including all users (authenticated) and not just users with at least one role. I will try to get clarification on that.

**Comment by briand44** [comment]
Had a conversation with AIS folks and they would like to include all users, authenticated as well as users with additional roles.

**Comment by joewhitsitt** [comment]
Just updated the logic to include all users, ran an export from DEV (yesterday's db sync) and emailed Ben and Himanshu.

**Comment by joewhitsitt** [comment]
This has been deployed and can be triggered when logged in at admin/reports/user-export
