### ISSUE TITLE
[ ITS ] Fix broken config.

### ISSUE THREAD

**Issue by GaryRidgway** [uiowa/uiowa#8272]
As seen [in this PR](https://github.com/uiowa/uiowa/pull/8261) there is some very wonky stuff going on with config on ITS right now.

- Config cannot be exported with a config split export command because of incorrect permissions listed in the help desk user role.
- There seems to be some odd moderation state stuff going on

What I did was delete the errant entries from the help desk user config file, import and then try and make my changes, but after that exporting also brought forth the other observed config changes.

Smoothing this out would be nice so that future devs don't have to know how to get around these issues.

**Comment by briand44** [comment]
We'll want to pair this work with the work in #8241 and keep to a single PR

We also want to make sure the alert title field doesn't reappear.
