### ISSUE TITLE
linkit_media_library is no longer working

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#8276]
# Problem

linkit_media_library doesn't appear to be working anymore. The ability to add or select existing. The balloon also is on top z-index-wise again in layout builder. we are using the latest version of the patch. https://www.drupal.org/project/linkit_media_library/issues/3329877

# Steps to reproduce

Add page > Body > Link > Media Library

OR

Layout builder > Text Area > Link > Media Library

<img width="1424" alt="Screenshot 2024-11-21 at 10 49 21 AM" src="https://github.com/user-attachments/assets/ee02a6f6-efde-4357-b3f2-3245f0e60c2a">

# Proposed solution
?

**Comment by briand44** [comment]
Grooming conversation... We own a patch for this and likely need to review/fix.

**Comment by briand44** [comment]
hmm... did some testing this morning on this and was able to add media through the link it media library on the node edit form and then was able to choose existing media using the text area component in layout builder as well. Tested on https://sandbox.prod.drupal.uiowa.edu/test-3

I did notice the z-index issue using the text area component in layout builder

**Comment by pyrello** [comment]
Grooming conversation... original bug seems to not be an issue anymore, so we'll close this issue in favor of another issue specific to the z-index problem.
