### ISSUE TITLE
Deactivate v1 standard sites that still remain

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#8277]
We previously communicated Dec 2nd was our final extended deadline. Are we moving forward with deactivating remaining sites?

https://github.com/uiowa/uiowa/issues/8230

Deactivate = remove domain from Acquia, not permanently removing. We likely will want to wait 30-60 days before backing up and permanently removing. I will carve off a separate slice for that.

Max has asked us not to deactivate Ted Abel's site.

We will want to maintain a list of sites that we deactivated.

**Comment by briand44** [comment]
blocked until Dec 3rd

**Comment by joewhitsitt** [comment]
Include post-deactivated comms.

**Comment by pyrello** [comment]
A couple ideas that were discussed for the comms:
- Set the subject line to `Re:` + whatever the previous email subject was to see if that allow Outlook to group the emails together.
- Include the text of the previous email as a quote underneath the email to provide additional context.

**Comment by joewhitsitt** [comment]
After team consideration, atasoy.lab.uiowa.edu was granted an extension till 12/9.

**Comment by joewhitsitt** [comment]
perception.lab.uiowa.edu thread is in its-web, they were aware of the deadline but didn't give approval before break. might be worth checking with them before deactivating it.

**Comment by joewhitsitt** [comment]
Thinking about working on this. Sanity-check - Is https://github.com/uiowa/uiowa/issues/8230 up-to-date? @GaryRidgway do you have capacity this morning to check in with:

ieee.org.uiowa.edu
perception.lab.uiowa.edu
rohlman.lab.uiowa.edu

**Comment by briand44** [comment]
>Is https://github.com/uiowa/uiowa/issues/8230 up-to-date?

As far as what has launched, I believe it is. The notes may be outdated by now though.

**Comment by joewhitsitt** [comment]
Proposed post-deactivation email:

```
<p>The following websites have been deactivated:</p>

<p>Current SiteNow v1 URL: ${v1domain}</p>
<p>The internal staging SiteNow v3 URL: ${v3domain}</p>

<p>As no response was received by the December 2, 2024 deadline, both websites have been deactivated and will eventually be queued for removal.</p>

<p>If this was in error or you need assistance, please contact us immediately at its-web@uiowa.edu.</p>

<p>OSC Web Team</p>

<hr />

<blockquote>
<p>This is your final reminder to transition your website to the new SiteNow platform. If we do not receive a response by December 2, 2024, your current SiteNow v1 and SiteNow v3 replacement websites will be removed.</p>

<p>Your current SiteNow v1 URL is: ${v1domain}</p>
<p>The internal staging SiteNow v3 URL is: ${v3domain}</p>

<p>Please let us know if you are:
    <ul>
      <li>Ready to launch the new website</li>
      <li>Unable to meet the deadline</li>
      <li>No longer needing your current website and don't plan on replacing it</li>
    </ul>
</p>

<p>In addition to contacting you, we have also contacted the following individuals regarding the status of this website:<br>
${others}
</p>

<p>To learn more about the SiteNow v1 Standard service retirement, <a href="https://sitenow.uiowa.edu/sitenow-v1-standard-platform-shutdown">click here</a>.</p>

<p>Thank you for your attention to this matter and for your continued support.</p>

<p>Best regards,<br>
OSC Web Team</p>
</blockquote>
```

**Comment by joewhitsitt** [comment]
Are we deactivating their v1 and non-live v3 or just the v1?

**Comment by joewhitsitt** [comment]
Reminder for myself - Need to update the population to remove websites that have launched or weren't deactivated.

**Comment by briand44** [comment]
>Are we deactivating their v1 and non-live v3 or just the v1?

My thought was we would deactivate the v1 sites as part of this slice and keep a record of the sites we deactivated. In a future slices we would potentially archive v1 standard sites that have been deactivated with libraries, backup and remove v1 standard sites that were deactivated and a slice to cleanup v3 sites that were provisioned but never transitioned.

**Comment by cory-skeers** [comment]
> Proposed post-deactivation email:

Only note would be to change "...and will eventually be queued for removal..." to "...and will be queued for eventual removal" or just "...and will be queued for removal" (former is less urgent; but for either, the deadline has passed so the queueing part happens now).

> Are we deactivating their v1 and non-live v3 or just the v1?

Since we're including the text of the previous email, and it did say "your current SiteNow v1 and SiteNow v3 replacement websites will be removed," both? But maybe it could be in steps. v1 now, v3 in a month.

**Comment by joewhitsitt** [comment]
>keep a record of the sites we deactivated

Where would you like me to do this? Drupal 7 Sites spreadsheet? #8230?

**Comment by briand44** [comment]
>Where would you like me to do this? Drupal 7 Sites spreadsheet? https://github.com/uiowa/uiowa/issues/8230?

Seems like we should keep track of this in the D7 site spreadsheet since that is our primary source of info for these sites. I think a separate column would be better than just adding to the notes.

**Comment by joewhitsitt** [comment]
There is a test email in its-web with an updated population here https://apps.its.uiowa.edu/dispatch/populations/1370800048/members

Send? I'll work on the spreadsheet in the meantime.

**Comment by joewhitsitt** [comment]
Can I rename the "Domain Redirected or Removed (no v3 site)" column and use that to document the deactivated?

**Comment by briand44** [comment]
sure, just want to be able to quickly filter by all sites that have been deactivated

**Comment by briand44** [comment]
looked at the test email and curious if there is an issue:

>In addition to contacting you, we have also contacted the following individuals regarding the status of this website:
[kcoreykirk-corey@uiowa.edu](mailto:kcoreykirk-corey@uiowa.edu), [courtney-hoffman@uiowa.edu](mailto:courtney-hoffman@uiowa.edu)

kcoreykirk-corey@uiowa.edu looks odd

**Comment by joewhitsitt** [comment]
That is how the value was in the spreadsheet. I've updated the spreadsheet and the population for that one.

The spreadsheet is also updated with Deactivated values. I went through the column and specified which "yes" values mean redirected or removed. A few were marked as Removed but the domain is still pointing at Acquia.

**Comment by joewhitsitt** [comment]
Chatted with Brian a bit about the v1/v3 difference here. How about changing the first section to something like:

```html
<p>The following SiteNow v1 website, ${v1domain}, has been deactivated.</p>

<p>As no response was received by the December 2, 2024 deadline, both ${v1domain} and ${v3domain} websites will be queued for removal.</p>

<p>If this was in error or you still want to launch ${v3domain}, please contact us immediately at its-web@uiowa.edu.</p>

<p>OSC Web Team</p>
```

**Comment by joewhitsitt** [comment]
I sent the email at 3PM. From what I am seeing in its-web, leaving the v3 version enabled was the right call.
