### ISSUE TITLE
Replicate homepage on default site isn't working

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#8279]
# Problem
When reviewing the core update PR (https://github.com/uiowa/uiowa/pull/8273), Sean noticed that replicate on the default content homepage is not working. Other nodes it is working. Confirmed it was the same on `main`

# Proposed Solution

**Comment by cory-skeers** [comment]
This is an issue with our additional Replicate subscriber (which is included to replicate our list blocks, which don't get handled through Replicate's layout builder plugin.

Creating a fresh page and adding a section with at least 2 list components and then replicating the page leads to the same error.

**Comment by cory-skeers** [comment]
> This is an issue with our additional Replicate subscriber (which is included to replicate our list blocks, which don't get handled through Replicate's layout builder plugin.
> 
> Creating a fresh page and adding a section with at least 2 list components and then replicating the page leads to the same error.

Specifically, here: https://github.com/uiowa/uiowa/blob/5de72a59133a82772335b92441986f36f975aef3/docroot/modules/custom/layout_builder_custom/src/EventSubscriber/ReplicateSubscriber.php#L190
