### ISSUE TITLE
Add additional correspondence category mappings

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#8287]
# Story

As a Registrar site owner, we would like to map additional topics to the correspondence feature.

# Additional Info

https://github.com/uiowa/uiowa/blob/1f8c8d18614c6024215d487ab0e7217a357b9fd3/docroot/sites/registrar.uiowa.edu/modules/registrar_core/registrar_core.module#L277

**Additional Topics**
courses = Courses
sample plans = Sample Plans
general catalog = General Catalog

**Comment by briand44** [comment]
blocked until we get the additional categories

**Comment by pyrello** [comment]
Grooming conversation... Adding additional categories to the mapping in the function referenced in the IS.
