### ISSUE TITLE
Provide Events to AIS for consumption

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#8294]
# Story

As an AIS team working to rebuild the event system, we would like all of the event information so that we can import into our system.

# Additional info

Slice of #8266 

As part of https://github.com/uiowa/uiowa/issues/8267, we have provided them with taxonomy info and user/event admin info. They also want all event information.

They do want us to add the author user id to the single event endpoint ([https://content.uiowa.edu/api/v1/node/{event_id}.json](https://content.uiowa.edu/api/v1/node/%7Bevent_id%7D.json)) and we discussed providing an additional endpoint that would include all event id's, status (published/unpublished) and approver info.

**Comment by briand44** [comment]
Grooming conversation.. There is possibly an event_instances endpoint that is not documented that we should make visible to AIS if we need it going forward (https://content.uiowa.edu/api/v1/views/event_instances_api.json?display_id=events). This endpoint gives us individual event instances if there is date recurring type stuff going on. Concerns about providing revision information. Should discuss that more with them to see if they plan to make these revisions available and if they are a requirement or not.

Joe mentioned providing a dump of the files so they are not scraping the site for all files at once.

API endpoints only include published entities of type "event".

If we can't get them all the data they need through existing endpoints it would make sense to create a new one for them to use before doing any kind of data export.

Going to get clarity on revisions and unpublished and then we can go from there.

**Comment by briand44** [comment]
After another conversation with AIS, they are fine with not including past revisions at this point in time. They also do not need a files dump as the endpoints contain the absolute file path.

They do want us to add the author user id to the single event endpoint (https://content.uiowa.edu/api/v1/node/{event_id}.json) and we discussed providing an additional endpoint that would include all event id's, status (published/unpublished) and approver info.

**Comment by joewhitsitt** [comment]
"approver info" can you remind me if that is just the unit or the user that approved the event for their unit? if the former, the "department" property has the units. if the latter, that will be some complex revision queries.

**Comment by joewhitsitt** [comment]
thinking about this more, we could probably list out all known revision authors, but it would be much more to tie each revision author with a unit approval

**Comment by briand44** [comment]
Currently adding status and author info to the single event endpoint. Need to get some clarification on approver info and add that to single event endpoint. New endpoint with all event ids also in progress just dealing with feature issues.

**Comment by joewhitsitt** [comment]
Based on the response from AIS, I've been poking at the approver info and got the bare minimum accomplished. I should note that this is a unique list of users from the node revisions table and not necessarily the users that approved the event for their unit. For example, it also includes the original author who could just be an authenticated user that submitted an event for review.

```php
if ($view->name == 'event_ids') {
    $new_output = array();
    foreach ($output as $item) {
      $new_event = new stdClass();
      $new_event->id = (int) $item->nid;
      $new_event->published = (int) $item->published;

      $query = db_select('node_revision', 'nr')
        ->fields('nr', ['uid'])
        ->condition('nr.nid', $item->nid)
        ->distinct()
        ->execute();

      $revision_authors = $query->fetchCol();

      $new_event->revision_authors = $revision_authors;
      $new_output[] = (object) ['event' => $new_event];
    }
    $output = (object) ['events' => $new_output];
  }
```

<img width="405" alt="Screenshot 2024-12-05 at 10 17 01 AM" src="https://github.com/user-attachments/assets/55e4391f-4535-44bf-a453-5bc1a4ca6954">

**Comment by joewhitsitt** [comment]
I honestly think ^^ is the best we can do without causing a timeout or descending into nested field/revision hell. We are loading all event ids here so we need to keep the query performant.

The field that event editors interact with on events is `field_event_units` which is a paragraphs parent field. So the non-event admin could "change" the field to add units initially. Those units are then notified and asked to approve the event. There is a dropdown on the paragraph entity so the actual action of approval is deeper. Tracing/linking that back to the overall node save and seeing who the revision author is would be quite complex.

Instead, with the data provided, revision authors, approved units and the users list with roles/units, they can draw reasonable connections.

**Comment by joewhitsitt** [comment]
Emailed them with the changes to see if it is enough.

**Comment by joewhitsitt** [comment]
This work was merged into master and is being deployed with #8335

**Comment by joewhitsitt** [comment]
We should update the documented endpoints on content.uiowa.edu with the author and status properties

**Comment by joewhitsitt** [comment]
Updated https://content.uiowa.edu/events-api/events and https://content.uiowa.edu/home/events-api/individual-event with author and status info. Sent an email to AIS informing them that these changes have been deployed to production.
