### ISSUE TITLE
Delete engineering viewbook on uiowa

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#8303]
From Melanie Laverman:

>Could you please delete this website: https://viewbook.engineering.uiowa.edu/? We will house this information on the main college website.

https://viewbook.engineering.uiowa.edu/ is on uiowa app

**Comment by joewhitsitt** [comment]
Reclaim domain and ~~archive repo~~ deprovision this V2 website?

**Comment by pyrello** [comment]
V2 site. Needs to be deprovisioned and domain reclaimed.

**Comment by bspeare** [comment]
Engineering responded so we can close this issue.
