### ISSUE TITLE
SSL cert for maps.uiowa.edu

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#8309]
Certificate is expiring 12/17/2024

https://docs.prod.drupal.uiowa.edu/dns-ssl

**Comment by briand44** [comment]
Grooming conversation... Once we've shared the cert, private key and chain via LastPass, email Abe and CC Patrick to let them know we shared those with them. Remove those assets from LastPass once Concept3D is finished.

**Comment by e-marie-w** [comment]
Email sent to Abe and Patrick. Fingers crossed everything goes well, I had to use a different cert type than previously.

**Comment by briand44** [comment]
Going to move forward with cleanup here since the cert is showing that it now expires Wednesday, December 10, 2025 at 5:59:59 PM

**Comment by briand44** [comment]
I found the thread with Concept3D in its-web and followed up to confirm moving forward. Got confirmation from Abe and have since revoked the old cert, removed the files from lastpass and removed the CSR from Acquia Cloud. Closing this.
