### ISSUE TITLE
Missing <description> and images in article RSS feeds

### ISSUE THREAD

**Issue by quamsta** [uiowa/uiowa#8310]
# Problem
We used to get the old "Article Summary" and/or possibly truncated content field in RSS feeds, but don't seem to be getting the new Summary field or any truncated text now.

# Steps to reproduce

1. Add a summary to an article
2. View an RSS feed containing that article
3. Note that there is no content in the `<description>` fields

Prod Example:
Article with the summary field filled out:
https://pathology.medicine.uiowa.edu/news/2024/11/dr-kai-rogers-receives-future-leader-transfusion-medicine-and-biotherapies-fellow

Feed containing that article (and others) with no content in the `<description>` elements:
https://pathology.medicine.uiowa.edu/taxonomy/term/16/feed

# Proposed solution
Ensure the summary field and/or truncated text is getting exposed to the feed.

**Comment by quamsta** [comment]
On second look, it also looks like we're missing images in these feeds as well.

**Comment by joewhitsitt** [comment]
Perhaps a duplicate of https://github.com/uiowa/uiowa/issues/6985 summary/description.

**Comment by quamsta** [comment]
Yeah this is a duplicate. Closing in favor of #6985
