### ISSUE TITLE
One-off find and replace for Admissions

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#8316]
# Problem

Until we develop a find/replace solution (#4258), Admissions has requested a one-off update hook to update 100+ instances of a string found on their Area of Study content.

**Search**:
`Iowa graduates have a 95 percent job/grad school placement rate`
**Replace**:
`Iowa graduates have a 96 percent job/grad school placement rate`
**Scope**: Area of Study content type

# Additional info

We have a similar update hook in admissions_core (admissions_core_update_9001) for updating a link.

# Proposed Solution

- Use find text to see if we can scope it down to a particular set of fields.
- Write an update hook in admissions_core to loop through AoS content and update instances with the new placement rate saving as a new revision but also accounting for tempstore and drafts. No need to update all revisions.
- Do a test run in DEV so that Admissions staff can review the result.
- Backup the database in production before triggering the update.

**Comment by briand44** [comment]
Grooming conversation.. May want to review update hook in admissions_core (admissions_core_update_9001) to see if there are any useful bits there that we can reuse.

Reusable content was brought up as a potential longer term solution when we have more time to put into this.

**Comment by joewhitsitt** [comment]
Going to make a couple tweaks. Add revision/message on save. Log output to terminal. Change update hook number to the 10001 instead of 9001
