### ISSUE TITLE
Deprovision magazine.engineering.uiowa.edu and news.engineering.uiowa.edu

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#8332]
Deprovision magazine.engineering.uiowa.edu and news.engineering.uiowa.edu and email engineering hostmaster to reclaim domain names. 

Melanie L email in its-web inbox. 

magazine.engineering.uiowa.edu - v2 on uiowa
news.engineering.uiowa.edu - v2 on uiowa

**Comment by james917** [comment]
Update, I made a mistake I sent the the email notification to the wrong email address instead of hostmaster@icaen.uiowa.edu but to hostmaster@uiowa.edu which turned out to be (ITS-hostmaster). I saw the email this morning and re sent it to the correct email/
