### ISSUE TITLE
D7 core update

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#8335]
# Story

As a web team, we would like all our D7 codebases that will be using HeroDevs Drupal 7 NES to be on Drupal Core 7.101 or later so that those codebases our compatible with Drupal 7 NES.

# Additional Info

In a conversation with HeroDevs, they mentioned we need to be on 7.101 or later. Should we be upgrading core for D7 applications so this isn't an issue if we move forward with HeroDevs Drupal 7 NES?

```[tasklist]
### Tasks
- [x] uiowa701
- [x] uiowa702
- [x] uiowa703
```
Grad College doesn't need upgrading as it will be going away.

# Questions

- Any other contrib updates as part of this (file entity, Acquia Connector, etc.)?

**Comment by briand44** [comment]
Grooming conversation... We may need to investigate if there are contrib updates needed to be compatible with the latest version of Drupal Core. If not, let's keep this scoped to core. We will want to do some testing, media/wysiwyg, content hub views, etc. 702 could be a good first application. We should test critical sites and features but probably don't have the time to thoroughly test everything. First slice lets scope to 70x applications and address rest in a separate slice.

**Comment by joewhitsitt** [comment]
Going to get a briefing from Brian on this and see how I can push this forward.

**Comment by joewhitsitt** [comment]
Going to start with 701 since it has the smallest footprint of live sites now. I'll test against the stories site and one of the remaining standard sites.

**Comment by joewhitsitt** [comment]
hitting snags getting a local website working enough to compare against.

**Comment by joewhitsitt** [comment]
Seeing similar stuff as in https://github.com/uiowa/uiowa/issues/8337#issuecomment-2546175068.

Not seeing the change to default.settings but I think that is based on how 701-3 `up drupal` is triggered. If it is just comments, I probably won't worry about it.

imagemagick is broken for me locally but I think that is because I didn't install it when I got my new machine. this is making local testing of media wysiwyg a bit more challenging though.

Realizing now that `scripts/set-private-path.sh` from our ACN upgrade mess was put in a bad spot. core is trying to delete it. i may just add this as a gist since we shouldn't need it again.

**Comment by joewhitsitt** [comment]
i am going to move forward with getting feature branches pushed up for each of these applications and we can check it out on one of the DEV environments for auth/media testing.

**Comment by joewhitsitt** [comment]
I pushed the core 7.103 update to a feature branch on 701-3 separately. Coincidentally, `update_core_7_103`

**Comment by joewhitsitt** [comment]
Testing on https://labroman.dev.drupal.uiowa.edu/ and https://studiovandervelde.dev.drupal.uiowa.edu/ by running updb and a cc all on each site.

- Authentication worked.
- I was able to upload and place media through the WYSIWYG without issue.

**Comment by joewhitsitt** [comment]
I feel like this has been an issue for a long time:

```
Notice: Trying to access array offset on value of type null in hs_menu_hierarchical_select_valid_item() (line 219 of /var/www/html/docroot/profiles/sitenow/modules/contrib/hierarchical_select/modules/hs_menu.module).
```

Update module is apparently turned on for standard sites, but nothing new here:
<img width="1343" alt="Screenshot 2024-12-19 at 11 13 09 AM" src="https://github.com/user-attachments/assets/2ba46ecd-874f-4490-868e-3d0c9f33685e" />

**Comment by joewhitsitt** [comment]
I guess at this point, I am wondering about some kind of "go for it" from the team to deploy the core update to at least one of these apps. Unfortunately, there is a biggie site still left on each:  Stories on 701, Content Hub on 702, Registrar on 703

**Comment by joewhitsitt** [comment]
Ah. Just saw the comments over on https://github.com/uiowa/uiowa/issues/8337. Moving forward with Stage today.

**Comment by briand44** [comment]
I would be okay with going for it on one app. I would go with 701 but open to other ideas or suggestions.

**Comment by briand44** [comment]
we will probably want to create db backups before running. If we do 701 first, at least for the two custom sites on that app.

**Comment by joewhitsitt** [comment]
i mean i can trigger PROD early like you are doing dentistry and rely on the overnight backups instead of triggering our own.

**Comment by briand44** [comment]
I am doing Dentistry early upon their request, not to avoid making a db backup. However you would like to proceed, just don't want you thinking you need to do it off hours.

**Comment by joewhitsitt** [comment]
i haven't observed this in testing, but i wonder if the session thing will kick folks out. we pass off to authenticate but the sessions are stored in memcache for D7? that is another reason for early deployment

**Comment by joewhitsitt** [comment]
deployed to DEV/STAGE with `updb` against `@sites`

emoji approval to deploy to PROD tomorrow morning 12/20. https://iowaweb.slack.com/archives/C8SM82ZFZ/p1734645036102169

not previously noted in this issue: .htaccess changes incorporated into existing file leaving redirects and other modifications untouched. robotstxt file removed. set-private-path script was deleted. settings.php for each site was left unmodified.

originally followed Drupal Core Update instructions found here: https://iowa.sharepoint.com/sites/Drupal-7-ITS-Docs/SitePages/uiowa701_2_3/uiowa701_2_3.aspx

**Comment by joewhitsitt** [comment]
Deployed to PROD across 701-3 and ran database updates. I logged in to a website on each to confirm.
