### ISSUE TITLE
D7 Core Update Part 2

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#8337]
# Story

As a web team, we would like all our D7 codebases that will be using HeroDevs Drupal 7 NES to be on Drupal Core 7.101 or later so that those codebases our compatible with Drupal 7 NES.

# Additional Info

In a conversation with HeroDevs, they mentioned we need to be on 7.101 or later. Should we be upgrading core for D7 applications so this isn't an issue if we move forward with HeroDevs Drupal 7 NES?

Follow up to the first slice in https://github.com/uiowa/uiowa/issues/8335

Grooming conversation from first slice - https://github.com/uiowa/uiowa/issues/8335#issuecomment-2540087331

```[tasklist]
### Tasks
- [x] UIClas
- [x] Signage
- [x] HC Signage
- [x] We'll want to make sure we merge the feature branches for the Hawk Alert work and deploy as part of this -https://github.com/uiowa/uiowa/issues/8336#issuecomment-2557798869
- [x] Dentistry
```

**Comment by briand44** [comment]
looks like there are changes to default.settings.php in 7.98, 7.99 (just comments), 7.101, 7.103. There are changes to .htaccess in 7.101 - https://www.drupal.org/node/3443661.

Also sounds like there are db updates in 7.98 related to session id's, option to opt out - https://www.drupal.org/node/3364841

Another db update in 7.100 that can be opted out - https://www.drupal.org/node/3424912

**Comment by briand44** [comment]
https://dentistryintradent.dev.drupal.uiowa.edu has been updated. Still need to deploy to stage and prod. I let Dentistry know so they can do some testing in the Dev environment.

**Comment by joewhitsitt** [comment]
Coming from #8335, i think we should opt-in to accept both the session id and announcement changes. @briand44  explained that these were fairly transparent. worse case user sessions will expire suddenly but they already do that current 😜  just deploy first thing in the morning?

**Comment by briand44** [comment]
I plan to deploy Dentistry updates at 6:30am Friday, Dec 20th. I'll try and get stage deployed yet today.

**Comment by briand44** [comment]
stage has been deployed and db updates ran

**Comment by briand44** [comment]
prod has been deployed for Dentistry, db updates ran, caches cleared

**Comment by joewhitsitt** [comment]
We could address the cache busting endpoint for hawk alerts in this work (Signage/Healthcare Signage). https://github.com/uiowa/uiowa/issues/8336

https://github.com/uiowa/uiowa/issues/8336#issuecomment-2557798869

**Comment by joewhitsitt** [comment]
healthcare signage has some additional htaccess customizations. originally thought it was on an older version, but it is the same. going to assume i keep the customizations and only add the one line that the other apps had after updating

the git history for the file does not describe the origins of these differences so i assume they are intended.

**Comment by joewhitsitt** [comment]
Actually, should I keep the `RequestHeader unset Proxy` in addition to the `Header onsuccess unset X-Content-Type-Options`?

```diff
-# Add headers to all responses.
+# Various header fixes.
 <IfModule mod_headers.c>
+  # Disable content sniffing for all responses, since it's an attack vector.
+  # This header is also set in drupal_deliver_html_page(), which depending on
+  # Apache configuration might get placed in the 'onsuccess' table. To prevent
+  # header duplication, unset that one prior to setting in the 'always' table.
+  # See "To circumvent this limitation..." in
+  # https://httpd.apache.org/docs/current/mod/mod_headers.html.
+  Header onsuccess unset X-Content-Type-Options
   # Disable content sniffing, since it's an attack vector.
   Header always set X-Content-Type-Options nosniff
+  # Disable Proxy header, since it's an attack vector.
+  RequestHeader unset Proxy
 </IfModule>
```

Update: I am going to add it. It feels like it was missed previously.

**Comment by joewhitsitt** [comment]
BTW, ran updb (`@sites` for uiclas, against the single site on signage and healthcare signage) in each environment for each app updated.

Remembered I don't have a hawkid account on the clas website so I am unable to properly test authentication without granting myself an account/role.

**Comment by joewhitsitt** [comment]
I think this is done.
