### ISSUE TITLE
Test email functionality from SiteNow websites

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#8352]
At 8am, Dec 30th, the email team will be updating SPF to Hard fail for acq-mail.uiowa.edu. We will want to test that we can successfully send email from SIteNow sites after this change has been made.

From Teresa Rose:

> I have requested the DNS changes with Hostmaster for December 30 at 8am with a TTL of 5 minutes. I also let them know if there are issues, we would need to have changes reverted right away.
>  
> Once the changes have been made, we will need to send test messages so we can verify the headers all look good.  Having a form submitted from an @uiowa.edu address and an external email address would be good to make sure they behave the same.  If you could forward me, as attachments, the test messages when they are received, we can look through and verify the headers.

From Joe:

> In preparation, I've set up this webform to send two emails to [its-web@uiowa.edu](mailto:its-web@uiowa.edu). One should be from [its-web@uiowa.edu](mailto:its-web@uiowa.edu) (the configured site email address) the other is configured to send from the email input address on the form (e.g. [random@random.com](mailto:random@random.com)) but should be intercepted and sent from [sitenow-noreply@uiowa.edu](mailto:sitenow-noreply@uiowa.edu).
> 
> https://sandbox.prod.drupal.uiowa.edu/form/spf-test
> 
> We can trigger these after the change and send you the message details we receive.

**Comment by joewhitsitt** [comment]
A bit more background. The email team made the switch and then asked us to trigger webform submissions and send them the email messages as separate attachments for them to review. They responded back that everything looked okay.
