### ISSUE TITLE
Request form does not validate www

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#844]
Right now, people can request sites that contain www even though we do not support that. We should adjust the validation logic to account for that. 

https://github.com/uiowa/uiowa/blob/master/docroot/sites/sitenow.uiowa.edu/modules/sitenow_core/src/Validate/RequestASiteUriConstraint.php

**Comment by joewhitsitt** [comment]
@GaryRidgway i tested out the PR #850 and came across this:
`Notice: Undefined index: host in Drupal\sitenow_core\Validate\RequestASiteUriConstraint::validate() (line 30...` when trying anything without https://, etc.
