### ISSUE TITLE
SSL Cert - shl.uiowa.edu

### ISSUE THREAD

**Issue by GaryRidgway** [uiowa/uiowa#845]
uiowa application 
we may also need to cover www.shl.uiowa.edu. I have reached out to Modei to clarify if we will need the www or not but he has not gotten back to me quite yet.

**Comment by joewhitsitt** [comment]
This sounds like it is blocked until they decide about a domain name and the direction for the website.

**Comment by briand44** [comment]
I am just closing this until they determine the proper url to use.
