### ISSUE TITLE
Build a CRM

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#861]
## Problem
We need a way to track sites and their customizations, and some people [don't like the README.md per site method](https://github.com/uiowa/uiowa/pull/857).

There has also been interest in a drupal manifest for SiteNow v2

## Proposed Solution
Either coordinate with CSI and use their system or develop a CRM within sitenow.uiowa.edu

**Comment by joewhitsitt** [comment]
This is also becoming more important to track who manages each site. There are other web properties besides *.grad.uiowa.edu *.clas.uiowa.edu that we don't manage.

**Comment by joewhitsitt** [comment]
We also are going to have v2 and v3 sites, other splits

**Comment by richardbporter** [comment]
> There are other web properties besides *.grad.uiowa.edu *.clas.uiowa.edu that we don't manage.

Seems like we all manage things together now. :)

**Comment by joewhitsitt** [comment]
I am going to close this unless someone objects. We have been getting by tracking v1 in a spreadsheet. We are no longer tied to ITS CSI. We have been using webmasters as a way to contact individuals about a site and work is being done to provide information about custom functionality here: https://github.com/uiowa/uiowa/pull/4091
