### ISSUE TITLE
Adopt Core's Media Library for v2

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#865]
## Problem
With 8.8, Media/Media Library is stable and includes CKEditor placement of media entities, however it looks like there are some steps involved to adopt it over our Media/Entity Browser approach along with some limitations to think about.

- [x] Find/replace database across all sites/all filtered_html and full_html fields update to change <drupal-entity> markup to <drupal-media>
  - Look into how Reports > Field List is generated to get all fields and their type (long text formatted)
- [x] Configure media library form modes and view modes for each media entity type.
- [x] Swap out the EB button for the Media button and configure.
- [x] media_library_media_source_info_alter() to allow add-form for non-core media entities.
- [ ] Styles need to be adjusted for `<drupal-media>`
- [ ] Monitor https://www.drupal.org/node/2657592 as key to focal point/media library integration.
- [ ] Deal with the coronavirus.uiowa.edu mix of v2/layout
- [x] ~~Regex account for sm/md/lg view modes that have different machine names in v3.~~ - It looks like we don't have to account for view mode changes because we can keep the existing view modes.

**Comment by joewhitsitt** [comment]
We should spend some time to review what we gain versus what we lose by switching at this point in time:

> Depends on your use case. For media entities, Media Library is usually a good option for basic functionality. Install the latest Drupal and give it a shot. If you need some sort of advanced feature, Entity Browser continues to be the best choice.

 -- phenaproxima

**Comment by pyrello** [comment]
Here is a drupal.org issue with what seems to be a working patch to resolve the the issue with view modes displaying for media types that don't have them enabled: https://www.drupal.org/project/drupal/issues/3097416

**Comment by joewhitsitt** [comment]
Lifting a lot of weight off this issue as we have an opportunity to adopt Media Library for v3 without addressing v2 sites.
https://github.com/uiowa/uiowa/issues/2099

**Comment by pyrello** [comment]
My idea for an update hook would utilize a similar approach to something we came up with working on migrations:
https://github.com/uiowa/uiowa/blob/3ca5397d977c03a819cbe5d4be54ef7d292b650d/docroot/modules/custom/sitenow_migrate/src/Plugin/migrate/source/ProcessMediaTrait.php#L300-L399

This uses Drupal's utility wrapper around DOMDocument to parse text area content for images and ultimately replace them with their `<drupal-media>` equivalent. Our update hook code would actually be much simpler because I think we could just take the existing instance and replace it without having to do any background processing.

**Comment by pyrello** [comment]
> Swap out the EB button for the Media button and configure.

I think that this is outdated. Instead we would just remove the relevant format overrides from the `sitenow_v2` split.

> Styles need to be adjusted for `<drupal-media>`

Would be good to get some more details on this.

> Deal with the coronavirus.uiowa.edu mix of v2/layout

I think this could be removed from here in favor of #2358
