### ISSUE TITLE
Review PR template

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#867]
https://github.com/uiowa/uiowa/blob/master/.github/PULL_REQUEST_TEMPLATE.md

Review this template to see if it meets our needs for PR's going forward.

**Comment by richardbporter** [comment]
FWIW, I'm not loving the current template. I'm not sure what to change. Maybe checkboxes for what the PR includes? Like `[ ] Includes dependency updates.` instead of `[ ] Dependencies have been properly updated` when that does not apply most of the time.

**Comment by pyrello** [comment]
@richardbporter I think that is a good change.

**Comment by pyrello** [comment]
@mark-bennett-uiowa and @bspeare I was hoping to get your input on this, as this will eventually be what we are using too.

**Comment by pyrello** [comment]
@richardbporter I was getting ready to file an issue with the Drupal VM project and I noticed that they use comments to give directions to the user, but which don't show up in the actual issue: https://github.com/geerlingguy/drupal-vm/blob/master/.github/ISSUE_TEMPLATE

That might be something we could use for this.

**Comment by joewhitsitt** [comment]
Site provisioners over here in ITS are up in arms about the current PR template as none of it really applies to those. So change needs to come. I could also see a wiki with Q/A steps instead of a PR template.

**Comment by richardbporter** [comment]
The checkboxes are misleading because every PR says "0 of 7 completed". I would vote for the commented out template.
