### ISSUE TITLE
Gut the gh-pages branch

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#875]
## Problem
We are no longer using the gh-pages branch for documentation. Even though we have redirect the index page, everything is still being crawled by Google.

## Proposed Solution
Determine what the future of the uiowa->gh-pages branch is and repurpose it. Consider removing all interior pages until then to get started on SEO cleanup.

**Comment by richardbporter** [comment]
I would vote for deleting soon. We'll want to talk with other groups to determine the purpose for gh-pages going forward.
