### ISSUE TITLE
Run sitemap command for newly-provisioned sites

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#879]
#876 introduced a change that will require sitemaps be generated initially through the Drush command `simple-sitemap:generate`. Then cron will handle afterwards. We should verify this and automate if accurate.

This would need to happen around https://github.com/uiowa/uiowa/blob/07931712ca7da769e7a3f319856ce82cbb0d2a75/blt/src/Blt/Plugin/Commands/ReplaceCommands.php#L42

**Comment by joewhitsitt** [comment]
Will this handle the domain change that happens later for internal to production domains?

**Comment by richardbporter** [comment]
I ran a fresh install locally. Hit sitemap.xml and got a 404. Ran cron. Hit it again and the sitemap was there.

Also, looks like the sitemap uses the base URL. Ex: https://mnh.prod.drupal.uiowa.edu/sitemap.xml
