### ISSUE TITLE
Error: "Could not delete ..."

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#88]
I have regularly been running into this issue. I have been experimenting with the alpha and beta releases of Drupal 8.7, so needing to run `lando composer update drupal/core` to get that updated.

I just did a vanilla install to test this to make sure it wasn't some issue with my existing version of the app. Here are the steps I took to test it:

1. `lando poweroff` on my existing app (in `~/acquia/uiowa`)
2. `git clone git@github.com:uiowa/uiowa.git ~/acquia/uiowa_test`
3. `cd uiowa_test`
4. `lando start`

Here is the output up to the error:
```
$ git clone git@github.com:uiowa/uiowa.git ~/acquia/uiowa_test
Cloning into '/Users/sadamshiett/acquia/uiowa_test'...
remote: Enumerating objects: 93, done.
remote: Counting objects: 100% (93/93), done.
remote: Compressing objects: 100% (63/63), done.
remote: Total 1048 (delta 51), reused 61 (delta 29), pack-reused 955
Receiving objects: 100% (1048/1048), 411.16 KiB | 3.61 MiB/s, done.
Resolving deltas: 100% (634/634), done.
GRAD-M003:acquia sadamshiett$ cd uiowa_test/
GRAD-M003:uiowa_test sadamshiett$ lando start
Let's get this party started! Starting app..
Starting landoproxyhyperion5000gandalfedition_proxy_1 ... done
Starting uiowa_appserver_1 ... done
Starting uiowa_node_1      ... done
Starting uiowa_database_1  ... done
Starting uiowa_cache_1     ... done
Waiting until database service is ready...
Waiting until cache service is ready...
Waiting until appserver service is ready...
Waiting until node service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Gathering patches for root package.
Removing package drupal/core so that it can be re-installed and re-patched.
  - Removing drupal/core (8.7.0-alpha2)
                                  
  [RuntimeException]              
  Could not delete docroot/core:  
```

After trying the above, I was curious about whether there might still be something in my local environment that was affecting the outcome. I tried `git clone` to a different directory entirely (~/testfolder/uiowa_test) and ended up getting the same error as above. At this point, I realized that the above error doesn't actually make any sense. It was talking about removing  drupal/core (8.7.0-alpha2), but that version of Drupal was specific to the feature branch I have been using for the collegiate profile development. Instead, this entirely new instance of the app should be referencing the master branch, which would be pointing to the latest stable version of Drupal 8.6.

So, it seems that maybe the different containers within lando get reused because the name property inside the `.lando.yml` file is the same in each case, `uiowa`.

To test this theory out, I destroyed all my existing `uiowa` lando instances, removed the files for the 2 tests I had done, then repeated the last test (git cloning into an entirely new set of directories). Before running `lando start`, I changed the name property to `uiowatest`.

This time through I got a different (but similar) error:
```
  [RuntimeException]                                                    
  Could not delete docroot/themes/custom/uiowa_bootstrap/node_modules: 
```

I tested this with both *rc13* and *rc14* and the result is the same.

**Comment by pyrello** [comment]
I suspect that this issue will be mitigated by commenting out the excludes lines in the .lando.yml file.

**Comment by richardbporter** [comment]
Yes, I'm playing around with that. Its time consuming because I wan't to make sure it works for a "fresh" install as well as rebuild/restart for an existing app.

**Comment by pyrello** [comment]
One thing to note for doing fresh installs is that you have to ensure that you change the app name for testing purposes. Otherwise, it may end up reusing the existing uiowa_* containers.
