### ISSUE TITLE
SiteNow Migration links

### ISSUE THREAD

**Issue by cory-skeers** [uiowa/uiowa#894]
## Problem
NIDs change during migration, breaking some links and causing other links to direct to incorrect pages.

## Proposed solution
Add a link collector to the page migration body preprocess, scanning for and flagging internal links. Post-migration update for this list based on migration mapping of old NIDs to new NIDs.

**Comment by cory-skeers** [comment]
Branch is up for testing.

Currently d7_page must be run after d7_article and d7_person though this is not enforced. Link search/replacement is based on all content having been migrated already. Need to determine whether this should be enforced through dependencies, or if extra handling needs to be added (i.e. should clients be forced to migrate ALL content, or pick and choose, like migrating pages but not articles).

Checks for relative paths and absolute paths using the base path, and updates all to '/node/nid' format based on D7->D8 node migration mappings. Works for the test site I used in development, but possibly (probably) some edge cases it misses.

### Method update
Dropped the idea for a flagger during migration. Instead it's all handled in a post-migration process which queries for a list of nodes with potentially problematic links, and then checks/updates those nodes.

**Comment by joewhitsitt** [comment]
@cory-skeers can you create a draft PR for this for more visibility. someone can help with the merge conflicts and we can get your drupalVM setup so you can keep up to date with this branch. I keep forgetting about this.

migration stuff will probably have to change anyway to deal with D8 local now being in a vagrant container.

**Comment by cory-skeers** [comment]
Blocked by #1010

**Comment by joewhitsitt** [comment]
Is this still an issue? @cory-skeers

**Comment by cory-skeers** [comment]
Closed as part of #994
