### ISSUE TITLE
Changes to composer files discarded during `lando restart`

### ISSUE THREAD

**Issue by genjohnson** [uiowa/uiowa#9]
When running `lando restart` to test a PR, changes to my composer.json and composer.lock file were unexpectedly discarded.

My steps to test a feature branch of uiowa/multisite:

1. Edited composer.json (at the root of the application) to use the desired feature branch (generate_hash_salt) of uiowa/multisite.
2. Ran `composer update uiowa/multisite` to update composer.lock.
3. Ran `lando restart` (so that my local site would be re-generated).
4. Verified that the changes in the feature branch worked as expected.
5. Noticed that the branch specified for uiowa/multisite in composer.json has been re-set to master. Running `git status` verified that **my changes to composer.json and composer.lock had been discarded**.

**Comment by briand44** [comment]
I can confirm this.

**Comment by richardbporter** [comment]
I just ran through those steps with a feature branch of the profile but it worked as expected. My changes to composer.json/lock are still present.

**Comment by adamdelaney** [comment]
I cannot replicate the behavior in this issue, my composer.json and lock files changes were present as well.

**Comment by adamdelaney** [comment]
Closing this issue for now.
