### ISSUE TITLE
Create new shared base theme for integrating HDS

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#904]
Related to #855. Follow up to #903. 

- [ ] Create a new base theme (hds_base?) to serve as the basis for integrating the HDS into Drupal
- [ ] Move components as necessary from collegiate_theme to the new theme
- [ ] Update collegiate_theme to use the new theme as its base theme

**Comment by pyrello** [comment]
@bspeare Do you think that the layouts should be moved to hds_base? Or should they stay in the collegiate_theme? I thinking that if hds_base is somewhat agnostic about the approach to laying out pages, then it makes more sense to add the layouts to collegiate_theme, which is more layout-builder specific.

**Comment by bspeare** [comment]
I was thinking it would make sense to have them in the hds_base theme.
