### ISSUE TITLE
Update to drupal/core-dev from webflo/drupal-core-require-dev

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#921]
https://www.drupal.org/docs/8/update/update-core-via-composer#s-removing-or-replacing-dev-packages.

This will make updates to `drupal/core` easier :)

**Comment by joewhitsitt** [comment]
This is done now right @richardbporter ?

**Comment by richardbporter** [comment]
Nope - had to just update core with webflo in place due to that auth issue.
