### ISSUE TITLE
Create communications for training event

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#926]
- [x] Initial
- [x] Reminder

**Comment by makurj** [comment]
**Thanks for registering/confirmation email:**

Hello,

Thanks for registering for the SiteNow v2 Website Basics Training on Wednesday, January 29, 2020 from 9:30 - 11:30 in UCC 2523 Training Room.

This is a hands-on training so we encourage you to utilize the computers provided in the training room or bring your own device. 

A couple of days before the training, you will receive an email notifying you of being added to a sandbox site. Please complete the steps in that email before the training.

As space is limited, we ask that you let us know 24 hours prior to the training so we can give the spot to someone on the waitlist.

We look forward to seeing you there.

ITS Web Services

**Reminder emails: a week before AND day before.**

Hello,

This is a reminder that you are registered for the SiteNow v2 Website Basics Training on Wednesday, January 29, 2020 from 9:30 - 11:30 in UCC 2523 Training Room.

If you are unable to attend, please let us know.

We look forward to seeing you there.

ITS Web Services
