### ISSUE TITLE
Post training survey/resources communication

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#929]

**Comment by makurj** [comment]
Thanks for attending the SiteNow v2 Website Basics Training. Below are some resources from the training.

We also encourage you to complete our training survey to help making future training sessions better. Complete survey here: SURVEY LINK.

ITS Web Services

-----------------------


Please answers the questions below to help us make future training better. The survey will take 3-5 minutes.

1. The length of the training was: short / okay / too long.
2. Was the content relevant?
3. Which aspects of the training would you like to change?
4. Which aspects of the training would you like to keep? 
5. At what times during the year would these trainings be helpful?
6. What other topics would you like us to cover in future trainings?
7. Other feedback.

**Comment by makurj** [comment]
Survey printed.
