### ISSUE TITLE
Create a basic UI-branded theme

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#93]
Create a UI-branded theme which will evolve as the UI branding project continues. Major components to style include (not an exhaustive list):
- site header
- top-level menu items (superfish)
- Paragraph bundles
  - Section
  - Cards
  - Accordion groups/items
- basic typography & HTML elements
  - headers
  - links
  - lists
  - tables
- site footer (this might already be done in uiowa_footer)

It was suggested that https://innovation.uiowa.edu/ be used as a starting point.

**Comment by joewhitsitt** [comment]
Without further input from OSC, this has been implemented
