### ISSUE TITLE
Re-factor Sitenow Multisite command to work with typhonius/acquia-php-sdk-v2 2.x

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#930]
As part of #916, the typhonius/acquia-php-sdk-v2 package was updated to the 2.x releases. The Sitenow Multisite command uses this library to create remote databases during site provisioning. The code needs to be refactored to work with the 2.x branch. For reference, here is the code from uiowa01 refactored to work with the new version:https://github.com/uiowa/uiowa01/blob/master/blt/src/Blt/Plugin/Commands/MultisiteCommands.php#L900

**Comment by richardbporter** [comment]
I did this as part of #916 since that is where the updated dependency is. This will auto-close once merged.

**Comment by pyrello** [comment]
Perfect.
