### ISSUE TITLE
Replace Pipelines setup_app functionality to run multiple profiles

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#934]
Haven't dug into this one yet to see what exactly needs to be replaced. We should be able to iterate over the `uiowa.profiles` config key and run each on the default site.

**Comment by richardbporter** [comment]
Blocked by #933

**Comment by pyrello** [comment]
@richardbporter I had another idea for this. Maybe we could just create an actual test? That seems like it might be the easier route.

**Comment by richardbporter** [comment]
I'm not sure I follow you. Pipelines runs a site install via Drush for every job. It takes a while but it tests whether or not the profile can be installed without errors. This is especially important for sitenow since it validates configuration stored in the profile.

I think we can modify/replace whatever BLT command is doing this so that each profile we outline in our custom BLT configuration is tested. We could make optional if desired by adding more configuration like:
```
uiowa:
  profiles:
    foo:
      ci_install: true
    bar:
      ci_install: false
```

Essentially, running the install is the test. I'm not sure how we would mock that.

**Comment by richardbporter** [comment]
Sorry, I think I understand now.

We used to run functional tests for our profile where it was installed per test but we found that it was taking too long for jobs to complete. If we want to start functional testing profiles, we could but I would like to investigate running them simultaneously using TravisCI or similar.

**Comment by pyrello** [comment]
Do you know what `${drush.aliases.ci}` resolves to?

**Comment by richardbporter** [comment]
I do not.

**Comment by pyrello** [comment]
It looks like it resolves to `self`.
