### ISSUE TITLE
How to add ssh-key automatically on computer start?

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#937]
How do we make sure that this command is run when computers get restarted?

```
ssh-add -K ~/.ssh/id_rsa
```

**Comment by pyrello** [comment]
@richardbporter This is an occasional issue that affects the VM. This seems to be a necessary step after you restart your computer prior to provisioning the VM. I had not made any progress on it and it comes up infrequently so it had fallen off my radar.

**Comment by richardbporter** [comment]
This worked for our team: https://apple.stackexchange.com/a/250572

**Comment by pyrello** [comment]
Hmm... I have my ~/.ssh/config file already set up like this and yet I have still run into the issue where my keys aren't loaded. Maybe I'm misunderstanding what the issue is.
