### ISSUE TITLE
Set git config inside vagrant during provisioning

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#938]
Add to setup documentation that it is necessary to set git config for username and email:

```
$ git config --global user.name "Mona Lisa"
$ git config --global user.email mona-lisa@uiowa.edu
```

**Comment by pyrello** [comment]
This looks like a possibility for automating this: https://groups.google.com/d/msg/vagrant-up/5fWmRCuIcJA/2fnh8uBvJyQJ

**Comment by richardbporter** [comment]
No longer applicable.
