### ISSUE TITLE
Restrict ability to add block (types) to layout regions

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#955]
Tracking issue from https://www.drupal.org/project/layout_builder_restrictions/issues/2982452#comment-13367752.

Once a patch is created, test and add to the project.

**Comment by bspeare** [comment]
Also related: https://www.drupal.org/docs/8/modules/layout-builder-restrictions/restricting-blocks-to-specific-layouts-regions

**Comment by pyrello** [comment]
This is actually being used in #1622

**Comment by richardbporter** [comment]
Seems like this was resolved in #1979. Reopen if not!

**Comment by joewhitsitt** [comment]
Is this "done?" I was going to restrict more general non-layout specific blocks here: https://github.com/uiowa/uiowa/issues/1920

**Comment by richardbporter** [comment]
I'm not sure. I thought it was initially but then read https://github.com/uiowa/uiowa/pull/1979#issuecomment-670245133 which maybe indicated it was not completely done?

**Comment by richardbporter** [comment]
I would be in favor of closing this since #1920 represents the further investigation.

**Comment by pyrello** [comment]
Sounds good to me.
