### ISSUE TITLE
Add Layout Builder UX Module to Collegiate

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#956]
I've tested https://www.drupal.org/project/lb_ux and it will work if I adjust the admin.css file in the theme.   @pyrello, any objections to adding it after what you saw in the user testing demo?

**Comment by pyrello** [comment]
@bspeare Still interested in adding this?

**Comment by bspeare** [comment]
@pyrello I just tried this on uiowa.local.drupal.uiowa.edu and I liked what they have implemented for UX improvements.

<img width="401" alt="Screen Shot 2020-05-12 at 9 38 10 AM" src="https://user-images.githubusercontent.com/1036433/81742290-7b550a80-9465-11ea-8270-0ffe318a3041.png">

There were also ajax errors when I tried to add a new layout section - can you verify this same issue on your end?

**Comment by pyrello** [comment]
I can confirm the same issues when I test it.

I would be interested in figuring out how they did some of the things that are included in this module and bringing them in either via theming or via the layout_builder_custom module. I'm not sure if the whole experience is better.

**Comment by pyrello** [comment]
So, I think we can close this based on recent conversations.
