### ISSUE TITLE
Investigate Layout Builder Styles patch that will allow for the grouping of styles

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#958]
# The Problem

Layout Builder Styles does not allow for the grouping of styles into separate categories. 

# Proposed Solution

There is a patch at https://www.drupal.org/project/layout_builder_styles/issues/3075502 that has worked in the past.

**Comment by pyrello** [comment]
FYI, I reviewed the above issue a few days ago and there still isn't an RTBC patch yet.

**Comment by bspeare** [comment]
Related modules to consider:

https://www.drupal.org/project/layout_builder_component_attributes
https://www.drupal.org/project/block_style_plugins
https://www.drupal.org/project/block_styles
https://www.drupal.org/project/block_class

**Comment by richardbporter** [comment]
Seems like this was resolved with https://github.com/uiowa/uiowa/commit/5a693fe0ff325718ff11a37e37a4532c42f14ad5 unless its something different.
