### ISSUE TITLE
Limit the number of layout builder styles available based on base theme settings

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#959]
# The Problem
The style options in the settings tray for "full width container" appear as an option if "full width container" is already selected.   Ideally, this option would not be available based on the theme setting. 

![Screen Shot 2019-11-12 at 4 09 23 PM](https://user-images.githubusercontent.com/1036433/68715089-d1a0c980-0566-11ea-9beb-284a74d9ee5a.png)

# Proposed Solution
Have the uiowa_lb_blocks module check the theme settings in collegiate_basic before displaying the options in the settings tray.

**Comment by pyrello** [comment]
I think that this was resolved in #2076
