### ISSUE TITLE
Command should write database include specific to app container

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#961]
This line in the Multisite command file hard codes the uiowa application container when writing the database include line into the settings file. This would ideally either use the appropriate application or (even better) it could be dynamically set based on some environmental variable so that we wouldn't have to change it when moving a site from one container to another container.

**Comment by pyrello** [comment]
It looks like there is not currently an environment variable that would work for this: https://docs.acquia.com/acquia-cloud/develop/env-variable/#available-environment-variables

Also, it looks like we could create an environment variable: https://docs.acquia.com/acquia-cloud/manage/variables/

**Comment by richardbporter** [comment]
The `AH_SITE_GROUP` variable is the application name. I tested on dev and it works. Seems odd that Acquia docs recommend not using environment variables before the database include but BLT does exactly this: https://github.com/acquia/blt/blob/11.x/settings/blt.settings.php#L118
