### ISSUE TITLE
Update test to check db include statement to use regex

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#964]
The FilesystemTest class checks the database include statement against a path that includes a hard-coded reference to `uiowa`. This obviously is going to be a problem for `uiowa01` sites.

https://github.com/uiowa/uiowa/blob/master/tests/phpunit/src/Unit/FilesystemTest.php#L138

**Comment by richardbporter** [comment]
Turns out we won't need regex if we use the appropriate environment variable. Closing in favor of #961.
