### ISSUE TITLE
How to upload and link to files in WYSIWYG?

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#966]
So I asked this in the Slack channel, but how are we planning on adding files as links in a WYSIWYG text area? In D7, we could use CKFinder, upload the file and choose it from a file picker window as a link to the file. In our D8 implementation, we dont currently have that option. When I add the Add Media button to one of the text formats, I get the option of uploading the file and selecting it, but then it overwrites the text I want as the link text with something like this:
![Screen Shot 2020-01-16 at 12 55 04 PM](https://user-images.githubusercontent.com/3067017/72641731-6a214480-3930-11ea-9cf3-433f1cba6b98.png)

**Comment by pyrello** [comment]
Moved this from the `collegiate split` label to the `SiteNow v3` label because of #2110

**Comment by joewhitsitt** [comment]
Wonder if this can be closed or rewritten based on https://github.com/uiowa/uiowa/pull/2177

**Comment by pyrello** [comment]
@mark-bennett-uiowa Can you confirm that your issue is fixed by #2177?

**Comment by joewhitsitt** [comment]
> @joewhitsitt @pyrello Yes, this has been solved. Thanks so much. The issue I originally had in https://icsa.uiowa.edu/resources/forms was fixed with the Media updates.
https://github.com/uiowa/uiowa/pull/2177#issuecomment-693446833
