### ISSUE TITLE
How are side menus going to be handled?

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#967]
On the [https://icsa.uiowa.edu/](https://icsa.uiowa.edu/) site, I need to add side menus that are dynamically visible depending on what page is being viewed. For instance, the About menu is only visible on /about and /about/*.
I edited the basic page content type (in order to edit the layout for ALL pages), and changed the single content column into two columns. I added two of the side menus (About and Services) to the new left-hand column and saved. Upon viewing the page, both menus were visible (side-by-side btw, not one above the other), even on a page where only the About menu should be visible.
I can recreate this and send screenshots if need be. Thoughts?

**Comment by pyrello** [comment]
How to handle this depends on the complexity of the page layouts and the site itself. If you have a pretty basic, straightforward site, I'm not sure I would use layout builder to solve this problem.

**Comment by joewhitsitt** [comment]
So v3 has sidebar layout by default with an active trail menu block in place if children items exist. Is this still an issue that will be handled differently in the collegiate split? If so, should this be labeled collegiate? If not, can we close?

**Comment by pyrello** [comment]
@joewhitsitt I think this is solved going forward either by using V3 default or by replicating the way it is done in V3 default. @mark-bennett-uiowa Please re-open if you think this is still an issue and clarify why this does not resolve it for you.
