### ISSUE TITLE
"You have unsaved changes" Error is back on prod

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#968]
This time, I was editing the content inside of a UIowa block on the frontpage of the policy site: [https://policy.clas.uiowa.edu/](https://policy.clas.uiowa.edu/). I removed the title and body of the block, but kept the Link title and Link, in order to see if we could just have an image and link. Immediately upon the save attempt, Im locked in the "You have unsaved changes" error again.

The following did NOT fix the issue:
drush cr.
Clear cache from Configuration > Performance.
Discard changes button in LB.
Revert to default button in LB.
Returning all deleted content back to the block and re-saving.

**Comment by pyrello** [comment]
Looks like there is a new RTBC patch to fix this issue: https://www.drupal.org/project/drupal/issues/3045171#comment-13450756
