### ISSUE TITLE
How to solve global containers

### ISSUE THREAD

**Issue by adamdelaney** [uiowa/uiowa#97]
- sidebars
- global regions
- paragraphs
- system pages
- etc

**Comment by joewhitsitt** [comment]
Right now the default is container-fluid on uiowa_bar, brand, footer and basic page. header, system pages, etc. are container. #94 will be used to implement a configurable container for the uiowa_bar, brand and footer areas based on what we recieve from OSC for final design

**Comment by joewhitsitt** [comment]
blocked. should be addressed if at all with #371
