### ISSUE TITLE
Adding *-date to node title for page URL wont work with repeating dates

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#971]
We can add dates to URLs using pathauto, but we run into issues when we have repeating dates. For instance, changing the URL pattern for events to "events/[node:event_date]-[node:title]" causes a URL like this: http://theming.uiowa.local.site/events/fri-11012019-1300-fri-11012019-1600-mon-11042019-1300-mon-11042019-1600-wed-11062019-1300.

Unless we can eventually grab the delta[0] date of a repeating date, we may need to stay with "events/[node:title]". We can fix this down the road or allow webmasters to control their own patterns (already allowed) on their sites.

**Comment by joewhitsitt** [comment]
@mark-bennett-uiowa I am working on the local event content type and was wondering what the path should be. Did you ever reach a conclusion? The event content type also has multi-dates and repeats.

PR: https://github.com/uiowa/uiowa/pull/2765
Issue/Question: https://github.com/uiowa/uiowa/issues/3170#issuecomment-829635036

**Comment by joewhitsitt** [comment]
I am seeing a lot of examples of just using the event/[node:title] pattern. Of course, events of the same name get the -0, -1, treatment, but is that a bad thing in this case? The benefit of multi and repeat dates is that they can use the one event and it will house all of the instances. If the instances are unique enough that they are separate nodes, I don't think the -0, -1, is that bad.
https://www.drupal.org/community/events
https://www.eventbrite.com/

**Comment by mark-bennett-uiowa** [comment]
@joewhitsitt I dont believe we ever reached a conclusion. Current events pulled from Content Hub get paths like: [https://socialwork.uiowa.edu/event/63481/0](https://socialwork.uiowa.edu/event/63481/0) or [https://socialwork.uiowa.edu/event/63536/3](https://socialwork.uiowa.edu/event/63536/3). It appears that the /3 comes from a repeating date in Content Hub. We dont seem to use the date in the path at all for SiteNow Events, so maybe we just drop the date?

I would prefer something similar to the above, but if we used local NID we could potentially reach a conflict with a Content Hub path.

- Would `/event/nodetitle/x` work, where nodetitle is the title of the event, and x would be the instance # of the event?
- Should we also save /events for the full list of upcoming events, and individual events are found under /event/... to match SIteNow Events implementation?

**Comment by joewhitsitt** [comment]
@mark-bennett-uiowa I might have caused some confusion by commenting here. content.uiowa.edu events don't have that pattern. We are dynamically doing that based on content.uiowa.edu events instances API that is offered. events.uiowa.edu creates a different id for each instance. This local content type feature, AFAIK, won't have those dynamic instance pages. Users click and see the all-encompassing event node with all dates listed.

I imagine the default view path will be /events but being a feature split, this will probably checked when enabled. The path will also be configurable similar to SiteNow Articles/People. https://github.com/uiowa/uiowa/issues/3171

**Comment by joewhitsitt** [comment]
For the local event feature, we moved away from repeating dates for SEO and simplicity. Closing this.
