### ISSUE TITLE
SiteNow/LinkIt Upload - file not available for selection after immediate upload

### ISSUE THREAD

**Issue by makurj** [uiowa/uiowa#986]
Uploading a file to an accordion item disappeared after being added but it did upload successfully to the media browser.

**Comment by joewhitsitt** [comment]
It gets uploaded to the system but the autocomplete is not aware of the file yet and it isn't very intuitive to the editor what to do after upload. **WORKAROUND: I had to close the linkit modal and open back up to search on the first few letters of the file to have it show up.**

**Comment by joewhitsitt** [comment]
We might want to re-evaluate how core media is now handling images and documents. If they can be inline docs and linked images, maybe it is more reasons to focus on #865

**Comment by joewhitsitt** [comment]
Looks like core is so far ignoring inline media... and entity_embed is not quite there. #116

**Comment by joewhitsitt** [comment]
Linkit doesn't plan to do this and a contrib project is currently broken: https://www.drupal.org/project/linkit/issues/3038115

**Comment by joewhitsitt** [comment]
https://www.drupal.org/project/linkit/issues/2828190

**Comment by joewhitsitt** [comment]
I was thinking about this last night. I am surprised this isn't more of an issue as people migrate and try to link up files.

So far the community has solved this with clunky workarounds that we might need to investigate adopting.

I suggest trying to separate out the file upload into a separate button on the wysiwyg with ample help text to guide them to upload the file here or thought the media add page. then link the link button to reference the file. we could encourage the media add page by adding multiple upload.

**Comment by joewhitsitt** [comment]
If sticking with the current setup, the at the very least, the following should be done:

- [ ] min-height: 490px; on #entity_browser_iframe_file_link_browser in the nested context to deal with Claro spacing
- [ ] help text to explain the workflow, upload file, close/reopen linkit and autocomplete the filename (not the media name).
- [ ] **Bonus**, some kind of ajax callback on upload to "retrigger" the autocomplete field or inject the media path of the new file

**Comment by joewhitsitt** [comment]
Removing myself again for now. Haven't had time to work on this

**Comment by joewhitsitt** [comment]
This would be the entity_embed solution for inline files which would mean we could abandon linkit for files: https://www.drupal.org/project/entity_embed/issues/2640398. Core Media has mentioned inline files but so far has done very little to deal with it: https://www.drupal.org/project/drupal/issues/2801307

**Comment by joewhitsitt** [comment]
This just happened... https://www.drupal.org/project/linkit_media_library
