### ISSUE TITLE
BLT Sync Not Importing Local Split Config

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#988]
```
> drupal:config:import
[warning] BLT will NOT import configuration, /var/www/uiowa/docroot/../config/default/core.extension.yml was not found.
[warning] The drupal:toggle:modules command is disabled.
```
I was expecting stage file proxy to be on locally and had to run a `cim` on the site to import the already "active" local split.

**Comment by richardbporter** [comment]
Which site?

**Comment by richardbporter** [comment]
I synced sitenow.uiowa.edu and the local config seemed to be imported just fine.

**Comment by joewhitsitt** [comment]
it was sitenowdemo.dev to local

**Comment by joewhitsitt** [comment]
Just pulled master and vagrant provisioned to try again:
<img width="807" alt="Screen Shot 2020-01-29 at 1 47 59 PM" src="https://user-images.githubusercontent.com/4663676/73392021-a3e23b80-429e-11ea-9f05-ba9e1a71854c.png">
