### ISSUE TITLE
Docs - Wrap an image with a link

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#993]
Create a link above or below the image.
Disable rich-text.
Delete the link text in between.
Move the beginning or end of the `<a></a>` so that it surrounds the media entity code.

**Comment by dnkemper** [comment]
@joewhitsitt I added documentation to https://sitenow.uiowa.edu/documentation/media/images-and-files. Let me know if I need to fix anything

**Comment by joewhitsitt** [comment]
Thanks!
